### ISSUE TITLE
anonymous `SecurityIdentity` is not available inside background vertx worker, says "RequestScoped context was not active"

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#38704]
Starting with Quarkus 3.7.2, trying to use an injected `SecurityIdentity` inside a vertx worker fails sometimes. This used to work in 3.7.1. My test setup is as follows:

```java
@ApplicationScoped
public class TestSchedule {
    @Inject SecurityIdentity securityIdentity;
    @Inject Vertx vertx;

    @Scheduled(every= "1s")
    void testSchedule() {
        vertx.executeBlocking(() -> {
            Thread.sleep(100); // make sure this gets executed after the schedule method has ended
            try {
                System.out.println("is user anonymous? " + securityIdentity.isAnonymous());
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            return null;
        });
    }
}
```

With **Quarkus 3.7.1** and below, this successfully prints `is user anonymous? true`

With **Quarkus 3.7.2** (latest as of writing), this produces an exception:
```
jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.security.runtime.SecurityIdentityProxy, id=U3fuB4yO9MSr82V2xU36xFn98dk]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:70)
	at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:30)
	at io.quarkus.security.runtime.SecurityIdentityProxy_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.security.runtime.SecurityIdentityProxy_ClientProxy.isAnonymous(Unknown Source)
	at org.acme.TestSchedule.lambda$testSchedule$0(TestSchedule.java:19)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:177)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:209)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

This either appears to be a regression, or it should have never been possible to successfully use an injected `SecurityIdentity` this way in the first place. I'm not sure which one it is.

**Comment by Felk** [comment]
Here's a reproducer project: 
[inject-securityidentity-regression.zip](https://github.com/quarkusio/quarkus/files/14220745/inject-securityidentity-regression.zip)

It's basically just https://code.quarkus.io/?a=inject-securityidentity-regression&j=21&e=oidc&e=scheduler with the above code added.

**Comment by Felk** [comment]
Judging from the changelog of 3.7.2, this might be a consequence of https://github.com/quarkusio/quarkus/pull/38605  

Judging from the pull request's description, my use-case should was never legal and should have never worked to begin with. Would you agree @mkouba ?

**Comment by sberyozkin** [comment]
Also CC @manovotn @michalvavrik

**Comment by michalvavrik** [comment]
Hey, I'll let answer Martins on CDI request being active, but I have a comment on the use case if you don't mind.

I checked your reproducer and the identity is always going to be anonymous (even with active CDI request context), won't it? If so, I'm not sure why to bother, just use `QuarkusSecurityIdentity.builder().setAnonymous(true).build()`. I appreciate your real use case might be much more complex, but I can't imagine where the identity is coming from unless you set it yourself in the `SecurityIdentityAssociation`, in which case you need to do it inside same CDI request context in which you set it. Doesn't it basically means you need to do it inside scope of the same method where you request the identity?

I ask because if your real use case has non-anonymous identity that is accessible without the `ContextNotActiveException`, it should mean you had activated CDI request context in that scenario. So you can just activate it here as well.

**Comment by michalvavrik** [comment]
> My real-world usecase is that I have a @PreUpdate listener on JPA entities that sets a "updated_by"-kind of field on every update. That listener exists in all situations, including background workers, but also in the context of actual HTTP requests that do have a security context automatically.

Cool, that's legit scenario.

> I didn't model any of that in the reproducer, so sorry if the reproducer looks a bit silly.

I just tried to understand, this is okay. Thank you

**Comment by mkouba** [comment]
> Judging from the changelog of 3.7.2, this might be a consequence of #38605
> 
> Looking at the pull request's description, my use-case was never legal and should have never worked to begin with. Would you agree @mkouba ?
> 

That's correct. It only "worked" by coincidence.

**Comment by Felk** [comment]
Alright, thanks for confirming! I'll close this issue
