### ISSUE TITLE
RestEasy extension no longer picks up Resource implementations with a corresponding interface

### ISSUE THREAD

**Issue by garyttierney** [quarkusio/quarkus#3871]
**Describe the bug**

Previously it was possible to create an interface specification of a JAX-RS resource, and implement it separately:

<small>common-project/MyResource.java</small>
```java

@Path("/")
interface MyResource {
    @GET 
    String value()
}
```

<small>quarkus-project/ServerMyResource.java</small>
```java
class ServerMyResource implements MyResource {

    @Override 
    public String value() {
        return "value";
    }
}
```
**Expected behavior**

Accessing `/` in my Quarkus application should return "value".

**Actual behavior**

I see a 404 instead.

**To Reproduce**
1.  Create a new JAX-RS resource with the JAX-RS annotations on an interface
2.  Attempt to access the resource paths via. a Quarkus app

**Configuration**
```properties
N/A
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 5.2.7-200.fc30.x86_64 #1 SMP Thu Aug 8 05:35:29 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`:  openjdk version "1.8.0_222"
 - GraalVM version (if different from Java):  N/A
 - Quarkus version or git rev: c519e38da9fc4c588c9bdde02c2d4c5861a239e5

**Additional context**

This only became a problem as of 21.0, in 20.0 it still works fine. I've put together a test case to verify this behaviour:

```java
public class RestEasyAbstractResourceTestCase {
    @RegisterExtension
    static QuarkusUnitTest runner = new QuarkusUnitTest()
            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
                    .addClasses(ConcreteRootResource.class));

    @Test
    public void testRootResource() {
        RestAssured.when().get("/").then().body(Matchers.is("root"));
    }
}

public class ConcreteRootResource implements AbstractRootResource {

    @Override
    public String root() {
        return "root";
    }
}

@Path("/")
public interface AbstractRootResource {

    @GET
    String root();
}
```

Which fails with the following (not sure why it's manifesting as unauthorized):

```
[ERROR]   RestEasyAbstractResourceTestCase.testRootResource:20 1 expectation failed.
Response body doesn't match expectation.
Expected: is "root"
  Actual: <html><head><title>Error</title></head><body>Forbidden</body></html>
```

**Comment by garyttierney** [comment]
Update: this stemmed from the fact that my project is a multi-module project. In 0.20.0, one of my modules was included in the Jandex index even though it had no `beans.xml` or `application.properties` listing.

I'm not sure if this a regression, but I do wonder if we can handle the multi-module case in a better way (is sticking all our user modules in the Jandex index a reasonable thing to do?)

Happy to close this unless the behaviour is viewed as a regression.

**Comment by mkouba** [comment]
> In 0.20.0, one of my modules was included in the Jandex index even though it had no beans.xml or application.properties listing.

This is how bean discovery currently works in Quarkus, ie. a module must contain `beans.xml`, `META-INF/jandex.idx` or be referenced by quarkus.index-dependency in `application.properties`. See https://quarkus.io/guides/cdi-reference#bean_discovery for more details.

So I'd say it's not a regression but a fixed bug in the gradle integration.

> but I do wonder if we can handle the multi-module case in a better way

Hm, something like "add all modules from the project automatically" similarly as we do with the root? I'm not sure it's a good idea. @stuartwdouglas @gsmet @aloubyansky @geoand WDYT?
 
For now just add an empty `beans.xml` descriptor and you're done.

**Comment by geoand** [comment]
> Hm, something like "add all modules from the project automatically" similarly as we do with the root? I'm not sure it's a good idea. @stuartwdouglas @gsmet @aloubyansky @geoand WDYT?

Maybe this would create more problems that it solved? Not sure either, so just asking
