### ISSUE TITLE
entityManager.merge does not work in some cases

### ISSUE THREAD

**Issue by alomine** [quarkusio/quarkus#38722]
### Describe the bug

Hello!
In some cases hibernate entityManager.merge fails to update some fields when setting them to null. I have prepared some test cases to show when it works just fine and when it fails. Fails are when database fields are null except the one that needs to be set to null AND its not date field (which somehow works).

Case might be similar to:
https://github.com/quarkusio/quarkus/issues/22080
and 
https://github.com/quarkusio/quarkus/issues/2815

Also if something is not clear or i need to provide more info, please feel free to ask

### Expected behavior

All tests in given repository should pass

### Actual behavior

2 of 6 tests fails. You can see in logs that update is not made

### How to Reproduce?

Simply use `.\mvnw test` in [my project](https://github.com/alomine/quarkus-hibernate-bug)

### Output of `java -version`

17

### Quarkus version or git rev

3.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

**Comment by yrodiere** [comment]
Hey @alomine, thanks for reporting.
Are you sure this is specific to Quarkus? Can you reproduce with [plain Hibernate ORM test case templates](https://github.com/hibernate/hibernate-test-case-templates/tree/main/orm/hibernate-orm-6)?

**Comment by alomine** [comment]
Hello @yrodiere, thanks for response.
I'll try this. For now i can say two things - its not working in both quarkus 2.x.x version and 3.x.x (different hibernate versions) and its totally working on wildfly 26

**Comment by yrodiere** [comment]
Thanks, looking forward to the reproducer.

**Comment by alomine** [comment]
@yrodiere 
I did two [test cases](https://github.com/alomine/hibernate-qtest-case) with plain hibernate based on examples that you posted.  Both 7/7 successful

**Comment by gsmet** [comment]
My guess is that it's related to the bytecode enhancement.

**Comment by Nikita-V0lkov** [comment]
I have some research on this issue.
---
### 1. Transactional annotation on the TestBugTest class instead of TestEntityService. 

All tests will be passed, but the data in the database will not be updated.

---
### 2. QuarkusTransaction instead of annotation. You will have two possible variants:
2.1 Test fail, data not updated.

```
@Test
public void saveAndCheckWithNonNullNumber_test() {
    QuarkusTransaction.begin();
    testEntityService.clean();
    TestEntity testEntity = createEntityWithNonNullNumber();
    testEntityService.save(testEntity);
    QuarkusTransaction.commit();
    assertEquals(1, testEntityService.find(1L).getNumberField());
    
    QuarkusTransaction.begin();
    testEntity = createEntityWithAllNulls();
    testEntityService.update(testEntity);
    QuarkusTransaction.commit();
    assertEquals(null, testEntityService.find(1L).getNumberField());
}
```

2.2 Test passed, data not updated (similar to placing the Transactional annotation on the TestBugTest class).

```
@Test
public void saveAndCheckWithNonNullNumber_test() {
    QuarkusTransaction.begin();
    testEntityService.clean();
    TestEntity testEntity = createEntityWithNonNullNumber();
    testEntityService.save(testEntity);
    assertEquals(1, testEntityService.find(1L).getNumberField());
    QuarkusTransaction.commit();
    
    QuarkusTransaction.begin();
    testEntity = createEntityWithAllNulls();
    testEntityService.update(testEntity);
    assertEquals(null, testEntityService.find(1L).getNumberField());
    QuarkusTransaction.commit();
}
```
---
### 3. Update "refreshed" data after save (Transactional on TestEntityService).

3.1 Works as intended data in db updated.
```
@Test
public void saveAndCheckWithNonNullNumber_test() {
    testEntityService.clean();
    TestEntity testEntity = createEntityWithNonNullNumber();
    TestEntity savedEntity = testEntityService.save(testEntity);
    assertEquals(1, testEntityService.find(1L).getNumberField());
    
    savedEntity.setDateField(null);
    savedEntity.setNumberField(null);
    savedEntity.setStringField(null);
    testEntityService.update(savedEntity);
    assertEquals(null, testEntityService.find(1L).getNumberField());
}
```
```
public TestEntity save(TestEntity entity) {
    testEntityRepository.getEntityManager().persist(entity);
    testEntityRepository.getEntityManager().flush();
    testEntityRepository.getEntityManager().refresh(entity);
    return entity;
}
```

3.2 Save and find. Works similar to 3.1

```
@Test
public void saveAndCheckWithNonNullNumber_test() {
    testEntityService.clean();
    TestEntity testEntity = createEntityWithNonNullNumber();
    testEntityService.save(testEntity);
    assertEquals(1, testEntityService.find(1L).getNumberField());
    
    TestEntity savedEntity = testEntityService.find(1L);
    savedEntity.setDateField(null);
    savedEntity.setNumberField(null);
    savedEntity.setStringField(null);
    testEntityService.update(savedEntity);
    assertEquals(null, testEntityService.find(1L).getNumberField());
}
```

I hope this helps in some way.

**Comment by alomine** [comment]
Hello @Nikita-V0lkov,
in 3.1 and 3.2 entity you named as **savedEntity** is in _persistent_ state and in this state this seems to be working. However by explicitly calling merge it shouldnt really matter.

**Comment by marko-bekhta** [comment]
Hey,

> I did two [test cases](https://github.com/alomine/hibernate-qtest-case) with plain hibernate based on examples that you posted. Both 7/7 successful

As Guillaume suggested, you'd need to add bytecode enhancement to reproduce the issue with Hibernate ORM only. Here's a bug report based on this in ORM's JIRA: https://hibernate.atlassian.net/browse/HHH-17761

**Comment by alomine** [comment]
Is there a way to disable hibernate bytecode enhancement on quarkus ?

**Comment by yrodiere** [comment]
There is not, and there are no plans to allow it.

**Comment by HOPtool** [comment]
I have an entity object

@Entity
@Table(name="profiles_logs")
public class ProfileSetup extends PanacheEntityBase implements Serializable
{

  @Id
  @GeneratedValue(strategy=GenerationType.IDENTITY)
  @Column(name="tid")
  public long tid;

  @Column(name="first_name")
  public String firstName;

  ......
  ......

  and in my Repository  I am doing this 

  @Transactional
  public ProfileSetup doLog(UserProfileRequest request ) throws Exception {
    ProfileSetup profile = null;
    try 
    {
        
    UserProfileRequestObj fromJson =  new UserProfileRequestObj(request);
      

    ProfileSetup profilex = doLookUpByName(fromJson.emailAddress,fromJson.mobileNo);

       log.info("--doLookUpByParamName -- "+profile);
       if(profilex == null)
       {

                   
               profile = new ProfileSetup();
               profile.createdDate = LocalDateTime.now();
               profile.emailAddress = fromJson.emailAddress;
               profile.firstName = fromJson.firstName;
               profile.full_name = fromJson.fullName;
               profile.lastName = fromJson.lastName;
               profile.loginStatus = 0;
               profile.mobileNo = fromJson.mobileNo;
               profile.tilAccount   = fromJson.tilAccount;
               profile.status = ResourceStatusEnum.INACTIVE.name();
               profile.userRole = fromJson.userRole;
               //Panache.getEntityManager().merge(profile);
               Panache.getEntityManager().persist(profile);//.merge(profile);
               Panache.getEntityManager().flush();//.getTransaction()..commit();
       
       } 
       else
       {
           return profilex;
       }
       
    } 
    catch (Exception e) {
        e.printStackTrace();
        throw new Exception(e);
    }
 return profile;
}
Both Panache.getEntityManager().merge(profile) and Panache.getEntityManager().persist(profile) return without errors, and the tid (PK) returns incremented and no errors, however data not persisted to database, I also tried using an Agroal Implementation where I obtained the connection object and used prepared statement executeUpdate() which returned a value of 1, yet no data in my database. Amazingly someother objects are persisting to database in the same project. Please can anyone help?

I have tried the following.
1. Recreate the database table
2. Use and Agroal implementation so I can  grab the connection object and use prepare statement
3. Have my entity  object extand PanacheEntity and used PanacheEntity.getEntityManager()


All this have not solved the issue

**Comment by yrodiere** [comment]
Hello @HOPtool .

Please do not post like this on old issues. You should open a new issue.

In order for us to help, that issue should include:

1. A high-level description of your problem
2. Any relevant stacktrace (the _whole_ stacktrace) and logs
3. A reproducer, i.e. a small Quarkus application (as a ZIP or GitHub repository) that we can execute locally to reproduce the issue.
