### ISSUE TITLE
Java 21: @VirtualThreadUnit produces very slow tests

### ISSUE THREAD

**Issue by SpaceFox** [quarkusio/quarkus#38721]
### Describe the bug

On a Java 21 project, following [this documentation](https://quarkus.io/blog/virtual-threads-3/), I added `@VirtualThreadUnit @ShouldNotPin` annotations on several tests to ensure there is no thread pinning due to using some external libs.

As result, my tests becomes very slow: 52 seconds for 32 tests, instead of 10 seconds without the `@VirtualThreadUnit` annotation.

### Expected behavior

The overhead to detect thread pinning is reasonnable, **or** if this behaviour is inevitable, it is documented.

### Actual behavior

Tests become way slower without any warning. This may lead this annotation to be unusable on large test suites. This it the cause for me to categorize this point into a bug and not an enhancement.

### How to Reproduce?

1. Create a new Quarkus project with sample code and no additional module.
2. Add the `io.quarkus.junit5:junit5-virtual-threads` dependency
3. ~~Add `@RunOnVirtualThread` on `GreetingResource#hello()`~~ _(edit: not mandatory – the result is the same without this annotation – but actual code should use this annotation)_
4. Lanch the tests and check the time for them to run (~1.9 s on my desktop)
5. Add `@VirtualThreadUnit @ShouldNotPin` to the `GreetingResourceTest`
6. Lanch the tests and check the time for them to run (~6.6 s on my desktop)

You may use this project https://github.com/SpaceFox/test-quarkus-java21-tests to check the exact versions I used.

### Output of `uname -a` or `ver`

Linux cthulhu 6.5.0-17-generic #17~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan 16 14:32:32 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Corretto-21.0.2.13.1 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.2.13.1 (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /home/spacefox/.m2/wrapper/dists/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6 Java version: 21.0.2, vendor: Amazon.com Inc., runtime: /home/spacefox/.jdks/corretto-21.0.2 Default locale: fr_FR, platform encoding: UTF-8 OS name: "linux", version: "6.5.0-17-generic", arch: "amd64", family: "unix"

### Additional information

Tested with both Maven and Gradle, no notable difference.

Tested with temurin-21.0.1 and corretto-21.0.2, no notable difference.

Tested with ibm-semeru-21.0.2, `@VirtualThreadUnit` breaks the tests.

**Comment by fcolin-odigo** [comment]
I also tested with original `me.escoffier.loom:loom-unit:0.3.0` version by @cescoffier and as expected, the behaviour is the same.

**Comment by SpaceFox** [comment]
I also tested with `me.escoffier.loom:loom-unit:0.3.0` from @cescoffier and as expected, the behaviour is the same.

**Comment by cescoffier** [comment]
Unfortunately, there is not much we can do.

Let me explain. We trigger JFR recording to detect pinning and analyze when a specific event is fired. Unfortunately, to ensure we do not miss any events, we must ensure the JFR recording is on and off. We fire a mock event and wait until we read it. 

The JFR recording API is not great, and it takes a lot of time to do these loops, there are many file reads. As you can see, it takes around 2 seconds to start and 2 seconds to stop. But without them, we cannot be sure we are not missing an event. 

I hope it will be improved in future versions of the JDK. I know we kind of abuse something that was not meant to be used like that. 

I have tried other ways, based on bytecode manipulation - but manipulating classes from the JDK is... never a good idea.

**Comment by cescoffier** [comment]
(obviously if you think of a better way, I would love to hear about it)

**Comment by SpaceFox** [comment]
Thank you very much for your explanation.

I’m not aware enough of JVM internals to have a better solution that the current one; however, I can add your explanation to the `@VirtualThreadUnit` annotation Javadoc. This would at least warn users about the potential performance issues.

Let me know if this is a good idea and if yes, I’ll do it (I know some projects prefer not having this kind of data in their Javadoc).

**Comment by cescoffier** [comment]
Yes! Having a note in the javadoc would be great! Ping me once you have a PR.
