### ISSUE TITLE
javax.sound.midi.MidiSystem not working

### ISSUE THREAD

**Issue by three-old-coders** [quarkusio/quarkus#38725]
### Describe the bug

I built my quarkus native app using gradle and quarkus 3.7.2
Native app starts without issues, but the Midi Device list is empty (output from MidiSystem.getMidiDeviceInfo()). 

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-02-10 21:44:16,516 INFO  [io.quarkus] (main) java 0.1.0 native (powered by Quarkus 3.7.2) started in 0.032s. 
2024-02-10 21:44:16,516 INFO  [io.quarkus] (main) Profile prod activated. 
2024-02-10 21:44:16,516 INFO  [io.quarkus] (main) Installed features: [cdi]
[]

```

Building a traditional fat jar everything works as expected and all connected usb devices are listed.

```
[Gervill, Real Time Sequencer, M4x4 [hw:2,0,0], M4x4 [hw:2,0,1], M4x4 [hw:2,0,2], M4x4 [hw:2,0,3], M4x4 [hw:2,0,0], M4x4 [hw:2,0,1], M4x4 [hw:2,0,2], M4x4 [hw:2,0,3]]
SOFTWARE_MIDI_SYNTHESIZER-GERVILL-OPENJDK OUTs: 0, INs: -1
SOFTWARE_SEQUENCER-REAL_TIME_SEQUENCER-ORACLE_CORPORATION OUTs: -1, INs: -1
MIDISPORT_4X4_USB_MIDI_MIDISPORT_4X4-M4X4_HW200-ALSA_HTTPWWWALSA-PROJECTORG OUTs: 0, INs: -1
MIDISPORT_4X4_USB_MIDI_MIDISPORT_4X4-M4X4_HW201-ALSA_HTTPWWWALSA-PROJECTORG OUTs: 0, INs: -1
MIDISPORT_4X4_USB_MIDI_MIDISPORT_4X4-M4X4_HW202-ALSA_HTTPWWWALSA-PROJECTORG OUTs: 0, INs: -1
MIDISPORT_4X4_USB_MIDI_MIDISPORT_4X4-M4X4_HW203-ALSA_HTTPWWWALSA-PROJECTORG OUTs: 0, INs: -1
MIDISPORT_4X4_USB_MIDI_MIDISPORT_4X4-M4X4_HW200-ALSA_HTTPWWWALSA-PROJECTORG OUTs: -1, INs: 0
MIDISPORT_4X4_USB_MIDI_MIDISPORT_4X4-M4X4_HW201-ALSA_HTTPWWWALSA-PROJECTORG OUTs: -1, INs: 0
MIDISPORT_4X4_USB_MIDI_MIDISPORT_4X4-M4X4_HW202-ALSA_HTTPWWWALSA-PROJECTORG OUTs: -1, INs: 0
MIDISPORT_4X4_USB_MIDI_MIDISPORT_4X4-M4X4_HW203-ALSA_HTTPWWWALSA-PROJECTORG OUTs: -1, INs: 0

```

### Output of `uname -a` or `ver`

Linux debian 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux

### Quarkus version or git rev

3.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5, Apache Ant(TM) version 1.10.13 compiled on January, Mac OS X 14.0 x86_64 4 2023, 17.0.7 (GraalVM Community 17.0.7+7-jvmci-22.3-b18), 

### Additional information

 ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.additional-build-args=-march=compatibility,--initialize-at-run-time=javax.el.ELUtil,--initialize-at-run-time=javax.sound.midi.MidiSystem -Dquarkus.native.compression.level=5

**Comment by geoand** [comment]
This is definitely not supported out of the box by Quarkus. 

I propose asking the GraalVM folks if and how this can be achieved
