### ISSUE TITLE
Programatically scheduled function via quartz not possible to disable if started in @PostConstruct of @Startup bean

### ISSUE THREAD

**Issue by HelvetiaAppDev** [quarkusio/quarkus#38729]
### Describe the bug

When using the quarkus-quartz extension and only having programatically scheduled functions that are started within the `@PostConstruct` of a `@Startup` bean the config `quarkus.scheduler.enabled=false` leads to an exception on startup.

### Expected behavior

No exception and scheduler is disabled

### Actual behavior

Quarkus fails to start because with the following exception:
`java.lang.IllegalStateException: Quartz scheduler is either explicitly disabled through quarkus.scheduler.enabled=false or no @Scheduled methods were found. If you only need to schedule a job programmatically you can force the start of the scheduler by setting 'quarkus.scheduler.start-mode=forced'.`

### How to Reproduce?

1. Init empty quarkus project with only dependency quarkus-quartz
2. add `quarkus.scheduler.enabled=false` to application.properties
3. Add a programatically scheduled method within a `@Startup` bean
e.g.

```
import io.quarkus.runtime.Startup;
import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.quartz.Job;
import org.quartz.JobBuilder;
import org.quartz.JobDetail;
import org.quartz.JobExecutionContext;
import org.quartz.Scheduler;
import org.quartz.SchedulerException;
import org.quartz.SimpleScheduleBuilder;
import org.quartz.Trigger;
import org.quartz.TriggerBuilder;

import java.util.concurrent.atomic.AtomicInteger;

@Startup
@ApplicationScoped
public class CounterBean {
    @Inject Scheduler scheduler;

    private AtomicInteger counter = new AtomicInteger();

    public int get() {
        return counter.get();
    }

    void increment() {
        counter.incrementAndGet();
    }

    @PostConstruct
    void init() throws SchedulerException {
        JobDetail job = JobBuilder.newJob(JobClass.class)
                .withIdentity("programmatic", "default")
                .build();
        Trigger trigger = TriggerBuilder.newTrigger()
                .withIdentity("programmatic-trigger", "default")
                .startNow()
                .withSchedule(SimpleScheduleBuilder.simpleSchedule().withIntervalInMinutes(1).repeatForever())
                .build();

        scheduler.scheduleJob(job, trigger);
    }

    public static class JobClass implements Job {
        @Inject CounterBean counterBean;

        @Override public void execute(JobExecutionContext jobExecutionContext) {
            System.out.println("programmatic schedule");
            counterBean.increment();
        }
    }
}
```

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 W62902 3.3.6-bec3d608-341.x86_64 2023-02-22 08:29 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)                   OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

3.7.2 (but already in 2.16.12.Final)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.6

### Additional information

Does not happen with quarkus scheduler, only with quartz.
Not tested why, but with quarkus 2.16.12.Final everything works with `quarkus.scheduler.enabled=true`, in 3.7.2 this also seems to fail without the `quarkus.scheduler.start-mode=forced`.

**Comment by mkouba** [comment]
This works as designed and [documented](https://quarkus.io/guides/scheduler-reference#programmatic_scheduling). If you explicitly disable the scheduler then you can't use it at all.

If you really need to do something like in the snippet above, you can inject the `io.quarkus.quartz.QuartzScheduler` instead and then test the `QuartzScheduler#isRunning()` status or the return value of `QuartzScheduler#getScheduler()` (which is `null` if the scheduler was not started).

> Not tested why, but with quarkus 2.16.12.Final everything works with quarkus.scheduler.enabled=true, in 3.7.2 this also seems to fail without the quarkus.scheduler.start-mode=forced.

Yes, `quarkus.scheduler.start-mode=forced` is needed unless your app declares at least one `@Scheduled` method. I believe that the error message is clear.

**Comment by HelvetiaAppDev** [comment]
@mkouba thank you for your quick answer.

I couldn't find any information in the documentation stating that if `quarkus.scheduler.enabled` is set to `false`, you need to manually verify whether the scheduler is running. Based on my understanding of the documentation, this property should be used to disable all schedulers, regardless of how they are started.

It's a bit inconsistent that the "normal" Quarkus scheduler can be invoked (without actually starting the scheduled task), while the Quartz scheduler prevents the application from starting.

**Comment by mkouba** [comment]
> Based on my understanding of the documentation, this property should be used to disable all schedulers, regardless of how they are started.

It is. `quarkus.scheduler.enabled=false` means: do not start the scheduler. Still, it's very convenient to be able to inject the `io.quarkus.scheduler.Scheduler` in order to find out if it's running or not.

> It's a bit inconsistent that the "normal" Quarkus scheduler can be invoked (without actually starting the scheduled task), while the Quartz scheduler prevents the application from starting.

The thing is that if `quarkus.scheduler.enabled=false` is set then we don't instantiate the Quartz scheduler at all. Which is IMO reasonable. And thus it's not possible to inject `org.quartz.Scheduler` directly.
