### ISSUE TITLE
Accept-Header in hibernate validator's ResteasyReactiveLocaleResolver is resolved case-sensitive

### ISSUE THREAD

**Issue by ChMThiel** [quarkusio/quarkus#38730]
### Describe the bug

According to [HTTP-Standard](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2) HTTP-header-keys are to be compared case-insensitive. in [ResteasyReactiveLocaleResolver.getHeaders()](https://github.com/quarkusio/quarkus/blob/0290e66d11a47fd52ab7fe2d39505c78caa2e883/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/locale/ResteasyReactiveLocaleResolver.java#L34) all values of the case-insensitive Headers-Map are copied in a standard HashMap. So requesting the value for a given key in this map is no longer case-insensitive.

If any Proxy (Like HA-Proxy is doing) converts given headers to lower-case (according HTTP-Standard), the ResteasyReactiveLocaleResolver will not find the given header but always return default-Locale as fallback.

### Expected behavior

ResteasyReactiveLocaleResolver resolves given _Accept-Language_ HTTP-Header to a Locale, regardles of the upper/lower-case of the given key.

### Actual behavior

lower-case HTTP-header 'accept-language' is not resolved, default locale is returned instead.

**Comment by geoand** [comment]
@ChMThiel would you like to contribute a fix for this?

**Comment by ChMThiel** [comment]
Yes, i can

**Comment by geoand** [comment]
🙏🏼

**Comment by gsmet** [comment]
I agree it should be fixed. Looking forward to your contribution!

**Comment by gsmet** [comment]
I think we should probably go for the easiest way meaning storing the header names as lower case and getting them as lowercase too.
We should add a Javadoc to `AbstractLocaleResolver#getHeaders()` to make it clear.

**Comment by ChMThiel** [comment]
see PR https://github.com/quarkusio/quarkus/pull/38738
