### ISSUE TITLE
OpenApi generates non-ordered params

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#38736]
### Describe the bug

Open Api genrator doesn't preserve the order of method parameters. This leads to a weird parameter order in the client using the API specs to generate the clients. Example:

Resource
```

@Path("/api")
public class GreetingResource {

    @GET
    @Path("/hello/start/{start}/end/{end}/another/{another}")
    @Operation(operationId = "getHello", summary = "params demo", description = "returns hello with given params")
    @APIResponses({@APIResponse(responseCode = "200", description = "Success"), @APIResponse(responseCode = "500", description = "Error"),})
    public String hello(
            @Parameter(description = "Start", example = "start") @PathParam("start") String start,
            @Parameter(description = "End", example = "end") @PathParam("end") String end,
            @Parameter(description = "Another", example = "another") @PathParam("another") String another
    ) {
        return "Hello %s %s %s".formatted(start, end, another);
    }
}
```

Generated yaml:
```
---
openapi: 3.0.3
info:
  title: code-with-quarkus API
  version: 1.0.0-SNAPSHOT
paths:
  /api/hello/start/{start}/end/{end}/another/{another}:
    get:
      tags:
        - Greeting Resource
      summary: params demo
      description: returns hello with given params
      operationId: getHello
      parameters:
        - name: another
          in: path
          description: Another
          required: true
          schema:
            type: string
          example: another
        - name: end
          in: path
          description: End
          required: true
          schema:
            type: string
          example: end
        - name: start
          in: path
          description: Start
          required: true
          schema:
            type: string
          example: start
```

### Expected behavior

the generated yaml must preserve the order of method parameters. in the example above: start,end,another

### Actual behavior

the generated yaml does not preserve the order of method parameters. in the example above: another,end,start

### How to Reproduce?

[demo.tar.gz](https://github.com/quarkusio/quarkus/files/14238619/demo.tar.gz)
1. extract
2. ./mvnw quarkus:dev
3. curl localhost;8080/q/openapi

### Quarkus version or git rev

3.7.2

**Comment by phillip-kruger** [comment]
Why does the order matter ? These are named parameters.

**Comment by ennishol** [comment]
@phillip-kruger  because the generated code with openapi maven plugin will be like 
```
String getHello(String another, String end, String start);
```
it is weird here because `end` parameter comes before `start` one.

**Comment by MikeEdgar** [comment]
@ennishol if you place your `@Parameter` annotations on the method and not the parameters, the order should be respected. You'll need to add the `name` property to the annotations so that they can be matched to the method arguments. Depending on how many REST operations you have, that might be an acceptable solution.

**Comment by MikeEdgar** [comment]
@ennishol did you try it with related `@Parameter` annotations?

**Comment by ennishol** [comment]
@MikeEdgar Yes when put on the method it then works as expected. Thank you!
