### ISSUE TITLE
SchedulerUtils Duration parsing breaks when using duration in days without explicit prefix

### ISSUE THREAD

**Issue by kovacevicm** [quarkusio/quarkus#38766]
### Describe the bug

If the duration text starts with a digit, SchedulerUtils adds "PT" prefix.
https://github.com/quarkusio/quarkus/blob/main/extensions/scheduler/common/src/main/java/io/quarkus/scheduler/common/runtime/util/SchedulerUtils.java#L178

This works for hours, minutes and seconds, but not for days, as it causes `DateTimeParseException` with the message "Text cannot be parsed to a Duration".
See "Examples" at https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence- .

### Expected behavior

I can either define Scheduler annotation `every` property as `1D` or the documentation states the limitation about having to use `P1D`.

### Actual behavior

The app won't start throwing `IllegalStateExcption` caused by `DateTimeParseException` with the message "Text cannot be parsed to a Duration".

**Comment by mkouba** [comment]
> If the duration text starts with a digit, SchedulerUtils adds "PT" prefix.

Yes, it's properly documented both in the [reference guide](https://quarkus.io/guides/scheduler-reference#intervals) and in the javadoc of `@Scheduled#every()` as well.

> This works for hours, minutes and seconds, but not for days, as it causes DateTimeParseException with the message "Text cannot be parsed to a Duration".

Obviously.

> I can either define Scheduler annotation every property as 1D or the documentation states the limitation about having to use P1D.

Yes, we could detect the suffix and then adapt the "implicit" prefix. Would you care to send a pull request?
