### ISSUE TITLE
Refresh token reuse

### ISSUE THREAD

**Issue by rwb196884** [quarkusio/quarkus#38778]
### Describe the bug

I'm seeing lots of errors in IdentityServer for token issued failure when this library is trying to re-use refresh tokens.

![image](https://github.com/quarkusio/quarkus/assets/12090617/435c791b-e8f2-4799-bc83-7cd88a804a7d)

### Expected behavior

The library does not use a refresh token more than once.

### Actual behavior

The library does use refresh tokens more than once.

**Comment by sberyozkin** [comment]
Hi @rwb196884 I believe you should move this issue to the Keycloak project repository, cc @pedroigor
