### ISSUE TITLE
Resteast Reactive: BlockingNotAllowedException on POST Method with Uni return type

### ISSUE THREAD

**Issue by ITrium-Salah** [quarkusio/quarkus#38788]
### Describe the bug

I'm encountering a BlockingNotAllowedException in my RESTEasy Reactive code while trying to return a Uni<String> from a POST endpoint with a request body. The endpoint is supposed to return a Uni created using Uni.createFrom().item(""), yet I'm still facing this exception. The exception seem to be triggered when Vertx try to read the inputstream

### Expected behavior

No exception or more specific for the actual problem

### Actual behavior

BlockingNotAllowedException: Attempting a blocking read on the io thread

### How to Reproduce?

```java
@Path("/message")
@Produces({MediaType.APPLICATION_JSON})
@Consumes({MediaType.APPLICATION_JSON})
public class Controller{

      @POST
      @Path("add")
      public Uni<String> test(String body)
      {
           return Uni.createFrom().item("res");
      }
}
```

Make a request with postman.

I'm pretty sure the problem don't come from the endpoint but maybe from the dependencies.
I'm using quarkus-resteasy-reactive-jackson, quarkus-qpid-jms, quarkus-config-yaml, quarkus-websocket-client, lombok and mapstruct.

### Output of `java -version`

openjdk version 21.0.1

### Quarkus version or git rev

Quarkus 3.5.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

version 3

### Additional information

If i remove the body part of the endpoint the exception is not thrown.

**Comment by geoand** [comment]
Can you try with the latest Quarkus and see if the problem persists?

Asking because we recently fixed a similar bug.

Thanks

**Comment by ITrium-Salah** [comment]
I upgrade quarkus to version 3.7.2 and i don't see the bug anymore.
Thanks @geoand for the quick reply

**Comment by geoand** [comment]
Glad to hear it!
