### ISSUE TITLE
Add support for @TransactionalScoped into narayana extension

### ISSUE THREAD

**Issue by manovotn** [quarkusio/quarkus#3878]
Narayana offers `@TransactionalScoped` as a "custom" CDI context. This is normally registered via CDI extension which of course isn't possible here - instead we should use [`ContextRegistrar` ](https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ContextRegistrar.java )Arc extension (or its [build item](https://github.com/quarkusio/quarkus/blob/master/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ContextRegistrarBuildItem.java) variant) to get that context in.

As much as possible, we should reuse Narayana's [`TransactionContext`](https://github.com/jbosstm/narayana/blob/master/ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionContext.java).

Note that this is currently blocking TCKs for MP Context Propagation which assumes transactional scoped can be used.

**Comment by kenfinnigan** [comment]
Maybe @xstefank can help with this?

**Comment by manovotn** [comment]
Also note that the context will need things like `TransactionSynchronizationRegistry` and current Narayana extension already has providers for those, see [`NarayanaJTAProducers`](https://github.com/quarkusio/quarkus/blob/master/extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaProducers.java).

**Comment by manovotn** [comment]
I was thinking @ochaloup from Narayna might be interested in looking into this?

**Comment by ochaloup** [comment]
@manovotn yes, I would be. @kenfinnigan what is the priority (and +/-deadline) for this feature?

**Comment by kenfinnigan** [comment]
Right now it blocks adding the MP Context Propagation TCK into the build, and also prevents `@TransactionalScoped` from being used in Quarkus.

There's no hard deadline, but we're trying to get all TCKs running in Quarkus before 1.0 to ensure we pass and resolve minor issues

**Comment by ochaloup** [comment]
@kenfinnigan not so far, but I finally have some time to look into it. Hopefully I'll have some better new this week.
