### ISSUE TITLE
Built-in RestDataPanacheExceptionMapper is not overridable or has higher priority

### ISSUE THREAD

**Issue by slgobinath** [quarkusio/quarkus#38799]
### Describe the bug

The PanacheEntityResource implementations throws RestDataPanacheException which is handled by the built-in [io.quarkus.hibernate.orm.rest.data.panache.runtime.RestDataPanacheExceptionMapper](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-orm-rest-data-panache/runtime/src/main/java/io/quarkus/hibernate/orm/rest/data/panache/runtime/RestDataPanacheExceptionMapper.java) class. I want to return custom responses for certain types of RestDataPanacheExceptions but my custom ExceptionMapper is used neither in dev mode nor when I run uber jar.

This issue is similar to https://github.com/quarkusio/quarkus/issues/7883 but not sure if the fix was specific to all exception mappers or only for NotFoundExceptionMapper.

### Expected behavior

The custom ExceptionMapper implemented by the user must take precedence.

### Actual behavior

The custom ExceptionMapper is not used at all. Always Quarkust runs the default RestDataPanacheExceptionMapper.

### How to Reproduce?

1. Create a rest resource extending `PanacheEntityResource` for an entity with generated id
2. Create a custom exception mapper `ExceptionMapper<RestDataPanacheException>`
3. Send a POST request to create an entity with an explicitly defined id
4. Observe that the default RestDataPanacheExceptionMapper is used instead of the custom mapper

### Output of `uname -a` or `ver`

Linux mypc 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "21.0.1" 2023-10-17 LTS Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29) Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

### Quarkus version or git rev

3.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by geoand** [comment]
Can you please attach a sample application that behaves as you mention?

Thanks

**Comment by slgobinath** [comment]
Hi @geoand , Thanks for the quick response.
I've created the new project here https://github.com/slgobinath/issue-38799 
Here's the link to core classes:
- PanacheEntityResource: [FooResource](https://github.com/slgobinath/issue-38799/blob/main/src/main/java/com/example/foo/FooResource.java)
- ExceptionMapper: [RestDataPanacheExceptionMapper](https://github.com/slgobinath/issue-38799/blob/main/src/main/java/com/example/foo/RestDataPanacheExceptionMapper.java) - If this class is picked up the response code must be 400 and the test will pass. Instead, if the built-in mapper is used, 500 status code will be returned and the test will fail.
- Test class: [FooResourceTest](https://github.com/slgobinath/issue-38799/blob/main/src/test/java/com/example/FooResourceTest.java)

While playing with it more I came across an interesting case.
Setting `@Priority(1)` to [[RestDataPanacheExceptionMapper.java#L12](https://github.com/slgobinath/issue-38799/blob/main/src/main/java/com/example/foo/RestDataPanacheExceptionMapper.java#L12)] fixes the problem which makes sense to me - Is this is the expected behavior? I'm new to Quarkus so not sure if all custom mappers must have an explicit priority set.

However, moving the `RestDataPanacheExceptionMapper` class to the `com.example.config` package also fixes the problem which I don't know how. Again, I'm new to Quarkus so not sure if this is an expected behavior but as a novice Quarkus user, I expected it to work regardless of the location (aka package) of the class.

**Comment by geoand** [comment]
I am not sure what the problem is, but if you use `quarkus-resteasy-reactive-jackson` (as we recommend) instead of `quarkus-resteasy-jackson`, then everything works as expected

**Comment by slgobinath** [comment]
Thanks @geoand
Switching to `quarkus-resteasy-reactive-jackson` does fix the problem. Feel free to close this issue or edit it to `quarkus-resteasy-jackson` specific.
