### ISSUE TITLE
Quarkus camel Context in storage not the expected context, Scope.close was not called correctly

### ISSUE THREAD

**Issue by brianmolinaspring** [quarkusio/quarkus#38808]
### Describe the bug

Context in storage not the expected context, Scope.close was not called correctly

### Expected behavior

Not receiving the warning

### Actual behavior

Warning : Context in storage not the expected context, Scope.close was not called correctly

### How to Reproduce?

when using version [3.0.0-M1] onwards it happens, dependency used:

<dependency>
<groupId>org.apache.camel.quarkus</groupId>
<artifactId>camel-quarkus-opentelemetry</artifactId>
<version>3.7.0</version>
</dependency>

### Output of `java -version`

17

### Quarkus version or git rev

3.2.10.Final

### Additional information

How can I remove this warning since I am using a log collection and I do not want to show those warnings

**Comment by gastaldi** [comment]
Please open issues regarding Quarkus Camel in https://github.com/apache/camel-quarkus/issues, this tracker is for Quarkus core and core extensions only
