### ISSUE TITLE
Mocking Singleton does not work even when using @MockitoConfig(convertScopes = true) - Bean produced from factory method

### ISSUE THREAD

**Issue by connorsadler** [quarkusio/quarkus#38817]
### Describe the bug

We have an issue when using @InjectMock with a `@Singleton `bean and using `@MockitoConfig(convertScopes = true)`
It does not work if our "bean" (sorry if this is not the right term) is created using a factory method / producer method.
The mocking does not seem to work, until I mark the factory method explicitly as `@Produces` - usually you don't have to do this in Quarkus, but to get `@InjectMock` and `@MockitoConfig` to work, it seems to be necessary (to get this mocking to work).

This is a follow on from my comment on here: https://github.com/quarkusio/quarkus/issues/35080

### Expected behavior

Mocking should work and test should run

### Actual behavior

Test does not run

Error is of form as follows:
(please see README.md in enclosed reproducible for full error)
```
...
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
...
Caused by: java.lang.IllegalStateException: Invalid use of io.quarkus.test.InjectMock - the injected bean does not declare a CDI normal scope but: jakarta.inject.Singleton. Offending field is sampleApiFromFactory of test class class org.acme.SampleUseCaseTest

```

### How to Reproduce?

[sample_app_issue_10022024.zip](https://github.com/quarkusio/quarkus/files/14310941/sample_app_issue_10022024.zip)

Small reproducible attached - please see README.md

### Output of `uname -a` or `ver`

Mac os

### Output of `java -version`

Zulu 21.0.2

### Quarkus version or git rev

3.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.3

**Comment by geoand** [comment]
cc @manovotn  @Ladicek you were part of the discussion in #35080 that led to this

**Comment by Ladicek** [comment]
This is because the annotation transformer in `SingletonToApplicationScopedTestBuildChainCustomizerProducer`:

1. doesn't look into the annotation overlay for the `@Produces` annotation, but directly into Jandex;
2. always runs _before_ the annotation transformer in `AutoProducerMethodsProcessor`, due to `getPriority()`.

Should be an easy fix.
