### ISSUE TITLE
quarkus-redis-client: issue when publishing data using ReactiveRedisDataSource.pubsub

### ISSUE THREAD

**Issue by jithinsethu** [quarkusio/quarkus#38831]
### Describe the bug

quarkus-redis-client data is not inserted to redis using ReactiveRedisDataSource.pubsub.publish but works in the case of RedisDataSource

### Expected behavior

Can able to push to redis using ReactiveRedisDataSource.pubsub.publish method

### Actual behavior

No errors or logs are seen

### How to Reproduce?

https://github.com/jithinsethu/quarkus-redis-example/tree/main

### Output of `java -version`

17

**Comment by cescoffier** [comment]
`reactivePub.publish` returns a Uni. You'll need to subscribe to it, or nothing will happen.

See: https://smallrye.io/smallrye-mutiny/latest/tutorials/creating-uni-pipelines/#subscribing-to-a-uni.
