### ISSUE TITLE
Keycloak Admin Client Reactive error id: 9009f9b4-1d58-4011-9ff2-49b87bb59ddd-1: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "authHeader" is null

### ISSUE THREAD

**Issue by maxlam79** [quarkusio/quarkus#38833]
### Describe the bug

Hello there,

I was attempting migrating one of my existing projects to Quarkus Reactive with Keycloak Admin. Unfortunately, I hit this error, error id: 9009f9b4-1d58-4011-9ff2-49b87bb59ddd-1: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "authHeader" is null while calling the Keycloak class via REST end-point.

Here's a small repo to demonstrate this issue:
[https://github.com/maxlam79/KeycloakReactiveNullAuthHeaderProblemDemo](https://github.com/maxlam79/KeycloakReactiveNullAuthHeaderProblemDemo)

I was attemping to migrate a past quarkus class project to quarkus reactive. The keycloak config fields in the application.properties are the config fields with values which was working well in the past classic project. Now, I have included the same config with the "quarkus-" prefix in the application.properties according to the documentation.

I wonder if I'm calling methods from the Keycloak Admin Client correctly?

### Output of `uname -a` or `ver`

MacOS Montery 12.7.2

### Output of `java -version`

openjdk version "21" 2023-09-19

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.4

**Comment by michalvavrik** [comment]
Thanks, I had to adjust your reproducer bit, but indeed there is a bug when using Keycloak Admin Client with `-jsonb` extensions. I'll look into in next week.

**Comment by michalvavrik** [comment]
fyi @maxlam79 you can work around it by using `-jackson` extensions instead (drop `-jsonb`), but you probably know that.

**Comment by michalvavrik** [comment]
I'm honestly not sure if you can use Keycloak Admin Client with the `quarkus-rest-client-reactive-jsonb` and I'll try to understand it first and if there is not a reasonable way I'll document it in the https://quarkus.io/guides/security-keycloak-admin-client#references.

/cc @geoand just in case you have an opinion on that, not necessary to spend time

**Comment by michalvavrik** [comment]
Alright, it's definitely possible. I'll have to investigate proper way to do it, but at the very least replacing of the 
https://github.com/quarkusio/quarkus/blob/427e73fa9b9b95b61a7d2cf62a2e5cc8131ff8a1/extensions/keycloak-admin-client-reactive/runtime/src/main/java/io/quarkus/keycloak/admin/client/reactive/runtime/ResteasyReactiveClientProvider.java#L47
with the:
```
        clientBuilder.withConfig(new ConfigurationImpl(RuntimeType.CLIENT));
        clientBuilder.register(new ClientJacksonMessageBodyWriter(new ObjectMapper()), 100);
        clientBuilder.register(new ClientJacksonMessageBodyReader(new ObjectMapper()), 100);
```
works around the issue. So I'll try to achieve it next week. Thanks for reporting the issue.

**Comment by michalvavrik** [comment]
Also tweaking https://github.com/quarkusio/quarkus/blob/427e73fa9b9b95b61a7d2cf62a2e5cc8131ff8a1/extensions/keycloak-admin-client-reactive/runtime/src/main/java/io/quarkus/keycloak/admin/client/reactive/runtime/ResteasyReactiveClientProvider.java#L31 works around the issue. I'll try to find how to fix it best though.

**Comment by maxlam79** [comment]
@michalvavrik, thanks for the effort.
