### ISSUE TITLE
Raw Socket Protocol Support

### ISSUE THREAD

**Issue by DaiYuANg** [quarkusio/quarkus#38873]
### Description

Do we have something like [Spring Integration TCP/UDP Support](https://docs.spring.io/spring-integration/reference/ip/intro.html)
I have known it can use vertx `createNetServer` implement, but can we add an extension or annotation to create net server?
Like
```java
@NetServer(port=9090,channel="mainChannel")
publick class NetServer{

	@NetServerHandler(channel="mainChannel")
	public void handlerSocketMessage(Buffer buf){
		//handle socket message
	}
}
```

**Comment by cescoffier** [comment]
We do not have a specific extension. The reason is that TCP is rather low level, and configuration can be tedious. Thus we prefer proposing a programmatic approach:

```java
@Startup 
public class MyTcpServer {
     public MyTcpServer(Vertx vertx) {
     
          vertx.createNetServer(....);
     }
}
```

**Comment by cescoffier** [comment]
We can work with you to improve the documentation - because it's clearly undocumented.

**Comment by DaiYuANg** [comment]
> We do not have a specific extension. The reason is that TCP is rather low level, and configuration can be tedious. Thus we prefer proposing a programmatic approach:
> 
> ```java
> @Startup 
> public class MyTcpServer {
>      public MyTcpServer(Vertx vertx) {
>      
>           vertx.createNetServer(....);
>      }
> }
> ```

I agree with you but could we provide a way like VertxOptionsCustomizer for configure net server or some clean way for accept raw TCP packet to avoid using vertx low level API?

**Comment by cescoffier** [comment]
Can you provide an example of how it would look like? 
I guess it would only save the cal to the `.listen` method.

**Comment by cescoffier** [comment]
Closing - lack of feedback. 

It is possible to create TCP server using the Vert.x API directly.
