### ISSUE TITLE
Kafka Messaging extension: Ability to create/provision Reactive Kafka Consumers dynamically(Runtime) without @Incoming annotations

### ISSUE THREAD

**Issue by xqianwang** [quarkusio/quarkus#38892]
### Description

We need to create/provision kafka Consumer dynamically during runtime. For example, if there is a new topic created in kafka, we need to create consumers for that newly created topic. Another use case is webhook. Whenever there is a webhook client registered/called, we need to create consumers for some topics for listening messages.

**Comment by xqianwang** [comment]
@cescoffier @ozangunalp  Some suggestions or insights please.

**Comment by cescoffier** [comment]
Reactive messaging has been designed for a declarative model where you know the topics in advance.

You can use regexp on the consuming side or metadata on the producing side to handle dynamic topics. Note that for regexp, it will only fetch new topics when metadata are refreshed (that's periodic).


If you need more dynamism, you can use the bare Kafka client for this. Note that you will need to make sure you understand how Kafka consumers and producers work. Also, creating Kafka topic dynamically has costs on the broker - make sure you understand that before creating millions of topics.

**Comment by xqianwang** [comment]
> Reactive messaging has been designed for a declarative model where you know the topics in advance.
> 
> You can use regexp on the consuming side or metadata on the producing side to handle dynamic topics. Note that for regexp, it will only fetch new topics when metadata are refreshed (that's periodic).
> 
> If you need more dynamism, you can use the bare Kafka client for this. Note that you will need to make sure you understand how Kafka consumers and producers work. Also, creating Kafka topic dynamically has costs on the broker - make sure you understand that before creating millions of topics.

Thanks for reply. For the webhook use case, how can I handle it with reactive messaging?

**Comment by cescoffier** [comment]
Kafka and webhooks are tricky. Basically, you will need a single topic with a single partition but acknowledgement will be tricky. 

You can try without reactive messaging, but you will have the same limitations.
