### ISSUE TITLE
Build Card Page for Dev UI results in NPE in ArtifactInfoUtil

### ISSUE THREAD

**Issue by Dudeplayz** [quarkusio/quarkus#38908]
### Describe the bug

I want to create a Dev UI for our extension. I copied some code form the docs and the openapi extension and ending always in a NPE.

```java
    @BuildStep(onlyIf = IsDevelopment.class)
    public CardPageBuildItem pages(NonApplicationRootPathBuildItem nonApplicationRootPathBuildItem,
                                   ManagementInterfaceBuildTimeConfig managementInterfaceBuildTimeConfig,
                                   LaunchModeBuildItem launchModeBuildItem) {

        String schemaPath = nonApplicationRootPathBuildItem.resolveManagementPath("test2",
                managementInterfaceBuildTimeConfig, launchModeBuildItem);

        CardPageBuildItem cardPageBuildItem = new CardPageBuildItem();

        cardPageBuildItem.addPage(Page.externalPageBuilder("Schema yaml")
                .url(schemaPath, schemaPath)
                .isYamlContent()
                .icon("font-awesome-solid:file-lines"));

        String jsonSchema = schemaPath + "?format=json";
        cardPageBuildItem.addPage(Page.externalPageBuilder("Schema json")
                .url(jsonSchema, jsonSchema)
                .isJsonContent()
                .icon("font-awesome-solid:file-code"));

        return cardPageBuildItem;
    }
```

### Expected behavior

A starting app with the created Dev UI.

### Actual behavior

Getting an NPE at https://github.com/quarkusio/quarkus/blob/885cb8ab3625f106ddd7cf9105fc606e47d5c218/core/deployment/src/main/java/io/quarkus/deployment/util/ArtifactInfoUtil.java#L120

```
2024-02-20 23:25:26,894 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.devui.deployment.BuildTimeContentProcessor#mapPageBuildTimeData threw an exception: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null
        at io.quarkus.deployment.util.ArtifactInfoUtil.isDeploymentTargetClasses(ArtifactInfoUtil.java:120)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:93)
        at io.quarkus.devui.spi.AbstractDevUIBuildItem.getExtensionPathName(AbstractDevUIBuildItem.java:61)
        at io.quarkus.devui.deployment.BuildTimeContentProcessor.mapPageBuildTimeData(BuildTimeContentProcessor.java:157)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

This is the state of the input value when the NPE occurs:
![CleanShot 2024-02-20 at 23 40 26@2x](https://github.com/quarkusio/quarkus/assets/15174076/c66935ac-eefe-4bc8-979d-c62e88fd2f92)

 I think there is a missing `null` check for `location.getFileName()` where it is `null` for the root path. Also I don't know if it is MacOS related.

### How to Reproduce?

Note: The project is a multi-module project.
1. Copy the processor code form above into a processor
2. Run the extension in development mode on MacOS
3. NPE should occur

### Output of `uname -a` or `ver`

Darwin MBP-von-Dario.fritz.box 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment JBR-17.0.5+1-653.23-nomod (build 17.0.5+1-b653.23) OpenJDK 64-Bit Server VM JBR-17.0.5+1-653.23-nomod (build 17.0.5+1-b653.23, mixed mode)

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

IntelliJ bundled maven 3.9.5

**Comment by phillip-kruger** [comment]
@Dudeplayz Do you have a reproducer I can look at ?

**Comment by Dudeplayz** [comment]
@phillip-kruger I think the issue is another. We created a deployment-common package where the code rests.
So this line https://github.com/quarkusio/quarkus/blob/885cb8ab3625f106ddd7cf9105fc606e47d5c218/core/deployment/src/main/java/io/quarkus/deployment/util/ArtifactInfoUtil.java#L128
fails for us, where our path is: `/Users/.../deployment-commons/target/classes`.

**Comment by Dudeplayz** [comment]
I tired to add the Dev UI here: https://github.com/mcollovati/quarkus-hilla/tree/main/deployment-commons/src/main/java/com/github/mcollovati/quarkus/hilla/deployment

The Dev UI processor is above. I don't have an explicit reproducer by now. But I think it relates to the different package naming I mentioned above. I can create one if still needed?

**Comment by phillip-kruger** [comment]
Ok, if you can share something that reproduce this I can see if it's possible to accommodate that structure. But if you can change to use the default structure we can probably close here

**Comment by Dudeplayz** [comment]
We will discuss it. Is this restriction/behavior documented somewhere? Maybe just check if it begins or contains the `deployment` phrase instead of equality?

**Comment by phillip-kruger** [comment]
Let me have a look and get back to you

**Comment by Dudeplayz** [comment]
But maybe some catching of the `null` returning root path or more meaningful error message would be helpful there too.

**Comment by phillip-kruger** [comment]
I think the way we have done it in Quarkus, is to move common stuff a separate extension. Example: electon security: https://github.com/quarkusio/quarkus/tree/main/extensions

elytron-security-common
elytron-security-jdbc
elytron-security-ldap
elytron-security-oauth2
elytron-security-properties-file
elytron-security

So a user will add one of the extensions, example elytron-security-oauth2 and that will pull in the elytron-security-common extension. 

Doing it this way should allow you to put the common Dev UI in the common extension

**Comment by phillip-kruger** [comment]
Clossing, no feedback. Please reopen if needed.
