### ISSUE TITLE
Offer a conversion table between Spring Boot annotations and Quarkus annotations

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3890]
A user at the BordeauxJUG asked me for a conversion table between the Spring Boot annotations and the CDI/RESTEasy etc annotations. I think it would be a good guide complement

**Comment by geoand** [comment]
Sure thing.

I assume we are talking about a separate guide?

**Comment by emmanuelbernard** [comment]
Yes but I think it would be referenced or in the "landing guide" for Spring users as well

**Comment by geoand** [comment]
This will need to be done sometime soon

**Comment by geoand** [comment]
I'm doing this one now and will open a PR soon
