### ISSUE TITLE
try it out in swagger configuration option

### ISSUE THREAD

**Issue by msillence** [quarkusio/quarkus#38933]
### Description

The quarkus swagger ui configuration options: https://quarkus.io/guides/openapi-swaggerui#swagger-ui
cover many of the options but there are a few omissions I'd really like the tryItOutEnabled flag https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

Thanks it's been super swift getting this up and running

**Comment by gsmet** [comment]
@msillence looks like a good opportunity to contribute. I think it shouldn't be too hard.

The code for the Swagger UI extension is here: https://github.com/quarkusio/quarkus/tree/main/extensions/swagger-ui

And we have some guidance for contributing here: https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md

**Comment by phillip-kruger** [comment]
@msillence if you are keen, the change will have to start in SmallRye: https://github.com/smallrye/smallrye-open-api/blob/main/ui/open-api-ui/src/main/java/io/smallrye/openapi/ui/IndexHtmlCreator.java

**Comment by msillence** [comment]
Oh that's odd it was added in October, looking at the tag it should be in release > 3.7.0 and I'm using 3.7.3
I however don't see the option in the swagger plugin https://github.com/quarkusio/quarkus/blob/main/extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiConfig.java

**Comment by phillip-kruger** [comment]
Maybe it's just not mapped in Quarkus then ?
