### ISSUE TITLE
Decorating MongoClient does not work because decorator is removed during build

### ISSUE THREAD

**Issue by luca-bassoricci** [quarkusio/quarkus#38970]
I wrote a `@Decorator` around a MongoClient but the decorator is never called because it is removed during build.

 [this reproducer](https://github.com/luca-bassoricci/mongo-client-decorator-issue) contains a simple decorator around a MongoClient and a test; this test fails because decorator is never called (it is removed during build).

Currently I'm using quarkus-morphia.
When I tried to decorate the synthetic Morphia's `Datastore` created from extension because I want to add transactional support and I faced the same problem I had decorating the `MongoClient`. 
Could be a problem related to synthentic beans?

_Originally posted by @luca-bassoricci in https://github.com/quarkusio/quarkus/discussions/38926#discussioncomment-8557028_

**Comment by loicmathieu** [comment]
@mkouba is there a known limitation with CDI decorator of synthetic beans?

**Comment by mkouba** [comment]
> @mkouba is there a known limitation with CDI decorator of synthetic beans?

Yes, decorators and interceptors are never applied to synthetic beans because the container does not control instantiation of a bean.
