### ISSUE TITLE
cert chain public key resolver thumbprints

### ISSUE THREAD

**Issue by calvernaz** [quarkusio/quarkus#38989]
### Describe the bug

I have a truststore configured to validate the oidc token, a self contained token with full chain certs, but fails to validate the thumbprints [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CertChainPublicKeyResolver.java#L40). However, I can debug and verified that one if the thumbprints is valid, happens not to be the **first one** on index 0. 

So, I'm thinking if instead of picking one (index 0), we should instead call calculate all the thumbprints of the chain and check if any of the set are part of the trust store certificate thumprints.

### Expected behavior

Except one the thumbprints to be valid and proceed.

### Actual behavior

Throws an exception `UnresolvableKeyException("Certificate chain thumprint is invalid")`

**Comment by sberyozkin** [comment]
@calvernaz As far as I recall it is a root cert thumbprint,  will look next week,  thanks

**Comment by sberyozkin** [comment]
Correction: it is a subject certificate one, at least in the test

**Comment by sberyozkin** [comment]
So, in prod, the truststores may not have the leaf/subject certificates, but only the root certificates.

Right now, Quarkus OIDC expects the leaf certificate be in the store as it must trust the leaf certificate itself - as per the `x5c` claim specification it is this certificate that must be used to verify the signature.

If we have a situation where the truststore only has a root certificate there must be a way to identify at the `quarkus-oidc` level the leaf certificate which is a signature verification certificate - using `CName` is what has to be done in such cases.

For example: `quarkus.oidc.certificate-chain.cname`. Adding this CName will help to assert that this is indeed the expected leaf certificate. And if this property is set then Quarkus will expect the root certificate in the `x5c` chain match the keystore certificate thumbprint.

It can be made more configurable later but for now lets try to stay quite strict with respect to accepting such chains.
