### ISSUE TITLE
Wrong duplicateEndPoint when implements two Rest interfaces

### ISSUE THREAD

**Issue by FredMencier** [quarkusio/quarkus#38982]
### Describe the bug

I got an DeploymentException when i try to implements two Rest interfaces. The problem is present just when the interfaces define a unique method. In this case the @Path annotation is on the interface and not on the method. If i add @Path annotation on method the problem disappear. My Interfaces are define with contract first (openApi yaml) and are generated by the plugin maven OpenApi (not visible in my reproducer)

### Expected behavior

Build successful

### Actual behavior

[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.7.4:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: jakarta.enterprise.inject.spi.DeploymentException: POST /admin/transaction/createpseudotransactions is declared by :
[ERROR] org.test.GreetingResource#pushForward consumes *, produces *
[ERROR] org.test.GreetingResource#createPseudoTransactions consumes *, produces *
[ERROR]
[ERROR]         at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.checkForDuplicateEndpoint(ResteasyReactiveProcessor.java:1382)
[ERROR]         at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:673)

### How to Reproduce?

https://github.com/FredMencier/quarkus-restapi

### Output of `uname -a` or `ver`

MSYS_NT-10.0-19045 DEVVX700057 3.3.6-341.x86_64 2023-01-31 15:09 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.8.1" 2023-08-24 OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode, sharing)

### Quarkus version or git rev

3.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

**Comment by geoand** [comment]
This is weird, I'll have to take a look

**Comment by geoand** [comment]
What happens is that because the concrete class has no `@Path`, it takes the `@Path`  from the first interface it implements and then uses that as the base path. 

I would argue that the generated code is simply incorrect... 
For example if you add `quarkus.resteasy-reactive.fail-on-duplicate=false` and do a `POST http://localhost:8080/admin/treasury/pushforward`, you will get a 404.

So I am going to close this as there is no really way to handle this pathological case

**Comment by FredMencier** [comment]
Hi geoand, thks for your answer.
Are you saying that an interface rest with only one method cannot be written like that ? :

@Path("/admin/treasury/pushforward")
public interface MyApi {
    @POST
    void myMethod(@QueryParam("contractRef") String contractRef);
}

**Comment by geoand** [comment]
What I am saying is that you can't expect a concrete class to implement interfaces that both have a `@Path` annotation on them.

**Comment by FredMencier** [comment]
hi geoand, thanks for your answer. I understand, i try another way
