### ISSUE TITLE
[Extension Proposal] shedlock

### ISSUE THREAD

**Issue by dcdh** [quarkusio/quarkus#38993]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-shedlock

### Short description

Integrate shedlock as a quarkiverse extensions

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/shedlock/dev/

### Repository Topics

- quarkus-extension
- shedlock

### Team Members

- me
- everyone
-

**Comment by dcdh** [comment]
work in progress here https://github.com/dcdh/quarkus-shedlock

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-shedlock/. Enjoy!

**Comment by melloware** [comment]
Nice @dcdh i used Shedlock for Spring Boot and its a nice simple alternative to Quartz!
