### ISSUE TITLE
@Cache annotation not honored on reactive REST resource beans with separate interface

### ISSUE THREAD

**Issue by danielbobbert** [quarkusio/quarkus#39002]
### Describe the bug

The org.jboss.resteasy.reactive.Cache annotation is only honored, if it is put on a JaxRS bean or a JaxRS interface itself.
If put on a bean that *implements* a JaxRS interface, the annotation is ignored.

Reasoning: We have lots of services where the JaxRS interfaces are generated from OpenAPI specification. We provide beans that implement these interfaces and Quarkus. We would like to add @Cache annotations to some of the implemented methods to control generated "Cache-Control" headers. But the annotation is ignored.
We cannot put the annotation of the JaxRS interface itself, because that is generated from an OpenAPI spec.

### Expected behavior

When putting a @Cache annotation on a bean method that implements a JaxRS interface, the appropriate "Cache-Control" header should be generated.

### Actual behavior

@Cache annotation is only honored when put on the JaxRS interface itself.

### How to Reproduce?

See attached maven project with failing unit test.

### Output of `uname -a` or `ver`

Mac OS 14 (on MacBook Pro M1)

### Output of `java -version`

openjdk version "17.0.2"

### Quarkus version or git rev

3.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.6

### Additional information

[resteasy-reactive-cache.zip](https://github.com/quarkusio/quarkus/files/14403472/resteasy-reactive-cache.zip)

**Comment by danielbobbert** [comment]
The first sample project was actually missing the @Cache annotation on the implementation. I added it (but of course, the test still fails)
[resteasy-reactive-cache.zip](https://github.com/quarkusio/quarkus/files/14403514/resteasy-reactive-cache.zip)

**Comment by geoand** [comment]
Makes sense to me. 

Would you like to implement this fix?

**Comment by geoand** [comment]
> Can you very briefly point me to an explanation of the difference? In my tests, they seem to return the same thing, so I am unsure which one I should use and why.

`AnnotationStore` gives you a way to find annotations of all classes. 
`method.annotation()` gives you the annotations of a method.
`class.declaredAnnotation()` gives you the annotations declared on the class only

**Comment by geoand** [comment]
> Or am I missing something here?

You are right. If you want you can fix this behavior, but please do it in a separate PR
