### ISSUE TITLE
quarkus-redis-client tracing

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#39011]
### Description

We need to implement quarkus-redis-client tracig with OpenTelemetry.
The implementation must be placed under the instrumentation of the `quarkus-opentelemetry` extension.

The Redis client responses are async. See `io.quarkus.redis.runtime.client.ObservableRedisMetrics` class for reference.

See: https://github.com/quarkusio/quarkus/discussions/33196

**Comment by Ladicek** [comment]
I'm not sure how Vert.x tracing (and client metrics) can be used in Quarkus, but if they can, I'd like to point out that the Vert.x Redis client now has client metrics and tracing (see https://github.com/vert-x3/vertx-redis-client/pull/398).

**Comment by luneo7** [comment]
I've added tracing support for Redis Client locally, I am just writing the integration test and can do a PR tomorrow.

**Comment by cescoffier** [comment]
Awesome! Thanks, @luneo7, I am looking forward to seeing it!

**Comment by tarric1** [comment]
The same thing is needed for DB access by means of Panache!
