### ISSUE TITLE
Dev-UI : Documentation ehancement

### ISSUE THREAD

**Issue by allemas** [quarkusio/quarkus#39027]
### Description

I wanted to dive into the Dev-UI configuration to disable it in the production profile. Maybe I've missed something, I couldn't find any documentation about it. I mainly found this documentation : https://quarkus.io/guides/dev-ui and I think I'm not the only one who lacked information.

I suggest working on the documentation and adding a configuration section to detail the possibilities. 

### Implementation ideas

In a first time 
- How devui works inside Quarkus (maybe by add details on how its loaded)
- How enable/disable it (for production env)
- Improve readability flow with more sections and updates found outside the official documentation.

I'm open to any suggestions :)

**Comment by phillip-kruger** [comment]
Dev UI does not run in Prod.

**Comment by allemas** [comment]
Yes, that I said. I found the information outside the documentation. I suggest add a mention and take the opportunity to improve our documentation. 

That's why I've come to discuss it in a previous issue.

**Comment by phillip-kruger** [comment]
Ok, so you want to add to the documentation that Dev UI is only in Dev ? Sorry if I misunderstood.

**Comment by phillip-kruger** [comment]
This is fairly clear in the documentation:

"Quarkus ships with a Developer UI, which is available in dev mode (when you start quarkus with mvn quarkus:dev) at /q/dev-ui by default"

**Comment by allemas** [comment]
Maybe add more details, and add a reference to the profile configuration? This would help people who start their jar in `java -jar` mode with the default profile in application.properties and miss it.

**Comment by phillip-kruger** [comment]
I think documentation can always be improved, but we also need to be careful not to include to much details that is not important for most users and extension developers.

> How devui works inside Quarkus (maybe by add details on how its loaded)

This is probably out of scope for the user guide, but we can document if somewhere. It's fairly complex with multiple things happening. There are static Js files (web components) that loads, there are UI libs that loads, there are build time data that loads, there are the setup of the runtime backend services, then there are the websocket and json-rpc service that loads. All only in Dev mode. It's very internal, but can be documented. I think most users will not be interested in this.

> How enable/disable it (for production env)

It's not available in prod, so not sure we can document anything here. You cannot disable it in Dev mode.


> Improve readability flow with more sections and updates found outside the official documentation.

Not sure what you mean here. Can you give an example ?

**Comment by phillip-kruger** [comment]
> Maybe add more details, and add a reference to the profile configuration? This would help people who start their jar in `java -jar` mode with the default profile in application.properties and miss it. 
> 
> 

This maybe ? https://quarkus.io/guides/lifecycle#launch-modes

**Comment by allemas** [comment]
> I think documentation can always be improved, but we also need to be careful not to include to much details that is not important for most users and extension developers.
> 
> > How devui works inside Quarkus (maybe by add details on how its loaded)
> 
> This is probably out of scope for the user guide, but we can document if somewhere. It's fairly complex with multiple things happening. There are static Js files (web components) that loads, there are UI libs that loads, there are build time data that loads, there are the setup of the runtime backend services, then there are the websocket and json-rpc service that loads. All only in Dev mode. It's very internal, but can be documented. I think most users will not be interested in this.
> 

Ok we forgot it :) It was a simply suggestion

> > How enable/disable it (for production env)
> 
> It's not available in prod, so not sure we can document anything here. You cannot disable it in Dev mode.

Say it more clearly.

The issue was firstly for discuss and know if your open to suggestions on this :)
I can't atm, I'll prepare a PR with more details about relation between profile configurations and DevUI (Be sure, I understood : devui is not available in production) with a plan suggestion.

**Comment by melloware** [comment]
@allemas can this ticket be closed now?  The documentation is clear to me and no PRs have been accepted.

**Comment by cescoffier** [comment]
Thanks for the feedback - closing.
