### ISSUE TITLE
Add support for OpenTelemetry metrics.

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#39033]
### Description

Include in the current `quarkus-opentelemetry` extension the ability to create and export OpenTelemetry Metrics data.
This issue will not instrument any Quarkus code, That will continue to be done with Micrometer.

This issue will facilitate the creation of a Micrometer to OpenTelemetry bridge in Quarkus.

**Comment by antonaverin-oviva** [comment]
@brunobat thanks a lot for the work on the open telemetry integrations. Planning observability in the project, I have a couple questions about `Micrometer to OpenTelemetry bridge in Quarkus`:
- would it also connect metrics with "other signals"? This is one of the main design goals for OTel metics stated here: https://opentelemetry.io/docs/specs/otel/metrics/#design-goals. My expectation would be to have OTel traces and metrics connected.
- when it comes to instrumentations, for eg. http clients, Micrometer and OTel generate different metrics in different format. Would the bridge pass Micrometer metrics as is or it will also transform it to the OTel format? Metrics format is important when defining alerts based on metrics.

**Comment by brunobat** [comment]
Hi @antonaverin-oviva. The idea is to have the ability to have an integrated experience of traces and metrics. 
If the case of metrics we plan to support tracing exemplars. 
In relation to the automatic instrumentation, for now, we only plan a bridge from the current metrics implemented with Micrometer to OpenTelemetry format. The semantic conventions to use (the names of the attributes in metrics) will be the ones coming from Micrometer.
There are many reasons for this, I can highlight a few:

- Micrometer conventions are quite stable and currently, OpenTelemetry Semantic conventions are still being created and change quite frequently.
- There are many projects already instrumented with Micrometer and very few using OpenTelemetry metrics. 

Saying this, after this issue is implemented, users can actually create their own metrics on OpenTelemetry directly, no need for Micrometer.

**Comment by brunobat** [comment]
Still working on Documentation and signal agnostic configurations.
