### ISSUE TITLE
JAX-RS seeOther does not work with IPv6

### ISSUE THREAD

**Issue by imperatorx** [quarkusio/quarkus#39041]
### Describe the bug

If you access a Quarkus app on an ipv6 address on a port, like http://[xxxx:xxxx:xxxx......]:8080, and send a Response.seeOther in your jaxrs resource, the ResponseBuilderImpl gets confused by the extra ":" charecters while trying to extract the port and fails.

### Expected behavior

ResponseBuilderImpl should correctly parse an IPv6 address

### Actual behavior

java.lang.NumberFormatException: For input string: "d014:32c:xxxx:xxxx:xxxx:xxxx:xxxx]:8080"
        at java.base@21.0.2/java.lang.Integer.parseInt(Integer.java:662)
        at java.base@21.0.2/java.lang.Integer.parseInt(Integer.java:778)
        at org.jboss.resteasy.reactive.server.jaxrs.ResponseBuilderImpl.location(ResponseBuilderImpl.java:33)
        at jakarta.ws.rs.core.Response.seeOther(Response.java:713)

### How to Reproduce?

See description

### Output of `uname -a` or `ver`

Linux ip-172-26-1-8 6.1.0-18-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS

### Quarkus version or git rev

2.7.x

**Comment by geoand** [comment]
Indeed!

**Comment by geoand** [comment]
The interesting thing is that `RestResponseBuilderImpl` has the correct use of `lastIndexOf` 🤦🏼
