### ISSUE TITLE
`quarkus` subcommands change POM formatting and drops XML comments

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#39048]
### Describe the bug

When I use `quarkus ext add <something>` in an application, the command will fully rewrite the POM, changing formatting and, critically, dropping XML comments (`<!-- ... -->`).

### Expected behavior

`quarkus` subcommands manipulating the POM should not change its formatting, reorder properties or drop any meaningful information like XML comments.

This seems possible as, from what I've seen, `quarkus update` manages to do it using OpenRewrite.

### Actual behavior

`quarkus` subcommands manipulating the POM change its formatting and drop XML comments.

I remember seeing them reorder Maven properties or dependencies as well, but I didn't check recently, so I may be wrong about that.

### How to Reproduce?

Use `quarkus ext add hibernate-search-orm-outbox-polling` on a Quarkus application whose POM contains comments, e.g., https://github.com/quarkusio/search.quarkus.io where the POM contains this:

```
  <properties>
    <compiler-plugin.version>3.12.1</compiler-plugin.version>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.version>3.7.3</quarkus.version>
    <revision>999-SNAPSHOT</revision>
    <skipITs>true</skipITs>
    <surefire-plugin.version>3.2.5</surefire-plugin.version>
    <test.jvm.args>-Xms2g -Xmx2g</test.jvm.args>
    <version.docker.plugin>0.44.0</version.docker.plugin>
    <version.formatter.plugin>2.23.0</version.formatter.plugin>
    <version.impsort-maven-plugin>1.9.0</version.impsort-maven-plugin>
    <!-- This version needs to match the version in src/main/docker/opensearch-custom.Dockerfile -->
    <version.opensearch>2.11</version.opensearch>
  </properties>
```

### Quarkus version or git rev

3.7.4

**Comment by gsmet** [comment]
Closed in favor of https://github.com/quarkusio/quarkus/issues/39088 where I centralized all the info so far.
