### ISSUE TITLE
Reactive pg datasource with enabled health check opens more connections than configured

### ISSUE THREAD

**Issue by dgewiss** [quarkusio/quarkus#39047]
### Describe the bug

We use the reactive postgresql datasource, with configured max-size and enabled datasource health check.

### Expected behavior

The maximum number of open connections are equals the configured number.

### Actual behavior

The number of open database connections increases to twice the maximum number configured.

### How to Reproduce?

1. Create a simple app with reactive postgresql datasource and datasource health check (quarkus create app  --extension='resteasy-reactive,reactive-pg-client,resteasy-reactive-jackson,smallrye-health')
2. Configure max-size (quarkus.datasource.reactive.max-size=5)
3. Enable health check (quarkus.datasource.health.enabled=false)
4. Create an endpoint with database access
5. Call this endpoint and the health endpoint a view times (for example with apache benchmark)
6. Check the open connections in your database

Small reproducer can be found here: https://github.com/dgewiss/quarkus-reactive-health-check-test

### Output of `java -version`

openjdk 21 2023-09-19 LTS

### Quarkus version or git rev

3.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

### Additional information

This workaround works for me:

Disable the datasource health check and use a own implementation of ReactivePgDataSourcesHealthCheck.

The difference to the original implementation is that `io.vertx.mutiny.pgclient.PgPool` is used to select the connection pool instead of `io.vertx.pgclient.PgPool`. The delegate is then passed to the ReactiveDatasourceHealthCheck.

This workraound is also incuded in the reproducer.

**Comment by xstefank** [comment]
Inner health check implementation detail. CC/ @reactive-sql-clients @tsegismont @vietj.

**Comment by tsegismont** [comment]
It seems this isn't a problem with the health check implementation, but rather a problem with the pool injection.

Consider this:

```java
	@Inject
	private io.vertx.mutiny.pgclient.PgPool mutinyPool;
	@Inject
	private io.vertx.pgclient.PgPool pool;

	@PostConstruct
	protected void init() {
		System.out.println("pool = " + pool);
		System.out.println("mutinyPool.getDelegate() = " + mutinyPool.getDelegate());
	}
```

The output will be something like:

```
pool = io.vertx.pgclient.impl.PgPoolImpl@6a6aea13
mutinyPool.getDelegate() = io.vertx.pgclient.impl.PgPoolImpl@37d7bd79
```

But it should be:

```
pool = io.vertx.pgclient.impl.PgPoolImpl@6a6aea13
mutinyPool.getDelegate() = io.vertx.pgclient.impl.PgPoolImpl@6a6aea13
```

In other words, Quarkus creates two different pools if both the Mutiny and Vert.x variants are injected.

@geoand I'm not sure, but I suspect this might be related to https://github.com/quarkusio/quarkus/commit/dc78468f027944b66396fd5b89abd111e219e54a

Would you mind taking a look?

**Comment by geoand** [comment]
Sure yeah, I'll have a look tomorrow

**Comment by tsegismont** [comment]
> Sure yeah, I'll have a look tomorrow

Thank you



> @geoand I'm not sure, but I suspect this might be related to [dc78468](https://github.com/quarkusio/quarkus/commit/dc78468f027944b66396fd5b89abd111e219e54a)

In fact, the regression was introduced before this commit, I can see the problem with `3.4.3`.

However, the output is correct with `3.3.2`

**Comment by geoand** [comment]
So the commit above could very well be the culprit as it was introduced in `3.4.1`

**Comment by tsegismont** [comment]
Can you please try this:

1. create a new project with https://code.quarkus.io/?j=21&e=reactive-pg-client&extension-search=origin:platform%20postgres
2. add the class below to the project
3.  run

```java
import io.quarkus.runtime.Startup;
import jakarta.annotation.PostConstruct;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;

@Singleton
@Startup
public class Test {

    @Inject
    io.vertx.mutiny.pgclient.PgPool mutinyPool;
    @Inject
    io.vertx.pgclient.PgPool pool;

    @PostConstruct
    protected void init() {
        System.out.println("pool = " + pool);
        System.out.println("mutinyPool.getDelegate() = " + mutinyPool.getDelegate());
    }

}
```

I get this on the console:

```
pool = io.vertx.pgclient.impl.PgPoolImpl@795fb3c5
mutinyPool.getDelegate() = io.vertx.pgclient.impl.PgPoolImpl@41c8893a
```

**Comment by geoand** [comment]
> I get this on the console:

That I get, but I can't reproduce the real problem of having more open connections that the configured max number

**Comment by tsegismont** [comment]
> That I get, but I can't reproduce the real problem of having more open connections that the configured max number

Do you mean, running the reproducer provided by @dgewiss ? In this case, if you didn't modify anything, that is expected. The builtin health check is disabled in the config and a user provided health check uses an injected mutiny pool (so it's always the same pool that's injected).

**Comment by tsegismont** [comment]
To be precise: in order to reproduce, you must delete the custom health check class and enable health checks in config.

**Comment by geoand** [comment]
Ah okay.

I'll do that tomorrow

**Comment by geoand** [comment]
#39251 takes care of the problem

**Comment by tsegismont** [comment]
@geoand thanks, I'll review it right away

**Comment by geoand** [comment]
🙏🏼

**Comment by geoand** [comment]
👌
