### ISSUE TITLE
Add support for device flow grant type to oidc-client

### ISSUE THREAD

**Issue by stianst** [quarkusio/quarkus#39050]
### Description

I'm working on a token CLI for Keycloak that can be useful for developers to understand tokens and flows, but also that can be used to obtain tokens for other CLIs, including supporting for kubectl.

For password and service accounts I'm using the `oidc-client`, which is great as it has a lot of features that I would otherwise have to write, but one problem is that it doesn't support [Device Authorization Grant](https://oauth.net/2/grant-types/device-code/).

I'm not expecting `oidc-client` to do the first leg of obtaining the device code, but would be great if it could support the token request. I suspect this may be as simple as adding DEVICE_CODE("urn:ietf:params:oauth:grant-type:device_code") to https://github.com/quarkusio/quarkus/blob/053cb7ce662a56830126aae31bc35d15d5d2543f/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/OidcClientConfig.java#L55.

**Comment by sberyozkin** [comment]
Hi Stian, @stianst, sure, yes, the dynamic parameters can be passed with the map, would you like to open a PR to add that enum value, I can help with adding a simple test ?

**Comment by sberyozkin** [comment]
@stianst I can do the whole PR a bit later as you already proposed the actual enum value, we can do it for Quarkus 3.9.0

**Comment by stianst** [comment]
@sberyozkin thanks, I did a quick draft PR for this

**Comment by col-panic** [comment]
Is there some helper code in `quarkus-oidc` that helps performing the first leg of obtaining the device code?
