### ISSUE TITLE
Check why Vert.x extension is depending on jboss-jaxrs-api_2.1_spec

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3907]
In `extensions/vertx/runtime/pom.xml`, we have a dependency to `jboss-jaxrs-api_2.1_spec`. We should check if it's really necessary and remove it if we can.

**Comment by gastaldi** [comment]
There are `javax.ws.rs.ext.MessageBodyReader`s and `javax.ws.rs.ext.MessageWriter`s implementations in https://github.com/quarkusio/quarkus/tree/master/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime that require that dependency

**Comment by gastaldi** [comment]
Since https://github.com/quarkusio/quarkus/pull/3924 was merged, I think this issue is safe to be closed?

**Comment by gsmet** [comment]
@gastaldi yup, thanks!
