### ISSUE TITLE
get rid of: [WARNING] [io.quarkus.config] Unrecognized configuration key

### ISSUE THREAD

**Issue by c-schmitz-tsystems** [quarkusio/quarkus#39077]
### Description

for a compact configuration property file (application.properties) it would be nice to extend already used sections with custom config keys. this is supported by quarkus but throws the following warning: [WARNING] [io.quarkus.config] Unrecognized configuration key ...

for example:

quarkus.restclient."myrestclient".mycustomproperty=myvalue

warning:

[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.restclient."myrestclient".mycustomproperty" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

this warning would make sense if the application is not intended for using such a key. so it would be nice, when the application can define its whish to extend already existing config sections with app specific config keys, like the extension do that introduced this section.

**Comment by c-schmitz-tsystems** [comment]
i wrote the supported section not correctly, sorry. its

quarkus.rest-client...

but it could be any other section f.i.

quarkus.cxf.client."myclient"...
quarkus.oidc-client."myclient"...

**Comment by gsmet** [comment]
Yes, the `quarkus.` namespace is reserved for Quarkus extensions. I don't think we would want to change that.

**Comment by c-schmitz-tsystems** [comment]
this is an academic reason. for pratical use its better to have for instance one section to fully configure a rest client and not spreaded it accross different sections. the large the app the worst it is. when the app can register its custom attributes as an extension to existing sections the warning can go away. the encapsulation of custom attributes in existing sections does already work.

**Comment by codespearhead** [comment]
> this is an academic reason. for pratical use its better to have for instance one section to fully configure a rest client and not spreaded it accross different sections. the large the app the worst it is. when the app can register its custom attributes as an extension to existing sections the warning can go away. the encapsulation of custom attributes in existing sections does already work.

I'm not sure I understand your point. There's probably a language barrier here.

Are you suggesting that there should be a way to pass arbitrary configuration properties? If so, you can't and you shouldn't be able to control the implementation of external packages. This would also render static checks less useful.

**Comment by c-schmitz-tsystems** [comment]
my english is not the best but i hope i can clarify it. i want to get rid of the warning "unrecognize config key ..." when i use application specific config keys in quarkus config sections. therefore my app should expose those custom config keys as valid so that the framework does not throw this warning anymore (think of it as an extension to existing config sections). there is no need to change anything in external dependencies. the beauty of this solution would be a much more compact configuration

**Comment by radcortez** [comment]
It is possible to extend the Quarkus configuration from the application side and add your own custom names for validation. For instance, you can add:

```java
@ConfigRoot(phase = ConfigPhase.RUN_TIME)
@ConfigMapping(prefix = "quarkus.rest-client")
interface RestClientConfig {
    @WithParentName
    Map<String, Custom> custom();

    interface Custom {
        @WithParentName
        Map<String, String> properties();
    }
}
```

And register `RestClientConfig` in a `META-INF/quarkus-config-roots.list` file.

You can then inject and access all your custom properties. The `Map` is greedy and will match anything under `quarkus-rest.client.*`. Ideally, you should provide a specific structure to your case.
