### ISSUE TITLE
Cannot open WebSocket with Sec-WebSocket-Protocol header in Quarkus version 3.7.1 and above with quarkus-websockets package

### ISSUE THREAD

**Issue by paolo-cutilli-eudata** [quarkusio/quarkus#39082]
### Describe the bug

After upgrading from Quarkus version 3.6.9 to 3.7.1 (and above) cannot use Sec-WebSocket-Protocol header in WebSocket handshake anymore.
I'm using _quarkus-websockets_ dependency

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-websockets</artifactId>
</dependency>
```

and providing a simple class annotated with ServerEndpoint annotation with `subprotocol` parameter

```
package org.acme;

import jakarta.enterprise.context.RequestScoped;
import jakarta.websocket.CloseReason;
import jakarta.websocket.OnClose;
import jakarta.websocket.OnError;
import jakarta.websocket.OnOpen;
import jakarta.websocket.Session;
import jakarta.websocket.server.ServerEndpoint;

@RequestScoped
@ServerEndpoint(value = "/ws", subprotocols = "custom-protocol")
public class SocketController {

    @OnOpen
    public void onOpen(Session socket) {
        System.out.println("Socket opened: " + socket.getId());
    }

    @OnError
    public void onError(Session socket, Throwable t) {
        System.out.println("Socket error: " + socket.getId() + " - " + t.getMessage());
    }

    @OnClose
    public void onClose(Session socket, CloseReason reason) {
        System.out.println("Socket closed: " + socket.getId() + " - " + reason.getReasonPhrase());
    }
}
```

Starting an instance on localhost listening on port 9999 and trying to open a WebSocket with the following headers

```
Request Headers:
    Sec-WebSocket-Version: 13
    Sec-WebSocket-Key: b8AIdJa6JU6639p8l6ksvQ==
    Connection: Upgrade
    Upgrade: websocket
    Sec-WebSocket-Protocol: custom-protocol
    Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
    Host: localhost:9999
```

produces the following results:

- With Quarkus version up to 3.6.9 the connection is successful and the response headers are
```
Response Headers
    sec-websocket-protocol: custom-protocol
    sec-websocket-location: ws://localhost:9999/ws
    sec-websocket-accept: UO7wLZQUzQFNeu16t2rdcauYHso=
    upgrade: WebSocket
    connection: upgrade
    content-length: 0
```

- With Quarkus version 3.7.1 and above the connection is denied and the response headers are
```
Response Headers
    upgrade: websocket
    connection: upgrade
    sec-websocket-accept: qvy6uu3bZV8FQoxVAQIsCer5128=
```

It seems that the use of `sec-websocket-protocol` is not supported anymore.

### Expected behavior

Opening a WebSocket with a Sec-WebSocket-Protocol header is accepted and the response headers contains the given `sec-websocket-protocol`

### Actual behavior

Passing a Sec-WebSocket-Protocol header in WebSocket headers does not permit to open a WebSocket in Quarkus version 3.7.1 and above

### How to Reproduce?

- Start a Quarkus instance with Quarkus version 3.7.1 or above able to handle WebSocket connections
- Try to connect a WebSocket with a Sec-WebSocket-Protocol header

Attachment
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/14446424/code-with-quarkus.zip)

With the provided project (Quarkus version 3.7.1 with `quarkus-websockets` dependency and ServerEndpoint annotated class)
- you can launch a local instance in dev mode with `quarkus dev -Dquarkus.http.port=9999`
- open a WebSocket at localhost:9999/ws adding `Sec-WebSocket-Protocol: custom-protocol` header

If you switch Quarkus version to 3.6.9 the WebSocket connection will be successful

### Output of `uname -a` or `ver`

Linux 5.15.0-97-generic #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

### Quarkus version or git rev

3.7.1 and above

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by sberyozkin** [comment]
I'm not seeing anything in https://github.com/quarkusio/quarkus/commits/main/extensions/websockets that might've caused it. @mkouba @cescoffier, please comment if you have some ideas

**Comment by mkouba** [comment]
@paolo-cutilli-eudata Hm, I've tried to connect to the endpoint using `new WebSocket("ws://" + location.host + "/ws", "custom-protocol")` in JS and it seems to work - I can even see the log message `Socket opened: abcdef...` in the console. In fact, the protocols paremeter seems to be ignored completely. I don't know if that's expected though, in the sense that the server can fall back to the default protocol if no matching protocol is found. 

By the way, I don't think that `@RequestScoped` is a good match for a `jakarta.websocket` server endpoint. The spec does not say anything about CDI contexts so I'd say that `@ApplicationScoped`/`@Dependent` would be a "safer" choice.

**Comment by mkouba** [comment]
Hm, I do not observe this behavior :shrug:.

> is there additional information that i can give you so that you can reproduce the problem?

I can't think of anything.

**Comment by paolo-cutilli-eudata** [comment]
@mkouba I gathered some other interesting information. The same test described above works in Firefox.
From Chrome it does not work. I tried Postman WebSocket also and it does not work from there. I have Postman installed as a snap package on Ubuntu that i think it's based on electron/chromum engine. Do you think that this can be useful to circumscribe the problem?

**Comment by mkouba** [comment]
> @mkouba I gathered some other interesting information. The same test described above works in Firefox. From Chrome it does not work. I tried Postman WebSocket also and it does not work from there. I have Postman installed as a snap package on Ubuntu that i think it's based on electron/chromum engine. Do you think that this can be useful to circumscribe the problem?

It might be related. On the other hand, I've tried with Chromium (Version 122.0.6261.94 (Official Build) snap (64-bit)) and it worked just fine.

**Comment by paolo-cutilli-eudata** [comment]
> > @mkouba I gathered some other interesting information. The same test described above works in Firefox. From Chrome it does not work. I tried Postman WebSocket also and it does not work from there. I have Postman installed as a snap package on Ubuntu that i think it's based on electron/chromum engine. Do you think that this can be useful to circumscribe the problem?
> 
> It might be related. On the other hand, I've tried with Chromium (Version 122.0.6261.94 (Official Build) snap (64-bit)) and it worked just fine.

Same configuration - Version 122.0.6261.94 (Official Build) snap (64-bit) - throws me this error

![image](https://github.com/quarkusio/quarkus/assets/161705180/f2b880a9-9d2c-492f-80ed-ed83126d607e)

**Comment by mkouba** [comment]
@sberyozkin Could you pls run this ^ test too?

**Comment by istosSchulz** [comment]
We have the exact same issue after upgrading to Quarkus 3.8.1. We downgraded to 3.6.7 to get it working. The upgrade to 3.7.1 seems to be the one that breaks it.
Same errors and behaviour. Our custom protocol is called differently but the issue seems to be the same. @OnOpen is called seemingly successful and immediately afterwards @OnClose is called. The client (Postman) reports "Error: Server sent no subprotocol".

**Comment by cescoffier** [comment]
It is likely due to:

- https://github.com/quarkusio/quarkus-http/commit/805bb3f4ce9d8779bf43ea6443ce88c49dd563cf

**Comment by cescoffier** [comment]
Confirmed - See https://github.com/quarkusio/quarkus-http/pull/143.
