### ISSUE TITLE
OOMs and performance degradation after updating quarkus from 3.6.8 to 3.7.1 due to changed default jvm flags. 

### ISSUE THREAD

**Issue by u6f6o** [quarkusio/quarkus#39084]
### Describe the bug

After we migrated from quarkus `3.6.8` to `3.7.1`, we experienced a lot of OOMs in our production environment. It did not affect all of our applications but especially those that have an unstable load pattern (e.g. experiencing load peaks at a certain time of the day). 

We experienced these problems in the past as well (~1 year ago) and found out that these OOMs were caused by the resizing of the committed heap. To address this issue we added the `-XX:InitialRAMPercentage` jvm flag and kinda forced the jvm to occupy a larger amount of the available heap per default. 

Regretfully this flag dos not work any more in the `3.7.1` version. As you can see in the following screenshot (`3.6.1` and `3.7.1`next to each other),  the jvm only commits to a very small portion of the available heap: 

![image](https://github.com/quarkusio/quarkus/assets/1176370/d610846f-2403-4ca6-b350-b8b41c4a0878)

Further investigation revealed that the default jvm flags for the newer version have been changed: 

**3.7.1**
```
-XX:MaxRAMPercentage=80.0
-XX:+UseParallelGC
-XX:MinHeapFreeRatio=10
-XX:MaxHeapFreeRatio=20
-XX:GCTimeRatio=4
-XX:AdaptiveSizePolicyWeight=90
-XX:+ExitOnOutOfMemoryError
```
**3.6.8**
```
```

I also discussed this issue with @geoand and @jmtd in zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/JVM.20flag.20changes.20from.203.2E6.2E8.20to.203.2E7.2E3.3F/near/423765621

Imho, these settings are too invasive to be used as a default. If these settings are considered as a good default for the vast majority of the quarkus users, it would be nice to have them documented somewhere (preferably also in the migration guide) and to offer an option to turn these on or off. 

### Expected behavior

There are no pre-set jvm flags provided as before. 

### Actual behavior

The following jvm flags are set with 3.7.1 and onwards: 
```
-XX:MaxRAMPercentage=80.0
-XX:+UseParallelGC
-XX:MinHeapFreeRatio=10
-XX:MaxHeapFreeRatio=20
-XX:GCTimeRatio=4
-XX:AdaptiveSizePolicyWeight=90
-XX:+ExitOnOutOfMemoryError
```

### How to Reproduce?

1. Clone https://github.com/u6f6o/jvm-flag-changes
2. `git checkout quarkus-3.6.8`
3. `./gradlew clean build -Dquarkus.container-image.build=true && cd build && docker run $(cat jib-image.id)`
4. Check the log line starting with `INFO  [org.acm.GreetingResource] (main) JVM flags:`
5. Apply steps 2 - 4 for the branch quarkus-3.7.1 

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.5 ------------------------------------------------------------  Build time:   2023-11-29 14:08:57 UTC Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598  Kotlin:       1.9.20 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          17.0.9 (Homebrew 17.0.9+0) OS:           Mac OS X 12.6 aarch64

**Comment by geoand** [comment]
@jmtd I wonder if the choice for these flags needs to be revisited. 

I'll cc @franz1981 in this discussion as well as he likely has plenty of knowledge to contribute

**Comment by u6f6o** [comment]
I forgot to share one thought in my initial post: According to my current knowledge, the jvm flags are put into a `Properties` object (thus a HashSet underneath) which means that the last flags provided wins (e.g. `-XX:MaxRAMPercentage=80.0, -XX:MaxRAMPercentage=40.0` would lead to `-XX:MaxRAMPercentage=40.0`. (We currently try to reset the defaults by providing custom jib jvm flags). 

I don't know though, which rules apply to"switchable" flags, like `-XX:+ExitOnOutOfMemoryError,-XX:-ExitOnOutOfMemoryError`. Does `-` or `+` win in such a case? Kind of the same situation if we want to use a different GC.

**Comment by franz1981** [comment]
> We experienced these problems in the past as well (~1 year ago) and found out that these OOMs were caused by the resizing of the committed heap

Can you share more about this instead? G1 can return back heap memory (uncommitted) enabling periodic GCs, but I didn't hear anything about OOM cause by such. Are you mentioning OOM at java level or due to OS OOM killer?

**Comment by u6f6o** [comment]
@franz1981 I am no expert on this topic bus this is one of the applications that ran into an OOM: 
![image](https://github.com/quarkusio/quarkus/assets/1176370/0e8917b4-86dd-4028-9f65-5ab7683ac147)
The jvm started with the desired committed heap (`InitialRAMPercentage`) but after at while it was shrinked. I found this on a redhat blog post: 
![image](https://github.com/quarkusio/quarkus/assets/1176370/0a39fc45-e363-4f91-b0f5-45a2aae46084)
Source: https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers

>  Are you mentioning OOM at java level or due to OS OOM killer?

OOM on java level

**Comment by u6f6o** [comment]
We went for a workaround that resets the new jvm flags to their defaults: 

![image](https://github.com/quarkusio/quarkus/assets/1176370/b9b2ce90-8cbf-41c2-b0c3-c2d334ce7895)

The OOMs are gone now and our quarkus applications run smoothly again as they did before the quarkus update to 3.7 happened.

**Comment by u6f6o** [comment]
@geoand : but why did you close it? Just because we found a workaround, this is still a bug imho? Up to my understanding, quarkus is supposed to run in different scenarios like typical every day joe webservers as well as heavy lifting batch jobs? Choosing a parallelGC and a very offensive heap shrinking behaviour as default is a very bad approach especially for the later one imo.

**Comment by geoand** [comment]
I'll leave it up to @franz1981 to decide

**Comment by coolersham** [comment]
@franz1981 what is the status of this?
