### ISSUE TITLE
quarkus-documentation rendering into a source directory

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#3909]
**Describe the bug**
The `quarkus-documentation` project is generating the docs into `docs/src/main/asciidoc`.  It should be generating into `docs/target/...`.  It's just a matter of time before a PR includes the generated files by accident.

**To Reproduce**
Do a clean build.

**Comment by gsmet** [comment]
The directory is part of the .gitignore so I'm not sure there is a real problem regarding PR.

I agree it's not ideal but we need them to be there for the includes to work.

**Comment by dmlloyd** [comment]
Hmm it didn't seem to ignore for me even though my checkout is up to date.  Will investigate further.

We can't use e.g. `docs/target/generated-sources/asciidoc` or something?  I guess it's an asciidoctor config problem of some sort?

**Comment by gsmet** [comment]
We could maybe make it work by having an attribute for the generated path.
I need to check if I can make it work with the website too.

I'll dig a bit further. I agree the current situation is not ideal.

**Comment by machi1990** [comment]
> Hmm it didn't seem to ignore for me even though my checkout is up to date. Will investigate further.
> 

 
We have a `.gitignore` entry for generated docs. I am curios to what might have went wrong.

**Comment by gsmet** [comment]
For the record, it's not possible to put things in `docs/target` as it gets cleaned up before generating the doc on `mvn clean install` so I moved things to the global `target/` directory.
