### ISSUE TITLE
Support CAST to enable substring searching on numeric fields

### ISSUE THREAD

**Issue by tmulle** [quarkusio/quarkus#39112]
### Description

We have a requirement from a legacy application to let the end users search a numeric field in the database using a partial search.

So, they find records by serial number as either: `%17%` or the full `17890`

I tried the following code using Panache after looking online about CAST keyword, but sadly it didn't work.

Would it be possible to add this keyword support? I have converted the application to use Panache Repository and would like to keep the jumping out to `entityManager.createQuery` to a minimum, especially since I also need to support Paging, Filtering, and Sorting. 

Tried this and it failed:

```
query = registrationRepo.find("from RegistrationEntity r CAST(r.serialNumeric as text) LIKE :filter", sorting,
                        Parameters.with("filter", "%" + filter + "%"));
``` 

Error:
```
java.lang.IllegalArgumentException: org.hibernate.query.SyntaxException: At 1:26 and token 'CAST', mismatched input 'CAST', expecting one of the following tokens: <EOF>, ',', CROSS, FULL, GROUP, INNER, JOIN, LEFT, ORDER, OUTER, RIGHT, SELECT, WHERE [from RegistrationEntity r CAST(r.serialNumeric as text) LIKE :filter ORDER BY registrationDate DESC NULLS FIRST]
```

**Comment by luca-bassoricci** [comment]
Where keyword should be optional if query starts with a condition. In this case I suppose where must be present

**Comment by tmulle** [comment]
Ok thanks. You were right, I got the query to work with the following. I added the WHERE clause.

```
query = registrationRepo.find("from RegistrationEntity r WHERE CAST(r.serialNumeric as text) LIKE :filter", sorting,
                        Parameters.with("filter", "%" + filter + "%"));
```

I will close this ticket since it is working and it was my bad query.
