### ISSUE TITLE
Difficulties running native tests with Quarkus and gradle

### ISSUE THREAD

**Issue by mnguetsa** [quarkusio/quarkus#39110]
### Describe the bug

It is not clear at all how to run native (@QuarkusIntegrationTest) with gradle. 
I read the following documentations and still couldn't understand how it is supposed to be done:
https://quarkus.io/guides/building-native-image#testing-the-native-executable
https://quarkus.io/guides/getting-started-testing#native-executable-testing

So far I run the following to build the native application:  `./gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true` . It runs the normal @QuarkusTests, builds the native application but does not run the integration tests

How to trigger integration/native tests I have under native-test/**IT.java so they run against the native application that was just built.

I really cannot see how to do it with gradle in the quarkus docs. 
My goal overall is basically :

- run my normal tests and build the native image
- run integration tests against that image

Thanks a lot

This can all be reproduced by downloading the gradle getting started application as it already has some native test. Those commands (./gradlew testNative, ./gradlew quarkusIntTest) don't work already with that application. https://quarkus.io/guides/getting-started#bootstrapping-the-project

_No response_

### Output of `java -version`

21

### Quarkus version or git rev

3.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.5

**Comment by galderz** [comment]
https://quarkus.io/guides/gradle-tooling#running-native-tests ?

**Comment by mnguetsa** [comment]
@galderz I tried those as well. Did not work as expected. 

- When I run `./gradlew testNative` first I get                                                                                        

`The Quarkus tasks testNative and buildNative are deprecated and subject to removal. Please migrate your build to use 'test -Dquarkus.package.type=native' and 'quarkusBuild -Dquarkus.package.type=native'.`
Moreover my test in native-test folder which is annotated with @QuarkusIntegration test is not even run. 

- When I run ./gradlew quarkusIntTest it runs my normal tests. It does not attempt the build the native image it does not run the integration tests at all even though the name suggest it is for integration tests.

Somehow all this is very confusing to me in the doc and so far I could not find something that works using gradle. 

This can all be reproduced by downloading the gradle getting started application as it already has some native test. Those commands don't work already with that application. https://quarkus.io/guides/getting-started#bootstrapping-the-project

**Comment by mnguetsa** [comment]
Hi @galderz thanks that works with `./gradlew build testNative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true`
However for my understanding what does `./gradlew quarkusIntTest`  do?
 It did not work for me. I am wondering whether it shouldn't be removed or fixed in the [doc](https://quarkus.io/guides/gradle-tooling#running-native-tests)

**Comment by galderz** [comment]
> However for my understanding what does `./gradlew quarkusIntTest` do? It did not work for me. I am wondering whether it shouldn't be removed or fixed in the [doc](https://quarkus.io/guides/gradle-tooling#running-native-tests)

Looking at the `quarkusIntTest` docu in that guide, it says that the tests should be in `src/integrationTest/java` and the getting started code does not have that folder.

If you look at the Quarkus testsuite, https://github.com/quarkusio/quarkus/blob/main/integration-tests/gradle/src/test/java/io/quarkus/gradle/IntegrationTestBuildTest.java is the test that exercise this, and https://github.com/quarkusio/quarkus/tree/main/integration-tests/gradle/src/main/resources/it-test-basic-project is the project that is being tested. In that project you can see a test within that folder structure https://github.com/quarkusio/quarkus/blob/main/integration-tests/gradle/src/main/resources/it-test-basic-project/src/integrationTest/java/org/acme/ExampleResourceIT.java

**Comment by mnguetsa** [comment]
Sorry @galderz for the later feedback. I wanted to try everything you wrote out. Your answer helped me a lot. I was able to create a nice integration tests suite using the quarkusIntegration test annotation and run it as a gradle task with `quarkusIntTest`.
