### ISSUE TITLE
[Extension Proposal] - Mongock MongoDB database migrations during Quarkus startup

### ISSUE THREAD

**Issue by janknobloch** [quarkusio/quarkus#39111]
### Description

Hey, just build an extension at work using mongock v5 (https://mongock.io) and could provide it towards quarkiverse / quarkusio if there is any interest.

it needs bit of polishing I guess, that said it contains basic health checks and config params to enable/disable the whole extension and its health checks. 

For now it supports the default MongoDB client (not multi tenant, yet) and uses an underlying MongoDB sync driver for doing so.

Since it's my first official extension offered/proposed some review / feedback round would be appreciated. 😄 

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-mongodb-mongock

### Short description

Allows mongock database migrations for MongoDB to be executed during Quarkus startup

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-mongodb-mongock/dev/

### Repository Topics

- quarkus-extension
- mongodb
- mongock
- database migration

### Team Members

@janknobloch

**Comment by loicmathieu** [comment]
We already have [Liquibase MongoDB](https://quarkus.io/guides/liquibase-mongodb) for such use cases in the Quarkus repository.
But it could be a great addition inside the Quarkiverse as not everybody would be happy with what Liquibase provides.

**Comment by janknobloch** [comment]
Hey,
my 2 cents on the liquibase integration:

Liquibase is seemingly strongly focussed on sql compared to mongodb. 
Even claiming they support mongodb Is quite statement to me - looking at the community version.

Liquibase offers MongoDB support using the Pro using mongosh / or driver syntax for that matter.
Whereas the open source extension basically does not allow for anything "useful" in the sense of db migrations despite wrapping all your commands around the MongoDB.runCommand(), next to createCollection, dropCollection and insertOne, and creating indexes. ( see : https://github.com/liquibase/liquibase-mongodb)

So basically you can not use mongsh syntax and or typical change / update statements for that matter using liquibase-mongodb while you can if using liquibase with sql.

At least I dropped liquibase as one can not simply do e.g:

`db.collection.updateMany(cond,action); `

including a proper rollback function with:
`db.collection.updateMany(cond,action); 

without opting for the pro version or wrapping / reformatting your syntax into runCommands as seen here:
https://github.com/liquibase/liquibase-mongodb/issues/290

But maybe im wrong, lets see if anyone else stumbles across this post and agrees / disagrees, who tried to solve mongo migrations using liquibase.

**Comment by gastaldi** [comment]
@janknobloch https://github.com/quarkiverse/quarkus-mongock was created and you were given the permissions to maintain it. Enjoy!

Here is what you need to do to have your extension visible in the Quarkus tooling and tested against the latest Quarkus changes: 
https://hub.quarkiverse.io/checklist/#after-the-repository-is-created

**Comment by tms0** [comment]
Hi @janknobloch,

I'm working on a Mongock extension too. I'm curious how you make Mongock working with Quarkus, on my side there is a classloader issue (see https://github.com/mongock/mongock/issues/663).

Do you think you will push your code soon ?

**Comment by tms0** [comment]
Hi @gastaldi,

With no news from @janknobloch, do you think you can give me the permissions to maintain the created repository ?
I have a fully functional extension, and I would be proud to bring my contribution to the community.

**Comment by janknobloch** [comment]
hey @tms0 ,
did you solve the sub dependency issue between the quarkus bom and the needed org.reflections library bug so its not needed to force projects using the extension to have a separate dependency of org.reflections 0.10.1 in place?

i was still boggling my mind around it on how to fix this issue.

@gastaldi gladly give ownership / permissions to @tms0.

**Comment by janknobloch** [comment]
thx for addressing this so quickly @gastaldi .

i pushed all my code @tms0 , currently there seems to be an issue for the native pipeline, the rest should work fine with the mentioned limitation, (in some cases) depending on the sub dependencies pulled into the quarkus project.

**Comment by tms0** [comment]
Hi,

@gastaldi Thank you for giving me the ownership :-)
@janknobloch I will submit a PR to make the extension working in native executables.

**Comment by janknobloch** [comment]
@gastaldi sorry to bother again, after a discussion with @tms0 , he decided to take over the extension, as we have different views on how how it should run and what it should support. 

since im not using the extension he offered maintaining it as he will also actively use it.

so feel free to remove me from the maintainers, I gladly send a PR if needed.

**Comment by gastaldi** [comment]
@janknobloch sure, if you could send a PR to the quarkiverse-devops repo that would be great (you should have access to create a branch in the repository, don't use a fork)

**Comment by janknobloch** [comment]
@gastaldi sure - said an done. :-)

**Comment by gastaldi** [comment]
Merged, goodbye @janknobloch, it was a fun ride! 😀
