### ISSUE TITLE
Unable to produce multiple synthetic beans of same type having different identifiers

### ISSUE THREAD

**Issue by dcdh** [quarkusio/quarkus#39169]
### Describe the bug

I am producing multiple synthetic beans of same type without qualifier.
I am using the identifier to distinct them.

```java
@BuildStep
    @Record(ExecutionTime.STATIC_INIT)
    List<SyntheticBeanBuildItem> registerJdbcLockProviderInitializer(
            final ApplicationIndexBuildItem applicationIndexBuildItem,
            final DataSourceNameRecorder dataSourceNameRecorder) {
        final List<String> dataSourceNames = getDataSourcesNameFromJdbcSchedulerLocks(applicationIndexBuildItem);
        List<SyntheticBeanBuildItem> list = dataSourceNames.stream()
                .map(dataSourceName -> SyntheticBeanBuildItem.configure(DataSourceName.class)
                        .scope(Singleton.class)
                        .identifier(dataSourceName)
                        .supplier(dataSourceNameRecorder.dataSourceNameSupplier(dataSourceName))
                        .unremovable()
                        .done())
                .toList();
        return list;
    }
```

When running my integration test on **integration-tests** / **jdbc** it fails - while two synthetic beans are produced having **\<default\>** and **master** identifier - about already registered bean with same identifier.

```
[ERROR] Errors: 
[ERROR]   SchedulerLockResourceTest.testShedlockEndpoint » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.SyntheticBeansProcessor#initStatic threw an exception: java.lang.IllegalStateException: A synthetic bean with identifier ouqbYaizsnxlxh2wrovrwNxvSIQ is already registered: SYNTHETIC bean [types=[io.quarkiverse.shedlock.providers.jdbc.runtime.DataSourceName, java.lang.Object], qualifiers=[@Default, @Any], target=n/a]
        at io.quarkus.arc.processor.BeanDeployment.addSyntheticBean(BeanDeployment.java:1472)
```

### Expected behavior

Two Synthetic beans should be produced and injected inside **JdbcLockProviderInitializer**

### How to Reproduce?

1. git clone https://github.com/dcdh/quarkus-shedlock
2. mvn clean install

### Output of `uname -a` or `ver`

Linux 2a02-8428-dff8-c601-234b-8c10-a3c4-2308.rev.sfr.net 6.6.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 10 19:25:59 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (Red Hat 3.9.1-3)

**Comment by mkouba** [comment]
Indeed, there is a bug in the `BeanConfiguratorBase.read(BeanConfiguratorBase<?, ?>)` method - the `identifier` is not copied from the original configurator. This method is used when processing `SyntheticBeanBuildItem`s.

A workaround is to use the `BeanRegistrationPhaseBuildItem` directly in the build step, i.e. `beanRegistration.getContext().configure(...)`.
