### ISSUE TITLE
AudioSystem.getMixerInfo return empty array when running desktop application with quarkus framework in JVM Mode with Quarkus.run method

### ISSUE THREAD

**Issue by ITrium-Salah** [quarkusio/quarkus#39183]
### Describe the bug

I am adding to a JavaFX application, running with Java 21, the quarkus framework to improve code maintainability and and to take advantage of the CDI arc system, rest-client, graphql, ... My application was working fine until  I realized that a central and very stable part of the application stopped working. In fact, the application uses the audio output and the microphone of the Windows system. However the AudioSystem.getMixerInfo function return an empty array. It seem that the Audio Providers  are not accessible after the Quarkus.run call although the java.desktop package is available in the JDK.

Quarkus is run via the main method with:
```
@QuarkusMain
public class App{
    public static void main(String[] args)
    {
        Mixer.Info[] mixerInfo = AudioSystem.getMixerInfo(); //<- Work fine
        System.err.println(Arrays.toString(mixerInfo)); //Correctly list mixer info (can access dataline, mixerinfo, audioclip etc...
        Quarkus.run(QuarkusApp.class,(i,throwable)->{]);
    }
}

public class QuarkusApp implements QuarkusApplication{
    public int run(final String ...args)
    {
        Mixer.Info[] mixerInfo = AudioSystem.getMixerInfo(); //<- Empty array
        System.err.println(Arrays.toString(mixerInfo)); //At this point exception NoSuchMethod for Audio.getClip or error accessing dataline  mixerinfo, audioclip etc...
        Application.launch(FXApplication.class,args);//Launch FX App
        return 0;
    }
}
```
After the call of Quarkus.run i can't access the AudioSystem from anywhere in the code.

### Expected behavior

AudioSystem.getMixerInfo should return the available mixer of the system and the service providers in java.desktop package should be available to the app

### Actual behavior

AudioSystem.getMixerInfo return an empty array. (Working without quarkus framework with spring-boot or without framework)

### How to Reproduce?

see bug description

### Output of `java -version`

21.0.2

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.5

### Additional information

I try with intellij, maven, etc..

**Comment by geoand** [comment]
Without debugging this on Windows, it's impossible to know what the problem is...

**Comment by ITrium-Salah** [comment]
When debugging with breakpoint step by step it seems that  no Service Provider for Mixer are registred or accessible on the classpath. I don't know how quarkus manage the classpath and how it clash with JavaFX. Without JavaFX the AudioSystem work fine. I was able to find a workaround.
Adding in the pom a dependency which include ServiceProvider for AudioSystem:
```
<dependency>
    <groupId>com.googlecode.soundlibs</groupId>
     <artifactId>tritonus-share</artifactId>
     <version>0.3.7.4</version>
</dependency>
```

**Comment by geoand** [comment]
Interesting, thanks for the update

**Comment by ITrium-Salah** [comment]
I don't know if it's worth it for me to create a minimal javafx project to reproduce the bug and share it?

**Comment by geoand** [comment]
Well, I definitely won't be able to debug it for lack of a Windows machine.

**Comment by CodeSimcoe** [comment]
@ITrium-Salah 
Have you tried using quarkus-fx extension ?

Made a quick test, no issue retrieving data with MixerInfo()

![image](https://github.com/user-attachments/assets/1e85a1ce-533a-4c8f-80e2-3358fdb9e81b)

![image](https://github.com/user-attachments/assets/aee5c037-c37c-454e-9e80-e23b1b53feae)

**Comment by ITrium-Salah** [comment]
@CodeSimcoe this extension look really interesting, in fact i had to implement the same features (@OnFxThread, CDI override, ...). I will have a look on it and test (removing the goodle sound lib) for the audio mixer trouble.

**Comment by dmlloyd** [comment]
It probably has something to do with the difference between the application class loader and the Quarkus class loader being set as the TCCL.

You could try something like this for a workaround:

```java
ClassLoader old = Thread.currentThread().getContextClassLoader();
Thread.currentThread().setContextClassLoader(null);
try {
    mixerInfo = AudioSystem.getMixerInfo();
} finally {
    Thread.currentThread().setContextClassLoader(old);
}
```

**Comment by ITrium-Salah** [comment]
It seem that the bug is not present after the release 3.9.2, i have removed the googlesoundlib from my dependencies and i have access to the mixerinfo. No need to set the classloader or use the quarkus-fx extension.
I don't know the changes made by the latest release but no bug anymore (i have upgrade to 3.12 and no bug).

**Comment by ITrium-Salah** [comment]
I close the issue, the bug si not present on the latest releases
