### ISSUE TITLE
JAX-RS sub resource is not gererated in OpenAPI schema

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#3918]
I mounted the subresource in the parent resource like this:

```java
public class PostResource{
    //other methods are omitted here.
    
   @Path("{id}/comments")
    public CommentResource commentResource() {
        return resourceContext.getResource(CommentResource.class);
    }    

}
```
The details of this issue can be found on stackoverflow:
https://stackoverflow.com/questions/57830712/jax-rs-sub-resource-is-not-generated-in-quarkus-openapi-schema

**Comment by emmanuelbernard** [comment]
Related to https://github.com/quarkusio/quarkus/issues/3919

**Comment by machi1990** [comment]
Fixed by https://github.com/smallrye/smallrye-open-api/pull/190. We'll need an upgrade once there is a new smallrye release to fix the issue.

**Comment by gsmet** [comment]
This one should be fixed by now.
