### ISSUE TITLE
JAX-RS sub resource is not recognised in Quarkus

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#3919]
Register sub resource in the parent resource.

```java
public class PostResource{
    //other methods are omitted here.
    
   @Path("{id}/comments")
    public CommentResource commentResource() {
        return resourceContext.getResource(CommentResource.class);
    }    
} 
```
`CommentResource` is like this, it does not includ a `@Path`.

```java
@RequestScoped
public class CommentResource {}
```

The details and workaround can be found on stackoverflow.
https://stackoverflow.com/questions/57820428/jax-rs-subresource-issue-in-quarkus

**Comment by geoand** [comment]
@gsmet, @mkouba IIRC you were talking about this, right?

**Comment by mkouba** [comment]
@geoand Yep, exactly.
