### ISSUE TITLE
Add Jakarta/Java EE  8 Security Spec support

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#3920]
I am not sure if possible to add Security Spec 1.0 support in Quarkus.

I browsed the quickstarts samples, currently in the JAX-RS Resource, the `SecurityContext` from Jaxrs, but if I want to use SecurityContext in other places, such as Domain Service codes  JPA codes,  Security Spec 1.0 specific `SecurityContext` is a good option.

Or is there some approaches to transfer a `SecurityContext` like Bean through `Context Propagation`(supports Sync, Async, and Reactive Context) ?

**Comment by sberyozkin** [comment]
Hi, 
In Thorntail we had it supported by depending on the [WildFly features](https://github.com/thorntail/thorntail/blob/master/fractions/javaee/ee-security/module.conf).
I think having an extension to have the EE Security optionally supported would be good, but things are changing right now in the Quarkus security, so I don't think depending on the PicketBox for example is an option, but hopefully there will be a way to pull in some newer WildFly code without having to depend on PicketBox.
@stuartwdouglas, hi Stuart, FYI
+1 to this enhancement request.

**Comment by stuartwdouglas** [comment]
We will have a very similar bean called SecurityIdentity: https://github.com/quarkusio/quarkus-security/blob/master/src/main/java/io/quarkus/security/identity/SecurityIdentity.java

**Comment by sberyozkin** [comment]
Nice, can be a much lighter alternative

**Comment by gsmet** [comment]
@stuartwdouglas is this one considered fixed then?

**Comment by stuartwdouglas** [comment]
Not really. We will likely never support the full spec as it is tied to JASPIC but there are parts of it we may want to implement in future.

**Comment by hantsy** [comment]
Quarkus Security is accepted now, but I think it should be compatible with the existing security context, such as jaxrs `SecurityContext`, etc.  

Additionally, besides the annotation aware security declaration, if possbile provide a central place to configure security by Http path matching, WebSocket routing, etc.  like the solution in Spring security's [`WebSecurityConfigurer`](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/WebSecurityConfigurer.html), and PicketBox's [`ConfigurationBuilderProvider` ](https://docs.jboss.org/author/display/SECURITY/Configuration)

**Comment by stuartwdouglas** [comment]
You can provide a io.quarkus.vertx.http.runtime.security.HttpSecurityPolicy CDI bean that allows you to add custom permission checks

**Comment by geoand** [comment]
I am going to close this as for one there has been very little request for it while Quarkus Security provides a lot of different options
