### ISSUE TITLE
Inconsistent config behavior across Quarkus nested tests

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#39229]
### Describe the bug

I'm writing nested tests for my Quarkus main method. In each nested test i override the config but the problem is that other tests see the changed config when it shouldn't.

In the following class the `MainTest#testMain` and `Inner2Test#testMain` work as expected but the `Inner#testMain` fails since the `Inner2Test` change the config.

If you run each individual test from the IDE they do work, in order to reproduce it you have to run the whole test (MainTest.java) or simple run `mvn test`.

I have created a reproducer [here](https://github.com/gbourant/main-test).

```java
@QuarkusMainTest
class MainTest {

    @Nested
    @TestProfile(Inner.MyTestProfile.class)
    class Inner {

        public static class MyTestProfile implements QuarkusTestProfile {
        }

        @Test
        @Launch(value = {}, exitCode = 0)
        public void testMain() {
        }
    }
    @Nested
    @TestProfile(Inner2Test.MyTest2Profile.class)
    class Inner2Test {

        public static class MyTest2Profile implements QuarkusTestProfile {

            @Override
            public Map<String, String> getConfigOverrides() {
                return Map.of("project.required", "false");
            }

        }

        @Test
        @Launch(value = {}, exitCode = 1000)
        public void testMain() {
        }
    }

    @Test
    @Launch(value = {}, exitCode = 0)
    public void testMain() {
    }
}
```

**Comment by gbourant** [comment]
After further investigation, the problem is not just in the `getConfigOverrides` but it expands to the `getEnabledAlternatives` method (maybe other methods too ?).

It seems that when a class implements QuarkusTestProfile which overrides the default values (getEnabledAlternatives/getConfigOverrides/etc) they are not isolated to the current test but they are visible to other tests.

**Comment by gbourant** [comment]
If i put each nested class to each own file then the tests are working fine, it has nothing to do with `getConfigOverrides` or `getEnabledAlternatives` rather than `@Nested`.

**Comment by gbourant** [comment]
This might got fixed by https://github.com/quarkusio/quarkus/issues/44117 (I did not try it)

**Comment by gsmet** [comment]
Indeed, the reproducer passes with 3.17.5, closing!
