### ISSUE TITLE
e quarkus-azure-functions-http  generationg function.json with missing method.

### ISSUE THREAD

**Issue by jelmew** [quarkusio/quarkus#39242]
### Describe the bug

When following the guide https://quarkus.io/guides/azure-functions-http
, we expect a function.json to be created containing the methods called in the code.

### Expected behavior

A working guide with a function.json containing a GET method.

### Actual behavior

A function.json missing methods is created. That means that while running this, either using quarkus:run or on azure, the method is non responsive.

```
cat function.json 
{
  "scriptFile" : "../code-with-quarkus-1.0.0-SNAPSHOT.jar",
  "entryPoint" : "io.quarkus.azure.functions.resteasy.runtime.Function.run",
  "bindings" : [ {
    "type" : "httpTrigger",
    "direction" : "in",
    "name" : "req",
    "route" : "{*path}",
    "methods" : [ ],
    "dataType" : "binary",
    "authLevel" : "ANONYMOUS"
  }, {
    "type" : "http",
    "direction" : "out",
    "name" : "$return"
  } ]

```

### How to Reproduce?

1.  Run quarkus create app --extension=quarkus-azure-functions-http
2. Run quarkus build && quarkus run.

See that the hello-world is unreachable.

### Output of `uname -a` or `ver`

Linux pop-os 6.6.10-76060610-generic #202401051437~1709085277~22.04~31d73d8 SMP PREEMPT_DYNAMIC Wed F x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.10" 2024-01-16 OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7) OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment]
This seems to be the result of ##38923

**Comment by kdubois** [comment]
I can confirm this is still an issue in 3.8.2. 

`quarkus run` or deploying the function to azure functions with `quarkus deploy` will effectively push the function but you'll get a 404 due to the 'methods' field having an empty value in the generated function.json file.   When I remove this field altogether it works again.

**Comment by geoand** [comment]
Right, we need https://github.com/quarkusio/quarkus/pull/39252 - cc @patriot1burke

**Comment by jelmew** [comment]
Backport to the lts version perhaps?  It's broken in 3.8 now.

**Comment by geoand** [comment]
Yup, that's the point of the labels on #39252 :)

**Comment by jelmew** [comment]
> Yup, that's the point of the labels on #39252 :)

I've said nothing. :)

**Comment by geoand** [comment]
😄
