### ISSUE TITLE
Improve track-config-changes performance by delegating dependencies fingerprinting to the Develocity extension

### ISSUE THREAD

**Issue by jprinet** [quarkusio/quarkus#39256]
### Description

This [PR](https://github.com/quarkusio/quarkus/pull/37622) introduced the `target/quarkus-<profile-name>-dependency-checksums.txt` file which contains the list of Quarkus extra dependencies brought during a Quarkus `build`.
This file is used in the context of caching.
For `SNAPSHOT` versions, a fingerprint is computed to be able to track differences among builds.

This fingerprinting would actually be more naturally handled by the [Develocity Maven extension](https://docs.gradle.com/enterprise/maven-extension/).
In details, the Quarkus build caching capability is brought by the [Quarkus Maven build caching extension](https://github.com/gradle/develocity-build-config-samples/tree/main/quarkus-build-caching-extension).

This extension is already ready to integrate the fingerprinting currently handled by the Quarkus Maven plugin since [this PR](https://github.com/gradle/develocity-build-config-samples/pull/1078).

The required changes are:
- list dependencies with absolute path
- create a file named `target/quarkus-<profile-name>-dependencies.txt`

**Comment by jprinet** [comment]
cc @aloubyansky

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/41482 to address this.

**Comment by gsmet** [comment]
@jprinet I also created https://github.com/quarkusio/quarkus-project-develocity-extension/pull/32 if you want to have a look?
