### ISSUE TITLE
Quarkus Kogito code generator plugin still using javax

### ISSUE THREAD

**Issue by deepakkapoor23** [quarkusio/quarkus#39273]
### Describe the bug

The generated kogito source classes under target can be seen to have javax annotation and enterprise usage which is no longer available at runtime in Quarkus 3
Is this a known issue? Are there any plans to update the plugin to start using Jakarta packages instead?
The workaround is to revert to Quarkus version 2.16.12.Final which still uses javax

Quarkus maven plugin version - 3.8.1
Quarkus version - 3.8.1
Kogito version - 1.43.0.Final
JDK 17

**Comment by mariofusco** [comment]
This has been already fixed in the drools and kogito main branches and will be available with the upcoming 10.0.x releases.

**Comment by deepakkapoor23** [comment]
Thanks Mario.
Can you please clarify, which component/module is that and what's the timeline for release 10.0?

**Comment by mariofusco** [comment]
All drools and kogito modules have been migrated to Quarkus 3 and jakarta namespace on their main branches. We don't have a ETA for 10.0 yet, because we're still in the process to migrate to the Apache Foundation and it is taking longer than expected. Hopefully just a few more weeks.

**Comment by deepakkapoor23** [comment]
So 10.0.x is the drools release. Can you please also confirm which kogito release version this fix will be included in? I am currently running kogito version 1.43.0.Final

**Comment by mariofusco** [comment]
We want a fresh start, so will align all release versions to 10.0.x

**Comment by deepakkapoor23** [comment]
Any update or ETA?

**Comment by krishnaklgr** [comment]
Any update on this please. We are currently blocked due to recent vulnerability on quarkus-core. Appreciate it if you provide some updates. Thanks.

**Comment by deepakkapoor23** [comment]
@mariofusco We have been blocked due to severe vulnerabilities as well on quarkus 2 and kogito won't work on quarkus 3 due to this issue.
It's been almost two months now, is there now an estimated timeframe available for v10 release?
If not, is it possible to provide a patch for this so kogito can run on quarkus 3 in the time being?

**Comment by mariofusco** [comment]
@deepakkapoor23 I'm sorry but apache related bureaucracy is taking forever and at the moment I cannot commit on any ETA yet.

**Comment by krishnaklgr** [comment]
@mariofusco Any update on this issue? Appreciate your efforts.

**Comment by mariofusco** [comment]
Still trying to finalize the 10.0, I know it's taking forever :(

**Comment by fmatar** [comment]
@mariofusco is there any way we can use snapshots?  I'm willing to build from the source and test new features.

Another question regarding SonataFlow  (Serverless Workflow). Is the implementation updated to use spec 1.0.0 already like Synapse?

**Comment by gsmet** [comment]
I will close this one. It's not a bug in Quarkus, just an external extension that is not available.

**Comment by krishnaklgr** [comment]
Great!!
