### ISSUE TITLE
Hibernate ORM: package-info is ignored when specifying scan packages

### ISSUE THREAD

**Issue by flokle** [quarkusio/quarkus#39299]
### Describe the bug

When specifying scan packages via application property `quarkus.hibernate-orm.packages` package-info-Files within these scan-packages are not taken into account. 

### Expected behavior

package-info-Files within  `quarkus.hibernate-orm.packages` can be interpreted by hibernate.

### Actual behavior

Having for example a hibernate @FilterDef within a package-info.java, startup of Quarkus will stop with an exception:
```
org.hibernate.AnnotationException: Entity 'MyEntity' has a '@Filter' for an undefined filter named 'filterDeleted'
```

Removing the property `quarkus.hibernate-orm.packages` fixes the problem. 

### How to Reproduce?

I have created a simple reproducible:

https://github.com/flokle/bug-reproducibles/tree/main/java/quarkus-orm-package-info-ignored-bug

Starting this project with goal `compile quarkus:dev` will lead to a failed startup. Removing the `quarkus.hibernate-orm.packages` property from /src/main/resources/application.properties and running again leads to a successfull start.

### Output of `uname -a` or `ver`

Darwin Florians-MBP 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

3.8.2

### Additional information

io.quarkus.hibernate.orm.runtime.boot.scan.QuarkusScanner.Result removes the package-info-candidate in line 61/62

**Comment by yrodiere** [comment]
Thanks for reporting.

If anyone has time to look at this, my bet would be on:

* [`JpaJandexScavenger`](https://github.com/quarkusio/quarkus/blob/83cd68b1bce1aa0c650a3b441b693c606236999a/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/JpaJandexScavenger.java) not returning the right classes/packages (though given the problem disappears when not specifying packages, that's unlikly)
* Or `[HibernateOrmProcessor#getModelClassesAndPackagesPerPersistenceUnits`](https://github.com/quarkusio/quarkus/blob/cf765fcec280d808b8c0acc071e4f1a70d72e9c9/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L1240) not returning package names as expected
* Or [`HibernateOrmProcessor#buildQuarkusScanner`](https://github.com/quarkusio/quarkus/blob/cf765fcec280d808b8c0acc071e4f1a70d72e9c9/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L1458) missing some info
* or...
