### ISSUE TITLE
We need an entry point guide for Messaging

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#39336]
Apparently, the guide in the SmallRye Reactive Messaging metadata was pointing to https://quarkus.io/guides/reactive-messaging which redirects to the Reactive Event Bus page and has nothing to do with our Messaging stack.

For now I dropped the guide from the descriptor as we need a working page but I think we need a https://quarkus.io/guides/messaging entry point with links to the various guides we have for messaging.

When created, we need to update the extension descriptor for the SmallRye Reactive Messaging extension.

@cescoffier does it make sense?

**Comment by cescoffier** [comment]
Agreed, makes sense.
