### ISSUE TITLE
Avro schemas aren't generated in isolation

### ISSUE THREAD

**Issue by MThomassen** [quarkusio/quarkus#39344]
### Describe the bug

When generating source files from Avro schema (.avsc) files, if no import option is set, schemas should remain isolated from each other.

Commit [Add backward compatible support for multiple extensions in CodeGenProvider](https://github.com/quarkusio/quarkus/commit/8af488dbd96f902872171d76b69bd48971897067) introduced a new way to create an (empty) list from a non-set `avro.codegen.*.imports` setting, breaking evaluation with static `EMPTY` object [here](https://github.com/quarkusio/quarkus/blob/5c25ff5a2d23eb634fc1a0d01ca2357a24222fc7/extensions/avro/deployment/src/main/java/io/quarkus/avro/deployment/AvroSchemaCodeGenProvider.java#L50).

### Expected behavior

When setting `avro.codegen.*.imports` is undefined or empty, all Avro files should be regarded as separate schemas

### Actual behavior

When setting `avro.codegen.*.imports` is undefined or empty, all Avro files aren't regarded as separate schemas. This causes the generate-sources process to fail if 2 or more Avro schema files are present defining the same named Avro-structure.

### Output of `uname -a` or `ver`

Linux 6.7.9-arch1-1 x86_64 GNU/Linux

### Output of `java -version`

openjdk 21.0.2

### Quarkus version or git rev

3.7.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

**Comment by cescoffier** [comment]
As you did the analysis, would you fancy a PR? We can guide you.
