### ISSUE TITLE
Feature Request: Immediate Exception Handling for Unreachable Kafka Broker

### ISSUE THREAD

**Issue by KaisNeffati** [quarkusio/quarkus#39351]
### Description

Hello, Quarkus team,
I've been working with the quarkus-smallrye-reactive-messaging-kafka extension and would like to discuss an enhancement that could greatly improve handling and control of Kafka messaging within Quarkus.
Currently, the SmallRye Reactive Messaging Kafka extension defaults to resilience through automatic retries when a Kafka broker is unreachable due to network issues or broker downtime. While this is generally effective, it does not cover all use cases and can introduce issues in some scenarios.
To illustrate this, let's consider an application that sends messages to Kafka:

```
@Path("/publish")
public class MessageResource {

    @Channel("message-topic") 
    Emitter<Message> emitter;

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.TEXT_PLAIN)
    public String publish(Message message) {
        emitter.send(message);
        return "Message sent successfully!";
    }
}
```

In this example, if the Kafka broker is unreachable, the emitter.send(message) line would not immediately fail. Instead, it would hold the messages in memory and continually retry, which could lead to significant issues because:
The application could be evicted by an orchestrator (like Kubernetes) at any time due to resource constraints or during normal operations, such as rolling updates. This eviction could lead to significant data loss if there are unsent messages held in memory.
The current setup offers no inherent ability to manage failure in message publishing. If an immediate exception were thrown when the broker is unreachable, it would trigger a failure mechanism, thus enhancing the robustness and reliability of the application.
Having the ability to choose between immediate exception or retries when the Kafka broker is unreachable would increase the flexibility and control developers have over their message-producing applications.

Thank you for considering this feature request
Best Regards,

**Comment by cescoffier** [comment]
The send method returns a CompletionStage. You can adds a timeout and fail explicitly.

Last time I checked the retry was handled in the network client of Kafka - not something we can modify. You may be able to configure the amount of retries.

**Comment by KaisNeffati** [comment]
Thank you @cescoffier for this prompt response 

Here is an example that I implemented locally : 

```
                String result = emitter.send(SomeObject.newBuilder().setBody(body).setHeader(header).build())
                        .toCompletableFuture()
                        .orTimeout(10, TimeUnit.SECONDS)
                        .thenApply(ignore -> "Message sent successfully!")
                        .exceptionally(throwable -> {
                            if (throwable instanceof TimeoutException) {
                                return "Kafka broker unreachable.";
                            } else {
                                return "Error sending message: " + throwable.getMessage();
                            }
                        }).join();
```

Here is the steps I've made to test this feature:

1. Start the application.
2. Start a consumer on the target topic.
3. Publish a record to Kafka.
4. Validate the presence of this record on the respective topic.
5. Disconnect Kafka by shutting down its respective Docker image.
6. Attempt publishing a record to Kafka.
7. Ensure the Timeout exception is triggered (which indeed gets triggered).
8. Restore Kafka.
9. Check the absence of the message in Kafka (which surprisingly FAILS. The message was sent despite the Timeout exception trigger. Even worse, there was an external retry mechanism beyond the message production process that resulted in N messages being sent when Kafka was back up).

Here is the configuration I ve used to set the retries to zero:

> mp.messaging.outgoing.topicName.retries=0

So the message is always kept in memory and resent after when the Kafka is up again

**Comment by KaisNeffati** [comment]
For others looking for a workaround to guarantee single delivery and synchronous behavior. 
Here's a code example
```
// A Future that will hold the HTTP response status when the task completes
CompletableFuture<Response.Status> statusCompletableFuture = new CompletableFuture<>();

// A supplier that creates a task which, when run, will asynchronously complete the future with a status OK
Supplier<CompletionStage<Void>> ackSupplier = () -> CompletableFuture.runAsync(
        () -> statusCompletableFuture.complete(Response.Status.OK)
);

// A function that creates a task which, if an error occurs, completes the future with status "request timeout" and rethrows the exception
Function<Throwable, CompletionStage<Void>> nackSupplier = throwable -> {
    statusCompletableFuture.complete(Response.Status.REQUEST_TIMEOUT);
    throw new RuntimeException(throwable);
};

// Creation of a message with body, header and an ackSupplier and nackSupplier
// Additionally, metadata is added for Kafka with message key and topic
Message<Dataset> message = Message.of(SomeObject.newBuilder().setBody(body).setHeader(header).build(), ackSupplier, nackSupplier)
        .addMetadata(OutgoingKafkaRecordMetadata.<String>builder()
                .withKey(MessageKEy)
                .withTopic(topic)
                .build());

// The message is registered to be sent by Quarkus
emitter.send(message);

// Obtain the HTTP response status by waiting for the completion of the Future
Response.Status responseStatus = statusCompletableFuture.join();

// If the status is OK, the message was successfully sent and a log is created
// If the status is not OK, an error log is generated and an error response is built
if (Response.Status.OK.equals(responseStatus)) {
    log.info(
        "Message header: {} - body : {}  sent to topic: {}",
        header,
        body,
        topic
    );
    return Response.accepted().build();
} else {
    log.error(
        "Failed to send message header: {} - body : {} to topic: {}",
        header,
        body,
        topic
    );
    return Response.serverError().build();
}
```

This code creates a message with specified header and body, then attempts to send it to a Kafka topic through Quarkus emitter. It also handles acknowledgements and failures in the process of sending the message. The future statusCompletableFuture is used to wait until the sending process completes or an error is occurred. It then logs whether the message was successfully sent and generates error response if it failed

By the way, while examining the documentation of Spring, I discovered this behavior in their KafkaTemplate API. I hope this encourages you to consider incorporating this feature into the Quarkus implementation
@cescoffier 
https://docs.spring.io/spring-kafka/docs/1.0.6.RELEASE/reference/html/_reference.html#_kafkatemplate

**Comment by cescoffier** [comment]
Actually, you can disable the kafka producer retries and the connector retry - which would simplify the code a lot.

**Comment by KaisNeffati** [comment]
Thank you for your prompt response as always. I truly appreciate your assistance
I'm experiencing the same behavior with the following configuration:

```
mp.messaging.outgoing.prv_dataset_int_v1.enable.retries=0 or false
mp.messaging.outgoing.prv_dataset_int_v1.failure-strategy=fail
```

Am I missing something !

**Comment by cescoffier** [comment]
You need to configure https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#retries as documented in https://smallrye.io/smallrye-reactive-messaging/latest/kafka/writing-kafka-records/#configuration-reference:

```
mp.messaging.outgoing.prv_dataset_int_v1.retries=0
```
