### ISSUE TITLE
Using Vert.x logging APIs

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#3935]
I am porting a Vert.x app which uses Vert.x logging APIs. It's not obvious how to set up logging to use Quarkus logging facilities;
```
java \
  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory ' \
  -Dquarkus.log.category."foo.bar".level=TRACE' \
  -jar ./target/foobar-1.0-SNAPSHOT-runner.jar
```
works but 
```
/target/foobar-1.0-SNAPSHOT-runner \
  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory ' \
  -Dquarkus.log.category."foo.bar".level=TRACE'
```
does not. Also, I can't just set the system property in a static constructor (it won't work even in the JVM version).

**Comment by gsmet** [comment]
@cescoffier @vietj shouldn't we deal with it in Quarkus itself if not already done? Using our JBoss Logging infrastructure should be the default.

**Comment by cescoffier** [comment]
We need to implement and configure a Vert.x logging facade using the Quarkus logging support. There is no existing facade for JBoss Logging.

**Comment by rvansa** [comment]
@cescoffier Why can't the existing facade that delegates to SLF4J or some other framework be used, and use its adaptor to Quarkus? I understand it's not 100% efficient, but that's more a good-to-have.

**Comment by cescoffier** [comment]
@rvansa it won't work in native as the LoggerDelegateFactory is not registered for reflection.
