### ISSUE TITLE
Dev UI /endpoints does not show all of my endpoints

### ISSUE THREAD

**Issue by mcanzerini** [quarkusio/quarkus#39360]
### Describe the bug

In dev mode, when I go to `/q/dev-ui/endpoints`, I do not see my routes (onle the `/q/*` routes)

Is it a bug ? Or do I need to add a configuration to show the routes ?

Thanks

### Expected behavior

All of my routes are displayed in `/q/dev-ui/endpoints`

### Actual behavior

Only the `/q/*` routes are displayed

### Additional information

Quarkus version : 3.8.2

**Comment by geoand** [comment]
cc @phillip-kruger

**Comment by phillip-kruger** [comment]
You can not configure to see it. I'll enhance the page to include the /q sub-router

**Comment by phillip-kruger** [comment]
What endpoints are you missing ? I can see some:
![image](https://github.com/quarkusio/quarkus/assets/6836179/66e59c2a-e999-4c13-afba-0e3c76b3dec6)

**Comment by mcanzerini** [comment]
My own endpoints are missing, I mean the routes I developed and exposed

**Comment by phillip-kruger** [comment]
You mean your Rest endpoints?

**Comment by mcanzerini** [comment]
Yes

**Comment by phillip-kruger** [comment]
Ok cool, yes for those I recommend SmallRye openAPI, we did not want to repeat the work that openAPI and swagger is already doing (much better).

**Comment by mcanzerini** [comment]
Thanks for your answer!
Maybe the documentation could be more precise on this? There is nothing about endpoints here: https://quarkus.io/guides/dev-ui

**Comment by phillip-kruger** [comment]
Sure ! The documentation needs to be updated
