### ISSUE TITLE
Avoid throwing a RuntimeException when parsing an invalid XML body using JAXB

### ISSUE THREAD

**Issue by davidreis97** [quarkusio/quarkus#39375]
### Description

Throwing a RuntimeException when an invalid XML body gets deserialized by JAXB makes exception handling difficult using the ExceptionMapper mechanism.

### Implementation ideas

Create a new exception, dedicated to JAXB deserialization errors, that wraps the UnmarshalException. Then it would be possible to handle that exception cleanly in a dedicated ExceptionMapper.

**Comment by ketola** [comment]
I compared the implementations of `ServerJaxbMessageBodyReader` to the json equivalent `ServerJacksonMessageBodyReader` and there, if the deserialization fails, a `WebApplicationException` is thrown.
Would that work for Jaxb also? I'd assume the same result: Bad Request would be a good default here also.

But the same way as in the jackson, the exceptions related to the configuration of the deserialization should be separated and thrown as runtime exceptions resulting in Internal Server Error.

Links:
[ServerJacksonMessageBodyReader](https://github.com/quarkusio/quarkus/blob/0a093408b0c4a49abfab231d76f00a011830a207/extensions/resteasy-reactive/rest-jackson/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/serialisers/ServerJacksonMessageBodyReader.java#L60)

[ServerJaxbMessageBodyReader](https://github.com/quarkusio/quarkus/blob/0a093408b0c4a49abfab231d76f00a011830a207/extensions/resteasy-reactive/rest-jaxb/runtime/src/main/java/io/quarkus/resteasy/reactive/jaxb/runtime/serialisers/ServerJaxbMessageBodyReader.java#L77)

I've been looking for an issue to contribute to Quarkus and I would like to work on this one if possible.

**Comment by ketola** [comment]
Based on my tests in the Draft PR I noticed that the `resteasy-reactive-jaxb` and `resteasy-jaxb` behave differently. The reactive implementation returns 500 when an invalid xml is sent and the other one returns 400. My suggestion is that `resteasy-reactive-jaxb` would be modified to work like `resteasy-reactive-jackson` works when invalid json is sent -> WebApplicationException resulting in http 400. 
I could go on and try to fix it if this sounds like a plan? I would also need to add an integration test module as I have done in the pr to bring up the issue and verify the fix.
