### ISSUE TITLE
Support the configuration property indirection with custom ConfigSource

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#3937]
**Description**
It is possible to use the property indirection when all the properties are set in `application.properties`:
```
quarkus.datasource.password=${password}
password=bar
```
but not when a resolution of the `password` property is supported by a custom `ConfigSource`, so the following does not work:

```
quarkus.datasource.password=${password}
```
Having it supported would benefit Quarkus immensely, especially from the security point of view: for example, all the extensions requiring secret or indeed even public key materials, could all use some kind of Vault such as the HashiCorp one to fetch the secret values.   

**Implementation ideas**
Try to update the way the property indirection resolution works - for example, in the above case, if no `password` property is available within `application.properties` then check the custom config source

**Comment by kenfinnigan** [comment]
This would likely require updates to https://github.com/smallrye/smallrye-config

**Comment by sberyozkin** [comment]
Hi @kenfinnigan, thanks, will have a look

**Comment by dmlloyd** [comment]
This happens because of how we wrap config sources.  But once property expansion hits the MP-config spec (and subsequently SmallRye Config), our custom property expansion will be removed and it should all begin to work consistently.

**Comment by vsevel** [comment]
@dmlloyd excellent - it opens up numerous opportunities
