### ISSUE TITLE
Hibernate runtime property persisting after build

### ISSUE THREAD

**Issue by stackoverflow2** [quarkusio/quarkus#39388]
### Describe the bug

The hibernate runtime property `quarkus.hibernate-orm.database.generation=drop-and-create`  persisting when set using environment variable during build  process as `set QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create `. 

After build this is used by application at runtime even if it is not set/configured in `application.properties`  file.  The default value of this config property is `none`.

### Expected behavior

`quarkus.hibernate-orm.database.generation=drop-and-create` should not persist after building even if we have set the environment variable `set QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create ` during build process.

We are not specifying this property quarkus.hibernate-orm.database.generation=drop-and-create` in our application.properties file hence it should take none as default value while running application as  java -jar quarkus-run.jar .

### Actual behavior

The hibernate runtime property `quarkus.hibernate-orm.database.generation=drop-and-create`  persisting when set using environment variable during build  process as `set QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create `. 

After build this is used by application at runtime even if it is not set/configured in `application.properties`  file.  The default value of this config property is `none`.

### How to Reproduce?

Reproducer steps : 

1. Set environment variable `set QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create `.
2. Build the application using `mvn clean install`.
3. Do not specify `quarkus.hibernate-orm.database.generation=drop-and-create` in application.properties file.
4. Run the application jar in other session/terminal  `java -jar quarkus-run.jar ` .
5. Application executes drop and create for tables instead of doing nothing.

Attached reproducer
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/14585171/code-with-quarkus.zip)

### Output of `java -version`

java version "17.0.4" 2022-07-19 LTS Java(TM) SE Runtime Environment (build 17.0.4+11-LTS-179) Java HotSpot(TM) 64-Bit Server VM (build 17.0.4+11-LTS-179, mixed mode, sharing)

### Quarkus version or git rev

Quarkus version  3.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: C:\Users\****\.m2\wrapper\dists\apache-maven-3.9.3-bin\326f10f4\apache-maven-3.9.3 Java version: 17.0.4, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17.0.4 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by yrodiere** [comment]
Requalifying as a config issue, since I don't think this is specific to the Hibernate ORM extension; it's probably the same for all configuration properties, it's just that you noticed it for one on the Hibernate ORM extension.

@radcortez It seems environment properties set during the build are treated just as properties coming from `application.properties`, and saved to be later applied at runtime... Is that on purpose, or just something we forgot to handle?

**Comment by stackoverflow2** [comment]
@yrodiere  I think its not general issue. Its not happening with other customer properties. For us this is happening with only for `quarkus.hibernate-orm.database.generation`

**Comment by yrodiere** [comment]
> @yrodiere I think its not general issue. Its not happening with other customer properties

I meant a general issue for extension properties.

Extensions properties don't work exactly the same as application properties, in particular some extensions that rely on the legacy configuration system, like the Hibernate ORM extension does in Quarkus 3.7.

By the way, the Hibernate ORM extension was [updated to use a newer configuration system](https://github.com/quarkusio/quarkus/pull/38731) in 3.9 (not yet released). Do you think you could try your reproducer against Quarkus version 999-SNAPSHOT, to see if those changes solve your problem? I think Quarkus snapshots are published to Maven Central, so hopefully you won't need to build Quarkus yourself.

**Comment by radcortez** [comment]
> @radcortez It seems environment properties set during the build are treated just as properties coming from `application.properties`, and saved to be later applied at runtime... Is that on purpose, or just something we forgot to handle?

Correct.

This was added some time ago in https://github.com/quarkusio/quarkus/pull/30368/.

It only applies to properties in the `quarkus` namespace. One goal was to not fail Quarkus configuration when a configuration is available in the Env at build time but not at runtime.
