### ISSUE TITLE
Log lra-coordinator output during microprofile-lra tck tests

### ISSUE THREAD

**Issue by marcosgopen** [quarkusio/quarkus#39390]
### Description

Logging lra-coordinator container output during microprofile-lra tck tests would help to better understand the behaviour of the coordinator and would help developers to debug tck tests issues when they occur. 

### Implementation ideas

I would propose to log the output using the followOutput method of the org.testcontainers.containers.GenericContainer class. See https://github.com/quarkusio/quarkus/pull/39104.

**Comment by gastaldi** [comment]
Fixed in https://github.com/quarkusio/quarkus/commit/7eb8479ed7bc097754600590ed7b66aa1640d1a4
