### ISSUE TITLE
Exception on amqp connection at the end of each test when application terminates

### ISSUE THREAD

**Issue by mnguetsa** [quarkusio/quarkus#39393]
### Describe the bug

When running my tests I am observing the following exception all the time: 
```
Mutiny had to drop the following exception [Error Occurred After Shutdown]
io.vertx.core.impl.NoStackTraceThrowable: Connection disconnected
```

This started when I introduced smallrye reactive messaging to communicate with an AMQP broker. 
It seems whenever the application terminates during tests the amqp connection is interrupted and that exception is thrown. 
Also setting `quarkus.shutdown.timeout` doesn't help.  The amqp connection should be gracefulfy terminated

### Expected behavior

No exception after each test run
The amqp connection should be gracefufly terminated

### Actual behavior

Not impacting the test but throwing that exception in the output after each test. 

### How to Reproduce?

I set up this small app for you to quickly reproduce. You just need to run the [GreetingResourceTest.java](https://github.com/mnguetsa/quarkus-reproducer/blob/amqp/src/test/java/org/acme/GreetingResourceTest.java) and you can see the exception already.
Checkout the **amqp** branch here: https://github.com/mnguetsa/quarkus-reproducer/tree/amqp

### Output of `java -version`

21

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.5

**Comment by cescoffier** [comment]
So, it's somewhat expected. The error comes from the fact that the AMQP client cannot disconnect properly because the broker has already stopped. We can hide the error when the application is stopping.

**Comment by cescoffier** [comment]
Fixed by https://github.com/smallrye/smallrye-reactive-messaging/pull/2527.

**Comment by cescoffier** [comment]
Hello, it's going to be in Quarkus 3.10. I think it's not critical enough to justify a backport in 3.8 and 3.9 (as it's expected and only for tests). My PR just cleans things.

**Comment by mnguetsa** [comment]
> Hello, it's going to be in Quarkus 3.10. I think it's not critical enough to justify a backport in 3.8 and 3.9 (as it's expected and only for tests). My PR just cleans things. 

Thank you. That's fine for me.
