### ISSUE TITLE
Consider retiring quarkus-test-keycloak-server, quarkus-test-oidc-server

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#39400]
In the same vein as https://github.com/quarkusio/quarkus/issues/39399 , we were wondering if we should retire quarkus-test-keycloak-server and quarkus-test-oidc-server.

Are they useful in the Quarkus build? There might be cases where Dev Services don't work well?

Are they useful for end users?

**Comment by sberyozkin** [comment]
@gsmet No, they are useful, both have support for the client side testing, example, `new KeycloakTestClient()`, `new OidcTestClient` which can be used to acquire tokens against DevService or live OIDC endpoints.

`OidcWireMockTest` is the `quarkus-test-oidc-server` is also very useful for testing when users don't work with Keycloak, a lot of tests depend on it in Quarkus too.

The only thing which is less useful now is a custom KeycloakFactoryTest support in the `quarkus-test-oidc-server` but it is the only piece which is still likely used.

Please close it as not planned, thanks

**Comment by sberyozkin** [comment]
>There might be cases where Dev Services don't work well?

Yes, Keycloak Dev Service can't cover all the variations, especially when user use non-Keycloak providers. `quarkus-test-oidc-server` covers both Wiremock but also provides `OidcTestClient` in the `.client.` subpackage - it is doc-ed in the Quarkus Auth0 guide.

As I said above, for Keycloak,  `quarkus-test-keycloak-server`, and we can continue making sure the DevService can do everything the the shipped test factory can, but in the `.client.` subpackage, it ships a very useful KeycloakTestClient.

**Comment by sberyozkin** [comment]
We could consider retire `quarkus-test-keycloak-server` but have the `quarkus-test-keycloak-client` which will ship KeycloakTestClient only - but I guess it is not worth it, the migration effort, and no fewer test extensions in the end

**Comment by gsmet** [comment]
Works for me!

**Comment by sberyozkin** [comment]
Thanks @gsmet, by the way, thinking about it more, once Steph finds time to complete his Keycloak-neutral Dev Service support, we can also deprecate the OIDC wiremock, and consider having `-client` only test extensions for OIDC in general and Keycloak in particular, but I guess it is a medium to longer term plan
