### ISSUE TITLE
Missing validation of javax validations inside subclasses

### ISSUE THREAD

**Issue by fbicak** [quarkusio/quarkus#39401]
### Describe the bug

I have a payload object used in a HTTP PUT resource method as follows:
`@Path("/{id}")
@PUT
public Dto update(@PathParam("id") String id, @NotNull @Valid UpdateEntityPayload payload)
`
This payload object contains a `List<ParameterDto>` field where ParameterDto class contains a field of an abstract class called `SchemaDto` which contains jackson annotations as follows:

`@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = StringSchemaDto.class, name = StringSchemaDto.TYPE),
        @JsonSubTypes.Type(value = BooleanSchemaDto.class, name = BooleanSchemaDto.TYPE)
})
public abstract class SchemaDto {} 
`
StringSchemaDto object contains a mandatory field as follows:

`
public class StringSchemaDto extends SchemaDto {

    public static final String TYPE = "string";

    @NotBlank(message = "Value can not be blank!")
    @JsonProperty("value")
    private String value;

    // getters and setters
}
`

When a client sends a request containing a string schema typed field without any value, the request is passed into my method's code block. I have noticed that, if I add a dummy StringSchemaDto field in my payload class, then it properly returns 400 HTTP response code. I have proper `@Valid` annotations through the path and I have validated that if I don't send a mandatory value in ParameterDto class, it returns 400 HTTP response code as well.

### Expected behavior

Quarkus resource should return 400 response code and should not invoke my resource method `update`.

### Actual behavior

My resource method `update` is invoked by Quarkus.

### How to Reproduce?

Reproducer:
1) Define a PUT resource containing a payload annotated with `@Valid`
2) Define an abstract class deserialized via Jackson and have at least one implementor of this class which contains a mandatory field i.e. string field
3) Send an HTTP request to this resource which does not contain the mandatory string field of this type.

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS

### Quarkus version or git rev

2.16.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.3

**Comment by gsmet** [comment]
Please provide a small Maven project reproducing the issue.

**Comment by fbicak** [comment]
You can check out this repository I created to demonstrate this problem: https://github.com/fbicak/quarkus-inheritance-validation-reproducer

**Comment by gsmet** [comment]
@fbicak as in Maven module? In that case, you need to make sure the module is indexed in Jandex. See my answer here: https://stackoverflow.com/a/55513723/5043585 .

Also please be aware that Quarkus 2.16 is not maintained anymore and it might become a security hazard.
I would recommend to update to Quarkus 3.x (either 3.8 LTS or the latest depending on your preferences) when you can.

`quarkus update` can help you with the task and should do most of the heavylifting: https://quarkus.io/guides/update-quarkus

**Comment by fbicak** [comment]
Thanks @gsmet adding that jandex plugin solves the problem.
