### ISSUE TITLE
JAX-RS method returning TemplateInstance executes on the event loop by default

### ISSUE THREAD

**Issue by imperatorx** [quarkusio/quarkus#39410]
### Describe the bug

When using  quarkus-resteasy-reactive-qute, any method that returns a TemplateInstance is executed on the event loop thread instead of a worker thread. 

- If I change the method signature to return a String, it is executed on a worker thread.
- If I add `@Blocking` to the ˛TemplateInstance method, it executes on a worker thread.

### Expected behavior

By default, a non reactive method gets executed on the worker thread

### Actual behavior

The method returning TemplateInstance executes on the event loop.

### How to Reproduce?

- Generate a new quarkus app with qute-reactive on the website
- Add the current thread to one of your pages
- It will be the vertx event loop

### Output of `java -version`

21

### Quarkus version or git rev

3.8.2

**Comment by geoand** [comment]
This is actually the desired behavior

cc @mkouba

**Comment by mkouba** [comment]
> This is actually the desired behavior
> 
> cc @mkouba

Yes, it's intentional (and also mentioned in [the docs](https://quarkus.io/guides/qute-reference#resteasy_integration)). The integration is using non-blocking API to render the template automatically.
