### ISSUE TITLE
OIDC `TenantConfigResolver` and `TenantResolver` are called even if the tenant id is already resolved 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#39417]
### Describe the bug

There are 2 cases right now where the OIDC tenant id is resolved before the tenant resolution code calling either `TenantConfigResolver` or `TenantResolver`, and other default resolvers starts runnning:
* When `@Tenant("sometenant")` annotation is used to resolve the tenant
* When the OIDC code flow session cookie is used to resolve it

In both cases, `TenantConfigResolver` or `TenantResolver` will still be called.

With `TenantResolver`,  the side-effect is minor, it just has to repeat the boilerplate:

```
String tenantId = getIdFromRoutingContext(rc);
if ((tenant != null) {
    return tenant;
}
``` 

but with `TenantConfigResolver` which returns an OidcTenantConfig instance, it is much worse, because unless it is a very limited number of configurations which can be just stored easily in the Map, users have to reread this config from some external source, or think of some more involved caching support. This is why I'm qualifying it as a bug.

But it should not be required since Quarkus already has the knowledge of the resolved OIDC tenants.

CC @calvernaz

**Comment by sberyozkin** [comment]
@michalvavrik Hey Michal, I know we discussed it recently and I was still thinking about keeping it, but once it became apparent the side-effect on the dynamic tenant resolution, I believe it should be simply be fixed, by checking at the start of the tenant resolution logic if the tenant id is resolved and this is it, no need (for me) to overthink it :-)

**Comment by sberyozkin** [comment]
@michalvavrik You are right,  if someone chose to use the tenant annotation then it takes a priority anyway,  and with the session cookie it is already resolved

**Comment by sberyozkin** [comment]
While fixing this issue, I've discovered a real bug with the session cookie tenant resolution when the `split` session cookie option is used, in which case there will be `q_session`, `q_session_at`, `q_session_rt` all coming in to Quarkus and the tenant id can be mistakenly set to a non-existent `at` or `rt`, instead of the default tenant. This option is unnecessary with the latest Quarkus when the session cookie is too large, and with the single configuration it ends up resolving to the same default tenant. But with complex multi-tenant setups, it can cause verification failures, when the token must be verified by some custom tenant, but due to this bug it falls back to the default tenant which does not have the matching verification keys. Or if the non-default and default tenant configuration use the same verification keys - which is the case with Quarkus OIDC test checking the split option.

**Comment by sberyozkin** [comment]
@michalvavrik @calvernaz @pedroigor 

I've spent most of the day today on this issue and had to accept preventing calling the resolvers when the session cookie is already available is impossible. 

The main reason it breaks the expectation that if a tenant1 authenticated user attempts to access the path expected to be protected by a tenant2, the access will be granted, because the session cookie will be verified by the tenant1 keys.

Advanced users can control it by restricting the cookie path per tenant, but users can be caught by surprise as well and we can't afford it.

TenantConfigResolver will be able to return null if the tenant id is set, and Quarkus will find the resolved oidc tenant.

The resolvers must be given a chance to handle such cases, either return, in the above case, tenant2, causing reauthentication, or throw a failure. 

For this reason the tenant id attribute should always be checked last, with the likely exception for the annotation case.

I will also fix the bug mentioned above.

**Comment by michalvavrik** [comment]
sounds reasonable @sberyozkin , I think the easiest (maybe bit lazy ? :-)) would be to introduce yet another `RoutingContext` attribute specific for annotations and check the tenant id attribute set in other scenarios as you suggest. Thanks for keeping us up to day, I definitely didn't thought about that before your comment.

**Comment by sberyozkin** [comment]
>I think the easiest (maybe bit lazy ? :-)) would be to introduce yet another RoutingContext attribute specific for annotations and check the tenant id attribute set in other scenarios last 

Makes sense

**Comment by sberyozkin** [comment]
It requires a bit more work following #39492.
Let me summarize. #39492 is required because without it custom tenant resolvers must either reload the OIDC configuration for authenticated users or multiple users accessing the same already resolved tenant or keep all the loaded configuration in the resolver in addition to Quarkus OIDC itself - and if a number of the resolved configurations goes into hundreds, reaching 1K, it can become really problematic.
So #39492 ensures that if the tenant resolver returns `null` with the tenant if already resolved from the session cookie, Quarkus will use that resolved tenant.
This however causes a problem if the resolver does not want that and wants to fallback to the default tenant, even if the session cookie is available. 
A situation like that can happen if a user authenticated with one tenant attempts to access the path protected by the default tenant where all the tenants share the same cookie path. I really expect, in practice, users are using named tenants in such cases, which is what we test. Furthermore, a proper and safe way to handle to distinguish between multiple tenants in such cases is to restrict a cookie path to the tenant specific path, when an already authenticated users attempting to access some other tenant's path will be required to authenticate.

The only edge case caught by the code flow test in the quickstarts is when multiple tenants share the same `/` cookie path, and the authenticated user authenticated by `tenant-a` attempts to access the path secured by the default tenant.

In this case, given that reverting #39492 would just make `TenantConfigResolver` not fit for any large OIDC tenant setup,  the way to do is for the custom tenant resolvers, if they want to return null and have the already set tenant-id ignored, is to just remove from the routing context. As rare such a case can be, unfortunately it is breaking change, and therefore  #39492 can not be backported

**Comment by michalvavrik** [comment]
> So https://github.com/quarkusio/quarkus/pull/39492 ensures that if the tenant resolver returns null with the tenant being already resolved from the session cookie, Quarkus will use that resolved tenant.
This however causes a problem if the resolver does not want that and wants to fallback to the default tenant, even if the session cookie is available.

That explanation makes perfect sense.

> The only edge case caught by the code flow test in the quickstarts is when multiple tenants share the same / cookie path, and the authenticated user authenticated by tenant-a attempts to access the path secured by the default tenant.

In past Quickstarts used to be run as part of the CI, right? Would it be possible to add a smoke test in your next PR when fixing this issue, please?

> In this case, given that reverting https://github.com/quarkusio/quarkus/pull/39492 would just make TenantConfigResolver not fit for any large OIDC tenant setup, the way to do is for the custom tenant resolvers, if they want to return null and have the already set tenant-id ignored, is to just remove it from the routing context. As rare such a case can be, unfortunately it is breaking change, and therefore https://github.com/quarkusio/quarkus/pull/39492 can not be backported.

It will work, but it sounds like very much implementation detail, or a hack. Do you know what I mean? I can't really explain it, but returning `io.quarkus.oidc.runtime.OidcUtils#DEFAULT_TENANT_ID` instead would make things more transparent. We can simply make sure that when `DEFAULT_TENANT_ID.equals(tenantId)` then we don't look into named clients, but use `defaultClient` instead.

**Comment by sberyozkin** [comment]
@michalvavrik `TenantConfigResolver` returns `Uni<OidcTenantConfig>`. Returning null from it has been supported from the start and always meant to fallback to the default tenant.

**Comment by michalvavrik** [comment]
> @michalvavrik `TenantConfigResolver` returns `Uni<OidcTenantConfig>`. Returning null from it has been supported from the start and always meant to fallback to the default tenant.

I was reacting to the `is to just remove it from the routing context` sentence. Otherwise I don't know how you want to make this backwards compatible. Returning null is alright.

**Comment by michalvavrik** [comment]
Ah, alright, got it.

**Comment by michalvavrik** [comment]
I confused it with the `io.quarkus.oidc.TenantResolver`.

**Comment by sberyozkin** [comment]
@michalvavrik Sure, with `@TenantResolver` returning `Default` would be just fine, it is just that from the start, for both of these resolvers when we did not quite yet know all the variations, returning null meant the default fallback. So for `TenantResolver` the breaking change is that returning `null` if the tenant is already resolved will not fallback to the default tenant. Indeed, returning `Default` would be the cleanest option, or removing the existing context attribute
 
Similarly for `TenantConfigResolver`. Users can reset a context attribute or remove it.

I'll doc it all once I'll fix the test next week
Thanks
