### ISSUE TITLE
Quarkus OpenTelemetry Rest Client Span Name with Route (URL Path Template)

### ISSUE THREAD

**Issue by luneo7** [quarkusio/quarkus#39457]
### Description

I've read the [OTEL spec](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name) and there it says that HTTP client span names SHOULD be `{method}`...
But it also says that:
```
Instrumentation MUST NOT default to using URI path as span name, but MAY provide hooks to allow custom logic to override the default span name.
```

A while back we already had Common URL Template path handling for client REST requests (https://github.com/quarkusio/quarkus/pull/17676/files#diff-7ec5f78d8d81fbcc3f6ddfbbaebd02aabf6bf0a843693411d955bdeba8a1d74eR56)... So can we maybe add a config parameter to change the behavior to the old way of creating rest client span names?

Having the name as `{method} {urlPathTemplate}` helps a lot while browsing the spans through the traces UI...

As right now everything (all rest clients in a app) are grouped as the HTTP methods (`GET`, `POST`, `PUT`....)

**Comment by brunobat** [comment]
This was fixed on the server but not in the client...

**Comment by brunobat** [comment]
Please do @luneo7 🙏
