### ISSUE TITLE
Allow @OIDCClientFilter at field level

### ISSUE THREAD

**Issue by neoludo** [quarkusio/quarkus#39460]
### Description

Hi

I'm using quarkus-oidc-client-reactive-filter extension to invoke remote REST calls with a specific JWT.
It's working pretty well, but I've only found the ability to decorate the Service Java Interface with (@RegisterRestClient).
I'd like to do that directly on the injection point. 

now:
```java
@OidcClientFilter("myapp")
public interface ApiController {
```

wished :
```java
@Inject
@RestClient
@OidcClientFilter("myapp")
private ApiController api;
```

Ludovic

**Comment by geoand** [comment]
I understand where this is coming from, but I am against it as having this kind of registration of filters at the injection point is **not** how any of our APIs work - not to mention that it would cause problems if multiple injection points exist.

I'll let @sberyozkin and @Ladicek decide, but I'll just reiterate that I am strongly against this.

**Comment by Ladicek** [comment]
This is not really my area of expertise, but I remember someone asking for a very similar thing in the CDI specification (to be able to apply decorators on an injection point) and while I see the appeal, it is indeed very much inconsistent with everything else and likely also incurs implementation difficulties.

**Comment by sberyozkin** [comment]
Hi @geoand I have to admit I don't follow what is so fundamentally wrong with this idea, the appeal is there, as I think @Ladicek agrees to. Using the application properties to bind the filter to the client conceptually does exactly the same which is why I'm not too concerned that other APIs don't do it. But my CDI knowledge is not great so from what I understand it is hard to do right. 
Let me also CC to @mkouba and @manovotn 

Thanks

**Comment by Ladicek** [comment]
There's one fundamental aspect to this. Is `@OidcClientFilter` a property of the _client_, or a property of the _user_ of the client? Alternatively, does it make sense to have _multiple_ users of the client, each with a different `@OidcClientFilter`?

My understanding is that in the current design, `@OidcClientFilter` is a property of the client. This issue basically asks for it to become a property of the _user_, and without even saying it, it also asks for the ability to have multiple users of the client, each with a different `@OidcClientFilter`. The question really is: do we want _that_?

**Comment by geoand** [comment]
Very eloquently put @Ladicek .

That's exactly why I am against this idea.

**Comment by neoludo** [comment]
When you are asking for a JWT, you specify who you are (aka the app name
id) and which resource you want to access.

We have a lot of micro services, sometimes sharing the same resource name,
sometimes not. So we have to provide multiple configurations.

Hope my explanation is not to confusing.

Ludo

Le ven. 15 mars 2024 à 11:38, Ladislav Thon ***@***.***> a
écrit :

**Comment by sberyozkin** [comment]
>This issue basically asks for it to become a property of the user, and without even saying it, it also asks for the ability to have multiple users of the client, each with a different @OidcClientFilter

Do you mean, it allows to support 
```
@OidcClientFilter("client-1")
@OidcClientFilter("client-2")
MyRestClient client;
```

? That can easily be blocked I believe to prevent it from being repeatable, from the multiple OIDC clients affecting the REST client.

As I said I'm not a CDI expert, but I'm finding it difficult to see the fundamental differences between

```
// user property
@OidcClientFilter("client-1")
MyRestClient client;
```
and

```
// MyRestClient property
@OidcClientFilter("client-1")
interface MyRestClient {}
```

**Comment by Ladicek** [comment]
No, I mean it allows

```java
public class Foo {
    @Inject
    @RestClient
    @OidcClientFilter("foo")
    MyRestClient client;
}
```

```java
public class Bar {
    @Inject
    @RestClient
    @OidcClientFilter("bar")
    MyRestClient client;
}
```

**Comment by sberyozkin** [comment]
Hmm, yeah, I see now...

**Comment by neoludo** [comment]
Correct, that's the point.

Le ven. 15 mars 2024 à 11:58, Ladislav Thon ***@***.***> a
écrit :

**Comment by sberyozkin** [comment]
@neoludo Can you clarify please, is it what you actually need ? To be able to do

```
public class Foo {
    @Inject
    @RestClient
    @OidcClientFilter("foo")
    MyRestClient client;
}

public class Bar {
    @Inject
    @RestClient
    @OidcClientFilter("bar")
    MyRestClient client;
}
```

in some different contexts ?

**Comment by geoand** [comment]
> We have a lot of micro services, sometimes sharing the same resource name,
sometimes not. So we have to provide multiple configurations.

Which to me sounds like they are different clients :)

**Comment by sberyozkin** [comment]
Closing it since #39461 was closed
