### ISSUE TITLE
Swagger UI unresponsive with big data model in native build

### ISSUE THREAD

**Issue by ivivanov-bg** [quarkusio/quarkus#39495]
### Describe the bug

Swagger UI gets completely unusable in native mode when dealing with big data model ( a lot of classes with a lot of nested properties), but the same code works just fine in JVM mode.

After quite some debugging different components the issue turned out to be that `swagger-core` defines several mix-ins to strip most of the properties from the openapi specification it creates.
https://github.com/swagger-api/swagger-core/blob/3fcc473c33c56f306902853a451020926ad691ea/modules/swagger-core/src/main/java/io/swagger/v3/core/util/ObjectMapperFactory.java#L244

During native build those classes apparently get erased by the compiler as they are abstract without any children and not references anywhere else.

The result is that the openapi json gets polluted with all those properties and the result size in my case is 402KB (vs 156KB for the same model in JVM mode) - mostly because of the `jsonSchema` map in the `Componnet.Schema` field.

This leads to the UI hanging and throwing out of memory errors in the browser, while trying to parse the model

The swagger-ui extension should register those mixins for reflections to allow the openapi json be reduced in size also for native images.

### Expected behavior

The fields ignored via MixIns to be removed from the openapi json 

### Actual behavior

All fields from the OpenAPI specification are serialized in the openapi json

### Output of `uname -a` or `ver`

any

### Output of `java -version`

java version "21" 2023-09-19

### Mandrel or GraalVM version (if different from Java)

Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15)

### Quarkus version or git rev

3.8.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by phillip-kruger** [comment]
@ivivanov-bg thanks for the issue. Are you keen to provide a PR with the fix ?

**Comment by ivivanov-bg** [comment]
When I tired to simply register all mixins the openapi endpoind stopped working at all.
Apparently I'm missing something, but don't really have the time to do further investigation.

**Comment by phillip-kruger** [comment]
Can you share a reproducer ?

**Comment by ivivanov-bg** [comment]
No.
And I can fix it locally for my setup.
Just wanted to put some details in case anyone else experience the same issue

**Comment by gsmet** [comment]
@ivivanov-bg if you can provide a small reproducer that doesn't output the same thing for JVM and native, that would be enough for us to reproduce the issue. We don't need the whole app.

Do you think you could do that?

**Comment by ivivanov-bg** [comment]
Trying to prepare the reproducer - I just realized that the issue is actually in another module:
it's in the `camel-quarkus-openapi-java` extension.

This is where the `openapi` generation actually happens. Still not ready with the reproducer, but once done - will close this issue and will open new in the camel quarkus project

**Comment by ivivanov-bg** [comment]
This it the related issue [camel-quarkus #5891](https://github.com/apache/camel-quarkus/issues/5891)
