### ISSUE TITLE
(Doc issue) How to list all quarkus.oidc-client properties.XXXXX

### ISSUE THREAD

**Issue by orivat** [quarkusio/quarkus#39527]
### Describe the bug

quarkus.oidc-client properties are scattered everywhere within https://quarkus.io/version/main/guides/security-openid-connect-client-reference

### Expected behavior

The expectation is to  have all the quarkus oidc client properties listed in a central place with something like this:

Note:
This requirement does not prevent from documenting/describing them at different places within the URL, but the expectation is to have also all those properties listed (likely at the end of the document) to have a kind of synthetic view of the available options.

quarkus.oidc-client.jwt-secret.auth-server-url=
quarkus.oidc-client.jwt-secret.client-id=
quarkus.oidc-client.jwt-secret.credentials.jwt.secret=
quarkus.oidc-client.grant.type=

quarkus.oidc-client.credentials.secret=

.....
quarkus.oidc-client.credentials.client-secret.method=
quarkus.oidc-client.credentials.jwt.secret-provider.name =

quarkus.oidc-client.client-id=quarkus-app
quarkus.oidc-client.credentials.jwt.key-store-file=
quarkus.oidc-client.credentials.jwt.key-store-password=
quarkus.oidc-client.credentials.jwt.key-password=

quarkus.oidc-client.grant.type=
quarkus.oidc-client.grant-options.password.username=
quarkus.oidc-client.grant-options.password.password=

### Actual behavior

NA

### How to Reproduce?

NA

### Output of `java -version`

17

### Quarkus version or git rev

3.8

**Comment by sberyozkin** [comment]
Fixed by #39367

**Comment by sberyozkin** [comment]
@orivat I've added a backport to 3.8 label to the linked PR

**Comment by orivat** [comment]
That's great
