### ISSUE TITLE
(Doc issue)  Getting token using blocking or non blocking calls

### ISSUE THREAD

**Issue by orivat** [quarkusio/quarkus#39528]
### Describe the bug

It should be worth indicated that it is possible to get access token in a blocking or not blocking way (reactive way)

```java
    @GET
    @Path("admin-name-with-oidc-client-token-header-param")
    @Produces("text/plain")
    public Uni<String> getAdminNameWithOidcClientTokenHeaderParam() {
    	Uni<OidcClient> oidcClient = createOidcClientDynamically();
    	return oidcClient.onItem()
        		.transformToUni(client -> client.getTokens().onItem()
        		.transformToUni(tokens -> restClientWithTokenHeaderParam.getAdminName("Bearer " + tokens.getAccessToken())));
}
```

```java
    @GET
    @Path("admin-name-with-oidc-client-token-header-param-blocking")
    @Produces("text/plain")
    public String getAdminNameWithOidcClientTokenHeaderParamBlocking() {
    	Uni<OidcClient> oidcClient = createOidcClientDynamically();
    	OidcClient client = oidcClient.await().indefinitely();
        Tokens tokens = client.getTokens().await().indefinitely();
        return restClientWithTokenHeaderParam.getAdminName("Bearer " + tokens.getAccessToken()).await().indefinitely();
    }
```

### Expected behavior

There should an an example  describing both  possible usage in the documentation and also quarkus quickstart

**Comment by sberyozkin** [comment]
@orivat Is it really necessary ? We checked it can work in the blocking mode with Resteasy but promoting this kind of code is not great as with the reactive mode this kind of code does not make a lot of sense

**Comment by orivat** [comment]
@sberyozkin 
I agree it is not great code, But I think it is worth indicating that blocking mode works with Resteasy  (likely in the doc)

**Comment by geoand** [comment]
I do agree with @orivat here that an example of both modes makes sense

**Comment by sberyozkin** [comment]
@orivat @geoand Sure, this is the PR, https://github.com/quarkusio/quarkus-quickstarts/pull/1399, which I'll refer to from the quickstart once it is merged
