### ISSUE TITLE
quarkus-cache might block indefinitely when backed by Redis and lockTimeout=0

### ISSUE THREAD

**Issue by lxngr** [quarkusio/quarkus#39558]
### Describe the bug

When using qarkus-cache backed by quarkus-redis-cache and lockTimeout=0 the cache might block indefinitely. This is the case when a cache miss uses a "heavy weight" operation that itself uses a cache and that operation misses too (two chained cache misses).

Might not a be the best idea but works well when using the default cache implementation (Caffeine).

### Expected behavior

The second "heavy weight" operation should be executed anyway and the cache should not block (like when using the default cache implementation).

### Actual behavior

Cache blocks indefinitely.

### How to Reproduce?

I've build an reproducer based on the cache example (APPLICATION DATA CACHING) that uses two caches chained and both miss: https://github.com/lxngr/quarkus-cache.

Test with: "curl http://localhost:8080/weather\?city\=LA"

### Output of `uname -a` or `ver`

Darwin Kernel Version 23.4.0 (macOS)

### Output of `java -version`

openjdk version "17.0.10" 2024-01-16 LTS

### Quarkus version or git rev

3.8.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2

**Comment by geoand** [comment]
Interesting scenario.

You mention ` lockTimeout=0` in the description, but I don't see that configured anywhere in the sample application you have attached. Can you clarify?

**Comment by lxngr** [comment]
I've left it out in my sample application as `lockTimeout = 0` is the default.

**Comment by geoand** [comment]
Ah, you're right.

I am not sure what we can really do about this one as it's a weird case...
