### ISSUE TITLE
Quarkus management interface and Swagger UI executing APIs at wrong path

### ISSUE THREAD

**Issue by ccarv** [quarkusio/quarkus#39561]
### Describe the bug

When the `quarkus.management.enabled` is set to `true`, it binds the OpenAPI extension to this interface as well. This is expected according to Quarkus management interface documentation.

However, when using the Swagger UI interface to interact with APIs, it does not invoke the proper URL where the API services are actually bound.

### Expected behavior

If my services are bound to HTTPS on port 8443 and my management port is bound to HTTP on port 9000, Swagger-UI should properly execute services calls to HTTPS on port 8443.

### Actual behavior

Swagger UI is invoking API services calls on the same management port 9000 on HTTP.

### How to Reproduce?

1. APIs should be bound to HTTPS
2. Management port bound to HTTP
3. Navigate to http://localhost:9000/q/swagger-ui and execute one of the APIs

### Output of `java -version`

java 17.0.9 2023-10-17 LTS

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

17.0.9

**Comment by phillip-kruger** [comment]
As a workaround you can add this ([quarkus.smallrye-openapi.servers](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus-smallrye-openapi-servers)) config:

`quarkus.smallrye-openapi.servers=`https://localhost:8443/`

I'll look into doing this automatically when management is enabled.

**Comment by phillip-kruger** [comment]
This seems to fix (I might have fixed it). Can you try with the latest version ?

**Comment by phillip-kruger** [comment]
@ccarv can you test with the latest version and report back

**Comment by gsmet** [comment]
I think I have fixed this here: https://github.com/quarkusio/quarkus/pull/44648 .

Note that you might still have some CORS issues in some cases and you might need to tweak your CORS config but the default case seems to work well now.

Closing.

**Comment by phillip-kruger** [comment]
@ccarv If I remember correctly, what I fixed was the correct port to be used when management interface is enabled. (Before that fix you could use the `quarkus.smallrye-openapi.servers` as a workaround. This was just on localhost.

If you know the list of possible urls, you can add them all to `quarkus.smallrye-openapi.servers`. If they are dynamic, ie. you only know them at runtime, you can create a filter to set them programmatically , see https://quarkus.io/guides/openapi-swaggerui#enhancing-the-openapi-schema-with-filters
