### ISSUE TITLE
Guide on Reactive SQL incomplete

### ISSUE THREAD

**Issue by avivmu** [quarkusio/quarkus#39601]
### Describe the bug

the [reactive-sql-clients guide](https://quarkus.io/guides/reactive-sql-clients) mentions creating an html file fruits.html but it doesn't mention where to place this file (and also where to place fruits.js)
Moreover I think it's also missing an additional endpoint to FruitResource to serve this html file from http://localhost:8080/fruits.html

I fixed it by adding it under src/main/resources and adding this endpoint:
```java
  @GET
  @Path("/fruits.html")
  @Produces(MediaType.TEXT_HTML)
  public Response getHtml() {
    try {
      String html = new String(Files.readAllBytes(Paths.get(getClass().getClassLoader().getResource("fruits.html").toURI())));
      return Response.ok(html).build();
    } catch (Exception e) {
      return Response.serverError().entity("Error loading fruits.html").build();
    }
  }
```

### Expected behavior

Guide should be complete

### Actual behavior

Guide doesn't include all the necessary code and information

**Comment by tsegismont** [comment]
Thanks for pointing this out @avivmu 

I've proposed an update of the doc in #39620 

In fact, you don't need to implement an endpoint in Java. Quarkus automatically serves static resources located under the `META-INF/resources` directory.
