### ISSUE TITLE
Clients do not receive error response in case of an exception when using default gRPC API with `@Blocking` or `@RunOnVirtualThread`

### ISSUE THREAD

**Issue by ranjanashish** [quarkusio/quarkus#39602]
### Describe the bug

Clients do not receive error response (they just hang waiting for a response that never arrives) in case of an exception when using default gRPC API with `@Blocking` or `@RunOnVirtualThread`.

Please note this bug is not seen with Mutiny gRPC API. Also, this works as expected with default gRPC API when `@Blocking` or `@RunOnVirtualThread` is not used.

|                                              | Mutiny gRPC API                      | Default gRPC API                     |
| -------------------------------------------- | ------------------------------------ | ------------------------------------ |
| Without `@Blocking` or `@RunOnVirtualThread` | *(expected)* client receives error   | *(expected)* client receives error   |
| `@Blocking`                                  | *(expected)* client receives error   | *(unexpected)* client hangs          |
| `@RunOnVirtualThread`                        | *(expected)* client receives error   | *(unexpected)* client hangs          |

### Expected behavior

Client should receive an error response

### Actual behavior

Client hangs

### How to Reproduce?

1. Clone repo - https://github.com/ranjanashish/quarkus-grpc-unhandled-exception-bug
2. Run unit tests using `./gradlew test`
3. Test will hang
4. Kill test and remove `@Blocking` from the RPC method
5. Re-run unit tests
6. Test will pass

The same behaviour applies when using `@RunOnVirtualThread`.

### Output of `uname -a` or `ver`

Darwin Kernel Version 23.4.0

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

**Comment by alesj** [comment]
jstack(s)
* https://gist.github.com/alesj/335cea2628746e70e0b59a92a86c0414#file-gistfile1-txt-L246

**Comment by alesj** [comment]
I've added this to our gRPC blocking tests -- which afais look the same as this reproducer
* https://github.com/alesj/quarkus/commit/7d3590a478088c53759baabdbd8281810cd56df5
... yet all works as expected ...

**Comment by alesj** [comment]
Ah, I see reproducer service code throws an exception ... let me try that.

**Comment by ranjanashish** [comment]
We need to have a `fail()` call after [this line](https://github.com/alesj/quarkus/blob/cd38b916b7d0e979d45968d088e5ae221f735a6f/extensions/grpc/deployment/src/test/java/io/quarkus/grpc/server/blocking/BlockingMethodsTest.java#L97). Otherwise the test might pass incorrectly if it doesn't throw any exception.

**Comment by alesj** [comment]
jstack for the reproducer ...
* https://gist.githubusercontent.com/alesj/41fd8943bde0bc2960d1d81d7ec5592e/raw/3910e4bd1870f1ed1e2227c68fe4abb79a5ac1c6/gistfile1.txt

**Comment by alesj** [comment]
```
java.lang.IllegalArgumentException: You're not allowed!
	at io.quarkus.grpc.server.services.BlockingTestService.unaryCallBlocking(BlockingTestService.java:64)
	at io.quarkus.grpc.blocking.BlockingTestServiceGrpc$MethodHandlers.invoke(BlockingTestServiceGrpc.java:1009)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.quarkus.grpc.runtime.supports.blocking.BlockingExecutionHandler.call(BlockingExecutionHandler.java:43)
	at io.quarkus.grpc.runtime.supports.blocking.BlockingExecutionHandler.call(BlockingExecutionHandler.java:11)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
```
