### ISSUE TITLE
Add Apache Camel extension available in project creation tooling

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#3962]
Until the Platform is ready, we need to temporarily make Apache Camel available in the project creation tooling:
https://github.com/apache/camel-quarkus/issues/190

We need to update: https://github.com/quarkusio/quarkus/blob/master/devtools/common/src/main/filtered/extensions.json

@aloubyansky is working on making it possible to add external extensions without affecting the bom. Could you link the related Issues/PRs please?

Doing that is a pre-requisit to have it available in Code Quarkus.

**Comment by davsclaus** [comment]
@aloubyansky is there any update on this?

**Comment by aloubyansky** [comment]
Yes, IMO, we should not do this. This could work if the Quarkus and the Camel extensions were pretty much always compatible, which I found was not actually the case. Given that we won't be testing the Camel extension in the Quarkus build (to avoid circular dependencies), we won't be catching introduced incompatibilities and risk promoting incompatible versions of Quarkus and the Camel extension through our tooling.
We should just do it right from the start, which means we need to release the platform which will include the latest compatible combo. The repo is https://github.com/quarkusio/quarkus-platform

**Comment by maxandersen** [comment]
I consider this one done as camel-quarkus is now in the platform - https://github.com/quarkusio/code.quarkus.io/issues/165 will cover the rest.
