### ISSUE TITLE
Type not consistent in sample code

### ISSUE THREAD

**Issue by avivmu** [quarkusio/quarkus#39623]
### Describe the bug

In the [rest client tutorial](https://quarkus.io/guides/rest-client-reactive#create-the-interface) the `id` parameter is defined with the `Integer` type:
```
    Set<Extension> getById(@QueryParam("id") String id);
```
However in the [next code sample](https://quarkus.io/guides/rest-client-reactive#query-parameters) the same `id` parameter is defined with the `String` type:
```
    Set<Extension> getById(@QueryParam("id") Integer id);
```

### Expected behavior

consistent parameter type

**Comment by gsmet** [comment]
I think it could probably be made an `Integer` in the first occurrence.

Would you mind creating a PR?

**Comment by geoand** [comment]
Actually, the quickstart uses `String` so it would be best to align with that
