### ISSUE TITLE
ParamConverter default value

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#39631]
### Description

Currently, when I have a ParamConverter like this (example):
```
@Provider
class MyConverterProvider implements ParamConverterProvider {

    @Override
    public <T> ParamConverter<T> getConverter(Class<T> rawType, Type genericType,
                                              Annotation[] annotations) {
        // declare a converter for this type
        if(rawType == SortAttribute.class) {
            return (ParamConverter<T>) new MyConverter();
        }
        return null;
    }
}

// this is my custom converter
class MyConverter implements ParamConverter<SortAttribute> {

    @Override
    public SortAttribute fromString(String value) {
        return GreetingListSortAttribute.FORMALITY_FACTOR;
    }

    @Override
    public String toString(SortAttribute value) {
        return "";
    }

}
```

This ParamConverter gets called if I have a value for e.g. a QueryParam.
It also gets called if I set a default value on my queryparam.

**Comment by FroMage** [comment]
Sorry, I'm not sure what the problem is? :)

**Comment by Postremus** [comment]
@FroMage The problem is, I want that my paramconverter gets called if *no* value for a queryparam is specified in the request. This should in the end allow the converter to provide the default value.

**Comment by FroMage** [comment]
Why do you think `ParamConverter` should provide a default value if `@DefaultValue` is not set on the parameter? What's the use-case?

**Comment by FroMage** [comment]
I'm not sure that it's a hack. So far the deal has been that if you want no default value, you get `null` and handle that yourself, or you want one and provide `@DefaultValue`, and it even goes through your `ParamProvider` so that's already two default values possible.

Perhaps you have a lot of places where you use this `ParamConverter` and you want to avoid using `@DefaultValue` on many use-sites?

**Comment by Postremus** [comment]
> Perhaps you have a lot of places where you use this ParamConverter and you want to avoid using @DefaultValue on many use-sites?

No, if https://github.com/quarkusio/quarkus/issues/39598 gets fixed, it will be exactly one place where I have to define this `@DefaultValue`. 
Does not seem too bad.
It is however kinda unexpected, and badly documented imo that null values are not passed to paramconverters. Maybe the doc could be improved in that regard at least?

The javadoc of `ParamConverter#fromString` even states
```
* @throws IllegalArgumentException if the supplied string cannot be parsed or is {@code null}.
```
Passing null (in case no defaultvalue is specified) is therefore also simply not allowed.

Anyway thanks for talking sense into me.

**Comment by FroMage** [comment]
> it will be exactly one place where I have to define this @DefaultValue.
> Does not seem too bad.

Right, so not obvious if it's worth adding support for default null-representing values.

> Maybe the doc could be improved in that regard at least?

PR more than welcome :)

> Passing null (in case no defaultvalue is specified) is therefore also simply not allowed.

Right, but that doesn't mean we can't deviate from the spec, or add an extra method. If we had a good use-case, but it's not entirely clear that we do, yet.

> Anyway thanks for talking sense into me

It's not about sense, it's about deciphering the problem, and finding use-cases and debating whether something is needed and what. Thank you for the discussion. Now if someone comes with a similar request in the future, we'll have this in mind to build on.
