### ISSUE TITLE
Github pipeline fails after quarkus and jdk upgrade

### ISSUE THREAD

**Issue by dineshv1234567** [quarkusio/quarkus#39635]
### Describe the bug

Hi upgraded my quarkus maven project.
Earlier JDK - 11
Upgrade JDK - 21
Earlier quarkus - 2.3.0.Final
Upgraded quarkus version - 3.5.0
---
When I build the project with mvn clean install in locally IntelliJ, it works fine. But when it is build on Github pipeline, it fails

### Expected behavior

Pipeline should pass

### Actual behavior

[[1;31mERROR[m] Failed to execute goal [32mio.quarkus.platform:quarkus-maven-plugin:3.5.0:generate-code-tests[m [1m(default)[m on project [36mq2t-common[m: [1;31mExecution default of goal io.quarkus.platform:quarkus-maven-plugin:3.5.0:generate-code-tests failed: An API incompatibility was encountered while executing io.quarkus.platform:quarkus-maven-plugin:3.5.0:generate-code-tests: java.lang.NoSuchMethodError: 'boolean org.apache.maven.settings.Mirror.isBlocked()'

**Comment by geoand** [comment]
What version of Maven are you using?

**Comment by dineshv1234567** [comment]
> What version of Maven are you using?
I am using maven 3.8.1 and below plugin. Here generate-code-test gets failed on Github pipeline but perfectly works in intelliJ.

               ```
<plugin>
                <groupId>io.quarkus.platform</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>3.5.0</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by geoand** [comment]
Can you try with Maven `3.9.6`? Also, is there any reason you are using Quarkus 3.5 and not 3.8 or 3.9?

**Comment by dineshv1234567** [comment]
> Can you try with Maven `3.9.6`? Also, is there any reason you are using Quarkus 3.5 and not 3.8 or 3.9?

I tried upgrading maven-compiler-plugin to 3.13.0 and quarkus to 3.8.3. But still error is coming:

`Failed to execute goal [32mio.quarkus.platform:quarkus-maven-plugin:3.8.3:generate-code-tests[m [1m(default)[m on project [36mq2t-common[m: [1;31mExecution default of goal io.quarkus.platform:quarkus-maven-plugin:3.8.3:generate-code-tests failed: An API incompatibility was encountered while executing io.quarkus.platform:quarkus-maven-plugin:3.8.3:generate-code-tests: java.lang.NoSuchMethodError: 'boolean org.apache.maven.settings.Mirror.isBlocked()'`

**Comment by gsmet** [comment]
Closing as I think it's really an environment issue.
Please reopen if you end up having the same issue after updating Maven.

**Comment by dineshv1234567** [comment]
> We are talking about your Maven install itself.
> 
> Maven 3.8.1 is not supported anymore with Quarkus. Try to upgrade to Maven 3.9.6 as @geoand mentioned.

I tried with 3.9 version but still same error is coming

**Comment by dineshv1234567** [comment]
This error comes with maven 3.6.3. If we upgrade to 3.8.1 or later to 3.8.1. It works fine.
