### ISSUE TITLE
@Transactional is an @Inherited annotation but its effect does not seem to be inherited from interfaces

### ISSUE THREAD

**Issue by gavinking** [quarkusio/quarkus#39657]
### Describe the bug

I have a Jakarta Data repository.

```java
@Repository
@Transactional
public interface Library {

    @Find
    Optional<Book> byIsbn(String isbn);

    @Find
    List<Book> byTitle(@Pattern String title);

    @Insert
    void add(Book book);

    @Delete
    void delete(String isbn);
}
```

The implementation of this interface is generated by Hibernate's annotation processor.

```java
@RequestScoped
@Generated("org.hibernate.processor.HibernateProcessor")
public class Library_ implements Library {
    ...
```

Since `@Transactional` is an `@Inherited` interceptor binding type, the effect of this annotation should apply to calls to an instance injected as follows:

```java
@Path("/")
public class LibraryResource {

    @Inject Library library;

    ...
```

But in fact the methods are executed outside of a transaction scope, causing Hibernate to reject invocations of `delete()`.

### Expected behavior

The effect of `@Transactional` should be inherited, and the methods of an injected `Library` should run in a transaction.

### How to Reproduce?

https://github.com/gavinking/data-demo-quarkus/

### Quarkus version or git rev

3.8.3

### Additional information

For the record, there's nothing specific to Jakarta Data here; I can reproduce the same issue for a RestEASY Classic resource class.

**Comment by Ladicek** [comment]
Annotations are not inherited from interfaces. Quoting from https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/annotation/Inherited.html:

>  Note also that this meta-annotation only causes annotations to be inherited from superclasses; annotations on implemented interfaces have no effect.

Jakarta Annotations specify the same behavior. Quoting from https://jakarta.ee/specifications/annotations/2.1/annotations-spec-2.1#general-guidelines-for-inheritance-of-annotations:

> The interfaces implemented by a class never contribute annotations to the class itself or any of its members.

CDI specifies the same behavior. Quoting from https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#inheritance:

> Type-level metadata is never inherited from interfaces implemented by a bean.

I assume that at some point, a class is generated from the interface. I assume that class becomes a managed bean (in the CDI sense). The common approach we take in Quarkus is that we copy the relevant annotations (which are generally all annotations, except of a known set of annotations that shouldn't be copied) to the generated class.

**Comment by gavinking** [comment]
OK, fine, so apparently this is something I used to know back when I wrote the CDI and Interceptors specs, because I see words in those specs that look suspiciously like my words, and that seem very aware of this fact. But I had forgotten it. 

It seems crazy but it is what it is.

> The common approach we take in Quarkus is that we copy the relevant annotations

Yeah this is what I will have to do.
