### ISSUE TITLE
ClassCastException thrown when using smallrye-mutiny-vertx-sql-client-templates

### ISSUE THREAD

**Issue by mocukie** [quarkusio/quarkus#39659]
### Describe the bug

ClassCastException thrown when using smallrye-mutiny-vertx-sql-client-templates
```java
java.lang.ClassCastException - class io.vertx.pgclient.PgPool_7weXgYHcaRck_k2l7dGKfXZMdD8_Synthetic_ClientProxy cannot be cast to class io.vertx.sqlclient.impl.SqlClientInternal 
```

But if you use sqlClient directly, there is no problem.
```java
sqlClient.query("select version()")
              .mapping(r -> r.getString(0))
              .execute()
              .onItem()
              .transformToMulti(rs -> Multi.createFrom().iterable(rs))
```

### Expected behavior

no exception

### Actual behavior

cdi client proxy cannot be cast to class io.vertx.sqlclient.impl.SqlClientInternal 

### How to Reproduce?

```java
  @Inject
  PgPool sqlClient;
```
```java
SqlTemplate.forQuery(sqlClient, "select version()")
              .mapTo(String.class)
              .execute(Map.of())
              .onItem()
              .transformToMulti(rs -> Multi.createFrom().iterable(rs))
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.4046]

### Output of `java -version`

OpenJDK 64-Bit Server VM Zulu21.30+15-CA (build 21.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5
Build time:   2023-11-29 14:08:57 UTC
Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.1 (Azul Systems, Inc. 21.0.1+12-LTS)
OS:           Windows 10 10.0 amd64

**Comment by cescoffier** [comment]
My guess is that the template downcast the pool which does not work because we inject proxy. We can change the scope to be in the singleton scoped, it should fix it.


CC @mkouba @tsegismont

**Comment by Ladicek** [comment]
Yeah, when creating the synthetic bean, we specify the `PgPool` interface as the implementation class. It seems we cannot really change that to `PgPoolImpl`, because there's an extension point that allows customizing the creation of the final `PgPool` instance (`PgPoolCreator`), which doesn't guarantee that the actual produced instance will in fact be `PgPoolImpl`. Which actually means that there's also no guarantee that the actual instance will implement `PgPoolInternal` (altough most of the time, it probably will) and therefore changing the scope to singleton is not guaranteed to help, strictly speaking.

By changing the scope to singleton, we'd possibly affect lifecycle (the singleton would be eagerly initialized), which would be my biggest worry.

**Comment by mkouba** [comment]
Ladislav is right, the injected client proxy for `PgPool` must also implement `io.vertx.sqlclient.Pool` and `io.vertx.sqlclient.SqlClient` interfaces but there's no requirement or guarantee to implement `io.vertx.sqlclient.impl.SqlClientInternal` which according to the name is a internal API anyway.

You can unwrap the client proxy and obtain the underlying instance which _could be_ an instance of `PgPoolInternal`: `io.quarkus.arc.ClientProxy.unwrap(T)`. But again, it's not guaranteed so you'll need to check the runtime class before the actual use in the `SqlTemplate`.

```java
PgPool unwrapped = ClientProxy.unwrap(sqlClient);
if (unwrapped instanceof PgPoolInternal) {
   SqlTemplate.forQuery(sqlClient, "select version()")
              .mapTo(String.class)
              .execute(Map.of())
              .onItem()
              .transformToMulti(rs -> Multi.createFrom().iterable(rs))
} else {
   throw new IllegalStateException("sqlClient is not PgPoolInternal");
}  
```

I would not recommend to change the scope of the `PgPool` bean at this stage. It may lead to unexpected problems.

**Comment by alexpoletaev** [comment]
Can we just use it that way?
```java
SqlTemplate.forQuery(sqlClient.getDelegate(), "select version()")
```

**Comment by mkouba** [comment]
> ```java
> sqlClient.getDelegate()
> ```

Where does this method come from?

**Comment by alexpoletaev** [comment]
> > ```java
> > sqlClient.getDelegate()
> > ```
> 
> Where does this method come from?

`io.vertx.mutiny.pgclient.PgPool`

**Comment by mkouba** [comment]
> > > ```java
> > > sqlClient.getDelegate()
> > > ```
> > 
> > 
> > Where does this method come from?
> 
> `io.vertx.mutiny.pgclient.PgPool`

That would not help because the delegate instance is the same as `@Inject io.vertx.pgclient.PgPool`.

**Comment by mocukie** [comment]
> Ladislav is right, the injected client proxy for `PgPool` must also implement `io.vertx.sqlclient.Pool` and `io.vertx.sqlclient.SqlClient` interfaces but there's no requirement or guarantee to implement `io.vertx.sqlclient.impl.SqlClientInternal` which according to the name is a internal API anyway.
> 
> You can unwrap the client proxy and obtain the underlying instance which _could be_ an instance of `PgPoolInternal`: `io.quarkus.arc.ClientProxy.unwrap(T)`. But again, it's not guaranteed so you'll need to check the runtime class before the actual use in the `SqlTemplate`.
> 
> ```java
> PgPool unwrapped = ClientProxy.unwrap(sqlClient);
> if (unwrapped instanceof PgPoolInternal) {
>    SqlTemplate.forQuery(sqlClient, "select version()")
>               .mapTo(String.class)
>               .execute(Map.of())
>               .onItem()
>               .transformToMulti(rs -> Multi.createFrom().iterable(rs))
> } else {
>    throw new IllegalStateException("sqlClient is not PgPoolInternal");
> }  
> ```
> 
> I would not recommend to change the scope of the `PgPool` bean at this stage. It may lead to unexpected problems.

Thanks, that's helpful.

Note that the smallrye version of PgPool does not work,  you need to use the unwrapped vanilla version of PgPool to build it.

**Comment by alexpoletaev** [comment]
> Ladislav is right, the injected client proxy for `PgPool` must also implement `io.vertx.sqlclient.Pool` and `io.vertx.sqlclient.SqlClient` interfaces but there's no requirement or guarantee to implement `io.vertx.sqlclient.impl.SqlClientInternal` which according to the name is a internal API anyway.
> 
> You can unwrap the client proxy and obtain the underlying instance which _could be_ an instance of `PgPoolInternal`: `io.quarkus.arc.ClientProxy.unwrap(T)`. But again, it's not guaranteed so you'll need to check the runtime class before the actual use in the `SqlTemplate`.
> 
> ```java
> PgPool unwrapped = ClientProxy.unwrap(sqlClient);
> if (unwrapped instanceof PgPoolInternal) {
>    SqlTemplate.forQuery(sqlClient, "select version()")
>               .mapTo(String.class)
>               .execute(Map.of())
>               .onItem()
>               .transformToMulti(rs -> Multi.createFrom().iterable(rs))
> } else {
>    throw new IllegalStateException("sqlClient is not PgPoolInternal");
> }  
> ```
> 
> I would not recommend to change the scope of the `PgPool` bean at this stage. It may lead to unexpected problems.

Is there a 100% working decision, especially if I need to make several calls in one transaction? I need to use a Vertx Sql Template in my Quarkus project, by I'm getting this exception despite the fact I'm unwrapping the smallrye `PgPool`  as it's described in the workaround

**Comment by tsegismont** [comment]
If you don't use `PgPoolCreator`, or don't create a `PgPool` with anything else than Quarkus or Vert.x API, the object will be an instance of `PgPoolInternal`.

**Comment by alexpoletaev** [comment]
> If you don't use `PgPoolCreator`, or don't create a `PgPool` with anything else than Quarkus or Vert.x API, the object will be an instance of `PgPoolInternal`.

So, it should work that way, right? I'm expecting that Quarkus must work correctly with all the Vertx tools as it's mentioned in the Quarkus docs.
So, I have this POJO
```java
@DataObject
@JsonGen
@RowMapped(formatter = SnakeCase.class)
@ParametersMapped(formatter = SnakeCase.class)
public class Aircraft {

    public Aircraft() {
    }

    public Aircraft(JsonObject jsonObject) {
        AircraftConverter.fromJson(jsonObject, this);
    }

    private String aircraftCode;
    private JsonObject model;
    private Integer range;

    public JsonObject toJson() {
        JsonObject json = new JsonObject();
        AircraftConverter.toJson(this, json);
        return json;
    }
    
    // getters/setters
}
```
DAO object:
```java
@ApplicationScoped
public class AircraftDao {

    @Inject
    io.vertx.mutiny.pgclient.PgPool client;

    public Uni<Aircraft> create(Aircraft aircraft) {
        return SqlTemplate.forUpdate(ClientProxy.unwrap(client), "insert into aircrafts_data values (#{aircraft_code}, #{model}::jsonb, #{range})")
                .mapFrom(AircraftParametersMapper.INSTANCE)
                .execute(aircraft)
                .replaceWith(aircraft);
    }
}
```
and finally resource:
```java
@Path("/aircrafts")
public class AircraftResource {

    @Inject
    AircraftDao dao;

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    public Uni<Aircraft> create(Aircraft aircraft) {
        return dao.create(aircraft);
    }
}
```
When I'm trying to create an aircraft entity using rest API, I'm getting this exception:

> java.lang.ClassCastException: class io.vertx.pgclient.PgPool_7weXgYHcaRck_k2l7dGKfXZMdD8_Synthetic_ClientProxy cannot be cast to class io.vertx.sqlclient.impl.SqlClientInternal (io.vertx.pgclient.PgPool_7weXgYHcaRck_k2l7dGKfXZMdD8_Synthetic_ClientProxy and io.vertx.sqlclient.impl.SqlClientInternal are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6328d34a)

Could you please tell me what I'm doing wrong?

**Comment by mkouba** [comment]
> Could you please tell me what I'm doing wrong?

@alexpoletaev You need to (A) inject `io.vertx.sqlclient.Pool` instead of the Mutiny version (`io.vertx.mutiny.pgclient.PgPool`) or (B) obtain the delegate first, i.e. `ClientProxy.unwrap(client.getDelegate())`. In other words, the Mutiny version of `PgPool` is not an instance of `PgPoolInternal`.

**Comment by alexpoletaev** [comment]
> > Could you please tell me what I'm doing wrong?
> 
> @alexpoletaev You need to (A) inject `io.vertx.sqlclient.Pool` instead of the Mutiny version (`io.vertx.mutiny.pgclient.PgPool`) or (B) obtain the delegate first, i.e. `ClientProxy.unwrap(client.getDelegate())`. In other words, the Mutiny version of `PgPool` is not an instance of `PgPoolInternal`.

@mkouba, if I understood correctly, your advice applies for the native (vertx) SQL Template library. And I agree, it works correctly, thank you for that. But this issue is related to the Mutiny SQL Template library. The `SqlTemplate.forUpdate` method requires an instance of the `io.vertx.mutiny.sqlclient.SqlClient` class. How I can make the example, I provided early, work with the Mutiny realization of the SQL Template library?

**Comment by mkouba** [comment]
> > > Could you please tell me what I'm doing wrong?
> > 
> > 
> > @alexpoletaev You need to (A) inject `io.vertx.sqlclient.Pool` instead of the Mutiny version (`io.vertx.mutiny.pgclient.PgPool`) or (B) obtain the delegate first, i.e. `ClientProxy.unwrap(client.getDelegate())`. In other words, the Mutiny version of `PgPool` is not an instance of `PgPoolInternal`.
> 
> @mkouba, if I understood correctly, your advice applies for the native (vertx) SQL Template library. And I agree, it works correctly, thank you for that. But this issue is related to the Mutiny SQL Template library. The `SqlTemplate.forUpdate` method requires an instance of the `io.vertx.mutiny.sqlclient.SqlClient` class. How I can make the example, I provided early, work with the Mutiny realization of the SQL Template library?

I see. 

Hm, the `io.vertx.mutiny.sqlclient.templates.SqlTemplate#forUpdate()` looks like:

```java
public static io.vertx.mutiny.sqlclient.templates.SqlTemplate<java.util.Map<String, java.lang.Object>, io.vertx.mutiny.sqlclient.SqlResult<Void>> forUpdate(io.vertx.mutiny.sqlclient.SqlClient client, String template) { 
    io.vertx.mutiny.sqlclient.templates.SqlTemplate<java.util.Map<String, java.lang.Object>, io.vertx.mutiny.sqlclient.SqlResult<Void>> ret = io.vertx.mutiny.sqlclient.templates.SqlTemplate.newInstance((io.vertx.sqlclient.templates.SqlTemplate)io.vertx.sqlclient.templates.SqlTemplate.forUpdate(client.getDelegate(), template), TypeArg.unknown(), TYPE_ARG_1);
    return ret;
}
```

I.e. it instantiates a new `io.vertx.sqlclient.templates.SqlTemplate` with `client.getDelegate()`. So one thing you could do is to inject the vanilla `io.vertx.sqlclient.PgPool` and then create a new instance of `io.vertx.mutiny.sqlclient.SqlClient` but pass the unwrapped `PgPool`. Something like:

```java
@Inject io.vertx.sqlclient.PgPool pool;

// ...and then
io.vertx.mutiny.sqlclient.SqlClient client = new SqlClient(ClientProxy.unwrap(pool));
SqlTemplate.forUpdate(client, "insert into aircrafts_data values (#{aircraft_code}, #{model}::jsonb, #{range})");

```

**Comment by alexpoletaev** [comment]
> > > > Could you please tell me what I'm doing wrong?
> > > 
> > > 
> > > @alexpoletaev You need to (A) inject `io.vertx.sqlclient.Pool` instead of the Mutiny version (`io.vertx.mutiny.pgclient.PgPool`) or (B) obtain the delegate first, i.e. `ClientProxy.unwrap(client.getDelegate())`. In other words, the Mutiny version of `PgPool` is not an instance of `PgPoolInternal`.
> > 
> > 
> > @mkouba, if I understood correctly, your advice applies for the native (vertx) SQL Template library. And I agree, it works correctly, thank you for that. But this issue is related to the Mutiny SQL Template library. The `SqlTemplate.forUpdate` method requires an instance of the `io.vertx.mutiny.sqlclient.SqlClient` class. How I can make the example, I provided early, work with the Mutiny realization of the SQL Template library?
> 
> I see.
> 
> Hm, the `io.vertx.mutiny.sqlclient.templates.SqlTemplate#forUpdate()` looks like:
> 
> ```java
> public static io.vertx.mutiny.sqlclient.templates.SqlTemplate<java.util.Map<String, java.lang.Object>, io.vertx.mutiny.sqlclient.SqlResult<Void>> forUpdate(io.vertx.mutiny.sqlclient.SqlClient client, String template) { 
>     io.vertx.mutiny.sqlclient.templates.SqlTemplate<java.util.Map<String, java.lang.Object>, io.vertx.mutiny.sqlclient.SqlResult<Void>> ret = io.vertx.mutiny.sqlclient.templates.SqlTemplate.newInstance((io.vertx.sqlclient.templates.SqlTemplate)io.vertx.sqlclient.templates.SqlTemplate.forUpdate(client.getDelegate(), template), TypeArg.unknown(), TYPE_ARG_1);
>     return ret;
> }
> ```
> 
> I.e. it instantiates a new `io.vertx.sqlclient.templates.SqlTemplate` with `client.getDelegate()`. So one thing you could do is to inject the vanilla `io.vertx.sqlclient.PgPool` and then create a new instance of `io.vertx.mutiny.sqlclient.SqlClient` but pass the unwrapped `PgPool`. Something like:
> 
> ```java
> @Inject io.vertx.sqlclient.PgPool pool;
> 
> // ...and then
> io.vertx.mutiny.sqlclient.SqlClient client = new SqlClient(ClientProxy.unwrap(pool));
> SqlTemplate.forUpdate(client, "insert into aircrafts_data values (#{aircraft_code}, #{model}::jsonb, #{range})");
> ```

That works, thank you very much! But don't you think this looks like a workaround\hack? It's really not obvious. Maybe we should reopen this issue?

**Comment by mkouba** [comment]
> That works, thank you very much! But don't you think this looks like a workaround\hack? It's really not obvious. Maybe we should reopen this issue?

Yes, it is a workaround.

The only thing we could do on Quarkus side is to modify the `PgPool` bean in a way that it would also implement `io.vertx.sqlclient.impl.SqlClientInternal` which is obviously an internal implementation detail and it's not guaranteed that the produced instance will implement this interface. TBH it feels weird that `io.vertx.sqlclient.templates.SqlTemplate` accepts `io.vertx.sqlclient.SqlClient` but requires an implementation of `io.vertx.sqlclient.impl.SqlClientInternal` :shrug:.

NOTE for @cescoffier: changing the scope would not help because the `PgPool` bean is synthetic and defines the set of bean types explicitly.

**Comment by alexpoletaev** [comment]
@mkouba, since it's a workaround I believe that we need an **open** issue to be able to track progress on that, no matter how the fix will be implemented in quarkus. Otherwise everybody just forget about that. What do you think? Maybe we should reopen this issue?

**Comment by mkouba** [comment]
> @mkouba, since it's a workaround I believe that we need an **open** issue to be able to track progress on that, no matter how the fix will be implemented in quarkus. Otherwise everybody just forget about that. What do you think? Maybe we should reopen this issue?

TBH I'm not sure this could/should be fixed in Quarkus.

Is it a good idea to add `SqlClientInternal` to the set of bean types of the `PgPool` bean? I mean is it guaranteed that the underlying instance will always implement this interface? @cescoffier @vietj

**Comment by cescoffier** [comment]
@mkouba At the moment yes.... but we cannot tell you for how long.

**Comment by mkouba** [comment]
> @mkouba At the moment yes.... but we cannot tell you for how long.

That's what I expected and the reason why I hesitate to implement the aforementioned "fix" :shrug:.
