### ISSUE TITLE
quarkus.native.enabled=false is not reflected when maven profile has <id>native</id>

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#39669]
### Describe the bug

quarkus.native.enabled=false is not reflected when maven profile has <id>native</id>

This got noticed after https://github.com/quarkusio/quarkus/pull/39295 change CC @dmlloyd 

Generated Quarkus applications always have native profile with <id>native</id>.

### Expected behavior

quarkus.native.enabled=false is gets reflected even if maven profile has <id>native</id>

### Actual behavior

quarkus.native.enabled=false is not reflected when maven profile has <id>native</id>

native build is performed

### How to Reproduce?

 - Build the latest Quarkus
 - Use [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/14742683/code-with-quarkus.zip)
 - Run `mvn clean verify -DskipTests -Dnative`
 - Check the log to see NativeImageBuildRunner in action

Change the maven profile id to see that `<quarkus.native.enabled>false</quarkus.native.enabled>` settings get reflected.

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus main a7ce8110af6

**Comment by dmlloyd** [comment]
Before this PR, if I changed the package-type away from `native` when the native profile was enabled, would it work? I'm having a hard time isolating the specific change which caused this issue to start.

**Comment by gsmet** [comment]
I'm sorry but can the issue happen in a plausible scenario? Because I don't see the point of changing the native profile to not build in native.

Now if there is a plausible scenario when this is a pain point, I agree we should fix it.

**Comment by dmlloyd** [comment]
Never mind, I did find the problem and it is a behavior change. Before we would check to see if the Maven project properties or the system properties contained the package type key and would only selectively override the package type. But I mistakenly removed that logic. The fix is pretty minimal.

**Comment by gsmet** [comment]
Cool, thanks David!
