### ISSUE TITLE
Rest client filter does not add header when sending input stream

### ISSUE THREAD

**Issue by mcanzerini** [quarkusio/quarkus#39671]
### Describe the bug

I have a `ClientRequestFilter` which add an `Authorization` header to requests.
Everything works fine in quarkus 3.8.2.
Since quarkus 3.8.3, it seems that the header is not added anymore to the request.
Unfortunately, I was not able to debug using `quarkus.rest-client.logging.scope=request-response`. The request in not logged, only the response (another bug maybe?)

Anyway, I guess this bug is related to this [commit](https://github.com/quarkusio/quarkus/commit/b38eb07096b429ac59ea4d510b293ba67ec69225#diff-03d3c6adcdcc01b3a1f8daccc773adc6ee1c598afa245a445a24383a77f3b3a4)

### Expected behavior

My header is added to my outgoing request

### Actual behavior

The header is not added

### Quarkus version or git rev

3.8.3

**Comment by geoand** [comment]
This has already been fixed in main and will be included in 3.8.4
