### ISSUE TITLE
Quarkus caches Failures

### ISSUE THREAD

**Issue by wesleysalimansdvb** [quarkusio/quarkus#39677]
### Describe the bug

Whenever a failure occurs such as a Timeout this failure is cached, so each subsequent call will retrieve this failure from cache (and the remote service is not called, until the cache is invalidated).

### Expected behavior

Quarkus does not cache the failure.

### Actual behavior

Quarkus caches the failure and each subsequent call for that cache key get the failure from cache (the remote service is not called)

### How to Reproduce?

```
@CacheResult(cacheName = "username")
  public Uni<String> getUsernameById(String userId) {
    return remoteApi
        .getUser(userId)
        .onFailure()
        .invoke(failure -> Log.error("Error when getUsername", failure))
        .onItem()
        .transform(User::getName);
  }
```

### Output of `uname -a` or `ver`

Darwin REDACTED 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 21.0.1 2023-10-17 LTS OpenJDK Runtime Environment Corretto-21.0.1.12.1 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.9.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by gsmet** [comment]
@gwenneg could you have a look?

Now I'm not entirely sure that's something we can fix without introducing an annotation to specify the behavior as caching the failure could be a valid behavior too.

**Comment by stefvanderweldevolksbanknl** [comment]
> @gwenneg could you have a look?
> 
> Now I'm not entirely sure that's something we can fix without introducing an annotation to specify the behavior as caching the failure could be a valid behavior too.

It doesn't seem logical to me that failures are cached, but [Exceptions are not](https://quarkus.io/guides/cache#let-exceptions-bubble-up).

**Comment by wesleysalimansdvb** [comment]
And if this is expected behaviour, what would be the recommended way to ensure that subsequent calls of a failed request *do* call the remote service and *don't* get the cached failure?

**Comment by geoand** [comment]
I consider this behavior incorrect and have opened #39762 to address it.
