### ISSUE TITLE
Provide Asyn CompletableFuture in Hibernate ORM Panache

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#3968]
Execute the query in another thread. 

Some like the example in Spring Data. 

```java
@Async
CompletableFuture<List<Post>> findByStatus(Status status);
```

**Comment by machi1990** [comment]
@FroMage is this somehow related to Panache-Rx https://github.com/quarkusio/quarkus/issues/2198, you have been working on ?

**Comment by Sparow199** [comment]
I think that adding support for CompletableFuture && Optional to wrap the responses could be interesting. Panache is already supports Java 8 Streams, so the integration will not be difficult ?
@machi1990 @FroMage, I can try to do it, if you are interested with this enhancement.

**Comment by FroMage** [comment]
We already have an issue open for `Optional`, and as I said, Async is not useful unless we have an async driver, so I was more leaning towards closing this issue…

**Comment by hantsy** [comment]
@FroMage  I think it is useful, in Spring, it can be run in another thread, see [my Spring example](https://github.com/hantsy/spring-reactive-sample/blob/master/java8/src/main/java/com/example/demo/PostRepository.java#L19). In Quarkus, this can align with Async support in Jaxrs.

**Comment by FroMage** [comment]
I can't think of a use-case where it's useful, though. Why would you want it to run in another thread? This is not at all reactive-programming where we use async IO, which requires a non-blocking driver (see reactive clients: https://quarkus.io/guides/reactive-sql-clients) but this is not supported yet in Panache.
