### ISSUE TITLE
UpxCompressionBuildStep Not Executed Since Quarkus 3.8.2

### ISSUE THREAD

**Issue by gcw-it** [quarkusio/quarkus#39699]
### Describe the bug

When building a native executable with UPX compression enabled, the compression build step is not executed in Quarkus >=3.8.2.

This happens with a direct as well as an in-container build.

### Expected behavior

The executable gets compressed.

### Actual behavior

The executable won't be compressed without any hint or warning.

### How to Reproduce?

1. Create app with Quarkus >= 3.8.2: quarkus create
2. Build the app: mvn package -Dnative -Dquarkus.native.compression.level=1
3. The executable won't be compressed.

### Output of `uname -a` or `ver`

Darwin 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_X86_64 x86_64

### Output of `java -version`

java 21.0.2 2024-01-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

Up until version 3.8.1 the compression step runs without problems.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/39069/files#r1539397175 is very suspect :)

**Comment by gcw-it** [comment]
No there isn't any output regarding ups compression. The build step simply isn't  executed.

In the correct case (quarkus < 3.8.2) these are the executed steps:
JarResultBuildStep
NativeImageBuildStep
UpxCompressionBuildStep

In the failure case (quarks >= 3.8.2) the steps are as follows:
JarResultBuildStep
NativeImageBuildStep
QuarkusAugmentor

The UpxCompressionBuildStep is simply missing.

**Comment by gsmet** [comment]
Ah, yes, silly me!

That needs to go in the next patch release, thanks a lot for your report!
