### ISSUE TITLE
Provide a more generic save method in Hibernate ORM Panache

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#3969]
Currently  the persist is provided, I can not found the merge method.

If possible provide a generic  `save` method(and `saveAll`) like Spring Data JPA. 

```java
if( Entity is new) {
     em.persist(entity)
     return entity;
}else{
     return em.merge(entity);
}
```

**Comment by dwamara** [comment]
It's strange that you write that because the merge method is implemented by the EntityManager and up til now I have been using it without any problem.
This is a piece of one of my codes and I am using Hibernate with Panache
```
    public Response.ResponseBuilder update(final UpdateTourRequest request) throws ValidationException {
        Response.ResponseBuilder responseBuilder;
        Tour tour = findTour(request.getCode());
        tour.transportation = "";
        em.merge(tour);
        responseBuilder = ok(new UpdateTourResponse(request.getCorrelationId(), objectFactory.createCommonTour(tour)));
        LOGGER.info("Tour with code {} --> {}", request.getCode(), tour);
        return responseBuilder;
    }
```

**Comment by hantsy** [comment]
@dwamara I have not found it in the `PanacheEntity` and `PanacheRepository`.

**Comment by dwamara** [comment]
@hantsy because you can find it in the EntityManager. The datasource you declare in your application.properties also serves to instantiate the EntityManager and you can then use it to merge your entities if you want.

**Comment by hantsy** [comment]
@dwamara Yes, as a workaround, it worked well. I understood your meaning. What I said is it is missing in the Quarkus's Hibernate ORM Panache.

**Comment by AlexanderHofmeister** [comment]
@dwamara I do not get your explanation about

>  because you can find it in the EntityManager. 

You can also find the method  `persist` in the entity manager and even though it is implemented in the `PanacheEntityBase`. Would you mind to explain me, why merge is not implemented yet? I mean no offense, just curious.

**Comment by loicmathieu** [comment]
@hantsy for MongoDB with Panache we provide `entity.saveOrUpdate()` that save the entity if not existing in the database otherwise update it.

Will the same functionality on Hibernate with Panache OK for you ?

Some pseudo code implementation would be :

```java
public void persistOrUpdate() {
    if(entity.isPersistent()){
        entity.persist();
    }
    else {
        em.merge(entity);
    }
}
```

Warning that as `isPersistent` uses `EntityManager.contains()` it will not works if the entity is not yet managed by the entity manager but already existant in the database.

**Comment by hantsy** [comment]
@loicmathieu  if Mongo used `saveOrUpdate`, I think use the same naming is better.

**Comment by loicmathieu** [comment]
> @loicmathieu if Mongo used saveOrUpdate, I think use the same naming is better.
This was an error of mine, I updated my comment, MongoDB with Panache uses `persistOrUpdate()` so we should use the same here.

@dwamara To make an update on an entity inside Hibernate with Panache you can load the entity from the database (via findById() for exemple) then update it's fields. There is no need to use `merge` from the Entity manager as all managed entity will have there modifications sent to the database automatically (this is standard JPA behaviour).

Anyway, I think we should ask @FroMage about this he's the Hiberate with Panache expert ;)

**Comment by FroMage** [comment]
Yeah, this is code built around unserialising the entity itself rather than a DTO which is a very dangerous way to build applications with many security risks that we don't want to promote.

**Comment by hantsy** [comment]
>. There is no need to use merge from the Entity manager as all managed entity will have there modifications sent to the database automatically (this is standard JPA behaviour).

This depends on the session/transaction boundary. If the modifying entities happen in an active session it works. `@Transcational` must ensure there is an active session available and commit the transaction when the session is close.

**Comment by loicmathieu** [comment]
@FroMage WDYT of this one ?

Should we  provides `persistOrUpdate` for Hibernate with Panache with an implementation close to what I propose here: https://github.com/quarkusio/quarkus/issues/3969#issuecomment-570586080 or should we close it ?

Maybe @Sanne has some ideas around this as well ;)

**Comment by FroMage** [comment]
Well, we're still trying to avoid exposing `merge` at this point, so let's hold.

**Comment by codespearhead** [comment]
Should this issue be closed like https://github.com/quarkusio/quarkus/pull/9759 , which is a more recent duplicate and was closed with the tag `triage/wontfix`?

Justification:
> [FroMage](https://github.com/FroMage) commented [on Jun 5, 2020](https://github.com/quarkusio/quarkus/pull/9759#issuecomment-639596950): It's super dangerous because people use entities as DTOs from REST controllers most of the time, on data that comes directly from the user, which may have bindings that they're not allowed to access (say, an isAdmin property set to true when the current user doesn't have the right to edit it) and JPA due to its behaviour of auto-flushing changes to the DB is especially susceptible to those attacks, because the user may forget to check for what fields got sent in the request before merging and even in some use-cases will forget to throw an exception or rollback the transaction to prevent those changes from hitting the DB.
> [FroMage](https://github.com/FroMage) commented [on Jun 5, 2020](https://github.com/quarkusio/quarkus/pull/9759#issuecomment-639597602): If you don't your entities as DTOs you are exempt from this type of security issue, but you also don't need merge anymore.

**Comment by FroMage** [comment]
Yeah, we can close this.
