### ISSUE TITLE
smallrye-jwt fails if keys cannot be fetched at startup

### ISSUE THREAD

**Issue by The-Funk** [quarkusio/quarkus#39698]
### Describe the bug

smallrye-jwt seems to fetch keys from the oauth provider's key endpoint only on application startup, however if this original fetch fails, the extension never retries, and all subsequent auth requests fail until the application is restarted.

### Expected behavior

If enabled, and there's a network blip at startup and the application is unable to fetch proper keys, the extension should retry fetching the keys on each successive auth request or on a schedule, or on 1 in X number of requests.

### Actual behavior

See bug description.

### How to Reproduce?

Start an application with smallrye-jwt and with your oauth provider firewalled and inaccessible or unrouteable. Once the startup process has fully completed, try authenticating (the request will fail) 

re-establish connectivity between the application and the oauth provider. Attempt authentication again (the request will still fail)

### Output of `uname -a` or `ver`

Windows 11

### Output of `java -version`

openjdk 21.0.2

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.6

**Comment by sberyozkin** [comment]
@The-Funk I think this issue should be moved to the smallrye-jwt repository because Quarkus has no control over the way it fetches the keys.

By the way, are you sure it happens on the startup and not during the first request ? AFAIK, at the moment, smallrye-jwt reads the keys at the startup only if they are local resources.

**Comment by The-Funk** [comment]
@sberyozkin understood. I will open this over there.
