### ISSUE TITLE
REST Client not sending headers when using InputStream

### ISSUE THREAD

**Issue by dominikrebhan** [quarkusio/quarkus#39697]
### Describe the bug

With Quarkus 3.8.3 the REST Client won't send any headers when the input is an InputStream. I think this is related to https://github.com/quarkusio/quarkus/pull/39265

### Expected behavior

Send input headers as before or when using no InputStreama as input.

### Actual behavior

No headers are sent.

### How to Reproduce?

`private final Client client = ClientBuilder.newClient();

    @GET
    @Path("bytes")
    @Produces(MediaType.TEXT_PLAIN)
    public int testWithBytes() throws Exception {
        var response = client.target("http://192.168.2.172:9090")
                .path("/")
                .request()
                .header("X-Test", "FOO")
                .post(Entity.entity("Hello World".getBytes(StandardCharsets.UTF_8),
                        "text/plain"));

        return response.getStatus();
    }

    @GET
    @Path("stream")
    @Produces(MediaType.TEXT_PLAIN)
    public int testWithStream() throws Exception {
        var response = client.target("http://192.168.2.172:9090")
                .path("/")
                .request()
                .header("X-Test", "FOO")
                .post(Entity.entity(new ByteArrayInputStream("Hello World".getBytes(StandardCharsets.UTF_8)),
                        "text/plain"));

        return response.getStatus();
    }`
<img width="445" alt="Bildschirmfoto 2024-03-26 um 13 00 13" src="https://github.com/quarkusio/quarkus/assets/71136398/2c73ff51-a56e-4766-b15a-465722e4d1e4">
<img width="445" alt="Bildschirmfoto 2024-03-26 um 13 00 05" src="https://github.com/quarkusio/quarkus/assets/71136398/9c97a525-dd5a-4daf-8496-ecc141df1514">

### Quarkus version or git rev

3.8.3

**Comment by geoand** [comment]
This has already been fixed in `main` and will be available with the next 3.8 release
