### ISSUE TITLE
OIDC code flow access token verification is enforced even if the application code does not use it as JWT

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#39717]
### Describe the bug

We enforced the code flow access token verification as part of #39458. FYI, with the code flow only the ID token is verified by default but not the access token which is not used for any security decisions for the current endpoint by default.  So the idea is that if the user code tries to access the access token in the code as `JsonWebToken` then it must be verified, as opposed to users having to enable it manually. 

This is a correct decision because if the user forgets to enable the code flow access token verification and the user code checks JWT claims from the unverified access token then it is not good.

Unfortunately, #39458 detects `JsonWebToken` in `io.smallrye.jwt.auth.cdi.RawClaimTypeProducer` which is not an application code.

This causes side-effects when the user code has no JsonWebToken injected, uses a provider like Google which has binary access tokens.

Reported by @alesj 

I'd really like to avoid reverting it as it is a good hardening fix. So I'd like to filter out any injection point targets which start from `io.quarkus.` (Resteasy token propagation filter has JsonWebToken injected) and `io.smallrye.jwt` packages which should be reasonable

**Comment by michalvavrik** [comment]
I'm sorry for the bug, I didn't realize what it can cause for non-application beans. thanks for the fix.
