### ISSUE TITLE
Replace Vert.x Buffer.toJson() method with Buffer.toJsonValue()

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#39712]
### Describe the bug

It's not really a bug, but currently, Quarkus uses a deprecated method: Buffer.toJson(). This method will be removed at some point. It was replaced with Buffer.toJsonValue(). We should replace our calls.

**Comment by geoand** [comment]
Are you sure we are using it?

My IDE could not find any usages of `io.vertx.core.buffer.Buffer#toJson` or `io.vertx.mutiny.core.buffer.Buffer#toJson`

**Comment by geoand** [comment]
Very likely :0
