### ISSUE TITLE
Some OIDC and smallrye-jwt beans are unremovable even if they are not used

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#39727]
### Describe the bug

@michalvavrik  had a good point about some OIDC and smallrye-jwt beans being unremovable, for example, an OIDC token propagation JWT filter, smallrye-jwt producers, and there could be more in OIDC, OIDC Client and other OIDC extensions. 
It consumes extra memory and may cause side-effects

**Comment by sberyozkin** [comment]
For filters it may be required to check annotations like `@JsonWebToken` as well as `@RegisterProvider(FilterClassName.class)`

**Comment by gsmet** [comment]
My personal recommendation would be to close this issue: adding some complex logic to potentially drop a few beans doesn't sound very attractive to me, especially if they are related to security. I would rather focus on fixing actual issues.

I will let you decide what you want to do with it. In any case, it's not a big.

**Comment by michalvavrik** [comment]
I made this point during some review and don't really remember details. I thought it wasn't so much about "unremovable" as  about registering some SR JWT beans we don't need by default. I don't remember details and I think we are at completely different place with the OIDC extension now. We are moving fast as we keep changing things. And I have very limited knowledge about SR JWT. @sberyozkin I am going to close it, please reopen if you disagree. Thanks
