### ISSUE TITLE
Authentication support for GraphQL UI

### ISSUE THREAD

**Issue by jgrabowski** [quarkusio/quarkus#39736]
### Description

GraphQL UI in dev mode should allow to authenticate/authorize the same way as SwaggerUI. Currently it's not possible to retrieve data from GraphQL API annotated with @Authenticated annotation.

**Comment by phillip-kruger** [comment]
@jmartisk in the old UI we could add headers. I can't remember if the new one has that. If so we should document it somewhere.

**Comment by phillip-kruger** [comment]
@jgrabowski it is possible, just not as simple as in swagger-ui

**Comment by jgrabowski** [comment]
Thanks! It's not that hard and it works. Anyway it's 49:55 :-)

Regards,
Jakub.

śr., 27 mar 2024 o 12:16 Phillip Krüger ***@***.***>
napisał(a):

**Comment by phillip-kruger** [comment]
Cool :)
