### ISSUE TITLE
Quarkus Smallrye-kafka connector custom kafka-configuration not working

### ISSUE THREAD

**Issue by angelfrend** [quarkusio/quarkus#39744]
### Describe the bug

As per the document https://quarkus.io/guides/kafka#kafka-configuration-resolution, we can provide custom kafka configuration using below property,
`mp.messaging.incoming.my-channel.kafka-configuration=my-configuration`

However, when I tried to use the feature, this is not working.

Sample Code :

```
package demo.config;

import io.smallrye.common.annotation.Identifier;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;

import java.util.Map;

@ApplicationScoped
public class KafkaConfig {

    @Produces
    @Identifier("my-configuration`)
    @ApplicationScoped
    Map<String, Object> customKafka() {
        return Map.ofEntries(
                Map.entry("bootstrap.servers", "http://bootstrap-server1:9092"),
                Map.entry("schema.registry.url", "http://schema-registry-1:8091")
        );
    }

    @Produces
    @Identifier("default-kafka-broker")
    @ApplicationScoped
    Map<String, Object> defaultKafka() {
        return Map.ofEntries(
                Map.entry("bootstrap.servers", "http://bootstrap-server2:9092"),
                Map.entry("schema.registry.url", "http://schema-registry-2:8091")
        );
    }
}
```

```
application.properties

ms.messaging.outgoing.notification.connector=smallrye-kafka
ms.messaging.outgoing.notification.kafka-configuration=my-configuration
ms.messaging.outgoing.notification.topic=notification topic

ms.messaging.outgoing.command.connector=smallrye-kafka
ms.messaging.outgoing.command.topic=command_topic
```
In the above application.properties, the default-kafka-broker bean is initialized and the values are used properly. However the custom Kafka configuration bean "my-configuration" is never initialized or called. Even the notification topic is initialized with the default configuration.

### Expected behavior

my-configuration bean should have been initialized and the bootstrap servers and schema registry should have been picked from there into the notification topic producer.

### Actual behavior

my-configuration is ignored and instead the default configuration is used.

### How to Reproduce?

1. Create two kafka server instances OR add entry in your etc/host file to create two aliases bootstrap-server-1 and bootstrap-server-2 and schema-registry-1 and schema-registry-2 pointing same local instance
2. Checkout https://github.com/angelfrend/quarkus-kafka-demo
3. Execute the application
4. As per the application.properties configuration, emitter-2 should get initialized with bootstrap-server-2. But it will start with bootstrap-server-1 instead which is default configuration.

### Output of `java -version`

C:\Users\rajag>java -version
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.2.0+13-2) (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.2.0+13-2) (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

<quarkus.platform.version>3.9.1</quarkus.platform.version>

### Additional information

At first, I tried using below configuration:

```
Application.properties
ms.messaging.outgoing.channel-1.connector=smallrye-kafka
ms.messaging.outgoing.channel-1.topic=topic-1
ms.messaging.outgoing.channel-1.bootstrap.servers=http://bootstrap-server-1:9092
ms.messaging.outgoing.channel-1.schema.registry.url=http://schema-registry-1:8091
ms.messaging.outgoing.channel-1.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
ms.messaging.outgoing.channel-1.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.channel-1.max.in.flight.requests.per.connection=1

ms.messaging.outgoing.channel-2.connector=smallrye-kafka
ms.messaging.outgoing.channel-2.bootstrap.servers=http://bootstrap-server-2:9092
ms.messaging.outgoing.channel-2.schema.registry.url=http://schema-registry-2:8091
ms.messaging.outgoing.channel-2.topic=topic-2
ms.messaging.outgoing.channel-2.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
ms.messaging.outgoing.channel-2.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.channel-2.max.in.flight.requests.per.connection=1


quarkus.devservices.enabled=false
quarkus.kafka.devservices.enabled=false

quarkus.log.level=INFO
quarkus.log.min-level=DEBUG
```
But the app ignored bootstrap-server configurations and configured local host bootstrap server and schema-registry which failed application.

```
2024-03-28 07:59:31,631 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-producer-thread-0) SRMSG18258: Kafka producer kafka-producer-channel-1, connected to Kafka brokers 'localhost:9092', is configured to write records to 'channel-1'
2024-03-28 07:59:31,654 INFO  [io.sma.rea.mes.kafka] (Quarkus Main Thread) SRMSG18213: Setting bootstrap.servers to localhost:9092
2024-03-28 07:59:31,655 INFO  [org.apa.kaf.com.tel.int.KafkaMetricsCollector] (smallrye-kafka-producer-thread-1) initializing Kafka metrics collector
2024-03-28 07:59:31,662 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-producer-thread-1) SRMSG18258: Kafka producer kafka-producer-channel-2, connected to Kafka brokers 'localhost:9092', is configured to write records to 'channel-2'
2024-03-28 07:59:31,685 INFO  [io.quarkus] (Quarkus Main Thread) kafka-demo 1.0-SNAPSHOT on JVM (powered by Quarkus 3.9.1) started in 2.170s. 
```
Then I have gone through the documentation and found that the default kafka configuration should be given and also a bean should be initialized if we add second kafka cluster. So I implemented the sample given in repo https://github.com/angelfrend/quarkus-kafka-demo. ( Configuration described in the beginning of topic... ) App picked up only the default configuration.

```
2024-03-28 08:11:08,964 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, confluent-registry-avro, kafka-client, messaging, messaging-kafka, smallrye-context-propagation, vertx]
2024-03-28 08:11:17,131 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-channel-2) [Producer clientId=kafka-producer-channel-2] Bootstrap broker bootstrap-server-1:9092 (id: -1 rack: null) disconnected
2024-03-28 08:11:19,120 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-channel-1) [Producer clientId=kafka-producer-channel-1] Bootstrap broker bootstrap-server-1:9092 (id: -1 rack: null) disconnected
2024-03-28 08:11:33,514 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-channel-2) [Producer clientId=kafka-producer-channel-2] Bootstrap broker bootstrap-server-1:9092 (id: -1 rack: null) disconnected
[INFO] ------------------------------------------------------------------------
```

**Comment by cescoffier** [comment]
Do you have a reproducer?

**Comment by angelfrend** [comment]
@cescoffier I have edited the topic and added a sample project in "How to reproduce" section. I also added additional information. Thanks for responding quickly.

**Comment by ozangunalp** [comment]
You've a typo in there. The config properties must start with `mp.messaging` not `ms.messaging`.
