### ISSUE TITLE
Global OIDC TokenCustomizer is ignored

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#39799]
### Describe the bug

https://github.com/quarkusio/quarkus/blob/eb566083adc6b70b85af3669439b0641e7bcecc4/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/TokenCustomizer.java#L22

says that the customizer without `@TenantFeature` is tied to every tenant. Strictly speaking I didn't try it, but after reading code I'm sure it doesn't work. We only inject customizer with the `@TenantFeature` from start - https://github.com/quarkusio/quarkus/pull/33319.

### Expected behavior

Javadocs says it should work.

### Actual behavior

I expect that customizer is ignored.

### How to Reproduce?

Drop `@TenantFeature` from ITs.

### Additional information

I'd like to refactor how `@TenantFeature` is used with the `TokenCustomizer` and JWT `Validator` and I can fix this as part of that (that's why I'm opening this issue). Noone has complained so far, which tells me it is unlikely this feature is frequently used in a global scope.

It is not documented outside of the interface Javadoc.

**Comment by sberyozkin** [comment]
There should be a test for the global one

**Comment by michalvavrik** [comment]
> There should be a test for the global one

I looked for it before I opened this issue. I'll try it eventually (not today), but I can't imagine how could it possibly work when I didn't find a code that does that. Anyway, I can be wrong.

**Comment by michalvavrik** [comment]
This issue will become irrelevant with recent refactoring of this feature - https://github.com/quarkusio/quarkus/pull/40525
