### ISSUE TITLE
Update documentation for QUARKUS AND GRADLE - Development mode: quarkusDev#workingDir has been deprecated

### ISSUE THREAD

**Issue by sdavids** [quarkusio/quarkus#39798]
### Describe the bug

`quarkusDev#workingDir` has been deprecated

https://github.com/quarkusio/quarkus/blob/eb566083adc6b70b85af3669439b0641e7bcecc4/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java#L191-L195

### Expected behavior

```kotlin
tasks.quarkusDev {
  workingDirectory = rootProject.layout.projectDirectory.asFile
}
```

### Actual behavior

```kotlin
tasks.quarkusDev {
    workingDir = rootProject.projectDir.toString()
}
```

### How to Reproduce?

https://quarkus.io/guides/gradle-tooling#dev-mode

### Additional information

Related: [Add 'rootProjectDirectory' to 'project.layout' (ProjectLayout)](https://github.com/gradle/gradle/issues/13654)

**Comment by gastaldi** [comment]
Good catch, want to submit a PR fixing that?

**Comment by sdavids** [comment]
The Gradle snippet should be updated as well.

**Comment by sdavids** [comment]
> Good catch, want to submit a PR fixing that?

Will do, later today.
