### ISSUE TITLE
Vertx SQL template mappers are not generated

### ISSUE THREAD

**Issue by alexpoletaev** [quarkusio/quarkus#39805]
### Describe the bug

Row and parameter mappers are not generated for the Vertx `@DataObject`. I'm trying to use Vertx sql template in my Quarkus project like it is described [here](https://vertx.io/docs/vertx-sql-client-templates/java/#_mapping_with_vert_x_data_objects), but required mappers are not generated, meanwhile the json converter is successfully generated.

### Expected behavior

PersonRowMapper and PersonParamMapper are successfully generated

### Actual behavior

PersonRowMapper and PersonParamMapper are not generated

### How to Reproduce?

1. extract code from the archive
2. go to the project root directory
3. execute `./gradlew clean build`
4. check the generated classes
[quarkus-sql-template.zip](https://github.com/quarkusio/quarkus/files/14817265/quarkus-sql-template.zip)

**Comment by geoand** [comment]
cc @vietj @tsegismont

**Comment by yuhaibohotmail** [comment]
[quarkus-sql-template-demo.zip](https://github.com/quarkusio/quarkus/files/14860373/quarkus-sql-template-demo.zip)
@alexpoletaev  This is a demo.

**Comment by geoand** [comment]
@yuhaibohotmail is that a working project you added?

**Comment by yuhaibohotmail** [comment]
> @yuhaibohotmail is that a working project you added?

yes，it worked  fine.

**Comment by alexpoletaev** [comment]
> [quarkus-sql-template-demo.zip](https://github.com/quarkusio/quarkus/files/14860373/quarkus-sql-template-demo.zip) @alexpoletaev This is a demo.

@yuhaibohotmail, thank you very much! But your demo uses Maven and I need a working example with Gradle. And I can't understand what I've missed, at first glance all required dependencies are in place...

**Comment by alexpoletaev** [comment]
Finally I fixed it. I missed this dependency:
`annotationProcessor 'io.smallrye.reactive:smallrye-mutiny-vertx-sql-client-templates:2.25.0'`

Here is a working example with gradle 
[quarkus-sql-template-fixed.zip](https://github.com/quarkusio/quarkus/files/14863644/quarkus-sql-template-fixed.zip)

The issue can be closed, thank you.
