### ISSUE TITLE
Flags passed to quarkus.native.container-runtime-options not recognized when separated by whitespace rather than equal sign

### ISSUE THREAD

**Issue by codespearhead** [quarkusio/quarkus#39808]
## Describe the bug

As discussed in #39670 , the configuration property `quarkus.native.container-runtime-options` fails if whitespace is used as a separator between the flag and its value instead of an equal sign.

Both syntaxes (using either an equal sign or whitespace as the separator) are supported in Podman and in the Docker CLI interface (see Additional Information section if you're using Docker).

You'll encounter the same error when using whitespace as a separator as when you misspell the flag name, for example, passing `--archh=...` instead of `--arch=...`.

- Happy Path

```bash
# BUILD SUCCESS
quarkus.native.container-runtime-options=--arch=amd64
```
- Erro Path

```bash
# BUILD FAILURE
# Error: unknown flag: --arch amd64
quarkus.native.container-runtime-options=--arch amd64
```

## Logs:

[happy_path.log](https://github.com/quarkusio/quarkus/files/14818645/happy_path.log)
[error_path.log](https://github.com/quarkusio/quarkus/files/14818646/error_path.log)

## Expected behavior

Native image builds successfully.

## Actual behavior

Native image build fails with `Error: unknown flag: --arch amd64`.

## How to Reproduce?

1. Install [SDKMAN](https://sdkman.io/install) and [Podman](https://podman.io/docs/installation).
2. Install the Java 21 (Java 17 will yield the same results) and the Quarkus CLI:

```bash
sdk install java &&
sdk install quarkus
```

3. Create a sample Quarkus project and `cd` into it.

```bash
quarkus create &&
cd code-with-quarkus
```

4. Set configuration for native image and build it:

- Happy Path

```bash
# BUILD SUCCESS

cat > src/main/resources/application.properties <<EOF && quarkus build --native > happy_path.log 2>&1
quarkus.log.level=DEBUG
quarkus.native.container-build=true
quarkus.native.container-runtime=podman
quarkus.native.container-runtime-options=--arch=amd64
EOF
```

- Error Path

```bash
# BUILD FAILURE

cat > src/main/resources/application.properties <<EOF && quarkus build --native > error_path.log 2>&1
quarkus.log.level=DEBUG
quarkus.native.container-build=true
quarkus.native.container-runtime=podman
quarkus.native.container-runtime-options=--arch amd64
EOF
```

### Output of `uname -a` or `ver`

Linux DESKTOP-OR8HCTU 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /home/wsl/.m2/wrapper/dists/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6 Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: /home/wsl/.sdkman/candidates/java/21.0.2-tem Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "5.15.146.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

### Additional information

Java 17 (17.0.10-tem) and/or [Docker](https://docs.docker.com/engine/install/) will yield the same results.

If you're using Docker:

4. Set configuration for native image and build it:

- Happy Path

```bash
# BUILD SUCCESS

cat > src/main/resources/application.properties <<EOF && quarkus build --native > happy_path.log 2>&1
quarkus.log.level=DEBUG
quarkus.native.container-build=true
quarkus.native.container-runtime=docker
quarkus.native.container-runtime-options=--platform=amd64
EOF
```

- Error Path

```bash
# BUILD FAILURE

cat > src/main/resources/application.properties <<EOF && quarkus build --native > error_path.log 2>&1
quarkus.log.level=DEBUG
quarkus.native.container-build=true
quarkus.native.container-runtime=docker
quarkus.native.container-runtime-options=--platform amd64
EOF
```

**Comment by tarishij17** [comment]
I'd like to try fixing this issue.

**Comment by dmlloyd** [comment]
This is actually working as designed. The type of the configuration property is "list of strings". For `.properties` files, lists are encoded using comma delimiters.

Changing this behavior is somewhat more difficult than one would think, mainly due to the way that Microprofile Config (the progenitor of this configuration system) requires that lists be interpreted, and also due to interactions with other file formats.

To give an example, we might want (for this property only) to allow `--foo --bar "--name=Something With Spaces"` as a way to express three arguments. One could even write a `Converter` which accepts this. However, then when we read a YAML-formatted list of arguments from `configuration.yaml`, we will run into problems because items encoded as a YAML list will fail to parse.

This is probably a solvable problem, but not at this exact moment. Some configuration architecture changes would be needed.

**Comment by dmlloyd** [comment]
I guess we should close it as "not planned"?
