### ISSUE TITLE
Rest Client - Disabling Hostname Verification not working

### ISSUE THREAD

**Issue by crilofer** [quarkusio/quarkus#39810]
### Describe the bug

As indicated [here](https://quarkus.io/guides/rest-client#disabling-hostname-verification) for Quarkus 3.9.1, the flag `quarkus.rest-client.extensions-api.verify-host` is not working properly when is set to `false`.

This is my restClient:

```
@RegisterRestClient(configKey = "remote-api")
public interface MyRemoteService {

    @GET
    @Path("/")
    Response test();

}
```
and the controller:

```
@Path("/hello")
public class GreetingResource {

    @Inject
    @RestClient
    MyRemoteService myRemoteService;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response hello() {
        return myRemoteService.test();
    }
}
```

application.properties:

```
quarkus.rest-client.remote-api.verify-host=false
quarkus.rest-client.remote-api.uri=https://self-signed.badssl.com
```

As you can see, I am using a self-signed host in order to reproduce the issue.

### Expected behavior

Proceeding with the actual request

### Actual behavior

receiving `jakarta.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException`

### How to Reproduce?

[test-ssl.zip](https://github.com/quarkusio/quarkus/files/14823373/test-ssl.zip)

**Comment by geoand** [comment]
Thanks for reporting, I'll take a look.

**Comment by geoand** [comment]
You actually need to configure the trust-store when dealing with self-signed certificates, hostname verifycation is (mostly) irrelevant

**Comment by crilofer** [comment]
I was going to use `quarkus.tls.trust-all` but is not present in the documentation anymore. What is the alternative if we don't use `trust-store`?

**Comment by geoand** [comment]
> quarkus.tls.trust-all

Have you tried it? It should work

**Comment by cescoffier** [comment]
Trust all and hostname verification are two different things. You probably only need trust-all and not the verification (or your self-signed certs are very broken). 

I would strongly recommend that you use a trust store. The usage of trust-all is a test only thing that hopefully will disappear at some point.
