### ISSUE TITLE
CxfClient with ComplexTypes fails on subsequent re-runs of quarkus test.

### ISSUE THREAD

**Issue by akil-rails** [quarkusio/quarkus#39811]
### Describe the bug

1. When a CxfClient that has only primitive types is injected in a @QuarkusTest, all works fine (including re-runs of the test)
2. When a CxfClient that has a complex type is injected in a @QuarkTest, the test passes once, and fails on every subsequent re-run, and works again when quarkus test is exited and re-started
3. When 2 CxfClient's are injected in separate @QuarkusTest, neither tests pass, one has to be commented out.

### Expected behavior

1. CxfClient with Complex Types should support continuous tests (quarkus test - re-run)
2. Multiple CxfClient should work without causing conflicts with each other.

### How to Reproduce?

[Reproducer](https://github.com/akil-rails/spike-quarkus-cxf/tree/main)
The steps are mentioned in ReadMe.

### Output of `uname -a` or `ver`

Darwin Akhileshs-Air.domain.name 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112 arm64

### Output of `java -version`

openjdk version "21" 2023-09-19 LTS OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS) OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode)

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /Users/akil/.m2/wrapper/dists/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6 Java version: 21, vendor: Eclipse Adoptium, runtime: /Users/akil/.sdkman/candidates/java/21-tem Default locale: en_IN, platform encoding: UTF-8 OS name: "mac os x", version: "14.4.1", arch: "aarch64", family: "mac"

### Additional information

Adding a @RequestWrapper annotation removes this error - but this annotation is optional, and should not be required.

**Comment by geoand** [comment]
Thanks for reporting, but I am pretty sure this should be reported [here](https://github.com/quarkiverse/quarkus-cxf).

This isn't a Quarkus
