### ISSUE TITLE
Fatal error compiling: error: release version 17 not supported

### ISSUE THREAD

**Issue by jxtpro** [quarkusio/quarkus#39820]
### Describe the bug

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project kubernetes-quickstart: Fatal error compiling: 错误: 不支持发行版本 17 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

### Actual behavior

./mvnw install is working

### Output of `uname -a` or `ver`

Linux xujie-system 6.5.13-7-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Dec 20 07:15:58 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.10" 2024-01-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 17.0.10+11.1 (build 17.0.10+11-LTS-jvmci-23.0-b27) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.10+11.1 (build 17.0.10+11-LTS-jvmci-23.0-b27, mixed mode, sharing)

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

/home/xujie/桌面/kubernetes-quickstart Found /home/xujie/桌面/kubernetes-quickstart/.mvn/wrapper/maven-wrapper.jar [INFO] Apache Maven Wrapper 3.2.0 [INFO] Detected MVNW_REPOURL environment variable https://maven.aliyun.com/repository/public Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /home/xujie/.m2/wrapper/dists/apache-maven-3.9.6-bin/80151456/apache-maven-3.9.6 Java version: 17.0.10, vendor: N/A, runtime: /usr/lib/jvm/java-17-openjdk Default locale: zh_CN, platform encoding: UTF-8 OS name: "linux", version: "6.5.13-7-manjaro", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Does `./mvnw -X install` give any useful information?

**Comment by iocanel** [comment]
I think that we need more info.

**Comment by jxtpro** [comment]
Now it's normal
