### ISSUE TITLE
Property `quarkus.management.port` is ignored if passed on CLI during OpenShift deployment

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#39838]
### Describe the bug

I have an application, which uses separate management interface[1] and deployed on OCP via `quarkus-openshift` extension. When I use property `quarkus.management.port` to change the port of the interface, app fails to start on the OpenShift due to "connection refused" during health check. This doesn't happen, when I put hte option into application.properties file.

[1] https://quarkus.io/guides/management-interface-reference

### Expected behavior

The way the property is provided should not affect the result.

### Actual behavior

According to the app logs, management interface listens on the default port 9000, not the chaned one.

### How to Reproduce?

1. Clone: `git clone git@github.com:fedinskiy/reproducer.git -b openshift-extension-management`
2. Create new openshift project: `oc new-project fd-reproducer`
3. Deploy the app: `mvn clean install -Dquarkus.management.port=9002`
4. Check the events:
```
$ oc get events | grep "probe"
5m58s       Warning   Unhealthy           pod/openshift-quickstart-c4dcf74dc-bxdt2     Startup probe failed: Get "http://$EDITED:9002/q/health/started": dial tcp $EDITED:9002: connect: connection refused
5m58s       Normal    Killing             pod/openshift-quickstart-c4dcf74dc-bxdt2     Container openshift-quickstart failed startup probe, will be restarted
```
5. Check the logs:
```
$oc logs  pod/openshift-quickstart-c4dcf74dc-bxdt2
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
<...>
2024-04-02 15:31:26,990 INFO  [io.quarkus] (main) openshift-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.9.1) started in 0.767s. Listening on: http://0.0.0.0:8080. Management interface listening on http://0.0.0.0:9000.
```

If property `quarkus.management.port=9002` put into the application.properties, the app starts. Same happens, when we use Quarkus 3.8.3, eg by adding option `-Dquarkus.platform.version=3.8.3`

### Output of `uname -a` or `ver`

6.7.3-200.fc39.x86_64

### Output of `java -version`

Java version: 21.0.1, vendor: Eclipse Adoptium

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by geoand** [comment]
I assume this can be reproduced locally as well right?

**Comment by fedinskiy** [comment]
@geoand no, it can not. If the app started  with `mvn quarkus:dev -Dquarkus.management.port=9002`, then the management interface listens on port 9002.

**Comment by geoand** [comment]
How about if you build with `mvn package` and run with `java -jar target/quarkus-app/quarkus-run.jar`?

**Comment by fedinskiy** [comment]
In that case the property is ignored as well:
```
java -jar target/quarkus-app/quarkus-run.jar -Dquarkus.management.port=9002
$ java -jar target/quarkus-app/quarkus-run.jar -Dquarkus.management.port=9002 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-04-03 11:50:47,403 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.openshift.route.expose" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-04-03 11:50:47,403 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.kubernetes.deploy" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-04-03 11:50:47,403 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.kubernetes-client.trust-certs" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-04-03 11:50:47,712 INFO  [io.quarkus] (main) openshift-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.9.1) started in 0.479s. Listening on: http://0.0.0.0:8080. Management interface listening on http://0.0.0.0:9000.
```

**Comment by geoand** [comment]
The problem is that you are not passing JVM System Properties to the applicaiton properly.

You need to do:

```
java -Dquarkus.management.port=9002 -jar target/quarkus-app/quarkus-run.jar
```

instead of 

```
java -jar target/quarkus-app/quarkus-run.jar -Dquarkus.management.port=9002
```

**Comment by geoand** [comment]
The problem with the OpenShift side of things is that the manifests are generated with the management port overriden for the container port, but the application itself does not have this information (because remember it's a runtime property) so it starts on `9000`.

Theoretically we could enhance the `Deployment` to also set `JAVA_OPTS_APPEND` to `-Dquarkus.management.port=9002`, WDYT @iocanel ?

**Comment by fedinskiy** [comment]
In that case it works locally, thanks.

@geoand why did you close the issue? It still fails on openshift.

**Comment by geoand** [comment]
I explained above - what you are trying to do is debatable if it should work on not.

**Comment by fedinskiy** [comment]
@geoand why is it "debatable"? The property is described[1] as a "run-time", so it should be possible to overload it. Overloading works locally, but not on Openshift. Additionally, it worked fine for Openshift on previous versions. Sounds like a text-book example of a regression to me.

[1] https://quarkus.io/guides/management-interface-reference#quarkus-management-management-management-interface-configuration_quarkus-management-port

**Comment by geoand** [comment]
> why is it "debatable"? The property is described[1] as a "run-time", so it should be possible to overload it.

The debatable (without the quotes) because you are setting a runtime property at build time.

> Sounds like a text-book example of a regression to me.

Stuff that worked in the past by accident are definitely not text book regressions.


Having said all that, I don't think it will be too much trouble to make it work (as I mentioned above) without that meaing that it's semantically correct.
I'll leave that decision to @iocanel

**Comment by fedinskiy** [comment]
Does Quarkus not allow to "set a runtime property at build time"? Is it documented somewhere?

The only thing I see currently is this[1]: `Configuration property fixed at build time - All other configuration properties are overridable at runtime`, which doesn't put any limitations on runtime properties


[1] https://quarkus.io/guides/config-reference

**Comment by geoand** [comment]
> Does Quarkus not allow to "set a runtime property at build time"? 

This is an oxymoron as `runtime` means when the application is **actually launches** and build time means when the application is **built**. 
I'll concede that in the case of generating Kubernetes / OpenShift manifests things are a little fuzzy since the runtime properties need to be configured in the manifest. but as I said before, we could support that but it's a hack.

**Comment by radcortez** [comment]
> And I am also going to guess that this worked in the past because we (probably incorrectly) "captured" the values of the system properties used at build time and used them as the default values of runtime properties. @radcortez can you confirm that we used to do this and we no longer do?

Correct. This was fixed with https://github.com/quarkusio/quarkus/pull/39604
