### ISSUE TITLE
Compilation error in WebSocketSessionContext with GraalVM SDK 22

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#39846]
When compiling with the GraalVM JDK 22, I get the following error:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project quarkus-websockets-next: Compilation failure
> [ERROR] /home/gsmet/git/quarkus/extensions/websockets-next/server/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSessionContext.java:[228,40] variable IS_VALID might not have been initialized

I'm not entirely sure if it's a problem with the code or with the GraalVM JDK:

https://github.com/quarkusio/quarkus/blob/b870f323fc902285dbc67ed4b64f46b73bfe4b83/extensions/websockets-next/server/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSessionContext.java#L228-L236

(discovered that by mistake as I forgot resetting my JDK after testing something)

/cc @zakkak @mkouba

**Comment by mkouba** [comment]
Hm, we use the same code in (i.e. the code was copied from) the `io.quarkus.arc.impl.RequestContext.RequestContextState`. The only difference is that `SessionContextState` is not static, i.e. it's an inner class. We can change that if it helps...

**Comment by gsmet** [comment]
I confirm making the nested class static fixes the issue: https://github.com/quarkusio/quarkus/pull/39855
