### ISSUE TITLE
Reactive Debezium Outbox extension commits database changes in new, separate transaction

### ISSUE THREAD

**Issue by ArDrift** [quarkusio/quarkus#39848]
### Describe the bug

I'm trying to apply the transactional outbox pattern for inter-microservice communication. In order to ease that, I tried out the [Debezium Quarkus Outbox _Reactive_ extension](https://quarkus.io/extensions/io.debezium/debezium-quarkus-outbox-reactive/), since I'm using the reactive programming approach (this includes hibernate-reactive with panache, pg-reactive client, etc.).

As consistency is really important in my project, after having written the necessary code, I first checked to see if the entity's database is modified in the **same** database transaction as the outbox table's insert (AFAIK this is an essential part of the [transactional outbox pattern](https://microservices.io/patterns/data/transactional-outbox.html)).

To my surprise, the outbox extension starts a new, separate transaction for this insert, no matter how I tried to control the transaction boundaries (I followed the respective guides on quarkus.io, tried wrapping the whole code with `Panache.withTransaction()` or annotating the method with `@WithTransaction`, without luck).

Am I missing something here, or could it be that the "same transaction" aspect of the outbox pattern was forgotten in the reactive debezium outbox extension?

Thank you for your help in advance!

P.S.: Although not part of the main Quarkus repo, I found [these lines](https://github.com/debezium/debezium/blob/main/debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/AbstractEventDispatcher.java#L41) that I think are related to this issue. For me it does not seem like the extension tries to make sure that it reuses an already existing transaction, but I can easily be wrong here.

### Expected behavior

When using the Debezium Quarkus Outbox Reactive extension, the modification in the entity table of the database should happen in the **same** database transaction as the insert to the outbox table caused by the outbox extension, as per the transactional outbox pattern.
This transactionality is essential to guarantee consistence between the service's inner state and the services observing its outbox table for communication.

### Actual behavior

I checked the transactions with Postgres using the virtual transaction IDs and also by defining constraints to make the entity update fail, but the outbox insert did not fail with it, so it couldn't have been in the same transaction as the update (it should have also been rolled back).
Examining the virtual tx ids resulted in the same finding, the two are unfortunately separate transactions.

### How to Reproduce?

I do not have one currently, but I can put one together if needed.

### Output of `uname -a` or `ver`

Linux fedora 6.7.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar  6 19:35:04 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.22" 2024-01-16 OpenJDK Runtime Environment (Red_Hat-11.0.22.0.7-1) (build 11.0.22+7) OpenJDK 64-Bit Server VM (Red_Hat-11.0.22.0.7-1) (build 11.0.22+7, mixed mode, sharing)

### Quarkus version or git rev

3.2.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (Red Hat 3.9.1-3) Maven home: /usr/share/maven Java version: 11.0.22, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.22.0.7-1.fc39.x86_64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.7.9-200.fc39.x86_64", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
I am pretty sure this should be reported in the extension's repo. 

cc @Naros

**Comment by ArDrift** [comment]
> I am pretty sure this should be reported in the extension's repo.
> 
> cc @Naros

I'm sorry this wasn't obvious at first, but you're right. I have opened a new bug report in Debezium's Jira: https://issues.redhat.com/browse/DBZ-7735

**Comment by geoand** [comment]
🙏🏼

**Comment by Naros** [comment]
Thanks @ArDrift and @geoand, I'll look at this at the top of my day tomorrow 👍
