### ISSUE TITLE
Create quarkus-sentry Extension

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#3985]
**Description**
This extension would add sentry support, the idea would be that when the sentry extension is enabled, you configure `quarkus.sentry.dsn` and you are done.

**Implementation ideas**
Here are some leads to implement it provided by @dmlloyd:
> basically logging is configured in `io.quarkus.deployment.logging.LoggingResourceProcessor`
the configuration is held in `io.quarkus.runtime.logging.LogConfig` and its members
in order to add Sentry support, we'd need to do one of two possible things
one would be to add a Sentry extension which adds a new configuration root, for example `LogSentryConfig`, and then has configuration options similar to the existing `ConsoleConfig`, `FileConfig`, etc.
then it would have a processor which produces a new build item that would be added to the core module, for example `LogHandlerBuildItem`, which the `LoggingResourceProcessor` would consume to complete the handler setup
so that's option one
option two would be to add a generic handler config to `LogConfig`
something like `Map<String, CustomHandler> customHandlers;` with a `CustomHandler` class that includes a class name and some generic way to set up the custom handler

**Comment by rkraneis** [comment]
In the meantime, something like this could help:
https://github.com/quarkusio/quarkus/issues/1847 (additionally registering SentryHandler and configuring the `ConsoleHandler` with `PatternFormatter` as is done in https://github.com/quarkusio/quarkus/blob/6cb8707e56b16100e2ec27b67f975da3237eeb6a/core/runtime/src/main/java/io/quarkus/runtime/logging/InitialConfigurator.java#L46).
