### ISSUE TITLE
Quarkus crashes and the pod can't restart

### ISSUE THREAD

**Issue by ihepda** [quarkusio/quarkus#39853]
### Describe the bug

Dear all, 
I'm using quarkus version 3.9.1/openjdk 21 with Docker container and K8s.
Some of our micro-services crashed without a known reason but the real problem is the pod can't restart well because quarkus continues to crash at startup with this error and we have a lot af restarts until the crashloopbackoff:

> Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
> INFO exec -a "java" java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -cp "." -jar /deployments/quarkus-run.jar
> INFO running in /deployments
> __  ____  __  _____   ___  __ ____  ______
>  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
>  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
> --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
> 2024-04-02 16:04:23.311 [] WARN  traceId=, parentId=, spanId=, sampled= [io.qu.config] (main) Unrecognized configuration key "quarkus.jacoco.excludes" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
> 2024-04-02 16:04:23.311 [] WARN  traceId=, parentId=, spanId=, sampled= [io.qu.config] (main) Unrecognized configuration key "quarkus.grpc.server.enable" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
> 2024-04-02 16:04:23.312 [] WARN  traceId=, parentId=, spanId=, sampled= [io.qu.config] (main) Unrecognized configuration key "quarkus.cache.caffeine."expressionLanguage"maximum-size" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
> 2024-04-02 16:04:23.312 [] WARN  traceId=, parentId=, spanId=, sampled= [io.qu.config] (main) Unrecognized configuration key "quarkus.jacoco.includes" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
> 2024-04-02 16:04:42.210 [] WARN  traceId=, parentId=, spanId=, sampled= [io.qu.ru.co.DeprecatedRuntimePropertiesRecorder] (main) The 'quarkus.log.console.color' config property is deprecated and should not be used anymore
> 2024-04-02 16:04:49.901 [] WARN  traceId=, parentId=, spanId=, sampled= [io.qu.gr.ru.GrpcServerRecorder] (main) Using legacy gRPC support, with separate new HTTP server instance. Switch to single HTTP server instance usage with quarkus.grpc.server.use-separate-server=false property
> 2024-04-02 16:04:51.206 [] INFO  traceId=, parentId=, spanId=, sampled= [io.qu.gr.ru.GrpcServerRecorder] (vert.x-eventloop-thread-1) Started gRPC server on 0.0.0.0:9000 [TLS enabled: false]
> 2024-04-02 16:04:52.312 [] INFO  traceId=, parentId=, spanId=, sampled= [io.quarkus] (main) dossier 1.0-SNAPSHOT on JVM (powered by Quarkus 3.9.1) started in 35.798s. Listening on: http://0.0.0.0:8080
> 2024-04-02 16:04:52.313 [] INFO  traceId=, parentId=, spanId=, sampled= [io.quarkus] (main) Profile prod activated.
> 2024-04-02 16:04:52.402 [] INFO  traceId=, parentId=, spanId=, sampled= [io.quarkus] (main) Installed features: [agroal, cache, cdi, grpc-client, grpc-server, hibernate-validator, kubernetes, micrometer, mongodb-client, mongodb-panache, narayana-jta, opentelemetry, resteasy, resteasy-client, resteasy-jackson, scheduler, security, smallrye-context-propagation, smallrye-health, smallrye-jwt, vertx]
> 2024-04-02 16:04:52.406 [] DEBUG traceId=, parentId=, spanId=, sampled= [be.di.do.se.DossierService] (executor-thread-128) checkDossierScaduti: Starting to remove old dessiers
> 2024-04-02 16:04:53.414 [] ERROR traceId=, parentId=, spanId=, sampled= [be.di.do.se.DossierService] (executor-thread-128) checkDossierScaduti: Error to update invalid dossiers [Error Occurred After Shutdown]:java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.instance(java.lang.Class, java.lang.annotation.Annotation[])" because the return value of "io.quarkus.arc.Arc.container()" is null
>         at io.quarkus.mongodb.panache.common.runtime.BeanUtils.clientFromArc(BeanUtils.java:35)
>         at io.quarkus.mongodb.panache.common.runtime.MongoOperations.mongoDatabase(MongoOperations.java:399)
>         at io.quarkus.mongodb.panache.common.runtime.MongoOperations.mongoCollection(MongoOperations.java:193)
>         at io.quarkus.mongodb.panache.common.runtime.MongoOperations.executeUpdate(MongoOperations.java:775)
>         at io.quarkus.mongodb.panache.common.runtime.MongoOperations.update(MongoOperations.java:765)
>         at be.digitech.dossier.entity.Dossier.update(Dossier.java)
>         at be.digitech.dossier.service.DossierService.checkDossierScaduti(DossierService.java:1027)
>         at be.digitech.dossier.service.DossierService_Subclass.checkDossierScaduti$$superforward(Unknown Source)
>         at be.digitech.dossier.service.DossierService_Subclass$$function$$38.apply(Unknown Source)
>         at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
>         at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
>         at io.quarkus.micrometer.runtime.MicrometerTimedInterceptor.timedMethod(MicrometerTimedInterceptor.java:79)
>         at io.quarkus.micrometer.runtime.MicrometerTimedInterceptor_Bean.intercept(Unknown Source)
>         at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
>         at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
>         at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
>         at be.digitech.dossier.service.DossierService_Subclass.checkDossierScaduti(Unknown Source)
>         at be.digitech.dossier.service.DossierService_ClientProxy.checkDossierScaduti(Unknown Source)
>         at be.digitech.dossier.service.DossierService_ScheduledInvoker_checkDossierScaduti_69b335ef1dded47c824a851ecb4049b50416cc31.invokeBean(Unknown Source)
>         at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
>         at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
>         at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask.doInvoke(SimpleScheduler.java:443)
>         at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$2.call(SimpleScheduler.java:425)
>         at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$2.call(SimpleScheduler.java:422)
>         at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
>         at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
>         at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
>         at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
>         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
>         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
>         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
>         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> 2024-04-02 16:04:53.701 [] INFO  traceId=, parentId=, spanId=, sampled= [io.quarkus] (main) dossier stopped in 1.100s

We must destroy the pod and create a new one (kubectl scale ... --replicas=0  kubectl scale ... --replicas=1), The old pod still unusable.

The starting problem, at the moment, is not known because the pod restart clears logs.

We are using this docker image

> FROM registry.access.redhat.com/ubi8/openjdk-21:1.19
> 
> ENV LANGUAGE='en_US:en'
> 
> 
> # We make four distinct layers so if there are application changes the library layers can be re-used
> COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
> COPY --chown=185 target/quarkus-app/*.jar /deployments/
> COPY --chown=185 target/quarkus-app/app/ /deployments/app/
> COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/
> 
> EXPOSE 8080
> USER 185
> ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
> ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
> 

### Expected behavior

After the crash the restarted pod must work fine.

### Actual behavior

The pod restart continuously because quarkus goes in error (see above) unitl the K8s error crashloopbackoff.

### How to Reproduce?

I can't reproduce the case, it's not clear at the moment the cause of the first crash and it is random

### Output of `uname -a` or `ver`

Linux dossier-dpl-5d6fb76c64-8zxph 5.10.210-201.855.amzn2.x86_64 #1 SMP Tue Mar 12 19:03:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 21.0.2 2024-01-16 LTS

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.1

**Comment by geoand** [comment]
I am pretty sure that you would see the same behavior locally if you built the application with

```bash
mvn package
```

and ran it with

```
java -jar target/quarkus-app/quarkus-run.jar
```

Can you please check and if so attach a sample application we can use to debug?

**Comment by ihepda** [comment]
I can try but the first crash is random. 
But the principal issue is the pod not restart correctly. 

I'll try to run locally to understand if I can reproduce the first crash but it is a completely different environmnet (windows vs linux, real machine vs virtual machine, etc...)

I'll get back to you if I have news

Thanks a lot

**Comment by ihepda** [comment]
I'm not an expert of K8s but I hoped to see the old logs after restarting instead all log files are deleted.
My log configuration is 
# Logger console properties
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{uuid}] %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
#quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{jwtId}-%X{transactionId}] %-5p [%c{2.}] %s%e%n
quarkus.log.console.color=false

# Logger file properties
quarkus.log.file.enable=true
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{uuid}] %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
quarkus.log.file.path=logs/dossier/dossier.log
#quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{jwtId}-%X{transactionId}] %-5p [%c{2.}] %s%e%n

# Logger category properties
quarkus.log.category."be.digitech.dossier".level=DEBUG
quarkus.log.category."be.grpc.logging".level=DEBUG
%dev.quarkus.log.category."io.quarkus".level=INFO

On the base of the documentation I expect to have a rotation of the log during the reboot, but it isn't so

**Comment by gsmet** [comment]
So the warning is apparently about not being able to access the database.

Unfortunately, I think we have a small issue leading to the underlying exception not being logged. @yrodiere I wonder if we should return a default implementation of `SqlExceptionHelper` in `JdbcServicesImpl#getSqlExceptionHelper` instead of null.
My understanding is that some errors can happen before the JDBC environment is set up (at least in Quarkus).

I still recommend to have a look at the health checks as I'm very suspicious something might be wrong there. And that something not working (maybe the database access as we can see this app wasn't able to connect to the database) leads to your pods being killed (and maybe also never being ready).

**Comment by gsmet** [comment]
BTW, I'm not saying it's not an issue in Quarkus. I just think we will need more input to determine if it's a regression in our code or something odd in your code/infra (that might trigger something on our side).

The pods being killed is usually something triggered by the health checks thus my suspicion.

By any chance, are you setting `quarkus.datasource.db-kind` in your `application.properties` or are you relying on the fact it automatically selects the right one with only one driver present?

**Comment by gsmet** [comment]
@ihepda I think it could be interesting to get something to query and log the health check status (with the JSON included) but I'm not sure how easy it would be for you.

Yeah I completely agree that losing the logs on restart is very painful.

**Comment by ihepda** [comment]
The app is just crashed, I can see in pod this:
```
Events:
  Type     Reason     Age                  From     Message
  ----     ------     ----                 ----     -------
  Warning  Unhealthy  2m47s                kubelet  Readiness probe failed: Get "http://10.109.0.25:8080/q/health/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  2m41s                kubelet  Readiness probe failed: Get "http://10.109.0.25:8080/q/health/ready": read tcp 169.254.175.250:46546->10.109.0.25:8080: read: connection reset by peer
  Warning  Unhealthy  2m41s                kubelet  Liveness probe failed: Get "http://10.109.0.25:8080/q/health/live": read tcp 169.254.175.250:46544->10.109.0.25:8080: read: connection reset by peer
  Normal   Pulled     2m39s                kubelet  Successfully pulled image "isypolregistry.azurecr.io/isypol/dossier:1.0.0" in 404.964416ms (404.976941ms including waiting)
  Normal   Pulled     2m2s                 kubelet  Successfully pulled image "isypolregistry.azurecr.io/isypol/dossier:1.0.0" in 172.418977ms (172.431513ms including waiting)
  Normal   Killing    90s (x2 over 2m10s)  kubelet  Container dossier failed startup probe, will be restarted
  Normal   Pulling    87s (x4 over 127m)   kubelet  Pulling image "isypolregistry.azurecr.io/isypol/dossier:1.0.0"
  Normal   Created    87s (x4 over 127m)   kubelet  Created container dossier
  Normal   Pulled     87s                  kubelet  Successfully pulled image "isypolregistry.azurecr.io/isypol/dossier:1.0.0" in 215.105915ms (215.121343ms including waiting)
  Normal   Started    86s (x4 over 127m)   kubelet  Started container dossier
  Warning  Unhealthy  70s (x9 over 127m)   kubelet  Startup probe failed: Get "http://10.109.0.25:8080/q/health/started": dial tcp 10.109.0.25:8080: connect: connection refused
```

Is it possible that during some calls the health system is not able to respond cause few thread for example?

**Comment by ihepda** [comment]
Dear all,
We discovered that the crash was fargate killed the pod for a pod OOM (without register any events).
Now rhe only question is why after the restart quarkus can't initialize the container correctly (see the first exception in this thread).

Other applications restart correctly. The only difference is the scheduled method.

**Comment by geoand** [comment]
Is there anything we need to do on this one?

**Comment by geoand** [comment]
Closing for lack of feedback
