### ISSUE TITLE
Add property to force `cache-control: no-store` on: quarkus.smallrye-health

### ISSUE THREAD

**Issue by jycr** [quarkusio/quarkus#39868]
### Description

Between our browser and target server, we use corporate proxy.
When our UI check URL health of our application modules, when one module is down (TCP connexion down : Couldn't connect to server), our proxy continue to serve a cached response.

If the response to the healthcheck URL included a `cache-control: no-store` header, it would not be stored in our corporate proxy's cache.

### Implementation ideas

Add a property (eg: `quarkus.smallrye-health.reponse-header."cache-control"=no-store`) to customize HTTP response header

**Comment by gsmet** [comment]
Yeah I think that makes perfect sense and we should avoid all caching for health checks.

**Comment by geoand** [comment]
#39872 is what I have in mind
