### ISSUE TITLE
Include LICENSE in source jar

### ISSUE THREAD

**Issue by sincejune** [quarkusio/quarkus#39865]
### Description

Hi team, is it possible to include `LICENSE` into source jar? This will be helpful when using some vulnerability detection tools scanning java dependencies. Thanks!

ref: https://mvnrepository.com/artifact/io.quarkus/quarkus-arc/3.9.1

### Implementation ideas

None

**Comment by gsmet** [comment]
I created a PR to address that here: https://github.com/quarkusio/quarkus/pull/39869

Let's see what others think as it makes our jar a bit larger.

**Comment by maxandersen** [comment]
Curious why the pom.xml that has license and DEP info is not enough?

Similar the signing is external file. 

Which tools is it that needs/wants the license file inside the jar file?

**Comment by gsmet** [comment]
I saw a few people developing tooling based on the `Bundle-License` entry of the manifest and/or the presence of a `META-INF/LICENSE` file.

**Comment by gsmet** [comment]
Using the `pom.xml` is not always practical when all you have is the jar. There is a `pom.xml` in the jar file but it is not the fully resolved one so you don't really have the information handy.

**Comment by sincejune** [comment]
@gsmet Thank you for the help on this!

I tried to download a latest version of SNAPSHOT jar on sonartype. It seems that the `LICENSE` file is still not present. And I can see `Bundle-License: Apache License 2.0` entry in `quarkus-arc`'s `MANIFEST.MF` but not in `quarkus-resteasy-client`. Would you mind taking a look at this? Thanks!

arc: https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkus/arc/arc/999-SNAPSHOT/
quarkus-resteasy-client: https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkus/quarkus-resteasy-client-jackson/999-SNAPSHOT/

**Comment by gsmet** [comment]
@sincejune The licenses are added in the `release` profile which is only used when releasing. I did a few checks and things look good so let's wait for the next release (3.9.4 should have the fix).

**Comment by maxandersen** [comment]
So..we could we not just have the bundle header - and not the repeated license file ?

**Comment by gsmet** [comment]
Not sure the bundle is used that much, from what I can see it's an OSGi thing.

We could try that and see how it goes if you prefer.

**Comment by aloubyansky** [comment]
@sincejune you are asking to add license info to the sources jar, not the binary one? Could you please elaborate on the approach of that vulnerability scanning tool?

**Comment by maxandersen** [comment]
@sincejune is it sufficient with the bundle-* flag ? no license txt file?
