### ISSUE TITLE
Routing for index.html fails with 404 for directories

### ISSUE THREAD

**Issue by yazalulloa** [quarkusio/quarkus#39871]
### Describe the bug

I have static html inside src/main/resources/META-INF/resources, if I a put a directory inside that path with an index.html it fails with 404 when I make a GET /{directory}

In local and jvm mode it does return the html

Repo: https://github.com/yazalulloa/routing-assets-example

### Expected behavior

When a request is done to a path (GET /users) that has a folder with an index.html return the html 

### Actual behavior

GET /users returns 404

### How to Reproduce?

There is a Dockerfile and a bash script to generate the native image and run the container

Make a GET request to /users

### Output of `java -version`

Java 21

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by geoand** [comment]
I don't consider this a bug, but a feature request and would actually like to know if any other framework behaves as is asked for here.

**Comment by zakkak** [comment]
> I don't consider this a bug, but a feature request and would actually like to know if any other framework behaves as is asked for here.

@geoand why so? Since it behaves that way in JVM mode shouldn't we consider it a bug if it behaves differently in native?

I also think the `area/native-image` is valid even if it's not a bug as it concerns native image vs JVM mode.

**Comment by geoand** [comment]
Ah sorry, I misread the part where it worked in JVM mode - my bad.

**Comment by geoand** [comment]
I'll check it out

**Comment by geoand** [comment]
I had something I thought would fix the issue but it doesn't... Given that there is no logging in `io.vertx.ext.web.handler.impl.StaticHandlerImpl` I am not sure how I can debug what's going on in native...

**Comment by zakkak** [comment]
Sounds like you will need to compile with `-Dquarkus.native.debug.enabled=true` and open the binary with gdb, then set a breakpoint in the methods you are interested in and step through the code. Hopefully there will be enough info to let you understand what's going on. If you need any help let me know.
