### ISSUE TITLE
Infinispan client extension : infinispan version upgrade to 10.0.0.CR1 

### ISSUE THREAD

**Issue by anadollu** [quarkusio/quarkus#3987]
**Description**
A newest more stable version of Infinispan server 10.0.0.CR1 is available at the moment but current quarkus infinispan client extension uses 10.0.3.Beta version of infinispan client libraries.

**Comment by gwenneg** [comment]
`10.0.0.CR1` is the current version on [master](https://github.com/quarkusio/quarkus/blob/master/bom/runtime/pom.xml#L116), so I'm closing this issue.
