### ISSUE TITLE
Support config service in cxf code generator phase again

### ISSUE THREAD

**Issue by camproto** [quarkusio/quarkus#39884]
After updating quarkus from 3.2.4 to 3.6.9 and updating matching cxf extension from 4.0.1 to 4.0.3 my custom SecretsKeyHandler is not generated anymore. 

I believe this is caused by https://github.com/quarkiverse/quarkus-cxf/issues/1007.

In the Quarkus `CodeGenerator` we ban such services from the classloader, but in the case `Wsdl2JavaCodeGen`, there is an explicit call to get the configuration with the TCCL. It worked in the past because this did not exist in previous versions.

While Config services cannot be available in the code generator phase, fixing the issue in the Quarkiverse CXF repo can prevent the build from failing.

Can you please open a new issue there? Thanks!

_Originally posted by @radcortez in https://github.com/quarkusio/quarkus/issues/39689#issuecomment-2035262285_

**Comment by radcortez** [comment]
Sorry, I'm a bit confused. Is this to fix https://github.com/quarkiverse/quarkus-cxf/issues/1007? or is something different?

**Comment by camproto** [comment]
sorry my fault, I tried to follow your comment in https://github.com/quarkusio/quarkus/issues/39689, but did not create the ticket in quarkiverse issue list. Could be discarded.

**Comment by radcortez** [comment]
Thanks
