### ISSUE TITLE
[3.2] [3.8] Empty welcome page on new projects for old versions of Quarkus

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#39909]
### Describe the bug

When generated apps are downloaded from code.quarkus.io and run in dev mode, there is no welcome page("index.html" with "Congratualtions, you use Quarkus") on localhost.

### Expected behavior

There should be a welcome page, just like for 3.9 and apps, downloaded from code.quarkus.redhat.com

### Actual behavior

Http 404

### How to Reproduce?

1. Download an app: `https://code.quarkus.io/api/download?e=quarkus-resteasy-reactive&S=3.2&j=17`
2. Unpack the zip
3. Run `mvn quarkus:dev`
4. Open localhost:8080 in a browser

If one downloads the latest version (eg `https://code.quarkus.io/api/download?e=quarkus-resteasy-reactive&S=3.9&j=17`) or uses RHBQ (`https://code.quarkus.redhat.com/api/download?e=quarkus-resteasy-reactive&S=3.2&j=17`) the welcome page is there

### Output of `uname -a` or `ver`

6.7.3-200.fc39.x86_64

### Output of `java -version`

Java version: 21.0.1, vendor: Eclipse Adoptium

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

Probably related to https://github.com/quarkusio/quarkus/pull/37680

**Comment by geoand** [comment]
cc @ia

**Comment by ia3andy** [comment]
Yeah, this is known. I didn't find a simple way to solve this :-/

For context, the default page is now dynamic and handled by Quarkus, since the codestarts are using a set of base codestarts the index.html is not there anymore and this affect all versions.

**Comment by michalvavrik** [comment]
When I create 3.8.x application with Quarkus CLI on Linux with Quarkus CLI version 3.8.3 then localhost:8080/ in DEV Mode index is there and when I create the same application with Quarkus CLI snapshot, it's not there.

**Comment by maxandersen** [comment]
@ia3andy why can't the generation be based on what version is targeted ? that must be possible otherwise can never adjust behavior like what was now apparently done with dynamic index page.

even if we can't find it for generic resources we are now at least forced to do it for index.html generation.

**Comment by ia3andy** [comment]
> @ia3andy why can't the generation be based on what version is targeted ? that must be possible otherwise can never adjust behavior like what was now apparently done with dynamic index page.
> 
> even if we can't find it for generic resources we are now at least forced to do it for index.html generation.

I will try to find a way to fix it with new CLI when using older versions
