### ISSUE TITLE
NPE when handling circular dependencies

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#3990]
If there is a normal scoped bean that declares a normal scoped producer and the bean depends on the producer method a NPE is thrown. See for example [MPConfigBean from the MP CP TCK](https://github.com/eclipse/microprofile-context-propagation/blob/master/tck/src/main/java/org/eclipse/microprofile/context/tck/MPConfigBean.java)

The producer bean can be added before the declaring bean and so a null `ResultHandle` is passed to Gizmo: https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java#L248.

**Comment by mkouba** [comment]
I fixed one issue but there are certainly other corner cases that are not covered. In any case, I'm going to send a PR and we can continue improving the code ;-). Thanks a lot for the feedback.

**Comment by mthmulders** [comment]
Thanks for having a fix ready even before I could start to think of one :-)
