### ISSUE TITLE
Support for JWTProvider injection? (JWTParser is provided, but not JWTProvider?)

### ISSUE THREAD

**Issue by StephenOTT** [quarkusio/quarkus#39946]
### Description

JWTParser was provided in https://github.com/quarkusio/quarkus/issues/9012

`Jwt` class was provided in https://github.com/quarkusio/quarkus/issues/5341

But was there a reason for JWTProvider to not be provided as a default injection point?

```java
import io.smallrye.jwt.build.spi.JwtProvider;

@Inject
JWTProvider jwtProvider;
```

### Implementation ideas

Provide JWTProvider option

**Comment by sberyozkin** [comment]
@StephenOTT That `JwtProvider` is about providing custom Jwt Build API implementations, instead of the default one. It is not meant to be injected. Does it clarify it ?

**Comment by StephenOTT** [comment]
Okay understood.  

From a design perspective, is there a particular reason for why JWTParser (through injection) can be/is used for parsing, but `Jwt` with static methods is used for jwt creation?  

(just trying to understand the nuance if there is any)

**Comment by sberyozkin** [comment]
@StephenOTT They serve different purposes. `JWTParser` is used for parsing the tokens manually in the code if it is necessary, JWR build API is for generating tokens. HTH

**Comment by StephenOTT** [comment]
Yes, sorry let me clarify the question: I understand the usage difference; my question is why was JWTParser provided as an injection but Jwt was provided through static methods? (Instead of through injection)

**Comment by sberyozkin** [comment]
@StephenOTT I see, `Jwt` it is expected to work in the client, non-server set ups, it does not really represent something that can be used to process the current request, when injection won't work.

May be for some cases like `@Inject Keycloak keycloak;` where am initialized Keycloak admin client is injected, saving users going through Keycloak builder steps, can make sense. But even here, `@Inject Keycloak keycloak;` is a convenience that complements the builder option.
If users had to manually preconfigure Jwt in the code, before starting building the token, then maybe we'd consider an in inject option but for now I'm not seeing such a requirement.

Hope it clarifies it

**Comment by StephenOTT** [comment]
Okay great. Thank you for the explanation. It is appreciated greatly.

**Comment by sberyozkin** [comment]
@StephenOTT Np at all, thanks; it is not a thread-safe as well, a new instance is created for every new token, you can reuse the same builder instance, but it has state, so having `@Inject Jwt jwt;` would probably not work in any case.
