### ISSUE TITLE
File and FileUpload result in different OpenAPI spec, upload button missing

### ISSUE THREAD

**Issue by BrianSetz** [quarkusio/quarkus#39950]
### Describe the bug

The following:

```kotlin
@POST
@Path("/file")
fun postFile(@RestForm file: File): String {
    // Do nothing
    return "File"
}

@POST
@Path("/fileupload")
fun postFileUpload(@RestForm fileUpload: FileUpload): String {
    // Do nothing
    return "FileUpload"
}
```

Results in different OpenAPI specs for each endpoint, the upload button is missing in the SwaggerUI for the FileUpload endpoint. 

File endpoint:

![image](https://github.com/quarkusio/quarkus/assets/1055477/24c587f2-fe20-4664-9ab5-4c2a6fc2acad)

FileUpload endpoint:

![image](https://github.com/quarkusio/quarkus/assets/1055477/85e3e633-01c2-4639-8643-63cc4d45346c)

I am not sure if this is intended behavior?

### Expected behavior

I expected to be able to use File and FileUpload interchangeably (from OpenAPI point of view). 

### Actual behavior

File and FileUpload endpoints have vastly different OpenAPI specs. When using FileUpload there is no upload button in the SwaggerUI. When using File there is a file upload button. 

### How to Reproduce?

Reproducer: https://github.com/BrianSetz/quarkus-file-fileupload-reproducer (or use the above endpoint definitions in a Quarkus project with Reactive REST and OpenAPI)

1. Run Quarkus app
2. Open Quarkus Dev UI
3. Navigate to Swagger UI
4. Compare endpoints / OpenAPI spec

### Output of `uname -a` or `ver`

Linux p15v 6.5.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar  5 21:19:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

### Additional information

OpenAPI spec:

```yaml
---
openapi: 3.0.3
info:
  title: demo API
  version: 1.0-SNAPSHOT
paths:
  /hello:
    get:
      tags:
      - Example Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /hello/file:
    post:
      tags:
      - Example Resource
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  format: binary
                  type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /hello/fileupload:
    post:
      tags:
      - Example Resource
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                fileUpload:
                  $ref: '#/components/schemas/FileUpload'
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    FileUpload:
      type: object
```

**Comment by ramiswailem** [comment]
You need something like this:


@Schema(type = SchemaType.STRING, format = "binary")
    public interface UploadItemSchema {
    }




public Response upload(@RestForm(FileUpload.ALL) @Schema(implementation = UploadItemSchema.class) List<FileUpload> uploads) throws IOException {....

**Comment by geoand** [comment]
Indeed FileUpload should be treated like File

**Comment by BrianSetz** [comment]
I can confirm that the workaround at least fixes the incorrect type/format.

```kotlin
@POST
@Path("/fileupload")
fun postFileUpload(@RestForm @Schema(implementation = BinaryStringSchema::class) fileUpload: FileUpload): String {
    // Do nothing
    return "FileUpload"
}

@Schema(type = SchemaType.STRING, format = "binary")
interface BinaryStringSchema
```

Results in

```yaml
---
openapi: 3.0.3
info:
  title: demo API
  version: 1.0-SNAPSHOT
paths:
  /hello:
    get:
      tags:
      - Example Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /hello/file:
    post:
      tags:
      - Example Resource
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  format: binary
                  type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /hello/fileupload:
    post:
      tags:
      - Example Resource
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                fileUpload:
                  $ref: '#/components/schemas/BinaryStringSchema'
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    BinaryStringSchema:
      format: binary
      type: string
    FileUpload:
      type: object
```

Which at least adds the upload button in the Swagger UI. But  the following is missing

```yaml
required:
- fileUpload
```

And there is an unused (?) schema component:
```yaml
FileUpload:
  type: object
```

**Comment by phillip-kruger** [comment]
This has been fixed in upstream smallrye, @MikeEdgar please close here once new version of SmallRye openapi is included in Quarkus. Thanks :)

**Comment by MikeEdgar** [comment]
The fix for this was included in https://github.com/quarkusio/quarkus/pull/41037

**Comment by geoand** [comment]
🙏
