### ISSUE TITLE
MessageBundle naming issue

### ISSUE THREAD

**Issue by ercalamar** [quarkusio/quarkus#39960]
### Describe the bug

In this kind of situation:

```
public class EmailBundles {
    @MessageBundle
    interface started {
        @Message
        String started(String id, String filename);
        @Message
        String documentAccessUrl(String url);
...
    @MessageBundle
    interface startedValidator {
        @Message
        String started(String id, String filename);
        @Message
        String turnEmailWillBeSent();
...
```

The following error appears:

```
io.quarkus.qute.deployment.MessageBundleException: Message bundle method turnEmailWillBeSent() not found on: com.iarchiva.EmailBundles$started
```

If I rename "interface started {" to "interface rstarted {" the initial part of the name does not match and there is no issue.

### Expected behavior

I expect no name collision between "started" and "startedValidator".

### Actual behavior

Names collide being different.

### How to Reproduce?

Having two interfaces that start with the same string.

### Output of `uname -a` or `ver`

Microsoft Windows [Versión 10.0.22631.3296]

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15) OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

**Comment by gastaldi** [comment]
Can you attach a sample reproducer project please?

**Comment by ercalamar** [comment]
[qute-locale.zip](https://github.com/quarkusio/quarkus/files/14928211/qute-locale.zip)

As requested :)

Another issue is moving the 3 classes in the project to the default package.
