### ISSUE TITLE
Information Exposure Through Environmental Variables

### ISSUE THREAD

**Issue by drimer** [quarkusio/quarkus#39969]
### Describe the bug

I found a report of this vulnerability in:
- https://bugzilla.redhat.com/show_bug.cgi?id=2273281
- https://security.snyk.io/vuln/SNYK-JAVA-IOQUARKUS-6564967

**Overview**

	
A vulnerability was found in the quarkus-core component. Quarkus captures the local environment variables from the Quarkus namespace during the application's build. Thus, running the resulting application inherits the values captured at build time. 

However, some local environment variables may have been set by the developer / CI environment for testing purposes, such as dropping the database during the application startup or trusting all TLS certificates to accept self-signed certificates. If these properties are configured using environment variables or the .env facility, they are captured into the built application. It leads to dangerous behavior if the application does not override these values.

This behavior only happens for configuration properties from the `quarkus.*` namespace. So, application-specific properties are not captured.

**Comment by gsmet** [comment]
Thanks for the report but we are aware of it since we were the ones who created the CVE.

The CVE is fixed in 3.9.2 and we will backport the fix as soon as we judge it sufficiently safe for other supported branches.
