### ISSUE TITLE
OTEL EUSP error when using Custom Jakarta REST SecurityContext

### ISSUE THREAD

**Issue by fabrii** [quarkusio/quarkus#39970]
### Describe the bug

If using [Custom Jakarta REST SecurityContext](https://quarkus.io/guides/security-customization#jaxrs-security-context) and quarkus.otel.traces.eusp.enabled=true, then we get the following exception:

`java.lang.UnsupportedOperationException: retrieving all roles not supported when JAX-RS security context has been replaced
        at io.quarkus.resteasy.runtime.SecurityContextFilter$1.getRoles(SecurityContextFilter.java:64)
        at io.quarkus.security.runtime.SecurityIdentityProxy.getRoles(SecurityIdentityProxy.java:34)`

It should be possible to propagate the principal name, without throwing the exception.

By the way, the property quarkus.otel.traces.eusp.enabled is documented in https://quarkus.io/blog/quarkus-3-3-0-released/ but not in https://quarkus.io/guides/opentelemetry#configuration-reference.

### Quarkus version or git rev

3.8.3

**Comment by brunobat** [comment]
Duplicated from https://github.com/quarkusio/quarkus/issues/39563
