### ISSUE TITLE
Mock not executed when running native Tests

### ISSUE THREAD

**Issue by DrHackschnitzel** [quarkusio/quarkus#39984]
### Describe the bug

I have a Service:

```java
@ApplicationScoped
public class BusinessService
{
	public String greet()
	{
		return "hello";
	}

}
````

which i want to mock in a junit test. I try to throw a Runtimeexception with Mockito when greet() is called.
```java
@InjectMock
	private BusinessService mock = Mockito.mock(BusinessService.class);
        [...]
        Mockito.doThrow(new RuntimeException()).when(mock).greet();
```

The Exception is perfectly thrown when running the Tests on java, but the exception is never thrown on native compiled

A minimalistic Example of the code to reproduce the steps can be found here:
https://github.com/DrHackschnitzel/quarkus-mock
   
 

### Expected behavior

Mocks should be executed on native

### Actual behavior

Mocks are only executed on java execution, not on native

### How to Reproduce?

Steps to reproduce:

1. Clone example project https://github.com/DrHackschnitzel/quarkus-mock
2. Verify it works on java mode: (mvn package)
3. Build with native mode to see the failed tests: (mvn package -Pnative)

### Output of `uname -a` or `ver`

6.8.2-arch2-1

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Mandrel or GraalVM version (if different from Java)

MANDREL 23.1.2.0 JDK 21.0.2+13-LTS

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

**Comment by geoand** [comment]
This is the expected behavior as a `@QuarkusIntegrationTest` cannot alter the built application in any way - all it does is run it
