### ISSUE TITLE
Failed to generate Java classes from proto files

### ISSUE THREAD

**Issue by ti-casoca** [quarkusio/quarkus#39998]
### Describe the bug

From version 3.8.3 to version 3.9.x, an error is occurring when generating/compiling classes from .proto files.

### Expected behavior

Generate and compile classes with .proto files.

### Actual behavior

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.9.3:dev (default-cli) on project code-with-quarkus: Quarkus code generation phase has failed: InvocationTargetException: Failed to generate Java classes from proto files: [/Users/rodrigo/Downloads/code-with-quarkus/src/main/proto/hello.proto] to /Users/rodrigo/Downloads/code-with-quarkus/target/generated-sources/grpc with command /Users/rodrigo/Downloads/code-with-quarkus/target/com.google.protobuf-protoc-osx-x86_64-exe -I=/Users/rodrigo/Downloads/code-with-quarkus/src/main/proto -I=/Users/rodrigo/Downloads/code-with-quarkus/target/protoc-dependencies/a8021084782e76858f2824ee9cae13370b2a7e0a --plugin=protoc-gen-grpc=/Users/rodrigo/Downloads/code-with-quarkus/target/io.grpc-protoc-gen-grpc-java-osx-x86_64-exe --plugin=protoc-gen-q-grpc=/Users/rodrigo/Downloads/code-with-quarkus/target/quarkus-grpc10514800561735552649.sh --q-grpc_out=/Users/rodrigo/Downloads/code-with-quarkus/target/generated-sources/grpc --grpc_out=/Users/rodrigo/Downloads/code-with-quarkus/target/generated-sources/grpc --java_out=/Users/rodrigo/Downloads/code-with-quarkus/target/generated-sources/grpc /Users/rodrigo/Downloads/code-with-quarkus/src/main/proto/hello.proto
```

### How to Reproduce?

Using the "https://code.quarkus.io/" wizard, generate a Quarkus project, version 3.9.0 | 3.9.1 | 3.9.2 | 3.9.3, include the "quarkus-grpc" extension, download and run "./mvnw quarkus:dev".
- Build Tool: Maven
- Java Version: 17

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-de-Rodrigo.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Homebrew (build 17.0.5+0, mixed mode, sharing)

### Quarkus version or git rev

3.9.0 | 3.9.1 | 3.9.2 | 3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by cescoffier** [comment]
This protocol update keeps giving...

**Comment by cescoffier** [comment]
Seems to work for me:

```
INFO] --- quarkus:3.9.3:dev (default-cli) @ grpc-repro ---
[INFO] Invoking resources:3.3.1:resources (default-resources) @ grpc-repro
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] Invoking quarkus:3.9.3:generate-code (default) @ grpc-repro
[INFO] [io.quarkus.grpc.deployment.GrpcCodeGen] Successfully finished generating and post-processing sources from proto files
[INFO] Invoking compiler:3.12.1:compile (default-compile) @ grpc-repro
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 11 source files with javac [debug release 17] to target/classes
[INFO] Invoking resources:3.3.1:testResources (default-testResources) @ grpc-repro
[INFO] skip non existing resourceDirectory /Users/clement/Downloads/grpc-repro/src/test/resources
[INFO] Invoking quarkus:3.9.3:generate-code-tests (default) @ grpc-repro
[INFO] Invoking compiler:3.12.1:testCompile (default-testCompile) @ grpc-repro
```

**Comment by cescoffier** [comment]
Do you have more than just that error message?

**Comment by ti-casoca** [comment]
Hello @cescoffier Escoffier,

I recorded a video "https://drive.google.com/file/d/1pPfNgpaXNLtFQL1JJM6OL09jDLm0208l/view?usp=sharing" and attached the output log "39998.log".

What version of Maven are you using?

Att,
Rodrigo

[39998.log](https://github.com/quarkusio/quarkus/files/14986248/39998.log)

**Comment by cescoffier** [comment]
So the latest protoc needs libc+ to be installed on your system to work:

Expected in: /usr/lib/libc++.1.dylib
 in /Users/rodrigo/Downloads/code-with-quarkus/target/io.grpc-protoc-gen-grpc-java-osx-x86_64-exe
--grpc_out: protoc-gen-grpc: Plugin killed by signal 6.

**Comment by ti-casoca** [comment]
Good morning.

Builds up to 3.8.3 work fine. It was when switching to 3.9 that it broke.

It has something to do with the Mac SDK version.

**Comment by cescoffier** [comment]
Do you know which SDK version you are using?

**Comment by ti-casoca** [comment]
Mine is MacOS Catalina (10.15.7), Mac Pro. It no longer receives updates.

From the queries I made, the error "__ZTTNSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE" is generated by incompatibilities between compiler versions.

**Comment by cescoffier** [comment]
yes, that's unfortunate but I'm not sure what can be done. Basically, you would need to revert to a previous protoc version. We, for CVE reasons, have to use the latest one.
