### ISSUE TITLE
Add ability to hide rest endpoints from OpenAPI schema / Swagger

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#40007]
### Description

I'm unable to hide JAXRS methods in OpenAPI schema / Swagger.

For endpoints that are experimental or legacy ones I don't want them to be part of the generated schema. That schema serves as public contract in many cases.

I found `io.swagger.v3.oas.annotations.Hidden` annotation, but no equivalent of it in Quarkus OpenAPI extension.
SB has ways to hide endpoints from the generated document even without using `@Hidden` annotation.

Please add ability to hide rest endpoints from OpenAPI schema / Swagger.

**Comment by phillip-kruger** [comment]
We do not support the swagger annotations. Please use MicroProfile OpenAPI

**Comment by phillip-kruger** [comment]
Example: if this is an operation you can do `@Operation(hidden=true)`

**Comment by rsvoboda** [comment]
Thanks @phillip-kruger, this helps a lot!

As stated in description of this issue, I was able to find a lot of resources describing swagger way and even more resources for SB. I looked into openapi for examples, I scraped https://github.com/eclipse/microprofile-open-api/blob/main/spec/src/main/asciidoc/microprofile-openapi-spec.asciidoc too, but nothing popped up.

https://quarkus.io/guides/openapi-swaggerui guide could be extended with examples how to hide methods/endpoints and fields of returrned objects.
Seems that we are expecting that people are quite familiar with Eclipse MicroProfile OpenAPI and all the constructs it allows, but in reality there are not many resources that people can use.

**Comment by phillip-kruger** [comment]
Agree, we can definitely update the docs. We also have on our to-do list to add support for swagger annotations, but it has never really been a priority. See https://github.com/smallrye/smallrye-open-api/issues/752

**Comment by Serkan80** [comment]
@rsvoboda this is already possible, but it is nowhere documented and I found it by accident. 

So it works something like this:

```java
import io.quarkus.runtime.StartupEvent;
import io.quarkus.runtime.rest.DisabledRestEndpoints;
import jakarta.enterprise.event.Observes;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.util.HashMap;
import java.util.List;

/**
 * Removes the internal api's from the Swagger UI & OpenAPI yaml.
 */
public class SwaggerUiConfig {

    @ConfigProperty(name = "swagger-ui.show-internal-apis")
    boolean showInternalApis;

    @ConfigProperty(name = "swagger-ui.disabled-paths")
    List<String> disabledPaths;

    public void init(@Observes StartupEvent event) {
        if (!this.showInternalApis) {
            var result = new HashMap<String, List<String>>();
            this.disabledPaths.forEach(path -> {
                   if (path.matches(".+(/admin|/management).+")) {
                       result.put(path, List.of("DELETE", "POST", "PATCH", "PUT"));
                   }                  
           }
           DisabledRestEndpoints.set(result);
       }
   }
}

```

```properties
swagger-ui.show-internal-apis=false
%dev.swagger-ui.show-internal-apis=true
swagger-ui.disabled-paths=/v1/admin/fruits,/v1/management/fruits/
```

I hope this helps you.

**Comment by rsvoboda** [comment]
Thanks @Serkan80! It's good there a way to achieve this right now.
Quarkus should provide simpler way through annotation.

**Comment by Serkan80** [comment]
@rsvoboda I'm afraid that to achieve this through annotation, is going to be hard, because this needs to be a part of the MP OpenApi specification. So everyone needs to agree on it, and this can take a while. For the time being, this solution is good enough for me.

**Comment by MikeEdgar** [comment]
Have you looked at using `mp.openapi.scan.exclude.classes` or `mp.openapi.scan.exclude.packages` to skip the resources implementing the endpoints you'd like to hide?

**Comment by phillip-kruger** [comment]
@rsvoboda can we close this ?

**Comment by rsvoboda** [comment]
`mp.openapi.scan.exclude.classes` and `mp.openapi.scan.exclude.packages` work well

I've created https://github.com/quarkusio/quarkus/pull/43593 to reference the spec from the guide so people can find `mp.openapi` config options more easily
