### ISSUE TITLE
Changing Accept Header in PreMatching filter isn't considered by MessageBodyWriter

### ISSUE THREAD

**Issue by myroch** [quarkusio/quarkus#40019]
### Describe the bug

#38130 fixed just the routing, but not the rendering by MessageBodyWriters

### Expected behavior

Accept Header set in the pre-matching request filter shall decide which MessageBodyWriter will be selected.

### Actual behavior

Setting the Accept Header inside the pre-matching request filter doesn't affect which MessageBodyWriter is being selected.

### How to Reproduce?

- checkout https://github.com/myroch/quarkus-prematching-servermessagebodywriter-bug
- run ExampleResourceTest

### Output of `java -version`

java 17.0.9 2023-10-17 LTS

### Quarkus version or git rev

3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by geoand** [comment]
Thanks for reporting.

#40022 fixes the issue

**Comment by anchialas** [comment]
Wow that was quick, thank you! Can this fix also be backported to 3.8 LTS?

**Comment by geoand** [comment]
🙏.


We do plan to backport the fix to 3.8 during the next patch release
