### ISSUE TITLE
Import DB data from data.sql when using quarkus-spring-data-jpa extension

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#40037]
### Description

In Quarkus we have support for loading data from `import.sql` in dev and test mode. SB uses `data.sql`. When people are moving to Quarkus they need to be aware of different file name and rename their `data.sql`.

Quarkus should be able to to work with `data.sql` when `quarkus-spring-data-jpa` extension is added to the project to make the transition slightly easier.

Another approach could be a global change to make `data.sql` fallback if `import.sql` is unavailable.

**Comment by geoand** [comment]
Makes perfect sense!

**Comment by geoand** [comment]
#40039 should do the trick
