### ISSUE TITLE
Support FileUpload in REST Client for MultiPart requests

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#40052]
### Description

Initial discussion here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20Rest.20Client.20Multipart.20with.20FileUpload.20broken/near/432913650

Currently, the FileUpload class is only supported for the server REST API, but not for the Rest client. It would be very nice if this would also be supported for the Rest client.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/40094 adds support for this

**Comment by andreas-eberle** [comment]
Amazing! Thanks for the super quick support as always!

**Comment by geoand** [comment]
🙏🏼
