### ISSUE TITLE
Method level Constraint Annotations are not Validated after update to quarkus 3.9.3

### ISSUE THREAD

**Issue by kgorica** [quarkusio/quarkus#40071]
### Describe the bug

I have an POJO
```
public class MyModel {
    @RestQuery @NotNull
    private String testStr;
    @RestQuery
    private String value1;
    @RestQuery
    private String value2;

    @AssertTrue(message = "Values are invalid")
    public boolean isValid() {
        return value1 != null || value2 != null;
    }
}
```

and then expose an endpoint:
```
   @GET
    @Produces({MediaType.APPLICATION_JSON})
    @Consumes({MediaType.APPLICATION_JSON})
    public RestResponse<Smthing> get(@BeanParam @Valid MyModel model) {
        //dosmth
    }
```

Validation is fired and works on field-level validation testStr but does not validate` @AssertTrue` on method level.
It worked fine on quarkus 3.9.1 if I remember correctly but after latest update it doesn't work.

### Expected behavior

ValidationException to be thrown

### Actual behavior

nothing, validation is marked as valid

### Output of `java -version`

openjdk 17.0.8 2023-07-18 OpenJDK Runtime Environment OpenLogic-OpenJDK (build 17.0.8+7-adhoc..jdk17u) OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 17.0.8+7-adhoc..jdk17u, mixed mode, sharing)

### Quarkus version or git rev

3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.6 Java version: 17.0.8, vendor: OpenLogic, runtime: C:\Program Files\OpenLogic\jdk-17.0.8.7-hotspot Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by gsmet** [comment]
I'm not convinced it worked on private methods.

If you can come up with a reproducer that worked with 3.9.1 and fails with 3.9.3, I'm interested.

**Comment by kgorica** [comment]
> I'm not convinced it worked on private methods.
> 
> If you can come up with a reproducer that worked with 3.9.1 and fails with 3.9.3, I'm interested.

I'm trying both private and public method, same issue.

**Comment by yrodiere** [comment]
@kgorica Alright, can you please provide a reproducer -- a small project that demonstrates the error, so we can debug it?

**Comment by geoand** [comment]
Closing for a lack of a reproducer
