### ISSUE TITLE
Support JWT `key ` property for the OIDC client authentication

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#40078]
### Discussed in https://github.com/quarkusio/quarkus/discussions/40036

Both `quarkus-oidc-client` and `quarkus-oidc` need to talk to the OIDC provider and they must authenticate to the OIDC provider in some cases. Many authentication options are supported such as the client id and secret, but also several JWT options, where a JWT is generated to support the client authentication.
This JWT can be signed with the client secret. Or with the private key - and this private key must currently be located in the PEM file or the keystore.

However it would be great if it were also possible to supply the private key as a string so that it can inferred from various environment properties, without having to create files

**Comment by IvanPuntev** [comment]
@sberyozkin I see this is going to be added in version 3.11 but can it also be added in the 3.8 LTS or I need to update to the latest one?
