### ISSUE TITLE
Only one of the application instances/replicas within the same consumer group consumes events

### ISSUE THREAD

**Issue by Jcmateos** [quarkusio/quarkus#40070]
### Describe the bug

According to section 3 (_Multiple consumer applications inside a consumer group_) of the documentation (https://es.quarkus.io/guides/kafka#consumer-groups) concerning consumer groups, if we have 3 instances/replicas of an application subscribed to the same consumer group, all of them should consume the events, correct?

However, the current behavior is that only one out of the 3 instances/replicas consumes the events that arrive. I am unsure if this behavior is intended, but from my understanding of the documentation, all 3 instances/replicas should consume the events.

It is evident that using **_${quarkus.uuid}_** in the **_group.id_** ensures that each instance/replica consumes the events, as each would have its own consumer group...

Could you please clarify this situation for me?

Thank you, best regards.

### Quarkus version or git rev

3.6.3

**Comment by ozangunalp** [comment]
This depends solely on the Kafka consumer configuration. Please add a simple reproducer with the configuration.

**Comment by Jcmateos** [comment]
Apologies for any inconvenience caused, but I believe I have just grasped the flow by referring to this website (https://softwaremill.com/kafka-visualisation/) and revisiting the Quarkus documentation.

Everything is clear now, and I understand how, in the example provided, if we have two instances, each of them reads certain partitions and distributes the workload between them, always handling different events between instances.

Thank you very much.
