### ISSUE TITLE
Qute: i18n for enum 

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#40089]
### Description

Assigning a localized name for enum values is rather challenging with the current Qute API.
It would be helpful to be able to set part of the key as the first parameter of the message method:

### Implementation ideas

```java
public enum 
MyEnum {
  ON, OFF, UNDEFINED
}

@MessageBundle 
public interface AppMessages {

    @Message 
    String displayName(MyEnum name);

}
```

Then the localized file could look like:

```
# This comment is ignored
displayName.ON=On
displayName.OFF=Off
displayName.UNDEFINED=Undefined
```

We could add a new annotation for the parameter to make it explicit that it is part of the key:

```java

public interface AppMessages {

    @Message 
    String displayName(@MessageKey MyEnum name);

}
```

if we want to be able to provide the message in the @Message annotation, we could make it repeatable:

```java

public interface AppMessages {

    @Message(key="ON", value="On")
    @Message(key="OFF", value="Off")
    @Message(key="UNDEFINED", value="Undefined")
    String displayName(@MessageKey MyEnum name);

}
```
or we could just prevent to set the message if MessageKey is present ?

**Comment by mkouba** [comment]
So given the fact that you can use regular qute constructs in the localized message I would recommend to use the [`{#when}`](https://quarkus.io/guides/qute-reference#when_section) section in a message spread out across several lines. Something like:

```java
@Message
String displayName(MyEnum myEnum);
```
and in the localized file: 
```properties
displayName={#when myEnum}\
       {#is ON}On\
       {#is OFF}Off\
       {#else}Undefined\
      {/when}
```
Note that the backslash character must be used to escape a line separator.

One thing we could do is to integrate the type-safe messages with [`@io.quarkus.qute.TemplateEnum`](https://quarkus.io/version/main/guides/qute-reference#convenient-annotation-for-enums). I.e. if you annotate your enum with `@TemplateEnum` we could automatically process the localized messages that start with the corresponding namespace:

```properties
MyEnum.ON=On
MyEnum.OFF=Off
MyEnum.UNDEFINED=Undefined
```
and then in the template:
```html
{MyEnum:i18n(myEnumVal)}
```
WDYT?

**Comment by mkouba** [comment]
> @mkouba the first solution is a bit tedious, 

Well, I don't find it tedious. At least, it's perfectly clear what it does ;-).

> but @TemplateEnum makes perfect sense thank you !

I'll try to propose a new pull request.

**Comment by mkouba** [comment]
I was thinking about this and I believe that it would be better if we autogenerate the message template instead.

For example, if a message bundle method consumes _a single enum param_ and the _value is defaulted_:
```java
@Message
String myEnum(MyEnum myEnum);
```
For an enum:
```java
enum MyEnum {  ON, OFF, UNDEFINED }
```
Then we could treat this message bundle method definition as if it was:
```java
@Message("{#when myEnum}"
                + "{#is ON}{msg:org_acme_MyEnum_ON}"
                + "{#is OFF}{msg:org_acme_MyEnum_OFF}"
                + "{#is UNDEFINED}{msg:org_acme_MyEnum_UNDEFINED}"
                + "{/when}")
String myEnum(MyEnum myEnum);
```
And so the localized file could just contain:
```properties
# FQCN with underscores instead of dots
org_acme_MyEnum_ON=On
org_acme_MyEnum_OFF=Off
org_acme_MyEnum_UNDEFINED=Undefined
```
This way we could reuse the existing API and still provide a convenient way of localization for enum constants.

**Comment by rmanibus** [comment]
@mkouba I think that make sense. 
I am thinking about one detail: I think it would be more usable if we allowed multiple mapping for the same enum.
Use cases for this would be for example providing a short name and an extended name, or more contextualized names depending of where the enum is used.
So maybe we should add the name of the method as a prefix for this to work ?

**Comment by mkouba** [comment]
> I am thinking about one detail: I think it would be more usable if we allowed multiple mapping for the same enum.
> Use cases for this would be for example providing a short name and an extended name, or more contextualized names depending of where the enum is used.

That's a good idea. In theory, we could even skip the enum FQCN part and use the method name instead:
```properties
myEnum_ON=On
myEnum_OFF=Off
myEnum_UNDEFINED=Undefined
```
Of course, we will validate the enum constants and fail the build if appropriate.
