### ISSUE TITLE
Adapt new behavior of System.console() since JDK22

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#40087]
### Description

Since [JDK22](https://inside.java/2023/07/31/quality-heads-up/):

> In JDK 22, System.console() has been changed to return a Console with enhanced editing features that improve the experience of programs that use the Console API. In addition, System.console() now returns a Console object when the standard streams are redirected or connected to a virtual terminal. Prior to JDK 22, System.console() instead returned null for these cases. This change may impact code that checks the return from System.console() to test if the JVM is connected to a terminal. If required, the -Djdk.console=java.base flag will restore the old behavior where the console is only returned when it is connected to a terminal. Starting JDK 22, one could also use the new Console.isTerminal() method to test if the console is connected to a terminal.

I looked into Quarkus codebase and I found the following snippets that might need to be changed:

https://github.com/quarkusio/quarkus/blob/3b97e89d0f8b024050a3071798e42579e0577716/core/devmode-spi/src/main/java/io/quarkus/dev/console/QuarkusConsole.java#L121-L123

https://github.com/quarkusio/quarkus/blob/3b97e89d0f8b024050a3071798e42579e0577716/core/devmode-spi/src/main/java/io/quarkus/dev/console/BasicConsole.java#L32-L37

https://github.com/quarkusio/quarkus/blob/3b97e89d0f8b024050a3071798e42579e0577716/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/utils/Prompt.java#L27-L33

### Implementation ideas

Change `System.console() != null` to `System.console() != null && System.console().isTerminal()`.

Since [`isTerminal()`](https://docs.oracle.com/en%2Fjava%2Fjavase%2F22%2Fdocs%2Fapi%2F%2F/java.base/java/io/Console.html#isTerminal()) is a new method introduced in JDK22, we can either:

- Call it via reflection.
- Use "multi-release jar" feature ([JEP238](https://openjdk.org/jeps/238)).

**Comment by stuartwdouglas** [comment]
I think using reflection would be the simplest approach here, ideally guarded by a version check so we don't make the reflection calls for older versions.

**Comment by geoand** [comment]
> I think using reflection would be the simplest approach here, ideally guarded by a version check so we don't make the reflection calls for older versions.

+1 as I am pretty sure we are not setup for MR-Jars in the main Quarkus repo.

**Comment by geoand** [comment]
@Eng-Fouad would you like to contribute this?

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad would you like to contribute this?

Submitted a PR. Do we need to register `isTerminal` for reflection in native image?

**Comment by stuartwdouglas** [comment]
AFAIK graal should be able to detect this case automatically because it is basically hard coded.
