### ISSUE TITLE
@RestForm bindining not functional

### ISSUE THREAD

**Issue by spolom** [quarkusio/quarkus#40080]
### Describe the bug

According to https://quarkus.io/guides/rest#multipart the following code example should provide a REST resource with a file upload capability:

```java
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.core.MediaType;

import org.jboss.resteasy.reactive.PartType;
import org.jboss.resteasy.reactive.RestForm;
import org.jboss.resteasy.reactive.multipart.FileUpload;

@Path("multipart")
public class MultipartResource {
    public static class Person {
        public String firstName;
        public String lastName;
    }

    @POST
    public void multipart(@RestForm String description,
            @RestForm("image") FileUpload file,
            @RestForm @PartType(MediaType.APPLICATION_JSON) Person person) {
        // do something
    }
}
```

Upon consumption of the `multipart`-resource, the method variables are all `null`.
I suspect that the binding is somehow broken.

### Expected behavior

Correct variable binding.

### Actual behavior

Variables are null.

### How to Reproduce?

1. Create sample project via `mvn io.quarkus.platform:quarkus-maven-plugin:3.9.3:create -DprojectGroupId=foo -DprojectArtifactId=quarkus-rest-test`.
2. Copy and paste class from `https://quarkus.io/guides/rest#multipart`. Remove `Person`-class and its reference in the method signature for simplicity.
3. Start application via `mvnw compile quarkus:dev`.
4. Consume `multipart`-Endpoint with the correct form-data, e.g. via curl: `curl -X 'POST' 'http://localhost:8080/multipart' -H 'Content-Type: multipart/form-data' -F 'image=@diagram-6150124113476008988.png;type=image/png;description=foo'`.

### Output of `uname -a` or `ver`

Darwin *.*.* 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode

### Quarkus version or git rev

3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

### Additional information

Example project with observed behaviour under https://github.com/spolom/quarkus-rest-test.

**Comment by luca-bassoricci** [comment]
Adding a Consume(MULTIPART_FORM) resolve the problem? Maybe is just a missing in doc

**Comment by spolom** [comment]
> Adding a Consume(MULTIPART_FORM) resolve the problem? Maybe is just a missing in doc

Makes no difference.

**Comment by geoand** [comment]
> Example project with observed behaviour under https://github.com/spolom/quarkus-rest-test.

How are you hitting the POST endpoint?

**Comment by spolom** [comment]
> > Example project with observed behaviour under https://github.com/spolom/quarkus-rest-test.
> 
> How are you hitting the POST endpoint?

With curl as mentioned in `How to Reproduce?`: `curl -X 'POST' 'http://localhost:8080/multipart' -H 'Content-Type: multipart/form-data' -F 'image=@diagram-6150124113476008988.png;type=image/png;description=foo`.
Also tried Postman.

**Comment by geoand** [comment]
The command is incorrect, you need to use something like:

```bash
curl -v -X 'POST' 'http://localhost:8080/multipart' -H 'Content-Type: multipart/form-data' -F 'image=@test.png;type=image/png' -F 'description=test'
```

**Comment by spolom** [comment]
Thank you @geoand. It works like this.

**Comment by geoand** [comment]
👌
