### ISSUE TITLE
@Startup on @Produces method

### ISSUE THREAD

**Issue by msilvacsw** [quarkusio/quarkus#40083]
### Describe the bug

According to the documentation (https://quarkus.io/guides/lifecycle):

"A bean represented by a class, producer method or field annotated with `@Startup` is initialized at application startup:"

From this it seems that annotating the `@Produces` method with `@Startup` will make the bean be created at startup.
Using the `@Startup` annotation does create the bean. However, it throws a warning during compilation:

`[WARNING] [io.quarkus.arc.deployment.StartupBuildSteps] Ignored an invalid @Startup method declared on ...`

Ideally I would like the startup to be valid on producers.

### Expected behavior

`@Startup` + `@Produces` creates the bean at startup and no warning is given during compilation.

### Actual behavior

`@Startup` + `@Produces` creates the bean at startup, but a warning is given during compilation.

### Quarkus version or git rev

3.8.3

**Comment by mschorsch** [comment]
We also use @Startup on @Produces methods and get the same warning.

**Comment by mkouba** [comment]
I agree that the warning is misleading and it was probably added by accident. We should only log this warning for invalid non-producer methods annotated with `@Startup`.
