### ISSUE TITLE
native-image - static resources in sub-directories

### ISSUE THREAD

**Issue by haraldatbmw** [quarkusio/quarkus#4009]
**Describe the bug**
My static HTML web-resources are located inside the directory META-INF/resources. My JavaScript, CSS files and images are in sub-directories (e.g. META-INF/resources/images, META-INF/resources/scripts, META-INF/resources/styles). 

If I create a native image only the files directly inside the META-INF/resources directory are included not the sub-directories and its files.

**Expected behavior**
sub-directories of META-INF/resources are included in the native image too.

**Actual behavior**
only files directly in META-INF/resources directory are included.

**To Reproduce**
1. Create a project with static web-content located in META-INF/resources and in sub-directories
2. Build and run a native image
3. Try to access the static resource inside the sub-directory

**Workaround**
Add additional build args to the native-image build.

```xml
<plugin>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-maven-plugin</artifactId>
  <version>${quarkus.version}</version>
  <executions>
    <execution>
      <goals>
        <goal>native-image</goal>
      </goals>
      <configuration>
        <additionalBuildArgs>
          <additionalBuildArg>-H:IncludeResources=META-INF/resources/.*</additionalBuildArg>
        </additionalBuildArgs>
...
```

**Comment by geoand** [comment]
Hi,

Can you please try:

```
<additionalBuildArg>-H:IncludeResources=META-INF/resources/**</additionalBuildArg>
```

I haven't tried it, but it might work.

In any case this isn't a Quarkus bug. This parameter is passed straight to GraalVM native-image.

**Comment by haraldatbmw** [comment]
Hi,

it already works with this argument:
`<additionalBuildArg>-H:IncludeResources=META-INF/resources/.*</additionalBuildArg>`

I think it should be the default behaviour of the native image builder that sub-directories are part of the image.

**Comment by geoand** [comment]
Oh, sorry I misread your issue :)

I think this makes sense

**Comment by emmanuelbernard** [comment]
CC @stuartwdouglas but feel free to delegate that one

**Comment by stuartwdouglas** [comment]
Can you provide a reproducer? I just tested this locally (see linked PR) and it worked for me.

**Comment by haraldatbmw** [comment]
> Can you provide a reproducer? I just tested this locally (see linked PR) and it worked for me.

Did you test against a native image?

**Comment by stuartwdouglas** [comment]
Yes, those tests are run in native mode

**Comment by haraldatbmw** [comment]
I have created a project to reproduce this issue.
https://github.com/haraldatbmw/subresources-showcase

**Comment by jaikiran** [comment]
@haraldatbmw I used the repo you pointed to and followed the exact instructions in the README, but couldn't reproduce any error. The resource is properly displayed:

```curl http://localhost:8080/subdir/index.html
<html>
<head><title>A page</title></head>
<body>
A HTML page in sub-dir
</body>
</html>
```
Even from browser it works fine. What exact error are you seeing? Can you paste the logs?

**Comment by haraldatbmw** [comment]
@jaikiran Just repeated my tests with Quarkus 0.23.1 with the same error result.

Here are some logfile snippets.

**Native Build-Call inside Docker:**

```
...
[INFO] --- quarkus-maven-plugin:0.23.1:native-image (default) @ subresources-showcase ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v C:\git\Back2Code.CampusStudents\subresources-showcase\target:/project:z --rm quay.io/quarkus/ubi-quarkus-native-image:19.2.0.1 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar subresources-showcase-1.0.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-JNI -H:-UseServiceLoaderFeature -H:+StackTrace
Build on Server(pid: 27, port: 40921)*
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]    classlist:   7,144.54 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]        (cap):   1,578.09 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]        setup:   3,191.88 ms
11:04:46,124 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]   (typeflow):  20,515.60 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]    (objects):  10,482.42 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]   (features):     392.79 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]     analysis:  32,354.57 ms
Printing call tree to /project/reports/call_tree_subresources-showcase-1.0.0-SNAPSHOT-runner_20190927_110519.txt
Printing list of used classes to /project/reports/used_classes_subresources-showcase-1.0.0-SNAPSHOT-runner_20190927_110523.txt
Printing list of used packages to /project/reports/used_packages_subresources-showcase-1.0.0-SNAPSHOT-runner_20190927_110523.txt
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]     (clinit):     528.24 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]     universe:   1,679.92 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]      (parse):   3,083.78 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]     (inline):   6,370.53 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]    (compile):  30,663.80 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]      compile:  41,870.77 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]        image:   2,698.25 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]        write:   1,083.06 ms
[subresources-showcase-1.0.0-SNAPSHOT-runner:27]      [total]:  97,629.41 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:57 min
[INFO] Finished at: 2019-09-27T13:06:12+02:00
[INFO] ------------------------------------------------------------------------
```

**Browser output:**
`RESTEASY003210: Could not find resource for full path: http://localhost:8080/subdir/index.html`

![quarkus-subresources](https://user-images.githubusercontent.com/49680586/65765414-7aff3d80-e128-11e9-97fe-d486a6e3bad8.png)

**Quarkus runtime output:**
```
C:\git\Back2Code.CampusStudents\subresources-showcase>docker run -i --rm -p 8080:8080 --name subresource-showcase quarkus/subresource-showcase
2019-09-27 11:07:31,092 INFO  [io.quarkus] (main) Quarkus 0.23.1 started in 0.009s. Listening on: http://0.0.0.0:8080
2019-09-27 11:07:31,093 INFO  [io.quarkus] (main) Profile prod activated.
2019-09-27 11:07:31,093 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```

**Comment by jaikiran** [comment]
Couple of interesting things:
1. You seem to be on Windows OS, which is different from what I have been testing.
2. Based on your screenshot, it looks like RestEasy is responding to this resource URL instead of being served statically? Maybe the resource URL matching is going wrong for some reason on your (Windows OS) setup? I have to look at the code later to see if any of this makes sense.

**Comment by stuartwdouglas** [comment]
This is almost certainly a windows issue. I will try and take a look when I am back home and have access to a windows machine

**Comment by jaikiran** [comment]
@stuartwdouglas, perhaps this is relevant https://github.com/quarkusio/quarkus/pull/4244?

**Comment by gsmet** [comment]
Closing. Please reopen if it's still an issue with the latest versions.

**Comment by fgd99** [comment]
Hi all,

I was facing the same issue trying to build the native image with gradle and the resources were not included.

The only workaround that I've found is to add in the build.gradle file:
```
quarkusBuild {
    nativeArgs {
        additionalBuildArgs = "-H:IncludeResources=META-INF/resources/.*"
    }
}
```

I hope that could be helpful.

regards

**Comment by opendoc-tree** [comment]
add **quarkus.native.additional-build-args = -H:IncludeResources=META-INF/resources/.***  in **application.properties** file
