### ISSUE TITLE
error: cannot get the logs from *v1.Ingress: selector for *v1.Ingress not implemented

### ISSUE THREAD

**Issue by jxtpro** [quarkusio/quarkus#40090]
### Describe the bug

部署k8s，暴漏出ing，出现502，出现错误：error: cannot get the logs from *v1.Ingress: selector for *v1.Ingress not implemented

### How to Reproduce?

# server.port
#quarkus.http.port=8888

# harbor
quarkus.container-image.username=admin
quarkus.container-image.password=Harbor12345

# docker image -> 10.7.0.147:8088/quarkus/demo-app:1.0
quarkus.container-image.registry=10.7.0.147:8088
quarkus.container-image.builder=docker

# docker
quarkus.container-image.group=library
quarkus.container-image.name=demo-app
quarkus.container-image.tag=1.0

# k8s
quarkus.kubernetes.replicas=1
quarkus.kubernetes.ingress.expose=true
quarkus.kubernetes.ingress.host=prod.svc.com
quarkus.kubernetes.ports.http.path=/prod

# k8s route rules
quarkus.kubernetes.ingress.rules.1.host=dev.svc.com
quarkus.kubernetes.ingress.rules.1.path=/dev
quarkus.kubernetes.ingress.rules.1.path-type=ImplementationSpecific
quarkus.kubernetes.ingress.rules.2.host=alt.svc.com
quarkus.kubernetes.ingress.rules.2.path=/ea
quarkus.kubernetes.ingress.rules.2.service-name=updated-service
quarkus.kubernetes.ingress.rules.2.service-port-name=tcpurl

# host
quarkus.kubernetes.hostaliases."10.7.0.147".hostnames=dev.svc.com,prod.svc.com,alt.svc.com

### Output of `uname -a` or `ver`

Linux xujie-system 6.5.13-7-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Dec 20 07:15:58 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.10" 2024-01-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 17.0.10+11.1 (build 17.0.10+11-LTS-jvmci-23.0-b27) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.10+11.1 (build 17.0.10+11-LTS-jvmci-23.0-b27, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Warning: JAVA_HOME environment variable is not set. /home/xujie/桌面/kubernetes-quickstart Found /home/xujie/桌面/kubernetes-quickstart/.mvn/wrapper/maven-wrapper.jar [INFO] Apache Maven Wrapper 3.2.0 [INFO] Detected MVNW_REPOURL environment variable https://maven.aliyun.com/repository/public Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /home/xujie/.m2/wrapper/dists/apache-maven-3.9.6-bin/80151456/apache-maven-3.9.6 Java version: 17.0.10, vendor: Oracle Corporation, runtime: /home/xujie/installed/graalvm-jdk-17.0.10+11.1 Default locale: zh_CN, platform encoding: UTF-8 OS name: "linux", version: "6.5.13-7-manjaro", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
I can't say I understand what the problem is here.

Please add more text describing what you are trying to do and how it's failing.

Thanks

**Comment by geoand** [comment]
Closing for the lack of feedback
