### ISSUE TITLE
Quarkus ActiveMQ Classic Extension

### ISSUE THREAD

**Issue by frekiv** [quarkusio/quarkus#40112]
### Description

Quarkus JMS Client & JMS Resource Adapter Extension for ActiveMQ Classic with DevServices

### Repository name

quarkus-activemq-classic

### Short description

Quarkus ActiveMQ Classic Extension

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- activemq-classic

### Team Members

- frekiv

**Comment by seravat** [comment]
@frekiv would this mean using the openwire protocol? Because ActiveMQ classic supports the AMQP protocol, and there is already an AMQP quarkus extension

**Comment by gastaldi** [comment]
This is already implemented in https://github.com/quarkiverse/quarkus-artemis
