### ISSUE TITLE
Quarkus guides code block background too dark

### ISSUE THREAD

**Issue by boriskrassimipro** [quarkusio/quarkus#40129]
### Describe the bug

On https://quarkus.io/guides the color of the code blocks has become too dark grey, so in light mode it is very hard to read comments. Wayback machine shows the background used to be lighter, and the comments were visible. The dark mode is ok.

### Expected behavior

All code, including comments shall be visible in light mode too

### Actual behavior

The background is too dark, and light grey comments are not visible. Besides, the contrast between the light window and the code block has become too large.

### How to Reproduce?

For example: https://quarkus.io/guides/hibernate-orm-panache

**Comment by geoand** [comment]
Is this still an issue?

**Comment by boriskrassimipro** [comment]
> Is this still an issue?

Not an issue anymore, got resolved nearly instantly. Many thanks!

**Comment by geoand** [comment]
Thanks a lot for the update!
