### ISSUE TITLE
Quarkus Dev UI - Calling gRPC endpoint is not working

### ISSUE THREAD

**Issue by darrenclark** [quarkusio/quarkus#40123]
### Describe the bug

I am seeing some JS errors when trying to use the Quarkus Dev UI (on Quarkus 3.9.3) to query a sample gRPC endpoint:

<img width="1840" alt="Screenshot 2024-04-17 at 11 49 55 AM" src="https://github.com/quarkusio/quarkus/assets/446024/316efb62-b2c8-4c1a-941b-e1b55f0ce4af">

### Expected behavior

- successful gRPC responses are displayed in the UI
- gRPC responses with a non-OK gRPC status code are displayed in the UI

### Actual behavior

Seeing JS exceptions in Chrome

### How to Reproduce?

Reproducer: https://github.com/darrenclark/reproduce-quarkus-grpc-dev-ui-issue

1. Clone the above repo
2. Run `quarkus dev`
3. Open dev UI -> navigate Extensions -> gRPC -> Services
4. Open Chrome console
5. Try to query one of the gRPC APIs, error will popup in Chrome console.

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Quarkus version or git rev

3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by phillip-kruger** [comment]
This is something that broke with the upgrade to codemirror 6. I am having a look to fix this

**Comment by phillip-kruger** [comment]
Ok I fixed this in the upstream javascript web component. I'll close here when that update is done in Quarkus
