### ISSUE TITLE
Upgrade GraalVM to 19.2.0.1

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#4013]
The GraalVM team released a critical patch update today: [19.2.0.1](https://github.com/oracle/graal/releases/tag/vm-19.2.0.1) ([release note](https://www.graalvm.org/docs/release-notes/19_2/#19201)).

**Comment by gsmet** [comment]
@cescoffier ping to create the images :).

**Comment by gastaldi** [comment]
Since https://github.com/quarkusio/quarkus/pull/4043 was merged I think this issue can be closed?

**Comment by gastaldi** [comment]
Also worth adding a `noteworthy` label on it ;)

**Comment by gsmet** [comment]
I removed the label as the PR already has one.
