### ISSUE TITLE
Generate ad-hoc signed JAR in `JarResultBuildStepTest`

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#40156]
In #40001 we're using the dependency plugin to download an already signed JAR to run the `JarResultBuildStepTest`. It would be nice if we could create one on the fly if possible (with Shrinkwrap?) and then sign it with some randomly generated keys.

_Originally posted by @galderz in https://github.com/quarkusio/quarkus/issues/40001#issuecomment-2058792934_

**Comment by DShivansh** [comment]
Hey @gastaldi 
I was thinking of picking this issue so far I have figured out how to make a jar using shrinkwarp but I am not sure how to sign the jar programmatically do you have any suggestions on this.

**Comment by DShivansh** [comment]
Hi @galderz 
I saw your comment -> https://github.com/quarkusio/quarkus/pull/40001#issuecomment-2058792934
I was just wondering whether we can use bouncycastle as I could not find any other way to generate certificate on the fly.

**Comment by galderz** [comment]
@DShivansh That's probably fine, just add it as a test dependency.

**Comment by DShivansh** [comment]
Hi @galderz 
I have created the PR but github action is failing and I am not able to understand the reason as to why is it happening can you please help me with this?
