### ISSUE TITLE
Redis client fails when cluster / sentinel configuration is changed

### ISSUE THREAD

**Issue by ivivanov-bg** [quarkusio/quarkus#40151]
### Describe the bug

When connected to redis running in sentinel mode, writing fails when master node is changed.

### Expected behavior

Redis client to automatically detect the cluster topology change and to issue commands to the new master

### Actual behavior

Commands are issued to the previous master node, resulting in
```
READONLY You can't write against a read only slave
```

### Additional information

Most probably this is caused by an issue in the underlying redis client.

[vertx-redis-client#320](https://github.com/vert-x3/vertx-redis-client/issues/320)

**Comment by Ladicek** [comment]
This will be fixed in Vert.x 4.5.10.

**Comment by Ladicek** [comment]
Fixes in #43041.
