### ISSUE TITLE
Unable to see database changes in tests

### ISSUE THREAD

**Issue by rafasf** [quarkusio/quarkus#40174]
### Describe the bug

Querying for a record after making a change using the `#update`, from `PanacheRepository<T>` method doesn't reflect the change.

Here's an example (the same as in the reproducer artefact attached): 

### 1 Test

```java
@Test
@TestTransaction
void changes_fruit_name() throws Exception {
   repository.persist(new Fruit("apple", "description", "a1"));
   repository.changeName("Apple: Gala", "a1");

    var fruit = repository.find("reference", "a1").firstResult();

    assertThat(fruit.getName()).isEqualTo("Apple: Gala");
}
```

### 2 The implementation of `#changeName`

```java
@Transactional
public void changeName(String name, String reference) {
    update(
            "name = :name where reference = :reference",
            Parameters
                    .with("name", name)
                    .and("reference", reference));

}
```

### 3 Seeing the correct output

The interesting, _or weird part is_, the expected result is correct when using the entity manager directly, as shown below:

```java
@Test
@TestTransaction
void changes_fruit_name_checking_natively() throws Exception {
   repository.persist(new Fruit("apple", "description", "a1"));
   repository.changeName("Apple: Gala", "a1");

    var fruit = (Object[]) repository.getEntityManager()
            .createNativeQuery("select * from Fruit where reference = ?")
            .setParameter(1, "a1")
            .getSingleResult();

    assertThat(fruit[1]).isEqualTo("Apple: Gala");
}
```

### Expected behavior

Expect to see the record changed when retrieving with `#find` or other framework methods.

### Actual behavior

The record returned has the information from the first time it was persisted, as part of the setup.

### How to Reproduce?

[reproducer-repository-test.tgz](https://github.com/quarkusio/quarkus/files/15052318/reproducer-repository-test.tgz)

### Output of `uname -a` or `ver`

Darwin NDg2Nwo 23.3.0 Darwin Kernel Version 23.3.0: Thu Jan  4 13:56:14 PST 2024; root:xnu-10002.81.5~13/RELEASE_ARM64_T8112 arm64 arm Darwin

### Output of `java -version`

openjdk 21.0.2 2024-01-16 LTS OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

openjdk 21.0.2 2024-01-16 LTS OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)

**Comment by DavideD** [comment]
I will have a look at the reproducer

**Comment by rafasf** [comment]
> I will have a look at the reproducer

Did you have a chance to take an initial look?

**Comment by yrodiere** [comment]
@DavideD is on PTO, but I'm sure he'll provide an update when he's back.

**Comment by rafasf** [comment]
👋  Did anyone have sometime to take a look?

**Comment by DavideD** [comment]
No, I will have a look now

**Comment by DavideD** [comment]
The problem is that the entity gets cached, so when you execute the find it returns the value cached in the session.

If you clear the session before running the find query, it will work:
```java
	@Test
	@TestTransaction
	void changes_fruit_name() {
		repository.persist( new FruitEntity( "apple", "description", "a1" ) );
		repository.changeName( "Apple: Gala", "a1" );
		repository.getEntityManager().clear();

		var fruit = repository.find( "reference", "a1" ).firstResult();

		assertThat( fruit.name ).isEqualTo( "Apple: Gala" );
	}
```

or, you can refresh the entity:
```java
		FruitEntity entity = new FruitEntity( "apple", "description", "a1" );
		repository.persist( entity );
		repository.changeName( "Apple: Gala", "a1" );
		repository.getEntityManager().refresh( entity );

		assertThat( entity.name ).isEqualTo( "Apple: Gala" );
	}
```

It works when you use the entity manager because you are running an SQL query on the database to get the entity.

I will close this issue because this is not a bug, but feel free to comment here if you have more questions.

**Comment by rafasf** [comment]
Great thanks for looking and providing a solution.

That's better than using native querty to do the asserts!
