### ISSUE TITLE
More complete SecurityEvents

### ISSUE THREAD

**Issue by mrickly** [quarkusio/quarkus#40170]
### Description

I have noticed the following when using SecurityEvents: 

- An `AuthorizationSuccessEvent` is fired when a REST resource or method annotated with `@PermitAll` is called. However the `SecurityIdentity` of that event is `null`. I'd rather know the `SecurityIdentity` even in that case.
-  When a method (as opposed to a REST resource) is annotated with an RBAC annotation, then the event properties of the `AuthorizationSuccessEvent` or `AuthorizationFailureEvent` fired has not `RoutingContext`. It would be nice to have a way to determine the method.

**Comment by mrickly** [comment]
@sberyozkin : Do you have an opinion on this enhancement proposal?

**Comment by mrickly** [comment]
Hello @michalvavrik , thank you for your reply. Could you clarify this statement for me?

> However when the proactivate authentication is enabled, we can do that.

Does that mean that you could do it, but don't do it currently? Apparently, it is not done, since I get an authentication event with the correct principal, but the AuthorizationSuccessEvent has not SecurityIdentity.

**Comment by mrickly** [comment]
Thanks for confirming. Regarding the second question, you wrote
> I'd expect that SecurityIdentity will have attribute with the RoutingContext set. Check the attributes. Or access it programmatically from the Arc container
It looks like the `SecurityConstrainer.check` method gets the location (the full name of the method annotated with `RolesAllowed`), but that information is not passed as an attribute of the `AuthorizationSuccessEvent/AuthorizationFailureEvent`.

**Comment by mrickly** [comment]
@michalvavrik : To summarize what we would like: 

- identity in authorization events (even `PermitAll`), provided proactive authentication is enabled
- method annotated with `RolesAllowed` in authorization events (as a substitute for the routing context when it isn't available)
- roles in the `RolesAllowed` annotation in the case of an `AuthorizationFailedEvent`  

I am not sure that we need the routing context at all cost (if the method name is available instead). In any case, none of the two options seem to work currently for a RolesAllowedCheck performed downstream from the REST resource: the ctx from the identity is null and any method call on RoutingContext throws a `jakarta.enterprise.inject.IllegalProductException`.

**Comment by mrickly** [comment]
I agree that the `roles in the RolesAllowed annotation in the case of an AuthorizationFailedEvent` is more of a nice to have. It's true that if a user gets a 403 from somewhere, he will probably make sure to obtain the required roles. In general, we have the requirement that security relevant actions (covered by the events) must be logged for security audit purposes.  

I will try to provide a minimal reproducer for my claim today or tomorrow.

**Comment by mrickly** [comment]
[quarkus-40170-reproducer.zip](https://github.com/quarkusio/quarkus/files/15322876/quarkus-40170-reproducer.zip)
@michalvavrik : This is a small reproducer with a test for the standard case (RolesAllowed on the resource) and the non-standard case (RolesAllowed delegated to a bean method). The second test shows that: 

1. `event.getSecurityIdentity().getAttribute(RoutingContext.class.getName())` is null
2.  `Arc.container().instance(RoutingContext.class).get().currentRoute().getPath()` throws `IllegalProductException`.

**Comment by michalvavrik** [comment]
thanks @mrickly , 

> Arc.container().instance(RoutingContext.class).get().currentRoute().getPath() throws IllegalProductException

okay so it seems that async observer is activated with a brand new CDI request context which is not pre-populated with the `RoutingContext`

> event.getSecurityIdentity().getAttribute(RoutingContext.class.getName()) is null

I believe this is `@TestSecurity` specific and you won't reproduce this in a production unless you have a custom `HttpAuthenticationMechanism`. However it is still a bug (in the `quarkus-test-security`) I'll look into ways of fixing it. I'll also re-check if we cannot just add the `RoutingContext` without bigger cost, though I think it cannot be avoided.
