### ISSUE TITLE
Support Mapper applied in the query result in Panache

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#4017]
Spring Data JPA and Apache DeltaSpike provides possibility to mapping the query result to another type.

eg. 

`PostDto findByStatus(status)` to convert Post to PostDto automatically.

```java
@Mapper(mymapper.class)
PostDto findByStatus(status)
```
to convert Post to PostDto by the custom mapper.

And It should also convert the model type in a `List`, `Stream`, `Optional`, `CompleteFuture` etc.

**Comment by ard333** [comment]
I also need custom result mapping in panache, so I don't need to use [Spring Data JPA API](https://github.com/quarkusio/quarkus/issues/6205) :eyes:

**Comment by ard333** [comment]
It will be a great feature, so we don't need to use [Spring Data JPA API](https://github.com/quarkusio/quarkus/issues/6205). :eyes:

**Comment by loicmathieu** [comment]
There is an open issue for supporting projection inside Hibernate with Panache: #6261

Projection should be a better implementation than a mapper as it will send the projection to the database returing only the needed column.

If you really want a mapper, you can still use MapStruct anyway ;)

Can we close this one and focus on projection support ?

**Comment by hantsy** [comment]
The Apache DeltaSpike also has similar feature, not sure if possible to make it work in Quarkus.

**Comment by loicmathieu** [comment]
@hantsy I understand it, but as I said I think that projection is a better use case and allow to map an entity to a POJO with the advantage of also restricting the number of columns to load from the database (if possible, still investigating).

As it provides the same kind of functionality, I propose to close this one.
