### ISSUE TITLE
Getting class build error while using aws sdk 1.1 with quarkus application version 3.8

### ISSUE THREAD

**Issue by bala4work** [quarkusio/quarkus#40177]
### Describe the bug

Error: Class initialization of com.amazonaws.services.lambda.AWSLambdaClient failed. This error is reported at image build time because class com.amazonaws.services.lambda.AWSLambdaClient is registered for linking at image build time by command line and command line. Use the option

Getting above error when building using 
build -Dquarkus.package.type=native -Dquarkus.native.container-build=true --stacktrace

### Output of `java -version`

java version "21.0.2"

### Quarkus version or git rev

3.8.2

**Comment by galderz** [comment]
We recently had an issue with the AWS v1 SDK, see https://github.com/quarkusio/quarkus/issues/39548. The relevant comment here would be https://github.com/quarkusio/quarkus/issues/39548#issuecomment-2032066278. It seems that support for native compilation on AWS v1 SDK has a lot of problems. You probably want to use AWS v2 SDK instead.

**Comment by zakkak** [comment]
@bala4work have you tried @galderz's suggestion? Is this still an issue for you? If so please provide a minimal reproducer.

**Comment by geoand** [comment]
Closing for a lack of a feedback.
