### ISSUE TITLE
ServerRequestFilter Example if-else bug

### ISSUE THREAD

**Issue by Petkomat** [quarkusio/quarkus#40195]
**Describe the bug**

The method below disallows (only) GET requests rather than allows them (as claimed in the comment):

```java

import java.util.Optional;

class Filters {
    @ServerRequestFilter
    public Optional<RestResponse<Void>> getFilter(ContainerRequestContext ctx) {
        // only allow GET methods for now
        if(ctx.getMethod().equals(HttpMethod.GET)) {
            return Optional.of(RestResponse.status(Response.Status.METHOD_NOT_ALLOWED));
        }
        return Optional.empty();
    }
}
```

**Which pages**

[https://quarkus.io/guides/rest#request-or-response-filters](https://quarkus.io/guides/rest#request-or-response-filters)

**Comment by maxandersen** [comment]
thanks for noticing. opened #40476 to fix this.
