### ISSUE TITLE
Improve the application cofiguration

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#4021]
When I wrote my [Quarkus sample](https://github.com/hantsy/quarkus-sample), I found an issue.
I am tried to use `quarkus-test-h2`, and it requires extra configuration in *src/test/resources/application.properties*. 

If I do not define the  `quarkus.hibernate-orm.database.generation` in this test application properties. It will complain the tables are not existed when I ran tests.

But I have defined such one in the application properties(src/main/resources). 

`quarkus.hibernate-orm.database.generation = drop-and-create`

When I ran tests, the test application properties will **replace** the entire application.properties file. I think it could be **override**.

1. Read the application properties firstly,
2. Then read the test application properties.  
3. If there is an existed property key in step 1, override it by replacing the value in the step 2.

**Comment by gsmet** [comment]
That's how Maven works, we want change that.

What you need is the profile feature: https://quarkus.io/guides/application-configuration-guide#configuration-profiles .
