### ISSUE TITLE
State cookies (q_auth) keeps piling up in code flow

### ISSUE THREAD

**Issue by segersb** [quarkusio/quarkus#40268]
### Describe the bug

Quarkus does not properly manage existing q_auth cookies during the OIDC code flow in web applications. When the OIDC code flow is triggered (e.g., upon access token expiration), Quarkus generates a new q_auth cookie without considering if one already exists. This results in multiple q_auth cookies accumulating in the user's browser over time.

### Expected behavior

Quarkus should check for existing q_auth cookies before generating a new one during the OIDC code flow. If an existing q_auth cookie is found, it should either be reused or invalidated before a new cookie is created. This approach would prevent the accumulation of q_auth cookies in the user's browser.

### Actual behavior

Whenever the OIDC code flow is initiated by Quarkus, a new q_auth cookie is created regardless of whether a similar cookie already exists. This leads to an accumulation of q_auth cookies, particularly noticeable in scenarios with frequent token expirations and renewals, such as when a heartbeat mechanism in the frontend continuously calls an endpoint after the access token expires. Eventually, this accumulation can cause the browser to send an HTTP 431 error due to oversized request headers.

### How to Reproduce?

1. Set up a Quarkus application with OIDC code flow authentication.
2. Implement a frontend heartbeat mechanism that continuously calls a backend endpoint using the current access token.
3. Allow the access token to expire, triggering the OIDC code flow repeatedly through the heartbeat calls.
4. Observe the accumulation of q_auth cookies as each new token expiration leads to a new code flow initiation.
5. After multiple heartbeat cycles and token expirations, attempt to access the application and observe an HTTP 431 error (Request Header Fields Too Large), indicative of too many q_auth cookies.

### Additional information

Temporary Solution
We have implemented a workaround by extending the default OidcAuthenticationMechanism. In the overridden getChallenge method, we explicitly check for and expire any existing q_auth cookies before proceeding with the default Quarkus OIDC implementation.

```
@Alternative
@Priority(1)
@ApplicationScoped
public class CustomOidcAuthenticationMechanism implements HttpAuthenticationMechanism {
    @Inject
    OidcAuthenticationMechanism oidcAuthenticationMechanism;

    @Override
    public Uni<SecurityIdentity> authenticate(RoutingContext context, IdentityProviderManager identityProviderManager) {
        return oidcAuthenticationMechanism.authenticate(context, identityProviderManager);
    }

    @Override
    public Uni<ChallengeData> getChallenge(RoutingContext context) {
        System.out.println("custom getChallenge");
        context.request().cookies().stream()
                .filter(cookie -> cookie.getName().startsWith(OidcUtils.STATE_COOKIE_NAME))
                .forEach(cookie -> {
                    System.out.println("expire cookie: " + cookie.getName());
                    context.response().addCookie(Cookie.cookie(cookie.getName(), cookie.getValue()).setPath(cookie.getPath()).setMaxAge(0));
                });

        return oidcAuthenticationMechanism.getChallenge(context);
    }
}
```

Suggestion for Quarkus Improvement
It would be beneficial for Quarkus to incorporate a similar check and handling mechanism for q_auth cookies directly within its default OIDC authentication mechanisms to prevent this issue from affecting other users.

**Comment by sberyozkin** [comment]
@segersb What Quarkus version is it ? The state cookie is removed the moment it is detected, and we have a good number of tests confirming it is null at the end.
What I will do, I'll update https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-openid-connect-web-authentication-quickstart/src/test/java/org/acme/security/openid/connect/web/authentication/CodeFlowTest.java to double check it and then if it works as expected I'll ask you to modify that test to reproduce the problem

**Comment by segersb** [comment]
We're on the laster 3.9.4

I did notice "removeCookie" calls in the "CodeAuthenticationMechanism" class
However it seems those are called when the flow processes the redirect, not in the initial getChallenge

**Comment by sberyozkin** [comment]
@segersb But in any case, I can also do what I've been thinking about doing for a long time and never done, the state cookie age is set to 30 mins by default, it should be set max to 5 mins by default and users should be able to tune it to 1 min if they need to, which will accelerate the browser getting rid of any stale state cookies

**Comment by segersb** [comment]
We ran into a problem because we use Vaadin for our frontend, and it sends out heartbeat requests. These heartbeats don’t interact with OIDC, so when the access token expires, each request ends up creating a new cookie. We can adjust the heartbeat interval, but if a heartbeat fails due to an expired token, it tries again every second. This was a problem even though the cookies are only good for 30 minutes.

Setting the property like you suggested worked out great. Our own fix, where we expire the tokens ourselves, does pretty much the same thing. I’m not totally sure when you'd need multiple code flows, but if that's the standard and it's working as intended, then it's all good.

Thanks for your help. I’m going to close the ticket now.

**Comment by sberyozkin** [comment]
Thanks @segersb, I'll re-open just so that I remember to do this task of having the state cookie timeout controlled better, and will close once that is done, thanks
