### ISSUE TITLE
OidcClientImpl does not support quarkus.oidc.credentials.client-secret.method=query

### ISSUE THREAD

**Issue by TheHandOfNOD** [quarkusio/quarkus#40260]
### Describe the bug

I configured the OIDC client to use `quarkus.oidc.credentials.client-secret.method=query`.

In my POM I have the following 2 dependencies, which I understand from the helptext from the documentation should be sufficient to make it work:

```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc-client</artifactId>
        </dependency>
```

The documentation I refer to is [OIDC configuration reference](https://quarkus.io/guides/security-oidc-configuration-properties-reference)

See this screenshot for the relevant part I am referring to.
![image](https://github.com/quarkusio/quarkus/assets/10324233/545e630a-c9db-4cc7-a190-e970393e2a66)

Unfortunately when I set this parameter the `client_id` and `client_secret` are not attached as Query Parameter, so I debugged the code of the `OidcClientImpl` and there seems to be a missing implementation. I checked the implementation beginning from version *3.8* up 'til *main*  which is why I create this bug.

If I understand it correctly (and I changed this particular code within my own OidcClientImpl) the handling is just missing for this configuration value. See `io.quarkus.oidc.client.runtime.OidcClientImpl#postRequest` method:

```
else if (OidcCommonUtils.isClientSecretPostAuthRequired(oidcConfig.credentials)) {
      body = !refresh ? copyMultiMap(body) : body;
      body.set(OidcConstants.CLIENT_ID, oidcConfig.clientId.get());
      body.set(OidcConstants.CLIENT_SECRET, OidcCommonUtils.clientSecret(oidcConfig.credentials));
}
```

in this particular `if` condition I think should be added another `if` condition which checks if the values should be added to the `body` of the request or as `query` parameter.

```
else if (OidcCommonUtils.isClientSecretPostAuthRequired(oidcConfig.credentials)) {
      body = !refresh ? copyMultiMap(body) : body;
      body.set(OidcConstants.CLIENT_ID, oidcConfig.clientId.get());
      body.set(OidcConstants.CLIENT_SECRET, OidcCommonUtils.clientSecret(oidcConfig.credentials));
}
```

set them as query parameter into the request:
```
request.setQueryParam(OidcConstants.CLIENT_ID, oidcConfig.getClientId().get());
request.setQueryParam(OidcConstants.CLIENT_SECRET, OidcCommonUtils.clientSecret(oidcConfig.credentials));
```

### Expected behavior

When I configure the property `quarkus.oidc.credentials.client-secret.method=query` with the value query, the `client_id` and `client_secret` are actually used and appended as query parameter to the post request.

### Actual behavior

The query parameter are not set, even though the values are configured.

### Output of `uname -a` or `ver`

Darwin XXX.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64 arm Darwin

### Output of `java -version`

17

### Quarkus version or git rev

3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /opt/homebrew/Cellar/maven/3.9.6/libexec Java version: 17.0.3, vendor: Amazon.com Inc., runtime: /Users/daniel/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home Default locale: en_AT, platform encoding: UTF-8 OS name: "mac os x", version: "14.4.1", arch: "aarch64", family: "mac"

**Comment by TheHandOfNOD** [comment]
I do use indeed a provider which requires client_id and secret to be sent as query parameters. Unfortunately their documentation is also misleading and states that they need it in the POST request body, but everytime I send it to them without the query parameters I get a 401.

Nevertheless I think it's still relevant for the oidcclientimpl and I am not sure which part of the documentation you mean to be honest, because I am just referring to the one pasted in the image. But maybe I just understand the help text wrong.

**Comment by sberyozkin** [comment]
Closing as not planned for now as Personio Auth API is not Oauth2-grant aware. We may re-open it depending on how # 40258 progresses
