### ISSUE TITLE
Introduce DevServices in quarkus:run Maven goal

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#40270]
### Description

Currently `mvn quarkus:run` simply runs the built artifact, but it would be very handy if it also setup DevServices in a similar manner as `@QuarkusIntegrationTest` does.

**Comment by geoand** [comment]
@aloubyansky I opened https://github.com/quarkusio/quarkus/pull/40273 as a draft. It's pretty hacky, but I don't see really see a better way around it given how `quarkus:run` is meant to work

**Comment by maxandersen** [comment]
How do I as user turn this on/off ?

The main idea of quarkus:run is to have something closer to prod meaning hooking up docker functionality is not (always) wanted.

**Comment by geoand** [comment]
> How do I as user turn this on/off ?

The same way you would for regular dev services, i.e.  you provide the appropriate configuration option.

**Comment by aloubyansky** [comment]
We should have some doc about it

**Comment by geoand** [comment]
Seems like it it's only documented in Azure Functions, so we should probably document it in the Maven and Gradle guides

**Comment by maxandersen** [comment]
> > How do I as user turn this on/off ?
> 
> 
> 
> The same way you would for regular dev services, i.e.  you provide the appropriate configuration option.

But that then impliess to me that when I use Quarkus:run there is "stuff" added to the classpath and startup that would not be present when I do jar run?

This should imo be a deliberate choice or at least be possible to completely turn off as I wouldn't otherwise be able to test how the Quarkus run behaves in prod like setup.

**Comment by maxandersen** [comment]
Ie. Quarkus run should fail fast rather than spend time hooking up to docker (which can be quite slow!). 

It could then show command option to run to enable those services ? WDYT?

**Comment by maxandersen** [comment]
Alternative - make a devrun action.

**Comment by geoand** [comment]
> But that then impliess to me that when I use Quarkus:run there is "stuff" added to the classpath and startup that would not be present when I do jar run?

Not true

**Comment by geoand** [comment]
The mechanism is the same as used in `@QuarkusIntegrationTest` where DevServices are started and then their configuration is used to set system properties for the production jar.

**Comment by maxandersen** [comment]
So the wiring up start of services is done outside the actually run Quarkus process ?

**Comment by geoand** [comment]
Yes

**Comment by maxandersen** [comment]
okey, but still should have a way to turn this explicit off IMO. I would even suggest it is something that should be turned on.

quarkus:run is supposed to fail/start fast and get as close to same  behavior as a jar run.

**Comment by geoand** [comment]
I don't really agree, as it makes `quarkus:run` pretty unusable, but I don't care enough about it to fight this too much

**Comment by gsmet** [comment]
I'm also not convinced it's a good idea. Dev Services were specifically designed for dev mode and I wouldn't expect them to run for `quarkus:run`. If you want Dev Services, just run in dev mode.

**Comment by geoand** [comment]
> Dev Services were specifically designed for dev mode

That same argument could have been used against their use in `@QuarkusIntegrationTest`  yet they work remarkably well in that case too.

**Comment by geoand** [comment]
We can always make this opt-in
