### ISSUE TITLE
SecurityConfig marked as Runtime, but used in Static Init

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#40318]
### Describe the bug

The  `SecurityConfig` mapping is marked as `RUNTIME`:
https://github.com/quarkusio/quarkus/blob/c06cf1e22afea4baedb3903e26613383197e9ddc/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java#L11-L13

But its configuration is used during `STATIC_INIT`:
https://github.com/quarkusio/quarkus/blob/81386fd5531cdb36d2edcc7c09ef031bfab2d2cb/extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/EagerSecurityFilter.java#L60-L68

Due to a configuration bug, runtime defaults were leaking to static init. With that fixed, some tests started to fail because the default is `false`, and tests expected events to be available. Regardless, the `EagerSecurityFilter` configuration cannot be changed after the build because `@Provider` is initialized during static init.

This was discovered with https://github.com/quarkusio/quarkus/pull/40225/, and the mapping was changed to `BUILD_AND_RUN_TIME_FIXED` to fix the tests, but we must decide what the correct behavior should be.

**Comment by michalvavrik** [comment]
Thank you for cc me.

I'd suggest we can initialize `SecurityEventHelper` lazily (on the first request) inside RESTEasy Classic. Implementation in Quarkus REST is better as it's initialized on application startup. If my memory serves well, in other cases it's only used at runtime, but we need to check when fixing this issue.

Regarding security impact of this bug - if `quarkus.security.events.enabled` runtime value wasn't reflected, it would mean that security events were not produced in case the property were only set at runtime. In my eyes, it's a bug, but not a vulnerability.

**Comment by sberyozkin** [comment]
I recall that for the csrf work,  I had to convert @Provider to ServerHandler, though that was for Quarkus REST.
Lazy initialization for the Resteasy Classic case sounds reasonable

**Comment by michalvavrik** [comment]
`JaxRsPermissionChecker` is using it as well (it actually receives it as method parameter in one of cases from this filter). so I'll just put it there. Thanks for a feedback.
