### ISSUE TITLE
WebSockets Next: security integration

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#40312]
### Description

Follow-up of https://github.com/quarkusio/quarkus/pull/39142.

**Comment by sberyozkin** [comment]
Hi @mkouba, can you explain a little bit how one can retain the property (such as a token) which is available at the on-open step in the WS-Next, such that this property is returned with subsequent on-message steps ? 
If there was some code/test showing how it can be done for some custom header, let's  say `X-WebSocket` HTTP header is available at the upgrade/onOpen time, and then it is bound to the WS channel and this header is accessible in the onMessage methods, then it would be ideal.

I guess we'll have to follow a step similar to the one shown in https://github.com/quarkusio/quarkus/files/15130826/quarkus-sec-issue.zip (a reproducer for #40307)

Another question, is resolving #40307 must be done first before planning this enhancement work ?

Thanks Sergey

**Comment by michalvavrik** [comment]
I was thinking the authentication must have HTTP request scope rather than to be session-scoped bean. Which would allow us to rely what we have. But that's how far I got in studying CDI-next reference. Let's see what Martin thinks.

> Another question, is resolving https://github.com/quarkusio/quarkus/issues/40307 must be done first before planning this enhancement work ?

nope, not related

**Comment by mkouba** [comment]
> I was thinking the authentication must have HTTP request scope rather than to be session-scoped bean. Which would allow us to rely on what we have already. But that's how far I got in studying WS-next reference. Let's see what Martin thinks.

The problem is that for WebSockets there is only the initial handshake HTTP request and afterwards, after upgrade, when processing incoming messages there's no HTTP request available at all; e.g. we do activate the request context for an `@OnTextMessage` callback but it's not backed by an HTTP request.

>> Another question, is resolving https://github.com/quarkusio/quarkus/issues/40307 must be done first before planning this enhancement work ?

> nope, not related

It's not related to WebSockets at all actually ;-)

**Comment by michalvavrik** [comment]
> The problem is that for WebSockets there is only the initial handshake HTTP request and afterwards, after upgrade, when processing incoming messages there's no HTTP request available at all; e.g. we do activate the request context for an @OnTextMessage callback but it's not backed by an HTTP request.

Thanks. I guess I need to dig more. But AFAICT CDI request context activation, we don't really care as what I wanted to reuse is HTTP Authenticator / Authorizer and they do work with RoutingContext rather than CDI req. ctx. I mean _one connection == one authentication_. However if WS will send authN headers later, we need something smarter. Okay.

**Comment by mkouba** [comment]
> > The problem is that for WebSockets there is only the initial handshake HTTP request and afterwards, after upgrade, when processing incoming messages there's no HTTP request available at all; e.g. we do activate the request context for an @OnTextMessage callback but it's not backed by an HTTP request.
> 
> Thanks. I guess I need to dig more. But AFAICT CDI request context activation, we don't really care as what I wanted to reuse is HTTP Authenticator / Authorizer and they do work with RoutingContext rather than CDI req. ctx. I mean _one connection == one authentication_.

I guess I need to dig more as well :-)

> However if WS will send authN headers later, we need something smarter. Okay.

It's not that it sends the headers later. In fact, WS itself does not send metadata along with messages. That's up to the procotol which is something we don't control.

Maybe we could authenticate/authorize the initial handshake request?

FYI the opening handshake is described here: https://datatracker.ietf.org/doc/html/rfc6455#section-1.3

BTW this the security part of the Jakarta WS spec: https://jakarta.ee/specifications/websocket/2.1/jakarta-websocket-spec-2.1#security

**Comment by michalvavrik** [comment]
> > However if WS will send authN headers later, we need something smarter. Okay.
> 
> It's not that it sends the headers later. In fact, WS itself does not send metadata along with messages. That's up to the procotol which is something we don't control.
> 
> Maybe we could authenticate/authorize the initial handshake request?

Yes, that sounds good to me ATM (see below)

> FYI the opening handshake is described here: https://datatracker.ietf.org/doc/html/rfc6455#section-1.3
> 
> BTW this the security part of the Jakarta WS spec: https://jakarta.ee/specifications/websocket/2.1/jakarta-websocket-spec-2.1#security

Thank you, I'll study it.


Sorry @mkouba I didn't mean to steal @sberyozkin show, could you please also answer his question when the time is right for you. This was helpful though.

**Comment by mkouba** [comment]
> Hi @mkouba, can you explain a little bit how one can retain the property (such as a token) which is available at the on-open step in the WS-Next, such that this property is returned with subsequent on-message steps ? If there was some code/test showing how it can be done for some custom header, let's say `X-WebSocket` HTTP header is available at the upgrade/onOpen time, and then it is bound to the WS channel and this header is accessible in the onMessage methods, then it would be ideal.
> 

I have to admit that I have no idea yet ;-). In any case, we can extract the information from the initial handshake request and store it either in a `@SessionScoped` bean or directly in the connection object.

> I guess we'll have to follow a step similar to the one shown in https://github.com/quarkusio/quarkus/files/15130826/quarkus-sec-issue.zip (a reproducer for #40307)
> 

But this reproducer does not provide a working solution, or? 

> Another question, is resolving #40307 must be done first before planning this enhancement work ?
> 
> Thanks Sergey

**Comment by sberyozkin** [comment]
Thanks @michalvavrik @mkouba, and yeah, was a good joke, Michal, that it was my show :-)

The use case which I have in mind, and is particularly relevant to the Quarkus LangChain4j Chat Bot demos, is when I authenticate to Quarkus with OIDC, and now I request a Chat Bot resource which upgrades the request to the WS Next session. 
At this point, at the time of the initial handshake, Quarkus Security must've already created a Security Identity, and this is what I guess we need to retain.

So what Martin said,

>In any case, we can extract the information from the initial handshake request and store it either in a @SessionScoped bean or directly in the connection object.

Sounds good and hopefully simple enough, IMHO this is the path forward. I'm not sure what is best though, using the session scoped bean or  the connection object as a storage. The only requirement is to have `@Inject SecurityIdentity` available from the `@Authenticated` onMessage handlers.

@mkouba @michalvavrik, what do you think ?

**Comment by sberyozkin** [comment]
>using the session scoped bean or the connection object as a storage

The latter is probably better as it will let users avoid having to use `@SessionScoped` or is `@SessionScoped` a prerequisite for WS Next ?

**Comment by mkouba** [comment]
> using the session scoped bean or the connection object as a storage
> 
> The latter is probably better as it will let users avoid having to use `@SessionScoped` or is `@SessionScoped` a prerequisite for WS Next ?
> 
> I've read https://quarkus.io/guides/websockets-next-reference#cdi-scopes-for-websocket-endpoints, looks like `@SessionScoped` is not required, it is implicitly managed.

Each connection has its own session context. When a server/client endpoint callback is executed this session context is activated automatically. The advantage of the latter approach is that you could access the connection _outside_ an endpoint callback invocation. Which might be helpful but not necessary.

**Comment by sberyozkin** [comment]
Thanks @mkouba,

>The advantage of the latter approach is that you could access the connection outside an endpoint callback invocation. Which might be helpful but not necessary.

Interesting, I believe with Quarkus LangChain4j, users get responses in scope of the callback. I'm not certain if retaining it in the connection object might increase the likelihood of the identity going stale.  I suppose we can start with storing it in the session scope bean, and move it to the connection if necessary or make it configurable.

How would we get the security info the the WS Next session scope bean though, an we add a `quarkus-security` dependency only to it for WS Next to check the availability of `SecurityIdentity` ? (Not sure what else but `SecurityIdentity` we can retain, seems simplest)

**Comment by sberyozkin** [comment]
In general, this is how I'd suggest for a non-security extension to pick up whatever one of the security extensions converted into SecurityIdentity. https://github.com/quarkusio/quarkus-security alone which just SPI should give it, it gives `SecurityIdentity` interface but also an interface like TokenCredential which may come from OIDC, smallrye-jwt, etc as well. A light weight dependency.

**Comment by sberyozkin** [comment]
@mkouba Yes, something like that would be perfect to have I think.

> I will try to prepare something by the end of this week.

It would be awesome, if you get a chance to look at it

Thanks

**Comment by romulogranato** [comment]
@mkouba Hi Guys, I new on GitHub discussions. I'm currently using Quarkus WebSocket Next and tried to use Quarkus Security on callback method (@OnTextMessage), but it is not working for the @AuthorizationPolicy annotation. It is never called in the callback methods, either with the request context activated. The others annotations worked (@PermitAll, @DenyAll...).

Is there a way to check why is this happening?

Thanks

**Comment by michalvavrik** [comment]
We could also add validation for `@AuthorizationPolicy` in case someone miss that as well. I'll check and if it can be done with few lines of code, I'll add it.

**Comment by michalvavrik** [comment]
sure @romulogranato , I didn't mean to mention it, but if you really need `RoutingContext`, it is usually available as a `Securityidentity` attribute, so something like (meta code):
```
boolean check(SecurityIdentity identity) {
RoutingContext routingContext = identity.getAttribute(RoutingContext.class.getName());
return false;
}
```

should work. Anyway, I believe it works because it he have tests for `@PermissionsAllowed` but I need to check, add test and docs so it is possible I am wrong. Good luck at any rate!

**Comment by romulogranato** [comment]
@michalvavrik, thanks for looking into it.

I am probably doing something wrong, because I still can't use PermissionChecker for my project.

This is my code example:
`@PermissionsAllowed(value = "send-message")
    @OnTextMessage
    public void onMessage(WebSocketConnection connection, String code) {
        final String key = UUID.randomUUID().toString();
        final Event event = Event.builder()
                .action(code)
                .build();

        final String message = this.jsonParserUtil.parse(event, Event.class);
        this.kafkaService.send(message, key);

        return Response.noContent().build();
    }

    @PermissionChecker("send-message")
    public boolean checkPermission(WebSocketConnection connection, String code) {
        final String path = connection.handshakeRequest().path();
        final AuthRequestBodyDTO authRequestBodyDTO = AuthRequestBodyDTO.builder()
                .requestPath(path)
                .method(GET_METHOD)
                .build();

        LOGGER.infof("Authenticating %s", authRequestBodyDTO);
        this.authenticationService.authorize(code, authRequestBodyDTO);

        return true;
    }`

But when I send a request to the API, I've always receive 403 (Forbidden). It seems that the "Permission Checker" is never called., but the "Permissions Allowed" do the work and deny the access without the required permission 'checkPermission'.

Am I doing something wrong?

Sorry for being annoying.

**Comment by michalvavrik** [comment]
You use `public boolean checkPermission(WebSocketConnection connection, String code)` but I explicitly mentioned (SecurityIdentity identity)` only. The reason I offered `@PermissionChecker` is that you were trying to use `@AuthorizationPolicy` that offers you (relevant) 2 things:

- security identity
- routing context

The permission checker offers same, I think we just misunderstood each other. np

> I've always received UnauthorizedException

good, means it's just bad user experience of undocumented feature; I'll fix that.

Let me conclude this:

- all builtin security checks provided by Quarkus are performed on HTTP upgrade, which is before WS connection is opened. Therefore you will never be able to access `WebSocketConnection connection`. Honestly, it doesn't really makes sense because `@OnTextMessage` can be invoked million times as far as I am concerned. And you would perform security check again and again even though security-related stuff won't change.
- I will open PR this week to document and test `@PermissionChecker` with WS Next and improve validation so that scenarios that you describe results in build failure
- please open discussion https://github.com/quarkusio/quarkus/discussions if you have more questions and mention me that  (so that I can answer :-)) because this is a wrong place to discuss this. Thanks

**Comment by romulogranato** [comment]
Yes, you're right. This isn't the place to have this kind of discussion.

Anyway, thanks for all the insights.

**Comment by michalvavrik** [comment]
hey @romulogranato , please see https://github.com/quarkusio/quarkus/pull/45704 for how to use permission checkers with WS Next

**Comment by romulogranato** [comment]
Thanks for the feedback. I'll check the issue and follow what you are improving for the documentation.
