### ISSUE TITLE
It's not possible to recover from the database exception with the hibernate reactive

### ISSUE THREAD

**Issue by alexpoletaev** [quarkusio/quarkus#40314]
### Describe the bug

Consider we have an entity like this:
```java
@Table(name = "person")
@Entity
public class Person {

    @Id
    @GeneratedValue
    private UUID id;

    @Column(name = "first_name", nullable = false)
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    //getters/setters
}
```

repository (I'm using Panache)
```java
@ApplicationScoped
public class PersonRepository implements PanacheRepositoryBase<Person, UUID> {
}
```
and finally service:
```java
@ApplicationScoped
public class PersonService {

    private static final Logger log = Logger.getLogger(PersonService.class);

    @Inject
    PersonRepository repository;

    public Uni<Boolean> batchCreate(List<Person> persons) {
        return Multi.createFrom().iterable(persons)
                .onItem().transformToUniAndConcatenate(person -> Uni.createFrom().item(person)
                        .chain(repository::persist)
                        .replaceWith(Boolean.TRUE)
                        .onFailure().recoverWithItem(throwable -> {
                            log.warn("Something went wrong: " + throwable.getMessage());
                            return Boolean.FALSE;
                        })).collect().asList()
                .map(list -> list.stream().noneMatch(Boolean.FALSE::equals));
    }
}
```
According to [this](https://quarkus.io/blog/mutiny-failure-handling/) article it's possible to isolate underlying execution and catch exception to process the remaining correct records from `Multi`. In my real application I'm consuming a batch of records from Kafka and I'm expecting that incorrect records will be just logged, but other correct records from the batch will be saved to the database.
Kafka consumer example:
```java
@ApplicationScoped
public class PersonConsumer {

    @Inject
    PersonService service;

    @WithTransaction
    @Incoming("person.create")
    public Uni<Void> consume(List<Person> persons) {
        return service.batchCreate(persons).replaceWithVoid();
    }
}
```
So when I'm sending a message like this:
```
[
	{
		"lastName": "Bobson"
	},
	{
		"firstName": "Alice",
		"lastName": "Alisson"
	}
]
```
I'm expecting that Alice will be saved in the database and error message about Bob record (required first name is missed) is logged. But the whole message is "nacked" and nothing is saved to the database

### Expected behavior

One correct record from the batch is saved to the database. No Kafka errors

### Actual behavior

Kafka message is "nacked" and no records are saved to the database

**Comment by DavideD** [comment]
In this scenario,  `.chain(repository::persistAndFlush)` should also work without the transaction.

> Do I understand correctly, that if the whole method is wrapped in transaction and the **database** exception is thrown

This should happen for any kind of exception, if the actual database transaction is still open.
In case of exception, one usually doesn't want to have malformed data in the database.
Plus, the Hibernate session becomes unusable and should be recreated after an exception.

> I'm asking because if I throw my own exception (e.g. IllegalArgumentException) inside method wrapped with the transaction, then the recovering is working fine.

Are you throwing the exception when there's  an open transaction?
`@WithTransaction` will notify Hibernate that the operations executed on the database should belong to the same transaction. But, hibernate decides when to create the actual database transaction.

Personally, I would validate the data before touching the database when possible.
You might also want to have a look at [Hibernate Validator](https://hibernate.org/validator/).

**Comment by DavideD** [comment]
Closing this.
Feel free to comment here if you have more questions
