### ISSUE TITLE
Websockets Next: Kotlin Coroutines Support

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#40325]
### Description

Kotlin coroutines should be supported out-of-the-box, this means `suspend` functions and Kotlin `Flow` as return type.

see also: https://github.com/quarkusio/quarkus/discussions/38473#discussioncomment-8353461

In the "old" websocket Implementation this is a long standing issue (https://github.com/quarkusio/quarkus/issues/29929#issuecomment-1978788877)

**Comment by Ladicek** [comment]
I don't think we support `Flow` anywhere, and there's a simple extension function for `Flow` to convert to `Multi` (see https://smallrye.io/smallrye-mutiny/latest/guides/kotlin/). This is available out of the box when you use `quarkus-kotlin`.

I'm reducing the scope of this request to support of `suspend` functions, unless someone shows me where do we support `Flow`.

**Comment by mschorsch** [comment]
@Ladicek Resteasy Reactive has `Flow` Support.

**Comment by mschorsch** [comment]
Flow support was implemented in https://github.com/quarkusio/quarkus/pull/18222 long time ago.

**Comment by Ladicek** [comment]
OK, I see. Well, I'll see how that goes.

**Comment by mschorsch** [comment]
But as always, i'm happy that someone takes the time to improve the Kotlin support in Quarkus.
