### ISSUE TITLE
ContainerResponseFilter not invoked for not found urls

### ISSUE THREAD

**Issue by vkn** [quarkusio/quarkus#40331]
### Describe the bug

Hello, 
after migrating from 3.8.x to 3.9.x response filter annotated with `@Provider` is not called anymore if the response is 404
This was working in 3.8.x and before with resteasy reactive extension.

```java
@Provider
public class ResponseFilter implements ContainerResponseFilter {
    private static final Logger LOGGER = LoggerFactory.getLogger(ResponseFilter.class);

    private final HttpServerRequest request;
    private final LoggingBean loggingBean;

    @Inject
    public ResponseFilter(@Context HttpServerRequest request, LoggingBean loggingBean) {
        this.request = request;
        this.loggingBean = loggingBean;
    }

    @Override
    public void filter(ContainerRequestContext requestCtx, ContainerResponseContext responseCtx) {
        String uri = request.uri();
        LOGGER.info("ResponseFilter url {}", uri);
        loggingBean.log(uri);
    }
}

```

### Expected behavior

ContainerResponseFilter is not invoked for 404 responses

### Actual behavior

ContainerResponseFilter should also work for 404 responses

### How to Reproduce?

[code-with-quarkus.tar.gz](https://github.com/quarkusio/quarkus/files/15145926/code-with-quarkus.tar.gz)
Run `GreetingResourceTest`

**Comment by geoand** [comment]
@phillip-kruger this seems to have broke as part of https://github.com/quarkusio/quarkus/pull/39897

**Comment by phillip-kruger** [comment]
I'll have a look

**Comment by geoand** [comment]
🙏🏼

**Comment by phillip-kruger** [comment]
Ok, so what we have here is what was described in the PR: https://github.com/quarkusio/quarkus/pull/37680

From that PR description:

**Breaking change (with a workaround  if needed)**

In the current version, if you have a JAX-RS Filter, that filter will run, even in the case that the requested resource was not a REST resource (in my opinion, that is wrong). This will not happen anymore. Filters for JAX-RS will now only run on JAX-RS resources. In the case that you want your Filters to also run on non JAX-RS resource, you need to add your own ExceptionMapper:

```java
package io.quarkus.resteasy.reactive.server.test.customproviders;

import jakarta.ws.rs.NotFoundException;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.ext.ExceptionMapper;
import jakarta.ws.rs.ext.Provider;

@Provider
public class NotFoundExeptionMapper implements ExceptionMapper<NotFoundException> {
    @Override
    public Response toResponse(NotFoundException exception) {
        return Response.status(404).build();
    }
}
```

Now, JAX-RS becomes responsible for the Not Found resources, and the Filter will run. In the current version where this always happens, it makes it impossible for other extensions to handle Not Found.

**Comment by phillip-kruger** [comment]
So `/hello/non-existing` will work, but `/non-existing` not, except if you add your own handler.

**Comment by geoand** [comment]
> In the current version, if you have a JAX-RS Filter, that filter will run, even in the case that the requested resource was not a REST resource (in my opinion, that is wrong). This will not happen anymore

I agree that the previous behavior was wrong

**Comment by geoand** [comment]
@phillip-kruger should we add something to the migration guide and close this?

**Comment by vkn** [comment]
> Filters for JAX-RS will now only run on JAX-RS resources. In the case that you want your Filters to also run on non JAX-RS resource,

Makes sense. Thanks for looking into it

**Comment by phillip-kruger** [comment]
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#resteasy-reactive-filters-on-non-rest-paths
