### ISSUE TITLE
Support @TestSecurity annotation with @QuarkusIntegrationTest

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#40340]
### Description

Currently you can only use `@TestSecurity` with `@QuarkusTest`. I believe that simplifying a security testing for users that use native executables would also be useful. In general, I understand that integration tests are likely to test integration with other software components like SSO, but we should not force that. It would be nice if user could have one test base that they can run with both QuarkusTest and QuarkusIntegrationTest.

### Implementation ideas

Expose test non-application endpoint that sets the identity instead of using Arc to propagate selected identity during integration testing.

**Comment by geoand** [comment]
Although this sounds reasonable, it's highly unlikely it can be done. 

The reason is that `@TestSecurity` alters the application itself, something that is not possible (or desired) with `@QuarkusIntegrationeTest`

**Comment by michalvavrik** [comment]
> Although this sounds reasonable, it's highly unlikely it can be done.

I though one HTTP request performed at the point where `Arc` is set during QuarkusTest will take care of it. We know where to call. I saw that lightweight Keycloak PR that is under review also changes state of the application their custom testing endpoints. It's just about propagation of the information.

> The reason is that `@TestSecurity` alters the application itself, something that is not possible (or desired) with `@QuarkusIntegrationeTest`

If it is not desirable, I am completely fine with closing this. We can wait if ever there is user request. It was just a thought :-) Thank you for the feedback.

**Comment by geoand** [comment]
🙏🏼
