### ISSUE TITLE
Unable to enlist connection to existing transaction

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#40343]
### Describe the bug

Trying to use two non-xa datasources with quarkus.datasource.*.transactions=enabled fails

This appears to be a regression - the exception does not happen with agroal 2.1 / quarkus 3.8.1

### Expected behavior

The transaction manager should just coordinate single phase commit transactions for each datasource.

### Actual behavior

When the second datasource is used an exception is raised "Unable to enlist connection to existing transaction"

### How to Reproduce?

See https://github.com/quarkusio/quarkus-quickstarts/compare/main...shawkins:keycloak-iss28725?expand=1

**Comment by shawkins** [comment]
See https://github.com/keycloak/keycloak/issues/28725#issuecomment-2076207578 - this due to a change in agroal-narayana from 2.1 to 2.3. In 2.1 LocalXAResource now implements LastResource - https://github.com/agroal/agroal/commit/e5cafc2fd1d6da27e11814d99d46d6b6d1fd0e41#diff-d6c0a87c07c761a760bb2d43218139307a1c0ce42c9f62437a699cf03f1d9707R23

**Comment by mmusgrov** [comment]
There is an open PR to address this issue: https://github.com/quarkusio/quarkus/pull/40365
Note that using two  XA unaware is transactionally unsafe and that is why we disallow it by default.
I believe this issue duplicates https://github.com/quarkusio/quarkus/issues/39283, if you agree can we close this one?

**Comment by shawkins** [comment]
> Note that using two XA unaware resources is transactionally unsafe and that is why we disallow it by default.

I don't disagree in general, but this specific situation for keycloak and probably others is that the resources are being used in a read only fashion - it's unexpected that this should proactively fail.

> I believe this issue duplicates https://github.com/quarkusio/quarkus/issues/39283, if you agree can we close this one?

Sounds good, I'll add a comment over there.
