### ISSUE TITLE
Suggestion for improved error message from io.quarkus.security.identity.SecurityIdentity

### ISSUE THREAD

**Issue by flowt-au** [quarkusio/quarkus#40357]
### Description

I recently updated my Quarkus app to 3.9.5 and Keycloak to 23.0.7.

Before updating, my Keycloak authentication all worked well. As soon as I updated I started getting the following exception:
```
Cannot invoke "io.quarkus.security.identity.SecurityIdentity.isAnonymous()" because "identity" is null
```
It turns out the cause was entirely my fault: I had an errant Singleton AuthFilter hanging around from tests some time ago which didn't cause any issues until now. This filter was removing / corrupting the auth token so `io.quarkus.security.identity.SecurityIdentity` failed with a Status Code 500 and the message above.

So, the purpose of this suggestion is whether that kind of user error (invalid / missing token) can be handled with a message and a more appropriate status code. Or, if not, at least someone else might find this and give them a clue to what that error could be caused by.

Thanks,
Murray

**Comment by sberyozkin** [comment]
@flowt-au Hi, I don't think we can know figure out at the level where this check is done, why it is null, there could be multiple authentication mechanisms, Quarkus can't know that a custom filter removed the token. 
Perhaps we can only do a better NPE message, @michalvavrik, what do you think ?

**Comment by flowt-au** [comment]
Yes, I understand. I created the error upstream. It was more that if a null token turns up maybe status 500 is too severe? I was thinking at that point there could be a check, that's all.
Thanks for looking at it. It is just a small possible improvement. :-)

**Comment by michalvavrik** [comment]
Sorry to answer question with a question, but my first thought is that we should not work with nulls, but have anonymous identity. To me knowledge, there should be really rare situations where it is a null. That's why I would not bother with a NPE detection (which only idea I have is yet another proxy that performs check :-)).

Did you produce NPE directly or is the identity produced by Quarkus null as well?

**Comment by michalvavrik** [comment]
Alternatively, please provide a reproducer, because I can't be completely sure what is happening in your app from the description. Thanks

**Comment by flowt-au** [comment]
Sure. The issue arose because some time ago I was trying to work out how to add auth tokens to WebSockets so I could use the Keycloak instance I use for my REST api for my WS requests. One approach that was suggested was to use a filter as below. It didn't help solve the issue and since it didn't break anything I simply forgot to remove it. When I upgraded to 3.9.5 for some reason it started mattering! ;-)

Anyway, removing this singleton solved my problem.

The reason I made the suggestion about the error message is because the of the wording of the error: `Cannot invoke "io.quarkus.security.identity.SecurityIdentity.isAnonymous()" because "identity" is null`. 

In my secured class I injected the SecurityIdentity:
```java
  @Inject
  SecurityIdentity securityIdentity;
```
and in my constructor I found it was, indeed, null. So I spent a lot of time trying to work out what changed in the update such that the injection and instantiation didn't work, thinking that was the issue. I finally stumbled on the real issue when I noticed the filter class buried well down in the stack trace.

I guess the filter from previous versions of Quarkus needed to be updated but since I didn't need it I just removed it. I am not sure at all that SecurityIdentity is receiving a null token, although that interpretation of the error message seems to indicate that. Whatever it got, it couldn't use it.

```java
package com.flowt.orgserver.gateway;

import jakarta.inject.Singleton;

import io.quarkus.logging.Log;
import io.quarkus.vertx.web.RouteFilter;

import io.vertx.ext.web.RoutingContext;

@Singleton
public class WSAuthFilter {
  @RouteFilter(401)
  void addAuthHeader(RoutingContext rc) {
    try {
      if (rc.request().headers().get("Sec-WebSocket-Protocol") != null) {
        String token = "Bearer " + rc.request().headers().get("Sec-WebSocket-Protocol").split(", ")[1];
        Log.info("addAuthHeader token=" + token.substring(0, 20) + " {etc...}");
        rc.request().headers().add("Authorization", token);
      }
    } finally {
      rc.next();
    }
  }
}
```
Thanks for looking into this. As I said, my request relates not to catching my silly mistake but to a possibly clearer error message that indicates it is the token that is the issue not the instantiation of the SecurityIdentity per-se.

Cheers,
Murray

**Comment by sberyozkin** [comment]
@flowt-au Thanks for the clarification. Quarkus security, when it checks SecurityIdentity, is not aware which HTTP or other transport authentication mechanism may have created it, and which credentials were used to create it. 
It does not look like we can make a more specific exception at this level and this is why I suggest we close the issue as we can't do anything about it anyway

**Comment by flowt-au** [comment]
Understood, thank you. :-)
This thread might help others who make a similar mistake.
Go well,
Murray
