### ISSUE TITLE
${project.groupId} does not work well with Maven 3.6.2 

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#4035]
Just reported https://issues.apache.org/jira/browse/MNG-6767 

What it means for Quarkus: If you are building the Quarkus source tree using Maven 3.6.2, Maven will take the latest release (currently 0.22.0) of `quarkus-maven-plugin` instead of the extpected `999-SNAPSHOT`. We either have to stay with Maven 3.6.1 or we have to replace `${project.groupId}` with `io.quarkus`.

**Comment by ppalaga** [comment]
Why are we actually using `${project.groupId}`?

**Comment by gsmet** [comment]
No real reason I suppose except we had plans to rename the project, which we did.

**Comment by ppalaga** [comment]
Robert Scholte [says](https://twitter.com/rfscholte/status/1173622004529999874)

> I'm kind of surprised this used to work. There used to be a statement that says plugins must exist before making the BuildPlan, which implies plugins cannot be part of the build they're being used.

So replacing `${project.groupId}` with `io.quarkus` might be the preferred solution.

I can prepare a patch. Feel free to assign to me.

**Comment by Sanne** [comment]
many thanks @ppalaga , had the same issue when reviewing #3832 now :)
