### ISSUE TITLE
Introduce support for Spring's @ConfigurationProperties

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#4038]

**Comment by hantsy** [comment]
I think `@ConfigurationProperties` is from Spring Boot.

**Comment by geoand** [comment]
That is true

**Comment by geoand** [comment]
Prerequisite Quarkus - native work is being done at #4075

**Comment by geoand** [comment]
The native Quarkus support is already in `master`. However I think we will also need #3436. The reason is that we don't want to pull in a ton of code just to support this (and maybe a few other annotations)

**Comment by cmoulliard** [comment]
Can you @geoand describe what we will support from ConfigurationProperties as Spring proposes [many features](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config) ?

**Comment by geoand** [comment]
From a user's perspective `@ConfigurationProperties` would just be used to group properties together into a single class.
The "backend" of how those properties are retrieved would of course be Quarkus specific and be bound by how Quarkus deals with properties, not how Spring does.

So the idea is to give users the familiariry they are used to - `@ConfigurationProperties` is very widely used and very useful

**Comment by cmoulliard** [comment]
> would just be used to group properties together into a single class.



> The "backend" of how those properties are retrieved would of course be Quarkus specific and be bound by how Quarkus deals with properties, not how Spring does.

We should take care about what we will offer and propose as this property is a SpringBoot Annotation, that Boot'users are familiar with it, it is then very important to document what we will first support then

**Comment by geoand** [comment]
Yes makes perfect sense - things should be properly documented.
As with every other Quarkus equivalent of the Spring stuff, we are aiming at porting knowledge, not providing a totally complete and drop in replacement for whatever Spring did.

**Comment by gsmet** [comment]
@geoand hasn't this been implemented?

**Comment by geoand** [comment]
Not yet, but it will be soon

**Comment by geoand** [comment]
This was delivered by @gytis with 1.2
