### ISSUE TITLE
Getting annotation on intercepted static method returns null

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#40399]
### Describe the bug

`invocationContext.getMethod().getAnnotation(MyInterceptorBinding.class)` is returning `null` on an intercepted static method (which is annotated with `MyInterceptorBinding`).

Using `invocationContext.findIterceptorBinding(MyInterceptorBinding.class)` on the `ArcInvocationContext` seems to work as expected.

### Expected behavior

`invocationContext.getMethod().getAnnotation(MyInterceptorBinding.class)` returns the annotation.

### Actual behavior

`invocationContext.getMethod().getAnnotation(MyInterceptorBinding.class)` returns `null`.

### How to Reproduce?

```
@Inherited
@InterceptorBinding
@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
public @interface MyInterceptorBinding {}

@Interceptor
@MyInterceptorBinding
public class MyInterceptor {

    @AroundInvoke
    public Object invoke(ArcInvocationContext invocationContext) throws Exception {
        System.out.println("Intercepted");
        System.out.println(invocationContext.getMethod().getAnnotation(MyInterceptorBinding.class)); //Prints null
        System.out.println(invocationContext.findIterceptorBinding(MyInterceptorBinding.class)); // Seems to work fine
        return invocationContext.proceed();
    }

}

public class MyClass {

    @MyInterceptorBinding
    public static void myMethod() {
        System.out.println("my method");
    }

}


@QuarkusTest
class MyClassTest {

    @Test
    void test() {
        MyClass.myMethod();
    }

}
```

### Output of `uname -a` or `ver`

Darwin N4MFM06QYD 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "22.0.1" 2024-04-16 OpenJDK Runtime Environment GraalVM CE 22.0.1+8.1 (build 22.0.1+8-jvmci-b01) OpenJDK 64-Bit Server VM GraalVM CE 22.0.1+8.1 (build 22.0.1+8-jvmci-b01, mixed mode, sharing)

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by manovotn** [comment]
The reason for this is that Quarkus has to do some class/method transformation on the static method (basically copy it over to add interception logic) and the `java.lang.reflect.Method` you are inspecting is the new one, not the original one.
And we don't seem to copy over annotations - which should be fixable.

That being said, I'd highly recommend using `ArcInvocationContext#findIterceptorBinding`, or, with CDI 4.1 this is standardized into `InvocationContext#getInterceptorBindings`. The reason being, you can technically add some annotations programmatically and those will never be reflected onto the `Method` object

**Comment by xtaixe** [comment]
@manovotn thanks for the suggestion! Are there any plans to bring CDI 4.1 to Quarkus soon?

**Comment by manovotn** [comment]
> @manovotn thanks for the suggestion! Are there any plans to bring CDI 4.1 to Quarkus soon?

That's already in Quarkus main branch via https://github.com/quarkusio/quarkus/pull/40208
So next release should have it :)
