### ISSUE TITLE
Make quarkus-security jar names unique so they do not conflict with java auto modules

### ISSUE THREAD

**Issue by diversit** [quarkusio/quarkus#40417]
### Description

When using the dependency `io.quarkus:quarkus-security` this also adds a dependency on `io.quarkus.security:quarkus-security`.

The names of the jar files of both dependencies are identical.
Since Quarkus still has not defined a module-info, when using Java Modules, the module names are created automatically based on the jar name.
Adding `requires quarkus.security` does not work since it matches both jars.
This results in these compile errors:
```
package io.quarkus.security.identity does not exist
cannot find symbol
[ERROR]   symbol:   class SecurityIdentity
[ERROR]   location: class my.pkg.MyHttpSecurityPolicy
```

### Implementation ideas

Please rename one of the security packages to solve this name conflict since this now means we can no longer use Java Modules when using Quarkus Security.

**Comment by sberyozkin** [comment]
I'll open a PR renaming `io.quarkus.security:quarkus-security` to `io.quarkus.security:quarkus-security-spi` as agreed awhile back at #25795 with @stuartwdouglas
