### ISSUE TITLE
No database found to handle jdbc:postgresql://....

### ISSUE THREAD

**Issue by vipul0805** [quarkusio/quarkus#40436]
### Describe the bug

I upgraded the Quarkus platform version from `3.9.1` to `3.10.0`.  After that `flywayMigrate` fails with the error `No database found to handle jdbc:postgresql://127.0.0.1:52504/postgres`

### Expected behavior

I expected `flywayMigrate` to work as before. 

### Actual behavior

```
> Task :flywayMigrate FAILED

Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
  No database found to handle jdbc:postgresql://127.0.0.1:52856/postgres

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 17s
4 actionable tasks: 4 executed
```

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.7

**Comment by ivu-mawi** [comment]
Have you added the new flyway-postgres dependency as mentioned in the [Migration Guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10)?

**Comment by mschorsch** [comment]
This is'nt a bug.

I assume you are executing the Gradle Task `flywayMigrate` directly e.g. from the command line. In this case you have to add `org.flywaydb:flyway-database-postgresql` to the `buildscript` classpath https://documentation.red-gate.com/fd/gradle-task-184127407.html).

```kotlin
buildscript {
    dependencies {
        // ...
        classpath("org.flywaydb:flyway-database-postgresql:10.12.0")
    }
}
```

**Comment by vipul0805** [comment]
@mschorsch That worked. Thanks a lot.
