### ISSUE TITLE
Support config doc sections

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#4045]
@machi1990 moving the discussion here.

I think we could just have:
```
    /**
     * Database related configuration.
     */
    @ConfigItem
    @ConfigDocSection
    public HibernateOrmConfigDatabase database;
```
because we will need a comment (it's mandatory) and we could have the first sentence of the comment be the title (we could automatically remove the dot) and the rest of the comment would be the intro of the section.

We could imagine supporting Asciidoc in this case too with `@asciidoclet`.

WDYT? Does it seem feasible?

**Comment by machi1990** [comment]
Hi @gsmet thanks. It is feasible. I’ll work on this. 

Just a quick question, do we support embedded ConfigDocSection?

**Comment by gsmet** [comment]
Good question. If not overly complicated, why not. If it's complicated, one level looks good for now and would be nice to have ASAP (@marcinczeczko also asked for it for the Amazon Dynamodb extension).

**Comment by machi1990** [comment]
Okay,  I have the data structure in mind. I’ll see in practice when I have my PC in front of me. 

Good to see these kind of feedback after early adoption.
