### ISSUE TITLE
quarkus disposal method called in wrong order

### ISSUE THREAD

**Issue by sixcorners** [quarkusio/quarkus#40460]
### Describe the bug

Sometimes quarkus disposes my instances in the order I expect. Sometimes it doesn't. My example uses System.exit() to get it to try to dispose of the Singletons but Quarkus.exitAsync() also errors. My example uses method parameter injection but field injection also errors. If I change BProducer to a Singleton and field inject the A the error still happens.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/15210516/code-with-quarkus.zip)

### Expected behavior

```
producing an A: org.acme.A@73752c2d
producing a B: org.acme.B@647432d1 with A: org.acme.A@73752c2d
disposing a B: org.acme.B@726dd9a3 with A: org.acme.A@73752c2d
disposing an A: org.acme.A@73752c2d
2024-05-04 12:09:13,934 ERROR [io.qua.arc.imp.UncaughtExceptions] (Shutdown thread) Error occurred while destroying instance of PRODUCER METHOD bean [types=[java.lang.Object, org.acme.B], qualifiers=[@Default, @Any], target=org.acme.B produce(org.acme.A a), declaringBean=org.acme.BProducer]: java.lang.RuntimeException: a is closed [Error Occurred After Shutdown]
```

### Actual behavior

```
producing an A: org.acme.A@73752c2d
producing a B: org.acme.B@647432d1 with A: org.acme.A@73752c2d
disposing an A: org.acme.A@73752c2d
disposing a B: org.acme.B@726dd9a3 with A: org.acme.A@73752c2d
2024-05-04 12:24:39,333 ERROR [io.qua.arc.imp.UncaughtExceptions] (Quarkus Main Thread) Error occurred while destroying instance of PRODUCER METHOD bean [types=[java.lang.Object, org.acme.B], qualifiers=[@Default, @Any], target=org.acme.B produce(org.acme.A a), declaringBean=org.acme.BProducer]: java.lang.RuntimeException: a is closed [Error Occurred After Shutdown]
```

### How to Reproduce?

1 run the app
2 send a request to the GreetingResource (GET http://localhost:8080/hello)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.3527]

### Output of `java -version`

openjdk version "21" 2023-09-19 LTS OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS) OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by manovotn** [comment]
Will take a look tomorrow

**Comment by mkouba** [comment]
The ordering of bean destruction is not guaranteed (nor defined by the spec). In other words, you should not expect/rely on this behavior.

I'll let @manovotn to double check but from my point of view this issue should be closed as "not planned".

**Comment by manovotn** [comment]
Martin is right on the money.
The specification doesn't specify the order in which beans are destroyed.
I don't think we can improve this because the same bean instance can be injected into `n` places each of which might make similar assumption on the destruction order.
This behavior should therefore not be relied on.

If you describe the use case you are trying to achieve with this, we might be able to suggest alternative approach.

**Comment by sixcorners** [comment]
Is it allowed to inject already disposed beans into a disposes method?

My use case is I have a bunch of beans that need another bean to dispose of them. An alternative I could go with is to just call Runtime.getRuntime().halt() since currently the cleanup stuff doesn't really matter. I could use java.lang.ref.Cleaner instead of disposes methods. I could also just leak some things if they are going to be singletons anyway. Are those the alternative approaches you would have recommended?

**Comment by manovotn** [comment]
> Is it allowed to inject already disposed beans into a disposes method?

Of course not, if the bean has been disposed, it was destroyed, it doesn't exist any more.
You could use a bean with different *scope* - there is no guarantee in CDI spec for this but as far as I recall Quarkus tries to destroy the "short lived" scope first - so req. scope before app scope for instance.

> My use case is I have a bunch of beans that need another bean to dispose of them. An alternative I could go with is to just call Runtime.getRuntime().halt() since currently the cleanup stuff doesn't really matter. I could use java.lang.ref.Cleaner instead of disposes methods. I could also just leak some things if they are going to be singletons anyway. Are those the alternative approaches you would have recommended?

What kind of cleanup are we talking?
Is this app shutdown or just some context (req. context for instance) being destroyed?
Why do you need another bean (of the same scope) to destroy this one?

**Comment by sixcorners** [comment]
Well that's what's happening. One singleton bean is being destroyed then it's being injected into the disposer that's trying to dispose of another bean.

The API I'm trying to use with CDI beans is vulkan. You can allocate a VkInstance and that has pointers to a bunch of functions then you can create a VkDevice from one of those functions and that will have pointers to more functions that you can use to create yet more things. When I Quarkus.asyncExit() I get a crash because it tries to jump to a function pointer on a bean that has already been disposed of.
