### ISSUE TITLE
codestart are using legacy properties still

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#40462]
### Describe the bug

when generating a 3.10 project via code.quarkus.io
the pom.xml still has;
`<quarkus.package.type>native</quarkus.package.type>`
instead of
`<quarkus.native.enabled>true<quarkus.native.enabled>`

and the readme.md still has
`./mvnw package -Dquarkus.package.type=uber-jar`
instead of
`./mvnw package -Dquarkus.package.jar.type=uber-jar`

I looked at the main branch and the 3.10 branch and it looks fine in terms of the above so unsure why this happens.

### Expected behavior

new properties are used

### Actual behavior

legacy properties are used

### How to Reproduce?

1- go to https://code.quarkus.io/
2- click generate and download the app
3- observe the pom.xml and README.md

**Comment by gastaldi** [comment]
This should be hopefully fixed by https://github.com/quarkusio/code.quarkus.io/pull/1374, right @ia3andy ?

**Comment by manofthepeace** [comment]
This seems fixed now. thanks.
