### ISSUE TITLE
Update ubi8/openjdk-VERSION from 1.18 to 1.19

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#40468]
### Description

`1.19` is recommended (https://catalog.redhat.com/software/containers/ubi8/openjdk-21/653fb7e21b2ec10f7dfc10d0?architecture=amd64&image=66215ae965a2c95dee4e50fb).  Currently `1.18` is still being used: https://github.com/quarkusio/quarkus/blob/3.10.0/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/Dockerfile-layout.include.qute

One more question, can the version of ubi8/openjdk-21 be upgraded for Quarkus 3.10 without risk or are adjustments necessary?

**Comment by mschorsch** [comment]
@gastaldi For each Java Version there are two images `ubi8/openjdk-VERSION:1.19` and `ubi8/openjdk-VERSION:1.19-runtime`. Could you explain the difference? Why Quarkus did not use the runtime version?

**Comment by gastaldi** [comment]
@mschorsch According to the `ubi8/openjdk-11-runtime` image docs: The container does not contain the Java compiler / JDK tools or Maven.

> Edit: A project that does not use "Source To Image (S2I)" can use `ubi8/openjdk-VERSION:1.19-runtime`, right?

It depends on what your image needs. If you are simply packaging the binary produced in a previous stage, then yes, the runtime should be enough for you.
