### ISSUE TITLE
OIDC: injecting a `UserInfo` breaks startup

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#40473]
Turns out [this feature](https://github.com/quarkusio/quarkus/pull/39458) is what broke Renarde CI: https://github.com/quarkiverse/quarkiverse/issues/74#issuecomment-2092412856

In Renarde, we support various named OIDC providers, and so we support multiple tenants, where each tenant is a known provider, and we have an API that abstracts over them. For some of them we have to use the `UserInfo`, and for others, we don't use it. As such, we inject it every time, we only use it when required.

This commit appears to require a user info endpoint at the global level, even though it's not supported or required by every tenant.

I support my only workaround is to use programmatic injection to bypass this check, but is this really an intended side-effect?

**Comment by sberyozkin** [comment]
Hi @FroMage, @michalvavrik fixed it on main, and it is marked for a backport. Do you ser it failing against the main branch ?

**Comment by FroMage** [comment]
> Do you ser it failing against the main branch

yes

> If config source with a priority higher than a default config source sets ..user-info-required=false than it is respected and works.

So, my extension needs to set this property for the user, then?

The problem with detecting that something like `UserInfo` is required based on injection is that you can't detect whether there will be a code path accessing it for _every_ tenant. In my case I only access it for the tenants that require it, but you can't scan that.

**Comment by FroMage** [comment]
It's possible I checked with `3.10.0` and not `main`, lemme check.

**Comment by FroMage** [comment]
It looks like indeed, it failed with `3.10.0` and it works now with `main`, so your PR did indeed fix the problem. I'll close this. Sorry for the confusion :(

**Comment by sberyozkin** [comment]
Thanks @FroMage @michalvavrik
