### ISSUE TITLE
Document how to properly override the RESTEasy Jsonb instance

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#4048]
See this question on SO: https://stackoverflow.com/questions/57935807/initialize-jsonb-configuration-once/57959679#57959679 .

It's not obvious that the `Jsonb` instance will be created for each request when using the OP's pattern so we should test and document a proper way of doing that.

**Comment by loicmathieu** [comment]
Thinking about it and the discussion we had for MongoDB with Panache that needs to register custom serializers, maybe the best is to have a ContextProvider that retrieve the Jsonb instance from Arc, providing a default bean that the user can override. 

So instead provinding it's own ContextResolver a user should provides a Jsonb object.

**Comment by gsmet** [comment]
That's a good idea.

**Comment by geoand** [comment]
Yeah, we already do that Jackson.

I also have that implemented in #3553 which I have not had time to bring up to date and add benchmarks yet

**Comment by geoand** [comment]
If anyone wants to take this up, it's indeed a nice first issue and I would be willing to help out if needed

**Comment by loicmathieu** [comment]
@gsmet the works @geoand done for #4212 fixes this issue right ?
Maybe providing a new SO answer based on a JsonbCustomizer will be a good thing ? I can do it if you want

**Comment by geoand** [comment]
@loicmathieu That would be great!

**Comment by loicmathieu** [comment]
New SO answer with the JSON-B customizer approach: https://stackoverflow.com/a/58608559/3603660
I'm closing the issue!
