### ISSUE TITLE
code.quarkus.io templates not updated to new config changes

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#40480]
I don't think the templates on code.quarkus.io were updated to accomodate some of the changes in #39295. When I create a project from code.quarkus.io it still generates `<quarkus.package.type>native</quarkus.package.type>` in the `native` profile...

_Originally posted by @edeandrea in https://github.com/quarkusio/quarkus/issues/39295#issuecomment-2096806169_

**Comment by manofthepeace** [comment]
see: https://github.com/quarkusio/quarkus/issues/40462

**Comment by edeandrea** [comment]
Duplicate of #40462
