### ISSUE TITLE
[Extension Proposal] Statiq an extension to generate static pages from your Quarkus web-app

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#40488]
### Description

- has a configuration to describe what to generate
- provides a endpoint to generate on the server fs (or dl as a tar.gz)
- provides a CLI command to generate on the fs

### Repository name

quarkus-statiq

### Short description

An extension to generate/publish static pages from your Quarkus web-app

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-statiq/dev/

### Repository Topics

- quarkus-extension
- web
- static
- generate
- blog

### Team Members

- ia3andy

**Comment by maxandersen** [comment]
interesting. so like gatsby hybrid static/dynamic generation?

what is your thinking about what  that configuration be like?

not sure about the "quote" name...destined to be confusing as pronunciation is same as qute.

**Comment by ia3andy** [comment]
> interesting. so like gatsby hybrid static/dynamic generation?
> 
> what is your thinking about what that configuration be like?
> 
> not sure about the "quote" name...destined to be confusing as pronunciation is same as qute.

Yeah I thought the same and went for Qout

**Comment by maxandersen** [comment]
> Yeah I thought the same and went for Qout

isn't that the same pronunciation ? :)

**Comment by ia3andy** [comment]
Q-out

**Comment by ia3andy** [comment]
Ok I went for `qublish` as `qout` or `quote` even if I liked them are really close to `qute`

**Comment by gastaldi** [comment]
How about having this as another extension in the `quarkus-web-bundler` repository? The description matches the intent anyway (`Create full-stack web apps quickly and easily with this Quarkus extension`)

**Comment by ia3andy** [comment]
> How about having this as another extension in the `quarkus-web-bundler` repository? The description matches the intent anyway (`Create full-stack web apps quickly and easily with this Quarkus extension`)

no I think this is worth a specific repository, you can create it, I will start it soon.

**Comment by ia3andy** [comment]
@maxandersen any thoughts?

**Comment by maxandersen** [comment]
this isn't (only) for full-stack web apps so makes sense to me its separate. This is me assuming I can use this on even "pure" raw quarkus app without webbundler...

**Comment by gastaldi** [comment]
https://github.com/quarkiverse/quarkus-statiq is now created. Enjoy!

**Comment by aloubyansky** [comment]
What was wrong with quarkus-static-pages?.. :)

**Comment by maxandersen** [comment]
didnt see it proposed? but its not all pages :)

**Comment by aloubyansky** [comment]
I mean the naming approach, it's getting way too cryptic, imo

**Comment by maxandersen** [comment]
yes, thats why I propose statiq over qout, quot,etc. since static would be bad for package names :)
