### ISSUE TITLE
add Liquibase config option allowDuplicatedChangesetIdentifiers

### ISSUE THREAD

**Issue by joachimglink** [quarkusio/quarkus#40493]
### Description

With Liquibase 4.25.1 a new config option was introduced: liquibase.allowDuplicatedChangesetIdentifiers (see https://docs.liquibase.com/parameters/allow-duplicated-changeset-identifiers.html)

This option allows that a change set is found multiple times without failing the Liquibase migration; it effectively just ignores duplicate changesets.
As of now, there is no Quarkus specific config property for this, so one needs to define it as environment variable or system property; neither is very nice to handle.

It would be great if Quarkus adds this config option to the current list of options.
Or: would it be possible to create a more generic config way so that we could define every Liquibase config property with one single Quarkus property using a map?

Thanks.

**Comment by geoand** [comment]
Does something like `quarkus.liquibase.change-log-parameters.allowDuplicatedChangesetIdentifiers=true` work?

**Comment by joachimglink** [comment]
No, this is not working. I already tried this.
Seems that these parameters can only be used in the changelog definitions itself but they are not set as Liquibase config options.

**Comment by geoand** [comment]
If that's the case, then unfortunately I don't think we can do much, because from what I saw from the code, Liquibase has its own way of setting configuration that we can't hook into

**Comment by gsmet** [comment]
I see we can set it as a system property: `JAVA_OPTS=-Dliquibase.allowDuplicatedChangesetIdentifiers=<true|false>`, maybe producing a `SystemPropertyBuildItem` would work?

**Comment by geoand** [comment]
Yeah, we could do that early enough to make it work, but it's very unfortunate to have to resort to that kind of hack

**Comment by gsmet** [comment]
Yeah, I completely agree it's not pretty.

Not sure how to structure it but these options would basically need to be added in `LiquibaseBuildTimeConfig`. Then you would add a method in `LiquibaseProcessor` consuming the config (you already have examples of that in this class) and producing the appropriate `SystemPropertyBuildItem`.

It should be simple enough if you're willing to give it a try.

Be aware though that these will be fixed at build time. Overriding the property directly at runtime might work but you would have to test it.

**Comment by joachimglink** [comment]
That sounds great.
The System property approach was what I used as a workaround; not in such a nice way though.
Thanks for getting this resolved so quickly.
