### ISSUE TITLE
Micrometer performance improvements

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#40507]
### Description

The current way we are using Micrometer has negative performance impacts, as described in this blog post from @tsegismont: 
https://vertx.io/blog/micrometer-metrics-performance/

In a nutshell:

- fil­ter­ing tags up front in­stead of using a Mi­crom­e­ter MeterFilter
- avoid­ing re­dun­dant copies when com­bin­ing tags
- look­ing up me­ters once if their tags are known in ad­vance
- use a MeterProvider when some tags can be de­ter­mined only after an event oc­cured.

This issue will be the parent issue of many enhancements that should happen on the `quarkus-micrometer` extension, mainly in the `io.quarkus.micrometer.runtime.binder` package classes.

Will create an issue per package because this can be a good first issue for someone. To help with this, the [Vert.x package PR](https://github.com/quarkusio/quarkus/issues/40506) will serve as a reference implementation.

List of child issues:

- [x] https://github.com/quarkusio/quarkus/issues/40506
- [x] https://github.com/quarkusio/quarkus/issues/40597 (PR available)
- [x] https://github.com/quarkusio/quarkus/issues/40598
- [x] https://github.com/quarkusio/quarkus/issues/40599

You just need to pick one for you.

**Comment by brunobat** [comment]
This is done

**Comment by tsegismont** [comment]
@brunobat great! Have you been able to measure improvements?

**Comment by brunobat** [comment]
Not yet. I' m still working on the performance setup.
