### ISSUE TITLE
Path param annotated with @Encoded are not url encoded by the quarkus-rest-client-jackson anymore

### ISSUE THREAD

**Issue by mrickly** [quarkusio/quarkus#40521]
### Describe the bug

quarkus-rest-client-jackson interface:

```
package ch.mobi.glu.test.reproducer.rest;

import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.Encoded;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/api/v4")
@ApplicationScoped
@RegisterRestClient
public interface GitLabClient {

    @GET
    @Path("/projects/{projectId}/repository/files/{filePath}/raw")
    @Produces(MediaType.TEXT_PLAIN)
    String getRawFile(@PathParam("projectId") Integer projectId, @PathParam("filePath") @Encoded String filePath);

}
```

### Expected behavior

The filePath path param is url encoded. Still working with 3.8.4

### Actual behavior

The filePath path param is not url encoded anymore. Fails since 3.9.1

### How to Reproduce?

```
package ch.mobi.glu.reproducer.rest;

import org.eclipse.microprofile.rest.client.inject.RestClient;
import org.junit.jupiter.api.Test;

import ch.mobi.glu.test.reproducer.rest.GitLabClient;
import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
public class GitLabClientTest {

    @RestClient
    GitLabClient gitLabClient;

    @Test
    public void testRawFileEndpoint() {
        gitLabClient.getRawFile(123, "src/main/resources/messages/test1_en_GB.properties");
    }

}
```

### Output of `java -version`

openjdk 21.0.3 2024-04-16 LTS OpenJDK Runtime Environment Zulu21.34+20-SA (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Zulu21.34+20-SA (build 21.0.3+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c) Maven home: C:\ieu\apache-maven-3.9.2 Java version: 21.0.3, vendor: Azul Systems, Inc., runtime: C:\ieu\java\openjdk-21 Default locale: en_US, platform encoding: UTF-8 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by mrickly** [comment]
Removing the `@Encoded` annotation helps. What does the spec say?

**Comment by gastaldi** [comment]
I created a test here that shows it works properly: https://github.com/quarkusio/quarkus/pull/40522

**Comment by mrickly** [comment]
@gastaldi : Thank you. Adding the regex in the interface does not change the url of the GET request in 3.9.1 (or 3.9.4) though: `https://somehost.example.com/api/v4/projects/123/repository/files/src/main/resources/messages/test1_en_GB.properties/raw`. 
But the result should be (and used to be) `https://somehost.example.com/api/v4/projects/123/repository/files/src%2Fmain%2Fresources%2Fmessages%2Ftest1_en_GB.properties/raw`.
Adding `@Encoded` used to be necessary to obtain this behaviour. Now apparently it is url encoded by default and `@Encoded` disables the url encoding. It is not clear to me what microprofile spec the client is conforming to.
