### ISSUE TITLE
WebSockets Next: close the connection if the security identity has expired

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#40536]
### Description

This enhancement request is a follow up to #40312 (PR: #40534).
The idea is that the identity time validity constraints should not be dropped once a user moves from the authenticated HTTP session to the WS channel, i.e, if the user is required to re-authenticate or have the session cookie refreshed when working with HTTP, for example, when the OIDC Keycloak session expires after 1 hour, then it should also be the case if the user upgrades to WS. 

### Implementation ideas

OIDC already sets the following `SecurityIdentity` attribute:

```
public static final String QUARKUS_IDENTITY_EXPIRE_TIME = "quarkus.identity.expire-time";
``` 

which we agreed earlier with @stuartwdouglas about. At the moment it is only OIDC which sets it but other security mechanisms like `Form`, `WebAuthn`, can also set it later.

It is in seconds, so it is checked during the callback if it is less than the current time in seconds and the connection is closed if it is true.
 
The related issue is where the user is returned to once the connection is closed for the user to repeat the original HTTP request for another upgrade.

Lets say I'm authenticating with Google and now I'm looking at the Quarkus LangChain4j demo page with a chat bot icon, I press on it, I'm in the WS session... Now if the authentication has expired, I'd like to be returned to this initial demo page where I can click on the ChatBot icon again.

Adding a Web Sockets Next configuration property which will let the user be redirected to the configured HTTP page would be nice - for example, if this original HTTP page is an OIDC secured initial demo page, then OIDC will refresh the session and the user will be able to get back to the WS channel

**Comment by michalvavrik** [comment]
I started to look at it.

**Comment by michalvavrik** [comment]
> Adding a Web Sockets Next configuration property which will let the user be redirected to the configured HTTP page would be nice - for example, if this original HTTP page is an OIDC secured initial demo page, then OIDC will refresh the session and the user will be able to get back to the WS channel

I read https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.4 and to my understanding it is not possible without creating a custom extension that would also WebSocket client need to implement. So we can only close the connection with a reason. Please correct me @mkouba if I am wrong.

**Comment by mkouba** [comment]
> > Adding a Web Sockets Next configuration property which will let the user be redirected to the configured HTTP page would be nice - for example, if this original HTTP page is an OIDC secured initial demo page, then OIDC will refresh the session and the user will be able to get back to the WS channel
> 
> I read https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.4 and to my understanding it is not possible without creating a custom extension that would also WebSocket client need to implement. So we can only close the connection with a reason. Please correct me @mkouba if I am wrong.

Yes, I believe that it's up to the client to react appropriately.
