### ISSUE TITLE
Quarkus 3.10 - Flyway with SQL Server DB failed to compile in native

### ISSUE THREAD

**Issue by Vinche59** [quarkusio/quarkus#40551]
### Describe the bug

Problem in flyway subsitution with SQL Server database.
Cannot compile in native mode.

### Expected behavior

The native compilation should be possible

### Actual behavior

Native compilation failed with "return type mismatch"

`Error: Return type mismatch:
    public java.lang.Object io.quarkus.flyway.runtime.graal.SQLServerDatabaseTypeSubstitutions.createDatabase(org.flywaydb.core.api.configuration.Configuration,org.flywaydb.core.internal.jdbc.JdbcConnectionFactory,org.flywaydb.core.internal.jdbc.StatementInterceptor)
    public org.flywaydb.core.internal.database.base.Database org.flywaydb.database.sqlserver.SQLServerDatabaseType.createDatabase(org.flywaydb.core.api.configuration.Configuration,org.flywaydb.core.internal.jdbc.JdbcConnectionFactory,org.flywaydb.core.internal.jdbc.StatementInterceptor)
com.oracle.svm.core.util.UserError$UserException: Return type mismatch:
    public java.lang.Object io.quarkus.flyway.runtime.graal.SQLServerDatabaseTypeSubstitutions.createDatabase(org.flywaydb.core.api.configuration.Configuration,org.flywaydb.core.internal.jdbc.JdbcConnectionFactory,org.flywaydb.core.internal.jdbc.StatementInterceptor)
    public org.flywaydb.core.internal.database.base.Database org.flywaydb.database.sqlserver.SQLServerDatabaseType.createDatabase(org.flywaydb.core.api.configuration.Configuration,org.flywaydb.core.internal.jdbc.JdbcConnectionFactory,org.flywaydb.core.internal.jdbc.StatementInterceptor)
`

### How to Reproduce?

Reproducer can be found here : https://github.com/Vinche59/flyawy-sqlserver-native-reproducer

Just try to compile in native: mvn -Pnative clean package

### Output of `uname -a` or `ver`

Linux Asguard 5.15.0-106-generic #116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "22" 2024-03-19 OpenJDK Runtime Environment Temurin-22+36 (build 22+36) OpenJDK 64-Bit Server VM Temurin-22+36 (build 22+36, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

Mandrel 24

### Quarkus version or git rev

3.10

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1

**Comment by gastaldi** [comment]
For the record, this error only happens in Mandrel 24+. I haven't been able to reproduce using GraalVM 21.0.2+13.1, for example
