### ISSUE TITLE
Malformed LocalDate QueryParam yields HTTP 404 (Not Found) instead of HTTP 400 (Bad Request)

### ISSUE THREAD

**Issue by BureschT** [quarkusio/quarkus#40554]
### Describe the bug

When I call the following endpoint with "/notes?startDate=2024", I get HTTP 404 (Not Found) instead of HTTP 400 (Bad Request).

```
    @GET
    @Path("/notes")
    public Response getNotes(@QueryParam("startDate") LocalDate start) {
        return Response.ok().build();
    }
```

Same goes for "/notes?startDate=". Although, in this latter case start == null would also make sense, WDYT?

### Expected behavior

I would expect HTTP 400 error when the local date is malformed in the query parameter.
I would like to be able to catch this situation in an exception mapper too.

### How to Reproduce?

[localdate-validation-issue.zip](https://github.com/quarkusio/quarkus/files/15275237/localdate-validation-issue.zip)

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by geoand** [comment]
This is actually tested that the JAX-RS (now Jakarta REST TCK) so what you are seeing is the spec conformant behavior (although I agree that it's not terribly intuitive).

**Comment by otonielsilva** [comment]
Is there an alternative to make it BAD Request  http 400  ?

**Comment by geoand** [comment]
There is not, but we could consider it
