### ISSUE TITLE
[Extension Proposal] easy-retrofit for Quarkus Extension 

### ISSUE THREAD

**Issue by liuziyuan** [quarkusio/quarkus#40585]
### Description

Quickly using Retrofit 2 in the Quarkus project, the easy-retrofit provides an annotation based configuration to create Retrofit instances, and enhances general functionality through more annotations. 
Currently, this project has completed its core functions within the Spring boot framework。
Retrofit  is A type-safe HTTP client for Android and Java，Retrofit provides both synchronous and asynchronous HTTP requests。

`easy retrofit`  website on github [easy-retrofit-spring-boot-stater](https://github.com/liuziyuan/easy-retrofit)

### Repository name

quarkus-easy-retrofit

### Short description

easy-retrofit-client provides an annotation based configuration to create Retrofit instances, and enhances general functionality through more annotations. 

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-easy-retrofit/dev/

### Repository Topics

- quarkus-extension
- http-client
- retrofit
- 

### Team Members

- liuziyuan

**Comment by liuziyuan** [comment]
The core of easy retrofit is to implicitly provide injection to the DI framework and enhance the entire framework with more annotations.
for example , 
on official retrofit ,  
first， you need to define an interface 。
second ，you need create a instance of interface
last, you could access http request.
```java
public interface GitHubService {
  @GET("users/{user}/repos")
  Call<List<Repo>> listRepos(@Path("user") String user);
}

Retrofit retrofit = new Retrofit.Builder()
    .baseUrl("https://api.github.com/")
    .build();
GitHubService service = retrofit.create(GitHubService.class);

Call<List<Repo>> repos = service.listRepos("octocat");
```

on easy retrofit,
You just need to declare @EnablingRetrofit Annotation ，second, define an interface. last, inject interface by DI framework,
Then you could access http request
```java
@RetrofitBuilder(baseUrl = "${app.hello.url}")
public interface HelloApi {
    @GET("v1/hello/{message}")
    Call<ResponseBody> hello(@Path("message") String message);
}

@Autowired
private HelloApi helloApi;

@GetMapping("/{message}")
public ResponseEntity<String> hello(@PathVariable String message) throws IOException {
    final ResponseBody body = helloApi.hello(message).execute().body();
    return ResponseEntity.ok(body.string());
}
```
Actually, I have already completed the integration of the entire retrofit on quarks at my local

**Comment by liuziyuan** [comment]
@maxandersen  @gastaldi @aloubyansky  @gsmet  I would like to know when I can create a project for the easy retrofit extension in the Quarkiverse Hub

**Comment by gastaldi** [comment]
@liuziyuan I can create a repository for you. Have you already created a protoype as a Quarkus extension (maybe in your personal org) so we can take a look or the plan is to start from zero?

**Comment by liuziyuan** [comment]
> @liuziyuan I can create a repository for you. Have you already created a protoype as a Quarkus extension (maybe in your personal org) so we can take a look or the plan is to start from zero?

In my local area, the core functions of the Quarkus easy regression project have been completed and I have pushed [quarkus-easy-retrofit](https://github.com/liuziyuan/quarkus-easy-retrofit)  to my GitHub. This project is just a demo for you to see

you can run integration-tests sub-module, http://localhost:8080/retrofit-client，and observe the value returned by the retrofit interface

**Comment by gastaldi** [comment]
@liuziyuan [quarkiverse/quarkus-easy-retrofit](https://github.com/quarkiverse/quarkus-easy-retrofit) is now provisioned. Welcome to Quarkiverse! See [hub.quarkiverse.io/checklist/#after-the-repository-is-created](https://hub.quarkiverse.io/checklist/#after-the-repository-is-created) for the next steps

**Comment by maxandersen** [comment]
thanks for the info @liuziyuan -  i took a look at  the integration test sub module and wondered what these adapters are for: https://github.com/liuziyuan/quarkus-easy-retrofit/tree/main/integration-tests/src/main/java/io/quarkiverse/easy/retrofit/client/it/retrofit ?

are those something users need to add?

**Comment by liuziyuan** [comment]
> thanks for the info @liuziyuan - i took a look at the integration test sub module and wondered what these adapters are for: https://github.com/liuziyuan/quarkus-easy-retrofit/tree/main/integration-tests/src/main/java/io/quarkiverse/easy/retrofit/client/it/retrofit ?
> 
> are those something users need to add?


Essentially, @RetrofitBuilder is a substitute for `Retrofit.Builder()`, Builder provides some methods to assemble the final Retrofit object, and in Easy Retrofit, the same applies.
As for the other files, they are used by me to test the Easy Retrofit Extension function and can be ignored in the demo
For more usage, you can check readme。[easy Retrofit readme advanced configuration](https://github.com/liuziyuan/easy-retrofit?tab=readme-ov-file#advanced-configuration)
```java
@RetrofitBuilder(baseUrl = "${app.url}" ,
        addConverterFactory = {JacksonConvertFactoryBuilder.class},
        addCallAdapterFactory = {BodyCallAdapterFactoryBuilder.class, GuavaCallAdapterFactoryBuilder.class},
        validateEagerly = false,
        globalOverwriteRule = OverrideRule.LOCAL_FIRST)
//@RetrofitInterceptor(handler = TestInterceptor.class)
public interface BaseApi {

    @GET("api/hello")
    Call<ResponseBody> hello();

    @GET("backend/v1/hello/abc")
    HelloBean helloBean2();
}

```

**Comment by liuziyuan** [comment]
> @liuziyuan [quarkiverse/quarkus-easy-retrofit](https://github.com/quarkiverse/quarkus-easy-retrofit) is now provisioned. Welcome to Quarkiverse! See [hub.quarkiverse.io/checklist/#after-the-repository-is-created](https://hub.quarkiverse.io/checklist/#after-the-repository-is-created) for the next steps

thank you very much.I will start the next step
