### ISSUE TITLE
Support Kotlin 2.0

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#40590]
### Description

Kotlin is preparing the 2.0 release. As of this writing, the Kotlin 2.0 RC3 is out (https://kotlinlang.org/docs/whatsnew-eap.html). Since Kotlin 2.0 brings some major changes under the hood (new compiler), I assume this might have implications for the Quarkus integrations. Therefore it probably is a good idea to start looking into what needs to be adapted. 

I had a first glance and updated the libraries locally but noticed some problems. Unfortunately, I currently don't have the time to investigate it further myself and I'm not deep enough into the Quarkus internals yet.

**Comment by geoand** [comment]
Do you by any chance have stacktraces of things that were failing?

**Comment by andreas-eberle** [comment]
I pushed the initial changes here https://github.com/andreas-eberle/quarkus/tree/feature/kotlin-2.0. But it only contains the version number increase. 

At the moment, the buid fails when I run `./mvnw install -Dquickly -DskipTests -DskipITs`.

The error is
```
javax.annotation.processing.Processor: Provider io.quarkus.panache.common.runtime.PanacheAnnotationProcessor not found
```

and happens when it tries to compile

```
[INFO] Quarkus - Hibernate Reactive with Panache - Common - Runtime FAILURE [  0.707 s]
```

**Comment by mschorsch** [comment]
Kotlin 2 was released https://kotlinlang.org/docs/whatsnew20.html, but the IDE support still seems to have alpha status.

**Comment by geoand** [comment]
@gastaldi just merged a PR that bumps to Kotlin 2.

**Comment by gastaldi** [comment]
Yeap, https://github.com/quarkusio/quarkus/pull/40745. Closing this now

**Comment by mschorsch** [comment]
Thanks @gastaldi 👍
