### ISSUE TITLE
Micrometer performance improvements - runtime package

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#40598]
### Description

Implement improvements described in #40507 on the `io.quarkus.micrometer.runtime` packages.
There are 2 classes that I identified for optimisation: 

- `MicrometerCountedInterceptor`
- `MicrometerMetricsFactory`
- `MicrometerTimedInterceptor`

**Comment by prateekrai1** [comment]
Can I take this issue?

**Comment by julant7** [comment]
Hello!
I am very interested in this task. Could you please assign this issue to me?

**Comment by brunobat** [comment]
It's all yours @julant7. Please let me know if you need any help.

**Comment by DShivansh** [comment]
@julant7 are you working on this task?

**Comment by julant7** [comment]
Hello [@DShivansh](https://github.com/DShivansh)! Yes I am

**Comment by brunobat** [comment]
No work needed on this one anymore.
