### ISSUE TITLE
[Extension Proposal] Nagios health endpoint

### ISSUE THREAD

**Issue by derari** [quarkusio/quarkus#40617]
### Description

Nagios (https://www.nagios.org/) is a monitoring and alerting tool.

Nagios allows to add custom health checks via shell scripts. A simple way to monitor the uptime of a quarkus application is to curl the (SmallRye) health endpoints.

However, if you want to use more features of Nagios, such as specific error messages, performance graphs, and alert levels, you need to implement a custom script for each aspect you want to check. Scripts need to output their data in a specific format for Nagios to pick it up. Such a setup creates friction between Devs and Operation every time checks need to be modified.

This extension adds endpoints that report all Microprofile health checks in the Nagios format, so that in the Nagios server a small re-usable script around curl is enough to configure all checks.

Furthermore, this extension provides a custom implementation of the Microprofile HealthCheckResponse API, that allows to use more Nagios features:
* 4 alert levels (ok, warning, unknown, critical)
* export numerical results as performance data (allows Nagios to graph historic data)
* re-usable check definitions with Nagios alert ranges

Code currently hosted here: https://github.com/derari/quarkus-nagios

### Repository name

quarkus-nagios

### Short description

Health endpoints in Nagios format

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- observability

### Team Members

- @derari

**Comment by maxandersen** [comment]
interesting and useful for those using nagios.

What is the health-api in https://github.com/derari/quarkus-nagios about ? seems like a copy of other library or ?

**Comment by derari** [comment]
it's the implementation of the microprofile health response api that I mentioned. I put it in a separate module so I could version it independently

**Comment by gastaldi** [comment]
@derari Welcome to Quarkiverse! The repository https://github.com/quarkiverse/quarkus-nagios has been created. See the next steps here: https://hub.quarkiverse.io/checklist/#after-the-repository-is-created

**Comment by derari** [comment]
@gastaldi it seems I have not been added as a maintainer, is there something else I need to do first?

**Comment by gastaldi** [comment]
You newd to accept the GitHub invitation email, check your inbox

**Comment by derari** [comment]
ah, it was buried in the spam. thanks for sending it again

**Comment by maxandersen** [comment]
@derari did you manage to get setup ? curious to play with it but quarkus-nagios shows up empty to me.
