### ISSUE TITLE
Quarkus upgrade to 3.10.0 in gradle environment

### ISSUE THREAD

**Issue by DaveO-Home** [quarkusio/quarkus#40664]
### Description

build.gradle - if (id "io.quarkus") is defined without a version and after the upgrade, ./gradlew quarkusDev will fail with a conflict between 3.9.5 and 3.10.0.

### Implementation ideas

Can be fixed with:
1. change `id "io.quarkus"` with `id "io.quarkus" version "3.10.0"`
2. Or by removing gradle cache

**Comment by gastaldi** [comment]
Do you have a `settings.gradle` with the following content? 

```gradle
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id "${quarkusPluginId}" version "${quarkusPluginVersion}"
    }
}
```


And a `gradle.properties` with:

```properties
#Gradle properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.10.1
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.10.1
``` ?

**Comment by DaveO-Home** [comment]
@gastaldi - yes I understand the config, however I have a very old build.gradle and did not have "version"/${quarkusPluginVersion}" set for "id". I only reported it because other applications may also have old configurations. At first it just wasn't clear how to fix. I will make sure the plugin version is set. Thx
