### ISSUE TITLE
RESTEasy is @GET optional?

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4069]
On stage I did the following and the endpoint was not published

```
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@Path("/api")
public class TodoResource {

    @Path("/search/{word}")
    public List<Todo> search(@PathParam("id") String word) {
        return Todo.listAll();
    }
}
```

Notice the absence of `@GET`. @cescoffier seems to say that it is a bug as GET is the default. But I don't know. It's to double check.

**Comment by gsmet** [comment]
@asoldano @patriot1burke ?

**Comment by kenfinnigan** [comment]
I'm pretty sure there's no default for HTTP method verbs in JAX-RS

**Comment by asoldano** [comment]
https://docs.jboss.org/resteasy/docs/4.3.0.Final/userguide/html/JAX-RS_Resource_Locators_and_Sub_Resources.html

**Comment by gastaldi** [comment]
The above link seems to answer the question:

>Resource methods that have a `@Path` annotation, but no HTTP method are considered sub-resource locators

**Comment by emmanuelbernard** [comment]
Ok so in my case the resource locator also had no `@GET` hence was not a resource locator. Thus I had the bug.

It would be nice for the RESTEasy extension or core to scan and detect that mistake and either

1. stop the build with a nice error
2. show the error in the Error 500 page in dev mode if somehits the path maybe?

**Comment by stuartwdouglas** [comment]
This is not actually an error though, if that method returned a custom instance of List that had a method annotated with @GET then this would be valid (I guess you could check if there are any valid sub resource locators that implement the interface, but it still would not be perfect).

**Comment by patriot1burke** [comment]
There is no default method type in JAX-RS.  If you do not have an http method, JAX-RS assumes it is a sub resource locator.

**Comment by patriot1burke** [comment]
And the return value can be anything, even java.lang.Object.  The JAX-RS runtime scans the class to try and resolve the request at runtime.  All dynamically.  We used this extensively in Keycloak to allow people to plug in their own REST APIs under how URL hierarchy.

**Comment by stuartwdouglas** [comment]
Yea, I think the only validation you could do is that if a type is returned (e.g. List) and there are no discovered locators that implement List then you could detect the problem. This would likely work for 99% of cases where there is user error, although I am not sure if it is worth it.

**Comment by geoand** [comment]
I am going to close this because as Stuart mentioned, this is likely not worth the effort.
