### ISSUE TITLE
mvn quarkus:dev fails on new projects without compile

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4070]
@cescoffier told me that `compile` is optional now in `mvn compile quarkus:dev` but on new projects it will fail because there is no target directory created yet (I think). Is that to be considered a bug? @stuartwdouglas @aloubyansky

**Comment by geoand** [comment]
I don't think this has been included in `0.22`.

https://github.com/quarkusio/quarkus/pull/3879
