### ISSUE TITLE
quarkus-hibernate-orm - lazy loading of parameterized attributes from MappedSuperclass with getter does not work.

### ISSUE THREAD

**Issue by mapuci** [quarkusio/quarkus#40719]
### Describe the bug

Reproducer: https://github.com/mapuci/hibernate-parameterized-mappedsuperclass
* contains issue reproducer with `quarkus`
* contains working example with same entities in `wildfly`

I believe reading the simple reproducer code offers the best explanation.
* See https://github.com/mapuci/hibernate-parameterized-mappedsuperclass/blob/main/quarkus3-hibernate-parameterized-mappedsuperclass/src/main/java/si/mapuci/ReproducerEndpoint.java method `thisWillFail`
* See classes 
  * https://github.com/mapuci/hibernate-parameterized-mappedsuperclass/blob/main/quarkus3-hibernate-parameterized-mappedsuperclass/src/main/java/si/mapuci/entity/AbsOne.java
  *  https://github.com/mapuci/hibernate-parameterized-mappedsuperclass/blob/main/quarkus3-hibernate-parameterized-mappedsuperclass/src/main/java/si/mapuci/entity/One.java
* Notice that `hibernate_interceptor` does not get invoked when calling getter of `parameterized entity field, inside abstract MappedSuperClass `

If you have read the code and README, stop reading.

We have entity and its abstract parameterized MappedSuperclass:
```java
@MappedSuperclass
public abstract class AbsOne<TWO extends AbsTwo<?, ?>> {
    @Id
    @GeneratedValue
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "two_id")
    private TWO two;
//... getters, setters... are ommited
}

@Entity
public class One extends AbsOne<Two> {
    private String oneConcreteProp;
//... getters, setters... are ommited
}    

//and some more, for the context
@MappedSuperclass
public abstract class AbsTwo<ONE extends AbsOne<?>, THREE extends AbsThree<?, ?>> {
    @Id
    @GeneratedValue
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "three_id")
    private THREE three;
//... getters, setters... are ommited
}

@Entity
public class Two extends AbsTwo<One, Three> {
    private String twoConcreteProp;
//... getters, setters... are ommited
}    
```

After these entities are enhanced by bytebuddy/hibernate, invoking getters for parameterized field (e.g. `one.getTwo()`) do not invoke  `$$_hibernate_getInterceptor()`, so the relation is not lazily fetched.
Works as expected in latest wildfly.

### Expected behavior

Hibernate interceptor is invoked, triggering lazy load.

### How to Reproduce?

clone https://github.com/mapuci/hibernate-parameterized-mappedsuperclass
here you will find quarkus reproducer AND wildfly project, with same entities working normally.
With some of my additional insights in readme. :)

To reproduce, change directory to `quarkus3-hibernate-parameterized-mappedsuperclass` and run `./mvnw test`. 

### Output of `uname -a` or `ver`

Darwin Matejs-MacBook-Pro-2.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

17 (tried with 21 also)

### Quarkus version or git rev

3.10.1 (I also tried 2.0.3.Final, 3.2.0.Final, 3.8.0)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by yrodiere** [comment]
Hey @mapuci ; thanks for reporting.

IIRC WildFly doesn't enable bytecode enhancement by default, so I don't think the WildFly reproducer is relevant.

Are you able to reproduce your issue in this test? https://github.com/hibernate/hibernate-test-case-templates/blob/main/orm/hibernate-orm-6/src/test/java/org/hibernate/bugs/QuarkusLikeORMUnitTestCase.java

If so, that's a bug in Hibernate ORM and we should fix it there. If not, it's indeed a bug in Quarkus itself.

**Comment by mapuci** [comment]
Hi @yrodiere thank you for the reply.

I will try to reproduce the issue with test mentioned above, I will let you know what I find.

About `WildFly doesn't enable bytecode enhancement by default`...
Sry, I misunderstood. Quarkus does bytecode enhancement with bytebuddy, WF just create proxies at runtime. With bytebuddy :D

But, results should be identical. 

I'll let you know what I find.

**Comment by mapuci** [comment]
Hey @yrodiere 
I managed to reproduce it in hibernate repo. I have created PR and an issue:

https://github.com/hibernate/hibernate-test-case-templates/pull/387
https://hibernate.atlassian.net/browse/HHH-18151

I think that piece of code is cool. :)
![image](https://github.com/quarkusio/quarkus/assets/20385863/04dcb192-c2f1-4a59-bd29-d555aa63f9cf)

I'm closing this issue, because 'it's not quarkus related'

**Comment by yrodiere** [comment]
Thanks a lot @mapuci!
