### ISSUE TITLE
Enable in CI the build of GraalVM master and run the Quarkus test suite against it

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4071]
The Micronaut team and GraalVM team are doing that. Or more precisely, the micronaut team is having a CI job and monitor it. When they detect that something fails, they report to the GraalVM team. If that not complicated it would be nice to do the same on our side. I'd also love to get the memory usage diff to make sure they don't regress.

CC @dmlloyd for Mandrel's PoV

**Comment by dmlloyd** [comment]
Good idea IMO.

**Comment by emmanuelbernard** [comment]
@geoand this is done right?

**Comment by geoand** [comment]
Yes it is. Just not in GH Actions yet.

However I think @galderz also has something similar, but I don't know the details of his setup.

**Comment by galderz** [comment]
The script I have is mostly for bare metal testing end-to-end, and try out fixes...etc.

**Comment by emmanuelbernard** [comment]
So can I close this issue? Do we have a stable chain validating this?

**Comment by geoand** [comment]
+1 from me
