### ISSUE TITLE
Build Error after bump jandex-maven-plugin version from 3.1.8 to 3.2.0

### ISSUE THREAD

**Issue by oflorez-airgraft** [quarkusio/quarkus#40739]
### Describe the bug

Error:  Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.10.1:build (default) on project XXXXX: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: [ERROR] 	[error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: org.jboss.jandex.UnsupportedVersion: Can't read Jandex index from /META-INF/jandex.idx: Can't read index version 12; this IndexReader only supports index versions 2-3,6-11
Error:  	at io.quarkus.deployment.index.IndexingUtil$MetaInfJandexReader.apply(IndexingUtil.java:288)
Error:  	at io.quarkus.deployment.index.IndexingUtil$MetaInfJandexReader.apply(IndexingUtil.java:264)
Error:  	at io.quarkus.paths.PathTreeVisit.process(PathTreeVisit.java:39)
Error:  	at io.quarkus.paths.DirectoryPathTree.apply(DirectoryPathTree.java:106)
Error:  	at io.quarkus.paths.ArchivePathTree$OpenArchivePathTree.apply(ArchivePathTree.java:262)
Error:  	at io.quarkus.paths.PathTreeWithManifest.apply(PathTreeWithManifest.java:[74](https://github.com/airgraft/eventbridge-lambdas/actions/runs/9158956926/job/25178357029#step:9:75))
Error:  	at io.quarkus.paths.SharedArchivePathTree$CallerOpenPathTree.apply(SharedArchivePathTree.java:153)
Error:  	at io.quarkus.deployment.index.IndexingUtil.indexTree(IndexingUtil.java:63)
Error:  	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.lambda$addMarkerFilePaths$1(ApplicationArchiveBuildStep.java:251)
Error:  	at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.apply(PathTreeClassPathElement.java:136)
Error:  	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.addMarkerFilePaths(ApplicationArchiveBuildStep.java:238)
Error:  	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.scanForOtherIndexes(ApplicationArchiveBuildStep.java:144)
Error:  	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.build(ApplicationArchiveBuildStep.java:105)
Error:  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:5[80](https://github.com/airgraft/eventbridge-lambdas/actions/runs/9158956926/job/25178357029#step:9:81))
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
Error:  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
Error:  	at java.base/java.lang.Thread.run(Thread.java:15[83](https://github.com/airgraft/eventbridge-lambdas/actions/runs/9158956926/job/25178357029#step:9:84))
Error:  	at org.jboss.threads.JBossThread.run(JBossThread.java:483)

### Expected behavior

running  mvn install -Dnative -DskipTests -Dquarkus.native.container-build=true works with jandex-maven-plugin 3.1.8 works

### Actual behavior

running  mvn install -Dnative -DskipTests -Dquarkus.native.container-build=true works with jandex-maven-plugin 3.2.0 doesn't work

### How to Reproduce?

run command running  mvn install -Dnative -DskipTests -Dquarkus.native.container-build=true works with jandex-maven-plugin 2.2.0

### Output of `java -version`

21

### Mandrel or GraalVM version (if different from Java)

graalvm-community-jdk-21.0.2

### Quarkus version or git rev

3.10.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by DSkoufis** [comment]
@gsmet is there a way to automatically use the jandex maven plugin version that Quarkus supports?
