### ISSUE TITLE
Is Quarkus supposed to be supported by AWS CDK ? 

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#40748]
### Describe the bug

Hello,

I'm trying to use Quarkus 3.10.0 in an AWS CDK service. To simplify, I need to use MP Config in CDK apps, for example:

    @ApplicationScoped
    public class MyStack extends Stack
    {
      @Inject
      @ConfigProperty(defaultValue = "function.zip", name="zip-location")
      private String zipLocation;
      ...
      public MyStack()
      {
          ...
          System.out.println (">>> zipLocation: " + zipLocation);
          ...
      }
      ...
    }

There is no any `application.properties` file and, hence, I expect that the `defaultValue` be assigned. But the line which is printed out here looks as follows:

        >>> zipLocation: null

meaning that the injection hasn't been done. I'm not sure why ? 

Doing the same in a Quarkus test, as shown below, works as expected:

    @QuarkusTest
    public class MyStackIT
    {
      @Inject
      @ConfigProperty(defaultValue = "function.zip", name="zip-location")
      private String zipLocation;

      @Test
      public void test123()
      {
        assertThat(zipLocation).isEqualTo("function.zip");
      }
    }

Is that because, in the first case, the injection isn't yet effective in the constructor ? Or does it have anything to do with AWS CDK ?  To resume, is Quarkus supposed to work with CDK at all ? I don't see any reason it doesn't but you never know.

Many thanks in advance.

Kind regards,

Nicolas

### Expected behavior

I'd expect that the config injection be effective in an AWS `Stack` having the `ApplicationScoped`.

### Actual behavior

Actually, the injected property has the value `null`.

### How to Reproduce?

Don't have a reproducer

### Output of `uname -a` or `ver`

Linux nicolas-XPS-15-9570 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /opt/apache-maven-3.9.5 Java version: 21.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21-oracle-x64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-107-generic", arch: "amd64", family: "unix"

### Additional information

N/A

**Comment by geoand** [comment]
Hi,

I am not sure. but I assume that this one should be reported at https://docs.quarkiverse.io/quarkus-amazon-services/dev/index.html, no?

**Comment by gsmet** [comment]
I think in this very case, you need to use constructor injection. I'm not 100% sure this works with `@ConfigProperty` but I believe so, so maybe start with trying that.

**Comment by nicolasduminil** [comment]
@geoand : the link you've provided leads to the page attached below where it doesn't seem possible to report anything.
![Screenshot_20240522_143347](https://github.com/quarkusio/quarkus/assets/1037978/7c50dd9a-14f1-4707-9604-bb1007777738)

**Comment by argenstijn** [comment]
Ps.

A little bit late but still for folks who wants to know:

you can run AWS CDK with Quarkus. Even native.

-> when creating a stack you NEED to do constructor injection!

When building a native image: 

--initialize-at-run-time=software.amazon.awscdk

Because else it fails at build time because it needs Nodejs. Other option is to create a docker build image where you have a nodejs installed when building a native image!

for example see: https://dzone.com/articles/quarkus-api-aws-ecs-fargate-cdk
