### ISSUE TITLE
Opentracing extension: java.lang.reflect.InvocationTargetException: Illegal character in authority

### ISSUE THREAD

**Issue by jamesfalkner** [quarkusio/quarkus#4077]
**Describe the bug**
When building an app with the OpenTracing extension, and specifying an environment variable in the definition of an application property in `application.properties`:

```properties
quarkus.jaeger.endpoint=http://${JAEGER_ENDPOINT:jaeger-tracing}:14268/api/traces
```

The application fails to build (jvm or native) with

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.22.0:build (default) on project getting-started: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: java.lang.reflect.InvocationTargetException: Illegal character in authority at index 7: http://${JAEGER_ENDPOINT:jaeger-tracing}:14268/api/traces -> [Help 1]
```

**Expected behavior**
App builds and runs with no errors and the property is settable via environment variable at runtime.

**Actual behavior**
Unable to build (See above). If I rename the property to anything else, e.g.

```properties
quarkus.foobar.endpoint=http://${JAEGER_ENDPOINT:jaeger-tracing}:14268/api/traces
```
it works. If I set it to a value not using an environment variable, it also works:

```properties
quarkus.jaeger.endpoint=foo
```

**To Reproduce**
1.

```sh
mvn io.quarkus:quarkus-maven-plugin:0.21.1:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello" -Dextensions="opentracing"
```

2. 

Add variable definition to `src/main/resources/application.properties`

3. `mvn clean package -DskipTests`

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.jaeger.endpoint=http://${JAEGER_ENDPOINT:jaeger-tracing}:14268/api/traces
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Darwin jfalkner-OSX 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

 - Output of `java -version`: 

```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

 - GraalVM version (if different from Java): 

`graalvm-ce-19.1.1`

 - Quarkus version or git rev: 

0.22.0

**Comment by gsmet** [comment]
There's a good change you're hitting this issue: https://github.com/quarkusio/quarkus/issues/3516 and that the env variable is not expanded and Jaeger refuses either $ or { in the URL.

@dmlloyd what's the status of this one? It's an issue that often gets reported.

**Comment by dmlloyd** [comment]
It's in progress, but keeps getting bumped down due to one-off issues... sorry.  I'll try to get it done ASAP.
