### ISSUE TITLE
dynamic default index page has bad behavior when access from non localhost

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#40828]
### Describe the bug

I'm using ngrok to expose my app as github/zulip bots.

the new default landing page then now just shows up with /q/dev-ui/welcome and stuck at "quarkus" logo.

This is due to default cors preventing such access.

Same will happen I assume in web ide dev environments etc.

### Expected behavior

that *some* index page can be shown with a hint of what went wrong - unauthorized access would be useful.

or at least *some* info.

**Comment by phillip-kruger** [comment]
Can you describe how to recreate this ?

**Comment by phillip-kruger** [comment]
Thanks. Max showed me how, so I'll fix it soon
