### ISSUE TITLE
Add datasource configurations for initSQL and validationQuery

### ISSUE THREAD

**Issue by Rashmini** [quarkusio/quarkus#4082]
**Description**
Just tried to set up a connection pool using Quarkus. The first limitation is that there are no configuration keys for initSQL and validationQuery which can be configured using the application.properties file.

**Comment by chaminnk** [comment]
Initial SQL is now implemented in 0.24.0 release. Check `quarkus.datasource.new-connection-sql` in https://quarkus.io/guides/datasource-guide

**Comment by gsmet** [comment]
@anamarija maybe you could work on the addition of `validationQuery`?

**Comment by anamarija** [comment]
ok.
