### ISSUE TITLE
Extending a resource class loses OpenAPI security scheme when generated

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#40839]
### Describe the bug

When a resource extends an abstract class it will generate the OpenAPI methods but loses the security scheme.

```
components:
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: bearer
      bearerFormat: Opaque
```

### Expected behavior

An extended resource extends the security scheme

```yaml
  /goodbye:
    get:
      tags:
      - Regular Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "403":
          description: Not Allowed
        "401":
          description: Not Authorized
      security:
      - SecurityScheme: []
```

### Actual behavior

The security scheme is missing from the generated OpenAPI spec.

```yaml
  /hello:
    get:
      tags:
      - Extended Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
```

### How to Reproduce?

1 . Run `mvn install`
2. See the `target/openapi.yml` 

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/15443343/code-with-quarkus.zip)

### Output of `java -version`

21

### Quarkus version or git rev

3.10.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9

**Comment by kjq** [comment]
I think I have a rather elegant workaround for the time being using a OASFilter to apply the missing security scheme.

**Comment by phillip-kruger** [comment]
@MikeEdgar
