### ISSUE TITLE
Quarkus REST: setting a `LocalDate` parameter to an empty value results in a 400 instead of a `null` parameter

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#40833]
Given this endpoint:

```
@POST
public void foo(@RestForm LocalDate date){}
```

And this payload:
```
date=
```

I get a 400 from Quarkus REST. Probably because `TemporalParamConverter` doesn't handle empty strings? I think it should be set to a `null` value. I also assume other temporal types have the same issue.

**Comment by DShivansh** [comment]
@geoand can I pick this issue? I am not sure what the label triage/needs-triage mean :(

**Comment by DShivansh** [comment]
Hi @FroMage @geoand @ia3andy  
I was thinking that we can put a null check in the function `convert` to return null that is present inside `TemporalParamConverter` abstract class, does this seem like a good idea?

**Comment by geoand** [comment]
You can certainly give it a try
