### ISSUE TITLE
kafka metrics : label kafka_version=unknown in native mode

### ISSUE THREAD

**Issue by amkac** [quarkusio/quarkus#40851]
### Describe the bug

In native mode only the property 'kafka_version' does not apppear in the kafka_metrics, the value is always UNKNOWN. this issue does not occur in the jvm mode.

### Expected behavior

kafka_consumer_successful_authentication_rate{client_id=.... ",kafka_version="3.7.0"} 0.10734796843969728

### Actual behavior

kafka_consumer_successful_authentication_rate{client_id=.... ",kafka_version="unknown"} 0.10734796843969728

### How to Reproduce?

1. Build the app in native mode: `mvn clean install -Pnative`
2. Search for kafka metrics on` /q/metrics`

### Output of `java -version`

21

### Quarkus version or git rev

3.10.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9

**Comment by cescoffier** [comment]
Seems to be an issue in the micrometer binder. 

The KAfka version is set in:

```java
void prepareToBindMetrics(MeterRegistry registry) {
        this.metrics.set(this.metricsSupplier.get());
        Map<MetricName, ? extends Metric> metrics = this.metrics.get();
        // Collect static metrics and tags
        Metric startTimeMetric = null;

        for (Map.Entry<MetricName, ? extends Metric> entry : metrics.entrySet()) {
            MetricName name = entry.getKey();
            if (METRIC_GROUP_APP_INFO.equals(name.group()))
                if (VERSION_METRIC_NAME.equals(name.name())) {
                    kafkaVersion = (String) entry.getValue().metricValue();
                }
                else if (START_TIME_METRIC_NAME.equals(name.name())) {
                    startTimeMetric = entry.getValue();
                }
        }

        if (startTimeMetric != null) {
            MetricName startTimeMetricName = startTimeMetric.metricName();
            bindMeter(registry, startTimeMetric, meterName(startTimeMetricName), meterTags(startTimeMetricName));
        }
    }
```

For some reason, there is no version in native ("unknown" is the default one).
