### ISSUE TITLE
Allow unsupported Quartz scheduler properties

### ISSUE THREAD

**Issue by michelkaeser** [quarkusio/quarkus#40850]
### Description

Similar to how the Hibernate extension allows setting unsupported properties, the Quartz scheduler (why not all extensions? 😃) should allow setting unsupported properties.

Personally I am interested in enabling the JMX export via `org.quartz.scheduler.jmx.export = true` which I am unable to enable otherwise.

### Implementation ideas

`quarkus.quartz.unsupported-properties` should be available similar to `quarkus.hibernate-orm.unsupported-properties`.

**Comment by mkouba** [comment]
@michelkaeser That's a good idea. Would you care to work on this feature? ;-)

**Comment by geoand** [comment]
I would call them `quarkus.quartz.additional-properties` really instead of `unsupported-properties`

**Comment by mkouba** [comment]
> I would call them `quarkus.quartz.additional-properties` really instead of `unsupported-properties`

I don't know. It might make sense to keep it consistent with [`quarkus.hibernate-orm.unsupported-properties`](https://quarkus.io/guides/all-config#quarkus-hibernate-orm_quarkus-hibernate-orm-unsupported-properties-full-property-key) :shrug:.

**Comment by geoand** [comment]
Right, consistency is important, but I am pretty sure that in Hibernate they are called unsupported because there is no guarantee they will work, whereas AFAIU in Quartz the situation is different

**Comment by mkouba** [comment]
> Right, consistency is important, but I am pretty sure that in Hibernate they are called unsupported because there is no guarantee they will work, whereas AFAIU in Quartz the situation is different

I'm not so sure TBH.
