### ISSUE TITLE
POM is not preserved when we add or remove extensions with CLI

### ISSUE THREAD

**Issue by jcarranzan** [quarkusio/quarkus#40853]
### Describe the bug

I was testing the backport related to preserving POM integrity after adding an extension ( https://github.com/quarkusio/quarkus/pull/40663/commits/2bb40f94ac518a45a092054f42b06f4e60680b24).
However, it seems that POM integrity is still not preserved when we add or remove extensions through CLI commands.
I've created a reproducer to show you this behavior (`git clone -b pom-preserve-cli https://github.com/jcarranzan/quarkus-reproducer.git`).

### Expected behavior

The POM retains the same structure and comments after adding or removing an extension.

### Actual behavior

The POM is overwritten, and comments are not preserved.

### How to Reproduce?

`git clone -b pom-preserve-cli https://github.com/jcarranzan/quarkus-reproducer.git`

### Quarkus version or git rev

3.8.999-SNAPSHOT

**Comment by rsvoboda** [comment]
@gsmet https://github.com/jcarranzan/quarkus-reproducer/blob/pom-preserve-cli/src/test/java/io/quarkus/QuarkusCliPomIntegrityIT.java is the test, using `io.quarkus.test.bootstrap.QuarkusCliClient;`

**Comment by rsvoboda** [comment]
@jcarranzan  `mvn clean verify -Dquarkus.platform.version=3.10.2` fails too

I don't think you persist comment addition back to the pom.xml file after https://github.com/jcarranzan/quarkus-reproducer/blob/pom-preserve-cli/src/test/java/io/quarkus/QuarkusCliPomIntegrityIT.java#L39C34-L39C41

**Comment by gsmet** [comment]
I would recommend to start with a POM file containing comments and new lines.

**Comment by jcarranzan** [comment]
I tweak the test with the @rsvoboda  suggestion,

1. It creates a Quarkus application named APP_NAME using the QuarkusCliClient.
2. Reads the initial content of the POM file.
3. Adds the COMMENT at line 1, and writes the modified content back to the file.
4. Next, it installs the new extension using` app.installExtension() `with `QuarkusCliClient` from `QuarkusCliRestService` .
5. After installation, it reads the updated content of the POM file and asserts that it contains the comment added.
Then the test fails because the comment is not there.

Finally, it removes the extension and repeats the process to ensure that the comment remains in the POM file even after the extension is remove, but this part of the code is not executed because fails in the lines before mentioned.

**Comment by rsvoboda** [comment]
Thanks @jcarranzan for the update.

I tried with quarkus command (version 3.10.2) and I can confirm that the comments are not preserved @gsmet 

```
quarkus create app foo:bat:1.0
cd bat
open pom.xml, add comment to the file, save
quarkus ext add quarkus-kafka-client
check pom.xml, comment is not there
```

**Comment by rsvoboda** [comment]
@gastaldi can you look into this? (As you worked on https://github.com/quarkusio/quarkus/pull/39382)

**Comment by gastaldi** [comment]
I've investigated and figured out that's caused by 68a1bbe7424ff482bb2c63f76219eb2591c2a394, I'm working on a fix right now.

**Comment by gastaldi** [comment]
@jcarranzan yes, you need to build my branch to test that
