### ISSUE TITLE
UT005071: Undertow request failed HttpServerExchange

### ISSUE THREAD

**Issue by yoinercoding** [quarkusio/quarkus#40856]
### Describe the bug

Hi everyone, I have this problem when an application tries to communicate with my endpoint. BPM queries my endpoint and then I go to another application to fetch the response which it successfully returns to me in a json. The issue is that BPM can't reach my endpoint, it throws the following error within a 500 = 

{"timestamp":"2024-05-27T13:09:48.652-03:00","sequence":3297,"loggerClassName":"io.undertow.UndertowLogger_$logger","loggerName":"io.undertow.request","level":"ERROR","message":"UT005071: Undertow request failed HttpServerExchange{ GET
http://localhost:8080/v1/solicitudes/10186427/consulta/apiVentas
delegate io.undertow.vertx.VertxHttpExchange@5eaabe88}","threadName":"executor-thread-0","threadId":221,"mdc":{},"ndc":"","hostName":"099n6737","processName":"api-originacion-dev.jar","processId":30048,"exception":{"refId":1,"exceptionType":"java.lang.IllegalArgumentException","message":"UT000068: Servlet path match failed","frames":[{"class":"io.undertow.servlet.handlers.ServletPathMatchesData","method":"getServletHandlerByPath","line":83},{"class":"io.undertow.servlet.handlers.ServletPathMatches","method":"getServletHandlerByPath","line":89},{"class":"io.undertow.servlet.handlers.ServletInitialHandler","method":"handleRequest","line":124},{"class":"io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1","method":"handleRequest","line":120},{"class":"io.undertow.server.Connectors","method":"executeRootHandler","line":284},{"class":"io.undertow.server.DefaultExchangeHandler","method":"handle","line":18},{"class":"io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1","method":"run","line":417},{"class":"java.util.concurrent.Executors$RunnableAdapter","method":"call","line":572},{"class":"java.util.concurrent.FutureTask","method":"run","line":317},{"class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14","method":"runWith","line":576},{"class":"org.jboss.threads.EnhancedQueueExecutor$Task","method":"run","line":2449},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"run","line":1478},{"class":"org.jboss.threads.DelegatingRunnable","method":"run","line":29},{"class":"org.jboss.threads.ThreadLocalResettingRunnable","method":"run","line":29},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","line":30},{"class":"java.lang.Thread","method":"run","line":1583}]}}

The route you send is fine, since I test it myself (already deployed in the corresponding environment and local) and it works.

In spring it works fine, I am migrating it to Quarkus and when doing this integration test it fails.

Any suggestions? I send you the controller as defined 

@ApplicationScoped
@Path(value = "/v1")
@Tag(name = "ventas-controller", description = "VentasController")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class VentasController extends ControllerBase {

        @Inject
        VentasService service;

        @Extensions({
                @Extension(name = "ServiceName",
                            value = "Api-Originacion_getSolicitudApiVentas"),
                @Extension(
                            name = "MandatoryHeaders",
                            value = "x-canal, x-idProceso, x-usuario, x-usuarioIP"
                )
        })
        @GET
        @Path(value = "/solicitudes/{nroSolicitud}/consulta/apiVentas")
        @Operation(summary = "Recurso que se encarga de obtener los datos de una solicitud a traves de api-ventas",
                    description = "Recurso que se encarga de obtener los datos de una solicitud a traves de api-ventas")
        @APIResponse(
                responseCode = "200",
                description = "OK",
                content = @Content(
                        mediaType = "application/json",
                        schema = @Schema(
                                implementation = ApiVentasResponseDTO.class
                        )
                    )
                )
        public Response getSolicitudFromApiVentas(
                @Context HttpHeaders httpHeaders,
                @PathParam("nroSolicitud") BigInteger nroSolicitud
        ) throws Exception {
            String contentType = httpHeaders.getHeaderString("Content-Type");
            ApiVentasResponseDTO response = service.getSolicitudFromApiVentas(nroSolicitud, httpHeaders);
            return Response.ok().entity(response).build();
        }
}

### Output of `java -version`

Java version: 17.0.7, vendor: GraalVM Community

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.6

**Comment by gastaldi** [comment]
Please create a small reproducer and attach to this issue

**Comment by geoand** [comment]
Closing for the lack of a reproducer
