### ISSUE TITLE
WebSockets Next: make it possible to perform logic before the HTTP upgrade is started

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#40867]
### Description

Most likely introduce a new interface that can be implemented by CDI beans. We should be able to order the implementations (e.g. `@Priority` + `@All List<T>`).

The implementations should be able to inspect the HTTP request (headers etc.), reject the upgrade, ....

**Comment by michalvavrik** [comment]
Looks very interesting and will help me with #40622. Thanks

**Comment by michalvavrik** [comment]
Quarkus REST https://quarkus.io/guides/rest has https://javadoc.io/doc/io.quarkus.resteasy.reactive/resteasy-reactive/3.10.2/org/jboss/resteasy/reactive/server/ServerExceptionMapper.html that allows to register either global mapper for all the REST resources, or just for the one resources where the bean is produced. 

For WS Next, it could be of interest to register this new interface for one endpoint only to avoid path-matching inside that bean.

**Comment by michalvavrik** [comment]
Maybe later though.

**Comment by geoand** [comment]
Definitely +1 on focusing on global and then moving to per class

**Comment by michalvavrik** [comment]
> Definitely +1 on focusing on global and then moving to per class

hey @geoand , yes as far as user beans go, but it would be ineffective to have a global bean applied on every endpoint and then start matching request with a bean to determine if you need to run it. If I need to secure just one endpoint of all, I think it's better to have a local endpoint specific. in #40873 I added build item for that, so it's Quarkus internal but it will exist.

**Comment by geoand** [comment]
I'll have to have a look in a few days

**Comment by michalvavrik** [comment]
> I'll have to have a look in a few days

sure, no hurry, thx

**Comment by geoand** [comment]
👍🏼

**Comment by michalvavrik** [comment]
> @michalvavrik We could also add a method to the interface to be able to filter the endpoints by id, i.e. io.quarkus.websockets.next.WebSocket.endpointId().

I like that, I can refactor #40873 to use that instead.

**Comment by michalvavrik** [comment]
Done.
