### ISSUE TITLE
quarkus.package.decompiler warning in quarkus 3.10+

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#40874]
### Describe the bug

when using `quarkus.package.decompiler.enabled=true` in an an app the following is printed;

```
[INFO] --- quarkus:3.10.2:build (default) @ code-with-quarkus ---
[WARNING] [io.quarkus.deployment.configuration] Configuration property 'quarkus.package.decompiler.enabled' has been deprecated and replaced by: [quarkus.package.decompiler.enabled]
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.package.decompiler.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] The decompiled output can be found at: /Users/alex/Downloads/code-with-quarkus 2/target/decompiled
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 8668ms
```

### Expected behavior

Warning should not be issued. In quarkus 3.8 the warning is not printed

### Actual behavior

Warning is printed

### How to Reproduce?

to reproduce

1- download the default project from code.quarkus.io
2- add the following to the application.properties; `quarkus.package.decompiler.enabled=true`

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

jdk 21

### Quarkus version or git rev

3.10.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 1.9.7

**Comment by dmlloyd** [comment]
It looks like #40277 had an error in it. Sorry about that.
