### ISSUE TITLE
RestEasy Server - @RestForm List<T>/Set<T> parameters not being split

### ISSUE THREAD

**Issue by TheGeekPharaoh** [quarkusio/quarkus#40903]
### Describe the bug

A Set/List property annotated with `@RestForm` as part of an HTTP POST/PUT/etc. is not having its values split.

### Expected behavior

A property that looks like this:

```
	@RestForm("assignedUsers")
	private Set<String> assignedUsers = null;

```
...that receives PUT values of "abcd,wxyz,1234,4321" should consist of a Set<String> of those values.

### Actual behavior

The assignedUsers value comes back as a Set<String> with only one value:  abcd,wxyz,1234,4321.  The results are returned as a Set<String> with a single String with all values, rather than a Set<String> with 4 values.

### How to Reproduce?

See behavior description

### Additional information

Tested on Quarkus 3.11.0

**Comment by geoand** [comment]
It would be very useful if you could attach a sample application that exhibits the behavior you mention and sample invocation (via a test or a curl command)?

Thanks

**Comment by luca-bassoricci** [comment]
@separator annotation doesn't apply here?

**Comment by geoand** [comment]
I don't remember really, but it's definitely worth a try

**Comment by TheGeekPharaoh** [comment]
I just tried with @Separator("") and got the same result.

**Comment by TheGeekPharaoh** [comment]
Sorry, @Separator(",")

**Comment by geoand** [comment]
Please add a sample application that we can use to test. Thanks

**Comment by geoand** [comment]
Closing for a lack of a reproducer. If one becomes available, please attach it and we can reopen the issue
