### ISSUE TITLE
turn on hibernate.highlight_sql

### ISSUE THREAD

**Issue by gavinking** [quarkusio/quarkus#40921]
### Description

Quarkus does not appear to give me a way to enable `hibernate.highlight_sql`, making the logged SQL difficult to read.

Since Quarkus already highlights log messages by default, I would actually just turn this setting on by default.

**Comment by Eng-Fouad** [comment]
Have you tried `quarkus.hibernate-orm.unsupported-properties."hibernate.highlight_sql"=ture`?

**Comment by geoand** [comment]
Cool feature!

#40954 adds support for it
