### ISSUE TITLE
`@OidcClientFilter` triggers several tokens in concurrency conditions 💣 

### ISSUE THREAD

**Issue by Dougniel** [quarkusio/quarkus#40923]
### Describe the bug

When the [rest client](https://quarkus.io/guides/security-openid-connect-client-reference#resteasy-client-oidc-filter) is used for the first time, or when the token is being refreshed, multiple concurrent calls cause multiple request to retrieve the token.

It happens when the concurrency could even come from : 
- outside of the application _(through concurrent REST/gRPC calls)_ during a burst period
- or from the application itself as well, when concurrent calls are made _(throughout a `Uni.join()`)_

### Expected behavior

The token be retrieved once and shared for all customer calls, like in no concurrency conditions

### Actual behavior

Each concurrent call triggers a token retrieval 

### How to Reproduce?

I made a [test-case](https://github.com/Dougniel/quarkus-rest-client-oidc-race-condition/blob/main/src/test/java/org/acme/GreetingResourceTest.java) that simulates concurrency from outside the application and from inside. The test fails as only one call is expected to the `/oauth2/token`

### Output of `uname -a` or `ver`

Darwin Kernel Version 23.5.0 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode)

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.6

### Additional information

I had a look at [`TokensHelper.java`](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/TokensHelper.java) and it seems that the problem is between the first call to get the token and the reply : subsequent clients calls subscribes the same `Uni<Tokens>` thought the filter and so, triggers again the call to get the token. 

So I made a [patch](https://github.com/Dougniel/quarkus-rest-client-oidc-race-condition/blob/f3e28fba42da3fda2edcdaa32752e304c2520e5f/src/main/java/org/acme/runtime/PatchedTokensHelper.java#L79) by doing a `.memorize()` on `Uni<Tokens>` before `prepareUni(Uni<Tokens> uni)` returns

**Comment by sberyozkin** [comment]
@Dougniel Thanks, but the `memoize().indefinitely()` is a problem, right ? Some clients can fail with a blocked thread error as a result.

What exactly is a problem with the token endpoint called concurrently under some conditions ? As long as OidcClient ends up with a single valid token, it should work  ?

**Comment by sberyozkin** [comment]
CC @cescoffier, @jponge

**Comment by Dougniel** [comment]
Hi @sberyozkin, thanks for your reactiveness 😎

> @Dougniel Thanks, but the `memoize().indefinitely()` is a problem, right ? Some clients can fail with a blocked thread error as a result.

Nope, `memoize().indefinitely()` is about saving the state of the `Uni` indefinitely (even if it looks like the blocking method `.await().indefinitely()`😉).

So, if some concurrent client call gets the same `Uni<Tokens>` (but this [way](https://github.com/quarkusio/quarkus/blob/6bc64a00d8748e56db2e4bb7a49f13f1c30d51de/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/TokensHelper.java#L49)) that was _memorized_, at subscription :
- if the HTTP request to retrieve the token is still running, the Uni will resolve once the token arrives
- if the token had been received, the Uni resolves immediately 

Without the _memorization_, the subscription will replay the HTTP request to retrieve the token, the actual behaviour.

> What exactly is a problem with the token endpoint called concurrently under some conditions ? As long as OidcClient ends up with a single valid token, it should work ?

I noticed it because I reached some eq/secondes limits with the Oauth2 server during a burst moment causing errors. This 
is also increase latency as there is one call more for each client call and flood the audit log..

Above all, Quarkus will be even more awesome 🤩 with predictable behaviour 😉

**Comment by sberyozkin** [comment]
Hey @Dougniel 

>if the HTTP request to retrieve the token is still running, the Uni will resolve once the token arrives

and

>if the token had been received, the Uni resolves immediately

Yes, I realized it shortly after I switched off my laptop and went for a walk :-), that other requests will not be worse if one is already busy retrieving tokens, thanks for the summary.

Can you please open a PR with your update when you get a chance ? If possible, add a test too, in `integration-tests/oidc-client-wiremock`.

I'll be on PTO from tomorrow, so I won't be able to review/approve but please tag @michalvavrik, @stuartwdouglas @cescoffier and @jponge and hopefully it will be approved :-)

Thanks
