### ISSUE TITLE
open classes/files listed in devui in IDE

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#40929]
### Description

early days we had classes and methods in devui linked so a click would open them in your IDE. 

I don't spot them anymore, especially not in Arc and Qute devui where this would be amazing.

@phillip-kruger any good way of enabling this we can point to in specifci isseus for various extnensions devmode?

Examples where open in IDE would be awesome:

<img width="1028" alt="2024-06-01_09-15-38" src="https://github.com/quarkusio/quarkus/assets/54129/ad3c5f4b-a5ff-4415-a55c-0aaee6ff7b56">
<img width="1028" alt="2024-06-01_09-15-25" src="https://github.com/quarkusio/quarkus/assets/54129/8eff0934-fcec-4a80-b871-f65f32293fdf">
<img width="1028" alt="2024-06-01_09-15-13" src="https://github.com/quarkusio/quarkus/assets/54129/2cd7675f-ffd3-41f9-b8a3-e73fa0cbb3d7">

### Implementation ideas

We can at least derieve file name for classes and resources, and for some we could even have code that locate the most likely line/column number in that file and pass that to the openIDE method.

**Comment by maxandersen** [comment]
cc @ia3andy

**Comment by phillip-kruger** [comment]
This should work. I'll have a look

**Comment by phillip-kruger** [comment]
@maxandersen there was a small issue, please see PR

**Comment by maxandersen** [comment]
#41014 fixes it for arc - but webbundler resources are not linked.

**Comment by phillip-kruger** [comment]
Then the web bundler is not using the ide component. Let's open a ticket there.

**Comment by phillip-kruger** [comment]
https://github.com/quarkiverse/quarkus-web-bundler/issues/236
