### ISSUE TITLE
Duplicated dependencies in main integration test

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#4093]
```console
[WARNING] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Dependencies with duplicate files detected. The dependencies [org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec::jar:1.1.1.Final(compile), javax.transaction:java>
[WARNING] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Dependencies with duplicate files detected. The dependencies [javax.xml.bind:jaxb-api::jar:2.3.1(compile), org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:1.0.1.Fin>
[WARNING] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Dependencies with duplicate files detected. The dependencies [org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec::jar:1.0.1.Final(compile), javax.interceptor:jav>
```

This appears during augmentation on `integration-tests/main`.

**Comment by AmauryOrtega** [comment]
I get exactly the same error.

**Comment by gsmet** [comment]
Most of this got solved by my Jakarta patch but we still have:
```
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.jboss.logging:commons-logging-jboss-logging::jar:1.0.0.Final(compile), commons-logging:commons-logging::jar:1.2(compile)] contain duplicate files, e.g. org/apache/commons/logging/impl/SimpleLog$1.class
```
when building `integration-tests/main`.

The funny thing is that we don't have it in `mvn dependency:tree` so I really don't know where it's coming from.

@anamarija if you're up for some detective work, this one would be a good one to deep dive into our build process :).

**Comment by anamarija** [comment]
ok

**Comment by AmauryOrtega** [comment]
@gsmet @anamarija I'm quite a noob when it comes to dependency inversion and injection, specially when it comes to CDI. Could you recommend some sources where I could read about it? Really curious what is going on here.

**Comment by anamarija** [comment]
[https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#introduction](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#introduction)

**Comment by gsmet** [comment]
I'm closing this one as @dmlloyd opened a more focused one here: https://github.com/quarkusio/quarkus/issues/5361 .
