### ISSUE TITLE
Quarkus REST: Allow multiple `HttpAuthenticationMechanism` annotations

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#40952]
### Description

Since Quarkus 3.10 it is possible to use annotations to select an authentication mechanism specific to each Jakarta REST endpoint via `HttpAuthenticationMechanism` (https://quarkus.io/guides/security-authentication-mechanisms#use-annotations-to-enable-path-based-authentication-for-jakarta-rest-endpoints), with the restriction that currently only one `HttpAuthenticationMechanism` annotation can be defined on the same endpoint.

Please allow to define multiple `HttpAuthenticationMechanism` annotations on the same endpoint.

**Comment by geoand** [comment]
cc @michalvavrik

**Comment by mschorsch** [comment]
Hello @michalvavrik  thank you for your reply.

We have a legacy application where several authentication methods are permitted for some endpoints. in our case a user can provide credentials via basic authentication or from a cookie. 

One of the authentication mechanism must authenticate.The order of the authentication procedures is relevant and the last authentication procedure should be required.

I can see it's not that easy 😃

**Comment by michalvavrik** [comment]
I see @mschorsch , yes, it's not trivial. It would be much easier to implement this for HTTP Security policy. Let's keep it open and gather opinions / interest.

**Comment by michalvavrik** [comment]
For now, your only option is to select your custom mechanism and delegate to other mechanisms dynamically https://quarkus.io/guides/security-customization#httpauthenticationmechanism-customization. That's not ideal.

**Comment by sberyozkin** [comment]
Hi @mschorsch @michalvavrik 

IMHO we should close this issue as not planned, as allowing multiple HTTP auth mechanism annotations would allow duplicate annotations like `@BasicAuthentication @BasicAuthentication` and it is a sign that, even though we can expect users not to do it, that it is not the right path. I believe the @mschorsch use case is quite specific and does warrnt an introduction of the custom mechanism, ensuring the correct ordering, and the controlling the way other mechanisms are called

**Comment by sberyozkin** [comment]
Perhaps at a later stage, having an inclusive authentication supported would also help

**Comment by michalvavrik** [comment]
Yeah, this is definitely not on my list for now, I think that delegating custom auth mechanism is acceptable solution as long as this is rare use case.

**Comment by sberyozkin** [comment]
Let me close for now then, thanks
