### ISSUE TITLE
Quarkus CLI can't find goal native-image-agent

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#40951]
### Describe the bug

When building project by latest Quarkus cli (999-SNAPSHOT) I get the error:
```
Could not find goal 'native-image-agent' in plugin io.quarkus.platform:quarkus-maven-plugin:3.11.0 
among available goals add-extension, add-extensions, analyze-call-tree, build, create, create-extension,
create-jbang, dependency-tree, deploy, dev, generate-code, generate-code-tests, go-offline, help,
image-build, image-push, info, list-categories, list-extensions, list-platforms, prepare, prepare-tests,
remote-dev, remove-extension, remove-extensions, run, test, track-config-changes, update -> [Help 1]
```

Most likely caused by https://github.com/quarkusio/quarkus/pull/36826

### Expected behavior

Build succesfully or have updated docs (don't know if this expected or not) as for example following [this guide](https://quarkus.io/guides/getting-started#packaging-and-run-the-application) I shouldn't get error.

### Actual behavior

Getting `Could not find goal 'native-image-agent'`

### How to Reproduce?

1. Build latest Quarkus
2. `cd devtools/cli`
3. Build latest CLI `mvn clean install -Dquickly -Dno-test-modules -Prelocations`
4. You can create script or run directly `devtools/cli/target/quarkus-cli-999-SNAPSHOT-runner.jar`
5. Create Quarkus app `java -jar devtools/cli/target/quarkus-cli-999-SNAPSHOT-runner.jar create app org.acme:getting-started --extension='rest'`
6. `cd getting-started`
7. `java -jar /home/jjedlick/work/quarkus/devtools/cli/target/quarkus-cli-999-SNAPSHOT-runner.jar build`

### Quarkus version or git rev

main

**Comment by zakkak** [comment]
> Most likely caused by #36826

@galderz FYI

**Comment by jedla97** [comment]
Looking into this and probably the [quarkus-maven-plugin](https://github.com/quarkusio/quarkus-platform/tree/main/generated-platform-project/quarkus-maven-plugin) was not updated.

The Quarkus CLI generate template containing `quarkus-maven-plugin` using latest released version (3.11.0 atm). But even when I use 999-SNAPSHOT version for `quarkus-maven-plugin` I still get this error. Removing the  `quarkus-maven-plugin` from generated pom it build fine.

**Comment by galderz** [comment]
I'm trying this but looking at the error there seems to be a mismatch somewhere:

```
Could not find goal 'native-image-agent' in plugin io.quarkus.platform:quarkus-maven-plugin:3.11.0...
```

The goal won't be found in a Quarkus maven plugin for version 3.11.0. No idea where that version is coming from but really the code should be testing/executing vs version 999-SNAPSHOT.

**Comment by galderz** [comment]
Yeah, the way this is being tested is not right:

```
        <quarkus.platform.version>3.11.0</quarkus.platform.version>
```

That's in the generated project and that's never going to work if you are building main and you are generating a project that uses an older version. Otherwise we would never be able to add new goals if this test was valid.

**Comment by jedla97** [comment]
@galderz thanks for investigating! I see it's working! Just a question:

If I use `--platform-bom=io.quarkus.platform::999-SNAPSHOT` I still getting the same error `Could not find goal 'native-image-agent' in plugin io.quarkus.platform:quarkus-maven-plugin:999-SNAPSHOT`. Shouldn't it work same? I build Quarkus and Quarkus platform today. I just want to be sure that this is expected.

**Comment by rsvoboda** [comment]
`<quarkus.version>3.11.0</quarkus.version>` in https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L58
You would need to patch the platform pom.xml or run something like `mvn clean install -Dquarkus.version=999-SNAPSHOT`

**Comment by jedla97** [comment]
Oh I miss this one! Thanks! with updated platform to 999-SNAPSHOT it's work even with platform.
