### ISSUE TITLE
ExceptionMapper not being called for WebApplicationException subclasses

### ISSUE THREAD

**Issue by tmulle** [quarkusio/quarkus#40965]
### Describe the bug

It appears that my custom exception mapper is not being called for anything other than throwing a raw `WebApplicationException`.

Trying to use `NotFoundException` or `BadRequestException` doesn't trigger it.

Is this by design? I didn't see anything in the docs.

Here is a simple reproducer. Start 2 windows, 1 for the app to run so you can see the output and another to use curl to hit it.

When you hit the endpoint `/hello/boom` you should see the stack trace print out in the console on the server.
When you hit the endpoint `/hello/boom2` you DON'T see the stack trace print, but I think it should right?
When you hit the endpoint `/hello/boom3` you DO see the stack trace print
When you hit the endpoint `/hello/boom4` you DON'T see the stack trace print, but I think it should right?

I tried different variations of the `NotFoundException` and `BadRequestException` with different parameters, but nothing triggered it.

Actually, if you use something like `BadRequestException("BOOM 3")` it triggers it.

So, it appears when using a `Response` object as a parameter, it doesn't work. 

Is using a Response object correct as a parameter? The Javadocs show it to be true.

https://github.com/tmulle/quarkus-exception-mapper-test

### Actual behavior

I would think I should see the exception mapper be trigger for ANY subclass of `WebApplicationException` ?

### Output of `java -version`

JDK 17

### Quarkus version or git rev

3.11

**Comment by geoand** [comment]
What you are seeing is the expected behavior based on the JAX-RS / Jakarta REST spec. 

Essentially when a `WebApplicationException` or one of the subclasses is thrown and it has an entity, no exception mapping takes place.
