### ISSUE TITLE
JMX inhibits quarkus fork join pool initialization

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#40977]
### Describe the bug

This relates to https://github.com/keycloak/keycloak/issues/30120 - after debugging it was clear that the JMX agent transitively was initializing the ForkJoinPool common pool (via smallrye common References ReaperThread) before quarkus got a chance to set the java.util.concurrent.ForkJoinPool.common.threadFactory system property. 

### Expected behavior

That the common pool is initialized as expected by quarkus.

### Actual behavior

Subsequent work submitted to common pool was not under a quarkus classloader, so usage of static Configuration methods did not work as expected.

### How to Reproduce?

- Start quarkus with with JMX enabled.
- Use the ForkJoinPool common pool to run code that is dependent upon the quarkus classloader

### Quarkus version or git rev

3.8.4

### Additional information

Our possible workaround is to take responsibility for setting and validating java.util.concurrent.ForkJoinPool.common.threadFactory https://github.com/keycloak/keycloak/pull/30149

**Comment by geoand** [comment]
I am not sure what we can do here because if you look at the generated main, 

```
System.setProperty("java.util.concurrent.ForkJoinPool.common.threadFactory", "io.quarkus.bootstrap.forkjoin.QuarkusForkJoinWorkerThreadFactory");
```

is one of the first things we do... 

Perhaps @dmlloyd has a trick up his sleeve :)

**Comment by shawkins** [comment]
@dmlloyd @geoand thanks for the confirmation that our workaround is valid. Feel free to close this if there's nothing more to be done.

**Comment by vmuzikar** [comment]
Would it make sense to mention this in Quarkus docs somewhere (that thread factory should be explicitly set and apps can't rely on Quarkus to do that)? From my perspective, it might be a bit sensitive issue – e.g. config options might not be correctly loaded when accessed from fork join thread.

**Comment by geoand** [comment]
We could, the problem is where to put that...

**Comment by geoand** [comment]
To me this sounds pretty obscure to be in such a generic guide - not to mention that someone trying to find info about the problem would be very unlikely to go looking there. 

Having said that, I really don't have any good candidates in mind... @gsmet any ideas?

**Comment by Sanne** [comment]
If we were to provide and optimised, j-linked JDK we could pre-bake all such properties in it.

And I happen to be working on that..

We would still want to document such things, but at least if we were to go in such a direction only a certain type of advanced integrators would need to know.
