### ISSUE TITLE
Better Error messages for invalid REST Client interface

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#4097]
**Description**
If I define a REST Client interface but forget to add the HTTP verb annotation, an exception is received that the method doesn't exist. It's not very intuitive as to what the issue is.

**Implementation ideas**
Provide a more meaningful error message when HTTP verb annotations are missing from an interface with `@RegisterRestClient` present.

**Comment by Erfankam** [comment]
Could I work on This?

**Comment by Erfankam** [comment]
How can I assign this issue to myself?

**Comment by geoand** [comment]
I am pretty sure this has since been addressed so I will close this
