### ISSUE TITLE
NamedQuery inside repository

### ISSUE THREAD

**Issue by akastyka** [quarkusio/quarkus#40987]
### Describe the bug

According to the documentation it is possible to define a @NamedQuery at entity's repository

_Named queries can only be defined inside your Jakarta Persistence entity classes (being the Panache entity class, or the repository parameterized type), or on one of its super classes._

(link https://quarkus.io/guides/hibernate-orm-panache#named-queries)

However it fails with  :

`io.quarkus.panache.common.exception.PanacheQueryException: The named query 'Test.update' must be defined on your JPA entity or one of its super classes`

### Expected behavior

`@NamedQuery` on top of repositories works in same way as at Entities

### Actual behavior

`@NamedQuery` on top of repositories fails with 

`o.quarkus.panache.common.exception.PanacheQueryException: The named query 'Test.update' must be defined on your JPA entity or one of its super classes`

### How to Reproduce?

Define `@Entity`, define its repository which implements `PanacheRepositoryBase<_Entity_, UUID>`, define `@NamedQuery` on top of repository.

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

**Comment by yrodiere** [comment]
I think this is just a documentation problem, right @FroMage?
I don't know how defining named queries on repositories would work, as those classes are not technically part of the persistence unit as far as Hibernate ORM is concerned.

**Comment by FroMage** [comment]
Looking at the processor code, it appears that indeed it's a documentation issue, we only look at named queries on the entities and their hierarchy.

**Comment by FroMage** [comment]
I think, perhaps, that "being the Panache entity class, or the repository parameterized type" means "the panache entity, or the type argument to the repository" but that's not clear at all, I'll delete that part.

**Comment by FroMage** [comment]
PR done https://github.com/quarkusio/quarkus/pull/41053

**Comment by akastyka** [comment]
Spring provides a possibility to specify queries inside repositories:

```
Using @Query
Using named queries to declare queries for entities is a valid approach and works fine for a small number of queries. As the queries themselves are tied to the Java method that runs them, you can actually bind them directly by using the Spring Data JPA @Query annotation rather than annotating them to the domain class. This frees the domain class from persistence specific information and co-locates the query to the repository interface.

Queries annotated to the query method take precedence over queries defined using @NamedQuery or named queries declared in orm.xml.
```

Would be good to have something similar in quarkus

**Comment by FroMage** [comment]
We are working on type-safe queries for Hibernate in Quarkus.
