### ISSUE TITLE
Params need double URL-safe-encoding for use with WebSocketConnector

### ISSUE THREAD

**Issue by wabrit** [quarkusio/quarkus#40981]
### Describe the bug

I've implemented a ws server endpoint using the `quarkus-websockets-next` extension and have written a test using `WebSocketConnector` and a suitable client endpoint class.

One param within my server URL requires safe encoding so I do something like the following:

```java
final WebSocketClientConnection connection = connector
        .baseUri(uri)
        .pathParam("param", URLEncoder.encode(paramValue))
        .connectAndAwait();
```

However that results in a URISyntaxException being thrown at the start of Http1xClientConnection.toWebSocket() as by that time the safe encoding has been removed.

I got round this by double-encoding the value, but I don't think that should be necessary; I think the issue is in the WebSocketConnectorImpl.connect() method:

```java
       URI serverEndpointUri;
        try {
====>>> At this point serverEndpoint contains the safe-encoded value <<<==========
            serverEndpointUri = new URI(serverEndpoint.toString());
        } catch (URISyntaxException e) {
            throw new WebSocketClientException(e);
        }

       WebSocketConnectOptions connectOptions = new WebSocketConnectOptions()
                .setSsl(serverEndpointUri.getScheme().equals("https"))
                .setHost(serverEndpointUri.getHost())
                .setPort(serverEndpointUri.getPort());
        StringBuilder uri = new StringBuilder();
        if (serverEndpointUri.getPath() != null) {
====>>> Calling serverEndpointUri.getPath removes the safe-encoding <<<==========
            uri.append(serverEndpointUri.getPath());
        }
```

### Expected behavior

It should only be necessary to safe-encode the param value at most once (preferably not all all)

### Actual behavior

It is necessary to double-safe-encode the param value for the test to pass

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 LAP1453 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 LTS OpenJDK Runtime Environment Zulu17.38+21-CA (build 17.0.5+8-LTS) OpenJDK 64-Bit Server VM Zulu17.38+21-CA (build 17.0.5+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by mkouba** [comment]
I think that we should also encode the param value by default.
