### ISSUE TITLE
Write down exception stack in reverse order in 500 error page

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4099]
Play had a nice feature where they showed the most nested cause exception text and stack first and then moved up the chain.
A lot of time, you want to see the nested one which has the most context.

**Comment by FroMage** [comment]
Didn't know of this feature, but yeah, it's nice.

**Comment by jaikiran** [comment]
@emmanuelbernard Does this look like what you had in mind https://github.com/quarkusio/quarkus/pull/4109?

**Comment by emmanuelbernard** [comment]
Turns out it wasn’t from play. They do something different. But I still
think it’s a good feature.

**Comment by emmanuelbernard** [comment]
gentle ping :)

**Comment by emmanuelbernard** [comment]
Got the same comment while driving a lab. Getting the first exception first is preferablr

**Comment by jaikiran** [comment]
Hello @emmanuelbernard, I will get back to this, this week.

**Comment by jaikiran** [comment]
@emmanuelbernard Here's a version which I think achieves what you wanted https://github.com/quarkusio/quarkus/pull/4904

**Comment by jaikiran** [comment]
FWIW, here's how it actually looks like, now that this has made into the release - this image https://user-images.githubusercontent.com/846671/68887904-afac7000-073b-11ea-8b7b-34bdad16f71b.png from https://github.com/quarkusio/quarkus/issues/5488
