### ISSUE TITLE
Make `quarkus.jacoco.title` defaults to `project.name`

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkus#40993]
### Description

Currently, when configuring `quarkus-jacoco` extension on a project and running tests, the report title is defined as the name of the first`@QuarkusTest` class.

It'd be nice if the title is defined as the name of the current project (POM.project.name, which internally defaults to POM.project.artifactId), similar to what is defined for `jacoco-maven-plugin`.

More info:
- https://www.eclemma.org/jacoco/trunk/doc/report-mojo.html#title
- https://stackoverflow.com/questions/78577433/how-to-set-jacoco-report-name-with-quarkus/78580315

### Implementation ideas

Current title:
- $NameClass (QuarkusTest)

Title suggestions:
- $POM.project.name (QuarkusTest)
- $POM.project.name
- quarkus.application.name
- quarkus.application.name (QuarkusTest)

**Comment by geoand** [comment]
Makes sense to me. Would you like to contribute this feature?

**Comment by gian1200** [comment]
Sure. By any chance do you know which files should be related to it, or where I can start looking?

**Comment by geoand** [comment]
I would start looking at https://github.com/quarkusio/quarkus/blob/404ff079199a2ad8a874d872ca962df902a60983/test-framework/jacoco/runtime/src/main/java/io/quarkus/jacoco/runtime/ReportCreator.java#L28

**Comment by gian1200** [comment]
I found `quarkus.application.name` (https://es.quarkus.io/guides/all-config#quarkus-core_quarkus-application-name)
> The name of the application. If not set, defaults to the name of the project (except for tests where it is not set at all).

Not sure why it has that description. It seems to work fine for testing, too (same value as `quarkus:dev` runtime)

Given the following `pom.xml` fragment:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.acme</groupId>
    <artifactId>code-with-quarkus-artifact</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>code-with-quarkus-name</name>
```

I tried the following and it worked
```properties
%test.quarkus.jacoco.title=${quarkus.application.name}
```
![image](https://github.com/quarkusio/quarkus/assets/405347/3ab65212-433d-4b41-94fb-ba22257abb12)

Original (without):
![image](https://github.com/quarkusio/quarkus/assets/405347/1405312b-c0dc-4666-bb74-f3413a4e1a29)

Also tried reading it's value at runtime (`quarkus:dev`) with `@ConfigProperty` and I got the same value (`POM.project.artifactId`). I'm not sure if that's expected or if it should be `POM.project.name` (maybe a separate issue?)


I was thinking about just updating `io.quarkus.jacoco.runtime.JacocoConfig`  (as well as the docs)

https://github.com/quarkusio/quarkus/blob/92226822eb0495fc0eae64b948b46f26667ee3e4/test-framework/jacoco/runtime/src/main/java/io/quarkus/jacoco/runtime/JacocoConfig.java#L55-L56
with
```java
@ConfigItem(defaultValue = "${quarkus.application.name}")
public Optional<String> title;
```

However, I'm currently unable to validate if it works or not.  As stated in https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#test-coverage, running `mvn install jacoco:report -Ptest-coverage` does generate the JaCoCo report, but it also sets a title.
