### ISSUE TITLE
Native build failing depends on snowflake-jdbc

### ISSUE THREAD

**Issue by ValentynaBondarenko** [quarkusio/quarkus#41017]
### Describe the bug

When trying to build a native image, I found an error that it is impossible with the snowflake-jdbc dependency

### Expected behavior

the build finishes successfully

### Actual behavior

build crashes on initialization
[1/8] Initializing...                                                                                    

### How to Reproduce?

A simple Quarkus project that is build natively when I add a 
```
<dependency>
   <groupId>net.snowflake</groupId>
   <artifactId>snowflake-jdbc</artifactId>
</dependency>
```
native build is failing

### Output of `uname -a` or `ver`

No response

### Output of `java -version`

21

### Quarkus version or git rev

3.10.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4

**Comment by geoand** [comment]
For this to work, someone would have to develop a `snowflake-jdbc` extension.
