### ISSUE TITLE
Allow quarkus.application.name to be overridden for Spring Cloud Config Server

### ISSUE THREAD

**Issue by thibaultmeyer** [quarkusio/quarkus#41011]
### Description

The ‘Spring Cloud Configuration’ extension uses the `quarkus.application.name` property to determine the configuration files to be loaded on the remote server. This works, but can lead to problems when there are multiple files to load. The property no longer corresponds to anything.

```
quarkus.application.name=common,dc1,my-application
quarkus.application.version=2.62.3

quarkus.spring-cloud-config.enabled=true
quarkus.spring-cloud-config.fail-fast=true
quarkus.spring-cloud-config.url=https://xxxxxx/spring-config-server/
```

In this example, the `quarkus.application.name` option loses its usefulness because the extension forces you to enter information that has nothing to do with the name of the application.

### Implementation ideas

It could be nice to implement a new property `quarkus.spring-cloud-config.names` (default value is `quarkus.application.name`)

**Example**
```
quarkus.application.name=my-application
quarkus.application.version=2.62.3

quarkus.spring-cloud-config.enabled=true
quarkus.spring-cloud-config.fail-fast=true
quarkus.spring-cloud-config.names=common,dc1,my-application
quarkus.spring-cloud-config.url=https://xxxxxx/spring-config-server/
```

**Comment by geoand** [comment]
Sounds interesting. 

Would you be willing to add this new feature?

**Comment by thibaultmeyer** [comment]
hi @geoand,

no problem, I'm looking into opening an enhancement PR.
