### ISSUE TITLE
OidcRedirectFilter behavior when the session cookie has expired and was removed

### ISSUE THREAD

**Issue by calvernaz** [quarkusio/quarkus#41015]
### Describe the bug

This issue is related with the new feature introduce in 3.11 https://github.com/quarkusio/quarkus/issues/40562 to allow session redirect paths when the session has expired.

Let's start with the happy path that I was able to reproduce constantly. 

1. The session expire date is about to expire and there is a in-flight request which by the time is evaluated [here](https://github.com/quarkusio/quarkus/blob/20d3c9d576d596ef3cdb90be7ce692afab63a7cb/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L319) will throw `TokenAutoRefreshException` and if there is a session expire path the redirect happens. The take away is, an in-flight request while the session is about to expire, which might happen in real live, but I don't think this should be the main use case. Again, I can reproduce this all the time by having a breakpoint that allows me to control the timings of this. **This is not a bug, this works as expected**

2. However, when the session was expired and there are no in-flight requests the request doesn't contain the cookie anymore, and therefore the code path is not the expected one, there is no tenant information. I could debug to [here](https://github.com/quarkusio/quarkus/blob/20d3c9d576d596ef3cdb90be7ce692afab63a7cb/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcAuthenticationMechanism.java#L53) where the `OidcTenantConfig` defaults to the default tenant and in the end returns a `401` unauthorized request, which is no different from the previous behaviour, especially for XHR requests, is hard to understand what's happening.

 

### Expected behavior

The expected behavior from my PoV should cover more than just in-flight requests but also when cookies have been deleted. I understand the challenge since there is no connection between the incoming request (no cookie) and the session.

### Actual behavior

The request completely bypasses the session redirect filter.

### How to Reproduce?

1. Configure IdP (e.g Keycloak) with access token lifespan and session idle timeout to 60secs. 
2. Login and check the cookie is valid for 1min.
3. Let the cookie expire and make a request (fetch API or whatever)
4. It will return a 401, instead of a redirect 302 response.

### Quarkus version or git rev

3.11

**Comment by sberyozkin** [comment]
@calvernaz, Hi, without the session cookie it is a unauthenticated user's request. But setting `quarkus.oidc.authentication.session-age-extension` to some large value exceeding any reasonable idle time,  8h, etc   will get the expired ID token back to Quarkus.
The more I think about it, the more I'm getting convinced this property must be set to a large value by default since the only role of this property is to make sure, the real session,  ID token, is returned back to Quarkus.

Also, the fact you are seeing 401 implies various tenant resolution strategies may need to be tuned. 

Let's discuss next week,  back from PTO on Tue

**Comment by calvernaz** [comment]
@sberyozkin your suggestion worked! After extending the session we can see the redirect and we have a flow we can rely and understand. I'll close this one since it works as expected after extending the session. Given is a new feature it might need some adjustments to the docs or the defaults to make it easier to developers.

Thanks!

**Comment by sberyozkin** [comment]
Hey @calvernaz Sounds good, I opened #41130 to track it further
