### ISSUE TITLE
LambdaIdentityProvider not called for resteasy handler when running in quarkus:dev mode.

### ISSUE THREAD

**Issue by anoppe** [quarkusio/quarkus#41026]
### Describe the bug

We've got a bunch of AWS Lambdas that we are refactoring to Quarkus resteasy. A custom `LambdaIdentityProvider` was introduced to customize the authentication logic and add some attributes to the `SecurityIdentity` that is injected into the lambda, and works as expected when deployed on AWS.

When running the Quarkus resteasy handler locally using `mvn quarkus:dev`, and doing an HTTP GET to `http://localhost:8080/v1/locations` with an valid `Authorization` header, results in errors in the handler. This happens because the expected customs attributes are missing in the `securityIdentity` object.

After debugging the call stack as much as possible, I found out that Quarkus (?) concludes that the request is 'anonymous', and selects the corresponding `AnonymousIdentityProvider` for the request. Which doesn't add the required attributes to the `SecurityIdentity`.

I'd expect that Quarkus detects the authentication header and uses the appropriate IdentityProvider.

### Expected behavior

The custom IdentityProvider is triggered for the request

### Actual behavior

The built-in `AnonymousIdentityProvider` is triggered instead.

### Output of `uname -a` or `ver`

```
Darwin ********.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64
```

### Output of `java -version`

```
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Homebrew (build 17.0.11+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.11+0, mixed mode, sharing)
```

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

IntelliJ 2024.2.1 Ultimate Edition bundled maven v3.9.6.

**Comment by patriot1burke** [comment]
The mock event server doesn't handle authentication right now.  You'll have to post a lambda http event directly to the mock server with the appropriate json for authentication within it.

https://quarkus.io/guides/aws-lambda-http#live-coding-and-simulating-aws-lambda-environment-locally

**Comment by anoppe** [comment]
Hi @patriot1burke Works like a charm, thanks!
