### ISSUE TITLE
Write an ADR explaining how clients should use the TLS registry 

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#41042]
### Description

See https://github.com/quarkusio/quarkus/pull/40990#discussion_r1629719466 to see the rationale.

So, we should use a named configuration for the clients. Otherwise, it will likely conflict with servers. Note that multiple clients (like the REST client and the mailer) may use the same TLS configuration - just not the default one.

Follow up from https://github.com/quarkusio/quarkus/pull/40990.

**Comment by geoand** [comment]
I would say the scope should be to explain how clients should use the registry, not just why they should not use the default one :)

**Comment by cescoffier** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/41126.
