### ISSUE TITLE
Implemented healthcheck in quarkus application using smallrye- /myapp/health-ui is not working on demo/Approval environment 

### ISSUE THREAD

**Issue by bondeamol94** [quarkusio/quarkus#41052]
### Describe the bug

Hello Team,

We're facing an issue with our health check implementation using the Smallrye dependency in our Quarkus application.

The problem arises when triggering the health check endpoint "https://app.amol.com/myapp/health-ui" using the Smallrye UI library. It automatically appends a "/" at the end of the URL (like "https://app.amol.com/myapp/health-ui/"), which doesn't match the Lua script in our ingress configuration. Unfortunately, we're unable to modify the ingress due to security policies prohibiting the addition of "/" or "*".

We suggested using "/myapp/health-ui/index.html", but this proposal was also rejected.

The relevant Lua script snippet causing the issue is as follows:

elseif ngx.var.request_uri:match("^/myapp/health%-ui$") ~= nil then

We urgently need a solution to bypass the addition of "/" to the URL or any other alternative approach. Your prompt assistance in resolving this matter would be greatly appreciated.

**Comment by phillip-kruger** [comment]
The URL needs to be in health-ui/ for relative links to work.
