### ISSUE TITLE
Reactive Messaging - Handle inheritance of mediators

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#4106]

**Comment by cescoffier** [comment]
@mkouba I will need your help on this one.

**Comment by mkouba** [comment]
@cescoffier this issue is a result of our discussion around TCK: https://github.com/quarkusio/quarkus/pull/4083#discussion_r326006667. I believe that a spec clarification would be useful. The behavior defined by Commons Annotations shouldn't be hard to implement, well except for generics...

**Comment by geoand** [comment]
Is there a good reason to keep this issue around or should we close it?

**Comment by cescoffier** [comment]
@geoand we can close it. IT's somewhat tracked by https://github.com/smallrye/smallrye-reactive-messaging/issues/17.

**Comment by geoand** [comment]
👍🏼
