### ISSUE TITLE
Vert.x Http: application/json MIME not compressed by default

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#41094]
### Describe the bug

As discovered in #40750

`application/json` and `application/xhtml+xml` MIMEs are not compressed by default.

See [HttpBuildTimeConfig.java](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpBuildTimeConfig.java#L97).

@mkouba, was there a specific reason for not including it? It seems in the log that you originated it in https://github.com/quarkusio/quarkus/commit/670a205d3870a517001a53006d46ac08c5cb5437

I left the default intact in #40750, merely documenting it.

### Expected behavior

Major MIME like `application/json` gets compressed.

### Quarkus version or git rev

3.8.4, main

**Comment by mkouba** [comment]
> `application/json` and `application/xhtml+xml` MIMEs are not compressed by default.

I can't remember any particular reason. We probably just wanted to keep the initial list small and nobody raised the hand so :shrug:.

Feel free to send a PR.

It would be kind of a breaking change so a note in the [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guides) would be needed.
