### ISSUE TITLE
Changing Accept Header in PreMatching filter isn't considered by MessageBodyWriter

### ISSUE THREAD

**Issue by myroch** [quarkusio/quarkus#41097]
### Describe the bug

#40019 fixed the routing to correct MessageBodyWriters in case that response is POJO. For JAX WS Response remains the old behavior.

### Expected behavior

Accept Header set in the pre-matching request filter shall decide which MessageBodyWriter will be selected, even if returned value is JAX WS Response.

### Actual behavior

Setting the Accept Header inside the pre-matching request filter doesn't affect which MessageBodyWriter is being selected in case that return type is JAX WS Response.

### How to Reproduce?

checkout https://github.com/myroch/quarkus-prematching-servermessagebodywriter-bug
run ExampleResourceTest

### Output of `java -version`

java 17.0.9 2023-10-17 LTS

### Quarkus version or git rev

3.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by geoand** [comment]
Thanks for reporting.

https://github.com/quarkusio/quarkus/pull/41111 takes care of it and should be backported to both 3,11 and 3.8 (the LTS release)
