### ISSUE TITLE
ProfileManager is 'almost' removed

### ISSUE THREAD

**Issue by mapuci** [quarkusio/quarkus#41092]
### Describe the bug

ProfileManager functionality was removed with 3.11, but the class still exists. 
Class should be deleted or at least marked as deprecated.

The migration guide clearly says, it is removed.
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.11
<img width="901" alt="image" src="https://github.com/quarkusio/quarkus/assets/20385863/40e4e2cc-5d05-464d-9608-1c83366d9005">

**Comment by radcortez** [comment]
Yes, it was probably an accident. I went on removing the methods first to make sure everything was ok, and the class remained. I'll remove it.

**Comment by radcortez** [comment]
Removed in https://github.com/quarkusio/quarkus/pull/41897.
