### ISSUE TITLE
RolesAllowed not working on inherited enpoints

### ISSUE THREAD

**Issue by paknecht** [quarkusio/quarkus#41119]
### Describe the bug

I have an interface where I define my resource:
```
@Path("/hello")
public interface GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    String hello();
}
```
and an implementation:
```
@Path("/hello")
public class GreetingResourceAdapter implements GreetingResource {

    public static final String TEST_ROLE = "TEST-ROLE";

    @Override
    @RolesAllowed({ TEST_ROLE })
    public String hello() {
        return "Hello from RESTEasy Reactive";
    }
}
```
And make sure that this config property is set `quarkus.security.jaxrs.deny-unannotated-endpoints=true` in order to get the `EagerSecurityHandler`.

When I now call this endpoint I always getting an HTTP 403 Response.
But if I move the `RolesAllowed({ TEST_ROLE })` to the interface everything works fine.

It worked fine before this change here:
https://github.com/quarkusio/quarkus/commit/37834cb44a0bc5101cdf60922c8dd0301efac822#diff-588500226d86bda61956c3a62f2ecb300f3666b48f3f172ec55bbf7a80469eeeL190

### Expected behavior

It shouldn't matter where the annotation is placed, the check should work in both scenarios. 

### How to Reproduce?

The reproducer has a test in it. 
[roles-allowed-reproducer.zip](https://github.com/user-attachments/files/15788274/roles-allowed-reproducer.zip)

### Output of `uname -a` or `ver`

Linux xxxxx 4.18.0-513.24.1.el8_9.x86_64 #1 SMP Thu Mar 14 14:20:09 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.23" 2024-04-16 LTS OpenJDK Runtime Environment (Red_Hat-11.0.23.0.9-2) (build 11.0.23+9-LTS) OpenJDK 64-Bit Server VM (Red_Hat-11.0.23.0.9-2) (build 11.0.23+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.8.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by michalvavrik** [comment]
> RolesAllowed not working on inherited enpoints

Just for context: It is working, but default JAX-RS security has priority. This issue is duplicate to https://github.com/quarkusio/quarkus/issues/39964. I agree this needs to be addressed.

**Comment by geoand** [comment]
Closing as a duplicate
