### ISSUE TITLE
Properly manage the order of Vert.x filters

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#4113]
Right now, the Vert.x filters are added in a totally unordered way.

This definitely won't work: we need to be able to order them properly.

@cescoffier I'm assigning this one to you for 0.24.0. It will definitely be needed for security + cors.

**Comment by cescoffier** [comment]
Great, thanks @gsmet. I will add this feature next week. I will be able to discuss with Stuart next week, do we sure to set up our filters "order" correctly.
