### ISSUE TITLE
Support for @Conditional Spring annotation

### ISSUE THREAD

**Issue by VBorikic** [quarkusio/quarkus#4114]
**Description**
I would like Quarkus to have support for @Condtional annotation. This would allow optional Bean initialization, when some conditions are met.

At the moment, `@Conditional` annotation is not recognized by Quarkus, my defined condition is not evaluated at all

**Comment by geoand** [comment]
Hi @VBorikic,

The trouble with `@Conditional` is that with a general `@Conditional` there could certainly be conditions that don't fit the everything evaluated at build time view of the world that Quarkus takes.

Would you like to elaborate on which specific `@Conditional` derivatives you would like to see and explain your use cases a little more?

Thanks

**Comment by VBorikic** [comment]
Hi @geoand,

For my use case evaluating based on application properties would be enough. (Similar like @ConditionalOnProperty SpringBoot annotation)

I would like to initialize a Bean only in some cases, which are controlled by an boolean application property

Thanks and Regards,
Vlada

**Comment by geoand** [comment]
Thanks for the information @VBorikic.

What you describe although useful in certain circumstances, kind of runs counter to the general Quarkus philosophy (and how Arc handles beans, @mkouba or @manovotn can confirm this) so I am not sure we will be bringing support for that.
It's definitely something worth looking into however.

**Comment by manovotn** [comment]
> and how Arc handles beans

That's true. What you describe is sort of like CDI alternatives but only enabled sometimes, which Arc doesn't have (in CDI you could use beans.xml to achieve that, but also in a slightly different way then you seek).

You could also make a CDI producer for that bean - from within the producer method, you are free to check the system property and based on that return some result. It can even be `null` if the producer is to return `@Dependent` beans.

**Comment by hantsy** [comment]
@geoand  Hope Quarkus provide a general similar mechanism to activate CDI beans by conditions.

**Comment by geoand** [comment]
A general @Condition type annotation seems out of the question because as explained above those conditions could change at runtime, breaking the "everything known at build time" philosophy of Quarkus.

That said, I am sure we can provide some types of conditional support (Quarkus already has the @DefaultBean annotation which is similar to Spring Boot's @ConditionalOnMissingBean)

**Comment by mkouba** [comment]
@geoand is right. We can't build the "exlude conditions" based on runtime configuration (system properties and ENV variables). It could be useful to have a possibility to "exclude" a bean class based on the presence/absence of a certain class, ie. something like `@Exclude(ifClassNotAvailable = "org.acme.Foo")`. The downside of this approach is that it's not type-safe...

**Comment by geoand** [comment]
@mkouba we should probably have a discussion when we have time about how to approach such conditional beans in Quarkus.

**Comment by ebullient** [comment]
I think we can get some help with thinking about this. Re: conditional beans, we'd need some choices made at compile time that can help constrain evaluation of conditionals at runtime (and possibly provide some help for Spring devs to flag behaviors that won't be possible at runtime when built this way).

**Comment by josephearl** [comment]
I’d like something like this to conditionally enable JAX RS resources based on a property set from an environment variable.

**Comment by geoand** [comment]
You can already do this with https://quarkus.io/guides/cdi-reference#enable_build_properties

**Comment by josephearl** [comment]
@geoand I did read that but the docs said

> Properties set at runtime have absolutely no effect on the bean resolution using @IfBuildProperty.

which made me think this wouldn’t work for me since value of the property is an environment variable which is defined at runtime but not at build time?

**Comment by mkouba** [comment]
> which made me think this wouldn’t work for me since value of the property is an environment variable which is defined at runtime but not at build time?

Yes, this would not work. The set of components is set in stone at build time, i.e. you can't add/remove anything at runtime.

**Comment by geoand** [comment]
> The set of components is set in stone at build time

I should add that this is a core tenet of the Quarkus architecture and not something we are willing to compromise on

**Comment by josephearl** [comment]
In my case the use case is having the same container image deployed to multiple OpenShift namespaces/environments and wanting to toggle/disable some JAX RS resources in some environments (e.g. only enable a particular resource in a test environment).

**Comment by geoand** [comment]
Understood, there are certainly cases where are build time resolution of everything makes things a little more difficult, but it's a core part of what makes Quarkus more effective than other runtimes / frameworks.

**Comment by geoand** [comment]
@hantsy thanks for the info.

But I don't see how it applies to this use case.

**Comment by hantsy** [comment]
CDI Lite also introduce build-time feature. Eclipse Open DI includes an implementation of Micronaut. https://projects.eclipse.org/projects/ee4j.odi

**Comment by geoand** [comment]
I am actually going to close this issue, as providing a general `@Conditional` style annotation is not something we are going to do.

**Comment by mkouba** [comment]
> @geoand Micronaut includes a `@Requires` to compute the condition of creating a bean and Micronaut also handle bean definitions, DI, validation at **build time**.

Yes, but it seems that you can't use `@Requires` for the use case mentioned by @josephearl, i.e. disable a component at runtime via an environment variable.
