### ISSUE TITLE
Move the classes from quarkus-vertx-utils to Vert.x

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#41150]
### Description

https://github.com/quarkusio/quarkus/pull/40995 added a new independent module called [quarkus-vertx-utils](https://github.com/quarkusio/quarkus/tree/main/independent-projects/vertx-utils). The classes there depend solely on `vertx-core` and `vertx-web`. Thus, the classes could get moved to Vert.x.

**Comment by ppalaga** [comment]
@vietj could you please throw a quick look at the classes in https://github.com/quarkusio/quarkus/tree/main/independent-projects/vertx-utils/src/main/java/io/quarkus/vertx/utils and say whether the move is feasible at all and which Vert.x module/package should the classes go to? I can prepare a PR as soon as you ack the plan.

**Comment by cescoffier** [comment]
I would keep them here right now. These classes would go in Vert.x Core, and with Vert.x 5 being developed right now, it might not be very sustainable (these classes may need to be updated for Vert.x 5 - well, actually for sure :-)).

**Comment by cescoffier** [comment]
Closing - we will reconsider after Vert.x 5.
