### ISSUE TITLE
default datasource health check is up, without any url configured

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#41151]
### Describe the bug

The health check for the default datasource shows an `UP` status, without any url being configured.

### Expected behavior

The application should fail to start, since the datasource is not configured correctly

### Actual behavior

The health check for the default datasource shows an `UP` status

### How to Reproduce?

Reproducer:
- clone https://github.com/turing85/quarkus-camel-local-transactions
  ```bash
  git clone https://github.com/turing85/quarkus-camel-local-transactions.git
  cd quarkus-camel-local-transactions
  ```
- look at the [`application.properties`](https://github.com/turing85/quarkus-camel-local-transactions/blob/main/src/main/resources/application.properties) and verify that no database url is configured
- build the application:
  ```bash
  ./mvnw --define skipTests clean package
  ```
- run the application:
  ```bash
  QUARKUS_ARTEMIS_URL=tcp://localhost:5432 java -jar target/quarkus-app/quarkus-run.jar
  ```
- access http://localhost:8080/q/health
- notice that the health check for the database is up:
  ```json
  {
    ...
    "checks": [
      ...
      {
        "name": "Database connections health check",
        "status": "UP",
        "data": {
          "<default>": "UP"
        }
      },
      ...
    ]
  }
  ```

### Output of `uname -a` or `ver`

Linux xxx 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 21.0.2 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

**Comment by geoand** [comment]
Is this different than #41152?

**Comment by turing85** [comment]
uh... yeah... it is... how did this duplicate?

**Comment by geoand** [comment]
Stuff happens :)
