### ISSUE TITLE
Investigate SharedOpenArchivePathTree users counting

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#41158]
I was having a look at a dump provided by @brunobat and I saw quite a lot of:

![Screenshot from 2024-06-12 14-20-40](https://github.com/quarkusio/quarkus/assets/1279749/bb14313f-824b-4241-8b0c-4702fad1224a)

I had a look at the code of `SharedOpenArchivePathTree` here: https://github.com/quarkusio/quarkus/blob/3c6e8f9962e5c2d5c29f52458a10c2abe19afae5/independent-projects/bootstrap/app-model/src/main/java/io/quarkus/paths/SharedArchivePathTree.java#L68-L110 .

And I found something a bit suspicious as to how the `users` are counted:

- We initialize `users` at `1`
- We increment it in the constructor
- We also increment it on every `acquire()`
- When closing, we check if `decrementAndGet()` is `0`

Let's take a very simple example of me just creating an instance of `SharedOpenArchivePathTree` and closing it right away:

- `users` will be `2` after the constructor call
- when closing and decrementing it, it will be `1` and will not be closed

Now I might have missed something obvious but in that case, a comment in the code would probably be welcome.

**Comment by gsmet** [comment]
OK, so I missed the obvious, in the constructor, it's incrementing `openCount` that is another `AtomicInteger` in the enclosing class.

I'm having a further look and I see some instances that have `users` to `0` but still have the fs open, which is odd.

**Comment by gsmet** [comment]
So actually, the `ZipFileSystem` `fs` is closed but... even closed it keeps the `cen` around so that doesn't reduce the memory usage.

**Comment by Sanne** [comment]
> So actually, the `ZipFileSystem` `fs` is closed but... even closed it keeps the `cen` around so that doesn't reduce the memory usage.

Right, the references to any ZipFileSystem need to be released aggressively. Good catch!
