### ISSUE TITLE
Make vertx-web handleFileUploads, uploadsDirectory, bodyLimit. etc. configurable 

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#4115]
The proposed options translate to the fields of `io.vertx.ext.web.handler.impl.BodyHandlerImpl`. I am primarily interested in the `uploadsDirectory` because when running integration tests, the default directory `file-uploads` is created under the root directory of the current Maven project instead of under `target`.

**Implementation ideas**

It seems to be easy to implement in `io.quarkus.vertx.web.runtime.VertxWebRecorder.addRoute(Router, Handler<RoutingContext>, Route, List<Handler<RoutingContext>>, HttpConfiguration)` where the `BodyHandler` is created. 
The only thing unclear to me is whether the new options should be added to a new `VertxWebRuntimeConfiguration` or if it is OK to add them to the existing `io.quarkus.vertx.http.runtime.HttpConfiguration`?

**Comment by gastaldi** [comment]
I think it would make sense to add to `HttpConfiguration` as a new set of properties.

**Comment by gastaldi** [comment]
And it looks like those options could be set here: https://github.com/quarkusio/quarkus/blob/5b5907093e56f38e964eb5d7d3e42df8694bcece/extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/VertxWebRecorder.java#L87

**Comment by ppalaga** [comment]
Thanks @gastaldi . I can prepare a patch. Feel free to assign to me.

**Comment by machi1990** [comment]
I think body limit is currently supported. See: 

 https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/VertxWebRecorder.java#L81-L87

And 
https://github.com/quarkusio/quarkus/blob/master/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java#L319-L323

for the undertow part.

**Comment by cescoffier** [comment]
Configuration should be in the quarkus "http" config (as well as cache).
