### ISSUE TITLE
Running Quarkus CLI rewrites gradle.properties

### ISSUE THREAD

**Issue by rodcheater** [quarkusio/quarkus#41182]
### Describe the bug

Running the Quarkus CLI to add an extension reorders the properties in `gradle.properties`. It also adds a timestamp. This is quite hostile to version control.

### Expected behavior

The file is not changed if no changes are required. If changes are required existing properties are not reordered and comments are not removed. No timestamp is added.

### Actual behavior

The properties are reordered and a timestamp is added.

### How to Reproduce?

Steps to reproduce

1. Create a Quarkus app with Gradle support: `quarkus create app --gradle && cd code-with-quarkus`
2. View `gradle.properties`.
3. Add an extension, e.g.: `quarkus extension add io.quarkus:quarkus-kotlin`
4. View `gradle.properties` again and note the changes.

### Output of `uname -a` or `ver`

Darwin Rods-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment Homebrew (build 21.0.2) OpenJDK 64-Bit Server VM Homebrew (build 21.0.2, mixed mode, sharing)

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

**Comment by maxandersen** [comment]
I can confirm this happens, example: 

before:

```
#Gradle properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.8.4
quarkusPlatformGroupId=com.redhat.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.8.4.SP2-redhat-00001
```

after:

```
#Gradle properties
#Mon Jul 08 11:27:08 CEST 2024
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformGroupId=com.redhat.quarkus.platform
quarkusPlatformVersion=3.8.4.SP2-redhat-00001
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.8.4
```

I don't know if that has always happed or not but the fact that there is zero changes in the actual content should alone mean we don't have to regenerate that file.

@aloubyansky @gastaldi is this something that changed or always been like this?

**Comment by gastaldi** [comment]
> @aloubyansky @gastaldi is this something that changed or always been like this?

That seems to have always been like this.

The calls to `getModel().getRootPropertiesContent().store(out, "Gradle properties");` in https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/buildfile/AbstractGradleBuildFile.java exist since 2020

**Comment by maxandersen** [comment]
@gastaldi gotcha - in that place we could at least read and compare the key/values to avoid re-generating.

or possibly even use something like https://github.com/codejive/java-properties which jbang uses to avoid exactly this issue.
