### ISSUE TITLE
quarkus-amazon-lambda-http: can't build a Fast-JAR

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#41234]
### Describe the bug

This has already been registered with quarkiverse but I have been asked to submit it again here (https://github.com/quarkiverse/quarkus-amazon-services/issues/1298).

With Quarkus 3.11, trying to perform a build containing a dependency to the `quarkus-amazon-lambda-http` extension, systematically creates a thin JAR instead of a fast one.

### Expected behavior

A Fast-JAR is expected to be built, as it's the case of all other builds not having dependencies on `quarkus-amazon-lambda-http` extension.

### Actual behavior

A thin JAR is built instead of a fast one, even if the option `-Dquarkus.package.jar.type=fast-jar` is used.

### How to Reproduce?

To reproduce:

    $ git clone https://github.com/nicolasduminil/quarkus-test-case.git
    $ cd quarkus-test-case
    $ mvn package

The following message will appear in the log file:

    [INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /home/nicolas/quarkus-test-case/target/quarkus-test-case-runner.jar

Now comment out the following in the pom.xml file:

    

and build again:

    $ mvn clean package

The following message will be logged:

    [INFO] --- quarkus:3.11.0:build (default) @ quarkus-test-case ---

In conclusion, without the `quarkus-amazon-lambda-http` extension, the Fats-JAR is generated, as expected, however as soon as this dependency is added, only a thin JAR is generated, even if the `-Dquarkus.package.jar.type=fast-jar` option is used.

How could I avoid this behavior ? Many thanks in advance for your help.

Nicolas

### Output of `uname -a` or `ver`

Linux P15s-Gen-2i 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

### Quarkus version or git rev

3.11

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /usr/share/apache-maven-3.9.6 Java version: 21.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21-oracle-x64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-112-generic", arch: "amd64", family: "unix"

### Additional information

None

**Comment by maxandersen** [comment]
Just to be clear - this is not new for 3.11, right ? Just then version you used?

The defaulting of this is deliberate as at the time no other option works with Amazon lambdas afaik. 
Not sure if things changed since then? Do you have a usecase where you need it ?

Cc @patriot1burke

**Comment by patriot1burke** [comment]
the lambda extension forces a thin jar because fast jar does not work on deployed lambdas....at least it didn't a few years ago.

**Comment by nicolasduminil** [comment]
@maxandersen : yes, 3.11 is the release I'm using and I ignore whether it's new for 3.11, it seems it isn't.

And yes, I have an use case: a script which deploys a CDK app with a Lambda construct inside and this lambda's body is a Quarkus service. This Quarkus service is variable and it is started via the `cdk.json` file as follows:

    "app": "java -jar target/quarkus-app/quarkus-run.jar"

but now, if the Quarkus service has dependencies on `quarkus-amazon-lambda-http`, this same line should be:

    "app": "java -jar target/quarkus-s3-runner.jar"

and it's difficult to deal with these two cases in the script.

But if this the only way that it works ...

**Comment by nicolasduminil** [comment]
@patriot1burke : any chance that it works now ? Is it worth trying ?

**Comment by patriot1burke** [comment]
I don't think it will work, but you can try it.  Lambda runtime loads the quarkus jar in its own way into it's own JVM.  For lambda, Quarkus has to be initialized within the lambda too, so main isn't called either.
