### ISSUE TITLE
Liquibase fails when changelog file is not the default resource path

### ISSUE THREAD

**Issue by murilo-develop** [quarkusio/quarkus#41236]
### Describe the bug

When I try to build a native app which uses Liquibase and the changelog file path is not the default the build fails.

### Expected behavior

Native app successfully built.

### Actual behavior

The build process fails with a message:

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.11.2:build (default) on project liquibase-quickstart: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.liquibase.deployment.LiquibaseProcessor#nativeImageConfiguration threw an exception: java.lang.IllegalStateException: liquibase.exception.ChangeLogParseException: The file local/changeLog.xml was not found in the configured search path:
```

### How to Reproduce?

[liquibase-quickstart.zip](https://github.com/user-attachments/files/15859145/liquibase-quickstart.zip)

1. Download the liquibase-quickstart.zip.
2. Unzip it where is most convenient for you.
3. Go to the folder created.
4. Open a terminal from there.
5. Run the command, "./mvnw clean install" (it should run with no errors)
6. Build a native image using the command, "./mvnw clean package -Dnative"

### Output of `uname -a` or `ver`

Linux L-PW03AH72 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

Picked up JAVA_TOOL_OPTIONS: -Dos.version=arch openjdk version "17.0.5" 2022-10-18 LTS OpenJDK Runtime Environment Zulu17.38+21-CA (build 17.0.5+8-LTS) OpenJDK 64-Bit Server VM Zulu17.38+21-CA (build 17.0.5+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

I also tried to add additional resource files through the property "quarkus.native.resources.includes". For instance, "quarkus.native.resources.includes=db/changelog/**". But it also did not work.

However, when I created the file "src/main/resources/local/changeLog.xml" and removed the quarkus property, "quarkus.liquibase.search-path=db/changelog", it worked.

Furthermore, if I let the quarkus's property,"quarkus.liquibase.search-path=db/changelog", in the application.properties file it finds twice the same file and fail.

Therefore, I hope to have the same behavior, once set the quarkus.liquibase.search-path it should be handled in the same way no matter the sort of the build.

**Comment by geoand** [comment]
It seems that `quarkus.liquibase.search-path` seems to not be taked into account at build time. 
@juanjogv as you added this feature, mind taking a look?

Thanks

**Comment by juanjogv** [comment]
@murilo-develop  when you say 

> When I try to build a native app which uses Liquibase and the changelog file path is not the default the build fails.

as the error shows your change log file name is "changeLog.xml" but is located in a directory named "local", right? the "local" directory is in the classpath or where is it?

**Comment by geoand** [comment]
It's part of the file system - the attached sample perfectly reproduces the problem being described

**Comment by juanjogv** [comment]
understood, when I have some time I will take a look at it.

**Comment by geoand** [comment]
Thanks a lot!

**Comment by juanjogv** [comment]
@geoand I have just made the adjustment is on this [PR](https://github.com/quarkusio/quarkus/pull/41530)

**Comment by geoand** [comment]
Thanks!
