### ISSUE TITLE
MP-Configuration: Environment variables not resolved in prod mode

### ISSUE THREAD

**Issue by HeavyTobi** [quarkusio/quarkus#4123]
**Describe the bug**
I am trying to configure the REST client base url using the application.properties, which is working 

**Expected behavior**
If no environment variable called SERVICE_URL is set, a default value should be used as URL, if it is set, it should use the env variable. 

**Actual behavior**
the application is not even resolving the expression in the application.properties file when using the jar file generated with the quarkusBuild task. But works fine in QuarkusDev.

Same issue when using Windows and Linux

**To Reproduce**
1. Create a quarkus project with gradle as build tool
2. Implement an example REST Client as described on official quarkus docs
3. in application.properties replace the given url with ${SERVICE_URL;http://example-api.com}
4. set the environment variable SERVICE_URL using export SERVICE_URL=http://some-other-api.com
5. Try with quarkusDev and quarkusBuild

**Configuration**
```properties
com.somecompany.test.service.CamundaService/mp-rest/url=${CAMUNDA_URL:http://localhost:6060}
%prod.com.somecompany.test.service.CamundaService/mp-rest/url=${CAMUNDA_URL:http://localhost:6060}
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment [Windows] (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18362.356]
 - Output of `java -version`: openjdk version "11" 2018-09-25
 - GraalVM version (if different from Java): not used
 - Quarkus version or git rev: 0.22.0

**Environment [WSL] (please complete the following information):**
 - Output of `uname -a` or `ver`:  4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.4" 2019-07-16
 - GraalVM version (if different from Java): not used
 - Quarkus version or git rev: 0.22.0

**Additional context**
using gradle as build tool

**Comment by geoand** [comment]
I tried the general idea with the a modified version of the `application-configuration` [quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/application-configuration) (basically setting the value `greeting.message` to `${ENV_GREETING:hello}`) and things worked as expected.
I remember this working because I had added a SO [answer](https://stackoverflow.com/a/55806466/2504224) about it.

Then I also tried with the REST-Client and indeed I could reproduce the problem you mention.

**Comment by geoand** [comment]
@dmlloyd I looks like the `ExpandingConfigSource` is not used at runtime so when an attempt is made to pull a property value from `Config`, it never gets expanded.
Is there any reason we can't use `ExpandingConfigSource` for the in-jar properties?

**Comment by dmlloyd** [comment]
> @dmlloyd I looks like the `ExpandingConfigSource` is not used at runtime so when an attempt is made to pull a property value from `Config`, it never gets expanded.

If not it's a bug.  We definitely should be adding the expander to all config sources.

That said it might not be worth fixing right now because (apart from the config work I'm already doing which would definitely conflict) I expect MP-config and thus SmallRye Config to formally support property expansion sometime in the next few weeks.

**Comment by geoand** [comment]
Nice! I think then it makes sense to wait.

**Comment by HeavyTobi** [comment]
I can't wait because of an important project. I need at least a workaround. I tried to place an application.properties in the config directory under the workdir but it is not working also. Any alternatives?

**Comment by geoand** [comment]
You can place `application.properties` in a directory named `config` which resides in the directory where you launch the process. Would that cover your needs temporarily?

**Comment by HeavyTobi** [comment]
@geoand I already tried that... sadly doesn't work..

**Comment by geoand** [comment]
@HeavyTobi doesn't work how? I have done that multiple times and it does work:

For example if I have:

```
/deployments/some-app.jar
/deployments/config/application.properties
```

and I launch the application from inside `/deployments` like so:

```
java -jar some-app.jar
```

then the (runtime) properties defined in `config/application.properties` will override the values of the `application.properties` file that is included inside the jar.

**Comment by kenfinnigan** [comment]
Can you try with 0.27, as there was an issue where Rest Client properties weren't respecting the config profiles, which is now resolved
