### ISSUE TITLE
"Failed to inject extension deployment dependencies: zip END header not found" error should mention the corrupt jar in my local maven repo

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#4126]
I managed to sync maven in intellij at the same time as running "mvn" on the command line.
So one of my jars got corrupted. No idea which one (I am still trying to figure out which one).

When I run "mvn quarkus:dev" now, it doesn't tell me which one:

```
[INFO] --- quarkus-maven-plugin:0.22.0:dev (default-cli) @ optaplanner-quarkus-example ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.22.0:dev (default-cli) on project optaplanner-quarkus-example: Failed to run: Failed to resolve Quarkus application model: Failed to inject extension deployment dependencies for org.optaplanner:optaplanner-quarkus-example:jar:7.28.0-SNAPSHOT: zip END header not found -> [Help 1]
...
```

**The Quarkus exception should include the name of the broken zip file (= corrupted jar file in my maven repo).** This messes up the getting started experience.

Stacktraces (mvn -e):
https://gist.github.com/ge0ffrey/1c1483b8508790aefeeda29580eeb20c

**Comment by ge0ffrey** [comment]
**WORKAROUND**

1. Run "mvn quarkus:dev -e" and put a breakpoint on the ZipFileSsystem line that throws the error.
2. Run `mvnDebug quarkus:dev -Ddebug` (note that `mvn quarkus:dev -Ddebug` is not enough).
3. Connect with a remote debugger on port 8000 (=non standard port)
4. Wait for breakpoint, in Frames, look at the "this" var of 1 call up in the stacktrace. It will mention the corrupted jar name.

**Comment by gsmet** [comment]
Looks like a good opportunity for a first contribution :).

**Comment by jaikiran** [comment]
I have created a PR with a potential fix for this https://github.com/quarkusio/quarkus/pull/4145
