### ISSUE TITLE
WebSockets Next - client: document TLS registry configuration

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#41279]
This is a follow-up of https://github.com/quarkusio/quarkus/issues/41004 and https://github.com/quarkusio/quarkus/pull/41095.

This issue is related to https://github.com/quarkusio/quarkus/issues/41280.

**Comment by geoand** [comment]
Didn't we already do this one?

**Comment by mkouba** [comment]
> Didn't we already do this one?

I don't see anything in the ref guide: https://quarkus.io/version/main/guides/websockets-next-reference :shrug:

**Comment by geoand** [comment]
I'll have to check
