### ISSUE TITLE
[Extension Proposal] Quarkus Data Files

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#41286]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

It should allow to declare yml/json files in a src/main/resources/data
They will be accessible through CDI
And we should allow to have strongly typed (record) either generated or manually implemented a bit like entities in panache

### Repository name

quarkus-data-files

### Short description

Allow to inject yml/json files and use their content in services or templates.

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-data-files/dev/

### Repository Topics

- quarkus-extension
- data
- file
- json
- yaml
- yml
- statiq

### Team Members

- ia3andy
- mkouba
- melloware
- mcruzdev

### Additional context

This has been discussed on zulip: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/statiq

**Comment by gastaldi** [comment]
According to the diacussion in Zulip, this will be developed under https://github.com/quarkiverse/quarkus-statiq
