### ISSUE TITLE
OTEL eventbus context

### ISSUE THREAD

**Issue by appiepollo14** [quarkusio/quarkus#41290]
### Describe the bug

When using the vertx eventbus in combination with the quarkus opentelemetry extension, all context is lost within the eventConsumer. I'm not sure wether this should work, but looking at [this code](https://github.com/quarkusio/quarkus/blob/50372634952488c3249f0f3bc4982792653cfd9f/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/EventBusInstrumenterVertxTracer.java), I would expect so. So please either help me with a sample implementation on how to use the OTEL context through the eventbus or fix the issue. 

I've made a [reproducer](https://github.com/appiepollo14/quarkus-reproducer/tree/c65b3b6fc33543faec3095bbbbecb7d250012b40). You can see the system output with the context in the `@EventConsumer` method to be empty.

### Expected behavior

I expect the OTEL context to be passed into the Vertx eventbus to be used in the eventconsumer method.

### Actual behavior

The OTEL context is empty.

### Output of `uname -a` or `ver`

Darwin xxx.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

### Quarkus version or git rev

3.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.6

**Comment by appiepollo14** [comment]
In addition, might be related, why is the current context in [this line](https://github.com/appiepollo14/quarkus-reproducer/blob/eventbus-otel/src/main/java/nl/appiepollo14/Blabla.java#L24), empty?

**Comment by brunobat** [comment]
As far as I can tell you need to use the Mutiny EventBus for this, because of the context propagation.

Please see test for the `EventBusInstrumenterVertxTracer`:
https://github.com/quarkusio/quarkus/blob/ebee0a4b66d1b4dba9c51165e78d22fbf3b90d3e/integration-tests/opentelemetry-vertx/src/main/java/io/quarkus/it/opentelemetry/vertx/HelloRouter.java#L24
and here:
https://github.com/quarkusio/quarkus/blob/fb79c7c22ee746c904a95199390e295865024f73/integration-tests/opentelemetry-vertx/src/test/java/io/quarkus/it/opentelemetry/vertx/HelloRouterTest.java#L110

**Comment by appiepollo14** [comment]
Thanks @brunobat 
Even with the mutiny eventbus, I still get no context passed through the eventbus IMO. See [this reproducer](https://github.com/appiepollo14/quarkus-reproducer/tree/eventbus-otel-mutiny). 

Still an issue due to misuse or is this a bug?

**Comment by brunobat** [comment]
I'm not sure what you are trying to do on the reproducer. Can you please start with the example we have in the tests?

**Comment by cescoffier** [comment]
The event bus does not propagate the context. This is done on purpose as the event bus can be distributed. 

I have been thinking whether it would be possible to pass the duplicated context in some cases, but the 'publish' (broadcasting of event) would lead to potential racy access to the context. 

Thus, there is no duplicated context right now when using the event bus.

Other solution like CDI events should work.

**Comment by brunobat** [comment]
Thanks @cescoffier.
In the case of distributed systems it could be possible to use header propagation (no need to store OTel context) to create links and not parent-child relationships. I imagine that a particular message might be received in multiple consumers...

**Comment by cescoffier** [comment]
Yes, that should be possible. The event bus does not have interceptors so it would be something manual.
