### ISSUE TITLE
Upgrade `ubi8/openjdk-VERSION:1:19` -> `ubi8/openjdk-VERSION:1:20`

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#41322]
### Description

[ubi8/openjdk-VERSION:1:20](https://catalog.redhat.com/software/containers/ubi8/openjdk-21/653fb7e21b2ec10f7dfc10d0?architecture=amd64&image=6661ff8e8d86ed30a8ce90ae) is available.

Please upgrade e.g. https://github.com/quarkusio/quarkus/blob/3.11.3/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/Dockerfile-layout.include.qute

**Comment by mschorsch** [comment]
> Red Hat strongly recommends updating to the newest image version [1.20-3](https://catalog.redhat.com/software/containers/ubi8/openjdk-21/653fb7e21b2ec10f7dfc10d0?image=6661ff8e8d86ed30a8ce90ae&architecture=amd64) unless otherwise defined by the support policy of [Red Hat](https://access.redhat.com/support).

**Comment by mschorsch** [comment]
@gastaldi

**Comment by gsmet** [comment]
PR welcome :)

You can use previous PRs as a base. For instance: https://github.com/quarkusio/quarkus/pull/40537 .

A search replace then compare to the previous PR is probably the best way to go.
