### ISSUE TITLE
Unable to build the codebase with mvnd 1.0.0

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#41323]
### Describe the bug

I'm unable to build this codebase with mvnd 1.0.0. I tried the latest main ed77ee257d5

Motivation: https://quarkus.io/blog/quarkus-3-11-3-released/ says there is compatibility with mvnd 1.0.0

Quarkus codebase builds well when using mvnd 1.0-m8-m39

mvnd 1.0.0 build fails with this error:
```
mvnd clean install -Dquickly -Prelocations  -Dno-test-modules
...
[ERROR] Failed to execute goal de.thetaphi:forbiddenapis:3.4:check (verify-forbidden-apis) on project 
  resteasy-reactive-common-processor: IO problem while reading files with API signatures.:
  /Users/rsvoboda/git/quarkus/independent-projects/resteasy-reactive/common/processor
  /${maven.multiModuleProjectDirectory}/.forbiddenapis/banned-signatures-common.txt
   (No such file or directory) -> [Help 1]
```

### Expected behavior

Compilation of Quarkus main works without any error

### Actual behavior

Compilation of Quarkus main works fails with `[ERROR] Failed to execute goal de.thetaphi:forbiddenapis:3.4:check ...` error

### How to Reproduce?

```
sdk use mvnd 1.0.0
sdk use maven 3.9.8
mvnd clean install -Dquickly -Prelocations  -Dno-test-modules
```

```
mvnd -version
Apache Maven Daemon (mvnd) 1.0.0 darwin-aarch64 native client (0cb7cbcbed6fad010b14dcd05acdc0a59685d88d)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jni.osx.OsXNativePty
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /Users/rsvoboda/.sdkman/candidates/mvnd/1.0.0/mvn
Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: /Users/rsvoboda/.sdkman/candidates/java/21.0.2-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "14.5", arch: "aarch64", family: "mac"
```

### Output of `uname -a` or `ver`

macOS 14.5 Sonoma

### Output of `java -version`

Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: /Users/rsvoboda/.sdkman/candidates/java/21.0.2-tem

### Quarkus version or git rev

ed77ee257d5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnd 1.0.0

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by rsvoboda** [comment]
Maybe @ppalaga could have a look too?

**Comment by ppalaga** [comment]
`maven.multiModuleProjectDirectory` does not exist anymore with mvnd 1.0.0. I have not seen any good solution yet.

**Comment by rsvoboda** [comment]
Nice trick with `.mvn/maven.config` @manofthepeace / @gsmet. I can confirm this issues is fixed.
