### ISSUE TITLE
quarkus.rest-client.*.uri overrides almost all REST client URI configuration options

### ISSUE THREAD

**Issue by martinoneutrino** [quarkusio/quarkus#41367]
### Describe the bug

When the (literal) property `quarkus.rest-client.*.uri` is set, the only way to use a different URI for a `RestClient` is to use the fully qualified class name in the `quarkus.rest-client."fully.qualfied.class.name".uri` property.

Setting the same property using the `RegisterRestClient`'s `configKey` value (eg. `quarkus.rest-client."configkeyvalue".uri`) has no effect, neither does the `RegisterRestClient`'s `baseUri`.

### Expected behavior

The property that uses the `RegisterRestClient`'s `configKey` value (eg. `quarkus.rest-client."configkeyvalue".uri`) should take precedence over the default value.

### Actual behavior

The only way to use a different URI for a `RestClient` is to use the fully qualified class name in the `quarkus.rest-client."fully.qualfied.class.name".uri` property.

### How to Reproduce?

1. Checkout and build sample project `openapi-swaggerui-quickstart` committed at https://github.com/martinoneutrino/quarkus-quickstarts/tree/Default-URI-precedence-issue.
2. Send a GET request to localhost:8080/fruits
3. Incorrect behaviour: throws an exception (due to invalid domain in URI)
4. Correct behaviour: API request completes

Enable/disable the config values `quarkus.rest-client.____.uri` in `application.properties` to see different behaviour.

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18

### Quarkus version or git rev

3.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2

**Comment by geoand** [comment]
I am not aware of `quarkus.rest-client.*.uri` being a supported property. Do you see that being mentioned somewhere in the docs?

**Comment by martinoneutrino** [comment]
I do acknowledge it is not mentioned in the documentation and is thus undocumented behavior for the REST client.

I would expect consistent behavior between the config key override and the class override however (which is what I initially tried), which is documented on the `RestClientsConfig`'s `configKey`.

Looking at the code however, it seems like the `quarkus.rest-client.*.uri` config will be used when referencing either a class name or config key, and so I can see how this has become a problem.

Since there is also a `url` property which is used if `uri` is not available, I may change to that for my default config to minimize any conflicts I get.
