### ISSUE TITLE
Multi Tenancy doesn't work properly 

### ISSUE THREAD

**Issue by crawer** [quarkusio/quarkus#41375]
### Describe the bug

Hello guys, 

I am trying to use the OIDC to resolve a multi-tenant issuer that I have here and I really need your help understanding why it is not working. 

I am following the https://quarkus.io/guides/security-openid-connect-multitenancy#issuer-based-tenant-resolver and my configuration is like this

# Default configuration
quarkus.oidc.resolve-tenants-with-issuer=true
quarkus.oidc.tls.verification=none
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.role-claim-path=authorities
quarkus.oidc.roles.role-claim-path=authorities
quarkus.http.auth.policy.role-policy1.roles-allowed=ROLE_SYSTEMUSER_TS
quarkus.oidc.authentication.user-info-required=true

# Tenant configurations

quarkus.oidc.auth-server-url=URL/REALM/TENANT
quarkus.oidc.token.issuer=URL/REALM/TENANT
quarkus.oidc.token.required-claims.client_id=client_id
quarkus.oidc.client-id=service-portal-frontend
# tenant-a
quarkus.oidc.tenant-a.auth-server-url=URL/REALM/TENANT
quarkus.oidc.tenant-a.token.issuer=URL/REALM/TENANT
quarkus.oidc.tenant-a.token.required-claims.client_id=client_id
quarkus.oidc.tenant-a.client-id=service-portal-frontend

# tenant-b
quarkus.oidc.tenant-b.auth-server-url=URL/REALM/TENANT
quarkus.oidc.tenant-b.token.issuer=URL/REALM/TENANT
quarkus.oidc.tenant-b.token.required-claims.client_id=client_id
quarkus.oidc.tenant-b.client-id=service-portal-frontend

But I am getting 

 rejected due to invalid claims or other invalid content. Additional details: [[12] Issuer (iss) claim value (url/realm/tenant-a) doesn't match expected value of url/realm/tenant-b, [17] claim client_id does not match expected value of client_id]
 
 

### Expected behavior

OIDC should validate every tenant and resolve the process of authentication

### Actual behavior

 rejected due to invalid claims or other invalid content. Additional details: [[12] Issuer (iss) claim value (url/realm/tenant-a) doesn't match expected value of url/realm/tenant-b, [17] claim client_id does not match expected value of client_id]
 

### Output of `java -version`

17

### Quarkus version or git rev

3.2.9.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw --version

**Comment by sberyozkin** [comment]
Hi @crawer 
The link points to the latest documentation (note By Version field there), but since you are on 3.2.9. you should check https://quarkus.io/version/3.2/guides/security-openid-connect-multitenancy#issuer-based-tenant-resolver, where the issue based tenant resolution is not available.
IMHO, it makes sense open a Discussion thread first when it is not obvious yet if it is a bug or something else.
If you'd like to use this specific issuer-based tenant resolution strategy, please migrate to the latest Quarkus and let us know how it goes. 
FYI, you'd typically use it if multiple tenants can support the token verification on exactly the same path....

HTH

**Comment by sberyozkin** [comment]
Hi @crawer ping me on Discussion or Zulip if you'd like some help on selecting the tenant strategy, cheers

**Comment by sberyozkin** [comment]
@crawer Also, I don't think `quarkus-oidc` reports `[17] claim client_id does not match expected value of client_id]`, open a discussion please to discuss why you may be getting this error, `client_id` is not typically set as a token claim
