### ISSUE TITLE
Native Build Fails, when Reusing Existing Executable with Compression Enabled

### ISSUE THREAD

**Issue by gcw-it** [quarkusio/quarkus#41373]
### Describe the bug

Building a native executable with `<quarkus.native.reuse-existing>true</quarkus.native.reuse-existing>` set, and compression enabled, leads to a failing build, when the artifact already exists.

### Expected behavior

The plugin skips the compression step for the already compressed executable, and the build is finished without error.

### Actual behavior

The build fails with:
`Build step io.quarkus.deployment.pkg.steps.UpxCompressionBuildStep#compress threw an exception: java.lang.IllegalStateException: Unable to compress the native executable`

### How to Reproduce?

1. quarkus create
2. add the following *properties* to the *native* profile in *pom.xml*.  
`<quarkus.native.container-build>true</quarkus.native.container-build>`  
`<quarkus.native.reuse-existing>true</quarkus.native.reuse-existing>`  
`<quarkus.native.compression.level>1</quarkus.native.compression.level>`  
3. `mvn package -DskipTests -Dnative`
4. When running the build a 2nd time (`mvn package -DskipTests -Dnative`) the build fails, because the plugin tries to recompress the already compressed executable.

### Output of `uname -a` or `ver`

Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64

### Output of `java -version`

java 22.0.1 2024-04-16

### Mandrel or GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21

### Quarkus version or git rev

3.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)

**Comment by galderz** [comment]
@gcw-it Fancy trying to implement this yourself? `UpxCompressionBuildStep` could be enhanced to see if the binary is already there (and reuse existing is on) and check if the file is already compressed.

**Comment by gcw-it** [comment]
@galderz I could tackle this in the next few days, when I find some spare time (Probably on the weekend).

But first and foremost  we should come to an understanding, what the expected behaviour should be.
Probably simplest and least surprising would be, to leave an existing artifact alone and skip the compression step.
If we go down the road to compress an existing uncompressed executable, if the compression settings have changed between builds, then we have to consider some other situations:
- What happens, when the file is already compressed and the compression level is changed?
- What happens to a compressed file, if compression is disabled?

In my opinion, the cleanest approach would be to take _Reuse Existing Executable_ literally and leave the existing artifact alone.
What are your thoughts?

**Comment by gcw-it** [comment]
@galderz After having a first look at the sources, it doesn't seem possible to gather the required information (was the artifact actually built or was it reused) from the previous build step for my idea to work.
The best approach seems to be, to leave the executable alone, if compressed, or compress it otherwise (as you hinted at in your previous comment).
This can lead to the potentially surprising situation, that an uncompressed, reused artifact will be compressed in a subsequent build run, if the compression settings are changed.
On the other hand a compressed artifact won't be modified, when the compression settings are altered.
Do you think this slight inconsistency should be mentioned in the documentation?
