### ISSUE TITLE
Do we need to update the "Security vulnerability detection and reporting" guide to focus more on CVE?

### ISSUE THREAD

**Issue by rolfedh** [quarkusio/quarkus#41394]
### Description

The current [SECURITY VULNERABILITY DETECTION AND REPORTING IN QUARKUS](https://quarkus.io/guides/security-vulnerability-detection) guide focuses on NVD. 
Feedback from @sberyozkin on our product documentation indicates that our focus has emphasis has shifted from NVD to CVE.
Does this guide need to be updated?

**Comment by sberyozkin** [comment]
Hi @rolfedh I meant to `cve.org`, this current section is kind of outdated for the product docs, but may still be relevant for users working with the OWASP dependency plugin, when they need to update NVD quickly. We are only startimg experimenting with reporting to cve.org, indirectly, with the help from ProdSec

**Comment by rolfedh** [comment]
Okay - thanks for the clarification, @sberyozkin. Makes sense. 
It seems like we can close this issue, then. Please reopen if needed.
