### ISSUE TITLE
JsonObject template extension for Qute built-in

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#41390]
### Description

This will be nice for https://github.com/quarkiverse/quarkus-statiq/issues/15

### Implementation ideas

This need to be added in quarkus-qute, here is an existing implementation : https://github.com/quarkusio/quarkus/blob/2.16/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/JsonObjectValueResolver.java

**Comment by ia3andy** [comment]
This need to be added in quarkus-qute, here is an existing implementation : https://github.com/quarkusio/quarkus/blob/2.16/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/JsonObjectValueResolver.java

**Comment by mcruzdev** [comment]
Hi @mkouba and @ia3andy , how are you?

Correct me if I'm wrong.

To solve it we need to create a new [ValueResolver as mentioned on the issue](https://github.com/quarkusio/quarkus/blob/2.16/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/JsonObjectValueResolver.java) and add it [here](https://github.com/quarkusio/quarkus/blob/32d0c2dd4d935149c71f6e81524fb3a46fe89515/independent-projects/qute/core/src/main/java/io/quarkus/qute/EngineBuilder.java#L129)? 

This solution is ok?

**Comment by mcruzdev** [comment]
I opened a draft pull request, but I am not sure when the best place to add this resolver. If in `EngineBuilder`, `Qute#newDefaultEngine()` or another place.

**Comment by mkouba** [comment]
Hi @mcruzdev, I added a comment there. Qute core is not the right place. It should go in the runtime module of the `quarkus-qute` extension. Ping me on zulip I'm happy to answer futher questions ;-).
