### ISSUE TITLE
Gradle `quarkusGenerateCode` runs far too often

### ISSUE THREAD

**Issue by FWest98** [quarkusio/quarkus#41404]
### Describe the bug

When using Gradle to build a Quarkus app, the `quarkusGenerateCode` task is almost never cached. Even on successive runs of the same codebase without any code changed, this job will rerun - even on codebases where no code is actually being generated.

I managed to boil it down to the following:
- The task is using cache only when rerunning the exact same configuration; even just running a different unit test (by clicking the gutter in IntelliJ) will cause a rerun.
- Gradle reports that
  > Task ':manager:quarkusGenerateCode' is not up-to-date because:
  Value of input property 'cachingRelevantInput' has changed for task ':manager:quarkusGenerateCode'
- When digging into what happens here, I found that both the `cachingRelevantInput` and `internalTaskConfig` are often found to be "changed". These values are provided by the task [here](https://github.com/quarkusio/quarkus/blob/542f5530b336ddd75a22e84fa878547a053f492d/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusGenerateCode.java#L68). These values are provided as a normal map.
- Gradle does not perform a "clever" comparison on these objects ([source](https://github.com/gradle/gradle/blob/master/platforms/core-execution/execution/src/main/java/org/gradle/internal/execution/history/changes/InputValueChanges.java#L38) - the equals call does map-specific things, but will consider map entries as a list and not as a set). In particular, a map with a different order but the same elements is not considered to be equal. Therefore, any change in the _order of variables_ is considered to be a change necessitating a rerun of the job.
  ![image](https://github.com/quarkusio/quarkus/assets/1918658/595a13fa-1b8d-4b29-b643-3b82520808f4)
- Gradle seems to be aware of this and and reports "Other pitfalls can be the use of HashMaps or other data structures without order guarantees in the task’s code." ([source](https://docs.gradle.org/current/userguide/common_caching_problems.html)) as a potential cause for cache invalidation.

So I think on the Quarkus side, it is best to move to a map implementation that guarantees order of some kind - or find some other way to convince Gradle the task can reuse the cached result. In addition, I feel like the scope of the `cachingRelevantInput` map is too large: it includes all system properties prefixed by `quarkus.`, even those not affecting code generation at all. It might be good to look into reducing this scope as well.

### Output of `uname -a` or `ver`

Linux FLORIS-NORTH 4.4.0-22621-Microsoft #3672-Microsoft Fri Jan 01 08:00:00 PST 2016 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.10" 2024-01-16

### Quarkus version or git rev

3.11

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.8

**Comment by dmlloyd** [comment]
I have a possible fix in #41428, could you give it a try?
