### ISSUE TITLE
Document removal of legacy OpenTelemetry configuration properties

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#41409]
### Description

We need to remove the legacy properties that use the `quarkus.opentelemetry.*` namespace. 
We also need to remove the associated relocations and fallbacks.

**Comment by brunobat** [comment]
fixed by https://github.com/quarkusio/quarkus/pull/41405

**Comment by brunobat** [comment]
Still missing the documentation update

**Comment by geoand** [comment]
Changed title to docs issue
