### ISSUE TITLE
https://code.quarkus.io/ uses gradle version unsupported by Kotlin

### ISSUE THREAD

**Issue by adampoplawski** [quarkusio/quarkus#41421]
### Describe the bug

When I use https://code.quarkus.io/ and generate project with Gradle+Kotlin dependecy I get project with Gradle 8.8 and 1.9.23

According to docs Kotlin 1.9.23 support fully 8.1.1
https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin 

I am not sure of that is real issue or what features of Gradle are not compatible 

### Expected behavior

Quarkus project Kotlin with 1.9.23 should use Gradle 8.1.1
Quarkus project Kotlin with 2.0.0 should use Gradle 8.5

### Actual behavior

Quarkus project Kotlin with 1.9.23 use Gradle 8.8

**Comment by geoand** [comment]
cc @ia3andy

**Comment by ia3andy** [comment]
@gsmet any thought?

**Comment by mschorsch** [comment]
The Kotlin documention mentions (https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin)

> You can also use Gradle and AGP versions up to the latest releases, but if you do, keep in mind that you might encounter deprecation warnings or some new features might not work.

So using Gradle 8.8 and newer should be fine.

**Comment by gsmet** [comment]
Yeah, I don't think we want to fix anything there. Kotlin is being overly cautious and very conservative in the version ranges of Gradle they "fully" support.
Basically, it's the version at the time they released.

I don't think we want to follow this as we would lag a lot on the Gradle side.

If you end up encountering real life issues, we can discuss this again.

Thanks for raising the issue anyway.
