### ISSUE TITLE
Kafka consumer has a lag when connecting to a broker in KRaft mode

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#41441]
### Describe the bug

I have an application, which contains a Rest endpoint, which sends messages to kafka via Emitter after receiving a HTTP request, and a consumer, which processes them.
When I connect to kafka broker, which runs in a "classic" mode (with Zookeeper), the application works as expected. When I connect to kafka broker, which runs in a KRaft mode (without Zookeeper), the application sends the messages to the kafka, but do not process them, unless I wait for some time after the app started to send the first request.

### Expected behavior

After the app started, it should process all incoming messages, be they from HTTP or Kafka.

### Actual behavior

The app doesn't start to process the messages right away.

### How to Reproduce?

1. `git clone -b slow-kraft git@github.com:fedinskiy/reproducer.git && cd reproducer`
2. [Optional] Build a image for dual-mode kafka: `podman build --tag double-kafka -f Dockerfile`
3. Run Kafka in a classic mode, eg: ` podman run --rm -it -p9092:9092 -p2181:2181 --name kafka double-kafka:latest /tmp/classic.sh`
4. Run the tests: `mvn clean verify  -Dtest=GreetingResourceTest#fastTest`. The logs contain line from consumer: ` INFO  [io.qua.qe.SlowTopicConsumer] (vert.x-eventloop-thread-3) Processed Message fast`
5. Run Kafka in a kraft mode, eg `podman run --rm -it -p9092:9092 -p2181:2181 --name kafka double-kafka:latest /tmp/kraft.sh`
6. Run the tests: `mvn clean verify  -Dtest=GreetingResourceTest#fastTest`. The logs doesn't contain line from consumer.
7. Run the tests with an initial waiting: `mvn clean verify  -Dtest=GreetingResourceTest#slowTest`. The logs contain line from the consumer: ` [io.qua.qe.SlowTopicConsumer] (vert.x-eventloop-thread-3) Processed Message wait`

### Output of `uname -a` or `ver`

6.7.3-200.fc39.x86_64

### Output of `java -version`

Java version: 21.0.1, vendor: Eclipse Adoptium

### Quarkus version or git rev

3.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

The error is reproduced using Quarkus tests but we first encountered using https://github.com/quarkus-qe/quarkus-test-suite, which runs an application in a prod mode.

**Comment by cescoffier** [comment]
I think it is the proper behavior. The consensus protocol happens after when using kraft, especially when the targeted partition is not yet determined.

**Comment by fedinskiy** [comment]
@cescoffier thank you! Is there a way to find, whether consensus was found from (ideally) quarkus APIs or kafka logs?

**Comment by ozangunalp** [comment]
If you create the topic beforehand, the consumer partition assignment would be less noticeable.

**Comment by ozangunalp** [comment]
@fedinskiy did creating the topic resolve the issue ?

**Comment by fedinskiy** [comment]
@ozangunalp it didn't, but it improved situation a bit (so thank you). Instead of waiting for 5 seconds, we only need to wait for one. I would still prefer, if Quarkus notified about being ready to receive messages.

**Comment by michalvavrik** [comment]
> @ozangunalp it didn't, but it improved situation a bit (so thank you). Instead of waiting for 5 seconds, we only need to wait for one. I would still prefer, if Quarkus notified about being ready to receive messages.

+1; IMO there can be user scenario when you only want app ready when it can process events, maybe users would expose custom probes so they would need to know state or at least rely on event

**Comment by michalvavrik** [comment]
> The readiness check for messaging channels already looks at the partition assignment. It is possible to access the [underlying Kafka client](https://quarkus.io/guides/kafka#kafka-bare-clients) and write a check on that.
> 
> Another option would be to write a custom [consumer rebalance listener](https://quarkus.io/guides/kafka#consumer-rebalance-listener) to listen rebalance events.

Cool, thanks.
