### ISSUE TITLE
Missing jar artifact when downloading dependencies for offline development

### ISSUE THREAD

**Issue by nyko29** [quarkusio/quarkus#41460]
### Describe the bug

I have a project that needs to be built in an offline environment.
From a computer having internet i download all artifact with:

`mvn quarkus:go-offline`

After the transfer of my .m2 on the offline environment I am able to build my project (mvn clean install). But when i want to launch it in dev mode, it fails requesting additional artifact.

(for instance maven-resolver-transport-http-1.9.20.jar) --> the pom has well been downloaded but not the jar.

### Expected behavior

Be able to use dev mode in offline mode with all artifacts

### Quarkus version or git rev

3.12.0

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
I just tried it and it was downloaded
```
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-transport-http/1.9.20/maven-resolver-transport-http-1.9.20.pom
Progress (1): 5.6 kB^M                    ^MDownloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-transport-http/1.9.20/maven-resolver-transport-http-1.9.20.pom (5.6 kB at 194 kB/s)
```
To reproduce I created a basic REST app and ran `mvn quarkus:go-offline -Dmaven.repo.local=temp-repo-dir`

@nyko29 do you have any more details or instructions to reproduce the issue?

**Comment by geoand** [comment]
Closing for a lack of feedback.
