### ISSUE TITLE
Split package in "io.fabric8.kubernetes.api.model" since Quarkus 3.12.0

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#41468]
### Describe the bug

```
Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-admissionregistration:6.13.0, io.fabric8:kubernetes-model-apiextensions:6.13.0, io.fabric8:kubernetes-model-apps:6.13.0, io.fabric8:kubernetes-model-autoscaling:6.13.0, io.fabric8:kubernetes-model-batch:6.13.0, io.fabric8:kubernetes-model-certificates:6.13.0, io.fabric8:kubernetes-model-coordination:6.13.0, io.fabric8:kubernetes-model-core:6.13.0, io.fabric8:kubernetes-model-discovery:6.13.0, io.fabric8:kubernetes-model-events:6.13.0, io.fabric8:kubernetes-model-extensions:6.13.0, io.fabric8:kubernetes-model-flowcontrol:6.13.0, io.fabric8:kubernetes-model-gatewayapi:6.13.0, io.fabric8:kubernetes-model-metrics:6.13.0, io.fabric8:kubernetes-model-networking:6.13.0, io.fabric8:kubernetes-model-node:6.13.0, io.fabric8:kubernetes-model-policy:6.13.0, io.fabric8:kubernetes-model-rbac:6.13.0, io.fabric8:kubernetes-model-resource:6.13.0, io.fabric8:kubernetes-model-scheduling:6.13.0, io.fabric8:kubernetes-model-storageclass:6.13.0]
```

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus 3.12.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

**Comment by geoand** [comment]
cc @manusa

**Comment by manusa** [comment]
Hi @shawkins 
I'm not sure if this is a regression or there were a few split packages still left, do you remember?

Related issues:
- https://github.com/fabric8io/kubernetes-client/issues/5113
- https://github.com/fabric8io/kubernetes-client/issues/3835
-

**Comment by manusa** [comment]
OK, it's not a regression, it's a side-effect of:
#40157
That's a fix addressing:
#39300

As far as I can tell, the issue is that all model packages contain the two KubeSchema and Validation classes at `io.fabric8.kubernetes.api.model`.

**Comment by manusa** [comment]
We should be able to address this for version 7, but that of course bears the (future, once released) discussion on how and when to bump Kubernetes Client from 6 to 7.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/41472 .

Next time, let's make sure to test this scenario before dropping the ignore rules. Thanks!

**Comment by manusa** [comment]
> I created #41472 .

Thanks
