### ISSUE TITLE
[Extension Proposal] JMX Beans

### ISSUE THREAD

**Issue by d135-1r43** [quarkusio/quarkus#41469]
### Description

The extension would allow annotating a class with `@QuarkusJmx`. All getters will be made available as JMX attributes, all methods will be made available as JMX operations. The Dev UI will have a page where you can easily access both the attributes and the operations. 

I would be willing to contribute and maintain this extension.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-jmx

### Short description

Provide JMX Management Beans

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- JMX
...

### Team Members

- @d135-1r43

**Comment by gastaldi** [comment]
@d135-1r43 the repository https://github.com/quarkiverse/quarkus-jmx is now available. Check the next steps in https://hub.quarkiverse.io/checklist/#after-the-repository-is-created 

Enjoy!

**Comment by gastaldi** [comment]
@d135-1r43 I don't see anything pushed to the repository yet, are you still interested in working on this extension?
