### ISSUE TITLE
Quarkus welcome page is different when rendered vai CLI on linux vs windows

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus#41473]
### Describe the bug

When creating app using quarkus cli and running it in a way:
```
quarkus create app app --stream=3.8 -Dquarkus.analytics.disabled=true
cd app
quarkus dev
```
After accessing localhost:8080 I expect to have a welcome page, saying congratulation. This is true for quarkus 3.2.12.Final and 3.8.5.

But for 3.9.5, 3.10.2, 3.11.3 and 3.12.0 behaviour differs. On linux this works the same way. But on windows (tested on win 2019 jdk 22). After I access the localhost:8080, I get redirected to http://localhost:8080/q/dev-ui/welcome. Where there is just white page.

This behaviour should be the same for both windows and linux.

**Comment by maxandersen** [comment]
since 3.9.x we moved to have dynamic index.html in devmode (which is served by dev-ui) - see https://github.com/quarkusio/quarkus/pull/37680

you can still add and have a index.html as usual and it should work the same across all OS's.

My guess is it might be a browser difference? 

there was some early issues with it older firefox versions but that should be fixed.

If you can provide some more info on what browser and just to exclude some funky possible java 22 impact. can you try with java 21 or java17 ?

**Comment by maxandersen** [comment]
cc @phillip-kruger

**Comment by phillip-kruger** [comment]
So does it redirect for Linux too? But the screen renders ? Ans for Windows it does not ? Any errors in your browsers dev console ?

**Comment by mocenas** [comment]
> If you can provide some more info on what browser and just to exclude some funky possible java 22 impact. can you try with java 21 or java17 ?

I originally tried it on some obsolete version of IE. I retested it with firefox 128.0. On windows I still gets redirect to http://localhost:8080/q/dev-ui/welcome , difference is, that FF can actually render this page and it also displays Congratulations web page. But it is clearly different Congratulations welcome page, than on Linux on localhost:8080/.

I also switched to java 17, no difference.

> So does it redirect for Linux too? But the screen renders ? Ans for Windows it does not ? Any errors in your browsers dev console ?

There is no redirect on linux, browser stays on localhost:8080. On Windows it actually renders t he Congratulations page, when I switched to up-to-date firefox. No relevant error is browser dev console.



Testing the windows welcome page with up-to-date browser make it actually render the welcome page, but the issue still stands, that only on windows it gets redirected from localhost:8080 to http://localhost:8080/q/dev-ui/welcome. Also the welcome page is different (while similar) on those URIs. I'm attaching their view and source code for both.
![lin_congrats](https://github.com/user-attachments/assets/8e88e255-7a38-4772-8a78-26fbd017ff75)
![win_congrats](https://github.com/user-attachments/assets/05731143-a944-4890-a98c-a0bc3434a52a)
[linux_index.html.txt](https://github.com/user-attachments/files/16332350/linux_index.html.txt)
[win_index.html.txt](https://github.com/user-attachments/files/16332351/win_index.html.txt)

**Comment by phillip-kruger** [comment]
The one with the pink color font is the old generated index.html. If you get that it means the app has been generated with an older (pre 3.9) quarkus. The other one is the new one. You can manually delete the index.html in META-INF/resources and then (if using the correct Quarkus version) you should see the new page.

**Comment by mocenas** [comment]
I didn't realize that quarkus CLI version is also coming into play. After upgrading CLI to 3.12 I'm getting same web UI everywhere.
Thanks for help.
