### ISSUE TITLE
Exception handling with @ServerExceptionMapper does not match method with more general exception

### ISSUE THREAD

**Issue by pengxo** [quarkusio/quarkus#41479]
### Describe the bug

Consider the quarkus app with some REST resouces and the following global Exception handling class:

```
class ExceptionHandler{
    @ServerExceptionMapper
    fun throwable(throwable: Throwable): Response {
        return Response.status(Status.INTERNAL_SERVER_ERROR).entity("").build()
    }
}
```

if a POST request is executed with malformed request body that leads to `com.fasterxml.jackson.databind.exc.MismatchedInputException`, then the exception will not be matched here. I tried to set the method parameter type from `Throwable` to any super exception class of  `MismatchedInputException` such as `com.fasterxml.jackson.databind.JsonMappingException` and `com.fasterxml.jackson.databind.DatabindException`, none of them works. It mathes only when the type is `MismatchedInputException`.

In the exception handling class, there can be multiple methods with annotation `@ServerExceptionMapper`  and different exception types to have different handling and have the method with type `Throwable` as default exception handling. But it seems  not work well. 

### Expected behavior

The method with `Throwable` type should match any exception type if there is no more specific matching.

### Actual behavior

The method with `Throwable` cannot match more specific exception `MismatchedInputException`

### Output of `java -version`

21

### Quarkus version or git rev

3.11.2 for quarkus

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradlew

**Comment by geoand** [comment]
This is actually the expected behavior because Quarkus [ships](https://github.com/quarkusio/quarkus/blob/3.11.2/extensions/resteasy-reactive/rest-jackson/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/mappers/DefaultMismatchedInputException.java) with an exception mapper for  `MismatchedInputException` and the JAX-RS / Jakarta REST spec states that a more specific exception mapper takes precedence over a more general one.

**Comment by pengxo** [comment]
Hi @geoand, thanks for your explaina. Now I understand the reason. Then in the app one need to find out all the implementations of ExceptionMapper if we want to customize the error response.

**Comment by geoand** [comment]
Yup and the DevUI will give you that information :)
