### ISSUE TITLE
3.8.4 OidcClientFilter not being called on deployed Quarkus Service

### ISSUE THREAD

**Issue by JM92103** [quarkusio/quarkus#41512]
### Describe the bug

I have implemented OIDC using the `quarkus-oidc-client-reactive-filter` dependency. When running the service locally, it works as expected (with overriding .env file to match my deployment). However, once deployed, OIDC isn't being called. The reason I suspect this is because I have a `ResteasyReactiveClientRequestFilter` which prints out all the headers in the request. Running locally I can see the Authorization header with the expected bearer token, whereas on my deployed service, there is no Authorization header.
Local:
```
Authorization=[Bearer xxxxx]
Content-Type=[application/json]
User-Agent=[Resteasy Reactive Client]
```
Deployed:
```
Content-Type=[application/json]
User-Agent=[Resteasy Reactive Client]
```
I am not seeing any errors in the logs regarding OIDC setup issues, only the 401 from my rest client. Happy to provide any other code if needed.

### Expected behavior

I expect there to be an Authorization Header with the Bearer token generated from Azure.

### Actual behavior

No Header is present in the request.

### Output of `uname -a` or `ver`

Linux LG39016415 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 OpenJDK Runtime Environment (Red_Hat-17.0.9.0.9-4) (build 17.0.9+9) OpenJDK 64-Bit Server VM (Red_Hat-17.0.9.0.9-4) (build 17.0.9+9, mixed mode, sharing)

### Quarkus version or git rev

3.8.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (Red Hat 3.8.6-4) Maven home: /usr/share/maven Java version: 21.0.2, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-21-openjdk-21.0.2.0.13-1.fc38.x86_64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.153.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

**Comment by sberyozkin** [comment]
@JM92103, having more information would definitely help.

>I expect there to be an Authorization Header with the Bearer token generated from Azure. 

What are the differences in the way you configure OIDC client locally and in the cloud ? Is it possible for you to create a simple demo showing what works ?

**Comment by geoand** [comment]
> I don't think a small project will help, as this setup works perfectly in another running service, so my suspicion is a conflicting dependency or something along those lines.

As someone who looks at all sort of issues, I beg to differ :). Small projects that exhibit the exact problem being described are by far the most effective way for the team to home in the problem and iterate on a solution, while also providing a real world base for writing a test that ensures the issue won't occur again.
That's not even mentioning the cases where the author of the issue, in the process of creating this sample,  finds a problem in their own code instead of Quarkus.

**Comment by sberyozkin** [comment]
@JM92103 Can you try to enable the debug/trace logging for quarkus-oidc-client ? It feels like it has not been enabled. It should fail deployment if it fails to initialize, is is indeed appears to be a deployment specific problem.

https://github.com/quarkusio/quarkus/blob/3.8.4/extensions/oidc-client-reactive-filter/runtime/src/main/java/io/quarkus/oidc/client/reactive/filter/runtime/AbstractOidcClientRequestReactiveFilter.java will add `Authorization`.

One thing you can try, as georgios

**Comment by sberyozkin** [comment]
@JM92103 Did you have a chance to investigate it further ? We can't really do anything at the Quarkus level with some additional input

**Comment by sberyozkin** [comment]
Hey @JM92103 Let me close this one for now - it is hard to triage if there is no feedback. Please open it as soon as you can narrow down on your end and detect an actual OIDC client issue, you can ping on Zulip to clarify details if you'd like
