### ISSUE TITLE
Allow adding labels to routes

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#41536]
### Describe the bug

We have only annotations now:

```
quarkus.openshift.route.annotations."test"=value
```

And I need label for my use case.

### Expected behavior

There is something like:

```
quarkus.openshift.route.labels."test"=value
```

### Actual behavior

It's not possible to configure label just for the route.

### Additional information

I already have PR ready which is blocked on https://github.com/dekorateio/dekorate/pull/1296 and dekorate update in quarkus. Just logging this.

**Comment by geoand** [comment]
Seems reasonable to me

**Comment by iocanel** [comment]
Me too. dekorate release is on its way btw.
