### ISSUE TITLE
Documentation: Clarify possible self-invocation as CDI extension

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#41545]
### Description

It would be appreciated if some person of authority on the subject (@Ladicek maybe?) could clarify, and maybe even add a section about this to https://quarkus.io/guides/cdi-reference that in Quarkus, beans are indeed intercepted on self-invocation, even though this is not possible with standard CDI. For example, the following code works in Quarkus:
```java
@ApplicationScoped
@Transactional
public class MyService {
    @Transactional(REQUIRES_NEW)
    protected void doStuffInNewTransaction() {
        System.out.println("do stuff, but in a new transaction");
    }

    @Scheduled(every = "PT1S")
    void someSchedule() {
        System.out.println("do stuff");
        // This call goes through a transactional interceptor! (TransactionalInterceptorRequiresNew),
        // even though in pure CDI self-invocation does not perform interception.
        doStuffInNewTransaction();
    }
}
```

However, in CDI this would not be possible and instead none of the annotations on `doStuffInNewTransaction` would have any effect for the above invocation. See also [CDI-414](https://issues.redhat.com/browse/CDI-414)

**Comment by Felk** [comment]
I also found [this](https://stackoverflow.com/a/75804884/3688648) on StackOverflow:

> They need to be public, protected or package-private (default visibility). They must not be private. Self-interception works, so you can call a @Transactional method from within the same class and the transactional interceptor will be called, but again, the method must not be private. – Ladicek Jun 29, 2021 at 15:53

but couldn't find any source to verify these claims

**Comment by Ladicek** [comment]
Yeah, the situation on the specification(s) side is not very clear. It is a good point that we should make this clear in the documentation.
