### ISSUE TITLE
PostgreSQL DevServices with embedding Vectors

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#41569]
### Description

Currently, if you want to use PostgreSQL with the `hibernate-vector` dependency, when using DevServices with PostgreSQL database, it starts the service with a standard PostgreSQL database image (so no `vector` type available).

It would be great that if DevServices detects the `hibernate-vector` dependency, could start the `ankane/pgvector:v0.5.1` container image and execute the following command before executing any Hibernate SQL command:

```
CREATE EXTENSION IF NOT EXISTS vector;
```

Of course there are workarounds like using `quarkus.datasource.devservices.image-name=ankane/pgvector:v0.5.1` and then create an `import.sql` file with the SQL command. But would be great that devs can smoothly start using vectors.

**Comment by melloware** [comment]
I opened this ticket too on the Postgres Embedded extension: https://github.com/quarkiverse/quarkus-embedded-postgresql/issues/97

**Comment by melloware** [comment]
@mcruzdev @lordofthejars according to @geoand the PGVector is already configured: https://docs.quarkiverse.io/quarkus-langchain4j/dev/pgvector-store.html using `pgvector/pgvector:pg16` ??

So can this ticket be closed or is there something else that needs to be done?

**Comment by geoand** [comment]
@melloware, indeed that's the case!
