### ISSUE TITLE
Missing OIDC enabled property for tenants

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#41565]
### Describe the bug

I navigate the config documentation and i see that only `quarkus.oidc.enabled` exists and the `quarkus.oidc."tenant".enabled` is missing. As far as i know the config documentation is updated automatically so i assume, it's either not picking it up or quarkus does not support `quarkus.oidc."tenant".enabled`.

(even the Intellij does not offer auto completion for  `quarkus.oidc."tenant".enabled`)

**Comment by sberyozkin** [comment]
Hi @gbourant, `.enabled` is a build time property, individual tenants, including the default tenant,  can be disabled with `.tenant-enabled`.

Let me close this issue,  thanks
