### ISSUE TITLE
REST Client reporting "false negative" unrecognized URL configuration keys on startup

### ISSUE THREAD

**Issue by wabrit** [quarkusio/quarkus#41577]
### Describe the bug

When migrating from Quarkus service from 3.5 to 3.11, some new messages appear on startup of this form:

`Unrecognized configuration key "quarkus.rest-client-reactive."foo.bar.api".url" was provided; it will be ignored`

One of the properties YAML read by the service contains this snippet:

```yaml
foo:
  bar:
    "api/mp-rest/url": somevalue
```

(The `api/mp-rest/url` is a microprofile convention used by e.g. Spring Feign to declare endpoints for REST clients).

It appears that Quarkus REST client has some relocation / fallback rules to rewrite the mp config names to quarkus config names, and is picking up this `foo.bar,"api/mp-rest/url"` property and re-interpreting it as `quarkus.rest-client-reactive."foo.bar.api".url`.

At the least it would be good to be able to instruct Quarkus to ignore certain paths when it goes hunting for rest client URLs, as otherwise this can lead to a plethora of "false negative" unresolved property warnings amongst which could lurk some real issues. (this can occur for example when using a shared YAML that describes REST client mappings for a bunch of microservices, some of which are Spring Boot, and some of which are Quarkus).

### Expected behavior

To be able to specify via configuration a list of property path prefixes to be excluded from Quarkus rest client URL discovery, thereby suppressing such "unresolved property" warnings.

### Actual behavior

No such facility to exclude certain path roots is provided.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 LAP1453 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 LTS OpenJDK Runtime Environment Zulu17.38+21-CA (build 17.0.5+8-LTS) OpenJDK 64-Bit Server VM Zulu17.38+21-CA (build 17.0.5+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by geoand** [comment]
I am not aware of the relocations in question, @radcortez any idea?

**Comment by geoand** [comment]
@wabrit would you be able to attach a sample application that I can use to track down what is going on?

Thanks

**Comment by wabrit** [comment]
@geoand I'll put something simple together

**Comment by geoand** [comment]
@wabrit where you able to put a project together that shows the problem in action?

**Comment by wabrit** [comment]
Apologies - I thought a minimal repro would do the trick but sadly it didn't, so then it was a question of trying to figure out what was specific in my project (e.g. native vs non-native builds) and more urgent things intervened, Will try and get back to this when I get some time.

**Comment by geoand** [comment]
No problem

**Comment by geoand** [comment]
I am going to close this for now.

If a reproducer becomes available, please comment and we can reopen the issue.

Thanks

**Comment by wabrit** [comment]
Just to close this out, I no longer see this behaviour once I uprev'd to Quarkus 3.16.2

**Comment by geoand** [comment]
Thanks for the update!
