### ISSUE TITLE
Helpfull error message when there is no JSON extension in the classpath and @Produces(MediaType.APPLICATION_JSON) is used

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#4157]
To reproduce:
- Do getting started guide (= hello world example)
- Change @Produces(MediaType.TEXT-PLAIN) with @Produces(MediaType.APPLICATION_JSON)
- Change return type to LocalDate (or Duration or UUID)
- Browse to that url.

Output:

`Could not find MessageBodyWriter for response object of type: java.time.Duration of media type: application/json`

That's not the problem! There is no json extension (for example jackson) in the classpath. Once the error is detected, before the error is thrown, it could check if any json extension is available and if none is, mention that in the error message.

**Comment by machi1990** [comment]
> That's not the problem! There is no json extension (for example jackson) in the classpath. Once the error is detected, before the error is thrown, it could check if any json extension is available and if none is, mention that in the error message.

@ge0ffrey I was thinking of emitting a warning (or throw an error) during build time if we detect the need of a json extension and there is non provided. I could give this a shot sometime this week.

Also /cc @gsmet @geoand to have their opinion on this.

**Comment by geoand** [comment]
I think a warning message during build time would be a good idea

**Comment by ge0ffrey** [comment]
FWIW, the log already shows this:

```
.... ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002005: Failed executing GET /foo: org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: java.time.Duration of media type: application/json
+ stacktrace
```
