### ISSUE TITLE
Use conditional dependencies for Flyway

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#41580]
### Description

We should be able to automatically pull in the necessary Flyway dependency when a supported SQL driver is used, by introducing a conditional dependency that will get triggered when the Flyway and the driver extensions are present

**Comment by geoand** [comment]
#41583 is for PostgreSQL. 
Doing the same for other jdbc drivers is trivial by following the lead that of said PR.

**Comment by gastaldi** [comment]
Shall we create good first issues for the remaining JDBC drivers so it's easier to have them picked up?

**Comment by geoand** [comment]
I added the label to original issue
