### ISSUE TITLE
Make Metrics extension use Vert.x instead of Servlets

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#4159]
Per discussion with @jmartisk .

See this PR https://github.com/quarkusio/quarkus/pull/4062 for some examples.

**Comment by gastaldi** [comment]
That looks interesting. May I give it a try or is this already being worked on by someone else?

**Comment by jmartisk** [comment]
I'm planning to do that, per discussion in https://github.com/quarkusio/quarkus/issues/4151 if you don't mind :) yeah it does sound like an interesting task. I suppose there must be some more extensions that still need the same

**Comment by gastaldi** [comment]
> I'm planning to do that, per discussion in #4151 if you don't mind :)

@jmartisk not at all, by all means :wink: 

@gsmet can this issue be assigned to @jmartisk ?

**Comment by geoand** [comment]
Does is make sense to open a similar issue for Opentracing? That one relies on servlets in the way of providing a Servlet filter.
