### ISSUE TITLE
GraphQL Query generated from windows doesn't work

### ISSUE THREAD

**Issue by hanechris** [quarkusio/quarkus#41600]
### Describe the bug

When using restassured, sending a graphQL query returns a malformed error.  The issue is in SmallRyeGraphQLExecutionHandler.  This patter:

    PATTERN_NEWLINE_OR_TAB = Pattern.compile("\\n|\\t");

Needs to also remove \r.  \r remains in the string and isn't parsed by the JSON parser.  Hence malformed.

I stripped before sending to the server to fix.  Would be nice if fixed in the code above.

### Expected behavior

Strip \r in addition to \n and \t

### Actual behavior

Generates a malformed query exception.

### Output of `uname -a` or `ver`

windows 11

### Output of `java -version`

22

### Quarkus version or git rev

3.9.2

**Comment by jmartisk** [comment]
Ok, I struggled a bit to reproduce this because I don't have a Windows machine handy, but this seems to reproduce it on Linux:

```
# create a query that contains LF inside
echo -e "{\"query\": \"{__typename\n}\"}" > QUERY_LF
# create a query that contains CR+LF inside
echo -e "{\"query\": \"{__typename\r\n}\"}" > QUERY_CRLF
# execute with LF - works
curl -v localhost:8080/graphql --data-binary @QUERY_LF
# execute with CR+LF - doesn't work
curl -v localhost:8080/graphql --data-binary @QUERY_CRLF
```
We'll fix this, thanks for reporting.
