### ISSUE TITLE
Expose validate-on-borrow provided by Agroal through Quarkus

### ISSUE THREAD

**Issue by mkrueger92** [quarkusio/quarkus#41616]
### Description

At the moment the option validate-on-borrow is not configurable. I have a use-case for that and would like it to be configurable through Quarkus. The option is available in Agroal already but not used.

**Comment by yrodiere** [comment]
Agroal documentation defines the feature as follows:

> Allows connection validation prior to acquisition (foreground validation) overriding any idle timeout. Because of the overhead of performing validation on every call, it’s recommended to rely on idle validation instead

So from what I understand, usually Agroal would only validate connections when they've been idle for a while, and this instead forces validation on every single retrieval of a connection from the pool?

Can you please give us an example of a use case for that, for the record?

**Comment by yrodiere** [comment]
Also, hi and thanks for reporting and for the PR :)

**Comment by mkrueger92** [comment]
Hi,

my use-case is that we run Postgresql in K8s. We connect to the master through a service. When for some reason a read-replica gets promoted to master (becomes writable) then the old master becomes a read-replica. Persistent connections in the pool do not get notified about this. As a consequence the following write/update operation fails.

Allowing to validate the connection with a sql statement if the connection allows writes on borrow will not fail write of the application because this connection is then not used. The trick here is to raise an exception in case the connection points to a read-replica. 

Right now we are experimenting with this approach. Our current sql statement (works on Postgresl only!) is:
`select case when pg_is_in_recovery = false then 1 else 1/(select 0) end from pg_is_in_recovery();`
This will raise an division by 0 exception. It is quite "hacky". But it seems to do the trick.

**Comment by yrodiere** [comment]
Alright, I understand, thank you.
