### ISSUE TITLE
Since 3.12.0 filesystem write access during container build IT tests results in AccessDeniedException

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#41659]
### Describe the bug

I have an application that creates dirs and writes files to the file system. In production, this directory is mounted. During test we used to write directly into the container.

With the update to 3.12.0 this seem not to be possible anymore as we get a AccessDeniedException: java.nio.file.AccessDeniedException: /home/jboss/myDir

### Expected behavior

No change. Writing to the filesystem during a containerized test should still be possible

### How to Reproduce?

https://github.com/HerrDerb/quarkus-issue/tree/container-write

* `./mvnw verify -Dquarkus.container-image.build=true  -DskipITs=false`

when running with 3.12.0 the IT test will fail -> see target/quarkus.log
when run with 3.11.3 the IT test will succeed

**Comment by geoand** [comment]
This is really weird. From `3.12` the container logs:

```
/opt/jboss/container/java/run/run-java.sh: line 147: /opt/jboss/container/java/jvm/java-default-options: Permission denied
/opt/jboss/container/java/run/run-java.sh: line 150: /opt/jboss/container/java/jvm/debug-options: Permission denied
INFO exec -a "java" java -Djava.util.logging.manager=org.jboss.logmanager.LogManager -cp "." -jar /home/jboss/quarkus-run.jar 
INFO running in /home/jboss
/opt/jboss/container/java/run/run-java.sh: line 147: /opt/jboss/container/java/jvm/java-default-options: Permission denied
/opt/jboss/container/java/run/run-java.sh: line 150: /opt/jboss/container/java/jvm/debug-options: Permission denied
```

where those `Permission denied` entries don't exist for `3.12`. I have yet to discover what causes the problem...

**Comment by geoand** [comment]
@galderz this seems to be caused by 7493ab4ab24c7277067a0755354bb634bcdd5b5d, where we are using user `1000` for launching the container. This is incorrect for the container image created by Jib when running with Docker.

What was the reasoning behind this change?

**Comment by geoand** [comment]
Maybe we should only do call `getVolumeAccessArguments` when `volumeMounts` are not empty?

**Comment by HerrDerb** [comment]
Thank you (y)

**Comment by geoand** [comment]
🙏🏼
