### ISSUE TITLE
Hibernate entities: @UpdateTimestamp is triggered w/out change when bean contains JSON type

### ISSUE THREAD

**Issue by sbeigel** [quarkusio/quarkus#41674]
### Describe the bug

Using a JPA/hibernate entity with @UpdateTimestamp and a JSON property (SqlTypes.JSON / MySQL column type "json"), a change is triggered just by finding (i.e. getting) the entity without changing the content. Removing the JSON-property from the class, everything is back to normal: No update is triggered by just accessing the entity.

### Expected behavior

A change should not be triggered by only mapping JSON column, i.e. the "last update" should only be adjusted after explicit changes.

### Actual behavior

@UpdateTimestamp is triggered without any explicit change when the entity has a JSON column mapped (SqlTypes.JSON)

### How to Reproduce?

```
@Path("/foo")
public class FooResource {

    public static class Bar {
        ...
    }

    @Entity
    public static class Foo {
        @Id
        public Long id;

        @UpdateTimestamp
        public OffsetDateTime lastModified;

        @JdbcTypeCode(SqlTypes.JSON)
        @Column(columnDefinition = "json", nullable = false)
        public Bar bar;
    }
    @Inject
    EntityManager em;

    @GET
    @Path("/test")
    @Transactional
    public String test() {
        // just "finding" the entity triggers a lastModified update
        em.find(Foo.class, 1L);
        return "ok";
    }
}

```

Eveny request to the /foo/test endpoint updates the "lastModified" timestamp in the database.

### Output of `uname -a` or `ver`

Darwin ... 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

java version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.12.0

**Comment by marko-bekhta** [comment]
hey @sbeigel 

Thanks for reporting the issue. Does your `Bar` class implement hashcode/equals? If not, ORM may consider your JSON property dirty and trigger an update, bumping the timestamp. 
I've tried running a test based on your input, and if I have hash/euqals I'd get:
```sql
[Hibernate] 
    insert 
    into
        EntityWithJson
        (json, lastModified, id) 
    values
        (?, ?, ?)
[Hibernate] 
    select
        ewj1_0.id,
        ewj1_0.json,
        ewj1_0.lastModified 
    from
        EntityWithJson ewj1_0
[Hibernate] 
    select
        ewj1_0.id,
        ewj1_0.json,
        ewj1_0.lastModified 
    from
        EntityWithJson ewj1_0 
    where
        ewj1_0.id=?
[Hibernate] 
```
while if `Bar` has no hash/equals implementation the resulting SQL is:
```sql
[Hibernate] 
    insert 
    into
        EntityWithJson
        (json, lastModified, id) 
    values
        (?, ?, ?)
[Hibernate] 
    update
        EntityWithJson 
    set
        json=?,
        lastModified=? 
    where
        id=?
[Hibernate] 
    select
        ewj1_0.id,
        ewj1_0.json,
        ewj1_0.lastModified 
    from
        EntityWithJson ewj1_0
[Hibernate] 
    update
        EntityWithJson 
    set
        json=?,
        lastModified=? 
    where
        id=?
[Hibernate] 
    select
        ewj1_0.id,
        ewj1_0.json,
        ewj1_0.lastModified 
    from
        EntityWithJson ewj1_0 
    where
        ewj1_0.id=?
```

(additional updates because the json property is considered dirty)

**Comment by sbeigel** [comment]
Ah ok, you are right! However, that is rather complicated or at least inelegant for larger JSON objects containing nested object or list of objects etc. as all used classes have to implement equals/hashCode (considering all its properties!) to make this work (and catch property changes on the other hand).

You wouldn't have that problem using records though for the (nested) JSON stuff though :)
