### ISSUE TITLE
Infinispan extension needs to include Wildly SASL providers in the native executable

### ISSUE THREAD

**Issue by karesti** [quarkusio/quarkus#41677]
In some cases, Infinispan cannot start on FIPS enabled system and with Native mode. We need to include these classes to be loaded in the native executable. 

            "org.wildfly.security.sasl.plain.WildFlyElytronSaslPlainProvider",
            "org.wildfly.security.sasl.digest.WildFlyElytronSaslDigestProvider",
            "org.wildfly.security.sasl.external.WildFlyElytronSaslExternalProvider",
            "org.wildfly.security.sasl.oauth2.WildFlyElytronSaslOAuth2Provider",
            "org.wildfly.security.sasl.scram.WildFlyElytronSaslScramProvider",
            "org.wildfly.security.sasl.gssapi.WildFlyElytronSaslGssapiProvider",
            "org.wildfly.security.sasl.gs2.WildFlyElytronSaslGs2Provider"

**Comment by jerboaa** [comment]
@karesti Are Wildfly SASL providers known to work with the `SunPKCS11 + NSS` provider? That's the only one available for FIPS in native mode.

**Comment by karesti** [comment]
@jerboaa I'm fixing a FIPS error for Infinispan with this

**Comment by karesti** [comment]
@tristantarrant here
