### ISSUE TITLE
QUARKUS_LOG_METRICS_ENABLED=true doesn't always work

### ISSUE THREAD

**Issue by guignome** [quarkusio/quarkus#41671]
### Describe the bug

I have a simple and a complex Camel on Quarkus (CoQ) applications. In the complex application, I can only get the `log_total` metric to show if I use the `quarkus.log.metrics.enabled` property and not using the `QUARKUS_LOG_METRICS_ENABLED` env. Both the property and the env work in the simple CoQ app however.

In other words, here is what works and what doesn't:

|     |Simple CoQ application|Complex CoQ application|
|-----|----|----|
|QUARKUS_LOG_METRICS_ENABLED=true ./mvnw quarkus:dev| Yes | Yes|
|QUARKUS_LOG_METRICS_ENABLED=true java -jar quarkus-run.jar| Yes | No|
|quarkus.log.metrics.enabled=true in application.properties, then ./mvnw quarkus:dev|Yes | Yes |
|quarkus.log.metrics.enabled=true in application.properties, then java -jar quarkus-run.jar quarkus-run.jar|Yes | Yes |

**Comment by guignome** [comment]
@brunobat FYI.

**Comment by geoand** [comment]
I am pretty sure we'll need a sample application that exhibits the problematic behavior if we are to get to the bottom of this one

**Comment by guignome** [comment]
I'm just now realizing that the `quarkus.log.metrics.enabled` is a build-time property that is not overridable at runtime, so this explains the behavior.
