### ISSUE TITLE
quarkus create app throws ERROR

### ISSUE THREAD

**Issue by rinmalavi** [quarkusio/quarkus#41687]
### Describe the bug

Running 

      quarkus create app my-groupId:my-artifactId \
          --extensions=rest,rest-jackson \
          --gradle

returns 

[ERROR] ❗  Unable to create project: Failed to resolve codestart artifact io.quarkus:quarkus-project-core-extension-codestarts:jar:3.8.4

### Expected behavior

create a project skeleton like described in 
https://quarkus.io/guides/gradle-tooling

### Actual behavior

Criptic error in form of:

[ERROR] ❗  Unable to create project: Failed to resolve codestart artifact io.quarkus:quarkus-project-core-extension-codestarts:jar:3.8.4

### How to Reproduce?

1. follow instructions at https://quarkus.io/guides/gradle-tooling

### Output of `uname -a` or `ver`

Darwin RA-A964-mbp 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment (build 21.0.3+10-LTS) OpenJDK 64-Bit Server VM (build 21.0.3+10-LTS, mixed mode, sharing)

### Additional information

running mvn version of this procedure returns a bit more:

    $ mvn io.quarkus.platform:quarkus-maven-plugin:3.12.1:create \
        -DprojectGroupId=my-groupId \
        -DprojectArtifactId=my-artifactId \
        -Dextensions="rest,rest-jackson" \
        -DbuildTool=gradle

[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/platform/quarkus-maven-plugin/3.12.1/quarkus-maven-plugin-3.12.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.448 s
[INFO] Finished at: 2024-07-04T13:41:44+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin io.quarkus.platform:quarkus-maven-plugin:3.12.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for io.quarkus.platform:quarkus-maven-plugin:jar:3.12.1: Could not transfer artifact io.quarkus.platform:quarkus-maven-plugin:pom:3.12.1 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/io/quarkus/platform/quarkus-maven-plugin/3.12.1/quarkus-maven-plugin-3.12.1.pom: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

**Comment by gsmet** [comment]
Do you have a Maven proxy of some sort? Or are you using a very old Java version? (check with `mvn -v`)

It looks like the certificate you get when contacting https://repo.maven.apache.org/maven2 is not recognized by your Java.

**Comment by rinmalavi** [comment]
This is a proxy issue.
Sorry about irrelevant ticket.
