### ISSUE TITLE
Oracle: TNS URL Format is not supported when connecting to Autonomous DB

### ISSUE THREAD

**Issue by rbaumgar** [quarkusio/quarkus#41708]
### Describe the bug

Try to connect to an Oracle Autonomous DB with the `quarkus-reactive-oracle-client`.

vertx-reactive:oracle:thin:@(description=(address=(protocol=tcps)(port=1521)(host=adb.somewhere.oraclecloud.com))(connect_data=(service_name=abcdef_demodb_tpurgent.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))

Caused by: io.vertx.core.VertxException: TNS URL Format is not supported

Works fine with "normal" DBs.
connection_string=myhost:1521/mydb
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=${user}
quarkus.datasource.password=${password}

Work around:
create a file in /tnsnames/tnsnames.ora with
atp_tp=(description=...
and set the connection to
atp_tp?TNS_ADMIN=/tnsnames/

Documentation at https://quarkus.io/guides/datasource#jdbc-url points to https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/data-sources-and-URLs.html#GUID-8D0ADAE6-B8EF-4E02-85E3-15C2509ACBD8

Which means "(description..." should work fine.

### Output of `java -version`

17

### Quarkus version or git rev

3.11

**Comment by cescoffier** [comment]
@tsegismont, that's something that needs to be added to the Oracle reactive client, right?

**Comment by rbaumgar** [comment]
@tsegismont it is already solved in vertx-sql-client, https://github.com/eclipse-vertx/vertx-sql-client/issues/1156

**Comment by tsegismont** [comment]
@rbaumgar This is the issue tracking TNS Alias connection format (the workaround you described)

**Comment by cescoffier** [comment]
So, if I understand correctly it's not something currently supported by the Vertx client. Please open an issue in the upstream project.

**Comment by tsegismont** [comment]
The doc for Reactive Oracle client URL is correct: https://quarkus.io/guides/datasource#oracle-2

**Comment by rbaumgar** [comment]
@tsegismont, I see now where the misunderstanding is coming from. I was looking at the JDBC reference and not the reactive reference.
