### ISSUE TITLE
quarkus.swagger-ui.path doesn't accept environment variables as its value

### ISSUE THREAD

**Issue by limadelrey** [quarkusio/quarkus#4172]
Hey,

I'm using quarkus-smallrye-openapi maven dependency to take advantage of automatic OpenApi specifications and Swagger UI. In order to do that I've coded the following configurations on application.properties file:

```
quarkus.smallrye-openapi.path=/open-api
quarkus.swagger-ui.path=${PATH:default-path}
```

OpenApi is working fine. However, Swagger UI is being retrieved on {{host}}/default-path (which is the default value for $PATH environment variable) when it should be retrieved by {{host}}/{{PATH}} (e.g. http://localhost:8080/swagger-ui). 

This is specially important because I'm deploying this Quarkus application behind an Ingress controller on a Kubernetes cluster and Swagger UI can't aggregate Ingress path without changing its quarkus.swagger-ui.path property dynamically.

Is there any workaround?

Thank you in advance.

**Comment by gsmet** [comment]
@dmlloyd looks like we have a new one for the environment variable issue :).

**Comment by geoandri** [comment]
The same configuration parameters cannot be overridden via a runner jar as well.
`java -jar -Dquarkus.swagger-ui.path=/test-path/swagger-ui target/using-openapi-swaggerui-1.0-SNAPSHOT-runner.jar` does not work.

**Comment by gsmet** [comment]
> The same configuration parameters cannot be overridden via a runner jar
as well.

Isn't that expected? quarkus.swagger-ui.path is build time config.

**Comment by geoandri** [comment]
Yes, you 're right. It works as expected at this case.

**Comment by sirAlexanderT** [comment]
> Hey,
> 
> I'm using quarkus-smallrye-openapi maven dependency to take advantage of automatic OpenApi specifications and Swagger UI. In order to do that I've coded the following configurations on application.properties file:
> 
> ```
> quarkus.smallrye-openapi.path=/open-api
> quarkus.swagger-ui.path=${PATH:default-path}
> ```
> 
> OpenApi is working fine. However, Swagger UI is being retrieved on {{host}}/default-path (which is the default value for $PATH environment variable) when it should be retrieved by {{host}}/{{PATH}} (e.g. http://localhost:8080/swagger-ui).
> 
> This is specially important because I'm deploying this Quarkus application behind an Ingress controller on a Kubernetes cluster and Swagger UI can't aggregate Ingress path without changing its quarkus.swagger-ui.path property dynamically.
> 
> Is there any workaround?
> 
> Thank you in advance.

I'm currently facing the same issue, on both quarkus 1.5.2.Final and 1.6.0.CR1. Would appreciate if anyone could point me to a fix. Thanks.

**Comment by sirAlexanderT** [comment]
@limadelrey How did you get around this?

**Comment by limadelrey** [comment]
@sirAlexanderT Regarding OpenAPI & Swagger UI, there's a second issue that's been already addressed by Quarkus team: https://github.com/quarkusio/quarkus/issues/4200.

Is your problem about the usage of environment variables as properties?
