### ISSUE TITLE
Jbang - Unable to pass configuration

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#41739]
### Describe the bug

The configuration cannot be passed anymore when using JBang:

For example, this fails:
```java
//Q:CONFIG working-groups.project-prefix=wg

// ...

    @ConfigProperty(name = "working-groups.project-prefix")
    String prefix;
```

**Comment by maxandersen** [comment]
https://github.com/quarkusio/quarkus/issues/30087 duplicate I haven't found good solution for. 

Besides using //FILES application.properties

**Comment by gastaldi** [comment]
Duplicates #30087
