### ISSUE TITLE
JBang + Qute - Where should be the templates?

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#41740]
### Describe the bug

It's more a question than a bug.

Where should the `templates` directory be when using JBang with Qute? I can recreate my Qute Engine, but I want to avoid this. 

I tried in the `src` directory alongside my `main.java` file. I also tried from the root directory. None of them worked. It's more

**Comment by ia3andy** [comment]
This works: https://github.com/ia3andy/quarkus-reveal/blob/main/QuarkusReveal.java

**Comment by maxandersen** [comment]
You need to map in using //FILES as Andy shows. The locations are what quarkus uses anyway in the jar. 

That will make it work at build/runtime but devmode might make assumptions that sources are in some special hardcode place dependent on how the extension you use are implemented.
