### ISSUE TITLE
New TLS registry: How to configure certificate reload period?

### ISSUE THREAD

**Issue by sdavids** [quarkusio/quarkus#41758]
### Describe the bug

https://quarkus.io/guides/tls-registry-reference

There is no example of how to configure the certificate reload period.

### Expected behavior

There is a migration example for:

```
quarkus.http.ssl.certificate.files=cert.pem
quarkus.http.ssl.certificate.key-files=key.pem
quarkus.http.ssl.certificate.reload-period=30s
```
⇓

```
quarkus.tls.key-store.pem.0.cert=cert.pem
quarkus.tls.key-store.pem.0.key=key.pem
??? quarkus.tls.key-store.pem.0.reload-period=30s ???
```

### Quarkus version or git rev

3.12.1

**Comment by geoand** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
That feature has not been released yet, but you can see the "next-to-be" documentation on: https://quarkus.io/version/main/guides/tls-registry-reference#reloading-certificates

Note that the TLS registry, unlike the previous approach let you implement your own _reloader_ (so not only periodic)

**Comment by michalvavrik** [comment]
I just wrote automated test for this and works like charm. Also there is docs released now https://quarkus.io/guides/tls-registry-reference#periodic-reloading. I will close this as I think it's fine.

**Comment by sdavids** [comment]
Should it be mentioned in a [Migration Guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0)?

Or is it handled by `quarkus update` automatically?

… or would this be a new issue?

**Comment by michalvavrik** [comment]
> Should it be mentioned in a [Migration Guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0)?

Migration guide is for migration. So you mean for example between from `quarkus.http.ssl.certificate.reload-period` to `quarkus.tls.reload-period` and from `quarkus.management.ssl.certificate.reload-period` to `quarkus.tls.reload-period`? I think their implementation differs, but you can use both. 

> Or is it handled by `quarkus update` automatically?

My observation is that for now, the old ways to configure certificates are not deprecated, therefore is no migration required. TLS registry is wonderful option, but I have reviewed PRs integrating it to other extensions and didn't find that any migration was required. That said, I don't know plan, it's just what I assume based on PRs.
 
> … or would this be a new issue?

you can always open one if you see space for improvement :-) I am not a source of truth
