### ISSUE TITLE
Enhance Keycloak Integration tests

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4175]
**Description**
`integration-tests/keycloak` should run against a Keycloak IDP bootstrapped in a separate process/container

**Implementation ideas**
Make sure a Keycloak docker image is started before the tests are run, have the client test code working with the dynamically created tokens

**Comment by sberyozkin** [comment]
@pedroigor, @sebastienblanc Hi, if you are already aware of some template pom configuration which can get a KC IDP loaded then please comment or update the tests whenever time allows :-), cheers

**Comment by pedroigor** [comment]
@sberyozkin, IIRC, the integration tests for the keycloak extension is using containers to bootstrap the server during test execution. Or do you mean to something else ?

**Comment by sberyozkin** [comment]
@pedroigor ignore me please, another pint on me :-), I was under impressions there were only mocked tests there. sorry
