### ISSUE TITLE
VirtualThreadExtension does not take super classes into account

### ISSUE THREAD

**Issue by bdeneuter** [quarkusio/quarkus#41782]
### Describe the bug

A lot of our test classes have a single super class which contains the `@ShouldNotPin` annotation. The class VirtualThreadExtension does not take super classes into account when determing if recording is needed:
https://github.com/quarkusio/quarkus/blob/main/independent-projects/junit5-virtual-threads/src/main/java/io/quarkus/test/junit5/virtual/internal/VirtualThreadExtension.java#L65

### Expected behavior

When a super class declares the `@ShouldNotPin` annotation that the extension validates that no pinning occurs.

### Actual behavior

The `@ShouldNotPin` annotation is ignored

**Comment by cescoffier** [comment]
Fancy a PR as you found the place where we need to check for the super class?

**Comment by bdeneuter** [comment]
Yes, of course. When I find the time I will create the PR
