### ISSUE TITLE
Resteasy Reactive AsyncFile is never closed

### ISSUE THREAD

**Issue by Mulgish** [quarkusio/quarkus#41811]
### Describe the bug

AsyncFile is never closed in Resteasy Reactive HTTP server

### Expected behavior

AsyncFile should be closed

### Actual behavior

AsyncFile is not closed:
![image](https://github.com/quarkusio/quarkus/assets/27741935/4f1cf401-7977-4bd3-937a-ac64d117414d)

### How to Reproduce?

1. Return `AsyncFile` in Resteasy Reactive route
2. Put a breakpoint on `AsyncFIle#close`
3. Attempt to download the file
4. Observe that `AsyncFIle#close` has not been called
5. (Optional) When testing on an NFS share, try to delete test file and observe `.nfsxxxxxxx` file being created [due to open file handle](https://docs.oracle.com/en-us/iaas/Content/File/Troubleshooting/nfsxxxxxxxxxx.htm).
6. (Optional) Observe that shutting down Quarkus service removes `.nfsxxxxxxx` file

#### Reproducer repository
https://github.com/Mulgish/quarkus-issue-41811-reproducer
See README for steps.

#### Example code
```java
package com.bla;

import io.smallrye.mutiny.Uni;
import io.vertx.core.file.OpenOptions;
import io.vertx.mutiny.core.Vertx;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.Response;


import static jakarta.ws.rs.core.MediaType.*;

@ApplicationScoped
@Path("/downloads")
public class DownloadsEndpoint {

    public static final OpenOptions READ_ONLY = new OpenOptions()
        .setRead(true).setWrite(false);

    @Inject
    Vertx vertx;

    @GET
    @Path("/someFile")
    @Produces(APPLICATION_OCTET_STREAM)
    public Uni<Response> downloadFile() {
        return vertx.fileSystem()
            .open("/tmp/someFile.txt", READ_ONLY)
            .onItem().transform(asyncFile -> Response.ok(asyncFile).build());
    }
}
```

### Output of `uname -a` or `ver`

Linux 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 OpenJDK Runtime Environment (Red_Hat-21.0.3.0.9-1) (build 21.0.3+9) OpenJDK 64-Bit Server VM (Red_Hat-21.0.3.0.9-1) (build 21.0.3+9, mixed mode, sharing)

### Quarkus version or git rev

3.12.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (Red Hat 3.9.6-6) Maven home: /usr/share/maven Java version: 21.0.3, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-21-openjdk-21.0.3.0.9-1.fc40.x86_64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.146.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

### Additional information

I have noticed this issue because I was getting .nfsxxxxx files created on an NFS share everytime I would delete a file after streaming it with [FIlesystem.open](https://vertx.io/docs/apidocs/io/vertx/core/file/FileSystem.html#open-java.lang.String-io.vertx.core.file.OpenOptions-) call.

Switching to [Filesystem.readFIle](https://vertx.io/docs/apidocs/io/vertx/core/file/FileSystem.html#readFile-java.lang.String-io.vertx.core.Handler-) has fixed the issue but it is not ideal as I can not stream large files to a client.

**Comment by geoand** [comment]
Can you please attach a sample project that shows the problem in action?

**Comment by Mulgish** [comment]
@geoand Sure, I will need dome time to prepare it.

**Comment by geoand** [comment]
Thanks!

**Comment by mschorsch** [comment]
@Mulgish Does this also happen when you return `Uni<AsyncFile>` instead of `Uni<Response>`?

**Comment by Mulgish** [comment]
> @Mulgish Does this also happen when you return `Uni<AsyncFile>` instead of `Uni<Response>`?

Yes

**Comment by Mulgish** [comment]
@geoand I have created a reproducer at https://github.com/Mulgish/issue-41811-reproducer.
Please see README file for steps to reproduce.

**Comment by geoand** [comment]
Thanks a lot!

https://github.com/quarkusio/quarkus/pull/41824 fixes the issue
