### ISSUE TITLE
grpc-server gets deactivated if no proto file and corresponging implementation is present

### ISSUE THREAD

**Issue by ncabanis** [quarkusio/quarkus#41861]
### Describe the bug

If both extensions "grpc" and "kotlin" are active, then when running the application in non-dev-mode, the feature "grpc-server" is missing. In dev-mode, it works.

### Expected behavior

grpc and kotlin should work together also in production mode

### How to Reproduce?

[code-with-quarkus.zip](https://github.com/user-attachments/files/16195613/code-with-quarkus.zip)

1. create the app with gRPC, Rest and Kotlin, using Gradle Kotlin DSL
e.g: https://code.quarkus.io/?b=GRADLE_KOTLIN_DSL&e=grpc&e=rest&e=kotlin
2. `./gradlew quarkusBuild`
3. `java -jar build/quarkus-app/quarkus-run.jar`
4. observe in installed features, grpc-server is missing: 
Installed features: [cdi, kotlin, rest, smallrye-context-propagation, vertx]

by the way: `./gradlew quarkusRun` also does not work

### Output of `uname -a` or `ver`

Darwin ADC-MB20046 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment Zulu21.28+85-CA (build 21+35) OpenJDK 64-Bit Server VM Zulu21.28+85-CA (build 21+35, mixed mode, sharing)

### Quarkus version or git rev

3.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

❯ ./gradlew --version  ------------------------------------------------------------ Gradle 8.8 ------------------------------------------------------------  Build time:   2024-05-31 21:46:56 UTC Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082  Kotlin:       1.9.22 Groovy:       3.0.21 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          21 (Azul Systems, Inc. 21+35) OS:           Mac OS X 14.5 aarch64

**Comment by cescoffier** [comment]
Do you have a gRPC service defined? 

In dev mode we always run the gRPc server (for the reflection service), but because this service is disabled by default in production mode, the gRPC server may disable itself as there are no services to serve.

**Comment by ncabanis** [comment]
Yes, I have a service annotated with `io.quarkus.grpc.GrpcService` included.
In the dev-ui, it is also listed here: http://localhost:8080/q/dev-ui/io.quarkus.quarkus-grpc/services
But the proto file is not within this project, but externally defined.

**Comment by ncabanis** [comment]
I also tried: if I remove the Kotlin extension, then it works as expected.
(I generated plain starters with different features selected.)

**Comment by ncabanis** [comment]
The IDE also complains about "Kotlin not configured".
Even though the Kotlin editing, running etc. seems to work normally.
![image](https://github.com/user-attachments/assets/c575e457-7468-4219-bbbe-a91c1fccb230)

**Comment by ncabanis** [comment]
Hmm, I tried again my project now without Kotlin and it does not work. Maybe I was wrong in the assumption that there is a connection.

**Comment by cescoffier** [comment]
Wondering why it does not find the service in that case. I would say it's a bug.

**Comment by cescoffier** [comment]
Does your dependency contains not only the proto file but also the generated code. If that's the case that's actually the expected behavior.

We recommend to either:

- jandex your dependency or force indexing in Quarkus
- configure Quarkus gRPC to re-generate the generated files from the proto file

**Comment by geoand** [comment]
Closing for lack of feedback. 

If the requested information becomes available, we can reopen

**Comment by ncabanis** [comment]
The proto files and the generated code is contained in this jar: `opentelemetry-proto-1.3.1-alpha.jar`

About your recommendations: if I re-generate the code, I would end up with the same classes multiple times on the classpath, which is probably not the best idea.

How do I force indexing in Quarkus?

**Comment by pauldpearson** [comment]
For prod profile using docker compose I had to set these
quarkus.index-dependency.mywinecellar-grpc-protos.group-id=
quarkus.index-dependency.mywinecellar-grpc-protos.artifact-id=

I have a similar setup I believe with my proto lib being pulled in as a dependency and the grpc-server was not being listed as an extension.

**Comment by ognivo777** [comment]
I faced with same strange behaviour as mentions above. In development mode I successfully used externally generated grpc stubs from dependency (in my case - `io.camunda:zeebe-gateway-protocol-impl:8.5.18`) without any proto files in my project, but when I try to build and run the application I see that no feature grpc-server is installed.

**Comment by cescoffier** [comment]
Make sure you _jandex_ the `io.camunda:zeebe-gateway-protocol-impl:8.5.18` dependency.

```
quarkus.index-dependency.<name>.group-id=
quarkus.index-dependency.<name>.artifact-id=(this one is optional)
quarkus.index-dependency.<name>.classifier=(this one is optional)
```

**Comment by ognivo777** [comment]
This dependency only contains gRPC stubs — no CDI beans. I implemented the service myself and annotated it with @GrpcService. To test, I added a minimal proto file and service class to the project. After that, grpc-server started successfully and my original service also worked. So it's likely not a CDI/jandex issue, but rather how Quarkus decides what features to activate.

**Comment by ognivo777** [comment]
> Make sure you _jandex_ the `io.camunda:zeebe-gateway-protocol-impl:8.5.18` dependency.
> 


I did a second test: removed the additional proto file and service, and added the mentioned dependency to Jandex:
```
quarkus.index-dependency.zeebe-gw-api.group-id=io.camunda
quarkus.index-dependency.zeebe-gw-api.artifact-id=zeebe-gateway-protocol-impl
```
 Indeed, grpc-server started successfully and everything worked as expected — thank you!

However, the question remains: why is the behavior so different between dev and prod profiles? It's a bit confusing.
