### ISSUE TITLE
Mailer: In dev mode send emails in all locales

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#41879]
### Description

When you are in dev mode, it would be nice if an email was sent in all locales defined in `quarkus.locales`.

**Comment by melloware** [comment]
@gbourant can you be more clear?  Do you mean your Qute template run through all locales and sent?

**Comment by gbourant** [comment]
> @gbourant can you be more clear? Do you mean your Qute template run through all locales and sent?

Yes, when you send an email and you are in dev mode, it should send it in all locales for debugging purposes. (maybe it should be enabled via a config option).

So if you have defined 3 locales and you send a single e-mail, it should have sent 3 emails in 3 different locales.

**Comment by gbourant** [comment]
Well, i was thinking about that and i came up with this

```java
@ApplicationScoped
public class MailService {

    @Inject
    I18N i18n;

    public void send(MailTemplate.MailTemplateInstance mailTemplateInstance, String emailType, String subjectKey, Object... params) {
        if (LaunchMode.current() == LaunchMode.DEVELOPMENT) {
            for (String locale : Globals.locales()) {
                i18n.setForCurrentRequest(locale);
                doSend(mailTemplateInstance, subjectKey, params);
            }
        } else {
            doSend(mailTemplateInstance, subjectKey, params);
        }
    }

    private void doSend(MailTemplate.MailTemplateInstance mailTemplateInstance, String subjectKey, Object... params) {
        mailTemplateInstance
                .subject(i18n.formatMessage(subjectKey, params))
                .send()
                .await()
                .atMost(Duration.ofSeconds(10));

    }
}
```

**Comment by geoand** [comment]
I can say that if I were using Quarkus and came across this while developing, I would be very surprised at the behavior and perhaps annoyed of this default

**Comment by melloware** [comment]
@gbourant  I think @geoand and myself are both -1 on this feature.  Since you have a local fix do you want to close this ticket or do you still feel strongly about it?

**Comment by gbourant** [comment]
Yeap, it's ok.
