### ISSUE TITLE
When calling `/q/metrics` once, `http_server_bytes_written_count` increases by 2

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkus#41884]
### Describe the bug

`http_server_bytes_written_count` increases by 2 per single `/q/metrics` invocation, 

### Expected behavior

`http_server_bytes_written_count` should increase once when  `/q/metrics` is invoked

### Actual behavior

When `/q/metrics` is invoked, `http_server_bytes_written_count` increases by 2

Also, even if there is no content-length (body) in GET requests, shouldn't `http_server_bytes_read_count` increase by 1 per each GET request?

### How to Reproduce?

1. Basic Quarkus project with a REST API (1 POST and 1 GET), and `quarkus-micrometer-registry-prometheus`, `quarkus-smallrye-health` extensions.
2. Call `/q/metrics`, `/q/health` or any user GET API.

### Output of `java -version`

openjdk version "17.0.11" 2024-04-16

### Quarkus version or git rev

3.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7

**Comment by cescoffier** [comment]
I reproduced it.
It only happens for /metrics (and not the other framework routes or business routes)

**Comment by cescoffier** [comment]
It's not a bug.

It could happen with any response larger than the max "chunk". Let me explain.
The Prometheus response is large enough to exceed this limit. This means that there is not a single write at the TCP level but two (one at capacity and then the remaining). So, we increment the counter twice.
