### ISSUE TITLE
Please provide `quarkus image build --push` parameter

### ISSUE THREAD

**Issue by weltonrodrigo** [quarkusio/quarkus#41882]
### Description

It's cumbersome having to write `quarkus image build -Dquarkus.container-image.push=true`.

In my understanding the quarkus cli is a helper to simplify interaction with the quarkus maven (and gradle, I suppose) plugins. As such it has created a ergonomic DSL to improve productivity.

I believe the `--push` would be a nice addition to that, but I see that this argument will have to be present in other commands that have an `--image-build` argument, like:

`quarkus deploy kubernetes --image-build -Dquarkus.container-image.push=true` would have to become ``quarkus deploy kubernetes --image-build --image-build-push` and so on.

I also understand that having `-D` arguments some kind of central registry of parameters instead of surfacing parameters to the DSL is a nice compromise, but I also believe that `--push` is such a common use that it justifies it.

Thanks for this AMAZING software, both quarkus and the quarkus CLI. ♥️

Update: bot,  mark this as quarkus cli, please.

**Comment by geoand** [comment]
I think this makes sense!

WDYT @iocanel

**Comment by iocanel** [comment]
I think there already something like this.

**Comment by geoand** [comment]
I see there is `quarkus image push`

**Comment by iocanel** [comment]
Exactly. `quarkus image push --also-build` should do the trick.

**Comment by weltonrodrigo** [comment]
Closing because there is already an alternative.
