### ISSUE TITLE
Allow reload trigger to watch for config changes

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#41895]
### Description

When we currently save `application.properties`, it doesn't trigger dev mode reload. We need to trigger reload in another way (HTTP request, manually, pom.xml save, etc.). Also, saving the config in DevUI does trigger live reload.

I wonder if we could add a config property like `quarkus.devmode.trigger` that could extend which files would be watched for save triggers. Values, for instance, `config`, `*.java`, `*Test.java`.

This is open for community feedback. Please comment on this issue.

**Comment by xstefank** [comment]
Discussed in https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Why.20no.20reload.20on.20application.2Eproperties.20save.3F. TBH, I'm not sure if having a config for something that can be implemented with continuous testing and a simple ping test is necessary. If no one comments otherwise I'll close this by the end of the week.

**Comment by geoand** [comment]
-1 as well

**Comment by maxandersen** [comment]
no usecase provided; lets close it. feel free to open new  if there are a case where autoreload is useful without doing any user action (i.e. send a request or have test code call the quarkus app)
