### ISSUE TITLE
Websocket quickstart failing

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#4190]
The tests of the Websocket quickstart are failing in native mode. No exception, just that the message doesn't seem to be broadcast properly (or the test client doesn't get it for whatever reason).

I tested the native image manually and the chat app seems to work. That being said, there is another issue: once we have used the chat a bit, it's impossible to stop the application with a `^C`. I had to use a `kill -9` to get it to finish. Not sure if it's the normal behavior.

**Comment by gastaldi** [comment]
@gsmet I couldn't reproduce the issue with 1.0.0.CR1. I ran `mvn integration-test -Dnative` in https://github.com/quarkusio/quarkus-quickstarts/tree/1.0.0.CR1/websockets-quickstart and the `ChatITCase` passed. 

Can you verify if this is still reproducible in your environment?

**Comment by gsmet** [comment]
Yeah, it has been fixed a while ago.
