### ISSUE TITLE
Qute: single quotes in variables break string

### ISSUE THREAD

**Issue by markus-lehr-dedalus** [quarkusio/quarkus#41918]
### Describe the bug

When declaring a variable inside a Qute template using `#let="..."`, the variable can only contain single quotes if they come in pairs and don't contain spaces.

i.e. This works
```
{#let variable="'oneWord'"}
{variable}
{/let}
```

This breaks
```
{#let variable="apostrophe'"}
{variable}
{/let}
```
With the exception:
io.quarkus.qute.TemplateException: Parser error: unexpected non-text buffer at the end of the template - unterminated string literal: #let variable="apostrophe'"}

Escaping the apostrophe using `{#let variable="apostrophe\'"}` does not help.

This breaks as well
```
{#let variable="'two words'"}
{variable}
{/let}
```
With the exception:
io.quarkus.qute.TemplateException: Rendering error: Entry "words'"" not found in the data map in expression {words'"}

### Expected behavior

Single quotes in double quotes and vice versa don't impact each other. I should be able to use single quotes non-pairwise in double quotes. 

### Actual behavior

Various parser errors happen when declaring the variable 
io.quarkus.qute.TemplateException: Parser error: unexpected non-text buffer at the end of the template - unterminated string literal: #let variable="apostrophe\'"}

io.quarkus.qute.TemplateException: Rendering error: Entry "words'"" not found in the data map in expression {words'"}

### How to Reproduce?

```java
@Test
public void testFunctionParsing() {
    Engine engine = Engine
        .builder()
        .addDefaults()
        .build();
    String templateString = "" +
        "{#let variable=\"'hello world'\"}" +
        "{variable}" +
        "{/let}";
    Template template = engine.parse(templateString);
    String result = template.render();
    Assertions.assertEquals("'hello world'", result);
}
```

### Output of `uname -a` or `ver`

Linux hostname 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

 openjdk version "17.0.9" 2023-10-17 LTS OpenJDK Runtime Environment Corretto-17.0.9.8.1 (build 17.0.9+8-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.9.8.1 (build 17.0.9+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.16.12.Final and 3.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by geoand** [comment]
> 2.16.12.Final

This is a very old and totally unsupported version. Please try the latest Quarkus version or the latest LTS

**Comment by geoand** [comment]
Thanks
