### ISSUE TITLE
OIDC: List of JWKS is not checked without specified kid

### ISSUE THREAD

**Issue by c15yi** [quarkusio/quarkus#41931]
### Describe the bug

I want to protect my resource with the `@Authenticated` annotation and have an oidc `quarkus.oidc.auth-server-url` defined.
From the `jwks_uri` endpoint I have these keys:

``` JSON
{
    "keys": [
        {
            "n": "value for n",
            "e": "AQAB",
            "kty": "RSA",
            "kid": "fQ-Uyjg7QvTpf_mn9yKXmeYPsPE",
            "x5t": "fQ-Uyjg7QvTpf_mn9yKXmeYPsPE",
            "use": "sig"
        },
        {
            "n": "value for n",
            "e": "AQAB",
            "kty": "RSA",
            "kid": "sgw",
            "x5t": "sgw",
            "use": "sig"
        },
        {
            "n": "value for n",
            "e": "AQAB",
            "kty": "RSA",
            "kid": "msgw",
            "x5t": "msgw",
            "use": "sig"
        }
    ]
}
```

My JWS looks like this:

``` JSON
{
    "alg": "RS256"
}
{
    "iss": "https://example.domain.com/openid",
    "sub": "",
    "exp": 1721139705,
    "nbf": 1721138805,
    "iat": 1721138805,
    "jti": "d9e88d72-78fe-430f-8ff3-391161622986",
    "aud": "1234423458943498493883498432348293"
}
<signature>
```

Not completely sure, whether this is a but or intended behaviour, but regarding the [JWS documentation](https://datatracker.ietf.org/doc/html/rfc7515#appendix-D) multiple keys could be used to verify the signature.

The "issue" seems to be, that the keys are not checked for best effort, but Quarkus is rather looking for a matching kid or falls back to `keyWithoutKeyIdAndThumbprint` (OidcProvider.java:480), which is empty, because all keys have an id set.

Would it make sense, to take all available keys into account before OidcProvider.java:492 to have another fallback for verifying the signature?

### Expected behavior

The JWS is correctly verified with one of the provided keys.

### Actual behavior

No key is selected for verification, therefore failing with this message (decoded token content can be seen above):

```
Unable to process JOSE object (cause: org.jose4j.lang.UnresolvableKeyException: JWK is not available, neither 'kid' nor 'x5t#S256' nor 'x5t' token headers are set): JsonWebSignature{"alg":"RS256"}->{token content}
```

### How to Reproduce?

1. Have multiple JWKS keys all with a `kid`
2. Don't specify `kid` in the JWS
3. JWS verification will fail, because no key will be selected for verification

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.3880]

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Corretto-21.0.3.9.1 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.3.9.1 (build 21.0.3+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.8 ------------------------------------------------------------   Build time:   2024-05-31 21:46:56 UTC Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082   Kotlin:       1.9.22 Groovy:       3.0.21 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          21.0.3 (Amazon.com Inc. 21.0.3+9-LTS) OS:           Windows 11 10.0 amd64

**Comment by sberyozkin** [comment]
@c15yi  Hi,

We can do it, but IMHO it is definitely not a bug but an enhancement request. In your example, you have 3 RSA keys, so if it were done by default, it would be expensive to fail 2 RSA signature verifications and finally verify it with the last key, in the worst case. And if it is a large set, like the one one can see in Azure accounts, it will be really expensive.

FYI, I won't have time to look at it in the next few weeks due to other commitments and traveling. 

If you'd like, please consider opening a PR. I believe we should let users opt in with a property like `quarkus.oidc.jwks.try-all`, which if enabled, would pick up all the keys with a matching algorithm and retry with the next key in case of the signature exception only

**Comment by c15yi** [comment]
As far as I could see, verifying with multiple keys would also require substantial changes in the code base, because everything is build for evaluating only a single key. Therefore, we found another solution to make our case work.
