### ISSUE TITLE
Auto configure prometheus scraping for lgtm dev service

### ISSUE THREAD

**Issue by jtama** [quarkusio/quarkus#41944]
### Description

If `quarkus-micrometer` extensions is used it can be configured to push metrics to prometheus. I think the same could be achieved if `quarkus-micrometer-registry-prometheus` extension is used.

@melloware already produced a snipet here 
https://github.com/quarkusio/quarkus/issues/40933#issuecomment-2168344159, (I think there may be an issue with the target.

I guess it could be done only if `quarkus-micrometer-registry-prometheus` is used.

**Comment by melloware** [comment]
@jtama in my PR I fixed the pathing issue to look up the proper scrape.

```java
private String getPrometheusConfig() {
        Config runtimeConfig = ConfigProvider.getConfig();
        String rootPath = runtimeConfig.getOptionalValue("quarkus.management.root-path", String.class).orElse("/q");
        String metricsPath = runtimeConfig.getOptionalValue("quarkus.management.metrics.path", String.class).orElse("/metrics");
        int httpPort = runtimeConfig.getOptionalValue("quarkus.http.port", Integer.class).orElse(0);
        PrometheusYamlFile prometheusYamlFile = new PrometheusYamlFile(config.serviceName(), rootPath, metricsPath,
                "host.docker.internal", httpPort);
        return prometheusYamlFile.createPrometheusYamlFile();
    }
```

**Comment by jtama** [comment]
this pr would definitely close this issue : https://github.com/quarkusio/quarkus/pull/41264/files

**Comment by melloware** [comment]
I linked my PR to this ticket.

**Comment by Legion2** [comment]
If the management interface uses a different port that the default quarkus http port this scraping config does not work. If the management interface is enabled, the `quarkus.management.port` port should be used instead in the scrape config.
