### ISSUE TITLE
implements ReaderInterceptor, WriterInterceptor could not get response headers

### ISSUE THREAD

**Issue by yangyuanqiang** [quarkusio/quarkus#41946]
### Describe the bug

1. When i use Multi<String>，in aroundReadFrom method, System.out.println(context.getHeaders());//console print: []；But with Uni<String>，context.getHeaders() will get response's headers；I wonder if there's a problem...
2. If i want to propagate X-Request-Id(a request header attribute), from aroundWriteTo method to aroundReadFrom method，Should i use [ThreadLocal]??? Or what should i do?

```java
@Path("/hello")
public class ExampleResource {

    @RestClient
    MyRemoteService myRemoteService;

    @GET
    @Path("chart")
    @RestStreamElementType(MediaType.APPLICATION_JSON)
    public Multi<String> chart() {
        String token = "";
        Map<String, String> msg = new HashMap<>();
        msg.put("content", "Write a 1000-word news article about OpenAI");
        msg.put("role", "user");

        ArrayList<Map<String, String>> arrayList = new ArrayList<>();
        arrayList.add(msg);

        ChatParam param = new ChatParam();
        param.max_output_tokens = 1500;
        param.messages = arrayList;
        param.setStream(true);

        return myRemoteService.doSseChart(param, token);
    }
}

@RegisterRestClient(baseUri = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop")
public interface MyRemoteService {

    @POST
    @Path("/chat/ernie-4.0-turbo-8k")
    @RestStreamElementType(MediaType.APPLICATION_JSON)
    Multi<String> doSseChart(ChatParam param, @QueryParam("access_token") String token);
}

@Provider
@ConstrainedTo(RuntimeType.CLIENT)
public class ClientInterceptor implements ReaderInterceptor, WriterInterceptor {

    ThreadLocal<String> threadLocal = new ThreadLocal<>();

    @Override
    public Object aroundReadFrom(ReaderInterceptorContext context) throws IOException, WebApplicationException {
        System.out.println("--------------------------");
        System.out.println(context.getHeaders());//console print: []
        System.out.println("--------------------------");

        //Should i use [ThreadLocal] like this?
        String requestId = threadLocal.get();
        System.out.println(requestId);
        return context.proceed();
    }

    @Override
    public void aroundWriteTo(WriterInterceptorContext context) throws IOException, WebApplicationException {
        //TODO
        String requestId = (String) context.getHeaders().getFirst("X-Request-Id");
        threadLocal.set(requestId);

        context.proceed();
    }
}
```

### Expected behavior

1. In aroundReadFrom method,context.getHeaders() return response headers.
2. With reactive Multi<String> request and response,**public class ClientInterceptor implements ReaderInterceptor, WriterInterceptor** How to propagate some properties(like requestId、traceId、user,and etc)；Is there any problem with using ThreadLocal?

### How to Reproduce?

https://github.com/yangyuanqiang/quarkus-ai.git

### Output of `java -version`

openjdk version "17.0.11" 2024-04-16 LTS OpenJDK Runtime Environment Zulu17.50+19-CA (build 17.0.11+9-LTS) OpenJDK 64-Bit Server VM Zulu17.50+19-CA (build 17.0.11+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: D:\Develop\apache-maven-3.9.6 Java version: 17.0.11, vendor: Azul Systems, Inc., runtime: C:\Users\yangyuanqiang\.jdks\azul-17.0.11 Default locale: zh_CN, platform encoding: GBK OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
Can you please attach a sample project that reproduces what you are seeing? Asking because I am not sure I understand what you are asking here.

**Comment by yangyuanqiang** [comment]
> Can you please attach a sample project that reproduces what you are seeing? Asking because I am not sure I understand what you are asking here.

Glad to see your reply.

sample project link:
https://github.com/yangyuanqiang/quarkus-ai.git

**Comment by geoand** [comment]
Thanks for the sample, I now understand what you are trying to do.


## Question 1

`ReaderInterceptor` does not have access to the headers when reading SSE data - although this may seem surprising it actually makes sense because the interceptor is invoked for each piece of data read from the server.

You can however use a `ClientResponseFilter` in order to read the headers. 

## Question 2

If I understand correctly what you are trying to do, then again you should use `ClientResponseFilter` and `ClientRequestFilter`. In the latter you can set an arbitrary property which you can then retrieve in the former.
