### ISSUE TITLE
Quarkus Diameter Stack

### ISSUE THREAD

**Issue by eddiecarpenter** [quarkusio/quarkus#41970]
### Description

The Diameter protocol is a computer networking protocol for Authentication, Authorization and Accounting (), as defined in RFC3588. It is extensively used in the 3GPP telecommunication industry.

JDiameter is an existing Java Diameter stack that supports the protocol. The implementation is quite old, and active support for it has stopped. 

The proposed Diameter extension proposes updating the JDiameter implementation so that it can be used in both a Quarkus JVM and a Native application.

If you are interested in this extension, please +1 via the emoji/reaction feature of GitHub (bottom left).

### Repository name

quarkus-diameter

### Short description

Quarkus Diameter Stack

### Repository Homepage URL

https://github.com/eddiecarpenter/quarkus-jdiameter forked from https://github.com/RestComm/jdiameter

### Repository Topics

- quarkus-extension
- JDiameter 

### Team Members

- Eddie Carpenter eddie.carpenter@icloud.com

**Comment by gastaldi** [comment]
https://github.com/quarkiverse/quarkus-jdiameter is now provisioned. See the next steps here: https://hub.quarkiverse.io/checklistfornewprojects/#after-the-repository-is-created

Enjoy!
