### ISSUE TITLE
Support Spring Data `JpaRepository#getReferenceById(ID)` (replacement for deprecated `getOne(ID)`)

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#41987]
### Description

`JpaRepository#getOne(ID)` was marked deprecated a long time ago: https://github.com/spring-projects/spring-data-jpa/issues/1697
and javadoc suggests to use `getReferenceById`: https://github.com/spring-projects/spring-data-jpa/pull/2398
In Quarkus, we are seeing this deprecation since #40344.

Now, when trying to use `getReferenceById` the following is thrown:
```
io.quarkus.spring.data.runtime.FunctionalityNotImplemented: Method getReferenceById of class foo.BarRepository_cbd379646a149ba2465a399aca3df36673c2a7c1Impl from Spring Data has not yet been implemented
```

### Implementation ideas

Support `getReferenceById` just like `getOne`

**Comment by geoand** [comment]
cc @aureamunoz

**Comment by famod** [comment]
Please note that #getById and #deleteInBatch are deprecated too.

**Comment by funnyDevGirl** [comment]
Hi!
Is it relevant, or has someone already taken up the task?

**Comment by aureamunoz** [comment]
Oups, just raised the PR with the change: https://github.com/quarkusio/quarkus/pull/41993

**Comment by famod** [comment]
Oh wow, that was quick - thanks all!
