### ISSUE TITLE
Stuck hibernate-orm-resteasy QS when running with Quarkus master in native mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#4198]
Stuck hibernate-orm-resteasy QS when running with Quarkus master in native mode
App seems to be started but tests are not executed. Noticed this on Linux box and on macOS machine too.

```
git clone https://github.com/quarkusio/quarkus-quickstarts.git
cd quarkus-quickstarts/hibernate-orm-resteasy
mvn clean verify -Dnative
...
[INFO] Running org.acme.hibernate.orm.NativeFruitsEndpointIT
Executing [/Users/rsvoboda/git/quarkus-quickstarts/hibernate-orm-resteasy/target/hibernate-orm-resteasy-1.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
Hibernate:

    drop table if exists known_fruits cascade
Hibernate:

    drop sequence if exists known_fruits_id_seq
Hibernate: create sequence known_fruits_id_seq start 10 increment 1
Hibernate:

    create table known_fruits (
       id int4 not null,
        name varchar(40),
        primary key (id)
    )
Hibernate:

    alter table if exists known_fruits
       add constraint UK_57g3m8wr3qxoj706a6hsqg6ye unique (name)
2019-09-25 10:08:31,382 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.120s. Listening on: http://0.0.0.0:8081
2019-09-25 10:08:31,383 INFO  [io.quarkus] (main) Profile prod activated.
2019-09-25 10:08:31,383 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb]
^C rsvoboda - hibernate-orm-resteasy $ date
Wed Sep 25 10:11:14 CEST 2019
```
Waited more than 2 minutes before hitting Ctrl+C

**Comment by gastaldi** [comment]
I tried with `mvn clean verify -Pnative -Dnative-image.docker-build=true` and haven't had any trouble. Maybe it's something in your local GraalVM?

**Comment by rsvoboda** [comment]
`mvn clean verify -Pnative -Dnative-image.docker-build=true` ends with following trouble because Linux targeted binary can't be run on macOS. So it doesn't help me much now :( I can try tomorrow on my Linux box.

```
[INFO] Running org.acme.hibernate.orm.NativeFruitsEndpointIT
Executing [/Users/rsvoboda/git/quarkus-quickstarts/hibernate-orm-resteasy/target/hibernate-orm-resteasy-1.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
/Users/rsvoboda/git/quarkus-quickstarts/hibernate-orm-resteasy/target/hibernate-orm-resteasy-1.0-SNAPSHOT-runner: /Users/rsvoboda/git/quarkus-quickstarts/hibernate-orm-resteasy/target/hibernate-orm-resteasy-1.0-SNAPSHOT-runner: cannot execute binary file
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 60.296 s <<< FAILURE! - in org.acme.hibernate.orm.NativeFruitsEndpointIT
[ERROR] testListAllFruits  Time elapsed: 0.081 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.hibernate.orm.NativeFruitsEndpointIT]: Unable to start native image in 60s
Caused by: java.lang.RuntimeException: Unable to start native image in 60s
```

The problem with the QS isn't that native binary can't be built. It seems that the binary starts properly, but tests are not started against binary. Like if it is waiting for something.

**Comment by rsvoboda** [comment]
I was using GraalVM 19.2.0 and to be sure I tried GraalVM 19.2.0.1 too.
And it behaves the same - QS execution gets stuck, tests against native binary don't get started.

I checked master branch (Quarkus 0.22.0) and everything works well

**Comment by gsmet** [comment]
What happens if you try to start the app yourself?

If it gets stuck, can you try to launch it with strace and see if there's anything useful when it gets stuck?

**Comment by gsmet** [comment]
Also, can you try with the 0.23.0 branch?

**Comment by rsvoboda** [comment]
@gsmet ok, will do

Something from master vs. 0.22.0 comparison:

Quarkus master:
```
Hibernate:

    alter table if exists known_fruits
       add constraint UK_57g3m8wr3qxoj706a6hsqg6ye unique (name)
2019-09-25 20:56:32,302 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.076s. Listening on: http://0.0.0.0:8081
2019-09-25 20:56:32,302 INFO  [io.quarkus] (main) Profile prod activated.
2019-09-25 20:56:32,302 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb]
```
Quarkus 0.22.0
```
Hibernate:

    alter table if exists known_fruits
       add constraint UK_57g3m8wr3qxoj706a6hsqg6ye unique (name)
Hibernate:
    INSERT INTO known_fruits(id, name) VALUES (1, 'Cherry')
Hibernate:
    INSERT INTO known_fruits(id, name) VALUES (2, 'Apple')
Hibernate:
    INSERT INTO known_fruits(id, name) VALUES (3, 'Banana')
2019-09-25 21:04:16,580 INFO  [io.quarkus] (main) Quarkus 0.22.0 started in 0.063s. Listening on: http://[::]:8081
2019-09-25 21:04:16,580 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb]
```

With Quarkus master there are no inserts. DB feeding doesn't happen

**Comment by rsvoboda** [comment]
hm, there is https://github.com/quarkusio/quarkus-quickstarts/commit/4717c348acbd7c466e455de6f36ee38233197371

let me rebase QS and rerun it

**Comment by gsmet** [comment]
So not having the inserts is expected, I fixed that here: https://github.com/quarkusio/quarkus-quickstarts/commit/4717c348acbd7c466e455de6f36ee38233197371 . I have an email ready for this issue, I will send it tomorrow.

**Comment by rsvoboda** [comment]
With Quarkus 0.23.0 quickstart passes

With Quarkus master quickstart is stuck. At least inserts are there ...

**Comment by gsmet** [comment]
This one has been fixed, it was the http handler not being declared in the quickstarts.

**Comment by rsvoboda** [comment]
@gsmet - https://github.com/quarkusio/quarkus-quickstarts/commit/167803fb5cf4d0632d3847422ee656d0ce45055a ?

Seems `enableHttpUrlHandler` should be by default true :) It's in every QS.

**Comment by gsmet** [comment]
Yeah, we need to think about it, and also how to potentially only enable https.
