### ISSUE TITLE
Panache for Hibernate ORM assumes the datasource has the same name as the persistence unit

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#42001]
### Describe the bug

See this code:

https://github.com/quarkusio/quarkus/blob/742f2262dda20da987d26a66860cca6e90539806/extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java#L87-L92

`new DataSource.DataSourceLiteral(persistentUnitName)` <= What is going on here?!

As a reminder, the name of the datasource can be completely different from the name of the persistence unit.

@geoand seems this is yours; is there such a thing as too much Monster Energy? :thinking: 

From what I can see this was introduced to "Provide actionable information when EntityManager is not available in Hibernate Panache". Not sure why this would involve looking up the datasource...

**Comment by geoand** [comment]
> is there such a thing as too much Monster Energy? 🤔

There is not

**Comment by geoand** [comment]
I need to have a look because I obviously have no idea recollection of me adding this (thank goodness for git)

**Comment by geoand** [comment]
I think we can safely just drop that checkl
