### ISSUE TITLE
Dev services use Mongodb 4.4 which is EOL

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#42045]
### Describe the bug

By default, Quarkus running in dev mode with mongodb extensions will start container of version 4.4, which reached end of life in February of 2024[1]. Since Quarkus is running fine with the latest (7.0) version of Mongodb, it makes sense to update the defaults

[1] https://www.mongodb.com/legal/support-policy/lifecycles

### Expected behavior

Quarkus dev services use the latest supported versions

### Actual behavior

Quarkus uses version 4.4, which reached EOL

### How to Reproduce?

1. Generate the app: ` wget -O app.zip 'https://code.quarkus.io/d?a=app&e=mongodb-panache&e=rest&cn=code.quarkus.io'`
2. `unzip app.zip && cd app`
3. `mvn quarkus:dev`
4. Check the version in another window:
```
$ podman ps
CONTAINER ID  IMAGE                                COMMAND               CREATED         STATUS         PORTS                                NAMES
e49657c97688  docker.io/testcontainers/ryuk:0.7.0  /bin/ryuk             32 minutes ago  Up 32 minutes  0.0.0.0:38483->8080/tcp, 8080/tcp    testcontainers-ryuk-f2ceb91e-81ef-491c-a32e-5a60d2452997
c49dc4bf63dc  docker.io/library/mongo:4.4          --replSet docker-...  32 minutes ago  Up 32 minutes  0.0.0.0:40857->27017/tcp, 27017/tcp  ecstatic_mestorf

```
5. Overload the version: ` mvn quarkus:dev -Dquarkus.mongodb.devservices.image-name=docker.io/library/mongo:7.0`
6. The app starts fine

### Output of `uname -a` or `ver`

4.18.0-553.5.1.el8_10.x86_64

### Output of `java -version`

17.0.7, vendor: Red Hat, Inc.

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by geoand** [comment]
Makes sense, thanks for spotting this!

Would you like to do a PR to update the version?

**Comment by melloware** [comment]
you can also just set the image with `quarkus.mongodb.devservices.image-name=mongo:latest`

**Comment by geoand** [comment]
Absolutely, but I think the issue is about providing a good default

**Comment by famod** [comment]
It seems the entire block needs some updating: https://github.com/quarkusio/quarkus/blob/3.13.0.CR1/build-parent/pom.xml#L83-L90

**Comment by melloware** [comment]
PR submitted: https://github.com/quarkusio/quarkus/pull/42078
