### ISSUE TITLE
[3.8] Upgrade `jboss-logmanager` dependency

### ISSUE THREAD

**Issue by mabartos** [quarkusio/quarkus#42043]
### Description

As for the Keycloak project, the customer asks for the support of `jboss-logmanager:3.0.6.Final` dependency version for the Quarkus 3.8.x due to providing a fix for https://github.com/jboss-logging/jboss-logmanager/pull/468.

Is it possible to backport changes from the https://github.com/quarkusio/quarkus/pull/40405 to 3.8.x? 

Thanks for the response.

**Comment by dmlloyd** [comment]
This seems reasonable to me.

**Comment by geoand** [comment]
Closing this as we added the label to the PR in question
