### ISSUE TITLE
REST Reactive Server: support multiple outparts with the same key in MultipartFormDataOutput

### ISSUE THREAD

**Issue by comrt** [quarkusio/quarkus#42053]
### Description

Unfortunately the Quarkus REST (Reactive) server side implementation of `MultipartFormDataOutput` does not support multiple form data with the same key. This is very inconvenient if you're coming from resteasy classic, where this is supported.

e.g. this formData will return only the last added part, because internally it is kept in a linkedhashmap.
```java
import org.jboss.resteasy.reactive.server.multipart.MultipartFormDataOutput;

...

MultipartFormDataOutput formData = new MultipartFormDataOutput();
try {
  formData.addFormData("files", new TempFileInputStream(invoice), MediaType.APPLICATION_OCTET_STREAM_TYPE, "invoice.pdf");
  formData.addFormData("files", new TempFileInputStream(agb), MediaType.APPLICATION_OCTET_STREAM_TYPE, "agb.pdf");
} catch (FileNotFoundException e) {
 throw new IllegalStateException(e.getMessage());
}
return formData;
```

Hope you can me help out here. I my use case `MultipartFormDataOutput` is very useful, because you can return binary data, which is loaded from a database and temporarily written to a tempfile for deletion, when response is sent.
Thanks and keep up the marvelous work!

**Comment by geoand** [comment]
Seems reasonable to me, let me take a look
