### ISSUE TITLE
In some context, `NoSuchElementException: No line found` error thrown from telemetry

### ISSUE THREAD

**Issue by apupier** [quarkusio/quarkus#42058]
### Describe the bug

It can be reproduced when using the devfile from the devfile registry and starting the remote dev

see https://github.com/devfile/api/issues/1611

### Expected behavior

no stacktrace

### Actual behavior

there is a stacktrace logged:

```
tools: ----------------------------
tools: --- Help improve Quarkus ---
tools: ----------------------------
tools: * Learn more: https://quarkus.io/usage/
tools: * Do you agree to contribute anonymous build time data to the Quarkus community? (y/n and enter) 
tools: [WARNING] Failed to collect user input for analytics
tools: java.util.NoSuchElementException: No line found
tools:     at java.util.Scanner.nextLine (Scanner.java:1660)
tools:     at io.quarkus.maven.DevMojo.lambda$execute$0 (DevMojo.java:445)
tools:     at io.quarkus.analytics.ConfigService.lambda$userAcceptance$0 (ConfigService.java:79)
tools:     at java.util.concurrent.CompletableFuture$AsyncSupply.run (CompletableFuture.java:1768)
tools:     at java.lang.Thread.run (Thread.java:1583)
tools: [info] [Quarkus build analytics] Didn't receive a valid user's answer: `y` or `n`. The question will be asked again next time.
```

### Additional information

I wasn't able to reproduce with a local build https://github.com/devfile/api/issues/1611#issuecomment-2210420139

**Comment by geoand** [comment]
cc @brunobat

**Comment by brunobat** [comment]
This is just a harmless warning it can be avoided altogether by placing the following file:
`~/.redhat/io.quarkus.analytics.localconfig`
with contents:
```json
{"disabled":false}
```
This way analytics will be on and user input will not be requested.

**Comment by brunobat** [comment]
There was a nicer message: `[WARNING] Failed to collect user input for analytics`...
