### ISSUE TITLE
Quarkus throws an IllegalArgumentException on startup if a yaml file is too large

### ISSUE THREAD

**Issue by krusc84** [quarkusio/quarkus#42070]
### Describe the bug

With Quarkus I use a ConfigMapping interface that reads its data from a Yaml file. The Yaml file contains a list with over 2000 entries.

When I start the application I get the following error:
[error]: Build step io.quarkus.deployment.steps.ConfigGenerationBuildStep#generateBuilders threw an exception: java.lang.RuntimeException: java.lang.IllegalArgumentException: UTF8 string too large

### Expected behavior

A Quarkus application can be started if a YAML file used by ConfigMapping contains a list with many values.

### Actual behavior

A Quarkus application cannot be started if a YAML file used by ConfigMapping contains a list with many values.

### How to Reproduce?

Step 1: Generate a Quarkus Application
Step 2: Add quarkus-config-yaml dependency
Step 3: Add yaml file with a list of values. The values in the list should be over 65535 characters in total.
Step 4. Create ConfigMapping interface that contains a list that is read from the Yaml file
Step 5. Start the application

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.4651]

### Output of `java -version`

openjdk version "17.0.11" 2024-04-16 LTS OpenJDK Runtime Environment Corretto-17.0.11.9.1 (build 17.0.11+9-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.11.9.1 (build 17.0.11+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by radcortez** [comment]
I'm able to generate a `org.objectweb.asm.MethodTooLargeException` as #22027 , but not a `java.lang.RuntimeException: java.lang.IllegalArgumentException: UTF8 string too large`.

Please, provide us with a reproducer. Thank you!

**Comment by krusc84** [comment]
The error only occurs if the list entries in the yaml file contain umlauts:

[code-with-quarkus.zip](https://github.com/user-attachments/files/16357362/code-with-quarkus.zip)

**Comment by dmlloyd** [comment]
The umlauts aren't the problem, it's more likely that these list entries all get concatenated into one giant string (joined by `,`) and that string is too big to represent in a single class constant pool entry (whose limit is 65535 utf8-encoded bytes). The Ä character is two bytes in UTF-8, iirc.

I guess we could work around the issue by breaking giant strings into chunks and merging them with `String.concat`.

**Comment by radcortez** [comment]
Thank you for the reproducer!

Yes, the issue is that we generated a value with all the list elements separated by commas for Collections types. This is / was required by MicroProfile Config, and before, we had support for indexed properties. I believe we don't need that anymore and I removed it: https://github.com/smallrye/smallrye-config/pull/1203

**Comment by dmlloyd** [comment]
Well, I hope you're right.
