### ISSUE TITLE
Maven Native docker build fails: AccessDeniedException: /project/reports

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus#4209]
**Describe the bug**
Graalvm experiments a file access denied when file should be created under docker mounted volume on macos -> `-v /Users/dabou/Downloads/code-with-quarkus/target:/project:z`

**Actual behavior**
See: https://gist.github.com/cmoulliard/e62057cc0749fb8117f8dcd63181ca71
```
Caused by: jdk.vm.ci.common.JVMCIError: java.nio.file.AccessDeniedException: /project/reports/call_tree_code-with-quarkus-1.0.0-SNAPSHOT-runner_20190926_044702.txt
	at jdk.vm.ci.common.JVMCIError.shouldNotReachHere(JVMCIError.java:54)
	at com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:81)
	at com.oracle.graal.pointsto.reports.CallTreePrinter.print(CallTreePrinter.java:64)
```

There are no local permission issues to access the files of the quarkus project
```
drwxr-xr-x@  11 dabou  staff         352 Sep 26 06:05 code-with-quarkus
 ls -la ~/Downloads/code-with-quarkus
total 88
drwxr-xr-x@  11 dabou  staff    352 Sep 26 06:05 .
drwx------+ 160 dabou  staff   5120 Sep 26 06:15 ..
-rw-r--r--@   1 dabou  staff   8196 Sep 26 06:05 .DS_Store
-rw-r--r--@   1 dabou  staff     53 Sep 17 12:06 .dockerignore
-rw-r--r--@   1 dabou  staff    295 Sep 17 12:06 .gitignore
drwxr-xr-x@   3 dabou  staff     96 Sep 17 12:06 .mvn
-rwxr-xr-x@   1 dabou  staff  10078 Sep 17 12:06 mvnw
-rwxr-xr-x@   1 dabou  staff   6609 Sep 17 12:06 mvnw.cmd
-rw-r--r--@   1 dabou  staff   3699 Sep 17 12:06 pom.xml
drwxr-xr-x@   5 dabou  staff    160 Sep 26 06:05 src
drwxr-xr-x   18 dabou  staff    576 Sep 26 07:24 target
```
**To Reproduce**
1. Generate a zip project of quarkus using code generator, unzip it
2. Start "docker-machine start dev"
3. eval $(docker-machine env dev
4: `./mvnw package -Pnative -Dnative-image.docker-build=true`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin dabou 18.7.0 Darwin Kernel Version 18.7.0`
 - Output of `java -version`: 
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-20190711112007.graal.jdk8u-src-tar-gz-b08)
OpenJDK 64-Bit GraalVM CE 19.2.0.1 (build 25.222-b08-jvmci-19.2-b02, mixed mode)
```
- GraalVM version (if different from Java): `OpenJDK 64-Bit GraalVM CE 19.2.0.1 (build 25.222-b08-jvmci-19.2-b02, mixed mode)`
 - Quarkus version or git rev: `0.22`

**Comment by cescoffier** [comment]
Quarkus requires docker for mac. There are several issues with docker-machine.

**Comment by cmoulliard** [comment]
> Quarkus requires docker for mac

Can you then document for mac users then within the HowToGuide how they could do a native docker build please, tools they should use, ... ?

**Comment by geoand** [comment]
https://quarkus.io/guides/building-native-image now contains plenty of information about building with MacOS so I will close this
