### ISSUE TITLE
Update examples to use org.htmlunit:htmlunit

### ISSUE THREAD

**Issue by rolfedh** [quarkusio/quarkus#42112]
### Description

@michalvavrik  commented that examples with the following text should be updated to use https://mvnrepository.com/artifact/org.htmlunit/htmlunit instead:
```
<dependency>
    <groupId>net.sourceforge.htmlunit</groupId>
    <artifactId>htmlunit</artifactId> 

```

These include the following results for "net.sourceforge.htmlunit" in "*.adoc"

/home/rdlugyhe/quarkus/docs/src/main/asciidoc/security-oidc-code-flow-authentication.adoc:
  1503:      <groupId>net.sourceforge.htmlunit</groupId>
  1523:  testImplementation("net.sourceforge.htmlunit:htmlunit")

/home/rdlugyhe/quarkus/docs/src/main/asciidoc/security-openid-connect-multitenancy.adoc:
  436:      <groupId>net.sourceforge.htmlunit</groupId>
  447:  testImplementation("net.sourceforge.htmlunit:htmlunit")

fyi: @sberyozkin

**Comment by michalvavrik** [comment]
for context: I made comments on 3.8 product branch, I suppose my comments are valid for 3.8 community branch, but I didn't check

**Comment by sberyozkin** [comment]
@rolfedh @michalvavrik, AFAIK, the package change for HTML unit occurred in 3.12.0, #40765.
So 3.8 should continue referencing the old package.
@rolfedh Are you OK to update 2 upstream docs ? I won't really have much time, though I can try tomorrow

**Comment by michalvavrik** [comment]
> @rolfedh @michalvavrik, AFAIK, the package change for HTML unit occurred in 3.12.0, https://github.com/quarkusio/quarkus/pull/40765. So 3.8 should continue referencing the old package.

Last release I can see was https://mvnrepository.com/artifact/net.sourceforge.htmlunit/htmlunit year and half ago. You are absolutely correct that Quarkus uses `net.sourceforge` https://github.com/quarkusio/quarkus/blob/3.8/build-parent/pom.xml#L308 but IIUC it is not managed by BOM, so I think using a newer package is not a bad idea as long as version suggested is backwards compatible to our tests.

Anyway, I can see it is hardly important, I apologize for bringing it up @rolfedh , we can probably just close it as far as 3.8 is related.

**Comment by rolfedh** [comment]
I found a couple of instances that needed updating in `main` and fixed them with https://github.com/quarkusio/quarkus/issues/42112.

**Comment by rolfedh** [comment]
> as long as version suggested is backwards compatible to our tests.

@sberyozkin @michalvavrik  It's easy enough for me to make similar updates in `3.8`. Just let me know what you prefer.
