### ISSUE TITLE
Core module is using a mix of traditional `@ConfigRoot` and `@ConfigMapping`

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#42114]
@radcortez if you want to help, it would be nice if you could make sure the `quarkus-core` modules (runtime and deployment) uniformly use `@ConfigMapping` (or `@ConfigRoot`, your choice but I suspect you will choose the former).

This won't be allowed anymore with the new annotation processor.

See `PackageConfig` for `@ConfigMapping` and `ShutdownBuildTimeConfig` for traditional `@ConfigRoot`.

**Comment by radcortez** [comment]
Sure

**Comment by gsmet** [comment]
SmallRye Reactive Messaging is also in the way with `ReactiveMessagingConfiguration` and `HealthCenterFilterConfig`.

**Comment by gsmet** [comment]
FWIW, we will unfortunately need this fixed before we can think about merging the new annotation processor. I'm iterating on the full build atm to detect all the issues.

**Comment by radcortez** [comment]
Ok. I'll work on this today.
