### ISSUE TITLE
Setting quarkus.http.test-port to a non-default value breaks tests in MP OpenAPI TCK

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#4211]
This is because the `@BeforeSuite` callback (https://github.com/eclipse/microprofile-open-api/blob/1.1.2/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AppTestBase.java#L48) runs too early, before the `TestHTTPResourceManager` has a chance to set the `test.url` property, so the callback picks up the one that is passed from `pom.xml`, but that one has a hardcoded port 8081

**Comment by jmartisk** [comment]
Options what we can do:
- Change our Arquillian adapter and introduce a new `BeforeSuite` callback that runs before the one in the TCK and set a `test.url` property there based on the value of `quarkus.http.test-port`. However, the problem is that for `test.url=0` (random port, introduced by https://github.com/quarkusio/quarkus/pull/4140/), this will not work because at this point we don't know yet what the actual port will be, that is decided during boot of the container. And it is fragile because the property will later be overwritten by `TestHTTPResourceManager#getUri`
- Change the TCK itself so that the `test.url` property is read later than in `@BeforeSuite` - moving it to `@BeforeClass` should do it I think, at that point the container is started and `test.url` is set correctly even if the port was random. We would also remove the `test.url` property from pom.xml, it will not be needed anymore.

I'd go with trying to change the tck if we want this fixed. What's your opinion @kenfinnigan ?

**Comment by kenfinnigan** [comment]
I think changing the TCK makes the most sense.

I only added the `test.url` to the pom as it was the only way to get the TCK to pass at the time

**Comment by gastaldi** [comment]
👍 to change the TCK.

**Comment by stuartwdouglas** [comment]
Closing, as it sounds like this is no longer an issue.
