### ISSUE TITLE
Sort identity providers by priority in QuarkusIdentityProviderManagerImpl

### ISSUE THREAD

**Issue by danilopiazza** [quarkusio/quarkus#42126]
### Description

`IdentityProvider` from [quarkus-security](https://github.com/quarkusio/quarkus-security/commit/44ef3b9e6eb75590ee107a338443e1e16cce78b2) has a `priority` method which, apparently, is not used anywhere.

Should `QuarkusIdentityProviderManagerImpl` sort each value of `providers` by priority, like it does for `augmentors`?

### Implementation ideas

The implementation could look like this code from `QuarkusIdentityProviderManagerImpl.Builder.build()`:

    @Override
    providers.values().forEach(providers -> providers.sort(new Comparator<IdentityProvider>() {
        @Override
        public int compare(IdentityProvider o1, IdentityProvider o2) {
            return Integer.compare(o2.priority(), o1.priority());
        }
    }));

**Comment by sberyozkin** [comment]
Thanks @danilopiazza for marking it as an enhancement, it looks like a bug. What is happening in your case, do you see built in providers getting in front unexpectedly ? AFAIK, if you use CDI `@Alternative`, possibly with `@Priority(1)`, you should get your custom IdentityProvider chosen only.

**Comment by sberyozkin** [comment]
But that would be a workaround. if it has a priority method then it should be effective

**Comment by danilopiazza** [comment]
> Thanks @danilopiazza for marking it as an enhancement, it looks like a bug. What is happening in your case, do you see built in providers getting in front unexpectedly ? AFAIK, if you use CDI `@Alternative`, possibly with `@Priority(1)`, you should get your custom IdentityProvider chosen only.

Yes, I see this exact behavior and I can confirm that the workaround is working. Thanks!
