### ISSUE TITLE
ArrayIndexOutOfBoundsException occurred when  i was serializing data from redis with quarkus redis extension

### ISSUE THREAD

**Issue by Awen92** [quarkusio/quarkus#42131]
### Describe the bug

As the title, when i was serializing data from redis, i got an excetion, i found that there were sth wrong with Marshaller while JDK compiles the code.

Here is the sourece code of Marshaller

```java

final <F, V> Map<F, V> decodeAsOrderedMap(Response response, Type typeOfValue, F[] fields) {
        Iterator<Response> iterator = response.iterator();
        Map<F, V> map = new LinkedHashMap<>();
        for (F field : fields) {
            Response v = iterator.next();
            map.put(field, decode(typeOfValue, v));
        }
        return map;
    }

```

The JDK compiles code as 

```java
final <F, V> Map<F, V> decodeAsOrderedMap(Response response, Class<V> typeOfValue, F[] fields) {
        Iterator<Response> iterator = response.iterator();
        Map<F, V> map = new LinkedHashMap();
        Object[] var6 = fields;
        int var7 = fields.length;

        for(int var8 = 0; var8 < var7; ++var8) {
            F field = var6[var8];
            Response v = (Response)iterator.next();
            map.put(field, this.decode(typeOfValue, v));
        }

        return map;
    }

```

Here is my test code 

```java
HashCommands<String, String, String> infoHashCommands = redisDs.hash(String.class, String.class, String.class);
        infoHashCommands.hmget("", code, code2);

```

if the `code` parameter is `null`,it will caused ArrayIndexOutOfBoundsException
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/bfef8102-e648-4391-b37c-224e6e556138">

**Comment by cescoffier** [comment]
Do you have some code reproducing this issue? 

Also, check your redis server version.

**Comment by Awen92** [comment]
> Do you have some code reproducing this issue?
> 
> Also, check your redis server version.

Here was my test code 

```java

HashCommands<String, String, String> infoHashCommands = redisDs.hash(String.class, String.class, String.class);
infoHashCommands.hmget("", code, code2);

```

Pass the **code parameter as null object**, you can reproduce this issue

**Comment by cescoffier** [comment]
Ah ok, you pass 'null'. I don't believe it should be possible (I will check). Anyway, the error message is incorrect.

**Comment by cescoffier** [comment]
Opened https://github.com/quarkusio/quarkus/pull/42142 to improve the error message.
