### ISSUE TITLE
Extend @TestSecurity to support Credential

### ISSUE THREAD

**Issue by danilopiazza** [quarkusio/quarkus#42148]
### Description

Currently, `@TestSecurity` supports `SecurityIdentity` attributes.

The annotation could be extended to support `Credential`s, too.

**Comment by michalvavrik** [comment]
> The annotation could be extended to support Credentials, too.

I take it you mean `io.quarkus.security.identity.SecurityIdentity#getCredential` ? How would you set it `TestSecurity` annotation attribute? You would need some class for it, in which case I don't see a difference to registering `SecurityIdentityAugmentor` that configures the credential. Can you elaborate, please?

**Comment by danilopiazza** [comment]
> You would need some class for it, in which case I don't see a difference to registering `SecurityIdentityAugmentor` that configures the credential.

Yes, you're right. I am closing this issue.
