### ISSUE TITLE
Resteasy-reactive Unit endpoint reported as "Run time writers required"

### ISSUE THREAD

**Issue by StianHaSu** [quarkusio/quarkus#42159]
### Describe the bug

When returning a Uni with a Unit (using Kotlin), the Dev UI will report a 0/100 for the Writer, with the message: "Run time writers required". This was a bug previously for Uni with a Void as well, as reported in issue: https://github.com/quarkusio/quarkus/issues/27338.  

### Expected behavior

The same Writer score as when returning a Uni with Void

### Actual behavior

A score of 0/100, with message: Run time writers required

### How to Reproduce?

This repo has a minimal recreation of the bug: https://github.com/StianHaSu/quarkus-Uni-Unit-bug.
1. Run in dev mode
2. See endpoint scores in Dev UI

**Comment by geoand** [comment]
Thanks for spotting this.

https://github.com/quarkusio/quarkus/pull/42195 fixes the problem
