### ISSUE TITLE
Security related quickstarts/ guide

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#4215]
* One big guide containing everything
* Cover annotations
* “Concepts”
* Link to the other guides
* Extending the security layer (IDP, Handler, augmentation)
* File-based auth quickstart
* JPA-based auth quickstart
* Update the Keycloak quickstart

**Comment by gsmet** [comment]
> File-based auth quickstart

If we document that, can we please document something where the passwords are properly hashed/salted? Our current documentation has the passwords in clear text and that's really not something acceptable nowadays - even if an example.

(Mentioning that because we just had a related question on Zulip)

**Comment by cescoffier** [comment]
Keycloak quickstart update: https://github.com/quarkusio/quarkus-quickstarts/pull/294

**Comment by cescoffier** [comment]
JWT quickstart is broken :-(

**Comment by sberyozkin** [comment]
@stuartwdouglas I'm still not sure `-vertx-` qualifier is worth it :-), one more extra problem during the migration to the users (they will have to change from `quarkus-keycloak` to `quarkus-vertx-keycloak`)

**Comment by cescoffier** [comment]
@sberyozkin the trick is that it does not provide the keycloak classes anymore. So there is a change in the structure of the artifact.

**Comment by gintsgints** [comment]
@cescoffier In keycloak guide, write tests part is missing. Probably, best way could be start from writing tests at https://github.com/quarkusio/quarkus-quickstarts.git (using-keycloak)

**Comment by gsmet** [comment]
I think this one is OK now. If there are missing things, let's open more focused issues.
