### ISSUE TITLE
unable to load resource bundle from dependent jar

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#42165]
### Describe the bug

an application has some bundles, and a dependency on an external jar that has additional different bundles, plus some logic to retrieve the values from the bundles.
when running `mvn quarkus:test`, the bundles that are in the app can't be found, if loaded from the code located in the external jar.
but they are found if the logic is in the app itself.

### Expected behavior

the bundles in the app should be found, whether or not they are loaded from the app or external jar code.

### Actual behavior

the bundles that are in the app can't be found, if loaded from the code located in the external jar.
but they are found if the logic is in the app itself.

#### external module 

create an external module `foo`, with this class:
```
public class ResourceBundleProvider {

    public String getValue(String basename, String key) {
        return ResourceBundle.getBundle(basename).getString(key);
    }
}
```

and create in this module a resource bundle `ValidationMessages_BAR.properties` with:
```
BAR=this is bar
```

#### application

create an application with the following resource bundle `ValidationMessages_FOO.properties`:
```
FOO=this is foo
```

add the following endpoint:
```
package org.acme;

import com.foo.ResourceBundleProvider;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ResourceBundle;

@Path("/hello")
public class GreetingResource {

    private static final Logger log = LoggerFactory.getLogger(GreetingResource.class);


    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello from Quarkus REST";
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/bundle1")
    public String bundle1() {
        return ResourceBundle.getBundle("ValidationMessages_FOO").getString("FOO");
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/bundle2")
    public String bundle2() {
        return new ResourceBundleProvider().getValue("ValidationMessages_FOO", "FOO");
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/bundle3")
    public String bundle3() {
        return new ResourceBundleProvider().getValue("ValidationMessages_BAR", "BAR");
    }
}

```

and the following test:
```
package org.acme;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
class GreetingResourceTest {
    @Test
    void testHelloEndpoint() {
        given()
          .when().get("/hello")
          .then()
             .statusCode(200)
             .body(is("Hello from Quarkus REST"));
    }

    @Test
    void testHelloBundle1() {
        given()
                .when().get("/hello/bundle1")
                .then()
                .statusCode(200);
    }

    @Test
    void testHelloBundle2() {
        given()
                .when().get("/hello/bundle2")
                .then()
                .statusCode(200);
    }

    @Test
    void testHelloBundle3() {
        given()
                .when().get("/hello/bundle3")
                .then()
                .statusCode(200);
    }
}
```

and add pom dependency:
```
        <dependency>
            <groupId>...</groupId>
            <artifactId>foo</artifactId>
            <version>...</version>
        </dependency>
```

#### run

1. execute `mvn clean package` => all tests are green
2. execute `mvn quarkus:test` => `GreetingResourceTest#testHelloBundle2() 1 expectation failed.`
3. execute `mvn quarkus:dev` and `curl localhost:18080/hello/bundle1 2 or 3` => 1 and 3 are success, 2 is failed

### Quarkus version or git rev

3.12.3

**Comment by gsmet** [comment]
Did you try loading the bundle using the TCCL? The dev mode CL infrastructure is rather complex and you need to use the TCCL.

**Comment by geoand** [comment]
> Did you try loading the bundle using the TCCL

Just to make it clear:

`Thread.currentThread().contextClassLoader`

**Comment by vsevel** [comment]
it works with the TCCL indeed. thanks for the suggestion. what is disturbing is that it works when running tests from the IDE and when running the app in prod mode. only `quarkus:test` and `quarkus:dev` fail. I understand the difference of setup, but this is still unfortunate. plus in that case, it happened only if the resources were located in a different jar. this presented an additional level of debugging complexity with the dev team.

**Comment by geoand** [comment]
Right, that's unfortunately the price we need to pay to have some of the nice features of Quarkus
