### ISSUE TITLE
[Extension] setForcedDependencies not present inside ApplicationArchivesBuildItem

### ISSUE THREAD

**Issue by dcdh** [quarkusio/quarkus#42188]
### Describe the bug

I would like to check the presence of  a dependency using the ApplicationArchivesBuildItem.

However, the dependency is not found.

### Expected behavior

The dependency should be found and validation should fail.

### Actual behavior

The test fail in an unexpected manner and I expect it to catch a validation error..

Failing this way 

```
org.opentest4j.AssertionFailedError: The build was expected to fail
```

### How to Reproduce?

The processor definition

```java
class BannedDependenciesProcessor {

    @BuildStep
    void banDependencies(final ApplicationArchivesBuildItem applicationArchivesBuildItem,
                         final BuildProducer<ValidationPhaseBuildItem.ValidationErrorBuildItem> validationErrorBuildItemProducer) {
        applicationArchivesBuildItem.getApplicationArchives().stream()
                .map(ApplicationArchive::getKey)
                .filter(new IsBannedDependency())
                .forEach(bannedDependency ->
                        validationErrorBuildItemProducer.produce(new ValidationPhaseBuildItem.ValidationErrorBuildItem(
                                new IllegalStateException(String.format("Dependency '%s' '%s' is banned and so cannot be used", bannedDependency.getGroupId(), bannedDependency.getArtifactId()))
                        ))
                );
    }

    private record IsBannedDependency() implements Predicate<ArtifactKey> {
        private final static List<ArtifactKey> BANNED_ARTIFACTS = List.of(
                ArtifactKey.ga("io.quarkus", "quarkus-config-yaml"));

        @Override
        public boolean test(final ArtifactKey artifactKey) {
            return BANNED_ARTIFACTS.contains(artifactKey);
        }
    }
}
```

The test definition
```java
public class ShouldFailWhenABannedDependencyIsUsedTest {

    @RegisterExtension
    static final QuarkusUnitTest unitTest = new QuarkusUnitTest()
            .withEmptyApplication()
            .setForcedDependencies(
                    List.of(
                            Dependency.of("io.quarkus", "quarkus-config-yaml", Version.getVersion())))
            .assertException(throwable -> assertThat(throwable)
                    .hasNoSuppressedExceptions()
                    .rootCause()
                    .hasMessage("TODO")
                    .hasNoSuppressedExceptions());

    @Test
    public void test() {
        Assertions.fail("Startup should have failed");
    }
}
```

### Output of `uname -a` or `ver`

Linux 2a02-8428-dff8-c601-234b-8c10-a3c4-2308.rev.sfr.net 6.9.6-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 21 15:48:21 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16

### Quarkus version or git rev

3.12.3

### Additional information

Maybe I am using the wrong build item ?

**Comment by dcdh** [comment]
When I add the dependency inside an application with

```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-config-yaml</artifactId>
    </dependency>
```

the application starts meanwhile I expect it to fail at startup.

**Comment by aloubyansky** [comment]
`ArtifactKey.ga("io.quarkus", "quarkus-config-yaml")` results in an incomplete key. It's confusing but it's for different purposes. The complete key will be `ArtifactKey.of("io.quarkus", "quarkus-config-yaml", null, "jar")`.

**Comment by aloubyansky** [comment]
That's actually the first part of it. The other thing to keep in mind is that `ApplicationArchivesBuildItem` does not represent all the application dependencies. `CurateOutcomeBuildItem.getApplicationModel().getDependencies()` or (in case you are interested only in the runtime dependencies) `CurateOutcomeBuildItem.getApplicationModel().getRuntimeDependencies()` will return all the necessary dependencies.

**Comment by dcdh** [comment]
Thanks
