### ISSUE TITLE
Security annotation error raised at startup when controllers are in other jars, when using quarkus-security extension

### ISSUE THREAD

**Issue by rober710** [quarkusio/quarkus#42187]
### Describe the bug

When a project has a dependency on the `quarkus-security` extension, and it has controllers that are loaded from other jars (libraries), Quarkus fails to start with the following error:
```
java.lang.IllegalStateException: Security annotation placed on resource method 'com.kenect.integrations.models.LibraryController#doSomething' wasn't detected by Quarkus during the build time.
Please report issue in Quarkus project.

        at io.quarkus.resteasy.reactive.server.runtime.security.EagerSecurityHandler$Customizer.handlers(EagerSecurityHandler.java:263)
        at org.jboss.resteasy.reactive.server.core.startup.RuntimeResourceDeployment.addHandlers(RuntimeResourceDeployment.java:629)
        at org.jboss.resteasy.reactive.server.core.startup.RuntimeResourceDeployment.buildResourceMethod(RuntimeResourceDeployment.java:208)
        at org.jboss.resteasy.reactive.server.core.startup.RuntimeDeploymentManager.deploy(RuntimeDeploymentManager.java:136)
        at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder.createDeployment(ResteasyReactiveRecorder.java:154)
        at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment713137389.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment713137389.deploy(Unknown Source)
        ... 17 more
```
This doesn't happen with Quarkus 3.12.X releases.

### How to Reproduce?

Here's the reproducer project for this issue. The instructions to reproduce can be found in the readme.
https://github.com/rober710/resteasy-reactive-reproducer

### Output of `uname -a` or `ver`

Linux polaris 6.5.12-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:28:44 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment (build 21.0.2+13-58) OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)

### Quarkus version or git rev

3.13.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)

**Comment by michalvavrik** [comment]
The exception is consequence of the https://github.com/quarkusio/quarkus/pull/41784 but it is not a regression, because this exception should only be raised for scenarios that we previously didn't handle eagerly but we should. I have extremely little time ATM but I'll do a quick check of the reproducer and report back.

**Comment by michalvavrik** [comment]
thanks for reporting this issue @rober710, known workaround:

```
quarkus.index-dependency."lib1".group-id=com.kenect.integrations
quarkus.index-dependency."lib1".artifact-id=test-resteasy-reactive-models
```

**Comment by rober710** [comment]
Thanks @michalvavrik ! I tested the workaround at my current project and it worked.

**Comment by geoand** [comment]
I am going to close this as this essentially works in the same way as other extensions work, i.e. the library that contains Quarkus code needs to be indexed.

I propose adding an empty `src/main/resources/META-INF/beans.xml` to the `library` module.

**Comment by smil2k** [comment]
I have the same problem. The controller is in a different module, it is indexed, I've added the annotation and a beans.xml none of them helped. 

Also the controller did not had any security annotation:
```
@RegisterRestClient(configKey = "filexchange-client")
@RegisterProvider(AccessTokenRequestReactiveFilter.class)
public interface FileXchangeClient {

    @GET
    @Path("/{visibility}/{fileName}")
    InputStream get(@PathParam("visibility") Visibility visibility, @PathParam("fileName") String fileName);
}
```

**Comment by michalvavrik** [comment]
> I have the same problem. The controller is in a different module, it is indexed, I've added the annotation and a beans.xml none of them helped.
> 
> Also the controller did not had any security annotation:
> 
> ```
> @RegisterRestClient(configKey = "filexchange-client")
> @RegisterProvider(AccessTokenRequestReactiveFilter.class)
> public interface FileXchangeClient {
> 
>     @GET
>     @Path("/{visibility}/{fileName}")
>     InputStream get(@PathParam("visibility") Visibility visibility, @PathParam("fileName") String fileName);
> }
> ```

What you call 'controller' judging by the code is a REST client. However this exception cannot be thrown for the REST client because the code is run during scanning of REST resources. I cannot help without more information. Can you open issue with reproducer, please?

However, if you actually have secured endpoint that are indexed, it doesn't add up. Reproducer would help.
