### ISSUE TITLE
Way to inject the TestResource into the test

### ISSUE THREAD

**Issue by Nunalves** [quarkusio/quarkus#4219]
**Description**
I find it annoying that when using a TestResource i cannot inject its instance into the test.

I have TestResources (classes implementing `QuarkusTestResourceLifecycleManager`) that use an ephemeral port and then we have to have a static field on the test resource to know on which port it started. And if running tests in parallel, well, the static field will not work.

Something like this:
```java
public class KafkaTestResource implements QuarkusTestResourceLifecycleManager {

    private static KafkaCluster kafka;
    public static int ZOOKEEPER_PORT;
    public static int KAFKA_PORT;

    @Override
    public Map<String, String> start() {
        try {
            Properties kafkaProps = new Properties();
            File directory = Testing.Files.createTestingDirectory("kafka-data", true);
            ZOOKEEPER_PORT = findAvailablePort();
            KAFKA_PORT = findAvailablePort();
            kafka = new KafkaCluster().withPorts(ZOOKEEPER_PORT, KAFKA_PORT).addBrokers(1).usingDirectory(directory).deleteDataUponShutdown(true).withKafkaConfiguration(kafkaProps).deleteDataPriorToStartup(true).deleteDataUponShutdown(true).startup();
            Map<String, String> testProps = new HashMap<>();
            return testProps;
        } catch (Exception e) {
            LoggingUtils.writeException(getClass(), e);
            throw new RuntimeException(e);
        }
    }

    private int findAvailablePort() throws IOException {
        ServerSocket serverSocket = new ServerSocket(0);
        int availablePort = serverSocket.getLocalPort();
        serverSocket.close();
        return availablePort;
    }

    @Override
    public void stop() {
        kafka.shutdown();
    }

    public static KafkaCluster getKafka() {
        return kafka;
    }
}

```

Then, in the test we want to create a consumer to consume the messages produced by our code and assert them. So we create the consumer for the port on `KafkaTestResource.KAFKA_PORT`. Something like:

```java
    public static Consumer<String, String> createConsumer(String consumerGroupId) {
        Properties props = new Properties();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:" + KafkaTestResource.KAFKA_PORT);
        props.put(ConsumerConfig.GROUP_ID_CONFIG, consumerGroupId);
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true");
        props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        KafkaConsumer<String, String> consumer = new KafkaConsumer<>(props);
        return consumer;
    }
```

This is not pretty. It does not allow to run tests using the same resource in parallel. It would be really cool if we can inject the specific instance of the KafkaTestResource being used for the class.

**Implementation ideas**
TestResources are started before Quarkus so Arc is not aware of them.

**Comment by gsmet** [comment]
@mkouba this comes from a discussion we had with Nuno on Zulip and I was wondering if you would have some clever ideas to be able to push the test resources to Arc (even if they are started well before ArC comes at play).

**Comment by mkouba** [comment]
Hm, it seems that `QuarkusTestResourceLifecycleManager` instances are created per test class. And the final set is build from `@QuarkusTestResource` annotations found on the classes in the test classes directory + `QuarkusTestResourceLifecycleManager` service providers.

So in theory, we could register a bean for each `QuarkusTestResourceLifecycleManager` service provider and `@QuarkusTestResource` annotation found.

**Comment by mkouba** [comment]
It turns out that a `QuarkusTestResourceLifecycleManager` can inject anything in a test instance. See `QuarkusTestResourceLifecycleManager#inject(Object)`. And so it should be pretty easy to inject self or a special object like in https://github.com/quarkusio/quarkus/blob/master/test-framework/kubernetes-client/src/main/java/io/quarkus/test/kubernetes/client/KubernetesMockServerTestResource.java#L37-L57. That would be probably the easiest way. No need to do some extra stuff.

**Comment by geoand** [comment]
I propose this issue be closed since the mechanism that @mkouba described (seems to be that it) can be used to achieved

**Comment by languitar** [comment]
> It turns out that a `QuarkusTestResourceLifecycleManager` can inject anything in a test instance. See `QuarkusTestResourceLifecycleManager#inject(Object)`. And so it should be pretty easy to inject self or a special object like in https://github.com/quarkusio/quarkus/blob/master/test-framework/kubernetes-client/src/main/java/io/quarkus/test/kubernetes/client/KubernetesMockServerTestResource.java#L37-L57. That would be probably the easiest way. No need to do some extra stuff.

Am I right that this doesn't help when testing native executables where injection isn't available?

**Comment by geoand** [comment]
No, that is not correct. `QuarkusTestResourceLifecycleManager#inject(Object)` has nothing to do with CDI injection, it's a totally different mechanism that works for all kinds of Quarkus tests
