### ISSUE TITLE
Kafka Transactions are not commited if emitter is used within Uni

### ISSUE THREAD

**Issue by ColdanR** [quarkusio/quarkus#42209]
### Describe the bug

I cannot send a message using Mutiny and Kafka Transactions. I can send messages without mutiny and with transaction or without transaction and with mutiny.
The behavior is not always reproduceable, as the messages are sometimes sent

### Expected behavior

Messages are sent within Transaction and within Mutiny chain.

### Actual behavior

Messages are not sent always if Mutiny and Kafka Transactions are combined.

### How to Reproduce?

https://github.com/ColdanR/reproducer-messaging

Test 1 fails most of the time.
Test 2 and 3 always are ok.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 PC 3.4.10-87d57229.x86_64 2024-02-14 20:17 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment Microsoft-7626293 (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Microsoft-7626293 (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7 (8b094c9513efc1b9ce2d952b3b9c8eaedaf8cbf0)

**Comment by mmusgrov** [comment]
Quarkus supports the propagation of the transaction context to other threads using smallrye-context-propagation. The [setup is in the guide](https://quarkus.io/guides/context-propagation#setting-it-up). It's odd that it sometimes works, but would you be able to retest by including the dependency in your pom.

**Comment by ColdanR** [comment]
Adding the dependency resolves the bug. I'm still a little bit confused if I have missed the note about the dependency. Time to hit the guides again about mutiny.

Thanks for the help!
