### ISSUE TITLE
Field Name Collision and incorrect Binding of Boolean Fields When Using `isX` in a data class

### ISSUE THREAD

**Issue by moalshak** [quarkusio/quarkus#42221]
### Describe the bug

In the swagger-ui schema generated for the `/test/b` endpoint, both `isBoolean` and `boolean` fields appear in the schema, even though only `isBoolean` should be present. This can cause confusion and unexpected behavior, such as setting one field inadvertently setting the other.

<img width="652" alt="image" src="https://github.com/user-attachments/assets/7c712f97-4340-4eea-ae39-93a1afc4c857">

### Expected behavior

Only `isBoolean` should be present

### Actual behavior

The `boolean` field appears out of nowhere

### How to Reproduce?

1. Make a new project
2. Create a Resource
3. Create a datacalss with a boolean field with the name `isSomething`
4. Run the application
5. Visit the swagger UI
```kotlin
import com.fasterxml.jackson.annotation.JsonProperty
import jakarta.ws.rs.Consumes
import jakarta.ws.rs.GET
import jakarta.ws.rs.POST
import jakarta.ws.rs.Path
import jakarta.ws.rs.Produces
import jakarta.ws.rs.core.MediaType

@Path("/test")
class ExampleResource {

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/a")
    fun a(isBoolean: Boolean): String {
        return isBoolean.toString()
    }

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/b")
    fun b(isBoolean: IsBooleanDataClass): String {
        return isBoolean.toString()
    }

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/c")
    fun c(boolean: BooleanDataClass): String {
        return boolean.toString()
    }
}

data class IsBooleanDataClass(
    @JsonProperty("isBoolean")
    val isBoolean: Boolean)
data class BooleanDataClass(
    @JsonProperty("boolean")
    val boolean: Boolean)
```

### Output of `uname -a` or `ver`

Ubuntu

### Output of `java -version`

17

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.9

**Comment by phillip-kruger** [comment]
Thanks @MikeEdgar !
