### ISSUE TITLE
Transfer-Encoding header is set twice

### ISSUE THREAD

**Issue by FloGro3** [quarkusio/quarkus#42238]
### Describe the bug

In our BFFs we found out that when receiving a response from the backend that has "Transfer-Encoding" header set to "chunked" and we forward this response to the FE suddenly there are two "Transfer-Encoding" headers present which are set to "chunked". The browser is ignoring this but some rest clients are throwing an error because of theses duplicate headers. 

### Expected behavior

"Transfer-Encoding" header is only present once in the response of the bff. 

### Actual behavior

"Transfer-Encoding" header is set twice. 
<img width="914" alt="image" src="https://github.com/user-attachments/assets/93773c3a-1af4-452e-9d5d-303d66e9b10a">
<img width="362" alt="image" src="https://github.com/user-attachments/assets/7a2b0d24-1898-496b-b6dc-296b40f03db1">

### How to Reproduce?

Here is a minimal project that reproduces the issue: https://github.com/FloGro3/response-header-issue-example

### Output of `java -version`

Java version: 19.0.2

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7

**Comment by melloware** [comment]
not sure if its related but I see Pragma set twice as well.

![image](https://github.com/user-attachments/assets/7ba94c51-195c-4cdc-92bb-cc9b43dde47c)

**Comment by suchwerk** [comment]
In quarkus 3.23 this issue is still (or again) an issue.

**Comment by geoand** [comment]
Please open a new issue, and ideally add a reproducer.

**Comment by suchwerk** [comment]
Just to be complete: https://github.com/quarkusio/quarkus/issues/49875 with reproducer
