### ISSUE TITLE
Gradle early task configuration causes ` quarkus.container-image.` properties to be ignored

### ISSUE THREAD

**Issue by Malandril** [quarkusio/quarkus#42256]
### Describe the bug

When resolving early a project's configurations in gradle build for exemple with 
```kotlin
tasks.all {
    println("Hello")
}
```
the properties related to ` quarkus.container-image.` cannot be overriden by the usual means.
Setting a system property, a build property through the `quarkus` extension, or in a application.properties does not override it.

The only way to override the property is through `project.ext.set`.

### Expected behavior

Setting a system property or a build property through the `quarkus` extension,or in a application.properties should override the container properties, no matter if an early task configuration occured.

### Actual behavior

Properties cannot be overriden

### How to Reproduce?

A reproducer is available here [https://github.com/Malandril/quarkus-image-properties](https://github.com/Malandril/quarkus-image-properties).
You can run `./gradlew quarkusShowEffectiveConfig -Dquarkus.container-image.push=false` and see that the property is still set to true although it was set to false in application.properties, quarkus build properties and system properties.

Removing the `tasks.all` in the gradle build file, the build behaves as expected.

### Quarkus version or git rev

3.13.0

**Comment by radcortez** [comment]
It seems that the `ImageTask` sets the property in a very high ordinal source (600), which prevents the property from being overridden by other sources:

https://github.com/quarkusio/quarkus/blob/1b0b5f5b2ac2e94a049cd39606dd4d004d03c227/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/ImagePush.java#L15-L21

@snazy I'm not totally sure what the rationale behind this is. Can you please provide some insight before we make any changes? Thank you!

**Comment by Malandril** [comment]
I think it actually makes sens that when running the imagePush or imageBuild task the corresponding properties are set with a high ordinal.
Howerver i think its is done at the wrong time, on task configuration rather than task execution which makes it all buggy when both tasks are configured, for example with a `tasks.all` which forces all tasks configuration.
