### ISSUE TITLE
smallrye-jwt does not work on top of vertx

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4226]
@stuartwdouglas you've mentioned as part of the earlier PR conversation that the Undertow specific code will be gone, do you know how it can be replaced :-) ? With smallrye-jwt not depending on vertx-web it will not be able to connect with the vertx keycloak adapter in order to have the validated tokens exposed

**Comment by cescoffier** [comment]
Smallrye JWT use code that we don't support in the new stack (HTTPAuthenticator thingy). However, I've opened a PR to depends on Undertow. 

So if you really want to use SmallRye-JWT, you would need to use Undertow (it's going to be pulled anyway).

JWT support is going to be handled by the new security architecture, it won't be the SmallRye component.

**Comment by sberyozkin** [comment]
@cescoffier are you saying smallrye-jwt is not part of the new security architecture ? That sounds pretty wrong to me. @stuartwdouglas what am I missing ?

**Comment by cescoffier** [comment]
Update: it does work now.

**Comment by sberyozkin** [comment]
@cescoffier:+1: thank you
