### ISSUE TITLE
Quarkus Playpen

### ISSUE THREAD

**Issue by patriot1burke** [quarkusio/quarkus#42269]
### Description

Playpen allows you to do live local development on an existing deployed service in kubernetes/openshift.  Requests from a development cluster can be routed to your local dev instance instead of your deployed service.  Playpen defines a proxy, k8s operator, client, and quarkus extension to do this work.

Additionally, in future versions, we will provide an additional mode to make Quarkus Remote Dev Mode easier within kubernetes.  The service will deploy a remote dev container in the k8s cluster that can override the existing service temporarily and have requests routed to it.  The developer can then code locally using quarkus remote dev mode.

### Repository name

quarkus-playpen

### Short description

Live local development on a deployed k8s service

### Repository Homepage URL

https://github.com/patriot1burke/quarkus-devspace/blob/main/README.md

### Repository Topics

- quarkus-extension
- operator
- remote dev k8s
- local dev k8s

### Team Members

- patriot1burke

**Comment by gastaldi** [comment]
@patriot1burke https://github.com/quarkiverse/quarkus-playpen created. Check the next steps to make your extension visible in the Quarkus tooling world: https://hub.quarkiverse.io/checklist/#after-the-repository-is-created 

Enjoy!
