### ISSUE TITLE
@RunOnVirtualThread Not Working with Undertow Servlet

### ISSUE THREAD

**Issue by otavioprado** [quarkusio/quarkus#42274]
### Describe the bug

The @RunOnVirtualThread annotation seems not to work as expected when used in the Undertow extension. Specifically, the servlet's service method does not run on a virtual thread as intended.

Code:
```
@WebServlet(urlPatterns = "/*")
@RunOnVirtualThread
public class MyServlet extends HttpServlet {

    @Override
    protected void service(HttpServletRequest servletRequest, HttpServletResponse servletResponse) throws IOException {
        Log.infof( "Current thread: %s", Thread.currentThread().getName());
        Log.infof("Is virtual thread? %s", Thread.currentThread().isVirtual());
    }
}
```
Log:
```
2024-08-01 14:55:41,415 INFO  [com.sen.api.ser.MyServlet] (executor-thread-1) Current thread: executor-thread-1
2024-08-01 14:55:41,416 INFO  [com.sen.api.ser.MyServlet] (executor-thread-1) Is virtual thread? false
```

### Expected behavior

The service method should run on a virtual thread, and the logs should indicate that the current thread is a virtual thread.

### Actual behavior

The service method does not appear to run on a virtual thread as expected. Instead, it runs on a regular thread.

### How to Reproduce?

1) Set up a Quarkus project using the Undertow extension. 
2) Create a new Java class named MyServlet that extends HttpServlet. Annotate the class's service method with @RunOnVirtualThread.
3) In the service method, add logging statements to output the current thread's name and whether it is a virtual thread. 
4) Send an HTTP request to the servlet endpoint to trigger the service method.
5) Check the application logs for the output from the logging statements. Observe the thread name and whether it is marked as a virtual thread.

### Output of `uname -a` or `ver`

Linux latitude 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7

**Comment by otavioprado** [comment]
@mkouba 
Do you know if there are plans to add support for virtual threads in quarkus-undertow when Jakarta EE 11 is released? It would be great to know if this is on the roadmap.

Thank you!

**Comment by mkouba** [comment]
I don't know if there's a plan to add VT support to `quarkus-undertow` but given the fact that Servlet API is not the preferred programming model for webapps in Quarkus (compared to `quarkus-rest`, `quarkus-grpc`, etc.) I don't think it would be a high priority.

**Comment by cescoffier** [comment]
There is no plan to support virtual threads with undertow (servlets).
