### ISSUE TITLE
Error using UriInfo in ResponseExceptionMapper with reasteasy reactive.

### ISSUE THREAD

**Issue by CarlosPanarello** [quarkusio/quarkus#42281]
### Describe the bug

Since migrating from quarkus 2.16 to quarkus 3.8.5, I started receiving the error `java.util.concurrent.CompletionException: java.lang.IllegalStateException: No RESTEasy Reactive request in progress` I find that this is related to the use of `@Context UriInfo` inside `ResponseExceptionMapper`. To get around this, I created a filter and a RequestScoped class to get the path or pathTemplate that caused the error.  

This also happened in the rest and rest-client filters, but I managed to get the path and pathTemplate with some casts but this doesnt smell good, this is the class LogFilter in pathTemplate method at project in how to reproduce section.

### Expected behavior

Using `@Context UriInfo` or `@Context ResourceInfo` without error .

### Actual behavior

When using `@Context UriInfo or ResourceInfo` in quarkus 3.8.5 with RESTeasy-reactive throw a error `java.util.concurrent.CompletionException: java.lang.IllegalStateException: No RESTEasy Reactive request in progress`

### How to Reproduce?

Reproducer error :

1. Clone project from https://github.com/CarlosPanarello/quarkus-rest-problem
2. run with mvn compile quarkus:dev
3. await some seconds

This project use scheduler to create users and add then using rest-client, if user id is even it will generate an error that will be catch in ExceptionMapper class, where i`m using UriInfo to get origin path, this class has some TODO where you can change to make this work properly.

### Output of `uname -a` or `ver`

Linux ZZAED-FG1234Z1Z 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS

### Quarkus version or git rev

3.8.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.5

**Comment by geoand** [comment]
This actually now works as expected as `UriInfo` refers to the server data, not the client data and in the case you are showing, the is no server request in progress as the call to the client is being made by a scheduler invocation.

**Comment by CarlosPanarello** [comment]
> This actually now works as expected as `UriInfo` refers to the server data, not the client data and in the case you are showing, the is no server request in progress as the call to the client is being made by a scheduler invocation.
> 
> I assume what you are trying to do is obtain the URI that was used in REST call?

Yes, i need to get path and pathTemplate (that is used inside annotation @Path).  Looking in Response class, when is instance of ClientResponseImpl , there has a RestClientRequestContext wich have the info i need, but is protected property. Because of that create a filter to get this info from request to use in ResponseExceptionMapper class. do you know better way than this? .

**Comment by geoand** [comment]
What you are doing is generally not correct, but I completely understand why you are resorting to such trick: The Jakarta REST API is generally very bad in this respect. 

What is you can is something like this:

```java
public class ExceptionMapper implements ResteasyReactiveResponseExceptionMapper<MyRuntimeException> {

    @Override
    public MyRuntimeException toThrowable(Response response, RestClientRequestContext context) {
        PathInfo pathInfo = (PathInfo) context.getProperty("PathInfo");

        //TODO uncomment this to work
        //var path = restClientPathInfo.of().path();

        return new MyRuntimeException(pathInfo.path(), "Mapper Error RestClient Example") ;
    }
}

@Provider
@Priority(Priorities.AUTHENTICATION+1)
public class RestClientPathInfoFilter implements ClientRequestFilter {


        @Override
        public void filter(ClientRequestContext request) {
            request.setProperty("PathInfo", new PathInfo(request.getUri().getPath(), pathTemplate(request)));
        }

        String pathTemplate(ClientRequestContext request) {
            return String.valueOf(request.getProperty("UrlPathTemplate"));
        }
}
```

This is a subpar experience however, so I am thinking that I should update the `@ClientExceptionMapper` to have the ability to inject this information.

**Comment by geoand** [comment]
I have opened #42293 to track the proposed enhancement.

**Comment by CarlosPanarello** [comment]
Thanks @geoand , besides that I have done some casts to get pathTemplate in RESTEasy filters like [this]( https://github.com/CarlosPanarello/quarkus-rest-problem/blob/f5c420253eac648ff90b78e8243aa7f5966162e6/src/main/java/org/acme/filter/LogFilter.java#L40)
```java
    String pathTemplate(ContainerRequestContext request){
        return ((ResteasyReactiveRequestContext)((ContainerRequestContextImpl) request).getServerRequestContext()).getTarget().getPath().template;
    }

    String pathTemplate(ClientRequestContext request) {
        return String.valueOf(((ClientRequestContextImpl) request).getRestClientRequestContext().getProperties().get("UrlPathTemplate"));
    }
```
Do you know a better way to do it?

**Comment by geoand** [comment]
I need to provide a proper API so you can access that

**Comment by geoand** [comment]
I am trying to think of what the best way to access `UrlPathTemplate` would be... Any proposals?

**Comment by FroMage** [comment]
I would help, but I've no idea what this is :-/ Also, perhaps best to ask that question on #42408 ?

**Comment by geoand** [comment]
It contains the path declared on the annotation (so it can be a template)

**Comment by geoand** [comment]
@FroMage see https://github.com/quarkusio/quarkus/issues/42408#issuecomment-2326273748
