### ISSUE TITLE
Can't change between light and dark mode in DevUI

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#42297]
### Describe the bug

I'm not sure how long this is not possible, but when I click the icon in the top right corner to change the theme in DevUI, the icons pop up, but they are not clickable. So I'm unable to change to a different theme.

### Expected behavior

DevUI can change the theme.

### Actual behavior

Not possible to change the theme in DevUI.

### How to Reproduce?

- Open DevUI.
- Click the icon in the top right corner.
![2024-08-02-1722609908_316x62](https://github.com/user-attachments/assets/3d03f816-3124-4c5b-98f8-9dfcf81a08f5)
- Try to change the theme, I can't click any of the icons that pop up.
![2024-08-02-1722609885_324x110](https://github.com/user-attachments/assets/058051a1-de43-4d12-a5a3-7a94e9ef6aa5)
- After you click away, they disappear but the monitor icon doesn't appear again unless DevUI restarts.

**Comment by melloware** [comment]
Confirmed I see this also.

**Comment by phillip-kruger** [comment]
Probably with the last vaadin-web-components upgrade. I am having a look
