### ISSUE TITLE
Working Directory for mvnw compile quarkus:dev

### ISSUE THREAD

**Issue by brentcrammond** [quarkusio/quarkus#4229]
**Description**
The current system changes the working directory when run using "mvnw compile quarkus:dev" to the target/classes directory.  This basically comes down to an unexpected behaviour. 

A basic tenant I normally work to is "when I run something from a directory I expect it to be running in that directory rather than changing to another directory."

As mentioned in the bug report that I believe this will be confusing for anyone new to the Quarkus framework as it is an unexpected behaviour.

![Screen Shot 2019-09-27 at 08 30 12](https://user-images.githubusercontent.com/6261538/65722826-34e2b380-e101-11e9-8f63-7f7af41b0483.png)

[QuarkusExample.zip](https://github.com/quarkusio/quarkus/files/3659773/QuarkusExample.zip)

The above code has been modified (from that provided in the bug report) slightly to better explain the issue.

See related Issue https://github.com/quarkusio/quarkus/issues/4205.

I believe this will save people new to the framework a significant time, effort.  I am concerned that it will put people off this fantastic framework.  I is very important make sure that the framework behaviour is what you would expect.  

**Implementation ideas**
This is the example of what I mean.

The internal application.properties has the quarkus.http.port set to 9090 and the external my_application.properties file has the quarkus.http.port set to 9292.

When I start up the application either through
mvnw compile quarkus:dev

or
java -jar target/quarkus-example-runner.jar

I am expecting it to listening on 9292.

Actual behavior
When started with the mvnw compile quarkus:dev it listens on 9090 (and can't find the my_application.properties) and java -jar target/quarkus-example-runner.jar listens on 9292.

As pointed out in the bug to me, I could get it to work by putting an absolute path to the external my_application.properties and it would work.  But that fact that it has changed directory is confusing.

**Comment by paulolieuthier** [comment]
Looks like [here](https://github.com/quarkusio/quarkus/blob/7a0679e6cd06084a3aa8db2b74bd08fdec1dc3a7/devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java#L311).
