### ISSUE TITLE
Records that contain Enum are still unsupported with @ParameterizedTest even with Serializable in 3.13.0

### ISSUE THREAD

**Issue by yk-littlepay** [quarkusio/quarkus#42301]
### Describe the bug

This is kind of this [#40148](https://github.com/quarkusio/quarkus/issues/40148) , [#42006](https://github.com/quarkusio/quarkus/issues/42006) and[#42098](https://github.com/quarkusio/quarkus/issues/42098).
When a @ParameterizedTest contains a record as a parameter that has an enum property the error is thrown like this
`[ERROR]   GreetingResourceTest.should_postUsers(UserRequest)[1] » IllegalState Error calling onstructor on record class class org.acme.model.UserRequest` if remove enum then it starts to work.

PS. But the same test works fine with Serializable as expected  in 3.12.3 

### Expected behavior

Each @ParameterizedTest must accept a `record` containing a property of `Enum<E extends Enum<E>>` type

### Actual behavior

Each @ParameterizedTest is failed if a parameter is a record that contains enum property

### How to Reproduce?

Create any `@ParameterizedTest` with `@MethodSource("requestSamples")` where the method `requestSamples ` provides a `Stream<SomeRecord>` and `SomeRecord ` looks like
```
public record SomeRecord(String name, SomeEnum someEnum) { 
    enum SomeEnum { A, B, C }
}
```
here is some project example 
[code-with-quarkus.zip](https://github.com/user-attachments/files/16473049/code-with-quarkus.zip)

**Comment by gsmet** [comment]
@dmlloyd could you have a look at this one? It's a regression in 3.13.

**Comment by holly-cummins** [comment]
Another side effect of #40601.

**Comment by geoand** [comment]
https://github.com/jboss-remoting/jboss-marshalling/pull/147 fixes the problem, but I am really not sure it's the proper fix, so we'll have to wait until @dmlloyd is back :)
