### ISSUE TITLE
Quarkus instrument live-reload doesn't work when using Kotlin 1.8+

### ISSUE THREAD

**Issue by lujun2** [quarkusio/quarkus#42302]
### Describe the bug

Kotlin 1.8+ introduce [@SourceDebugExtension](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/runtime/kotlin/jvm/internal/SourceDebugExtension.kt)

This annotation is used to embed Kotlin bytecode or something like. 
Every single byte of Kotlin source code change will generate different `@SourceDebugExtension`

When enable `quarkus.live-reload.instrumentation`, it will [check the class structure is same or not](https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/dev/ClassComparisonUtil.java#L170) before reload.
This check always fail and fallback to application restart.

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/92d3b500-d9f7-402e-82be-d7e8662c4109">

### Expected behavior

When `quarkus.live-reload.instrumentation` enabled only affected classes be replaced when Kotlin source code changes

Should provide a mechanism to exclude unrelated annotation value comparison in dev mode.

### Actual behavior

Kotlin source code change trigger application restart

### Output of `uname -a` or `ver`

Darwin Juns-MBP.local 24.0.0 Darwin Kernel Version 24.0.0: Sat Jul 13 00:58:03 PDT 2024; root:xnu-11215.0.165.0.4~50/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "21.0.2" 2024-01-16 LTS

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.9

### Additional information

Kotlin version: 2.0.20-RC

**Comment by geoand** [comment]
Thanks a lot for debugging this!

Since you have figured out what the problem is, would you like to propose a Pull Request that addresses the issue?

**Comment by lujun2** [comment]
I'd like to, but need some suggestion

## Solution 1

disable `@SourceDebugExtension` via Kotlin compiler option `-Xno-source-debug-extension` in [KotlinCompilationProvider](https://github.com/quarkusio/quarkus/blob/b5231da73dbab06e869941aaf2c4e87d79233aac/extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinCompilationProvider.java#L48C15-L48C37)
Kotlin compiler arguments defined in Maven/Gradle settings also need to be configured

because the initial compiled class is usually generated by Maven/Gradle plugin, and the live reload is another process, they don't share the same configuration

> I don't think this is a good solution, since it need extra documentation and may have some side  effect

## Solution 2

another solution is to modify `ClassComparisonUtil`, ignore unrelated annotation values during live reload

@geoand any suggestion

**Comment by geoand** [comment]
I would modify `ClassComparisonUtil` to specifically ignore `@SourceDebugExtension`  - we could have some list of annotations that are ignored which for now would contain only `@SourceDebugExtension`
