### ISSUE TITLE
Vert.x Cache Directory configuration ignored

### ISSUE THREAD

**Issue by frootshoot** [quarkusio/quarkus#42313]
### Describe the bug

the new vertx configuration for cache directory "quarkus.vertx.cache-directory" is being ignored

### Expected behavior

When setting "quarkus.vertx.cache-directory" configuration property the vert.x cache directory should use this value

### Actual behavior

The configuration option is ignored - this is due to a bad "if" statement in VertxCoreRecorder (lines 336 - 339)

```
String fileCacheDir = System.getProperty(CACHE_DIR_BASE_PROP_NAME);
if (fileCacheDir != null) {
      fileCacheDir = conf.cacheDirectory().orElse(null);
}
```

The if statement should read "fileCacheDir == null" - as you only want to use the configuration if the standard vert.x one is NOT set as per the documentation.

### How to Reproduce?

Simply start any Quarkus process with the configuration set, and it will be ignored.

**Comment by geoand** [comment]
Makes sense!

Would you like to provide a PR fixing the issue?

**Comment by frootshoot** [comment]
> Makes sense!
> 
> Would you like to provide a PR fixing the issue?

Sadly still not in a position to actually provide code fixes yet - working on it ..

**Comment by geoand** [comment]
No rush!

**Comment by geoand** [comment]
@frootshoot if you would like us to fix this, that's certainly fine too

**Comment by gaol** [comment]
I would like to work on this one if nobody is working on it yet as my first code contribution :)
