### ISSUE TITLE
JPA writes don't work when using ONLY named data sources since 3.13.0

### ISSUE THREAD

**Issue by krisztiankocsis** [quarkusio/quarkus#42314]
### Describe the bug

We upgrade Quarkus from 3.12.0 -> 3.13.0. We are using 3 named data sources / Hibernate ORM configuration - no default data source is configured. This was working till 3.13.0. DB reads still work, but as soon as we do any update agains a named DB, we get the following exception:

The default datasource has not been properly configured. See https://quarkus.io/guides/datasource#jdbc-datasource for information on how to do that.

### Expected behavior

Both DB reads/writes work the same way as in the previous version, and not complaining about unconfigured default data source - we don't need such.

### Actual behavior

It is throwing an exception about the missing default data source configuration.

### Output of `java -version`

21

### Quarkus version or git rev

3.13.0

**Comment by krisztiankocsis** [comment]
Downgrading back to 3.12.3, it starts working again as expected (updates going through without having such an exception).

**Comment by geoand** [comment]
Thanks for reporting.

I assume you mean `3.13` and not `1.13`, correc?

**Comment by krisztiankocsis** [comment]
> Thanks for reporting.
> 
> I assume you mean `3.13` and not `1.13`, correct?

Yeap, its 3.13 (and 3.12 is working).

**Comment by gsmet** [comment]
@krisztiankocsis can you provide the full stacktrace?

**Comment by gsmet** [comment]
Also it would help if you could assemble a small reproducer so that we could reproduce the issue easily.

**Comment by krisztiankocsis** [comment]
`{
  "timestamp": "2024-08-08T11:42:48.239339829+02:00",
  "sequence": 3211,
  "loggerName": "com.bmw.ipdm.cedec.simon.control.AbstractWorkerThread",
  "level": "ERROR",
  "message": "An unexpected error occurred in ZAK Transmission thread loop",
  "threadName": "ZAK Transmission",
  "threadId": 68,
  "mdc": {},
  "ndc": "",
  "exception": {
    "refId": 1,
    "exceptionType": "java.lang.IllegalStateException",
    "message": "The default datasource has not been properly configured. See https://quarkus.io/guides/datasource#jdbc-datasource for information on how to do that.",
    "frames": [
      {
        "class": "io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations",
        "method": "getSession",
        "line": 74
      },
      {
        "class": "io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations",
        "method": "executeUpdate",
        "line": 485
      },
      {
        "class": "io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations",
        "method": "update",
        "line": 515
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.entity.simon.SimonSimulationDataRecord",
        "method": "update"
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.SimulationDataStore",
        "method": "acquireForExecution",
        "line": 701
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.SimulationDataStore_Subclass",
        "method": "acquireForExecution$$superforward"
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.SimulationDataStore_Subclass$$function$$1",
        "method": "apply"
      },
      {
        "class": "io.quarkus.arc.impl.AroundInvokeInvocationContext",
        "method": "proceed",
        "line": 73
      },
      {
        "class": "io.quarkus.arc.impl.AroundInvokeInvocationContext",
        "method": "proceed",
        "line": 62
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase",
        "method": "invokeInCallerTx",
        "line": 335
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired",
        "method": "doIntercept",
        "line": 40
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase",
        "method": "intercept",
        "line": 61
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired",
        "method": "intercept",
        "line": 32
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean",
        "method": "intercept"
      },
      {
        "class": "io.quarkus.arc.impl.InterceptorInvocation",
        "method": "invoke",
        "line": 42
      },
      {
        "class": "io.quarkus.arc.impl.AroundInvokeInvocationContext",
        "method": "perform",
        "line": 30
      },
      {
        "class": "io.quarkus.arc.impl.InvocationContexts",
        "method": "performAroundInvoke",
        "line": 27
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.SimulationDataStore_Subclass",
        "method": "acquireForExecution"
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.SimulationDataStore_ClientProxy",
        "method": "acquireForExecution"
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.zak.FutureSimulationFetcher",
        "method": "findAndAcquireOldestInitiatedNotDeadNotPreventedSimulation",
        "line": 85
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.zak.FutureSimulationFetcher_Subclass",
        "method": "findAndAcquireOldestInitiatedNotDeadNotPreventedSimulation$$superforward"
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.zak.FutureSimulationFetcher_Subclass$$function$$1",
        "method": "apply"
      },
      {
        "class": "io.quarkus.arc.impl.AroundInvokeInvocationContext",
        "method": "proceed",
        "line": 73
      },
      {
        "class": "io.quarkus.arc.impl.AroundInvokeInvocationContext",
        "method": "proceed",
        "line": 62
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase",
        "method": "invokeInOurTx",
        "line": 136
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase",
        "method": "invokeInOurTx",
        "line": 107
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired",
        "method": "doIntercept",
        "line": 38
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase",
        "method": "intercept",
        "line": 61
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired",
        "method": "intercept",
        "line": 32
      },
      {
        "class": "io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean",
        "method": "intercept"
      },
      {
        "class": "io.quarkus.arc.impl.InterceptorInvocation",
        "method": "invoke",
        "line": 42
      },
      {
        "class": "io.quarkus.arc.impl.AroundInvokeInvocationContext",
        "method": "perform",
        "line": 30
      },
      {
        "class": "io.quarkus.arc.impl.InvocationContexts",
        "method": "performAroundInvoke",
        "line": 27
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.zak.FutureSimulationFetcher_Subclass",
        "method": "findAndAcquireOldestInitiatedNotDeadNotPreventedSimulation"
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.zak.FutureSimulationFetcher",
        "method": "getNextExecutableSimulation",
        "line": 61
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.zak.SimulationTransmissionThread",
        "method": "runActionRepeatedly",
        "line": 45
      },
      {
        "class": "com.bmw.ipdm.cedec.simon.control.AbstractWorkerThread",
        "method": "run",
        "line": 64
      }
    ]
  }
}`

Here is the stack trace.
Note that the code is called from a thread NOT managed by Quarkus!
However, this was working in 3.12.3.

DB updates comming from a Vert.X worker thread seem to work.

@gsmet

**Comment by krisztiankocsis** [comment]
Maybe the issue is with the non-managed thread, and not the multiple data sources.

**Comment by krisztiankocsis** [comment]
We have 3 special threads, so we need a solution to be able to keep them.

**Comment by marko-bekhta** [comment]
I didn't see any obvious change in 3.13 to explain the different behaviour..  Is there any chance you can create a small reproducer @krisztiankocsis, as Guillaume was suggesting? That'll help us track down the reason for this change of behaviour. Thanks!

**Comment by gsmet** [comment]
I think I found the culprit and this is embarrassing.

**Comment by gsmet** [comment]
Should be fixed by https://github.com/quarkusio/quarkus/pull/42400.

**Comment by krisztiankocsis** [comment]
I checked the changes in the fix commit. That perfectly makes sense. Thanks for the quick fix @gsmet!

**Comment by gsmet** [comment]
@marko-bekhta added some tests. I will merge once CI is green.

I think I will expedite a 3.13.2 once this is merged as it's rather annoying. Thanks for the report!

**Comment by gsmet** [comment]
I will announce it on Monday morning but I released 3.13.2 today with the fix.

**Comment by krisztiankocsis** [comment]
Its working! Thanks @gsmet !
