### ISSUE TITLE
Websocket extension: cannot connect to a web socket

### ISSUE THREAD

**Issue by ailiskovic** [quarkusio/quarkus#42318]
### Describe the bug

I followed the guide described on [https://quarkus.io/guides/websockets](url), upon starting the server (with only this extension installed) I tried to connect to a web socket, but got:  **Error: connect ECONNREFUSED ::1:8080**

The server uses default settings and it's hosted on localhost:8080. 

### Expected behavior

I should be able to connect to a web socket

### Actual behavior

Not able to connect to a web socket. 

### How to Reproduce?

1. Generate new app on [https://code.quarkus.io/](url) with only WebSockets extension. 
2. Build and start application. 
3. Try to connect to a web socket (I used Postman to test the connection and sent CONNECT as message upon sending connect request)

### Output of `java -version`

Java 21

**Comment by mkouba** [comment]
@ailiskovic pls provide a reproducer app if possible or at least document the exact way how exactly did you try to connect to the WS endpoint.

Also consider using the WebSocket Next extension instead. It will become the preferred solution in the near future. See also [Getting started with WebSockets Next](https://quarkus.io/guides/websockets-next-tutorial) and [WebSockets Next extension reference guide](https://quarkus.io/guides/websockets-next-reference).

**Comment by ailiskovic** [comment]
The example in [Getting started with WebSockets Next](https://quarkus.io/guides/websockets-next-tutorial) works as expected. 

Thank you!
