### ISSUE TITLE
Explicit flush needed in 3.13.0 spring-data-jpa when running `@Query` that updates foreign key column with newly saved associated entity

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#42322]
### Describe the bug

Starting from 3.13.0.CR1 (#41284 respectively), an explicit flush is needed to make sure that a `@Query('update A set associatedB where ...')` [repository method](https://quarkus.io/guides/spring-data-jpa#user-defined-queries) does not run into a foreign key constraint violation when the other entity (here: `B`) was just created in the same transaction (shortly before the update).

In other words, the following fails in 3.13.0 (but works in 3.12):
- `B b = new B(...)`
- `BRepository.save(b)`
- `ARepository.updateAssociatedB(b)` <- foreign key constraint violations (b doesn't exist)

Using `BRepository.saveAndFlush(b)` works around the issue.

### Expected behavior

No explicit flush needed; persistence layer/Hibernate should detect on its own that a flush is needed.

### Actual behavior

Explicit flush required.

### How to Reproduce?

https://github.com/quarkusio/quarkus-quickstarts/compare/main...famod:quarkus-quickstarts:spring-jpa-flush

1. check out the `spring-jpa-flush` branch
2. fails: `./mvnw clean install -f spring-data-jpa-quickstart`
3. works: `./mvnw clean install -f spring-data-jpa-quickstart -Dquarkus.platform.version=3.12.3`

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.8

### Additional information

First reported here: https://github.com/quarkusio/quarkus/pull/41284#issuecomment-2242385942

I haven't had the time yet to report the issue upstream via `QuarkusLikeORMUnitTestCase`.

**Comment by gsmet** [comment]
@beikov @dreab8 any chance one of you could have a look at this one so that we understand why the behavior changed?

**Comment by dreab8** [comment]
@gsmet looking into it

**Comment by dreab8** [comment]
The update query was triggering a flush only because the default flush mode was set to ALWAYS but this has been changed by [#41284 ](https://github.com/quarkusio/quarkus/pull/41284) so Hibernate executes a flush after a query only when the result of the query may be affected by dirty state not synchronised with the db  [flush on JPQL/HQL query](https://docs.jboss.org/hibernate/orm/6.5/userguide/html_single/Hibernate_User_Guide.html#_auto_flush_on_jpqlhql_query) and in this case
```
var fruit = fruitRepository.findByName("Apple").orElseThrow(NotFoundException::new);
var logEntry = new FruitLogEntry(fruit, LocalDateTime.now() , "foo");
fruitLogEntryRepository.save(logEntry);
fruitRepository.updateLastLogEntry(fruit.getId(), logEntry);
```
 the executed query `update Fruit set lastLogEntry = :logEntry where id = :fruitId` affects only the `Fruit` entity that is not dirty, so no flush is expected to happen.

**Comment by famod** [comment]
@dreab8 thanks for your analysis.

So basically your are saying that Hibernate ORM is not meant to detect this case, hence no bug in Hibernate, right?

**Comment by dreab8** [comment]
yes this is not a bug, hibernate flushes the session only if fruit entity is dirty (e.g `fruit.setColor( "Green" );` ) when the query is executed.

**Comment by famod** [comment]
> I noticed that spring offers this annotation ` @Modifying(flushAutomatically = true)` but is seems not working

I think I know why. I'll try to come up with a PR soonish.

**Comment by famod** [comment]
So, I'm under the impression that this issue is to be closed as won't fix. Any objections?

**Comment by yrodiere** [comment]
Agreed, since the problem was not quite the one described in the issue. Thanks for the fix.

**Comment by famod** [comment]
Hi @yrodiere,
> Agreed, since the problem was not quite the one described in the issue. Thanks for the fix.

To avoid confusion: I've never used `flushAutomatically` and even after the fix (#42376 / Quarkus 3.13.2) I won't be using it for the cases that lead to this issue.
When @dreab8 mentioned `flushAutomatically` (and reporting it as broken) I was just interested in why it didn't work and had a quick look.

So what I'm trying to say is that with Quarkus 3.13.0 I need and explicit flush, in one way or the other.
And as @dreab8 described, Hibernate is not supposed to detect the need for a flush in the cases I described.

**Comment by yrodiere** [comment]
Thanks for the clarification.

So your patches addresses `flushAutomatically`, which you don't personally use but were kind enough to fix anyway (thanks!).

Can you confirm you don't need any other change? I.e. that migration notes sort of address your problem, which was only that your application was relying on flushes that were never meant to happen?

**Comment by famod** [comment]
> Can you confirm you don't need any other change? I.e. that migration notes sort of address your problem, which was only that your application was relying on flushes that were never meant to happen?

Of course it would be nice if Hibernate would detect that special case automatically, but I'm ok with the explicit flushes. :-)

**Comment by yrodiere** [comment]
Right, by "other changes" I meant "changes in Quarkus or bugfixes in Hibernate".

Filing feature requests to Hibernate ORM is still an option, of course :)
