### ISSUE TITLE
OIDC documentation not explaining format for realm files

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#42330]
### Describe the bug

For the devservice of oidc the format of the files for property [`quarkus.keycloak.devservices.realm-path`](https://quarkus.io/guides/dev-services#quarkus-keycloak-devservices-keycloak-keycloak-build-time-config_quarkus-keycloak-devservices-realm-path) is not explained or linked, also it's not clear where these files have to be in the project to be loaded

### Expected behavior

* The json schema of the realm files should be linked or at least a documentation on how to create these files by hand.
* It should be explained where these files have to be, something like "files have to be in the resources"

### Actual behavior

the javadoc of the property does not help find these information, so in the guide pages it's also not clear how to use this property

### Quarkus version or git rev

3.8,  and main (b5231da73dbab06e869941aaf2c4e87d79233aac)

**Comment by sberyozkin** [comment]
@bulldog98 JavaDocs is saying it is a class or file system resource. Realm is not a quarkus concept, and you can't really create it manually. 
Would you like to open a doc PR adding some clarifications like mentioning `src/main/resources`, and adding a link to Keycloak docs related to creating realms ?

**Comment by bulldog98** [comment]
@sberyozkin sure I'm willing to do a PR.

Note the guide to [importing and exporting a realm](https://www.keycloak.org/server/importExport)
