### ISSUE TITLE
Review a quarkus-vertx-keycloak module name

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4235]
Because it is not based on the keycloak specific adapter code any longer and it does not support Keycloak API such as KeycloakConfigResolver and it is meant to be generic (work with any 3rd party OIDC providers)

**Comment by sberyozkin** [comment]
@stuartwdouglas 
I've looked at the code more carefully and I understand it better why you call it `quarkus-vertx-keycloak` :-), but I do feel it would be better to make a clean break now with something like `quarkus-vertx-oidc` because otherwise we will keep sending some kind of a message that it is Keycloak based, but it won't be, given the generic nature of the Vertx adapter which can validate tokens from not only KC as far as I understand. With `quarkus-vertx-oidc` we will be safe irrespective of the implementation decisions at the Vertx level

**Comment by sberyozkin** [comment]
As discussed with @pedroigor as well, the proposal is to to rename `quarkus-vertx-keycloak` to `quarkus-vertx-oidc`; Configuration properties should have `oidc` instead of `keycloak` as well I guess. The question is, should we have it done for 0.24.0 to minimize the migration pain :-) ? If we rename it later then the users will have to deal with the major changes twice. So I feel we should do it now, what do you think ?

**Comment by gsmet** [comment]
FWIW, I’m not totally happy with having vertx in the name. 

People using RESTEasy will use Vert.x underneath but they won’t really be aware of it. But they are clearly the target of this extension. Will they think they can use it or not, that’s the question. 

@emmanuelbernard WDYT?

**Comment by emmanuelbernard** [comment]
Same here. Let’s name it after the usage. Not the implementation.

**Comment by stuartwdouglas** [comment]
I thought our naming policy was implementation-feature (hibernate-orm,
smallrye-health etc)?

I know we went through and renamed everything a while ago so most things
follow this pattern but not everything, is there an official rule on when
an extension should not follow this pattern?

**Comment by sberyozkin** [comment]
@stuartwdouglas We had `quarkus-keycloak` and what I've focused on in this issue is on replacing a `keycloak` bit since no keycloak-specific API has stayed and the Vertx based adapter is generic. So if we have `quarkus-oidc` then the naming pattern would stay consistent with the original `quarkus-keycloak` pattern (which was not called `quarkus-undertow-keycloak` because it was based on the Undertow adapter). Let me give it a try :-)

**Comment by stuartwdouglas** [comment]
Can you submit a pr to do the rename?

**Comment by sberyozkin** [comment]
@stuartwdouglas Yes, I'm focusing on the security related work from today (I only have one unrelated quarkus quickstarts issue to fix but the work has been mostly done there)

**Comment by stianst** [comment]
Perhaps obvious, but as it is renamed to be more generic so should the config options. One example is to set the URL of the IdP it should be setting the URL of the discovery endpoint (with or without .well-known/openid-configuration, as that can be added if missing). So for configuring Keycloak it should be something like:

discoveryUrl=https://auth.company.com/auth/realms/myrealm

Instead of auth-server-url and realm which Keycloak adapters use.

**Comment by sberyozkin** [comment]
@stianst I see, missed this comment; I'd like @pedroigor to review if it is possible to collapse these two properties into a single one such that it actually works at the Vertx adapter level;

**Comment by sberyozkin** [comment]
@stianst @pedroigor @stuartwdouglas FYI, https://github.com/quarkusio/quarkus/issues/4392, I've opened a new issue to track it
