### ISSUE TITLE
Quarkus Temporal Extension 

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#42358]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

Temporal is a popular workflow engine

https://temporal.io/

This extension will allow to trigger workflows from quarkus (client mode) as well as run temporal workers directly from quarkus code.

See the existing integration with spring boot:
https://learn.temporal.io/tutorials/java/build-an-email-drip-campaign/

### Repository name

quarkus-temporal

### Short description

Build invincible applications

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- workflow 
...

### Team Members

- rmanibus

**Comment by rmanibus** [comment]
yeah I saw this project but assumed it was abandoned

**Comment by melloware** [comment]
It looks like a decent start though. I posted and asked him how alive it was an whether he wanted to move it to a Quarkiverse extension.

**Comment by tmulle** [comment]
@rmanibus I too saw that extension and it looked old ~3years so I just ended up manually configuring the temporal workflow and activity workers using the bare Temporal APis. It's not hard and I followed the examples from their Java SDK. 

The only thing that looks like a little snag is that  you can't seem to do @Inject with your workflow implementation classes. Temporal has to stub that out. But you can @Inject your activities into your workflows. 

Other than that, it's pretty simple boiler plate to use the Temporal code. 

I built a 6 service microservice online ordering system for my company and using Temporal is going to be great for handling all the service failure, retry logic, dashboard UI for Workflow viewing, etc.

All of that stuff I would've had to write by hand...I just learned of Temporal about a 2 months ago and when I saw it I knew it was exactly what we needed.

**Comment by melloware** [comment]
@tmulle but you have not tried it in Native mode yet right?

**Comment by tmulle** [comment]
I did try it actually and it failed..something with the version of Netty they used I think. There is this forum post I saw but never really looked into it.

https://community.temporal.io/t/issue-on-building-with-graalvm-native-image-discovered-unresolved-type-during-parsing-io-grpc-netty-shaded-io-netty-util-internal-logging-log4j2logger/9124

**Comment by melloware** [comment]
OK to get it running in Native mode is probably why this would need a Quarkiverse Extension.

That is why the Extension dev had this: https://github.com/mostafacs/quarkus-temporal-extension/blob/main/deployment/src/main/java/io/quarkus/temporal/client/deployment/graalvm/NettyShadedProcessor.java  To handle Netty issues with GraalVM.

**Comment by rmanibus** [comment]
this project can definitely be used as a base for the native part. 
I also have this available: https://github.com/rmanibus/quarkus-temporal
there are two artifacts, the second one is providing the mock environment

**Comment by melloware** [comment]
@rmanibus awesome!   @gastaldi i think this is an Extension worth getting started as Temporal is pretty awesome and @rmanibus  is willing to get it started and @tmulle and @melloware are interested in seeing it successful.

**Comment by gastaldi** [comment]
`Build invincible applications` is a rather confusing description, how about : `Temporal (https://temporal.io/) is a developer-first, open source platform that ensures the successful execution of services and applications.`?

**Comment by melloware** [comment]
Sounds good to me.  I think if we get it working you guys will be really impressed with a Demo we can put together maybe for a Quarkus Insights!

**Comment by rmanibus** [comment]
Would love to be part of this @melloware !

**Comment by gastaldi** [comment]
Let's begin then: https://github.com/quarkiverse/quarkus-temporal is online ;)

**Comment by melloware** [comment]
@rmanibus do you want to move your code over to that new GitHub repo?

**Comment by rmanibus** [comment]
yep it's done, I think it's missing all the CI / all contrib part though, is there any automation add that ?

**Comment by rmanibus** [comment]
thank you !

**Comment by gastaldi** [comment]
Perhaps we should add @melloware as a committer to this repo? Sounds like it would be really productive this way

**Comment by gastaldi** [comment]
Done in https://github.com/quarkiverse/quarkiverse-devops/pull/260, waiting for @rmanibus's approval now

**Comment by melloware** [comment]
that would be great @gastaldi i plan on getting all the Quarkivrese goodness set up etc.
