### ISSUE TITLE
QuarkusTest reloading CDI for each test class with v3.13 (related to @WithTestResource)

### ISSUE THREAD

**Issue by PedroRodP** [quarkusio/quarkus#42365]
### Describe the bug

New annotation `@WithTestResource` from v3.13.0 restricts the resource to the annotated class by default, so I would expect it to be executed once per test class. But I noticed that using it in this way also makes the CDI to be reloaded, as my `@Startup` method is being called more than once when running the whole test set, so the execution time increase becomes remarkable if tasks are heavy.
When setting `restrictToAnnotatedClass` to _false_, it seems to fall back to the previous behavior, sharing both the resource and the context across the test classes (as with `@QuarkusTestResource` in v3.12.3).

Is this expected? I currently need to use dependency injection to configure an instance and execute some code just once when running all tests. I'm not using test resources for that since I can't inject a bean into these. 

### Expected behavior

I'd expect the `QuarkusTestResourceLifecycleManager` implementations to be isolated for each test class with the new `@WithTestResource` annotation default behavior, while my `@ApplicationScoped` class being created just once.

### Actual behavior

Both `QuarkusTestResourceLifecycleManager` implementations and `@ApplicationScoped` classes are being created for each test class when using `@WithTestResource(restrictedToAnnotatedClass = true)`.

### How to Reproduce?

I uploaded [this little project](https://github.com/PedroRodP/quarkus-test-behavior-3.13) so you can check it. You can test the behavior by playing with the `restrictToAnnotatedClass` flag and checking the logs my test resource and my application scoped class are printing.

### Output of `uname -a` or `ver`

Darwin Pedros-MacBook-Pro.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:59 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6030 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

### Time taken when restrictToAnnotatedClass = true
<img width="881" alt="image" src="https://github.com/user-attachments/assets/7c3f1d4e-f777-4f59-a6ef-5504e8ba4794">
<img width="999" alt="image" src="https://github.com/user-attachments/assets/9bc3da3b-70e0-40e9-8870-b70b9eb67671">

You can see that my logs are printed twice (once per test class) and Quarkus was reloaded.

### Time taken when restrictToAnnotatedClass = false
<img width="865" alt="image" src="https://github.com/user-attachments/assets/6e1eced3-1369-4c47-8143-2fdb1df4592d">
<img width="539" alt="image" src="https://github.com/user-attachments/assets/88957e2a-476f-43a7-b6cd-31ee1a77f3e8">

Here there's no new logs, no reloading. And time has clearly decreased.

**Comment by mkouba** [comment]
CC @edeandrea

**Comment by edeandrea** [comment]
If you use `@QuarkusTestResource(restrictedToAnnotatedClass = true)` do you see the same behavior?

See https://github.com/quarkusio/quarkus/discussions/42298

**Comment by edeandrea** [comment]
And also, could you try downgrading your application to 3.12.3 and just update to use `@QuarkusTestResource(restrictAnnotatedClass=true)` and see if behavior is consistent?

**Comment by PedroRodP** [comment]
@edeandrea yep, same behavior when using `@QuarkusTestResource(restrictedToAnnotatedClass = true)` with v3.13.0. Quarkus is reloaded for each test class
<img width="865" alt="image" src="https://github.com/user-attachments/assets/90aa9c0b-e1a4-4daf-8696-1a0f5dd14b42">

And also for v3.12.3, which is consistent.
<img width="874" alt="image" src="https://github.com/user-attachments/assets/e7dae954-7ff0-41aa-81da-bdb38f6d1c9e">

So, as you mentioned in [#42298](https://github.com/quarkusio/quarkus/discussions/42298), we can confirm it's only a change in the default behavior, not a new bug. But is this the intended way of it to work when using `restrictToAnnotated` to _true_ or should it be reviewed?

**Comment by edeandrea** [comment]
> So, as you mentioned in https://github.com/quarkusio/quarkus/discussions/42298, we can confirm it's only a change in the default behavior, not a new bug. But is this the intended way of it to work when using restrictToAnnotatedClass to true or should it be reviewed?

My guess is that it should be reviewed, but I don't think I'm the right person to review it. I don't know much about how it works behind the scenes. All I did was create a new annotation.

For the time being, you can use `@WithTestResource(restrictToAnnotatedClass=false)` to revert to previous default behavior.

cc: @maxandersen @gsmet

**Comment by geoand** [comment]
> Is this expected? I currently need to use dependency injection to configure an instance and execute some code just once when running all tests. I'm not using test resources for that since I can't inject a bean into these.

This is not a bug, but it is the expected behavior.

What happens essentially is that Quarkus reruns the build time steps and "restarts" the application.
