### ISSUE TITLE
Setting quarkus.http.proxy.proxy-address-forwarding=true changes Host header to host

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#42367]
### Describe the bug

When running the following code without setting the `quarkus.http.proxy.proxy-address-forwarding` it returns the `Host` header.

```java
        @Context
        Instance<RoutingContext> routingContext;

        HttpServerRequest request = routingContext.get().request();

        MultiMap headers = request.headers();
```

When running the same code while quarkus.http.proxy.proxy-address-forwarding is set to true, it returns `host` (different case)

**Comment by geoand** [comment]
cc @sberyozkin

**Comment by gsmet** [comment]
Not sure what's exactly causing but headers are case insensitive. And the Vert.x header `MultiMap` is case insensitive.

**Comment by geoand** [comment]
> And the Vert.x header MultiMap is case insensitive.

True, but I think that only comes into play when you pull a specific name out of the map - when you iterate over the names, you can get whatever was put in.

@gbourant what's the use case for iterating over the names?

**Comment by geoand** [comment]
Gotcha, that sounds legit :)

**Comment by sberyozkin** [comment]
Thanks, I'll also CC @cescoffier

**Comment by cescoffier** [comment]
Yep, it should be `Host` following the convention.

**Comment by cescoffier** [comment]
`Host` and `host` should be equivalent. 

Netty uses the `host` header, which is what it used in this case. We could switch to `Host`, BUT... it has a performance regression as we cannot reuse the cached Netty buffer.

**Comment by cescoffier** [comment]
@gbourant can you try with: https://github.com/quarkusio/quarkus/pull/42648.

**Comment by gbourant** [comment]
@cescoffier I tried your change and it works as excepted. The MultiMap headers now contains the `Host` key. Thank you
