### ISSUE TITLE
Provide a way to execute some logic when the HTTP server is started

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#42366]
### Description

`StartupEvent`/`@Startup` does not help because the CDI event is fired _before_ the HTTP server is started.

The only workaround I can think of is to schedule a task in a `StartupEvent`/`@Startup` to execute some logic with a delay, e.g. something like:

```java
class MyBean {

   @Inject
   ScheduledExecutorService executor;

   @Startup
   void init() {
      executor.schedule(new Task(), 500, TimeUnit.MILLISECONDS);
   }
}
```

and non-blocking variant:

```java
class MyBean {

   @Inject
   Vertx vertx;

   @Startup
   void init() {
      vertx.setTimer(500, new Handler());
   }
}
```

This is of course not reliable at all because of the hard-coded delay.

### Implementation ideas

We could fire a specific CDI event, or introduce a special interface to be implemented by beans (e.g. `HttpServerListener`) and called when the server is listening. I'm proposing a CDI-specific API because that's what Quarkus users are used to do.

**Comment by geoand** [comment]
+1 for this. I'm pretty sure we've heard of similar requests in the past.

**Comment by mkouba** [comment]
> The one complication I can think of is that we would need to provide enough context so the users knows whether it's the HTTP or HTTPS server being started

Yes, I was thinking of separate events/methods for HTTP and HTTPS...
