### ISSUE TITLE
Centralize reference to UBI images (and maybe others)

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#42389]
In https://github.com/quarkusio/quarkus/pull/42316, we are adding more references to the UBI image and we should really centralize them in constants somewhere so that we don't have to update 10 places when updating.

I think we could have a `UbiImages` class somewhere in core to centralize this. And I have a vague recollection we have other images that are also affected by this issue so either we create an `Images` class or we have a class per type of images.

/cc @cescoffier assigning to you so that we discuss it when you're back.

**Comment by cescoffier** [comment]
I agree we should centralize the image names and versions.
