### ISSUE TITLE
Executing tests in Quarkus 3.13+ are extremely slow

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#42390]
### Describe the bug

Since the introduction of the annotation `@WithTestResource(value = OidcWiremockTestResource.class)`, tests are executed extremely slowly because the application is started for each test class. If `@WithTestResource(value = OidcWiremockTestResource.class, restrictToAnnotatedClass = false)` is used, the tests are fast again.

Note: The constant restarts then also show the classloader problems which then lead to the OOMs (https://github.com/quarkusio/quarkus/issues/42303, https://github.com/quarkusio/quarkus/issues/42355).

### How to Reproduce?

1. Download [slow-tests-reproducer.zip](https://github.com/user-attachments/files/16539937/slow-tests-reproducer.zip)
2. `./gradlew clean build` -> Extremly slow
3. Replace all `@WithTestResource(value = OidcWiremockTestResource.class)` with `@WithTestResource(value = OidcWiremockTestResource.class, restrictToAnnotatedClass = false)`
4. `./gradlew clean build` -> Fast again

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus 3.13.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

**Comment by mschorsch** [comment]
@gsmet @geoand might be interested

**Comment by geoand** [comment]
The slowness is also likely being exarcebated by the fact that under yet to be determined cases, we are leaking ClassLoaders

**Comment by geoand** [comment]
@edeandrea I wonder if we need to make it clearer in the docs that `@WithTestResource` (by default) causes a restart which can slow down the testsuite (regardless of the ClassLoader leaks which we can hopefully fix)

**Comment by mschorsch** [comment]
> @edeandrea I wonder if we need to make it clearer in the docs that `@WithTestResource` (by default) causes a restart which can slow down the testsuite (regardless of the ClassLoader leaks which we can hopefully fix)

I read this to mean that this issue is not a bug but the expected (default) behavior of annotation `@WithTestResource`. Is that correct?

**Comment by geoand** [comment]
Yes, absolutely, but it seems like we need to make that clearer in the docs :)

**Comment by gsmet** [comment]
I think we need more than something in the Javadoc, we also need to document it very clearly in the doc.

And we should also make it clear in the migration guide.

We already had two reports of this and we are in the middle of the summer.

**Comment by geoand** [comment]
Sure yeah, all that makes sense. 

@edeandrea are you up for it?

**Comment by gsmet** [comment]
BTW, @mschorsch you confirm that you didn't use `quarkus update`? Because I actually made a recipe that should keep the original intent of `QuarkusTestResource` when upgrading.

**Comment by mschorsch** [comment]
> BTW, @mschorsch you confirm that you didn't use `quarkus update`? Because I actually made a recipe that should keep the original intent of `QuarkusTestResource` when upgrading.

Yes we do not use `quarkus update`, it doesn't work for us, but I haven't investigated this further.

**Comment by gsmet** [comment]
@mschorsch another small question to make sure I fully understand this: you had `@QuarkusTestResource` set up without restriction on one class and you changed it to `@WithTestResource` with restriction on many classes? And that's when things started to get slow, right?

**Comment by mschorsch** [comment]
> @mschorsch another small question to make sure I fully understand this: you had `@QuarkusTestResource` set up without restriction on one class and you changed it to `@WithTestResource` with restriction on many classes? And that's when things started to get slow, right?

Yes, we used `QuarkusTestResource` and then simply replaced the annotation with `WithTestResource` but since the behavior of the annotation changed implicitly (`restrictToAnnotatedClass` was implicitly changed from `false` to `true`) we got several problems:
- OOMs
- slow tests

**Comment by edeandrea** [comment]
> Edit: To make it fully clear, we changed in all our tests `@QuarkusTestResource(OidcWiremockTestResource::class)` to `@WithTestResource(OidcWiremockTestResource::class)`.

If you want to be 100% backwards compatible with `@QuarkusTestResource(OidcWiremockTestResource::class)`, use `@WithTestResource(value = OidcWIremockTestResource::class, restrictToAnnotatedClass = false)`. That will give you what you had before.

**Comment by gsmet** [comment]
Also you need only one annotation if you're doing this ^

**Comment by mschorsch** [comment]
My question has been answered and the behavior of `WithTestResource` has been documented in https://github.com/quarkusio/quarkus/issues/42406.

**Comment by HerrDerb** [comment]
For the sake of completeness, what was the intention to change this behaviour?

**Comment by geoand** [comment]
The old default behavior was super confusing to anyone that was not aware of it. The fact that an annotation added to a specific test affected the entire testsuite is very counter intuitive and was recognized very early on as a mistake that would have to be rectified at some point
