### ISSUE TITLE
Create a backstage extension

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#42398]
### Description

I would like to propose a Quarkus plugin for Backstage.

The main role of the plugin is to generate the Backstage entities for the current project. While Backstage does provide the ability to generate a very basic `Compoent` for registering a Quarkus application, the user is expected to maintain by hand and align it the application as it evolves. However, for Backstage to produce value, it's important to keep these metadata up to date, but more importantly to document and register things like provided or consumed APIs.

A Quarkus extension can use the build items from extension and register things like:
- Rest APIs
- Rest Clients
- gRPC APIs
- QraphQL 
and more

Additionally, when an application is meant to be registered to backstage it is important that things like helm chars, generated manifests etc, are added under version control. The Backstage extension could coordinate with plugins like:
- kubernetes
- helm
- argocd (wip)
- tekton (wip)

In order to get the generated resources where they need to be in order to be correctly registered to backstage.

### Additional features
The extension could possibly host additional features like:
- client
- cli
- backstage template generator.

An first draft of the extension that implements the core features can be found at: https://github.com/iocanel/quarkus-backstage

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-backstage

### Short description

A backstage extension for Quarkus

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-backstage/dev/

### Repository Topics

- quarkus-extension
- 
...

### Team Members

- iocanel
- aureamunoz 
- cmoulliard

**Comment by geoand** [comment]
cc @gastaldi
