### ISSUE TITLE
Panache Regression in 3.13: `singleResult` throws wrong `NonUniqueResultException`

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#42416]
### Describe the bug

In Quarkus 3.13.0 and 3.13.1, calling [`singleResult()`](https://javadoc.io/doc/io.quarkus/quarkus-hibernate-orm-panache/latest/io/quarkus/hibernate/orm/panache/PanacheQuery.html#singleResult()) or [`singleResultOptional()`](https://javadoc.io/doc/io.quarkus/quarkus-hibernate-orm-panache/latest/io/quarkus/hibernate/orm/panache/PanacheQuery.html#singleResultOptional()) now throws a `org.hibernate.NonUniqueResultException` if there are 2 or more results. It used to throw a `jakarta.persistence.NonUniqueResultException` in Quarkus 3.12 and earlier, and the documentation for 3.13 also still says it throws a `jakarta.persistence.NonUniqueResultException`.

I haven't checked whether other exceptions, e.g. `jakarta.persistence.NoResultException` are also affected.

### Expected behavior

`singleResult()` throws `jakarta.persistence.NonUniqueResultException`, like in Quarkus 3.12.x and before

### Actual behavior

`singleResult()` throws `org.hibernate.NonUniqueResultException`

**Comment by gbourant** [comment]
Maybe this is caused because Panache no longer depends on EntityManager? https://github.com/quarkusio/quarkus/pull/41518

**Comment by gsmet** [comment]
Yeah I suspect that's the culprit. I'm not sure if this was foreseen and accepted or not.

It's definitely a breaking change though.

@yrodiere is on PTO and I think we really need to talk to him about this as it ends up being a rather radical change from a user POV.

**Comment by gsmet** [comment]
My current recommendation is to not update your app. I will discuss this with @yrodiere and @marko-bekhta on Monday.

**Comment by gsmet** [comment]
I will announce it on Monday morning but I released 3.13.2 today with the fix.
