### ISSUE TITLE
100% CPU in epoll_wait

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#4241]
**Describe the bug**
In some environments, using native image, all threads reading I/O can spend 100% CPU time polling `epoll_wait(..., timeout=0)`. Turns out this is an effect of `static final io.netty.util.concurrent.ScheduledFutureTask.START_TIME` being set to system-dependent `System.nanoTime()` during compilation and the NioEventLoop behaving in an unexpected way.

Note that this behaviour cannot be reproduced when compiling and running on the same machine, due to the nature of `System.nanoTime()` base value.

**Comment by Sanne** [comment]
thanks @rvansa ! Pinging @stuartwdouglas as I believe he was looking as well into moving such initializations to runtime.

**Comment by rvansa** [comment]
Could someone on quarkus-dev ml also ping this user who seems to suffer from the same problem?
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/jjwCQJMV434/mlujuFClAAAJ
