### ISSUE TITLE
Integration test fails to start mongo with Liquibase

### ISSUE THREAD

**Issue by vkn** [quarkusio/quarkus#42453]
### Describe the bug

Mongodb dev services don't start if `quarkus.liquibase-mongodb.migrate-at-start=true` when running `@QuarkusIntegrationTest`

### Expected behavior

devservices must start mongo container

### Actual behavior

Mongodb is not starting

### How to Reproduce?

[mongodb-quickstart.tar.gz](https://github.com/user-attachments/files/16564614/mongodb-quickstart.tar.gz)
Unpack and run `./mvnw -Dquarkus.container-image.build=true verify`

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS

### Quarkus version or git rev

3.13.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8

**Comment by gsmet** [comment]
Actually, the container is started but the MongoDB client cannot connect to the container because it's using the wrong port.

I created a fix here: https://github.com/quarkusio/quarkus/pull/42472 .
