### ISSUE TITLE
Explore the use of StackWalker in REST Client

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#42508]
### Description

Currently in the REST Client when `quarkus.rest-client.capture-stacktrace` is set to true  (which is the default), we capture the entire stacktrace of the Thread in order to enhance the debugging experience when something goes wrong.

@johnaohara has found however that in some cases up to 20% of the users application code callstack in capturing a stack trace, which is a waste of cpu cycles, but also forces the JVM to safepoint the mutating threads during every call to the api

**Comment by geoand** [comment]
Gotcha, thanks.

**Comment by geoand** [comment]
We can also look into caching the part of the stacktrace we care about

**Comment by geoand** [comment]
@johnaohara would you be able to test https://github.com/quarkusio/quarkus/pull/42544?

The reason I ask is that I wasn't able to reproduce the initial results so I don't have a baseline

**Comment by johnaohara** [comment]
Hi @geoand I did not have chance last week.  I public holiday today,  I can verify the patch tomorrow

**Comment by geoand** [comment]
Thanks!

**Comment by geoand** [comment]
@johnaohara when you get a chance to look at https://github.com/quarkusio/quarkus/pull/42544, I'd be happy to hear about the results :)

**Comment by johnaohara** [comment]
@geoand  checking now

**Comment by geoand** [comment]
🙏🏽

**Comment by johnaohara** [comment]
@geoand quick update on the testing so far.  I tried with your PR branch, but saw some extra call stacks that I was not expecting, so backported to 3.12.2 (this was the version that produced the above baseline), and I am still seeing the unexpected stack, see;

![image](https://github.com/user-attachments/assets/1bd3f256-f3ac-4b79-99e9-b793c3c197de)


I am looking at the test now to see why these stacks are showing in the flamegraph

**Comment by gsmet** [comment]
@johnaohara you talking about the ones from `ExtLogRecord`?

If so, I reported it here: https://github.com/quarkusio/quarkus/issues/42858 and it should be fixed in current `main` with the update of SmallRye Common to 2.6.0. The PR might need a rebase.

**Comment by johnaohara** [comment]
@gsmet yeah, that is what I was talking about.  But I cherry-picked onto 3.12.2, so expected it to disappear. 

I just realized what I have done wrong, I will try running the test again.

**Comment by gsmet** [comment]
This particular issue is in all 3.13.x and in 3.14.1. It should be fixed in 3.14.2.

**Comment by johnaohara** [comment]
@geoand sorry about the noise yesterday.
testing with #42544 

The cpu time for processing the stack frames (in my particular test) has dropped approx 10% with the new implementation (691 cpu samples -> 623 cpu samples)

Application code stack went from 21.2% of cpu time processing stack to 19.2% with the change.  Although it is improved, there is still a considerable overhead on each invocation

Before:

![Screenshot from 2024-09-04 09-11-07](https://github.com/user-attachments/assets/bdced061-ae09-47c4-9c8c-2221bf5554ec)


After:

![Screenshot from 2024-09-04 09-11-10](https://github.com/user-attachments/assets/6e375ec9-c772-4bff-9d1e-788d080efd48)

**Comment by geoand** [comment]
Thanks a lot @johnaohara! 

> Application code stack went from 21.2% of cpu time processing stack to 19.2% with the change. Although it is improved, there is still a considerable overhead on each invocation

Indeed.... 

I wonder if we should change the default to not capture the stack... @cescoffier @gsmet WDYT

**Comment by johnaohara** [comment]
obvious setting `quarkus.rest-client.capture-stacktrace=false` removes all the calls

idk if the stack traces were intended to be used in a prod deployment or just for development

**Comment by geoand** [comment]
They were intended for both

**Comment by gsmet** [comment]
How confusing is the stack trace without it?

I wonder if we should have the following behavior:
- Enabled in dev and test mode / disabled in prod mode by default
- Make sure you have at least the name of the REST Client around even in prod mode - can we at least push this info?

Not sure if it's feasible but that might help?

**Comment by geoand** [comment]
> How confusing is the stack trace without it?

It's almost meaningless...

**Comment by gsmet** [comment]
Yeah better than nothing and better than slowing down the whole app.

Now, that's not the only place where our stack traces are border line useless unfortunately :/

**Comment by geoand** [comment]
True, so if @cescoffier is also on board, I can make the change

**Comment by geoand** [comment]
Actually, we already print the method that causes the failure, so  nothing needs to be done on that fronty

**Comment by cescoffier** [comment]
What's the gist of the work that need to be done?

**Comment by geoand** [comment]
We would only change the default or the property that controls whether or not we capture the real stack.

**Comment by cescoffier** [comment]
Ah ok, makes sense.

**Comment by geoand** [comment]
I'll do it tomorrow

**Comment by geoand** [comment]
#43037 changes the default
