### ISSUE TITLE
Quarkus is using Micrometer version that is reaching EOL

### ISSUE THREAD

**Issue by vmuzikar** [quarkusio/quarkus#42517]
### Describe the bug

Quarkus [still uses](https://github.com/quarkusio/quarkus/blob/baf77db720ab5794a1b152c87a01df3c291f864e/bom/application/pom.xml#L38) Micrometer 1.12.x while 1.13.x is already available. Branch 1.12.x [will reach end of support in November 2024](https://micrometer.io/support/).

### Expected behavior

Quarkus uses supported Micrometer version.

### Additional information

Originally reported by @ahrycej in https://github.com/keycloak/keycloak/issues/31896.

**Comment by brunobat** [comment]
Changes will be implemented soon. As this is not a real bug, will close.

**Comment by ahrycej** [comment]
OK can you say what is the target for this one, as delays are reaching production systems. Having EOL components in production impose major security risks.
I think pointing out to the planned quarkus version is just fine, we expect keycloak project to deliver it before Novemver so we can integrate it in our product.
@brunobat
