### ISSUE TITLE
Update docs to reflect Panache annotation processor removed for Hibernate ORM/Hibernate Reactive/MongoDB

### ISSUE THREAD

**Issue by rolfedh** [quarkusio/quarkus#42531]
### Description

The `docs/src/main/asciidoc/mongodb-panache.adoc` file instructs users to provide use the `quarkus-panache-common` annotation processor, which is no longer required as of 3.9. 

See [Panache annotation processor removed for Hibernate ORM/Hibernate Reactive/MongoDB](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#panache-annotation-processor-removed-for-hibernate-ormhibernate-reactivemongodb-gear-white_check_mark).

### Implementation ideas

Remove related content.

**Comment by loicmathieu** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/42532
