### ISSUE TITLE
Use of both configs of quarkus.keycloak keycloak.json and application.properties.

### ISSUE THREAD

**Issue by gintsgints** [quarkusio/quarkus#4253]
When I have application which have keycloak.config in json file for config, application.properties file seems to be ignored.

How to repeat:
* Create keycloak.config with full configuration except auth-server-url.
* add variable quarkus.keycloak.auth-server-url to application.properties with correct url.

What happens:
application complains about auth-server-url not provided.

What I expect:
application reads keycloak.json file and overrides it with settings from application.properties file.

**Comment by gintsgints** [comment]
For now I use workaround to change keycloak.config within external environment variable:

```"auth-server-url": "http://${env.KEYCLOAK_SERVER}/auth"```

**Comment by geoand** [comment]
@sberyozkin this one is for you perhaps? :)

**Comment by sberyozkin** [comment]
@geoand Hi, yeah, I was wondering what to reply, because right now, on master, the oidc adapter code is being changed :-)

**Comment by gintsgints** [comment]
@sberyozkin I see new oidc code available. Can you use both files with it now?

**Comment by gsmet** [comment]
I think `keycloak.json` is probably not supported anymore. @sberyozkin @pedroigor could you check if this issue still makes sense with the new architecture?

**Comment by gintsgints** [comment]
I did need keycloak.json to allow some paths go without checking. If it is possible via annotattions now, then it is ok.

**Comment by sberyozkin** [comment]
@gintsgints Sorry, there was no oidc label so I've missed this issue recently. I agree we should close this issue as `keycloak.json` is not supported. @gintsgints Perhaps you should watch  #6807 if you need the anonymous access with `quarkus-keycloak-authorization`, otherwise HTTP security policy configuration can be used to allow an anonymous access for the selected paths. Thanks

**Comment by gintsgints** [comment]
Yes. This is solved now.
