### ISSUE TITLE
quarkus update sometimes fails to correctly update @QuarkusTestResource

### ISSUE THREAD

**Issue by Ortofta** [quarkusio/quarkus#42568]
### Describe the bug

In some cases quarkus update seems to be unable to correctly migrate @QuarkusTestResource to the new @WithTestResource annotation.

In my case, the old annotation looked like this:
`@QuarkusTestResource(OidcWiremockTestResource.class)`
the automatically converted code, which does not compile, looks like this:
`@WithTestResource(restrictToAnnotatedClass = false, OidcWiremockTestResource.class)`

I assume the correct code would be:
`@WithTestResource(restrictToAnnotatedClass = false, value = OidcWiremockTestResource.class)`

### Output of `uname -a` or `ver`

Windows 11

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.13.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by gsmet** [comment]
I can see this is an OpenRewrite issue that has been fixed lately: https://github.com/openrewrite/rewrite/commit/14aef405998f4a07a034c7b87deb3d359b3bb0ae .

Let me try to update to the latest version.

**Comment by gsmet** [comment]
I worked on the update to latest OpenRewrite here: https://github.com/quarkusio/quarkus-updates/pull/201 and released a new 1.0.20 of Quarkus Updates.

It has hit Maven Central now, could you retry an update and see if things are better?

The new version should be automatically picked up (but not sure if Maven refreshes things daily or more often), in the logs you should see that OpenRewrite Maven Plugin 5.39.0 is used.

Let me know how it goes for you.

**Comment by Ortofta** [comment]
I tried it now, but still got the old Maven plugin (`rewrite-maven-plugin:5.36.0:run`). 
I'll try again tomorrow - maybe our Nexus proxy and the other Maven magic has had a chance to update.

**Comment by gsmet** [comment]
Yeah my recollection is that Maven updates the metadata daily and that’s what we use to resolve the latest.

**Comment by Ortofta** [comment]
I tested it again this morning - and now I got the new OpenRewrite plugin - ` Resolved io.quarkus:quarkus-update-recipes:LATEST with 1 recipe(s) to update from 3.12.3 to 3.13.2 (initially made for OpenRewrite MAVEN plugin version: 5.39.0)`.

And now the converted code is correct and compiles.

**Comment by gsmet** [comment]
Perfect, thanks for the confirmation!
