### ISSUE TITLE
Deprecate `quarkus.datasource.jdbc.tracing`

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#42563]
### Description

According to https://quarkus.io/guides/datasource#datasource-tracing, the `quarkus.datasource.jdbc.tracing` property is not even mentioned in the docs (except in the config table) and requires the `io.opentracing.contrib.jdbc.TracingDriver` driver to be present in the classpath (I figured that out by reading the code). 
 

### Implementation ideas

Deprecate the `quarkus.datasource.jdbc.tracing` configuration and remove in a future version

**Comment by brunobat** [comment]
yes, we need to remove that prop.

**Comment by brunobat** [comment]
CC @danielsoro

**Comment by danielsoro** [comment]
If I understood well, follow the PR: https://github.com/quarkusio/quarkus/pull/43416

cc/ @brunobat @gastaldi

**Comment by brunobat** [comment]
Clarification, @danielsoro.
`quarkus.datasource.jdbc.tracing` is the old property to configure tracing. Now we use `quarkus.datasource.jdbc.telemetry` and we need to remove the old code.

**Comment by danielsoro** [comment]
> Clarification, @danielsoro. `quarkus.datasource.jdbc.tracing` is the old property to configure tracing. Now we use `quarkus.datasource.jdbc.telemetry` and we need to remove the old code.

Ok, so I'll remove it. ;)
