### ISSUE TITLE
CLI in version 3.8.5 does not properly update

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus#42567]
### Describe the bug

Using quarkus 3.8.5 I cannot update app from 3.2.12.Final to 3.8.5. Update process reports no issues, just does not do any changes. 
It can be reproduced by creating app using CLI and trying to update it. Attaching [update.log](https://github.com/user-attachments/files/16622316/update.log) from that.

Switching quarkus CLI to 3.12.3 solves the problem. Using that version of CLI it works no problem.

### Expected behavior

App will be update to 3.8.5. Especially quarkus version in pom.xml

### Actual behavior

No changes were made.

### How to Reproduce?

Use quarkus CLI 3.8.5

1. `quarkus create app app --stream=3.2`
2. `cd app`
3. `quarkus update --stream=3.8`

### Output of `java -version`

17

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

quarkus CLI

**Comment by gsmet** [comment]
The key in your log is:
```
[INFO] --- rewrite:5.36.0:run (default-cli) @ upstreamApp ---
[INFO] Using active recipe(s) []
[INFO] Using active styles(s) []
```
It doesn't apply anything.

Now we need to figure out why :).

To clarify, why doesn't work is:
- use Quarkus CLI 3.8.5
- update to 3.8.5

What does work:
- use Quarkus CLI 3.12.3
- update to 3.8.5

Can you confirm?

**Comment by mocenas** [comment]
> To clarify, what doesn't work is:
> 
>     * use Quarkus CLI 3.8.5
> 
>     * update to 3.8.5
> 
> 
> What does work:
> 
>     * use Quarkus CLI 3.12.3
> 
>     * update to 3.8.5
> 
> 
> Can you confirm?

Yes that is true.

**Comment by gsmet** [comment]
I wonder if it could be related to this thing I fixed for 3.12: https://github.com/quarkusio/quarkus/commit/634a8513b6d769f593b7ed93dfc4191cbfa0b576

**Comment by gsmet** [comment]
@mocenas cool, thanks for confirming, I will backport this to 3.8.6!

**Comment by gsmet** [comment]
I pushed this commit to https://github.com/quarkusio/quarkus/pull/42547 so we should be all good for 3.8.6.

Thanks for the report!
