### ISSUE TITLE
be explicit/use examples in websocket.next docs when it comes to subscribe call for action

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#42566]
### Description

Trying to use websockets.next primiarly the client but i see similar challenges with server side.

reading https://quarkus.io/guides/websockets-next-reference there are a mix of places where it says things like:

"The method must subscribe to the `Multi` to receive these items (or return a Multi)."

and 

"Sends a text message to the client. It returns a `Uni`. It's non-blocking, but you must subscribe to it."

..and no example so is this saying that i.e. it must be `.sendText(msg).subscribe()` or must it be `.sendText(msg).subscribe().with(()->{});` ? we should provide examples in these places to reduce ambiguity/errors.

### Implementation ideas

I would make a PR for these but I'm not actually sure what the required minimal samples are ;)

**Comment by cescoffier** [comment]
We may need a warning containing the code showing how to subscribe but making it clear that the framework is usually subscribing. Explaining when it does subscribe and when it does not is tricky—it depends on the used extensions.

**Comment by cescoffier** [comment]
Assigning it to me, I will update the documentation.
