### ISSUE TITLE
Custom Smallrye ConfigSourceInterceptor not loading class using Gradle

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#42584]
### Describe the bug

When adding a custom ConfigSourceInterceptor implementation in `src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceInterceptor`:

```
acme.CustomConfigInterceptor
```

Where `CustomConfigInterceptor.java` is:

```
package acme;

import io.smallrye.config.ConfigSourceInterceptor;
import io.smallrye.config.ConfigSourceInterceptorContext;
import io.smallrye.config.ConfigValue;
import io.smallrye.config.Priorities;
import jakarta.annotation.Priority;

@Priority(Priorities.APPLICATION)
public class CustomConfigInterceptor implements ConfigSourceInterceptor {
    @Override
    public ConfigValue getValue(ConfigSourceInterceptorContext context, String name) {
        if ("property".equals(name)) {
            return new ConfigValue.ConfigValueBuilder().withValue("pong").build();
        }
        return context.proceed(name);
    }
}
```

This works in Maven, but not in Gradle, where it fails with:

```
quarkus-examples/smallrye-config-gradle$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
io.smallrye.config.ConfigSourceInterceptor: Provider acme.CustomConfigInterceptor not found

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 723ms
```

### How to Reproduce?

I created a very basic example in Maven and in Gradle in order to prove that in Maven works, but not in Gradle. 
1.- git clone `https://github.com/Sgitario/quarkus-examples`
2.- go to the Maven example: `cd smallrye-config`
3.- the "property" is properly populated from CustomConfigInterceptor. Running the test will validate this: `mvn clean install` 
4.- then, go to the Gradle example: `cd smallrye-config-gradle`
5.- When building `./gradlew build`, then it fails with the above error.

### Output of `java -version`

17

### Quarkus version or git rev

3.13.2

### Additional information

This has been working so far prior to the Quarkus version 3.13.2 (the last version we used is `3.9.2`).
I tried to find the exact changes that made this started failing and I think it was: https://github.com/quarkusio/quarkus/commit/78045ea67413518f7c77271d08a70d03d1fffbbd

**Comment by iasonp87** [comment]
We are facing the same issue. With 3.12.3 it is working fine.
