### ISSUE TITLE
Swagger UI Config for Implicit Auth Broken in Native Build

### ISSUE THREAD

**Issue by davetrux** [quarkusio/quarkus#42594]
### Describe the bug

We are using Azure AD to authenticate the API. We are using the Oauth2 implicit flow.

I'd like to allow users to login via the Swagger UI to authenticate to test APIs. When I run the app as a jar, it works as expected. The native build however does not load `quarkus.smallrye-openapi.oauth2-implicit-authorization-url` from the `application.properties` file. That value is missing in the Swagger UI and missing in the results from the Swagger UI calling the `/q/openapi` endpoint.

### Expected behavior

The window pops up, accepts the Client ID and starts an authentication flow in the browser. The user logs in and is redirected back to the Swagger UI. Subsequent API calls in the UI attach the bearer token correctly.

<img width="671" alt="java" src="https://github.com/user-attachments/assets/1ea234af-e73c-4a66-9011-12f1c0b1d073">

In the endpoint call to `/q/openapi` I expect to find the URL configured at `quarkus.smallrye-openapi.oauth2-implicit-authorization-url` in `application.properties`:

```
"components" : {
    "securitySchemes" : {
      "Azure AD" : {
        "type" : "oauth2",
        "description" : "Authentication",
        "flows" : {
          "implicit" : {
            "authorizationUrl" : "https://login.microsoftonline.com/<tenantid>f/oauth2/v2.0/authorize"
          }
        }
      }
    }
```

### Actual behavior

The window pops up. and the authorization URL is blank on the popup. Entering the Client ID and clicking the button causes a JavaScript error in the browser:

`TypeError: Cannot read properties of undefined (reading 'indexOf')`

No redirects happen and the user cannot log in.

<img width="670" alt="native" src="https://github.com/user-attachments/assets/06479644-08f4-4012-9ac2-b14368f00c75">

The call to  the`/q/openapi` endpoint are missing the value for the URL in the JSON returned:

```
"components" : {
    "securitySchemes" : {
      "Azure AD" : {
        "type" : "oauth2",
        "description" : "Authentication",
        "flows" : {
          "implicit" : { }
        }
      }
    }
  }
```

### How to Reproduce?

I made a [repo with the minimum configuration](https://github.com/davetrux/quarkus-issue) that caused the problem, but to run it requires an app registration in Azure.

1. I created a simple Quarkus app using the [web interface](https://code.quarkus.io/). I included REST, OpenID Connect, and SmallRye with Gradle compiling against Java 17.
2. Added `@Authenticated`  to the `/hello` endpoint
3. Added the following in `application.properties`:
```
quarkus.swagger-ui.title=Demo API
quarkus.smallrye-openapi.info-title=Issue Demo API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API for demonstrating a config problem
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.operations-sorter=alpha

quarkus.oidc.auth-server-url=https://sts.windows.net//${TENANT_ID}
quarkus.smallrye-openapi.security-scheme=oauth2-implicit
quarkus.smallrye-openapi.security-scheme-name=Azure AD
quarkus.swagger-ui.oauth-scopes=openid
quarkus.smallrye-openapi.oauth2-implicit-authorization-url=https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/authorize
quarkus.oidc.token.customizer-name=azure-access-token-customizer
```
4. Build the native app: `./gradlew clean build -x test -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false`
5. Run the native app: `TENANT_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ./build/implicit-issue-1.0.0-SNAPSHOT-runner` where TENANT_ID is a UUID obtained from Azure.
6. Visit the Swagger UI page: [http://localhost:8080/q/swagger-ui/](http://localhost:8080/q/swagger-ui/)
7. Click the "Authorize" button

### Output of `uname -a` or `ver`

Darwin trux.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk 22.0.2 2024-07-16 OpenJDK Runtime Environment GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01) OpenJDK 64-Bit Server VM GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01, mixed mode, sharing)

### Quarkus version or git rev

3.13.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.8 ------------------------------------------------------------  Build time:   2024-05-31 21:46:56 UTC Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082  Kotlin:       1.9.22 Groovy:       3.0.21 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          22.0.2 (GraalVM Community 22.0.2+9-jvmci-b01) OS:           Mac OS X 14.6.1 aarch64

### Additional information

We discovered the problem running in a container in K8s, but I was able to reproduce it locally with a simpler app. The container version is compiled for amd64 so the issue does not seem to be platform-specific.

**Comment by galderz** [comment]
Don't have Azure so can't try the reproducer, but my gut feeling would be that some reflection configuration is missing in the swagger/smallrye/openapi layer. Experts in these libraries would really know if reflection is used at all in this case.

**Comment by phillip-kruger** [comment]
Hi @davetrux . Thanks for creating the reproducer, I did not manage to run the re-creator (probably my gradle, I don't use that often). However I recreated the reproducer (see attached) and I can not manage to recreate the issue. Can you check if my re-creator works for you ?
[code-with-quarkus.zip](https://github.com/user-attachments/files/16683913/code-with-quarkus.zip)

**Comment by davetrux** [comment]
Yours worked. The only real difference between the two is that I'm using an environment variable to inject the TENANT_ID, but you did not. And that seems to be the issue. Even if I set the TENANT_ID as an environment variable in my shell, the native runner fails as I described. If I build the uber-jar and run that the environment variable in my shell is getting picked up and the Swagger UI works as expected.

**Comment by phillip-kruger** [comment]
maybe @radcortez can comment here ?

**Comment by phillip-kruger** [comment]
It's probably because [quarkus.smallrye-openapi.oauth2-implicit-authorization-url](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus-smallrye-openapi-oauth2-implicit-authorization-url) is a built time config. You best workaround for now would be to create a filter and set the value that way.  see https://quarkus.io/guides/openapi-swaggerui#runtime-filters

**Comment by radcortez** [comment]
> It's probably because [quarkus.smallrye-openapi.oauth2-implicit-authorization-url](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus-smallrye-openapi-oauth2-implicit-authorization-url) is a built time config. 

Correct.

**Comment by davetrux** [comment]
Well, that explains it. Thank you.

Where can I find out which configs are build-time so we can avoid this going forward?

**Comment by radcortez** [comment]
In the configuration list, if the configuration name has a lock icon, it means it is build time fixed only.

**Comment by davetrux** [comment]
Thank you!
