### ISSUE TITLE
An extension providing Narayana Software Transactional Memory

### ISSUE THREAD

**Issue by mmusgrov** [quarkusio/quarkus#4260]
The Narayana open source project [provides a Software Transactional Memory implementation](https://narayana.io/docs/project/index.html#d0e16066). To simplify the use of STM in quarkus based applications an extension would be useful. In particular our STM implementation makes use of reflection and dynamic proxies which makes native mode difficult for developers and it would be nice if these can be handled by an extension rather than directly by the application developer.

There is [more information about the proposal in my fork](https://github.com/mmusgrov/quarkus/blob/issue4260/docs/src/main/asciidoc/stm-guide.adoc)

And I have prepared a [quickstart](https://github.com/quarkusio/quarkus-quickstarts/compare/development...mmusgrov:development?expand=1
) to demonstrate usage of the extension.

**Comment by mmusgrov** [comment]
PR merged

**Comment by gsmet** [comment]
@mmusgrov could you send me an email with a description of the use case of this extension? I want to add it to the announcement but I have no idea what it brings to the plate.
