### ISSUE TITLE
Convinient way to access build metadata at runtime

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#42602]
### Description

Today quarkus capture the application version and makes it available at runtime via `quarkus.application.version`

It would be pretty handy to make metadata about the build available in the application code via config properties (for example the build id provided by the CI, the commit sha or the build date).

Today, the only solution I can think of to achieve this is to use a maven plugin to write this data in a file that is included in the jar as a resources.

Context: 

We are building an extension for temporal https://github.com/quarkiverse/quarkus-temporal
Temporal enable durable execution, In order for a workflow that started with a given version to complete with the same version, there is a feature called worker versioning relying on the build id:

https://docs.temporal.io/develop/java/versioning#worker-versioning

I am creating this issue to explore whether this process could be standardized.

**Comment by rmanibus** [comment]
cc @melloware

**Comment by melloware** [comment]
well three is the INFO endpoint and DevUI you can hook into.

```xml
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-info</artifactId>
		</dependency>
```

```js
{
  "git" : {
    "branch" : "main",
    "commit" : {
      "id" : "721764af95b98c74d17d43b111ef57f067ee7726",
      "time" : "2024-08-06T09:44:35-04:00"
    }
  },
  "java" : {
    "version" : "17.0.11"
  },
  "os" : {
    "name" : "Windows 11",
    "version" : "10.0",
    "arch" : "amd64"
  },
  "build" : {
    "group" : "com.melloware",
    "artifact" : "quarkus-primereact",
    "version" : "10.8.2",
    "time" : "2024-08-16T14:28:22.464974-04:00",
    "quarkusVersion" : "3.13.1",
    "enabled" : "true"
  }
}
```

Is that what you are looking for?

![image](https://github.com/user-attachments/assets/995240e7-7381-4ffe-bf00-18987a34b9a0)

**Comment by rmanibus** [comment]
Is this accessible at runtime or only in dev mode ?

**Comment by melloware** [comment]
`runtime` and you can add your own data to it as well and its exposed as a Rest Endpoint.

**Comment by gsmet** [comment]
Not sure if it’s documented but you can also inject the info as a bean since https://github.com/quarkusio/quarkus/pull/33226

**Comment by rmanibus** [comment]
I tried to add quarkus-info to the runtime module and all tests fails because it cannot find the quarkus.http.host property.

I think the info present in quarkus info is exactly what I need, but it worries me a bit to pull all the http dependencies for this (in theory this app does not require any web server) !

**Comment by rmanibus** [comment]
see: https://github.com/quarkiverse/quarkus-temporal/pull/55/files

**Comment by rmanibus** [comment]
nevermind, it seems vertx was already pulled in before !

**Comment by melloware** [comment]
Safe to close this ticket @rmanibus ?

**Comment by rmanibus** [comment]
Yeah I think we have what we need for now, Thanks a lot !
