### ISSUE TITLE
MQTT dev services always start if another reactive messaging connector is present

### ISSUE THREAD

**Issue by kdurnoga** [quarkusio/quarkus#42612]
### Describe the bug

If a Quarkus app uses at least 2 distinct reactive messaging connectors, one of the `smallrye-mqtt` type and another one of a different type, then the dev services for MQTT connector spawn a broker container, regardless of whether MQTT connector is configured to use an external broker or not.

The relevant piece of code that determines if MQTT dev services are needed is as follows:
https://github.com/quarkusio/quarkus/blob/a41f7de85bef9a72d4a09c830a2f6209047d6d0c/extensions/smallrye-reactive-messaging-mqtt/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/mqtt/deployment/MqttDevServicesProcessor.java#L208-L215
This is executed for each connector, so if another connector is also present, `isMqtt` is equal to `false`. So is `isConfigured` and we exit this method with the return value `true`, indicating that MQTT dev services are actually needed. The proper logic should be more like:
```java
if (isMqtt && !(hasHost || hasPort)) {
    return true;
}
```

Similarly to #32463, in this case MQTT dev services must be explicitly disabled with
```
quarkus.mqtt.devservices.enabled=false
```

### Expected behavior

MQTT dev services are not spawned.

### Actual behavior

MQTT dev services are spawned even if the connector is configured to connect to an external MQTT broker.

### How to Reproduce?

Have 2 reactive messaging connectors of distinct types, one being `smallrye-mqtt`.

### Quarkus version or git rev

3.13.2

**Comment by cescoffier** [comment]
Great catch, can you open a PR as you found the buggy code?

**Comment by kdurnoga** [comment]
> Great catch, can you open a PR as you found the buggy code?

Please verify if my PR works. I'm a Quarkus newbie so I might happen that I have broken something else accidentally.
