### ISSUE TITLE
Quarkus REST: AsyncInvoker doesn't fire callbacks

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#42610]
### Describe the bug

I'm using Quarkus 3.11.0 with the `quarkus-rest-client-jackson` extension to asynchronously invoke a simple REST service. Using the polling feature seems to work as expected but using the callback one doesn't. The callback doesn't get called.

### Expected behavior

Using statements like:

    ClientBuilder.newClient().target(...).request().async().get(new TimeCallback());

I expect that the `TimeCallback.completed()` method be invoked when the result of the REST endpoint is available.

### Actual behavior

The `TimeCallback.completed()` method isn't invoked.

### How to Reproduce?

    $ git clone https://github.com/nicolasduminil/quarkus-jaxrs-async-with-callback.git
    $ cd quarkus-jaxrs-async-with-callback
    $ mvn package
    $ java -jar target/quarkus-app/quarkus-run.jar
    ...

In another terminal:

    $ cd quarkus-jaxrs-async-with-callback
    $ mvn -DtimeSrvUrl=http://localhost:8080/time failsafe:integration-test

The tests will run successfully despite the statement `assertThat(false).isTrue();` in the `TimeCallback.completed()` method, proving that it doesn't get called. The output of the `System.out.println(...)` statements doesn't appear neither.

### Output of `uname -a` or `ver`

Linux nicolas-XPS-13-9360 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "21.0.4" 2024-07-16 LTS Java(TM) SE Runtime Environment (build 21.0.4+8-LTS-274) Java HotSpot(TM) 64-Bit Server VM (build 21.0.4+8-LTS-274, mixed mode, sharing)

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9) Maven home: /opt/apache-maven-3.9.4 Java version: 21.0.4, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21.0.4-oracle-x64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.8.0-40-generic", arch: "amd64", family: "unix"

### Additional information

None

**Comment by geoand** [comment]
The problem is that when you do:

```
client.target(timeSrvUrl).request().async().get(new TimeCallback());
```

you are not waiting for the `Future` to complete. 
That results in the test finishing and ultimately the client being closed before the callback can be invoked.

Simply changing your code to something like:

```
client.target(timeSrvUrl).request().async().get(new TimeCallback()).get(10_000, TimeUnit.MILLISECONDS);
```

makes things work as expected.

**Comment by geoand** [comment]
I'll take another look tomorrow, but I tried what I mentioned above and it worked as expected

**Comment by geoand** [comment]
I tried your updated version and the `completed` method of the `TimeCallback` is invoked.
