### ISSUE TITLE
@QuarkusComponentTest doesn't initialize injected beans

### ISSUE THREAD

**Issue by dasha-klim** [quarkusio/quarkus#42643]
### Describe the bug

`@QuarkusComponentTest` doesn't allow to inject a list of classes that implement a specific interface using `@Inject` `@All annotations`
Like:
```
    @Inject
    @All
    List<Secondary> secondaries;
```
Each class that implements the interface is annotated with `@ApplicationScoped`
`@Startup` and  has a  `@Postconstruct` method which doesn't get called at all when running a test.

### Expected behavior

Classes are injected 

### Actual behavior

List of classes remains empty.

### How to Reproduce?

Reproducer: https://github.com/dasha-klim/quarkus_test.git

### Output of `java -version`

17.0.11

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

### Additional information

If it is expected behaviour and the @QuarkusComponentTest shouldn't allow this to be done, how it should be done without using @QuarkusTest annotation and starting the whole quarkus application as we have a lot of other verticles and services that we don't need for testing.

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
Yes, it seems that we incorrectly detect the component classes for `@Inject @All List<>`. You can specify additional component classes via `@QuarkusComponentTest#value()`  as a workaround.

**Comment by dasha-klim** [comment]
@mkouba Thank you for your reply!
I tried `@QuarkusComponentTest(value = SecondaryOne.class)` and i tried `@QuarkusComponentTest(value = Secondary.class)` and i still didn't see sysout from postConstruct method. How should i do this? Also if i specify them one by one in value, how do i call their methods from tests? 
Also we have about 30 implementations of the service and its a changing number, it would be complicated to add/remove class in tests when we add/remove a new implementation.
Any chance this will be fixed any time soon?

**Comment by mkouba** [comment]
> I tried @QuarkusComponentTest(value = SecondaryOne.class) and i tried @QuarkusComponentTest(value = Secondary.class) and i still didn't see sysout from postConstruct method. How should i do this?

You should only add implementations, i.e. something like `@QuarkusComponentTest({SecondaryOne.class,SecondaryTwo.class})`. But you're right that in your case it's not enough because ArC considers those beans _unused_ and [removes them](https://quarkus.io/guides/cdi-reference#remove_unused_beans) from the configuration automatically :-(.

Unfortunately, the only workaround I can see is to annotate those beans with `@Unremovable` or simply inject them in the test class.

> Also we have about 30 implementations of the service and its a changing number, it would be complicated to add/remove class in tests when we add/remove a new implementation.

I agree that it's not very convenient (although mentioned in the javadoc of `@QuarkusComponentTest#value()` and in the docs). I'm working on a fix so that `@Inject @All List<X>` and `@Inject Instance<X>` are treated in a similar way as `@Inject X`. But keep in mind that the goal of `QuarkusComponentTest` is to test a specific set of beans. So it's always good to define the set of components under the test explicitly.

**Comment by mkouba** [comment]
Hm, I've just realized that even if we treat `@Inject @All List<X>` as `@Inject X` it would not help in your use case with an interface implemented by several beans. We would be able to exclude the unused beans from removal but we wouldn't be able to register them as additional components. In other words, you would still need to register them with `@QuarkusComponentTest#value()`.

**Comment by dasha-klim** [comment]
@mkouba , thank you for looking into the issue!
I adjusted the code - added `@Unremovable` to the `Secondary ` implementations and `@postconstuct` method now puts these implementations in a map created in `MainService`. I have a `getSecondariesMap()` method in `MainService` that returns this map.
In test class in `@beforeAll` i am trying to get the map using the mentioned method however it seems that Secondary beans are getting initialized and added to map only after i loop through `secondaries` in test class . When after looping i try to get the map from the `MainService` again - the map is filled. You can see this according to logs.
I was under impression that adding `@Unremovable` would initialize the beans right away, even `@beforeAll` in tests. Could let me now if it is expected behaviour? Thank you.

**Comment by dasha-klim** [comment]
@mkouba 
Its not in the project that i linked for reproduction, but in our project  the services (that are like  Secondaries) also use Vertx.
If i try to inject Vertx using `@Inject Vertx vertx` i get `java.lang.IllegalStateException: The injected field io.vertx.core.Vertx TestClassName.vertx expects a real component; but obtained: SYNTHETIC bean`.
If i don't inject Vertx in test class, i get `NullPointerException` from bean `Cannot invoke "io.vertx.core.eventbus.EventBus.request(String, Object, io.vertx.core.Handler)" because the return value of "io.vertx.core.Vertx.eventBus()" is null`
How can i make sure that when using `@QuarkusComponentTest ` the beans specified via `@QuarkusComponentTest#value()` would be able to use Vertx? Can i inject it via TestClass or should it be done some other way? 
Thank you.

**Comment by mkouba** [comment]
> I was under impression that adding `@Unremovable` would initialize the beans right away, even `@beforeAll` in tests. Could let me now if it is expected behaviour? Thank you.

Not really. `@Unremovable` merely prevents the beans from being removed (if considered unused).

Unfortunately, you can't use `@QuarkusComponentTest` + `@BeforeAll` to initialize the tested components. You can however use the `QuarkusComponentTestExtension.builder()` as mentioned in the [basic example](https://quarkus.io/guides/testing-components#basic-example).

**Comment by mkouba** [comment]
> If i try to inject Vertx using @Inject Vertx vertx i get java.lang.IllegalStateException: The injected field io.vertx.core.Vertx TestClassName.vertx expects a real component; but obtained: SYNTHETIC bean.

I assume you're trying to inject `Vertx` in the test? If so then you'll have to (a) provide your own `Vertx` implementation and add it to the set of tested components, or (b) use `@InjectMock` and configure the mock instead.

**Comment by mkouba** [comment]
As explained in https://github.com/quarkusio/quarkus/issues/42643#issuecomment-2309934358 we can't fix this issue completely. The fix in https://github.com/quarkusio/quarkus/pull/42779 is IMO the best thing we can do. Feel free to reopen this issue or open a [new discussion](https://github.com/quarkusio/quarkus/discussions).
