### ISSUE TITLE
@NamedDynamoDbTable applicable to parameters would enable constructor injection

### ISSUE THREAD

**Issue by nicklasweasel** [quarkusio/quarkus#42647]
### Description

Currently it is not possible to have

private final DynamoDbTable<Foo> fooTable;

FooDao(@NamedDynamoDbTable("Foo") fooTable) {
  this.fooTable = fooTable
}

Because @NamedDynamoDbTable is not applicable to method parameters. Would this be feasible?

**Comment by manovotn** [comment]
I am not familiar with the amazon-services extension but from a CDI standpoint, this should be fine. Would you care to send a PR to the [respective quarkiverse repo](https://github.com/quarkiverse/quarkus-amazon-services) along with a test @nicklasweasel?

Cc @scrocquesel

**Comment by nicklasweasel** [comment]
I'll have a look, should be a simple addition of Parameter in the annotation and a test with a field injection and a constructor injection and then a == check to verify the same produced bean is used and the rest is up to ARC

**Comment by manovotn** [comment]
> ... and then a == check to verify the same produced bean/proxy is used and the rest is up to ARC.

With beans, you should verify inner state instead of `==` due to proxies.
But in this case, you can use a test with code from you initial comment, plain constructor injection.

**Comment by scrocquesel** [comment]
I create a dup in the quarkiverse repo. This one could be closed.

**Comment by manovotn** [comment]
Closing in favor of https://github.com/quarkiverse/quarkus-amazon-services/issues/1408
