### ISSUE TITLE
Extensions created with 999-SNAPSHOT cli depend on non-existing plugin

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#42649]
### Describe the bug

I use Quarkus CLI to generate quarkus extension. When I use cli from 999-SNAPSHOT, the pom file contains dependency io/quarkus/quarkus-config-doc-maven-plugin of version 3.12.3, which doesn't exist.

### Expected behavior

Generated apps and extensions should not contain non-existing dependencies

### Actual behavior

```
2024-08-20T09:15:32.0278431Z [WARNING] The POM for io.quarkus:quarkus-config-doc-maven-plugin:jar:3.13.2 is missing, no dependency information available
2024-08-20T09:15:32.0279918Z [ERROR] [ERROR] Some problems were encountered while processing the POMs:
2024-08-20T09:15:32.0284197Z [ERROR] Unresolveable build extension: Plugin io.quarkus:quarkus-config-doc-maven-plugin:3.13.2 or one of its dependencies could not be resolved: io.quarkus:quarkus-config-doc-maven-plugin:jar:3.13.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced @ 
2024-08-20T09:15:32.0287744Z  @ 
```

### How to Reproduce?

1. Use the latest cli:
```
          cat <<EOF > ./quarkus-dev-cli
          #!/bin/bash
          java -jar ~/.m2/repository/io/quarkus/quarkus-cli/999-SNAPSHOT/quarkus-cli-999-SNAPSHOT-runner.jar "\$@"
          EOF
          chmod +x ./quarkus-dev-cli
```
2. Create an extension using cli:
```
./quarkus-dev-cli create extension edge && cd quarkus-edge
```
3. Try to build the extension:
`mvn clean install -Dinsecure.repositories=WARN`

If `quarkus` cli of version 3.13.2 (eg from sdkman) is used in p.2, the build works

### Output of `uname -a` or `ver`

6.10.4-200.fc40.x86_64

### Output of `java -version`

Java version: 21.0.1, vendor: Eclipse Adoptium

### Quarkus version or git rev

b7d6639ec4941ec9473bd37081f51a47d2806962

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information
This is a difference between generated poms (`edge` is 999-SNAPSHOT, `stable` is 3.12.3):

```
$ diff quarkus-edge/pom.xml quarkus-stable/pom.xml 
10,11c10,11
<     <groupId>io.quarkiverse.edge</groupId>
<     <artifactId>quarkus-edge-parent</artifactId>
---
>     <groupId>io.quarkiverse.stable</groupId>
>     <artifactId>quarkus-stable-parent</artifactId>
14c14
<     <name>Quarkus Edge - Parent</name>
---
>     <name>Quarkus Stable - Parent</name>
23,25c23,25
<         <connection>scm:git:git@github.com:quarkiverse/quarkus-edge.git</connection>
<         <developerConnection>scm:git:git@github.com:quarkiverse/quarkus-edge.git</developerConnection>
<         <url>https://github.com/quarkiverse/quarkus-edge</url>
---
>         <connection>scm:git:git@github.com:quarkiverse/quarkus-stable.git</connection>
>         <developerConnection>scm:git:git@github.com:quarkiverse/quarkus-stable.git</developerConnection>
>         <url>https://github.com/quarkiverse/quarkus-stable</url>
62,66d61
<                 </plugin>
<                 <plugin>
<                     <groupId>io.quarkus</groupId>
<                     <artifactId>quarkus-config-doc-maven-plugin</artifactId>
<                     <version>${quarkus.version}</version>

```

**Comment by gsmet** [comment]
This is due to this patch: https://github.com/quarkusio/quarkus/pull/42469 .

Apparently, we still need to condition things on the version... I thought this had been changed.
Will take care of it.

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/42653 should address it.

Thanks again for the very detailed report!
