### ISSUE TITLE
Add OpenTelemetry Tracing instrumentation to the JDK HTTP client.

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#42660]
### Description

This has been requested by several users over the time.

**Comment by geoand** [comment]
Hm...

I am not sure how this could be done in Quarkus itself as the instances of JDK HTTP are not managed by Quarkus, instead users manage their lifecycles as they see fit.

**Comment by brunobat** [comment]
It requires research and possibly some upstream issues.

**Comment by brunobat** [comment]
Won't do.
