### ISSUE TITLE
Support WebSocket sub-protocols setting for Vert.x web server

### ISSUE THREAD

**Issue by cristianonicolai** [quarkusio/quarkus#4267]
**Description**
In order to allow using GraqhQL WebSocket subscription implementation, Quarkus needs to allow setting the Vert.X webserver WebSocket sub-protocols.
See: https://vertx.io/docs/vertx-web-graphql/java/#_apollo_websocketlink

**Implementation ideas**
Add new configuration parameter to application.properties which allows to set the sub-protocols string. Ex: quarkus.http.web-socket-sub-protocols=graphql-ws

**Comment by cescoffier** [comment]
@tsegismont FYI

**Comment by cescoffier** [comment]
@tsegismont if we add a sub-protocol config would that be enough?

**Comment by tsegismont** [comment]
@cescoffier yes that should be enough

**Comment by cescoffier** [comment]
Ok will work on it.

**Comment by cescoffier** [comment]
@stuartwdouglas Actually, how would that work as the WebSocket is managed in quarkus-http?

**Comment by cescoffier** [comment]
Actually, Stuart already commented on the PR:
https://github.com/quarkusio/quarkus/pull/4268#issuecomment-536398930

**Comment by gsmet** [comment]
I think this has been merged here: https://github.com/quarkusio/quarkus/pull/4268 .
