### ISSUE TITLE
security-oauth2-quickstart is failing with main (at least)

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#42680]
See https://github.com/quarkusio/quarkus-quickstarts/actions/runs/10482330857/job/29033262358 for a failing run.

```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.715 s <<< FAILURE! -- in org.acme.security.oauth2.TokenSecuredResourceTest
Error:  org.acme.security.oauth2.TokenSecuredResourceTest.testRolesAllowed -- Time elapsed: 0.803 s <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <401>.
```

**Comment by sberyozkin** [comment]
This extension is not supported right now, would Loic @loicmathieu like to refresh it a bit ?

**Comment by loicmathieu** [comment]
I can have a look later this week as to why this test is failing.

@sberyozkin what do you think need to be refreshed on this extension?

**Comment by sberyozkin** [comment]
Hey @loicmathieu , good to hear from you, yeah, I meant, please check what is failing as opposed to some major refactoring, may be some minor updates are necessary. I'll try to help if you won't find enough time, thanks

**Comment by sberyozkin** [comment]
@jedla97 https://github.com/quarkusio/quarkus-quickstarts/pull/1445 should fix this one, right ?

**Comment by loicmathieu** [comment]
I cannot ses how the assertions worked in the first place as the header value should be `Bearer <token>` not `Bearer: <token>`.

**Comment by loicmathieu** [comment]
> it had something like .substring(7), which is why I guess it worked

Yes, if it substring, then trim it would have worked.

I merged the quickstart PR as it's obviously right.
Let's see if it fixes native CI on the next run.
