### ISSUE TITLE
Keycloak Admin Client version 25.x is no longer compatible with older versions of Keycloak.

### ISSUE THREAD

**Issue by andrejpetras** [quarkusio/quarkus#42701]
### Describe the bug

The latest Quarkus version > 3.13.x uses the Keycloak admin client version 25.x. This client is no longer compatible with older versions of Keycloak.

Keycloak ticket: https://github.com/keycloak/keycloak/issues/32337

### Expected behavior

Create a compatible API where optional attributes are possible.

### Actual behavior

The library's ClientRepresentation model has a new attribute that is not optional.

Error: 
 {"error":"Unrecognized field \"type\" (class org.keycloak.representations.idm.ClientRepresentation), not marked as

### Output of `uname -a` or `ver`

Java version: 21.0.1, vendor: Azul Systems, Inc., runtime: /home/andrej/tools/zulu21.30.15-ca-jdk21.0.1-linux_x64 Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "5.15.146.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

### Output of `java -version`

21

### Quarkus version or git rev

3.13.x

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 21.0.1, vendor: Azul Systems, Inc., runtime: /home/andrej/tools/zulu21.30.15-ca-jdk21.0.1-linux_x64 Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "5.15.146.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

**Comment by sberyozkin** [comment]
Thanks @andrejpetras, I suppose we can only wait until the Keycloak issue is resolved

**Comment by gsmet** [comment]
This is an upstream issue. Let's track it upstream.
