### ISSUE TITLE
Enhanced conditional BuildStep

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#4270]
The `BuildStep` annotation supports simple conditions `onlyIn/onlyIfNot` that one can implement using a `BooleanSupplier` but in some cases it would be nice to have support for more enhanced construct.

In my specific case I have a core extension with a `BuildStep` that should provide the default instance for a given interface and a number of extensions that can provide specialized implementations for that.

I've actually solved the issue by using an `MultiBuildItem` and depending on number of instances found, I do instantiate the default implementation, get the first one that is found or throw an exception in case of multiple instances being found.

This solution works fine but as it seems to me a common pattern it would be nice if it could be expressed through annotations, i.e. spring has a `ConditionalOnMissingBean` that I've used extensively to implement the same logic at runtime. 

Maybe related to: https://github.com/quarkusio/quarkus/issues/4114

**Comment by stuartwdouglas** [comment]
I don't know if the core build step processing can actually handle this, at the moment we handle this as you have described, with a MultiBuildItem that extensions produce, and then an aggregator step that produces the real SimpleBuildItem (providing a default if necessary). 

@dmlloyd is there a way to simplify this, or would it require major changes to the build step handling?

**Comment by dmlloyd** [comment]
I have a couple ideas, let me get back to you.

**Comment by dmlloyd** [comment]
How abour #4297?

**Comment by lburgazzoli** [comment]
Tested and works for my case
