### ISSUE TITLE
Continuous testing exclude-tags or exclude-engines cannot be configured via pom.xml anymore in 3.13

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#42714]
### Describe the bug

Imagine a test with `@Tag("slow")` and the following in `pom.xml`:
```xml
<quarkus.test.exclude-tags>slow</quarkus.test.exclude-tags>
```
As expected, Quarkus 3.12.3 does not execute this test in continuous testing, but Quarkus 3.13.3 (or 3.13.0) does.

Same goes for `quarkus.test.exclude-engines`.

### Expected behavior

Test excluded

### Actual behavior

Test not excluded

### How to Reproduce?

[q_ct-tags.zip](https://github.com/user-attachments/files/16717385/q_ct-tags.zip)

- `mvn quarkus:test` -> test is executed 🔴 
- `mvn quarkus:test -Dquarkus.platform.version=3.12.3` -> test is not executed 🟢 

### Quarkus version or git rev

3.13.0-.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.8

### Additional information

First discussed here: https://github.com/quarkusio/quarkus/discussions/42326

https://github.com/quarkusio/quarkus/commit/00350b7a84a3a1ec0aee49be9e848c84cda2bafd broke it.

You cannot use `application-test.properties` either, but that has never worked AFAICS.

`mvn ... -Dquarkus.test.exclude-tags=slow` does work.

A workaround can be found here: https://github.com/quarkusio/quarkus/discussions/42326#discussioncomment-10276264

**Comment by gsmet** [comment]
@radcortez I think I will need your help here. My commit broke getting the properties from the POM. Not sure how we populate them? Or if the fact that it was working before was just a consequence of it being poorly implemented in the first place.

**Comment by radcortez** [comment]
Looking into the old implementation, I don't see how POM properties were getting loaded. The code was looking directly into a `Properties` instance loaded from `application.properties`.

Let me investigate.
