### ISSUE TITLE
Update to new postgres jdbc driver version 42.7.4

### ISSUE THREAD

**Issue by svendiedrichsen** [quarkusio/quarkus#42723]
### Description

Please update to the latest postgres jdbc driver version [42.7.4](https://github.com/pgjdbc/pgjdbc/releases/tag/REL42.7.4).  It contains some notable performance enhancements and bugfixes.

**Comment by svendiedrichsen** [comment]
Fixed with #42742

**Comment by gsmet** [comment]
Will backport to 3.14.1.

**Comment by svendiedrichsen** [comment]
@gsmet Do you also plan to backport to 3.8.x LTS?

**Comment by gsmet** [comment]
That's not actually planned for the next one (that is planned for Aug 29th).

Having a look at the relatively massive changelog for a late micro, I think I would prefer some bake time before backporting to the 3.8 branch.

Is there a particular item that is blocking you?

**Comment by svendiedrichsen** [comment]
Not really blocking but we are planning to switch to 3.8.x Version and would like to harvest the performance gains the new JDBC driver offers. We have a mixed system architecture and are already using this JDBC driver version with our Payara servers and have seen a significant performance improvement there.

**Comment by gsmet** [comment]
OK. I would recommend to update it locally then. I don't foresee any issue doing that.

As for LTS versions, we are usually a bit conservative as the shiny new performance patch can sometimes have bad consequences. And in the case of the JDBC driver, it can quickly become critical.

**Comment by svendiedrichsen** [comment]
Yes, I understand it of course. We will try to update locally. Thanks for your work on quarkus. It a really great project.
