### ISSUE TITLE
Ability to pass CDI managed instances into a recorder

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#4272]
At the moment it is quite difficult to mix recording and CdI managed instances. It should be possible to use the RecorderContext to request a proxy for a CDI normal scoped bean or Instance that can then be passed into the recorder. 

I think has the potential to simplify a lot of code, and make it much less likely to get circular dependencies with the bean container.

**Comment by mkouba** [comment]
@stuartwdouglas A simple pseudocode example would be really helpful. It has a potential to simplify the code but it could be also even more confusing for extension authors.

**Comment by stuartwdouglas** [comment]
The synthetic bean stuff takes care of my use case.
