### ISSUE TITLE
Config Doc - Better structure path and the corresponding env var

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#42736]
When I worked on the new annotation processor, I followed a similar structure for the path, the additional paths and the environment variable than what was existing.

It was a mistake because we end up having only the env var for the main path, and we probably want to have the env var for all the paths (even if we don't display it in the doc).

Typically, that can be useful when providing the info to the IDEs as we denormalize the properties.

**Comment by lasteris** [comment]
@gsmet can you point some info more about new annotation processor, please ? Because we want to create `quarkus-extension-processor` based project to *generate* config-docs not to extensions, but microservices. Something happened important in last weeks with this functionality ? I ask it, because see in migration to 3.14 ` legacy @ConfigRoot approach` - phrase, so... @ConfigRoot is deprecated ?(

**Comment by gsmet** [comment]
What is considered deprecated is the use of `@ConfigRoot` alone with config classes. Extensions should use `@ConfigRoot` in conjunction with `@ConfigMapping` and interfaces.
Maybe I didn't choose my name wisely. I will clarify in the migration guide.

I agree that having an annotation processor to generate the doc of an application would be useful, even if a bit orthogonal as extensions are a bit of a different beast, there's definitely some code that could be shared.

I know that @radcortez wanted to integrate something in SmallRye Config at some point.

The code for our new extension annotation processor is here: https://github.com/quarkusio/quarkus/tree/main/core/processor .

The doc part is clearly isolated. It generates a model that is then assembled and used by a Maven plugin that generates Asciidoc that we can integrate in our doc.

**Comment by radcortez** [comment]
Extension Configuration should be done as documented:
https://quarkus.io/guides/writing-extensions#configuration

We have been supporting `@ConfigRoot` with classes and `@ConfigRoot` with interfaces `@ConfigMapping` for a while, but we want to drop the class support completely.
