### ISSUE TITLE
Possible inconsistencies in Kafka Streams guide

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4275]
Hey @gunnarmorling 

I was discussing with @mouachan and he had a hard time following the guide. In particular, `metadata.host().equals(host)` came out of nowhere and he did not get how we retrieve the host.

He looked at https://github.com/quarkusio/quarkus-quickstarts/tree/master/kafka-streams-quickstart but it looks like an entirely different code than the one in the guide.

I'm opening this to qualify the issue and see what we can do about it.

**Comment by gunnarmorling** [comment]
Ok, let's see what we can do.

> In particular, metadata.host().equals(host) came out of nowhere and he did not get how we retrieve the host.

The host name [is injected](https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-streams-quickstart/aggregator/src/main/java/org/acme/quarkus/sample/kafkastreams/streams/InteractiveQueries.java#L27-L28) based on the `HOSTNAME` env var.

It is part of a key's metadata on which application node (as identified by host names) it is maintained. So when looking up a key we can decide whether it's owned by the queried node itself or by another one. In case of the latter, we currently return a redirect, but one could also think of course of using the JAX-RS client API and obtaining that data, so  that the client can get key from any host.

> He looked at https://github.com/quarkusio/quarkus-quickstarts/tree/master/kafka-streams-quickstart but it looks like an entirely different code than the one in the guide.

Hum, it shouldn't really be different. Any specific differences you could point out?

**Comment by mouachan** [comment]
Hi Gunnar,

Thanks for the explanation ! If we follow only the guide (without looking to the git repo), it’s a bit hard to understand that the hostname is injected. 

> Hum, it shouldn't really be different. Any specific differences you could point out?
> 

Please forget this, I was looking to the wrong git repo.

Thanks a lot.

Regards,

Mourad

**Comment by gunnarmorling** [comment]
> If we follow only the guide (without looking to the git repo), it’s a bit
hard to understand that the hostname is injected.

I see; so perhaps we should expand this part a bit then. Perhaps you could
send a PR with the clarification you have in mind?

>

**Comment by gsmet** [comment]
@gunnarmorling do you see anything we need to improve or should we close?

**Comment by gunnarmorling** [comment]
@gsmet, I think it can be closed.

**Comment by geoand** [comment]
Closing as per the comment above (not even 5 years late :))
