### ISSUE TITLE
Rest Client (formerly reactive) keep using DEFAULT_MAX_POOL_SIZE

### ISSUE THREAD

**Issue by lasteris** [quarkusio/quarkus#42778]
### Describe the bug

Quarkus 3.13.3
Java 21
Problem:

```
jakarta.ws.rs.ProcessingException: The timeout of 30000 ms has been exceeded when getting a connection to 10.148.10.23:8122
```

In Source code of Quarkus we have found this:
```
org.jboss.resteasy.reactive.client.impl;
public class ClientImpl implements Client {

    private static final Logger log = Logger.getLogger(ClientImpl.class);

    private static final int DEFAULT_CONNECT_TIMEOUT = 15000;
    private static final int DEFAULT_CONNECTION_POOL_SIZE = 20;
......

Object connectionPoolSize = configuration.getProperty(CONNECTION_POOL_SIZE);
        if (connectionPoolSize == null) {
            connectionPoolSize = DEFAULT_CONNECTION_POOL_SIZE;
        } else {
            log.debugf("Setting connectionPoolSize to %d", connectionPoolSize);
        }
        options.setMaxPoolSize((int) connectionPoolSize);
        options.setHttp2MaxPoolSize((int) connectionPoolSize);
....
```

But this is obviously ignored, see last image (dump of our service in visualvm).

Also, if you read documentation, you may find https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus-rest-client-connection-pool-size.
And this is in source code used like that:
```
package io.quarkus.rest.client.reactive.runtime;

public class RestClientCDIDelegateBuilder<T> {
...

private void configureCustomProperties(QuarkusRestClientBuilder builder) {
       .....

        Optional<Integer> poolSize = oneOf(clientConfigByClassName().connectionPoolSize,
                clientConfigByConfigKey().connectionPoolSize, configRoot.connectionPoolSize);
        if (poolSize.isPresent()) {
            builder.property(QuarkusRestClientProperties.CONNECTION_POOL_SIZE, poolSize.get());
        }
.....
```

Then, we have set it up to `uarkus.rest-client.oms-client.connection-pool-size=1500` but this is ignored too.

Also, we tried to do https://quarkus.io/guides/rest-client#use-custom-http-options, but still no effect at all.

Look at our netstat:
![изображение](https://github.com/user-attachments/assets/3795c83a-f8c6-444a-ba11-c0d017db4669)

Look at our dump:

![изображение](https://github.com/user-attachments/assets/203c2232-6b09-4986-9145-44bf7955aa0f)

### Output of `uname -a` or `ver`

Linux rmis01service 5.15.87-1.el7.3.x86_64 #1 SMP Mon Jan 16 21:44:20 MSK 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21" 2023-09-19 LTS OpenJDK Runtime Environment Corretto-21.0.0.35.1 (build 21+35-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.0.35.1 (build 21+35-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.13.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.9

**Comment by geoand** [comment]
Thanks!

Any chance you can upload a sample so we can be sure we are fixing against the proper thing?

**Comment by lasteris** [comment]
> Thanks!
> 
> Any chance you can upload a sample so we can be sure we are fixing against the proper thing?

You mean dump file  ?

**Comment by geoand** [comment]
No no, I mean a reproducer that I can use to see what configuration and code you use and see why the proper settings is not applied

**Comment by lasteris** [comment]
> No no, I mean a reproducer that I can use to see what configuration and code you use and see why the proper settings is not applied

ok, i ll do it.

**Comment by geoand** [comment]
🙏🏽

**Comment by lasteris** [comment]
@geoand https://github.com/lasteris/quarkus-repro-42778/blob/main/README.md
Tell me, if such suite not enough (I hope my tests are not useless :) )

**Comment by geoand** [comment]
@cescoffier I see that `HttpClientOptions` (which is the what the REST Client populates via `org.jboss.resteasy.reactive.client.impl.ClientImpl`) has a `PoolOptions` object which we populate correctly.

However, `HttpClientBuilder` in addition to `HttpClientOptions` (which as we said, we populate correctly), can also be configured with `PoolOptions` (which we never do). 

What is the intended use of these two options? Should we copy the `PoolOptions` we are setting in `HttpClientOptions` into `HttpClientBuilder` with an explicit call?

**Comment by cescoffier** [comment]
Do you have the link to the code? I believe if we do not copy, it creates an empty (using default value) `PoolOptions`.

**Comment by geoand** [comment]
See https://github.com/quarkusio/quarkus/blob/43680ebbcd4b4a3a633965baeeffa381e3dd0915/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientImpl.java#L195

**Comment by cescoffier** [comment]
We need to call `with(PoolOptions)` explicitely, otherwise:

```
    PoolOptions po = poolOptions != null ? poolOptions : new PoolOptions();
```

The `new PoolOptions` is configured and use the default values.

**Comment by geoand** [comment]
Yeah, that's exactly what I was asking :)

**Comment by geoand** [comment]
@lasteris can you try https://github.com/quarkusio/quarkus/pull/42823 please?

**Comment by lasteris** [comment]
yeah, of course

**Comment by lasteris** [comment]
@geoand @cescoffier Also, can you give an advice how i can build client to pass this options (in current version of Quarkus ) to make it work ? 
Right now i see only option to use WebClient directly..

**Comment by geoand** [comment]
I don't think there is anything you can do until we backport the fix

**Comment by lasteris** [comment]
@geoand sorry for delay. 
I've build Quarkus with this change and run test `provesThatEven6CallsRequiresQueuing` again:
``Expecting actual:
  1196L
to be greater than or equal to:
  2000L
```
So i can approve, that it works!

**Comment by geoand** [comment]
Thanks for checking!
