### ISSUE TITLE
User entity containing @UserDefined will not be listed if it is from external dependency.

### ISSUE THREAD

**Issue by pasha-gr** [quarkusio/quarkus#42777]
https://github.com/quarkusio/quarkus/blob/2ca270361fa1a2e6b3035d576c4517d9c905e8c4/extensions/security-jpa-common/deployment/src/main/java/io/quarkus/security/jpa/common/deployment/QuarkusSecurityJpaCommonProcessor.java#L32

Everything is ok when my user entity containing `@UserDefined` annotation is located in the source code. As I move them into external package, `ApplicationIndexBuildItem `instance can't find and list it. Using `Jandex `didn't helped. 
At the end `AnonymousIdentityProvider `is selected as default bean instead of `JpaIdentityProvider `and it makes my application remain unsecure.

My assumption is my code is implemented correctly and quarkus-security-jpa still should work properly.
Any comment?

**Comment by geoand** [comment]
What is done is correct. 

If you have libraries which contain such annotations what you have to do is index them. There are multiple ways to do this and the best description I have come across on how to do that is [this](https://stackoverflow.com/a/55513723/2504224).

**Comment by pasha-gr** [comment]
@geoand I already mentioned that I have used jandex, it only helps Hibernate to scan my entities but does not help quarkus-security-jpa to recognize and secure the app!
