### ISSUE TITLE
RxJava Support

### ISSUE THREAD

**Issue by deripas** [quarkusio/quarkus#4278]
How about using asynchronous Rest in a reactive style.
For example, current support `CompletionStage`:
```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public CompletionStage<String> hello() {
        CompletableFuture<String> result = new CompletableFuture<>();
        Single.just("hello")
                .subscribeOn(Schedulers.single())
                .subscribe(result::complete, result::completeExceptionally);
        return result;
    }
```
Expected replacement:
```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Single<String> hello() {
        return Single.just("hello")
                .subscribeOn(Schedulers.single());
    }
```

From Spring [Reactive Types](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-async-reactive-types)
> Reactive return values are handled as follows:
> 
> - A single-value promise is adapted to, similar to using DeferredResult. Examples include Mono (Reactor) or Single (RxJava).
> - A multi-value stream with a streaming media type (such as application/stream+json or text/event-stream) is adapted to, similar to using ResponseBodyEmitter or SseEmitter. Examples include Flux (Reactor) or Observable (RxJava). Applications can also return Flux<ServerSentEvent> or Observable<ServerSentEvent>.
> - A multi-value stream with any other media type (such as application/json) is adapted to, similar to using DeferredResult<List<?>>.

**Comment by kenfinnigan** [comment]
I'm pretty sure RX return types are already supported with RESTEasy.

@FroMage should be able to confirm

**Comment by deripas** [comment]
You can learn more about how to do this?
I have  dependency RestEasy:
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy</artifactId>
        </dependency>
```
And Rest controller:
```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Single<String> hello() {
        return Single.just("hello")
                .subscribeOn(Schedulers.single());
    }
```

Response via rest-client (as simple `toString`):
```
io.reactivex.internal.operators.single.SingleSubscribeOn@5027b7c0
```

**Comment by kenfinnigan** [comment]
Take a look at https://docs.jboss.org/resteasy/docs/4.3.1.Final/userguide/html_single/index.html#d4e2322

You would need a dependency for `resteasy-rxjava2` artifact from RESTEasy. It's already present within the Quarkus BOM (https://github.com/quarkusio/quarkus/blob/master/bom/runtime/pom.xml#L1546) so you don't need to specify a version

**Comment by deripas** [comment]
Thanks!
