### ISSUE TITLE
quarkus-websockets-next client connect to WSS not possible

### ISSUE THREAD

**Issue by CLandsberg** [quarkusio/quarkus#42806]
### Describe the bug

Client connect to a WSS (WebSockets over SSL/TLS) is not possible. This is because the URI is check on https:// and not wss://

io.quarkus.websockets.next.runtime.WebSocketConnectorBase
Line 209:

```
    protected boolean isHttps(URI uri) {
        return "https".equals(uri.getScheme());
    }
```

Check should be on wss instead

### Expected behavior

Client connect to a WSS

### Actual behavior

Not connecting to WSS

### How to Reproduce?

1. configure a websocket server with mtls
2. connect as a client with wss

### Output of `uname -a` or `ver`

Linux endeavouros 6.10.6-arch1-1

### Output of `java -version`

openjdk version "21.0.4"

### Quarkus version or git rev

Version 3.13.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8

**Comment by geoand** [comment]
cc @mkouba
