### ISSUE TITLE
quarkus-websockets-next client adds / to empty path

### ISSUE THREAD

**Issue by CLandsberg** [quarkusio/quarkus#42808]
### Describe the bug

Using @WebSocketClient(path = "") with an empty path is not possible.
io.quarkus.websockets.next.runtime.WebSocketConnectorBase line 128:
`return path.startsWith("/") ? sb.toString() : "/" + sb.toString();`
This adds a / even if the path is empty

### Expected behavior

Add no / for an empty path

### Actual behavior

Adds a / to an empty path

### Output of `uname -a` or `ver`

Linux endeavouros 6.10.6-arch1-1

### Output of `java -version`

openjdk version "21.0.4"

### Quarkus version or git rev

Version 3.13.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
@CLandsberg I'm not 100% sure I understand your use case correctly but hopefully the https://github.com/quarkusio/quarkus/pull/42830 will fix the problem. It would be great if you could test the PR with your setup/app.
