### ISSUE TITLE
The configuration options missing the `quarkus.oidc.credentials.*`

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#42815]
### Describe the bug

Going through the [OpenID Connect authorization code flow mechanism for protecting web applications](https://quarkus.io/guides/security-oidc-code-flow-authentication) guide I wanted to check the description of some properties at [All configuration options](https://quarkus.io/version/main/guides/all-config) but the configuration option found only references in other properties or nothing. The affected properties are probably all `quarkus.oidc.credentials.*`. Try to run some quicstart which contain these properties and don't see warning that they are unknow.

When checked the [All configuration options](https://quarkus.io/guides/all-config) for 3.13 I see these properties.

### Quarkus version or git rev

main

**Comment by jedla97** [comment]
Looking at it more it seems that whole section for `[OpenID Connect](https://quarkus.io/guides/all-config#quarkus-oidc_quarkus-oidc-openid-connect)` missing on main preview [OpenID Connect](https://quarkus.io/version/main/guides/all-config#quarkus-oidc_quarkus-oidc-openid-connect)

**Comment by sberyozkin** [comment]
Looks like the individual properties which represent groups are not expanded

**Comment by gsmet** [comment]
When I look for `quarkus.oidc`, I can see the `quarkus.oidc.credentials.*` block.

**Comment by gsmet** [comment]
Ah OK, sorry, I misunderstood, they are in the all config doc but not in the partial include.

**Comment by gsmet** [comment]
Ah no, I even misunderstood again, you're complaining about `main` missing things. It's probably due to the new extension annotation processor, I will have a look.

**Comment by gsmet** [comment]
Not sure exactly what's going on yet but the pattern is a bit odd so that might be causing issues:

```
@ConfigGroup
public class OidcTenantConfig extends OidcCommonConfig {
```

We have an extension config group extending a config group that comes from another extension.
