### ISSUE TITLE
Show the list of endpoints on the default index page

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#42825]
### Describe the bug

Currently it's not obvious how to find the list of available endpoints when opening Quarkus:
![image](https://github.com/user-attachments/assets/db6e35e7-fbab-46ed-89b9-b7575ba9f594)

This is very important as we previously had the codestart list with their link and now there is nothing to find it.

### Expected behavior

Display the list of endpoint like on the 404 page
![image](https://github.com/user-attachments/assets/e056d895-bb3b-4aaf-8e3d-2ab85c61a851)

### How to Reproduce?

Create any Quarkus app with a codestart from code.quarkus.io

### Quarkus version or git rev

3.14.0

**Comment by maxandersen** [comment]
couldn't the page include the readme sections that each codestart contribute to readme ?

they can have more info than just URLs to go visit.

**Comment by ia3andy** [comment]
Also I think we should sort the list of endpoint by number of `/` in order to have the direct pages first..

**Comment by ia3andy** [comment]
I also added important because it look like a minor issue, but it really isn't

**Comment by maxandersen** [comment]
It's a bug. Code starts in past could add info to guide users to what to navigate to and what to do. 

Relevant for the quick presets added to code.quarkus which now don't show/help the user what to do.

**Comment by cescoffier** [comment]
The title of an issue should not indicate its priority or importance. Doing so would break tools' building release notes or script reporting activity (typically, I would do the same edit because it messes up my report). We have "priority" labels (blocker and urgent). We could potentially add "important."

However, I'm not totally sure about the "good first issue".

**Comment by cescoffier** [comment]
BTW, I totally agree it's a bug / regression and we should fix it, and backport it to the LTS.

**Comment by ia3andy** [comment]
> The title of an issue should not indicate its priority or importance. Doing so would break tools' building release notes or script reporting activity (typically, I would do the same edit because it messes up my report). We have "priority" labels (blocker and urgent). We could potentially add "important."
> 
> However, I'm not totally sure about the "good first issue".

I should have asked the proper way to mark it as important you are right..

The fix shouldn't be too hard as we already have the 404 page no?

**Comment by cescoffier** [comment]
It should not be too hard if you are @phillip-kruger .... it can be a bit overwhelming if that's your first contribution.

**Comment by phillip-kruger** [comment]
I'll have a look

**Comment by maxandersen** [comment]
lets add link to the readme on local file system from the index page - then I think we are covered well for LTS to enable codestarts to provide context/info to users.

**Comment by ia3andy** [comment]
and the list of endpoints please :)

**Comment by phillip-kruger** [comment]
This is done
