### ISSUE TITLE
quarkus-rest-client-jackson - Force property

### ISSUE THREAD

**Issue by Visserr2** [quarkusio/quarkus#42857]
### Describe the bug

When upgrading to Quarkus 3.14.1 I noticed the following warning:
`Unrecognized configuration key "quarkus.rest-client.x,.x.x.force" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo`

When looking in the configuration page in dev-ui it looks like for every rest-client there is a "force" property set to "yes". When reverting back to 3.13.3 al those properties are gone. But I cannot find any information about this.

Also I use quotes around the rest-client name like the following:
`quarkus.rest-client."api-name".url`

This now only seem to work for for a acouple of rest-client while when calling another client it will give the following error:
`Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'quarkus.rest-client.api-name.url'`

### Expected behavior

I would expect the same behaviour for all rest-clients regarding urls in de config file. Also I do not expect the 'force' properties on the Rest Clients.

### Actual behavior

Example from my code:
quarkus.rest-client."mhno-selligent-api".url=https://api-test.ndcnet.nl/v2/selligent  <-- gives error
quarkus.rest-client."mhno-zeno-api".url=https://api-test.ndcnet.nl/v2/zeno <-- is fine

Also see image below for the force properties that are not specified in property file:
![afbeelding](https://github.com/user-attachments/assets/5581c0de-e181-4fd5-b015-f6e6811bbd7e)

### How to Reproduce?

1. Upgrade to 3.14.1. 
2. use quarkus-rest-client-jackson and quarkus-rest-jackson
3. Having rest-clients set up and declare urls in property file

### Output of `java -version`

java 21.0.2 2024-01-16 LTS

### Quarkus version or git rev

3.14

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9,9

**Comment by geoand** [comment]
Please attach a sample application we can check.

Thanks

**Comment by Visserr2** [comment]
As you can see when starting this app you will see a lot of "force" attributes:
![afbeelding](https://github.com/user-attachments/assets/406dd5e6-38d5-4d7a-ae7c-8212e080af61)

I also think I know what is happening with the quotes on the url name. It looks like within quotes a word cannot be longer then 10 characters. When you separate with a dot it will start counting a new word. If you use another separator it wil will fail. 

quarkus.rest-client."urlabcdefghij.xyzi".url is possible but 
quarkus.rest-client"abcdefghij-xyz".url is not

When I remove the quotes it is fine. So I can change the urls but it is worth to know when upgrading to 3.14.1.
[code-with-quarkus.zip](https://github.com/user-attachments/files/16799712/code-with-quarkus.zip)

**Comment by geoand** [comment]
Thanks, we'll have a look soon.

**Comment by gsmet** [comment]
This is due to this patch: https://github.com/quarkusio/quarkus/pull/42106/files#diff-8680405c2cc745118cb17d3c1ad556d76c84132421204242a772afa8a9c929c9R26-R37 

/cc @radcortez

**Comment by radcortez** [comment]
I'll have a look.
