### ISSUE TITLE
classic resteasy-client: ensure sub-resources are also proxied

### ISSUE THREAD

**Issue by stesie** [quarkusio/quarkus#42851]
### Describe the bug

resteasy [resteasy-microprofile](https://github.com/resteasy/resteasy-microprofile) "recently" applied a bugfix that makes sure, that sub-resources to a microprofile client are also proxied properly.

* their bug report -> https://github.com/resteasy/resteasy-microprofile/issues/239
* their pr -> https://github.com/resteasy/resteasy-microprofile/pull/241

Given that in `quarkus-rest-client` the class `QuarkusProxyInvocationHandler`  duplicates their `ProxyInvocationHandler` and `QuarkusRestClientBuilder` duplicates their `RestClientBuilderImpl` ... both should be updated accordingly.

### Expected behavior

sub-resources are properly proxied, like they are with resteasy's microprofile client implementation.

### Actual behavior

sub-resources aren't proxied.

### Output of `uname -a` or `ver`

Darwin Stefans-Air.localdomain 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30) OpenJDK 64-Bit Server VM GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30, mixed mode, sharing)

### Quarkus version or git rev

3.8.5 and/or 3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 21.0.2, vendor: GraalVM Community, runtime: /Users/stefansiegl/.sdkman/candidates/java/21.0.2-graalce Default locale: de_DE, platform encoding: UTF-8 OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"

**Comment by geoand** [comment]
cc @jamezp

**Comment by jamezp** [comment]
I think this already works in RESTEasy. A simple test I just did seems to work.

**Comment by gsmet** [comment]
@jamezp you tested it in Quarkus? Because what the OP says is that it’s fixed in RESTEasy but not in the Quarkus versions of the classes.

**Comment by jamezp** [comment]
Oh, I see. So this is in Quarkus where a change needs to happen. To be honest, I'm not sure when I'd have time to look at that. My plate is pretty full at the moment with WildFly, RESTEasy and Jakarta EE 11. One of these days though I'd like to learn more about how all this works in Quarkus and with RESTEasy Reactive :)

**Comment by gsmet** [comment]
@stesie would you be willing to create a PR given you did the analysis?

**Comment by maxr2011** [comment]
@gsmet just created a pull-request for the Quarkus based classes of the ProxyInvocationHandler and RestClientBuilder: https://github.com/quarkusio/quarkus/pull/42905

Since this code snippet is already tested inside the resteasy lib, I did not add any additional integration tests, but can do so if necessary.

CC @stesie
