### ISSUE TITLE
org.springframework.aot.hint.annotation.Reflective missing from our Spring compatibilty layer?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#42871]
In `main`, when I `mvn clean verify -f integration-tests/openapi`, I get this warning:

> 2024-08-29 16:57:33,730 WARN  [io.qua.arc.pro.BeanArchives] (build-8) Failed to index org.springframework.aot.hint.annotation.Reflective: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: TEST for BigDecimalTest (QuarkusTest)@218e186b

We should probably add this class to our Spring compatibility layer?

**Comment by aureamunoz** [comment]
Yes, we can add it to quarkus-spring-aop-api

**Comment by gsmet** [comment]
Thanks, let's fix that before we release the LTS!

**Comment by aureamunoz** [comment]
https://github.com/quarkusio/quarkus-spring-api/pull/34
