### ISSUE TITLE
Quarkus 3.11: RxJava2 call raises NPE

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#42873]
### Describe the bug

I need to use RxJava2 API in a Quarkus 3.11 REST service. For some reason, I cannot use anything else like Mutiny, etc.
The only Maven dependency I found is `org.jboss.rest-easy:resteasy-rxjava2`. I didn't find anything like `io.quarkus:quarkus-rest-rxjava2`.
In an integration test I'm calling the service with a REST client. Since I'm using ` resteasy-rxjava2` I need to use `quarkus-resteasy-client` as well such that to avoid mixing.
But doing that i get the following exception:

    2024-08-29 17:34:11,682 INFO  [io.quarkus] (main) quarkus-rxjava2-issue 1.0-SNAPSHOT on JVM (powered by Quarkus 3.11.0) started in 1.740s. Listening on: http://localhost:8081
    2024-08-29 17:34:11,684 INFO  [io.quarkus] (main) Profile test activated. 
    2024-08-29 17:34:11,684 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-client, smallrye-context-propagation, vertx]
    jakarta.ws.rs.ProcessingException: java.lang.NullPointerException: Cannot invoke  "org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.getMethod()" because the return value of "org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.getClientInvoker()" is null 

### Expected behavior

I expect that everything works without exception but I'm not sure whether the mentioned artifacts and extensions are the correct ones.

### Actual behavior

The following exception is raised:

    2024-08-29 17:34:11,682 INFO  [io.quarkus] (main) quarkus-rxjava2-issue 1.0-SNAPSHOT on JVM (powered by Quarkus 3.11.0) started in 1.740s. Listening on: http://localhost:8081
    2024-08-29 17:34:11,684 INFO  [io.quarkus] (main) Profile test activated. 
    2024-08-29 17:34:11,684 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-client, smallrye-context-propagation, vertx]
    jakarta.ws.rs.ProcessingException: java.lang.NullPointerException: Cannot invoke  "org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.getMethod()" because the return value of "org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.getClientInvoker()" is null 

### How to Reproduce?

    $ git clone https://github.com/nicolasduminil/quarkus-rxjava2-issue.git
    $ cd quarkus-rxjava2-issue
    $ mvn package
    $ java -jar target/quarkus-app/quarkus-run.jar

In a different terminal:

    $ cd quarkus-rxjava2-issue
    $ $ mvn -Dbase_uri/mp-rest/url=http://localhost:8080 failsafe:integration-test
    [INFO] Scanning for projects...
    [INFO] 
    [INFO] ---------< fr.simplex-software.workshop:quarkus-rxjava2-issue >---------
    [INFO] Building quarkus-rxjava2-issue 1.0-SNAPSHOT
    [INFO]   from pom.xml
    [INFO] --------------------------------[ jar ]---------------------------------
    [INFO] 
    [INFO] --- failsafe:3.2.5:integration-test (default-cli) @ quarkus-rxjava2-issue ---
    [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
    [INFO] 
    [INFO] -------------------------------------------------------
    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    [INFO] Running fr.simplex_software.workshop.tests.TimeResourceIT
    2024-08-29 17:58:50,646 INFO  [io.quarkus] (main) quarkus-rxjava2-issue 1.0-SNAPSHOT on JVM (powered by Quarkus 3.11.0) started in 1.714s. Listening on: http://localhost:8081
    2024-08-29 17:58:50,648 INFO  [io.quarkus] (main) Profile test activated. 
    2024-08-29 17:58:50,648 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-client, smallrye-context-propagation, vertx]
    jakarta.ws.rs.ProcessingException: java.lang.NullPointerException: Cannot invoke "org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.getMethod()" because the return value of "org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.getClientInvoker()" is null

### Output of `uname -a` or `ver`

Linux nicolas-XPS-15-9570 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /opt/apache-maven-3.9.5 Java version: 21.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21-oracle-x64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-119-generic", arch: "amd64", family: "unix"

### Additional information

N/A

**Comment by codespearhead** [comment]
That [1] seems to be a private repository.

Either way, the following sounds like an XY problem:

> "For some reason, I cannot use anything else like Mutiny, etc."

[1] https://github.com/nicolasduminil/quarkus-rxjava2-issue.git

**Comment by nicolasduminil** [comment]
@gsmet: I'm sorry, I forgot to make the repo public. Now I modified it, if you can have a look.

**Comment by geoand** [comment]
We made the decision a while ago that we are not going to support RxJava in any way, shape or form. 

For the REST Client specifically, that means that when you want to have an async response, you need to use Mutiny or the JDK's `CompletionStage`.

**Comment by nicolasduminil** [comment]
I've found that: https://github.com/quarkusio/quarkus/issues/4278. But probably things has changed since ...

**Comment by geoand** [comment]
Right, that was a very long time ago
