### ISSUE TITLE
Maven plugin's devmode doesn't take into account versions overridden through system properties or profiles

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#4289]
If I run devmode with an application with a pom like this:
```
(...)
<properties>
  <quarkus.version>0.21.0</quarkus.version>
</properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

(... and then whatever dependencies I need)
```

but I override the `quarkus.version` from the command line (as an argument to the `mvn` command), it will still spin up Quarkus 0.21.0 instead of the version that I requested (it will execute the Maven plugin of the correct version, but the Maven plugin will run the wrong version of Quarkus). The same thing happens if I add and activate a specific Maven profile which overrides the version.

**Comment by jmartisk** [comment]
This is still an issue.
Probably closely related: https://github.com/quarkusio/quarkus/issues/3834

**Comment by gsmet** [comment]
@aloubyansky you aware of that one?

**Comment by aloubyansky** [comment]
i've recall the profiles-related issue but not the dev mode with the property.

**Comment by aloubyansky** [comment]
Looks like I have a fix for the dev mode at least.
