### ISSUE TITLE
Cannot initialize file manager

### ISSUE THREAD

**Issue by ChristianKernDev** [quarkusio/quarkus#42908]
### Describe the bug

Live reload in dev mode fails because of generated sources
![grafik](https://github.com/user-attachments/assets/d9eb54e7-50c9-4eff-ace7-fda5a3b591ff)

Project Setup: 
Quarkus Version: 3.13.1
Multi module maven setup with annotation processing declared in parent pom:
```
<pluginManagement>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>${compiler-plugin.version}</version>
      <configuration>
        <!-- keep parameter information for generators to work correctly -->
        <compilerArgument>-parameters</compilerArgument>
        <generatedSourcesDirectory>${project.build.directory}/generated-sources/
        </generatedSourcesDirectory>
        <source>${java.version}</source>
        <target>${java.version}</target>
        <annotationProcessorPaths>
          <path>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
          </path>
          <path>
            <groupId>project-groupId</groupId>
            <artifactId>annotation-processor</artifactId>
            <version>${project.version}</version>
          </path>
        </annotationProcessorPaths>
      </configuration>
    </plugin>
  </plugins>
</pluginManagement>
```

The initial startup of the app works just fine, but as soon as some file is changed and a reload is triggered i get above error message.

### Expected behavior

Live reload is working as expected with generated sources

### Actual behavior

Quarkus fails to reload. The change can be in any file for this to happen (no need to change a generated file)

**Comment by geoand** [comment]
Any chance you could attach a sample project that demonstrates the problem?

Thanks

**Comment by geoand** [comment]
cc @aloubyansky @FroMage

**Comment by FroMage** [comment]
This is weird, because we create it from Maven just in case this happens:

https://github.com/FroMage/quarkus/blob/259285db445adb1319e53db921ea69cccd4fe6f2/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L959

When your application starts, does this folder exist? Before any live-reload happens.

Also, how do you start Quarkus? What OS is this on?

**Comment by FroMage** [comment]
Oh, so it's a CLI, then?

**Comment by ChristianKernDev** [comment]
Yes the start Parameters are set by IntelliJ to the following:
```
C:\Users\VZU4427\.jdks\temurin-21.0.4\bin\java.exe -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:58740,suspend=y,server=n -javaagent:C:\Users\VZU4427\AppData\Local\JetBrains\IntelliJIdea2024.2\captureAgent\debugger-agent.jar=file:/C:/Users/VZU4427/AppData/Local/Temp/capture2.props -Dkotlinx.coroutines.debug.enable.creation.stack.trace=false -Ddebugger.agent.enable.coroutines=true -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 @C:\Users\VZU4427\AppData\Local\Temp\idea_arg_file2142525378 com.test.app.TestApp
```

I fixed the issue by changing the pom.xml configuration of the annotation processor to the following:
```
<pluginManagement>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>${compiler-plugin.version}</version>
      <configuration>
        <!-- keep parameter information for generators to work correctly -->
        <compilerArgument>-parameters</compilerArgument>
        <generatedSourcesDirectory>${project.build.directory}/generated-sources/annotations/</generatedSourcesDirectory>
        <source>${java.version}</source>
        <target>${java.version}</target>
        <annotationProcessorPaths>
          <path>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
          </path>
          <path>
            <groupId>project-groupId</groupId>
            <artifactId>annotation-processor</artifactId>
            <version>${project.version}</version>
          </path>
        </annotationProcessorPaths>
      </configuration>
    </plugin>
  </plugins>
</pluginManagement>
```

So generating the sources in the folder "target/generated-sources/annotations/" instead of "generated-sources/" seems to work. I guess some component is expecting the folder "generated-sources/annotations/" to exist.

Do you have any idea what component could cause this? The stacktrace is very vague in this area

**Comment by FroMage** [comment]
It's the Java compiler expecting this folder to exist. Normally, Maven creates `target/generated-sources/annotations` for us, but apparently it ignores `generatedSourcesDirectory` when you override it.

We should improve our code to automatically create the folder if it does not exist, in my opinion.

Do you feel like providing a PR? I can tell you where to add the line :)

**Comment by FroMage** [comment]
Great. I think the easiest is to add a `mkdirs` in https://github.com/quarkusio/quarkus/blob/b5a181e3cfe501b9d1ae261b5b4b875623b19386/core/deployment/src/main/java/io/quarkus/deployment/dev/filesystem/QuarkusFileManager.java in the two places where we have an annotation processors path, if it does not exist, with a comment mentioning this issue to make sure it does not get removed.
