### ISSUE TITLE
Provide a way to exclude /q/health from OpenAPI spec

### ISSUE THREAD

**Issue by brice-laurencin** [quarkusio/quarkus#42912]
### Description

SmallRye health is add through a filter [here](https://github.com/quarkusio/quarkus/blob/9ce1059f8742e385c1e63178cb9dba14916f89b2/extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/HealthOpenAPIFilter.java).
I'd like to be able to deactivate the addition of those endpoints to the generated openapi.json/yaml file.

I suppose a property in `application.properties` would help here.

Thanks!

**Comment by MikeEdgar** [comment]
@brice-laurencin, there is already a property which defaults to `false`. Do you have either of the following configurations set?
```
quarkus.smallrye-health.openapi.included=true
quarkus.health.openapi.included=true
```

**Comment by brice-laurencin** [comment]
Indeed!
thanks a lot for pointing that out.
