### ISSUE TITLE
Test: `quarkus.http.port` is not updated with random port activated through `quarkus.http.test-port=0`

### ISSUE THREAD

**Issue by edeweerd1A** [quarkusio/quarkus#42944]
### Describe the bug

Imagine an application calling itself and a test testing the flow.
We activate this through:

```properties
quarkus.http.test-port=0
clientService/mp-rest/url=http://localhost:8080
%test.clientService/mp-rest/url=http://localhost:${quarkus.http.port}
```

### Expected behavior

In a QuarkusTest, as it was working in Quarkus 3.13.3, expecting `quarkus.http.port` to be resolved with the random HTTP port.

### Actual behavior

Since Quarkus 3.14 the port is not resolved and it keeps the production port, here 8080 the default port. The test is broken.

### How to Reproduce?

[repro-http-port-not-injected.zip](https://github.com/user-attachments/files/16835330/repro-http-port-not-injected.zip)

* Unzip above reproducer project
* Run `mvn clean install`

### Output of `uname -a` or `ver`

Linux 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 OpenJDK Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22) OpenJDK 64-Bit Server VM GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22, mixed mode, sharing)

### Quarkus version or git rev

3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

**Comment by gsmet** [comment]
You're completely right and thanks for the report. There is a WIP here https://github.com/quarkusio/quarkus/pull/42932 that we plan to include in 3.14.2.

Maybe you could try this branch and make sure it fixes your case?

**Comment by edeweerd1A** [comment]
Hi, thanks for the good news. I built the branch locally and can confirm it fixes this issue.
