### ISSUE TITLE
Vertx web - shared BodyHandler instance

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#4294]
@stuartwdouglas @cescoffier Is there a reason why we create a new `BodyHandler` for each `@Route` method?

https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/VertxWebRecorder.java#L70-L82

If not I can modify the code to share one instance instead.

**Comment by cescoffier** [comment]
Good catch, we should have only one.

**Comment by cescoffier** [comment]
(as you proposed yourself, I've assigned the issue to you)
