### ISSUE TITLE
 Signed OIDC UserInfo whith charset not recognized

### ISSUE THREAD

**Issue by airone-x1** [quarkusio/quarkus#42958]
### Describe the bug

#42519 allows signed userinfo token.
After testing this is not always the case, perhaps due to the presence of a specified encoding (charset).

Same message as #42341 : `ID token verification has failed: Unexpected char 101 at (line no=1, column no=1, offset=0` 

### Expected behavior

Quarkus OIDC client accept and read UserInfo response in jwt format as allowed by OIDC specification

### Actual behavior

Signed UserInfo responses are not supported by Quarkus

### Output of `uname -a` or `ver`

Linux pc1 5.4.0-190-generic https://github.com/quarkusio/quarkus/pull/210-Ubuntu SMP Fri Jul 5 17:03:38 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.4" 2024-07-16 LTS OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.14.1

### Additional information

The userinfo endpoint returns a content-type "application/jwt; **charset**=utf-8".
I see in changes a strict test on "application/jwt" (OIDCProvider.java), may be the reason.

**Comment by sberyozkin** [comment]
@airone-x1 Right, it must be it...
