### ISSUE TITLE
Changed order of property resolution in tests

### ISSUE THREAD

**Issue by i-vim** [quarkusio/quarkus#42950]
### Describe the bug

Currently, our tests are driven by mock-services (like wiremock servers) that are managed via `QuarkusTestResourceLifecycleManager`. The managers start the services and place information on how to reach thoses services in properties (returned by `getConfigOverrides`).

Additionally, in order to test app behaviour when those services are down, we override the respective properties and set them to nonsense values, using `TestProfiles`

Starting with 3.14.1, these tests (asserting correct behaviour in the face of failing services) are failing. Seemingly because the order of property resolution has changed

### Expected behavior

Prior to 3.14.1, properties set with `@TestProfile`, won the race and were used in tests. This is what we expect.

Setting properties with Testprofiles should have the highest prio in the resolution chain.

### Actual behavior

Since 3.14.1, we observe that properties set by the LifeCycleManager are used in tests, which render the use of @TestProfile useless for overriding properties.

### How to Reproduce?

Link to repo: https://github.com/i-vim/regressiontest

1. Start the test
2. it will fail because we expect the property to carry the value set by the TestProfile

### Output of `java -version`

21

### Quarkus version or git rev

3.14.1

**Comment by gsmet** [comment]
Thanks for the report. We actually reverted the change here https://github.com/quarkusio/quarkus/pull/42862 and it will be fixed in 3.14.2 that we will release on Wednesday.
