### ISSUE TITLE
Make AssertJ Library in BOM Available Again

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#42960]
### Description

The most basic test setup for Quarkus (using Gradle) could be to include `io.quarkus:quarkus-junit5-mockito` or just `io.quarkus:quarkus-junit5`.

That brings pretty much everything one would need, except the widely used and expressive AssertJ library.

So I would like to poke again and request its inclusion in the BOM :monocle_face:

### Implementation ideas

Just include the library in the BOM

**Comment by x80486** [comment]
By the way, if this is fine, I can send a pull request with the changes.

It looks like it's just a matter of including `assertj-core` in one (or all) of these files: `https://github.com/quarkusio/quarkus/tree/main/test-framework/{common, junit5-component, junit5-internal, junit5}/pom.xml`.

**Comment by scordio** [comment]
See also https://github.com/quarkusio/quarkus/issues/38689#issuecomment-4885543628.
