### ISSUE TITLE
RESTEasy Classic - annotation on abstract jakarta.ws.rs.core.Application class is not ignored

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#42963]
### Describe the bug

RESTEasy Classic - annotation on abstract jakarta.ws.rs.core.Application class is not ignored

https://github.com/quarkusio/quarkus/pull/41465 should ensure abstract jakarta.ws.rs.core.Application classes are ignored

But it's not the case when I put `@ApplicationPath` on it. Path gets unfortunately reflected.
E.g. endpoint is available on http://localhost:8080/rest/hello instead of http://localhost:8080/hello.

### Expected behavior

Annotation on abstract jakarta.ws.rs.core.Application class is ignored

### Actual behavior

annotation on abstract jakarta.ws.rs.core.Application class is NOT ignored

### How to Reproduce?

 - Get app https://code.quarkus.io/?e=resteasy&extension-search=resteasy%20classic
 - add AbstractApplication into the app
 - run `mvn clear verify`
 - alternatively run `mvn quarkus:dev` and access http://localhost:8080/rest/hello and http://localhost:8080/hello

```java
package org.acme;

import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.core.Application;

@ApplicationPath("/rest")
public abstract class AbstractApplication extends Application {
}
```

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus 3.14.1

**Comment by rsvoboda** [comment]
@geoand did https://github.com/quarkusio/quarkus/pull/41465/files to ignore abstract jakarta.ws.rs.core.Application classes. So that's why I assume no annotation on such abstract classes should make any impact to the app.

Quarkus REST ignores `@ApplicationPath` in the same use-cese.

@jamezp what's your view on this?

**Comment by geoand** [comment]
Same for Quarkus

**Comment by jamezp** [comment]
Cool, kind of what I assumed :) So it's likely somewhere in Quarkus it needs to be fixed then.

**Comment by geoand** [comment]
Okay, no I see what the problem is

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/44195 is what I have in mind

**Comment by jamezp** [comment]
@geoand Correct. Any abstract classes are simply ignored. TBH I can't think of a use-case for an abstract application class though.
