### ISSUE TITLE
Display a part of the readme file in the dev-ui default index.html

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#42989]
### Description

The goal is to show info about how to use the generated code.

### Implementation ideas

If readme.md contains `<!-- Generated code info -->`, take the part after it, convert to html and print

**Comment by ia3andy** [comment]
When ready, I will start updating codestart to follow this convention

**Comment by maxandersen** [comment]
had chat with @phillip-kruger and I realized in https://quarkus.io/guides/extension-codestart#index-html that codestarts are actually documented as having way to add *different* things to readme and index.html - and that actually makes sense as readme you can add more verbatim details but in index.html its more like just providing links and pointers.

including readme into index.html isn't the right solution.

I suggest we as part of #42825 add link to open readme file (if it exists) and leave it at that.

**Comment by ia3andy** [comment]
Ok!
