### ISSUE TITLE
Openapi and extended classes

### ISSUE THREAD

**Issue by seseso** [quarkusio/quarkus#4298]
**Describe the bug**
When a resource is created which extends another class, the extended methods are not listed by openapi.

**Expected behavior**
All available methods should be listed by openapi

**Actual behavior**
Only resources from the "primary" class are listed.

**To Reproduce**
1. clone repo https://github.com/seseso/quarkus-openapi
2. run with quarkus:dev
3. access http://localhost:7777/openapi and see that only the /hello endpoint is listed. There should also exists the method /hello/extension, that exists in the extended class.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10 Pro
 - Output of `java -version`: OpenJdk 8
 - GraalVM version (if different from Java): Not used
 - Quarkus version or git rev: 0.22.0

**Comment by kenfinnigan** [comment]
@ewittmann Does MP OpenAPI, or SmallRye, support annotations coming from parent methods?

**Comment by EricWittmann** [comment]
The spec doesn't have an opinion on this one way or the other.  The Smallrye impl does not currently support climbing up the resource class hierarchy, but I think it probably should.

**Comment by kenfinnigan** [comment]
I've opened https://github.com/smallrye/smallrye-open-api/issues/184 for this

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/5571 has fixed this one.
