### ISSUE TITLE
`gu install native-image` instructions are not need anymore

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#42981]
### Describe the bug

I think `gu install native-image` instructions are not need anymore, but we still have this hint in the codebase / facing users.

Mandrel provides `native-image` out of the box and I think it is also included in graalvm-ce-builds, I checked graalvm-community-jdk-21.0.2_macos-aarch64_bin.tar.gz.

```
core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:
   "` in the GRAALVM_HOME, JAVA_HOME and System PATH. Install it using `gu install native-image`.";
docs/src/main/asciidoc/scripting.adoc:
   WARN: Cannot find the `native-image` in the GRAALVM_HOME, JAVA_HOME and System PATH. 
   Install it using `gu install native-image` Attempting to fall back to container build.
```

@zakkak / @galderz / @Karm

**Comment by gsmet** [comment]
It's not causing any harm so while we should improve, I wouldn't qualify it as a bug.
