### ISSUE TITLE
Injection of BrowserContext stopped working on main/999-SNAPSHOT 

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#43034]
### Describe the bug

Injection of `BrowserContext` stopped working on main/999-SNAPSHOT branch but it works on 3.14.2 version

```java

@QuarkusTest
@WithPlaywright
public class EmailTagTest {

    @InjectPlaywright
    BrowserContext context;

    @Test
    void test(){
        assertNotNull(context);
    }

}
```

**Comment by mkouba** [comment]
CC @holly-cummins

**Comment by geoand** [comment]
@gbourant thanks a lot for reporting this issue so early!

Do you have a sample we can try to see the issue in action?

**Comment by geoand** [comment]
FWIW, it seems to be the same as reported [here](https://github.com/quarkusio/quarkus/issues/23612#issuecomment-2330640845)

**Comment by geoand** [comment]
This is definitely related to https://github.com/quarkusio/quarkus/pull/42852, so I'll have a look

**Comment by gbourant** [comment]
> Do you have a sample we can try to see the issue in action?

Yes i will provide a reproducer soon.

> This is definitely related to #42852, so I'll have a look

Yes, it seems that if you just run a single test with the injected BrowserContext it works. (no restarts)

**Comment by geoand** [comment]
> Yes i will provide a reproducer soon.

Actually, you don't have to. Quarkus Super Heroes suffers from the same problem, so I am going to use it to see what's going on

**Comment by gbourant** [comment]
Not prob, it's already done, in case you need it https://github.com/gbourant/qplay

**Comment by geoand** [comment]
🙏🏽

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/43035 fixes the issue

**Comment by gbourant** [comment]
I just tested with your branch and indeed it works as expected.
