### ISSUE TITLE
include sbom feature in LTS

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#43044]
### Description

this feature missed 3.14 codefreeze and we have request from owasp / https://dependencytrack.org/ if could be inlcuded in LTS release.

https://github.com/quarkusio/quarkus/pull/42451/files#diff-cf2d01772577454ecc28d3f98dc173bf451046606bffa781d9f4b1a1fc93d1b3 reads to me as its purely addition; not changing dependency chain /bom and does not affect quarkus unless you add the cyclone extension.

opening this issue to add it for discussion/tracking on lts board

### Implementation ideas

backport https://github.com/quarkusio/quarkus/pull/42451/files

**Comment by gsmet** [comment]
Backport PR is here: https://github.com/quarkusio/quarkus/pull/43139
