### ISSUE TITLE
Optimize the registration of OIDC BackChannel logout routes  

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#43046]
### Description

Currently, OIDC `BackChannelLogoutHandler` is a CDI bean which `@Observes` the `Router` and iterates over all static tenants and registers tenant specific routes for managing back-channel logout callbacks if required.

It should be recorded instead in `OidcRecorder`, similar to have it is done in [the WebAuthn extension](https://github.com/quarkusio/quarkus/blob/main/extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRecorder.java#L35), though I believe we should not deal with prefixes in case of the main router.

### Implementation ideas

`BackChannelLogoutHandler#setup` and `BackChannelLogoutHandler#addRoute` should be gone and re-implemented in the `OIdcRecorder`. `OidcRecorder` iterates over the default and all  other static tenants, so hopefully, all what will be needed, is to check if the current static tenant requires a back-channel logout support and if yes, `router.post` should be done adding `BackChannelLogoutHandler`.

`OidcBuildStep` should use a built item representing the main `Router` to pass `RuntimeValue<Router>` to `OidcRecorder`. I'm assuming it is `VertxWebRouterBuildItem`

**Comment by sberyozkin** [comment]
@AB-xdev FYI, just in case it might of interest for you at some point

**Comment by michalvavrik** [comment]
> It should be recorded instead in OidcRecorder, similar to have it is done in [the WebAuthn extension](https://github.com/quarkusio/quarkus/blob/main/extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRecorder.java#L35), though I believe we should not deal with prefixes in case of the main router.

That cannot be done because that requires to know path during the build time as the current state of things is. 

> OidcBuildStep should use a built item representing the main Router to pass RuntimeValue<Router> to OidcRecorder. I'm assuming it is VertxWebRouterBuildItem

That however, is different thing then what WebAuthn does. I am asking simply because I am curious, it doesn't matter whether this gets to implement or not. But if you don't mind, could you elaborate bit what will be a gain here?

**Comment by michalvavrik** [comment]
Closing as unless I seriously misunderstood this comment https://github.com/quarkusio/quarkus/pull/43295#issuecomment-2435515379, we agreed to not do this.
