### ISSUE TITLE
Multipart mixed boundary on rest-client

### ISSUE THREAD

**Issue by Visserr2** [quarkusio/quarkus#43048]
### Describe the bug
The Content-Type is being overwritten by `application/json` when trying to set content-type via `@ClientHeaderParam`. I'm not sure when this stopped working. 13.3 already had the same issue.

### Expected behavior
Client should use the value defined in `@ClientHeaderParam`. The docs on the website show the following instruction for `Multipart/mixed`:
![{688D2C9E-647A-4E70-8B34-C29C78FB4AD3}](https://github.com/user-attachments/assets/14adac2a-0f92-4dce-96d4-d6842968ceb8)

### Actual behavior
The content-type that is being sent is always `application/json`.

### How to Reproduce?
Using `@ClientHeaderParam` for content-type.
![{DAF18C1E-B845-4B23-9871-85244A0C7155}](https://github.com/user-attachments/assets/95bd1924-1457-4a62-9a65-8c841ff419e6)

### Output of `java -version`
```java
java 21.0.2 2024-01-16 LTS
```

### Quarkus version or git rev
3.14.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```java 
maven
```

**Comment by geoand** [comment]
Can you please attach a sample application that shows the problem in action?

Thanks

**Comment by Visserr2** [comment]
Hi,

It looks like the problem is more nuanced. 
[code-with-quarkus.zip](https://github.com/user-attachments/files/16906092/code-with-quarkus.zip)

I have made two rest-calls with a calculated value for content-type. The first call accepts only one param (a string that is being used by calculated value) that is annotated by @NotBody. The second call is one param with @NotBody and a second string that is being used as body. In the second call the content-type is alway Application/json.

**Comment by geoand** [comment]
I confirm I can see the problem. I'll have a look

**Comment by geoand** [comment]
The problem can be overcome by adding `@Consumes(MediaType.TEXT_PLAIN)` to `callWithOnlyBoundaryAndBodyDoesntWork`

**Comment by geoand** [comment]
The reason you need to do that is because the use of `quarkus-rest-client-jsonb` means that JSON is used as the default media type
