### ISSUE TITLE
Custom annotation not present at runtime

### ISSUE THREAD

**Issue by helpmessage** [quarkusio/quarkus#43080]
### Describe the bug

I have a bean with an intercepted method. On that method, I also have a custom annotation that I want to process on runtime. The problem is that when I try to read that annotation (method.getAnnotation(Documentation.class), it always return null.

My custom annotation is defined as:
```java
  @Target({ElementType.TYPE, ElementType.PARAMETER, ElementType.METHOD})
  @Retention(RetentionPolicy.RUNTIME)
public @interface Documentation {

    String description();

    String[] examples() default {};

}
```

My interceptor annotation is:

```java
@InterceptorBinding 
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD}) 
@Inherited
public @interface Traceable {
    
    @Nonbinding
    TraceTypeParseResult type() default TraceTypeParseResult.DataGuid;
    
    @Nonbinding
    boolean includeParams() default false;
    
    @Nonbinding
    boolean includeParamsIfResultIsNull() default false;
    
    @Nonbinding
    boolean includeService() default true;
    
    @Nonbinding
    boolean includeMethod() default true;
}
```

My method is annotated with:

```java
   @Documentation(description = "Fecth a hierarchy by node Id")
    @Traceable(type = TraceTypeParseResult.DataGuid, includeParamsIfResultIsNull = true)
public ClassNodeDto fetchHierarchyByNodeId(LocalDate versionDate, String schemaName, String rootNodeId, String nodeID) {
```

and at runtime, the `@Documentation` annotation is nowhere to be found.

If I remove the `@Traceable` (interceptor annotation), I can read my `@Documentation` annotation at runtime, which seems to show that quarkus is removing my annotaion. Is there any configuration (or any other way) to keep my annotations untouched at runtime? 

### Output of `uname -a` or `ver`

Linux 6.10.7-061007-generic #202408291638

### Output of `java -version`

17.0.12

### Quarkus version or git rev

3.13.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8

**Comment by manovotn** [comment]
Quarkus isn't removing your annotation.

Interceptor means a subclass will be generated for your bean. From a quick glance it seems like you might be reading the annotation from there instead of the original class?

**Comment by manovotn** [comment]
I did a quick test to verify my above claims and adding `@Inherited` makes the annotation visible.

Overall, this behavior is expected due to proxying/subclassing and it concerns all annotations, not just non-CDI ones.

As a side note, you can determine when a bean has been proxied or subclasses as it will implement either [`io.quarkus.arc.ClientProxy`](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/ClientProxy.java) or [`io.quarkus.arc.Subclass`](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/Subclass.java) interfaces respectively.

**Comment by mkouba** [comment]
> I did a quick test to verify my above claims and adding `@Inherited` makes the annotation visible.

Hm, `@Inherited` should only be reflected on the class level, or?

> As a side note, you can determine when a bean has been proxied or subclasses as it will implement either [`io.quarkus.arc.ClientProxy`](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/ClientProxy.java) or [`io.quarkus.arc.Subclass`](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/Subclass.java) interfaces respectively.

Yes, in both cases you can query the `java.lang.Class.getSuperclass()` for annotations.

**Comment by manovotn** [comment]
> Hm, @Inherited should only be reflected on the class level, or?

Oh, I didn't realize the issue is about method-level annotations :man_facepalming:  
You're right OFC, my test was with class-level annotations :)

**Comment by Ladicek** [comment]
@helpmessage You don't really show how you're trying to obtain the annotation, but I assume @manovotn is correct -- you inject an instance of the intercepted class, call `getClass()`, then call `getMethod()` or `getDeclaredMethod()`, and then call `getAnnotation()`. If that's so, then what @manovotn and @mkouba suggest is the correct way -- check if the object is `instanceof ClientProxy` or `instanceof Subclass` and if so, use `getSuperclass()` before calling `get[Declared]Method()`.
