### ISSUE TITLE
Documentation generation for configuration properties in OIDC module leaves out plenty of information

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#43109]
### Describe the bug

I go to https://quarkus.io/version/main/guides/all-config or https://quarkus.io/guides/all-config and type `quarkus.oidc.credentials`. Literally no credential properties have documentation. However if I go to Java config class, I can see there is nice Javadoc:

- https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcClientCommonConfig.java#L52
- https://github.com/quarkusio/quarkus/blob/613cdf3670f2ef234c93805e5a8aacb5f09f20d0/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcClientCommonConfig.java#L136

Try it also for `quarkus.oidc.tls` and `quarkus.oidc-client.tls` and so on. Same problem.

### Expected behavior

Users can read what are properties for.

### Actual behavior

Users don't see documentation.

### How to Reproduce?

Write `quarkus.oidc` in the all config page and find many other OIDC properties without docs.

**Comment by gsmet** [comment]
Hmmm. This should have been fixed recently. And I have seen them popping up. 

I’ll have a closer look at what’s going on.

**Comment by michalvavrik** [comment]
Yeah, I didn't mention https://github.com/quarkusio/quarkus/issues/42815 before you mentioned recent fixes. Ok, I only used what is already deployed.

**Comment by gsmet** [comment]
Yeah https://github.com/quarkusio/quarkus/pull/42835 should have fixed it and I really saw these config properties pop up so there's something odd.

**Comment by gsmet** [comment]
And they indeed appeared here: https://github.com/quarkusio/quarkusio.github.io/commit/bf3ea8cc182496270c84af2f191ccaee596d5773#diff-a86dd8f41ab52d1dbb7e16ffa55570b722c72b6ba4a2ef6ed1e31d66a1b1137e

**Comment by gsmet** [comment]
And they disappeared the next day: https://github.com/quarkusio/quarkusio.github.io/commit/7ed3ff6a02f644c429a7f8db39bc71828d04de37

**Comment by gsmet** [comment]
Ah I see in the 3.14.2, they are around but don't have javadoc. So there might be an issue with how the javadoc is resolved, it's a different process.

**Comment by gsmet** [comment]
OK, so the first fix actually made them appear in the model but there's a problem with the Javadoc collection (which is done separately) and the Javadoc for the config group is not around thus the problem.

Need to go do some cooking for now but will have a look after, it will be a simple fix hopefully.

**Comment by michalvavrik** [comment]
Thank you @gsmet

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/43115 will take care of it.

So the first issue was that the properties weren't present in the model, this is what the previous patch fixed (and I actually checked they were in the model, thus why I was surprised).
The model is built where the `@ConfigRoot` is and can resolve ``@ConfigGroup``s that are in a dependency.

But the Javadoc cannot be accessed from another module so it's actually collected locally (and then later aggregated).

There was another issue: the OIDC Common artifact wasn't configured for legacy config roots (I looked for `@ConfigRoot` everywhere but this artifact is specific as you only have a `@ConfigGroup` and no `@ConfigRoot`).

So it was looking for methods and not fields and thus didn't collect the Javadoc.

**Comment by gsmet** [comment]
From what I can see the doc appeared for main. So things should be OK once back ported.

**Comment by michalvavrik** [comment]
> From what I can see the doc appeared for main. So things should be OK once back ported.

Absolutely. I was collecting certs related OIDC properties on main and didn't realize I was reading previously missing docs until I read your message :-D Thanks for the fix!
