### ISSUE TITLE
The class CertificateReloadedEvent missing

### ISSUE THREAD

**Issue by amusarra** [quarkusio/quarkus#43135]
### Describe the bug

The documentation [7. Reloading certificates](https://quarkus.io/guides/tls-registry-reference#reloading-certificates) reports the CertificateReloadedEvent class in the code example, but this class apparently does not exist. The code reported in the documentation consequently does not compile.

Could you also report the complete code to reload the certificates successfully? The code block also refers to `server.updateSSLOptions(event.tlsConfiguration().getSSLOptions());` but how do you get the server object?

```java
@Inject
TlsConfigurationRegistry registry;

public void reload() {
    TlsConfiguration config = registry.get("name").orElseThrow();
    if (config.reload()) {
        event.fire(new CertificateReloadedEvent("name", config));
    }
}

// In the server or client code
public void onReload(@Observes CertificateReloadedEvent event) {
    if ("name".equals(event.getName())) {
        server.updateSSLOptions(event.tlsConfiguration().getSSLOptions());
        // Or update the SSLContext.
    }
}
```
Snippet from [7. Reloading certificates](https://quarkus.io/guides/tls-registry-reference#reloading-certificates)

Could you update the documentation to provide a correct example?

### Expected behavior

I expect the code in the documentation to work.

### Actual behavior

The code in the documentation does not work.

### Output of `uname -a` or `ver`

Darwin amusarra-macbook-pro.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

java 21.0.2 2024-01-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)

### Quarkus version or git rev

3.14.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

**Comment by cescoffier** [comment]
Great catch, the class should be `CertificateUpdatedEvent`.

**Comment by amusarra** [comment]
Yes @cescoffier, thank you. Exploring the code, I then saw that the class is called `CertificateUpdatedEvent`.

My need is to load a PEM bundle of CA certificates. I tried to implement what is indicated in the documentation but it seems not to work correctly. Below is the piece of code I wrote.

```java
@ApplicationScoped
public class GovCertificateUpdater {

  @ConfigProperty(name = "gov.trust.certs.url")
  String certsUrl;

  @Inject
  Logger log;

  @Inject
  GovCertParser certParser;

  @Inject
  Event<CertificateUpdatedEvent> certificateUpdatedEvent;

  @Inject
  TlsConfigurationRegistry tlsConfigurationRegistry;

  public void reload() {
    TlsConfiguration tlsConfiguration = tlsConfigurationRegistry.get("https").orElseThrow();

    try {
      // Path to the PEM file containing all CA certificates
      String pathGovBundlePemTrustStore = certParser.getOutputPathPemBundle() + File.separator +
                                          certParser.getOutputPemBundleFileName();

      Path caCertsPath = Path.of(pathGovBundlePemTrustStore);

      // Load the CA certificates
      CertificateFactory certFactory = CertificateFactory.getInstance("X.509");
      try (var certStream = Files.newInputStream(caCertsPath)) {
        var certs = certFactory.generateCertificates(certStream);
        for (var cert : certs) {
          X509Certificate caCert = (X509Certificate) cert;

          tlsConfiguration.getTrustStore()
              .setCertificateEntry(caCert.getSubjectX500Principal().getName(), caCert);
          
          log.info("Loaded CA certificate: " + caCert.getSubjectX500Principal().getName());
        }
      }

      // Reload the TLS configuration to apply the changes
      if (tlsConfiguration.reload()) {
        log.info("TLS configuration reloaded to apply new CA certificates");

        certificateUpdatedEvent.fire(new CertificateUpdatedEvent("https", tlsConfiguration));
      } else {
        log.error("Failed to reload TLS configuration");
      }

    } catch (Exception e) {
      log.error("Failed to load additional CA certificates", e);
    }
  }

  @Scheduled(every = "2h")
  public void updateCertificates() {
    // Download bundle PEM certs
    ....

    // reload the certificates
    reload();
  }
}
```
Code example that loads/updates CA certificates

In the log I see the following entry which seems to indicate that the update was successful.

```
2024-09-09 15:05:33,004 INFO  [io.qua.ver.htt.run.HttpCertificateUpdateEventListener] (vert.x-eventloop-thread-3) The TLS configuration `https` used by the HTTP server `http server` has been updated
2024-09-09 15:05:33,004 INFO  [io.qua.ver.htt.run.HttpCertificateUpdateEventListener] (vert.x-eventloop-thread-3) The TLS configuration `https` used by the HTTP server `http server` has been updated
```
Log

When I go to check via the OpenSSL command (`openssl s_client -connect localhost:8443 -showcerts`), I see only one CA and not the others.

```
---
Server certificate
subject=C=IT, ST=Catania, L=Bronte, O=Dontesta, OU=IT Labs, CN=rd.quarkus.dontesta.it
issuer=C=IT, ST=Catania, L=Bronte, O=Dontesta, OU=IT Labs, CN=Dontesta CA
---
Acceptable client certificate CA names
C=IT, ST=Catania, L=Bronte, O=Dontesta, OU=IT Labs, CN=Dontesta CA
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA1:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1758 bytes and written 409 bytes
Verification error: unable to verify the first certificate
---
```

**Comment by cescoffier** [comment]
The reload will reload from the file system, thus your change:

```
 tlsConfiguration.getTrustStore()
              .setCertificateEntry(caCert.getSubjectX500Principal().getName(), caCert);
```

is likely going to be overridden by the reload from the file system.

**Comment by cescoffier** [comment]
Yes, because `reload()` reloads the content from the file system.

**Comment by amusarra** [comment]
@cescoffier what file system is it loading from? Is there any specific property like this `quarkus.tls.https.trust-store.pem.certs` ?

The problem is that I generate the PEM bundle file after the application has started, so I assumed that the tlsConfiguration.getTrustStore().setCertificateEntry() API worked.

If I set the property `quarkus.tls.https.trust-store.pem.certs` with the values `certs/ca_cert.pem,/tmp/tsl-it/tsl-it_bundle.pem` certificates are loaded correctly at application startup **but only if the files exist**.

Unfortunately the bundle file is not available at application startup because it is generated later, which is why I wrote the code to load the CAs later, and I was sure it worked even reading the documentation.

**Comment by cescoffier** [comment]
Try to call reload and then set the truststore (before firing the event).

**Comment by cescoffier** [comment]
otherwise, write the content of the expect place on the file system.

**Comment by amusarra** [comment]
@cescoffier even now that the tls configuration has all the other certificates loaded from the PEM bundle and on the log I see the message 

"2024-09-09 16:36:31,352 INFO [io.qua.ver.htt.run.HttpCertificateUpdateEventListener] (vert.x-eventloop-thread-3) The TLS configuration `https` used by the HTTP server `http server` has been updated" 

it actually does not load it on the HTTP server, this in my opinion is a bug.

![image](https://github.com/user-attachments/assets/80b0b41d-630f-437e-b5cb-d3a08032080b)

**Comment by cescoffier** [comment]
It does load the certificate - but ignore your changes.

**Comment by cescoffier** [comment]
By the way, since the issue is closed ( I fixed the documentation issue), please open a new issue and attach a reproducer.

As said, it reloads from the file system, so it must be written there; otherwise, it will not see your change.

**Comment by amusarra** [comment]
OK, I'll do as you wrote to open another issue.

Last thing. So, how can I implement the scenario I showed? Could you indicate a complete example in the documentation?

I think my scenario is clear, that is, the possibility of loading one or more certificates after the application has started without the path of these having been previously set on the application.

Many thanks.
