### ISSUE TITLE
Define and create platform bound extensions.json 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#4313]
Currently extension.json is in a core module (`devtools/common`) - this is read and parsed by maven/gradle/etc. tooling to provide extension selection/queriying etc. 

Going forward this needs to be separated and be linked to the platform rather than core.

**Comment by aloubyansky** [comment]
I'm closing this one, as such as file was already generated in 0.25.0. And is going to be generated the same way for the universe.

**Comment by maxandersen** [comment]
btw. sholdn't we remove the extension.json at some point in core ? its going to be a cause of confusion at some point if still need to be maintained?

**Comment by aloubyansky** [comment]
Yes, it's officially deprecated. Let's keep for the upcoming release at least though.
