### ISSUE TITLE
`  quarkus.configuration.build-time-mismatch-at-runtime` should be in the `quarkus.config` namespace

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#43149]
We have several `quarkus.config.*` properties in the tree and we have `quarkus.configuration.build-time-mismatch-at-runtime` that is in a separate config root.

It should be moved to the `quarkus.config` root.
I'm not sure it's worth deprecating it properly as it seems very technical and probably not something people would widely use?

/cc @radcortez for advice.

**Comment by radcortez** [comment]
I agree. We can move it to `quarkus.config`.
