### ISSUE TITLE
Quarkus 3.11.0: quarkus-junit5 depends on javax.json.bind.Jsonb

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#43153]
### Describe the bug

In a simple Quarkus REST service I get the following exception:

    Caused by: java.lang.ClassNotFoundException: javax.json.bind.Jsonb
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:476)

### Expected behavior

I expect that the class `jakarta.json.bind.Jsonb` be referenced, not `javax.json.bind.Jsonb`.

### Actual behavior

Here attached is the dependency tree. It shows that `quarkus-junit5` includes `rest-assured` 5.4.0, which `JsobObjectMapperFactory` class imports `javax.json.bind.Jsonb`, as shown below;

    package io.restassured.path.json.mapper.factory;

    import io.restassured.common.mapper.factory.ObjectMapperFactory;
    import javax.json.bind.Jsonb;

    public interface JsonbObjectMapperFactory extends ObjectMapperFactory<Jsonb> {
    } 

[deps.txt](https://github.com/user-attachments/files/16933438/deps.txt)

### How to Reproduce?

No reproducer

### Output of `uname -a` or `ver`

Linux nicolas-XPS-15-9570 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /opt/apache-maven-3.9.5 Java version: 21.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21-oracle-x64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.8.0-41-generic", arch: "amd64", family: "unix"

### Additional information

N/A

**Comment by gsmet** [comment]
This is a REST Assured limitation: they don't have support for Jakarta EE 10+. There's not much we can do here (and also one of the reasons why we recommend using Jackson).

See https://github.com/rest-assured/rest-assured/issues/1651 .

Also my understanding is that REST Assured is not a dependency of `quarkus-junit5`.

**Comment by jmini** [comment]
See https://github.com/quarkusio/quarkus/issues/29225
