### ISSUE TITLE
Redis client list command returns empty name ("name=") when i set @RedisClientName

### ISSUE THREAD

**Issue by balfarkas** [quarkusio/quarkus#43167]
### Describe the bug

When i set @RedisClientName as described in https://quarkus.io/guides/redis-reference#default-and-named-clients, the Redis client list command returns empty client name.
```
@ApplicationScoped
class TestService {

   @Inject 
   @RedisClientName("client1")
   RedisDataSource redisDataSource;

   String getKeys() {
   KeyCommands<String> keyCommands=redisDataSource.key();
       return keyCommands.keys("*").toString();
    }

}
```

Redis client-list output:
```
127.0.0.1:6379> client list
id=11722 addr=127.0.0.1:40822 laddr=127.0.0.1:6379 fd=8 name=console age=6261 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=26 qbuf-free=20448 argv-mem=10 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22298 events=r cmd=client|list user=default redir=-1 resp=2
id=14225 addr=10.244.0.1:27440 laddr=10.244.4.29:6379 fd=9 name= age=4 idle=2 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22272 events=r cmd=keys user=default redir=-1 resp=3
``` 

### Expected behavior

Redis client list command returns the client name (id=14225):
```
127.0.0.1:6379> client list
id=11722 addr=127.0.0.1:40822 laddr=127.0.0.1:6379 fd=8 name=console age=6261 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=26 qbuf-free=20448 argv-mem=10 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22298 events=r cmd=client|list user=default redir=-1 resp=2
id=14225 addr=10.244.0.1:27440 laddr=10.244.4.29:6379 fd=9 name=client1 age=4 idle=2 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22272 events=r cmd=keys user=default redir=-1 resp=3
```

### Actual behavior

Redis client list command returns empty client name:
```
127.0.0.1:6379> client list
id=11722 addr=127.0.0.1:40822 laddr=127.0.0.1:6379 fd=8 name=console age=6261 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=26 qbuf-free=20448 argv-mem=10 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22298 events=r cmd=client|list user=default redir=-1 resp=2
id=14225 addr=10.244.0.1:27440 laddr=10.244.4.29:6379 fd=9 name= age=4 idle=2 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22272 events=r cmd=keys user=default redir=-1 resp=3
```

### How to Reproduce?

1) Execute the redis-test simple project ([redis-test.zip](https://github.com/user-attachments/files/16942649/redis-test.zip))
2) Configure running redis-host in application.properties
3) Call curl http://localhost:8080/test
4) Execute redis client-list command

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### Quarkus version or git rev

3.2.12.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Maven home: C:\tools\apache-maven-3.8.8 Java version: 17, vendor: Oracle Corporation, runtime: C:\tools\openjdk-17+35_windows-x64_bin\jdk-17 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Ladicek** [comment]
I don't think we ever call `CLIENT SETNAME`, so this happens even for the default ("unnamed") Redis client. I'm also fairly sure this is not documented anywhere as a feature. Removing `kind/bug`, this is a feature request really.

**Comment by cescoffier** [comment]
As @Ladicek said, the name is just to find the proper configuration. We do not use that name for any other purpose.

**Comment by mcruzdev** [comment]
I would like to contribute with this one, doing some research I think we need to change `vertx-redis-client` first.
