### ISSUE TITLE
curate extensions in core

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#4316]
would want to identify which plugins we from quarkus community 
consider maintained (by who?), GA/alpha/beta? and/or makes sense to externalise rather than have in the core repo

**Comment by maxandersen** [comment]
@paulrobinson once you think the spreadsheet is fairly decent report back and we'll use that for this.

**Comment by paulrobinson** [comment]
@maxandersen will do. I'll be chasing people today.

**Comment by paulrobinson** [comment]
@emmanuelbernard, @maxandersen: Are we still planning to label (e.g. alpha, beta, etc) extensions for 1.0.0? If so, we will need an algorithm to determine this. I would suggest something that can be codified into the spreadsheet using the responses from the extension maintainers.

**Comment by paulrobinson** [comment]
@maxandersen  We are now down to 10 extensions that still need review. When do you need the final list?

**Comment by maxandersen** [comment]
@paulrobinson yesterday ? :) realistically I wouldn't be ready to do the updates in metadata before monday/tuesday.

**Comment by maxandersen** [comment]
included in fix for https://github.com/quarkusio/quarkus/issues/4771
