### ISSUE TITLE
Have `HttpClientMetricsTagsContributor` in addition to `HttpServerMetricsTagsContributor`

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#43178]
### Description

As per discussion in https://github.com/quarkusio/quarkus/issues/42800 it would be nice to have `HttpClientMetricsTagsContributor` in addition to `HttpServerMetricsTagsContributor`.

**Comment by geoand** [comment]
@ppalaga is this something Camel needs?

**Comment by ppalaga** [comment]
> @ppalaga is this something Camel needs?

No, but we may leverage it in Quarkus CXF.

**Comment by geoand** [comment]
Understood, thanks
