### ISSUE TITLE
Generate extensions.json based on `quarkus-extension.properties`

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#4317]
Once we have #833 and all extensions own its own default metadata we should generate `extensions.json` based on the properties. 

There seem to exist https://github.com/quarkusio/quarkus/pull/663 that does something similar - need to check if we can just use that or not.

**Comment by kenfinnigan** [comment]
Why generate a file from a file?

For Thorntail we had the metadata for an extension in the `pom.xml` for that extension, and then we generated a file with all that information

**Comment by maxandersen** [comment]
that is what is proposed here - each extension add the metadata into the pom.xml where a plugin generates quarkus-extension.properties with the values.

That is then picked up to generate the extensions.json which will be used by the platform which  mvn/gradle/cli and code.quarkus.io will use. Later one we'll have to have some kind of registry that provide an api to look these up for things in broader ecosystem.

This allows extension owners to "own" the initial metadata and reduces the need for maintanence. 

make sense now @kenfinnigan  ?

**Comment by maxandersen** [comment]
and this is similar to what https://github.com/quarkusio/quarkus/pull/663 does afaics - thus wondering what happened to that ;)

**Comment by kenfinnigan** [comment]
#663 I think is still there, but it's not getting information from anywhere at present, so it just generates a skeleton.

I guess I'm wondering why pom.xml -> quarkus-extension.properties -> extensions.json and why not skip the middle man?

**Comment by maxandersen** [comment]
because when you access a jar you don't necessarily have the pom.xml. Some artifact in the extension is where you would have this. And what if you use gradle or gawd forbid manually wrote that file :)

Idea is that quarkus-extension.properties becomes the place to declare the metadata used for registries/platforms. extension.json is just our current mechanism to "aggregate" it if that makes sense ?

**Comment by maxandersen** [comment]
the difference from #663 (unless I misread it) is that we don't have all the extensions in the same reactor/pom.xml to go generate from or am I missing your point ? :)

**Comment by kenfinnigan** [comment]
The original plan with the extension generator piece I wrote is that it runs as part of the build, so, therefore, has access to all the pom.xml content.

Is that no longer the case?

**Comment by kenfinnigan** [comment]
So `extension.json` is now the aggregated version?

Why not have our one, and then each extension from outside our repo generates it's own into the artifact, and we just "collate" them?

**Comment by maxandersen** [comment]
Today quarkus-camel is not part of the overall build. In future (post 1.0) we expect more and more to be outside core quarkus build.

So no -:)

**Comment by maxandersen** [comment]
> So `extension.json` is now the aggregated version?

extension.json as it is in core would stop to exist.  It would be part of the quarkus-platform.

> Why not have our one, and then each extension from outside our repo generates it's own into the artifact, and we just "collate" them?

using quarkus-extension.properties is the thing we would collate. 

Maybe I'm missing some magic feature of extension.jsorn but why would we not just have all extensions declare the initial metadata the same way ? 

There is another issue on being able to augment the "collated" result to remove and do additional classification of extensions.

**Comment by emmanuelbernard** [comment]
Let me give you my perspective. we need a file I will call `foos` that:

- list the extensions available in the platform
- foos is specific per Quarkus Platform version
- foos-platform-version-n and foos-platform-version-m will likely have extensions in common ; corollary, one extension at one given version will live in several foos.
- let's not force an extension to re-release to update information on the foos it is targeting
- foos must be able to override metadata information around the extensions:
    - labels
    - whether a technical extension or not
    - the category (we might disagree with the categorization of an extension author)
    - beta / recommended etc status (could all be labels I don't know but probably a different thing)
- foos might contains the order of categories used by code.quarkus.io and CLI and VSCode

Therefore foos cannot be 100% derived from the `quarkus-extension.properties`

CC @maxandersen

**Comment by maxandersen** [comment]
This issue is about having quarkus-extension.properties actually added to extensions we have and then feed into extensions.json generation - for overriding/customization we have https://github.com/quarkusio/quarkus/issues/4320

Lets say what you call `foos` is 'a platform description` and currently the idea for that to be very similar to `extensions.json`

> * list the extensions available in the platform

Yes - and that list is made by having a BOM (platform-bom) which we then iterate for extensions to generate the inittial content for extensions.json.

> * foos is specific per Quarkus Platform version

Yes - the generation is tied to release of platform-bom. https://github.com/quarkusio/quarkus/issues/4313

> * foos-platform-version-n and foos-platform-version-m will likely have extensions in common ; corollary, one extension at one given version will live in several foos.

Yes - that’s why in various issues and doc we talk about the tooling cannot assume a hardcoded platform. Must be possible to use a specific one and fall back on a default lookup mechanism.

> * let's not force an extension to re-release to update information on the foos it is targeting

I agree. Can you give an example of what you would want to override in the platform description about an extension ? 

> * foos must be able to override metadata information around the extensions:

Same as above ^^ 

>   * labels

what does that mean ? that besides labels put by extension writer the platform should be able to override them or ? 

>   * whether a technical extension or not

would this just be a boolean and then users can in `listExtensions` ask to have the flag ignored ? 
do we have that today btw ? was wondering which extensions are today considered technical.

>   * the category (we might disagree with the categorization of an extension author)

yes, for now idea is to just make it so in the platform we can override each individual property so we would ignore or accept whats in the extension. post 1.0 we can make it more fine grained if need by.

>   * beta / recommended etc status (could all be labels I don't know but probably a different thing)

personally I would have preferred the version string of the extension would indicate wether beta or not but as long as we force same version on extensions it could make sense to have a "quality" rating on it.

recommended I would assume is done by merely being in the platform or not ? 

> * foos might contains the order of categories used by code.quarkus.io and CLI and VSCode

Can you elaborate "the order of categories" ? you mean the platform description should have a field to sort the categories when presented ?

**Comment by emmanuelbernard** [comment]
> This issue is about having quarkus-extension.properties actually added to extensions we have and then feed into extensions.json generation - for overriding/customization we have #4320

My bad, should I copy my message there then?
I got caught off guard because you asked Guillaume about `_data/extensions.json` and its relation to this issue.

> 
> Lets say what you call `foos` is `a platform description` and currently the idea for that to be very similar to `extensions.json`
> 
> > * list the extensions available in the platform
> 
> Yes - and that list is made by having a BOM (platform-bom) which we then iterate for extensions to generate the inittial content for extensions.json.
> 
> > * foos is specific per Quarkus Platform version
> 
> Yes - the generation is tied to release of platform-bom. #4313
> 
> > * foos-platform-version-n and foos-platform-version-m will likely have extensions in common ; corollary, one extension at one given version will live in several foos.
> 
> Yes - that’s why in various issues and doc we talk about the tooling cannot assume a hardcoded platform. Must be possible to use a specific one and fall back on a default lookup mechanism.

Right but I was going at it from the other side. Whatever metadata you put in a given extension release cannot assume which platform it will join and in which capacity (beta, stable, recommended etc)

> 
> > * let's not force an extension to re-release to update information on the foos it is targeting
> 
> I agree. Can you give an example of what you would want to override in the platform description about an extension ?

The list is below.

> 
> > * foos must be able to override metadata information around the extensions:
> 
> Same as above ^^

well the list is below :)

> 
> > * labels
> 
> what does that mean ? that besides labels put by extension writer the platform should be able to override them or ?

Yes to avoid label squatting.

> 
> > * whether a technical extension or not
> 
> would this just be a boolean and then users can in `listExtensions` ask to have the flag ignored ?
> do we have that today btw ? was wondering which extensions are today considered technical.

We don't have a boolean, some extensions are not listed in `_data/extensions.json`. For example

- caffeine
- elasticsearch rest client
- netty
- ...

these are used by other extensions.


> 
> > * the category (we might disagree with the categorization of an extension author)
> 
> yes, for now idea is to just make it so in the platform we can override each individual property so we would ignore or accept whats in the extension. post 1.0 we can make it more fine grained if need by.
> 
> > * beta / recommended etc status (could all be labels I don't know but probably a different thing)
> 
> personally I would have preferred the version string of the extension would indicate wether beta or not but as long as we force same version on extensions it could make sense to have a "quality" rating on it.

I am open to it on the beta one.
For the qualifier related to recommended / community etc, I think we should be able to override.

> 
> recommended I would assume is done by merely being in the platform or not ?

Well there are several levels:

- recommended as in we will guarantee that you have the same version and run well for the platform release (smoke tests and all)
- community as in provided and maintained by the community but no strong guaranteed for it to work with the rest.
- (optional but I don't like it too much) maintained by the "team" (whatever that means) and probably has a longer shelf life as part of the platform a priori

> 
> > * foos might contains the order of categories used by code.quarkus.io and CLI and VSCode
> 
> Can you elaborate "the order of categories" ? you mean the platform description should have a field to sort the categories when presented ?

in https://code.quarkus.io/, you can see that the order is Core, Web, Data etc

**Comment by maxandersen** [comment]
> My bad, should I copy my message there then?

no its fine - we'lll clean it up/duplicate as needed. 

> Right but I was going at it from the other side. Whatever metadata you put in a given extension release cannot assume which platform it will join and in which capacity (beta, stable, recommended etc)

Yes - fully agree when including extension into a platform we need a mechanism to override values. But still think it make sense the extension itself can express its own defaults.


> Well there are several levels:
> 
> * recommended as in we will guarantee that you have the same version and run well for the platform release (smoke tests and all)
> * community as in provided and maintained by the community but no strong guaranteed for it to work with the rest.
> * (optional but I don't like it too much) maintained by the "team" (whatever that means) and probably has a longer shelf life as part of the platform a priori

So I think might be talking about different aspects of platforms here. i.e. I'm talking about "THE Platform" we'll publish and maintain to start with - I sense you are talking about the notion of the "Whole possible set of extensions".

Within a platform I think it makes sense to say all  within it is assumed to work together. For v1 there was an earlier agreement that we would focus on just having that one supported platform published/exposed.

The "whole possible set of extensions" with various qualifiers on wether its supported by one or the other team/individual/company etc. we've for now just talked about being doable by making another platform, lets call it "everything-quarkus-platform" which is a full list of any extension. 

Then you point the tools to what platform you want to explore - the quarkus-platform or everything-quarkus-platform, etc. Then the tools work within that platform.

I think that post v1.0 code.quarkus.io would need to grok multiple platforms and allow to reconfigure its list of options based on what platforms the user wants to look at OR we decided to add a more dynamic registry to code.quarkus.io that is not based on the notion of a platform.

**Comment by emmanuelbernard** [comment]
On 3 Oct 2019, at 22:56, Max Rydahl Andersen wrote:

> > My bad, should I copy my message there then?
>
> no its fine - we'lll clean it up/duplicate as needed.
>
>> Right but I was going at it from the other side. Whatever metadata 
>> you put in a given extension release cannot assume which platform it 
>> will join and in which capacity (beta, stable, recommended etc)
>
> Yes - fully agree when including extension into a platform we need a 
> mechanism to override values. But still think it make sense the 
> extension itself can express its own defaults.
>
>
>> Well there are several levels:
>>
>> * recommended as in we will guarantee that you have the same version 
>> and run well for the platform release (smoke tests and all)
>> * community as in provided and maintained by the community but no 
>> strong guaranteed for it to work with the rest.
>> * (optional but I don't like it too much) maintained by the "team" 
>> (whatever that means) and probably has a longer shelf life as part of 
>> the platform a priori
>
> So I think might be talking about different aspects of platforms here. 
> i.e. I'm talking about "THE Platform" we'll publish and maintain to 
> start with - I sense you are talking about the notion of the "Whole 
> possible set of extensions".
>
> Within a platform I think it makes sense to say all  within it is 
> assumed to work together. For v1 there was an earlier agreement that 
> we would focus on just having that one supported platform 
> published/exposed.
>
> The "whole possible set of extensions" with various qualifiers on 
> wether its supported by one or the other team/individual/company etc. 
> we've for now just talked about being doable by making another 
> platform, lets call it "everything-quarkus-platform" which is a full 
> list of any extension.
>
> Then you point the tools to what platform you want to explore - the 
> quarkus-platform or everything-quarkus-platform, etc. Then the tools 
> work within that platform.
>
> I think that post v1.0 code.quarkus.io would need to grok multiple 
> platforms and allow to reconfigure its list of options based on what 
> platforms the user wants to look at OR we decided to add a more 
> dynamic registry to code.quarkus.io that is not based on the notion of 
> a platform.
>

Good plan to layer these over time.
