### ISSUE TITLE
RoutingContext request do not provides X-Forwarded-Prefix header

### ISSUE THREAD

**Issue by demeureg** [quarkusio/quarkus#43183]
### Describe the bug

Hello, 

as we use quarkus-cxf for our SOAP webservice, header `X-Forwarded-Prefix` is not provided by [CxfHandler](https://github.com/quarkiverse/quarkus-cxf/blob/main/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/transport/CxfHandler.java).

Regards, 

Guillaume Demeure

### Expected behavior

If `X-Forwarded-Prefix` header is present, it should be provided to the handler and replace the context path.

### Actual behavior

Header `X-Forwarded-Prefix` is always null.

### How to Reproduce?

1. Start the application running SOAP service
2. From terminal, run: 
`curl -H 'X-Forwarded-Port: 443' -H 'X-Forwarded-Host: bla' 'X-Forwarded-Prefix: /proxy' -H 'X-Forwarded-Proto: https' 'http://localhost:8080/services/wifi?wsdl'`
3. At the bottom of your terminal, you should see: 
```
...
  <wsdl:service name="WifiWSImpl">
    <wsdl:port binding="tns:WifiWSImplSoapBinding" name="WifiWSPort">
      <soap:address location="https://bla:443/services/wifi"/>
    </wsdl:port>
  </wsdl:service>
...
```
4. From a debug step into the [CxfHandler](https://github.com/quarkiverse/quarkus-cxf/blob/628fcf90ba0f212e3a46f3ad60a5626a19bac6ac/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/transport/CxfHandler.java#L206), the list of headers names do not contains `X-Forwarded-Prefix`: 
<img width="423" alt="image" src="https://github.com/user-attachments/assets/a4760ce8-f761-4465-9527-d6680e3cfdae">

### Output of `uname -a` or `ver`

Darwin mbp-de-gdemeure.home 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30) OpenJDK 64-Bit Server VM GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30, mixed mode, sharing)

### Quarkus version or git rev

3.8.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /Users/g.demeure/.m2/wrapper/dists/apache-maven-3.9.5/2021cb71 Java version: 21.0.2, vendor: GraalVM Community, runtime: /Users/g.demeure/.sdkman/candidates/java/21.0.2-graalce Default locale: fr_FR, platform encoding: UTF-8 OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"

**Comment by demeureg** [comment]
Hello, 

sorry is the explaination was not clear. I have put some debug step into the [CxfHandler class](https://github.com/quarkiverse/quarkus-cxf/blob/main/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/transport/CxfHandler.java). The header `X-Forwarded-Prefix` sent by curl to my quarkus application is not provided to the CxfHandler, and so [the variable `originalPrefix` is always null.](https://github.com/quarkiverse/quarkus-cxf/blob/53923a365646039b0be2cad07eb975ef571bfc95/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/transport/CxfHandler.java#L212)

**Comment by ppalaga** [comment]
@demeureg thanks for the report! It is really a Quarkus CXF bug, could you please file an issue there?

**Comment by demeureg** [comment]
> @demeureg thanks for the report! It is really a Quarkus CXF bug, could you please file an issue there?

You're welcome, I have updated the original with the steps to reproduce the bug. I'll create an issue into quarkus-cxf for the tracking.

**Comment by ppalaga** [comment]
The code handling the headers was indeed a bit broken. I am cleaning it and adding some tests. 

Anyway, I'd say that your use case should actually work as of Quarkus Platform 3.14.2, if you set `quarkus.http.proxy.enable-forwarded-prefix = true` see also https://docs.quarkiverse.io/quarkus-cxf/dev/user-guide/advanced-service-topics/running-behind-a-reverse-proxy.html
