### ISSUE TITLE
Pulsar devservice is not starting on RHEL 8 aarch64

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#43187]
### Describe the bug

Pulsar devservice is not starting on RHEL 8 aarch64

Checked through Quarkus Quickstarts by running `mvn clean verify -pl 'pulsar-quickstart/pulsar-quickstart-producer'`

I was able to capture some logs from the container / devservice initialization procedure through `docker ps -a | grep pulsar` and `docker container logs $CONTAINER_ID --follow`.

Here is the log: [pulsar.txt](https://github.com/user-attachments/files/16946424/pulsar.txt)

The main failure is at the end of file
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffffae613ef8, pid=10, tid=270
#
# JRE version: OpenJDK Runtime Environment Corretto-21.0.4.7.1 (21.0.4+7) (build 21.0.4+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-21.0.4.7.1 (21.0.4+7-LTS, mixed mode, tiered, compressed class ptrs, z gc, linux-aarch64)
```

Seems the container is using internally Corretto JDK and it face some issues on RHEL 8.10 machine

### Expected behavior

Pulsar devservice starts well on RHEL 8 aarch64

### Actual behavior

Pulsar devservice is not starting on RHEL 8 aarch64

### How to Reproduce?

 - get Quarkus Quickstarts https://github.com/quarkusio/quarkus-quickstarts
 - run `mvn clean verify -pl 'pulsar-quickstart/pulsar-quickstart-producer'`

### Output of `uname -a` or `ver`

RHEL 8.10 aarch64 - 4.18.0-513.5.1.el8_9.aarch64 #1 SMP Fri Sep 29 05:50:39 EDT 2023 aarch64 aarch64 aarch64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.4" 2024-07-16 LTS OpenJDK Runtime Environment (Red_Hat-21.0.4.0.7-1) (build 21.0.4+7-LTS) OpenJDK 64-Bit Server VM (Red_Hat-21.0.4.0.7-1) (build 21.0.4+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

Quarkus 3.14.2

**Comment by geoand** [comment]
cc @ozangunalp

**Comment by ozangunalp** [comment]
I can reproduce that on a raspberrypi, but I don't have any more info on the error. I observed that with image version 3.3.0 and 3.3.1. 
I didn't have the issue with 3.2.2, so I suspect that this is due to https://github.com/apache/pulsar/pull/22054

**Comment by rsvoboda** [comment]
Thanks for the update. So we downgrade to 3.2.2?

Alternatively I can try `quarkus.pulsar.devservices.image-name` workaround to the job with quarkus quickstarts.

**Comment by rsvoboda** [comment]
Just fyi, `mvn clean verify -pl pulsar-quickstart/pulsar-quickstart-producer -Dquarkus.pulsar.devservices.image-name=apachepulsar/pulsar:3.2.4` works fine

**Comment by ozangunalp** [comment]
I think we should downgrade to use the 3.2.4 image by default and open an issue on pulsar upstream.
