### ISSUE TITLE
Generation of extension.json should allow for overrides

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#4320]
When a platform generates json it should be possible to override/add metadata:

- Categories
- Excluding extensions
- redefine its labels
- Technical vs exposed extensions
 
current idea:
have `<extension-name>.properties` and any property defined in here overrides what comes from the extensions own `quarkus-extension.properties`

**Comment by maxandersen** [comment]
Just realized this notion of overrides has a challenge - might not be a problem; but something to be aware of. The manifest metada in quarkus-extension.json I assume will be or already is (@aloubyansky ?) available at build and runtime as metadata.

These would always read the data from the manifest and not from the platform - thus the overrides in the platform will be purely cosmetic for when using tools.

**Comment by aloubyansky** [comment]
It will be available, yes. It also depends what kind of overrides we will be doing. And what it would be consumed for.

**Comment by ia3andy** [comment]
We discussed it with @maxandersen and thought that using K8S style labels would be nice:
```
Name: RESTEasy
Description: REST framework implementing JAX-RS and more
Labels:
  ShortName: jax-rs
  Keywords: resteasy, jaxrs, web, rest
  Category: web
  Guide: https://quarkus.io/guides/rest-json-guide
  Status: stable
```

Here are the different labels would be supported (other would be ignored by tooling or could be specific to a sort of tooling):
- "ShortName" is an abbreviation of the name use for search purpose
- "Keywords" is what we previously referred as "labels" used for search purpose
- "Category" or "Categories" can be used to define the cat ids
- "Hidden" is default to false and can be used to hide an extension from tooling
- "Doc", "Documentation" or "Guide" is a link to the documentation previously referred as "guide"
- "Status" is the status of the extension "Draft", "Experimental", "Beta", "Stable" (default to Draft which is not visible), is always overridden by the platform layer.

**Comment by emmanuelbernard** [comment]
I can live with that as long as some labels will be constrained and others are more free.

I'd likely go for lower case though for keys
Remember that one extension could have several guides
Why is status always overridden by the platform layer?

**Comment by ia3andy** [comment]
> I can live with that as long as some labels will be constrained and others are more free.
Sure

> I'd likely go for lower case though for keys
I don't mind either. I just find it nice K8S way, but that must be my frontend side talking

> Why is status always overridden by the platform layer?
Because we want full control over that no? if not then nevermind

**Comment by emmanuelbernard** [comment]
@ia3andy the casing is nice but will it be remembered and will we have to deal with people with mis-casing?

**Comment by emmanuelbernard** [comment]
An extension can declare itself beta, I think that's fair. We just need to be able to override it

**Comment by ia3andy** [comment]
> the casing is nice but will it be remembered and will we have to deal with people with mis-casing?

I would say we suggest that casing, but we handle any casing? Maybe we could have some kind of extension validator showing warning in case of mis-casing, or even auto-reformating?

**Comment by ia3andy** [comment]
What did we decide about linking a readme file? That's really something I want for Code Quarkus..

**Comment by emmanuelbernard** [comment]
@ia3andy we have not decided AFAIK. I'm fine either way but I think the readme model would need to be clarified further:
- can I get a shorter description version?
- is that by taking the first paragraph of the readme or separate?
- how do deal with multiple versions,
    - should I point to a specific file with tag on GitHub? like this https://github.com/quarkusio/quarkus/blob/0.25.0/README.md
    - can I point to a file that's not released yet :) no tag yet

I think if we can support both raw decription as well as pointing to a md via a URL we should be good.

**Comment by emmanuelbernard** [comment]
@maxandersen cc^

**Comment by emmanuelbernard** [comment]
> > the casing is nice but will it be remembered and will we have to deal with people with mis-casing?
> 
> I would say we suggest that casing, but we handle any casing? Maybe we could have some kind of extension validator showing warning in case of mis-casing, or even auto-reformating?

I'm fine with all but when you step back:

- you go for the case sensitive way but make it case insensitive (with the associated possible bugs)
- you go for the above and you write a whole tooling to warn people that they did a typo
- you go for case insensitive

Solution 2 is a lot of work and over board for something that "looks nicer" to Kube people. I personally thing it looks less nice and is not how we define Quarkus properties for example. we use lower case and - for term separator

**Comment by ia3andy** [comment]
@emmanuelbernard TBH I am not attached to the casing that much, let's stay uniform & use lowercase :) I am editing the above format proposal accordingly

**Comment by quintesse** [comment]
Btw, does anyone have a suggestion on where those override files would be located?

**Comment by aloubyansky** [comment]
They could be in the platform for a start, I guess.

**Comment by quintesse** [comment]
Sorry @aloubyansky , I'm not fluent in Quarkus yet, what is "the platform" exactly? :-)

**Comment by aloubyansky** [comment]
There is a separate repo for it which is https://github.com/quarkusio/quarkus-platform
I'll create a new branch soon called "universe", as we've decided to call it that actually for 1.0, which will be an updated version of the current master. The JSON will be generated in this repo and deployed as a Maven artifact.

**Comment by quintesse** [comment]
> using K8S style labels would be nice:

If we want to follow what K8s does here we should really be talking about `annotations`, not `labels`. Labels in K8s are specifically meant for identifying and looking up resources. Their values can only be simple ID strings. Annotations on the other hand are basically free-form, their values can be as simple or as complex as you want,

**Comment by ia3andy** [comment]
@quintesse maybe we should name it `metadata`? does it ring a bell in ur memory 😂

**Comment by maxandersen** [comment]
@quintesse it was actually for selection/querying I was thinking...but not sure we care about the "performance" aspects here and need to have both labels and annotations ;) 

Basically what I'm suggesting is just doing: 

Map<String, List> metadata;  :)

**Comment by emmanuelbernard** [comment]
Well. Let’s use the English meaning for label :)

**Comment by quintesse** [comment]
@emmanuelbernard not sure what you mean exactly. Is that comment pro or contra using the name "labels"? I think the word "label" can mean many things in English ;-)
When you say in English that you "label something" it generally means that you associate a simple description. On the other hand the label on a jar of let's say honey can be pretty complex. :-)

@maxandersen I like `metadata` too, nicely non-specific

**Comment by gastaldi** [comment]
Perhaps overrides in the `extension.json` could be done with JSON Patch (http://jsonpatch.com/) - just an idea.
