### ISSUE TITLE
WebSockets-next Ping/pong not working

### ISSUE THREAD

**Issue by Paul6552** [quarkusio/quarkus#43210]
### Describe the bug

Hey guys, again me x)

If a websocket connection is established and the client sends a `ping` message the quarkus-server should responde with a `pong` message.

The documentation [Websockets-next / ping/pong](https://quarkus.io/guides/websockets-next-reference#pingpong-messages) already states that an `@onPing` callback is not necessary because the server does this independently:

> Server/client endpoints automatically respond to a ping message sent from the client/server. In other words, there is no need for @OnPingMessage callback declared on an endpoint.

But the server does not responde with a `pong` message (Chrome dev-tools):
![ChromeWebsockets](https://github.com/user-attachments/assets/2d8d8c75-3faf-4731-ae51-a0b203a0ebfa)

I have turned on all logging to websockets but the server logs only show the incoming pings, but not the pong:
```
quarkus.websockets-next.server.traffic-logging.enabled=true
quarkus.websockets-next.server.traffic-logging.text-payload-limit=50
quarkus.log.category."io.quarkus.websockets.next.traffic".level=FINEST
quarkus.websockets-next.client.traffic-logging.enabled=true
```

Quarkus Server-log:

```
2024-09-10 22:23:24,517 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-3) [server] sent text message, Connection[endpointId=Beamer, id=fa6b9e29-d53d-4a82-92b4-ca0a2afb42d3], Payload: 
onOpen
2024-09-10 22:23:49,507 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-3) [server] received text message, Connection[endpointId=Beamer, id=fa6b9e29-d53d-4a82-92b4-ca0a2afb42d3], Payload: 
ping
2024-09-10 22:24:14,506 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-3) [server] received text message, Connection[endpointId=Beamer, id=fa6b9e29-d53d-4a82-92b4-ca0a2afb42d3], Payload: 
ping
2024-09-10 22:24:39,506 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-3) [server] received text message, Connection[endpointId=Beamer, id=fa6b9e29-d53d-4a82-92b4-ca0a2afb42d3], Payload: 
ping
2024-09-10 22:25:04,506 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-3) [server] received text message, Connection[endpointId=Beamer, id=fa6b9e29-d53d-4a82-92b4-ca0a2afb42d3], Payload: 
ping
```

I tried the other way, that the server automatically sends `ping` messages to the client and turned on the properties:
```
quarkus.websockets-next.server.auto-ping-interval=2
quarkus.websockets-next.client.auto-ping-interval=3
```
Also no `ping` to the client.

I checked the developer-tools from quarkus `/q/dev` and the websocket-client is always connected. The client does not lose the connection to the server.

This is my websocket-next code:
```
@Slf4j
@WebSocket(path = "/app/websocket/beamer", endpointId = "Beamer")
@ApplicationScoped
public class BeamerWebsocketEndpoint {

    @Inject
    WebSocketConnection connection;

    @OnOpen()
    public String onOpen() {
        return "onOpen";
    }

    @OnClose
    public void onClose() {
        System.out.println(connection.pathParam("meisterschaftID") + " left the game");
    }

    @OnError
    String error(Exception t) {
        log.error( "Websocket Beamer onError: " + t.getMessage() );
        return "error";
    }
}
```

### Expected behavior

The server should send ping and pong messages.

### Actual behavior

no pong message after a client-ping.

Also the automatic pings do not work.

### How to Reproduce?

1. Create websockets-next endpoint
2. Connect with a client
3. Send a ping message from the client to the quarkus server
4. No response

### Output of `java -version`

21.0.3

### Quarkus version or git rev

3.14.2

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
@Paul6552 thanks for the report.

> 3\. Send a ping message from the client to the quarkus server

How do you send the ping message? AFAIK you can't send a [Ping frame](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2) from the JavaScript API. It should be handled by the browser automatically.

> I have turned on all logging to websockets but the server logs only show the incoming pings, but not the pong:

Yes, the traffic logger does not log the control frames. It only logs text/binary messages and connection open/close.

> I tried the other way, that the server automatically sends `ping` messages to the client and turned on the properties:
> 
> ```
> quarkus.websockets-next.server.auto-ping-interval=2
> quarkus.websockets-next.client.auto-ping-interval=3
> ```

Have you tried to add an `@OnPongMessage` callback to your enpoint? It is possible that the browser does not log the Ping/Pong frames either...

**Comment by Paul6552** [comment]
> How do you send the ping message? AFAIK you can't send a [Ping frame](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2) from the JavaScript API. It should be handled by the browser automatically.

I am using `react` with this [react-use-websocket](https://github.com/robtaussig/react-use-websocket#readme). We have once already used this in an spring boot websocket project and it worked without any problems also with ping and pongs :-/ If the connection was not established correctly, the `onOpen` callback would not occur. So I believe the connection is/is established correctly.

> Have you tried to add an `@OnPongMessage` callback to your enpoint? It is possible that the browser does not log the Ping/Pong frames either...
I tried it now with the following code:
```
@OnPongMessage
Uni<Void> pong( Buffer data) {
    System.out.println("Pong message send");
    return connection.sendPong( data );
}
```

But I do not really understand the output from quarkus:
```
2024-09-11 09:02:54,155 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-2) [server] sent text message, Connection[endpointId=Beamer, id=69aebc3f-16fc-44ce-aaa7-4834d74f909e], Payload: 
onOpen
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
2024-09-11 09:03:19,153 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-2) [server] received text message, Connection[endpointId=Beamer, id=69aebc3f-16fc-44ce-aaa7-4834d74f909e], Payload: 
ping
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
Pong message send
```

Quarkus sends every few seconds a pong message. Interestingly, this never arrives on the client (Chrome dev tools).

**Comment by mkouba** [comment]
> I am using react with this [react-use-websocket](https://github.com/robtaussig/react-use-websocket#readme). We have once already used this in an spring boot websocket project and it worked without any problems also with ping and pongs :-/

I don't know this particular JS library but from the docs it seems that it does not provide a specialized method to send ping control frames :shrug:. Just try to add an `@OnTextMessage` callback and you'll see if the "ping" from the client is a regular message.

> But I do not really understand the output from quarkus:

So the `@OnPongMessage` is called every time a client sends a _pong_ in reply to the _ping_ from the server. The "Pong message send" should be "Pong message received from the client".
  
> Quarkus sends every few seconds a pong message. 

If you have `quarkus.websockets-next.server.auto-ping-interval=2` then Quarkus sends a _ping_ message to the client every two seconds. And it seems that the client correctly responds with a pong control frame => `@OnPongMessage` is invoked.

> Interestingly, this never arrives on the client (Chrome dev tools).

It could be that Chrome dev tools don't show the ping/pong messages (control frames, not regular messages) at all.

**Comment by mkouba** [comment]
Just to be clear - all the [Ping/Pong functionality mentioned in the docs](https://quarkus.io/guides/websockets-next-reference#pingpong-messages) is related to Ping/Pong [control frames](https://datatracker.ietf.org/doc/html/rfc6455#autoid-26) and not regular text/binary messages. The regular messages can be used to implement heartbeat as well but they need to be handled manually.

**Comment by Paul6552** [comment]
Thanks again for the explanation.

I've now read a lot and apparently it is the case that the [IETF](https://datatracker.ietf.org/doc/html/rfc6455#autoid-26) standard supports control frames, but not the [websocket standard](https://websockets.spec.whatwg.org//#ping-and-pong-frames).
I found also a lot of chrome/chromium bug issues to support this functionality:
[Issue 1](https://issues.chromium.org/issues/41309915) [Issue 2](https://bugs.chromium.org/p/chromium/issues/detail?id=706002&no_tracker_redirect=1)

I asked my colleague why the `ping` and `pong` functionality seemed to work in SpringBoot. According to his feedback, there is an extension in SpringBoot that pays attention to the IETF ControlFrame, but also responds to normal messages as `ping`. That's why this library apparently already worked back then.

I will now implement my own `ping` and `pong` based on `@OnTextMessage` - Callback.

Sorry again for the noise and thanks for the explanations!

**Comment by mkouba** [comment]
> According to his feedback, there is an extension in SpringBoot that pays attention to the IETF ControlFrame, but also responds to normal messages as ping. That's why this library apparently already worked back then.

Interesting, so I assume that they intercept the normal messages and if the payload equals to "ping" they respond with "pong" and ignore the endpoint callbacks.

> I will now implement my own ping and pong based on @OnTextMessage - Callback.

:+1: 

> Sorry again for the noise and thanks for the explanations!

No problem at all. I'm glad we're on common ground now ;-)
