### ISSUE TITLE
Reflection free serializer doesn't take `JsonInclude.Include.NON_ABSENT` into account

### ISSUE THREAD

**Issue by luneo7** [quarkusio/quarkus#43223]
### Describe the bug

When serializing something setting `JsonInclude.Include.NON_ABSENT` in an objectmapper customizer the reflection free serializer doesn't check the settings when serializing null values or absent (Java 8) 

### Expected behavior

Reflection free serializer takes the current object mapper serialization settings when serializing values

### Actual behavior

Values get serialized as null.

### How to Reproduce?

Get an Quarkus quickstart with Quarkus 3.14.3 set:
```
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
```
Create an object mapper customizer:
```
@Singleton
public class RegisterObjectMapperCustomizer implements ObjectMapperCustomizer {

    @Override
    public void customize(ObjectMapper objectMapper) {
        objectMapper
                .enable(DeserializationFeature.FAIL_ON_NULL_CREATOR_PROPERTIES)
                .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                .setSerializationInclusion(JsonInclude.Include.NON_ABSENT);
    }
}
```
Create one endpoint that has a return type with `Optional` and set the optional to empty, instead of having the field omitted, it will be there with null value 

### Quarkus version or git rev

3.14.3

**Comment by mariofusco** [comment]
I have a test case reproducing the problem and I'm working on it.

**Comment by mariofusco** [comment]
This issue should be fixed by this pull request https://github.com/quarkusio/quarkus/pull/43443

**Comment by gsmet** [comment]
@mariofusco my understanding was that the reflection free serializers would only be used if in a supported configuration and that we would default to the standard serializers if not. Did something change in that matter?

**Comment by mariofusco** [comment]
> @mariofusco my understanding was that the reflection free serializers would only be used if in a supported configuration and that we would default to the standard serializers if not. Did something change in that matter?

What you wrote is correct, but there's a caveat in this case. The serializers generator skips the generation for Java classes having at least a field or a method annotated with a Jackson's annotation that the generator doesn't know how to menage. This case is different: the Java classes don't have any special annotation so the serializers are correctly generated at deployment time. Conversely this configuration is provided at runtime through the Jackson's `ObjectMapper`, so the serializers factory doesn't see it at all during the generation phase.
