### ISSUE TITLE
Merge extension catalog metadata properties when merging catalogs from different registries

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#43236]
### Description

The issue was discovered trying to setup an extension registry with a custom Quarkus platform.
The idea was to provide overrides for certain properties present in the Quarkus upstream platform catalogs for custom project creation.

Original discussion happened in https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/custom.20create.20app.20scaffolding/near/469586566

FYI @vsevel

**Comment by maxandersen** [comment]
what are the "certain properties"?

**Comment by vsevel** [comment]
new properties to add configure the way the pom should be generated:
- add a parent pom
- avoid generating properties
- avoid the dep mgmt section
- avoid the plugins except the quarkus maven plugin
- avoid adding a few dependencies that are fetched from our main extension: `rest`, `config-yaml`, ... => property

properties to change the `FROM` in dockerfiles:
- existing property `dockerfile.native-micro.from`
- new proposed property `dockerfile.jvm.from`
