### ISSUE TITLE
Gradle - kotlin classes missing from the jar 

### ISSUE THREAD

**Issue by kesslerd** [quarkusio/quarkus#43242]
### Describe the bug

Kotlin classes are missing from the jar used for the docker build

I created a new project on https://code.quarkus.io/ using 
- Gradle with kotlin dsl
- Java 21
- Starter Code
- Extensions: Rest and Kotlin

Using the dev server I can access the GreetRessource, however, when I build a docker image(Dockerfile.jvm) I get the "Resource not found" message.

When adding a new endpoint using a java class the endpoint is both accessible using the dev server and the docker image

### Expected behavior

Kotlin and Java resources should work

### Actual behavior

Kotlin resources are missing

### How to Reproduce?

https://github.com/kesslerd/kotlin-docker-test 

1. create a docker image based on https://github.com/kesslerd/kotlin-docker-test/blob/main/src/main/docker/Dockerfile.jvm 
2. Check if the endpoints /hello and /hello-java work

### Output of `uname -a` or `ver`

23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment Zulu21.36+17-CA (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Zulu21.36+17-CA (build 21.0.4+7-LTS, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

**Comment by geoand** [comment]
So the problem is that when both Java and Kotlin sources exist, the production artifact does not include the kotlin stuff.

BTW, this happens not only with a docker build, but with a plain jar build as well.

**Comment by kesslerd** [comment]
@geoand It also happens for me if there is no java class in the project

**Comment by gsmet** [comment]
I think I have seen some reports of weird things happening with Kotlin + Gradle but only in dev mode.

**Comment by geoand** [comment]
In this case, dev mode worked just fine

**Comment by kesslerd** [comment]
@geoand I attached two screenshots of the contents of the jars I get. 

`./gradlew jar` (build/libs)
![jar](https://github.com/user-attachments/assets/5b4eea01-2b78-4cdf-a2f8-caa4bcbb05e3)

`./gradlew build` (build/quarkus-app/app)
![quarkus-app-jar](https://github.com/user-attachments/assets/4cc25f32-e5d7-4340-9650-2ab09e12ff8b)

Out of curiosity did you use the linked project to reproduce?

**Comment by geoand** [comment]
Yup, that's what I used

**Comment by gsmet** [comment]
@aloubyansky maybe you could have a look?

**Comment by geoand** [comment]
> @geoand When I change the quarkus version to 3.14.2 in the gradle properties the jar gets correctly generated. I verified this claim by switching several times between 3.14.2 and 3.14.3

I can confirm this, so I'll reopen it

**Comment by geoand** [comment]
> @aloubyansky maybe you could have a look?

Nothing jumps out as the culprt in the [release notes](https://github.com/quarkusio/quarkus/releases/tag/3.14.3), so I would appreciate your help here @aloubyansky

**Comment by gsmet** [comment]
Could be https://github.com/quarkusio/quarkus/pull/42496

**Comment by mschorsch** [comment]
BTW I'm not sure this is the same issue but theres definitly something wrong with Quarkus 3.14.3 using Gradle and Kotlin. In all of our Quarkus projects we have failing ci builds, failing/dubious Intellij builds and services not starting due to class not being found since Quarkus 3.14.3. Quarkus 3.14.2 works fine. I'm working on a reproducer and will open a new issue. 

I suspect it's due to https://github.com/quarkusio/quarkus/pull/42496.

**Comment by geoand** [comment]
Thanks for that info

**Comment by geoand** [comment]
Also cc @cdsap

**Comment by gsmet** [comment]
What's interesting is that the classes are actually compiled. I can see them in the `build` directory but they are not included in the jar.

**Comment by geoand** [comment]
Right, I saw that yesterday which is very weird

**Comment by gsmet** [comment]
3.14.4 released today should address the issue.
Let's keep this issue open as I only reverted the changes in 3.14/3.15 and we still need to fix the issue in `main` as we want to keep the enhancement that introduced the regression long term.
