### ISSUE TITLE
Add a way to disable http and have only https available

### ISSUE THREAD

**Issue by mazegreg** [quarkusio/quarkus#4324]
**Description**
Add the possibility to disable HTTP, and to have only HTTPSremaining.

**Implementation ideas**
Support a parameter that could be called "quarkus.http.port.state" (and value = "enabled" by default) that could be set to "disabled" by the application.properties.
If set so, the application would not open the HTTP port (not sure where this should be implemented!).

As @stuartwdouglas says in this zulip topic (https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Disable.20http/near/177142685), if HTTP is disabled, there should be a mechanism that automatically redirects to HTTPS (maybe with usual 443 port?).

**Comment by CSTDev** [comment]
I've attempted to resolve this, what I've done works (as far as I've tested) but I'm having issues getting the unit test to work, if anyone could take a look and offer suggestions that'd be great, thanks!

**Comment by emmanuelbernard** [comment]
Fixed by #7588 I think
