### ISSUE TITLE
App should exit immediatelly when java.net.BindException: Address already in use is issued

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#4325]
**Describe the bug**
Start a quarkus app in a port that's already used and you should see a `java.net.BindException: Address already in use`, making the app unusable

**Expected behavior**
The application should be killed and be terminated immediately

**Actual behavior**
Application is still running

**To Reproduce**
1. Create a quarkus app using code.quarkus.io
2. Start the same app twice (using the same port)
3. Voilà 

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.port=8080
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux ggastald-laptop 5.2.15-200.fc30.x86_64 #1 SMP Mon Sep 16 15:17:36 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`:  
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
```
 - GraalVM version (if different from Java): Not used
 - Quarkus version or git rev: 0.22.0

**Comment by geoand** [comment]
I am going to close this since it has already been fixed on master (I just verified it).

**Comment by gastaldi** [comment]
I think this issue needs to be targeted to 0.24.0 then? Just for tracking purposes :)

**Comment by geoand** [comment]
Actually it might have even been back ported to `0.23.x`. Let me check

**Comment by geoand** [comment]
So yeah, this was already part of `0.23.0`
