### ISSUE TITLE
Quarkus is using an H2 version with a regression causing data loss

### ISSUE THREAD

**Issue by vmuzikar** [quarkusio/quarkus#43261]
### Describe the bug

There seem to be a regression in the latest H2 version released (2.3.232) that is causing data loss. The previous version (2.3.230) seems to be unaffected so far. Quarkus 3.14/3.15 LTS is using the affected 2.3.232 version.

For details, see:
* https://github.com/keycloak/keycloak/issues/32785
* https://github.com/h2database/h2database/issues/4123

This issue is to track this on the Quarkus side. Depending on how quickly there will be fix and a release of H2, it might be good to consider temporarily downgrading H2 in Quarkus.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/43265 .
