### ISSUE TITLE
Quarkus application build fails inside a folder that ends with `!`

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#43273]
### Describe the bug

Quarkus application build fails inside a folder that ends with `!`

Build ends with `[ERROR] Caused by: java.nio.file.NoSuchFileException: /Users/rsvoboda/tmp/getup!/app-3.14.3/target/quarkus-app/quarkus/transformed-bytecode.jar`. 
There is a file new file generated outside the application target directory (`/Users/rsvoboda/tmp/getup` in my case) instead of the `transformed-bytecode.jar`.

This was discovered as part of the review of https://github.com/quarkusio/quarkus/issues/42248. @dmlloyd , in my opinion this is not related to the https://github.com/smallrye/smallrye-common/pull/293 changes as this scenario also fails with Quarkus 3.12.3.

Some details are also in https://github.com/quarkusio/quarkus/issues/42248#issuecomment-2324230877

### Expected behavior

Quarkus application builds successfully 

### Actual behavior

transformed-bytecode.jar gets created in different place and Quarkus application build fails 

### How to Reproduce?

mkdir 'getup!'
cd 'getup!'

## Both 3.14.3 and 3.12.3 fail to build the app

mvn io.quarkus.platform:quarkus-maven-plugin:3.12.3:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-3.12.3 -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DquarkusRegistryClient=false -DplatformVersion=3.12.3 -Dextensions=quarkus-rest
mvn -e clean package -f app-3.12.3

mvn io.quarkus.platform:quarkus-maven-plugin:3.14.3:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-3.14.3 -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DquarkusRegistryClient=false -DplatformVersion=3.14.3 -Dextensions=quarkus-rest
mvn -e clean package -f app-3.14.3

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Quarkus version or git rev

3.14.3

**Comment by rsvoboda** [comment]
I also tried Quarkus 3.2 and 2.13 and they fail too, so thi seems to be pretty old bug, but nobody hit that yet or remained silent about it.

```
mvn io.quarkus.platform:quarkus-maven-plugin:3.2.3.Final:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-3.2.3 -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DquarkusRegistryClient=false -DplatformVersion=3.2.3.Final
mvn clean package -f app-3.2.3

sdk use maven 3.8.8
mvn io.quarkus.platform:quarkus-maven-plugin:2.13.3.Final:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-2.13.3 -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DquarkusRegistryClient=false -DplatformVersion=2.13.3.Final
mvn clean package -f app-2.13.3
```

**Comment by gsmet** [comment]
FWIW, I'm not willing to personally chase this more.

**Comment by dmlloyd** [comment]
Fixing this further would (I believe) necessarily incur a performance penalty because we'd have to examine the filesystem at each point where we encounter a file that ends in `!` to see if it exists before moving on to the JAR it references. I would vote to not fix this, if my vote counts.

**Comment by rsvoboda** [comment]
Let's go ahead and close for now
