### ISSUE TITLE
InMemoryLogHandler is not showing the log line with MDC format

### ISSUE THREAD

**Issue by deejonz** [quarkusio/quarkus#43302]
### Describe the bug

if I set in a unit test the formatter InMemoryLogHandler with a MDC format like {"application_name": "%X{application_name}"} the log is captured but there is no way to get the log programmatically.

### Expected behavior

the captured log should show the formatted log line

### Actual behavior

it's not showing it.

### How to Reproduce?

```
@Test
public void test() {
	InMemoryLogHandler inMemoryLogHandler = new InMemoryLogHandler(record -> true);
	Logger logger = LogManager.getLogManager().getLogger("com.report.ReportLog");
	logger.setLevel(Level.ALL);
	logger.setUseParentHandlers(false);

	PatternFormatter formatter = new PatternFormatter("\"application_name\": \"%X{application_name}\"");
	inMemoryLogHandler.setFormatter(formatter);

	logger.addHandler(inMemoryLogHandler);
	System.out.println(logger.getHandlers());

	yourMethodWhichAddLogsWithMDCAndApplication("testApp");

	List<LogRecord> records = inMemoryLogHandler.getRecords();
	LogRecord record = records.get(0);
	// I would expect to get a log line with: {"application_name": "testApp"}
	// how to get it from the record object?
}
```

**Comment by geoand** [comment]
cc @phillip-kruger

**Comment by phillip-kruger** [comment]
cc @dmlloyd

**Comment by dmlloyd** [comment]
To view the formatted line, using the code from your example, you could call `formatter.format(record)`. To look at the MDC values directly, you would need to cast the `LogRecord` to `org.jboss.logmanager.ExtLogRecord` and call `getMdc(String)` on the result, as the MDC data is not stored by default on the base class.
