### ISSUE TITLE
Make it possible to set the base URL of the REST Client when actually performing the call

### ISSUE THREAD

**Issue by lasteris** [quarkusio/quarkus#43316]
### Description

We have the case, where we need to change URL per request. 
Mostly that's because we are trying to obtain URL from some other remote API.
For now, we have to write something like that:
```java
try (Client client = ClientBuilder.newClient()) {
                    WebTarget target = client.target(urlObtainedFromAnySource);
                    webiomedResponse = target.request()
                            .header("Authorization", "Bearer ..."))
                            .get(String.class);
```

But surely, we want just use Quarkus RestClient abstraction via declarative API, or QuarkusRestClientBuilder.

### Implementation ideas

Most likely i see this like such things done in Retrofit (@Url annotation), or special processing of Url/Uri type (like in HttpExchange in Spring Boot. But you know better :

**Comment by geoand** [comment]
#43331 introduces this capability and should be available in `3.16`

**Comment by lasteris** [comment]
@geoand Holy s**t. You are simply amazing. Thank you.

**Comment by geoand** [comment]
🙏🏽
