### ISSUE TITLE
Docs: config property names in the generated docs are no longer links

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#43310]
### Describe the bug

So a link like https://quarkus.io/version/3.8/guides/logging#quarkus-log-logging-log-config_quarkus-log-level does not work since 3.14.

Zulip discussion: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Docs.20-.20config.20options.20-.20no.20longer.20links.3F

### Expected behavior

Links like https://quarkus.io/version/3.14/guides/logging#quarkus-log-logging-log-config_quarkus-log-level should work in the docs of 3.14+.

### Actual behavior

No links ;-)

### Quarkus version or git rev

3.14+

**Comment by mkouba** [comment]
CC @gsmet

**Comment by mcruzdev** [comment]
I would like to contribute with this one @mkouba

**Comment by mkouba** [comment]
> I would like to contribute with this one @mkouba

@mcruzdev That would be awesome! Go ahead please...

**Comment by gsmet** [comment]
A few pointers:
- Changes should be made in the Qute template in this module here: https://github.com/quarkusio/quarkus/tree/main/devtools/config-doc-maven-plugin
- Output should be made similar to what we did earlier: https://github.com/quarkusio/quarkusio.github.io/blob/main/_generated-doc/3.8/config/quarkus-agroal.adoc?plain=1#L13

**Comment by gsmet** [comment]
Sorry, I will fix it myself as there's a good chance we will have to do a 3.15.1 emergency release and it might be a good idea to include it.

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/43493 will take care of it.

**Comment by gsmet** [comment]
I confirm the links are back: https://quarkus.io/guides/validation#configuration-reference .

**Comment by mkouba** [comment]
> I confirm the links are back: https://quarkus.io/guides/validation#configuration-reference .

Thanks Guillaume!
