### ISSUE TITLE
CDI security interceptor for @RolesAllowed, etc

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#4334]
> There are a few things to bear in mind here, one is that those annotations are not actually interceptor bindings, so you will need to use an ArC build time extension to do the bindings, the other is to figure out how it works with RESTEasy. At the moment there is a RESTeasy Filter thing that handles this, but it would be better to just have the interceptor handle everything and the filter just catch the exception and handle it appropriatle

The source of roles is `io.quarkus.security.identity.SecurityIdentity`

**Comment by michalszynkiewicz** [comment]
probably requires: https://github.com/quarkusio/quarkus/issues/4344

**Comment by michalszynkiewicz** [comment]
In Thorntail, and SmallRye JWT, unannotated method of a resource that has at least one annotation on its methods may be forbidden by default (based on a switch).
Do we want it working the same in Quarkus?

In other words, should the `methodInQuestion` below be accessible for all by default or not?
```java
@ApplicationScoped
class MyBean {
  @RolesAllowed("admin")
   void restrictedMethod() {}

   void methodInQuestion() {}
}
```


CC @stuartwdouglas @sberyozkin

**Comment by stuartwdouglas** [comment]
We should have a switch, and we should default to DenyAll if security annotations are present IMHO. 

On an only tangentially related note I think we should also have the option to auto deny all REST endpoints (basically an option to require rest endpoints to have explicit security config).

**Comment by michalszynkiewicz** [comment]
SmallRye JWT defaults to `@PermitAll` and if a specific file (`/META-INF/MP-JWT-DENY-NONANNOTATED-METHODS`) is created, switches to applying `@DenyAll` for all methods of classes with any security annotations. Maybe better be somewhat consistent with that?

(this switch is not MP JWT-wide, it's SmallRye specific and I'd rather have it as a property)

**Comment by michalszynkiewicz** [comment]
Note: handle `@Authenticated`

**Comment by stuartwdouglas** [comment]
This needs to be a normal config property, not a magic marker file.

**Comment by geoand** [comment]
I've been looking at the security stuff today and FWIW I think handling all the security related annotations via CDI interceptors makes perfect sense. 

For one thing, it would allow us in the future (if we so desire) to do more advanced filtering based on the values bound to Resource Methods. 
Another issue is implementation uniformity, as Hibernate Validator already uses CDI interceptors on JAX-RS resource methods are implemented.

**Comment by n1hility** [comment]
@michalszynkiewicz does this look still on track for completion in the next week or so?

**Comment by michalszynkiewicz** [comment]
@n1hility I hope to have it done next week.
Last week I paused working on it to prepare for the talks I gave this week but now I'm back on it.

**Comment by geoand** [comment]
@michalszynkiewicz If you would like a hand with anything, let me know. I was looking into the security stuff to get a deep understanding of how things work so I can definitely help out if needed.

**Comment by michalszynkiewicz** [comment]
@geoand at this point the biggest help would be to review the code

**Comment by geoand** [comment]
@michalszynkiewicz Will do! Once I figure some gradle issues I'll take a look :)
