### ISSUE TITLE
Issue with multiform data rest client on Quarkus 3.14

### ISSUE THREAD

**Issue by djphatmix** [quarkusio/quarkus#43364]
### Describe the bug

I have the below rest endpoint. Whenever I start Quarkus, I get an error saying that my rest client has not been indexed at build time. I am using Quarkus 3.14.1

```java
public class Request {
    
    @RestForm("file")
    @PartType(MediaType.APPLICATION_OCTET_STREAM)
    private InputStream file;

    @RestForm("filename")
    @PartType(MediaType.TEXT_PLAIN)
    private String filename;
}
```

Endpoint definition:

```java
    @POST
    @Path("/upload")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    public String upload(Request request) {
      // business logic.
        return "done";
    }
```

Error: 
Caused by: java.lang.IllegalStateException: REST client interface: interface com.test.api.restclient.TestRestApi was not indexed at build time.

### Expected behavior

The expectation is that the app should start up without any issues.

**Comment by geoand** [comment]
Is `TestRestApi` in another module?

**Comment by djphatmix** [comment]
Yes, TestRestAPI is in a different module. I did add the jandex plugin in my POM but it does not seem to make a difference.

**Comment by geoand** [comment]
Have you tried the `META-INF/beans.xml` method described [here](https://stackoverflow.com/a/55513723)?

**Comment by djphatmix** [comment]
I did try it. So basically what we have observed is that once we remove the fileInputStream parameter on the Request then everything works as expected. 

My issue is very similar to this one https://github.com/quarkusio/quarkus/issues/42077.

**Comment by geoand** [comment]
Very interesting. 

If you attach a sample application that exhibits the problem in action, I can do a deep dive and see what can be done.

**Comment by djphatmix** [comment]
I have created 2 sample projects. In my consumer project, I run a test inside ExampleResourceTest.java and that is where I get the error message.

Error: 
Caused by: java.lang.IllegalStateException: REST client interface: interface za.co.tutorial.StickerDefinitionRestApi was not indexed at build time. See https://quarkus.io/guides/cdi-reference#bean_discovery for information on how to index the module that contains it.
	at org.jboss.resteasy.reactive.client.impl.ClientProxies.get(ClientProxies.java:35)
	at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.proxy(WebTargetImpl.java:449)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:528)
[consumer.zip](https://github.com/user-attachments/files/17089308/consumer.zip)

The producer is greater than 25MB so I will find a way to send you a link to my repo.

**Comment by djphatmix** [comment]
> Very interesting.
> 
> If you attach a sample application that exhibits the problem in action, I can do a deep dive and see what can be done.

I have uploaded the two projects. The rest API is defined inside a project called sample and the failing test is defined inside the consumer project.

**Comment by geoand** [comment]
Thanks, I'll check soon

**Comment by geoand** [comment]
Your reproducer was super helpful, thanks!

**Comment by djphatmix** [comment]
> Your reproducer was super helpful, thanks!
> 
> #43437 fixes the issue

So will the fix go into 3.14.4 or will it be part of a new patch release?

**Comment by geoand** [comment]
I will hopefully be part of `3.15.1`

**Comment by djphatmix** [comment]
> I will hopefully be part of `3.15.1`

So when is the tentative release date for 3.15.1?

**Comment by geoand** [comment]
Towards the end of the month or beginning of October unless something unforeable happens

**Comment by djphatmix** [comment]
> Towards the end of the month or beginning of October unless something unforeable happens

Thanks for the quick response.
