### ISSUE TITLE
Application hangs on https=http port check failure

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#43373]
### Describe the bug

If the http and https ports are the same the application will show an error, but hang.

### Expected behavior

The application will terminate after the exception.

### Actual behavior

The application will hang.

### Quarkus version or git rev

3.14.2

### Additional information

Similar to https://github.com/quarkusio/quarkus/issues/43247

**Comment by geoand** [comment]
Thanks for reporting.

#43376 fixes the issue
