### ISSUE TITLE
Add support for timeouts, ssl and other %s/mp-rest/* config properties for MicroProfile RestClient 

### ISSUE THREAD

**Issue by doroshevich** [quarkusio/quarkus#4338]
**Description**

Would be nice to have possibility to configure rest-client(s) timeouts and key store(s) with configuration parameters in quarkus. 

MP rest client have config properties for timeouts  
https://download.eclipse.org/microprofile/microprofile-rest-client-1.3/microprofile-rest-client-1.3.html#_configuration_keys
```
%s/mp-rest/connectTimeout
%s/mp-rest/readTimeout
```
and for trust/key store
https://download.eclipse.org/microprofile/microprofile-rest-client-1.3/microprofile-rest-client-1.3.html#ssl
```
%s/mp-rest/trustStore
%s/mp-rest/trustStorePassword
%s/mp-rest/trustStoreType
%s/mp-rest/hostnameVerifier
%s/mp-rest/keyStore
%s/mp-rest/keyStorePassword
%s/mp-rest/keyStoreType
```
**Implementation ideas**

New to quarkus so not sure, but maybe ```io.quarkus.restclient.runtime.RestClientBase``` should do like ```org.jboss.resteasy.microprofile.client.RestClientDelegateBean``` or just use it.

**Comment by lhauspie** [comment]
I would like to work on this one...
Is it OK ?

**Comment by machi1990** [comment]
Hi @lhauspie this is okay and your contribution is highly welcomed. Consider the issue users. Feel free to ping us if you a helping hand on it.

**Comment by lhauspie-adeo** [comment]
I still working on it, I just spend more time than I expected due to difficulties with integration tests.

**Comment by machi1990** [comment]
@lhauspie or is it @lhauspie-adeo :-) it is okay, take the time you need. If you think you can use some help from the team, you can also open a draft PR so that others contributors/maintainers can look at it and give their inputs.

**Comment by lhauspie** [comment]
Damn! I miss clicked when choosing my github account :/

**Comment by loicmathieu** [comment]
@lhauspie I you are still blocked you can open a PR and ask for help. When we have the code we will be able to help you.

**Comment by lhauspie** [comment]
@loicmathieu, I think you know that it's mainly a planning issue. I've to work on an other subject, my deadline is tomorrow so I will continue to work on that issue tomorrow ;)

**Comment by kenfinnigan** [comment]
This is being done as part of #4520

**Comment by kenfinnigan** [comment]
This is part of 0.27
