### ISSUE TITLE
Disable SSL/TLS for management host and port

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#43380]
### Description

I want to disable TLS for management host. 

My current configuration like this
```
quarkus.tls.key-store.pem.0.cert=cert.pem
quarkus.tls.key-store.pem.0.key=key.pem
quarkus.management.enabled=true
```

The above configuration starts the server like this

```
2024-09-18T17:28:06.891000-0500 INFO  [io.quarkus] (main) {} rest-json-quickstart-test 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.14.4) started in 2.478s. 
Listening on: http://0.0.0.0:8080.
https://0.0.0.0:8443. 
Management interface listening on https://0.0.0.0:9000.
2024-09-18T17:28:06.905000-0500 INFO  [io.quarkus] (main) {} Profile prod activated.
2024-09-18T17:28:06.906000-0500 INFO  [io.quarkus] (main) {} Installed features: [cdi, micrometer, rest, rest-jackson, smallrye-context-propagation, smallrye-health, vertx]
```

I want management endpoint to be on the Non SSL. I don't see any configuration to do that.  Please provide a capability to disable SSL for the management endpoint

**Comment by geoand** [comment]
What you have to do in this is to not rely on the default TLS configuration, but instead use a named configuration only for the HTTP server as mentioned [here](https://quarkus.io/guides/tls-registry-reference#referencing-a-tls-configuration).

So for example:

```properties
quarkus.tls.my-server.key-store.pem.0.cert=server.crt
quarkus.tls.my-server.key-store.pem.0.key=server.key
quarkus.http.tls-configuration-name=my-server
quarkus.management.enabled=true
```

should do the trick.

Can you give it a shot?

**Comment by missourian55** [comment]
Thank you. The recommendations worked.

**Comment by geoand** [comment]
👌
