### ISSUE TITLE
Max frame length of 65536 has been exceeded - Quarkus 3

### ISSUE THREAD

**Issue by dometec** [quarkusio/quarkus#43381]
### Describe the bug

WebSocket Server ignores Max Frame Size after upgrade from Quarkus 1.x to 3.14.4.
In application.properties I set:

`quarkus.websocket.max-frame-size=2097152`

and get the exception:
```

2024-09-18 18:45:18,450 INFO  [com.vim.ngv.wss.TunnelWSS] (executor-thread-3) WebSocket tunnel error, session: lUIS0BLIvL7sX4SNrHaQrjlQCd3ld1B5W_yJT2FQ, error: Max frame length of 65536 has been exceeded..: io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:427)
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:288)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
...
```

### Expected behavior

No exception, or a message with my max frame size setting in "Max frame length of 65536 has been exceeded".

### Output of `uname -a` or `ver`

Linux localhost.localdomain 6.4.4-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jul 19 17:06:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.14.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

### Additional information

I think this method miss to take the quarkus.websocket.* configuration...

https://github.com/quarkusio/quarkus/blob/1c8464b3ff87a75857bc1a8a9f0e8a72db584d58/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L1009-L1025

**Comment by geoand** [comment]
Thanks for reporting.

Going forward, all our efforts around WebSockets are focused on [WebSockets Next](https://quarkus.io/guides/websockets-next-tutorial). If you could try and see if the problem exists with that stack, it would be great.

cc @mkouba

**Comment by mkouba** [comment]
Hm, the `quarkus.websocket.max-frame-size` is a [WebSocket client config property ](https://github.com/quarkusio/quarkus/blob/main/extensions/websockets/client/deployment/src/main/java/io/quarkus/websockets/client/deployment/WebsocketConfig.java#L16) so I'm not really sure it ever worked on the server.
  
The corresponding configuration properties in WS Next are `quarkus.websockets-next.server.max-message-size` and `quarkus.websockets-next.client.max-message-size`.

**Comment by dometec** [comment]
@geoand  ok I'll try.
@mkouba not in Quarkus 1.x see https://github.com/quarkusio/quarkus/pull/7861/files#top

**Comment by mkouba** [comment]
> @geoand ok I'll try. @mkouba not in Quarkus 1.x see https://github.com/quarkusio/quarkus/pull/7861/files#top

Interesting, it was removed (maybe unintentionally) in the "split" PR https://github.com/quarkusio/quarkus/pull/7861.

In any case, the development of the original WS extension is discontinued. We're looking forward to your feedback about [WS next](https://quarkus.io/guides/websockets-next-reference)! ;-)

**Comment by mkouba** [comment]
Hi @etiennedv-mathu, the `65536` value comes from Vertx, see `io.vertx.core.http.HttpServerOptions.DEFAULT_MAX_WEBSOCKET_FRAME_SIZE`. A message could be assembled from multiple frames.

I think that we should add the `quarkus.websockets-next.server.max-frame-size` config property.

**Comment by geoand** [comment]
> I think that we should add the quarkus.websockets-next.server.max-frame-size config property.

+1

**Comment by mkouba** [comment]
@etiennedv-mathu FYI: https://github.com/quarkusio/quarkus/pull/46233

**Comment by etiennedv-mathu** [comment]
Thank you very much.

**Comment by mkouba** [comment]
> [@mkouba](https://github.com/mkouba) it doesn't look like adding a WebSocketHttpServerOptionsCustomizer has any effect.

This is weird. I've tried to modify the test introduced in https://github.com/quarkusio/quarkus/pull/46233 and it seems to work just fine. Could you provide more details about your app, endpoint class, etc.?

**Comment by etiennedv-mathu** [comment]
Sure:

For context: This app is is acting as a business logic layer. FerretPlanner is sending this app updates on the lesson model. The exception occurs when this app tries to access lessons that are too big. The initial message includes the entire Lesson model. 

The following class is where we actually open the web socket. 

```
@Slf4j
@Dependent
public abstract class WebSocketConnectionCreator<Connector, Model> {
    @Inject
    WebSocketConnector<Connector> connector;

    public abstract void forwardMessage(Model model, WebSocketClientConnection connection);

    public WebSocketClientConnection openStream(URI uri, JsonWebToken bearerToken, String pathParameterName, String pathParameter) throws UpgradeRejectedException {
        log.debug("WebSocketClientConnection.openStream Attempting to open a WebSocket connection");

        WebSocketClientConnection connection = connector
                .baseUri(uri)
                .pathParam(pathParameterName, pathParameter)
                .addHeader("Authorization", String.format("Bearer %s", bearerToken.getRawToken()))
                .connectAndAwait();

        log.debug("WebSocketClientConnection.openStream Connected to WebSocket");
        return connection;
    }
}
```

The following class is a "API" so to speak. it captures the messages and. sends them upwards via the event bus. This is also where the error is happening.
```
package za.co.mathu.bear.connectors.ferret.planner.socket;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.quarkus.websockets.next.*;
import io.vertx.core.http.UpgradeRejectedException;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Inject;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.eclipse.microprofile.jwt.JsonWebToken;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import za.co.mathu.bear.connectors.ferret.shared.models.StreamMessage;
import za.co.mathu.bear.connectors.ferret.sockets.WebSocketConnectionCreator;
import za.co.mathu.bear.connectors.ferret.planner.FerretPlannerException;
import za.co.mathu.bear.connectors.ferret.planner.FerretPlannerExceptionMapper;
import za.co.mathu.bear.connectors.ferret.planner.models.Lessons;
import za.co.mathu.bear.connectors.ferret.planner.socket.events.LessonEventBus;

import java.net.URI;
import java.nio.charset.StandardCharsets;

@RegisterProvider(FerretPlannerExceptionMapper.class)
public interface FerretPlannerLessonWebSocketConnector {
    @Slf4j
    @ApplicationScoped
    @WebSocketClient(path = "/lesson/stream/{lessonId}")
    class LessonEndpoint {
        @Inject
        FerretPlannerLessonSocketCreator connector;

        @Inject
        private ObjectMapper mapper;


        @OnOpen
        void onOpen (WebSocketClientConnection connection) throws FerretPlannerException {
            log.info("FerretPlannerLessonWebSocketConnector.LessonEndpoint.onOpen");
        }

        @OnClose
        void onClose(WebSocketClientConnection connection) throws FerretPlannerException {
            log.info("FerretPlannerLessonWebSocketConnector.LessonEndpoint.onClose");
        }

        @OnError
        void onError(WebSocketClientConnection connection, Throwable throwable) throws FerretPlannerException {
            log.error("FerretPlannerLessonWebSocketConnector.LessonEndpoint.onError", throwable);

            throw new FerretPlannerException()
                    .setMessage(throwable.getMessage());
        }

        @OnBinaryMessage
        void onBinaryMessage(WebSocketClientConnection connection, byte[] message) throws FerretPlannerException {
            log.debug("FerretPlannerLessonWebSocketConnector.LessonEndpoint.onBinaryMessage");

            String messageString = new String(message, StandardCharsets.UTF_8);
            handleMessage(connection, messageString);
        }

        @OnTextMessage
        void onTextMessage(WebSocketClientConnection connection, String message) throws FerretPlannerException {
            log.debug("FerretPlannerLessonWebSocketConnector.LessonEndpoint.onStringMessage");

            handleMessage(connection, message);
        }

        private void handleMessage(WebSocketClientConnection connection, String message) throws FerretPlannerException {
            try {
                StreamMessage.StreamPayload payload = mapper.readValue(message, StreamMessage.StreamPayload.class);
                Lessons.LessonStream lessonStream;

                if (payload.getType().equals(StreamMessage.MessageFields.DATA)) {
                    Lessons.Lesson lesson = mapper.convertValue(payload.getMessage(), Lessons.Lesson.class);

                    lessonStream = new Lessons.LessonStream()
                            .setType(payload.getType())
                            .setPayload(lesson);
                } else {
                    lessonStream = new Lessons.LessonStream()
                            .setType(payload.getType())
                            .setMessage(payload.getMessage().toString());
                }
                connector.forwardMessage(lessonStream, connection);
            } catch (JsonProcessingException e) {
                throw new FerretPlannerException()
                        .setMessage(e.getMessage());
            }
        }
    }

    @Slf4j
    @RequestScoped
    class FerretPlannerLessonSocketCreator extends WebSocketConnectionCreator<LessonEndpoint, Lessons.LessonStream> {
        @ConfigProperty(name = "quarkus.rest-client.ferret-planner-api.url")
        URI uri;

        @Inject
        LessonEventBus eventBus;

        @Override
        public void forwardMessage(Lessons.LessonStream lessonStream, WebSocketClientConnection connection) {
            eventBus.publish("Lesson-message", lessonStream, connection);
        }

        public WebSocketClientConnection openStream(JsonWebToken bearerToken, String lessonId) throws FerretPlannerException {
            try {
                return super.openStream(uri, bearerToken, "lessonId", lessonId);
            } catch (UpgradeRejectedException e) {
                throw new FerretPlannerException()
                        .setStatus(e.getStatus())
                        .setMessage(e.getMessage());
            }
        }
    }
}
```

**Comment by mkouba** [comment]
> Sure:
> 
> For context: This app is is acting as a business logic layer. FerretPlanner is sending this app updates on the lesson model. The exception occurs when this app tries to access lessons that are too big. The initial message includes the entire Lesson model.
> 
> The following class is where we actually open the web socket.
> ...

Ah ok, so it's a WS next client. In that case, a `HttpServerOptionsCustomizer ` has no effect and I'm afraid that I don't have a workaround for you because there's no way to customize the `WebSocketClientOptions` used for a `WebSocketConnector`. The good news is that https://github.com/quarkusio/quarkus/pull/46233 will be backported and `quarkus.websockets-next.client.max-frame-size` should fix your problem.

I've also created https://github.com/quarkusio/quarkus/issues/46244 so that it's possible to customize the `WebSocketConnectOptions` and `WebSocketClientOptions` used.
