### ISSUE TITLE
Replace broken link in migration guide new one for OpenTelemetry - semantic convention changes

### ISSUE THREAD

**Issue by rolfedh** [quarkusio/quarkus#43397]
### Description

In https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#semantic-convention-changes,
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#semantic-convention-changes is 404.
Please replace it with https://github.com/open-telemetry/semantic-conventions/blob/main/docs/non-normative/http-migration.md.

**Comment by brunobat** [comment]
Thanks @rolfedh. Fixed.
