### ISSUE TITLE
Quarkus does not decompress Brotli requests in native mode

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#43392]
### Describe the bug

I have an application which uses brotli for compression of HTTP requests and responses. It works as expected in JVM mode, but in native it fails to decrypt incoming requests.

The method in question looks like this:

```
    @POST
    @Path("/decompression")
    @Produces(MediaType.TEXT_PLAIN)
    public String decompressionHttpResponse(byte[] compressedData) {
        String decompressedData = new String(compressedData);
        System.out.println(decompressedData);
        return decompressedData;
    }
```

### Expected behavior

Brotli should decompress the input and return the decompressed data (like it does in JVM)

### Actual behavior

Brotli returns compressed data

### How to Reproduce?

1. `git clone -b brotli-native https://github.com/fedinskiy/reproducer`
2. `cd reproducer`
3. `mvn clean verify -Dnative` # GreetingResourceTest, which is run in JVM succeeds, GreetingResourceIT, which is run the same checks in native fails

### Output of `uname -a` or `ver`

6.10.4-200.fc40.x86_64

### Output of `java -version`

Java version: 21.0.1, vendor: Eclipse Adoptium

### Quarkus version or git rev

3.14.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

This issue is a follow up to https://github.com/quarkusio/quarkus/issues/40533, which used the same cases with slightly different properties

**Comment by zakkak** [comment]
@fedinskiy https://github.com/quarkusio/quarkus/pull/44348 should fix this. Please give it a try if possible.

**Comment by fedinskiy** [comment]
@zakkak building this branch and running the reproducer with `mvn clean verify -Dnative -Dquarkus.platform.group-id=io.quarkus -Dquarkus.platform.version=999-SNAPSHOT` solved the problem
