### ISSUE TITLE
Update protobuf-java to 3.25.5

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#43414]
### Describe the bug

Please update protobuf-java to 3.25.5 because of https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-735f-pc8j-v9w8.

https://github.com/quarkusio/quarkus/blob/78ff38019b9c9632ed64ade2ce3e20ccc4a2c163/pom.xml#L85-L86

**Comment by cescoffier** [comment]
Can you open a pull request?
