### ISSUE TITLE
@RegisterForReflection ignored when using a multimodule project (with different package path)

### ISSUE THREAD

**Issue by ITrium-Salah** [quarkusio/quarkus#43423]
### Describe the bug

I have a project with an openapi generated client maven submodule. With quarkus 3.9.2 i have just to annotate the model with @RegisterForReflection but after migrating to Quarkus 3.14.4 the register for reflection seem to be ignored and i have a deserialization error

### Expected behavior

Detect the @RegisterForReflection on submodule. 
Or add some specification on how the project sources are scanned by quarkus.

### Actual behavior

RegisterForReflection ignored

### Quarkus version or git rev

3.14.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.5

**Comment by melloware** [comment]
@ITrium-Salah is all that code in a standalone JAR now you include?  If so you might have to add an empty `beans.xml` to that submodule JAR to tell Quarkus to actually scan that JAR for annoations.

**Comment by galderz** [comment]
Yeah, this sounds like what @melloware hints. The alternative is to force the submodule to produce a jandex index, see https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index

**Comment by melloware** [comment]
No response from OP. I think this is safe to close.
