### ISSUE TITLE
HTTP HEAD to @GET endpoint of (reactive) Jakarta RESTful web services sub resource returns 405

### ISSUE THREAD

**Issue by DeMol-EE** [quarkusio/quarkus#43422]
### Describe the bug

I have a `@GET` endpoint inside a Jakarta RESTful web services sub resource. Doing an HTTP HEAD request to it, I would expect to get a 2XX, but instead, I got a 405.

### Expected behavior

2XX

### Actual behavior

405

### How to Reproduce?

Run the test of this [reproducer](https://github.com/DeMol-EE/quarkus-reproducer-43422) to see the failing case.

### Output of `uname -a` or `ver`

Darwin <..> 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

OpenJDK 64-Bit Server VM Zulu21.28+85-CA (build 21+35, mixed mode, sharing)

### Quarkus version or git rev

3.14.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)

**Comment by geoand** [comment]
Thanks for the reproducer. #43440 fixes the issue
