### ISSUE TITLE
Locales Some integration test fails with GraalVM for JDK 24

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#43436]
### Describe the bug

Starting with GraalVM for JDK 24 (24.2) native image will no longer set the locale default at build time. See https://github.com/oracle/graal/pull/9694. This apparently breaks the Locale Some integration test of Quarkus.

See https://github.com/graalvm/mandrel/issues/755#issuecomment-2367117119

### Expected behavior

The test should pass

### Actual behavior

The test fails with errors like the following:

```
 Error:  Tests run: 20, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 6.895 s <<< FAILURE! -- in io.quarkus.locales.it.LocalesIT
Error:  io.quarkus.locales.it.LocalesIT.testCurrencies(String, String, String)[3] -- Time elapsed: 0.033 s <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "česká koruna"
  Actual: Czech Republic Koruna
```

See https://github.com/graalvm/mandrel/actions/runs/10985696189/job/30498542041#step:12:3093

### How to Reproduce?

1. Build GraalVM for JDK 24
2. Run `locales/some` integration test in native mode

### Additional information

The regression is introduced by https://github.com/oracle/graal/pull/9694

**Comment by jerboaa** [comment]
> The regression is introduced by [oracle/graal#9694](https://github.com/oracle/graal/pull/9694)

I came to the same conclusion (noticed it too late). Why is this being tracked as a quarkus issue?

**Comment by zakkak** [comment]
Because Quarkus assumes build-time fixed locales and needs some adaptation (working on it) to support the new runtime locales.

**Comment by zakkak** [comment]
> That would be useful info to have in the ticket. Thanks!

Turns out it was simpler than I expected :)

More details in https://github.com/quarkusio/quarkus/pull/43448

**Comment by jerboaa** [comment]
Let me add some explanation to this issue for posterity.

Prior GraalVM for JDK 24 (currently EA), the default locale for the native image at runtime was determined at native image build time (set by `-Duser.language=X -Duser.country=Y`). With GraalVM for JDK 24 this now changes and behaves similar to how `java` behaves. That is, the default locale can get selected by passing `-Duser.language=X -Duser.country=Y` to the native image.
