### ISSUE TITLE
Handle non-binding fields for interceptor bindings from non-binding annotations

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#4344]
`InterceptorBindingRegistrar` makes it possible to make annotations binding even if they do not have `@InterceptorBinding`.

I'd like to use it `@RolesAllowed`. The problem is this annotation requires a `value`. 
An interceptor for it should be triggered regardless of the value. I'd like to have an option to specify that the `value` field is non-binding in this situation.

I have briefly discussed it with @mkouba and one option to achieve that would be to extend `InterceptorBindingRegistrar` to provide such information.

I'd like to implement it, creating the issue to provide a space to discuss the problem.

cc @manovotn

**Comment by manovotn** [comment]
Maybe we could reuse annotation transformer for the field somehow?
Since the added binding will be evaluated just as any other binding and if you look at the jandex class (which is what we do now) then you will see it as binding still.

**Comment by michalszynkiewicz** [comment]
@manovotn what could such transformer do?  As I understand we can manipulate the annotations this way and thought of replacing e.g. `@RolesAllowed` with our interceptor-binding version that would define the roles as nonbinding. Is this what you have in mind?

**Comment by michalszynkiewicz** [comment]
This is how it may look like when if we'll add the info to `InterceptorBindingRegistrar`.
(The `Map` that is returned there is not very nice to work with, so if that would be the solution I'd like to replace it with some custom object)

**Comment by manovotn** [comment]
@michalszynkiewicz what I meant was [`AnnotationsTransformer`](https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AnnotationsTransformer.java). If we could grant user access to transformer while adding the binding, then user could specify what fields are to be `@Nonbinding`. Or any other API that will lead to us registering another transformer.

`AnnotationsTransformer` creates an abstraction layer on top on jandex indexed classes and allows you to change them - but in code you then need to query for annotations via [`AnnotationStore`](https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AnnotationStore.java) which is what lazily applies and caches the modifications. The upside is that anyone (any extension for instance) can then see those fields as non-binding when looking via `AnnotationStore`.

WDYT @mkouba , would that make sense?

**Comment by geoand** [comment]
FWIW, this is how the Hibernate Validator integrates with JAX-RS resource methods: https://github.com/quarkusio/quarkus/blob/master/extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java#L49
