### ISSUE TITLE
Docs: Duration and MemorySize links do not work

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#43469]
### Describe the bug

For example, in https://quarkus.io/version/main/guides/all-config the `quarkus.datasource.jdbc.background-validation-interval` config property is of type `java.time.Duration` and the links points to `https://quarkus.io/version/main/guides/all-config#duration-note-anchor-{summaryTableId}`. It should be `https://quarkus.io/version/main/guides/all-config#duration-note-anchor-all-config` instead.

**Comment by gsmet** [comment]
FWIW, as mentioned to @mkouba, it was already broken before, I just kept the existing behavior, which is due to a limitation of AsciiDoc.

Ideally, we should have Qute replacing it instead of using an Asciidoc attribute but I need to refactor the code a bit for that.
