### ISSUE TITLE
quarkus:update fails on Windows with quarkus-cli

### ISSUE THREAD

**Issue by codengine** [quarkusio/quarkus#43473]
### Describe the bug

I'm using the Quarkus CLI 3.14.4 that I installed through Chocolatey with PowerShell on Windows 10.
When I try to update my project through `quarkus:update`, the generated openrewrite recipe contains a non-escaped path to the recipe itself here:

```
configFile = project.getRootProject().file("C:\Users\xxx\AppData\Local\Temp\quarkus-project-recipe-8715019618984806815.yaml")
```

It should be

```
configFile = project.getRootProject().file("C:\\Users\\xxxx\\AppData\\Local\\Temp\\quarkus-project-recipe-8715019618984806815.yaml")
```

With that change, the recipe works fine when I invoke the upgrade through gradle manually.

Moreover, instead of reporting the error, the upgrade itself is stuck and does nothing.

### Expected behavior

The upgrade is cancelled on errors and paths should be generated correctly on Windows environments.

### Actual behavior

Process is stuck and silent, upgrade fails.

### How to Reproduce?

- Windows 10 (11 perhaps also)
- Chocolatey
- PowerShell 7
- quarkus-cli 3.14.4
- An upgradable project

### Output of `uname -a` or `ver`

Windows 10 22H2

### Output of `java -version`

openjdk version "22.0.1" 2024-04-16

### Quarkus version or git rev

3.14.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

**Comment by maxandersen** [comment]
the bug is here https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdateCommand.java#L85

that is resulting in an unescaped string to be made.

up for try fix that and test on windows and make a pullrequest ?

**Comment by maxandersen** [comment]
something like `path.replace("\\", "\\\\");` should suffice.

**Comment by gsmet** [comment]
Yeah so we usually replace them by `/` in other parts of the code. I was actually fixing it and saw your message when looking for the issue number.

**Comment by gsmet** [comment]
@codengine if you can check `/` in the path works for you, https://github.com/quarkusio/quarkus/pull/43536 should address the issue.

**Comment by codengine** [comment]
@gsmet Is there an artifact that I can use for testing?

**Comment by gsmet** [comment]
@codengine if you can confirm manually changing things to `/` works for you, I can merge and then you will have the snapshots available here: https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#using-snapshots

**Comment by codengine** [comment]
> @codengine if you can confirm manually changing things to `/` works for you, I can merge and then you will have the snapshots available here: https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#using-snapshots

I can confirm that it works with `/` on Windows.

**Comment by gsmet** [comment]
Thanks for confirming! I merged the PR.
