### ISSUE TITLE
Add a JPA Identity Extension

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#4347]
This extension would allow for an easy annotation driven approach to creating JPA entities that represent a user. An entity can be annotated with @Username and @Password (and maybe @Salt) to inform Quarkus that this entity represents a user. Quarkus will then automatically wire up authentication based on this entity.

**Comment by FroMage** [comment]
Looking at it for prototyping.

**Comment by FroMage** [comment]
Well, I stopped looking at it, but I do have a branch with the start of this. I hit the issue that it appears that the credentials are being looked up outside of a scope in which ArC can deliver an `EntityManager` (so probably outside the request scope), which I'm not sure how to fix. I can probably get an `EntityManagerFactory` and create one, but it's probably not right performance-wise?

**Comment by stuartwdouglas** [comment]
We need to create the request scope earlier then I guess. I was trying to avoid this as there is some complexity in dealing with this if the thread is propagated between different threads. 

Creating an EntityManager is also a solution (and should not really be a perf issue, they are supposed to be fairly cheap), but it means that if we are going to stick the user entity into the SecurityIdentity then it will be a detached entity, although this might be ok.

**Comment by FroMage** [comment]
It's almost done here: https://github.com/quarkusio/quarkus/pull/5660
