### ISSUE TITLE
Integration with Smallrye Reactive Messaging SQS

### ISSUE THREAD

**Issue by adampoplawski** [quarkusio/quarkus#43485]
### Description

Around April SQS support was added to Smallrye Reactive Messaging. Is there integration with Quarkus planned?
For potential reference https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/smallrye.20reactive.20messaging.20SQS.20support.

![image](https://github.com/user-attachments/assets/987880c7-f5ef-48d6-b20a-e89f2ea15d56)

ref:
https://github.com/quarkiverse/quarkus-amazon-services/issues/1414
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/smallrye.20reactive.20messaging.20SQS.20support

**Comment by cescoffier** [comment]
@ozangunalp Do you know the state of the SQS connector?

**Comment by ozangunalp** [comment]
I'll link my answer here : https://github.com/quarkiverse/quarkus-amazon-services/issues/1414#issuecomment-2373223639

**Comment by ozangunalp** [comment]
I don't think we will include an additional messaging extension to the core. So we can close this one @cescoffier wdyt ?

**Comment by cescoffier** [comment]
In the core, for sure,
But it should be listed in code.quarkus.io. (even if it's in quarkiverse).

**Comment by ozangunalp** [comment]
That's why I suggested a contribution to the https://github.com/quarkiverse/quarkus-amazon-services

**Comment by scrocquesel** [comment]
Why are some connector supported in core and not the other ? Shouldn't we have a smallrye messaging in quarkiverse supporting all the connector in a central place ?

**Comment by cescoffier** [comment]
The central messaging extension is hard to extract as improvements generally require changing things in Quarkus Core (for example, the graceful shutdown we want to add will need a few adjustments in Quarkus Core). Also, it is always a good reminder that everything we do needs to be designed for HTTP (request/reply) and messaging. 

Now, there are connectors, like the MQTT, RabbitMQ, AMQP, and even Pulsar, that could be moved to the quarkiverse but in different repositories. Kafka is slightly different as it relies on some internal Kafka client magic located in Quarkus. It would be slightly harder to find regression. However, the connector code would still be in SmallRye, and only the extensions would be moved to Quarkiverse.

However, there is no difference between being in Quarkus Core and being in Quarkiverse. You should be listed the same way on code.quarkus.io. 

Note that we also have connectors hosted directly by the vendor organization, like the Solace connector.

**Comment by adampoplawski** [comment]
@cescoffier @ozangunalp @cescoffier so to summarize
1. Current separation for core and quarkiverse will stay as it is
2. Now integration needs to be implemented (topic in AWS Quarkiverse)
3. After point 2 we can move back here, and https://code.quarkus.io/ will be updated

So now this topics needs to wait and we need to move to AWS Quarkiverse to proceed
Am I understanding correctly?

**Comment by adampoplawski** [comment]
@cescoffier Great. I will try to contribute in AWS Quarkiverse and ping you here if I succeed.

**Comment by ozangunalp** [comment]
This is now available in Quarkiverse AWS
