### ISSUE TITLE
OpenTelemetry instrumentation still active after `quarkus.otel.sdk.disabled=true`

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#43502]
### Describe the bug

OpenTelemetry instrumentation is still active even when the SDK is disabled, therefore performing a non trivial amount of work and allocations that are not needed.

See the following flamegraph:
<img width="1659" alt="Screenshot 2024-09-25 at 17 46 14" src="https://github.com/user-attachments/assets/c1177f55-ad0c-468d-a945-64181615d536">

This must be corrected.

### Expected behavior

When `quarkus.otel.sdk.disabled=true` the amount of OpenTelemetry related work must be near zero.

### Actual behavior

14,23% of all samples in the above flamegraph are OpenTelemetry related.

### How to Reproduce?

Using this project: https://github.com/brunobat/quarkus-observability-perf
Set `quarkus.otel.sdk.disabled=true`
Executing this hyperfoill test script to generate loa: https://github.com/brunobat/quarkus-observability-perf/blob/main/hyperfoil-scripts/quarkus-otel-perf.hf.yaml
And profiling the the execution with async profiler.

Data of the test execution can be seen performance test environment. Please contact me for details.

This affects all versions of the OpenTelemetry extension.

**Comment by brunobat** [comment]
`quarkus.otel.sdk.disabled` must be checked on each OTel related recorder.

**Comment by geoand** [comment]
Seems like something we should fix for `3.15`

**Comment by brunobat** [comment]
This is the flamegraph after the merge when OTel is disabled at runtime: 

![Image](https://github.com/user-attachments/assets/dff20a44-83a9-40a3-91af-8507489046cf)
