### ISSUE TITLE
List 3.15 version in the drop down menu on https://quarkus.io/guides/

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#43520]
### Description

The 3.15 guide links, such as https://quarkus.io/version/3.15/guides/http-reference
 seem to work, but the 3.15 version is missing in the menu:
![image](https://github.com/user-attachments/assets/fb1eca40-29bf-4faf-8ed4-2b699110aedc)

**Comment by gsmet** [comment]
Yes, the release is still in progress. It wasn't announced yet.

**Comment by gsmet** [comment]
(It has been extremely chaotic due to Maven Central limiting the requests for GH Actions and us getting 429 errors and the 3.15.0 being aborted in the middle of things because completely borked)

**Comment by gsmet** [comment]
I pushed the website update, the change should appear soon.
