### ISSUE TITLE
Officially support @Startup annotation on CDI beans created through method instead of class

### ISSUE THREAD

**Issue by davidreis97** [quarkusio/quarkus#43523]
### Description

I'm using the following code to create a bean:

```
@ApplicationScoped
@MyBananaMap
public RMapCache<String, MyBanana> myBananaCache() {
   ...
}
```

I would like to make this bean be initialized at startup, and after adding the `@Startup` annotation the method is indeed called at startup as it should, but I still get the following warning:

`Ignored an invalid @Startup method declared on <CacheCreationClass>: <CacheCreationClass>.myBananaCache()`

If we could move to officially support this usage of the `@Startup` method without throwing a warning, it would be very useful to us. Willing to contribute if you consider this idea feasible. Thanks!

**Comment by mkouba** [comment]
Thanks for reporting. What version of Quarkus do you use and where comes the warning from (a loggger name would be helpful)?

> If we could move to officially support this usage of the @Startup method without throwing a warning, it would be very useful to us.

It is officialy supported. This is very likely just an oversight. 

> Willing to contribute if you consider this idea feasible. Thanks!

:100:

**Comment by mkouba** [comment]
@davidreis97 I think that the problem should be fixed in https://github.com/quarkusio/quarkus/pull/40096 that targets Quarkus 3.9.4.

**Comment by davidreis97** [comment]
@mkouba Upgrading to the latest version does solve the issue, `@Startup` works as expected without warning 🙈 My bad, I'll remember to check the Quarkus version the next time and include it in the issue. Thanks for the quick feedback!
