### ISSUE TITLE
The WebSocket Dev UI widget does not connect for nested classes

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#43534]
### Describe the bug

When you click on `connect`, nothing happens.
The console says: 
Uncaught SyntaxError: Failed to execute 'querySelector' on 'DocumentFragment': '#org_acme_QuarkusAiServiceScopes$MyWSEndpoint' is not a valid selector.

I believe it's because my web socket is a nested class.

**Comment by phillip-kruger** [comment]
Is this Quarkus Dev ui or langchain4j extension?

**Comment by cescoffier** [comment]
Quarkus Dev UI.

Basically, if you have a websocket endpoint declared as a static nested class, the generated id is incorrect because of the `#`

```java
public class Application {

    @WebSocket(path="/ws")
    static class MyWebSocket {
    
         @OnTextMessage
         String echo(String s) { return s; }
    }

}

**Comment by mkouba** [comment]
> Is this Quarkus Dev ui or langchain4j extension?

I believe that it's a WS Next Dev UI. Will take a look.

**Comment by cescoffier** [comment]
The websocket works, it's just the dev ui that compute an invalid javascript it.

**Comment by cescoffier** [comment]
(BTW, I'm using the nested class technique in presentation to have everything in one file)

**Comment by mkouba** [comment]
> The websocket works, it's just the dev ui that compute an invalid javascript it.

Yes, I mean the Dev UI part of the WS Next extension...

**Comment by mkouba** [comment]
This [one-liner fix](https://github.com/quarkusio/quarkus/pull/43560) should help..
