### ISSUE TITLE
Replace broken link in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.13#breaking-changes

### ISSUE THREAD

**Issue by rolfedh** [quarkusio/quarkus#43546]
### Description

In https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.13#breaking-changes, `The full [list of changes](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/migration-guide.md#summary-of-changes).` link is broken (404). 

This issue is similar to https://github.com/quarkusio/quarkus/issues/43397, which was recently fixed.

**Comment by gsmet** [comment]
Done, thanks!
