### ISSUE TITLE
gRPC RESOURCE_EXHAUSTED with quarkus.grpc.server.use-separate-server=false

### ISSUE THREAD

**Issue by ncabanis** [quarkusio/quarkus#43573]
### Describe the bug

When using `quarkus.grpc.server.use-separate-server=false` sending a gRPC message of 256 KB results in RESOURCE_EXHAUSTED. This does not happen with `quarkus.grpc.server.use-separate-server=true`.
Furthermore, `quarkus.grpc.server.max-inbound-message-size` has no effect. Even though the default is 4 MB anyways for Java gRPC.

### Expected behavior

The integrated gRPC server should behave the same as the separate gRPC server and the configuration should be the same.

### How to Reproduce?

1. Generate the default starter with gRPC.
2. In `application.properties`, set `quarkus.grpc.server.use-separate-server=false`
3. Update the generated test case and execute:
```
    @Test
    void testHello() {
        var sizeInChars = 256 * 1024;
        helloGrpc.sayHello(
                HelloRequest.newBuilder().setName("a".repeat(sizeInChars)).build()
        ).await().atMost(Duration.ofSeconds(5));
    }
```

[code-with-quarkus.zip](https://github.com/user-attachments/files/17171506/code-with-quarkus.zip)

**Comment by cescoffier** [comment]
This is hitting the max message size configured in the Vert.x gRPC server.
As far as I can see, we cannot configure it (@alesj can you confirm). We definitely should have a configuration property for this.

In the `GrpcServerRecorder.java` file, line 149, I don't see the `GrpcServerOptions` passed to the server. We should have some options here, typically to configure the max message size. We do have a property about the max inbound message size that we could reuse (this one comes from gRPC Java), but we would still need to configure the server.

**Comment by cescoffier** [comment]
BTW, it's the only option of the GRPC server options right now, but more is coming in Vert.x 5.
