### ISSUE TITLE
Open Telemetry extension Traces and Logs are not linked with the span

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#43626]
### Describe the bug

 I found one issue that may be because I didn't use it correctly or because there is a bug it doesn't work from my understanding; I created the example in the documentation, and using the lgtm dev service, I started everything.

Then, Prometheus metrics, traces, and logs are there, so data is stored, but when I go to the trace, select a trace (by span ID), click the logs icon, and execute the query to Loki with the service name and span ID, it finds no logs.

So if I query logs by only the service name, all logs are there but it seems like the relationship with the span is not stored.

As I said I might have done something wrong, or I might be missing something.

@loicmathieu 

### Expected behavior

When I click log button from a specific span, it shows the logthe 

### Actual behavior

Not showing the log

### Quarkus version or git rev

999-SNAPSHOT (99278196c184491f8e3c86f1b8a58f014d209e58)

### Additional information

It comes from this PR https://github.com/quarkusio/quarkus/pull/38239

**Comment by geoand** [comment]
@lordofthejars can you please share your sample application?

**Comment by lordofthejars** [comment]
Sure: https://github.com/lordofthejars/quarkus-loki

It is the same of the documentation

**Comment by geoand** [comment]
🙏🏽

**Comment by geoand** [comment]
I tried this and it worked for me (after making sure that all the services were up and running)

**Comment by brunobat** [comment]
This might have been a bug from the previous Grafana image. @lordofthejars can you please retest with current main?

**Comment by lordofthejars** [comment]
Going to update the repo and try again

**Comment by lordofthejars** [comment]
Yes it works. Thanks

**Comment by geoand** [comment]
Thanks for checking
