### ISSUE TITLE
Document RestResponse<T> in rest client

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#43620]
### Description

I've multiple times has the need to do more "rest full" behaviors that needed access to response headers ( to get etag ) etc. 

turns out that the rest client supports things like:

```
 @GET
        @Path("/public/schedules")
        RestResponse<ScheduleLinks> getSchedules();

```

but its not documented at all at https://quarkus.io/guides/rest-client

discussed a bit here https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Getting.20headers.20like.20etag.20via.20rest.20client.20.3F

opening this to have a trace of it and when someone (even me) have time to document it feel encouraged to do so :)

**Comment by geoand** [comment]
cc @lasteris

**Comment by lasteris** [comment]
I will do it

**Comment by geoand** [comment]
🙏🏽
