### ISSUE TITLE
JPA lifecycle callback @PreUpdate is not running on proper time with Panache Reactive

### ISSUE THREAD

**Issue by cvgaviao** [quarkusio/quarkus#43652]
### Describe the bug

I have the following endpoint method to update an entity object:
```
     @PUT
    @Path("{userId}")
    public Uni<RestResponse<UserDto>> update(@RestPath("userId") Long pUserId, UserDto pUserUpdateDto) {

        return Panache.withTransaction(() -> userRepo.findById(pUserId)
                .onItem()
                .ifNull()
                .failWith(NotFoundException::new)
                .call(e1 -> Mutiny.fetch(e1.getUnits()))
                .onItem()
                .transform(o -> userMapper.mergeEntityWithDtoToBeUpdated(o, pUserUpdateDto))
                .chain(e -> userRepo.persist(e)
                        .invoke(e2 -> logger.infof("persisted with updatedOn: %1s", e2.getUpdatedOn())))
                .onItem()
                .transform(e -> {
                    UserDto dto = userMapper.mapToDto(e);
                    logger.infof("mapped object back to DTO: %1s", dto.toString());
                    return dto;
                })).onItem().transform(RestResponse::ok);
    }
```
The idea on this method is to find the object that needs to be updated, then use mapstruct to merge it with the update DTO, then persist the updated entity, and finally map it again to the DTO that will be returned in the response.

To write a proper non-blocking sentence with mutiny that properly works with hibernate have been a big stone in my team's shoes in the last few months, but I believe that this one is correct, at least it worked well, until I added the following callback:

```
    @PreUpdate
    protected void preUpdate() {
        updatedOn = ZonedDateTime.now();
        LOG.infof("Set the Update datetime to %s", updatedOn.toString());
    }
```

Adding the callback made some endpoint tests to fail due the fact that updatedOn was null. But the interesting thing is that I certified that the preUpdated() method is being called, but in the wrong time:
```
2024-10-02 12:28:56,649 INFO  [com.myc.api.app.res.UserResource] (vert.x-eventloop-thread-1) persisted with updatedOn: null
2024-10-02 12:28:56,651 INFO  [com.myc.api.app.res.UserResource] (vert.x-eventloop-thread-1) mapped object back to DTO: UserDto{name=Joana, surname=Dark, email=jane.d@bird.com, loginId=jane.d, createdBy=null, createdOn=null, optLock=0, updatedOn=null, id=1, units=[]}
2024-10-02 12:28:56,672 INFO  [com.myc.api.app.ent.BaseEntity] (vert.x-eventloop-thread-1) Set the Update datetime to 2024-10-02T12:28:56.672747900+01:00[Europe/Lisbon]
```

### Expected behavior

I expect the callback to be called in the proper time, before the persist.

### Actual behavior

the method annotated with `@PreUpdate` is being called after the persist.
```
2024-10-02 12:28:56,649 INFO  [com.myc.api.app.res.UserResource] (vert.x-eventloop-thread-1) persisted with updatedOn: null
2024-10-02 12:28:56,651 INFO  [com.myc.api.app.res.UserResource] (vert.x-eventloop-thread-1) mapped object back to DTO: UserDto{name=Joana, surname=Dark, email=jane.d@bird.com, loginId=jane.d, createdBy=null, creat
edOn=null, optLock=0, updatedOn=null, id=1, units=[]}
2024-10-02 12:28:56,672 INFO  [com.myc.api.app.ent.BaseEntity] (vert.x-eventloop-thread-1) Set the Update datetime to 2024-10-02T12:28:56.672747900+01:00[Europe/Lisbon]
```

### How to Reproduce?

Just run the test: com.mycompany.api.app_mngt.UserResourceTest#testUpdate() on the attached project
[quarkus-hibernate-callback-issue.zip](https://github.com/user-attachments/files/17228756/quarkus-hibernate-callback-issue.zip)

### Output of `uname -a` or `ver`

windows 10

### Output of `java -version`

java 21

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9

**Comment by DavideD** [comment]
I will have a look

**Comment by FroMage** [comment]
Thanks!

**Comment by DavideD** [comment]
> I expect the callback to be called in the proper time, before the persist.

No persist is executed in this code. You can see in the log that only one query update is executed.
The result of this find is going to be a managed user:
```
userRepo.findById(pUserId)
```

The fact that it's managed means that any change will be applied to the database when the transaction is committed.
It also  means that the entity is now in the session.

When you reach this code:
```
.chain(e -> userRepo.persist(e).
                        .invoke(e2 -> logger.infof("persisted with updatedOn: %1s", e2.getUpdatedOn()))) ... )
```

Normally, Hibernate would throw an exception. That's because you are trying to insert an entity with an id that already exists in the database. Somebody (@FroMage ?) decided to just [skip the persist when the object is in the session in Quarkus](https://github.com/quarkusio/quarkus/blob/a98a3f91fc06c959672b67ece75516bb59b994cd/extensions/panache/hibernate-reactive-panache-common/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/common/runtime/AbstractJpaOperations.java#L42). So nothing is happening. The object doesn't get updated and the log print null.

The entity will be updated later, when the transaction is committed.

To solve this issue you can flush the value before the transaction is committed:
```java
    @PUT
    @Path("{userId}")
    public Uni<RestResponse<UserDto>> update(@RestPath("userId") Long pUserId, UserDto pUserUpdateDto) {
        return Panache.withTransaction( () -> userRepo.findById( pUserId )
                .onItem().ifNull().failWith( NotFoundException::new ).call( entity -> Mutiny.fetch( entity.getUnits() ) )
                .onItem().transform( entity -> userMapper.mergeEntityWithDtoToBeUpdated( entity, pUserUpdateDto ) )
               
                // calling .flush will execute the query immediately and now the log will be correct
                .call( e -> userRepo.flush().invoke( () -> logger.infof( "persisted with updatedOn: %1s", e.getUpdatedOn() ) ) )

                .onItem().transform( e -> {
                    UserDto dto = userMapper.mapToDto( e );
                    logger.infof( "mapped object back to DTO: %1s", dto.toString() );
                    return dto;
                } ) ).onItem().transform( RestResponse::ok );
    }
```

But, a better solution is to just update the DTO after the transaction is committed (if I understand correctly your use case):
``` java
   @PUT
    @Path("{userId}")
    public Uni<RestResponse<UserDto>> update(@RestPath("userId") Long pUserId, UserDto pUserUpdateDto) {
        return Panache.withTransaction( () -> userRepo.findById( pUserId )
                        .onItem().ifNull().failWith( NotFoundException::new )
                        .call( entity -> Mutiny.fetch( entity.getUnits() ) )
                        .map( entity -> userMapper.mergeEntityWithDtoToBeUpdated( entity, pUserUpdateDto ) )
                )
                .onItem().transform( entity -> {
                    UserDto dto = userMapper.mapToDto( entity );
                    logger.infof( "mapped object back to DTO: %1s", dto.toString() );
                    return dto;
                } ).onItem().transform( RestResponse::ok );
    }
```

**Comment by DavideD** [comment]
I'm closing this issue, but feel free to continue asking question here if you have more doubts.

**Comment by FroMage** [comment]
> Normally, Hibernate would throw an exception. That's because you are trying to insert an entity with an id that already exists in the database. Somebody (@FroMage ?) decided to just [skip the persist when the object is in the session in Quarkus](https://github.com/quarkusio/quarkus/blob/a98a3f91fc06c959672b67ece75516bb59b994cd/extensions/panache/hibernate-reactive-panache-common/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/common/runtime/AbstractJpaOperations.java#L42). So nothing is happening

Ah, yes, I thought not doing anything to persist an already managed entity would be better than throwing. But in this case I suppose it would have shown the problem faster :-/

Thanks for the investigation and sorry for suspecting a real bug!
