### ISSUE TITLE
Please update smallrye-reactive-messaging to >= 4.25.0

### ISSUE THREAD

**Issue by diversit** [quarkusio/quarkus#43659]
Could you please update the smallrye-reactive-messaging dependency to >= 4.25.0.

Due to [this MQTT buffer size issue](https://github.com/smallrye/smallrye-reactive-messaging/pull/2741) we have not been able to upgrade Quarkus after 3.12.3.
This issue causes the MQTT consumer to spontaneously disconnect.

It has been fixed and merged in 4.25.0 'last week'. (Github sucks at showing the real date)

We like to keep update to date with Quarkus but have not been able to because of this issue.

**Comment by cescoffier** [comment]
The update is planned but it's not targeting the LTS. So it will be in 3.16.x
