### ISSUE TITLE
Gradle build doesn't work if the plugin isn't in the local repository

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#4365]
**Describe the bug**
When running any Gradle task, the build fails 

**Expected behavior**
Gradle build should work

**Actual behavior**
It doesn't work. The following stacktrace is shown: 

```bash
➜  code-with-quarkus ./gradlew quarkusDev

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'code-with-quarkus'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.quarkus:quarkus-gradle-plugin:0.23.2.
     Searched in the following locations:
       - file:/home/ggastald/.m2/repository/io/quarkus/quarkus-gradle-plugin/0.23.2/quarkus-gradle-plugin-0.23.2.pom
       - file:/home/ggastald/.m2/repository/io/quarkus/quarkus-gradle-plugin/0.23.2/quarkus-gradle-plugin-0.23.2.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 404ms
```

**To Reproduce**
1. Run code.quarkus.io with this PR: https://github.com/quarkusio/code.quarkus.io/pull/163  and generate a Gradle project
2. Unzip the generated project and run `./gradlew quarkusDev`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux ggastald-laptop 5.2.15-200.fc30.x86_64 #1 SMP Mon Sep 16 15:17:36 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
```
 - GraalVM version (if different from Java): Not applicable
 - Quarkus version or git rev: 0.23.2

Additional Context: 

I don't have the quarkus-gradle-plugin in my local repository

**Comment by maxandersen** [comment]
Does your build.gradle have references to the quarkus gradle plugin as outlined in #4311 and https://quarkus.io/guides/gradle-tooling.html ? 

If it does and still fails then #4311 is way more urgent/blocker than first thought.

**Comment by gastaldi** [comment]
Yes, I have that in my settings.gradle file

Em Qui, 3 de out de 2019 19:50, Max Rydahl Andersen <
notifications@github.com> escreveu:

**Comment by gastaldi** [comment]
It looks like for some bizarre reason,  the following content is not included in the `build.gradle` generated by code.quarkus.io (which uses the classes in the `devtools-common` module) BUT it is included when the maven plugin is used to generate the project: 

```gradle
plugins {
    id 'java'
}
```

The build works if I add that manually to the build.gradle.

**Comment by maxandersen** [comment]
did you use latest master to generate via maven ? when I use mvn master I get the same issue - but for any ordinary dependency. Have to add the above too to make it work.

But this is bad if we have to tell users to list repositories 3(!) times - 2 in build.gradle and 1  in settings.gradle. 

can't be right.

**Comment by maxandersen** [comment]
from chat:

with latest gradle the following in build.gradle is enough:

```
plugins {
    id 'java'
    id 'io.quarkus'
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation enforcedPlatform("io.quarkus:quarkus-bom:${quarkusVersion}")
    implementation 'io.quarkus:quarkus-resteasy'
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
}

group 'org.acme.quarkus.sample'

version '1.0-SNAPSHOT'
```

to fix this we need to update `GradleBuildFile.java` and the `.ftl` templates and the user guide.

Ultimately we shuold see if we can simplify even further if we publish the plugin to gradle registry.
