### ISSUE TITLE
HTTP features for 1.0 tracker

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#4366]
This issues tracks all issues related to new HTTP for the 1.0 release.

- **deferred** #4367 
- [x] #4368
- [x] #4332
- [x] #4407
- **deferred** #4455

**Comment by paulrobinson** [comment]
@stuartwdouglas is this still an accurate list of what's needed for this Epic for 1.0.0?

**Comment by stuartwdouglas** [comment]
It is now, the 2nd vert.x instance will likely be deferred.

**Comment by paulrobinson** [comment]
BTW, the GitHub automation doesn't like the use of a 'dot' at the start of the list. It seems to fail to find the done issues. I've not had chance to figure out why. I made a change to #4369 (hope you don't mind) to validate this theory.

**Comment by gsmet** [comment]
@stuartwdouglas what's the status of this? I see one of the issue is still open but I'm not sure if it has been addressed or not.

**Comment by stuartwdouglas** [comment]
It has been deferred.
