### ISSUE TITLE
Reflection-free jackson serializer serializes ObjectIds different

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#43674]
### Describe the bug

If the reflection-free serializer is activated, ObjectIds are serialized differently than without the generated serializer.
Normally, the ObjectID should be serialized as a HEX string. However, the generated serializer creates a JSON object from the object ID.

My model:
```java
public class Product {

    private ObjectId id;

    public ObjectId getId() {
        return id;
    }

    public void setId(ObjectId id) {
        this.id = id;
    }
}
```
JSON without reflection-free serializer:
```json
{
  "id": "66fe4c9df58b4c036cc92298"
}
```
JSON with reflection-free serializer:
```json
{
  "id": {
    "timestamp": 1727941789,
    "date": "2024-10-03T07:49:49.000+00:00"
  }
}
```

### How to Reproduce?

I've created a small reproducer project.
https://github.com/andlinger/quarkus-reproducer/tree/quarkus-43674

### Quarkus version or git rev

3.15.1

**Comment by mariofusco** [comment]
This issue has been already fixed on the main branch as a side effect of [this commit](https://github.com/quarkusio/quarkus/commit/bd57e87aa51cc725d7e30fc65ccfdffc3561a6c9) and more specifically thanks to the introduction of the `GeneratedSerializersRegister` [here](https://github.com/quarkusio/quarkus/commit/bd57e87aa51cc725d7e30fc65ccfdffc3561a6c9#diff-2141f56144766a341e4e3abf8f11b2d67369d9f8dfb17e9b3831097b2346d14fR24).

I sent a pull request that simply reproduces the issue and demonstrates that this working on main https://github.com/quarkusio/quarkus/pull/43860

@gsmet @geoand Please let me know if I should take some action to backport this fix (and only it) on the 3.15.x stream. I'm afraid it won't be trivial to only isolate this fix from that huge change that also introduced the generated deserializers.

**Comment by mariofusco** [comment]
Can we close this issue? Is it necessary to backport this change to the 3.15.x branch?

**Comment by geoand** [comment]
Let's close and we can discuss the backport at some later point (if necessary)

**Comment by gsmet** [comment]
I wouldn't backport it. This is an experimental feature, we will iterate over the course of several versions.

We can backport simple fixes but if they are too involved, it's not worth it IMO - except if we end up having a strong demand for it.
