### ISSUE TITLE
Remove 2nd Vert.x instance

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#4367]
As part of the new HTTP work we ended up with two Vert.x instances due to some issues with RESTEasy doing blocking writes from an IO thread. This needs to be fixed and the 2nd instance removed for the 1.0 release.

**Comment by FroMage** [comment]
Well, for now @patriot1burke is working on it. My PR https://github.com/resteasy/Resteasy/pull/2170 is likely to be withdrawn.

**Comment by n1hility** [comment]
I talked to @patriot1burke and this won't make 1.0

**Comment by FroMage** [comment]
What's the reason, then?

Note that I recently discovered that the test that my PR made fail sometimes, was in fact already failing on master sometimes, and so it wasn't my doing. Which means that my PR might be working and could perhaps be used.

**Comment by emmanuelbernard** [comment]
OK so after conversation with @n1hility and @FroMage we decided to give it a shot for 1.0. Stef will resuscitate his work but talk to @stuartwdouglas and @patriot1burke first to get the hang of the latest developments.

**Comment by emmanuelbernard** [comment]
We will resync in a week to know if we give that one up or pursue for 1.0

**Comment by emmanuelbernard** [comment]
Sorry I miscalculated the time we have, so let's scrap that plan and do this after 1.0.

**Comment by emmanuelbernard** [comment]
Done unless the single loop had babies after 1.3
