### ISSUE TITLE
Undertow CacheResourceManager can cause frequent GC

### ISSUE THREAD

**Issue by prateeksharma2988** [quarkusio/quarkus#43676]
We have recently migrated to Quarkus 3.11.2 and are facing increased heap issue.

**Below is the sample code for re-producing the issue.** 

- We have an API call for which every call with path param and all calls are saved in cache as CHM and as we receive more and more hit on this url heap started to increase.

```
-  Class Name                                                                                                                                  | Shallow Heap | Retained Heap
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[79024] java.util.concurrent.ConcurrentHashMap$Node @ 0xf82048e0                                                                            |           32 |            32
|- <class> class java.util.concurrent.ConcurrentHashMap$Node @ 0xfab56f60 System Class                                                      |            0 |             0
|- key java.lang.String @ 0xf82048a8  META-INF/resources/v1/se/{p1}/sd/{p2}/key/1|           24 |           144
'- val java.util.Collections$EmptyList @ 0xfab845c0                                                                                         |           16 |            16
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

- Is there anything which could stop this internal caching by JVM in Quarkus

```java
import java.util.Collection;
import java.util.List;
import java.util.Scanner;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Stream;

public class MainTest {

    static final AtomicLong sleep = new AtomicLong(1);

    static final AtomicLong counter = new AtomicLong(1000000000);

    static void loop() {
        while (true) {
            MainTest.class.getClassLoader().getResource("META-INF/resources/my-resource/id/" + counter.get());
//            System.out.println(".");
            counter.incrementAndGet();
            try {
                Thread.sleep(sleep.get());
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }

    public static void main(String[] args) {
        new Thread(() -> loop()).start();

        Scanner scanner = new Scanner(System.in);
        while (true) {
            String cmd = scanner.nextLine();
            System.out.println("delay " + sleep.get() + " /// " + counter);
            if (cmd.contains("u")) {
                sleep.set(sleep.get() / 2);
            }
            if (cmd.contains("d")) {
                sleep.set(1 + sleep.get() * 2);
            }

            printMem();
        }
    }

    private static void printMem() {
        Runtime rt = Runtime.getRuntime();
        long total_mem = rt.totalMemory() / (1024*1024);
        long free_mem = rt.freeMemory() / (1024*1024);
        long used_mem = (total_mem - free_mem)  / (1024*1024);
        System.out.println("Amount of used memory: " + used_mem + " / " + total_mem);

    }

}
```

**Comment by geoand** [comment]
Does the same problem occur with Quarkus `3.15.1`?

**Comment by gsmet** [comment]
If you have a heap dump, you should be able to find out what is the path of this CHM. Usually you have something to get to the path to the root. That will be an interesting piece of information.

Also, your example doesn't use Quarkus at all? Could you maybe create a small Maven reproducer inside a Quarkus project if it's something you can only reproduce with Quarkus?

You can either push it to a GitHub repository or attach a Zip file to your comment. You have a `Paste, drop, or click to add files` link just below the comment textarea.

**Comment by prateeksharma2988** [comment]
[sample-project-quarkus-main.zip](https://github.com/user-attachments/files/17246263/sample-project-quarkus-main.zip)

**Comment by geoand** [comment]
> Is there any setting in Quarkus which could stop this caching or should avoid the frequent Major GC.

Not currently. 

We would essentially need update [this](https://github.com/quarkusio/quarkus/blob/3.15.1/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java#L206)

**Comment by prateeksharma2988** [comment]
We planned to migrate to quarkus from TOMEE and after almost more than 2 months of migration of different microservices we are blocked to rollout our delivery with this issue. Can you suggest something we can do to avoid this caching.

Or any tentative timeline we can have this fix, so that we can plan accordingly our release.

@geoand @geoand

**Comment by gsmet** [comment]
I wonder if there's not something very odd because from what I can see, the big CHM you have in your heap dump is the `resourceCache` of the JDK `AppClassLoader` and I wouldn't expect us to use this CL to load the local resources - except if they don't exist... but given `KnownPathResourceManager`, I would have expected us to only serve the resources we know about. But we are not actually checking the set of known `files` when getting the resource in `KnownPathResourceManager`, it might be the problem.

I'm not exactly versed in this area so it's all handwaving at this stage.

Now, I'm not entirely sure we only need to serve the known files but I think that's the intent and maybe a simple patch like the following might actually fix your issue:

```diff
diff --git a/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/KnownPathResourceManager.java b/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/KnownPathResourceManager.java
index 0e665ab14a5..f0abd8c0723 100644
--- a/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/KnownPathResourceManager.java
+++ b/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/KnownPathResourceManager.java
@@ -69,6 +69,9 @@ public Resource getResource(String path) throws IOException {
         if (directories.contains(path)) {
             return new DirectoryResource(path);
         }
+        if (!files.contains(path)) {
+            return null;
+        }
         return underlying.getResource(path);
     }
 
```

If you follow the instructions in https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#building-main , and apply this small patch before building, you should be able to test this theory with your code base.

You would also have to check that it actually still serves the existing resources properly :).

How do you reproduce the issue with your reproducer? Because I might be blind but the test is apparently only doing a single request so I don't think it will do anything.

**Comment by geoand** [comment]
> How do you reproduce the issue with your reproducer? Because I might be blind but the test is apparently only doing a single request so I don't think it will do anything.

If you give us the information, we can try it out ourselves and likely come up with a patch (that is hopefully backportable to Quarkus 3.15) rather quickly.

**Comment by prateeksharma2988** [comment]
[JMX.zip](https://github.com/user-attachments/files/17256212/JMX.zip)

@gsmet @geoand we just hit the same request with the different path param , this increases our resource cache. attached is JMX we are using to replicate.

**Comment by prateeksharma2988** [comment]
@gsmet @geoand Let us try at our end also , Will let you guys know .... Thanks for Your Support 👍

**Comment by prateeksharma2988** [comment]
@gsmet @geoand Thanks Guys ...... We applied the patch and its working fine now and heap is not increasing now.

**Comment by gsmet** [comment]
OK, I will prepare a PR to see how CI reacts to it. I hope it's not breaking anything.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/43694 for CI to test.

**Comment by gsmet** [comment]
Thanks for the great report and sharing the information to get to the bottom of it!
