### ISSUE TITLE
Reactive redis client,  SCAN  .toMulti()  don't return all elements

### ISSUE THREAD

**Issue by adriano-moreira** [quarkusio/quarkus#43684]
### Describe the bug

Redis doc say: https://redis.io/docs/latest/commands/scan/
>SCAN family functions do not guarantee that the number of elements returned per call are in a given range. The commands are also allowed to return zero elements, and the client should not consider the iteration complete as long as the returned cursor is not zero.

Quarkus class io.quarkus.redis.runtime.datasource.ScanReactiveCursorImpl
currently has the filter

```java
 .whilst(m -> !m.isEmpty() && hasNext())
```

### Expected behavior

but redis command scan can return a empty set of key, and a cursor different of 0

I think the correct filter is
```java
 .whilst(m -> hasNext())
```

### Actual behavior

Quarkus Redis client stop retrieve elements when Redis return 0 elements, even though don't scan all keys

### How to Reproduce?

to reproduce need a scan command with count less than interval of other key than don't match scan

```java
package me.demo;

import io.quarkus.redis.datasource.ReactiveRedisDataSource;
import io.quarkus.redis.datasource.keys.KeyScanArgs;
import io.quarkus.test.junit.QuarkusTest;
import io.smallrye.mutiny.Multi;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.assertEquals;

@QuarkusTest
class ReactiveRedisScanTest {

    @Inject
    ReactiveRedisDataSource reactiveRedisDataSource;

    @Test
    void useScanWithToMulti() {
        var valueCommands = reactiveRedisDataSource.value(String.class);
        var keyCommands = reactiveRedisDataSource.key();

        //create a list with groupA and groupB
        var values = new ArrayList<String>();
        for (int i = 0; i < 100; i++) {
            values.add("groupA:" + i);
        }
        for (int i = 0; i < 10; i++) {
            values.add("groupB:" + i);
        }

        //persist all item from list
        Multi.createFrom().iterable(values)
                .onItem().call(v -> valueCommands.setex(v, 60, v))
                .collect().with(Collectors.counting()).await().indefinitely();

        //scan only groupB, but in redis the first 100 key belongs to groupA
        Long countedByScan = keyCommands
                .scan(new KeyScanArgs().match("groupB:*").count(10))
                .toMulti()  //<- Here are the problem
                .collect().with(Collectors.counting())
                .await().indefinitely();
        
        //expected is 10, but countedByScan value is less
        assertEquals(10, countedByScan);
    }

}
```

### Quarkus version or git rev

3.15.1

**Comment by cescoffier** [comment]
Nice catch! Fancy a PR (with your test and fix)?

**Comment by adriano-moreira** [comment]
I will try do a PR, this will be my first PR, ever

I see this affect too reactive hscan/scan/zscan commands
and method .toIterable() of blocking version, than use reactive under the hood

**Comment by cescoffier** [comment]
Yes, all scan method have the same check I believe. I wonder why I did it that way. 

Should we check each scan commands individually?

**Comment by adriano-moreira** [comment]
> Should we check each scan commands individually?

I've had to write code like this before, when needed add a `if(!keys.isEmpty())` because  `cursor.next()` return a empty list
```java 
        KeyScanCursor<String> cursor = keyCommands.scan(new KeyScanArgs().match(padrao).count(100));
        while (cursor.hasNext()) {
            var keys = cursor.next();
            if(!keys.isEmpty()) {
                keyCommands.del(keys.toArray(String[]::new));
            }
        }
```

I do a PR  just fixing .toMulti

might be a good idea, modify  `.next()` to repeat until return something or return cursor 0(end of scan)
