### ISSUE TITLE
quarkus-logging-json ignores additional-fields configured via environment variables

### ISSUE THREAD

**Issue by mickroll** [quarkusio/quarkus#43695]
### Describe the bug

Configuring additional fields that should be included in the log record only works in the style `quarkus.log.console.json.additional-field."example".value=hello world`, but not as environment variable `QUARKUS_LOG_CONSOLE_JSON_ADDITIONAL_FIELD__FIELD_NAME__VALUE`, despite this being the exact example given in the documentation.

documentation: https://quarkus.io/guides/logging#quarkus-logging-json_quarkus-log-console-json-additional-field-field-name-value

### Expected behavior

Documented example `QUARKUS_LOG_CONSOLE_JSON_ADDITIONAL_FIELD__FIELD_NAME__VALUE` works

### Actual behavior

Documented example `QUARKUS_LOG_CONSOLE_JSON_ADDITIONAL_FIELD__FIELD_NAME__VALUE` does not work, the field is not included. It looks like the configuration is ignored, where other `QUARKUS_LOG_CONSOLE_*`-config works as expected.

### How to Reproduce?

Reproducer:  https://github.com/mickroll/quarkus-demonstrator/tree/json-config-additional-field

Steps:
1. see pom.xml for configured environment variables (some work, but additional-fields config is ignored)
    - ```
       
      <QUARKUS_LOG_CONSOLE_JSON_ADDITIONAL_FIELD__FIELD_NAME__VALUE>hello</QUARKUS_LOG_CONSOLE_JSON_ADDITIONAL_FIELD__FIELD_NAME__VALUE>
      
      <QUARKUS_LOG_CONSOLE_JSON_ADDITIONAL_FIELD__SIMPLE__VALUE>hello</QUARKUS_LOG_CONSOLE_JSON_ADDITIONAL_FIELD__SIMPLE__VALUE>
      ```
2. `mvn test`
3. manually check output

result looks like:
```
{"timestamp":"2024-10-04T13:24:54.453337122+02:00","sequence":13,"loggerName":"org.example.StartupLoggingTest","level":"INFO","field_name_for_message":"message from test","threadName":"main","threadId":1,"mdc":{},"ndc":""}
```
but should include the configured values:
```
FIELD_NAME: "hello",
SIMPLE: "hello"
```

### Output of `uname -a` or `ver`

Linux <host> 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9

### Additional information

Side-question, maybe for considering when fixing the bug: is there a way to have a lower-case map key, when configuring using environment variables?
With `quarkus.log.console.json.additional-field."Example Key, with special chars!".value=hello world` i have quite some freedom for the key. How do i achieve this using environment variables?
Why is this important? Json log output is likely used for machine consumption, and json property names are case sensitive. In our use case, we would need keys like this: `example_key`.

`io.quarkus.logging.json.runtime.AdditionalFieldConfig` gives a hint for `fieldName1=value1,fieldName2=value2`, but i did not get this to work, either, and it doesn't look like a proper way for handling complex hierarchical values. Is this javadoc correct?

**Comment by radcortez** [comment]
> Side-question, maybe for considering when fixing the bug: is there a way to have a lower-case map key, when configuring using environment variables?
> With `quarkus.log.console.json.additional-field."Example Key, with special chars!".value=hello world` i have quite some freedom for the key. How do i achieve this using environment variables?
> Why is this important? Json log output is likely used for machine consumption, and json property names are case sensitive. In our use case, we would need keys like this: `example_key`.

If your environment supports it, you can use dotted format names.

**Comment by gsmet** [comment]
@radcortez I see you made it a logging issue instead of a config issue, do you know what's going on?

**Comment by radcortez** [comment]
> [@radcortez](https://github.com/radcortez) I see you made it a logging issue instead of a config issue, do you know what's going on?

Yes.

This is expected due to https://quarkus.io/guides/config-reference#environment-variables. When `QUARKUS_LOG_CONSOLE_JSON_ADDITIONAL_FIELD__FIELD_NAME__VALUE` is set alone, it is converted to `quarkus.log.console.json.additional.field."field.name".value`. Note that we cannot know from the environment variable name that `additional.field` should become `additional-field.`. The recommendation is to include an empty property in `application.properties` as `quarkus.log.console.json.additional.field."field.name".value` so we can disambiguate the case.

We can improve this by moving to `@ConfigMapping,` which is a bit smarter at picking up known configuration names like `additional-field`. However, using user-defined names like `field-name` would still require disambiguation.

@mickroll please use `quarkus.log.console.json.additional.field."field.name".value` and override it with an environment variable.

**Comment by mickroll** [comment]
Thank you for the clarification
