### ISSUE TITLE
Make native image test use the test profile or not

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4371]
I know we had some conversations recently on the subject but I don't recall the conclusion.
It was related to the shift of hibernate's import file feature having different defaults in prod vs dev.

So let's capture what we really want here and see if we need code change and / or documentation changes before 1.0

Today @cescoffier and @agoncal got hit by IT run in prod and thus confusion.

**Comment by FroMage** [comment]
My suggestion was that if you want to test a native-image you need to build it with the test profile.

**Comment by gsmet** [comment]
I agree on that. We need to find a workflow to do that that is Maven compatible and not too cumbersome.

Typically, with a standard Maven behavior, you would have:
```
$ mvn clean install -Dnative
> ...
> build test native image
> test native image
> build prod native image
```

```
$ mvn clean install -DskipITs -Dnative
> ...
> build prod native image
```

That works.

Now, what I'm wondering is how we can only build the test image and run the tests (and not build the prod one) while still being in a somewhat natural Maven workflow. Is it something we want to expose to the users (we will need it for our CI but we can have an internal thing)? If yes, how?

**Comment by rsvoboda** [comment]
> ... build test native image
> ... test native image
> ... build prod native image

How is ensured that test profile and prod profile are functionally the same without any chance for regression? With my super-skeptical hat on: Different bits => no guarantees.

**Comment by gsmet** [comment]
Well, you won't have more guarantees than when you use H2 to test whereas you use a PostgreSQL instance in production. There is a tradeoff for that. But the current situation makes it's very cumbersome to properly test a Java + native image application as both are using different profiles during the test phase.

**Comment by cescoffier** [comment]
In #4430 I've allowed the user to specify the profile he wants.

**Comment by stuartwdouglas** [comment]
I think this can be closed, there are no changes around this planned, I don't think we want to build separate native image test executables.
