### ISSUE TITLE
Dev-ui ignores `quarkus.rest.path` in endpoint scores

### ISSUE THREAD

**Issue by FreifeldRoyi** [quarkusio/quarkus#43735]
### Describe the bug

When using the property `quarkus.rest.path`, it is being ignored by `REST endpoint scores` and in `Resource Not Found` error screent
Note: It is not ignored by opanapi extension

### Expected behavior

If `quarkus.rest.path=my-service` for an endpoint path `/my-endpoint`, the REST endpoint scores and 404 error screen should show `/my-service/my-endpoint`.

### Actual behavior

Both screens show `/my-endpoint`

**Comment by gsmet** [comment]
@phillip-kruger could you have a look at this one when you have some cycles? Presenting incorrect paths is not great.

**Comment by phillip-kruger** [comment]
Yes, it's on my to-do list

**Comment by nikolassv** [comment]
Could this be loosly related to #40240? The problem seems to concern both `quarkus.rest.path` and `quarkus.http-root.path` config properties.
