### ISSUE TITLE
Document purpose and usage of `io.quarkus.arc.arquillian.DeploymentClassLoader`

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#43731]
### Description

It's not clear what the purpose and usage of `io.quarkus.arc.arquillian.DeploymentClassLoader` is in the `arc/tcks/arquillian` submodule. It should at least be documented what the purpose and expected behavior of this class loader is.

/cc @Ladicek

**Comment by manovotn** [comment]
I think the need was to have a single CL that has access to both, app classes and classes generated by Arc (plus the `ComponentsProvider`).
But I wouldn't bet on it at this point; maybe @Ladicek remembers more :-)

**Comment by Ladicek** [comment]
Yeah, @manovotn is right on the money. The TCK runner creates a directory to which it puts the ShrinkWrap `Archive` and all classes and resources generated by ArC. The CL then loads classes and resources from this directory.
