### ISSUE TITLE
AppCDS docs on usage with JIB are slightly misleading

### ISSUE THREAD

**Issue by DeMol-EE** [quarkusio/quarkus#43733]
In the documentation on AppCDS, it is stated that "simply setting `quarkus.package.jar.appcds.enabled` to `true`" is enough when using the `quarkus-container-image-jib` extension, but it is important to also set `quarkus.package.jar.appcds.use-container` to `false` (assuming that the choice for jib implies that docker is not available). Does anyone agree that it might be better to explicitly mention this?

**Comment by geoand** [comment]
Can you elaborate a little more on this?

Thanks

**Comment by DeMol-EE** [comment]
Sure. I was reading [this blog post on project Leyden](https://quarkus.io/blog/quarkus-and-leyden/), which lead me to [Quarkus’ AppCDS guide](https://quarkus.io/guides/appcds). There, I was reminded about jib. I remembered reading about it before on [the container image guide](https://quarkus.io/guides/container-image) but I had never given it much attention because I skipped straight to docker (which was familiar).
After reading the blog post, I was excited about both technologies, especially because the AppCDS guide mentions that it’s almost trivial to do when using jib. So, I set out on an undertaking to migrate all our services from docker to jib, and, in the process, also opt-in to AppCDS. As the AppCDS guide suggests, I added the flag `-Dquarkus.package.jar.appcds.enabled=true` to our maven build command, but was a little surprised by errors coming from AppCDS about the absence of a docker environment. I re-read both guides to see if I missed anything but didn’t find any clues until I started digging further online to discover the `quarkus.package.jar.appcds.use-container` flag.
I had falsely assumed that, given that we were now also using jib, the default for this flag would be "false", but I was mostly surprised I hadn’t read about this flag in either guide.
Don’t get me wrong, Quarkus still makes it child’s play to use jib and AppCDS; I merely wanted to suggest perhaps adding the "use-container" flag to either (or both) guides. What do you think?

**Comment by geoand** [comment]
Thanks a lot!

Your description is spot on (took me a while to remember how this works).

Would you like to enhance the documention along the lines of your proposal?

**Comment by DeMol-EE** [comment]
I could give it a go, sure, but now I’m wondering if it wouldn’t make more sense to change the default of the flag when it detects jib is used. Is that possible?

**Comment by geoand** [comment]
I'll have to look at it when I have some time

**Comment by geoand** [comment]
So IIUC, the machine on which you are building the container image does not have access to Docker?

In that case, setting `quarkus.package.jar.appcds.use-container=false` is indeed needed, however you need to make sure that the Java version used on that machine is **exactly** the same as the one used in the container image.

**Comment by DeMol-EE** [comment]
Indeed. So I suppose it isn't that trivial: jib can not just figure out which kind of image to build, this needs to be aligned with the Java version running the build, which could be anything. If this is working for me at this point in time, I guess I got lucky!
However, does having a docker environment change much? Perhaps then the AppCDS plugin is smart enough to use a container image that matches the one from jib?
Even so, doesn't it sort of defeat the purpose of jib, then? Though I suppose it is still nice not to have dockerfiles...

**Comment by geoand** [comment]
> However, does having a docker environment change much?

What it allows us to do is pull the base image and use the Java version from it to run the AppCDS creation process locally.

> Perhaps then the AppCDS plugin is smart enough to use a container image that matches the one from jib?

That is exactly what is happening.

> Even so, doesn't it sort of defeat the purpose of jib, then? Though I suppose it is still nice not to have dockerfiles...

Jib does docker-less push, not build and that's only one of its selling points. But I do see your point.

**Comment by DeMol-EE** [comment]
Thanks for clearing that out. I need to take another look at our pipeline to ensure our AppCDS setup actually works. Perhaps I'll just add docker back to the environment (it's available anyway) and still stick to jib for the simplified setup.
I'll see if I can free some time to prepare a PR with an extra sentence for the AppCDS guide mentioning the use-container flag, if that's still OK?

**Comment by geoand** [comment]
Definitely!

**Comment by DeMol-EE** [comment]
I’ve opened https://github.com/quarkusio/quarkus/pull/43946
