### ISSUE TITLE
Deprecate or remove `io.quarkus.test.common.DefineClassVisibleClassLoader`

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#43730]
### Description

The `io.quarkus.test.common.DefineClassVisibleClassLoader` class should not be used. If a class has to be defined for a test, normally `Lookup.defineClass` would be the appropriate thing to use.

There appears to be no usages of this class at this time.

/cc @geoand

**Comment by geoand** [comment]
I don't even remember why this was added, but it was probably for some old reason that no longer applies
