### ISSUE TITLE
CORS Regex Header Allow-Credentials Bug

### ISSUE THREAD

**Issue by GeorgeDanicico** [quarkusio/quarkus#43736]
### Describe the bug

When using regex for CORS origins, it seems that when there is a match between the regex and the Origin, it seems that `Access-Control-Allow-Credentials` header is false, and according to the documentation it should be true. Am I missing something? This can be fixed by declaring the property, but I was just curious if it is a bug.

### Expected behavior

The header `Access-Control-Allow-Credentials` should be true when the regex matches the Origins.

### Actual behavior

If the property `quarkus.http.cors.access-control-allow-credentials` is not mentioned and if the regex matches the origin, the header's value is false.

**Comment by gsmet** [comment]
Any chance you could prepare a small Maven reproducer for the issue? You can attach it as a zip to your description or comment. Thanks!

**Comment by GeorgeDanicico** [comment]
Sure. I have created the zip. I also attached some images with the curls. In the first image, the cors.origins is set to `https://app.mydomain.com` and in the second image it is set to `/https://\\.*mydomain\\\\.com/`
![Image](https://github.com/user-attachments/assets/37a5f973-3f67-4bb4-b8e0-3b14b1b0c669)
![Image](https://github.com/user-attachments/assets/b9ee5acf-da64-4a2e-b1f7-59483647aeee)
[issue.zip](https://github.com/user-attachments/files/17356951/issue.zip)

**Comment by gsmet** [comment]
Thanks for the reproducer. From what I can see, it looks like an oversight. I'm working on a patch.
