### ISSUE TITLE
ArC: improve support for active/inactive beans

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#43765]
### Description

We now have initial support for active/inactive beans in ArC, see #41810. Here are some ideas that would make that better:

We could add an `@Active` qualifier to inject only active beans into a `List`, similarly to `@All`. Alternatively, we could add something like this to `InjectableInstance`:
```java
default List<T> listActive() {
    return handlesStream().filter(h -> h.getBean().isActive()).map(InstanceHandle::get).toList();
}
```
- [x] Done in #43803

We might need to add the ability to use an exception as a cause of an inactive bean (in `ActiveResult`).

We might want to modify `Instance.isUnsatisfied()`/`isAmbiguous()` to remove inactive beans. There was also an idea to make inactive beans suppressed, but we cannot do that, because we sometimes need to access metadata of inactive beans through `Instance` (notably, to decide if some other bean is active or inactive, and use their `ActiveResult` as a cause). Perhaps this reason also precludes the modification of `isUnsatisfied()`/`isAmbiguous()`, need to think more about it.

We should add active/inactive support to ArC dev UI.
- [x] Done in #43781

Not sure if there's more.

**Comment by Ladicek** [comment]
Also CC @yrodiere

**Comment by manovotn** [comment]
> Not sure if there's more.

@Ladicek we could also modify Dev UI to mark beans that are possibly inactive in your app.

**Comment by Ladicek** [comment]
I actually think we _shouldn't_ modify `InjectableInstance.isUnsatisfied()`/`isAmbiguous()`, because that would make the result of these methods inconsistent with the behavior of `get()`/`iterator()`/etc.

This means the only unfinished thing from the list is supporting an exception as an `ActiveResult` cause, but that's not a terribly big deal. And perhaps some more user-friendly way of obtaining only active beans, but we need more feedback to actually consider something.

Therefore, closing this as done.
