### ISSUE TITLE
Support for Adding Schema Metadata (e.g., @Description, @NonNull) to Attributes Expanded via @Source in GraphQL Schema

### ISSUE THREAD

**Issue by chberger** [quarkusio/quarkus#43773]
### Description

Currently, when using a method with a `@Source`-annotated parameter to expand a `type` in a `GraphQL` schema, it seems that adding schema metadata such as `@Description` or `@NonNul` to the method does not affect the corresponding attribute in the GraphQL schema.

For example, in the official Quarkus GraphQL example:
```java
public List<Hero> heroes(@Source Film film) { 
    return service.getHeroesByFilm(film);
}
```

Annotating the `heroes` method with `@NonNull` or `@Description` does not modify the heroes attribute in the schema generated for the Film type.

It would be useful if the GraphQL extension could support adding these metadata annotations (e.g., for descriptions or required fields) to such attributes expanding the API dynamically. If this is already achievable through another procedure, please let me know, and feel free to disregard this feature request. Otherwise, it would be a valuable feature for improved schema documentation and validation.

**Comment by jmartisk** [comment]
This does look like a bug to me. @mskacelik is going to take a look :)

**Comment by chberger** [comment]
@mskacelik Do you have any updates on this? This feature would be immensely helpful, as it’s currently preventing us from upgrading from `Quarkus 3.8` to `Quarkus 3.15`. The main issue is that we can't generate an identical `graphql.schema` after the upgrade. In the previous LTS version, due to an older dependency on smallrye-graphql, it was possible to declare a field name and a source field name identically, allowing us to add metadata at least via the field name, which ended up the `graphql.schema`. However, since this change https://github.com/smallrye/smallrye-graphql/issues/2064, declaring a field and a source method with the same name is no longer possible.

While I understand the rationale behind this change, a fix would be greatly appreciated so we can add schema meta annotations to source methods as well. Thank you!

**Comment by chberger** [comment]
Yes, you understood the issue correctly. I didn’t expect it to work, but in my complex enterprise project, it doesn’t. I’ll try to simplify my project to see if the issue might be caused by other side effects or if I can create a reproducible example from it.

**Comment by chberger** [comment]
After further investigation, it turns out the problem was on my end and not with the code. 🤦 The metadata is generated as expected. Sorry for any confusion or trouble this might have caused.
