### ISSUE TITLE
Brotli doesn't work with mixed architectures on devel and runtime

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus#43770]
### Describe the bug

Using dependency `com.aayushatharva.brotli4j:brotli4j` does not work with quarkus on openshift, if I'm compiling app locally and my local machine has different architecture that OCP. I've encountered it on linux-x86_64 locally and Aarch64 on OCP.

Reason is, that brotli requires runtime dependency `com.aayushatharva.brotli4j-native-<arch>`. And if devel and deployment architectures differ, it will get wrong dependency. Brotli detect the architecture itself in pom using profiles like:
```
<profile>
    <id>linux-x86_64</id>
    <activation>
        <os>
            <family>Linux</family>
            <arch>amd64</arch>
        </os>
    </activation>
    <dependencies>
        <dependency>
            <groupId>com.aayushatharva.brotli4j</groupId>
            <artifactId>native-linux-x86_64</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
    </dependencies>
</profile>
```
But this detection happens at build time, and if app is deployed to OCP afterwards, it will fail on something like:
`Caused by: java.lang.UnsatisfiedLinkError: Failed to find Brotli native library in classpath: /lib/linux-aarch64/libbrotli.so`

This issue can be overcome by manually adding correct dependency. But it would be nice for devs to have a way to solve this seamlessly.

Also quarkus-bom defines only version for main brotli4j and for com.aayushatharva.brotli4j:native-linux-x86_64. Would be nice to also include other architectures or other way, to use brotli4j for other archs with same version.

### Output of `java -version`

17

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by geoand** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
We have to rework the brotli dependencies as the profile approach we have right now does not work with Gradle.

However, the only other solution is to include all architectures which will increase the size of the application significantly. 

So we are looking for a better solution, even if it would fix that problem.

**Comment by zakkak** [comment]
> Using dependency com.aayushatharva.brotli4j:brotli4j does not work with quarkus on openshift, if I'm compiling app locally and my local machine has different architecture that OCP. I've encountered it on linux-x86_64 locally and Aarch64 on OCP.

@mocenas so you do a 2-step build as described in https://quarkus.io/guides/building-native-image#separating-java-and-native-image-compilation right? You deploy/package on x86_64 and then try to do the native-image compilation on AArch64.

**Comment by mocenas** [comment]
> [@mocenas](https://github.com/mocenas) so you do a 2-step build as described in https://quarkus.io/guides/building-native-image#separating-java-and-native-image-compilation right? You deploy/package on x86_64 and then try to do the native-image compilation on AArch64.

In this case I'm not doing native-image compilation. Not as quarkus knows it. I'm deploying it to openshift and in this case (if I'm not wrong):
1. My local machine is compiling the app into jar.
2. Openshift is "compiling"/building the jar into docker container.
But final container is still working with jar, not native binary.

**Comment by cescoffier** [comment]
I guess you do a binary build, which means that OpenShift builds a container using a jar built on your machine. Am I right?

**Comment by mocenas** [comment]
> I guess you do a binary build, which means that OpenShift builds a container using a jar built on your machine. Am I right?

Yes that should be right.

**Comment by cescoffier** [comment]
This is now documented in https://quarkus.io/version/main/guides/vertx-reference#brotli4j-and-cross-platform-support. Also, the BOM now contains all the platforms.
