### ISSUE TITLE
websocket-next api - missing user properties map

### ISSUE THREAD

**Issue by fiorenzino** [quarkusio/quarkus#43772]
### Description

In the jakarta api for websockets we have the possibility to associate the session to some user properties map:
this is not possibile in the new api.
That is useful to fetch and filter the websocket session by some custom property and send a message in selective way.

The use case is the following:
```
@ServerEndpoint("/wsk/race/{uuid}")
 @Singleton
public class TRaceWsk {

    Map<String, Session> sessions = new ConcurrentHashMap<>();


    @OnOpen
    public void onOpen(Session session, @PathParam("uuid") String race_uuid) {
        session.getUserProperties().put("username", "xxxxx_"+System.milliseconds());
        session.getUserProperties().put("race_uuid", race_uuid);
        sessions.put(generatedString, session);
    }


      public void observeAsync(@ObservesAsync String race_uuid) {
            sessions.values().forEach(s -> {
                String race_uuid = (String) s.getUserProperties().get("race_uuid");
                s.getAsyncRemote().sendObject(json, result -> {
                       .....
                });
            });
       }

    }
```

**Comment by mkouba** [comment]
Indeed, you cannot store some arbitrary data in the context of a WebSocket session. On the other hand, you can obtain the path parameters, creation time and the data of the initial HTTP request from the connection object.

So your observer could be rewritten as:

```java
class AnyBean {

   public void observeAsync(@ObservesAsync String race_uuid, OpenConnections connections) {
      for (WebSocketConnection c : connections) {
         String race_uuid = c.pathParam("race_uuid");
         // do something with the path param...
         String username = "xxxx_" + c.creationTime().toEpochMilli();
         // do something with the username...
         c.sendText(json).subscribe(...);
      }
   }
}
```

An idiomatic way to store some arbitrary data in the context of a WebSocket session is to use a `@SessionScoped` CDI bean - each connection is [associated with its own CDI session context](https://quarkus.io/guides/websockets-next-reference#cdi-scopes). This `@SessionScoped` bean can be injected in the endpoint and used within an endpoint callback invocation. However, this bean is not available outside an endpoint callback.

As a workaround you can store the data in a map where the key is the connection id:

```java
@ApplicationScoped
public class Usernames {

   private final Map<String,String> names;

   void connectionOpened(@ObservesAsync @Open WebSocketConnection c) {
      names.put(c.id(), "xxxxx_"+System.milliseconds()); 
   }

   void connectionClosed(@ObservesAsync @Closed WebSocketConnection c) { 
      names.remove(c.id());
   }

   public void String getUsername(String id) {
      return names.get(id);
   }
}
```

And then use it like:
 
```java
class AnyBean {

   public void observeAsync(@ObservesAsync String race_uuid, OpenConnections connections, Usernames usernames) {
      for (WebSocketConnection c : connections) {
         String username =usernames.getUsername(c.id());
         // do something with the username...
         c.sendText(json).subscribe(...);
      }
   }
}
```

`jakarta.websocket.Session.getUserProperties()` returns `Map<String, Object>` which is not a very convenient API. We should try to provide something more usable.

**Comment by fiorenzino** [comment]
Thanks for the workaround. 
Happy to see your commit.

wow!
