### ISSUE TITLE
Rest: shorten the names of the generated classes

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#43786]
### Description

There seems to be no reason for the names to be so looong.

For example `io.quarkus.resteasy.reactive.server.runtime.exceptionmappers.AuthenticationFailedExceptionMapper$GeneratedExceptionHandlerFor$AuthenticationFailedException$OfMethod$handle`. The simple name has 111 chars in this particular case.

The  `ArC > Beans` view in the Dev UI does not look good. Also every call site of this class must store this name in the constant pool ;-).

Zulip discussion: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Loooong.20names.20of.20generated.20classes.20in.20resteasy-reactive

**Comment by cescoffier** [comment]
Any good solution outside computing a hash of the name?

**Comment by mkouba** [comment]
> Any good solution outside computing a hash of the name?

A computed hash is fine IMO.

**Comment by cescoffier** [comment]
Hashes work but make debugging harder and logger names useless. But if that's the only solution, we must live with it.

**Comment by maxandersen** [comment]
besides devui would these not show up in stacktraces too? all for not too long names but shouldn't also just be a hashid as name brings meaning :)

**Comment by cescoffier** [comment]
If we can keep the meaningful part and append a hash, it would provide a good experience.

**Comment by geoand** [comment]
#44418 would make the name something like: `io.quarkus.resteasy.reactive.server.runtime.exceptionmappers.AuthenticationFailedExceptionMapper$ExceptionMapper$123456`
