### ISSUE TITLE
Messager companions - method for getting all available messages

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#43793]
### Description

First off, apologies if this functionality exists and couldn't find it, but it seems like the `KafkaCompanion` doesn't support awaiting for all available messages, only the specified number of messages. This makes it hard to perform certain test cases.

Of note is I have tried simply awaiting for single messages in a loop, but that ended up with never actually exiting and always returning the same message. This seems infeasible without additional support from the companion.

### Implementation ideas

A utility method or way to specify to wait for all available messages, either within a timeframe or awaiting after the last message was received.

**Comment by cescoffier** [comment]
Can you reopoen this issue in https://github.com/smallrye/smallrye-reactive-messaging. The Kafka companion is not a Quarkus thing.

**Comment by cescoffier** [comment]
should be reported upstream.
