### ISSUE TITLE
WebSockets Next: make it possible to filter OpenConnections by userDataKey

### ISSUE THREAD

**Issue by fiorenzino** [quarkusio/quarkus#43790]
### Description

Hi @mkouba,
Inside OpenConnections we have some useful methods as:

```
    default Collection<WebSocketConnection> findByEndpointId(String endpointId) {
        return stream().filter(c -> c.endpointId().equals(endpointId)).toList();
    }

  
    default Optional<WebSocketConnection> findByConnectionId(String connectionId) {
        return stream().filter(c -> c.id().equals(connectionId)).findFirst();
    }

```

Why don't add a filter by UserData?

```
   Optional<List<WebSocketConnection>> findByUserData(String key){}
```

**Comment by mkouba** [comment]
I'm not sure to be honest. In your example the returned list would contain all connections that have some data for the given key but you might also need to match a specific value. Or the other way around - to match all connections that don't have some data. So I think that it would be better to leverage the Stream API for similar use cases:

```
connections.stream().filter(c -> c.userData().get(TypedKey.forString("username")) != null).toList();
```

**Comment by mkouba** [comment]
> it was a short way to do stream filtering. in my mind, was a similar think as you do with endpointId and connectionId. we can survive without!

Yeah, I know. The point is, for endpointId and connectionId it's pretty obvious. For user data - not so much. That's what I tried to explain in my previous comment.

> we can survive without!

👍 Let's reopen this issue once we know there are more people who would find this useful.
