### ISSUE TITLE
Quarkus test ignores maven settings

### ISSUE THREAD

**Issue by gcollin** [quarkusio/quarkus#4383]
My maven settings.xml contains a mirror section to use a local nexus and bypass a proxy my company is using.
`<mirrors>
	<mirror>
      <id>AdpNexus</id>
      <mirrorOf>springframework,commonsmath,central</mirrorOf>
      <name>Nexus in CRP</name>
      <url>https://nexus-adp-tools-agcs.apps.xxx/repository/maven-public</url>
  </mirrors>
`
**The sample quarkus project is building fine, but running maven test** show an error:

'Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact io.quarkus:quarkus-bom:pom:0.23.2 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection timed out: connect
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:178)
'
**You see Quarkus is trying to download directly from maven central repo and not using my nexus anymore:**

Strangely, **mvn compile quarkus:dev correctly uses the mirror**:

'C:\apps\jdk18\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\devs\portal-demo\portal-bff -Dmaven.home=C:\apps\maven -Dclassworlds.conf=C:\apps\maven\bin\m2.conf -Dmaven.ext.class.path=C:\apps\IdeaEap\plugins\maven\lib\maven-event-listener.jar -javaagent:C:\apps\IdeaEap\lib\idea_rt.jar=53733:C:\apps\IdeaEap\bin -Dfile.encoding=UTF-8 -classpath C:\apps\maven\boot\plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version2019.3 compile quarkus:dev
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.agcs.online.portal:portal-bff >------------------
[INFO] Building portal-bff 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ portal-bff ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ portal-bff ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus-maven-plugin:0.23.2:dev (default-cli) @ portal-bff ---
Downloading from AdpNexus: https://nexus-adp-tools-agcs.apps.tools.adp.allianz/repository/maven-public/io/quarkus/quarkus-devtools-common/0.23.2/quarkus-devtools-common-0.23.2.pom
Downloaded from AdpNexus: https://nexus-adp-tools-agcs.apps.tools.adp.allianz/repository/maven-public/io/quarkus/quarkus-devtools-common/0.23.2/quarkus-devtools-common-0.23.2.pom (3.3 kB at 1.9 kB/s)
Downloading from AdpNexus: https://nexus-adp-tools-agcs.apps.tools.adp.allianz/repository/maven-public/io/quarkus/quarkus-devtools-all/0.23.2/quarkus-devtools-all-0.23.2.pom
Downloaded from AdpNexus: https://nexus-adp-tools-agcs.apps.tools.adp.allianz/repository/maven-public/io/quarkus/quarkus-devtools-all/0.23.2/quarkus-devtools-all-0.23.2.pom (996 B at 1.4 kB/s)
Downloading from AdpNexus: https://nexus-adp-tools-agcs.apps.tools.adp.allianz/repository/maven-public/io/quarkus/quarkus-devtools-common-core/0.23.2/quarkus-devtools-common-core-0.23.2.pom
Downloaded from AdpNexus: https://nexus-adp-tools-agcs.apps.tools.adp.allianz/repository/maven-public/io/quarkus/quarkus-devtools-common-core/0.23.2/quarkus-devtools-common-core-0.23.2.pom (756 B at 1.4 kB/s)
Downloaded from AdpNexus: https://nexus-adp-tools-agcs.apps.tools.adp.allianz/repository/maven-public/io/quarkus/quarkus-smallrye-jwt-deployment/0.23.2/quarkus-smallrye-jwt-deployment-0.23.2.jar (0 B at 0 B/s)
...
Downloaded from AdpNexus: https://nexus-adp-tools-agcs.apps.tools.adp.allianz/repository/maven-public/io/quarkus/quarkus-smallrye-metrics-deployment/0.23.2/quarkus-smallrye-metrics-deployment-0.23.2.jar (0 B at 0 B/s)
Listening for transport dt_socket at address: 5005
2019-10-05 10:40:41,784 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-10-05 10:40:43,280 WARN  [io.qua.arc.pro.BeanArchives] (build-22) Failed to index org.bson.codecs.configuration.CodecProvider: Stream closed
2019-10-05 10:40:44,507 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 2726ms
2019-10-05 10:40:44,729 INFO  [io.qua.swa.run.SwaggerUiServletExtension] (main) Swagger UI available at /swagger-ui
2019-10-05 10:40:45,833 INFO  [io.quarkus] (main) Quarkus 0.23.2 started in 4.452s. Listening on: http://0.0.0.0:8080
2019-10-05 10:40:45,833 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2019-10-05 10:40:45,833 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client, resteasy, resteasy-jackson, security, smallrye-context-propagation, smallrye-jwt, smallrye-metrics, smallrye-openapi, smallrye-reactive-streams-operators, smallrye-reactive-type-converters, swagger-ui]
'

Reproduced with Quarkus 0.23.2, maven 3.6.2 and jdk 1.8 on Windows.
and with Quarkus 0.23.2, maven 3.5.x and jdk 11 on Windows

**Comment by gsmet** [comment]
@aloubyansky ^

**Comment by jaikiran** [comment]
@gcollin, What exact command do you use when you run into that error? Could you also paste the complete exception stacktrace?

**Comment by gcollin** [comment]
I ran
mvn -X clean test > error2.txt
and this is the resulting file.

If you search for  com.allianz.cisl.ext.agcs.jackson, which is a private package not present in maven central, you will see that maven correctly finds it in my local repo (Compile classpath line 1080), but during test it tries to download it again from central maven (lin 1806).

Hope this helps
[error2.txt](https://github.com/quarkusio/quarkus/files/3694627/error2.txt)

Previously the issue concerned quarkus-bom package but if managed to run mvn test with a direct connection, then it has downloaded the package once and the issue no longer occurs.

**Comment by gcollin** [comment]
I found out this is the same issue than 
#3721
I had maven installed in a non-standard directory (c:\apps\maven), didn't set MAVEN_HOME, didn't have ~/.m2/settings.xml.
  Maven was using the settings.xml in c:\apps\maven\conf whereas Quarkus test assumed no settings.xml existed.
  It works fine if you set MAVEN_HOME
