### ISSUE TITLE
Hardcoded reference to Quinoa in qute template for quarkiverse projects

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus#43854]
Looking at 

```
{#if input.extra-codestarts.contains("quarkiverse")}
  related-guide-section: https://docs.quarkiverse.io/quarkus-quinoa/dev/index.html
{#else}
```

[(source)](https://github.com/holly-cummins/quarkus/blob/438e4b19a7213925322362f41abcf4b7a4961716/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/extension-codestart/java/runtime/src/main/codestarts/quarkus/%7Bextension.id%7D-codestart/codestart.tpl.qute.yml#L9-L11) 

@gsmet [asks](https://github.com/quarkusio/quarkus/pull/43827#discussion_r1797700586)

> Why do we have quinoa hardcoded here?
> 
> Not sure what this related-guide-section metadata is about?

It looks like this code came in with https://github.com/quarkusio/quarkus/pull/26806. The [file was new in that PR](https://github.com/quarkusio/quarkus/blob/42f91e26a55a581739308e5325831f6a2a7c74de/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/extension-codestart/java/runtime/src/main/codestarts/quarkus/%7Bextension.id%7D-codestart/codestart.tpl.qute.yml). 

@ia3andy, can you answer Guillaume's questions?

**Comment by maxandersen** [comment]
this looks like its missing parameterization, should be something like:

`https://docs.quarkiverse.io/{extension-name}/dev/index.html`

to have it be using the right naming convention.

**Comment by ia3andy** [comment]
Yes it's a mistake..
