### ISSUE TITLE
Parameter 'value' may not be null message at Quarkus boot time.

### ISSUE THREAD

**Issue by whitingjr** [quarkusio/quarkus#43866]
Seeing this error due to a mis-configured property at boot time

`Caused by: java.lang.IllegalArgumentException: Parameter 'value' may not be null`

This has been discussed [here](https://github.com/quarkusio/quarkus/discussions/40215).

Make changes that provides useful context information to efficiently solve the issue.

**Comment by geoand** [comment]
cc @dmlloyd
