### ISSUE TITLE
Failed to index org.joda.convert.ToString: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV

### ISSUE THREAD

**Issue by somapersonalcode** [quarkusio/quarkus#43891]
### Describe the bug

I've converted the app from quarkus 3.5.1 to 3.15.1 and when I start the app, the receive the below Warning always on start-up

WARN  [io.qua.arc.pro.BeanArchives] (build-10) Failed to index org.joda.convert.ToString: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV

How do I get rid of it ?

Note : 
1. I have the joda-money dependency in my app
2. This is only coming after migrating to 3.15.1

### Expected behavior

It should start clean without any warning

### Actual behavior

warning is observed as below

WARN  [io.qua.arc.pro.BeanArchives] (build-10) Failed to index org.joda.convert.ToString: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV

### Output of `java -version`

21

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.12.1

**Comment by geoand** [comment]
Can you attach a sample application that exhibits the described behavior?

**Comment by gsmet** [comment]
Ping?

**Comment by somapersonalcode** [comment]
Hi Team,

I'm trying to replicate for a vanilla project, I'll let you know in a couple of days.

**Comment by gsmet** [comment]
Thanks!

**Comment by geoand** [comment]
@somapersonalcode did you have any luck replicating this?

**Comment by geoand** [comment]
Closing for a lack a reproducer. If one becomes available, please attach it and we can reexamine the issue.
