### ISSUE TITLE
Annotation not working - @Acknowledgment(Acknowledgment.Strategy.MANUAL)

### ISSUE THREAD

**Issue by Mohamed-Jaffer** [quarkusio/quarkus#43929]
### Describe the bug

Even after using the above annotation and doing an explicit acknowledgement, consumer keeps on polling messages from kafka and we have disabled auto commit. 

expected behaviour -> Quarkus should not poll kafka till all the previous batch has been acknowledged.

P.S -> Kafka batch is enabled.

### Expected behavior

Quarkus should not poll kafka till all the previous batch has been acknowledged.

### Actual behavior

Even after using the above annotation and doing an explicit acknowledgement, consumer keeps on polling messages from kafka and we have disabled auto commit.

**Comment by cescoffier** [comment]
I think I mention it in a discussion. The polling is paused when we are out of demands, which does not seem to be the case.
So, this is not a bug, the is the expected behavior.

@ozangunalp WDYT?

**Comment by Mohamed-Jaffer** [comment]
@cescoffier Lets say we are consuming the messages in the batches. Now, we want to poll the next batch once the current batch processing is completed. How to do that in quarkus?

**Comment by cescoffier** [comment]
@Mohamed-Jaffer you would need to pause and resume the client.

**Comment by ozangunalp** [comment]
@Mohamed-Jaffer Quarkus ensures that message batch processing happens sequentially, but polling the Kafka consumer and processing are unrelated and happen in different threads. 

Manual acknowledgement doesn't have any effect on this.
