### ISSUE TITLE
NPE when using nested JUnit5 classes

### ISSUE THREAD

**Issue by acoburn** [quarkusio/quarkus#4393]
When using the `quarkus-junit5` module (Quarkus version 0.23.2) with the `@QuarkusTest` annotation, any `@Nested` JUnit5 classes consistently lead to null pointer exceptions.

The relevant portion of the stack trace is:

```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.quickstart.GreetingResourceTest$NestedClass]: Bean is null
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:300)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:275)
	[ ... ]
Caused by: java.lang.NullPointerException: Bean is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at io.quarkus.arc.BeanManagerImpl.getReference(BeanManagerImpl.java:54)
	at io.quarkus.test.common.TestInstantiator.instantiateTest(TestInstantiator.java:25)
	at io.quarkus.test.junit.QuarkusTestExtension.createTestInstance(QuarkusTestExtension.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:285)
	... 82 more
```

I can reproduce this consistently in JDK8 and JDK11, with both Gradle and Maven build environments.

A minimal example of this error can be found at https://github.com/acoburn/quarkus-junit5-test, which is built from the `getting-started` archetype. The only [change](https://github.com/acoburn/quarkus-junit5-test/commit/5e6caeb240314c18fe5661fd1657ecc4e4fdc732) to the generated code is that the JUnit `@Test` is [wrapped](https://github.com/acoburn/quarkus-junit5-test/blob/master/src/test/java/org/acme/quickstart/GreetingResourceTest.java#L13-L23) in a `@Nested` class.

**Comment by geoand** [comment]
So after debugging a bit I saw that Arc doesn't support non-static inner classes (see [this](https://github.com/quarkusio/quarkus/blob/6bfe2b4bd5c6ab7c1e155b5bf3ef08326a15c727/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java#L553)).
So I'm not sure how `@Nested` can be supported. @manovotn @mkouba WDYT?

**Comment by manovotn** [comment]
In Junit testing with Quarkus, the test class in a bean (see [this code](https://github.com/quarkusio/quarkus/blob/6bfe2b4bd5c6ab7c1e155b5bf3ef08326a15c727/test-framework/common/src/main/java/io/quarkus/test/common/TestInstantiator.java)).
And CDI spec doesn't like inner classes (non static), see https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#what_classes_are_beans

**Comment by manovotn** [comment]
Although I agree that we should remedy the error and make it more readable.
We could probably detect this in `QuarkusTestExtension#createTestInstance()` and throw and exception?

**Comment by geoand** [comment]
> @geoand In Junit testing with Quarkus, the test class itself is a bean (see [this code](https://github.com/quarkusio/quarkus/blob/6bfe2b4bd5c6ab7c1e155b5bf3ef08326a15c727/test-framework/common/src/main/java/io/quarkus/test/common/TestInstantiator.java)).
 
Yup, that's why I looked at Arc in the first place :)

> We could probably detect this in QuarkusTestExtension#createTestInstance() and throw and exception?

Sounds reasoable to me

**Comment by manovotn** [comment]
Ok, in that case, I'll send a PR for that later today.

**Comment by manovotn** [comment]
@acoburn BTW if you really need it to be `@Nested` for some reason, then you can make it `static` and that will work too.

**Comment by geoand** [comment]
I think that `@Nested` in JUnit 5 is not supposed to be `static`. 

But of course the question of the usefulness of `@Nested` is still valid. I personally haven't encountered it.

**Comment by manovotn** [comment]
Ah, you're right, just spotted that in their docs - https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested

> But of course the question of the usefulness of @Nested is still valid. I personally haven't encountered it.

Yeah, I've got similar experience.

**Comment by acoburn** [comment]
@manovotn thanks for fixing this so quickly. While it would be nice to use `@Nested` classes at some future point, I can work around that. The NPE issue described here has been fixed, so I am going to close this issue.
