### ISSUE TITLE
Support Singlestore jdbc driver for jdbc extension

### ISSUE THREAD

**Issue by Hemantkumar-Chigadani** [quarkusio/quarkus#43941]
### Description

Singlestore is getting its popularity in the db world, Quarkus to support Singlestore jdbc for support to use it with native image.

Singlestore supports Mariadb driver and works for native image as well but when it comes using the Mariadb driver with flyway-mariadb does not work. I have tried many attempts using Mariadb jdbc driver with flyway-signstore.

Finally concluded without Singlestore jdbc support from Quarkus; its not going to work for us.

**Comment by melloware** [comment]
For those who had to google this like me... 

URL: https://www.singlestore.com/

> SingleStore is a distributed SQL database built from the ground up for maximum performance for transactions and analytics. The SingleStore server includes its own storage engine and SQL-based execution engine built around scalable distributed execution and lock-free data structures. SingleStore and MySQL servers do not share any code, but SingleStore is compatible with MySQL client software. SingleStore uses the same wire protocol as MySQL, and supports similar SQL syntax as MySQL for easier compatibility.

**Comment by yrodiere** [comment]
Hello,

Thanks for your proposal and PR.

I think this should be a Quarkiverse extension -- at least for a start. It's unclear right now how popular the extension would be, and how well it would integrate with other core extensions (e.g. not sure the MySQL compatibility is quite enough to fool Hibernate ORM).

Could you maintain something similar to [quarkus-jdbc-sqlite](https://github.com/quarkiverse/quarkus-jdbc-sqlite), but for Singlestore? If so, I'm sure @gastaldi will be able to create a repository for you.

**Comment by gsmet** [comment]
If you decide to move it to a Quarkiverse extension, I recommend you create the structure following the Quarkiverse template and then copy the classes from the extension you created.

That way your extension will properly use the Quarkiverse template, which is a bit different (it has publication workflows for instance).

**Comment by Hemantkumar-Chigadani** [comment]
Thanks @melloware @yrodiere 

Adding more to the context.

More specific information onto the Singlestore driver : https://docs.singlestore.com/cloud/developer-resources/connect-with-application-development-tools/connect-with-java-jdbc/the-singlestore-jdbc-driver/

MariaDb/Mysql drivers are supportive of the Singlestore for its connections but we it comes to flyway migration, we get following error from these drivers.

```
Caused by: java.sql.SQLException: Function 'mermaid_test.GET_LOCK' is not defined
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
	Please note: GET_LOCK is not supported by Singlestore database
	<https://docs.singlestore.com/cloud/developer-resources/unsupported-mysql-features/>

```

**LOCK** functions are **not** supported by Singlestore for their own specific reasons

https://docs.singlestore.com/cloud/developer-resources/unsupported-mysql-features/

`unsupported: get_lock() and related functions (release_lock(), etc.).`

I have done a good round of testing in JVM mode and native mode on the PR changes, fyi.I hope this helps.

@yrodiere Please I am happy to have this as Quarkiverse extension instead of core one.

Thanks @gsmet I will create  as Quarkiverse extension and get back to you guys.

**Comment by Hemantkumar-Chigadani** [comment]
@gsmet Could you please help me with repository set up [quarkus-jdbc-singlestore](https://github.com/quarkiverse/quarkus-jdbc-singlestore), thanks?

**Comment by gastaldi** [comment]
@Hemantkumar-Chigadani no, that template repository is archived and replaced with the Quarkus CLI. Just run `quarkus create extension singlestore` and you should have a skeleton ready

**Comment by Hemantkumar-Chigadani** [comment]
@gastaldi Thanks for your input, cheers. I will try and let you know how it goes.

**Comment by Hemantkumar-Chigadani** [comment]
@gastaldi Could you please let me know once repo is ready https://github.com/quarkiverse/quarkus-jdbc-singlestore? As I am ready with code changes, thanks

**Comment by gastaldi** [comment]
It is ready now, here are the next steps:
https://hub.quarkiverse.io/checklistfornewprojects/#after-the-repository-is-created

**Comment by Hemantkumar-Chigadani** [comment]
@gastaldi Somehow I can not initialise the repo to fork it as its empty repo, could you please initialise the repo for me, thanks?

**Comment by gastaldi** [comment]
@Hemantkumar-Chigadani I initialized the repository with the output of `quarkus create extension jdbc-singlestore`. Just a friendly reminder that since you're now the maintainer, you can push directly to that repository and create as many branches as you need 😉
