### ISSUE TITLE
Runtime/Extension distinction break Maven reactor ordering

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#4396]
Imagine a project with:
```
banner-extension
    banner-extension-deployment (dep)
    banner-extension-runtime (run)
some-project-using-the-banner-extension (app)
```
`app` depends on `run`.
`dep` depends on `run`.

So, Maven may build in the following order:

1.  run
2. app
3. dep

Unfortunately, that means that `app` test will fail because `dep` has not been built.

**Comment by gsmet** [comment]
IIRC dev mode won’t work very well either so that’s probably something people shouldn’t do.

**Comment by geoand** [comment]
Maybe we need some guide about the proposed project structures?

**Comment by agoncal** [comment]
@cescoffier correct me if I'm wrong, but you don't need the extension to compile, isn't it ? Why not having the extension in scope runtime ?

```
        <dependency>
            <groupId>io.quarkus.workshop.super-heroes</groupId>
            <artifactId>extension-banner</artifactId>
            <version>${project.version}</version>
            <scope>runtime</scope>
        </dependency>
```

**Comment by stuartwdouglas** [comment]
IMHO this is not something we want to be recommending users do, and if they really want to then the solution is to just add a test scoped dependency.

**Comment by stuartwdouglas** [comment]
We have worked around this by adding a test scoped dependency on the pom, I don't think there is much more we can do here.
