### ISSUE TITLE
Some Native tests don't run due to failsafe <skip>true</skip>

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#43997]
### Description

While reviewing https://github.com/quarkusio/quarkus/pull/43829 I noticed the GHA has been giving us false negative, not running `awt` integration test.

When I tried locally, I wasn't able to make maven run the awt testsuite with native-image either. The harness runs HotSpot tests, then it builds the native-image but it doesn't run any tests with it.

```
./mvnw verify -f integration-tests/pom.xml -pl awt  -Pnative
```

I did try to fiddle with various maven flags like `-DskipITs=false` to no avail.

Trying to run the test in container had a similar result, the harness executed HotSpot tests, it went on to build the native executable using builder-image, then it built a runtime container image and copied the executable in it, then it started the runtime container and terminated there, not executing any actual tests.

```
./mvnw verify -f integration-tests/pom.xml -pl awt -Ddocker -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 -Dquarkus.native.container-runtime=podman -DskipITs=false 2>&1 | tee log.log

```

I had to manually patch the pom.xml to make it run the testsuite properly:

```diff
tester@mandrel2:~/karm/quarkus (2024-10-11-awt-processor-refactor *%=)$ git diff
diff --git a/integration-tests/awt/pom.xml b/integration-tests/awt/pom.xml
index f71302da2c2..eb290a5e037 100644
--- a/integration-tests/awt/pom.xml
+++ b/integration-tests/awt/pom.xml
@@ -164,7 +164,7 @@
             <plugin>
                 <artifactId>maven-failsafe-plugin</artifactId>
                 <configuration>
-                    <skip>true</skip>
+                    <skip>false</skip>
                 </configuration>
             </plugin>
         </plugins>

```

It seems that this is the change that has brought the `skip>true</skip>` in: https://github.com/quarkusio/quarkus/commit/9f3ba1922d2

## Question

 * Isn't there any Maven flag missing from our GHA yaml? Which is it and how it was meant to be executed?
 * Aren't there many more native-image integration tests affected? Merely building the executables but silently not running any tests? A casual find && grep tells me that it might be the case.

Thx
K.

**Comment by gsmet** [comment]
Having a look at this one.

**Comment by gsmet** [comment]
I fixed the AWT case here: https://github.com/quarkusio/quarkus/pull/44139 .

Not sure if there are other cases though as for instance in the Redis case `integration-tests/redis-client`, it's expected that we disable Failsafe by default, it's enabled when you enable the container build.

If you have specific examples that look suspicious to you, please point them to me and I'll have a look. In the meantime, AWT testing should be fine after the PR. Sorry for the oversight!
