### ISSUE TITLE
Jacoco report incomplete when using surefire plugin argLine property

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#44010]
### Describe the bug

when using the jacoco extension plus the `jacoco-maven-plugin` combined with the `argLine` parameter on the `surefire` plugin,  component tests and unit tests are not included in the coverage. only quarkus tests are.

### Expected behavior

there should be a way to use the `argLine` parameter on the `surefire` plugin, use a mix of quarkus, component and unit tests, and get full code coverage.
the `argLine` parameter is used for instance to set memory when running tests.

### Actual behavior

component and unit tests do not get coverage.

### How to Reproduce?

Reproducer: https://github.com/vsevel/reproducer_jacoco

1. mvn clean verify
2. open target/jacoco-report/index.html 
3. check we have 100% coverage (OK)
4. mvn clean verify -Dsurefire.argLine=-Xmx1g
5. open target/jacoco-report/index.html 
6. check we have only 40% coverage (KO)

the difference of behavior happens on the surefire command line. when it is OK we have:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[DEBUG] Determined Maven Process ID 91787
[DEBUG] Fork Channel [1] connection string 'pipe://1' for the implementation class org.apache.maven.plugin.surefire.extensions.LegacyForkChannel
...
[DEBUG] Forking command line: /bin/sh -c cd '/Users/vsevel/dev/github/reproducer_jacoco' && '/usr/local/Cellar/openjdk@21/21.0.4/libexec/openjdk.jdk/Contents/Home/bin/java' '-javaagent:/Users/vsevel/.m2/repository/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/Users/vsevel/dev/github/reproducer_jacoco/target/jacoco-quarkus.exec,append=true,exclclassloader=*QuarkusClassLoader' '-jar' '/Users/vsevel/dev/github/reproducer_jacoco/target/surefire/surefirebooter-20241022072902508_3.jar' '/Users/vsevel/dev/github/reproducer_jacoco/target/surefire' '2024-10-22T07-29-02_378-jvmRun1' 'surefire-20241022072902508_1tmp' 'surefire_0-20241022072902508_2tmp'
[DEBUG] Fork Channel [1] connected to the client.
[INFO] Running org.acme.GreetingResourceTest
```

and when it is not:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[DEBUG] Determined Maven Process ID 91964
[DEBUG] Fork Channel [1] connection string 'pipe://1' for the implementation class org.apache.maven.plugin.surefire.extensions.LegacyForkChannel
...
[DEBUG] Forking command line: /bin/sh -c cd '/Users/vsevel/dev/github/reproducer_jacoco' && '/usr/local/Cellar/openjdk@21/21.0.4/libexec/openjdk.jdk/Contents/Home/bin/java' '-Xmx1g' '-jar' '/Users/vsevel/dev/github/reproducer_jacoco/target/surefire/surefirebooter-20241022072956389_3.jar' '/Users/vsevel/dev/github/reproducer_jacoco/target/surefire' '2024-10-22T07-29-56_247-jvmRun1' 'surefire-20241022072956389_1tmp' 'surefire_0-20241022072956389_2tmp'
[DEBUG] Fork Channel [1] connected to the client.
[INFO] Running org.acme.GreetingResourceTest

```

in that situation the `jacoco` agent is not configured.

### Output of `uname -a` or `ver`

macos

### Output of `java -version`

21

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.9

**Comment by vsevel** [comment]
cc @stuartwdouglas

**Comment by vsevel** [comment]
I tested the workaround `<argLine>@{argLine} -your -extra -arguments</argLine>` described [here](https://github.com/jacoco/jacoco/issues/964#issuecomment-543312882), and it works fine.
may we should just provide some doc in the https://quarkus.io/guides/tests-with-coverage documentation.

**Comment by vsevel** [comment]
sure @geoand

**Comment by geoand** [comment]
🙏🏽
