### ISSUE TITLE
quarkus.native.march should be x86-64-v2 when using quarkus-amazon-lambda-rest

### ISSUE THREAD

**Issue by stefvanderweldevolksbanknl** [quarkusio/quarkus#44019]
### Description

According to AWS docs:

> All AL2023 x86-64 binaries are built for the x86-64v2 revision of the x86-64 architecture by passing -march=x86-64-v2 to the compiler.

But Quarkus uses `x86-64-v3` by default (https://quarkus.io/guides/building-native-image#quarkus-core_quarkus-native-march). This might cause trouble if AWS provisions a Lambda with older hardware:
`The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].`

### Implementation ideas

When using the `quarkus-amazon-lambda-rest` extension, the [quarkus.native.march](https://quarkus.io/guides/building-native-image#quarkus-core_quarkus-native-march) property should default to `x86-64-v2`

**Comment by gsmet** [comment]
I'm not sure that's something we want to change. This will probably evolve on their side along the time (and probably in the v3 direction) and it's going to be hard to track for us.
That's why we have a configuration property, so that you can adapt it yourself.

**Comment by gsmet** [comment]
Yeah, we could add a warning in the Amazon Lambda doc.

That's one of the issues with the cloud: you never know which machine you will end up with and if you are using native, it can actually be problematic.
You might have to use `compatibility` if things are too unstable.

If you find a good place to add the info to the doc, please create a PR, I think that's an important piece of information to have. Thanks!

**Comment by stefvanderweldevolksbanknl** [comment]
> Yeah, we could add a warning in the Amazon Lambda doc.
> 
> That's one of the issues with the cloud: you never know which machine you will end up with and if you are using native, it can actually be problematic. You might have to use `compatibility` if things are too unstable.
> 
> If you find a good place to add the info to the doc, please create a PR, I think that's an important piece of information to have. Thanks!

Sounds good. I made a PR
