### ISSUE TITLE
OpenAPI: Allow configuration of name of generated files

### ISSUE THREAD

**Issue by AndreasPetersen** [quarkusio/quarkus#44041]
### Description

If we set [quarkus.smallrye-openapi.store-schema-directory](https://quarkus.io/guides/all-config#quarkus-smallrye-openapi_quarkus-smallrye-openapi-store-schema-directory) Quarkus will generate a `openapi.yaml` and `openapi.json` file in the specified directory.

Our organisation has a requirement that these files must have a specific name, which is not `openapi`. We would like a new config option to change the name of the generated files.

### Implementation ideas

A new configuration property, e.g. `quarkus.smallrye-openapi.file-name`, that determines the name of the generated OpenAPI files.

**Comment by phillip-kruger** [comment]
@AndreasPetersen do you want to do a PR for this ?
