### ISSUE TITLE
Dynamodb: Add support for Jdk buitin HttpClient - UrlConnectionHttpClient

### ISSUE THREAD

**Issue by Ravisankar-Challa** [quarkusio/quarkus#4406]
Hi Team,

Please also add support for UrlConnectionHttpClient as http client for Dynamo DB as an alternative to ApacheHttpClient.

Thanks,
Ravi

**Comment by gsmet** [comment]
Do you have any good reason of not using the Apache HTTP client?

(Real question, I'm not familiar with Amazon DynamoDB)

/cc @marcinczeczko

**Comment by Ravisankar-Challa** [comment]
Not suited for AWS LAMDA

**Comment by gsmet** [comment]
@marcinczeczko I let you reply on this one and see if we can do something about it?

**Comment by marcinczeczko** [comment]
Well, honesty there were no a good reason for that, except the counter-example for async client that was my primary goal :) It's fairly easy to add such support as AWS SDK supports it.

**Comment by marcinczeczko** [comment]
Please see #4471

**Comment by Ravisankar-Challa** [comment]
@marcinczeczko Tested it with 999-SNAPSHOT in aws lamda with **quarkus.dynamodb.sync-client.type=URL**. Workd fine. How to get this property in vscode auto complete feature. Do I have to raise a separate feature request for this?

**Comment by gsmet** [comment]
@marcinczeczko 's work has been merged.
