### ISSUE TITLE
Custom `SecurityContext` provokes `StackOverflowError`

### ISSUE THREAD

**Issue by kronst** [quarkusio/quarkus#44078]
### Describe the bug

In my application I have a custom `ContainerRequestFilter` implementation which replaces the `SecurityContext` in the `ContainerRequestContext`. At the same time there is a `io.quarkus.resteasy.runtime.SecurityContextFilter` in `quarkus-resteasy` which replaces the actual `SecurityIdentity` with an implementation that uses modified security context (added in [this commit](https://github.com/quarkusio/quarkus/commit/70f8288021d7eea10f8e53d8cf22bef2cc924aef)). 

Since my implementation of `SecurityContext` which is almost the same as `QuarkusResteasySecurityContext` invokes methods of `SecurityIdentity` this creates an infinity recursion and provokes `StackOverflowError`:  `SecurityContext` calls `SecurityIdentity` > `SecurityIdentity` calls `SecurityContext`.

Is this a potential bug or is there any workaround how can I solve this issue? All examples of my implementations of filter and context provided. Also example project with a test that will failed due to `StackOverflowError` will be attached. 

### How to Reproduce?

Custom filter example:
```java
@Provider
@PreMatching
public class CustomFilter implements ContainerRequestFilter {

    @Inject
    CurrentVertxRequest currentVertxRequest;

    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {
        SecurityContext securityContext = new CustomSecurityContext(
            requestContext,
            currentVertxRequest.getCurrent(),
            List.of("admin")
        );
        requestContext.setSecurityContext(securityContext);
    }
}
```

Custom security context example:
```java
public class CustomSecurityContext implements SecurityContext {

    private final ContainerRequestContext requestContext;
    private final RoutingContext routingContext;
    private final List<String> roles;

    public CustomSecurityContext(ContainerRequestContext requestContext, RoutingContext routingContext, List<String> roles) {
        this.requestContext = requestContext;
        this.routingContext = routingContext;
        this.roles = roles;
    }

    @Override
    public Principal getUserPrincipal() {
        QuarkusHttpUser user = (QuarkusHttpUser) routingContext.user();
        return user != null && !user.getSecurityIdentity().isAnonymous() // StackOverflowError
            ? user.getSecurityIdentity().getPrincipal() // StackOverflowError
            : null;
    }

    @Override
    public boolean isUserInRole(String role) {
        SecurityIdentity user = CurrentIdentityAssociation.current();

        System.out.println(user.isAnonymous()); // StackOverflowError

        if (role.equals("**")) {
            return !user.isAnonymous(); // StackOverflowError
        } else {
            return roles.contains(role);
        }
    }

    @Override
    public boolean isSecure() {
        return true;
    }

    @Override
    public String getAuthenticationScheme() {
        String authorizationValue = requestContext.getHeaders().getFirst("Authorization");
        if (authorizationValue == null) {
            return null;
        } else {
            return authorizationValue.split(" ")[0].trim();
        }
    }
}
```

Resteasy `SecurityContextFilter` that replaces the `SecurityIdentity`:
```java
@PreMatching
@Priority(Priorities.USER + 1)
@Provider
public class SecurityContextFilter implements ContainerRequestFilter {

    @Inject
    SecurityIdentity old;

    @Inject
    CurrentIdentityAssociation currentIdentityAssociation;

    @Inject
    RoutingContext routingContext;

    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {
        SecurityContext modified = requestContext.getSecurityContext();
        if (modified instanceof ServletSecurityContext || modified instanceof QuarkusResteasySecurityContext) {
            //an original security context, it has not been modified
            return;
        }
        Set<Credential> oldCredentials = old.getCredentials();
        Map<String, Object> oldAttributes = old.getAttributes();
        SecurityIdentity newIdentity = new SecurityIdentity() {
            @Override
            public Principal getPrincipal() {
                return modified.getUserPrincipal();
            }

            @Override
            public boolean isAnonymous() {
                return modified.getUserPrincipal() == null;
            }

            @Override
            public Set<String> getRoles() {
                throw new UnsupportedOperationException(
                        "retrieving all roles not supported when JAX-RS security context has been replaced");
            }

            @Override
            public boolean hasRole(String role) {
                return modified.isUserInRole(role);
            }

            @Override
            public <T extends Credential> T getCredential(Class<T> credentialType) {
                for (Credential cred : getCredentials()) {
                    if (credentialType.isAssignableFrom(cred.getClass())) {
                        return (T) cred;
                    }
                }
                return null;
            }

            @Override
            public Set<Credential> getCredentials() {
                return oldCredentials;
            }

            @Override
            public <T> T getAttribute(String name) {
                return (T) oldAttributes.get(name);
            }

            @Override
            public Map<String, Object> getAttributes() {
                return oldAttributes;
            }

            @Override
            public Uni<Boolean> checkPermission(Permission permission) {
                return Uni.createFrom().nullItem();
            }
        };
        routingContext.setUser(new QuarkusHttpUser(newIdentity));
        currentIdentityAssociation.setIdentity(newIdentity);
    }
}
```

Minimal example project:
[quarkus-custom-security-context.zip](https://github.com/user-attachments/files/17509384/quarkus-custom-security-context.zip)

### Output of `uname -a` or `ver`

Linux laptop 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 LTS

### Quarkus version or git rev

3.14.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.11-rc-1

**Comment by sberyozkin** [comment]
As far as I understand,  users are only expected to provide a single prematching filter resetting a custom jaxrs security context using jaxrs api, if they would like to use JAX-RS security context.
Can you try to simplify ? Access to the internal api should not be necessary

**Comment by kronst** [comment]
> As far as I understand, users are only expected to provide a single prematching filter resetting a custom jaxrs security context using jaxrs api, if they would like to use JAX-RS security context. Can you try to simplify ? Access to the internal api should not be necessary

Sorry, but I didn't quite understand what simplification you're talking about. Example project has only one `@PreMatching` filter: `CustomFilter`. The second one `SecurityContextFilter` is an internal filter from the `quarkus-resteasy` extension: `io.quarkus.resteasy.runtime.SecurityContextFilter`. I added it's source just in case to show how it replaces the `SecurityIdentity`. 

The main goal I want to achieve is to check if the `role` parameter from the `SecurityContext.isUserInRole` method is in my own list of roles which I provided in the filter. That's why I'm trying to use a custom context. Sorry if I didn't understand your message correctly.

**Comment by sberyozkin** [comment]
I see, sure. 
We haven't looked a lot into ensuring the interactions between custom JAX-RS SecurityContext and the internal API works.

We have only looked into  supporting a case where JAX-RS SecurityContext customization is done the way you did it but without mixing in internal security API...

You can achieve much more by using SecurityIdentity and the identity augmentor,  without having to link with unexpected results the internal api, while trying to retain 100% portable JAX-RS code.

Can you try to implement the custom context by only accessing the already available JAX-RS SecurityContext in the container request filter?

**Comment by kronst** [comment]
> I see, sure. We haven't looked a lot into ensuring the interactions between custom JAX-RS SecurityContext and the internal API works.
> 
> We have only looked into supporting a case where JAX-RS SecurityContext customization is done the way you did it but without mixing in internal security API...
> 
> You can achieve much more by using SecurityIdentity and the identity augmentor, without having to link with unexpected results the internal api, while trying to retain 100% portable JAX-RS code.
> 
> Can you try to implement the custom context by only accessing the already available JAX-RS SecurityContext in the container request filter?

Huh, looks like using `SecurityIdentityAugmentor` which adds my own pre-fetched roles to the identity solves the issue. As a result I don't need a filter and custom context at all 😲 
```java
@ApplicationScoped
public class CustomSecurityIdentityAugmentor implements SecurityIdentityAugmentor {

    @Override
    public Uni<SecurityIdentity> augment(SecurityIdentity identity, AuthenticationRequestContext context) {
        return context.runBlocking(() -> {
            Set<String> roles = Set.of("admin"); // Do some blocking work to get the roles for the request

            return QuarkusSecurityIdentity.builder(identity)
                .addRoles(roles)
                .build();
        });
    }
}
```
Hope there will be no other surprises in the real application. I think this issue could be closed. Thanks!
