### ISSUE TITLE
User Route should be called even when registered after the default route

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#4407]
**Describe the bug**
Default web route is a catch all

**Expected behavior**
Routes added to vertx web router after the default route is added should not be swallowed.

**Actual behavior**
When a route is added to the vertx web router at runtime, then the route is ignored if a default route is already in place, i.e. added by quarkus-resteasy

**To Reproduce**
1. clone and run https://github.com/lburgazzoli/quarkus-camel-http
2. http GET localhost:8080/platform-http/hello
3. this will fails with 404
4. remove the dependency on quarkus-resteasy
5. rebuild and run
6. this will succeed

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 0.23.2

**Additional context**
A workaround is top set the route added at runtime with order -1

**Comment by cescoffier** [comment]
Being a catch-all is not an issue, not being called last is more problematic as user routes appended to the router after the default route are ignored. We should set the `order` of the default route to something _high_.
