### ISSUE TITLE
Wrong HTTP code in case of resteasy + custom web router handler (404 instead of 405)

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#4408]
**Describe the bug**
If we mix jax rs + custom web router handler, 404 is returned instead of 405 in case of an unsupported method.

**Expected behavior**
405 should be returned in case of a request with wrong method on an existing path.

**Actual behavior**
404 is returned instead of 405

**To Reproduce**
1. clone and run https://github.com/lburgazzoli/quarkus-camel-http
2. http POST localhost:8080/platform-http/hello
3. this will fails with 404
4. remove the REST class (MyRest)
5. http POST localhost:8080/platform-http/hello
6. this will fails with 405

**Environment (please complete the following information):**
 - Quarkus version or git rev: 0.23.2

**Additional context**
This code actually need to build camel-quarkus from [this](https://github.com/lburgazzoli/apache-camel-quarkus/tree/platform-http-resteasy) as the workaround for #4407 is not yet available in master

**Comment by ppalaga** [comment]
Cannot reproduce with Quarkus 0.25 - see https://github.com/apache/camel-quarkus/pull/295 

This issue can probably be closed.

**Comment by lburgazzoli** [comment]
I think this happens because resteasy is not a dependency of such tests

**Comment by gsmet** [comment]
@lburgazzoli @ppalaga should this one be closed?

**Comment by geoand** [comment]
Is this still an issue?

**Comment by ppalaga** [comment]
Let's close
