### ISSUE TITLE
> ClientJacksonMessageBodyReader return a false BAD_REQUEST

### ISSUE THREAD

**Issue by benDeMtp** [quarkusio/quarkus#44100]
### Describe the bug

In ClientJacksonMessageBodyReader there is : 

```java
    @Override
    public Object readFrom(Class<Object> type, Type genericType, Annotation[] annotations, MediaType mediaType,
            MultivaluedMap<String, String> httpHeaders, InputStream entityStream) throws IOException, WebApplicationException {
        try {
            if (entityStream instanceof EmptyInputStream) {
                return null;
            }
            ObjectReader reader = getEffectiveReader(mediaType);
            return reader.forType(reader.getTypeFactory().constructType(genericType != null ? genericType : type))
                    .readValue(entityStream);

        } catch (JsonParseException e) {
            log.debug("Server returned invalid json data", e);
            throw new ClientWebApplicationException(e, Response.Status.OK);
        } catch (StreamReadException | DatabindException e) {
            throw new ClientWebApplicationException(e, Response.Status.BAD_REQUEST); // TODO: we need to check if this actually makes sense...
        }
    }
```

    

If a StreamReadException or a DatabinException is thrown, the exception is remapping in BadRequest.

Do you know why ?

IMO, if there is something returned by the server and this response does not have a 400-status code, we should not return BadRequest. It is misleading the troubleshooter.

In this case this is not the request that is "Bad" but the response that cannot be correctly handled.

I'am wrong ?

### Expected behavior

A more revelant exception is thrown

**Comment by geoand** [comment]
I think you are right that we should not be catching those exceptions. 
Do you want to submit a Pull Request fixing the issue?

**Comment by benDeMtp** [comment]
Sure. I'm AFK until monday. I will do the PR next week.

**Comment by benDeMtp** [comment]
Huston, we have a problem.

When I removed the catch, there was  a test that was apparently unrelated, which failed. 

`
ClientWithCustomObjectMapperTest.testCustomObjectMappersShouldBeUsedInReader:80 
Expecting actual throwable to be an instance of:
  org.jboss.resteasy.reactive.ClientWebApplicationException
but was:
  java.util.concurrent.CompletionException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "secondValue" (class io.quarkus.it.rest.client.ClientWithCustomObjectMapperTest$Request), not marked as ignorable (one known property: "value"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 41] (through reference chain: io.quarkus.it.rest.client.ClientWithCustomObjectMapperTest$Request["secondValue"])
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
        at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
        ...(79 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
`
-> https://github.com/benDeMtp/quarkus/actions/runs/11667741013#user-content-test-failures-job-32486556789


The behavior expected by this test is based on the removed ClientWebApplicationException.
What should I do ? 

Thanks

**Comment by geoand** [comment]
You can just update the test to test for the proper exception (the test would be to the cause, as that is where the Jackson exception would be present)
