### ISSUE TITLE
Generate only openapi.yaml

### ISSUE THREAD

**Issue by doussa2504** [quarkusio/quarkus#44102]
Hello,
According to [documentation ](https://quarkus.io/guides/openapi-swaggerui) openapi.yaml and openapi.yaml should be genrated when using quarkus.swagger-ui.
Is there a config to restrict the output format and generate only openapi.yaml?
Thank you :)

**Comment by phillip-kruger** [comment]
Not as far as I know. @MikeEdgar ?

**Comment by MikeEdgar** [comment]
No, we have nothing to limit the OpenAPI format. It's required to support both YAML and JSON by MicroProfile OpenAPI [1] and there's never been a reason or request to limit it (that I know of).


[1] https://download.eclipse.org/microprofile/microprofile-open-api-4.0.2/microprofile-openapi-spec-4.0.2.html#_content_format

**Comment by doussa2504** [comment]
Thank you! just wanted to be sure if such an option exist.
