### ISSUE TITLE
QuarkusMainTest always run even TestProfile's tags do not match

### ISSUE THREAD

**Issue by yuan-kuan** [quarkusio/quarkus#44118]
### Describe the bug

Tests annotated with `@QuarkusMainTest` and `@TestProfile` will always run despite the TestProfile has a different tags than the settings.

### Expected behavior

If the TestProfile's tags do not matched the setting, tests should not run.

### How to Reproduce?

1. clone my small reproducible project: https://github.com/yuan-kuan/quarkus-test-tags-bug/tree/main
2. `quarkus dev -Dquarkus.test.profile.tags=b`
3. press `o` and press `r` to run the unit tests with output on.
4. Observe that `bugTest` still run despite it's TestProfile only return `'a'` in `tags()` getter
5. Restart the Quarkus dev mode: `quarkus dev -Dquarkus.test.profile.tags=a`
6. Run the test again
7. Observe that `testOk`, which TestProfile has `'b'` tag only, will not run. 

### Output of `uname -a` or `ver`

Darwin 24.0.0 Darwin Kernel Version 24.0.0: Wed Aug  7 03:09:57 PDT 2024; root:xnu-11215.1.9~22/RELEASE_ARM64_T8112 arm64

### Output of `java -version`

openjdk version "21.0.5" 2024-10-15 LTS

### Quarkus version or git rev

quarkus 3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)

**Comment by geoand** [comment]
Thanks for the great reproducer!

#44371 fixes the issue
