### ISSUE TITLE
MicroProfile Config escape character not respected

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#4411]
**Describe the bug**
If you set a property as a list:

```
greeting.suffix=!!, How \, are you?,??

@ConfigProperty(name = "greeting.suffix")
List<String> suffixes;
```

The List should contain the next values: "!!", "How, are you?", "??" but it contains four elements instead of 3:  "!!", "How",  "are you?", "??

**Expected behavior**

Contain an array with 3 elements as escape char.

**Actual behavior**

Escape char is not an escape char but it is used as a separator.

**Comment by gwenneg** [comment]
It works for me as long as the backslash is doubled in the properties file:
`greeting.suffix=!!, How \\, are you?,??`

The first backslash is treated as an espace character during [Properties.load()](https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#load(java.io.Reader)) and then the second one is treated as an espace character by `smallrye-config`.

**Comment by lordofthejars** [comment]
Ok then I think we can close this.
