### ISSUE TITLE
TestResourceScope.MATCHING_RESOURCES ignores configuration annotations from QuarkusTestResourceConfigurableLifecycleManager

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#44129]
### Describe the bug

From what I can see, only the FQCN of the test resource lifecycle manager and the configured scope are taken into account when grouping together tests with matching resources:

https://github.com/quarkusio/quarkus/blob/2fc4833f3f52e7d7851bbea57653b1bca53af98c/test-framework/common/src/main/java/io/quarkus/test/common/TestResourceManager.java#L321-L332

This seems incomplete, as test resource lifecycle managers can implement `QuarkusTestResourceConfigurableLifecycleManager` to be customized per-test, like this:

https://github.com/quarkusio/search.quarkus.io/blob/41e3b9f2de465ea2dc74efaa46ee44b310d5cc08/src/test/java/io/quarkus/search/app/testsupport/QuarkusIOSample.java#L510-L531

https://github.com/yrodiere/search.quarkus.io/blob/42ebd004b6fa5d92960b0615fb8ead6b1b6cb726/src/test/java/io/quarkus/search/app/SearchServiceTest.java#L42

### Expected behavior

Tests are considered to have matching resources if they have the same resource lifecycle managers _with the same arguments_.

### Actual behavior

Tests are considered to have matching resources if they have the same resource lifecycle managers, _regardless of arguments_.

### How to Reproduce?

Check out https://github.com/quarkusio/search.quarkus.io/pull/345 , revert the last commit, and see how resources are reused despite the 

Or, probably simpler, add a unit test next to the existing ones for `@WithTestResource` within Quarkus itself.

### Additional information

Related conversation: https://github.com/quarkusio/search.quarkus.io/pull/345

PR introducing the feature: #42852

**Comment by geoand** [comment]
I will have to check this out as I don't really remember any of the details :)

**Comment by geoand** [comment]
> Tests are considered to have matching resources if they have the same resource lifecycle managers, regardless of arguments.

When you say arguments, I assume you mean the config annotation, right?

**Comment by yrodiere** [comment]
> > Tests are considered to have matching resources if they have the same resource lifecycle managers, regardless of arguments.
> 
> When you say arguments, I assume you mean the config annotation, right?

Right.

**Comment by geoand** [comment]
@yrodiere I started https://github.com/quarkusio/quarkus/pull/44215. I am pretty sure it doesn't cover this exact case

**Comment by yrodiere** [comment]
So, it's moved to #44279.

I think that PR handles `@WithTestResource#initArgs`, but not configuration annotations... It takes `io.quarkus.test.common.TestResourceManager.TestResourceClassEntry#args` into account for comparison, but not `io.quarkus.test.common.TestResourceManager.TestResourceClassEntry#configAnnotation`.

To be clear when I talk about "configuration annotations" I mean this:

https://github.com/quarkusio/quarkus/blob/ac87489590d40f51a23b6c016bb50418a5c88187/test-framework/common/src/main/java/io/quarkus/test/common/TestResourceManager.java#L157-L160

https://github.com/quarkusio/quarkus/blob/12fe9e07d2bedd6a2b539c6aa688c23bf7e1d9ae/test-framework/common/src/test/java/io/quarkus/test/common/TestResourceManagerTest.java#L216-L224


... which is separate from `@WithTestResource#initArgs`. It's an alternative to it, I think.
