### ISSUE TITLE
Start Keycloak Dev Service for standalone Keycloak Admin Client extensions and OIDC Client Registration

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#44143]
### Description

We now support starting Keycloak Dev Service for standalone OIDC Client https://github.com/quarkusio/quarkus/pull/43609. I _think_ we agreed to allow starting Keycloak Dev Service for standalone:

- Keycloak Admin REST Client
- Keycloak Admin RESTEasy Client
- OIDC Client Registration

### Implementation ideas

I am opening this for issue for myself, mostly to give anyone (like @sberyozkin ) chance to say we don't need this, because I might have misunderstood  original discussion. I plan to work on this very soon.

Regarding actual implementation, what needs to be done is:

- add dependency to Keycloak Dev Svc to these extensions
- refactor Keycloak Dev Svc:
  -  logic when the Dev Svc is disabled needs to be moved from this Dev Svc extension to individual extensions (like OIDC says when it needs Dev Svc, and OIDC Client says when it needs Dev Svc) so that we can extend this extension to support KC Admin client etc.
  - config properties preset by the Dev Svc for individual extensions (like OIDC auth server url, OIDC Client auth server URL and others) must also be somehow owned by individual extensions and not by the Dev Svc

**Comment by sberyozkin** [comment]
Thanks @michalvavrik, I'll get back to it asap, once we get the very important PR you did related to the ConfigMapping migration merged, cheers !
