### ISSUE TITLE
Discuss the possibility of dropping quarkus-elytron-security-oauth2

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4416]
**Description**
`quarkus-oidc`which depends on `vertx-oauth2` will now be able to do the token introspection and also will attempt to link the verified tokens with smallrye-jwt.
It may be beneficial to avoid having both `quarkus-oidc` and `quarkus-elytron-security-oauth2` duplicating each other 

@loicmathieu Hi Loic, I know `quarkus-elytron-security-oauth2` is the one you've put the effort into :-), but it looks like it can be just subsumed by `quarkus-oidc` in terms of allowing the same introspection-based approach. 

@pedroigor, @stianst, @pmlopes, @stuartwdouglas FYI

**Comment by loicmathieu** [comment]
Hi @sberyozkin just come back and needs to have a look at `quarkus-oidc` to see if it can offers the same functionalities.

OIDC is "an identity layer on top of the OAuth2 protocol", so it should be based "on top of OAuth2" so you should have the OIDC extension that uses the OAuth2 one ... 
Reading the [spec](https://openid.net/specs/openid-connect-core-1_0.html) OIDC don't support all the OAuth2 standard flows (client_credential and resource_owner_passord flows are not supported by OIDC).

But if we can have an oauth2 extension that supports all the standard flow + the OIDC ones, and works with basic introspection endpoint (the one used by the current oauth2 extension) and OIDC introspection endpoint, sure, why not combining them. 
But in this case this should be named OAuth2 and not OIDC :)

IMHO, the decision to have one or two extensions should be decided by the number of third-party libraries needed for OIDC and not needed by OAUth2, and the possiility to expose comprehensive configuration options for both mode : basic OAuth2 and OIDC.

I saw that OIDC depends on `smallrye-jwt` so for me it's a no-go for a single extension as JWT will comes with a lot of dependencies ... so I would say two extension, but maybe one build on top of the other to avoid too much code duplication.

**Comment by sberyozkin** [comment]
@loicmathieu Hi, 
Well, the JWT dependency brings an option to expose the tokens as `JsonWebToken`, even if it is an opaque token, the introspection response provides enough info to emulate it as `JsonWebToken`. We may need to make sure that if someone excludes `smallrye-jwt` dependencies then it still work. But the consistent approach toward accessing these tokens is important. In fact, non-OIDC OAuth2 applications can well use JWT tokens too.

We'd need to support the opaque tokens for `quarkus-oidc` 'service' applications anyway in time, in fact we already support it, JWT tokens are introspected same way as the opaque tokens. So it would work right now for the opaque tokens (the only thing which will require a tweak in this case is to properly emulate it as JsonWebToken).

So effectively we now have 2 extensions duplicating each other as far as the token introspection is concerned :-). If we keep it we will have to rewrite it on top of Vertx ot make it reactive. But then again it won't solve the problem of the duplication.

Re OIDC vs Oauth2, in reality, most of the IDPs I'm aware of will support the client credentials, etc, so while IDP OIDCs do support the higher level flows, in many cases they are OAuth2 IDPs as well...

**Comment by loicmathieu** [comment]
@sberyozkin if the elytron-security-oauth2 integration test can works with the quarkus-oidc extension so the elytron-security-oauth2 extension can be replaced by it! You can try it :) this will definitly prove that the extension can be replaced by the OIDC one.

Then we will need to rename it if it is a general purpose OAuth2 extension and not only OIDC/JWT. Still I think that we must provides an extension without all the JWT dependencies.

**Comment by sberyozkin** [comment]
@loicmathieu there s no rush but sooner or later IMHO we'd need to do something about it. I'd not rename it though from `quarkus-oidc` to something else because OIDC can be considered an instance of Oauth2. So having 2 extensions doing similar things but one with one less dependency (smallrye-jwt) seems not right to me.

The JWT thing is not that big of a problem IMHO.
I mean, yes, there are some binary tokens flowing around - but as I said we can have them in the OIDC flows (1) at least one OIDC provider I know of uses the binary tokens and 2) OIDC specifies the tokens can be encryped - which becomes an opaque token). So I said we'd need to fix it for `quarkus-oidc` anyway (and probably at the Vertx level only unless it already works) and then the strange thing would be, if it is an opaque token, then we will have 2 extensions which can do it.

If some of the OAuth2 extension users asks, oh, we need to access the token properties. Then we'd start with creating some annotations doing similar things to MP JWT.
 
So having a common MP JWT Api for accessing whatever the tokens are is good IMHO, but we may also introduce a property like `disableTokenInjection` so if some users do not need any token info then they just excludes `smallrye-jwt`, set that property and all works.

It may end up being not too bad if we actually do it :-), lets review it later on, I'll ping you whenever I have some updates on the quarkus-oidc end :-), thanks

**Comment by sberyozkin** [comment]
@loicmathieu Hi Loic, by the way, I don't think the oauth2 extension will be deleted any time soon, might get deprecated, but I will hope `quarkus-oidc` will prove adequate for your requirements in time as well :-)

**Comment by sberyozkin** [comment]
Going to close it for now
