### ISSUE TITLE
[Extension Proposal] OpenFeature

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#44171]
### Description

OpenFeature is an open specification that provides a vendor-agnostic, community-driven API for feature flagging that works with your favorite feature flag management tool.

https://openfeature.dev/

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-open-feature

### Short description

feature flagging standard

### Repository Homepage URL

https://docs.quarkiverse.io/open-feature/dev/

### Repository Topics

- quarkus-extension
- feature-flag

### Team Members

- rmanibus
- ???

**Comment by melloware** [comment]
+1 this was asked for before: https://github.com/quarkusio/quarkus/issues/28032

I wonder if we should close that other old ticket?

**Comment by gastaldi** [comment]
@melloware I feel like you want to work on this extension too, is that accurate? 😃

**Comment by gastaldi** [comment]
What features would this extension provide besides using the library directly? Native compilation?

**Comment by melloware** [comment]
I will let @rmanibus chime in but i was hoping for 

- Ease of configuration
- Native Compilation
- Possible CDI injection (if not already offered) to make it easier to use

I didn't study the spec yet in fact I just learned about it from this post!

**Comment by rmanibus** [comment]
yes this is what I had in mind ! Also want to provide sub extensions for various providers:

 https://openfeature.dev/ecosystem/?instant_search%5BrefinementList%5D%5Btechnology%5D%5B0%5D=Java

**Comment by unknownbanana** [comment]
@melloware @gastaldi  Excuse the personal tag, but I am unable to find this extension in any of the official repositories. Is it discontinued?

**Comment by melloware** [comment]
@unknownbanana go star this project its incubating here: https://github.com/quarkiverse/quarkus-open-feature

**Comment by unknownbanana** [comment]
> [@unknownbanana](https://github.com/unknownbanana) go star this project its incubating here: https://github.com/quarkiverse/quarkus-open-feature

Done. 👍

**Comment by kito99** [comment]
@melloware what ended up happening with your feature flag work? I see the extension wasn't updated after the initial commit. I'm looking for something for https://speakertrax.com.

**Comment by melloware** [comment]
@rmanibus started this thread and I volunteered to help out on the extension but i haven't done anything with it. I am more than happy to help though!

**Comment by kito99** [comment]
@melloware ah, ok. did you end up using unleash for your client?

**Comment by melloware** [comment]
Yep Unleash is VERY nice.  But obviously its a SASS product i like the idea of this Open Feature Flags.
