### ISSUE TITLE
[Extension Proposal] Add a quarkus extension for Apache Fury

### ISSUE THREAD

**Issue by zhfeng** [quarkusio/quarkus#44211]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

[Apache Fury](https://fury.apache.org/) is a blazingly-fast multi-language serialization framework powered by JIT (just-in-time compilation) and zero-copy, providing up to 170x performance and ultimate ease of use.

We had some discussion to create a quarkus extension for fury and support for native build especially:
- https://github.com/apache/fury/issues/678

### Repository name

quarkus-fury

### Short description

A blazingly fast multi-language serialization framework powered by JIT and zero-copy.

### Repository Homepage URL

https://docs.quarkiverse.io/quarkus-fury/dev/

### Repository Topics

- quarkus-extension
- fury
- serialization
...

### Team Members

- @chaokunyang
- @zhfeng

**Comment by zhfeng** [comment]
@gastaldi can you help us to create `quarkus-fury`?

**Comment by gastaldi** [comment]
@zhfeng there you go: https://github.com/quarkiverse/quarkus-fury
