### ISSUE TITLE
Quarkus Console Logging Does Not Support UTF-8 Encoding

### ISSUE THREAD

**Issue by melodyfromheaven** [quarkusio/quarkus#44247]
### Describe the bug

I have encountered an issue with the console logging in Quarkus. It appears that the console log does not support UTF-8 encoding, which causes problems when logging messages containing non-ASCII characters, such as Korean characters.

Relate Issues
https://github.com/quarkusio/quarkus/issues/36919
https://stackoverflow.com/questions/78465679/when-starting-quarkus-with-quarkusdev-in-intellij-idea-the-console-displays-ch

It's 2024, and it's surprising this issue still exists. Quarkus should be better than Spring, right?

Quarkus version : 3.15.1

**Comment by dmlloyd** [comment]
Quarkus console logging does in fact support UTF-8 and any other character encoding supported by the JDK.

**Comment by geoand** [comment]
@dmlloyd so I assume there is nothing for us to do here?

**Comment by dmlloyd** [comment]
I think it should work as it is, right.
