### ISSUE TITLE
Missing Accept-Language header results in an empty list with `getAcceptableLanguages()`

### ISSUE THREAD

**Issue by koplas** [quarkusio/quarkus#44253]
### Describe the bug

The Reactive Resteasy implementation of `jakarta.ws.rs.core.HttpHeaders` differs from the documentation. If a request contains no `Accept-Language` header and `HttpHeaders.getAcceptableLangauges()` is called, it will return an empty list.

The documentation specifies that a wildcard locale is returned, if no acceptable languages are specified: https://jakarta.ee/specifications/platform/10/apidocs/jakarta/ws/rs/core/httpheaders#getAcceptableLanguages().

### Expected behavior

Calling  `HttpHeaders.getAcceptableLangauges()` returns a list with a single wildcard locale, if no acceptable language header is given.

### Actual behavior

Calling  `HttpHeaders.getAcceptableLangauges()` returns an empty list, if no acceptable language header is given.

### Additional information

The reason for this issue is here: https://github.com/quarkusio/quarkus/blob/e158abcf0256ddfc8d6dd1eb9adf790f6e3235e8/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/headers/HeaderUtil.java#L296
Instead of returning an empty list, it should return a wildcard locale, like it is done here: https://github.com/resteasy/resteasy/blob/91f23fff5eca4b45fba4f45b938dca2fe5c0d16d/resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java#L232

**Comment by geoand** [comment]
You are free to try it and we can see what CI says :)
