### ISSUE TITLE
Unexpected task for quarkus.smallrye-openapi.auto-add-tags

### ISSUE THREAD

**Issue by yk-littlepay** [quarkusio/quarkus#44260]
### Describe the bug

This [PR#43206](https://github.com/quarkusio/quarkus/pull/43206) has brought ambiguous and moreover undesirable behaviour to the generation of specifications

First of all, the connection is not entirely obvious why adding auto tag to each operation also adds a description to each operation. Moreover, ignoring even the annotation like this `@Operation(operationId = "createUser", description = "")`

Not to mention, It is also quite controversial why the method name is used to create the `description` and not the `summary` 
The `@Operation` documentation says that:
`summary` -  Provides a brief description of what this operation does. 
`description` - A verbose description of the operation behaviour. CommonMark syntax MAY be used for rich text representation.

The simplest thing I would like to suggest is to simply roll back those changes because they do not look useful enough, but simply add pollution to the specification

Well, or add another config property (like `quarkus.smallrye-openapi.operation.summary=auto` , instead of `auto` there may be some naming strategy) that would add automatic `summary` based on the method name

CC: @phillip-kruger and @cescoffier 

### Expected behavior

 `quarkus.smallrye-openapi.auto-add-tags=true` (which actually by default) must not affect anything other than auto adding tags to each operation.

### Actual behavior

 `quarkus.smallrye-openapi.auto-add-tags=true` adds a description if it is missing or even if it is empty by setting in `@Operation`  like this `@Operation(operationId = "getAllItems", description = "")`

### How to Reproduce?

1) Setup the project without  prop config `quarkus.smallrye-openapi.auto-add-tags=false`
2) Generate spec

**Comment by MikeEdgar** [comment]
Maybe the generated description should be for the tag and not the operation? That would require inserting/updating the tag in the array at `/tags`

**Comment by phillip-kruger** [comment]
Let's change this to be in a separate filter for operations, and change to summary (as suggested). This `AutoOperationSummaryFilter` should then also have a way to turn off via config. I'll prepare a PR
