### ISSUE TITLE
Quarkus Dev UI - Clicking on gRPC - Services - service implementation class  Uncaught exception received by Vert.x

### ISSUE THREAD

**Issue by jjpinto** [quarkusio/quarkus#44263]
### Describe the bug

**Describe the bug**
I am seeing errors when trying to use the Quarkus Dev UI (on Quarkus 3.16.1) clicking on the service implementation class.

![Image](https://github.com/user-attachments/assets/08d2f061-4095-4b4c-b99e-77b342898794)

### Expected behavior

A successful gRPC module opens like the same way as it is clicked on the down arrow.

### Actual behavior

Seeing error exception in Chrome

### How to Reproduce?

Run quickstart example grpc-plain-text
Open dev UI -> navigate Extensions -> gRPC -> Services
Click on **io.quarkus.grpc.examples.hello.HelloWorldService** implementation class 

### Output of `uname -a` or `ver`

Linux L91PLPG3 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 22.0.1 2024-04-16

### Quarkus version or git rev

3.16.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5

**Comment by alesj** [comment]
I'm trying / running `quarkus/integration-tests/grpc-vertx` as `mvn clean quarkus:dev` in upstream main,
and I'm not seeing the issue -- although it does say "Could not open your IDE" ...
