### ISSUE TITLE
Included pages within a fragment ignores rendered=false property.

### ISSUE THREAD

**Issue by LukasLeppich** [quarkusio/quarkus#44281]
### Describe the bug

If another page is included within a fragment, the rendered=false of fragments within the other page will be ignored.

In this example, there are two pages A and B. Page A has a fragment called "content" which includes page B. Page B has two fragments with rendered=false, only the first is rendered with include.

There are two endpoints:

- /page/ok -> renders page A completely
- /page/wrong -> renders only the content fragment within page A.

### Expected behavior

Both endpoints should produce the same output on screen:
```
Body content in fragment

Fragment B -> A

Fragments should not be rendered:

End of fragments part
```

### Actual behavior

The "ok" endpoint renders as expected. The "wrong" endpoint contains the A and B fragments from page B, even though the rendered property was set to false:
```
Body content in fragment

Fragment B -> A

Fragments should not be rendered:

Fragment B -> A

Fragment B -> B

End of fragments part
```
[](url)
### How to Reproduce?

Reproducer: https://github.com/LukasLeppich/qute-fragment-nesting

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.5073]

### Output of `java -version`

openjdk version "17.0.12" 2024-07-16

### Quarkus version or git rev

3.16.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

**Comment by mkouba** [comment]
I can confirm that if you render a fragment that includes a template that declares `{#fragment rendered=false}` then `rendered=false` is ignored.

This pull request should fix the problem: https://github.com/quarkusio/quarkus/pull/44298
