### ISSUE TITLE
quarkus jakarta.ws.rs timeout exception

### ISSUE THREAD

**Issue by jordensy** [quarkusio/quarkus#44285]
### Describe the bug

I get a timeout

2024-11-04 12:55:26,465 ERROR [io.qua.web.nex.run.WebSocketEndpointBase] (vert.x-eventloop-thread-2) Unable to send text message from Multi: WebSocket connection [endpointId=dev.langchain4j.quarkus.workshop.CustomerSupportAgentWebSocket, path=/customer-support-agent, id=f7d7e5ae-53c4-48a9-9eec-bfdb71ffef01] : io.vertx.core.impl.NoStackTraceTimeoutException: The timeout period of 10000ms has been exceeded while executing POST /api/chat for server null

### Expected behavior

No time out but an answer from the LLM and a response to the client websocket

### Actual behavior

the Quarkus workshop UI keeps waiting for an answer as it does not handle the runtime exception

### How to Reproduce?

build the project mvn quarkus:dev
Open the URL in browser: send a message from the ai chat

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.4317]

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Corretto-21.0.1.12.1 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.16.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.13.0

### Additional information

Running any of the steps from  https://github.com/cescoffier/quarkus-langchain4j-workshop/tree/main gives me issues. Even with the same versions as set in their POM.

Changing this to the latest version gives other errors. 

See attached a step-01 that I have modified up to step-05. But I even can't get step-01 back to work.

Is quarkus-lanchan4J at this moment to unstable to use (from my opinion yes, but I not the most advanced Java developer so I might miss things some one else does not). So I hope that this issue can contribute to getting it more stable As I read there are other people with same issue.

The most important difference is that I do not have an open-ai key so I use Ollama! I see it is experimental as is easy-rag and a lot of other extensions so not sure if these extensions are already ready to use for production?

[step-01.zip](https://github.com/user-attachments/files/17617861/step-01.zip)

**Comment by geoand** [comment]
> Is quarkus-lanchan4J at this moment to unstable to use (from my opinion yes, but I not the most advanced Java developer so I might miss things some one else does not). So I hope that this issue can contribute to getting it more stable As I read there are other people with same issue.

The issue has nothing to do with Quarkus LangChain4j to be honest.

**Comment by geoand** [comment]
Closing for lack of feedback
