### ISSUE TITLE
quarkus-oidc should support a discovery endpoint

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4429]
**Description**
Right now `quarkus-oidc` has the following mechanism to configure the IDP endpoint addresses:
```
auth-base-url = http://host:port/idp
introspection-path=introspection
// etc for other IDP endpoints
``` 
Stian recommends supporting a discovery endpoint as a better alternative, the users will only configure a discovery endpoint address and the adapter will find out about all the required endpoints and other IDP properties.

**Implementation ideas**
Here are few possible options.
1. Introduce a `discovery-url` property which is a complete URL and document that if it is set then `auth-base-url` and all relative path properties such as `introspection-path` will be ignored
2. Introduce a `discovery-path` relative path property
```
auth-base-url = http://host:port/idp
discovery-path=discovery
``` 

Option 1 may offer a better separation between the manual IDP endpoints configuration and the auto-discovery of the same configuration.
Option 2 may be preferred if it could be useful for the adapter be aware of the base IDP URL even with the auto-discovery being enabled  

@stianst, @pedroigor FYI

**Comment by sberyozkin** [comment]
Right now it is [still tied to Keycloak](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/VertxKeycloakRecorder.java#L54) apparently so does not look like it will work with other providers for 0.24.0.

**Comment by pedroigor** [comment]
I think `auth-server-url` should be enough to support different providers. I've looked other providers such as Google and Azure, and for them, you can use the following URIs:

* `Google`: https://accounts.google.com/.well-known/openid-configuration
* `Azure`: https://login.microsoftonline.com/{tenant}/.well-known/openid-configuration

Maybe we could rename the `auth-server-url` to `issuer-url`?

**Comment by stianst** [comment]
Actually I would default to assuming Discovery endpoint is available.

With Discovery the config would be:

> auth-server-url=https://myidp.com/auth/realms/myrealm

Without Discovery I would support setting config fields from the [Discovery endpoint](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) directly in the config:

> oidc-issuer=http://localhost:8080/auth/realms/myrealm
> oidc-authorization_endpoint=http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/auth
> oidc-token_endpoint=http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token
> oidc-jwks_uri=http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs

A note here is that the base URL of the endpoints can be different. For example `authorization_endpoint` can point to a public domain name, while `token_endpoint` point to an internal IP address.

Not sure if property names should be prefixed with `oidc-` and also not sure if `_` should be converted to `-`.

The logic from the extension would be:

* Use Discovery endpoint unless `issuer` is specified (this should be assumed the default as most proper OIDC IdPs support this)
* If `issuer` is specified the required properties to list depends on the use-case. For example `authorization_endpoint` is only needed if authorization code flows are done (aka server-side web app)

Does the property files support some sort of replacement? So `authorization_endpoint=${issuer}/protocol/openid-connect/auth` could work?

With regards to being able to specify public key which is not a URL we probably would need to support both PEM and JWK encoded keys (base64 as it's a JSON structure).

**Comment by sberyozkin** [comment]
Quarkus has a '-' pattern

**Comment by stianst** [comment]
auth-base-url is fine by me. I wouldn't do `discovery-url` though, I'd just stick with `auth-base-url` in both cases. As I was thinking about it some more I found discovery-url a bit to technical.

In documentation I would start with assuming IdP supports Discovery and ask users to set `auth-base-url` to the IdP base url (which from OIDC discovery spec by adding .well-known/openid-configuration you should get discovery endpoint). Then as a separate section add a section if IdP doesn't support discovery.

**Comment by sberyozkin** [comment]
@stianst 
Sounds good, we just say then that all one has to do is to set `auth-base-url` if the IDP is known to implement the discovery. The adapter can try to discover, if 404 then check if the specific URLs are available (or may be it can do both actions, etc).
Thanks

**Comment by sberyozkin** [comment]
The discovery protocol is supported
