### ISSUE TITLE
allow custom `jakarta.ws.rs.ext.RuntimeDelegate` via configuration

### ISSUE THREAD

**Issue by kpagratis** [quarkusio/quarkus#44301]
### Description

We have a requirement where we need to use our own `jakarta.ws.rs.core.UriBuilder` when using quarkus REST.
We originally registered our implementation via the java service loader and this work in dev mode but stoped working in prod mode. 
We got around this issue by calling  `jakarta.ws.rs.ext.RuntimeDelegate::setInstance` in a startup method. It would be great if there was a configuration that could be set to defind the RuntimeDelgate to use. If this optional field is missing, then the default jboss delegate can be chosen.

### Implementation ideas

The runtime delegate is defined in the `ResteasyReactiveCommonProvessor` class on line 342 on tag `3.16`.
It seems like this could be executed conditionally based on a configuration value.

**Comment by geoand** [comment]
Thanks for reporting!

Mind providing a sample application that shows what you were doing and stopped working?

**Comment by kpagratis** [comment]
Sure I can cobble something together. Are you saying https://github.com/quarkusio/quarkus/pull/44335 fixes the problem?

I had created a `META-INF/services/jakarta.ws.rs.ext.RuntimeDelegate` where the first line was my delegate `com.example.MyRuntimeDelegate` and this worked in devmode but not in prod mode (`quarkusRun`)
I can try again if you let me know how to test with 44335

**Comment by geoand** [comment]
If it doesn't work, I certainly want to see what's going 🙂
