### ISSUE TITLE
When testing request payload is populated with string "null" if enable-reflection-free-serializers enabled

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#44300]
### Describe the bug

3.15.1 works but in 3.16.1 our tests fail when `enable-reflection-free-serializers enabled`.

What happens is it populates null String values with the string `"null`" instead of leaving it null.

It seems to work fine when running and just happens in tests.  It also does not seem to happen in every test because similar tests do no exhibit the issue.

### Expected behavior

Null values are left null and not populated with a string "null"

### Actual behavior

String values at least are populated with "null" (as a string) instead of being left null

### How to Reproduce?

1. Run `mvn install -DskipTest`
2. Set a breakpoint on the "resource" method `hello`
3. Debug using the test case - the "request" will have null string values populated with "null"

![Image](https://github.com/user-attachments/assets/64c12b4f-520d-4cd5-aed4-691d35b009ba)

4. Set quarkus.rest.jackson.optimization.enable-reflection-free-serializers=false
5. Repeat steps 2 & 3 above
6. The body is correct

![Image](https://github.com/user-attachments/assets/d94d3a41-0cbf-4f47-87d3-631f37738560)

[code-with-quarkus.zip](https://github.com/user-attachments/files/17621228/code-with-quarkus.zip)

### Quarkus version or git rev

3.16.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by mariofusco** [comment]
I will give a look.

**Comment by mariofusco** [comment]
This should fix the problem https://github.com/quarkusio/quarkus/pull/44309
