### ISSUE TITLE
Bean Validation and Eclipse MicroProfile Spec

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#4431]
**Description**

Hi today I was thinking that it would be interesting to have bean validation integrated with Config API (maybe not per spec but as a feature we are offering in Quarkus) so for example, you can do:

```
@Min(1)
@Max(3)
@ConfigProperty(name = "greeting.repeat", defaultValue = "1")
 int numberOfRepetitions;
```

And if a criteria is not met at runtime, then we can abort the boot process and show the message.

**Implementation ideas**

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/y95HxiHX1iI/NqYLqU5-BwAJ

**Comment by emmanuelbernard** [comment]
I like the idea but will close it. Can you open a sister issue in SmallRye so we can implement it there. And then we can propose it to the MP to improve the spec. cc @kenfinnigan

**Comment by emmanuelbernard** [comment]
that was a remark to @lordofthejars - forgot to add ;)
