### ISSUE TITLE
ProdModTestResults retained logs contain non-interpolated messages

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#44310]
### Describe the bug

I'd like to test that my extension is properly logging a warning in some cases. The extension is using a JBoss Logger instance for this. I have a test set up using QuarkusProdModeTest and would like to check that the retained logs (I have set up a log record predicate to match my logger's name) contain a given value. However, when debugging the tests, I can see that the test is failing because, while the proper log record exists in the test results, its message is not interpolated (despite having the parameters being properly recorded to do the interpolation).

### Expected behavior

Retained log messages should be the "final" version of the message, not the raw, not-interpolated version.

### Actual behavior

Log message is as setup in my logger, with the placeholders and the parameters, but not interpolated.

### How to Reproduce?

See https://github.com/quarkiverse/quarkus-operator-sdk/pull/988

**Comment by geoand** [comment]
This actually seems to work as intended as the log records (`org.jboss.logmanager.ExtLogRecord`) contain all the information necessary before the output being formatted (by `org.jboss.logmanager.ExtFormatter`).

**Comment by metacosm** [comment]
OK, this should be documented at the very least 😅

**Comment by gsmet** [comment]
``LogRecord``s are the raw data structure sent to the logger. The message is not yet interpolated there and you can actually assert on anything of the data structure.

**Comment by metacosm** [comment]
Perhaps this method should return the interpolated version (by applying format to each record as shown above) and have another method to get the raw records? This would help with the least-surprise principle as, as a user, I would expect the logs to be in the final state when calling this method.
