### ISSUE TITLE
Not found artifact

### ISSUE THREAD

**Issue by oflorez-airgraft** [quarkusio/quarkus#44327]
### Describe the bug

i upgrade my app from 3.15.1 to 3.16.1 and i got this Could not find artifact io.quarkus:quarkus-rest-client-reactive-jackson:pom:3.16.1, before upgrade was working fine with version 3.15.1

### Expected behavior

get all the dependencies

### Actual behavior

missing io.quarkus:quarkus-rest-client-reactive-jackson:pom:3.16.1

### How to Reproduce?

mvn clean install or mvn clean install -U

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-21.0.5+11

### Quarkus version or git rev

3.16.1

**Comment by manofthepeace** [comment]
you need to use `quarkus-rest-client-jackson`

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.16#big-reactive-rename-compatibility-layer-gone

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#resteasy-reactive-extensions-renamed-to-quarkus-rest-gear-white_check_mark
