### ISSUE TITLE
Remove `com.google.code.findbugs:jsr305` from gRPC

### ISSUE THREAD

**Issue by mabartos** [quarkusio/quarkus#44325]
### Description

Is it necessary to have included the `com.google.code.findbugs:jsr305` dependency for gRPC common extension? 

The latest release of this dependency was 2017 and it moved to `com.github.spotbugs:spotbugs-annotations`.

Is it possible to revisit it and if necessary, using the `spotbugs-annotations` ? 

Related to https://github.com/keycloak/keycloak/issues/34396

**Comment by cescoffier** [comment]
If I'm not mistaken it is used in the generate Java code.

**Comment by cescoffier** [comment]
My bad, it's not the case. It's a dependency of grpc-core, that seems to have been removed. We would need to test without it.
