### ISSUE TITLE
Migration guide 3.16 does not mention breaking changes on @WithTestResource

### ISSUE THREAD

**Issue by jorgebsa** [quarkusio/quarkus#44337]
### Description

Upgrading a Quarkus 3.15.1 application that declares `@WithTestResource(restrictToAnnotatedClass = false ...)` results in compilation errors.

The javadoc mentions the following, which would be nice to have on the migration guide as well:

```java
/**
 * Used to define a test resource, which can affect various aspects of the application lifecycle.
 * <p>
 * As of Quarkus 3.16, the default behavior of the annotation (meaning that {@code scope} has not been set)
 * is that test classes annotated with the same {@code WithTestResource} will <strong>not</strong> force a restart
 * of Quarkus.
 * <p>
 * The equivalent behavior to {@code QuarkusTestResource(restrictToAnnotatedClass = false)} is to use
 * {@code WithTestResource(scope = TestResourceScope.GLOBAL)},
 * while the equivalent behavior to {@code QuarkusTestResource(restrictToAnnotatedClass = true)} is to use
 * {@code WithTestResource(scope = TestResourceScope.RESTRICTED_TO_CLASS)},
```

I haven't tried the update with quarkus cli or maven plugin, this was detected by Renovate bot and failing Actions

### Implementation ideas

Add a section on Migration guide 3.16 with a comment similar to the javadoc

**Comment by geoand** [comment]
Thanks, I updated the [wiki](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.16#withtestresource)
