### ISSUE TITLE
Using ContextLocals in event observers

### ISSUE THREAD

**Issue by ls-bit** [quarkusio/quarkus#44349]
### Description

We try to pass some information via `io.smallrye.common.vertx.ContextLocals` (Vertx context) in our application. When trying to set ContextLocals in a StartupEvent observer it fails with exception:

```java
    void onStart(@Observes StartupEvent event) {
          ContextLocals.put("foo", "bar"); // fails `Caused by: java.lang.UnsupportedOperationException: Access to Context Locals are forbidden from a 'root' context  as it can leak data between unrelated processing. Make sure the method runs on a 'duplicated' (local) Context`
    }
```

`VertxContextSupport` introduced in #29466 looked promising, but seems to be aimed at usage with reactive code. https://quarkus.io/guides/vertx#executing-asynchronous-code-from-a-blocking-thread

Using `VertxContextSupport` we are able to set the ContextLocal but then using EntityManager fails:

```java
    void onStart(@Observes StartupEvent event) throws Throwable {
        VertxContextSupport.subscribeAndAwait(() ->
            Uni.createFrom()
                .item(() -> {
                    ContextLocals.put("foo", "bar"); // works
                    entityManager.find(...) // fails `io.quarkus.runtime.BlockingOperationNotAllowedException: Cannot start a JTA transaction from the IO thread.`
                    return null;
                })
        );
  }
```

Is there a way to make `ContextLocals` work in event observers for non-reactive code?

Or do we have to switch to another mechanism to pass information in that case? `ContextLocals` work already with Quarkus REST, gRPC, scheduler etc., so it would be annoying to use a different mechanism only for event observers.

**Comment by geoand** [comment]
What is the use case for using `ContextLocal` when observing events?

**Comment by ls-bit** [comment]
Our use case is that we are parsing tenant information in a `ContainerRequestFilter` and setting it in a `ContextLocal`. The tenant info from `ContextLocal` is then used by quarkus / hibernate in a `TenantResolver` to select the tenant datasource. This works fine.

In some cases we want to execute some database logic for tenants on startup or other events, so it would be convenient to also set the tenant info in the same way as for requests etc. with the `ContextLocal`.

I am gladly taking suggestions if there is a more recommended way to do it 😄

**Comment by cescoffier** [comment]
It works when you are in the flow of a http request processing (or message processing), but there is real flow for startup events. 

Let's see what @mkouba thinks.

**Comment by mkouba** [comment]
@ls-bit @cescoffier With Quarkus 3.16+ you can use `VertxContextSupport#executeBlocking(Callable<T>)` to execute some blocking logic on a Vertx duplicated context. For older versions of Quarkus you would need to copy this code.
