### ISSUE TITLE
Missing quarkus-smallrye-reactive-messaging and quarkus-smallrye-reactive-messaging-kotlin in 3.16.1

### ISSUE THREAD

**Issue by akoufa** [quarkusio/quarkus#44347]
### Describe the bug

Hello updating my Quarkus project to the 3.16.1 produces the following issues:

  > Could not find io.quarkus:quarkus-smallrye-reactive-messaging-kafka:.
     Required by:
         root project :
   > Could not find io.quarkus:quarkus-smallrye-reactive-messaging-kotlin:.
     Required by:
         root project :

Is this expected ?

**Comment by geoand** [comment]
The relocations were removed, so you need to use `quarkus-messaging-kotlin`

**Comment by akoufa** [comment]
Oh thanks and sorry for the spam. Somehow I never found out about the quarkus-messaging-kotlin ones.

**Comment by geoand** [comment]
NP!
