### ISSUE TITLE
Log file handler rotation maximum size is exceeded when process name is long

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#44346]
### Describe the bug

I am using Quarkus Log File Handler rotation and set maximum file size to 5K, `quarkus.log.handler.file.access-log.rotation.max-file-size=5K`, however when my process name is long (like in native, or when my JDK is installed in quite nested directory), maximum file size is exceeded.

### Expected behavior

Regardless of a process name value, maximum file size should be respected.

### Actual behavior

When the process name is long, log file size is longer (5335 or 5336 bytes). When I add `Runtime.getRuntime().halt(1)` after failing test assertion, I can see that log file is too big.

```
mvavrik@fedora:/tmp/aaaaaaaaaaaaaaaaaaaaaaaa/bbbbbbbbbbbbbbbbbbbbbbbbbbbb/ccccccccccccccccccccccccccc/ddddddddddddddddddddddddddd/eeeeeeeeeeeeeeeeeeeeeeeeeee/fffffffffffffffffffff/guesswhat/ggggggggggggggggggggggg/quarkus-test-suite/logging/jboss$ ls -la target/AccessLoggingIT/app/appAccess.log
-rw-r--r--. 1 mvavrik mvavrik 5336 Nov  6 14:02 target/AccessLoggingIT/app/appAccess.log
```

### How to Reproduce?

```
cd /tmp
mkdir -p aaaaaaaaaaaaaaaaaaaaaaaa/bbbbbbbbbbbbbbbbbbbbbbbbbbbb/ccccccccccccccccccccccccccc/ddddddddddddddddddddddddddd/eeeeeeeeeeeeeeeeeeeeeeeeeee/fffffffffffffffffffff/guesswhat/ggggggggggggggggggggggg
cd aaaaaaaaaaaaaaaaaaaaaaaa/bbbbbbbbbbbbbbbbbbbbbbbbbbbb/ccccccccccccccccccccccccccc/ddddddddddddddddddddddddddd/eeeeeeeeeeeeeeeeeeeeeeeeeee/fffffffffffffffffffff/guesswhat/ggggggggggggggggggggggg
git clone git@github.com:michalvavrik/quarkus-test-suite.git -b feature/jboss-logging-max-size-reproducer
cd quarkus-test-suite/logging/jboss

NATIVE:
mvn clean verify -Dit.test=AccessLoggingIT#logRotationTest -Dnative -Dreruns=0

JVM:
# download and unzip OpenJDK from https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?product=core.service.openjdk&downloadType=distributions
export JAVA_HOME="/tmp/aaaaaaaaaaaaaaaaaaaaaaaa/bbbbbbbbbbbbbbbbbbbbbbbbbbbb/ccccccccccccccccccccccccccc/ddddddddddddddddddddddddddd/eeeeeeeeeeeeeeeeeeeeeeeeeee/fffffffffffffffffffff/guesswhat/ggggggggggggggggggggggg/quarkus-test-suite/long-java-home/java-21-openjdk-21.0.5.0.11-1.portable.jdk.x86_64"
export PATH="$JAVA_HOME/bin:$PATH"
mvn clean verify -Dit.test=AccessLoggingIT#logRotationTest -Dreruns=0
```

### Output of `uname -a` or `ver`

Fedora 41, RHEL8

### Output of `java -version`

OpenJDK Runtime Environment (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11-LTS)

### Quarkus version or git rev

3.15.1, 999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

**Comment by gsmet** [comment]
I will defer to @jamezp and @dmlloyd but I'm not convinced it's worth fixing.

**Comment by dmlloyd** [comment]
This is not really fixable. The user could create a directory that only allows for one-character log file names for example. There's not much we can do about it at our end.

To work around the specific problem, change the output directory of the log handler using the `quarkus.log.file.path` property to put the log files in a less-nested directory. Otherwise my recommendation is: don't do that!

**Comment by michalvavrik** [comment]
Alright, thank you. Can you please document scenarios under which `quarkus.log.handler.file."file-handlers".rotation.max-file-size` works? I just spend 2 days to figure why this test is failing and I can assure you I wouldn't if it was documented, which is my motivation to have this documented. Thank you

**Comment by michalvavrik** [comment]
FYI @dmlloyd my colleague created this test based on your suggestion in https://issues.redhat.com/browse/QUARKUS-4663.

**Comment by michalvavrik** [comment]
Hope I don't overwhelm you with information, but here is how access log looks like on my local machine with short paths in JVM (just FYI):

```
{"timestamp":"2024-11-06T20:54:13.67287682+01:00","sequence":228,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.http.access-log","level":"INFO","message":"127.0.0.1 - - [06/Nov/2024:20:54:13 +0100] \"GET /access HTTP/1.1\" 200 12","threadName":"executor-thread-1","threadId":34,"mdc":{},"ndc":"","hostName":"fedora","processName":"/home/mvavrik/.sdkman/candidates/java/21.0.5-tem/bin/java","processId":21426}
{"timestamp":"2024-11-06T20:54:13.679976273+01:00","sequence":229,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.http.access-log","level":"INFO","message":"127.0.0.1 - - [06/Nov/2024:20:54:13 +0100] \"GET /access HTTP/1.1\" 200 12","threadName":"executor-thread-1","threadId":34,"mdc":{},"ndc":"","hostName":"fedora","processName":"/home/mvavrik/.sdkman/candidates/java/21.0.5-tem/bin/java","processId":21426}
{"timestamp":"2024-11-06T20:54:13.685111704+01:00","sequence":230,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.http.access-log","level":"INFO","message":"127.0.0.1 - - [06/Nov/2024:20:54:13 +0100] \"GET /access HTTP/1.1\" 200 12","threadName":"executor-thread-1","threadId":34,"mdc":{},"ndc":"","hostName":"fedora","processName":"/home/mvavrik/.sdkman/candidates/java/21.0.5-tem/bin/java","processId":21426}
{"timestamp":"2024-11-06T20:54:13.690072301+01:00","sequence":231,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.http.access-log","level":"INFO","message":"127.0.0.1 - - [06/Nov/2024:20:54:13 +0100] \"GET /access HTTP/1.1\" 200 12","threadName":"executor-thread-1","threadId":34,"mdc":{},"ndc":"","hostName":"fedora","processName":"/home/mvavrik/.sdkman/candidates/java/21.0.5-tem/bin/java","processId":21426}
{"timestamp":"2024-11-06T20:54:13.696166336+01:00","sequence":232,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.http.access-log","level":"INFO","message":"127.0.0.1 - - [06/Nov/2024:20:54:13 +0100] \"GET /access HTTP/1.1\" 200 12","threadName":"executor-thread-1","threadId":34,"mdc":{},"ndc":"","hostName":"fedora","processName":"/home/mvavrik/.sdkman/candidates/java/21.0.5-tem/bin/java","processId":21426}
{"timestamp":"2024-11-06T20:54:13.702358258+01:00","sequence":233,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.http.access-log","level":"INFO","message":"127.0.0.1 - - [06/Nov/2024:20:54:13 +0100] \"GET /access HTTP/1.1\" 200 12","threadName":"executor-thread-1","threadId":34,"mdc":{},"ndc":"","hostName":"fedora","processName":"/home/mvavrik/.sdkman/candidates/java/21.0.5-tem/bin/java","processId":21426}
{"timestamp":"2024-11-06T20:54:13.707562972+01:00","sequence":234,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.http.access-log","level":"INFO","message":"127.0.0.1 - - [06/Nov/2024:20:54:13 +0100] \"GET /access HTTP/1.1\" 200 12","threadName":"executor-thread-1","threadId":34,"mdc":{},"ndc":"","hostName":"fedora","processName":"/home/mvavrik/.sdkman/candidates/java/21.0.5-tem/bin/java","processId":21426}
{"timestamp":"2024-11-06T20:54:13.714684917+01:00","sequence":235,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.http.access-log","level":"INFO","message":"127.0.0.1 - - [06/Nov/2024:20:54:13 +0100] \"GET /access HTTP/1.1\" 200 12","threadName":"executor-thread-1","threadId":34,"mdc":{},"ndc":"","hostName":"fedora","processName":"/home/mvavrik/.sdkman/candidates/java/21.0.5-tem/bin/java","processId":21426}
```

**Comment by dmlloyd** [comment]
OK I misread the error, I thought you were saying "the file name is too long when the process name is long". Let me look at the code before I answer to make sure I don't give wrong information (again).

**Comment by michalvavrik** [comment]
> OK I misread the error, I thought you were saying "the file name is too long when the process name is long". Let me look at the code before I answer to make sure I don't give wrong information (again).

no worry, and yes, I think it is "operation name" because that was the only difference I could see from my machine to Jenkins run. And only way I could reproduce it, but I can easily be wrong.

What makes this weird for me is that I would expect this line

```
{"timestamp":"2024-11-06T20:54:13.714684917+01:00","sequence":235,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.http.access-log","level":"INFO","message":"127.0.0.1 - - [06/Nov/2024:20:54:13 +0100] \"GET /access HTTP/1.1\" 200 12","threadName":"executor-thread-1","threadId":34,"mdc":{},"ndc":"","hostName":"fedora","processName":"/home/mvavrik/.sdkman/candidates/java/21.0.5-tem/bin/java","processId":21426}
```

to be treated as any other log message, in which case I don't know why max size doesn't work.

**Comment by dmlloyd** [comment]
OK the way the logic works, the file size check is performed after the log record is written. So, if your rotation limit is a *hard* limit on the file size, and particularly when that limit is quite small, it's going to cause a problem because it's quite possible to (for example) fabricate e.g. a `GET` URI which itself already exceeds the size.

So, I'm not quite sure how to proceed here. What is the use case which requires such a limited file size?

**Comment by geoand** [comment]
@michalvavrik are you trying to stress the logging rotation subsystem or is there an actual use case for the 5k size limit?
If it's the former, I think we should just document that having a very low limit can be problematic

**Comment by michalvavrik** [comment]
> [@michalvavrik](https://github.com/michalvavrik) are you trying to stress the logging rotation subsystem or is there an actual use case for the 5k size limit? If it's the former, I think we should just document that having a very low limit can be problematic

Just to be clear, I can think of loads of better things to do than finding unimportant bugs :-D Here is why I opened this issue https://github.com/quarkusio/quarkus/issues/44346#issuecomment-2462364792.

**Comment by geoand** [comment]
Sure yeah, I didn't mean that you were mindlessly looking to break things :)

**Comment by michalvavrik** [comment]
Yeah, I can see the other side. But usually when a test is failing in very rare circumstances, I cannot just say "give it up". Now that @dmlloyd explained the issue to me, I'll fix the test for us (allow bigger size). From user POV, note to docs would be good.

**Comment by dmlloyd** [comment]
OK, here's what the documentation states:

```
[quarkus.log.file.rotation.max-file-size](https://quarkus.io/guides/logging#quarkus-core_quarkus-log-file-rotation-max-file-size)

The maximum log file size, after which a rotation is executed.

Environment variable: QUARKUS_LOG_FILE_ROTATION_MAX_FILE_SIZE
```

The key word here is "after". But it's subtle so maybe we need to expand on that a little bit?

**Comment by michalvavrik** [comment]
> OK, here's what the documentation states:
> 
> ```
> [quarkus.log.file.rotation.max-file-size](https://quarkus.io/guides/logging#quarkus-core_quarkus-log-file-rotation-max-file-size)
> 
> The maximum log file size, after which a rotation is executed.
> 
> Environment variable: QUARKUS_LOG_FILE_ROTATION_MAX_FILE_SIZE
> ```
> 
> The key word here is "after". But it's subtle so maybe we need to expand on that a little bit?

+1 for little more, I do interpret docs statement differently.
