### ISSUE TITLE
Test profile + microprofile rest client configuration + native + QuarkusIntegrationTest failure

### ISSUE THREAD

**Issue by edeweerd1A** [quarkusio/quarkus#44354]
### Describe the bug

Probably a niche issue. It concerns running QuarkusIntegrationTest with a microprofile using REST clients.

The resolution of the client URL is not working as expected.

We have the following:

```
remote-api/mp-rest/url=http://localhost:8081
quarkus.test.native-image-profile=test
%test.remote-api/mp-rest/url=${injected-value}
injected-value=http://localhost:9990
```

The remote URL of the remote-api is read from a dedicated configuration property `injected-value`.
And the URL is injected using prefix/mp-rest/url configuration.
If we use the Quarkus REST client one it works:

```
%test.quarkus.rest-client.remote-api.url=${injected-value}
```

### Expected behavior

Using the test profile in a QuarkusIntegrationTest makes %test.remote-api/mp-rest/url=${injected-value} being taken into account.

### Actual behavior

Timeout:

```
2024-11-06 17:57:45,593 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: d53013c1-ae6a-40b9-a140-960fba9f2c8c-1: jakarta.ws.rs.ProcessingException: The timeout period of 30000ms has been exceeded while executing GET /hello for server null
```

### How to Reproduce?

A reproducer is provided:

[reproducer-config-ignored-native.zip](https://github.com/user-attachments/files/17650681/reproducer-config-ignored-native.zip)

Just run:

```
mvn clean install -Pnative
```

### Output of `uname -a` or `ver`

Linux 6.5.0-45-generic 22.04.1-Ubuntu x86_64

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22)

### Quarkus version or git rev

3.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

**Comment by geoand** [comment]
When running `@QuarkusIntegrationTest`, `%test` isn't applied as the application runs in production mode.
