### ISSUE TITLE
Support `@ConfigDocSection` on super interfaces

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#44381]
### Description

In #44374, I was able to use `@ConfigDocSection` to mark individual sections in the `OidcTenantConfg`  interface.

This interface extends `OidcClientCommonConfig` which has a large [Credentials](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcClientCommonConfig.java#L51) mapping but applying `@ConfigDocSection` to it fails the documentation build because no config root information can be found at its level. 

It would be great if it were supported at the super interface level as well. @radcortez, if you can weave some magic over the next few weeks or later, it would be nice

**Comment by gsmet** [comment]
I'll have a look given I rewrote that part recently.

**Comment by gsmet** [comment]
This was fixed by https://github.com/quarkusio/quarkus/pull/44388 .
