### ISSUE TITLE
Remote Development not working because of missing /q/dev endpoints

### ISSUE THREAD

**Issue by ueberfuhr** [quarkusio/quarkus#44404]
### Describe the bug

When I create a simple quarkus project and deploy it to OpenShift for remote development, the pods, services and routes are created and I can invoke the `hello` endpoint successfully. But the Dev UI is missing, and connecting to the application for remote development is failing. What am I missing? I tested with the current version of Quarkus as well as some older versions. They alle behave the same.

### Expected behavior

This should connect to the application for remote development.

### Actual behavior

In the container, the logs look fine:

```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec -a "java" java -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar
INFO running in /deployments
Press [e] to edit command line args (currently ''), [h] for more options>
2024-11-09 20:30:18,464 INFO [io.qua.kub.dep.PropertyUtil] (build-3) Kubernetes manifests are generated with 'The container port http' having default value '8080'. The app and manifests will get out of sync if the property 'quarkus.http.port' is changed at runtime.
2024-11-09 20:30:18,483 WARN [io.qua.kub.dep.KubernetesProcessor] (build-3) No project was detected, skipping generation of kubernetes manifests!
__ ____ __ _____ ___ __ ____ ______
--/ __ \/ / / / _ | / _ \/ //_/ / / / __/
-/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-11-09 20:30:20,279 INFO [io.quarkus] (Quarkus Main Thread) openshift-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.16.2) started in 3.865s. Listening on: http://0.0.0.0:8080
2024-11-09 20:30:20,285 INFO [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-11-09 20:30:20,285 INFO [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, kubernetes, rest, smallrye-context-propagation, vertx]
```

But the landing page in the browser doesn't show up the DEV endpoints (they are correctly initialized when running the app locally):

![Image](https://github.com/user-attachments/assets/090ebc24-9163-4e6a-9b49-9ed351ad03f5)

So connecting to the application for remote development shows up these logs:

```
Listening for transport dt_socket at address: 5005
2024-11-09 21:32:28,576 INFO  [io.qua.kub.dep.PropertyUtil] (build-19) OpenShift manifests are generated with 'The container port http' having default value '8080'. The app and manifests will get out of sync if the property 'quarkus.http.port' is changed at runtime.
2024-11-09 21:32:28,959 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1000ms
2024-11-09 21:32:29,827 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Remote dev request failed: java.io.IOException: Server did not start a remote dev session. Make sure the environment variable 'QUARKUS_LAUNCH_DEVMODE' is set to 'true' when launching the server
```

### How to Reproduce?

These are the commands (while connected to an OpenShift project):
```bash
mvn io.quarkus.platform:quarkus-maven-plugin:3.16.2:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=openshift-quickstart \
    -Dextensions='rest,openshift'
cd openshift-quickstart
mvn clean package -DskipTests \
    -Dquarkus.kubernetes.deploy=true \
    -Dquarkus.package.jar.type=mutable-jar \
    -Dquarkus.live-reload.password=changeit \
    -Dquarkus.container-image.build=true \
    -Dquarkus.kubernetes-client.trust-certs=true \
    -Dquarkus.kubernetes.deployment-target=openshift \
    -Dquarkus.openshift.route.expose=true \
    -Dquarkus.openshift.env.vars.quarkus-launch-devmode=true
# after some time the pod is started
mvn quarkus:remote-dev \
    -Dquarkus.package.jar.type=mutable-jar \
    -Dquarkus.live-reload.password=changeit
    -Dquarkus.live-reload.url=http://<APP_ROUTE_URL>
```

### Output of `uname -a` or `ver`

Darwin head 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:00:32 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6030 arm64

### Output of `java -version`

openjdk version "21.0.4" 2024-07-16 OpenJDK Runtime Environment Homebrew (build 21.0.4) OpenJDK 64-Bit Server VM Homebrew (build 21.0.4, mixed mode, sharing)

### Quarkus version or git rev

3.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937) Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec Java version: 21.0.4, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk@21/21.0.4/libexec/openjdk.jdk/Contents/Home Default locale: de_DE, platform encoding: UTF-8 OS name: "mac os x", version: "15.1", arch: "aarch64", family: "mac"

**Comment by maxandersen** [comment]
Did you follow the guide at https://quarkus.io/guides/maven-tooling#remote-development-mode where it explains settings you need to set + the environment variable to have set before remote Dev is enabled ?

**Comment by ueberfuhr** [comment]
- ✅ Set the properties for live reload and mutable JAR per command line, but also tested it with the properties placed in the  `application.properties` file directly
- ✅ The environment variable `QUARKUS_LAUNCH_DEVMODE` in the container is set to `true`. As you can see in the container logs, it tells me that DEV mode is enabled.

I could not find any details about the conditions for the Dev UI to get activated, except that the application needs to be running in dev mode. 🤷‍♂️

**Comment by maxandersen** [comment]
Dev ui isnt exposed in remote Dev as it would leak secrets.

**Comment by ueberfuhr** [comment]
@maxandersen - I have tested a little around, and I found out that I also had to explicitely set the env var `JAVA_ENABLE_DEBUG` to a value of `true`. Now, the `quarkus:remote-dev` goal can connect to the container. Could you please verify if this is a correct behaviour? It is not documented in https://quarkus.io/guides/maven-tooling#remote-development-mode, but maybe this is an OpenShift-specific issue? (depending on the base image?)
