### ISSUE TITLE
Gradle `buildForkOptions` no longer used since quarkus 3.16.1

### ISSUE THREAD

**Issue by Malandril** [quarkusio/quarkus#44438]
### Describe the bug

Since quarkus 3.16.1 the `buildForkOptions` in the quarkus extensions is no longer used when running quarkus tasks such as `quarkusBuild`, or `imagePush`

### Expected behavior

The `buildForkOptions` should be used to configure the build tasks, and its actions should be applied to `QuarkusBuildTask`.

### Actual behavior

The `buildForkOptions` is not used, and the configuration actions are not executed

### How to Reproduce?

1. ` quarkus create app quarkus-bug-jib-proxy --gradle-kotlin-dsl --extension='rest'`
2. Add the following in `build.gradle.kts`:
```kotlin
quarkus {
    buildForkOptions {
        println("Build fork options")
    }
}
```

The line is never printed

### Quarkus version or git rev

3.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.10.2

### Additional information

The `codeGenForkOptions` is still correctly used.

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by geoand** [comment]
Thanks a lot @cdsap !

**Comment by Malandril** [comment]
Thanks a lot as always @cdsap
