### ISSUE TITLE
Moving to @ConfigMapping vastly increases memory requirements for native build

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus#44436]
### Describe the bug

Compiling quarkus app into native executable using docker image, requires a lot more memory since quarkus is moving to `@ConfigMapping`.

We have an example where [our testing app](https://github.com/quarkus-qe/quarkus-test-suite/tree/main/super-size/many-extensions) used to work with xmx=5g for native compilation a month ago. But since https://github.com/quarkusio/quarkus/pull/43862 and https://github.com/quarkusio/quarkus/pull/44140 requires at least 9g to successfully compile (otherwise compilation fails on OutOfMemory).

Increasing memory requirement to almost double, just by moving to `@ConfigMapping` is alarming. 

At this moment it is somehow manageable, but with more planned in https://github.com/quarkusio/quarkus/pull/44079 it is hard to say, how much memory will it require at the end.

**Comment by gsmet** [comment]
I think this duplicates https://github.com/quarkusio/quarkus/issues/44216 but you description comes with important information so I added it to the other issue.

Thanks!
