### ISSUE TITLE
quarkus-hal omits link params from response entity

### ISSUE THREAD

**Issue by gilday** [quarkusio/quarkus#44452]
### Describe the bug

Quarkus HAL extension omits extra params beyond "href" in its response.

### Expected behavior

The quarkus-hal extension should include all link attributes in the a link object in its response.

In this example, the "title" attribute is expected to be in the HAL response

```java
  public HalEntityWrapper<Greeting> hello(final String subject) {
    final var link = Link.fromResource(SubjectResource.class).rel("subject").title(subject).build();
    final var greeting = new Greeting(Language.ENGLISH, "Hello, " + subject);
    return new HalEntityWrapper<>(greeting, link);
  }
```

```json
{
  "_links": {
    "subject": {
      "href": "/subject",
      "title": "World"
    }
  }
}
```

### Actual behavior

Quarkus HAL extension only includes the `href` attribute in the link.

```json
{
  "_links": {
    "subject": {
      "href": "/subject"
    }
  }
}
```

### How to Reproduce?

[hal-title-missing.zip](https://github.com/user-attachments/files/17721546/hal-title-missing.zip)

### Output of `uname -a` or `ver`

Darwin pixee-mbp-gilday.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode)

### Quarkus version or git rev

3.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256) Maven home: /Users/jgilday/.m2/wrapper/dists/apache-maven-3.9.8-bin/337e6d14/apache-maven-3.9.8 Java version: 21.0.3, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "15.0.1", arch: "aarch64", family: "mac"

**Comment by geoand** [comment]
cc @Sgitario

**Comment by Sgitario** [comment]
I will work in this today

**Comment by geoand** [comment]
🙏🏽

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/44501 should address this.

**Comment by Sgitario** [comment]
Closed as https://github.com/quarkusio/quarkus/pull/44501 was merged.
