### ISSUE TITLE
WebSockets Next: mark the extension as "stable"

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#44469]
### Description

After https://github.com/quarkusio/quarkus/pull/44379 is merged the extension will be (more or less) feature complete.

I suggest to remove the experimental status in Quarkus 3.18.

**Comment by geoand** [comment]
👍🏽

**Comment by geoand** [comment]
@mkouba I think you can proceed with this, WDYt?

**Comment by mkouba** [comment]
> [@mkouba](https://github.com/mkouba) I think you can proceed with this, WDYT?

I'm on it. Will send a PR later today ;-).
