### ISSUE TITLE
Quarkus Websockets Next client connector is not reusable

### ISSUE THREAD

**Issue by andreiyusupau** [quarkusio/quarkus#44465]
### Describe the bug

I'm trying to open multiple connections using Websockets Next. Connections require different headers for auth purposes. Due to `addHeader` method not overwriting headers, but just adding new ones to the list, my upgrade request sends the initial header value instead of the new one.
How could the connector be reused?

### Expected behavior

connector should be completely reusable

### Actual behavior

connector is not reusable

### How to Reproduce?

```java
    @Inject
    WebSocketConnector<ExampleWebsocketClient> connector;

  public void connect() {
            var connection1 = connector.baseUri(uri)
                    .addHeader("Custom-Header", 1)
                    .connectAndAwait();

            var connection2 = connector.baseUri(uri)
                    .addHeader("Custom-Header", 2)
                    .connectAndAwait(); // still sends "Custom-Header"=1
}
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.4317]

### Output of `java -version`

Amazon Coretto 21

### Quarkus version or git rev

3.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.10.2

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
An injected `WebSocketConnector` should not be reused. It was not designed that way. I will update the javadoc which currently only states _"This construct is not thread-safe and should not be used concurrently"_.

You can inject `jakarta.enterprise.inject.Instance<WebSocketConnector<ExampleWebsocketClient>> connector` instead, and then call `connector.get()` to obtain a new instance of `WebSocketConnector`.

**Comment by andreiyusupau** [comment]
@mkouba Thanks, works nice

**Comment by mkouba** [comment]
> [@mkouba](https://github.com/mkouba) Thanks, works nice

I've tried to improve the javadoc/docs in https://github.com/quarkusio/quarkus/pull/44467 so that it's more clear.
