### ISSUE TITLE
Mutiple starts of Quarkus during Test execution (works in 3.15.1)

### ISSUE THREAD

**Issue by KaiSuchomel** [quarkusio/quarkus#44497]
### Describe the bug

With Quarkus 3.16.3 for every IT using `@TestProfile(IntegrationTestProfile.class)` a new quarkus is started.
IntegrationTestProfile uses Kafka TestContainer.

### Expected behavior

When building (https://github.com/KaiSuchomel/quarkus-test) with 3.15.1 (quarkus315-branch) the following Output is done:
```
2024-11-14 10:00:50,204 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.15.1) started in 3.622s. Listening on: http://localhost:8081
2024-11-14 10:00:50,204 INFO  [io.quarkus] (main) Profile test activated.
2024-11-14 10:00:50,204 INFO  [io.quarkus] (main) Installed features: [cdi, rest, smallrye-context-propagation, vertx]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.897 s -- in org.acme.GreetingResourceCopy1IT
[INFO] Running org.acme.GreetingResourceIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s -- in org.acme.GreetingResourceIT
2024-11-14 10:00:50,656 INFO  [io.quarkus] (main) code-with-quarkus stopped in 0.017s
....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.271 s
[INFO] Finished at: 2024-11-14T10:00:51+01:00
[INFO] ------------------------------------------------------------------------
```
Only one Start

### Actual behavior

When building (https://github.com/KaiSuchomel/quarkus-test) with 3.16.3 (main-branch) the following Output is done:
```
[INFO] Running org.acme.GreetingResourceCopy1IT
....
2024-11-14 09:57:26,031 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.16.3) started in 3.483s. Listening on: http://localhost:8081
....
[INFO] Running org.acme.GreetingResourceIT
2024-11-14 09:57:26,451 INFO  [io.quarkus] (main) code-with-quarkus stopped in 0.013s
....
2024-11-14 09:57:30,134 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.16.3) started in 3.240s. Listening on: http://localhost:8081
.....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.930 s
[INFO] Finished at: 2024-11-14T09:57:30+01:00
[INFO] ------------------------------------------------------------------------
```
Two Starts

### How to Reproduce?

see https://github.com/KaiSuchomel/quarkus-test
* run mvn clean install in branch main(3.16.3) and branch quarkus315 (3.15.1)

### Output of `uname -a` or `ver`

Darwin Mac-C6VD4H4XT3 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:00:32 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6030 arm64

### Output of `java -version`

openjdk version "21.0.5" 2024-10-15 OpenJDK Runtime Environment Homebrew (build 21.0.5) OpenJDK 64-Bit Server VM Homebrew (build 21.0.5, mixed mode, sharing)

### Quarkus version or git rev

3.16.3 vs 3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937) Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec Java version: 21.0.5, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk@21/21.0.5/libexec/openjdk.jdk/Contents/Home Default locale: de_DE, platform encoding: UTF-8 OS name: "mac os x", version: "15.1", arch: "aarch64", family: "mac"

**Comment by geoand** [comment]
Interesting that this worked with `3.15`, I need to check it out
