### ISSUE TITLE
Extension quarkus-jaxrs-client-reactive is missing from code.quarkus

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#44502]
### Describe the bug

Searching in code.quarkus for jaxrs client extension[ yields no results for both the old and the new name[1].

[1] https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9

### Expected behavior

The search should show the extension

### Actual behavior

The extension is not shown in the search

### How to Reproduce?

1. Search extension for the old name in 3.8: https://code.quarkus.io/?S=io.quarkus.platform%3A3.8&extension-search=quarkus-jaxrs-client-reactive
2. Search the new name in 3.16.2: https://code.quarkus.io/?S=io.quarkus.platform%3A3.16&extension-search=quarkus-rest-client-jaxrs
3. Search the old name in 3.16.2: https://code.quarkus.io/?S=io.quarkus.platform%3A3.16&extension-search=quarkus-jaxrs-client-reactive
4. Search the new name in 3.8 (doesn't make sense, but also doesn't work):  https://code.quarkus.io/?S=io.quarkus.platform%3A3.8&extension-search=quarkus-rest-client-jaxrs

All search return nothing

**Comment by geoand** [comment]
The extension is called now called `quarkus-rest-client-jaxrs` but it's unlisted as it's only meant to be used as a transitive dependency of the `quarkus-rest-client`
