### ISSUE TITLE
Entity missing in case of WebApplicationException

### ISSUE THREAD

**Issue by FloGro3** [quarkusio/quarkus#44508]
### Describe the bug

When using Quarkus-Rest-Client in Quarkus 3.15.1 and catching a WebApplicationException because e.g. the call results in an internal server error WebApplicationException is missing the entity from the response. The problem is that the Headers from the response are copied to WebApplicationException which means that a content-length header is present without any entity:
![Image](https://github.com/user-attachments/assets/15aa17d3-57fe-49ce-b2ef-80b4dd146333)

### Expected behavior

When catching a WebApplicationException which results from a RestClient call and building a response from the webApplicationException via 
`Response.fromResponse(webApplicationException.getResponse()).build();`
then the response should include the response body from the failed RestClient call. 

### Actual behavior

The build response has not entity but not matching header fields (e.g. content-length):
![Image](https://github.com/user-attachments/assets/a43e2293-22c6-47cd-bd83-22bdc0bc8348)

### How to Reproduce?

Here is a reproducer project: https://github.com/FloGro3/Minimal-Reproducer-Quarkus-3.15-LTS/tree/main

To simulate the issue call "/hello" endpoint. The endpoint itself calls another endpoint inside the application which returns an internal server error with a small entity. 

### Output of `java -version`

21.0.5

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by geoand** [comment]
I just tried `3.8` LTS and the corresponding client (`quarkus-rest-client-reactive`) does behave in the exact same way.

Now this is not something I really want to change, not least because you can easily work around the behavior by doing:

```java
try {
            return defaultApi.test();
        } catch (WebApplicationException webApplicationException) {
            webApplicationException.getResponse().readEntity(String.class); // force reading the body
            Response response = Response.fromResponse(webApplicationException.getResponse()).build();
            return response;
        }
```

**Comment by cescoffier** [comment]
Except if it's a regression, I don't believe we want to change that behavior (like @geoand said).

**Comment by FloGro3** [comment]
@geoand You are right, the entity is also not read in by default in Quarkus 3.8 LTS (don't know why it does it anyway on our side). The big difference I see between 3.8 LTS and 3.15 LTS is that the header fields are not present in 3.8, but in 3.15. In both cases we don't have any entity by default which means that in 3.15 we send an invalid response, because header fields like content-length are set, but no body is returned (as entity is null by default). In 3.8 this header fields are not present.

Both simulated with my minimal reproducer.
3.8:
![Image](https://github.com/user-attachments/assets/4ad8e1bd-1a11-4eea-bd8e-dddd5dbf782d)

3.15:
![Image](https://github.com/user-attachments/assets/3838930d-01d5-4e53-b265-a101db407bd5)

**Comment by cescoffier** [comment]
Can you check the headers in both cases?

**Comment by FloGro3** [comment]
So in case of 3.8 we have these headers in webApplicationException response (which are then also copied to the response that is build based on the webApplicationException response:
![Image](https://github.com/user-attachments/assets/d57f716e-95ec-4656-978e-5f8a3aa5a8b1)

In case of 3.15 we have these headers:
![Image](https://github.com/user-attachments/assets/c7e696d7-7164-4b9a-a267-2dfa1d052e95)
Content-length is set to "32" in this case even though we don't send any body by default.

**Comment by geoand** [comment]
@FloGro3 I checked and the behavior of `quarkus-rest-client` in `3.15`  is the same as `quarkus-rest-client-reactive` in `3.8`.

Having said that, I do of course need to point out that the  `quarkus-rest-client` in `3.15`  is not the same one as in `3.8` - the `quarkus-rest-client` of 3.8 is essentially the `quarkus-resteasy-client` in `3.15`. 
We renamed the REST Client see [this](https://quarkus.io/blog/the-big-rename/) and [this](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#resteasy-reactive-extensions-renamed-to-quarkus-rest-gear-white_check_mark) for more details.

**Comment by FloGro3** [comment]
@geoand I see. I didn't take the renaming into consideration. Thanks for the hint. I assume as the behavior is then consistent across different Quarkus versions you will not change it, right? Even though I still find it weird that we have to force read the entity from the WebApplicationException response to generate valid responses out of it. But I will then apply your suggested workaround for all of our cases. Thanks for that :)

**Comment by geoand** [comment]
🙏🏽
