### ISSUE TITLE
Document that one can override runtime properties via config/application.properties

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4452]
You can override runtime properties in bulk by placing a `config/application.properties` int he working directory of the application.
This is useful for users but not documented.

https://github.com/quarkusio/quarkus/issues/1218#issuecomment-491832844
https://github.com/geoand/quarkus/blob/46dc078de494b331d83d39df8dddcc97e516bf85/core/runtime/src/main/java/io/quarkus/runtime/configuration/ApplicationPropertiesConfigSource.java#L70

No reference in https://quarkus.io/guides/application-configuration-guide

**Comment by HelvetiaAppDev** [comment]
Thank you for adding this to the documentation!

When running quarkus:dev the "config" folder needs to be inside target/classes, however the hot code replacement (?) seems to get rid of it.

Could maybe also add how to deal with this for quarkus:dev? Or am I missing something?

**Comment by flo-ryan** [comment]
Thank you for adding this to the documentation!

When running quarkus:dev the "config" folder needs to be inside target/classes, however the hot code replacement (?) seems to get rid of it.

Could maybe also add how to deal with this for quarkus:dev? Or am I missing something?

**Comment by geoand** [comment]
Let me check and see how `quarkus:dev` behaves with this feature.

**Comment by geoand** [comment]
I just checked and `quarkus:dev` works file with this feature. I will add a note however in #4452 on how to use it.

**Comment by geoand** [comment]
Note added in #4452 about dev mode

**Comment by flo-ryan** [comment]
Is there a list or similar of runtime properties? Or some other way to find out which properties are build and which are runtime? Thanks!

**Comment by geoand** [comment]
> Is there a list or similar of runtime properties? Or some other way to find out which properties are build and which are runtime? Thanks!

@machi1990 @gsmet I think this one is for you

**Comment by emmanuelbernard** [comment]
@flo-ryan it should be describe in each relevant guide. We are also in the process of rolling out a unified rendering of the property list. See Hibernate ORM's for example, you will see the different icon depending on the lifecycle (build time vs runtime) see https://quarkus.io/guides/hibernate-orm-guide#properties-to-refine-your-hibernate-orm-configuration

PS @gsmet should we rename the `lifecycle` column to `build/runtime` to be a bit more specific?

**Comment by flo-ryan** [comment]
@emmanuelbernard A unified list of all available properties (for all microprofiles?) including the build/runtime info would be very helpful and highly appreciated! Thanks!

**Comment by emmanuelbernard** [comment]
@kenfinnigan we don't have a MP list of properties right in the Quarkus guides? I also felt we would be better with the list described. whether unified or in each guide, I personally was leaning towards each guide.

**Comment by flo-ryan** [comment]
For example: It is unclear to me if/how I can set user + password + roles at runtime using "quarkus.security.embedded.*" in application.properties in a "config" folder (to be able to set user passwords more securely at runtime).

**Comment by emmanuelbernard** [comment]
CC @sberyozkin
