### ISSUE TITLE
Add documentation for `@WithTestResource` and `TestResourceScope`

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#44530]
### Description

Due the lack of documentation of `@WithTestResource` and recent changes in 3.16.2, I just replaced all `WithTestResource` again with `QuarkusTestResource` as otherwise I ran in an OOM.

As I figured, `@WithTestResource` work with the `TestResourceScope` concept, which brings quite some different behavior, depending on the chosen scope. It would be helpful if those scopes, the way they work and example use cases would be documented in https://quarkus.io/guides/getting-started-testing.

**Comment by geoand** [comment]
That's a great idea!

Would you like to kick start this?

**Comment by geoand** [comment]
ping @HerrDerb :)

**Comment by HerrDerb** [comment]
@geoand I can give it a try :) But my only knowledge about this is reading the code, so it surely will be incomplete or even partially wrong :) 
How do you want this to do? Should I just start a branch and you guys will take it over after or contribute onto it?

**Comment by geoand** [comment]
Go ahead and push a draft PR whenever you are ready and we can update there

**Comment by HerrDerb** [comment]
As merged
