### ISSUE TITLE
Met dependency problem after upgrading quarkus platform to `3.16.3`

### ISSUE THREAD

**Issue by Moicen** [quarkusio/quarkus#44544]
### Describe the bug

After upgrading the quarkus platform version:

![Image](https://github.com/user-attachments/assets/517d6444-83c7-4ab3-824e-956577f5206b)

This error occurs:

![Image](https://github.com/user-attachments/assets/29cddd3f-5411-401d-b0c2-290ed2f878be)

I’m not sure whether I should explicitly set the version now for these components used in the project.

Can anyone help to check this? Thanks!

**Comment by maxandersen** [comment]
Please https://quarkus.io/blog/the-big-rename/ and https://quarkus.io/blog/quarkus-3-9-1-released/ for what happened here.

Since 3.9 there should have been relocation warnings printed and if you used quarkus update the code should have been migrated.

It would be great `quarkus update` could help do this between 3.15 to 3.16 but that is unfortunately not possible atm.

Thus If you haven't noticed those warnings or not used quarkus update you currently will have to handle this manually, see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7#rest-client-gear-white_check_mark for info.

**Comment by Moicen** [comment]
@maxandersen After I rename the dependencies according to your instruction I have fixed the problem:

```diff
diff --git a/pom.xml b/pom.xml
index e662ff2..0afc66a 100644
--- a/pom.xml
+++ b/pom.xml
@@ -15,7 +15,7 @@
         <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
         <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
         <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
-        <quarkus.platform.version>3.15.1</quarkus.platform.version>
+        <quarkus.platform.version>3.16.3</quarkus.platform.version>
         <surefire-plugin.version>3.5.2</surefire-plugin.version>
         <ver.jjwt>0.11.5</ver.jjwt>
         <ver.lombok>1.18.34</ver.lombok>
@@ -57,7 +57,7 @@
         </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-resteasy-reactive</artifactId>
+            <artifactId>quarkus-rest</artifactId>
         </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
@@ -81,15 +81,15 @@
         <!--        </dependency>-->
         <dependency>
             <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-resteasy-reactive-jsonb</artifactId>
+            <artifactId>quarkus-rest-jsonb</artifactId>
         </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-rest-client-reactive</artifactId>
+            <artifactId>quarkus-rest-client</artifactId>
         </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
+            <artifactId>quarkus-rest-client-jackson</artifactId>
         </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
```

Thanks for the great help on this!
