### ISSUE TITLE
Read timeout for Servlet

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#4455]
Undertow should have a read timeout for blocking IO. This should be inherited from the vert.x config.

**Comment by rsvoboda** [comment]
@michalszynkiewicz what's the status and plan here ?

**Comment by michalszynkiewicz** [comment]
So far i exposed the idle timeout (that's the thing vert.x gives us for free), it made the issue less urgent.
I have it on my todo list but haven't come back to it yet. 
If it's urgent, I can pick it up in parallel with my current assignment. Do you find it high prio?

**Comment by rsvoboda** [comment]
I don't want to dictate priority, let's see what @gsmet thinks
