### ISSUE TITLE
@AuthorizationPolicy is not compatoble with kotlin suspend functions

### ISSUE THREAD

**Issue by mschirmacher** [quarkusio/quarkus#44568]
### Describe the bug

The new annotation @AuthorizationPolicy does not work combined with kotlin suspend functions. Event worse: the error message makes it hard to debug.

### Expected behavior

It simply works: REST calls to suspend functions are handled and the authorization policies are applied/

### Actual behavior

REST calls run into a next to useless error:
[error]: Build step io.quarkus.vertx.http.deployment.HttpSecurityProcessor#gatherAuthorizationPolicyInstances threw an exception: java.lang.IllegalArgumentException: Not a class

### How to Reproduce?

check out this example code: https://github.com/mschirmacher/QuarkusAuthorizationPolicySuspendBug
The gradle build demonstrates the error

**Comment by michalvavrik** [comment]
thanks @mschirmacher , I'll have a look this week.

**Comment by geoand** [comment]
@michalvavrik do you need me to look into any Kotlin stuff for this?
