### ISSUE TITLE
Bootstrap resolver should log if it is accessing the network

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#4460]
When running tests or building for the first time the bootstrap resolver might need to download -deployment artifacts and their dependencies. If the network is slow this can appear that tests or the build are hanging. If we need to hit the network we should log a message and update the user on our progress in a similar way to a normal maven build,

**Comment by rsvoboda** [comment]
@aloubyansky any plans with this issue ? Asking because it's assigned to you and it makes impression it's on the radar or in progress

**Comment by aloubyansky** [comment]
I'll have a look into it once we get the new classloading in, as it touches a bit the relevant classes.
