### ISSUE TITLE
The only way to verify HttpResponse fluently is deprecated upstream

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#44612]
### Describe the bug

Currently, if users want to verify HTTP response before processing it, they can use method `io.vertx.mutiny.ext.web.client.HttpRequest.expect` (the class is automatically generated from`io.vertx.ext.web.client.HttpRequest`). Unfortunately, this method is deprecated[1], and documentation recommends to use HttpResponseExpectation together with Vert.X futures. The problem, that futures are not exposed by smallrye api, and `Uni`s, which are used instead, do not have anything corresponding to `Future.expecting` method. That leaves users without an option to do the verification fluently.

[1] https://github.com/vert-x3/vertx-web/blob/60202842cad48f700441f1c4401fbbd0db48544e/vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java#L427

### Expected behavior

There should be a supported way to do verification fluently

### Actual behavior

The only existing way is deprecated

### How to Reproduce?

An example of usage can be seen here:

https://github.com/quarkus-qe/quarkus-test-framework/blob/5f5daa9288cd63d141dba6bdb4ed72b3ff6c0e3b/examples/greetings/src/test/java/io/quarkus/qe/ReactiveGreetingResourceIT.java

### Additional information

Not sure whether that should be a bug or a discussion, so please feel free to change its type to the more relevant one.

**Comment by geoand** [comment]
cc @vietj @cescoffier

**Comment by fedinskiy** [comment]
@cescoffier thank you! Is it possible to put links to this into javadocs for deprecated methods?

**Comment by fedinskiy** [comment]
And I do not see "Expectations" class in smallrye-mutiny-vertx-core:3.15.0 (the version brought by Quarkus 3.16.4). Should it be come to Quarkus with some later update?

**Comment by cescoffier** [comment]
The javadoc is extracted from the upstream. We cannot decorate it.
