### ISSUE TITLE
Quarkus’s applyCompression Method Disables Vert.x Compression Logic

### ISSUE THREAD

**Issue by aruis** [quarkusio/quarkus#44637]
### Describe the bug

In the VertxHttpRecorder class, the applyCompression method forcibly adds a Content-Encoding: identity header when compression (enableCompression=true) is enabled. This behavior directly disables Vert.x’s built-in compression logic (HttpContentCompressor). As a result, even when HTTP compression is enabled in the Quarkus configuration, responses are not compressed.

### Expected behavior

When quarkus.http.enable-compression=true is set, the compression logic should be delegated to Vert.x. Vert.x should dynamically decide whether to apply compression based on the client’s Accept-Encoding header and response content size.

### Actual behavior

The applyCompression method explicitly sets the Content-Encoding: identity header:

https://github.com/quarkusio/quarkus/blob/fcf042c5fba4a247a33b6ece192b2414011cc063/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L641-L653

This leads to:
	1.	Disabling Vert.x Compression: Vert.x’s HttpContentCompressor detects that Content-Encoding is already set and skips the compression logic.
	2.	Additional Developer Effort: Developers must manually remove the Content-Encoding header in their custom handlers to allow compression to work properly, especially when using Vert.x features like StaticHandler.

### How to Reproduce?

Reproduction Steps

1. Enable HTTP compression in Quarkus:

quarkus.http.enable-compression=true

2. Create a custom route using Vert.x’s StaticHandler:

```
Router router = Router.router(vertx);
router.route("/static/*").handler(routingContext -> {
    // Without this line, compression won't work
    routingContext.response().headers().remove(HttpHeaders.CONTENT_ENCODING);
    StaticHandler.create().handle(routingContext);
});
```

3. Request a static file with Accept-Encoding: gzip:  curl -H "Accept-Encoding: gzip" http://localhost:8080/static/index.html

4. Observe that the response is not compressed unless the Content-Encoding header is explicitly removed in the handler.

### Output of `uname -a` or `ver`

Darwin mini2024.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Nov 14 18:15:21 PST 2024; root:xnu-11215.41.3~13/RELEASE_ARM64_T6041 arm64

### Output of `java -version`

openjdk version "21.0.5" 2024-10-15 LTS OpenJDK Runtime Environment Zulu21.38+21-CA (build 21.0.5+11-LTS) OpenJDK 64-Bit Server VM Zulu21.38+21-CA (build 21.0.5+11-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.16.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

### Additional information

Analysis

Netty Source Code Behavior

Vert.x’s compression logic relies on Netty’s HttpContentCompressor, which dynamically applies compression based on the Accept-Encoding header and response content. The critical part of HttpContentCompressor’s logic is as follows:

https://github.com/netty/netty/blob/a0e67671651a99977391c5552dd90e7bc147308a/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java#L246-L259

```@Override
protected Result beginEncode(HttpResponse httpResponse, String acceptEncoding) throws Exception {
    // Skip compression if the content is too small
    if (this.contentSizeThreshold > 0) {
        if (httpResponse instanceof HttpContent &&
                ((HttpContent) httpResponse).content().readableBytes() < contentSizeThreshold) {
            return null;
        }
    }

    // Skip compression if Content-Encoding is already set
    String contentEncoding = httpResponse.headers().get(HttpHeaderNames.CONTENT_ENCODING);
    if (contentEncoding != null) {
        return null;
    }

    // Dynamically choose compression encoding based on Accept-Encoding
    String targetContentEncoding = determineEncoding(acceptEncoding);
    if (targetContentEncoding == null) {
        return null;
    }

    return new Result(targetContentEncoding,
            new EmbeddedChannel(ctx.channel().id(), ctx.channel().metadata().hasDisconnect(),
                    ctx.channel().config(), encoderFactory.createEncoder()));
}
```
	•	Key Point 1: If Content-Encoding is set (even as identity), compression is skipped entirely.
	•	Key Point 2: If Quarkus sets Content-Encoding: identity, the compression logic is bypassed, even when the client requests gzip encoding.

Issues with Current Quarkus Implementation

	•	The applyCompression method’s forced header setting disrupts Vert.x’s native behavior.
	•	Developers are forced to manually adjust response headers to bypass this interference, adding unnecessary complexity.

Suggested Fix

Remove the forced addition of the Content-Encoding: identity header in the applyCompression method. Allow Vert.x to manage compression independently.

The updated code could be:

```
private void applyCompression(boolean enableCompression, Router httpRouteRouter) {
    // Do nothing here and delegate compression logic to Vert.x.
}
```

Summary

The current implementation of applyCompression conflicts with Vert.x’s dynamic compression capabilities and imposes unnecessary maintenance overhead on developers. By removing this logic, Quarkus can fully leverage Vert.x’s built-in features, streamline code behavior, and better align with user expectations.

**Comment by mkouba** [comment]
So the rules for HTTP compression are described in the corresponding docs, for example [HTTP Compression](https://quarkus.io/guides/http-reference#http-compression) for static resources and [HTTP Compression](https://quarkus.io/guides/rest#http-compression) for `quarkus-rest`.

Indeed, when `quarkus.http.enable-compression=true` is set we intentionally add the `Content-Encoding: identity` header and effectively disable the compression unless a well-defined rule applies. For example, for static resources the response body is compressed if the `Content-Type` header derived from the file name of a resource is a compressed media type as configured via `quarkus.http.compress-media-types`. For `quarkus-rest` there's also `@Compressed` annotation etc.

The main reason for this design was to avoid unintended compression (a typical example is a JPEG image). The thing is, you can't use only the `Accept-Encoding` header because that would usually mean to compress everything sent from the server.

> 2. Additional Developer Effort: Developers must manually remove the Content-Encoding header in their custom handlers to allow compression to work properly, especially when using Vert.x features like StaticHandler.

In Quarkus, most of the developers do not develop their own handlers. Instead, they rely on higher-level APIs. So I believe that our approach is convenient for most users.

**Comment by aruis** [comment]
@mkouba  Thank you for your detailed response. I appreciate the explanation and fully understand the rationale behind the current design, especially the intention to support scenarios like:

- Compressing static resources only when their `Content-Type` matches the types defined in `quarkus.http.compress-media-types`.  
- Using annotations like `@Compressed` for Quarkus-Rest to explicitly enable compression.

These considerations are entirely reasonable and legitimate.

However, I’d like to share a few thoughts regarding the implementation mechanism:

1. The introduction of `Content-Encoding: identity` during the intermediate process, and then conditionally overriding this header, may not be the most elegant approach. While it achieves the desired behavior in many cases, it feels somewhat counterintuitive and could lead to unexpected side effects.

2. This implementation does interfere with advanced users who need to manually control handlers like `StaticHandler`. For instance, users are forced to manually remove the `Content-Encoding` header to enable compression in custom handlers. This disrupts the natural behavior of Vert.x and adds unnecessary complexity.

3. Additionally, the documentation does not provide sufficient guidance or warnings regarding this behavior. This can confuse developers who rely on features like Vert.x’s `HttpContentCompressor` and expect it to handle compression dynamically.

4. I wonder if we could explore a more elegant solution that satisfies both the original design goals and the needs of advanced users. For example:
   - Avoid explicitly setting `Content-Encoding: identity` and instead rely on `compress-media-types` and Vert.x’s built-in compression logic to dynamically determine whether to compress the response.
   - Provide an additional configuration option to give users more control over how compression is handled.

I believe such changes could make Quarkus more flexible and user-friendly while still preserving the current business logic.

What do you think about this direction? I’d be happy to further discuss or help refine this idea.

**Comment by mkouba** [comment]
> The introduction of `Content-Encoding: identity` during the intermediate process, and then conditionally overriding this header, may not be the most elegant approach.

Indeed, it isn't. But we did not find a better solution.

> For instance, users are forced to manually remove the `Content-Encoding` header to enable compression in custom handlers.

Yes, advanced users who want to control the behavior have to remove the `Content-Encoding` header in their routes. That's all.

> Additionally, the documentation does not provide sufficient guidance or warnings regarding this behavior.

It's an implementation detail. And I think that it has no value for most of the users. That said, we could document this, probably in the Vert.x Reference Guide?

> This can confuse developers who rely on features like Vert.x’s HttpContentCompressor and expect it to handle compression dynamically.

FYI `HttpContentCompressor` comes from Netty, not Vertx.

> I wonder if we could explore a more elegant solution that satisfies both the original design goals and the needs of advanced users.

Of course we can, although I'm not completely sure it's worth the effort 🤷 . Feel free to propose a solution.

> Avoid explicitly setting Content-Encoding: identity and instead rely on compress-media-types and Vert.x’s built-in compression logic to dynamically determine whether to compress the response.

Keep in mind that this would require changes in a thrid-party project (Vertx or Netty).


@cescoffier @vietj Do you happen to know if there are any changes WRT HTTP compression in Vertx 5?

**Comment by cescoffier** [comment]
Not as far as I know.

**Comment by vietj** [comment]
Nothing has really changed, it's quite stable implementation.
