### ISSUE TITLE
Management interface - TLS detection apparently doesn't check TLS registry config

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#44643]
I don't think `NonApplicationRootPathBuildItem#isTLsConfigured()` has been updated since the TLS registry was introduced.

This code probably needs some updating.

/cc @cescoffier

**Comment by cescoffier** [comment]
Yes, I forgot this direct usage of the Configuration API.

**Comment by gsmet** [comment]
FWIW, I have a small patch for it in my branch, together with some doc improvements, given I was working in this area.
