### ISSUE TITLE
Dev console "crashes" with Java 23

### ISSUE THREAD

**Issue by CodeSimcoe** [quarkusio/quarkus#44653]
### Describe the bug

As discussed with @geoand on Zulip,
the dev console "crashes" when using Java 23.

Basic use case : bootstrap a "code-with-quarkus" app with rest only, launch app in dev mode via `mvn quarkus:dev`.
Got this weird output then nothing is displayed anymore (no standard or error output)
See that it fails to display Quarkus ascii art.

```
clem@CLEM-PC MINGW64 ~/repositories/code-with-quarkus
$ mvn quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus:3.16.4:dev (default-cli) @ code-with-quarkus ---
[INFO] Invoking resources:3.3.1:resources (default-resources) @ code-with-quarkus
[INFO] Copying 1 resource from src\main\resources to target\classes
[INFO] Invoking quarkus:3.16.4:generate-code (default) @ code-with-quarkus
[INFO] Invoking compiler:3.13.0:compile (default-compile) @ code-with-quarkus
[INFO] Nothing to compile - all classes are up to date.
[INFO] Invoking resources:3.3.1:testResources (default-testResources) @ code-with-quarkus
[INFO] skip non existing resourceDirectory C:\Users\clem\repositories\code-with-quarkus\src\test\resources
[INFO] Invoking quarkus:3.16.4:generate-code-tests (default) @ code-with-quarkus
[INFO] Invoking compiler:3.13.0:testCompile (default-testCompile) @ code-with-quarkus
[INFO] Nothing to compile - all classes are up to date.
Listening for transport dt_socket at address: 5005







--
Tests paused
Press [e] to edit command line args (currently ''), [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>:←[39m] for the terminal, [←[94mh←[39m] for more options>39m] for more options> more options>terminal, [←[94mh←[39m] for
```

No issue when running app with `-Djdk.console=java.base` as advised by Georgios.
Therefore, it might by this change introduced in Jdk 22 : __JLine As The Default Console Provider ([JDK-8308591](https://bugs.openjdk.org/browse/JDK-8308591))__ ?

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-22631 CLEM-PC 3.4.10-87d57229.x86_64 2024-02-14 20:17 UTC x86_64 Msys

### Output of `java -version`

openjdk version "23" 2024-09-17 OpenJDK Runtime Environment (build 23+37-2369) OpenJDK 64-Bit Server VM (build 23+37-2369, mixed mode, sharing)

### Quarkus version or git rev

3.16.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

**Comment by zakkak** [comment]
Related to https://github.com/quarkusio/quarkus/issues/44471

**Comment by geoand** [comment]
Thanks for reporting!

**Comment by maxandersen** [comment]
the "weird" output is shown in zulip as ` [←[94m:←[39m] for the terminal, [←[94mh←[39m] for more options>[39m] for more options>ons>ti` those are ansi codes not being interpreted correctly.

Why that is happening is the good question.

I also note you are on windows/mingw which probably could be related to it.

**Comment by CodeSimcoe** [comment]
> I also note you are on windows/mingw which probably could be related to it.

Same issue when using windows powershell 7.4.6.
But it works in my WSL Ubuntu, indeed

**Comment by geoand** [comment]
The way we are going to address #44471 for the time being, will also mean that the problem described here won't occur with the default settings (as we are going to default to the `java.base` console)
