### ISSUE TITLE
Implement a starter.quarkus.io

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#447]
Inspiration are http://thorntail.io/generator/ and https://start.spring.io
@kenfinnigan could we reuse the Thorntail one?

**Comment by andresetevejob** [comment]
I want to offer my help on this issue

**Comment by Dufgui** [comment]
I start an implementation https://github.com/Dufgui/quarkus-generator

**Comment by emmanuelbernard** [comment]
Awesome @Dufgui !
Vert.x did something interesting, it generates the artifacts and the zip from javascript on the client side
https://vertx-starter.jetdrone.xyz/

**Comment by kenfinnigan** [comment]
If we can do something that doesn't require a "backend", then it might scale better

**Comment by Dufgui** [comment]
Yes it's interesting without backend, but in this way we cannot mutualize code between maven generator and web generator. Or you want the maven generator call the js ?

**Comment by tsegismont** [comment]
Le jeu. 2 mai 2019 à 15:58, Emmanuel Bernard <notifications@github.com> a
écrit :

> Awesome @Dufgui <https://github.com/Dufgui> !
> Vert.x did something interesting, it generates the artifacts and the zip
> from javascript on the client side
> https://vertx-starter.jetdrone.xyz/
>

For the record, this is not the official starter (https://start.vertx.io)

It's an alternative starter from Paulo.

**Comment by emmanuelbernard** [comment]
> Yes it's interesting without backend, but in this way we cannot mutualize code between maven generator and web generator. Or you want the maven generator call the js ?

We wondered about the same thing. No clear cut answer but maintenance wise, a single template would be much easier. I don't know how much would that would be on the build tool side to use the js template.

**Comment by Dufgui** [comment]
maybe we can use https://mustache.github.io/ for templating. This way we can use same template from java or js side ? Maybe must talk about this on ziplib ? or google groups

**Comment by Dufgui** [comment]
i am sad for my dying PR ;o) lol

**Comment by emmanuelbernard** [comment]
@Dufgui +1 to talk about it on the ML

**Comment by kenfinnigan** [comment]
One option is that the templates are deployed to Maven.

So JS could access them directly, or even package them into website in some way, and then Maven CLI can embed those templates into itself directly so no download required

**Comment by FroMage** [comment]
@dmlloyd you sure this was meant to be closed?

**Comment by dmlloyd** [comment]
That's a question for @Dufgui I guess?  His PR closed this automatically.

**Comment by Dufgui** [comment]
I think it must be reopened.
I still have my repo website with backend here : https://github.com/Dufgui/quarkus-generator 
Please tell me if you want it inside quarkus repo or outside. (I prefer outside personally). If outside, please create an empty repo and I put inside it.

For the backend-less approach, I can push a specific branch on the same repo.

**Comment by fbricon** [comment]
I'm interested in this, so we can provide a vscode-quarkus extension. We'd prefer having a REST endpoint (i.e backen approach), rather than a solution strictly depending on a browser

**Comment by gastaldi** [comment]
I believe this issue can be closed as code.quarkus.io is now live?

**Comment by machi1990** [comment]
Good point. Starter site available at https://code.quarkus.io/.  Closing.
