### ISSUE TITLE
`io.quarkus.grpc.deployment` is split across multiple modules

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#44727]
The aforementioned package may be found in these modules:

* `extensions/grpc/codegen`
* `extensions/grpc/deployment`

**Comment by alesj** [comment]
@cescoffier I guess we could rename the one's in `codegen`?
No harm to that ... afais

**Comment by cescoffier** [comment]
It's no problem in codegen—it should not have been used anywhere else (honestly, I don't see how it could have been used outside of our integration).

**Comment by alesj** [comment]
So ... OK to rename in `codegen`?
Well, it's an easy mistake to make ... to use it elsewhere, when the name is so generic and useful :-)

**Comment by cescoffier** [comment]
@alesj yes, go ahead and rename the package in codegen.

**Comment by alesj** [comment]
Renamed.
