### ISSUE TITLE
`io.quarkus.kubernetes.client.runtime` is split across multiple runtime modules

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#44731]
The package `io.quarkus.kubernetes.client.runtime` is found in these runtime modules:

* `extensions/kubernetes-client/runtime`
* `extensions/kubernetes-client/runtime-internal`

**Comment by geoand** [comment]
Should also be an easy fix

**Comment by metacosm** [comment]
Is the expectation that things in the `*-internal` modules should not be used externally?

**Comment by geoand** [comment]
They are not part of the API
