### ISSUE TITLE
`io.quarkus.spring.web.runtime` is split across multiple runtime modules

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#44742]
`io.quarkus.spring.web.runtime` is found in:

* `extensions/spring-web/resteasy-classic/runtime`
* `extensions/spring-web/core/runtime`
* `extensions/spring-web/resteasy-reactive/runtime`

**Comment by geoand** [comment]
I'll let @aureamunoz handle this one as she has ongoing work in the area
