### ISSUE TITLE
Regression after 576ba7c: `io.vertx.core.http.HttpServerRequest.absoluteURI()` does not contain port anymore

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#44776]
After 576ba7c, the retrurn value of `io.vertx.core.http.HttpServerRequest.absoluteURI()` does not contain port anymore when only `X-Forwarded-Host` header is set.

See the reproducer in https://github.com/quarkusio/quarkus/pull/44777/files that is passing before 576ba7c.

**Comment by ppalaga** [comment]
@sberyozkin is this behavior perhaps intentional?

**Comment by sberyozkin** [comment]
Thanks @ppalaga, I meant to reply here but ended up replying in your reproducer PR, let's continue there, 

It looks like it is not a bad situation on main now, but we can tweak if we find it necessary,
cheers

**Comment by ppalaga** [comment]
Not a bug for reasons named in https://github.com/quarkusio/quarkus/pull/44777
