### ISSUE TITLE
Obsolete TestSecurity annotation documentation contains nonexistent "augmentors" parameter

### ISSUE THREAD

**Issue by okarmazin** [quarkusio/quarkus#44781]
### Describe the bug

https://quarkus.io/guides/security-testing

Just grep for `augmentors =`.

This documentation seems to be obsolete for at least 2 years - the following discussion from January 2023 already talks about `TestSecurityIdentityAugmentor` as opposed to the `augmentors` parameter: https://github.com/quarkusio/quarkus/discussions/30411

**Comment by sberyozkin** [comment]
@okarmazin Why do you think this documentation is obsolete ? This is a new attribute which was added recently

**Comment by okarmazin** [comment]
I see, I made an incorrect assumption that the parameter was old when it is in fact new. Closing!
