### ISSUE TITLE
Quarkus Qute broken in 3.16

### ISSUE THREAD

**Issue by Madere** [quarkusio/quarkus#44797]
### Describe the bug

Hi,
we used Quarkus Qute 3.15.2 and all worked fine. Since 3.16.1 we have an issue with calling a Java method. The parameter in the Java method is always the same value where in the HTML file the field has the correct value within a loop.

Html fragments:

```
{#for project in schedules.projects}
  {#for name in schedules.names}
    <script>console.log("Name: Project.name = [{project.name}]");</script>
    {#let schedule = schedules.forProjectAndName(project, name, project_index)}
    ........
  {/for}
{/for}
```

In the browser console logging, the value for project.name is correct for each project in 'schedules.projects'

Java Code:

```
public PipelineSchedule forProjectAndName(final Project project, final String scheduleName, final int indexCount) {
log.info("Name: Project.Name = [{}], ScheduleName = [{}], indexCount = [{}]", project.name(), scheduleName, indexCount);
```
The java logging shows always the first project name from the loop in the html code. Anyone an idea what is going on? And how to solve this?

### Expected behavior

That the loop works the same as in Quarkus version 3.15

### Actual behavior

The value of the parameter in the Java method is always of the first entry in the loop.

### Quarkus version or git rev

3.15 versus 3.16

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by mkouba** [comment]
Hi @Madere and thanks for the report. Would it be possible to extract the relevant code in a minimal reproducer project? It's hard to guess without something concrete in hand.

**Comment by Madere** [comment]
find attached a zip file with a short demo project. [Quarkus Qute issue.zip](https://github.com/user-attachments/files/17948651/Quarkus.Qute.issue.zip)

Compiled with Java-21

usage: 
java -jar target/documentation-runner.jar list-schedules

Screenshots: 
Html Output with Quarkus 3.15.2 (correct) ![Image](https://github.com/user-attachments/assets/69acb6eb-63bc-415b-9b80-d86f2a5d33af)

Html Output with Quarkus 3.16.1 (incorrect) ![Image](https://github.com/user-attachments/assets/cae643ff-7208-4411-ad50-e4c77f635c91)

**Comment by mkouba** [comment]
> Hi [@mkouba](https://github.com/mkouba) find attached a zip file with a short demo project. [Quarkus Qute issue.zip](https://github.com/user-attachments/files/17948651/Quarkus.Qute.issue.zip)
> 
> Compiled with Java-21
> 
> usage: java -jar target/documentation-runner.jar list-schedules
> 
> The Html ouput is in: pages/schedules.html
> 
> Screenshots: Html Output with Quarkus 3.15.2 (correct) ![Image](https://github.com/user-attachments/assets/69acb6eb-63bc-415b-9b80-d86f2a5d33af)
> 
> Html Output with Quarkus 3.16.1 (incorrect) ![Image](https://github.com/user-attachments/assets/cae643ff-7208-4411-ad50-e4c77f635c91)

Thanks. I'll take a look.

**Comment by mkouba** [comment]
Ok, found it. It's a regression caused by https://github.com/quarkusio/quarkus/pull/43308.

I've sent a PR with a fix. This is the fix: https://github.com/quarkusio/quarkus/pull/44817/files#diff-172c5b92001e43b2cc32c9a8025b0730084d360fa398a1600dc4e4a8b88cc3d3R65 🤦 😦 

Workarounds exists: do not use the reflection fallback value resolver, but instead:

-  use type-safe templates/records/expressions (e.g. https://quarkus.io/guides/qute-reference#template-records)
- annotate the `ProjectSchedules` class with [`@TemplateData`](https://quarkus.io/guides/qute-reference#template_data)

**Comment by Madere** [comment]
Hi @mkouba , thanks.
Adding @TemplateData made it work again.
Regards,
Martin.
