### ISSUE TITLE
ElytronPasswordIdentityProvider does not forward attributes from SecurityIdentity

### ISSUE THREAD

**Issue by MelkorCC** [quarkusio/quarkus#44804]
### Describe the bug

In Wildfly Elytron it is possible to request additional attributes using attribute mappings. Quarkus does also enable this [via the configs](https://quarkus.io/guides/security-ldap#configuring-the-application) (example for ldap). 

Quarkus SecurityIdentity interface and [implementation](https://github.com/quarkusio/quarkus/blob/main/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java#L73-L81) has getAttribute and getAttributes methods available and likewise the builder used to construct it has [setAttribute and setAttributes methods](https://github.com/quarkusio/quarkus/blob/main/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java#L195-L209), however [ElytronPasswordIdentityProvider](https://github.com/quarkusio/quarkus/blob/main/extensions/elytron-security/runtime/src/main/java/io/quarkus/elytron/security/runtime/ElytronPasswordIdentityProvider.java#L54-L60) does not forward the attributes from the retrieved Wildfly [SecrutityIdentity](https://wildfly-security.github.io/wildfly-elytron/documentation/api/upstream/org/wildfly/security/auth/server/SecurityIdentity.html#getAttributes())to it. 

### Expected behavior

The attributes should be set on the builder and thus ultimately be available on the injected SecurityIdentity.

### Actual behavior

The attributes are not available on injected SecurityIdentity.

**Comment by geoand** [comment]
@MelkorCC as you seem to have analyzed the code, would you be willing to contribute the necessary fix?

Thanks

**Comment by MelkorCC** [comment]
Sure, however i have two questions:
- What about ElytronTokenIdentityProvider and ElytronTrustedIdentityProvider? They also use a Wildfly SecurityIdentity and build a Quarkus SecurityIdentity from it, so in theory it would also possible to change them to pass the attributes from the Wildfly SecurityIdentity into the QuarkusSecurityIdentity.Builder. I don't know if these two would ever have any attributes, but given that the attributes would then be set to [EMPTY](https://wildfly-security.github.io/wildfly-elytron/documentation/api/upstream/org/wildfly/security/authz/Attributes.html#EMPTY) i also don't see how it would cause any problems.

- Do you have any recommendation with regards to testing? I am unsure how to test the authenticate method (and thus setting the attributes), when i did a quick look at other classes implementing the IdentityProvider interface i didn't see any tests for any of them (it is ofc possible that i missed them).

**Comment by MelkorCC** [comment]
So, i looked into this a bit yesterday after work. The fix is pretty trivial, as already mentioned everything is already there and i just needed to forward it to the builder. Great. 

I also figured out that the IdentityProviders are covered by the integration tests rather than unittests, but this is where my problem started. I can't run the intergration tests. Every one that i tried (even the GreetingResourceTest mentioned in CONTRIBUTING.md) gave me the same error:
```
Caused by: java.lang.IllegalStateException: No config found for class io.quarkus.vertx.http.runtime.HttpBuildTimeConfig
```
Given that i was unable to find any information about this on github i feel like i missed some very obvious step when setting up the Quarkus repo locally. But i am unable to spot the step i might be missing.

**Comment by sberyozkin** [comment]
@MelkorCC Thanks for giving a try, can you open a draft PR request, updating the main source only to copy those attributes, and I can help next week to add a test

**Comment by MelkorCC** [comment]
@sberyozkin i reverted my attempts with adding the tests for an ldap setup and created the draft pr

**Comment by sberyozkin** [comment]
Thanks @MelkorCC, I've commented in the PR, can give me a hint what to update, for example, in the DB user name and password entry, for the extra attributes be available, I'll then update one of the integration tests to verify the attribute(s) are copied

**Comment by MelkorCC** [comment]
@sberyozkin thanks again for your time and work on this issue
