### ISSUE TITLE
Config: Pattern converter error when Pattern used as key in Map to Nested Group

### ISSUE THREAD

**Issue by rudiger3d** [quarkusio/quarkus#44805]
### Describe the bug

If I have the following code:

```java
@ConfigMapping(prefix = "provider.tryg")
public interface TrygConfiguration {
    Map<Pattern, String> infoMapping();
}
```
and application.properties
```properties
provider.tryg.info-mapping.Campervan\ \\d=CAMPERVAN
```

and change the `infoMapping()` Map to

```java
@ConfigMapping(prefix = "provider.tryg")
public interface TrygConfiguration {
    Map<Pattern, NameLimit> infoMapping();

    interface NameLimit {
        String name();
        int limit();
    }
}
```

```properties
provider.tryg.info-mapping.Campervan\ \\d.name=CAMPERVAN
provider.tryg.info-mapping.Campervan\ \\d.limit=7000
```

### Expected behavior

Then if I iterate the `TrygConfiguration.infoMapping()` entrySet(), i.e.

```
    Map.Entry<Pattern, ...>
    entry.getKey().matcher("Campervan 6").matches();
```

I'd expect `entry.getKey().matcher("Campervan 6").matches()` to return true in both cases.

### Actual behavior

However in the second case, it returns false, because the internal pattern of the converted java.util.regex.Pattern is `"Campervan d"` and not `"Campervan \\d"`.

I know it is somewhat weird to use Pattern as a key in a Map, as you may only retrieve it via iteration, but it made the corresponding configuration in the "application.properties" easier to write so that's why :)

### Output of `uname -a` or `ver`

Darwin CO-MBP-C02YL4N9LVCF-DK 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "21.0.5" 2024-10-15 LTS OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode)

### Quarkus version or git rev

3.17.0

**Comment by radcortez** [comment]
Our own key parser uses `\` as an escape sequence, meaning that if you want to have a key with a `Pattern` with a proper escape sequence, you need to use `Campervan\ \\\\d.

**Comment by rudiger3d** [comment]
> Our own key parser uses `\` as an escape sequence, meaning that if you want to have a key with a `Pattern` with a proper escape sequence, you need to use `Campervan\ \\d.

I'm not totally sure I follow: In both cases above I have used `\` as an escape sequence for the key:

```provider.tryg.info-mapping.Campervan\ \\d=CAMPERVAN``` 

and 

```provider.tryg.info-mapping.Campervan\ \\d.name=CAMPERVAN```.

The first case, the Pattern is parsed correctly, but second where the value of the map is a nested group, it does not.

I can provide a reproducer, but if this is only supported by accident then I guess it won't really matter...

**Comment by radcortez** [comment]
Yes, I'm sorry. I noticed that my comment was misleading. I did type `\\\\d`, but I missed the final code block end element, and it got displayed as `\\d` only.

Thank you very much for your feedback. Feel free to provide ideas or improvements :)
