### ISSUE TITLE
Allow disabling default ResponseExceptionMapper per REST client

### ISSUE THREAD

**Issue by neon-dev** [quarkusio/quarkus#44813]
### Description

`microprofile.rest.client.disable.default.mapper=false` works on a global level.
It would be useful to have a configuration option that works on a per client basis.
In addition, an annotation could be introduced as a counterpart to the [programmatic way](https://download.eclipse.org/microprofile/microprofile-rest-client-3.0/microprofile-rest-client-spec-3.0.html#_default_responseexceptionmapper).

A new section in the REST cllient docs about it would also be helpful.

### Implementation ideas

An annotation could also work at the method level to solve #23957 without introducing unwanted side effects with other methods.

**Comment by geoand** [comment]
If I have time, I'll look into getting this into `3.18`

**Comment by geoand** [comment]
#44816 adds this functionality

**Comment by chonton** [comment]
Additional PR for [disabling client exception mapper when the proxy method return type is jakarta.ws.rs.core.Response](https://github.com/resteasy/resteasy-microprofile/pull/408)

**Comment by geoand** [comment]
That's nice, thanks!
