### ISSUE TITLE
quarkus.jacoco.excludes doesn't work since 3.17.0

### ISSUE THREAD

**Issue by waldmaier** [quarkusio/quarkus#44811]
### Describe the bug

```
quarkus:
  jacoco:
     excludes:
       -  "**/xsdgen1/**/*"
       -  "**/xsdgen2/**/*"
```

does not take effect by creating jacoco report

### Expected behavior

exclude subdirectories listed in yaml config

### Actual behavior

generated classes excluded in yaml are in the code coverage calculation

### How to Reproduce?

`mvn clean test`

look into jacoco report

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

21

### Quarkus version or git rev

3.17.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.9

**Comment by waldmaier** [comment]
Hi @geoand i am preparing a pet project and i noticed, that when using application.properties then it works, but if you use applicaton.yaml the it is not working. Seems to be an issue of quarkus yaml config

**Comment by geoand** [comment]
Cool, let me know when you have something

**Comment by waldmaier** [comment]
@geoand 
here are samples: working with 3.16.1 and non working with 3.17.0 


![Image](https://github.com/user-attachments/assets/5fcea9e9-a644-4cb1-9965-1f3f829ec92e)
![Image](https://github.com/user-attachments/assets/35e1649f-59b0-482e-a954-582b1bf16926)
[tests-with-coverage-quickstart-3-16-1-working.zip](https://github.com/user-attachments/files/17951279/tests-with-coverage-quickstart-3-16-1-working.zip)
[tests-with-coverage-quickstart-3-17-0-non-working.zip](https://github.com/user-attachments/files/17951280/tests-with-coverage-quickstart-3-17-0-non-working.zip)

i found out, that if you exchange in application-test.yaml in 3.17.0

```
quarkus:
  jacoco:
    excludes:
      - "**/xsdgen1/**/*"
      - "**/xsdgen2/**/*"
```

to

```
quarkus:
  jacoco:
    excludes: "**/xsdgen1/**/*,**/xsdgen2/**/*"

```
Seems, that yaml extension in 3.17.0 handles yaml arrays on different way than 3.16.1

**Comment by geoand** [comment]
Interesting, thanks.

@radcortez does that ring a bell?

**Comment by radcortez** [comment]
Yes, caused by this: https://github.com/smallrye/smallrye-config/pull/1203, which we did to reduce some allocs.

This shouldn't be required, because to populate a `Collection` one must use `Config.getValues(name, itemType)`, but apparently old roots use `Config.getValue(name, converter)` with a clever converter layering to construct the `Collection`.

As a workaround, one can use the already found solution described in the issue or downgrade `io.smallrye.config:smallrye-config-source-yaml` to `3.9.1`, which is compatible.

I'll see what I can do. Sorry for the inconvenience.

**Comment by geoand** [comment]
Thanks for the info @radcortez!

**Comment by gsmet** [comment]
@radcortez so you're saying it would be fixed if we switched to `@ConfigMapping`? Maybe we should just do that given that's our plan?

**Comment by radcortez** [comment]
Yes, that would fix it for this case. But there may be other root classes that have the same issue.

**Comment by gsmet** [comment]
Yes, what I'm saying is that depending on the complexity of the fix, it might be better to invest this time in migrating more config roots, given that's our ultimate goal.

**Comment by radcortez** [comment]
I was thinking of reverting the YAML source change and adding a note only to remove it once we remove all the old roots.

**Comment by radcortez** [comment]
Do we agree to proceed with the revert? I did try it, and it reverts to the previous behavior without any additional changes.

I can release a new version of SR Config today and update it to this Tuesday's release.

**Comment by geoand** [comment]
Yeah, sounds fine to me

**Comment by gsmet** [comment]
Yeah, sure, that would work for me!
