### ISSUE TITLE
Vert.x and SmallRye Reactive - many (280+) dependencies in generated BOM

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#44812]
### Description

Our generated BOM contains a many (280+) Vert.x and SmallRye Reactive dependencies in generated BOM

While Guillaume did some work to reduce the cost of this in the Maven resolve, there's still a cost associated to it. I'm wondering if we should be a bit more careful about it.

See generated BOM here: https://central.sonatype.com/artifact/io.quarkus/quarkus-bom .

And search for relevant groupId.

```
182 <groupId>io.vertx</groupId>
104 <groupId>io.smallrye.reactive</groupId>
43 <groupId>io.smallrye</groupId>
```

For `io.smallrye.reactive` it looks like we have Mutiny bindings for each Vert.x artifact, also SmallRye Reactive Messaging is part of this.

Note that the answer might very well be yes we need to keep all of them but I wanted to make sure we are aware of the situation.

This is inspired by https://github.com/quarkusio/quarkus/issues/44771 issue created by @gsmet

**Comment by cescoffier** [comment]
Yes, we need to keep them to ensure alignment. Removing them will encourage version divergence.
