### ISSUE TITLE
Tests: oidc-wiremock old certs, some oidc*/JWT native tests disabled

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#44847]
### Describe the bug

Hello,

OIDC tests need some maintenance:

## 1) OIDC Wiremock

It has started to fail in our CI. At first we thought it was a regression in a buidler image but it turns out it's a probably an expired certificate?

```
2024-11-30 08:43:42,222 INFO  [io.qua.tes.oid.ser.OidcWiremockTestResource] (main) Keycloak was shut down
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BearerTokenAuthorizationInGraalITCase>BearerTokenAuthorizationTest.testAccessAdminResourceWithFullCertChain:256 1 expectation failed.
Expected status code <200> but was <401>.

[ERROR]   BearerTokenAuthorizationInGraalITCase>BearerTokenAuthorizationTest.testAccessAdminResourceWithKidOrChain:415 1 expectation failed.
Expected status code <200> but was <401>.

[ERROR]   BearerTokenAuthorizationInGraalITCase>BearerTokenAuthorizationTest.testAccessResourceAzure:84 1 expectation failed.
Expected status code <200> but was <401>.

[ERROR]   BearerTokenAuthorizationInGraalITCase>BearerTokenAuthorizationTest.testCertChainWithCustomValidator:207 1 expectation failed.
Expected status code <200> but was <401>.

[ERROR]   BearerTokenAuthorizationInGraalITCase>BearerTokenAuthorizationTest.testFullCertChainWithOnlyRootInTruststore:318 1 expectation failed.
Expected status code <200> but was <401>.

[ERROR]   CodeFlowAuthorizationInGraalITCase>CodeFlowAuthorizationTest.testCodeFlowUserInfoCachedInIdToken:372 1 expectation failed.
Expected status code <200> but was <401>.

[INFO] 
[ERROR] Tests run: 49, Failures: 6, Errors: 0, Skipped: 0
[INFO] 
```

Looking at the directory:

```
$ for i in /home/karm/workspaceRH/quarkus/integration-tests/oidc-wiremock/src/main/resources/*.p12; do keytool -storepass storepassword -list -v -keystore $i 2>&1 | grep 2023 ;done
Valid from: Fri Nov 17 13:36:45 CET 2023 until: Tue Nov 26 13:36:45 CET 2024
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Valid from: Fri Nov 17 13:27:26 CET 2023 until: Thu Nov 12 13:27:26 CET 2043
Valid from: Fri Nov 17 13:27:26 CET 2023 until: Thu Nov 12 13:27:26 CET 2043
```

Steps to reproduce, e.g. 

```
$ ./mvnw verify --batch-mode -fae -f integration-tests/pom.xml 
   -Dmaven.test.failure.ignore=true -pl 'oidc-wiremock' 
   -Ddocker -Dnative -Dquarkus.native.container-build=true 
   -Dquarkus.native.builder-image=registry.access.redhat.com/quarkus/mandrel-for-jdk-21-rhel8:latest 
   -Dquarkus.native.native-image-xmx=10g
```

## 2) Disabled native tests

I find it suspicious that these modules have failsafe plugin with skip set to true. Doesn't it make the test merely build the native executable and then just don't run it? It seems like it to me locally. Similar to #43997 

e.g.
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc/pom.xml#L121
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-token-propagation/pom.xml#L134
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-token-propagation-reactive/pom.xml#L124
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-tenancy/pom.xml#L151
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-mtls/pom.xml#L99
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-code-flow/pom.xml#L169
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client/pom.xml#L124
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client-registration/pom.xml#L109
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client-reactive/pom.xml#L156
https://github.com/quarkusio/quarkus/blob/main/integration-tests/smallrye-jwt-oidc-webapp/pom.xml#L158
https://github.com/quarkusio/quarkus/blob/main/integration-tests/smallrye-jwt-token-propagation/pom.xml#L157

### Output of `uname -a` or `ver`

5.14.0-362.13.1.el9_3.x86_64

### Output of `java -version`

JDK 17, 21

### Quarkus version or git rev

3.8.6, 3.15.1

**Comment by sberyozkin** [comment]
@Karm PR is open to resolve the oidc wiremock issue, this part of the issue is a duplicate of another issue, sorry,  on the phone right now. 
Can you please check and close the other one as duplicate? Or this one ?
Please open a dedicated issue related to native tests
