### ISSUE TITLE
quarkus create extension creates an incorrect integration-tests module

### ISSUE THREAD

**Issue by akil-rails** [quarkusio/quarkus#44862]
### Describe the bug

Hi, running a quarkus create extension, creates an integration-tests module, with the following dependency
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
```
This has to be manually changed to the following 
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest</artifactId>
    </dependency>
```
for the integration-tests project to compile. 

### Expected behavior

The integration-tests module should include the updated dependency `quarkus-rest` instead of `quarkus-resteasy-reactive`

### Actual behavior

The integration-tests module includes the dependency `quarkus-resteasy-reactive`

### How to Reproduce?

Reproducer:

1. quarkus create extension `com.example:something`
2. `mvn clean install`
3. cd integration-tests
4. `quarkus dev`

### Output of `uname -a` or `ver`

Darwin Mac.domain.name 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112 arm64

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15) OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

### Quarkus version or git rev

3.17.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: /Users/akil/.sdkman/candidates/maven/current Java version: 21, vendor: GraalVM Community, runtime: /Users/akil/.sdkman/candidates/java/21-graalce Default locale: en_IN, platform encoding: UTF-8 OS name: "mac os x", version: "15.1.1", arch: "aarch64", family: "mac"

**Comment by geoand** [comment]
Are you perhaps using an old version of the `quarkus` CLI?

Asking because #43132 should have fixed the issue.

**Comment by akil-rails** [comment]
Yes, sorry - I was using an older version of quarkus cli - .

**Comment by geoand** [comment]
Thanks for checking!
