### ISSUE TITLE
Setting headers for SSE annotated Multi resources is ignoring headers

### ISSUE THREAD

**Issue by dastrobu** [quarkusio/quarkus#44902]
### Describe the bug

Setting response headers as shown below does not work when the resource is annotated with `@Produces(MediaType.SERVER_SENT_EVENTS)` or `@RestStreamElementType(MediaType.APPLICATION_JSON)`. 

```java
        @POST
        @Path("sse-multi")
        @Produces(MediaType.SERVER_SENT_EVENTS)
        public Multi<String> sseMulti() {
            return RestMulti.fromMultiData(Multi.createFrom().items("hello", "world")).header("Foo", "Bar").build();
        }

```

See also https://github.com/quarkusio/quarkus/issues/44898#issuecomment-2514837180 

### Expected behavior

headers are set as in 

```java
        @POST
        @Path("multi")
        public Multi<String> multi() {
            return RestMulti.fromMultiData(Multi.createFrom().items("hello", "world")).header("Foo", "Bar").build();
        }

```

### Actual behavior

header is ignored 

### How to Reproduce?

I will provide a draft PR with a unit test.

**Comment by geoand** [comment]
We need to add `RestMulti` support to SSE handling

**Comment by geoand** [comment]
#44903 takes care of this

**Comment by geoand** [comment]
I am going to reopen this as I explain [here](https://github.com/quarkusio/quarkus/issues/45346#issuecomment-2574989650)
