### ISSUE TITLE
LogManager error of type GENERIC_FAILURE 

### ISSUE THREAD

**Issue by joe-specimen** [quarkusio/quarkus#44914]
### Describe the bug

Since Quarkus 3.17.2, the following error is thrown when starting the application:

`LogManager error of type GENERIC_FAILURE: Section header cannot be encoded into charset "windows-1252"`

I have no settings regarding logging inside of the application.properties file. So everything should be set to defalt.

It was working fine with Quarkus 3.17.0.

### Expected behavior

Before the Quarkus logo is being printed (see below)
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/

### Actual behavior

Now the following message is shown

`LogManager error of type GENERIC_FAILURE: Section header cannot be encoded into charset "windows-1252"`

### How to Reproduce?

1. Generate simple Quarkus REST maven project with the release number 3.17.2. 
2. Build it with maven wrapper inside project (I used java 21)
3. Start the application and there is no Quarkus logo but instead it is message "LogManager error of type GENERIC_FAILURE: Section header cannot be encoded into charset "IBM437"

**Comment by geoand** [comment]
@dmlloyd has this since been fixed?

**Comment by dmlloyd** [comment]
I was able to reproduce this on Linux:

```
$ /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home/bin/java -Dquarkus.platform.version=3.17.2 -Dquarkus.application.version=1.0.0-SNAPSHOT -Dquarkus.platform.artifact-id=quarkus-bom -Dquarkus.platform.group-id=io.quarkus.platform -Dquarkus.application.name=rest-project-test -jar /Volumes/Case-sensitive/david/src/java/rest-project-test/target/quarkus-app/quarkus-run.jar
LogManager error of type GENERIC_FAILURE: Section header cannot be encoded into charset "US-ASCII"
2024-12-04 09:05:04,955 INFO  [io.quarkus] (main) rest-project-test 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.17.2) started in 0.424s. Listening on: http://0.0.0.0:8080
2024-12-04 09:05:04,960 INFO  [io.quarkus] (main) Profile prod activated. 
2024-12-04 09:05:04,960 INFO  [io.quarkus] (main) Installed features: [cdi, rest, smallrye-context-propagation, vertx]
2024-12-04 09:05:07,328 INFO  [io.quarkus] (main) rest-project-test stopped in 0.022s
$ java --version
openjdk 21.0.3 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode)
```

However I have not been able to reproduce it directly in `jshell` yet.

**Comment by gsmet** [comment]
Let’s try to get a fix in the Quarkus tree before next Tuesday so that I can include it in 3.17.4.

**Comment by rsvoboda** [comment]
+1 to have this in ideally in 3.17.4, we noticed the same fail in PR for Quarkus bump in https://github.com/quarkus-qe/quarkus-startstop
