### ISSUE TITLE
Spring Cloud Configuration ordinal customization

### ISSUE THREAD

**Issue by thibaultmeyer** [quarkusio/quarkus#44923]
### Description

Currently, the ordinal of the Spring Cloud Configuration values start at 450 ([SpringCloudConfigClientConfigSourceFactory#76](https://github.com/quarkusio/quarkus/blob/main/extensions/spring-cloud-config-client/runtime/src/main/java/io/quarkus/spring/cloud/config/client/runtime/SpringCloudConfigClientConfigSourceFactory.java#L76)). This value is a bit high, according to the [Quarkus documentation](https://quarkus.io/guides/config-extending-support), System Properties have a ordinal of 400. With a ordinal of 450, Spring Cloud Configuration values cannot be overridden by existing configuration sources.

### Implementation ideas

Like the extension `quarkus-vault`, it could be a good idea to let the developper to choose ordinal of the Spring Cloud Configuration sources.

**Currently**
```java
int ordinal = 450;
// Profiles are looked from the highest ordinal to lowest, so we reverse the collection to build the source list
Collections.reverse(responses);
for (Response response : responses) {
    /* ... */
```

**Changes**
```java
int ordinal = config.ordinal();
// Profiles are looked from the highest ordinal to lowest, so we reverse the collection to build the source list
Collections.reverse(responses);
for (Response response : responses) {
    /* ... */
```

`config.ordinal()` will be defined in `SpringCloudConfigClientConfig` with default value of 450.

**Comment by thibaultmeyer** [comment]
hi @geoand 

no problem, I'm preparing a pull request.

**Comment by geoand** [comment]
🙏🏽

**Comment by thibaultmeyer** [comment]
@geoand 

I've just opened a PR to add ordinal customisation

**Comment by gsmet** [comment]
@thibaultmeyer do you have the default ordinal for Quarkus Vault in mind? Probably a good idea to make them consistent.

**Comment by thibaultmeyer** [comment]
hi @gsmet 

`quarkus-vault` ordinal is 270 [(VaultRuntimeConfig.java#L32)](https://github.com/quarkiverse/quarkus-vault/blob/main/runtime/src/main/java/io/quarkus/vault/runtime/config/VaultRuntimeConfig.java#L32).
