### ISSUE TITLE
Grpc client interceptors are not registered when injected via constructor

### ISSUE THREAD

**Issue by RoMiRoSSaN** [quarkusio/quarkus#44932]
### Describe the bug

Since version 3.9 client interceptors are not registered when injected via constructor, if there are more than 1 of interceptor. 
If there is one, then it registers successfully.
When inject by field - all works.

How I understand, there were changes in InjectionPointInfo or somewhere else that affected this. If more than 1 interceptor is listed, they are not included in the qualifiers. As a result, not a single interceptor is registered.
https://github.com/quarkusio/quarkus/blob/main/extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java#L433

Before version 3.9 it works normal. I checked from 3.9 to 3.17, and this bug containing.

### Expected behavior

1. If 1 interceptor - interceptor registered
2. If 2 or more interceptors - interceptor registered

### Actual behavior

1. If 1 interceptor - interceptor registered
2. If 2 or more interceptors - none are registered

### How to Reproduce?

Reproducer: [grpc-demo.zip](https://github.com/user-attachments/files/18021279/grpc-demo.zip)

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
It's very likely a regression caused by https://github.com/quarkusio/quarkus/commit/d34eb5adda6cd3fe534e538bbf16170b5f6df212#diff-c176df2cb8a1cd56ae30ff243a7c6f817604c94f4b755ff424a79bdf0fd6b798. The code filters the qualifiers by annotation target but for nested annotations (which is the case for repeatable annotations used in a container) it's `null`.

CC @manovotn

**Comment by manovotn** [comment]
@RoMiRoSSaN in your reproducer, I don't see the `FirstClientInterceptor` and `SecondClientInterceptor` being invoked regardless of whether you use field injection or constructor. Am I missing something?
I do see the `GlobalClientInterceptor` being invoked but none other.

> It's very likely a regression caused by https://github.com/quarkusio/quarkus/commit/d34eb5adda6cd3fe534e538bbf16170b5f6df212#diff-c176df2cb8a1cd56ae30ff243a7c6f817604c94f4b755ff424a79bdf0fd6b798. The code filters the qualifiers by annotation target but for nested annotations (which is the case for repeatable annotations used in a container) it's null.

Yes, after some digging it seems that the [code here](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InjectionPointModifier.java#L45-L49) is a leftover of the commit you posted that should have been removed with https://github.com/quarkusio/quarkus/pull/40841. We should now be able to just `return transformationContext.getQualifiers()`

**Comment by RoMiRoSSaN** [comment]
@manovotn Hi. I have redesigned the reproducer for better understanding.
Start it and call GET/client method. In out will be
```
Start call from injected by constructor one - first interceptor will be
FIRST CLIENT
End call from injected by constructor one. If you see FIRST CLIENT - all works

Start call from injected by constructor two - must be two interceptors messages
End call from injected by constructor two. Nothing. Interceptors not working     <------ problem

Start call from injected by field one - first interceptor will be
FIRST CLIENT
End call from injected by field one. If you see FIRST CLIENT - all works

Start call from injected by field two - will be first and second interceptors
FIRST CLIENT
SECOND CLIENT
End call from injected by field two. If you see FIRST and SECOND CLIENT - all works
```
Reproducer: [grpc-demo.zip](https://github.com/user-attachments/files/18028177/grpc-demo.zip)

**Comment by alesj** [comment]
> with constructor injection

Yeah, just copy/paste the test and should be fine.
Or perhaps some base class for both cases - field and ctor injection test.

```
    public CtorClientInterceptorRegistrationTest(
        @RegisterClientInterceptor(MyLastClientInterceptor.class)
        @RegisterClientInterceptor(MyThirdClientInterceptor.class)
        @GrpcClient("hello-service") GreeterGrpc.GreeterBlockingStub client)
    {
        this.client = client;
    }
```

**Comment by manovotn** [comment]
Ah, I see, I misunderstood it originally, thanks for clarification @RoMiRoSSaN :)

The fix I mentioned above works for your reproducer, so I'll push that along with a test momentarily.
