### ISSUE TITLE
Keycloak devservice can be started indirectly if `quarkus-oidc` uses `quarkus.oidc.provider`

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#44938]
### Describe the bug

At some point, when, for example,  both `quarkus-oidc` and `quarkus-oidc-client` were included, and no properties like `quarkus.oidc.auth-server-url` or `quarkus.oidc.provider` were configured, `quarkus-oidc` would have Keycloak devservice launched.

Now, `quarkus-oidc-client` and other OIDC/Keycloak aware extensions can launch Keycloak devservice on its own.

However, if `quarkus-oidc` has indicated that it does not want Keycloak devservice, then `quarkus-oidc-client` should not launch it. For example:

```
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc</artifactId>
 </dependency>
 <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-oidc-token-propagation</artifactId>
 </dependency>    
```

here, `quarkus-rest-client-oidc-token-propagation`  brings `quarkus-oidc-client` for the optional token exchange, the token propagation will be applied to REST clients which do not deal with OIDC.

And we have for example `quarkus.oidc.provider=slack` - indicating no Keycloak container is needed. But Keycloak container is still launched.

### Expected behavior

If `quarkus-oidc` does not need it, then client extensions like `quarkus-oidc-client` should not launch it either. 
IMHO it is very unlikely that when `quarkus-oidc` wants to work for example with `Slack`, the `quarkus-oidc-client` still wants to use Keycloak container.

**Comment by michalvavrik** [comment]
Thanks, it's on the top of my list now.
