### ISSUE TITLE
Bug Report: Multipart Parsing Issue with quarkus-resteasy-multipart

### ISSUE THREAD

**Issue by adaptivecodes** [quarkusio/quarkus#44950]
### Describe the bug

Hello,

I am using Quarkus platform version 3.16.4 along with the quarkus-resteasy-multipart extension for uploading files of various content types, such as CSV.

However, when sending files, the multipart data is parsed incorrectly.

**Root Cause Analysis**
After investigating, I identified the issue originates from the [james-mime4j](https://github.com/apache/james-mime4j) library. 
The RawFieldParser finds “name” in the content disposition and then checks via the CharsetUtils whether the rest of the string contains a non-asciicharacter. In my example, this is the case, which is why it then uses the method parseUtf8Filename(ByteSequence buf) to search for the prefix filename. The filename is then matched in my parameters instead of the name

**Related Work**
The issue has been identified in james-mime4j, and while a fix has been committed upstream, no updated version of the library has been released:
[Fix Commit in james-mime4j](https://github.com/apache/james-mime4j/commit/bdb2264abd17badf70e27f7e32907bccc82d005e)

**Request**
Since updating the library is not an option due to the absence of a release, is there a workaround or patch that can be implemented in Quarkus to address this issue?

Thank you!

### Expected behavior

Content-Disposition is matched correctly:
name="file"
filename="FILENAME_WITH_NON_ASCII_ääää.csv"

### Actual behavior

Content-Disposition is matched incorrectly:
name="FILENAME_WITH_NON_ASCII_ääää.csv"
filename="FILENAME_WITH_NON_ASCII_ääää.csv"
file=null
....

### How to Reproduce?

Following Payload can be used to provoke the issue: 

-----------------------------154025669139289077931562893868
Content-Disposition: form-data; name="file"; filename="FILENAME_WITH_NON_ASCII_ääää.csv"
Content-Type: text/csv

SPALTE_A;SPALTE_B
11111;ABCD
22222;ABCD

-----------------------------154025669139289077931562893868
Content-Disposition: form-data; name="fileName"

FILENAME_WITH_NON_ASCII_ääää.csv
-----------------------------154025669139289077931562893868--

Java part:     
@POST
    @Path("/myPath")
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public Response doUpload(MultipartFormDataInput uploadedFile) {
        return Response.ok("").build();
    }

### Output of `java -version`

openjdk version "17.0.13" 2024-10-15 LTS

### Quarkus version or git rev

3.16.4 

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /usr/lib/maven-3.9.8

**Comment by geoand** [comment]
cc @jamezp

**Comment by adaptivecodes** [comment]
It seems like someone else has also encountered this issue: [related Issue](https://github.com/quarkusio/quarkus/issues/41272)

**Comment by geoand** [comment]
Good point!

**Comment by jamezp** [comment]
@geoand This is related to https://issues.redhat.com/browse/RESTEASY-3495. There isn't anything in RESTEasy we can do. However, a workaround is to use something like `"filename=\"UTF=8'' + URLEncorder.encode() + "\""`.

**Comment by geoand** [comment]
Thanks @jamezp !
