### ISSUE TITLE
[Extension Proposal] - Quarkus Application Metadata Extension

### ISSUE THREAD

**Issue by amusarra** [quarkusio/quarkus#44951]
## Overview

The Quarkus Application Metadata Extension provides a way to manage and expose metadata about your Quarkus application. This includes information about the application itself, its dependencies, platform details, Java build information, and source control management (SCM) details.

## Features

- **AppMetadataHandler**: Handles HTTP requests and returns application metadata as a JSON response.
- **AppMetadataWrapper**: A CDI bean that wraps the `AppMetadata` object.
- **AppMetadata**: A record class that holds various metadata about the application, including platform info, dependencies, Java build info, and SCM info.

### Repository name

quarkus-app-metadata-extension

### Short description

Extension that displays Quarkus application metadata. In addition to displaying the usual information such as name, groupId, artifactId and version, it displays information about: platform version, runtime dependencies, Java build information and information about the scm.

### Repository Homepage URL

https://docs.quarkiverse.io/quarkus-app-metadata-extension/dev/

### Repository Topics

- quarkus-extension
- application-metadata

### Team Members

- @amusarra 

### Additional context

The source code repository is currently available on my GitHub account https://github.com/amusarra/quarkus-app-metadata-extension

**Comment by amusarra** [comment]
Hi @gastaldi and thanks for your quick response.

Then I will think about extending the extension you mentioned by adding the additional information I have planned on my implementation.

The following is an example of JSON where there is some additional information.

```json
{
  "name": "users-service",
  "groupId": "org.acme",
  "artifactId": "users-service",
  "version": "1.0.0-SNAPSHOT",
  "platformInfo": [
    {
      "platform": "io.quarkus.platform",
      "version": "3.15.1"
    }
  ],
  "dependencies": [
    {
      "groupId": "io.quarkus",
      "artifactId": "quarkus-resteasy",
    }
  ],
  "javaBuildInfo": [
    {
      "javaVendor": "Amazon.com Inc.",
      "javaVendorVersion": "Corretto-21.0.2.13.1",
      "javaVersion": "21.0.2",
      "osArch": "aarch64",
      "osName": "Mac OS X",
      "osVersion": "15.1.1",
      "buildTime": 1733422571929
    }
  ],
  "scmInfo": {
    "branch": "main",
    "tag": "v1.0.0-rc.01",
    "commitId": "2d41a5c891eb0ee07ba6727265898c4e45c08699",
    "commitDate": "2024-12-05T12:59:31Z",
    "authorName": "Antonio Musarra",
    "authorEmail": "antonio.musarra@gmail.com",
    "remoteUrl": "https://github.com/amusarra/quarkus-users-service.git"
  }
}
```

**Comment by melloware** [comment]
Yep you can just add your own metadata into the info extension . I do it in Quarkus OmniFaces Extension displaying the Faces version info etc.

See: https://github.com/quarkiverse/quarkus-omnifaces/blob/main/runtime/src/main/java/io/quarkus/omnifaces/runtime/FacesInfoContributor.java
