### ISSUE TITLE
 High contention on TransactionManager class

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#4497]
The current Narayana integration frequently calls TransactionalInterceptorBase.invokeInOurTx(), which looks up the current configured TX timeout via
((TransactionManagerImple) com.arjuna.ats.jta.TransactionManager.transactionManager()).getTimeout()

This is a very expensive call, as com.arjuna.ats.jta.TransactionManager.transactionManager() is synchronized on the com.arjuna.ats.jta.TransactionManager class.

1. Profiling applications using transactions under heavy load shows TransactionManager as a heavily contended monitor

**Comment by geoand** [comment]
With #4496 should this be closed?

**Comment by johnaohara** [comment]
Yes, closing
