### ISSUE TITLE
Quarkus Generator for gradle projects generates broken GitHub-Workflow

### ISSUE THREAD

**Issue by Joniator** [quarkusio/quarkus#44975]
### Describe the bug

If you use code.quarkus.io to generate a starter template using gradle instead of maven, it generates a wrong `.github/workflows/ci.yml` when pushing the project to github.

### Expected behavior

It generates a working workflow that builds the application with gradle

### Actual behavior

The generated workflow configures the java action to use caching for maven, which fails because the project doesn't contain any pom.xml files.

### How to Reproduce?

1. Go to https://code.quarkus.io
2. Select `Gradle` or Gradle with Kotlin DSL
3. Generate and push to github.

**Comment by geoand** [comment]
cc @gastaldi
