### ISSUE TITLE
REST Client not sending headers from shared configKey

### ISSUE THREAD

**Issue by jburkal** [quarkusio/quarkus#44989]
### Describe the bug

When multiple REST Client classes uses the same value for `configKey` in their `@RegisterRestClient` annotation, headers specified in `application.properties` (using the `quarkus.rest-client."client".headers."header-name"` format) are no longer sent for all of the clients.

### Expected behavior

Headers specified in the configuration of a specific REST client, e.g.:
```properties
quarkus.rest-client."testClient".headers."My-Header"=Test Header
```
should be sent on requests from all classes annotated with `@RegisterRestClient(configKey = "testClient")`

### Actual behavior

Since Quarkus 3.17.0, the headers are only sent for one of the REST client classes.

It works as expected in both Quarkus 3.15.2 and 3.16.4.

### How to Reproduce?

Reproducer: https://github.com/jburkal/quarkus-rest-header-test

Running the application (`./mvnw quarkus:dev`) with Quarkus 3.15.2 or 3.16.4 produces log lines such as:
```
DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] Request: GET https://stage.code.quarkus.io/api/extensions?id=quarkus-rest-client Headers[My-Header=Test Header User-Agent=Test User Agent], Empty body
DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] Request: GET https://stage.code.quarkus.io/api/streams Headers[My-Header=Test Header User-Agent=Test User Agent], Empty body
```
whereas with Quarkus 3.17.0 and newer, it looks like this:
```
DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] Request: GET https://stage.code.quarkus.io/api/extensions?id=quarkus-rest-client Headers[My-Header=Test Header User-Agent=Test User Agent], Empty body
DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] Request: GET https://stage.code.quarkus.io/api/streams Headers[User-Agent=Test User Agent], Empty body
```
Note that the second request no longer contains the "My-Header" header.

### Quarkus version or git rev

3.17.0

**Comment by radcortez** [comment]
For now, please use the FQN of the REST Client to set up the configuration.
