### ISSUE TITLE
The `elasticsearch-rest-client` extension not terminating dev mode service

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#44994]
### Describe the bug

When the Quarkus app contains `elasticsearch-rest-client`  extension, it start the elasticsearch service as devservice. When the dev mode is ended (by presing `q` or `ctrl + c`) it left the eleasticsearch container running.

Note: When the dev mode is started again, it connect to already created and running service.

### Expected behavior

The elesticsearch is shutdown when the dev mode is ended. We doing this with other dev services.

### Actual behavior

The elesticsearch is not shutdown

### How to Reproduce?

1. Simple quarkus app containing `elasticsearch-rest-client` extension (https://code.quarkus.io/?e=elasticsearch-rest-client)
2. Start dev mode
3. End dev mode
4. `docker/podman ps` and the elesticsearch still running

### Output of `uname -a` or `ver`

Fedora 40

### Output of `java -version`

OpenJDK Runtime Environment (build 21+35-2513)

### Quarkus version or git rev

3.17.3, 3.15.2, 3.8.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

**Comment by yrodiere** [comment]
Hey,

The Elasticsearch dev services (and a few others) supports reusing containers across app executions. This is documented [here](https://quarkus.io/guides/elasticsearch-dev-services#reuse).

This "reuse" feature is enabled automatically as soon as you have a file at `~/.testcontainers.properties` or `C:/Users/myuser/.testcontainers.properties` containing this line:

```properties
testcontainers.reuse.enable=true
```

Do you have such a file?

**Comment by jedla97** [comment]
Thanks @yrodiere I know that Quarkus have same property for this, but didn't know that there is testcontainer file itself.

I had the mentioned file, so I'm closing this as resolved. I have this file apparently for quite some time, but this is first time when this happen. Anyway thanks for explanation!

**Comment by yrodiere** [comment]
No problem, thanks for getting back to us!
