### ISSUE TITLE
Project Freezes During Build with quarkus-hibernate-validator and quarkus-openapi-generator

### ISSUE THREAD

**Issue by be320** [quarkusio/quarkus#44991]
### Describe the bug

When using both quarkus-hibernate-validator and quarkus-openapi-generator dependencies in the same project, the build process freezes indefinitely during the build phase. The issue occurs consistently and prevents the project from completing the build successfully.

### Expected behavior

The build should complete successfully without freezing when using both dependencies.

### Actual behavior

The build process freezes indefinitely, making it impossible to proceed.

### How to Reproduce?

Steps to Reproduce

1. Create a Quarkus project with the following dependencies:

<dependencies>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-hibernate-validator</artifactId>
        <version>...</version>
    </dependency>
    <dependency>
        <groupId>io.quarkiverse.openapi.generator</groupId>
        <artifactId>quarkus-openapi-generator</artifactId>
        <version>...</version>
    </dependency>
</dependencies>

2. Run the build command:
mvn clean install

3. Observe the build process freezing indefinitely.

### Output of `java -version`

21.0.5

### Quarkus version or git rev

3.17.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9

**Comment by marko-bekhta** [comment]
Hey @be320 

What version of `quarkus-openapi-generator` are you using? I think there was a problem with 2.5 (or one close to it) that may lead to the problem you've described. Please try with the latest `2.7.0`. If you still have a problem with the latest versions, could you share a reproducer, since I couldn't get the build to freeze with a simple project with these two dependencies? Thanks!

**Comment by yrodiere** [comment]
Hello,

I did this:

```shell
quarkus create app -x quarkus-hibernate-validator,quarkus-openapi-generator,quarkus-rest-client-jackson
cd code-with-quarkus
mvn clean install
```

And the build passed:

```
[INFO] --- install:3.1.2:install (default-install) @ code-with-quarkus ---
[INFO] Installing /home/yrodiere/tmp/tmp/code-with-quarkus/pom.xml to /home/yrodiere/.m2/repository/org/acme/code-with-quarkus/1.0.0-SNAPSHOT/code-with-quarkus-1.0.0-SNAPSHOT.pom
[INFO] Installing /home/yrodiere/tmp/tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT.jar to /home/yrodiere/.m2/repository/org/acme/code-with-quarkus/1.0.0-SNAPSHOT/code-with-quarkus-1.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.800 s
[INFO] Finished at: 2024-12-09T09:03:49+01:00
[INFO] ------------------------------------------------------------------------
```

Same with `./mvnw clean install`.

Here's my attempt: https://github.com/yrodiere/quarkus-playground/tree/i44991

We will need more information to help. Please provide:

1. A reproducer, including in particular code and configuration you're using.
2. _And_ any logs that may help determine what it freezing exactly (trace logging during the build may help here).

**Comment by Postremus** [comment]
@be320 
I had the same problem, as reported in https://github.com/quarkiverse/quarkus-openapi-generator/issues/824#issuecomment-2484834358.

The fix is
https://github.com/quarkiverse/quarkus-openapi-generator/pull/829

Could you try 2.7.0-lts?

**Comment by be320** [comment]
I upgraded quarkus-openapi-generator to 2.7.0-lts , and It is now fixed. Thanks alot for your support. @Postremus  @marko-bekhta @yrodiere @gsmet
