### ISSUE TITLE
[Extension Proposal] Create an extension for Presidio

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#44997]
### Description

With the advent of AI, obfuscating data is becoming increasingly important. One way to check the space out there, especially in Python, is to use Presidio (https://microsoft.github.io/presidio/).

This extension provides a REST Client to connect to a Presidio instance and, optionally, a DevService to start an instance.

I have already created a Rest Client to connect to a Presidio instance using the MicroProfile spec, so it is a matter of reusing that repo https://github.com/lordofthejars/presidio-java as a base.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-presidio

### Short description

Integration with Presidio

### Repository Homepage URL

https://docs.quarkiverse.io/quarkus-presidio/dev/

### Repository Topics

- quarkus-extension
- presidio
- obfuscating

### Team Members

- lordofthejars

**Comment by melloware** [comment]
I didn't know about Presidio but this will be a great extension.
