### ISSUE TITLE
REST Client using configKey resolves wrong config

### ISSUE THREAD

**Issue by elvoe** [quarkusio/quarkus#45002]
### Describe the bug

I have 2 REST clients with the same simple class name but different packages:
```
dk.elvoe.experiments.client1.MyClient
dk.elvoe.experiments.client2.MyClient
```
They use different configKey:
```
@RegisterRestClient(configKey = "myConfig1") interface MyClient {}
@RegisterRestClient(configKey = "myConfig2") interface MyClient {}
```
I configure them using the configKey:
```
quarkus.rest-client.myConfig1.url=http://localhost:8081/hello1
quarkus.rest-client.myConfig2.url=http://localhost:8081/hello2
```
The bug is that requests made using `client1.MyClient` uses the URL of `myConfig2`.

### Expected behavior

Using configKey should always resolve the corresponding configuration properties, regardless of the class name.

### Actual behavior

Since Quarkus 3.17.0, a REST client may use the wrong configuration for a configKey, when multiple REST client interfaces have the same simple class name.

It works as expected in Quarkus 3.16.4.

### How to Reproduce?

Reproducer: https://github.com/elvoe/quarkus-bug-rest-client-config

Run `gradle check` and the test method in MyTest will fail because of the Quarkus bug. It fails because the response from `myClient1.get()` is expected to receive the payload of the endpoint `/hello1`, but it actually receives the payload of the endpoint `/hello2`.

The test passes when changing the Quarkus version to 3.16.4.

### Output of `java -version`

21

### Quarkus version or git rev

3.17.3

### Additional information

The issue has similarities with #44989

**Comment by gsmet** [comment]
@radcortez could you have a look at this one? It looks related to the latest work done in this area and it looks quite problematic. Thanks!

**Comment by gsmet** [comment]
@radcortez please also have a look at https://github.com/quarkusio/quarkus/issues/44989 as they seem tightly related.

**Comment by radcortez** [comment]
For now, please use the FQN of the REST Client to set up the configuration.
