### ISSUE TITLE
Kubernetes ServiceAccount created when default init tasks is disabled

### ISSUE THREAD

**Issue by Malandril** [quarkusio/quarkus#45021]
### Describe the bug

With the kubernetes extension, and the liquibase extension when setting the configuration `quarkus.kubernetes.init-task-defaults.enabled=false` a `ServiceAccount` kubernetes resource is still added to the generated `kubernetes.yml`

### Expected behavior

A `ServiceAccount` should not be generated when not needed by init tasks.

### Actual behavior

A `ServiceAccount` is still added to the generated kubernetes yaml even with `quarkus.kubernetes.init-task-defaults.enabled=false` .

### How to Reproduce?

Create a project with kuberntes and liquibase
`quarkus create app  --gradle-kotlin-dsl  -x 'kubernetes,mariadb,liquibase' quark-bug-kube`

Add  `quarkus.kubernetes.init-task-defaults.enabled=false` to the application.properties
Generate the kubernetes.yml:

`./gradlew quarkusBuild`

The generated `ServiceAccount` is added

### Quarkus version or git rev

3.17.3

### Additional information

It seems to happen since this commit a9f23559e1e4c1c6de40d09374a53a2543272a9c

**Comment by geoand** [comment]
> It seems to happen since this commit https://github.com/quarkusio/quarkus/commit/a9f23559e1e4c1c6de40d09374a53a2543272a9c

cc @radcortez
