### ISSUE TITLE
Build with devservices failed because download of redpanda leads to 404

### ISSUE THREAD

**Issue by bumbel42so** [quarkusio/quarkus#45026]
### Describe the bug

I get the error message 
Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"pull access denied for vectorized/redpanda, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}
and the link in https://quarkus.io/guides/kafka-dev-services to https://hub.docker.com/r/vectorized/redpanda shows a 404 error page.

### Expected behavior

Devservices should use an existing image.

### Actual behavior

Devservices use a not existing image (https://hub.docker.com/r/vectorized/redpanda)

### How to Reproduce?

Do a quarkus build/dev/test which uses https://hub.docker.com/r/vectorized/redpanda on a machine its not cached

**Comment by geoand** [comment]
cc @ozangunalp

**Comment by ozangunalp** [comment]
Redpanda renamed their repository organization from vectorized to redpandadata. We didn't catch it because it was always redirected to the new one. I think docker hub stopped the follow.

**Comment by bumbel42so** [comment]
As Quick&Dirty workaround
`quarkus.kafka.devservices.image-name=redpandadata/redpanda`
works for me
