### ISSUE TITLE
Kafka devservices use deprecated redpanda image

### ISSUE THREAD

**Issue by jzanker** [quarkusio/quarkus#45037]
### Describe the bug

the kafka dev services currently use the vectorised/redpanda image from docker.io. which is deprecated (and now also deleted) and has been replaced by redpandadata/redpanda. 

### Expected behavior

the kafka dev services should use the new image as default.

### Actual behavior

the old image could not be pulled and the start of the dev service failed.

**Comment by geoand** [comment]
See https://github.com/quarkusio/quarkus/discussions/45032

**Comment by ozangunalp** [comment]
https://github.com/quarkusio/quarkus/discussions/45030

See the fix and possible workarounds
