### ISSUE TITLE
DataSource configuration is not passed to PgPool instance when using quarkus-reactive-pg-client and quarkus-hibernate-orm within the same project

### ISSUE THREAD

**Issue by abner** [quarkusio/quarkus#4505]
I got io.vertx.pgclient.PgException: password authentication failed for user "user" when trying the Reactive Postgres Client extension in a project after i added  quarkus-hibernate-orm.

If i comment out the dependency quarkus-hibernate-orm, then the datasource configurated works just fine.

**Comment by abner** [comment]
@FroMage i know you are the guy to help me with this. :sos: 
Thanks in advance!

**Comment by emmanuelbernard** [comment]
Hey @abner we did some work in that area in Quarkus 1.3. Can you try it out and reopen if that's still an issue?
