### ISSUE TITLE
[Extension Proposal] Model Context Protocol (MCP) server

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#45054]
### Description

_"[Model Context Protocol](https://modelcontextprotocol.io/) (MCP) is an open protocol that enables seamless integration between LLM applications and external data sources and tools."_

In this extension, we would like to provide a declarative API that enables developers to implement MCP server features easily.

For example, an exposed prompt template could be implemented as a business method of a CDI bean:
```java
public class MyPrompts {

    @Inject
    FooService fooService;

    @Prompt(description = "Not much we can say here.") // prompt name is derived from the method name, desc is optional
    PromptMessage foo(@PromptArg(description = "The name") String name) { // @PromptArg is optional
        return new PromptMessage("user", new TextContent(fooService.ping(name)));
    }

}
```

### Repository name

quarkus-mcp-server

### Short description

This extension enables developers to implement the MCP server features easily.

### Repository Homepage URL

https://docs.quarkiverse.io/quarkus-mcp-server/dev/

### Repository Topics

- quarkus-extension
- 
...

### Team Members

- @mkouba

**Comment by geoand** [comment]
🎉

**Comment by jmartisk** [comment]
I assume you plan to support the HTTP/SSE transport? Or also stdio transport (that may get tricky because Quarkus prints a lot of stuff to stdout, so we would have to turn all logging off I guess)

**Comment by mkouba** [comment]
> I assume you plan to support the HTTP/SSE transport? Or also stdio transport (that may get tricky because Quarkus prints a lot of stuff to stdout, so we would have to turn all logging off I guess)

Good question. Yes, only HTTP/SSE transport at the moment.
