### ISSUE TITLE
Error while application start after upgrade

### ISSUE THREAD

**Issue by Rohi-spark** [quarkusio/quarkus#45060]
### Describe the bug

After upgrading the quarkus in azure container app - one of the container throwing error - Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.core.LoggerContext [in thread "main"].

### Output of `java -version`

openjdk 21.0.5

### Quarkus version or git rev

3.17.3

**Comment by Rohi-spark** [comment]
@geoand Kindly let me know what details you need?

**Comment by geoand** [comment]
If you could provide an entire sample application that shows the error in action, that would be best

**Comment by gsmet** [comment]
I will close this as I'm pretty sure it's not related to this repository itself.

It might be something wrong in the dependency tree or something related to some other extensions but I don't see how it could be related to the core of Quarkus.

If you find out I'm wrong, please reopen the issue with a reproducer. Thanks!
