### ISSUE TITLE
BindException is not logged on startup in dev mode

### ISSUE THREAD

**Issue by rodcheater** [quarkusio/quarkus#45079]
### Describe the bug

I have a load-on-startup servlet which throws a bind exception when it can’t connect to a remote service. When launching in dev mode, this exception is not logged.

### Expected behavior

All exceptions from servlet startup are logged.

### Actual behavior

Bind exceptions are not logged. The app looks like it has hung.

### How to Reproduce?

Reproducer: [quarkus-reproducer.zip](https://github.com/user-attachments/files/18104972/quarkus-reproducer.zip)

**Steps to reproduce**

1. Run in dev mode: `./gradlew quarkusDev`

Note that after changing the type of thrown exception it is logged as expected.

### Output of `uname -a` or `ver`

Darwin Rods-MacBook-Pro.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:23 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

openjdk version "21.0.5" 2024-10-15 OpenJDK Runtime Environment Homebrew (build 21.0.5) OpenJDK 64-Bit Server VM Homebrew (build 21.0.5, mixed mode, sharing)

### Quarkus version or git rev

3.17.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.9

**Comment by geoand** [comment]
Thanks for reporting.

Although it would be possible to provide a fix for this, I would however suggest not using `BindException` as Quarkus interprets that as an actual inability to bind to the HTTP port  and tries to suggest users how to fix it.
