### ISSUE TITLE
quarkus.test.native-image-profile seems to be not reflected with Quarkus main

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#45083]
### Describe the bug

`quarkus.test.native-image-profile` seems to be not reflected with Quarkus main

security-openid-connect-client-quickstart is failing and it uses this property in https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-openid-connect-client-quickstart/src/main/resources/application.properties#L14 to control port number

security-openid-connect-client-quickstart works well with Quarkus 3.17.4

When native binary is executed in the test `INFO  [io.quarkus] (main) Profile prod activated.` appears in the log

`WARN  [io.qua.run.con.ConfigRecorder] (main) The profile 'prod' used to build the native image is different from the runtime profile 'test'. This may lead to unexpected results.` is the thing that should appear in the log as `quarkus.test.native-image-profile=test` is set in the application properties

### Expected behavior

security-openid-connect-client-quickstart passes with Quarkus main

### Actual behavior

security-openid-connect-client-quickstart fails with Quarkus main, `prod` mode is used in execution and `quarkus.test.native-image-profile=test` is not reflected

### How to Reproduce?

Make sure GraalVM or Mandrel is available, e.g. using `sdk use java 23.1.5.r21-mandrel`
Run
```
git clone https://github.com/quarkusio/quarkus-quickstarts -b development
cd quarkus-quickstarts/security-openid-connect-client-quickstart
#FAIL
mvn clean verify -Dnative -Dquarkus.platform.version=999-SNAPSHOT
#PASS
mvn clean verify -Dnative -Dquarkus.platform.version=3.17.4
```

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus main fc237a6007d

**Comment by rsvoboda** [comment]
CC @sberyozkin

**Comment by sberyozkin** [comment]
Hi @rsvoboda Thanks, @gsmet pinged me about it, and pointed out that it started failing about 4 days back from 9th Dec, I had a look at commits and could not find anything obvious in the commit history... 
I have to admit I'm not sure where in the Quarkus code I should look atround, so I'd appreciate some guidance where to start looking further, let me CC @geoand, @radcortez. My only idea right now, is to check if using `@TestHttpResource` annotation can do better

**Comment by sberyozkin** [comment]
OK, the plan is to go via https://github.com/quarkusio/quarkus/commits/main/test-framework, and try to narrow down something :-)

**Comment by rsvoboda** [comment]
@sberyozkin QS started to fail on Dec 6th
 - https://github.com/quarkusio/quarkus-quickstarts/actions/workflows/native-build-development.yml
 - last passing: https://github.com/quarkusio/quarkus-quickstarts/actions/runs/12172072155
 - first failed: https://github.com/quarkusio/quarkus-quickstarts/actions/runs/12191800548

**Comment by rsvoboda** [comment]
I found it, it's caused by https://github.com/quarkusio/quarkus/commit/a47ad6055f593f25b6c3c8810625ae889b1b3765

cc @sberyozkin @gsmet @radcortez

**Comment by sberyozkin** [comment]
Hey @rsvoboda Thanks a million, as I haven't got to it yet.

Thanks @radcortez, good news it is on `main` only :-)
