### ISSUE TITLE
Make cancellation handler for async requests configurable in quarkus-rest

### ISSUE THREAD

**Issue by us766** [quarkusio/quarkus#45141]
### Description

Based on this PR [#41710](https://github.com/quarkusio/quarkus/pull/41710) in Quarkus 3.13, cancellation handler for async requests has been added for `quarkus-rest` extension. With this change when client cancels a request, the processing pipeline receives a cancellation event. This change is breaking some parts of existing REST APIs.

Considering that issue [#41776](https://github.com/quarkusio/quarkus/issues/41776) describes a similar behavior for `Multi` subscription on gRPC calls and remains open, could these changes in behavior be configurable, or could an annotation be introduced to enable the previous behavior?

Preserving the old behavior by making these changes configurable would allow security updates and platform version bumping without forcing changes on the logic for adopting the new behavior (even though it is the correct one).

**Comment by geoand** [comment]
I think we could have some special annotation that control the behavior.

@cescoffier WDYT?

**Comment by cescoffier** [comment]
Yes, but cancellation should be the default.

**Comment by geoand** [comment]
Definitely

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/45144
