### ISSUE TITLE
ArC: make it possible to activate the session context for a specific business method in a test

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#45146]
### Description

Currently, it's not possible to test a `@SessionScoped` component used in a WS Next app outside the real websocket communication. That is quite limiting.

### Implementation ideas

We could provide an annotation similar to `@jakarta.enterprise.context.control.ActivateRequestContext`.

**Comment by mkouba** [comment]
Hm, I think that we should move the logic from [WebSocketSessionContext](https://github.com/quarkusio/quarkus/blob/main/extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSessionContext.java) into ArC because it does not contain anything WS Next-specific. It's actually almost identical to `io.quarkus.arc.impl.RequestContext`. So maybe we could also extract the logic in an abstract superclass.

**Comment by manovotn** [comment]
> Hm, I think that we should move the logic from [WebSocketSessionContext](https://github.com/quarkusio/quarkus/blob/main/extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSessionContext.java) into ArC because it does not contain anything WS Next-specific. It's actually almost identical to `io.quarkus.arc.impl.RequestContext`. So maybe we could also extract the logic in an abstract superclass.

Wouldn't that lead to a possible conflict with Undertow extension impl of `@SessionScoped`?

**Comment by manovotn** [comment]
> The plan is to only register the activating binding/interceptor for tests. And obviously, the interceptor should do nothing if the context is already active.

Got it; in that case, it should be perfectly fine 👍
