### ISSUE TITLE
MP Config TCK - Fix excluded tests

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#4516]
Currently, the below tests are excluded from execution when running the MP Config TCK. We need to either fix Quarkus so the test passes or challenge and fix the TCK if it's a problem there.

- [x] [ArrayConverterTest.*](https://github.com/quarkusio/quarkus/blob/master/tcks/microprofile-config/tck-suite.xml#L17)
- [ ] [ConfigProviderTest.testInjectedConfigSerializable](https://github.com/quarkusio/quarkus/blob/master/tcks/microprofile-config/tck-suite.xml#L26)
- [x] [ConfigProviderTest.testPropertyConfigSource](https://github.com/quarkusio/quarkus/blob/master/tcks/microprofile-config/tck-suite.xml#L28)
- [x] [ConfigProviderTest.testEnvironmentConfigSource](https://github.com/quarkusio/quarkus/blob/master/tcks/microprofile-config/tck-suite.xml#L36)

**Comment by kenfinnigan** [comment]
@dmlloyd @jmesnil I was taking a look at `ConfigProviderTest.testPropertyConfigSource` this afternoon and I'm not sure if the behavior is a problem with us or the TCK.

Basically the test iterates over system properties and verifies that the values from `System.getProperties()` are the same as `config.getValue()` retrieved from the system property config source.

What's weird is that the value for `env.MAVEN_CMD_LINE_ARGS` contains a leading space in the value when coming from the ConfigSource but doesn't from `System.getProperties()` in the test class, even though the ConfigSource uses `System.getProperty()` inside.

Any thoughts?

**Comment by dmlloyd** [comment]
There's an actual property called `env.MAVEN_CMD_LINE_ARGS`?  If so, we're not setting that AFAIK; Maven must be.  And perhaps they're inserting a leading space then?

**Comment by kenfinnigan** [comment]
I believe it's set by Maven.

I'm just confused how accessing it directly through system properties, and through system properties in the config source, lead to one having a leading space and one not

**Comment by dmlloyd** [comment]
Is there a log output I could look at without having to build everything?

**Comment by kenfinnigan** [comment]
Will run the test and capture it for you

**Comment by kenfinnigan** [comment]
@dmlloyd here's the output from running the single test method: https://gist.github.com/kenfinnigan/ede49a21fd7f144f7d58c65e29b295cc

**Comment by dmlloyd** [comment]
Hmm that's pretty strange.  I think we can rule out SmallRye Config though because that call path would just be `System.getProperty`.

**Comment by kenfinnigan** [comment]
Well I guess that's good, but I'm really confused as to how `System.getProperty` returns different values for that one key on the same system at the same time

**Comment by dmlloyd** [comment]
I think it's not `getProperty`.

Here's one hypothesis, which might be a little crazy but it's all I can think of that makes sense: Maven copies all the system and env properties into the Maven property map.  They somehow munge the whitespace at that time.  Or, at a later point, they set that property by hand for some reason.  Then we haplessly copy the build system properties in as a configuration source (we have one for the build system's properties), somehow including that property despite it not being within our namespace.

**Comment by kenfinnigan** [comment]
So you think we shouldn't be copying any property that doesn't begin `QUARKUS`?

**Comment by dmlloyd** [comment]
The intent for that code was in fact to only copy build system properties that started with `quarkus.`.  But I can't think of any other place it could have gone wrong, without attaching a debugger (I'm in the middle of a bunch of code changes so that isn't really a convenient option at this point).

**Comment by kenfinnigan** [comment]
That's fine, I can dig in to see if I can discover why we're reading more than needed.

Might be a key needs to be passed to SRye Config, maybe

**Comment by kenfinnigan** [comment]
@dmlloyd so I figured out what's going on with the system properties.

`ExpandingConfigSource` when it creates the expression compiler, doesn't set a flag for "no trim", which means the value is trimmed. Which leads to our mismatch.

Is it ok to add a no trim flag to the expression creation?

**Comment by dmlloyd** [comment]
Sure, that should be fine.

**Comment by kenfinnigan** [comment]
@dmlloyd `ConfigProviderTest.testInjectedConfigSerializable` fails because `Expression` isn't serializable.

Does it make sense to make it serializable in SmallRye Common and switch Quarkus to use that instead of WF common? Are the two "identical" enough to do that?

**Comment by dmlloyd** [comment]
It might be easier to make the `ExpandingConfigSource` properly serializable by way of `writeReplace`/`readResolve` to reconstruct an empty cache.  We don't really want to serialize the cache in any event.
