### ISSUE TITLE
MP Metrics TCK - Fix excluded tests

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#4518]
Currently, the below tests are excluded from execution when running the MP Metrics TCK.

- [ ] [GlobalTagsTest](https://github.com/quarkusio/quarkus/blob/master/tcks/microprofile-metrics/api/pom.xml#L36)

**Comment by jmartisk** [comment]
GlobalTagsTest is not working due to https://github.com/quarkusio/quarkus/issues/4512

**Comment by jmartisk** [comment]
I just verified that after the config update (merged) and updating the MP Metrics API to 2.2.1-RC2 (locally) the TCKs pass. I will get Metrics 2.2.1 released and send a PR.
