### ISSUE TITLE
Uber-Jar file name suffix issue for disabling it

### ISSUE THREAD

**Issue by jjpinto** [quarkusio/quarkus#45204]
### Describe the bug

There is a problem regarding the configuration for disabling the runner suffix in the generated uber JAR file in Quarkus documentation.

The documentation states:

"By default the generated uber JAR file name will have the -runner suffix, unless it was overridden by configuring a custom one with quarkus.package.runner-suffix configuration option. If the runner suffix is not desired, it can be disabled by setting quarkus.package.jar.add-runner-suffix configuration option to false, in which case the uber JAR will replace the original JAR file generated by maven-jar-plugin for the application module."

However, the correct configuration option is <quarkus.package.add-runner-suffix>false</quarkus.package.add-runner-suffix>. The quarkus.package.jar.add-runner-suffix option does not work as described.

[There is an issue in the Quarkus documentation ](https://quarkus.io/guides/maven-tooling#uber-jar-file-name-suffix)

### Expected behavior

Documentation needs to be updated.
<quarkus.package.add-runner-suffix>false</quarkus.package.add-runner-suffix>

### Actual behavior

Follow the documentation to disable the runner suffix using quarkus.package.jar.add-runner-suffix=false.
Build the project and observe that the runner suffix is still present in the uber JAR file name.

### How to Reproduce?

mvn clean package

### Output of `uname -a` or `ver`

Linux L91PLPG3 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "22.0.1" 2024-04-16

### Quarkus version or git rev

3.16.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)

**Comment by geoand** [comment]
Would you like to add a PR with the change you propose?

**Comment by jjpinto** [comment]
> Would you like to add a PR with the change you propose?

Ok, will do that.

**Comment by jjpinto** [comment]
Added: https://github.com/quarkusio/quarkus/pull/45205

**Comment by jedla97** [comment]
Isn't problem somewhere else? The https://quarkus.io/guides/all-config have only `quarkus.package.jar.add-runner-suffix` property and we have test for it in integration tests [PackageIT.java#L218](https://github.com/quarkusio/quarkus/blob/main/integration-tests/maven/src/test/java/io/quarkus/maven/it/PackageIT.java#L218)

Maybe https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigCompatibility.java#L402 ?

**Comment by geoand** [comment]
Oops, I totally misread the change

**Comment by jjpinto** [comment]
It makes sense now! Thanks @jedla97

**Comment by jjpinto** [comment]
@gsmet the issue was created because the uber-jar parameter wasn't working. I later found out that the parameter had a new path added in Quarkus 3.10+, but not in earlier versions. @jedla97 provided documentation stating the changes, so the .jar was included, and the issue is now closed.
