### ISSUE TITLE
encoding problems in console of IntelliJ IDEA 2024 (Community Edition)

### ISSUE THREAD

**Issue by lizhou828** [quarkusio/quarkus#45229]
### Describe the bug

when I using log some words with Chinese , the words in log file  is normal , but  console of IntelliJ IDEA print  some messy words ....
![Image](https://github.com/user-attachments/assets/bd52ec69-1ab7-417b-8939-54fbe01bfe08)

### Expected behavior

when I using log some words with Chinese ,  not only the words in log file  is normal , but  alose console of IntelliJ IDEA print  normal words ....

### Actual behavior

 console of IntelliJ IDEA print chinese words to  some messy words ....

### How to Reproduce?

i uploaded the project , my project source code is  here:
https://github.com/lizhou828/quarkus/blob/main/quarkus-helloworld.rar
![Image](https://github.com/user-attachments/assets/cc9df14c-d7ea-40be-a64c-a78c640bc51d)

1、run the project with "mvn compile quarkus:dev" in  IntelliJ IDEA

2、access the url "http://localhost:9000/" then check the log file  and console log info

3、 you will see the  words in log file  is normal  encoding, but console of IntelliJ IDEA print  some messy words ....

### Output of `java -version`

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37, mixed mode, sharing)

### Quarkus version or git rev

Quarkus version 3.13.0    git version 2.44.0.windows.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

C:\Users\liz>mvn -version Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: E:\Program Files\apache-maven-3.9.6 Java version: 21.0.3, vendor: Oracle Corporation, runtime: D:\ProgramFiles\graalvm-jdk-21_windows-x64_bin\graalvm-jdk-21.0.3+7.1 Default locale: zh_CN, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

my project source code is  here:

https://github.com/lizhou828/quarkus/blob/main/quarkus-helloworld.rar
![Image](https://github.com/user-attachments/assets/cc9df14c-d7ea-40be-a64c-a78c640bc51d)

**Comment by yuhaibohotmail** [comment]
Most likely this is not a quarkus problem, but an environment problem. Please carefully check the character set settings of your operating system, the character set of your Java code, etc.
Please refer to:
[https://github.com/quarkusio/quarkus/issues/44569](url)

**Comment by lizhou828** [comment]
> Most likely this is not a quarkus problem, but an environment problem. Please carefully check the character set settings of your operating system, the character set of your Java code, etc. Please refer to: [#44569](https://github.com/quarkusio/quarkus/issues/44569)

when i chose this this beta version(using Unicode UTF-8) ，then restart my computer ,  the log info in IDEA Console is normal ,  thanks you !!! 

![Image](https://github.com/user-attachments/assets/a1759347-2e62-40fa-a745-52febc31d9f4)

![Image](https://github.com/user-attachments/assets/ad64a27f-ec65-4df8-9e1c-bb68db029a5a)
