### ISSUE TITLE
Review HttpPermissionChecker priority mechanism 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4523]
**Description**
`HttpPermissionChecker` requires the implementations to set a priority. 
 The possible problem is that it complicates the process. 
**Implementation ideas**

Proposal: in scope of the security checks, every checker must have an equal chance to assert if the current request is allowed to proceed or not (based on possibly orthogonal requirements) and as such the use of the priorities should become redundant. The authors of these checkers should not be concerned about the ordering of their checks within a bigger sequence of checks. The first failing check will end the whole sequence of checks, but for the request to proceed all checks must give their `+1`
The checkers, as opposed to for example JAX-RS filters, have no 'side-effects'.

**Comment by sberyozkin** [comment]
Hi @stuartwdouglas, @gsmet I'll add `0.25.0` just to make sure this issue is resolved somehow: keep the interface as it is now or might be without the priorities, since after 0.25.0 it won't be really an option to change the interface...

**Comment by dmlloyd** [comment]
The key question is: are there any significant use cases that are difficult or impossible to solve without the "tri-state" logic that is enabled specifically by the order/priority approach?

**Comment by sberyozkin** [comment]
@dmlloyd 
Hi David, thanks for the fast feedback. I'd say all cases can probably be handled with the priority approach, but my concern is that for the security checks, I believe all of them have to run, so it is not clear to me why to sort them.
Perhaps having a `default` `getPriority` method can be a good compromise. If there will be some real requirement to have the checks in the specific order then the implementations would provide their own priority value...In most cases they'd likely need to know about the priority at all.
For example, Keycloak checker will enforce its policies, while the custom OIDC checker will enforce some claim content: both have to run

**Comment by dmlloyd** [comment]
They would all have to run only if the rule is that all checks have to explicitly pass.  I thought @stuartwdouglas had proposed that checks should be able to either explicitly pass, explicitly fail, or delegate the decision to the next handler - meaning that any handler would have the power to preemptively approve the request without consulting the rest of the handlers.

So my question is basically, *why* would we want to allow a handler to preemptively approve a request?  Is it to satisfy a use case?  If there is no such use case, then I agree that checks should all be required to pass in order to approve a request, and that order should not matter.

Of course it's possible I've completely misunderstood what was being proposed, in which case: sorry for the noise!

**Comment by sberyozkin** [comment]
@dmlloyd It is very helpful; that was my concern I commented about in the PR, if a checker can preemptively approve by design then there will always be a risk of some major check being ignored. It appears to me that the correct ordering, if it is really needed, can only be reliably set up at the custom checker level :-) but not via the generic properties mechanism; thanks

**Comment by stuartwdouglas** [comment]
The main use case is 'default deny' which is not really possible with pure boolean logic. At the moment this works more like an access control list. 

Maybe I could leave it as tri state, but record the results of every checker. If all 'IGNORE' then the default is used, if any return DENY then it will be denied. If at least one has permitted and the rest IGNORE then it will be permitted.

**Comment by dmlloyd** [comment]
How does that differ from the boolean approach in practice? What I meant by "use case" is some user situation that wouldn't be solvable with the simpler boolean approach.

**Comment by sberyozkin** [comment]
The checkers would still return the status (ignore/deny/permit) so the recording suggested by Stuart will support all the variations; 
Simple boolean logic should work too, though the checkers which ignore have to return 'permit'; or yes, I think I see what Stuart meant, if all ignore, then the code which decides what to do will only see permit (true) so no way to decide if it is either default permit or default deny.
So recording the results of all the checkers should work, unless I'm missing something :-)
