### ISSUE TITLE
ClassNotFoundException when using REST clients inside Kotlin coroutines with Quarkus v3.9+

### ISSUE THREAD

**Issue by snitish2607** [quarkusio/quarkus#45252]
### Describe the bug

I am trying to upgrade from Quarkus version 3.8.4 -> 3.15.2 and I'm facing the an issue when using REST clients inside a Kotlin coroutine launch block (`CoroutineScope(Dispatchers.IO).launch`). 

When calling an API from within a launch block, a ClassNotFoundException is being thrown. The same did not occur in Quarkus version 3.8 and below. This occurs due to a mismatch in Quarkus classloaders:

 ![Image](https://github.com/user-attachments/assets/827b399d-2d5d-4a96-9dc2-fa843ce0ed9c)

As seen in the above image, the classloader outside the coroutine (Marked as outside classloader) is different from the classloader inside the coroutine (Marked as inside classloader). The class loader inside the coroutine does not recognise the REST client generated class files.

I'm aware of existing issues pointing out a similar issue:
1.  https://github.com/quarkusio/quarkus/issues/41349
2. https://github.com/quarkusio/quarkus/issues/40245 (Workaround given)
3. https://github.com/quarkusio/quarkus/issues/42219

In the above issues, I'm unable to identify the issues have been fixed or not since I see some as "Closed" but I still do see the issue reproducing. In the attached zip file to reproduce the issue, I have the following code: 

```
 // This method will be triggered on application startup to set the proper class loader
    fun onStart(@Observes ev: StartupEvent) {
        // Capture the current thread's context class loader
        properTccl = Thread.currentThread().contextClassLoader
        println("properTccl set: $properTccl")
    }

    /**
     * Generic function to execute REST client calls asynchronously.
     * The `call` lambda should contain the actual REST client method to be executed.
     */
    suspend fun <T> executeRestClientCall(call: suspend () -> T): T {

        return withContext(Dispatchers.IO) {
            // Ensure the correct class loader context
            Thread.currentThread().contextClassLoader = properTccl

            // Execute the provided suspend function
            call()
        }
    }
```

This workaround allows me to run REST client API calls from within a coroutine launch block. **I would like to know if this is the only way to do this for now or there's something else?**

Additionally, I'd like to mention that this issue only occurs in dev mode and not when running the packaged .jar 

### Expected behavior

In this case, the exepcted behavior is that the functions inside the coroutine scope run as expected and give the output

> [Extension(id=io.quarkus:quarkus-rest-client, name=REST Client, shortName=rest-client-reactive, keywords=[call, rest, reactive, quarkus-rest-client, web, web-client, rest-client, resteasy-reactive, client, microprofile-rest-client, services, rest-client-reactive])]

This is what is happening when using the API endpoint `http://localhost:8090/hello/test2`

However, this call is made using the temporary workaround `(As seen in file RestClientExecutor.kt)` described in https://github.com/quarkusio/quarkus/issues/40245

### Actual behavior

When calling the API `http://localhost:8090/hello/test1`, the REST client API call is made within a Kotlin coroutine launch block and it throws the following error:

> Exception in thread "DefaultDispatcher-worker-1" jakarta.enterprise.inject.CreationException: java.lang.ClassNotFoundException: org.acme.serviceClients.MyRemoteService
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_Bean.create(Unknown Source)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_Bean.create(Unknown Source)
>         at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
>         at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c9(Unknown Source)    at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
>         at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
>         at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_ClientProxy.arc$delegate(Unknown Source)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_ClientProxy.getExtensionsById(Unknown Source)
>         at org.acme.GreetingResource$doSomething$2.invokeSuspend(GreetingResource.kt:33)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
>         at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
>         at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
>         Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4f7d10fa, Dispatchers.IO]
> Caused by: java.lang.ClassNotFoundException: org.acme.serviceClients.MyRemoteService
>         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:542)
>         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
>         at java.base/java.lang.Class.forName0(Native Method)
>         at java.base/java.lang.Class.forName(Class.java:467)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper.<init>(Unknown Source)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_Bean.doCreate(Unknown Source)
>         ... 20 more

### How to Reproduce?

[code-with-quarkus-testing.zip](https://github.com/user-attachments/files/18229988/code-with-quarkus-testing.zip)

1. Run the application using mvn compile quarkus:dev
2. Call API http://localhost:8090/hello/test1 for the error case
3. Call API http://localhost:8090/hello/test2 for the workaround case

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.4602]

### Output of `java -version`

openjdk version "17.0.12" 2024-07-16 OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7) OpenJDK 64-Bit Server VM Temurin-17.0.12+7 (build 17.0.12+7, mixed mode, sharing)

### Quarkus version or git rev

3.17.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937) Maven home: C:\Users\xxx\.m2\wrapper\dists\apache-maven-3.9.9-bin\33b4b2b4\apache-maven-3.9.9 Java version: 17.0.8, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17 Default locale: en_IN, platform encoding: Cp1252 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
> This workaround allows me to run REST client API calls from within a coroutine launch block. I would like to know if this is the only way to do this for now or there's something else?

As mentioned in https://github.com/quarkusio/quarkus/issues/40245#issuecomment-2076907560, it is the way to use it.

**Comment by snitish2607** [comment]
I modified my code to as such:

Controller and Service method:
```
    @GET
    @Path("test1")
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun test1(): String {
        doSomething()
        return "Hello from Quarkus REST"
    }

    suspend fun doSomething() {
        CoroutineScope(Dispatchers.IO).launch {
            println(myRemoteService.getExtensionsById("io.quarkus:quarkus-rest-client"))
        }
    }
```

REST client Interface:
```
    @GET
    @Path("/extensions")
    suspend fun getExtensionsById(@QueryParam("id") id: String): Set<Extension>
```
(Updated code: [updated-code-with-quarkus-testing.zip](https://github.com/user-attachments/files/18236176/updated-code-with-quarkus-testing.zip))

I still get a similar error:

> Exception in thread "DefaultDispatcher-worker-1" jakarta.enterprise.inject.CreationException: java.lang.ClassNotFoundException: org.acme.serviceClients.MyRemoteService
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_Bean.create(Unknown Source)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_Bean.create(Unknown Source)
>         at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
>         at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c5(Unknown Source)    at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
>         at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
>         at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_ClientProxy.arc$delegate(Unknown Source)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_ClientProxy.getExtensionsById(Unknown Source)
>         at org.acme.GreetingResource$doSomething$2.invokeSuspend(GreetingResource.kt:31)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
>         at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
>         at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
>         Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2569d430, Dispatchers.IO]
> Caused by: java.lang.ClassNotFoundException: org.acme.serviceClients.MyRemoteService
>         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:542)
>         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
>         at java.base/java.lang.Class.forName0(Native Method)
>         at java.base/java.lang.Class.forName(Class.java:467)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper.<init>(Unknown Source)
>         at org.acme.serviceClients.MyRemoteService$$CDIWrapper_Bean.doCreate(Unknown Source)
>         ... 20 more


@geoand Am I missing something? Is this what you mean by "returning a suspend function in REST Client interface" or you'd like me to implement it in a different way?

**Comment by geoand** [comment]
If your REST Client interface already returns a suspend function, what's the use case for using it the way currently are?

**Comment by snitish2607** [comment]
I'm trying to trigger multiple workflows in a single function that will asynchronously. For exmaple, I want to do some file conversions. I want the various file conversion workflow to be spinned off in a seperate Coroutine (each with its own timeout) so that the function flow isn't blocked. Here's a really simple code breakdown of what I'd like to do:

```
    suspend fun triggerConversion() {

        //Trigger conversion in a coroutine to avoid blocking the function flow
        CoroutineScope(Dispatchers.IO).launch {

            //Wrap the conversion functions in a withTimeout block to avoid long running tasks
            withTimeout(10000) {
                doConversionOne() // REST Client API call one
                doConversionTwo() // REST Client API call two
            }
        }
        // Do other DB updates
        // ...
    }
```

As per your suggestion, I converted both `doConversionOne` and `doConversionTwo` to suspend methods and I'm seeing the error mentioned in my previous comment.

**Comment by snitish2607** [comment]
@geoand Reminder for the above comment. Just in case you've missed it. TIA!

**Comment by snitish2607** [comment]
@geoand I had a look at the file you mentioned above. I see that there is code to store the original classloader and later reuse it when invoking coroutines. This should prevent the error that I'm seeing since I see this from v3.9.x onwards and I'm on 3.17.4. However, I'm still getting the error and I'd need more help on this.

I'd like to know if this is a known issue for now and if it is expected that the workaround is the norm or if there's a another correct way to bypass this?

**Comment by snitish2607** [comment]
@geoand Reminder for the above comment. Thanks for taking your time!
