### ISSUE TITLE
Gradle Model build failure with Java 21

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#45279]
### Describe the bug

I keep getting
```
[INFO] --- impsort:1.12.0:sort (sort-imports) @ quarkus-gradle-model ---
[INFO] Loaded from the build cache, saving 0.287s
[INFO] 
[INFO] --- exec:3.1.0:exec (gradle) @ quarkus-gradle-model ---
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.12/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':gradle-application-plugin'.
> Could not resolve all dependencies for configuration 'classpath'.
   > Could not resolve project :build-logic.
     Required by:
         project :gradle-application-plugin
      > Failed to calculate the value of task ':build-logic:compileJava' property 'javaCompiler'.
         > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=17, vendor=any vendor, implementation=vendor-specific} for LINUX on x86_64.
            > No locally installed toolchains match and toolchain download repositories have not been configured.

* Try:
> Learn more about toolchain auto-detection at https://docs.gradle.org/8.12/userguide/toolchains.html#sec:auto_detection.
> Learn more about toolchain repositories at https://docs.gradle.org/8.12/userguide/toolchains.html#sub:download_repositories.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
```

### Output of `java -version`

Java 21

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven version: 3.9.8

**Comment by Eng-Fouad** [comment]
Try adding this to `settings.gradle.kts`:

```
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version("0.9.0") // https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver-convention
}
```

**Comment by gsmet** [comment]
You need to have a Java 17 available that is resolvable by the Gradle resolver.

Personally, I now use SDKMAN! to manage my JDKs and it seems fine.

BTW, let's avoid adding the bug label for things that are not really bugs in the software itself.

**Comment by sberyozkin** [comment]
@gsmet So now, anyone who we ask to contribute and who are at newer JDKs must deal with JDK 17 resolution?
IMHO it is a poor experience,  this should be at least documented

**Comment by Eng-Fouad** [comment]
> [@gsmet](https://github.com/gsmet) So now, anyone who we ask to contribute and who are at newer JDKs must deal with JDK 17 resolution? IMHO it is a poor experience, this should be at least documented

[Foojay Toolchains Plugin](https://github.com/gradle/foojay-toolchains) is an official Gradle plugin that will download the required JDK locally if it is not available.

**Comment by gsmet** [comment]
Well, feel free to document it if you think it's needed.

Keep in mind Java 17 is our base JDK so I wouldn't say that's surprising you need Java 17 around.

And while @Eng-Fouad 's suggestion might be practical for user applications, I don't think our build should download random JDKs by itself.

**Comment by sberyozkin** [comment]
@gsmet I was able to build Quarkus with Java 21, without this failure. I have Java17 around,  in case I need it, but I didn't not have to use any managers.

**Comment by sberyozkin** [comment]
@gsmet SDKMAN helped, thanks for the hint. 

@Eng-Fouad Thanks for trying to help, but indeed, I'll stick with SDKMAN :-)

Thanks
