### ISSUE TITLE
Eclipse workspace is impacted by quarkus-devtools-base-codestarts

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#45283]
### Describe the bug

Apologies if it is not a bug but I'm really struggling with this one. The moment I run any test from the command line, The Eclipse workspace gets broken, which is only fixed by removing:

```
rm ~/.m2/repository/io/quarkus/quarkus-devtools-base-codestarts/999-SNAPSHOT/quarkus-devtools-base-codestarts-999-SNAPSHOT.jar
```

But then I can't start the test again because this dependency is longer available, so I have to rebuild.
Then I run the test and the cycle starts repeating.

**Comment by gsmet** [comment]
It would be interesting to have a look at what's in the jar when it's broken and compare to what's in the jar when it works.

**Comment by sberyozkin** [comment]
I'll check.

**Comment by sberyozkin** [comment]
@gsmet Let me close as it may be related to the outdated workspace, repository or Eclipse version.
If it happens again then I'll re-open with more details, sorry for the noise
