### ISSUE TITLE
Direct fluentd integration

### ISSUE THREAD

**Issue by n1hility** [quarkusio/quarkus#453]
Currently we have the JSON output formatter, and the ability to send to a socket, but we should look into how we can either make that an optimal integration with simple config, or look at a direct fluent handler.

**Comment by ia3andy** [comment]
JSON formatter is now available for console logging on master (target: 1.1.0).

**Comment by loicmathieu** [comment]
Sending logs to Fluentd is documented using both logging-gelf extension (needs EFK): https://quarkus.io/guides/centralized-log-management#send-logs-to-fluentd-efk and the syslog appender: https://quarkus.io/guides/centralized-log-management#fluentd-alternative-use-syslog

So I'm closing this one now.
