### ISSUE TITLE
Running a quarkus application with debug mode does not suspend the vm

### ISSUE THREAD

**Issue by tmplcl** [quarkusio/quarkus#4532]
When running a quarkus application with maven and the debug property as described in [https://quarkus.io/guides/maven-tooling#debugging](url) the vm does not wait for a debugger to attach.

**Expected behavior**
The VM should be suspended until a debugger is attached.

**Actual behavior**
The application starts without suspending the VM.

**To Reproduce**
1. Create simple quarkus application:
<pre><code>mvn io.quarkus:quarkus-maven-plugin:0.24.0:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"</code></pre>
2. Run the application in dev mode with maven debug property:
<pre><code>./mvnw compile quarkus:dev -Ddebug=true</code></pre>
3. Check is application is running:
<pre><code>wget localhost:8080/hello</code></pre>

**Environment:**
 - Output of `uname -a` or `ver`:
> Linux tmplcl-Virtual-Machine 5.0.0-31-generic #33-Ubuntu SMP Mon Sep 30 18:51:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
 - Output of `java -version`: 
> openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-20190711120915.buildslave.jdk8u-src-tar--b08)
OpenJDK 64-Bit GraalVM CE 19.2.0.1 (build 25.222-b08-jvmci-19.2-b02, mixed mode)
 - Quarkus version or git rev: 0.24.0

**Additional context**
Same behaviour with OpenJDK: 11 and 13

**Comment by jaikiran** [comment]
This looks like because of hte change I recently did https://github.com/quarkusio/quarkus/pull/4395. For now, you can additionally pass `-Dsuspend=true` to have the VM suspended when `-Ddebug=true`. I'll submit a PR tomorrow, to have `-Ddebug=true` behave like it used to before.

**Comment by geoand** [comment]
I am little lost with the change to `-Ddebug`. It was my understanding that that the fact that it no longer suspends was intentional. 
Is that not the case?

**Comment by jaikiran** [comment]
When I did that change I was only thinking about the port override and hadnt considered changing the debug=true case. But I think the current behaviour of letting suspend decide whether or not to suspend, I guess, makes it more consistent. We will have to fix our documentation about it.

**Comment by geoand** [comment]
Yes, let's at least have some documentation

**Comment by jaikiran** [comment]
Documentation has now been updated https://github.com/quarkusio/quarkus/pull/4596. I think we can close this one now.

**Comment by gsmet** [comment]
Thanks everyone!
