### ISSUE TITLE
Create a BodyHandleBuildItem to share vert.x body handler

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#4536]
**Description**
In camel-quarkus we programatically attach a route to quarkus' vertx router and we have to manually configure the body handler as you can see [here](https://github.com/apache/camel-quarkus/blob/master/extensions/platform-http/runtime/src/main/java/org/apache/camel/quarkus/component/platform/http/runtime/QuarkusPlatformHttpConsumer.java#L94-L129) but it would be nice to re-use the body handler currently attached to auto discovered routes.

**Implementation ideas**
Create a `BodyHandleBuildItem` we can reuse from camel-quarkus

**Comment by cescoffier** [comment]
@lburgazzoli the body handler should always be there no? 
In that case, you can retrieve the body from the routing context.

**Comment by lburgazzoli** [comment]
For what I can see the body handler is attached on per route basis:

- https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/VertxWebProcessor.java#L142
- https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/VertxWebRecorder.java#L69

Am I wrong ?
