### ISSUE TITLE
MediatorManager was already initialized!

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#4540]
**Describe the bug**

Hot reload does not work anymore with 0.24.0

**Expected behavior**

It should work

**Actual behavior**

MediatorManager was already initialized!

**Comment by geoand** [comment]
Oh darn!

What kind of error does it throw?

**Comment by machi1990** [comment]
> Hot reload does not work anymore with 0.24.0

Just a general question, do we have CI setup for a release branches/tags? @cescoffier @geoand

**Comment by geoand** [comment]
WDYM  @machi1990 ?

**Comment by geoand** [comment]
@cescoffier I couldn't reproduce this with `master` and the `kafka-quickstart`

**Comment by machi1990** [comment]
Is this reproducible with current master? I was just curious if we (re)run  CI jobs on release branches or just before releases with the test suite that we already have in the master branch.

**Comment by cescoffier** [comment]
I need to do further investigation.
It was probably related to the web socket issue.

**Comment by stuartwdouglas** [comment]
@cescoffier can this be closed?

**Comment by cescoffier** [comment]
Oh yes, that has been fixed a very long time ago...
