### ISSUE TITLE
Datasource configuration wrong in docs?

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#4543]
**Describe the bug**

I think that this https://github.com/quarkusio/quarkus/pull/4462/files#diff-339c141d88e1376f63c9e3d7e733b5adR284 properties should be `permissions` instead of `roles` as the datasource is defined as `permissions`.

**Comment by gwenneg** [comment]
From what I can see in [JdbcRecorder](https://github.com/quarkusio/quarkus/blob/master/extensions/elytron-security-jdbc/runtime/src/main/java/io/quarkus/elytron/security/jdbc/JdbcRecorder.java#L38-L39), `roles` is never used in the extension code, so its value doesn't really matter.

The link between the datasource and the query is done by `quarkus.security.jdbc.principal-query.roles.datasource=permissions`.

**Comment by gwenneg** [comment]
I'm closing this and removing the `bug` label since the doc seems to be ok. Do not hesitate to reopen the issue if you think there's something wrong.
