### ISSUE TITLE
Generate extension descriptor from `pom.xml`

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#4551]
Follow-up on #4539, it would be nice if we could generate the extension descriptor entirely from `pom.xml` properties, such as:

```
<project>
 ...
 <properties>
  <quarkus.extension.name>RESTEasy - Jackson</quarkus.extension.name>
  <quarkus.extension.labels>resteasy-jackson,jaxrs-json,resteasy-json,resteasy,jaxrs,json,jackson</quarkus.extension.labels>
 </properties>
...
</project>
```

**Comment by FroMage** [comment]
I don't think we should close this, right @aloubyansky ?

**Comment by aloubyansky** [comment]
I think it surely can be implemented. I'll leave it to you as the author of the issue to evaluate its worthiness :)
At this point, if no extra info is provided, the `name` will derived from the `pom.xml` or the artifactId https://github.com/quarkusio/quarkus/blob/master/independent-projects/bootstrap/maven-plugin/src/main/java/io/quarkus/maven/ExtensionDescriptorMojo.java#L156
The description is also taken from the pom.xml, unless provided from the outside.
However, the property-based approach as described in the summary above can also be added.

**Comment by gsmet** [comment]
I don't think we want to support several ways of doing the same thing.

We should decide and settle on one approach. TBH, I'm not a big fan of the extraction of the description of the pom.xml, I would have put all the metadata in the yaml file.

I think we should close this one and open another issue if at some point we decide on another approach.

**Comment by gastaldi** [comment]
+1 on @gsmet's comments above. Closing this
