### ISSUE TITLE
Unable to understand extension-authors-guide docs

### ISSUE THREAD

**Issue by dodalovic** [quarkusio/quarkus#4558]
Anyone knows what underlined thingy means? Taken from https://quarkus.io/guides/extension-authors-guide#some-types-of-extensions

![pasted_image](https://user-images.githubusercontent.com/6358061/66779810-73cd8300-eecf-11e9-948a-1186a8945074.png)

**Comment by gastaldi** [comment]
Yeah, that sentence is confusing, I think it should read: 
```
that will be executed at runtime and boot the framework
```

**Comment by dodalovic** [comment]
@gastaldi #4559

**Comment by cescoffier** [comment]
Merged!

Thanks @dodalovic !

**Comment by dodalovic** [comment]
@cescoffier The pleasure is whole mine!
