### ISSUE TITLE
Adjust memory and startup time numbers for 1.0 on website and presentations

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4560]
Let's adjust the memory usage for REST/REST+CRUD for both RSS and time to first request :

- on the website
- on slides

We need @stuartwdouglas to give the go before rerun (stable enough), @johnaohara to run the numbers and @jkbrock for both website new images and slides.

**Comment by johnaohara** [comment]
@stuartwdouglas are there any updates before 1.0.0.RC1 that I need to take into account or are we good ok ot verify/update numbers?

**Comment by emmanuelbernard** [comment]
@johnaohara Verify with The release happening Wednesday

**Comment by johnaohara** [comment]
@jkbrock I have sent an email with the figures

**Comment by jkbrock** [comment]
@johnaohara , I don't see it. did you send it to jbrock?

**Comment by johnaohara** [comment]
@jkbrock i did, forwarded again

**Comment by jkbrock** [comment]
Sorry, not sure how I missed it the first time. Thank you, @johnaohara

**Comment by jkbrock** [comment]
New images have been posted to the website and the master slide deck has been updated. It should be OK to resolve.
