### ISSUE TITLE
Vert.x routes are paused when RESTEasy is in the classpath

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#4564]
**Describe the bug**
After switching to quarkus 0.24.0 in camel-quarkus, the platform http component is unable to handle request because the vert.x route is paused when resteasy is added to the classpath.

A workaround is top resume routes, like we do here:
https://github.com/lburgazzoli/apache-camel-quarkus/blob/quarkus-0.24.0/extensions/platform-http/runtime/src/main/java/org/apache/camel/quarkus/component/platform/http/runtime/QuarkusPlatformHttpConsumer.java#L109-L114

**Expected behavior**
We should not need to explicit resume routes

**Comment by lburgazzoli** [comment]
//cc: @stuartwdouglas

**Comment by gsmet** [comment]
@lburgazzoli @stuartwdouglas is it still an issue? I know we fixed several similar issues recently.

**Comment by stuartwdouglas** [comment]
@lburgazzoli I believe this is fixed?

**Comment by lburgazzoli** [comment]
need to test it, will do it tomorrow

**Comment by lburgazzoli** [comment]
I confirm it is fixed. 
Do you have any commit I can use on my side as a reference ?

**Comment by stuartwdouglas** [comment]
I think it was https://github.com/quarkusio/quarkus/commit/86a790ada8fef9e4a744b7d4e735316f5f138d47
