### ISSUE TITLE
BuildStep utilizing InterceptorBindingRegistrarBuildItem results in IllegalArgumentException

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#4565]
**Describe the bug**

I followed the example from the CDI guide for implementing [additional interceptor bindings](https://quarkus.io/guides/cdi-reference#additional-interceptor-bindings). It fails with:

```
java.lang.IllegalArgumentException: Build item class must be leaf (final) types: class io.quarkus.arc.deployment.InterceptorBindingRegistrarBuildItem
	at io.quarkus.builder.item.BuildItem.<init>(BuildItem.java:22)
	at io.quarkus.builder.item.MultiBuildItem.<init>(MultiBuildItem.java:8)
	at io.quarkus.arc.deployment.InterceptorBindingRegistrarBuildItem.<init>(InterceptorBindingRegistrarBuildItem.java:9)
```

Presumably `InterceptorBindingRegistrarBuildItem` should be declared as `final` like the other `BuildItem` implementations?

**Expected behavior**

`InterceptorBindingRegistrarBuildItem` successfully registers the interceptor binding.

**Comment by gsmet** [comment]
Right, thanks for the report, I created a PR for that but we will also need to add a test.

We should release 0.25.0 tomorrow so your issue should be fixed shortly.
