### ISSUE TITLE
Document the use of addAllCharsets for Tika extension

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4602]
**Description**
As noticed by Guillaume @gsmet, one of the native Tika tests reports an unsupported charset exception

**Implementation ideas**

`TikaProcessor` has to produce `NativeEnableAllCharsetsBuildItem`, possibly optionally

**Comment by ppalaga** [comment]
We should perhaps recommend setting `quarkus.native.enable-all-charsets = true` in `application.properties` because it works both in Maven and Gradle.
