### ISSUE TITLE
DeploymentException not thrown when using @ConfigProperties

### ISSUE THREAD

**Issue by waggy55** [quarkusio/quarkus#4604]
`@ConfigProperties` does not behave the same as `@ConfigProperty`

When using `@ConfigProperty` to inject configuration, if the property is missing, a DeploymentException is thrown at start-up.

For example, adding the following to a Controller:
```
@ConfigProperty(name = "cassandra.connection.node") public String node;
@ConfigProperty(name = "cassandra.connection.port") public int port;
```
and the following to application.properties (notice additional r on node) :
```
cassandra.connection.noder=0.0.0.0
cassandra.connection.port=9042
```
results in an exception at start-up:
```
javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: cassandra.connection.node
```

However, when using `@ConfigProperties` as follows:
```
@ConfigProperties(prefix = "cassandra")
public class CassandraConfiguration
{
  public ConnectionData connection;

  public static class ConnectionData
  {
    public String node;
    public int port;
  }
}
```
Given the same application.properties file as above, an exception is not thrown at start-up. Instead, the application starts, but throws an UnhandledException, which wraps a NoSuchElementException, when the property is accessed:
```
UnhandledException: java.lang.RuntimeException: Error injecting com.***.CassandraConfiguration com.***.cassandraConfiguration
....
Caused by: java.util.NoSuchElementException: Property cassandra.connection.node not found
```

`@ConfigProperties` works as expected when the application.properties are correct:
```
cassandra.connection.node=0.0.0.0
cassandra.connection.port=9042
```

**Comment by gwenneg** [comment]
I'll take a look at this one.
