### ISSUE TITLE
Investigate possibility to use a lazy threadpool for Quartz backed scheduler

### ISSUE THREAD

**Issue by jaikiran** [quarkusio/quarkus#4606]
A recently merged PR https://github.com/quarkusio/quarkus/pull/4554 adds code which doesn't start the `Scheduler` if there's no `@Scheduled` annotations detected. A side-effect of this is that the `Schduler` if injected and used programmatically to start timers, will no longer function.

The reason why the `start()` of the scheduler has been skipped, when no `@Scheduled` is present is to prevent Quartz from eagerly starting a threadpool with certain (configured) number of threads. Details here https://github.com/quarkusio/quarkus/issues/4243. Looking at the implementation of the default and the only functional thread pool that comes in Quartz (`org.quartz.simpl.SimpleThreadPool`), it creates a fixed set of threads eagerly and doesn't let users configure the pool to be lazily initialized.
This enhancement request is to investigate if it's possible to use Quarkus internal thread pool as an implementation of `org.quartz.spi.ThreadPool`

**Comment by jglick** [comment]
> [if] the `Scheduler` if injected and used programmatically to start timers, will no longer function

Perhaps the title of this issue should be amended to clarify that 0.25.0 will break apps that were working in 0.24.0? I had to bisect versions and search for a while to get here. Workaround: add somewhere

```java
@Inject Scheduler scheduler;
// …call scheduler.startTimer…
@Scheduled(every = "P99D") public void workAroundQuarkus4606() {}
```

**Comment by jaikiran** [comment]
Hello @mkouba, would you happen to know if the recent enhancements done in master branch, around the scheduler, would fix this issue where if there are no annotated "schedules" then we don't start the scheduler and thus using such an injected scheduler for programatic scheduling, by the applicaiton, will fail?

@jglick Any chance you can test this against latest upstream master, if it's easy for you?

**Comment by jglick** [comment]
> test this against latest upstream master

Tried to build this repo from sources, but it died almost at once in the `arc/runtime` module:

    Plugin org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-1 or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.plugins:maven-compiler-plugin:jar:3.8.0-jboss-1 in <my-mirror>

I assumed there was some issue with the `pluginRepositories` specified in `azure-mvn-settings.xml`, but https://repository.jboss.org/nexus/content/repositories/central/org/apache/maven/plugins/maven-compiler-plugin/ does not have this, and I was unable to work around it (short of disabling the mirror, which would then download the Internet). Using the provided `mvnw` did not help, and `CONTRIBUTING.md` offered no other suggestions.

**Comment by mkouba** [comment]
So there is a backward incompatible change in the scheduler API for 1.1.0 - the `Scheduler#startTimer()` method was removed (we believe it was a mistake). In other words, programatic scheduling is not supported anymore. Furthermore, the default scheduler implementation does not create its own thread pool anymore.

I think that we can close this issue.

Note that thte scheduler extension was marked as PREVIEW until 1.1.0 and so breaking the API is "acceptable".

**Comment by jaikiran** [comment]
Thank you @mkouba. Closing based on Martin's input.

**Comment by jglick** [comment]
> programatic scheduling is not supported anymore

Meaning what, that this package is not unusable except for cron-like tasks, and for everything else I would need to use `java.util.concurrent` or the like directly?

**Comment by mkouba** [comment]
That means that the Scheduler extension API only supports declarative approach via the `@Scheduled` annotation. 

> for cron-like tasks

Not really. You can use `@Scheduled(every="10s")` where the value is parsed  with `Duration#parse()`. The value is always rounded to full second.

For programmatic approach you could try `Vertx.setTimer(long, Handler<Long>)` and `Vertx.setPeriodic(long, Handler<Long>)` methods for non-blocking stuff (see https://vertx.io/docs/vertx-core/java/#_executing_periodic_and_delayed_actions). We will probaly add support for an injectable `java.util.concurrent.ScheduledExecutorService` for blocking tasks.

**Comment by jglick** [comment]
For anyone stumbling across this, the following migration path seems to work:

* replace
```java
@Inject Scheduler scheduler;
// …
scheduler.startTimer(delay, () -> {
    // …
});
```
with
```java
@Inject Vertx vertx;
// …
vertx.setTimer(delay, id -> {
    // …
});
```
* remove `quarkus-scheduler` extension if unused

**Comment by mkouba** [comment]
Just one more comment - the handler passed to the `Vertx.setTimer()` method is executed using the event loop thread and so the code should not block. If you need to perform some blocking/long-running operation use the `Vertx.executeBlocking()` method inside the handler:

```java
@Inject Vertx vertx;
// …
vertx.setTimer(delay, id -> {
   vertx.executeBlocking(p -> {
      // ...
    }, p -> {});
});
```

See https://vertx.io/docs/vertx-core/java/#blocking_code for more information.
