### ISSUE TITLE
ci failures for BearerTokenAuthorizationTest

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#4626]
**Describe the bug**
CI native build for the mentioned test fails
**Expected behavior**
CI to pass

**Screenshots**
```
INFO] Running io.quarkus.it.keycloak.BearerTokenAuthorizationTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.282 s <<< FAILURE! - in io.quarkus.it.keycloak.BearerTokenAuthorizationTest
[ERROR] io.quarkus.it.keycloak.BearerTokenAuthorizationTest  Time elapsed: 4.282 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <201> but was <500>.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

**Additional context**
the following PRs from https://github.com/quarkusio/quarkus/pull/4609 to https://github.com/quarkusio/quarkus/pull/4623 seems to have hit this failure.

**Comment by geoand** [comment]
I am seeing a lot of the hit this failure.

**Comment by sberyozkin** [comment]
Hi All, this test passes on my machine; it appears the` docker-keycloak` profile is taking awhile to complete the initialization of the KC server instance.

**Comment by sberyozkin** [comment]
@geoand may be have some wait code in the test, ping the KC server endpoint for 30 secs or so ?

**Comment by gsmet** [comment]
AFAICS, the OIDC test is run last and it's native tests so the ones before take time.

Not entirely sure this is the problem.

**Comment by geoand** [comment]
I haven't done any testing on this so my idea above might have been totally off :P

**Comment by sberyozkin** [comment]
This fails with:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.it.keycloak.BearerTokenAuthorizationTest
12:20:37.564 Keycloak:12:20:37,563 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-14) Uncaught server error: java.lang.RuntimeException: Script upload is disabled
12:20:37.564 Keycloak:	at org.keycloak.keycloak-authz-policy-common@7.0.1//org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.updatePolicy(JSPolicyProviderFactory.java:125)
12:20:37.564 Keycloak:	at org.keycloak.keycloak-authz-policy-common@7.0.1//org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.onImport(JSPolicyProviderFactory.java:70)
12:20:37.564 Keycloak:	at org.keycloak.keycloak-server-spi-private@7.0.1//org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:2232)
12:20:37.564 Keycloak:	at org.keycloak.keycloak-server-spi-private@7.0.1//org.keycloak.authorization.AuthorizationProvider$3.create(AuthorizationProvider.java:351)
```
See https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=9906&view=logs

**Comment by sberyozkin** [comment]
@pedroigor FYI

**Comment by pedroigor** [comment]
@sberyozkin, This error should be fixed by passing the following system properties when booting the server:

```
-Dkeycloak.profile.feature.upload_scripts=enabled
```

**Comment by pedroigor** [comment]
In fact, I think we can just remove the logic from test that is trying to create policies on the server. They seem to be irrelevant to what is being tested (they were there for the old extension).

**Comment by geoand** [comment]
@pedroigor Whatever you think is best.

My "fix" was just a quick bandaid to get us back to green CI :)

**Comment by pedroigor** [comment]
Sent https://github.com/quarkusio/quarkus/pull/4670.

**Comment by pedroigor** [comment]
@geoand, it works too :)

But, as you know, we need to make sure we work with latest Keycloak version. So for OIDC, we don't need to deploy scripts to the server (but with the new extension I'm working).

**Comment by geoand** [comment]
@pedroigor yes of course! Thanks for the PR!

**Comment by sberyozkin** [comment]
Guys you are too fast :-)

**Comment by machi1990** [comment]
I am seeing a likely similar issue for these builds among others
- https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=12297&view=logs
- https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=12298&view=logs
- https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=12274&view=logs&jobId=a6aa59f2-f7fc-5b83-1893-1108437bc330

The failure is 
```
[INFO] Running io.quarkus.it.keycloak.BearerTokenAuthorizationTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.99 s <<< FAILURE! - in io.quarkus.it.keycloak.BearerTokenAuthorizationTest
[ERROR] io.quarkus.it.keycloak.BearerTokenAuthorizationTest  Time elapsed: 0.99 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440)
```

**Comment by machi1990** [comment]
@jaikiran opened https://github.com/quarkusio/quarkus/issues/5536.
