### ISSUE TITLE
Clarify which logging APIs are supported and what do we recommend

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#4629]
We have some paragraph here: https://quarkus.io/guides/logging-guide#supported-logging-apis but maybe we should push more JBoss Logging and put the paragraph at the top.

We should also be clear that some of them might need to add an adapter as a dependency.

/cc @emmanuelbernard

**Comment by emmanuelbernard** [comment]
That's a fair question, we [c|sh]ould push JBoss Logging yes, it has a few additional useful APIs. But gently, people can use what they want

**Comment by dmlloyd** [comment]
I noticed that log4j and log4j2 are missing from the list, but they should be supported as well.

**Comment by codeninja55** [comment]
Have a question whether log4j2 is supposed as well. Is there any way to adapt Quarkus to use log4j2 rather than JBoss?

**Comment by dmlloyd** [comment]
You can use the log4j2 logging API as long as you include the `org.jboss.logging:log4j2-jboss-logmanager` artifact.  The logging backend is not pluggable.

**Comment by hacst** [comment]
@dmlloyd For clarification: Will it stay possible to use log4j 2 as the jboss logging provider in quarkus or is that what you mean with "not pluggable" backend? There's a lot of appenders for log4j2 that, from what I can tell, are not available for the jboss provider (e.g. microsoft provides a log4j2 one for application insights).

**Comment by dmlloyd** [comment]
It is not possible to use log4j2 as the backend.  However, it is possible (at least theoretically) to adapt log4j2 appenders to be usable from the JBoss LogManager backend.  Such support would likely belong in the https://github.com/jboss-logging/log4j2-jboss-logmanager project.
