### ISSUE TITLE
Undocumented properties migration

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#4630]
**Describe the bug**
Migrating to 0.25.0 I have this WARNINGS:

WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.smallrye-jwt.auth-mechanism" provided
WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.security.users.embedded.auth-mechanism" provided

but in the guides those two are documented.

**Expected behavior**
No warnings

**To Reproduce**
Configure eyltron or smallrye as documented

**Comment by Sanne** [comment]
I didn't find these in the guides anymore. Safe to close this?
