### ISSUE TITLE
Incorrect debugging advice in extension authors guide

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#4635]
**Describe the bug**
[This](https://quarkus.io/guides/extension-authors-guide#troubleshooting-debugging-tips) of the extension author's guide mentions the use of `-Dquarkus.debug.generated-classes-dir` for `mvn install` which is incorrect.

That flag only applies to dev mode. In regular building mode the generated classes can be found in `target/wiring-classes`.

**Comment by loicmathieu** [comment]
@geoand I just tested it and the system property `quarkus.debug.generated-classes-dir` does not work anymore. Their didn't seems to be way to output the generated classes during a normal maven build anymore.

But on dev mode, classes are always generated in the `target/wiring-devmode`.

I will prepare a PR with the modification to the guide, but maybe the functionality to output the classes during a norma maven build still exist but longuer via the `quarkus.debug.generated-classes-dir` property.

**Comment by loicmathieu** [comment]
In fact, the system property is used inside `io.quarkus.runner.RuntimeClassLoader` but I'm not sure if it is used during a normal maven dir (mvn clean install) ?

**Comment by geoand** [comment]
@loicmathieu indeed, things have changed a lot WRT how the regular jar is produced.
AFAIR, `quarkus.debug.generated-classes-dir` was also about the dev mode though.

**Comment by loicmathieu** [comment]
Just tested it, `quarkus.debug.generated-classes-dir` have no impact on dev mode ... The classes are always generated inside `target/wiring-devmode` whether you use this sys properties or not

**Comment by geoand** [comment]
That is partly true, indeed `target/wiring-devmode` contains **some** classes. However, if you do:

```
./mvnw clean quarkus:dev -Dquarkus.debug.generated-classes-dir=generated-devmode
```

you will see a lot more classes inside `target/generated-devmode`. Can you give it a shot and see if that makes sense?

**Comment by loicmathieu** [comment]
@geoand I comes up with #4878
