### ISSUE TITLE
Using alpine or busybox:glibc as Dockerfile.native basimage

### ISSUE THREAD

**Issue by BeneStem** [quarkusio/quarkus#4647]
**Description**
I'd like to use alpine or busybox:glibc as a baseimage for the Dockerfile.native to further reduce the image size.

**Implementation ideas**
I tried to make this work by statically linking the glibc references with `--static` into the container while building the native image following this [guide](https://blog.softwaremill.com/small-fast-docker-images-using-graalvms-native-image-99c0bc92e70b).

In the end i was not able to make it due to not enough knowledge of the internal quarkus process. You might have an idea how to go further and make this happen :)

Would love to see even smaller containers :)
Currently with ubi-minimal + app they are around 120mb with alpine they can be reduced to ~30mb using the resteasy example app.

**Comment by cescoffier** [comment]
native image requires glibc, alpine is using musl if I'm not mistaken.

**Comment by BeneStem** [comment]
Linking the glibc stattically into the image during build should work.
With the small example from the mentioned guide it does.
`busybox:glibc` would also be fine as a small base image :)

**Comment by BeneStem** [comment]
I found a very well suited base image `gcr.io/distroless/base`.
