### ISSUE TITLE
Offer a way for an extension to know the types of files changed upon hot reload

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4649]
Problem space:

Recreating the database schema for Hibernate ORM at each change is expensive. All operations not involving @Entity (and friends) files, can force schema generation off. And possibly import.sql off too (TBD).

To do that, Quarkus between how deployment should give the list of resources that changed with the previous deployment.

The API need to be thought out but that would be powerful for some heavy startup extensions.

CC @stuartwdouglas @Sanne 

Post 1.0

**Comment by stuartwdouglas** [comment]
This should be possible, basically we would want have both the old and new Jandex indexes so you could see if entities had changed.

**Comment by Sanne** [comment]
> we would want have both the old and new Jandex indexes so you could see if entities had changed.

the Jandex index contains "touch" timestamps and such? Could we trust those?

I'm skeptical, I think I'd rather prefer an "input signature" handled by quarkus-core than having to implement custom logic in each extension.

**Comment by Sanne** [comment]
That's what I mean. I can't trust the jandex index alone; even if it had information about deleted entities, there's more missing.

**Comment by stuartwdouglas** [comment]
We mostly have this now with LiveReloadBuildItem.
