### ISSUE TITLE
Metrics - detect possible metric ID conflicts at build time

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#4650]
For example, if I have a method annotated like this:
```java
    @Metered
    @Timed
    public String hello() {
        return "Hello!";
    }
```
I get `java.lang.IllegalArgumentException: Previously registered metric org.acme.config.GreetingResource.hello is of type meter, expected timer` at runtime. The solution is to add an explicit name to one of the metrics. We could easily detect this error at build time. WDYT @jmartisk?

**Comment by jmartisk** [comment]
Having some sort of eager validation at build time would definitely be a good thing. A problem could be that this might not be easy to implement without duplicating a lot of logic from SmallRye Metrics that happens in runtime code (in the recorder we call `MetricsMetadata.registerMetrics`: https://github.com/quarkusio/quarkus/blob/0.25.0/extensions/smallrye-metrics/runtime/src/main/java/io/quarkus/smallrye/metrics/runtime/SmallRyeMetricsRecorder.java#L130) and computes the mapping between annotations and the actual MetricIDs. But it's definitely worth a shot.

**Comment by ebullient** [comment]
the micrometer extension detects a double annotation like this and flat out ditches one of them with a warning. Is there a reason you would need both Metered AND Timed? (don't all Timed metrics include a count?)

**Comment by ebullient** [comment]
I think we can close this.
