### ISSUE TITLE
Duplicate metrics HELP line

### ISSUE THREAD

**Issue by blxbrgld** [quarkusio/quarkus#4651]
**Duplicate metrics HELP line**

The metrics resource returns duplicate HELP line for `base_gc_time_total` and this as a result leads to telegraf failure when trying to collect the metrics from the /metrics resource (/metrics/application works fine). The error is the following:

```
[inputs.prometheus] Error in plugin: error reading metrics for http://localhost:8080/metrics: reading text format failed: text format parsing error in line 58: second HELP line for metric name "base_gc_time_total"
```
It's true that there are two identical HELP lines (for `PS MarkSweep` and `PS Scavenge`):

```
# HELP base_gc_time_total Displays the approximate accumulated collection elapsed time in milliseconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The Java virtual machine implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.
# TYPE base_gc_time_total counter
base_gc_time_total_seconds{name="PS MarkSweep"} 0.143

# HELP base_gc_time_total Displays the approximate accumulated collection elapsed time in milliseconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The Java virtual machine implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.
# TYPE base_gc_time_total counter
base_gc_time_total_seconds{name="PS Scavenge"} 0.081
```

**Comment by jmartisk** [comment]
Interesting, I thought we had this covered properly in tests, but for some reason it indeed behaves this way. I'll see what can be done to fix it.

**Comment by jmartisk** [comment]
I filed https://github.com/smallrye/smallrye-metrics/issues/188 on the SmallRye Metrics side and will submit a fix. Once a new release of SR-M is out, we can upgrade this in Quarkus, probably next week.

**Comment by jmartisk** [comment]
Should be fixed in current master

**Comment by dusty73** [comment]
Any news on this? We're currently facing the same problem, using Telegraph as scraper we receive errors because of duplicated help lines
