### ISSUE TITLE
Improve extension metrics

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#4675]
**Description**
Quarkus needs a consistent approach to metrics. It would be nice for extensions to:

1. Document not just how to enable metrics, but also document the metrics themselves
2. Consistency (or at least formality) for enabling and exposing metrics. 
 - Hibernate logs  statistics (via quarkus.hibernate-orm.statistics=true property setting) to stdout but not the /metrics endpoint.
 - Kafka extension does not use a binary "true/false" metrics setting but instead it uses a metrics "level" like kafka-streams.metrics.recording.level=DEBUG. Not sure if these are logged to /metrics.
3. I did not do an exhaustive search, only a handful of extensions (3-5) support metrics. For example, from what I can tell, there are no metrics for the web stack (REST), like number of http sessions or connections. This can make it difficult to diagnose issues in production.

**Implementation ideas**
None.

**Comment by gunnarmorling** [comment]
> it uses a metrics "level" like kafka-streams.metrics.recording.level=DEBUG. Not sure if these are logged to /metrics.

Currently the Kafka Streams extension doesn't expose any health checks or metrics. There's a related discussion in https://github.com/quarkusio/quarkus/issues/4375, which is about providing means for letting extensions automatically expose metrics and health checks if the required other extensions are enabled.

**Comment by ebullient** [comment]
I think some of this is changing as we switch over to micrometer: kafka instrumentation and hibernate instrumentation (and agroal.. ) all seem consistently enabled at this point..

**Comment by geoand** [comment]
@ebullient should this be considered done at this point?

**Comment by ebullient** [comment]
Either that, or John needs to go through and make a list. ;)

**Comment by jclingan** [comment]
Quarkus has come a long way since this was created. Consider this complete.
