### ISSUE TITLE
Add variable expansion in MANIFEST.MF file for CI/CD builds

### ISSUE THREAD

**Issue by rmcguinness** [quarkusio/quarkus#4684]
**Description**
When building a quarkus runner project, the MANIFEST file may contain existing META-INF/MANIFEST.MF entries, but those entries MUST be static. CI/CD systems often add attributes to the environment during execution of pipelines that are then used by downstream system for monitoring, routing and running the produced JAR files.

**Implementation ideas**
Allow the META-INF/MANIFEST.MF file to contain place holders wrapped in ${} notation and the System.getenv(<key_name>) to match a system property if the value is annotated, and the system property is found. Such that:

```
MY_PROPERTY_VALUE=${property.key}
```
Could resolve the '-Dproperty.key="My Value"' and the resulting MANIFEST entry would be:

```
MY_PROPERTY_VALUE=My Value
```

The other way to fix this would be honoring options in the plugin similar to how the JAR plugin works with Maven.

**Comment by geoand** [comment]
This has now been implemented. See https://github.com/quarkusio/quarkus/blob/b8dfcd92bef5f7d750a3f02a958a78598f3dc9d6/core/deployment/src/main/java/io/quarkus/deployment/pkg/ManifestConfig.java#L9
