### ISSUE TITLE
make spring-web extension REST endpoint published in openapi

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4693]
Create a Spring Web REST endpoint and add openapi. You will see that the end point is not published.

Can wait after 1.0 if needed.

**Comment by geoand** [comment]
This shouldn't be hard, basically we probably need some sort of implementation of `io.smallrye.openapi.runtime.scanner.AnnotationScannerExtension`.

I'll see if we can get it in before `1.0`

**Comment by geoand** [comment]
Actually is seems like some JAX-RS stuff are baked into the top level `io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner` so it might not be so easy after all. I'll continue to investigate and update later on feasibility for 1.0

**Comment by geoand** [comment]
So `OpenApiAnnotationScanner` is tied to JAX-RS currently and I don't see any useful injection points that would give us a quick win.
It looks like this would need some dedicated attention and since it's not a priority item I proposed we move it to after `1.0`, OK @emmanuelbernard ?

**Comment by geoand** [comment]
Makes sense

**Comment by kenfinnigan** [comment]
Don't we convert Spring Web annotations to JAX-RS ones for execution? So do we just need to modify SmallRye OpenAPI to be able to operate on a "current" set of beans instead of pre-computed jandex?

**Comment by kenfinnigan** [comment]
Ok.

Does that mean SRye OpenAPI needs to understand Spring annotations?

**Comment by geoand** [comment]
@ebullient will most likely be tackling this one

**Comment by emmanuelbernard** [comment]
@geoand isn't this one fixed or planned via SR fix? Feels like a duplicate.

**Comment by geoand** [comment]
There is a fix in the works on the smallrye side of things so yeah, let's close this
