### ISSUE TITLE
CDI security - determining security checks at build time

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#4695]
**Description**
The current implementation of CDI Security determines the check to be applied for a given method in runtime.
The result is cached but it could be moved to build time to further optimize

**Implementation ideas**

> collect/serialize the info (roles allowed) during build then we could inject/use it at runtime.

For more see https://github.com/quarkusio/quarkus/pull/4413/files#r335520637

**Comment by geoand** [comment]
I propose closing this unless this is something @michalvavrik or @sberyozkin really want
