### ISSUE TITLE
Rename Substrate build items

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#4704]
The `Substrate*` build items should be renamed to be `NativeImage*` instead.  The Graal people have repeatedly tried to pull back from the `Substrate` name, so it's probably best to avoid using product names period and instead name these items by their function.

Not really sure if this is a "bug" or an "enhancement".  Maybe we need another category. :)

**Comment by gwenneg** [comment]
@dmlloyd Should `@SubstrateTest` (and all related classes) also by renamed to `@NativeImageTest`?

**Comment by machi1990** [comment]
If yes, we have to think of a possible user migration path :-)

Maybe deprecate it first? Like what we did we `@Template` and `@Recorder`
