### ISSUE TITLE
Kafka Streams - Config - Topics should be a list

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#4706]
Right now, it's a string but it should rather be a proper list in config:

https://github.com/quarkusio/quarkus/blob/master/extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsRuntimeConfig.java#L37

@gunnarmorling can you have a look? Or maybe you had a particular reason to do it this way?

**Comment by lhauspie** [comment]
Can I work on this issue after @gunnarmorling answered ?

**Comment by gunnarmorling** [comment]
+1 for making this a list. No specific reason that isn't one yet, an
oversight probably. @Logan, feel free to grab this one. Thanks a lot!

**Comment by lhauspie** [comment]
Thanks. I'll work on it.

PS: my handle is @lhauspie ;)

**Comment by gunnarmorling** [comment]
> Thanks. I'll work on it.

👍 

> PS: my handle is @lhauspie ;)

Yeah, sorry, I was replying from my phone, didn't have the handle and didn't think that @ with your name would hit another user... :)

**Comment by gunnarmorling** [comment]
Btw. just in case you're interested in doing more contributions to the Quarkus Kafka Streams extensions, there's a few things we could talk about. E.g. built-in support for metrics and health checks, if the corresponding Quarkus extensions are enabled. It's on my list of things to work on, but would be more than glad about any help. As said, just in case, simply ignore this message otherwise :)

**Comment by lhauspie** [comment]
> Btw. just in case you're interested in doing more contributions to the Quarkus Kafka Streams extensions, there's a few things we could talk about. E.g. built-in support for metrics and health checks, if the corresponding Quarkus extensions are enabled. It's on my list of things to work on, but would be more than glad about any help. As said, just in case, simply ignore this message otherwise :)

It would be a pleasure. Feel free to give me some pointer to issues to start discussion.

**Comment by lhauspie-adeo** [comment]
As the `topics` String is a comma-separated list of topic names, `KafkaStreamsTopologyManager.java` parse this `topics` String to a Set<String> by using this piece of code : 
```Java
        Set<String> topicsToAwait = runtimeConfig.topics
                .map(n -> COMMA_PATTERN.split(n))
                .map(Arrays::asList)
                .map(HashSet::new)
                .map(Collections::unmodifiableSet)
                .orElseGet(Collections::emptySet);
```

So my question is: how is it possible to make `topics` to be a List (or a Set) in `KafkaStreamsRuntimeConfig.java` without parsing a comma-separated String ?

@gsmet do you have a use case where you need to retrieve the List (or Set) of topics ?

**Comment by machi1990** [comment]
> KafkaStreamsRuntimeConfig.java

Hi @lhauspie-adeo 

I guess changing 

```
@ConfigItem
public Optional<String> topics;
```

to 
````
@ConfigItem
 public List<String> topics;
```

In the config file should do the job.

**Comment by lhauspie-adeo** [comment]
Oh. OK, I did it, I just have to test before creating the PR.

Thanks

**Comment by machi1990** [comment]
> Oh. OK, I did it, I just have to test before creating the PR.
> 
> Thanks

You are welcome. Thanks for the contribution :-)

**Comment by lhauspie** [comment]
Sorry, I got the wrong account again.
Could you assign this issue to @lhauspie, not @lhauspie-adeo
