### ISSUE TITLE
Kubernetes Client - Config - Some properties should be optional

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#4707]
Nearly all the properties are required, whereas I'm pretty sure they should be optional (typically the proxy stuff).

Please use `Optional` where it makes sense.

@geoand @gastaldi could you have a look? It's not high priority but I just included the generated doc and it ends up with `required` everywhere.

I'm also wondering if most of the config should be runtime instead of build time?

**Comment by geoand** [comment]
I'll check it out
