### ISSUE TITLE
Swagger-ui response with wrong content-type?

### ISSUE THREAD

**Issue by seseso** [quarkusio/quarkus#4710]
**Describe the bug**
When using swagger-ui, responses are comming with content-type
text/html;charset=windows-1252
which shows strange characters on browser.

**Expected behavior**
By default, I would except UTF-8 in responses 

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Java version: OpenJDK 8
 - N/A
 - Quarkus version: 0.25.0

![image](https://user-images.githubusercontent.com/6703910/67221037-b983d180-f422-11e9-9cbe-0e65510a58ab.png)

**Comment by gsmet** [comment]
@seseso could you check if https://github.com/quarkusio/quarkus/pull/4713 fixes your issue?

Just build the PR with `mvn clean install -DskipTests -DskipITs` then use `999-SNAPSHOT` in your app.

**Comment by seseso** [comment]
Works like a charm!

Thanks!

**Comment by gsmet** [comment]
Thanks for checking!
