### ISSUE TITLE
quarkus-oidc should get JsonWebToken or JWT Map view from VertxOAuth2

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4716]
**Description**
Right now we have to double parse the token in the adapter code to create `JsonWebToken` because VertxOAuth2 has already got it parsed and it has no way to map that to JsonWebToken.

**Implementation ideas**
It is impossible to avoid the double parsing unless VertxOAuth2, at the moment of seeing the parsed token, could map it to `JsonWebToken` (possibly with the help of `smallrye-jwt`) or create a complete Map view of the token for the adapter itself to convert it to `JsonWebToken`

Likely a medium term issue

**Comment by gsmet** [comment]
This one got closed but no idea why? Won't fix? Out of date?
