### ISSUE TITLE
JdbcRecorder.registerPrincipalQuery() should never initialize ArC

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#4718]
See https://github.com/quarkusio/quarkus/blob/master/extensions/elytron-security-jdbc/runtime/src/main/java/io/quarkus/elytron/security/jdbc/JdbcRecorder.java#L44-L46. If it needs to perform some logic after ArC is initialized it should depend on the `BeanContainerBuildItem`.

**Comment by mkouba** [comment]
@stuartwdouglas @danielpetisme FYI

**Comment by mkouba** [comment]
@gsmet what's the reason to revert the commit?

**Comment by gsmet** [comment]
Sorry, I should have given an explanation: it makes the build fail.

But Stuart has probably a fix there: https://github.com/quarkusio/quarkus/pull/4740 . So let's wait for the CI result there and decide after.

**Comment by mkouba** [comment]
Ok, thanks.

**Comment by mkouba** [comment]
So we'll revert the revert if #4740 is merged?

**Comment by gsmet** [comment]
Well, let's not merge this one and wait for Stuart's PR CI run. It will fail in `PackageIT` anyway as we have another issue but if it goes until there, I will merge it.
