### ISSUE TITLE
Fix extension descriptions in the generated JSON

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#4724]
The maven plugin generating `quarkus-extension.json` file is taking description from the pom.xml file. Most of the extensions don't actually include the description. In that case the description gets inherited from the closest parent that has it. Currently what ends up in the JSON file looks completely wrong.

**Comment by gastaldi** [comment]
I can work on this to make sure the descriptions are correctly set in the `extensions/<name>/runtime` poms

**Comment by gastaldi** [comment]
The `<name>` always ends up with `- Runtime`, like in: 
```xml
    <artifactId>quarkus-agroal</artifactId>
    <name>Quarkus - Agroal - Runtime</name>
    <description>Pool your database connections (included in Hibernate ORM)</description>
```

Should we keep the `- Runtime` suffix or should I remove it?

**Comment by aloubyansky** [comment]
An alternative would be set the name in the JSON file (or whatever the replacement will be). But I guess it would be nice if the name in the pom would match the extension name.

**Comment by gastaldi** [comment]
@aloubyansky so I assume that as a yes? :) I'll add in a separate commit just in case

**Comment by aloubyansky** [comment]
Maybe you should ask the extension maintainers instead :)

**Comment by maxandersen** [comment]
-1 on doing "magic" prefix removals. Should just use the name and users can change it or override it explicitly.

**Comment by gastaldi** [comment]
@maxandersen Not sure I follow, what "magic" prefix removals are you talking about?

**Comment by maxandersen** [comment]
ah sorry - I misread it :) thought you were removing the specific *postfix* in the descriptor generator - now I grok you are just suggesting to remove it. Yeah, that’s fine but I would raise it on the dev list first before doing a bulk remove.
