### ISSUE TITLE
Explore notion of opinionated REST resource

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#474]
Objective, most simple hello world.

Use the notion of opinionated `@Controller`

From

```
@Path("/hello")
public class GreetingResource {

    @Inject
    GreetingService service;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/greeting/{name}")
    public String greeting(@PathParam("name") String name) {
        return service.greeting(name);
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}
```

To

```
@Controller
// /hello
public class Hello {

    // [...]/greetings/name
    public String greeting(String name) {
        return "Hello " + name;
    }

    // [...]/greetings/
    public String hello() {
        return "hello";
    }
}
```

**Comment by gastaldi** [comment]
I think https://github.com/quarkusio/quarkus/issues/474#issuecomment-454308926 is already implemented and (kinda) satisfies this issue. Can we close this now?

**Comment by FroMage** [comment]
Well, we never went full-on with this, but we could now, with RESTEasy Reactive, perhaps it's time to restart this. CC @geoand

**Comment by geoand** [comment]
Yup, there is no better time than now

**Comment by geoand** [comment]
I am going to close this as we now have [Quarkus - Renarde](https://github.com/quarkiverse/quarkus-renarde)
