### ISSUE TITLE
Generated maven project should have a property for quarkus platform and version

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#4744]
**Describe the bug**
when mvn project generated and quarkus version != platform version we fall back to hardcoded values.
Should use property replacements instead., i.e. ${quarkus.platform.version} and ${quarkus.platform.id} 

**To Reproduce**
use latest master/0.26 with universe platform with a version number updated to be 998-SNAPSHOT in all its pom.xml files and run:

`mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=org.acme -DprojectArtifactId=application-configuratxio557 -DclassName="org.acme.config.GreetingResource" -Dpath="/greeting" -DplatformArtifactId=quarkus-universe-bom -DplatformVersion=998-SNAPSHOT`

**Comment by aloubyansky** [comment]
You probably want to be checking whether the platform BOM comes from Quarkus itself or it's a universe or other external one. Because if it's Quarkus core then one property will be enough. And if it's an external BOM, where else would that property be used?

**Comment by maxandersen** [comment]
if you want to "optimize" that specific situation we could just use `<quarkus.platform.version>${quarkus.version}</quarkus.platform.version>`

I'm not really following why we would have that situation occur once first platform is released and out ?

**Comment by aloubyansky** [comment]
Where would 'quarkus.platform.version' be used?

**Comment by aloubyansky** [comment]
Besides the BOM import.

**Comment by maxandersen** [comment]
when doing `mvn -Dquarkus.platform.version=xyz clean install` to test/work with new version.

**Comment by aloubyansky** [comment]
ok

**Comment by maxandersen** [comment]
some cleanup made it into gradle for 0.28 but both maven and gradle could use a bit more cleanup but could probably be done in a backwards compatible way.
