### ISSUE TITLE
gradle wrapper not created when creating projects on windows

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#4745]
**Describe the bug**
CreateProjectMojo calls gradle instead of gradle.bat/cmd thus on windows gradle wrappers are never created.

https://github.com/quarkusio/quarkus/blob/8582422fd071d3ef152d861ab50de5ca1064e8cf/devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java#L219

**Comment by geoand** [comment]
@maxandersen Are you planning to address this one? I don't have a Windows machine so if I started it it would just be shooting in the dark :)

**Comment by maxandersen** [comment]
yes sorry - forgot to assign. I'll get it fixed.
