### ISSUE TITLE
Adding docker volume parameter to build-image goal

### ISSUE THREAD

**Issue by kameshsampath** [quarkusio/quarkus#475]
currently the maven goal to build the image (`mvn package  -Pnative -Dnative-image.docker-build=true`) does not allow me to configure the docker source volume on the host that will mapped to the docker run command to build the native image.

e.g. 

when running the command 

> docker run -v /home/docker/protean-demos:/project --rm swd847/centos-graal-native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dcom.sun.xml.internal.bind.v2.bytecode.ClassTailor.noOptimize=true -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar pgreeter-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:+PrintAnalysisCallTree -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace

I should be able to configure `/home/docker/protean-demos` to folder/mount-point of my choice

**Comment by rsvoboda** [comment]
@cescoffier something to keep open or it's ok to close it ?

**Comment by cescoffier** [comment]
Going to close it.
