### ISSUE TITLE
Define a notion of a beta/experimental extension in the tooling

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#4771]
Extension authors (or extension catalog authors) should be able to indicate in the metadata that the state/quality of certain extensions is beta or experimental.

**Comment by maxandersen** [comment]
these really just need to go into k8s style metadata - then we don't have to care.

**Comment by gastaldi** [comment]
How about setting this as a Maven `<property>` similar to what's done in https://github.com/thorntail/thorntail/blob/master/fractions/flyway/pom.xml#L37?

**Comment by maxandersen** [comment]
the plugin to generate the metadata already take values from pom.xml - that part is really secondary; the key is how we store and manage this at the API level between extensions and our platform/registry.

**Comment by gastaldi** [comment]
I believe this information (after read from the pom.xml) will be stored in the generated `extensions.json` (and as a new attribute in the `Extension` class). Each extension author could then define in their own pom.xmls how mature the extension is.

**Comment by maxandersen** [comment]
This is possible today via `quarkus-extension.yaml` - just need to hear from @ia3andy if he already picked a name/value set for it.

On call today we said that for v1 its basically just about identifying wether a feature is stable or not - no grading yet.

My suggestion is to use a key named "grading"  and for now only recognized value will be "preview"

**Comment by ia3andy** [comment]
@maxandersen I used "status" as a key already (we can change it):
https://github.com/quarkusio/quarkus/blob/1c8ed9b18f2afb4e29a6658f242d8efe51a9915c/independent-projects/tools/platform-descriptor-api/src/main/java/io/quarkus/dependencies/Extension.java#L36

**Comment by maxandersen** [comment]
status is equally neutral to grading so i'm fine with that. lets keep it simple ;)

so "status" = "preview" is the key/value pair we'll use for v1 to mark things non-stable, ok ?

**Comment by maxandersen** [comment]
fixed in core, outstanding issue in code.quarkus.io https://github.com/quarkusio/code.quarkus.io/issues/196
