### ISSUE TITLE
RESTEasy standalone - @ApplicationPath not honored if it does not start with a slash

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#4787]
Moreover, if it starts with a slash the resource is served from both the root and the app path. 

For example:
```java
@ApplicationPath("/foo")
public class MyApp extends Application {
}
@Path("/greeting")
public class GreetingResource {
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() { return "hello"; }
}
```
HTTP requests to `/greeting` and `/foo/greeting` are both handled by `GreetingResource`.

**Comment by mkouba** [comment]
For the record - I've just read the spec again and I'm not quite sure an `@ApplicationPath.value()` not starting with a slash must be supported (looks undefined). On the other hand, I believe we should support it to improve the usability. The other option would be to fail the build which seems a bit useless to me...

**Comment by gsmet** [comment]
I agree, let's be user friendly on this one. Especially since `@Path` supports not having a `/`.
