### ISSUE TITLE
quarkus-maven-plugin -Dpath is interpreted on Cygwin / Windows

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#4789]
**Describe the bug**

When you use the quarkus-maven-plugin on Cygwin on Windows, the -Dpath is interpreted. For example, if you open a Cygwin terminal and type : 

 ```
    -DprojectGroupId=io.quarkus.workshop.super-heroes \
    -DprojectArtifactId=rest-hero \
    -DclassName="io.quarkus.workshop.superheroes.hero.HeroResource" \
    -Dpath="/api/heroes"
```

Instead of generating :

```
@Path("/api/heroes")
public class HeroResource {
}
```

the code that is generated is 

```
@Path("C:/Program Files/api/heroes")
public class HeroResource {
}
```

**Expected behavior**

The expected code is 

```
@Path("/api/heroes")
public class HeroResource {
}
```

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
Yes, we already have a report of that somewhere. My understanding is that it's the shell doing bad things, not Quarkus.

**Comment by stauvel** [comment]
I tried without the first '/' in the -Dpath param, and then Maven plugin created it for me : 
    
    $ mvn io.quarkus:quarkus-maven-plugin:0.25.0:create     -DprojectGroupId=io.quarkus.workshop.super-heroes     -DprojectArtifactId=rest-hero     -DclassName="io.quarkus.workshop.superheroes.hero.HeroResource"     -Dpath="api/heroes"
    (...)
    $ cat rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/HeroResource.java
    package io.quarkus.workshop.superheroes.hero;
    (...)
    @Path("/api/heroes")
    public class HeroResource {
    (...)

**Comment by agoncal** [comment]
Yes, avoiding the first "/" works also under Mac (so `-Dpath="api/heroes"` instead of `-Dpath="/api/heroes"`)
