### ISSUE TITLE
Add a search feature in https://quarkus.io/guides/

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#4802]
**Description**
It would be nice to have a search feature in https://quarkus.io/guides/.  Right now everytime I navigate to that page I always end up using Ctrl+F to find the Guide I want.

**Implementation ideas**
Add a search field or organize the guides list

**Comment by machi1990** [comment]
+1 I remember opening this issue https://github.com/quarkusio/quarkusio.github.io/issues/259 in the website repo.

**Comment by sixdouglas** [comment]
Hi,
Maybe this one can be closed, since a search is now available on the guides page

**Comment by gastaldi** [comment]
Good catch! Closing now
