### ISSUE TITLE
Support Spring 5 Reactive (WebFlux)

### ISSUE THREAD

**Issue by ebullient** [quarkusio/quarkus#4803]
**Description**
Spring 5 Reactive support is based on WebFlux, which is a Java8-based reimplementation of RxJava. From a general Spring implementation perspective, the reactive workloads based on WebFlux can drop or bypass interaction with Tomcat to go right to Netty or Undertow, which could map nicely (with Quarkus undertow).

Reference: 
https://docs.spring.io/spring-framework/docs/5.0.0.M1/spring-framework-reference/html/web-reactive.html

**Comment by kenfinnigan** [comment]
I know @cescoffier has done some thinking on this, so not sure what the latest is.

But I believe the idea is we'd use reactive types that can be mapped to WebFlux, but not directly use WebFlux

**Comment by ebullient** [comment]
That's a possibility, sure. Point is, from an application developer's POV, they should be able to follow Spring docs & guides for writing WebFlux / Spring 5 Reactive applications, and it should work (within confines of what is possible with Quarkus re: dynamic behavior @ runtime)

**Comment by emmanuelbernard** [comment]
@ebullient I'm not sure WebFlux is used that much. So that would be a lot of effort for something not necessarily mainstream vs asking users to embrace Quarkus/Vert.x reactive web way (which might have even more usages)

**Comment by ebullient** [comment]
If a Spring developer follows the Spring way.. they will land on WebFlux. We should be able to get it working, as the snowdrop impl can put Vert.x underneath the WebFlux impl ..

**Comment by sbilello** [comment]
Is there any update on this? 
I have been using Spring WebFlux and I was looking for the integration to Quarkus. It looks like that I need to rewrite it with Quarkus/Vert.x and I can not reuse my existing code :(

**Comment by ebullient** [comment]
I haven't looked, as I went down the micrometer wormhole and haven't come back yet.

**Comment by geoand** [comment]
With Spring Web support now able to work on RESTEasy Reactive, we could run the controller methods on the event loop if we like, which is essentially what Webflux does.

ATM, a user can do that manually using the `@NonBlocking` annotation or returning a `Uni`
