### ISSUE TITLE
More flexible templating with your restful interface contract than with jax-rs

### ISSUE THREAD

**Issue by idrissneumann** [quarkusio/quarkus#4804]
**Description**
Is it possible to have a better way to design more flexible resftful client with templating like [OpenFeign/feign](https://github.com/OpenFeign) allow us to do?

Here is an example of interface contract with feign:

```java
  @RequestLine("GET /v1/myresource/{id}")
  @Headers("Authorization: Bearer {accessToken}")
  MyResource findById(@Param("id") String id, @Param("accessToken") String accessToken);
```

With Jax-Rs, I'll have to pass as argument value the complete header value wich looks like `Bearer <token value>`. Whereas with this solution, I can avoid to make the concatenation with a constant part like `Bearer` and only pass the real token value.

You can even be more flexible as you want like that:

```java
  @RequestLine("GET /v{version}/{ressourceName}?criteria1={criteria1}&criteria2={criteria2}")
  @Headers("Authorization: Bearer {accessToken}")
  SearchResult<MyResource> findByFilter(@Param("version") int version, @Param("ressourceName") String ressourceName, @Param("criteria1") String criteria1, @Param("criteria2") String criteria2, @Param("accessToken") String accessToken);
```

**Implementation ideas**
Maybe providing an integration of feign in quarkus should be enough?

**Comment by kenfinnigan** [comment]
Is this related to REST Client or more generally JAX-RS endpoints?

**Comment by idrissneumann** [comment]
I think it's possible to start by an integration of OpenFeign into quarkus. So it will resolve this issue only on the client side. Then, maybe think about an evolution of jax-rs to be more flexible.

**Comment by albertocavalcante** [comment]
@kenfinnigan @idrissneumann @geoand Is OpenFeign available to use with Quarkus? Thanks

**Comment by geoand** [comment]
It is not.

I would like however to know which features of it you would like to see in our REST Client.

**Comment by geoand** [comment]
@michalszynkiewicz @FroMage are there any cool ideas we could borrow from here to add to the new reactive REST client?

**Comment by michalszynkiewicz** [comment]
Using `@Headers("Authorization: Bearer {accessToken}")` may indeed be more straightforward than setting the constant part of the header value.

For the other mentioned features, I like `@RequestLine("GET /v{version}/{ressourceName}?criteria1={criteria1}&criteria2={criteria2}")` less than

```java
@GET
@Path("/v/{version}/{resourceName}?criteria1={criteria1}&criteria2={criteria2}")
```

We cannot do query params as ^ but does it make much sense? With JAX-RS we simply have them as `@QueryParam` in the method arguments. Less code, smaller probability of errors.

The strong side of OpenFeign is that the client can be load-balanced (on the client side). But we should have that soon with SmallRye Stork. 
The downside is, according to Spring Cloud OpenFeign docs, it does not support reactive: https://cloud.spring.io/spring-cloud-openfeign/reference/html/#reactive-support

**Comment by geoand** [comment]
I'll leave it up to you to decide whether or not to keep this ticket open or close as `won't fix`

**Comment by michalszynkiewicz** [comment]
I'd close it. @FroMage WDYT?
