### ISSUE TITLE
Multiple Improvements/addons to Hibernate with Panache

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#4809]
Here are the list of multiple improvements/addons to the Hibernate ORM with Panache extension.

You can find the code here (WIP) https://github.com/quarkusio/quarkus/compare/master...loicmathieu:feat/panache-improvements

### 1. Optional Support: :heavy_check_mark: 
Issues: https://github.com/quarkusio/quarkus/issues/3967 and  https://github.com/quarkusio/quarkus/issues/1368
Proposed implementation:
```
PanacheEntity.maybeFind/findOptionaly(Object id) 
```
Or we can change `findById()` to return an optional and use `getOne/findOneById()` to return the Entity or null, this will be a breaking change but is more understandable

### 2. LockModeType support: :heavy_check_mark: 
Issue: https://github.com/quarkusio/quarkus/issues/2744
Proposed implementation:
```
PanacheQuery.withLock(LockModeType lockModeType);
```

### 3. Query hint: :heavy_check_mark: 
Issue: #3482 and parts of https://github.com/quarkusio/quarkus/issues/3483
Can also resolves #5613
Proposed implementation:
```
PanacheQuery.withHint(String hintName, Object value);
```

We can also add a `PanacheQuery.withFlushMode(FlushModeType flushModeType)` that will complete the coverage of what can be done on a JpaQuery from PanacheQuery.

### 4. Range query :  :heavy_check_mark: 
Issue: https://github.com/quarkusio/quarkus/issues/3870
Proposed implementation:
```
PanacheQuery.range(int startIdx, int lastIdx)
```

### 5. JPA Query: 
Issue: parts of https://github.com/quarkusio/quarkus/issues/3483
Can also resolves #5613 if we don't want to support Query Hints
Proposed implementation:
```
PanacheEntity.find(Query query, String... params)
PanacheEntity.find(Query query, Map<String, Object> params)
PanacheEntity.find(Query query, Map<String, Parameters params)
```
Same for list/stream/delete/count methods
An other implementation will be to support named queries (via @NamedQuery), the implementation could be to lookup if the query string is equals one of the registered named query before using it ...
Or we can do both ;)

### 6. Specification/Example: 
Issues: #3965, #4015 and part of https://github.com/quarkusio/quarkus/issues/2303
Proposed impementation:
```
Person p = new Person();
p.lastName = "Mathieu";
PanacheQuery<Person> mathieus = Person.findByExample(Example.of(p));
```

The implementation can use Example or Specification semantic, or we can directly write `Person.findByExample(p)` if we don't care to enforce a semantic by having a carrier Example/Specification class.
Same for list/stream/delete/count methods

**Comment by emmanuelbernard** [comment]
I tried to offer my comments on the specific issues but there are a couple of general comments that I'll add here.

**Comment by emmanuelbernard** [comment]
@loicmathieu your `JpaOperations` implementation uses `java.beans.Introspector` is something we try and avoid using. It’s a slow framework and brings lots of dependencies. So it's a no no at runtime. Better implement your own or get the one from ORM, Validator or Search.

**Comment by emmanuelbernard** [comment]
## Extensibility of find / list and all Panache query methods.

@FroMage @loicmathieu 
I am foreseeing a general problem of having a lot of overloaded `find`, `list` etc methods.

The original API has been designed to accept strings that are PanacheQL and HQL queries.
But we are seeing requests to support:

- named queries
- typed queries (passing a JPA Query in)
- some weird composable Predicate providers (like Spring Data's Specification thing)

### Named queries

If we accept different types as the first parameter or have a find[WithNamedQuery], findAll[WithNamedQuery] etc, it will become a really hard API to use.

Specifically for named query, I was thinking of accepting the name of the query as part of the first argument of find, list, stream. But there could be [ambiguity](https://www.xkcd.com/327/). So we should have a flag to mark that the query is a named query.

```
#option 1
Country.withNamedQuery().find("Country.findAllWithWeirdQuery").list();
Country.withNamedQuery().list("Country.findAllWithWeirdQuery");

#option 2
if not ambiguous, go for 
Country.list("Country.findAllWithWeirdQuery");

#option3
Force named queries to always use `find` and not have lsit/stream shortcuts and accept
Country.findAsNamedQuery("Country.findAllWithWeirdQuery").list();
```

### Other types

I wonder why people thing it's useful to sue Panache with other types of queries like TypedQuery or some other mode.

Should we make `entityManager()` a method of `PanacheEntityBase` and `PanacheRepositoryBase` and add way more examples of writing a classic query with the JPA APIs as backup? Or is there value in passing a full JPA Query into a Panache method? I guess it is to pass parameters but that's a small improvement.

**Comment by emmanuelbernard** [comment]
@loicmathieu what are the usecase for the new `find(Query query, Map<String, Object> params)?` method you added? It says "Find entities using a JPA query, with optional indexed parameters." but I don't get it.

**Comment by emmanuelbernard** [comment]
Also as I mentioned in the https://github.com/quarkusio/quarkus/issues/2303 I think we should not try and do an example API before we do this one.

**Comment by FroMage** [comment]
We could alternately get rid of ambiguity with `Book.find("#myNamedQuery")` or some such syntax?

**Comment by loicmathieu** [comment]
> @loicmathieu your `JpaOperations` implementation uses `java.beans.Introspector` is something we try and avoid using.

I know, it's a basic implementation to show that it's possible, if we decide to implement Query by example we will need a better implementation.

**Named queries**

I think having `find("Country.findAllWithWeirdQuery") that first try to find an existing named queries then if none is found build a Query is OK. As @FroMage suggested we can use a maker char to avoid the ambiguity if needed.

> @loicmathieu what are the usecase for the new find(Query query, Map<String, Object> params)
I don't understand the question, the use case is the same as all the other find method accepting parameters as a Map<String, Object>.

**Comment by emmanuelbernard** [comment]
I'm doing a clean up of the roadmap for the next 3-6 months, @loicmathieu can you mention what you plan on working on and archive the things already done.
Also a title a bit more specific than multiple improvements / addons would be good.

**Comment by emmanuelbernard** [comment]
my point is that with a specific title we know what the outcome is and we can see it progressing

**Comment by loicmathieu** [comment]
@emmanuelbernard 

> can you mention what you plan on working on and archive the things already done.

There is two improvements still open for proposal : 

- JPA Query support : this can be closed if we decided to only do named query, a prototype is created at #8071 but there is not yet a concensus on the design
- Specification/Example : this one is highly demanded, I can propose a PR for it but you seem to be against it. A lot of people are asking for it and you answer that #2303 can provides the same functionality. According to me it's not the same and #2303 is open for a while and nobody seems to work on it ...

> Also a title a bit more specific than multiple improvements / addons would be good.

The purpose of this issue was to track multiple improvements proposal in a single place. As there is already a lot of those improvements done, and the last two already have specific issue, you can close it if you want.

**Comment by emmanuelbernard** [comment]
Thanks @loicmathieu , on #2303, it's just that I would like for it to be implemented first and tested before we go for the specification/example.

**Comment by emmanuelbernard** [comment]
I'm pretty confident the #8071 will be solved within 3-6 months :) I wonder if you would be ok to give #2303 a try (at implementation) within these 3-6 months? And we can evaluate gaps that would be addressed by Example (or other solutions).

**Comment by loicmathieu** [comment]
> I wonder if you would be ok to give #2303 a try (at implementation) within these 3-6 months?

Why not, but I have something else in my mind that I wanted to implement for Quarkus and implementing #2303 will be a complex task so maybe not in a near future. #2303 will need a parser and I'm a little afraid of some compatibility issues we can have if we use a such parser ... 

I will open an issue for Specification/Example where I will copy all the meaninfull discussion that we have here and link to the 3 existing issues related to it then I close this one.

**Comment by loicmathieu** [comment]
Closed as the remaining discussions around Specification/Criteria, Example, QueryDSL, ... is moved to #8136
