### ISSUE TITLE
Using tooling, platform descriptor should only be downloaded when targeting a different version

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#4822]
**Describe the bug**
When using maven plugin to create a project it downloads the descriptor even if it's the current used version in the plugin:
```
[INFO] --- quarkus-maven-plugin:0.26.1:create (default-cli) @ standalone-pom ---
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-bom-descriptor-json/0.26.1/quarkus-bom-descriptor-json-0.26.1.json
```

**Expected behavior**
Download only if the version is different and maybe have a cache?

**Actual behavior**
Download every time

**Comment by maxandersen** [comment]
if this is resovled in mvn aren't the ~/.m2 working as a cache ?
