### ISSUE TITLE
Jaeger: Initialise metrics in a more automated way - derive from annotations

### ISSUE THREAD

**Issue by objectiser** [quarkusio/quarkus#483]
Currently the metrics, declared using annotations in Jaeger, are manually initialised within Protean.

Ideally would be good to capture the declared metrics from the annotations during build time and use that information to initialise the metrics at runtime.

**Comment by jmartisk** [comment]
This looks like a job for the enhancement I'm currently working on via https://github.com/quarkusio/quarkus/issues/1435 - metrics declared by annotations will be registered automatically during build. I'm currently planning to get that in along with upgrade to SmallRye Metrics 2.0, after that is released (or if there's a requirement to get it in really fast I could backport it to SR-M 1.1.x).

**Comment by gsmet** [comment]
@objectiser @jmartisk what is the status of this one?

**Comment by objectiser** [comment]
@gsmet This is out of date, no longer required. Will close.
