### ISSUE TITLE
HealthChecks and CDI Produces

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#4831]
**Description**

Hi I have developed a Health Check using CDI so the code looks like:

```
@ApplicationScoped
public class HealthChecks {
    @Readiness
    @Produces
    public HealthCheck healthy() {
        return HealthStatus.up("name");
    }
}
```
I have read in this document https://github.com/eclipse/microprofile-health/blob/51c0421ee9ab68742126e98d52ff20542273d2fe/spec/src/main/asciidoc/java-api.adoc that  you can define health checks using CDI producers. 

I don't know exactly if this is mandatory or not regarding the MicroProfile Health Checks spec to have to use @Produces or not in case of Health Checks and CDI, but maybe we could skip this annotation as we are skipping for `@Inject`.

**Implementation ideas**

I think that skipping the `@Produces` annotation should only affect in case of HealthCheck is the return type.

**Comment by manovotn** [comment]
Theoretically we could eliminate the need for `@Produces` **on any methods** if there is at least one CDI qualifier annotation.

However, note that there are also **producer fields** in CDI and in that case we cannot apply this as we already automagically add `@Inject` if we detect any qualifier. Hence it wouldn't be intuitive when you do/don't need `@Produces` overall.

It might make sense for health check alone but then similar argument applies - why can you have a CDI producer methods without it in one case and not in another?

**Comment by mkouba** [comment]
> ...in that case we cannot apply this as we already automagically add @Inject if we detect any qualifier.

Yes, for fields a qualifier without `@Produces` implies an injection point.

> Hence it wouldn't be intuitive when you do/don't need @Produces overall.

We don't add automagically `@Inject` to initializers/setters either.

I'd personally vote for the generic approach + config flag (we have the same for "autoinject") OR nothing. In other words, I don't think it's reasonable to implement this only for health checks.

**Comment by mkouba** [comment]
To sum it up - we could:
1. Allow users to skip `@Produces` for producer methods with at least one qualifier by default (similar to our "autoinject" feature) and make it configurable.
2. Implement a special case for MP Health extension.
3. Do nothing ;-)

I vote for 1). @manovotn @lordofthejars WDYT?

**Comment by lordofthejars** [comment]
I vote for 1 for consistency with the other parts.

**Comment by manovotn** [comment]
I can see why you want 1) but I am not sure it makes the code more readable. TBF, you then have beans such as:

```
    @ApplicationScoped
    public class FooBean {

        // autoinjected field
        @MyString
        String s;

        // producer field
        @Produces
        @SomeQualifier
        Bar bar = new Bar("bar");

        // producer method
        @SomeQualifier
        public FooBarImpl doSomething(Mybean bean) {
            return new FooBarImpl();
        }

        // this is initializer
        @Inject
        public void init(SomeOtherBean someOtherBean) {
            someOtherBean.performFlip();
        }
    }
```

Which to me personally seems hard to read unless you (apart from knowing CDI) also know that Quarkus has these extra few cherries on top that sometimes let you omit an annotation, but then in other cases they require you to specify the very same annotation.

BTW you can make 1) work not just with qualifiers but also with just scope definition.

**Comment by mkouba** [comment]
> BTW you can make 1) work not just with qualifiers but also with just scope definition.

That's a good point.

> Which to me personally seems hard to read unless...

Yes, in this case using the `@Inject` and `@Produces` everywhere makes perfect sense.

On the other hand, the following snippet is IMHO OK:
```java
class Producers {

   @ConfigProperty(name = " foo")
   String foo;
 
   @ApplicationScoped
   MyService produce() {
      return MyService(foo);
   }
}
```

**Comment by manovotn** [comment]
Don't let my scepticism stop you ;-)
If I were to choose between a general approach and a specific for MP extension, then I'd go with the general one as well (which means option 1).

> On the other hand, the following snippet is IMHO OK:

True.

**Comment by mkouba** [comment]
> Don't let my scepticism stop you ;-)

The PR is almost finished :D

**Comment by mkouba** [comment]
Here we go: https://github.com/quarkusio/quarkus/pull/8359
