### ISSUE TITLE
Prepend a slash to a io.quarkus.vertx.web.Route.path if not present

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#4835]
A `Route` path must start with a `/`. So if a user declares `@Route(path = "hello")` Quarkus fails during RUNTIME_INIT. I think we should prepend the slash automatically if not present. For the record - JAX-RS `@Path` can have both values, ie. `@Path("hello")` and `@Path("/hello")`.

**Comment by qrman** [comment]
Hi, can I take this issue?

**Comment by mkouba** [comment]
@qrman Of course, go ahaead! ;-)
