### ISSUE TITLE
HttpAuthenticationMechanism.ChallengeSender.apply - return true instead of null

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#4838]
HttpAuthenticationMechanism.ChallengeSender.apply should probably return `true` instead of `null`

Issue for the discussion https://github.com/quarkusio/quarkus/commit/8f39da48551c27b6e3debc7b5683a704c74f8957#r35642382

**Comment by michalszynkiewicz** [comment]
thanks @rsvoboda !
