### ISSUE TITLE
Ability to use config objects within config sources

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#4848]
**Description**
Advanced config sources (such as [vault](https://github.com/quarkusio/quarkus/blob/master/extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/config/VaultConfigSource.java) or [zookeeper](https://github.com/smallrye/smallrye-config/blob/master/sources/zookeeper/src/main/java/io/smallrye/configsource/ZooKeeperConfigSource.java)) are likely to be configured themselves. It is desirable that those properties be located in the application.properties or other standard config sources (system properties, env), and that the config objects consumed by the advanced config source get built by the framework the usual way.
In the absence of this feature, config sources that require configuration need to fetch it from `ConfigProviderResolver.instance().getConfig().getConfigSources()` (making sure we do not run into recursion) and [redo](https://github.com/quarkusio/quarkus/blob/master/extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/config/VaultConfigSource.java#L153-L190) the parsing and object construction. 

**Implementation ideas**
See this [discussion](https://github.com/quarkusio/quarkus/pull/2897#discussion_r326806133)

**Comment by geoand** [comment]
I remember we had some preliminary discussions around this in the context of supporting a Kubernetes ConfigMap config source.

**Comment by geoand** [comment]
This has already been implemented via the `BOOTSTRAP` Config phase

**Comment by vsevel** [comment]
@geoand FYI I created https://github.com/quarkusio/quarkus/issues/9991 as a result of trying to implement https://github.com/quarkusio/quarkus/pull/9989

**Comment by geoand** [comment]
That is very odd... Thanks for opening the issue @vsevel

**Comment by vsevel** [comment]
another issue associated with the way vault properties get fetched: https://github.com/quarkusio/quarkus/issues/12243
