### ISSUE TITLE
Vert.X route handler not completing/resuming when handling requests

### ISSUE THREAD

**Issue by cristianonicolai** [quarkusio/quarkus#4852]
**Describe the bug**
Apparently router handlers are being paused in https://github.com/quarkusio/quarkus/blob/0.26/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L82, affecting some of the app-specific handlers to not resume once a request is executed.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

**Actual behavior**
Requests to graphql endpoint timeout without response.

**To Reproduce**
1. See router setup in here: https://github.com/kiegroup/kogito-runtimes/blob/master/data-index/data-index-service/src/main/java/org/kie/kogito/index/vertx/VertxRouterSetup.java#L47

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Fedora 30
 - Output of `java -version`: OpenJDK Runtime Environment (build 1.8.0_222-b10)
 - GraalVM version (if different from Java):  19.2.0.1
 - Quarkus version or git rev:  0.26.1

**Comment by cristianonicolai** [comment]
@stuartwdouglas fyi

**Comment by stuartwdouglas** [comment]
We need to wrap the router to have it automatically resume on these routes, @cescoffier we talked about this in Vienna
