### ISSUE TITLE
quarkus-smallrye-fault-tolerance extension should not have a hard dependency to quarkus-smallrye-metrics

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#4857]
**Describe the bug**
When including the `quarkus-smallrye-fault-tolerance` extension, we automatically have the metrics extension as it have a hard dependency to it.

**Expected behavior**
Metrics should be included only if the `quarkus-smallrye-metrics` extension is added in the pom.xml

**Environment (please complete the following information):**
 - Quarkus version or git rev: 0.26 or master

**Additional context**
The Jaeger extension only includes `smallrye-metrics` maybe the same approach can be use to avoid having the metrics extension directly as a dependency. 
But this does not fully solves the issue of having an un-necessary dependency (smallrye-metrics).

**Comment by stuartwdouglas** [comment]
This will need some work in Smallrye, at the moment there is a hard dependency within smallrye itself.

**Comment by loicmathieu** [comment]
@stuartwdouglas will you forward this issue to smallrye?

As I understand, smallrye-fault-tolerance get a MetricRegistry from CDI, so maybe we can add a no-op MetricRegistryto Arc if none already exist. With this we will be able to move the dependency from ` quarkus-smallrye-metrics` to `smallrye-metrics`.

**Comment by jmartisk** [comment]
AFAIU, to get rid of this dependency, we would need to remove all compile-time metric-related dependencies from SmallRye FT and somehow make them optional. Sounds doable, but not very easy.

I'm starting to realize that if we really want to unify the way extensions register metrics, this will, among other things, need a unified strategy in all SmallRye projects that would be compatible with the Quarkus strategy. The problem is when metrics are registered directly by the SmallRye project's code, then we can't reasonably use any sort of Quarkus-specific `MetricBuildItem` or whatever we want to do.
CC @Ladicek

**Comment by Ladicek** [comment]
Currently, the MicroProfile Fault Tolerance spec requires all implementations to publish metrics. It also defines a a switch that can be used to turn metrics off (`MP_Fault_Tolerance_Metrics_Enabled`). There's a noop metrics collector in SmallRye Fault Tolerance already, which is used when the config property it set to `false`, so there should be nothing preventing the Quarkus extension to selectively enable/disable metrics.

**Comment by loicmathieu** [comment]
@Ladicek so this switch must be turned off on the build if the Quarkus metrics capability is not present ?
Let me try this

**Comment by loicmathieu** [comment]
@Ladicek even if the metrics are turned off smallrye inject the metrics factory in [MetricsCollectorFactory.java](https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/src/main/java/io/smallrye/faulttolerance/metrics/MetricsCollectorFactory.java#L39) so we have a `javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.eclipse.microprofile.metrics.MetricRegistry and qualifiers [@Default]`

**Comment by loicmathieu** [comment]
@Ladicek @jmartisk by switching the config OFF and providing a NOOP Metrics Registry it works, not very elegant, but it works: https://github.com/quarkusio/quarkus/compare/master...loicmathieu:fix/smallrye-metrics-depdendency

If you think it's OK I can prepare a PR (more tests and some cleanup needed).

**Comment by Ladicek** [comment]
Ah, true. I'm looking into SmallRye FT and there's quite a lot of places that refer to the `MetricRegistry` class. It would require some amount of (boring) work to abstract that out. I think that providing a noop implementation of `MetricRegistry` is easiest, but you will only get rid of the SmallRye Metrics dependency. You will still need MicroProfile Metrics present.

**Comment by loicmathieu** [comment]
@Ladicek currently I only get rid of `quarkus-smallrye-metrics` and it's fine as a first step because it means that the metrics extension will not be enabled anymore when adding the fault-tolerance one.
I try by removing the depdendency to `smallrye-metrics` and it seems to works (but it should not ...).
As I said, I need more testing/polishing, but I will do it only if you think this is the good approach ...

**Comment by Ladicek** [comment]
I think the approach is OK. WDYT @jmartisk?

**Comment by jmartisk** [comment]
Sounds good. I didn't quite check whether SR-FT does anything more than just inject the `MetricRegistry` and call its methods, in which case the no-op registry trick might not be enough just by itself, but perhaps it will. 
We will still include the MP Metrics API in applications (or part of it, perhaps dead code elimination will do some work) but it's the best we can do for the moment, I guess

**Comment by loicmathieu** [comment]
OK, cool, I will do some testing and cleanup and open a PR for this.
