### ISSUE TITLE
Jaeger: Obtain Jaeger version to be returned for use in trace tag

### ISSUE THREAD

**Issue by objectiser** [quarkusio/quarkus#486]
Currently just return a blank string from a substituted method for the `JaegerTracer` class. This information is normally found in a file - so need to get this information during build stage and make it available to the runtime stage.

**Comment by gsmet** [comment]
@objectiser any chance we could make progress on this? That would be one less issue :)

**Comment by objectiser** [comment]
@gsmet Another one out of date - will close.

**Comment by gsmet** [comment]
Thanks!
