### ISSUE TITLE
Provides Jackson Java 8 modules with quarkus-jackson

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#4860]
**Description**
Quarkus provides Jackson 2 capabilities via the `quarkus-jackson` extension.
Jackson 2 is Java 7 compatible and specific Java 8 data types needs to be registred via the following [Java 8 modules](https://github.com/FasterXML/jackson-modules-java8): 

- com.fasterxml.jackson.datatype.jsr310.JavaTimeModule: for Java DatTime API
- com.fasterxml.jackson.datatype.jdk8.Jdk8Module: for Optional
- com.fasterxml.jackson.module.paramnames.ParameterNamesModule: to avoid `@JsonProperty` on constructor and creator methods (if compiled with `-parameters` javac option)

Using the two first modules is very frequent, so it is a pitty that each developers wanting to use Jackson with Quarkus has to add them manually. It can also leads to issues when migrating from JsonB to Jackson as JsonB correctly handle these types by defaults.

**Implementation ideas**
Add **JavaTimeModule** and **Jdk8Module** and document them, they are small and when we will migrate to Jackson 3 they will be included by default.

Don't inlcude the ParameterNamesModule by default as it needs a compiler option so it's usage is less frequent.

I can provide a PR for this :)

**Comment by gsmet** [comment]
I think it makes sense.

As for the `PamareterNamesModule`, our project template now enables `-parameters` so it might make sense too. If it doesn't have weird compatibility issues.

**Comment by loicmathieu** [comment]
OK, I will prepare a PR for this that includes the `PamareterNamesModule`.
I will double check the `PamareterNamesModule` ...
