### ISSUE TITLE
Add annotation to ignore classes

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#4862]
Some users (@alesj, for example) have a need to declare a class that should be ignored by the Quarkus extensions, even though they would otherwise be auto-detected and incorporated in the application.

In his example, he has an implementation of a JAX-RS interface that is only used internally and should not be exposed, but JAX-RS would automatically expose it.

CDI has `@Vetoed` to achieve the same result, but it's spec-dependent. JUnit has `@Ignore` in 4, and `@Disabled` in 5.

We could add a global annotation that would make every extension ignore such annotated beans, cross-spec. Perhaps it's as simple as filtering them out from our indexes?

There could be a use-case for a per-spec annotation too (such as `@Vetoed` for CDI) but I'm not sure there is, ATM.

Note: this is >1.0

**Comment by geoand** [comment]
This can essentially be done via https://github.com/quarkusio/quarkus/blob/2.7.1.Final/core/deployment/src/main/java/io/quarkus/deployment/configuration/ClassLoadingConfig.java#L74.
