### ISSUE TITLE
gradle testNative ignores *IT tests

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#4881]
**Describe the bug**
When I run `gradle testNative` in a Quarkus Gradle project, the `NativeGreetingResourceIT` test is not executed.

**Expected behavior**
IT test is executed

**Actual behavior**
It is not executed. It does execute if I rename to `NativeGreetingTest`.

**To Reproduce**
1. 
```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=org.acme -DprojectArtifactId=foo -DclassName="org.acme.quickstart.GreetingResource" -Dpath="/hello" -Dextensions="resteasy" -DbuildTool=gradle
```

2. `gradle buildNative --docker-build=true testNative`

**Additional context**
If I rename the test inside the `native-test` directory to `NativeGreetingResourceTest` it works

**Comment by geoand** [comment]
Weird... I specifically remember seeing tests being run and failing. Do you have a fix ready or should I take a look at it?

**Comment by gastaldi** [comment]
Nope, it's up for grabs :)  BTW have you been able to reproduce it using the steps I mentioned above?

**Comment by geoand** [comment]
I'll give it a shot and let you know

**Comment by geoand** [comment]
I can see the tests being executed (basically what I did is change the code to make the test fail and it did as expected).
What makes you think they don't run?

**Comment by gastaldi** [comment]
If you look at https://github.com/quarkusio/quarkus/pull/4579, the `NativeGreetingResourceTest` is not displayed in the console if you rename it to `NativeGreetingResourceIT`

**Comment by geoand** [comment]
I executed: `./gradlew clean buildNative  --docker-build=true testNative  --console=plain` on the created project (after editing the test to make it fail) and got:

```
> Task :clean
> Task :compileJava
> Task :processResources
> Task :classes
> Task :jar

> Task :quarkusBuild
building quarkus runner

> Task :assemble

> Task :buildNative
building native image

> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :compileNativeTestJava
> Task :processNativeTestResources NO-SOURCE
> Task :nativeTestClasses
> Task :quarkusTestConfig

> Task :testNative

org.acme.quickstart.NativeGreetingResourceIT > testHelloEndpoint() FAILED
    java.lang.AssertionError

1 test completed, 1 failed

> Task :testNative FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testNative'.
> There were failing tests. See the report at: file:///home/gandrian/Desktop/foo/build/reports/tests/testNative/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 7s
10 actionable tasks: 10 executed
```

If I revert the change to the test I get:

```
> Task :clean
> Task :compileJava
> Task :processResources
> Task :classes
> Task :jar

> Task :quarkusBuild
building quarkus runner

> Task :assemble

> Task :buildNative
building native image

> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :compileNativeTestJava
> Task :processNativeTestResources NO-SOURCE
> Task :nativeTestClasses
> Task :quarkusTestConfig
> Task :testNative

BUILD SUCCESSFUL in 1m 16s
10 actionable tasks: 10 executed
```

So I am not sure what else to do about this.

**Comment by gastaldi** [comment]
Hm, maybe I got confused because the test was not being shown in the console. I'll close the issue for now. Thanks for checking and sorry about the confusion

**Comment by geoand** [comment]
Not a problem at all! The more scrutiny on this better :)
