### ISSUE TITLE
ResponseExceptionMapper with @Provider annotation not automatically used

### ISSUE THREAD

**Issue by svinther** [quarkusio/quarkus#4886]
It is only possible to register a ResponseExceptionMapper by either:

- Use a custom RestClientBuilder and invoke RestClientBuilder.register()
- Annotate a resource with @RegisterProvider

The last option causes warnings being logged, such as

`WARN  [org.jbo.res.res.i18n] (vert.x-worker-thread-0) RESTEASY002160: Provider instance org.acme.MyResponseExceptionMapper is already registered.  2nd registration is being ignored.
`

**Expected behavior**
As an ExceptionMapper with @Provider annotation is picked up automatically, so should ResponseExceptionMapper

**Actual behavior**
ResponseExceptionMapper with @Provider annotation is ignored

**To Reproduce**
Here is a simple example project https://github.com/svinther/Quarkus-ExceptionResponseMapper

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Linux hp 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

 - Output of `java -version`: 
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```
 - Quarkus version or git rev:  `0.26.1`

**Comment by geoand** [comment]
@gastaldi what was your conclusion about this one?

**Comment by gastaldi** [comment]
I think the current behavior is correct and `@Provider` is not supposed to work in this case. At least the spec does not mention anything about it: https://github.com/eclipse/microprofile-rest-client/blob/master/spec/src/main/asciidoc/providers.asciidoc, but I may be missing something. Thoughts @kenfinnigan ?

**Comment by kenfinnigan** [comment]
It's not clear from the spec, but I do believe that because `ResponseExceptionMapper` is specific to MP REST Client that JAX-RS doesn't understand the class which is why `@Provider` doesn't work.

So it needs to be activated by either `@RegisterProvider` on the interface or `RestClientBuilder.register()`

**Comment by kenfinnigan** [comment]
I'm going to close as I don't think this is a bug.

Please reopen if it's proven otherwise
