### ISSUE TITLE
Add support for Vault Transit Engine

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#4888]
**Description**
The [transit engine](https://www.vaultproject.io/docs/secrets/transit/index.html) provides encryption as a service for a client application. Instead of storing your encryption key securely, and retrieve it from your application to apply the encrypt/decrypt algorithm locally, you delegate this to vault: You just ask vault to create a key and associate it with a name that you pass, then use the encrypt and decrypt services from vault passing just the key name. That way you do not have to embed the encryption algorithms in your app, and the encryption key never leaves the vault.
Encrypting/Decrypting sensitive data that need to be stored in a primary store is a very common use case. This would bring value to quarkus to make that feature available and usable with ease.

**Implementation ideas**
This should be similar to `VaultKVSecretEngine`, with methods:
```
public byte[] encrypt(byte[] optionalContext, byte[] data);
public byte[] decrypt(byte[] optionalContext, byte[] data);
public byte[] rewrap(byte[] optionalContext, byte[] data);
```
In the vault api, it is also possible to pass a batch of data. It is probably a good idea to support this as well.
`optionalContext` needs to be passed if key derivation is enabled. 
We might provide also simple signatures for the usual case, such as:
```
public String encrypt(String data);
public String decrypt(String data);
```
In that case we would just use `UTF-8` to get bytes out of this string.
`data` would be required to be non-null.

**Comment by michael-schnell** [comment]
The Spring Vault integration does offer similar functionality and more:

https://docs.spring.io/spring-vault/docs/current/api/org/springframework/vault/core/VaultTransitOperations.html

Would be great to have something like that in Quarkus. The above interface should be a good starting point.

**Comment by sberyozkin** [comment]
@michael-schnell In general our approach is to make things simple for the users. That interface is just probably a 1 to 1 mapping with the Vault API but most of those operations won't probably make much sense for example for the JAX-RS code having to do something with Vault in  scope of the current request. All those key creation operations for example, etc

**Comment by sberyozkin** [comment]
@vsevel, having something like 
```
public String encrypt(String data);
public String decrypt(String data);
```
would be just perfect IMHO, and also
```
public byte[] encrypt(byte[] optionalContext, byte[] data);
public byte[] decrypt(byte[] optionalContext, byte[] data);
```
as well as `sign`/`verify`.

But what is this `optionalContext` ? How can a user code calculate it ?

The other question is about `rewrap`. I guess that all the operations that the user code itself can not easily enough implement itself in context of the current call should be managed by the transit engine implementation ? Example, given the interface linked to by @michael-schnell, may be the rotate(), rewrap(), various key manipulation operations, can be done seamlessly and may be controlled by some properties ?

**Comment by vsevel** [comment]
@sberyozkin I agree we should start with a minimum of the most userful methods on the service.

I did not mention `rotate` because I think that this would not be used in a typical quarkus application. To me, it is more an administrative task.

I included `rewrap` in the proposition because I was thinking that a developer team might decide to write a job as a quarkus application to reencrpyt all data from, say, their database for instance. And that would be considered a development task, rather than an administrative task. Some organizations may disagree with this.

For `optionalContext` the documentation says:

> Key derivation is supported, which allows the same key to be used for multiple purposes by deriving a new key based on a user-supplied context value. In this mode, convergent encryption can optionally be supported, which allows the same input values to produce the same ciphertext.

So if you had a database with a Person and a CreditCard tables, you could use the same transit engine key `transit/mykeys/myapp`, and passing context `Person` when you want to encrypt person data, or `CreditCard` in the second case. That way you can encrypt all your sensitive data with different keys, but always using the same transit engine key. That is the way I understand it.

**Comment by michael-schnell** [comment]
Why not just migrate the Spring Boot code with the missing functions to Quarkus? I don't think there is much effort associated with this. The Spring code is already there, why should we try to reinvent the wheel?

**Comment by michael-schnell** [comment]
Maybe I could pick up this task and try to migrate the stuff next weekend.

**Comment by vsevel** [comment]
hello @michael-schnell,

When creating the vault extension, this has been a design goal to provide a higher level set of services for the most common use cases, and make them very easy to use for the typical client application.

There has been also some discussions in the context of https://github.com/quarkusio/quarkus/pull/2897 to provide as well a _vault client_, much like [VaultClient](https://github.com/quarkusio/quarkus/blob/master/extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/client/VaultClient.java) or for instance the whole quarkus kubernetes-client. 

Eventually we settled on keeping the VaultClient an implementation detail at this point, and not pushing it too soon into the api. The idea was to make the extension useful first, and not necessarily exhaustive at this point.

The interface you are referring to would find its place in a vault-client extension, or in the vault extension itself, but as a list of separate interfaces. Note also that when working at the client level, we must pass the client token (which I do not see in the spring interface - do you know how it is being specified ? - is it something that is part of the app context?), as it is part of the api. I would not want to hide that because when we are working at the client level, the user should have full control (including passing a specific client token).

What are the services you believe are absolutely necessary?

FYI I have created https://github.com/vsevel/quarkus/tree/transit to start experimenting.

cc @sberyozkin

**Comment by sberyozkin** [comment]
@michael-schnell I disagree. The simplicity is the key for Quarkus.

**Comment by sberyozkin** [comment]
@vsevel, "Eventually we settled on keeping the VaultClient an implementation detail at this point, and not pushing it too soon into the api. The idea was to make the extension useful first, and not necessarily exhaustive at this point." - yes, this is nicely summarized. 

Perhaps we can start considering making a complete `VaultClient` available as well, but I'd really consider an enhancement like that one be part of the separate enhancement request, and ideally, once the users actually start saying that without it they can't work with Vault :-)

I agree with @michael-schnell in that some users may want that kind of complexity/completeness, but I'd be cautious about giving the users the API where most of it won't be directly required for them.

**Comment by michael-schnell** [comment]
I think the minimum to implement are the non-admin functions:

```
Plaintext decrypt(String keyName, Ciphertext ciphertext)
List<VaultDecryptionResult> decrypt(String keyName, List<Ciphertext> batchRequest)
String decrypt(String keyName, String ciphertext)
byte[] decrypt(String keyName, String ciphertext, VaultTransitContext transitContext)
String encrypt(String keyName, byte[] plaintext, VaultTransitContext transitRequest)
List<VaultEncryptionResult> encrypt(String keyName, List<Plaintext> batchRequest)
Ciphertext encrypt(String keyName, Plaintext plaintext)
String encrypt(String keyName, String plaintext)
VaultTransitKey getKey(String keyName)
List<String> getKeys()
Signature sign(String keyName, Plaintext plaintext)
Signature sign(String keyName, VaultSignRequest request)
boolean	verify(String keyName, Plaintext plaintext, Signature signature)
SignatureValidation verify(String keyName, VaultSignatureVerificationRequest request)
```
The rest is not necessary for simple use cases.

**Comment by vsevel** [comment]
@sberyozkin I have created a new [post](https://groups.google.com/d/msg/quarkus-dev/2QNHq_9j5os/njmAQnDPBAAJ) in the quarkus-dev google group to get some feedback.

**Comment by sberyozkin** [comment]
@michael-schnell Thanks, IMHO this looks good, indeed, that is pretty much what Vincent and myself came to a general agreement about, make it easy for the users to adopt Vault API fast, and in due time, Vincent's complete VaultClient API can be expanded and exposed publicly if required. We hope to make it nearly trivial for the users to work with Vault, and Vincent did a lot of work with the original PR to support this strategy

**Comment by michael-schnell** [comment]
@sberyozkin Sounds good, I think the admin stuff is indeed not a primary focus. 
@vsevel I saw you've already started implementing it with #5147 Cool!
