### ISSUE TITLE
Improving the BindAddress error

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4890]
i often see in labs people hitting a BindAddress problem. They tend to blame Quarkus but it is invariably :

- another process running in the same port (usually the http port)
- sometimes a different Quarkus instance running 

We could improve the situation by : 
1. being more explicit in the exception (handling) and proposing ways to discover the culprit process (commands to run)
2. Try and find the process ourselves depending on the OS: something like Process 1234 - myFavAV already uses this port

**Comment by geoand** [comment]
I had people tell me that they wanted Quarkus to use a random port when there were clashes. The basic use case they mentioned was to easily run multiple Quarkus apps in Dev mode without having to configure anything.

**Comment by emmanuelbernard** [comment]
Well we could offer something like

```
quarkus.http.port=8080
quarkus.http.port.on-conflict=one-up
```

Which we could default to `fail` in prod and either `fail` or `one-up` 
in dev (to be discussed).

But that's a separate issue. My concern is that people will hit the old 
port and find it confusing until they go read the logs.

**Comment by 38leinaD** [comment]
I think "quarkus.http.port.on-conflict=one-up" will not help people that are confused about a port bind exception. Instead, they will now be confused that the app is not running on port 8080 as shown in all documentation and tutorials.
But it is a good idea to have this option to be able to easily start multiple instances.

**Comment by gastaldi** [comment]
AFAIK you can run Quarkus in a random port by using: 

```
quarkus.http.port=0
```

**Comment by famod** [comment]
I really wished @harthorst and I had more diagnostic output earlier today when we ran into #9889.
Even with DEBUG logging it was not obvious which port Qaurkus tried to acquire, which is especially annoying when you have both http and https ports.

**Comment by jaikiran** [comment]
In the long term, I think (only) in dev and test mode of Quarkus, we should evaluate setting the `jdk.includeInExceptions` security property to have the `hostInfo` value. This property is supposed to be used for the following (see `java.security` file of your JDK installation for more details):
```
#
# Enhanced exception message information
#
# By default, exception messages should not include potentially sensitive
# information such as file names, host names, or port numbers. This property
# accepts one or more comma separated values, each of which represents a
# category of enhanced exception message information to enable. Values are
# case-insensitive. Leading and trailing whitespaces, surrounding each value,
# are ignored. Unknown values are ignored.
#
# NOTE: Use caution before setting this property. Setting this property
# exposes sensitive information in Exceptions, which could, for example,
# propagate to untrusted code or be emitted in stack traces that are
# inadvertently disclosed and made accessible over a public network.
#
# The categories are:
#
#  hostInfo - IOExceptions thrown by java.net.Socket and the socket types in the
#             java.nio.channels package will contain enhanced exception
#             message information
#
# The property setting in this file can be overridden by a system property of
# the same name, with the same syntax and possible values.
#
#jdk.includeInExceptions=hostInfo
```




We (Quarkus) can do this by passing a security properties file when we launch the JVM in dev mode and test mode. As per the JDK documentation, it can be done as follows:
```
An alternate java.security properties file may be specified
# from the command line via the system property
#
#    -Djava.security.properties=<URL>
#
# This properties file appends to the master security properties file.
# If both properties files specify values for the same key, the value
# from the command-line properties file is selected, as it is the last
# one loaded.
```

I say this as a long term thing because right now, for the `BindException` that we are talking about here, this property currently doesn't work. However, there's some interest in supporting it and is being tracked at https://bugs.openjdk.java.net/browse/JDK-8247413

**Comment by sladyn98** [comment]
@gastaldi @geoand This has an open PR ? is it still being worked on @38leinaD or can I take this up and complete it ?

**Comment by gastaldi** [comment]
@sladyn98 I believe this is resolved in https://github.com/quarkusio/quarkus/pull/4947 but the PR needs to be rebased and reviewed

**Comment by famod** [comment]
#4947 only addresses devmode which is a good start but I think the regular mode should be addressed as well.

**Comment by geoand** [comment]
I personally have no idea what the status of the PR is so suggest you sort it out amongst the two of you :)

**Comment by sladyn98** [comment]
Okay Ill just pick up another issue https://github.com/quarkusio/quarkus/issues/6531

**Comment by 38leinaD** [comment]
I have tried rebase with the latest Quarkus master code, but exception seems now to be caught before DevModeMain; so my old code does not work anymore. I now identified this spot where i can check for the BindException: https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/dev/IsolatedDevModeMain.java#L128
Unfortunately, here i am not able to read out the port via `ConfigProvider.getConfig().getOptionalValue("quarkus.http.port", Integer.class)`
Getting `java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype`

Can someone guide me on this? Where is the best place to put this logic; and if this is a good place, how to gain access to the port-number?

**Comment by geoand** [comment]
@38leinaD have you tried obtaining the config before the TCCL is changed at https://github.com/quarkusio/quarkus/blob/f47484f8af41704d41ec9bc897d582e31e33de5d/core/deployment/src/main/java/io/quarkus/deployment/dev/IsolatedDevModeMain.java#L117 ?

**Comment by geoand** [comment]
And if all else fails, you might want to look into `ConfigInstantiator`

**Comment by amitrajpushkar** [comment]
i want to contribute in this project how can i fix them

**Comment by 38leinaD** [comment]
@amitrajpushkar Feel free to take this issue if you like. I am simply not getting to this issue currently.
You can have a look what i did in the old PR. Also, the TCCL hint from @geoand works.
