### ISSUE TITLE
The character set encoding of static HTML file is changed

### ISSUE THREAD

**Issue by yuhaibohotmail** [quarkusio/quarkus#4891]
**Describe the bug**
When browsing from a browser, the character set encoding of static HTML file is changed  in version 0.24 or higher.
But working fine in version 0.23.2 or lower.

![image](https://user-images.githubusercontent.com/48646226/67620490-2ab7f000-f83a-11e9-8623-7731a0200865.png)

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
![023 2](https://user-images.githubusercontent.com/48646226/67620496-53d88080-f83a-11e9-87f8-9f220c57248c.png)

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
![0 26 1](https://user-images.githubusercontent.com/48646226/67620508-75d20300-f83a-11e9-88a4-7bf82309b0f3.png)

**To Reproduce**
1. Create an HTML file  containing Chinese characters;
2. Copy the file to the directory : main/resources/META-INF/resources;
3. Run project and browsing from a browser.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:   windows 10 
 - Output of `java -version`:  1.8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:   0.24 , 0.25, 0.26.1

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@yuhaibohotmail can you try with this PR: https://github.com/quarkusio/quarkus/pull/4892 ?

**Comment by yuhaibohotmail** [comment]
It worked，Thanks!
