### ISSUE TITLE
0.26.1 is missing wiring-classes/bootstrap file

### ISSUE THREAD

**Issue by Ravisankar-Challa** [quarkusio/quarkus#4894]
0.26.1 is missing wiring-classes/bootstrap file. I have been using that for AWS lambda bootstrap. Will you reconsider enabling wiring-classes/bootstrap

**Comment by geoand** [comment]
cc @justinlee

**Comment by oztimpower** [comment]
This is the commit that removed the file from extensions/amazon-lambda/src/main/resources/bootstrap (yet adding it back doesn't get it back to your build path):

archetype and bugfix	1a5161a2d	Bill Burke <bburke@redhat.com>	24 Oct 2019 at 6:04 AM

**Comment by stuartwdouglas** [comment]
CC @patriot1burke

**Comment by Ravisankar-Challa** [comment]
With this commit https://github.com/quarkusio/quarkus/pull/4951 there is no need for wiring-classes/bootstrap. So closing the issue.

**Comment by Ravisankar-Challa** [comment]
With this commit https://github.com/quarkusio/quarkus/pull/4951 there is no need for wiring-classes/bootstrap. So closing the issue.
