### ISSUE TITLE
Graylog log management

### ISSUE THREAD

**Issue by viniciusfcf** [quarkusio/quarkus#4908]
**Describe the extension**
With distributed systems, centralized logs are required to unify everything. Otherwise, it is impossible to manage the scale.

Graylog is a great open source log management. 

Java client lib is: https://github.com/mp911de/logstash-gelf

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
```properties
level=(INFO, DEBUG...)
protocol=(UDP,TCP)
host=localhost
port=12201
gelfVersion=1.1
extractStackTrace=true
filterStackTrace=true
timestampPattern=yyyy-MM-dd HH:mm:ss
maximumMessageSize=8192(UDP datagrams are usually limited to a size of 8192 bytes)
additionalFields=fieldName1=fieldValue1,fieldName2=fieldValue2
additionalFieldTypes=fieldName1=String,fieldName2=Double,fieldName3=Long


```

**Additional context**
(Add any other context about the proposal here.)

**Comment by loicmathieu** [comment]
JSON loggin is already implemented bu not yet merged : #4121 maybe this will allow to send logs to graylog more easily.

**Comment by viniciusfcf** [comment]
> JSON loggin is already implemented bu not yet merged : #4121 maybe this will allow to send logs to graylog more easily.

Probably will not work with graylog. Graylog is able to accept and parse RFC 5424 and RFC 3164 compliant syslog messages and supports TCP transport with both the octet counting or termination character methods. UDP is also supported and the recommended way to send log messages in most architectures.

**Comment by loicmathieu** [comment]
@viniciusfcf you can already use syslog, it's supported.
JSON logging will allow you to write GELF format right ? But if you want to directly send the log event to graylog, right, I don't think it's possible yet ...

Did you try if this library is working on Quarkus: https://marketplace.graylog.org/addons/7ea104bd-519d-4140-a396-ff962314415e ? It seems that it allows to send logs to graylog from a lot of logging backend

**Comment by viniciusfcf** [comment]
Hi @loicmathieu. This library is the same of https://github.com/mp911de/logstash-gelf (I linked on my first post). Probably will work. I'm using it in other projects without quarkus.

I'm not sure JSON logging will alow me to write GELF format, I will try to test it.

I'm trying to undestand what define if a "extension proposal" is a good one. Just be usefull on distributed systems? 

The final purpose of a new extension configure it using application.properties and generate the native file?

**Comment by loicmathieu** [comment]
@viniciusfcf an extension is needed to include the framework/component/technology used inside the global configuration mechanism, to provides CDI beans if needed, and to have some native image customization/fixes if the third party library didn't works out of the box on GraalVM native image.

Anyway, please give us feedback on your tests we can then decide if we need to create a specific extension or if we just need to add some section on the logging guide.

**Comment by loicmathieu** [comment]
@viniciusfcf I made some test and as you need a special handler to send logs to Graylog and that there is currently no way to set the handler used by Quarkus logging, yes, it needs an extension.

Based on the works made by @dmlloyd on it's json logging PR I was able to build a graylog extension. It still needs polishing, documentation and testing but as soon as #4121 is merged I will be able to provides a graylog extension quickly.

I will try to make it also works with logstash to covers both Graylog and ELK.

**Comment by viniciusfcf** [comment]
Great. I saw logstash-gelf code and their main classes probably are: GelfLayout and GelfMessage (Really is a json message), and the Senders (HTTP, REDIS, Kafka...)
