### ISSUE TITLE
Offer a way to blacklist GraalVM metadata from JARs

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4919]
Some dependencies define GraalVM metadata in `MANIFEST`. But some goes against possible optimization of Quarkus. We need a mechanism to blacklist GraalVM metadata for specific dependencies.

**Comment by geoand** [comment]
@galderz IIRC there is now some way to do this?

**Comment by Sanne** [comment]
> @galderz IIRC there is now some way to do this?

was about to ask the same :) We'll need it for #19055

**Comment by galderz** [comment]
Hmmmm, I've added https://github.com/oracle/graal/pull/3179 (part of 21.1 onwards), which allows graalvm to exclude the configuration from certain resources within jars. However, I'm not sure if this is exactly what @emmanuelbernard was asking when talking about `MANIFEST`.

**Comment by Sanne** [comment]
Related: #21069 

And since that one is more specific and @galderz already solved oracle/graal#3179 I think we're good - closing this one.
