### ISSUE TITLE
Handle forwarded headers

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#4922]
When sitting behind a forwarding proxy (that has always been the case for my apps at least) we cannot trust the underlying TCP connection for the remote IP and current port, nor the HTTP `Host` header, so the information we expose to users is wrong. The impact is they cannot use JAX-RS `UriInfo` to build absolute URIs nor `HttpResponse.getRemoteAddress()` to log security violations, nor can they know if the current connection is encrypted.

We should read the https://tools.ietf.org/html/rfc7239#section-4 `Forwarded` header and the older equivalent headers to make sure the information we expose to users is accurate.

I would be tempted to say this is of the highest priority, but the fact that nobody noticed this before probably means deployments these days either don't use forwarding proxies, or mitigate their effects using alternative strategies.

**Comment by FroMage** [comment]
As noticed in https://github.com/quarkusio/quarkus/pull/4907#issuecomment-546870817

**Comment by stuartwdouglas** [comment]
I think we should be able to just stick this in the RoutingContext under some well key, and then RESTEasy and Undertow can be modified to look at this key for the remote address. 

All this code existing in Undertow already, so it should be pretty simple.

**Comment by lodrantl** [comment]
This setting work with vertx http, but as soon as quarkus-undertow is added it breaks. Maybe just the ForwardedHandler should be added to the deployment?

**Comment by stuartwdouglas** [comment]
This is a bug that will be fixed by https://github.com/quarkusio/quarkus-http/pull/20

For now you can use the forwarded handler as a workaround.

**Comment by lodrantl** [comment]
I tried with the master version of quarkus-http and nothing changes. X-Forwarded-Proto and X-Forwarded-Port are used correctly, but X-Forwarded-Host is just disregarded completely. Tracked it down to getHostandPort() method in HttpServerExchange.java.
https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/HttpServerExchange.java#L646

The ForwardedHandler from Undertow actually overwrites the Host field with the X-Forwarded-Host internally. 
https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/handlers/ForwardedHandler.java#L55
