### ISSUE TITLE
Quarkus:dev does not detect property change between compilation and start

### ISSUE THREAD

**Issue by Mefl** [quarkusio/quarkus#4928]
**Describe the bug**
Si you don't do mvn compile quarkus:dev but you do in 2 command, therefore 
1/ mvn compile
2/ mvn quarkus:dev

Any property change between the 2 operations is not detected, and the app start with the compiled value of properties.

**Expected behavior**
changing `quarkus.datasource.url` property :
1/ edit application.properties to put bad port number (543555)
2/ mvn clean compile
3/ edit application.properties to put good port number (5435)
4/ mvn quarkus:dev
-> start in error because it try to connect on 543555 port.
5/ mvn clean compile
6/ mvn quarkus:dev
-> start succesfully because the file is with good number

**Actual behavior**
changing `quarkus.datasource.url` property :
1/ edit application.properties to put bad port number (543555)
2/ mvn clean compile
3/ edit application.properties to put good port number (5435)
4/ mvn quarkus:dev
-> app should start with the 5435 port in jdbc url.

**Environment (please complete the following information):**
Java version: 13, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/jdk-13+33/Contents/Home
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"

**Additional context**
@emmanuelbernard the pb I showed you.

**Comment by geoand** [comment]
I you plan on using such a workflow often, the easy solution to this problem would be to just always do `mvn clean quarkus:dev`

**Comment by geoand** [comment]
Sorry, I closed it by accident...

**Comment by emmanuelbernard** [comment]
It's not a high priority bug but I was wondering why quarkus:dev was thinking there was no change in that case.

**Comment by geoand** [comment]
I'll take a look soon and see if there is an easy way to get it done

**Comment by geoand** [comment]
So basically the change to `application.properties` isn't picked up because the dev mode doesn't have a previous "last modified time" to compare with.
I assume for this very special case the dev mode could compare the "source" with the "target" since in this very special case they should be the same.

**Comment by stuartwdouglas** [comment]
There is a related problem with remote dev mode, in that if the container starting state is not the same as the local starting state things can get out of sync. 

Until we do the first run we don't actually have a list of hot deployment related files so we can't just check them before startup. We could hard code something for application.properties but that kinda sucks

**Comment by stuartwdouglas** [comment]
This is fixed now, as we auto compile when running quarkus:dev
