### ISSUE TITLE
Make new platform resolver code work in native app

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#4941]
I've tried to setup Code Quarkus to compile to native with master and the new resolver. It always misses some classes:
https://github.com/quarkusio/code.quarkus.io/pull/194/

The reflection file is there:
https://github.com/quarkusio/code.quarkus.io/pull/194/files#diff-92f9ada386b472dc5e9b8b6990b7a8a7

To reproduce:
```
$ make native
// Then
$./target/code.quarkus.io-1.0.0-runner  
```

**Comment by ia3andy** [comment]
@aloubyansky could you help make it work?

**Comment by ia3andy** [comment]
Once this is running, you need to make sure you can generate applications using the running webapp.

**Comment by emmanuelbernard** [comment]
Btw unrelated but @ia3andy you should not use the reflection object and instead write extensions to do that work :)

**Comment by ia3andy** [comment]
@emmanuelbernard yes for sure, I just never took the time to actually do it 😬

**Comment by ia3andy** [comment]
I created an issue for it: https://github.com/quarkusio/quarkus/issues/4944
