### ISSUE TITLE
Oidc Client roles

### ISSUE THREAD

**Issue by mathianasj** [quarkusio/quarkus#4946]
**Description**
It would be nice to be able to utilize the client roles in addition to the realm roles.

**Implementation ideas**
I would recommend the ability to provide custom role mappings from the jwt claims or perform flat map so you could use the client roles too.

**Comment by stuartwdouglas** [comment]
You can do this programatically using io.quarkus.security.identity.SecurityIdentityAugmentor. Create a CDI bean that implements this interface, inject the JsonWebToken, and you can modify the role set to whatever you want based on the token.

**Comment by sberyozkin** [comment]
@mathianasj In addition to what Stuart said, I think we just did it implicitly, see this [test resource](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/test/resources/tokenKeycloakResourceAccess.json#L16).
Is it what you had in mind ?
CC @pedroigor Hi Pedro, you mentioned there could be more enhancement applied there, please type a token example to show what can be enhanced.

**Comment by pedroigor** [comment]
I think this should be covered by what you did. @mathianasj do you need client roles other than those related with the client_id used by the application ?

**Comment by mathianasj** [comment]
I think that is doing exactly what I was looking for I will test it out when I’m back at a computer

**Comment by sberyozkin** [comment]
@mathianasj FYI, `0.27.0` is out, give it a try please

**Comment by sberyozkin** [comment]
@mathianasj I hope it all works good for you now. Please reopen if not; thanks

**Comment by mathianasj** [comment]
@sberyozkin yes it did resolve the issue, thanks!
