### ISSUE TITLE
[kafka streams] sasl not configurable

### ISSUE THREAD

**Issue by sander-su** [quarkusio/quarkus#4961]
**Describe the bug**
The kafka streams extensions only allows for the bootstrap-servers and application-id to be set at runtime. This works in a non authentication environment but when auth is required there are other properties which needs to be configurable at runtime.
Also the confluent schema registry need to be configurable (again with auth properties)

**Expected behavior**
More properties needs to be configurable @ runtime

For me now at least; could be more:
kafka-streams.schema.registry.url
kafka-streams.sasl.jaas.config
kafka-streams.ssl.truststore.location
kafka-streams.ssl.truststore.password
kafka-streams.ssl.keystore.location
kafka-streams.ssl.keystore.password
kafka-streams.ssl.key.password

**Actual behavior**
Properties cannot be overriden @ runtime.

**To Reproduce**

Try to change them @ runtime does not work.

**Solution proposal**
As there could be other properties which might need to be added could there be an option which let the user define which properties he/she whants configurable @ runtime?
Prefix the runtime config with quarkus.kafka-streams and the build time config just with kafka-streams.

**Comment by sander-su** [comment]
@gunnarmorling ?

**Comment by gunnarmorling** [comment]
@sander-su, sounds good to me. There's just one thing to consider in terms of backwards-compat: any of the properties now promoted to runtime-configurable should be obtained from the old location as a fallback. I.e. first try quarkus.kafka-streams.xyz, then kafka-streams.xyz.

Would you be interested in creating a PR for this?

**Comment by sander-su** [comment]
@gunnarmorling I can make a PR but as this is a side R&D project I dont know when it will be ready ..

**Comment by gunnarmorling** [comment]
Hey @sander-su, did you have a chance yet to take a look at this? No worries if not, just to see where we are.

**Comment by sander-su** [comment]
No not yet, also no idea when I have time.

**Comment by alesj** [comment]
@sander-su @gunnarmorling any idea where do I find these keys as constants?
sasl.jaas.config, ssl.truststore.location, ...

**Comment by sander-su** [comment]
The thing is that it is not a finite list. 
If you use for instance the confluent schema registry you'd need schema.registry.url.
Depending on your kafka installation you might need some other auth plugin. Some implementation of oauthbearer with config for instance.

Hence I proposed to let it up to the user what is build time and what is runtime config.

Thanks for taking a shot at this but to have a generic solution for this it needs to be more flexible.

**Comment by alesj** [comment]
> The thing is that it is not a finite list.

Yeah, well aware of it.

But I had a long discussion yday: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/build-time.20vs.20runtime.20properties.3F
Where as you can see the proposal is to do it like they did it for k8s support -- just keep on adding properties, as that's the only way you're adding value ...

I do still have back-compatibility, where I try to load from anywhere ...
* https://github.com/alesj/quarkus/tree/kafka_sasl

Which I guess will solve this runtime thing ... but not add much tooling value to it.

My question was just to find those constants, if they exist.
The rest is as it is -- just adding new props when needed ...

**Comment by sander-su** [comment]
> 
> Which I guess will solve this runtime thing ... but not add much tooling value to it.
> 
Agree, can you have both? 
So a static set for the tools and just load it all at runtime?

> My question was just to find those constants, if they exist.
> The rest is as it is -- just adding new props when needed ...

config is here
https://github.com/apache/kafka/tree/trunk/clients/src/main/java/org/apache/kafka/common/config

**Comment by PHameete** [comment]
Hi all. Thank you for your work on this! If I understand correctly, this is going to add support for all the currently missing Kafka Streams configuration properties, and not just SASL?

If desired, I can help with testing these changes.

**Comment by PHameete** [comment]
What is the status on this? Can I help in any way to move this forward - for example by testing?

**Comment by gunnarmorling** [comment]
The PR of @alesj is here, and I think it's good to go: https://github.com/quarkusio/quarkus/pull/7417. Essentially just needs merging by @gsmet or someone else with the right permissions. 

> Can I help in any way to move this forward - for example by testing?

If you could build Quarkus from that PR branch and give it a test run in your environment, that'd be welcomed very much. Thanks!

**Comment by PHameete** [comment]
@gunnarmorling @alesj I've built the branch and tested against my config (using confluent schema registry and sasl plaintext). I was able to configure a working example using runtime configuration.

My only question is why am I still getting many "Unrecognized configuration" messages, such as:

```
2020-04-07 12:45:32,322 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (main) The configuration 'bootstrap-servers' was supplied but isn't a known config.
2020-04-07 12:45:32,323 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (main) The configuration 'schema-registry-key' was supplied but isn't a known config.
2020-04-07 12:45:32,326 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (main) The configuration 'schema.registry.url' was supplied but isn't a known config.
2020-04-07 12:45:32,327 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (main) The configuration 'admin.retry.backoff.ms' was supplied but isn't a known config.
2020-04-07 12:45:32,331 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (main) The configuration 'topics' was supplied but isn't a known config.
2020-04-07 12:45:32,332 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (main) The configuration 'admin.retries' was supplied but isn't a known config.
2020-04-07 12:45:32,334 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (main) The configuration 'schema-registry-url' was supplied but isn't a known config.
2020-04-07 12:45:32,336 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (main) The configuration 'application-id' was supplied but isn't a known config.
```

Why is for example 'application-id' passed to the ConsumerConfig?

And two of my configuration parameters were also marked 'ignored' at the beginning:

```
2020-04-07 12:45:31,272 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.kafka-streams.sasl.jaas.config" was provided; it will be ignored
2020-04-07 12:45:31,272 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.kafka-streams.replication.factor" was provided; it will be ignored
```

Both of these configs are crucial. The jaas config did seem to get used by the kafka clients however.

**Comment by alesj** [comment]
I think the "issue" is that we try to push all sorts of properties into config -- the ones with prefix, w/o prefix, our (Quarkus compatilbe = with dash), etc ...
Where Kafka config just complains about those that it doesn't understand / know.
Could be annoying, but shouldn't result in an error.

**Comment by PHameete** [comment]
I agree it's not a big issue per se. For example the schema registry url config always throws a WARN from the Kafka client side despite is being necessary. 

I dont expect quarkus to warn me about unrecognized configuration keys that are valid though. So in this case `quarkus.kafka-streams.sasl.jaas.config` and `quarkus.kafka-streams.replication.factor` when it does not complain about the other kafka specific configs.

**Comment by vietk** [comment]
Hello, in @alesj 's PR : does it allow prefixing runtime properties to have whatever KafkaStream properties overridable at runtime,  as suggested by @sander-su. Or it's just limited to the SASL and SSL properties?

**Comment by alesj** [comment]
@vietk hmmm, good q ... I think you should be able to add anything ... just not in a type-safe way ...
Check/test and let us know :-)

**Comment by vietk** [comment]
Tested, it works 

~> mvn quarkus:dev -Dquarkus.kafka-streams.max.poll.records=12345
![image](https://user-images.githubusercontent.com/1568850/80494048-7e7cd080-8966-11ea-8a12-3b72e6409b11.png)

However I have a nice warning : 
![image](https://user-images.githubusercontent.com/1568850/80493998-6f961e00-8966-11ea-9cf2-0ff183fa970c.png)

Which is missleading as the property has been taken into account :D  

Regards
Kevin

**Comment by alesj** [comment]
I think we add both options/ways -- so we don't make too much assumptions,
one with the prefix and one w/o the prefix.
What you see is the one with prefix -- which is of course not understood by Kafka.

**Comment by gunnarmorling** [comment]
Hey @alesj, where are we with this one, it seems it stalled a bit. What's missing from your PoV to wrap it up?

**Comment by alesj** [comment]
@gunnarmorling nothing from my side.
@gsmet wdyt? Or what's holding this up?

**Comment by rquinio** [comment]
@alesj The native tests are failing in the PR CI build. I don't know if they worked before the big rebase done by @gsmet on May 20 ?
