### ISSUE TITLE
JWT quickstart uses a dependency with a security vulnerability (medium)

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4975]
https://github.com/quarkusio/quarkus-quickstarts/network/alert/using-jwt-rbac/pom.xml/com.nimbusds:nimbus-jose-jwt/open

https://github.com/quarkusio/quarkus-quickstarts/blob/master/using-jwt-rbac/pom.xml

@kenfinnigan I guestimate it's coming from SmallRye JWT but can you chase the right person?

**Comment by kenfinnigan** [comment]
I can't see security issues, which dependency is it?

**Comment by cescoffier** [comment]
<dependency>
  <groupId>com.nimbusds</groupId>
  <artifactId>nimbus-jose-jwt</artifactId>
  <version>[7.9,)</version>
</dependency>

**Comment by cescoffier** [comment]
well, you need at least 7.9.

**Comment by kenfinnigan** [comment]
It's not coming from `smallrye-jwt` as that doesn't have any dependencies on `nimbus-jose-jwt`

**Comment by kenfinnigan** [comment]
Maybe @sberyozkin knows as I think he wrote the quickstart

**Comment by cescoffier** [comment]
the quickstart does not have the dependency either.

**Comment by cescoffier** [comment]
It may come from:

```
[INFO] +- io.quarkus:quarkus-smallrye-jwt:jar:999-SNAPSHOT:compile
[INFO] |  +- io.smallrye:smallrye-jwt:jar:2.0.9:compile
[INFO] |  |  +- org.eclipse.microprofile.config:microprofile-config-api:jar:1.3:compile
[INFO] |  |  +- org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:jar:1.1.1:compile
[INFO] |  |  \- org.bitbucket.b_c:jose4j:jar:0.6.5:compile
```

**Comment by kenfinnigan** [comment]
In `smallrye-jwt` there aren't any security notifications about dependencies

**Comment by cescoffier** [comment]
can it be a false positive?

**Comment by cescoffier** [comment]
I would rather be sure before marking the issue invalid.

**Comment by stuartwdouglas** [comment]
mvn dependency:tree does not show up anything about it

**Comment by sberyozkin** [comment]
Hi All

smallrye-jwt itself does not use nimbus-jwt. We updated the demo to use jose4j. I can add an exclusion as well, but where, in the quickstart or the smallrye-jwt extension ?

**Comment by sberyozkin** [comment]
Let me add an exclusion to the extension

**Comment by sberyozkin** [comment]
Oh, actually, there is no nimbus-jwt in the tree at all, just jose4j, looks like a false positive

**Comment by kenfinnigan** [comment]
Are we good to close this?

I think we figured it was a notice on a previously used dependency right?

**Comment by sberyozkin** [comment]
No nimbus-jwt dependencies exist now, neither in the master nor quickstarts, so I will close it
