### ISSUE TITLE
Do not require Gradle to be installed to generate the Gradle wrapper

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#4982]
**Description**
When `mvn quarkus:create -DbuildTool=gradle` is invoked and Gradle isn't installed in the local environment, the Gradle wrapper is not created.

**Implementation ideas**
Do not require Gradle to be installed. Copy files manually as done in code.quarkus.io.

**Comment by ShubhamRwt** [comment]
@gastaldi Hello. I was of thinking of starting working on this issue. Can you give me some more details regarding this issue.

**Comment by ShubhamRwt** [comment]
@gastaldi Should we keep the files bundled in the code or should  we write a code that makes a request to download gradle wrapper files when needed during setup.

**Comment by gastaldi** [comment]
@ShubhamRwt keeping the files bundled in the code is better to avoid network trips.

**Comment by gastaldi** [comment]
Just make sure it is dynamically generated during the quarkus build

**Comment by ShubhamRwt** [comment]
@gastaldi I did some research on this issue. I guess we would need to use pom itself to generate gradle wrapper but for that we might require some external dependency.

**Comment by glefloch** [comment]
@ShubhamRwt I started looking at this last week. 
As @gastaldi said, we can run `gradle wrapper`command in the `platform-descriptor-json` `pom.xml`. This can be done using the `exec-maven-plugin` plugin. 

Then in the `CreateProjectMojo` mojo, If an exception occurred while generating the Gradle wrapper, we can fallback to a copy from the platform descriptor.

**Comment by ShubhamRwt** [comment]
Yes @glefloch , just had the same idea. I got a chunk of code regarding that

<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>gradle</id>
            <phase>prepare-package</phase>
            <configuration>
                <executable>${gradle.executable}</executable>
                <arguments>
                    <argument>clean</argument>
                    <argument>build</argument>
                    <argument>-Pgroup=${project.groupId}</argument>
                    <argument>-Pversion=${project.version}</argument>
                    <argument>-S</argument>
                </arguments>
            </configuration>
            <goals>
                <goal>exec</goal>
            </goals>
        </execution>
    </executions>
</plugin>

But I am not sure if I am headed in the right direction or not.

**Comment by glefloch** [comment]
Yes, actually, the gradle wrapper is generated, using the `gradle wrapper` task. 
This will generate `gardlew.sh`, `gradlew.bat` files and some others. 
Those files can be added into the `plateform-descriptor-json` artifact. The xml would looks like:

    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <executions>
    <execution>
        <id>gradle</id>
        <phase>prepare-package</phase>
        <configuration>
            <executable>gradle</executable>
            <arguments>
                <argument>wrapper</argument>
            </arguments>
        </configuration>
        <goals>
            <goal>exec</goal>
        </goals>
     </execution>
    </executions>
 
Then, in the `CreateProjectMojo`, if the `createGradleWrapper` method fails, gradle wrapper file should be copied from the `plateform-descriptor-json`.
