### ISSUE TITLE
quarkus-maven-plugin does not obey --file -f command line flag

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#4996]
**Describe the bug**
When --file is specified on command line (e.g. `mvn --file pom2.xml quarkus:dev`) it is ignored. Quarkus plugin either loads pom.xml or complains that there is no pom.xml.

**Expected behavior**
Plugin should use specified file.

**Actual behavior**
Plugin ignores the flag and always uses pom.xml.

**To Reproduce**
1. Rename pom.xml to pom2.xml.
2. mvn --file pom2.xml quarkus:dev

[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (D:\Atron\repo\asc\import-aservice-quarkus). Please verify you invoked Maven from the correct directory. -> [Help 1]

**Configuration**

Not relevant.

```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18362.418]
 - Output of `java -version`: 
      java version "1.8.0_221"
      Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
      Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 0.26.1

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Adding some useful logging output:

```
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to locate project pom.xml for /home/gandrian/Desktop/spring-test/target/classes
    at io.quarkus.bootstrap.resolver.maven.workspace.LocalProject.locateCurrentProjectDir (LocalProject.java:113)
    at io.quarkus.bootstrap.resolver.maven.workspace.LocalProject.loadWorkspace (LocalProject.java:43)
    at io.quarkus.bootstrap.resolver.maven.workspace.LocalProject.loadWorkspace (LocalProject.java:39)

```

**Comment by zeljkot** [comment]
@gsmet IMHO this should be labeled as area/maven or area/devtools
