### ISSUE TITLE
Decide which suffix to use RC or CR, Final or GA

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5000]
CC @n1hility

**Comment by maxandersen** [comment]
It can't be RC if its Final and GA as it will look like later release.

I only see one option if we want to stay sane - .CRn and .Final

**Comment by gsmet** [comment]
I asked this question because until now we didn't have a suffix for the releases (0.27.0).

I see two options:
- keep the no prefix way and go with: `x.y.z-rc1` and `x.y.z` for the final
- go the JBoss way: `x.y.z.CR1` and `x.y.z.Final`

I don't care either way, I just need to know :).

**Comment by maxandersen** [comment]
the first option using semver.org style is just not viable in maven - please don't use it. it will come back and burn us when/if we rely on resolving "latest" for extensions using maven (or gradle) versioning mechanics.

CR1 and Final is the only way to go IMO as that fits/does not conflict  with how productized bits are versioned.

**Comment by jorsol** [comment]
> the first option using semver.org style is just not viable in maven - please don't use it. it will come back and burn us when/if we rely on resolving "latest" for extensions using maven (or gradle) versioning mechanics.

Not sure if I follow... [maven versioning rules](https://cwiki.apache.org/confluence/display/MAVENOLD/Versioning) perfectly allows using `x.y.z-rc1` and `x.y.z`:
```
1. 1.0.0 == 1
   1.0.0 == 1.0.0.Final
2. 1.0.0.Final == 1
   1.0.0.Final > 1.0.0.CR1
3. 1.0.0.CR1 == 1.0.0.rc-1
   1.0.0.CR1 > 1.0.0-rc1
4. 1.0.0-rc1 == 1-rc-1
   1.0.0-rc1 == 1.0.0-CR1
5. 1.0.0-CR1 == 1-rc-1
```

And in fact the dot used in `1.0.0.CR1` creates a weird distinction compared to the dash qualifier type `1.0.0-rc1`

**Comment by maxandersen** [comment]
please see https://developer.jboss.org/wiki/JBossProjectVersioning - i should be more precise that the versioning mechanis that wiki describes works in any versioning system (mvn, osgi, npm and more) and it especially don't conflict with productized binaries versioning to avoid creation of separate GAV's.

**Comment by gastaldi** [comment]
+1 to https://developer.jboss.org/wiki/JBossProjectVersioning

**Comment by gsmet** [comment]
I'm closing this one. We will go with `1.0.0.CR1` and `1.0.0.Final` when time comes.
