### ISSUE TITLE
cleanup gradle resolution of platform for list and addextensions

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5006]
- [x] fix gradle to use properties to look up bom
- [ ] have tools use io.quarkus.platform:universe and look up latest as default, log warning if not avaialble and used bundled
- [x] define how to get from bom to extensions.json (use type?)
- [x] do a test release of universe following the details
- [x] look into #5008  
- [ ] doc impacts #5105

**Comment by maxandersen** [comment]
most done for 0.28 but default lookup/resolution of platform didn't make it in. to be discussed monday if we can/want to put it in for 1.0.

**Comment by stuartwdouglas** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing as this is really old at this point
