### ISSUE TITLE
figure out QuarkusDependencyPredicate hardcoding of io.quarkus

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5008]
QuarkusDependencyPredicate assumes extensions is io.quarkus.  

This seem to exclude any non io.quarkus from list/addextensions.

**Comment by maxandersen** [comment]
looked at this and its simply using it to try and mark a dependency as installed if it has quarkus- as start of its artifactid. That is obviously wrong/not enough and the current setup is just too far removed from having reliable access to the registry to check if really an extension so not something that is an easy fix.

but at the moment this code is not really resulting in any error/issues as the output is always all available extensions rather than some filtered list. 

Pushing this to post v1+

**Comment by stuartwdouglas** [comment]
Is this still a real issue? It looks like this class is only used in tests now.

**Comment by geoand** [comment]
Closing as per comment above
