### ISSUE TITLE
ScopeInfo should have a public constructor

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#5018]
Otherwise it can't be used for custom scopes in a `BeanConfigurator`. We should also add some javadoc to instruct the users to use `io.quarkus.arc.processor.BuiltinScope` for built-in scopes.

**Comment by kenfinnigan** [comment]
Is it ok to add a public constructor as part of REST TCK fix?

**Comment by mkouba** [comment]
@kenfinnigan sure. Pls update the javadocs as well.

**Comment by kenfinnigan** [comment]
Which javadoc? the ScopeInfo or somewhere else?

**Comment by mkouba** [comment]
Yep, `ScopeInfo`.
