### ISSUE TITLE
Scheduler - make the thread pool configurable and/or reuse ExecutorBuildItem

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#5020]
The values are currently hard-coded in `io.quarkus.scheduler.runtime.QuartzScheduler.start()`.

**Comment by jaikiran** [comment]
Just a FYI - there's a similar enhancement request here https://github.com/quarkusio/quarkus/issues/4606 :)

**Comment by mkouba** [comment]
@jaikiran Yes, I know :-).

**Comment by mkouba** [comment]
https://github.com/quarkusio/quarkus/pull/5481 was merged. The default scheduler impl delegates execution to an `ExecutorService` obtained from the `ExecutorBuildItem`. `quarkus-quartz` has a configurable thread pool.
