### ISSUE TITLE
Add additional metadata to MANIFEST.MF

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#5023]
Following this SO question - https://stackoverflow.com/questions/58623758/quarkus-maven-plugin-does-not-add-implementation-entries-to-manifest - stating that we don't push some useful information to the manifest, I think we could push at least a couple more, especially the suggested ones.

This should be done in `JarResultBuildStep`, we have a method to generate the manifest. The information are available in `CurateOutcomeBuildItem#getEffectiveModel()` which exposes at least the artifact name and the version, which could be a good first step.

When we generate the manifest, we read if there's an existing one, we should probably not override the values if they have been defined by the user.

It should probably be some sort of opt-in option as we could see that as an information leak if users don't want to push these info to the published jar.

The maven-jar-plugin option is called `manifest > addDefaultImplementationEntries` so let's mimic it.

**Comment by gsmet** [comment]
@anamarija this one might be a good issue to start with and understand the concept of build step and build items that is core to Quarkus.

**Comment by geoand** [comment]
And of course feel free to reach out for any help you might need

**Comment by anamarija** [comment]
Hi,
Could you please provide some additional info what you mean with the opt-in option. Should it be a custom gradle/maven configuration param which when set should define a build param which in the JarResultBuildStep enables implementationEntries in the manifest. As I understood from the SO question only these two are needed currently

Implementation-Title:  ${appArtifact.artifactId}
Implementation-Version: ${appArtifact.version}

or did you have something else in mind :)

**Comment by anamarija** [comment]
[#5100](https://github.com/quarkusio/quarkus/pull/5100)
