### ISSUE TITLE
Injection doesn't work in ClientHeadersFactory

### ISSUE THREAD

**Issue by tatute** [quarkusio/quarkus#5030]
Initial discussion can be found on [StackOverflow](https://stackoverflow.com/questions/58558635/quarkus-microprofile-is-there-a-better-way-to-use-a-property-from-applicatio/58623996)

**Describe the bug**
Injecting a bean into a class that extends ```ClientHeadersFactory``` doesn't work.

**Expected behavior**
I would like to have an instance of my class injected by the container

**Actual behavior**
The object is null

**To Reproduce**
Here is my code:
``` java 
public class StoresClientHeadersFactoryImpl implements ClientHeadersFactory {

    @Inject
    Configuration applicationConfig;

    @Override
    public MultivaluedMap<String, String> update(MultivaluedMap<String, String> inbound, MultivaluedMap<String, String> outbound) {

        MultivaluedMap<String, String> headers = new MultivaluedHashMap<>();
        headers.putAll(inbound);
        headers.putAll(outbound);
        headers.add("ApiKey", applicationConfig.getKey());
        return headers;
    }
}
```

```java
@ApplicationScoped
public class Configuration {

    @ConfigProperty(name = "apiKey.stores")
    private String apiStoreApiKey;

    public String getKey() {
        return apiStoreApiKey;
    }

    public static String getApiStoreApiKey() {
        return CDI.current().select(Configuration.class).get().getKey();
    }
}
```

```java
@Path("/stores")
@RegisterRestClient
@RegisterClientHeaders(value = StoresClientHeadersFactoryImpl.class)
public interface StoresService {

    @GET
    @Produces("application/json")
    Stores getStores();
}
```

**Configuration**
```properties
# Configuration file
com.acme.StoresService/mp-rest/url = <my-url>
com.acme.StoresService/mp-rest/scope = javax.inject.Singleton
apiKey.stores = <my-value>
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin mbp.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.3" 2019-04-16
 - GraalVM version (if different from Java): -
 - Quarkus version or git rev: 0.25.0

**Comment by geoand** [comment]
@kenfinnigan @asoldano  This will require a change in resteasy-client-microprofile since currently `ClientHeaderProviders` doesn't have a way to delegate the creation of a  `ClientHeadersFactory`.

**Comment by kenfinnigan** [comment]
Based on the current MP REST Client specification, it doesn't define whether injection should be possible within the factory.

I believe there are other types where injection isn't supported either for MP REST Client.

I think we'd need this clarified in the spec first

**Comment by geoand** [comment]
Makes sense.

My perspective is that this sort of injection is very useful for users.

**Comment by gsmet** [comment]
@kenfinnigan do you have the spec side under control on that one?

I'm not totally sure supporting more injection points than the spec strictly requires could be seen as a problem. But if you think it is, it would be nice to get this ball moving.

Thanks!

**Comment by kenfinnigan** [comment]
Was raised by someone else: https://github.com/eclipse/microprofile-rest-client/issues/234

**Comment by marcinczeczko** [comment]
@kenfinnigan - it was me :) 

@gsmet - about this injection point. At the moment there is no clean and elegant alternative to generate headers for annotated client interface. Other things like `@ClientHeaderParam` annotation requires either interface default method or static method, so again it's not possible to inject beans. So, implementation of the client for any API that requires e.g authentication tokens or some additional headers (that usually needs to be provided by app config) requires to pass those values into each client method which becomes quite cumbersome.

**Comment by jtama-op** [comment]
As of now MP REST Client is almost not usable in real-world applications where security is not an option.

**Comment by knutwannheden** [comment]
AFAICT the use case described in the issue description should meanwhile have been solved.

**Comment by geoand** [comment]
This has been fixed in the meantime, so I'm closing
