### ISSUE TITLE
Gradle plugin Uber-jar to use application.property quarkus.package.uber-jar=true like Maven

### ISSUE THREAD

**Issue by oztimpower** [quarkusio/quarkus#5036]
**Description**
Maven has really simple Uber-jar creation via the application.property quarkus.package.uber-jar=true.  Would it be possible to Gradle to also use this property.

Reason being, I'm seeing really weird behaviour using:
```
gradle clean
gradle build -x buildNative
gradle quarkusBuild --uber-jar
(or, gw clean build -x buildNative quarkusBuild --uber-jar)
```

It's incrementing the number on the runner ApplicationImpl.  This needs to be "1", as it's hard-coded in Class.ForName on startup in the Amazon-Lambda Stream Handler I'm testing.
```

java.lang.ClassNotFoundException: io.quarkus.runner.ApplicationImpl1
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.<clinit>(QuarkusStreamHandler.java:30)

```

Seems to be a *bug*.  Every time I run the build (after a clean) it is still incrementing the version of this class.

It would be nice therefore to have the application.property used instead.

 ```
    0 Wed Oct 30 23:21:37 SGT 2019 io/quarkus/runner/
  3238 Wed Oct 30 23:21:37 SGT 2019 io/quarkus/runner/ApplicationImpl6.class
   527 Wed Oct 30 23:21:37 SGT 2019 io/quarkus/runner/GeneratedMain.class



```

**Comment by geoand** [comment]
Hi, with Quarkus `0.27` you can do:

```
./gradlew clean build -x native -x check -Dquarkus.package.uber-jar=true
```

And to get the uber-jar. 

Can you give it a shot please?

**Comment by oztimpower** [comment]
Needless to say I don't have this issue with the Maven plugin (the version increment).

**Comment by stuartwdouglas** [comment]
I don't think we need this count thing any more, I think it was to work around class loading issues for tests back when our internal tests did not have an isolated class loader.

**Comment by geoand** [comment]
@oztimpower Would you be able to check and see if Stuart's #5060 PR fixes the issue with the gradle daemin?

**Comment by oztimpower** [comment]
Yes, after multi-executions with the same Gradle daemon I confirm it's stable.

Much appreciated! 

Validated below:
```
     0 Thu Oct 31 16:38:30 SGT 2019 io/quarkus/runner/
  3240 Thu Oct 31 16:38:30 SGT 2019 io/quarkus/runner/ApplicationImpl.class
   526 Thu Oct 31 16:38:30 SGT 2019 io/quarkus/runner/GeneratedMain.class

```

**Comment by geoand** [comment]
Thanks for checking @oztimpower!
