### ISSUE TITLE
Quarkus 0.27 - JWT role validation does not work

### ISSUE THREAD

**Issue by p-zalejko** [quarkusio/quarkus#5051]
Hi,

I have just migrated my small project from Quarkus 0.25 to 0.27 and I ran into an issue. 

Let's image we have the [SmallRye JWT extension](https://quarkus.io/guides/jwt-guide) configured and the following class:

```
@Path("/hello")
@RequestScoped
open class GreetingResource {

    @GET
    @Path("/protected")
    @Produces(MediaType.TEXT_PLAIN)
    @RolesAllowed(value = ["Echoer", "Subscriber"])
    fun helloProtected(@Context ctx: SecurityContext): String {
        val callerName = ctx.userPrincipal?.name ?: "unknown"
        return "hello $callerName"
    }
}
```

Corresponding test:

```
    @Test
    fun testHelloEndpoint_protectedAsUnknown() {
        given()
                .`when`().get("/hello/protected")
                .then()
                .statusCode(401)
    }
```

Everything works fine with 0.25. Unfortunately on Quarkus 0.27 my test fails because a request ends with HTTP 200 (```helloProtected``` method gets called).

I started looking into the problem and I found that in Quarkus 0.27:
- ```RolesFilterRegistrar#configure``` is not called and does not register ```RolesAllowedFilter```
- ```ResteasyDeploymentImpl``` contains a list (```providerClasses```) that in previous version contains ```io.quarkus.resteasy.runtime.RolesFilterRegistrar``` but in 0.27 this class is not there

 in Quarkus 0.25 ```RolesFilterRegistrar``` and ```RolesAllowedFilter``` are in ```quarkus-resteasy``` module, but 0.27 does not contain them. 

It looks that due to the fact that  ```io.quarkus.resteasy.runtime.RolesFilterRegistrar``` is not registered (present on the ```providerClasses``` list) JWT RBAC does not work. If there is a new way how ```RolesAllowedFilter``` is configured then maybe it is not enabled by default. ```RolesAllowedFilter``` class is also present in ```smallrye-jwt-2.0.9.jar```).

**Comment by stuartwdouglas** [comment]
This should be handled by the io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor now. 

Do you have a reproducer?

**Comment by stuartwdouglas** [comment]
I think you might have to declare the function as 'open'.

That said we really should throw a deployment error for this case.

**Comment by p-zalejko** [comment]
Hi, 

thanks for info. I will check it. I have a small project [here](https://github.com/p-zalejko/my-planner/tree/v0.0.4). There is ```GreetingResourceTest``` and it fails when in pom.xml 0.27 is set.

**Comment by p-zalejko** [comment]
@stuartwdouglas  thanks!, you are right, I changed these methods to ```open``` and now everything is fine.

**Comment by stuartwdouglas** [comment]
@mkouba it looks like ArC is just ignoring final methods for interceptors, is this intentional? It seems like a big problem for cases like this.

**Comment by stuartwdouglas** [comment]
Maybe if interceptors have been applied to final methods on application classes we could use our class transformers to make it 'just work' by removing the final modifier.

**Comment by geoand** [comment]
@stuartwdouglas That could be a general strategy for Kotlin, although it's probably better if we actually implement the kotlin compiler plugin which would open things we deem necessary to be open.

**Comment by mkouba** [comment]
Yes, we do ignore the final methods. The CDI spec requires a class that has a bound interceptor to be proxyable - no final methods. But we're a bit more lenient. I think we log a warning for each ignored final method...

**Comment by mkouba** [comment]
> Maybe if interceptors have been applied to final methods on application classes we could use our class transformers to make it 'just work' by removing the final modifier.

Sounds interesting. But I wonder if there could be any "hidden" problems with this approach?

**Comment by stuartwdouglas** [comment]
I think this behaviour is a big problem for security interceptors, especially if the interceptor has been bound to the method rather than the class

**Comment by emmanuelbernard** [comment]
Isn’t it the Kotlin extension job to open the useful classes ?

**Comment by stuartwdouglas** [comment]
This is not really a kotlin specific issue IMHO. If you apply a security annotation to a class it should either work, or cause a deployment error. Ignoring @RolesAllowed because a method is final is likely CVE material.

**Comment by geoand** [comment]
I completely agree with what @stuartwdouglas about failing on `final`.
On the other hand, making things non final is part of Kotlin support - not necessarily the extension but the Kotlin compiler addon we should to write (since our proposed changes to the generic all-open one got rejected)

**Comment by gsmet** [comment]
Is someone working on the deployment error approach? I think we should have it in 0.28.0.

**Comment by geoand** [comment]
I am not, but I can get to it in a few hours if no one picks it up sooner.

**Comment by mkouba** [comment]
It should be possible to throw a deployment error for non-proxyable types annotated with a security annotation. On the other hand, I'm not quite sure it should be the default behavior.  

Currently, we have a concept of "validation rules" that could be skipped: https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeploymentValidator.java#L31-L33. We could use something similar for non-proxyable types.

**Comment by gsmet** [comment]
So, the situation for now is that we will throw a proper error message for this and you will have to make your method `open`.

We will improve on this soon thanks to @geoand 's PR.
