### ISSUE TITLE
Include Throwable in startup error log message

### ISSUE THREAD

**Issue by brunoabdon** [quarkusio/quarkus#5058]
**Describe the bug**
The error log message "_Failed to start Quarkus, attempting to start hot replacement endpoint to recover_" should include the Throwable that caused it.

This is at this line: https://github.com/quarkusio/quarkus/blob/6ac42657d5c3cc95cf8a09feb8a1f52ebc80b4f7/core/devmode/src/main/java/io/quarkus/dev/DevModeMain.java#L187

**Expected behavior**
Show the Throwable info on error log.

**Actual behavior**
Throwable instance is swallowed.

**Suggestion**
Just pass `t`as second parameter:

`log.error("Failed to start Quarkus, attempting to start hot replacement endpoint to recover",t);`

**Comment by jaikiran** [comment]
https://github.com/quarkusio/quarkus/pull/5061

**Comment by Sanne** [comment]
I think we can consider this resolved by #5061 : closing
