### ISSUE TITLE
Provides extension HealthCheck

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#5073]
**Description**
Provides health check for some of the existing extensions.
It will not be exhaustive, please advise if some other extensions deserve an health check in the same batch of health check.

**Implementation ideas**

### MongoDB Health Check
Provides a **readiness** health check for MongoDB.
Proposed implementation: use the `MongoClient` to list the databases.
**Enabled** by default.

### Neo4J Health Check
Provides a **readiness** health check for Neo4J.
Proposed implementation: use the Bolt `Driver` to make a query to Neo4J.
**Enabled** by default.

### Kafka Health Check
Provides a **readiness** health check for Kafka.
Proposed implementation: use the Kafka `AdminClient` to connect to the cluster and check it's state.
**Disabled** by default.

_This is my opinion that as Kafka has built in resiliency for both producer and consumer, the health check should not be enabled by default. Some must have good arguments to enabled it by default and I'm open to discussion_

**Comment by geoand** [comment]
@cescoffier might have some comments on this
