### ISSUE TITLE
Quarkus with Struts2 and co.

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#5082]
I am not proficient with Javascript frameworks, having done most of my work with Frameworks like Struts2 and up to now, I have used Quarkus only for building my services. Is it possible to use one of those frameworks to build a web application based on Quarkus? Meaning the application, say using Struts2 will be deployed with Quarkus in native mode for example.

**Comment by maxandersen** [comment]
If you run in JVM mode it should be doable, but for native you'll most likely need to write an extension to let graalvm do its thing - but struts is probably too reliant on reflection so it might be hard if not impossible.

in any case the core quarkus team are not at this time spending time of writing extensions for past frontend technologies our selves, but if someone in the broader community would like to try we will happily answer questions to help.
