### ISSUE TITLE
Arc generated beans/subclasses/proxies are considered framework classes from CL point of view

### ISSUE THREAD

**Issue by manovotn** [quarkusio/quarkus#5083]
Assuming there are two junit test classes and assuming there is a synthetic bean created and used in both, then if the synthetic bean can differ on a test-to-test basis, the classloader will retain the class information possibly leading to test failures.
This only happens if you execute all tests at once (separetely, they would pass) and with `<reuseForks>` set to `true` (which is default).

This originated from @michalszynkiewicz tests around security, available on [this branch](https://github.com/michalszynkiewicz/quarkus/tree/cdi-security-deployment-time-scanning).
Tests are `CDIAccessDefaultTest` and `CDIAccessDenyUnannotatedTest`.

After some digging I figured we are using a `RuntimeClassLoader` which we create anew for every junit test. However, it always links to a parent CL that stays the same throughout the test suite execution. And the problem boils down to what classes are loaded by what CLs.
Anything considered "app classes" is loaded by `RuntimeClassLoader`, all else is considered "fwk" and is loaded by the parent CL. The generated synthetic bean is considered to be a "fwk" class and falls to the parent CL hence it doesn't get reloaded in between tests.

We also cannot just easily move synthetic beans to have them considered as fwk classes because there are possibly proxies built on top of those and the proxy, sitting in another CL, has old information about the class object it refers to (which gives you LinkageErrors).

I think we want to consider synthetic beans as application classes, but for that we'd need to also consider all of their possible subclasses and/or proxies as app classes.
I am not quite sure how to do it yet, but I wanted to write it down so we don't forget it.

**Comment by stuartwdouglas** [comment]
How do I reproduce this? I ran those tests with the random bean names code removed and they still passed.

**Comment by michalszynkiewicz** [comment]
hi @stuartwdouglas, were you running both tests in a single maven run? And from `cdi-security-deployment-time-scanning` branch of my fork? It failed both for me and Matej. 
You can also run the MP JWT TCK, the `RolesAllowedTest` should fail in it with the same problem. But that may depend on the test order.

**Comment by mkouba** [comment]
So the problem with synthetic beans is that unlike fwk class beans their `Bean#create()` implementation may be deployment-specific: https://github.com/michalszynkiewicz/quarkus/commit/b7e05dd0cc454c3062bf4daf3045b70797692826#diff-36e991a830b10f10b19a4360212eebcaR147-R156.

**Comment by manovotn** [comment]
@stuartwdouglas did you run it also with `<reuseForks>` set to `true` (which is default if you remove that line)?

**Comment by stuartwdouglas** [comment]
This should be fixed with the new class loading architecture.
