### ISSUE TITLE
Hibernate ORM should only enforce provider_disables_autocommit when using Agroal

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#5103]
**Describe the bug**
We decided to set the flag `provider_disables_autocommit` by default, as the expectation is to use the Agroal datasource - which takes care of this flag correctly.

However we need to consider that there's various ways in which the connection pool implementation could be overriden; this isn't a problem as all reasonable connection pool implementations do similarly disable autocommit, but the default connection pool in ORM would also pass such properties to the underlying JDBC driver - causing issues with drivers.

See also:
 - https://github.com/googleapis/google-cloud-java/issues/6671

A possible solution would be to enforce the flag without setting the configuration property, as the root issue is that this property has an unfortunate name.
 - https://hibernate.atlassian.net/browse/HHH-13700

**Comment by stuartwdouglas** [comment]
@Sanne is this an issue? I don't think we want to support other connection pools.

**Comment by Sanne** [comment]
I suppose we can close this now.

The reason was that in some cases they come as "highly recommended" by the DB vendor.

I'm thinking mainly about Oracle JDBC and its embedded UCP, until recently I had the impression they were pushing for this to be a requirement for supported customers, but it seems the wording about this is far more relaxed nowadays.

So let's close it for now; there are other similar cases but let's try to make it all work with Agroal first.

**Comment by Sanne** [comment]
BTW to bear in mind that  users configuring Hibernate ORM via a `persistence.xml` still have more freedom than what they should have ;)
