### ISSUE TITLE
investigate if/how docs and created projects build gets affected by the separate versions introduced

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5105]
as caught yesterday we actually end up having quarkus.version and quarkus.platform.version increasing at different speeds.

And in builds and lot of docs the quarkus.version is not really about quarkus core but about which quarkus.tools.version to use. 

We should just ensure that for v1 launch these things are okey to all point to same version (1.0.0.Final)
 
I *think* they can but we might want to separate things upfront generated build.

**Comment by gsmet** [comment]
This was fixed by introducing a Platform Maven plugin and keeping things in sync.
