### ISSUE TITLE
Inconsistent guides for native image

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#5111]
I see some inconsistencies in guides for native image

https://quarkus.io/guides/building-native-image-guide mentions new way using `<quarkus.package.type>native</quarkus.package.type>` property. 

https://quarkus.io/guides/maven-tooling mentions only maven plugin definition way.

https://quarkus.io/guides/writing-native-applications-tips mentions only maven plugin definition way.

https://quarkus.io/guides/maven-tooling#build-tool-maven says: If you have not used project scaffolding, add the following elements in your pom.xml
But project scaffolding now uses `<quarkus.package.type>native</quarkus.package.type>` property way but the guide uses old way.

I think there should be more details about two ways users can take, what are their advantages and how they should select their way. Maybe few words for guys migrating from previous versions.

I played a bit with some text changes but the result wasn't very good so I scratched it and creating issue instead ;)

**Comment by gsmet** [comment]
We shouldn't advertise the Maven way of doing things anymore.

**Comment by rsvoboda** [comment]
Just out of curiosity, what's the way for `additionalBuildArgs` with the new approach ?

And one more thing, `<enableHttpUrlHandler>true</enableHttpUrlHandler>` is enabled by default or what's the new way?

**Comment by geoand** [comment]
@rsvoboda yes, it's enabled by default. The new way of configuring things is just to use application.properties with the configuration available from [NativeConfig](https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java#L13)
