### ISSUE TITLE
Support injection of loggers

### ISSUE THREAD

**Issue by alexander-dammeier** [quarkusio/quarkus#5118]
**Description**
I am using slf4j as a logger and i always write an CDI-producer to inject a logger into my classes. Since Quarkus supports slf4j directly, it would be nice if quarkus itself implements this producer. This way nobody needs to write boilerplate code for this anymore.

**Implementation ideas**
My current producer looks like this:
```
public class CDIFactories {

    @Produces  
    public Logger produceLogger(InjectionPoint injectionPoint) {  
        return LoggerFactory.getLogger(injectionPoint.getMember().getDeclaringClass().getName());  
    }  
}
```
So you can inject it this way:
```
@ApplicationScoped
public class ExampleService {

	@Inject
	Logger logger;
}
```
I think this way a compile time optimization is possible too.

**Comment by chrisgleissner** [comment]
You may want to have a look at Lombok which means you can simply add an @SLF4J annotation to your class and a log field will be automatically created during compilation. This is even easier and requires less boiler plate than the suggested approach. I have been using this for a few years now across various frameworks and it works just fine with Quarkus. Plus, no additional library is required at runtime since Lombok enhances the code similar to how Quarkus does it, at compile time.

**Comment by dmlloyd** [comment]
The amount of boilerplate is quite small; it's usually recommended to create a static final field for your logger. Is there some use case that cannot be solved this way?

**Comment by chrisgleissner** [comment]
@dmlloyd @alexander-dammeier Yes, that is exactly what the @Slf4j annotation does that I mentioned. It adds a static final logger field. I have seen this approach used extensively in many projects and a Logger instance is typically considered too light-weight to make it part of the DI wiring.

There may have an ever so small performance hit of this approach compared with using a single Logger instance that gets autowired via DI, but you are trading instantiating a single, very light-weight Logger instance for the overhead of wiring, so the performance difference of either approach is likely to be tiny. For me, code simplicity and reduced boiler plate wins in this case.

I have no stake in Lombok but as a long-time user I have found it complements Quarkus nicely, e.g. also for WELD wiring immutable objects via the @RequiredArgsConstructor annotation.

**Comment by alexander-dammeier** [comment]
@chrisgleissner Thanks for mentioning the @slf4j annotation! I think that is a good way to reduce the boilerplate code. Its even fewer code than with injection. 
@dmlloyd No, there is no use case where i cannot solve it with a static reference. The only reason I created this issue is to enjoy Quarkus even more with fewer boilerplate code.

In my situation it does not matter if there is a little performance impact to inject a logger so this idea comes up. I fully understand if you decide to not implement this in Quarkus directly because of the performance impact. I already use immutables.org so i thought there is no reason to use lombok too. That our team needs a plugin for the IDE to use lombok is a tradeoff we have to think about. It would be great to have the possibility to inject the logger but its no problem for us to write it ourself.

**Comment by chrisgleissner** [comment]
@alexander-dammeier Thanks for pointing out immutables.org. Unlike Lombok, it also supports Java 7. Very useful.

**Comment by alexander-dammeier** [comment]
We can close this issue now. Quarkus supports this already.
See the example code here: https://quarkus.io/guides/logging#supported-logging-apis
