### ISSUE TITLE
Improve MP TCK execution time

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#5123]
The following TCKs require surefire to be configured to prevent the reuse of JVMs for different tests:

- [ ] [MP Config](https://github.com/quarkusio/quarkus/blob/master/tcks/microprofile-config/pom.xml#L38)
- [ ] [MP Fault Tolerance](https://github.com/quarkusio/quarkus/blob/master/tcks/microprofile-fault-tolerance/pom.xml#L32)
- [ ] [MP REST Client](https://github.com/quarkusio/quarkus/blob/master/tcks/microprofile-rest-client/pom.xml#L32)

This is required because there are several static values that aren't re-evaluated for each test.

It would be worth exploring whether there are ways we can manipulate the statics before/after test execution to enable reuse of the same JVM, and thus improve CI speed for the TCK execution

**Comment by jmartisk** [comment]
This workaround fixed the Config TCK for me: https://github.com/jmartisk/quarkus/commit/f0353a522063d96893fb8d2742a978a1aa58d6ab
Apparently we're hitting a variant of https://github.com/quarkusio/quarkus/issues/4512 again. There are two different `Config` instances available at runtime, and one of them does not have the needed converters configured. Unfortunately, the test uses the wrong one.

**Comment by kenfinnigan** [comment]
Submit a PR!

**Comment by jmartisk** [comment]
> Submit a PR!

Well as I said it's a workaround. `ConfigProviderResolver.instance().getConfig()` and `ConfigProvider.getConfig()` should return the same object. I'm not sure if this workaround will not break anything until we have a proper fix in Config, and I'm not sure if it's worth the risk for saving 30 seconds in TCK duration :/

**Comment by kenfinnigan** [comment]
fair enough.

Once @dmlloyd mega config PR is in the problem might go away as well

**Comment by geoand** [comment]
I think we can close this now as I have no seen anyone complain about the duration of the MP TCK execution in a long time :)
