### ISSUE TITLE
make Scheduler cron configurable via MP-Config

### ISSUE THREAD

**Issue by alexander-dammeier** [quarkusio/quarkus#5126]
**Description**
I am using quarkus scheduler for a registration task for IoT devices in a smart city application. The task repeats every minute and retries to register if something went wrong before. It would be very helpful if I dont have to hardcode the cron into my services. Then i can repeat the task more often in dev mode and less often in production for example.

**Implementation ideas**
I think of a configuration key in the annotation like in microprofiles rest client `@RegisterRestClient(configKey = "...")`.
```
@Scheduled(configKey = "registrationcron")
public void register() {
    //...
}
```

**Comment by machi1990** [comment]
Hi @alexander-dammeier thanks for reporting this.

This can current be achieved with 

```
@Scheduled(cron = "{registrationcron}")
public void register() {
    //...
}
```

With `registrationcron ` property being the `application.properties` configuration file.

**Comment by gsmet** [comment]
Is it documented somewhere? Do we have a test for it?

**Comment by machi1990** [comment]
It is not documented, I was planning to get to it a bit later.

As for the test we have one example job here: 
https://github.com/quarkusio/quarkus/blob/master/integration-tests/main/src/main/java/io/quarkus/it/scheduler/ExampleJobs.java#L27-L32

**Comment by gsmet** [comment]
Cool, thanks!

**Comment by alexander-dammeier** [comment]
The best feature requests are for non-documented features.
Thank you very much for your fast response and the example code 👍
As a test I worked for a private project with Quarkus and I am very satisfied. I'll suggest Quarkus at work.

**Comment by machi1990** [comment]
@alexander-dammeier I am glad it worked for you. We'll have the feature documented for the next release hopefully.

Looking forward to hear your success story on using Quarkus in production ;-)
