### ISSUE TITLE
Quarkus Lambda Http VertxRequestHandler -> request.remoteAddress().host() nullpointer exception

### ISSUE THREAD

**Issue by Ravisankar-Challa** [quarkusio/quarkus#5134]
Hi There,

I am getting NullPointerException in VertxRequestHandler.java line number 99 -> request.remoteAddress().host() when invoked from Amazon Api Gateway
request.remoteAddress() is null

I am using the following dependencies.
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-amazon-lambda-http</artifactId>
</dependency>

<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
</dependency>

Thanks,
Ravi

**Comment by gsmet** [comment]
It should be fixed by tomorrow's release.
