### ISSUE TITLE
Quarkus Kubernetes Dekorate kubernetes.group partially applied

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5135]
Create a new project
Add quarkus-kubernetes as dependency

Add the following to the `application.properties` file

```
kubernetes.group=example
quarkus.application.name=fruits-app
```

In `target/kubernetes/kubernetes.yml`, you will see

- spec.template.spec.containers.image : ${username}/fruits-app:1.0-SNAPSHOT
- metadata.labels.group: ${username}

Where ${username} is your environment username and where it should be `example`.

@iocanel @geoand 

To decide if that's fixable by 0.28

**Comment by geoand** [comment]
I'll check this out in an hour or so. @iocanel if you beat me to it, feel free to address

**Comment by geoand** [comment]
I can reproduce the problem

**Comment by geoand** [comment]
So @iocanel there seem to be 2 problems: 

* setting `kubernetes.group` doesn't affect the `group` label of the created `Service` (although it does affect the `group` label of the `Deployment`).
* setting `kubernetes.group` has no effect on the value of `image` of the container spec.
* setting `kubernetes.registry` also doesn't seem to affect the value of `image` at all.

**Comment by geoand** [comment]
For the time being I'll see if I can work around these issues on the Quarkus side of things until they are properly addressed in Dekorate.

**Comment by geoand** [comment]
I think I have some hacks to get things working correctly. I'll add some tests and open a PR soon
