### ISSUE TITLE
prefix "classpath:" does not work for "quarkus.flyway.locations " in native mode

### ISSUE THREAD

**Issue by JohT** [quarkusio/quarkus#5138]
Flyway does not use locations configured with the prefix "classpath:" in native mode.
The configuration entry (application.properties)
- `quarkus.flyway.locations=db/custom` works (native and substrate)
- `quarkus.flyway.locations=classpath:db/custom` doesn't (substrate only)

I suggest to simply delete the "classpath:" hint inside the JavaDoc and the description.
Since it may be, that "classpath:" is not only used here, it may be interesting, if there are similar problems in other places.

1. Setup using "mvn io.quarkus:quarkus-maven-plugin:0.26.1:create"
2. Adding flyway as described in [flyway guide](https://quarkus.io/guides/flyway-guide)
3. Renaming "META_INF/db/migration" to "META_INF/db/custom"
4. `application.properties` entry `quarkus.flyway.locations=classpath:db/custom`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: ...MacBook-Air.local 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
 - Quarkus version or git rev: 0.26.1

**Comment by stuartwdouglas** [comment]
It looks like this code just ignores the prefixes: https://github.com/quarkusio/quarkus/blob/5257fd855f44d1389e110bfc74303d835d0a3c05/extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java#L111

**Comment by aguibert** [comment]
I'll have a look into this issue and propose a PR when I'm done

**Comment by daggerok** [comment]
Hello,

please, let us know what we must to to make quarkus native flyway works?

Thanks

**Comment by gsmet** [comment]
It's supposed to work. Please open a separate issue with the issue you have, and preferably a reproducer.

**Comment by daggerok** [comment]
Hello @gsmet, thanks for feedback

I was able to setup it like [here](https://github.com/daggerok/quarkus-elytron-security-jdbc-postgresql-example/blob/master/src/main/java/daggerok/FlywayMigrate.java) only with manually implemented FlywayMigrate ApplicationScoped bean...

Just by using application.properties configurations, flyway migration is not started in native mode...
