### ISSUE TITLE
Please add null check for LambdaHttpHandler.java line 84 -> request.getMultiValueHeaders()

### ISSUE THREAD

**Issue by Ravisankar-Challa** [quarkusio/quarkus#5158]
Hi There,

Could you please add a null value check in LambdaHttpHandler.java line 84 ->  request.getMultiValueHeaders()

I able to send a request with out any http headers from AWS Api gateway and it fails in the above mentioned class with null pointer exception.

Thanks,
Ravi

**Comment by gsmet** [comment]
Could you provide a sample project reproducing the issue? We can't figure out how this could be null.

**Comment by stuartwdouglas** [comment]
Is https://github.com/quarkusio/quarkus/pull/5159 what you are after? I don't see any reference to getMultiValueHeaders() on line 84 in any version.
