### ISSUE TITLE
Should JWT @Claim require @Inject too

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5160]
The guide seems to use `@Claim` and `@Inject` together and 0.27 seems to mandate that. But  our quarkus lab used to work with just `@Claim` in seems
Is that a regression or was the behavior never intended?

@lordofthejars

**Comment by sberyozkin** [comment]
[This test](https://github.com/eclipse/microprofile-jwt-auth/blob/master/tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/ClaimValueInjectionEndpoint.java) shows `Inject` everywhere.
May be [this code](https://github.com/quarkusio/quarkus/commit/b8e5f55139aa14b959e12169ae369b1ae2f6adb6#diff-b54a42d0e73da6c5409eb000962bca27) is related ? Not 100% sure, CC Martin @mkouba and Michal @michalszynkiewicz

**Comment by mkouba** [comment]
`@Inject` is _optional_ for a **field** injection point if it has at least one qualifier. It's a Quarkus-specific feature that actually violates the CDI spec (where `@Inject` is mandatory).

@sberyozkin the TCK must be CDI-compliant. So it _has to_ use `@Inject`.

In any case, I wouldn't call it a "regression"...

**Comment by sberyozkin** [comment]
@mkouba Hi Martin, thanks for the fast update; As far as I'm concerned, the fewer annotations, the better :-), so if Qurakus allows for it then it is fine. May be some documentation has to be updated somewhere to answer a question from @emmanuelbernard ? If you tell me what to update then I can take of it, thanks

**Comment by mkouba** [comment]
I've updated the CDI guide to include few lines about this feature: https://github.com/quarkusio/quarkus/pull/5167 (previously it was only mentioned in the blogpost)

**Comment by emmanuelbernard** [comment]
@sberyozkin can you run some quarkus specific tests as well outside the TCK. Because if I did not make a mistake it was not working for me at the time. I had to add `@Inject`. But maybe I got it wrong.

**Comment by sberyozkin** [comment]
@emmanuelbernard 
Stuart updated [this test resource](https://github.com/quarkusio/quarkus/blob/master/integration-tests/oidc/src/main/java/io/quarkus/it/keycloak/AdminResource.java#L17) recently, the test itself is [here](https://github.com/quarkusio/quarkus/blob/master/integration-tests/oidc/src/test/java/io/quarkus/it/keycloak/BearerTokenAuthorizationTest.java#L162). So it works without `Inject`.

**Comment by mkouba** [comment]
Thanks @sberyozkin.
