### ISSUE TITLE
Multiple instances are created from a ConfigSource

### ISSUE THREAD

**Issue by jkristof94** [quarkusio/quarkus#5175]
Language: Kotlin (AWS Lambda)

Environment: When running a `@QuarkusTest` annotated test

Setup: A class implements `org.eclipse.microprofile.config.spi.ConfigSource` and is added to the list of entries in `org.eclipse.microprofile.config.spi.ConfigSource` under `META-INF/services`

Scenario: When running a test annotated with `@QuarkusTest` (Currently I can not test it any other way because of [this issue](https://github.com/quarkusio/quarkus/issues/3354)) multiple instances are created from the class defined in the services file.

**Comment by jmartisk** [comment]
Looks like yet another manifestation of https://github.com/quarkusio/quarkus/issues/4512

**Comment by emmanuelbernard** [comment]
can you check again on Quarkus 1.3+ Lots has happened since then. Please reopen as needed
