### ISSUE TITLE
Unable to change debug port in dev mode

### ISSUE THREAD

**Issue by nderwin** [quarkusio/quarkus#5186]
**Describe the bug**
The DevMojo no longer respects the `debug` option when setting up the debug port it dev mode.  Looks to be a result of commit https://github.com/quarkusio/quarkus/commit/66d25b78f0cd386b6deb7a3eeb20e3fb665bb01e

**Expected behavior**
`mvn compile quarkus:dev -Ddebug=5006` should listen on port 5006 for debugger connections.

**Actual behavior**
Dev mode always listens to port 5005 for debugger connections.

**To Reproduce**
1. Create a Quarkus project using at least version 0.27.0
2. Start the project with a debug port of something other than 5005
3. Note in the console that it uses 5005 instead of the specified value

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux vm 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

 - Output of `java -version`: 
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu219.04)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu219.04, mixed mode, sharing)
```

 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 0.28.0

**Comment by gsmet** [comment]
Right, looks fishy. @stuartwdouglas could you have a look?

**Comment by nderwin** [comment]
@gsmet In which release will the fix for this appear?

**Comment by gsmet** [comment]
It's going to be released very soon.
