### ISSUE TITLE
Unable to get the quarkus.http.port from environment variable

### ISSUE THREAD

**Issue by zthulj** [quarkusio/quarkus#5192]
**Describe the bug**
I'm trying to deploy the starter quarkus app via container to Heroku. 
The web process must listen for HTTP traffic on $PORT, which is set by Heroku

I have set in my application.properties : 
```
quarkus.http.port=${PORT:8080}
```

**Expected behavior**
Quarkus should start and listen on 8080 on my computer or if no $PORT is given, and listen on $PORT if given.
Tests should pass. 

**Actual behavior**
I get this error on start : 
```
ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus, attempting to start hot replacement endpoint to recover
```

And I get this error on tests : 
```
TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.ExampleResourceTest]: For input string: "${PORT:8080}"
```

**To Reproduce**
1. Create an app 
2. Add quarkus.http.port=${PORT:8080} to the application.properties
3. package or start

**Comment by stuartwdouglas** [comment]
Looks like when this is loaded 'expanding' is false in ConfigDefinition, so the ExpandingConfigSource ignores it

**Comment by dmlloyd** [comment]
I think this could be the same problem as #2816/#4077.

**Comment by binout** [comment]
Works until quarkus 0.19.1 😭

**Comment by machi1990** [comment]
> Works until quarkus 0.19.1 😭

We have a config PR that should fix this issue. We'll update this space once that is merged. Thanks

**Comment by samuelstein** [comment]
hey @grzi,
i tried the dynamic port setting with quarkus 1.11.1 and it is working fine.
