### ISSUE TITLE
aws-lambda-http how to turn off response body base64 encoding

### ISSUE THREAD

**Issue by Ravisankar-Challa** [quarkusio/quarkus#5196]
Hi Team,

I am using aws-lambda-http body is always base64 encoded (see sample response below) in response. Is there an option to not to do base 64 encoding?

{
	"statusCode": 200,
	"multiValueHeaders": {
		"Content-Length": ["23"],
		"Content-Type": ["application/json"]
	},
	"body": "eyJoZWxsbyI6ImhlbGxvIGpheHJzIn0=",
	"isBase64Encoded": true
}

Thanks,
Ravi

**Comment by Ravisankar-Challa** [comment]
> What problem are you seeing? This set up is working in all our tests with both curl and browser tests. Is it just the extra step of decoding using, say, a java client?

**Comment by Ravisankar-Challa** [comment]
It's not an issue it works fine from Anazon API Gateway. I am using https://github.com/lambci/docker-lambda for testing where lambda is invoked directly not through API Gateway. It would he really nice if you could provide some quarkus property to Devs/users to control the base64 encoding of body.

**Comment by patriot1burke** [comment]
Its hardcoded to base 64 because API Gateway requires you to specify your binary types up front and because anything not UTF-8 has to be encoded.  So, just decided to encode everything.

**Comment by patriot1burke** [comment]
If you're using aws-lambda-http, why not just use `sam local` like our docs suggest?

**Comment by Ravisankar-Challa** [comment]
@patriot1burke I totally agree but please do consider providing a quarkus property to disable base64 encoding.

**Comment by Ravisankar-Challa** [comment]
Have you tested using amazon api gateway? Because I am seeing base64 encoded response form api gateway as well.
Please have a look at the screen shot body is base64 encoded.

![image](https://user-images.githubusercontent.com/11788842/68329364-17890800-00f7-11ea-9d3d-2de4fee8e7ea.png)
