### ISSUE TITLE
Dev mode - 404 - List of static files not reloaded

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#5201]
Launch dev mode, go to an unknown page, you get the 404 with a list of static html files.

Create a new html file, reload the 404, the file is not there.

**Comment by gsmet** [comment]
@machi1990 I was wondering if you could have a look at this one, now that you're fluent in dev mode :).

**Comment by machi1990** [comment]
Yeap. I’ll have a look later on today.
