### ISSUE TITLE
Make the RESTEasy extension infer the mediatype like Spring Web extension does

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5206]
In RESTEasy, you need to set `@Produces(MediaType.APPLICATION_JSON)` but it's infered in the Spring equivalent. Could we do the same for RESTEasy?

CC @geoand

**Comment by geoand** [comment]
I see no reason why we can't do this.
Can you think any reason not to @asoldano , @gsmet ?

**Comment by kenfinnigan** [comment]
It depends on what the "default" is going to be, and/or how complicated it is to determine based on the return type.

JSON is not the default media type for JAX-RS

**Comment by geoand** [comment]
It's not, but couldn't we take the opiniotated approach and make it the default in Quarkus?

**Comment by asoldano** [comment]
@emmanuelbernard @geoand how does spring web actually infer this?
As for Quarkus being opinionated, etc. if we had RESTEasy completely rely on annotation metadata provided by Quarkus, we could simply change the input to RESTEasy adding the application/json as "produces"...

**Comment by geoand** [comment]
So basically for the Spring annotations, when there is no `@Produces`, the code just defaults to using json since that is what Spring Web does as well.

**Comment by emmanuelbernard** [comment]
So we could default to JSON if you add RESTEasy JSON but not sure that's an obvious choice.

**Comment by geoand** [comment]
That seems to me to be the proper choice and in line with the useful defaults that Quarkus provides in other cases

**Comment by geoand** [comment]
I think we discussed this as part of Panache RESTEasy

**Comment by geoand** [comment]
This has been implemented in RESTEasy Reactive
