### ISSUE TITLE
All configuration options guide - no RESTEasy config options

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#5214]
I.e. `ResteasyServerCommonProcessor.ResteasyConfig.singletonResources`. For the record `ResteasyConfig` is a static nested class.

@FroMage @machi1990 Any idea?

**Comment by FroMage** [comment]
It's in `target/asciidoc/generated/config/quarkus-resteasy-server.adoc` and in `target/asciidoc/generated/config/all-configuration-roots-generated-doc.properties` so it is picked up
and must be a bug in my all-config generator.

**Comment by FroMage** [comment]
I found the bug, but we're also missing `openapi`.

**Comment by FroMage** [comment]
The problem is due to `SmallRyeOpenApiConfig.java` being in `quarkus-smallrye-openapi-common-deployment` which does not have a `quarkus-config-roots.list` listing it.

@dmlloyd do you know why it would not list it?

**Comment by FroMage** [comment]
No, sorry, my bad, it is listed in `extensions/smallrye-openapi-common/deployment/target/classes/META-INF/quarkus-config-roots.list`

**Comment by FroMage** [comment]
OK, so the issue is that `quarkus-smallrye-openapi-common-deployment` is not listed as part of the platform, and so I'm not scanning it to find its config roots and I can't figure out which extension this property belongs to.

**Comment by FroMage** [comment]
I guess the same would happen of all config roots that live in `*-common` extensions not listed…

**Comment by FroMage** [comment]
Well, `quarkus-resteasy-common` and `quarkus-resteasy-server-common` are part of the platform BOM, but `quarkus-smallrye-openapi-common-deployment` is a deployment-only thing.

Really not sure how to fix that, guys.

**Comment by FroMage** [comment]
#5218 fixes the resteasy (and other member config types) issue.

But remains the issue of figuring out which extension holds the `openapi` one…

**Comment by gsmet** [comment]
Note that we can just push the fixed adoc file to the website while waiting
for the new release.

**Comment by FroMage** [comment]
Yeah, this is only impacting what we build from `docs`.

**Comment by dmlloyd** [comment]
Could hardcode it for now?

**Comment by FroMage** [comment]
Yes, that's what I'll do.
