### ISSUE TITLE
Allow setting a custom Hibernate ConnectionProvider

### ISSUE THREAD

**Issue by bvarner** [quarkusio/quarkus#5219]
**Description**
Allow setting `hibernate.connection.provider-class` through quarkus app application properties.

**Implementation ideas**
Implement adding the ability to specify a custom connection provider with a hibernate.orm setting such as: `quarkus.hibernate-orm.connection.provider-class` that would set `hibernate.connection.provider-class` within a jpa persistence context when not using a persistence.xml.

**Comment by Sanne** [comment]
Hi,
sorry I don't think that's a good idea. Historically Hibernate allowed a lot of flexibility in this area, as there were many buggy connection pools so it was a hard choice.. today it's more like the opposite, we can actually better prevent issues by doing better integration - while the connection provider patterns are well understood.

Why would you want a different provider?

**Comment by bvarner** [comment]
I have worked on _many_ hibernate projects over the years where the ability to customize the SQL connection context and state before it was handed off to the ORM provider was necessary.

Specifically, (in my experience) I've used it (and seen it used) to enable data-base level auditing that maps back to the Principal in use at the application level, or to enhance the instrumentation connection usage. I've also seen environments where it was essential to execute stored procedures from draconian DBAs before you'd have rights to execute anything else.

Normally the use-cases I see (specifically with ConnectionProvider -- I'm going to ignore the multitennancy provider options for the sake of this request) never intend to _replace_ the connection provider, but would be better implemented with  with interceptor type semantics with aroundInvoke on the ConnectionProvider. But...

* ConnectionProvider isn't a CDI bean.
* The ConnectionProviderInitiator service upstream from hibernate isn't really conducive to this.
* Applications normally know exactly what kind of ConnectionProvider they need, certainly within the scope of Quarkus this is true (as you point out).

My immediate use-case is for database-trigger level auditing, which depends upon certain statements / calls to be run on the Connection after being retrieved from the pool, or before it's returned to the pool. I did not see any 'easy' or obvious hook or interceptor option for doing this on the datasource itself -- and in the applications I've run into over the years, this was one way they handled it.

**Comment by Sanne** [comment]
That's awesome feedback, thanks!

Agreed then let's make sure all use cases can be covered - and yes let's skip multi-tenancy at this point as that's a complex one which will need a series of dedicated issues.

Agroal supports listeners; I'm not sure if they are flexible enough for all cases you describe, and we're not exposing any way of registering them, but that's certainly a reasonable request.

Could we narrow this request down into one specific need and specify it better? Feel free to open as many tickets as needed for the various different things it's missing.

I guess you have already seen the Agroal extension supports an "initialization SQL" statement? I guess you need that to be taking some parameter from a context - what defines the context, how do you expect to look up the contextual values?

thanks

**Comment by bvarner** [comment]
Thanks for the feedback.
Before you'd responded, I already had a fork that was working, so I've gone ahead and submitted a PR for _this_ issue.

It looks like there could be some work to do yet around wiring up agroal datasources with hibernate (especially in the cases there is or may be more than one agroal datasource defined), and I think that all bleeds a bit into this topic.

Before opening this issue I had poked through the Agroal code. In many cases, it may be better for me to set this stuff up there -- but I have other issues / concerns there that would be other issues or requests I should open with that project first. The fastest path to making sure my hibernate conversations happen in the context I need was to expose this setting that Hibernate provides.

Thanks for the feedback, @Sanne - I'll follow up with the Agroal bits shortly.

**Comment by Sanne** [comment]
sorry @bvarner I really need to be careful in not exposing such configuration properties. I've closed your PR, we can always find it back in case there's no better solution.

Please help me with a more concrete example of what you need from Agroal; even if you just use non-compiling pseudo-code for a prototype it's fine, it would still be an important milestone and then I can ask someone else to help, or try it myself :)

**Comment by bvarner** [comment]
Ok. I can get behind Quarkus being opinionated about what configuration it exposes.

For my specific use-case, I need to setup local SQL connection 'variables' (settings) and remove them when a connection goes in and out of the pool. The stuff that needs to be passed down to the database is accessible from CDI contexts, and I've seen this accomplished through customized data sources at the container level,  or through the hibernate connection provider. Certainly the datasource listener in Agroal would be the better place do it.

The interaction looks something like this:

application ->datasource.getConnection();
    datasource->invoke listeners in prioritized, synchronous manner
    listener->connection.execute("SET LOCAL foo = 'bar'");
    <-connection

application->(does stuff on connection)

application->connection.close();
    listener->(handles listeners in synchronous reverse prioritized manner)
    connection.statement.execute("RESET foo");


If we could setup Quarkus to register any `@Application` scoped implementations of `AgroalDataSourceListener` as listeners. (Using the `@Priority` annotation to determine listener list position) this seems like it would work very well, wouldn't require changes in Agroal (Everything would be fairly isolated to AbstractDataSourceProducer in quarkus-agroal), and would avoid adding any additional Configuration properties to Quarkus.

Thoughts?

(If you don't mind, I'd like to take a pass at implementing this.)

**Comment by Sanne** [comment]
Yes I like your proposal, that would be a really nice improvement.

Keep in mind one complexity: there might be multiple datasources defined, we'll need a way to let people choose to which connections their listeners are applied.

Maybe a convention with named beans to match datasource name in some way? I don't know much about CDI, feel free to experiment what would look best in your opinion.

> I'd like to take a pass at implementing this.

That would be awesome. Feel free to share an early draft if you need any help.

If you need any help or changes in Agroal, @barreiro might also be able to help.

**Comment by bvarner** [comment]
> Keep in mind one complexity: there might be multiple datasources defined, we'll need a way to let people choose to which connections their listeners are applied.

Yes. I was planning to use a qualifier that takes the datasource name to apply the listener to. In the case that the beans don't have an annotation, they'd be applied to all the data sources defined.

**Comment by bvarner** [comment]
@Sanne - I'm going to close this, as I've logged #5381 to replace the original intent.

**Comment by Sanne** [comment]
great, thanks
