### ISSUE TITLE
ConfigProvider.getConfig() should takes profile into account

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#5223]
**Describe the bug**
Following the discussion for #4869 it appears that when accessing the Config object from `ConfigProvider.getConfig()`, profiles is not taken into account.

Reading the spec, this is the prefered way to access the configuration programmaticaly

> The current configuration of an application can be accessed via ConfigProvider#getConfig().

https://github.com/eclipse/microprofile-config#design

**Expected behavior**
`ConfigProvider.getConfig()` take profiles into account.

**Additional context**
It has been suggested to use a ConfigResolver, but this is less obvious for a user and some internal Quarkus code already use `ConfigProvider.getConfig()` so it is a bug already present in Quarkus.

**Comment by dmlloyd** [comment]
The bug is that `ConfigProvider.getConfig()` and `ConfigProviderResolver.instance().getConfig()` are unfortunately returning different instances.  This is codified in the existing bug report #4653.

It does not have any relationship to profiles.

**Comment by loicmathieu** [comment]
@dmlloyd this is not #4653 as it's about GraalVM updates.

I was a mis-understanding relationship to profiles, but anyway, the important thing is to fix it to be able to offers an undertandable (and standard) way to access the config programmatically.

**Comment by dmlloyd** [comment]
I guess I had a clipboard/brain malfunction.  I corrected the issue link.

**Comment by loicmathieu** [comment]
OK , closed this one and link the documentation PR to #4512
