### ISSUE TITLE
Cannot add extensions to Gradle project with comma-separated extensions list

### ISSUE THREAD

**Issue by xorye** [quarkusio/quarkus#5224]
**Describe the bug**
In the guide: https://quarkus.io/guides/gradle-tooling#dealing-with-extensions

it looks like we can add extensions in a comma-separated list like so: 
`./gradlew addExtension --extensions="quarkus-artemis-jms,quarkus-vertx"`

However, for my Gradle project, I get this message:
```
> Task :addExtension
❌ Cannot find a dependency matching 'quarkus-artemis-jms,quarkus-vertx', maybe a typo?
```

I took those extensions from the list provided with ./gradlew listExtensions.

**Expected behavior**
Should be able to install each extension in the comma-separated list

**Actual behavior**
I get the error message above

**To Reproduce**
1. Create a new Gradle project using the Quarkus Maven plugin (as explained in the guide)
2. Create Gradle wrapper using `gradle wrapper` (I'm using Gradle 5.6.4)
3. Run `./gradlew addExtension --extensions="quarkus-artemis-jms,quarkus-vertx"`

Step 2 is optional, the extensions don't install whether or not I use the wrapper.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux unused-10-15-17-2.yyz.redhat.com 5.0.17-300.fc30.x86_64 #1 SMP Mon May 20 15:36:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

 - Quarkus version or git rev: 
0.28.1

**Comment by geoand** [comment]
Should be an easy fix. I can take it in a few hours if no one else does
