### ISSUE TITLE
Support LDAP identity provider

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#5226]
**Describe the extension**
This extension, possibly built on top of Elytron and called `elytron-security-ldap`, will support LDAP. Perhaps a Vertx based reactive alternative can be also investigated

**Comment by stuartwdouglas** [comment]
Looks like Vert.x LDAP support is based on top of Shiro and is blocking under the covers, so we should stick with Elytron.

**Comment by sberyozkin** [comment]
@stuartwdouglas thanks for checking it.

**Comment by hartimcwildfly** [comment]
I started implementing this on monday. Today my first tests we're sucessfully. I think on friday I can do a PullRequest.

**Comment by hartimcwildfly** [comment]
How can I assign this issue?

**Comment by hartimcwildfly** [comment]
See #6111 . Tests and documentation are missing atm.

**Comment by hartimcwildfly** [comment]
As the PR is merged, the issue can be closed.

**Comment by gsmet** [comment]
This one needs to be reopened. The PR was reverted because it didn't work in native mode.

I don't think anybody worked on it since then.

**Comment by hartimcwildfly** [comment]
Corresponding ticket is #6606

**Comment by hartimcwildfly** [comment]
Ticket can be closed.
