### ISSUE TITLE
Move handling of NotFound http code from resteasy to the vertx-http extension 

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#5236]
**Description**
Current the `NotFound` error page is handled by `resteasy` via https://github.com/quarkusio/quarkus/blob/44e029ba5f100594f1fe235c63c3aee280f253b9/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/NotFoundExceptionMapper.java. 

This presents two setbacks:

- We are unable to list `vertx-web` rest endpoints and various others endpoints eg swagger, metrics, health. 
- Also, if we change the http root path via quarkus.http.root-path to something else (other than /) and try to load localhost:8080/ we get `Resource not found` generated by `vertx` instead of the error page. 

**Implementation ideas**
- Add a `DisplayableEndpointBuildItem`. 
- add a `404 failure handler` in `vertx-http` to intercept 404 http codes
- make `resteasy`, `undertow`, `vertx-web` and `spring-web` and other extensions  produce the build item so that can be propery consumed and listed from the `vertx-http` in case of a 404 error. 

/cc @gsmet @stuartwdouglas .

**Comment by Dufgui** [comment]
hello. I am back and i will try this one.

**Comment by geoand** [comment]
@phillip-kruger I assume this is something you are working on?

**Comment by phillip-kruger** [comment]
Yes, PR coming soon

**Comment by geoand** [comment]
🥳
