### ISSUE TITLE
Should we wire mvn exec:exec to either java -jar *runner.jar or quarkus:dev?

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5243]
A thought that occurred to me cc @maxandersen

**Comment by maxandersen** [comment]
you mean in users generated project ? Sure, I would say `exec:exec` would be best suited for java -jar *runner.jar and then you use `quarkus:dev` for `quarkus:dev`

**Comment by geoand** [comment]
I think we should close this as `won't fix` since no one has ever complained about it (I assume because `mvn exec:exec` is not very popular)

**Comment by gsmet** [comment]
I asked for a `mvn quarkus:run` once :).

**Comment by maxandersen** [comment]
I say we implement it instead of closing it. 

Plenty of cases in past where I wish I could just run the app without having to juggle "java -jar target/someeverionchangingjar.jar"

**Comment by geoand** [comment]
We already have https://github.com/quarkusio/quarkus/issues/9315 to track `quarkus:run`, so I propose closing this

**Comment by gsmet** [comment]
Yeah, I agree having a `quarkus:run` and a consistent experience is better.

**Comment by maxandersen** [comment]
ack!
