### ISSUE TITLE
Offer a way to control the list of locale embedded in GraalVM native image

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5244]
I don't think we offer a facility to describe the list of locale a user wants in his native image. Something like`quarkus.native.locale=en_EN,fr-FR` driving native-image would be useful.

CC @dmlloyd @stuartwdouglas

**Comment by gsmet** [comment]
I'm a big +1 on this one as it's a major issue.

But AFAIK, there's no options for that in GraalVM for now.

**Comment by Sanne** [comment]
See also #5269 : timezones

**Comment by zbendhiba** [comment]
Is there's a chance we can have this feature someday soon ?

**Comment by ppalaga** [comment]
Blocked by https://github.com/oracle/graal/issues/2908

**Comment by ppalaga** [comment]
Citing from https://medium.com/graalvm/graalvm-21-1-96e18f6806b :

> GraalVM 21.1 adds support for multiple locales in Native Image. Now you can specify at build time which locales should be included in the generated executable. For example, to switch the default locale to German and also include French and English, use -H:DefaultLocale=de -H:IncludeLocales=fr,en. All locales can be included via -H:+IncludeAllLocales. ResourceBundles are included by default for all selected locales, but this can be changed by providing a locale-specific substring when requesting the bundle.

It would be nice if Quarkus had config options for end users and BuildItems for extension authors to leverage the new options of the native compiler.

**Comment by maxandersen** [comment]
related to https://github.com/oracle/graal/issues/8295

**Comment by Karm** [comment]
@maxandersen Yes, https://github.com/quarkusio/quarkus/pull/37106 fixed that.

Ad https://github.com/oracle/graal/issues/8295

I will take a look.  I am kind of surprised this is an issue though. It seemed solved. You include what you need and move on.

**Comment by Karm** [comment]
This is an old issue. Fixed by:
Initial support added in 2022:
https://github.com/quarkusio/quarkus/pull/23518
Broadened to include all locales if needed in 2023:
https://github.com/quarkusio/quarkus/pull/37106
