### ISSUE TITLE
0.28.1 -> amazon-lamda-http not working

### ISSUE THREAD

**Issue by Ravisankar-Challa** [quarkusio/quarkus#5247]
I am getting below error when a basic hellowrold lambda deploy to AWS and invoked through API gateway. you can see the stacktrace in the attached image

![image](https://user-images.githubusercontent.com/11788842/68294071-45e5f380-00b5-11ea-87ba-a5c73add22d6.png)

**Comment by jaikiran** [comment]
This looks like an issue in vertx itself where it can't handle unresolved `InetSocketAddress`. The only way for now to get past this is probably an ugly hack in Quarkus, until the fix is available in vertx. 
I'll propose a PR here and open an issue in vertx and see what gets decided.

**Comment by jaikiran** [comment]
I've opened a PR which proposes a workaround https://github.com/quarkusio/quarkus/pull/5250

**Comment by Ravisankar-Challa** [comment]
@patriot1burke

**Comment by gsmet** [comment]
@Ravisankar-Challa can you try @jaikiran 's PR mentioned above?

Get the code from the PR, build with `mvn clean install -DskipTests -DskipITs` then use `999-SNAPSHOT` as a version.

Thanks

**Comment by Ravisankar-Challa** [comment]
Tested with 999-SNAPSHOT now I am getting a proper response. Thanks for fixing.

**Comment by machi1990** [comment]
Re-opening as the PR #5250 is not yet merged.

**Comment by jaikiran** [comment]
Closing now since the PR got merged.
