### ISSUE TITLE
 Gradle kotlin project missing all-open plugin

### ISSUE THREAD

**Issue by zulq** [quarkusio/quarkus#5249]
**Describe the bug**
When kotlin is chosen, the all-open plugin is not added

**Expected behavior**
When kotlin is chosen the all-open plugin should be added and the default allOpen section

**Actual behavior**

**To Reproduce**
1. Visit https://code.quarkus.io/
2. Create a new project with kotlin and Gradle as build tool.

**Comment by gsmet** [comment]
@aguibert and while fiddling with Kotlin, you might want to have a look at that one too. I think we used to do it at some point.

There might be useful info in the Kotlin guide.

**Comment by gsmet** [comment]
Ah, in fact, it looks as if we have a PR for it there: https://github.com/quarkusio/quarkus/pull/5032 .

**Comment by oztimpower** [comment]
+ @geoand

**Comment by geoand** [comment]
@oztimpower I'll be looking at this first thing next week! Sorry for not being able to review sooner :)

**Comment by geoand** [comment]
#5032 was just merged

**Comment by oztimpower** [comment]
@zulq given the merge of #5032 can you please close this issue?

**Comment by gastaldi** [comment]
Closing as requested
