### ISSUE TITLE
Problem creating native image (CR1) Error: Unsupported features in 3 methods

### ISSUE THREAD

**Issue by codecr** [quarkusio/quarkus#5262]
**Image generation failed with simple Rest**
If you create a simple app with Quarkus CR1 and add the extensions hibernate-orm,mariadb,resteasy-jsonb,openapi you will get an error building the native image:

Error: Unsupported features in 3 [methods]
[error.txt](https://github.com/quarkusio/quarkus/files/3816145/error.txt)
[error.txt](https://github.com/quarkusio/quarkus/files/3816146/error.txt)

Caused by: java.lang.RuntimeException: Image generation failed
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:283)

**Expected behavior**
The native image is created.

**Actual behavior**
An error creating the native image, if you change the pom and switch back t0 0.28.1 everything works fine.

**To Reproduce**
1. mvn io.quarkus:quarkus-maven-plugin:1.0.0.CR1:create   (with the default resource)
2. mvn quarkus:add-extension -Dextensions=hibernate-orm,mariadb,resteasy-jsonb,openapi
3. mvn package -Pnative

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin Gerardos-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009173705.graal.jdk8u-src-tar-gz-b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
 - GraalVM version: graalvm-ce-19.2.1 
 - Quarkus version or git rev:  CR1

**Comment by codecr** [comment]
[error.txt](https://github.com/quarkusio/quarkus/files/3816151/error.txt)

**Comment by Sanne** [comment]
Many thanks @codecr ! That was super useful. I've sent a pull request with a fix, this should be solved in the next release.

**Comment by codecr** [comment]
Thank you @Sanne
