### ISSUE TITLE
Offer a Quarkus asciiart banner

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5267]
It should be displayed once per Quarkus dev run. And probably not in tests. 
And be overridable for the usâmes like Keycloak with a small powered by Quarkus subline. 

CC @cescoffier

**Comment by stuartwdouglas** [comment]
Can we do this on project creation instead of on every startup? 

You see the asciiart once you might think its cool, you see it multiple times a day every day then it is basically just noise, and reducing logging noise was one of the design goals.

**Comment by maxandersen** [comment]
I don’t believe it will be noise. It will be a useful visual marker to know when/where quarkus started and make it instantly recognizable. 

I agree it should be as small as possible but more than just one line :)

**Comment by emmanuelbernard** [comment]
I don't think project creation is enough but +1 for an option to hide for allergic folks.

**Comment by maxandersen** [comment]
inspiration/partial implementation: https://github.com/quarkusio/quarkus-workshops/tree/master/quarkus-workshop-super-heroes/extensions/extension-banner

**Comment by KaenDagger** [comment]
hello. I would like to take this beginner issue to work upon.

**Comment by maxandersen** [comment]
@KaenDagger sounds good - we don't assign "ownership" of issues per say - best is if you open a Pull-request with your proposal then you'll get feedback from there.

**Comment by KaenDagger** [comment]
Do I also have to implement the banner as extension just like in the quarkus-superheroes-workshop ?

**Comment by emmanuelbernard** [comment]
Good question @KaenDagger. Yes try and do so. But it might be an extension we always add and will need to interact witht he Quarkus messages we see at boot (Quarkus version etc).

**Comment by maxandersen** [comment]
reopening as banner isn't actually hooked up.

**Comment by maxandersen** [comment]
currently you can do: 

`./mvnw quarkus:add-extension -Dextensions=banner`

and you get the nice banner.

Optimally this should be default enabled imo, but a few things are missing:

- an option to turn the banner off (`quarkus.banner.enabled=false`)
- an option to override the tag/line and version (`quarkus.banner.tag-name=${quarkus.application.name} and quarkus.banner.version-name=${quarkus.application.version})
-  possibly change default of tag/name to  `${quarkus.application.name}  :: Quarkus :: ${quarkus.version}' ?
 
optimally but not required, right align of the "tag/line" (right now its just printed on the left.

**Comment by geoand** [comment]
> currently you can do:
> 
> `./mvnw quarkus:add-extension -Dextensions=banner`
> 
> and you get the nice banner.
> 
> Optimally this should be default enabled imo, but a few things are missing:
> 
> * an option to turn the banner off (`quarkus.banner.enabled=false`)

This is covered by: https://github.com/quarkusio/quarkus/pull/7478

**Comment by emmanuelbernard** [comment]
I am not sure what you are referring to by tag/line and version but it seems the banner idea has deviated compared to early conversations.

We wanted 

1. a default "Quarkus banner" and right below that would show Quarkus and its version.
2. a way to override the banner but right below have a line "powered by Quarkus 1.3.0.Final"

```

           ██████╗ ██╗   ██╗ █████╗ ██████╗ ██╗  ██╗██╗   ██╗███████╗    ██╗ ██╗
██╗██╗    ██╔═══██╗██║   ██║██╔══██╗██╔══██╗██║ ██╔╝██║   ██║██╔════╝    ╚██╗╚██╗
╚═╝╚═╝    ██║   ██║██║   ██║███████║██████╔╝█████╔╝ ██║   ██║███████╗     ╚██╗╚██╗
██╗██╗    ██║▄▄ ██║██║   ██║██╔══██║██╔══██╗██╔═██╗ ██║   ██║╚════██║     ██╔╝██╔╝
╚═╝╚═╝    ╚██████╔╝╚██████╔╝██║  ██║██║  ██║██║  ██╗╚██████╔╝███████║    ██╔╝██╔╝
           ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝    ╚═╝ ╚═╝
                                                Powered by Quarkus 1.3.0.Final
```

**Comment by emmanuelbernard** [comment]
BTW what does the :: and >> around Quarkus mean in `:: Quarkus >>`?

**Comment by maxandersen** [comment]
tagline  was the `:: Quarkus :: 1.3.0.Final ` in place now. i think it follows the convention others used here but i'm fine with "Powered by Quarkus ${quarkus.version}" right aligned and make the banner text the thing that can be overridden.

**Comment by KaenDagger** [comment]
Tag line `:: Quarkus:: 1.3.0.Final` was inspired from spring banner. 

Regarding banner text `:: Quarkus >>`  originally I wanted rocket in which qurakus is written . 
So banner idea According to me was a `rocket with Quarkus written inside it`. Rocket represented speed and powerful. 

But I was unable to make that ASCII art properly

**Comment by KaenDagger** [comment]
@emmanuelbernard 
I suppose original concerns are addressed. 
- Banner text could be overriden. 
- Below banner , a line `:: Quarkus :: ${project.version}` is there .

**Comment by maxandersen** [comment]
@KaenDagger  the ask is to make the label "Powered by Quarkus {version}" 

Ignore my suggestion on putting appname and tagname overrides in.

**Comment by emmanuelbernard** [comment]
Right and figuring out how we can make this on by default.

**Comment by KaenDagger** [comment]
Label could be easily changed. But currently I have got the idea of new banner. Could I change the label with new banner.txt PR ?
Also this week I would be busy for my college exams. So would be able to work from next week

**Comment by maxandersen** [comment]
Agreed that we should move this extension to core.

Do we remove quarkus-extension from 1.3 to not have anything overlapping ?

**Comment by geoand** [comment]
I'll update my banner PR to move it to the core in a few minutes

**Comment by CDPrete** [comment]
> @KaenDagger the ask is to make the label "Powered by Quarkus {version}"
> 
> Ignore my suggestion on putting appname and tagname overrides in.

How did you manage to change the tagline? 
I cannot find any property here https://quarkus.io/guides/all-config to change it

**Comment by geoand** [comment]
It's not configurable at the time being

**Comment by CDPrete** [comment]
> It's not configurable at the time being

I see. Too bad...
