### ISSUE TITLE
Generating OpenAPI as JSON or YAML file on build

### ISSUE THREAD

**Issue by HeavyTobi** [quarkusio/quarkus#5275]
**Description**
Currently, as far as I know, it is only possible to generate the OpenAPI file when configuring it using the application.properties and the openapi plugin. I need to generate the file in a Gradle task as I want to get the OpenAPI file in a Jenkins pipeline. 

**Implementation ideas**
Maybe it is possible to add a gradle and maven task to the openapi extension, which generates the OpenAPI docs.

**Comment by gastaldi** [comment]
Maybe https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin can help?

**Comment by HeavyTobi** [comment]
Any news on that?

**Comment by rosell** [comment]
Hi!

I do not known this cna help you, but I use the swagger-maven plugin to generate the docuemnt.
<project ...
 <build>
<plugins>
<plugin>
				<groupId>io.swagger.core.v3</groupId>
				<artifactId>swagger-maven-plugin</artifactId>
				<version>${io.swagger.core.v3-version}</version>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>resolve</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<outputPath>${basedir}/target/classes/META-INF</outputPath>
					<outputFileName>openapi</outputFileName>
					<outputFormat>YAML</outputFormat>
				</configuration>
			</plugin>
...
</plugins>
</build>
</project>

**Comment by gsmet** [comment]
This is really not a Quarkus issue. It would probably be better to create an issue there: https://github.com/smallrye/smallrye-open-api (it's the implementation we use for Quarkus) and see if they would be interested to provide a Maven or Gradle plugin.

I'm not entirely sure they would have the bandwidth though but you can try.

I'm closing it here as there's nothing we will do on the Quarkus side.

**Comment by gboro54** [comment]
@rosell - I know this ticket is closed but I see your solution and was curious if you had addition dependencies in your pom? I keep getting the below:
`Execution default of goal io.swagger.core.v3:swagger-maven-plugin:2.1.1:resolve failed: A required class was missing while executing io.swagger.core.v3:swagger-maven-plugin:2.1.1:resolve: Ljavax/servlet/ServletConfig;`

**Comment by gboro54** [comment]
@rosell  - Ignore my stupid... it would help if I actually looked at the docs
