### ISSUE TITLE
ArC - optimize CreationalContext

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#5281]
Do not store dependent instances that have no `@PreDestroy`/disposal method and no transitive dependency with `@PreDestroy`/disposal method.

See https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/contexts/unbound/DependentContextImpl.java#L80-L109 and https://issues.jboss.org/browse/WELD-1076.

**Comment by blsouthr** [comment]
Hi! Any chance for it to be implemented soon?
