### ISSUE TITLE
narayana-jta extension: Improve the way narayana properties are handled

### ISSUE THREAD

**Issue by mmusgrov** [quarkusio/quarkus#5282]
The extension has some issues around how the Narayana transaction manger properties are initialised:

1. It records the default properties at build time - Narayana normally sets config properties using reflective access to setters on various beans. Version 5.10.0.Final of Narayana adds a method for directly passing pre-configured beans (and this will avoid the need for reflective access code).
2. It sets the Narayana property factory by reflectively changing the Java access mode of a private field that holds the factory.
3. The extension hard codes the properties in the Narayana ConfigurationInfo bean. The previous version of Narayana set these properties by looking inside the Narayana Java archive which is not efficient in Quarkus. The latest version of Narayana sets the properties directly in the code as constants. Therefore the extension no longer needs to hard code the properties in the ConfigurationInfoSubstitution extension class

**Comment by gastaldi** [comment]
Closing for now, as it had too much pushback on https://github.com/quarkusio/quarkus/pull/5283, please reopen if it's still valid
