### ISSUE TITLE
Default realm is always returned with HTTP 401

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#5284]
**Describe the bug**
Andrey has reported that a default `Quarkus` realm is returned with 401 even when a property such as `quarkus.security.users.file.realm-name=MyRealm` is set.

**Expected behavior**
`WebAuthenticate` needs to have a custom realm name set.

**Comment by belyaev-andrey** [comment]
It looks like this is it and you're aware of this issue. 

```io.quarkus.vertx.http.runtime.security.HttpAuthenticator```
lines 43 - 48
```java
            if (!usernamePassword.isUnsatisfied()) {
                //TODO: config
                mechanism = new BasicAuthenticationMechanism("Quarkus");
            } else {
                mechanism = new NoAuthenticationMechanism();
            }
```
