### ISSUE TITLE
DynamoDB processor accesses run time config

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#5286]
**Describe the bug**
The `io.quarkus.dynamodb.deployment.DynamodbProcessor` class accesses `io.quarkus.dynamodb.runtime.DynamodbConfig` from non-recorder steps.  The run time configuration is not normally available during build and this functionality will fail in upcoming releases.  Run time configuration must be checked at run time only.  Build time configuration must be defined as a build time configuration object.

**Fix options**
1. Change `io.quarkus.dynamodb.runtime.DynamodbConfig` to have a phase of `ConfigPhase#BUILD_AND_RUN_TIME_FIXED`.
2. Skip the check in `io.quarkus.dynamodb.deployment.DynamodbProcessor#setup` and possibly do the check at run time instead.
3. After the config update is merged, go back and use the various built-in validation constructs (optional and required properties and config groups) to validate instead of using an explicit check method

/cc @marcinczeczko

**Comment by marcinczeczko** [comment]
@dmlloyd - see PR #5319 

Re pt. 3 - Is there are PR already for those changes that I can take a look early ?

**Comment by dmlloyd** [comment]
No PR yet, I'm just cleaning up the gruesome remains after a rebase.  Things are working though; I hope to file the PR early next week.
