### ISSUE TITLE
Quarkus maven plugin seems to ignore my mainClass setting

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#5291]
It seems that at some point between versions 0.22.0 and 1.0.0.CR1, Quarkus maven plugin stopped recognizing settings such as:

```
<configuration>
    <mainClass>biz.karms.quarkus.json.formatter.Main</mainClass>
</configuration>
```

## Platform
* graalvm-ce-19.1.1 Linux x86_64
* Apache Maven 3.6.0
* OpenJDK 11

## Steps to reproduce:

 * clone https://github.com/Karm/qjf.git
 * mvn clean package -Pnative
 * get some json file and let it format it:
 * curl https://starter.karms.biz/api/supportMatrix | ./target/qjf-runner 

It works as long as the version is e.g. 0.22.0 (which is in the aforementioned repo):

```
karm@local:~/workspaceRH/qjf $ cat ugly.json | ./target/qjf-runner

{
    "configs": {
        "MP30": {
            "supportedServers": [
                "LIBERTY",
<SNIP>
```

It breaks if you change Quarkus version in the pom.xml to e.g. 1.0.0.CR1:

By "it breaks" I mean that my Main class is ignored and the generated Quarkus one is used.

```
(base) karm@local:~/workspaceRH/qjf ((v1.0) *%)$ cat ugly.json | ./target/qjf-runner
2019-11-07 15:33:07,322 INFO  [io.quarkus] (main) qjf 1.0.0-SNAPSHOT (running on Quarkus 1.0.0.CR1) started in 0.001s.
2019-11-07 15:33:07,322 INFO  [io.quarkus] (main) Profile prod activated.
2019-11-07 15:33:07,322 INFO  [io.quarkus] (main) Installed features: []

...hangs....

^C

2019-11-07 15:33:09,139 INFO  [io.quarkus] (main) qjf stopped in 0.000s
```

Is this a configuration thing? Is it a feature or a bug? After some googling around the Quarkus guides I consider this a bug, hence this issue. Thank you for feedback.

**Comment by gastaldi** [comment]
I don't think that `mainClass` will ever get back to the plugin, but I'd rather let @stuartwdouglas confirm this

**Comment by Karm** [comment]
@gastaldi  @stuartwdouglas What is the reason for the removal? My motivation was simple: Use the power of prepared Quarkus machinery to generate GraalVM configs for me, but then use my own entry point...
I realize this is a niche thing, but then again, why shouldn't it be possible?

**Comment by stuartwdouglas** [comment]
The problem with MainClass is that it does not really work with dev mode, and anything that happens in the main class happens before CDI has started etc, so nothing Quarkus provided is available. 

Is there any reason why we can't just observe the StartupEvent?

**Comment by stuartwdouglas** [comment]
Also you should be able to still do this via quarkus.package.main-class in application.properties.

**Comment by Karm** [comment]
@stuartwdouglas 
Ad 

 > Also you should be able to still do this via quarkus.package.main-class in application.properties.
  
I can confirm it works with Quarkus 1.0.0 RC1: [application.properties](https://github.com/Karm/qjf/blob/master/src/main/resources/application.properties)  :+1:    Thank you for the hint.


Ad 

 > Is there any reason why we can't just observe the StartupEvent?

I took a look at [AppLifecycleBean.java](https://github.com/quarkusio/quarkus-quickstarts/blob/master/lifecycle-quickstart/src/main/java/org/acme/events/AppLifecycleBean.java) but I don't like the need for [GreetingResource.java](https://github.com/quarkusio/quarkus-quickstarts/blob/master/lifecycle-quickstart/src/main/java/org/acme/events/GreetingResource.java) there...   I want to start as quickly as possible; process stream from System.in and exit. I don't want to start the server. In this trivial example I also don't care about CDI, I just ab/used Quarkus to generate Graal config for me...

If I want to do something more, e.g. start, connect to Elastic, process something quickly and exit, I would need CDI. Again, I wouldn't want to start web server. What I would do, or better said, where I would start would be trying to rewrite things I used to do with Weld to Arc.... stuff in ```public static void main``` like:

```
 Weld weld = new Weld().beanClasses(
                ElasticClientProducer.class,
                SomeIOther.class,
                LoggerProducer.class,
                DataProcessor.class).disableDiscovery();
        weld.initialize();
```

I assume the debate on [Command Mode](https://groups.google.com/forum/#!msg/quarkus-dev/KiqCbqQZe_o/DEVowWmyAQAJ) bears some fruit...

**Comment by Karm** [comment]
/me looking at https://github.com/quarkusio/quarkus/pull/2866

**Comment by aj03794** [comment]
Question about this. If we use `@Observes StartupEvent` to define start up logic, when we run our tests, this same startup code will run - which doesn't really make a whole lot of sense when unit testing.

Is there a way to work around this without changing the entry point of the app with `quarkus.package.main-class`

**Comment by stuartwdouglas** [comment]
That is a good point, but I think it is going to depend a lot on what the tests do as to if you want the startup logic to run or not. At the moment you can just manually use io.quarkus.runtime.LaunchMode#current() to decide if you want to run the logic or not.

**Comment by stuartwdouglas** [comment]
This should not be a problem now we have command mode support.
