### ISSUE TITLE
NPE while :quarkusBuild gradle task when @ServletSecurity annotation not present on servlet

### ISSUE THREAD

**Issue by Xnyle** [quarkusio/quarkus#5293]
Trying to build a runnable jar with quarkus gradle plugin (versions tested 0.26 and CR1), i'm getting (line numbers from CR1):

Caused by: java.lang.NullPointerException
at io.quarkus.undertow.deployment.UndertowBuildStep.build(UndertowBuildStep.java:349)

Corresponding code is:

`ssmd.getEmptyRoleSemantic() == EmptyRoleSemanticType.DENY ? DENY : PERMIT);`

ssmd from webMetaData.getAnnotations().getServletSecurity() must therefore be null.

I have a few  
@WebServlet(...) annotated Servlets without 
@ServletSecurity annotation.

I didn't find anything about having to add that annotation in order to get quarkus running, so I guess it's a bug?

**Comment by Xnyle** [comment]
Just confirmed, after adding an empty @ServletSecurity annotation to all my servlets NPS disappears.

**Comment by geoand** [comment]
@Xnyle any change you can provide a small reproducer?

**Comment by Xnyle** [comment]
Just throw in an empty class annotated with only @WebServlet(urlPatterns = {"/something/*"})
**without** @ServletSecurity annotation.

or just change `ssmd.getEmptyRoleSemantic() == EmptyRoleSemanticType.DENY ? DENY : PERMIT)` to `ssmd == null ? PERMIT : ssmd.getEmptyRoleSemantic() == EmptyRoleSemanticType.DENY ? DENY : PERMIT)`

**Comment by geoand** [comment]
I'll give it a try

**Comment by Xnyle** [comment]
And ofc add quarkus-undertow dependency

**Comment by geoand** [comment]
@Xnyle what is `ofc`?

**Comment by geoand** [comment]
I haven't been able to reproduce this yet

**Comment by Xnyle** [comment]
"Of couse".

That's very strange. Have you looked at the source code? There is supposed to be a list of Annotations, but there is no list In my case, just null. I didn't look at where that list is coming from but I'm pretty sure you always get null at that point if there is not a single @ServletSecurity annotation in your test case.
Mit freundlichen Grüßen
Björn Schmidt

Am 7. November 2019 17:13:25 MEZ schrieb Georgios Andrianakis <notifications@github.com>:

**Comment by geoand** [comment]
I'll give it another shot soon

**Comment by geoand** [comment]
I tried again and still can't reproduce. I also looked at the source code and I didn't see anything fishy.
Can you please create a small reproducer that I can test, since I must be missing something :)

**Comment by Xnyle** [comment]
I'll try to strip my usecase down tomorrow.
Mit freundlichen Grüßen
Björn Schmidt

Am 7. November 2019 17:59:44 MEZ schrieb Georgios Andrianakis <notifications@github.com>:

**Comment by geoand** [comment]
Thanks!

**Comment by geoand** [comment]
Thanks!

**Comment by jaikiran** [comment]
Hello @geoand, @Xnyle,

I was able to reproduce this issue in a test case. I've submitted https://github.com/quarkusio/quarkus/pull/5316 to fix this.

**Comment by geoand** [comment]
Excellent!

**Comment by Xnyle** [comment]
[npequarkus.tbz2.this.is.not.a.zip](https://github.com/quarkusio/quarkus/files/3823423/npequarkus.tbz2.this.is.not.a.zip)
