### ISSUE TITLE
Dependency on io.sundr:sundr-codegen imports system dependency

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#5296]
**Describe the bug**
The `io.sundrbuilder-annotations` used by the Kubernetes extension is depending transitively on `io.sundr:sundr-codegen`, whose pom includes this section:

    <profile>
      <id>jdk9</id>
      <dependencies>
        <dependency>
          <groupId>com.sun</groupId>
          <artifactId>tools</artifactId>
          <version>1.7</version>
          <scope>system</scope>
          <systemPath>/home/iocanel/.sdkman/candidates/java/1.0.0-rc-16-grl/jre/../lib/tools.jar</systemPath>
        </dependency>
      </dependencies>
    </profile>

And of course that's an illegal path on my system.

This breaks my ability to import the Quarkus project in the IDE, it's quite annoying. Let's please cleanup that pom file  (hopefully there's better solutions), or perhaps we could exclude this dependency?

I don't know what `io.sundr:sundr-codegen` is.

Thanks

**Comment by geoand** [comment]
@iocanel has already fixed this in the upstream dekorate library so we'll need an update to pick it up.

@iocanel would you like to take care of that?

**Comment by geoand** [comment]
@iocanel does version `0.9.9` take care of the problem or do you have to do a release?

**Comment by iocanel** [comment]
We need a new release.

**Comment by geoand** [comment]
This has since been fixed, so I'm closing the issue.
