### ISSUE TITLE
Document how to discover services on Kubernetes

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#5298]
Not having this documented misleads users to think that Quarkus does not support the service discovery. This also makes us loose in comparison with other frameworks - see https://speakerdeck.com/fbascheper/2020-a-space-odyssey-with-micronaut-and-quarkus?slide=29

**Comment by geoand** [comment]
@ppalaga Can you explain this one a little? I am not sure what it refers to

**Comment by ppalaga** [comment]
This is really old. IIRC at that time, the team's strategy was that service discovery does not need any special implementation in Quarkus, because it is solved by Kubernetes or whichever other container orchestrator the application runs in. There was no sole word about this topic in the whole Quarkus docs and so newcomers could have thought that there is no solution to the problem at all. Although, in between, the perception of this may have changed on both sides, I still think Quarkus should have a service discovery guide.

@fbascheper would you perhaps like to sketch your expectations in this area?

**Comment by geoand** [comment]
Thanks for the information.

cc @michalszynkiewicz

**Comment by geoand** [comment]
Closing this as we now have https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/stork-reference.adoc
