### ISSUE TITLE
Exempt MicroProfile Health paths from security authorization

### ISSUE THREAD

**Issue by aaronanderson** [quarkusio/quarkus#5307]
**Description**
Currently the OIDC extension and possibly other security extensions are intercepting requests to the /health/ready and /health/live paths. This is causing a problem for  simple HTTP health checks initiated from loadbalancers without sophisticated authentication or redirect handling capabilities.

**Implementation ideas**
Several ideas were discussed on the [Quarkus Dev group](https://groups.google.com/forum/#!topic/quarkus-dev/P7g0er0vaa8). The simplest solution is to add an ability to exempt the /health paths and make them public. However the downside to this is that developers may have added custom health checks to their applications which may leak internal configuration data over the Internet.

Another option would be to startup a dedicated health check network port for exclusively for heath check requests. I am not sure how easy it would be to accomplish that.

**Comment by sberyozkin** [comment]
@aaronanderson Thanks, both mechanisms can be supported, the former for the simpler cases (Stuart may prefer to fix at the policy level directly), the latter - well, it is tricky, but may be we can just add a Label `Requires Stuart` to have it fixed too :-)

**Comment by stuartwdouglas** [comment]
This should be fixed by https://github.com/quarkusio/quarkus/pull/5315, in that you can now just exclude /health using your config.
