### ISSUE TITLE
Subresouce init resource failed when using `ResourceContext.getResource`

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#5314]
I have created a post about the sub resource issue on StackOverflow before, https://stackoverflow.com/questions/57820428/jax-rs-subresource-issue-in-quarkus 
It seems [Quarkus issue#3919](https://github.com/quarkusio/quarkus/issues/3919) has been resolved in the latest 1.0.0.CR1. 

When I tried to remove the workaround annotations(`@Unremovable`, `@RegisterForReflection `), it failed, there are still some issues in 1.0.0.CR1. 

```java
@RequestScoped
public class CommentResource {
    private final static Logger LOGGER = Logger.getLogger(CommentResource.class.getName());
    private final CommentRepository comments;

    @Context
    UriInfo uriInfo;

    @Context
    ResourceContext resourceContext;

    @PathParam("id")
    String postId;

    @Inject
    public CommentResource(CommentRepository commentRepository) {
        this.comments = commentRepository;
    }

    @GET
    public Response getAllComments() {
        return ok(this.comments.allByPostId(this.postId)).build();
    }
```

And declares it as sub-resources of `PostResource` like this.

```java
    @Path("{id}/comments")
    public CommentResource postResource() {
        return resourceContext.getResource(CommentResource.class);
    }
```

When I ran the application and tried to access comments resources like `/posts/< post id>/ comments`, failed with NPE exception in this line `  return ok(this.comments.allByPostId(this.postId)).build();`.

`@PathParam("id") String postId` or `this.comments` injection failure caused this exception. 

But when change the subresource declaration to the following. 

```java
    @Inject CommentResource commentResource;

    @Path("{id}/comments")
    public CommentResource postResource() {
        return resourceContext.initResource(commentResource);
    }
```
It works.  A updated version is [here](https://github.com/hantsy/quarkus-sandbox/tree/master/post-service). 

But I think both approaches(`getResource` or `initResource`) should work in JAX-RS.

**Comment by sdaschner** [comment]
+1 same happens for me `1.0.1.Final`. Are there any updates on this?

**Comment by gsmet** [comment]
@asoldano could you confirm that what is described above should work?

**Comment by sdaschner** [comment]
Some more investigation on this:

Apparently the issue is caused by removal of the sub-resource at build time. When I use `resourceContext.getResource(MySubResource.class)` and at the same time annotate `MySubResource` with `@Unremovable` (or use an unused, dummy injection of `@Inject MySubResource mySubResource`), then it works as expected.

From the logs:

```
2020-02-06 08:11:19,374 WARN  [io.qua.arc.run.ArcRecorder] (executor-thread-1) Bean matching class com.sebastian_daschner.MySubResource was marked as unused and removed during build.
```

So, I guess we could resolve this by taking the sub-resource creation via `ResourceContext#getResource(Class)` into account?

**Comment by geoand** [comment]
This works for RESTEasy Reactive does it not?

**Comment by siksniraps** [comment]
I'm having this same issue using RESTEasy Reactive as well. On 3.3.1

**Comment by geoand** [comment]
@siksniraps do you have a sample application I can try?

**Comment by siksniraps** [comment]
> @siksniraps do you have a sample application I can try?

Here's an example project with quarkus 3.7.4: https://github.com/siksniraps/example-quarkus-5314

**Comment by geoand** [comment]
Τηανκσ

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/39028 takes care of it for RESTEasy Reactive

**Comment by hantsy** [comment]
Thanks for resolving this issue, finally.

**Comment by geoand** [comment]
YW
