### ISSUE TITLE
quarkus.native.enable-code-size-reporting not work in GraalVM 19.2.1

### ISSUE THREAD

**Issue by jorsol** [quarkusio/quarkus#5324]
**Describe the bug**
Set property: `quarkus.native.enable-code-size-reporting` activates `-H:+PrintCodeSizeReport` in GraalVM native image parameters.

**Expected behavior**
The option/property should be probably removed since is not supported in GraalVM.

**Actual behavior**
```
Error: Could not find option 'PrintCodeSizeReport'. Use -H:PrintFlags= to list all available options.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.0.0-32-generic
 - Output of `java -version`: OpenJDK 64-Bit GraalVM CE 19.2.1
 - Quarkus version or git rev: 1.0.0.CR1

**Comment by machi1990** [comment]
I'll have a look.
