### ISSUE TITLE
Remove config customizer

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#5332]
We should probably remove config customizer.  It's better to produce a config source instead, and simplifies the native image stuff and the config handling code (not to mention all the APIs in between).

**Comment by stuartwdouglas** [comment]
@dmlloyd is this still an issue? I am not sure what it is referring too?

**Comment by dmlloyd** [comment]
It was referring to anything which depends on `io.quarkus.deployment.QuarkusAugmentor#configCustomizer`.
