### ISSUE TITLE
swagger-ui does not discover paths defined by spring-web annotations

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#5339]
**Describe the bug**
If the quarkus-smallrye-openapi extensions is included in a project that is using the quarkus-spring-web extension, swagger-ui does not discover and describe rest endpoints defined by spring web annotations in the application

**Expected behavior**
![swagger-ui-expected](https://user-images.githubusercontent.com/959822/68497453-80ce5f80-024c-11ea-9583-0b7bde8305fc.png)

**Actual behavior**
![swagger-ui-actual](https://user-images.githubusercontent.com/959822/68497463-86c44080-024c-11ea-83cd-fe3429512ee7.png)

**To Reproduce**
1. checkout quarkus-quickstarts 
2. `cd ./spring-web-quickstart/`
3. add the following to `pom.xml`
``` 
       <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
```
4. start quarkus in dev mode: `mvn compile quarkus:dev`
5. navigate to `http://localhost:8080/swagger-ui`

**Comment by geoand** [comment]
I'm going to close this as a duplication of #4693. Does that make sense @johnaohara ?

**Comment by johnaohara** [comment]
Sure, I did a search before opening this issue and didn't find that issue, but yes is a duplicate
