### ISSUE TITLE
Kubernetes exension should configure RBAC when kubernetes-client extension is present.

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#5345]
**Description**
When someone uses both `kubernetes` and `kubernetes-client` extensions, it's obvious that the intention is to use the `kubernetes-client` from a pod deployed on kubernetes. In this case, RBAC needs to be configured so that we ensure that the pod serviceAccount has all the required permission that the `kubernetes-client` can at least perform simple read operations.

**Implementation ideas**
When the `kubernetes-client` `FeatureBuildItem` the `kubernetes` extension adds the required RBAC config.

**Comment by gsmet** [comment]
@iocanel was something merged to fix that one? Or should I mark it as invalid?

**Comment by iocanel** [comment]
@gsmet #5367 was merged!

**Comment by gsmet** [comment]
Ok, I adjusted the fix version then. Thanks!
