### ISSUE TITLE
Simplest generated project fails with quarkus:dev with JDK 13 on Windows 10

### ISSUE THREAD

**Issue by bdesemb** [quarkusio/quarkus#5359]
**Describe the bug**
Generated project doesn't run with `quarkus:dev` on Windows 10. The same project run seamlessly on macOS Catalina.

**Expected behavior**
Runs without any error.

**Actual behavior**
Fails at run with error message:
```
[INFO] --- quarkus-maven-plugin:1.0.0.CR1:dev (default-cli) @ code-with-quarkus ---
Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Listening for transport dt_socket at address: 5005
Error: Could not find or load main class io.quarkus.dev.DevModeMain
Caused by: java.lang.ClassNotFoundException: io.quarkus.dev.DevModeMain
```

**To Reproduce**
1. Generate the simplest app on code.quarkus.io (whithout extensions)
2. Run `mvn compile quarkus:dev`

**Environment:**
 - OS: Windows 10 (KO) and macOS Catalina (OK)
 - JDK: tested with Oracle JDK 13

**Additional context**
I found a similar issue:
https://github.com/apache/camel-quarkus/issues/263
but this one seems related to camel and I am not using it.

**Comment by jaikiran** [comment]
Hello @bdesemb, does this only happen with Java 13?
Can you try with Java 8 and see if it works? Also, can you post the output of the directory listing of the "target" directory when this fails against Java 13? If its easier, you can just zip/tar the contents of your target dir and upload it as an attachment to this issue.

**Comment by bdesemb** [comment]
Hi @jaikiran, I tested with Java 11 and Java 8 and both are working well.

Here is all the generated files in target with Java 13
```
├───classes
│   │   application.properties
│   │
│   ├───be
│   │   └───devoxx
│   │           ExampleResource.class
│   │
│   └───META-INF
│       └───resources
│               index.html
│
├───generated-sources
│   └───annotations
├───maven-status
│   └───maven-compiler-plugin
│       └───compile
│           └───default-compile
│                   createdFiles.lst
│                   inputFiles.lst
│
└───wiring-devmode

```

FYI, `mvn package` passes in Java 13. It builds the 'runner' jar that I can run and see the result on http://localhost:8080

**Comment by jaikiran** [comment]
@bdesemb, thank you for these additional details. So it looks like this is specific to Java 13 on Windows. I'll try and find a Windows machine later this week to see what's going on.

**Comment by jaikiran** [comment]
@bdesemb I was able to reproduce this issue. Looks like the `Class-Path` parsing of `jar` `MANIFEST` has gone wrong again (within the JDK). I need to understand why/how this has regressed before I bring this up with the JDK team. For now, this isn't really something Quarkus can fix reliably across JDK versions (unless, there's some workaround I'll stumble upon during investigation). I'll keep this issue updated.

**Comment by jaikiran** [comment]
I've brought this up on OpenJDK mailing list to ask for their inputs https://mail.openjdk.java.net/pipermail/core-libs-dev/2019-November/063491.html

**Comment by jaikiran** [comment]
The JDK 13 `Class-Path` details in the `jar` spec[1] has additional details explaining what constitutes as valid `Class-Path` entries. Plus the linked mailing list thread makes it clear that this change is intentional. So I will try and come up with a fix to our `Class-Path` value generation to make it work against Java 13 as well as previous versions of Java.

[1] https://docs.oracle.com/en/java/javase/13/docs/specs/jar/jar.html#class-path-attribute

**Comment by jaikiran** [comment]
I've proposed https://github.com/quarkusio/quarkus/pull/5808 to see if we would like to go with the approach suggested in that PR.
