### ISSUE TITLE
Duplicated classes in commons-logging dependencies

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#5361]
**Describe the bug**
Apache commons logging dependency is sometimes being included in the build output along with our `commons-logging-jboss-logging` artifact, causing unpredictable issues with logging.

```console
$ cd integration-tests/main && mvn install -Dtest=io.quarkus.it.main.HealthCheckTestCase
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.jboss.logging:commons-logging-jboss-logging::jar:1.0.0.Final(compile), commons-logging:commons-logging::jar:1.2(compile)] contain duplicate files, e.g. org/apache/commons/logging/impl/SimpleLog$1.class
```

**Additional context**
Relates to #4528

**Comment by stuartwdouglas** [comment]
We really need the ability for extensions to 'filter' out bogus artifacts.

**Comment by geoand** [comment]
We essentially have this in https://github.com/quarkusio/quarkus/blob/2.7.1.Final/core/deployment/src/main/java/io/quarkus/deployment/configuration/ClassLoadingConfig.java#L56

**Comment by stuartwdouglas** [comment]
Even so should this just be banned outright?

**Comment by geoand** [comment]
This specific case probably should
