### ISSUE TITLE
Improve rendering of html code snippets in the docs

### ISSUE THREAD

**Issue by dodalovic** [quarkusio/quarkus#5362]
In https://quarkus.io/guides/vertx#streaming-using-server-sent-events, the following snippet not highlighted:

![image](https://user-images.githubusercontent.com/6358061/68547126-f9185a80-03dd-11ea-97f6-1efd5f2a9475.png)

**Comment by gwenneg** [comment]
Hi @dodalovic. All HTML snippets look like this one in the Quarkus documentation.

Is there a problem with this specific snippet or are you suggesting the HTML highlighting could be improved globally?

**Comment by dodalovic** [comment]
Globally, since other languages are indeed highlighted, I'm not sure if `html` is the only one causing issues

**Comment by gwenneg** [comment]
I agree we could do a better HTML highlighting (and check the highlighting for other types of sources) in the Quarkus doc. Thanks for suggesting this!

**Comment by gsmet** [comment]
I just pushed a fix to the website.
