### ISSUE TITLE
Cannot do docker build with gradle based on native image

### ISSUE THREAD

**Issue by majonga88** [quarkusio/quarkus#5363]
Hi folks.

I would like to know how we can do a docker build with gradle based on native build. 

I read this doc : https://quarkus.io/guides/gradle-tooling

I build a native image with this command : `./gradlew buildNative --docker-build=true`, it works.

But when i see the DockerFile.native, i would like to build my docker image with this command : 
`docker build -f src/main/docker/Dockerfile.native -t quarkus/openapi-swaggerui-quickstart .`

But i have an error into the DockerFile, at this line : `COPY target/*-runner /work/application`, with this error : 

> Step 3/6 : COPY target/*-runner /work/application
> COPY failed: no source files were specified

The cause is when i do this with maven package it works because a target folder is created but in gradle it's not. I tried to switch the **target** folder to **build** folder (where the runner is present) in the DockerFile, but i have the same error :

> Step 3/6 : COPY build/*-runner /work/application
> COPY failed: no source files were specified

Someone can help me about this problem ?

Ps : My project is based on this tutorial : https://quarkus.io/guides/openapi-swaggerui

Thanks a lot for your help, feel free to ask.

**Comment by gastaldi** [comment]
@majonga88 that's because the `.dockerignore` is ignoring it. Try deleting this file and run the command again. 

@geoand any idea why this file exists?

**Comment by gastaldi** [comment]
Ah the `.dockerignore` for gradle needs to reference the `build/` directory instead of `target/`, I'll submit a PR

**Comment by majonga88** [comment]
Ok thinks a lot for your support on this issue !
