### ISSUE TITLE
Support spring-web wildcard syntax in @RequestMapping

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#5370]
**Describe the bug**
Spring-web RequestMapping allows for wildcard definitions within paths that have a different syntax from valid jax-rs paths. 

In order to facilitate support of spring-web applications without developers having to re-define path mappings, quarkus should fully support the spring-web syntax in @RequestMapping definitions.

**Expected behavior**
e.g `@GetMapping("/wildcard/*/{name}")` should map `/wildcard/1/Quarkus`, currently returns HTTP 404, whereas `/wildcard/*/Quarkus` returns HTTP 200

`@RequestMapping("/car?/s?o?/info")` should also map urls  "/cars/shop/info" and "/cart/show/info"

**To Reproduce**
1. `git clone git@github.com:johnaohara/quarkusSpringWebWildcards.git `
2. `cd quarkusSpringWebWildcards`
3. `mvn clean test`

**Comment by geoand** [comment]
@asoldano @patriot1burke @FroMage does JAX-RS not support expressions like `@PATH("/wildcard/*/{name}")`?

**Comment by asoldano** [comment]
@geoand see https://docs.jboss.org/resteasy/docs/4.4.0.Final/userguide/html/Using_Path.html#_Path_and_regular_expression_mappings

**Comment by geoand** [comment]
Excellent, thanks @asoldano!

**Comment by geoand** [comment]
RESTEasy PR opened to address these cases. Once it's been merged and released I can update Quarkus to add some tests cases for this

**Comment by geoand** [comment]
I forgot to add tests, but actually they shouldn't be needed since all relevant the tests were added in RESTEasy
