### ISSUE TITLE
@InterceptorBinding no longer recognized/fired when they have additional fields

### ISSUE THREAD

**Issue by Xnyle** [quarkusio/quarkus#5373]
This interceptor binding is working fine, if there is an interceptor (having @Priority annotation or not, @AroundInvoke gets fired wherever @StorageThreadSession is annotated):

```
@Target({TYPE, METHOD})
@Retention(RUNTIME)
@InterceptorBinding
public @interface StorageThreadSession {
}
```

adding a field to the binding definition, @AroundInvoke stops working, it seems the interceptor binding is not recognized at all in this case:

```
@Target({TYPE, METHOD})
@Retention(RUNTIME)
@InterceptorBinding
public @interface StorageThreadSession {
	
	Class qualifier() default Object.class;
}
```

I can split up my annotation but I don't think that this is the desired behaviour.

**Comment by gwenneg** [comment]
Hi @Xnyle! Depending on how you want the interceptor to be activated, you might need to add the [@NonBinding](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#interceptor_resolution) annotation to the `qualifier` member of your interceptor.

**Comment by Xnyle** [comment]
Ok, learned something new, while @NonBinding might solve my problem, shouldn't any interceptor annotation used without any parameters still match all the default values defined in the binding definition?

Which it does on Wildfly/Thorntail but not on Quarkus.

Although I haven't tested it, I think you can reuse https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/bindings/MyTransactional.java, remove @NonBinding and then use @MyTransactional() without any parameters in InvocationContextBindingsTest.

That should reproduce my usecase and the expectation is that the interceptor still fires.

**Comment by gwenneg** [comment]
If it works with Wildfly and Thorntail but not with Quarkus, then it's worth asking @mkouba for his opinion.

**Comment by mkouba** [comment]
> shouldn't any interceptor annotation used without any parameters still match all the default values defined in the binding definition?

Yes, I think that default values should be used for both the bean and the interceptor. In other words, the interceptor should be bound to a bean annotated with the binding that has the same annotation member value.

It's probably a bug. I'll look into the relevant parts of ArC.
