### ISSUE TITLE
Spring-web integration does not support mapping multiple resource to same path root

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#5375]
**Describe the bug**
spring-web supports mapping of multiple Resources to the same path root.  For example, the following ResourceMappings definitions are valid in a spring-web application;

```
@RestController
public class PetResource {
    @GetMapping("/pets/{petId}")
    public Object findPet(@PathVariable("petId") int petId) {...}
...
    @GetMapping("/owners/pets/{petId}")
    public Object findOwnersPet(@PathVariable("petId") int petId) {...}
...
}
```

```
@RestController
@RequestMapping("/owners")
public class OwnerResource {
...
    @GetMapping(value = "/{ownerId}")
    public Integer findOwner(@PathVariable("ownerId") int ownerId) {...}
...
}
```

From the class definitions above the following urls should be valid;

`/pets/1`
`/owners/pets/1`
`/owners/1`

Currently, url `/owners/pets/1` returns a HTTP 404 error

**Expected behavior**

`/pets/1` -> HTTP 200
`/owners/pets/1` -> HTTP 200
`/owners/1` -> HTTP 200

**Actual behavior**

`/pets/1` -> HTTP 200
`/owners/pets/1` -> HTTP 404
`/owners/1` -> HTTP 200

**To Reproduce**
1. `git clone git@github.com:johnaohara/rest-multiPath.git`
2. `cd rest-multiPath
3. mvn clean test

**Comment by geoand** [comment]
@asoldano is this feature supported in JAX-RS?

**Comment by geoand** [comment]
@asoldano it seems like JAX-RS doesn't allow a scenario like @johnaohara describes (assuming JAX-RS annotations instead of Spring Web ones).
Is there some other alternative perhaps or any clues to where to look to support such a case and how difficult it would be?

**Comment by geoand** [comment]
I think this will now work if you use Spring Web on RESTEasy Reactive. Feel free to comment or reopen if it doesn't
