### ISSUE TITLE
Implicit serving of a welcome page

### ISSUE THREAD

**Issue by rboei** [quarkusio/quarkus#5378]
Hey,
as requested by Sergey Beryozkin in this zulip topic: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/implizit.20redirect.20to.20index.2Ehtml/near/180420334
a new feature request:
Add an option to enable automatic redirects to a welcome page.
e.g. a user requests http://server/a/ und gets served http://server/a/index.html if the option is enabled.

Kind regards,
Rene

**Comment by 38leinaD** [comment]
The way to do this in a servlet container should be via the web.xml and a welcome-file-list. It seems, this is not supported today though available from WebMetaData; so, should be easy to add.
	 https://github.com/quarkusio/quarkus/blob/8f0a74c70e137042cf17b085e6e44cb770b08ebc/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java#L200
