### ISSUE TITLE
Allow addition of AgroalDataSourceListener implementations during run-time production of DataSources.

### ISSUE THREAD

**Issue by bvarner** [quarkusio/quarkus#5381]
**Description**
Allow CDI @ApplicationScoped AgroalDataSourceListeners to be registered, prioritized, and applied to appropriate data sources during production of an AgroalDataSource.

**Implementation ideas**
Per discussion on #5219, [a CDI implementation](https://github.com/quarkusio/quarkus/issues/5219#issuecomment-551938067) may be an elegant way to handle this.

**Comment by Sanne** [comment]
hi @barreiro could you have a look here please from an Agroal perspective? Also see the linked previous discussion on #5219 to get some context

@mkouba and we'll need you for the CDI aspects :)

**Comment by bvarner** [comment]
Sorry for the confusing stuff on here. I've squashed my commits and rebased with a new PR.

**Comment by Sanne** [comment]
Related PR #9009 was merged
