### ISSUE TITLE
smallrye-reactive-messaging-mqtt-server support

### ISSUE THREAD

**Issue by romatthe** [quarkusio/quarkus#5382]
**Describe the extension**
Using Smallrye Reactive Messaging already seems to have support for MQTT in preview, but it seems this is currently only for the `smallrye-mqtt` connector, and not for the `smallrye-mqtt-server` connectors (which is used for ingesting MQTT messages directly). Using the `smallrye-mqtt-server` connector currently simply throws a `IllegalArgumentException: Unknown connector for data.`.

Is the `smallrye-mqtt-server` connector something that is planned for inclusion in the "SmallRye Reactive Messaging - MQTT Connector" extension that is currently in preview? Or should this take the form of a separate extension?

**Comment by bulldog98** [comment]
If I saw correctly in the [smallrye/smallrye-reactive-messaging repository](https://github.com/smallrye/smallrye-reactive-messaging) there exists no mqtt-server connector since version 3. Can this be close therefore @cescoffier ?

**Comment by cescoffier** [comment]
Yes, unfortunately, we didn't have the capacity to implement the support. 

Let's close it. If someone is interested in contributing, it's more than welcome.
