### ISSUE TITLE
void return type in Spring `@ExceptionHandler` should work without a @ResponseStatus annotation

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#5392]
I played more examples of exception handling except the ones mentioned in #4042 .

The following exception handling should work. 

```java
 @ExceptionHandler(Exception2.class)
 public void handleException2(Exception2 e, HttpServletResponse response) throws IOException {
        response.setHeader("Content-Type", "application/json");
        response.getWriter().write(e.getMessage());
        response.sendError(HttpServletResponse.SC_BAD_REQUEST);
 }
```

But in the startup stage, Quarkus will complain it should be used with a `@ResponseStatus`.

**Comment by hantsy** [comment]
I have added more [exception handlers](https://github.com/hantsy/quarkus-sandbox/blob/master/spring-post-service/src/main/java/com/example/PostExceptionHandler.java#L31) in my example codes, hope they work when building a real-world Spring application with Quarkus.

**Comment by geoand** [comment]
I'll fix this (hopefully) for `1.0.0.Final`.

**Comment by geoand** [comment]
#5395 should take care of this

**Comment by hantsy** [comment]
@geoand Another small issue. https://stackoverflow.com/questions/58966932/httpservletresponse-set-charset-does-not-wok-in-quarkus-undertow

Great work done in 1.0.0.CR2, I think the spring extensions are ready for production now.

**Comment by geoand** [comment]
Thanks @hantsy , I'll check it out
