### ISSUE TITLE
Follow the Spring ComponentScan rule to create beans

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#5393]
I created a  `AppConfig` to setup some configurations for Spring application. 

```java
@Configuration
public class AppConfig {

    @Bean
    public ObjectMapper jackson2ObjectMapperBuilder(){
        Jackson2ObjectMapperBuilder builder = Jackson2ObjectMapperBuilder.json()
                .featuresToEnable(INDENT_OUTPUT)
                .featuresToDisable(WRITE_DATES_AS_TIMESTAMPS);

        return builder.build();
    }
}
```

But if I removed `@Configuration` annotation, this class is still active, and the Jackson ObjectMapper format rule is applied.

I have created a `beans.xml` and set attribute  `bean-discovery-mode="annotated"` in the root element.

**Comment by geoand** [comment]
Thanks for reporting this.

`beans.xml` is not used at all

**Comment by geoand** [comment]
So the problem is that even if `@Configuration` is removed, the Jackson bean is still registered?

**Comment by hantsy** [comment]
@geoand  I found the Jackson ObjectMapper in `AppConfig` still affected the json when I remove `@Configuration` .

**Comment by geoand** [comment]
Thanks for the confirmation @hantsy

**Comment by geoand** [comment]
#5431 should take care of the issue
