### ISSUE TITLE
java.util.jar.JarInputStream.getManifest() returns null for quarkus-runner.jar

### ISSUE THREAD

**Issue by dabloem** [quarkusio/quarkus#5399]
**Describe the bug**
JarInputStream.getManifest() returns **null** for quarkus-runner.jar

**Expected behavior**
Return non-null Manifest.class

**Actual behavior**
Returns null

**To Reproduce**
1. create quarkus-runner.jar (which includes META-INF/MANIFEST.MF)
2. execute the following code
```
InputStream file = Main.class.getResourceAsStream("/quarkus-runner.jar");
Manifest manifest = new JarInputStream(file).getManifest();
Objects.requireNonNull(manifest);
```
3. Verify NullPointerException

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux
 - Output of `java -version`: OpenJDK-8, IBM-8, Corretto-8
 - Quarkus version or git rev: 1.0.0.CR1

**Additional context**
Issue encountered when using azure-webapp-maven-plugin:1.8.0, which verifies if the deployed jar is an executable jar based on JarInputStream.class

**Comment by geoand** [comment]
This seems related to: https://bugs.openjdk.java.net/browse/JDK-8031748

So basically for `JarInputStream` the manifest needs to be the first entry in the jar

**Comment by geoand** [comment]
#5409 should take care of this

**Comment by jaikiran** [comment]
For future reference - Quarkus uses ZipFileSystem for handling the jars. There's a JDK enhancement to help fix this problem within the ZipFS implementation https://bugs.openjdk.java.net/browse/JDK-8211917. For now the workaround @geoand added has helped us get past this.
