### ISSUE TITLE
ArC - verify occurences of  BytecodeCreator.loadClass()

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#5400]
This is a follow-up of https://github.com/quarkusio/quarkus/pull/5385. We should verify each occurence of  `BytecodeCreator.loadClass()` in ArC and decide whether it should be replaced with TCCL + `Class.forName()` in order to support more complex class hierarchies with package-private classes.

**Comment by mkouba** [comment]
For the record - this may also break private member access in the dev/test mode.

**Comment by gsmet** [comment]
@mkouba is this still on track for 1.1.0? Meaning basically tonight :)

**Comment by mkouba** [comment]
@gsmet Nope. But it's still on track for future versions ;-).

**Comment by stuartwdouglas** [comment]
@mkouba can this be closed?

**Comment by mkouba** [comment]
> can this be closed?

I'm not sure TBH. We use TCCL in some places (probably the most critical ones) but we also use  `BytecodeCreator.loadClass()` in many other places (`ClientProxtGenerator`, `AnnotationLiteralGenerator`, etc.).

**Comment by mkouba** [comment]
I think that we can close this.
