### ISSUE TITLE
when().get("/hello/greeting/{name}") pass null to GreetingResource if run from  IntelliJ Idea

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#5416]
**Describe the bug**

Maybe IDE bug.. not sure.

From @QuarusTest test:

        String uuid = UUID.randomUUID().toString();
        given()
                .pathParam("name", uuid)
                .when().get("/hello/greeting/{name}")
                .then()
                .statusCode(200)
                .body(is("hello " + uuid));

**Expected behavior**
pass name should not be null but generated uuid

**Actual behavior**
pass name as null in GreetingResource

**To Reproduce**
1. mvn io.quarkus:quarkus-maven-plugin:1.0.0.CR1:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
2.mvn quarkus:add-extension -Dextensions="resteasy-jackson"
3. Run test from IDE: IntelliJ Idea

The problem is gone WHEN i did from the console:

mvn test

as of mvn did something to the build so that IDE can run it.

**Comment by jmartisk** [comment]
I can't reproduce this with IDEA 2019.2.3 Ultimate. 
![image](https://user-images.githubusercontent.com/937315/68738167-e1132780-05e5-11ea-86cc-8466b512f024.png)
![image](https://user-images.githubusercontent.com/937315/68738196-f12b0700-05e5-11ea-9411-75fce7e249ad.png)

The test passes when I run it from Maven as well as in the IDE using ctrl+shift+F10 when my typing cursor is inside the test. Did you make any special changes to the run configuration?

**Comment by geoand** [comment]
I can't reproduce this either. I am tried with IntelliJ `2019.3` (Beta) and everything worked as expected.

**Comment by steven-intertec** [comment]
I am facing the same error reported before I am using 

@QuarkusTest

@Test
    public void testHelloEndpoint() {
        String name = "steven";

        given()
                .pathParam("name", name)
                .when().get("/rest/greeting/{name}")
                .then()
                .statusCode(200)
                .body(is("hello steven"));
    }

name parameter is always null.
