### ISSUE TITLE
"Failed to run" with no exception reported

### ISSUE THREAD

**Issue by 4ntoine** [quarkusio/quarkus#5417]
**Describe the bug**
I'm trying to run quarkus in dev mode for https://github.com/4ntoine/NotesServerApp/tree/issue-5-quarkus and `./gradlew :app-quarkus:quarkusDev` fails with no exception reported.

**Expected behavior**
Build error reported (most likely as use case impls are not configured (injection)) or app is runing in jvm mode.

**Actual behavior**
```
...
FAILURE: Build failed with an exception.
...
Execution failed for task ':app-quarkus:quarkusDev'.
...
23:30:01.383 [ERROR] ...> Failed to run
```

**To Reproduce**
1. git clone git@github.com:4ntoine/NotesServerApp.git
2. git checkout issue-5-quarkus
3. ./gradlew :app-quarkus:quarkusDev --debug
4. Make sure you can see build error message

**Configuration**
```properties
# It's empty actually

```

**Screenshots**
<img width="1193" alt="Снимок экрана 2019-11-12 в 23 47 01" src="https://user-images.githubusercontent.com/846671/68700462-c5d4f780-05a6-11ea-93b9-1ffc5aa5f959.png">

**Environment (please complete the following information):**
 - Output of `uname -a`:
> Darwin MBP-Anton.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64 
 - Output of `java -version`: 
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `1.0.0.CR1`

**Additional context**
I believe i should configure use case impls and db connection at least as it's done in https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus/app-spring/src/main/kotlin/name/antonsmirnov/notes/Application.kt#L16

Let me know if you need any assistance on it.

**Comment by 4ntoine** [comment]
`./gradlew .. --debug` file:
[build.txt.zip](https://github.com/quarkusio/quarkus/files/3837671/build.txt.zip)

**Comment by 4ntoine** [comment]
i haven't found any clue in `./gradlew --info` file

**Comment by 4ntoine** [comment]
All of this ^ related to revision https://github.com/4ntoine/NotesServerApp/commit/38713d86916191f2c6c7b26a645239ed3f5dabf1

I was able to fix it by comparing with demo app and migrating Gradle's Groovy DSL to Kotlin DSL, so https://github.com/4ntoine/NotesServerApp/commit/0614a963f7622728ba4e9fe61e287f3ce48d3aaa works.

However it picks only compiled classes (controllers) from current module and doesn't do it from dependencies. Eg. Hello2Controller from `infra-rest-jax-rs` is not picked though there is a dependency on it: https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus/app-quarkus/build.gradle.kts#L15

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
