### ISSUE TITLE
NotFoundExceptionMapperTestCase fails on some environments

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#5424]
**Describe the bug**
The two tests in `io.quarkus.resteasy.test.NotFoundExceptionMapperTestCase` added by @machi1990 which replace resources and expect to see the changed resources fail in some environments and not in others.

@kenfinnigan added some sleeps to these tests which seemed to fix the problems sometimes, yet the problem is still not consistently fixed.

The problem may be due to inadequate resolution of file and/or directory time stamps.  This was a known problem in Java 8 (where the test fails for me) that was fixed in Java 11 (where the test does not fail for me).

The commit which introduced the problematic test was d81e508b6fb543724bd526c01304c28ebedc3d8f.  The commit which added the sleeps was 24876d0b7a9be4445f4ee4188f97aba4dc9cd1cb.

**To Reproduce**
1. Run this test class on Java 8, hopefully the problem reappears.  Removing the sleeps might be necessary.

**Comment by machi1990** [comment]
Thanks @dmlloyd @kenfinnigan  for the analysis and good detective work. I was away most of yesterday so I was not able to properly follow the discussion. I'll have a look at this.

**Comment by geoand** [comment]
Unfortunately this still comes up from time to to time in CI ([this](https://github.com/quarkusio/quarkus/pull/7676) is the last I saw it) - only on Windows and only for Java 8.
