### ISSUE TITLE
Please implement graceful shutdown

### ISSUE THREAD

**Issue by blsouthr** [quarkusio/quarkus#5432]
Currently, all clients connected to quarkus application will be disconnected and not receive any response when the application is killed for restart or deploy of a new version. Please, consider adding support for graceful shutdown allowing all request to complete while not accepting the new once

**Comment by Sanne** [comment]
Agreed, thanks for opening this issue.

Look @dmlloyd , that didn't take too long for your prediction to materialize :+1:

**Comment by blsouthr** [comment]
Hi! Any chance for it to be implemented soon?

**Comment by vusalalishov** [comment]
+1

**Comment by wernert75** [comment]
This feature would be very helpful for me.

**Comment by blsouthr** [comment]
@wernert75 it is already implemented. e.g. 30 seconds
`quarkus.shutdown.timeout=30`

**Comment by wernert75** [comment]
@blsouthr Thank you for your information. But this seems not working for me. I'd like to graceful shutdown an backroundworker which is consuming Messages from Kafka. An here quarkus.shutdown.timeout=30 seems not to be working.

**Comment by geoand** [comment]
@cescoffier don't we already have this for Reactive Messaging? If so, I think we should close the issue

**Comment by cescoffier** [comment]
This has been fixed in Reactive Messaging.
