### ISSUE TITLE
Be more explicit in case of provided id and usage of PanacheMongoEntity

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#5433]
**Description**
`PanacheMongoEntity` should be used when a user don't want to handle itself the MongoDB `_id` field. If the user wants to handle the field itself, he should use the `PanacheMongoEntityBase` instead.

When a user misuse the `PanacgeMongoEntity` and specify it's own `_id` with a `@BsonId` annotation, this generates a cryptic error : `readObjectId can only be called when CurrentBSONType is OBJECT_ID, not when CurrentBSONType is INT64.`

See the following zulip thread: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/mongo.20panache.20-.20throw.20missing.20implementation

**Implementation ideas**
We should detect such mis-usage of `PanacheMongoEntity` and provides a meaninful error to the user.

**Comment by loicmathieu** [comment]
@FroMage reading this Zulip thread: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/panache.20sequence

I think that we need to implements for both Panache flavors a chech that if PanacheEntity is used and an ID is defined (via JPA `@Id` or Mongo `@BsonId` annotation) an exception is thrown at build time.
This avoid unexpected behaviour ...
WDYT ?

**Comment by FroMage** [comment]
I thought Hibernate ORM would throw in this case. If it doesn't, I agree we should check at build-time. I just don't want two extensions (ORM and ORM with Panache) throw for the same error.
