### ISSUE TITLE
Serialize Java 8 Stream in Jaxrs response

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#5434]
Quarkus Hibernate Panache supports  Java 8 `Stream` as a return type. 

I am trying to write Stream into response via a Jaxrs `MessageBodyWriter`, but it seems it depends on the transaction context. 

My [StreamBodyWriter](https://github.com/hantsy/quarkus-sandbox/blob/master/post-service/src/main/java/com/example/StreamBodyWriter.java)(which does not work), hope there is an official solution for it, allow `Stream` as Jaxrs Resource response body. 

BTW, I think all reactive `Publisher` and its variants should get support in Jaxrs response serialization. (which are supported in Jaxrs client.) 
* Java 9 Flow API
* RxJava 2, Single, Obseverable, Maybe, Flowable, etc. 
* Reactor Mono, Flux.

**Comment by geoand** [comment]
cc @FroMage

**Comment by FroMage** [comment]
Yeah, your transaction will be closed by the time you're serialising. This is probably a question to ask @Sanne 
For reactive types I think this will work because the request won't be over until we've collected all the elements.
As for the reactive types supported, RESTEasy supports RxJava2 and Reactor types. I don't think it supports Java 9 Flow types but I also don't think anyone provides them yet.

**Comment by Sanne** [comment]
Hi,
it's really not a good idea to serialize detached entities.

In fact, I'd say it even stronger: it's really not a good idea to work with detached entities - in any context. Make sure a transaction is started _first_ then load the entities you want to work with, do the work, wrap up the transaction and forget about the entities.

That said, I do understand that it's "popular" to want to send entities directly as JAXRS responses - we might work on a good solution to support that - but even so:
 

1. the feature to support it is not implemented yet
2. Even when it will, it will not be able to perform very well.

I would suggest to copy the data to a DTO first; that will work today, and will work better than any feature we might be able to support in the future.

Incidentally it also gives you a much better design, as you can evolve changes in your rest endpoints wihtout having to make changes all the way in your application, up to and including the database - that's usually a very bad idea.

**Comment by hantsy** [comment]
If I copy the data from Java 8 `Stream`,  reactive `Publisher` to a DTO wrapper in the Service/Repository codes,  etc. the codes will look good ugly and need much work for this transforming.  Can we provide Spring WebFlux like programming experience in Quarkus?

**Comment by Sanne** [comment]
Yes we can certainly explore such things. Would be really cool.

Just bear in mind that this wasn't done yet, so please be patient and write "ugly code" - that's a personal opinion BTW, as personally as I mentioned above it's the better design. I'd suggest to look at mapper libraries which nicely solve this problem, like MapStruct : makes it realy elegant, and yet allows you to separate the API you expose via JAXRS from the database schema.

https://mapstruct.org/

**Comment by hantsy** [comment]
@FroMage I have tried Rxjava `Observable` and `Maybe`, it seems it is problematic in 1.1.0.Final, check my [new sample](https://github.com/hantsy/quarkus-sandbox/tree/master/rx-post-service) .

**Comment by geoand** [comment]
I'll close this as won't fix since we now have much better solutions with RESTEasy Reactive, Hibernate Reactive and Munity
