### ISSUE TITLE
Template support for server side rendering

### ISSUE THREAD

**Issue by jorsol** [quarkusio/quarkus#5435]
**Description**
One thing missing in Quarkus is some template support for server side rendering, some applications can take advantage of template support, to render UI from server (yes, old school) or email templates.

**Implementation ideas**
Vert.x includes some support for the following template engines out of the box:

- Handlebars
- Jade
- MVEL
- Thymeleaf
- Apache FreeMarker
- Pebble
- Rocker

**Comment by geoand** [comment]
#3106 is a relevant issue

**Comment by jorsol** [comment]
Missed that one, closing this to avoid duplicates (and move this info to that issue).
Thanks!

**Comment by geoand** [comment]
You are welcome!
