### ISSUE TITLE
Limited scaling of REST application

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#5439]
**Describe the bug**
According to our testing, hitting simple REST endpoint in Quarkus, the application not scale to more that 10-12 cores. 

**Expected behavior**
Application should scale almost linearly with number of cores.

**Actual behavior**
CPU is not fully utilized but the throughput is capped. Strangely, starting more instances of Quarkus on the same application (on different ports) does not double the throughput - there is contention on hardware resources, probably.

**To Reproduce**
1. Start quarkus-quickstarts/getting-started on machine with at least 16 cores
2. Drive a high load on the REST endpoint (approx. 150k-200k reqs/s)
3. Observe CPU utilization.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: RHEL 7/8
 - Output of `java -version`: OpenJDK 8 
 - Quarkus version or git rev: 1.0.0

**Additional context**
We've found out that the contention is related to the implementation of queue handing work from eventloop-threads to worker-threads. Changing LinkedBlockingQueue to LinkedTransferQueue as in https://github.com/eclipse-vertx/vert.x/pull/3193 solves the problem.

Quarkus will need to upgrade dependency to `vertx-core` to `3.8.4` once that gets released.

More discussion and results can be found in https://github.com/eclipse-vertx/vert.x/pull/3182

**Comment by rvansa** [comment]
@johnaohara FYI.

**Comment by stuartwdouglas** [comment]
We are now on Vert.x 3.9 so this should be resolved.
