### ISSUE TITLE
Link to Infinispan Query DSL is broken on the documentation

### ISSUE THREAD

**Issue by tiagodolphine** [quarkusio/quarkus#5440]
**Describe the bug**
Link to Infinispan Query DSL is broken on the documentation.

**Expected behavior**
Click on the link and open the proper documentation on the Infinispan guide.

**Actual behavior**
It opens an error page on the Infinispan website.

**To Reproduce**
1. Click on the link

**Screenshots**
![image](https://user-images.githubusercontent.com/7445313/68771190-4840d400-0606-11ea-93f9-099ceea8ed78.png)

![image](https://user-images.githubusercontent.com/7445313/68771145-2fd0b980-0606-11ea-9dfe-c00b722354ce.png)

**Comment by gsmet** [comment]
@karesti @wburns could you fix that before the end of the week, please?

**Comment by tiagodolphine** [comment]
@gsmet @karesti @wburns I sent a PR https://github.com/quarkusio/quarkus/pull/5442 with the fix.

**Comment by gsmet** [comment]
Cool, thanks!

**Comment by Sanne** [comment]
Fix was merged.
