### ISSUE TITLE
Reactive MongoDB with Panache

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#5446]
**Describe the extension**
A reactive version of MongoDB with Panache based on the existing `ReactiveMongoClient` provided by the `quarkus-mongodb-client` extension.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
The configuration should be the same as the one from MongoDB with Panache.

**Additional context**
The API should be the same than the one from MongoDB with Panache but using the reactive client and returing Reactive Stream types from MP Reactive Stream.

**Comment by FroMage** [comment]
You will want to copy the API of https://github.com/quarkusio/quarkus/issues/2198, though probably I should extract the enhancers into panache-common, like we did for orm/mongo enhancers, because I assume they will be very similar.
