### ISSUE TITLE
Hide vertx graphql extension until it becomes native compliant

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#5448]
The extension is not yet native-compliant.

Until that, it needs to be marked as hidden and the guide not linked from the guide list).
Remove the native ITs as they are not passing.

**Comment by maxandersen** [comment]
hmm - why ? didn't we say if an extension eventually will be native we keep them active and listed ?

**Comment by gsmet** [comment]
My understanding of this one is that there's a good chance we don't want to expose it for now as we might add graphql support with a totally different implementation.

**Comment by maxandersen** [comment]
ok - that’s a valid reason.

**Comment by Sanne** [comment]
@cescoffier I regularly build the whole thing with `-Dnative` and this extension keeps nagging me. It's the last one so not too bad :)  But could we disable its native tests as well until this is "made compliant" ?

Could we consider that part of the tasks for this issue?

**Comment by cescoffier** [comment]
@Sanne +1

**Comment by emmanuelbernard** [comment]
@gsmet is that one closed?

**Comment by stuartwdouglas** [comment]
Closing, this was fixed a while ago.
