### ISSUE TITLE
Remove the ability to configure an existing pom.xml

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#546]
Right now, the `shamrock:create` mojo is able to extend an exiting `pom.xml` and add the required configuration for shamrock. However, it can be tricky as mentioned in #527. I'm in favor to remove this feature except if there are strong objections.

**Comment by stuartwdouglas** [comment]
@cescoffier is this still relevant?

**Comment by cescoffier** [comment]
Nope. Closing.
