### ISSUE TITLE
Generated Resteasy endpoint path in Windows is exposed in a weird path

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#5461]
**Describe the bug**
I am using Windows 10. I created a sample project using: 

```bash
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=org.acme -DprojectArtifactId=project -DclassName="org.acme.quickstart.GreetingResource" -Dpath="/hello" -Dextensions="resteasy"
```

Now doing a `mvn compile quarkus:dev`, I open the browser to http://localhost:8080/hello and the following error page is displayed: 

![Screenshot from 2019-11-13 23-02-32](https://user-images.githubusercontent.com/54133/68820331-b36fc200-0669-11ea-894f-ffa2f5b95b2b.png)

Yes, the endpoint is available at `http://localhost:8080/C:/Program%20Files/Git/hello`(!!!)

**Expected behavior**
The endpoint to be available at http://localhost:8080/hello

**Actual behavior**

The endpoint is available at `http://localhost:8080/C:/Program%20Files/Git/hello`

**To Reproduce**
1. In a Windows 10 VM, run the command above to create a sample project (or generate one from code.quarkus.io)
2.  Run `mvn compile quarkus:dev`
3. Open the browser at http://localhost:8080/hello

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`:  
 - GraalVM version (if different from Java): 19.2.1 (not used)
 - Quarkus version or git rev: 6ac8aaea00d2b2637d11e75e25b78563ba871153

**Additional context**

I am using Git Bash to build, but the problem can also be reproduced  with the Windows 10 command prompt. Looking at the generated code, I see this:

```java

package org.acme.quickstart;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/C:/Program Files/Git/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}
```

**Comment by jaikiran** [comment]
Hello @gastaldi, this has actually been reported before https://github.com/quarkusio/quarkus/issues/3786

**Comment by gastaldi** [comment]
@jaikiran Thank you! I'll close this issue as duplicate of #3786

**Comment by gastaldi** [comment]
Here is the solution for this problem in Git bash: https://github.com/moby/moby/issues/24029#issuecomment-250412919

**Comment by gastaldi** [comment]
@jaikiran actually this bug is different from #3786 but I found the solution in the link above (use double slashes  (`-Dpath="//hello"`) or set `MSYS_NO_PATHCONV=1`
