### ISSUE TITLE
Provide a build item that contains the module root path.

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#5474]
**Description**
Every now then when working with extensions, I need to use the path to the module root directory. This information is currently not available and one can only use workarounds.

It would be great if there was a build item provided that contained this information.

**Implementation ideas**
The maven BuildMojo does have access to this information so does the gradle BuildTask.
From there we could pass the information forward to the QuarkusAugmentor that could produce the desired build item.

**Comment by stuartwdouglas** [comment]
The issue with this is that it assumes that augmentation always happens from within the context of a Java project. One of our initial goals with Quarkus was the ability too easily do upgrades in a cloud based environment without needing to rebuild your project. This use case would involve augmenting a pre-built jar that does not necessarily still have the Java project present.

In addition to this if we provide it to the build then extensions are going to make assumptions about the structure of the project that is not always correct.

I think we need to look at the use cases here and see if there are other ways to solve this problem.

cc @emmanuelbernard @n1hility

**Comment by iocanel** [comment]
So, it seems that we won't proceed with this change.
I am closing the issue for now.
