### ISSUE TITLE
Support arbitrary auth expressions in an annotation

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#5479]
Spring Security's `@PreAuthorize` provides users the ability to write arbitrary expressions for auth checks using an expression language.

Some examples are:

```
@PreAuthorize("hasRole('ROLE_VIEWER') or hasRole('ROLE_EDITOR')")
String something()

@PreAuthorize("hasRole('ADMIN') AND hasRole('DBA')")
String somethingElse()

@PreAuthorize("#username == authentication.principal.username")
String somethingNew(String username)

@PreAuthorize("isAdmin() or isOwner(#id)") //isOwner is a user defined function
void deleteGame(@PathVariable int id, @ModelAttribute currentGame) 

@PreAuthorize("isAuthenticated()")  
void doSomething()
```

Do we feel that Quarkus should have something similar?

**Comment by geoand** [comment]
cc @FroMage @emmanuelbernard

**Comment by FroMage** [comment]
This looks a lot like Seam's UEL support for auth, which I used back in the day and which allowed us to write security rules in drools.

Except I can't make sense of the semantics at play here. Can you explain what the annotation does (besides have some EL) and what its relation to the method is?

**Comment by FroMage** [comment]
The first two examples only yield this use-case:

- be able to specify boolean logic combinations of role checks

I don't know what the third does.

In Seam, we frequently used those rules to check if the user had roles and was an actor for some object (as in: must be admin, or be the author of this comment entity).

**Comment by geoand** [comment]
The examples I added were a little confusing due to how I wrote them. I updated them to hopefully make them more clear.

The third example basically checks whether the method parameter is the same as the logged in user. My guess it's useful if you want to limit the data a logged in user can see.

**Comment by geoand** [comment]
I also added a couple more examples

**Comment by FroMage** [comment]
OK thanks. Let's assume those methods are CDI methods then, and the annotation checks for permissions rather than extracts some data related to permissions from the method's return value.

## Role combination

I'm going to assume that many of these role checks are reused over several methods, because security rules are rarely one-offs.

We could write them like this:

```java
public class Security {
 @DefinesPermission
 public static boolean canViewOrEdit(User user){
  return user != null && (user.hasRole("ROLE_VIEWER") || user.hasRole("ROLE_EDITOR");
 }
 @DefinesPermission
 public static boolean isAdmirAndDba(User user){
   return user != null && user.hasRole("ADMIN") && user.hasRole("DBA");
 }
}

@Path("games")
public class Games {
 @Path("{id}")
 @GET
 @RequiresPermission("view-or-edit")
 public Game get(@PathParam String id){
  ...
 }
 @Path("drop-all")
 @POST
 @RequiresPermission("admin-and-dba")
 public void dropAll(@PathParam String id){
  ...
 }
}
```

It is longer, but reusable, and you get IDE support, completion.

## Item-based permissions

For:

```java
@PreAuthorize("isAdmin() or isOwner(#id)") //isOwner is a user defined function
void deleteGame(@PathVariable int id, @ModelAttribute currentGame) 
```

I usually write:

```
@Entity
public class Game extends PanacheEntity {
  // ...
  public boolean canEdit(User user){
    return user != null && user.isAdmin || game.owner.equals(user) || game.admins.contains(user);
  }
}

@Path("games")
public class Games {
 @Path("{id}")
 @DELETE
 public void delete(@PathParam String id){
  Game game = getGameForEdit(id);
  ...
 }

  private Game getGameForEdit(String id) {
    Game game = Game.findById(id);
    User user = getUser();
    if(!game.canEdit(user)){
      // throw
    }
    return game;
  }
}
```

This is because in those cases we need to load the `Game` entity, and we don't want to load it twice, and usually we don't know how to load it from attributes. We have several discussions about automating this. From your example, it's really not clear if the `Game` entity is loaded, and how.

@stuartwdouglas suggested something like this:

```java
@Path("games")
public class Games {
 @Path("{id}")
 @DELETE
 public void delete(@EntityPathParam Game game){
  User user = getUser();
  if(!game.canEdit(user))
    throw;
  ...
 }
}
```

But if we have this, we can basically plug permissions dynamically like this:

```java
@Entity
public class Game extends PanacheEntity {
  // ...
  @DefinesPermission
  public boolean canEdit(User user){
    return user != null && user.isAdmin || game.owner.equals(user) || game.admins.contains(user);
  }
}

@Path("games")
public class Games {
 @Path("{id}")
 @DELETE
 public void delete(@RequiresPermission("edit") @EntityPathParam Game game){
  ...
 }
}
```

It _is_ longer than the EL version, BUT you have real Java code for your permissions, IDE completion, etc, and it's reusable in many places.

## Authenticated

For:

```java
@PreAuthorize("isAuthenticated()")  
void doSomething()
```

We already have 

```java
@Authenticated
void doSomething()
```

**Comment by FroMage** [comment]
Keep in mind those are ideas. Perhaps they're better, perhaps they're worse. They're only here to help discussing potential solutions to use-cases.

**Comment by geoand** [comment]
Excellent points!

**Comment by sberyozkin** [comment]
IMHO it might make sense to keep the authentication constraint check out of it, given we already have `@Authenticated` as per Stephane's comment, and it seems a little bit too flexible :-), having something like `isAuthenticated() and isAdmin()`, I'm assuming if someone says `isAdmin()` then the security identity has to be available ?

**Comment by sberyozkin** [comment]
Hey Georgios, @geoand, I was wondering, if one could write not only `isAdmin()` (i.e various variations about the roles) but also say `jwtClaim("email")== someuser@gmail.com`, etc, i.e expand it to claims based authorization or to whatever else is available in Quarkus `SecurityIdentity` then ot could be somehow different to just a Spring like syntax. Well, we'd still want to control the claim based AC with some new annotations in the OIDC land, but just typing it in in this PreAuthorize annotation can appeal to some users too; I guess `quarkus-smallrye-jwt` or `quarkus-oidc` would need to advertise somehow  they can resolve `jwtClaim("...")` terms... thanks

**Comment by geoand** [comment]
Hey  @sberyozkin 

Are you asking if Spring Security currently offers a similar capability?

**Comment by sberyozkin** [comment]
Hi @geoand Not really :-), the hope is that Spring Security developers will ask, can we have what is done in Quarkus about PreAuthorize and JWT claims (and more as needed from SecurityIdentity) :-)

**Comment by geoand** [comment]
Gotcha, thanks!

I definitely don't have the answers here :), I'm just stating what Spring Security supports and wondering what sort of experience we can bring to Quarkus

**Comment by sberyozkin** [comment]
Sure thanks; It was only a suggestion, alongside Stephane's ones, on how we might try to differentiate around it. I'll ping you later to discuss it in more detail if the work on this issue goes ahead. thanks

**Comment by geoand** [comment]
To be clear, I am not in favor of the Spring Security way of doing things, it leaves too much uncertainty. I would much prefer solution closer to what @FroMage proposes

**Comment by sberyozkin** [comment]
Hi Georgios, this one has already been fixed, right ?

**Comment by geoand** [comment]
Hey @sberyozkin 

I don't think it has, at least not to my knowledge
