### ISSUE TITLE
Allow triggering container builds and deployments during the build.

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#5493]
**Description**
Currently, every quarkus project comes with a set of Dockerfiles for jvm and native images. Also, its trivial to have kubernetes/openshift manifests generated using the `kubernetes` extension.

To further bump the developer joy, it would be great if we could trigger a docker build and deployment from the command line, with something like:

    mvn clean package -Dquarkus.container.deploy=true

This could hands down provide the faster way to get a java application running on Kubernetes / Openshift.

**Comment by lburgazzoli** [comment]
Shouldn't the deploy task a "tooling" task ? 
Something like `mvn quarkus:deploy`

**Comment by geoand** [comment]
@lburgazzoli that has been suggested too, but for the time being we are going to stick with config flags to control the execution
