### ISSUE TITLE
%test.quarkus.http.root-path does not have effect when run @QuarkusTest test

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#5494]
**Describe the bug**
%test.quarkus.datasource.url does not have effect when run @QuarkusTest test.

https://stackoverflow.com/questions/58841384/quarkus-reading-application-properties-from-the-quarkustest

**Expected behavior**

in test/resources/application.properties

%test.http.root-path=/my-service/api/v2

```
@QuarkusTest
@Tag("integration")
public class MyResourceTest {
    @Test
    public void testMyEndpoint() {

        given()
                .when().get("/my-service/api/v2/init")
                .then()
                .statusCode(200)
                .body(is("{}"));
    }
```

**Actual behavior**
```
@QuarkusTest
@Tag("integration")
public class MyResourceTest {
    @Test
    public void testMyEndpoint() {

        given()
                .when().get("/init")
                .then()
                .statusCode(200)
                .body(is("{}"));
    }
```

**To Reproduce**
1. 
in test/resources/application.properties

%test.quarkus.datasource.url=/my-service/api/v2
2. 
```
@QuarkusTest
@Tag("integration")
public class MyResourceTest {
    @Test
    public void testMyEndpoint() {

        given()
                .when().get("/my-service/api/v2/init")
                .then()
                .statusCode(200)
                .body(is("{}"));
    }
```

--
latest version of now.

**Comment by stuartwdouglas** [comment]
Restassued reads the value of quarkus.http.root-path, so you don't have to modify it in your tests.
