### ISSUE TITLE
Cannot build native image on WSL

### ISSUE THREAD

**Issue by majonga88** [quarkusio/quarkus#5497]
Hi guys, 

I have an other issue (not directly related with this one : #5363). 

I have two kind of machine for building native image : one in WSL (v1) and another one on Mac OSX.

I would like to build a native image following this guide : https://quarkus.io/guides/building-native-image.html

When i do the following cli : 

cli | MacOSX | WSL1
--- | --- | ---
`./mvnw verify -Pnative` | ✔️ | ✔️ 
`./mvnw package -Pnative -Dquarkus.native.container-build=true` | ✔️ | ❌ 

The following error on WSL1 is : 

> Error: Invalid Path entry getting-started-1.0-SNAPSHOT-runner.jar
> Caused by: java.nio.file.NoSuchFileException: /project/getting-started-1.0-SNAPSHOT-runner.jar

The lgo command line executed to getting this error :

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /home/xerxes/projects/quarkus-ms/target/openapi-swaggerui-quickstart-1.0-SNAPSHOT-native-image-source-jar:/project:z --user 1000:1000 --rm quay.io/quarkus/ubi-quarkus-native-image:19.2.1 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar openapi-swaggerui-quickstart-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace openapi-swaggerui-quickstart-1.0-SNAPSHOT-runner
```

See the full logs here : [error-log.txt](https://github.com/quarkusio/quarkus/files/3852344/error-log.txt)

When `./mvnw package -Pnative -Dquarkus.native.container-build=true`  execute the `docker run` command, i saw this strange thing in  : 

> /home/xerxes/projects/quarkus-ms/target/openapi-swaggerui-quickstart-1.0-SNAPSHOT-native-image-source-jar:**/project:z**

GRAALVM_HOME is already set in on my WSL : `/home/xerxes/graalvm-ce-19.2.1`

And the project structure is like this : 

![image](https://user-images.githubusercontent.com/46779480/68898434-b6cd8100-072f-11ea-954f-4fd72b209f36.png)

Ps > source code there :  https://github.com/majonga88/quarkus-ms

Thank you so much for your help.

**Comment by jaikiran** [comment]
Hello @majonga88, can you please paste the complete output of that mvn command execution? I'm mainly interested in the command execution message that gets logged by our native image build step.

**Comment by majonga88** [comment]
Hi,

Here they are : [error-log.txt](https://github.com/quarkusio/quarkus/files/3852347/error-log.txt)

Thank you.

**Comment by geniusit** [comment]
Hello,

I got the same issue. 

Here is my [error-log-quarkus.txt](https://github.com/quarkusio/quarkus/files/3862434/error-log-quarkus.txt)

Any help appreciated.

Thank you

**Comment by harpreetsingh29** [comment]
@geniusit, @majonga88 , @jaikiran ,  : 
Are you able to fix this error? I am also facing the same issue in windows 10.

If not, what alternative you suggest to use? Shall i use linux system?

**Comment by geniusit** [comment]
Definitively no. Windows doesnt work well with Docker, graalvm etc ... The best advice is to use a "real" linux system if you want to be productive. 
Windows is like hell for developpers but many companies don't let their developpers to chose the OS they want. It's really painful :(( and this makes my days so sad :(((

**Comment by harpreetsingh29** [comment]
@geniusit : 

:( , So i need to ask my IT team to provide the same as i have not worked on linux machine before. They are providing me centos7, i hope no issues with that.

**Comment by Karm** [comment]
@gsmet  This issue can be closed.
Windows Quarkus native app build works just fine, both using Docker Desktop and builder image (provided the volume is set [correctly](https://github.com/quarkusio/quarkus/issues/9816#issuecomment-640220866) to prevent NoSuchFileException) and using native WIndows toolchain to create Windows executable.

**Comment by geoand** [comment]
Let's this really old issue
