### ISSUE TITLE
[hibernate-validator] Provide ValidatorFactory as BuildItem

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#5511]
**Description**
Would be nice to have the `ValidatorFactory` computed by the `HibernateValidatorProcessor` available also as build item so we can configure resources that leverage need it on `STATIC_INIT`, 

i.e. the camel-bean-validator now looks up `ValidatorFactory` through CDI but we could bound the  factory to the component at `STATIC_INIT` if a build item were present

**Comment by gsmet** [comment]
@fmhwong this might be a nice issue to start with. Useful keyword: `RuntimeValue`.

**Comment by fmhwong** [comment]
@lburgazzoli  What do you think if I create a `@BuildStep` in `HibernateValidatorProcessor` that takes `BuildContainerBuildItem` as an input, read the `ValidatorFactory` instance from `ValidatorHolder` and create a `ValidatorHolderBuildItem`?

**Comment by fmhwong** [comment]
@lburgazzoli comments?

**Comment by lburgazzoli** [comment]
@fmhwong @gsmet 

I've missed this for quite a long time :) 

I've not followed hibernate-validator evolution since a while so I don't know if this has somehow been implemented

**Comment by gsmet** [comment]
Given how the VF is initialized, I don't think we can change that. The `ValidationFactory` is initialized when ArC is initialized and not before. We cannot push it to a build item.
