### ISSUE TITLE
LogManager GENERIC_FAILURE on Windows 10

### ISSUE THREAD

**Issue by mcrose** [quarkusio/quarkus#5522]
**Describe the bug**
when auto redeploy occurs, an exception with log file rises

> 10:48:55 INFO  [io.quarkus] Quarkus stopped in 0.020s
> 10:48:55 INFO  [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
> 10:48:55 INFO  [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 179ms
> LogManager error of type GENERIC_FAILURE: Failed to move file log\dataprocessor.log to log\dataprocessor.log.2019-11-15.1.
> java.nio.file.FileSystemException: log\dataprocessor.log -> log\dataprocessor.log.2019-11-15.1: The process cannot access the file because it is being used by another process.
> 
>         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
>         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
>         at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:395)
>         at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
>         at java.base/java.nio.file.Files.move(Files.java:1421)
>         at org.jboss.logmanager.handlers.SuffixRotator.move(SuffixRotator.java:239)
>         at org.jboss.logmanager.handlers.SuffixRotator.rotate(SuffixRotator.java:167)
>         at org.jboss.logmanager.handlers.SuffixRotator.rotate(SuffixRotator.java:226)
>         at org.jboss.logmanager.handlers.PeriodicSizeRotatingFileHandler.setFile(PeriodicSizeRotatingFileHandler.java:154)
>         at io.quarkus.runtime.logging.LoggingSetupRecorder.configureFileHandler(LoggingSetupRecorder.java:173)
>         at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(LoggingSetupRecorder.java:90)
>         at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit33.deploy_0(LoggingResourceProcessor$setupLoggingRuntimeInit33.zig:59)
>         at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit33.deploy(LoggingResourceProcessor$setupLoggingRuntimeInit33.zig:78)
>         at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:57)
>         at io.quarkus.runtime.Application.start(Application.java:94)
>         at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:143)
>         at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
>         at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:207)
>         at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:134)
>         at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:51)
>         at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:43)
>         at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> 10:48:55 INFO  [io.quarkus] Quarkus 1.0.0.CR1 started in 0.260s. Listening on: http://0.0.0.0:8092
> 10:48:55 INFO  [io.quarkus] Profile dev activated. Live Coding activated.
> 10:48:55 INFO  [io.quarkus] Installed features: [cdi, rest-client, resteasy, resteasy-jsonb]
> 10:48:55 INFO  [io.quarkus.dev] Hot replace total time: 0.295s

**To Reproduce**
1.  deploy the app
2. change some thing relevant

**Configuration**
```properties
quarkus.log.file.enable=true
quarkus.log.file.path=log/dataprocessor.log
quarkus.log.file.level=TRACE
quarkus.log.file.format=%d{HH:mm:ss} %-5p [%c{2.}]] (%t) %s%e%n
quarkus.log.file.rotation.max-file-size=1024
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
```

**Environment (please complete the following information):**
 - Output of `java -version`: 11, project based on 8
 - Quarkus version: 1.0.0.CR1
 - OS: Windows 10

**Comment by gsmet** [comment]
@mcrose can you try @machi1990 's PR: https://github.com/quarkusio/quarkus/pull/5535 and see if it fixes your issue?

**Comment by mcrose** [comment]
> 
> 
> @mcrose can you try @machi1990 's PR: #5535 and see if it fixes your issue?

done! is fixed
