### ISSUE TITLE
[Solved] REST Controller in transitive jar is not detected

### ISSUE THREAD

**Issue by 4ntoine** [quarkusio/quarkus#5526]
**Describe the bug**
I have a [controller](https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus-maven/infra-rest-jax-rs/src/main/kotlin/name/antonsmirnov/notes/controller/rest/Hello2Controller.kt) in [transitive jar](https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus-maven/app-quarkus/pom.xml#L44) and it's not detected

**Expected behavior**
Controllers in transitive jars are detected and exposed

**Actual behavior**
Controllers is not detected and exposed, but controllers in this jar are detected and exposed.

**To Reproduce**
1. git clone git@github.com:4ntoine/NotesServerApp.git
2. git checkout d24280679678d020d08702330c966980b6e1ae10
3. ./gradlew publishToMavenLocal
4. cd app-quarkus
5. ./mvnw compile quarkus:dev

**Configuration**
```properties
quarkus.datasource.url = jdbc:h2:mem:notes
quarkus.datasource.driver = org.h2.Driver

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create
```

**Screenshots**
<img width="1200" alt="Снимок экрана 2019-11-16 в 10 51 57" src="https://user-images.githubusercontent.com/846671/68988864-04490b80-0860-11ea-800b-331a1568e943.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 

**Additional context**
Similar to https://github.com/quarkusio/quarkus/issues/5521 issue.

**Comment by 4ntoine** [comment]
Can be solved with adding of empty `META-INF/beans.xml` into transitive jar:
https://github.com/4ntoine/NotesServerApp/commit/d24280679678d020d08702330c966980b6e1ae10

**Comment by 4ntoine** [comment]
It's mentioned in https://quarkus.io/guides/hibernate-orm#defining-entities-in-external-projects-or-jars but there it's written in context of ORM/JPA. I'd suggest to mention it in REST docs too

**Comment by geoand** [comment]
@4ntoine would you like to submit a PR to improve the docs?

**Comment by machi1990** [comment]
> It's mentioned in https://quarkus.io/guides/hibernate-orm#defining-entities-in-external-projects-or-jars but there it's written in context of ORM/JPA.
> 
> **I'd suggest to mention it in [REST docs ](https://quarkus.io/guides/rest-json)too and the same suggestion as [here](https://github.com/quarkusio/quarkus/issues/5521#issuecomment-554603021).**

We also have it here https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index maybe we can reference it somehow.

**Comment by 4ntoine** [comment]
@machi1990  It sounds a bit inconsistent that for same transitive deps one just need to add "META-INF/beans.xml" and for some one need to generate some index. BTW why not just generate index for all the transitive beans? Is it compiling performance the reason?
