### ISSUE TITLE
Support Classloader based resource filtering

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#554]
Arquillian let's you define subset of your applications for smaller tests. It is also very useful to define tests for different resources (by presence or content).
The main drawback is that Arquillian does this via zipping which is too slow.

Explore a way for Shamrock to receive a structure definition and use the classloader to filter the relevant classes and resources. The ability to NAT resource names is a must (`from("test1-persistence.xml").to("META-INF/persistence.xml")`).

Note that this is not top priority as we are really fast to start the full stack.

**Comment by stuartwdouglas** [comment]
@emmanuelbernard I think this can be closed, as we have QuarkusUnitTest that meets this requirement.

**Comment by geoand** [comment]
+1 for closing this as it is unlikely users (thus `@QuarkusTest`) will need this. For extension authors, we have plenty of options on the table already
