### ISSUE TITLE
Unable to register classes for reflection (Jandex)

### ISSUE THREAD

**Issue by mk2301** [quarkusio/quarkus#5546]
**Describe the bug**
My application uses gradle and kotlin.
I see the following warning in the log:
```
2019-11-17 20:52:42,824 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-23) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - javax.persistence.criteria.CriteriaBuilder
        - javax.persistence.criteria.Predicate
        - javax.persistence.criteria.Root
        - kotlin.jvm.functions.Function3
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
```
I was able to find the piece of code causing this warning:
```
@Path("/api")
class MyController {

    @GET
    fun entryPoint() = EntityFilterData(::addSomeFilter)

    private fun addSomeFilter(qf: Map<String, Any>, root: Root<MyEntity>, cb: CriteriaBuilder): Predicate? {
        return null
    }
}

class EntityFilterData<T : PanacheEntityBase>(

        // THE WARNING COMPLAINS ABOUT THIS CODE:
        @JsonIgnore
        val addCondition: ((@ParameterName(name = "queryFragment") Map<String, Any>,
                            @ParameterName(name = "root") Root<T>,
                            @ParameterName(name = "cb") CriteriaBuilder) -> Predicate?)? = null
)

@Entity
class MyEntity : PanacheEntity()
```

**Expected behavior**
As I am not familiar with the details of registering the class hierarchy, I am not sure if it is a bug in Quarkus or misconfiguration on my end. I opened this issue on demand of @gsmet (see https://stackoverflow.com/a/58903420/3952202)

I would expect no warning in the log.

**Actual behavior**
The log shows the warning:
```
Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - javax.persistence.criteria.CriteriaBuilder
        - javax.persistence.criteria.Predicate
        - javax.persistence.criteria.Root
        - kotlin.jvm.functions.Function3
```

**To Reproduce**
1. `git clone git@github.com:mk2301/reproduce-quarkus-jandex-warnings.git`
2. `./gradlew quarkusDev`

**Environment:**
 - Output of `uname -a` or `ver`:  
`Linux 5.3.8-200.fc30.x86_64 #1 SMP Tue Oct 29 14:46:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
```
 - GraalVM version (if different from Java): `CE 19.2.1`
 - Quarkus version or git rev: `1.0.0.CR1`

**Comment by gsmet** [comment]
Yeah, I don't think we take into account the `@JsonIgnore` annotations and we probably should, together with the `@JsonbTransient` one.

**Comment by geoand** [comment]
Makes sense

**Comment by glefloch** [comment]
I just tested it with the latest quarkus version and the warning does not appear anymore. I think #10345 fixed it.
