### ISSUE TITLE
Attempt to change a build-time only configuration at runtime should fail

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#5548]
**Describe the bug**
There's many people making the mistake of expecting a build-time-only configuration property to be picked up, either after the build, or during dev-mode.

Latest example:
 - https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Mysql.20driver.3A.20What.20to.20use.3F

I would suggest we introduce better checks against such mistakes, especially as both types of configuration properties are in the same file, not even using a separate section.

**Comment by dmlloyd** [comment]
Sure, this could be done as a warning I think.

**Comment by stuartwdouglas** [comment]
We have a warning for this, and can fail if you set `quarkus.configuration.build-time-mismatch-at-runtime = fail`
