### ISSUE TITLE
Repeated constraints are not supported

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#5549]
Right now, I don't think we properly support repeated constraints in the Hibernate Validator extension. I was recently made aware that Jandex does not return the repeated annotation occurrences when querying the index and that we should query the index with the container annotation too.

That means that for all the repeatable constraints (`@Pattern` is a good example of that and could be used for testing), we will also need to look for the associated containers.

So we should add the containers to the considered annotations here: https://github.com/quarkusio/quarkus/blob/master/extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java#L136-L141 .

The containers should probably be extracted from the constraint itself by querying the index and look for the container defined in the `@Repeatable` annotation.

As we don't really analyze the content of the constraints but are just looking for the occurrences, we shouldn't have to interpret the container as it is done here: https://github.com/quarkusio/quarkus/blob/master/extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java#L148 . Just mentioning it to be thorough.

A test should be added here (and we should start with that): https://github.com/quarkusio/quarkus/tree/master/extensions/hibernate-validator/deployment/src/test/java/io/quarkus/hibernate/validator/test .

**Comment by gsmet** [comment]
@irenakezic I think that would be a good starting point for you.

Feel free to ask any questions you have here or on Zulip, I'll be happy to guide you.

**Comment by irenakezic** [comment]
ok, thanks

**Comment by gastaldi** [comment]
This is the Jandex issue asking to support @Repeatable annotations:  https://github.com/wildfly/jandex/issues/67

**Comment by gsmet** [comment]
As explained above, if we can fix it directly in Quarkus, let's do it. That will give us more time to properly think how and if we should fix that in Jandex.
