### ISSUE TITLE
Simplify CDI security

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#5550]
**Description**
Try to simplify the CDI security logic

**Implementation ideas**
I think we could have:

1. a single annotation that would be bound to an interceptor, let's say `@QuarkusSecuredInternal` (ideas for a better name are welcome :) ) - it would eliminate the need to have multiple interceptor classes, binding registrar, etc

2. a build item to say that an annotation is a security annotation. It should take a `ClassInfo` of the annotation and a function to produce the security check ( `(AnnotationInstance, BytecodeCreator) -> ResultHandle`)

3. based on 2. (and other info, such as denying unannotated) following two would be creaed:

   a)  a build item to state that a class is secured, (`ClassInfo` of the class and `ClassInfo` of the annotation)

   b) a build item to state that a method is secured (`ClassInfo` of the class, some method descriptor and `ClassInfo` of the annotation)

The `@QuarkusSecuredInternal` would be added to classes based on the 3 a) and b).

A single build step would prepare a method -> check mapping based on the 3 a) and b) as well.

**Comment by michalszynkiewicz** [comment]
CC @geoand

**Comment by geoand** [comment]
@michalszynkiewicz Nice list, I'll look into it soon!

**Comment by michalszynkiewicz** [comment]
There is one thing that I see now may not be as clean as I'd like it to be.
We may need to differentiate between a build step that says "there is a security annotation on a class" and "we have added a security annotation on a class". In case someone e.g. uses deny unannotated and has the Spring's `@Secured` annotation on a class.

**Comment by geoand** [comment]
TBH I'm not sure if we want to have something like `deny unannotated` for Spring security stuff.
