### ISSUE TITLE
Resteasy @NoCache Annotation doesn't work

### ISSUE THREAD

**Issue by rboei** [quarkusio/quarkus#5551]
Hey,
we were using the `@NoCache` Annotation of RESTEasy to disable the caching for some rest interfaces. It is not working with Quarkus 1.0.0.CR1

It is ignored and no cache related headers are set.

**Comment by gastaldi** [comment]
@rboei I just wrote some tests and I see that `@NoCache` and `@Cache` works as expected. Do you have a reproducer project?

**Comment by rboei** [comment]
Sadly no, it happens in our own project. I will look into it and come back to you.

**Comment by geoand** [comment]
Closing as out of date
