### ISSUE TITLE
Docs: Create extension with quarkus-maven-plugin fails to mention required attritube artifactId

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#5555]
When I run this:

```
mvn io.quarkus:quarkus-maven-plugin:create-extension -N \
    -Dquarkus.artifactIdBase=my-ext \
    -Dquarkus.nameBase="My Extension"
```
As shown exactly like that in this guide: https://quarkus.io/guides/extension-authors-guide#create-new-extension-modules-using-maven

I get:

`[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create-extension (default-cli) on project quarkus-extensions-parent: Either artifactId or both artifactIdPrefix and artifactIdBase must be specified; found: artifactId=[null], artifactIdPrefix=[null], artifactIdBase[my-ext]`

I think the guide is stale and needs to be adjusted.

**Comment by geoand** [comment]
@ge0ffrey Thanks for spotting it! Would you like to provide a PR for the guide?

**Comment by kunal-kushwaha** [comment]
@ge0ffrey : I am unable to reproduce this error, has this issue already been fixed? Thanks.

**Comment by ggrebert** [comment]
For me the issue has been fixed and can be closed.

The new snippet in the guide referred by @ge0ffrey works for me:

```bash
mvn io.quarkus.platform:quarkus-maven-plugin:2.2.1.Final:create-extension -N \
    -DextensionId=my-ext \
    -Dname="My Extension"
```

**Comment by ge0ffrey** [comment]
+1 to close

Georgios, I missed your comment, so that never happened, but it's fix now :)
