### ISSUE TITLE
Support access log logging when using RESTEasy with Vert.x

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#5556]
I tried to use access log for getting started project (when looking at #4059) but didn't see any access log entries.

I think it's because quarkus-http-core is not used in getting started project :/
So all "quarkus-resteasy" apps won't be able to produce access log 

```
[INFO] org.acme:getting-started:jar:1.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-resteasy:jar:1.0.0.CR1:compile
[INFO] |  +- io.quarkus:quarkus-vertx-http:jar:1.0.0.CR1:compile
```

**Comment by gsmet** [comment]
We should also consider this issue: https://github.com/quarkusio/quarkus/issues/3140 .

**Comment by stuartwdouglas** [comment]
@cescoffier @vietj It looks like the vert.x Web access log handler is considerably more limited than the Undertow one. It would be pretty simple to wire up the vert.x one to config but I think users are likely going to want more features than it provides. I am thinking it might make sense to just port the Undertow version to our vert.x HTTP module, what do you guys think?

**Comment by cescoffier** [comment]
@pmlopes did the support for Vert.x Web. But yes, it should be straightforward.

**Comment by rsvoboda** [comment]
We need consistent way for this no matter what engine is used in the background, adding to stabilization effort board.

**Comment by rsvoboda** [comment]
@cescoffier / @pmlopes is there any progress with this issue ?
