### ISSUE TITLE
Allow to choose precisely the health checks to be activated.

### ISSUE THREAD

**Issue by lhauspie** [quarkusio/quarkus#5572]
**Description**
Issue created after a review on the PR https://github.com/quarkusio/quarkus/pull/5125/files/28579d94052eb47ae54ebe44ac5955f205fcf55c#r345089164.
> I think this should be a String allowing the following values:
> 
> `true`
> false
> the name of the check to enable as there is two different check
> => If you don't want to implent it now, please open a followup issue for this

For the moment, `xx.health.enabled` properties can only take 2 values : `true` or `false`.
So it will be complexe if we would like to choose https://github.com/quarkusio/quarkus/pull/5125/files/28579d94052eb47ae54ebe44ac5955f205fcf55c#r345089164.
For example, for datasources health, we maybe want to add checks on only one specific datasource.

**Implementation ideas**
Replace
```
    @ConfigItem(name = "health.enabled", defaultValue = "true")
    public boolean healthEnabled;
```
by
```
    @ConfigItem(name = "health.enabled", defaultValue = "true")
    public String healthEnabled;
```
in the config root `@ConfigRoot` class file.

Then change the corresponding `@BuildStep`s in `Processor` class file in `deployment` module to activate the right check(s).

**Comment by machi1990** [comment]
```
@ConfigItem
HealthProbe probe;

public enum HealthProbe {
  NONE,
  ALL,
  LIVENESS,
  READINESS
}
```

Is the above pseudo code an option?

**Comment by lhauspie** [comment]
> ```
> @ConfigItem
> HealthProbe probe;
> 
> public enum HealthProbe {
>   NONE,
>   ALL,
>   LIVENESS,
>   READINESS
> }
> ```
> 
> Is the above pseudo code an option?

I think we will need to be more specific than just liveness vs. readiness.
Typically, If we want to only use Liveness then we'll use `/health/live` endpoint and if we want to only use Readiness then we'll use `/health/ready` endpoint.

**Comment by machi1990** [comment]
The semantics with the enum approach above is that the health check could be defined or not (when prope is set to `NONE`). Either `/health/ready` or `/health/live` checks if set to `READINESS` or `LIVENESS` respectively. `ALL`which can be the  default will define the two checks `/health/ready` and `/health/live`

**Comment by loicmathieu** [comment]
@machi1990 @lhauspie I think the idea is to be able to select which health check (regardless to the health check being a liveness or a readiness) to activate for an extension.

As an extension a provides an arbitrary number of health check, we definitively should use a String instead of a boolean. And it's the work of each extension to provides this.

**Comment by geoand** [comment]
I am going to close this as we have configuration for each health check that allows them to be enabled or disabled
