### ISSUE TITLE
A BuildItem for excluding resources from the application archive

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#5576]
**Description**
We (Camel Quarkus) would need a MultiBuildItem that would allow excluding resources from the application archive.

In our case, it is an XSL template file that the user can place to src/main/resources. We compile it into a translet at build time so there is no point in having the source XSLT in the archive. We'd prefer to mark the file as ignored/excluded from the application jar so that the archive can be smaller.

**Comment by ppalaga** [comment]
cc @geoand @gastaldi

**Comment by geoand** [comment]
This would tie in nicely if we do: https://github.com/quarkusio/quarkus/issues/2746

**Comment by ppalaga** [comment]
After all I do not think this is important enough to bother. Sorry for the noise.

**Comment by gastaldi** [comment]
@ppalaga if you're building an UberJar, you can use: https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/pkg/builditem/UberJarIgnoredResourceBuildItem.java
