### ISSUE TITLE
BuildItem holding the current project's basedir 

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#5578]
We currently have OutputTargetBuildItem and ArchiveRootBuildItem that provide access to target and target/classes of the current project respectively. In addition to them, it would be handy to have a BuildItem for the current project's base directory (`${basedir}` for Maven projects).

Our (Camel Quarkus) specific use case is using paths relative to the `${basedir}` in the application.

**Comment by geoand** [comment]
cc @iocanel

**Comment by geoand** [comment]
@iocanel has a PR about this: https://github.com/quarkusio/quarkus/pull/5478

Also it's mentioned in https://github.com/quarkusio/quarkus/pull/5496 (@stuartwdouglas I assume this is very similar to what @iocanel is trying to do)

**Comment by ppalaga** [comment]
Yes this is a duplicate of https://github.com/quarkusio/quarkus/issues/5474
