### ISSUE TITLE
AWS Lambda project is not created if user includes "AWS Lambda" extension

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#5579]
**Describe the bug**
If a user selects the "AWS Lambda" extension when creating a new project at code.quarkus.io the project that is created is a normal RESTEasy JAX-RS project with the aws lambda extension included in the pom.xml 

AWS lambda projects have a different template and include classes and shell scripts to upload and invoke a Lamda onto AWS.

I was also unable to select the "RESTEasy JAX-RS" extension, which is not required in an AWS Lambda project

**Expected project layout**
```
├── create-native.sh
├── create.sh
├── delete-native.sh
├── delete.sh
├── invoke-native.sh
├── invoke.sh
├── payload.json
├── pom.xml
├── src
│   ├── assembly
│   │   └── zip.xml
│   ├── main
│   │   ├── java
│   │   │   └── org
│   │   │       └── acme
│   │   │           ├── InputObject.java
│   │   │           ├── OutputObject.java
│   │   │           ├── ProcessingService.java
│   │   │           ├── TestLambda.java
│   │   │           └── UnusedLambda.java
│   │   └── resources
│   │       └── application.properties
│   └── test
│       └── java
│           └── org
│               └── acme
├── update-native.sh
└── update.sh

```

**Actual project layout**
```
├── mvnw
├── mvnw.cmd
├── pom.xml
└── src
    ├── main
    │   ├── docker
    │   │   ├── Dockerfile.jvm
    │   │   └── Dockerfile.native
    │   ├── java
    │   │   └── org
    │   │       └── acme
    │   │           └── ExampleResource.java
    │   └── resources
    │       ├── application.properties
    │       └── META-INF
    │           └── resources
    │               └── index.html
    └── test
        └── java
            └── org
                └── acme
                    ├── ExampleResourceTest.java
                    └── NativeExampleResourceIT.java

```

**To Reproduce**
1. navigate to https://code.quarkus.io/
2. select "AWS Lambda" extension 
3. click "Generate your application"

Steps to produce correct Amazon Lambda project
1. Follow guide: https://quarkus.io/guides/amazon-lambda#creating-the-maven-deployment-project

```
mvn archetype:generate \
       -DarchetypeGroupId=io.quarkus \
       -DarchetypeArtifactId=quarkus-amazon-lambda-archetype \
       -DarchetypeVersion=1.0.0.CR1
```

**Comment by ia3andy** [comment]
I've moved this issue to GitHub since this case is affecting all the code generation tooling.

**Comment by johnaohara** [comment]
@ia3andy one question about code.quarkus.io, "I was also unable to select the "RESTEasy JAX-RS" extension"  the only dep for an aws projext created with quarkus-amazon-lambda-archetype is on `quarkus-maven-plugin`  Is the `RESTEasy JAX-RS` option mandatory?

**Comment by ia3andy** [comment]
Maybe you found this bug before we added the flag and tooltip:
![image](https://user-images.githubusercontent.com/2223984/69145353-c4875b80-0acd-11ea-9149-c0e708c300f9.png)

This is probably going to change in the future since extension selection is going to direct the code generation..

@johnaohara Does that answer your question?

**Comment by emmanuelbernard** [comment]
is that out of data @patriot1burke ?

**Comment by patriot1burke** [comment]
@emmanuelbernard Its out of date once my latest PR gets in.

**Comment by emmanuelbernard** [comment]
Keeping it open until it gets in then. Thanks.

**Comment by oztimpower** [comment]
Suggest to close, this is outdated.
