### ISSUE TITLE
Improve unit tests coverage regarding Hibernate ORM's handling of import.sql imports

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#558]
See #538

**Comment by machi1990** [comment]
> Specifically test the presence of `import.sql`, absence of it, test another file name and test the property pointing to an inexistent file.

This issue interests me a lot for two main reason:
- It is a good first issue as I am still taking my first steps in the codebase
- It touches unit tests, and I have always asked my self how does it work in the codebase. 
I managed to come with a few test case as suggested by @emmanuelbernard. If it looks good, I'll open a PR for review.

**Comment by Sanne** [comment]
@machi1990 that's awesome, really appreciate the help! Consider the issue yours.

No rush, but feel free to ask for any help you might neet.

**Comment by machi1990** [comment]
> @machi1990 that's awesome, really appreciate the help! Consider the issue yours.
> 
> No rush, but feel free to ask for any help you might neet.

Thanks. As of now, the commit is ready for review: see here: [@machi1990 74302491547cca556](https://github.com/machi1990/quarkus/commit/74302491547cca55649fdf16d85ad9e33d78e89b) . I have four test cases testing the presence of `import.sql`, of another file, and of an absent file. Any case we should can add?

**Comment by Sanne** [comment]
resolved by @machi1990 via PR #1757
