### ISSUE TITLE
Native image gets generated even when all classes are unchanged / up to date

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#5588]
Native image gets generated even when all classes unchanged / are up to date
maven-compiler-plugin detects that case, quarkus-maven-plugin always runs the build

Discussed in https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/skip.20native.20%28re%29build.2C.20run.20just.20test/near/181113795

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
```
```
mvn verify -Dnative  # runs the native compilation
mvn verify -Dnative  # second run should not run the native compilation but it runs it
```

**Comment by mkouba** [comment]
For the record - the fact that no class has changed does not imply that the native image generation should be skipped - for example you can add extesions, change the configuration, resource files, etc.

It's possible to skip the native image manually. Which is not very practical but sometimes it could be useful ;-)

- configure the `maven-failsafe-plugin` outside the "native" profile and skip the "native" profile activation for the second run:
   ```
   mvn verify -Dnative
   # This one will reuse the existing native image
   mvn verify
   ```
* configure the `maven-failsafe-plugin` and do not use the "native" profile at all:
   ```
   mvn verify -Dquarkus.package.type=native
   mvn verify
   ```

**Comment by rsvoboda** [comment]
> you can add extesions, change the configuration, resource files

dev mode can detect these things, standard quarkus build could leverage these capabilities too

> workaround with failsafe

I'd rather have `mvn verify -Dquarkus.native.skip-build=true` for better out-of-the-box experience

**Comment by gsmet** [comment]
I don’t see how that could become a priority anytime soon.

**Comment by rsvoboda** [comment]
I think https://github.com/quarkusio/quarkus/pull/5609 addresses this quite well

Native image gets built only once when following commands are used
```
mvn verify -Dnative
mvn failsafe:integration-test
```

**Comment by rsvoboda** [comment]
@mkouba / @gsmet I think this can be closed, 5609 is good enough for me.
