### ISSUE TITLE
Extension Driven Build Artefacts

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5600]
### Description
Allow extensions to create/modify build artefacts. This is of particular importance for things like Function deployment to the big platforms, Google App Engine etc.

### Analysis
_Links to analysis docs (E.g Design, Requirements, etc)_

### Tasks
- [ ] _Checklist of sub tasks goes here_

**Comment by emmanuelbernard** [comment]
Depends if @patriot1burke work is blocked by that or not to add it as work to be started now

**Comment by maxandersen** [comment]
this is related to #5496 and #6007 to give a zero-config/zero-install build/deploy mechanism.

**Comment by stuartwdouglas** [comment]
This is done.
