### ISSUE TITLE
Failed to package to native image with error: "No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: io.netty.buffer.UnpooledByteBufAllocator"

### ISSUE THREAD

**Issue by 4ntoine** [quarkusio/quarkus#5604]
**Describe the bug**
`./mvnw package -Pnative` failed with the following error:
```
...
No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: io.netty.buffer.UnpooledByteBufAllocator
...
Error: Unsupported features in 6 methods
Detailed message:
Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: io.netty.buffer.UnpooledByteBufAllocator. Try marking this class for build-time initialization with --initialize-at-build-time=io.netty.buffer.UnpooledByteBufAllocator
Trace: 	object io.netty.buffer.EmptyByteBuf
	method io.netty.handler.codec.http.HttpObjectDecoder.readTrailingHeaders(ByteBuf)
Call path from entry point to io.netty.handler.codec.http.HttpObjectDecoder.readTrailingHeaders(ByteBuf): 
	at io.netty.handler.codec.http.HttpObjectDecoder.readTrailingHeaders(HttpObjectDecoder.java:630)
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:361)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
...
```

**Expected behavior**
native image is generated and package succeeds

**Actual behavior**
Got compile error message.

**To Reproduce**
1. git clone git@github.com:4ntoine/NotesServerApp.git
2. cd NotesServerApp
3. git checkout 7c7e3dc9ba0760d2a4d5c52e6e9fe30eb7f449e3
4. ./gradlew publishToMavenLocal
5. cd app-quarkus
6. ./mvnm package -Pnative // make sure graalvm bin is on path

**Configuration**
```properties
quarkus.datasource.url = jdbc:h2:mem:notes
quarkus.datasource.driver = org.h2.Driver

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create

# scan transitive jars
quarkus.index-dependency.rest.group-id = name.antonsmirnov.notes
quarkus.index-dependency.rest.artifact-id = infra-rest-jax-rs
quarkus.index-dependency.jpa.group-id = name.antonsmirnov.notes
quarkus.index-dependency.jpa.artifact-id = infra-gateway-jpa
```

**Screenshots**
<img width="1179" alt="Снимок экрана 2019-11-19 в 22 19 18" src="https://user-images.githubusercontent.com/846671/69169731-aac03580-0b1a-11ea-87a3-09533a23eda2.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
> Darwin MBP-Anton.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
 - GraalVM version (if different from Java): `graalvm-ce-19.1.1`
 - Quarkus version or git rev: `1.0.0.CR1`

**Additional context**
actual last cmd is:
> PATH=$PATH:/Users/asmirnov/Documents/dev/src/graalvm-ce-19.1.1/Contents/Home/bin/ ./mvnw package -Pnative

full output is:

[package_log.txt.zip](https://github.com/quarkusio/quarkus/files/3865211/package_log.txt.zip)

**Comment by machi1990** [comment]
Hi @4ntoine I noticed that you are using GraalVM `19.1.1`, do you have the same output with  `19.2.1`?

**Comment by 4ntoine** [comment]
@machi1990 I haven't checked so far. Any reason think it should help?

**Comment by machi1990** [comment]
This is the latest GraalVM release in use. I cannot recall what is fixed between `19.1.1` and `19.2.1` hence my curiosity about see if we have the same error with the later.

**Comment by 4ntoine** [comment]
I've just tried with GraalVM CE 19.2.1 and the issue is gone. Feel free to close the ticket.
However instead i'm getting:
> General error: "java.lang.UnsupportedOperationException: H2 database compiled into a native-image is only functional as a client: can't create an Embedded Database Session" [50000-197]

I do understand H2 is not meant to be used in production, but is it expected behaviour?

**Comment by machi1990** [comment]
> I've just tried with GraalVM CE 19.2.1 and the issue is gone. Feel free to close the ticket.

Glad the issue is solved. 

> However instead i'm getting:
> 
> > General error: "java.lang.UnsupportedOperationException: H2 database compiled into a native-image is only functional as a client: can't create an Embedded Database Session" [50000-197]
> 
> I do understand H2 is not meant to be used in production, but just out of curiosity - is it expected behaviour?

Yes, H2  Embedded is not yet nativified :-) 

@gsmet I remember having seen an issue for it?
