### ISSUE TITLE
Provides query cache support for Hibernate with Panache

### ISSUE THREAD

**Issue by yuhaibohotmail** [quarkusio/quarkus#5613]
**Description**
Panache does not support hint at this time，so can't support query cache.

**Implementation ideas**
I think add a method is better than using hint.
`
Book.find("id", 12).withCache().list()
`

**Comment by loicmathieu** [comment]
Hi, this can be supports in different ways:

- Your proposal via a dedicated Query cache support
- Via a Query hint: #3482
- Via JPA Query support: named query (#3483) or direclty `PanacheEntity.find(Query query, ...)`

You can join these discussions ;)
There is also an umbrella issue for several Panache improvements: https://github.com/quarkusio/quarkus/issues/4809

Query caching is already enabled in Hibernate with Quarkus (https://quarkus.io/guides/hibernate-orm#caching-of-queries) so this is really how we can simplify it's usage.

**Comment by loicmathieu** [comment]
@yuhaibohotmail hint support just lands inside Hibernate with Panache.
Can we close this one ?

**Comment by yuhaibohotmail** [comment]
yes,Thanks a lot!
