### ISSUE TITLE
Vert.x also provides a JSON implementation so no warning should be emitted

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#5614]
Since https://github.com/quarkusio/quarkus/pull/4165 , we emit a warning if our REST services produce JSON and we don't have any of the RESTEasy JSON extensions:

> [WARNING] [io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor] Quarkus detected the need of REST JSON support but you have not provided the necessary JSON extension for this. You can visit https://quarkus.io/guides/rest-json for more information on how to set one.

Problem is: Vert.x also has the ability to serialize JSON via the Vert.x JSON types.

I think we should drop the warning also when we have the full Vert.x extension around.

See the Reactive MySQL client IT for an example of this issue.

**Comment by gsmet** [comment]
@machi1990 could you have a look at that one? I'd like to get it fixed for the Final we plan to release on Monday.

**Comment by machi1990** [comment]
Will check it a bit later :-)
