### ISSUE TITLE
Unable to use @RegisterRestClient(configKey = "some.config.key")

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#5619]
**UPDATE: this is not a bug, only the error message is misleading.**

Unable to use @RegisterRestClient(configKey = "some.config.key") ot have a more friendly configuration key for the rest client URL.

**Describe the bug***

When defining a rest client with `@RegisterRestClient(configKey = "some.config.key")`
```
@Path("/v1/accounts")
@RegisterRestClient(configKey = "account-api.base-uri")
@Produces("application/json")
@Consumes("application/json")
public interface AccountRestClient {
    [...]
}
```

And having the following line in my `application.properties`
```
account-api.base-uri=http://localhost:8080
```

It fails with the following error:
```
[...]
Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri", configKey="orkey"), or by adding 'account-api.base-uri' to your Quarkus configuration
	at io.quarkus.restclient.runtime.RestClientBase.configureBaseUrl(RestClientBase.java:191)
	at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:52)
```

**Expected behavior**
The MP Rest Client spec seems to allow using a different property but this seems not to works on Quarkus.

```
public @interface RegisterRestClient {
    [...]

    /**
     * Associates the annotated rest client interface with this configuration key. By specifying a non-empty value,
     * this interface can be configured more simply using the configuration key rather than the fully-qualified class
     * name of the interface.
     *
     * @return the configuration key in use by this client interface. An empty value means that this interface is not
     *  associated with a configuration key.
     * @since 1.3
     */
        String configKey() default "";
}
```

**To Reproduce**
1. Create a rest client
2. Use `RegisterRestClient(configKey="some.config")`
3. Add the following line to your application.properties `some.config=http://myhost:myport`
4. Call the rest client

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.0.0.CR1 or current master

**Additional context**
`io.quarkus.restclient.runtime.RestClientBase.configureBaseUrl(RestClientBuilder)` doesn't take into account the confgKey (in fact, the configKey is used ... but only to be used inside the error message).

I will provides a PR for this. 

I will also add an entry inside the documentation as it is not documented but really a good thing to use as the default config key is very long and not very friendly.

**Comment by machi1990** [comment]
+1. IIRC this is not implemented yet so I'd qualify it as enhancement rather than a bug.

**Comment by loicmathieu** [comment]
@machi1990 the code read this annotation property and the error message quote it so, according to me it's implemented but not document ... and buggy

**Comment by loicmathieu** [comment]
Wait, there is no bug, it's just me not understanding how to works because of the lack of documentation.

The configKey is a root config key, we still need to add the `/mp-rest/url`at the end:

The following works:
```
Path("/v1/accounts")
@RegisterRestClient(configKey = "account-apii")
@Produces("application/json")
@Consumes("application/json")
public interface AccountRestClient {
    [...]
}
```

With the following configuration:
```
account-api/mp-rest/url=http://localhost:8080
```

I will provides a fix to the error message that is incorrect and some documentation on it.
