### ISSUE TITLE
Reactive Messaging support

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#562]
* [x] Basic behavior
* [x] Stream qualifier support (https://github.com/jbossas/protean-shamrock/issues/497)
* [x] Get reactive converter working (https://github.com/jbossas/protean-shamrock/pull/605)
* [x] Get something working in native mode
* [x] MQTT sink and source
* [x] Kafka sink and source
* [x] AMQP sink and source
* [ ] Specific JAX-RS integration

**Comment by lulf** [comment]
@cescoffier What remains for the AMQP support?

**Comment by cescoffier** [comment]
@lulf We have implemented a new Vert.x AMQP client (will be released soon - code is here: https://github.com/vert-x3/vertx-amqp-client) that will be used in Reactive Messaging. So expect it in 2 weeks or so.

**Comment by andrejpetras** [comment]
@cescoffier any update on AMQP support? For me it is the last missing piece to migrate JMS application.

**Comment by cescoffier** [comment]
@andrejpetras AMQP has been added.

**Comment by andrejpetras** [comment]
@cescoffier thanks, is working well ;) I create a new ticket for the AMQP client to add the modified method.
https://github.com/vert-x3/vertx-amqp-client/issues/18

**Comment by cescoffier** [comment]
@andrejpetras I've added the `modified` method in the client. We would be able to benefit from it once it's released.

**Comment by andrejpetras** [comment]
@cescoffier thanks

**Comment by cescoffier** [comment]
The remaining action will be tracked in another issue.
