### ISSUE TITLE
Refactor GitHub Repositories

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5626]
### Description
We need to decide if https://github.com/quarkusio/quarkus should continue to be a mono-repo or if it should be broken up. 

Regardless of the outcome form that decision, we need to allow independent releases and CI runs.

This Epic covers the analysis of the above situation as well as any changes that are decided to be needed.

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
- [ ] Finish conversation and arrive at proposal conclusion
- [ ] Work on implementing it

**Comment by iocanel** [comment]
Definitely not an analysis but here are my two cents:

In the past I've worked with two pretty similar projects:

- Apache Camel
- Apache ServiceMix

Camel used a monorepo style (core and compoents were part of a single repo).
ServiceMix used different repos (core and compoents were split and released individually).

My experience as a user was that it was so much simpler to have everything released together. Indepndent releases meant that I would somehow find the right combination of core and components.

My experience as a committer on these projects was that split repos was always a source of furstration. It's hard to get CI right, refactoring are painful etc.

**Comment by dufoli** [comment]
just my 2 cents, git submodules is very painfull. I have used it on banshee long time ago.

**Comment by emmanuelbernard** [comment]
I'll close that issue as in the end the conversation is more about the notion of platform and universe and how to make sure testing results properly flow. We can reopen at some point once we get clearer ideas.
