### ISSUE TITLE
RecorderContext.proxyClass(...).asSubClass(...)  should return the proxy

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#5630]
RecorderContext.proxyClass() returns Class<?>, but sometimes we need Class<? extends Animal>.
The JDK supports that:

```
class Class<T> {
   public <U> Class<? extends U> asSubclass(Class<U> clazz) {...}
}
```

However, this code fails in deployment module:

```
Class<? extend Animal> animalClass = recorderContext.proxyClass("org.acme.Dog").asSubClass(Animal.class);
```

Because the proxy class passes the invocation along, instead of shortcutting it to return this.

**Comment by ge0ffrey** [comment]
**Workaround**:
Class<? extend Animal> animalClass = (Class<? extend Animal>) recorderContext.proxyClass("org.acme.Dog");

**Difficulty to fix with a Pull Request**
Hard: BytecodeRecorderImpl.classProxy() builds the proxy,
but there are no obvious ways to implement/override one of the proxy methods (the asSubClass method) to return the proxy itself.

**Comment by dmlloyd** [comment]
I don't think this analysis can possibly be correct.  `asSubClass` checks the type and returns `this`.  If calling that method fails, then the unsafe cast you mention will also fail (just later rather than sooner).

**Comment by ge0ffrey** [comment]
@dmlloyd The unsafe cast doesn't fail. In quarkus deployment, asSubClass doesn't return `this`, like it does in normal JDK. That's because Class is being proxied and does something else than `return this`, which it should be doing.

**Comment by dmlloyd** [comment]
You cannot proxy `Class` AFAIK?

**Comment by ge0ffrey** [comment]
@dmlloyd I definitely got the impression during debugging that there was some sort of Class proxy in play there during the "deployment" phase. I even tracked down the code creating it to `BytecodeRecorderImpl.classProxy()`. But then I got stuck in trying to fix this to make the proxy's `asSubClass` return itself.

**Comment by dmlloyd** [comment]
Ah I see, it's in the actual build step that you're having a problem.  And I see that it's not a proxy _of_ `Class`, it's a `Class` of the proxy of the injected type, which makes a bit more sense.

Normally you shouldn't perform too much complex logic in the build step; rather, you farm it out to a recorder class (annotated `@Recorder`) which deals with the real classes, not proxies.  Basically the build step can usually directly call the recorder method which can do the real work.

So usually problems like this mean you're trying to push the build step side a bit too far.

**Comment by ge0ffrey** [comment]
Closing this as it's no longer needed on my side and there is little expectation that others need it.
