### ISSUE TITLE
Remove the workaround for ForkJoin to spin up threads

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#5631]
**Describe the bug**
We set `-J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1` in `NativeImageBuildStep`
to workaround for 
 - https://github.com/oracle/graal/issues/660

It seems the GraalVM issue was resolved; are we safe to remove the workaround from Quarkus?

@stuartwdouglas needs your opinion at least

**Comment by gsmet** [comment]
I'm not sure the commit has been included in 19.2.x:
https://github.com/oracle/graal/commit/e78fc21f53488848f791dca3db394031698177f2

From what I can see, it's only in 19.3 but I might be wrong.

**Comment by gwenneg** [comment]
This was included in 19.3.0 indeed.

**Comment by stuartwdouglas** [comment]
This would be a good fix to have, I think it may speed up our native builds as I know the native compilation does use fork join internally in places.

**Comment by machi1990** [comment]
> This was included in 19.3.0 indeed.

@gwenneg Good to know. Any chance you could take this as part of your on going work with `19.3.0` ?

**Comment by gwenneg** [comment]
@machi1990 Sure, this could be part of #5358

**Comment by machi1990** [comment]
Thanks @gwenneg

**Comment by gwenneg** [comment]
Done in #5358.
