### ISSUE TITLE
Create Panache RX (via Hibernate) MVP

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5634]
### Description
Create an initial Minimal Viable Product for Panache RX (via Hibernate). 

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
- [ ] _Checklist of sub tasks goes here, represented as links to GitHub issues_

**Comment by paulrobinson** [comment]
@emmanuelbernard are we ready to assign a person to this Epic?

**Comment by emmanuelbernard** [comment]
It's Davide, Stef, Gavin, Martin and Sanne

**Comment by paulrobinson** [comment]
@FroMage, @gavinking, @Sanne is there an obvious person between you that will be organising this work? Just working out who to assign it to. FYI: this is how we decide who is assigned: https://github.com/quarkusio/quarkus/wiki/High-Level-Planning-Process#ive-been-assigned-an-epic-what-do-i-need-to-do

Also, can you ping "Davide and Martin" on this. I'm not 100% sure who Emmanuel refers to (I could guess).

**Comment by FroMage** [comment]
They are Davide d'Alto (Hibernate team) and @mkouba.

You can assign the epic to me.

**Comment by geoand** [comment]
With Hibernate Reactive having been integrated in Quarkus, I think this can be closed now, right?

**Comment by Sanne** [comment]
Right, closing.
