### ISSUE TITLE
Vault Extension Serialization Error in Native Mode at Runtime

### ISSUE THREAD

**Issue by valones** [quarkusio/quarkus#5636]
**Description**
Following the implementation of the Vault guide (https://quarkus.io/guides/vault) generates serialization error in native mode at runtime, [stacktrace attached](https://github.com/quarkusio/quarkus/files/3870212/stacktrace.txt).

As a workaround, I added the following `reflection-config.json`:
```json
[
  {
    "name" : "io.quarkus.vault.runtime.client.dto.VaultAppRoleAuthBody",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  },
  {
    "name" : "io.quarkus.vault.runtime.client.dto.VaultAppRoleAuthAuthMetadata",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  }
]
```

**Steps to reproduce the behavior**
1. Follow the guide: https://quarkus.io/guides/vault
2. `mvn package -Pnative`
3. Run the native runner

**Configuration**
```properties
quarkus.vault.url=https://my-vault.onkubernetes.intranet
quarkus.vault.tls.skip-verify=true
quarkus.vault.authentication.app-role.role-id=******
quarkus.vault.authentication.app-role.secret-id=******
quarkus.vault.kv-secret-engine-version=2
quarkus.vault.secret-config-kv-path=apps/sample/config
```

**Environment**
 - OS
Linux xxxxxx 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Java
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
 - GraalVM
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
 - Quarkus version
1.0.0.CR2

**Comment by vsevel** [comment]
@valones you are right both of those classes are missing `implements VaultModel`, which is the marker for creating a `ReflectiveClassBuildItem` in `VaultProcessor`
@gsmet it is an easy fix. you can assign to me. I will try to do it these coming days.

**Comment by vsevel** [comment]
https://github.com/quarkusio/quarkus/pull/5717
