### ISSUE TITLE
[Vault]: Add Support to Multiple Vault KV Paths

### ISSUE THREAD

**Issue by valones** [quarkusio/quarkus#5638]
It would be nice if the `quarkus.vault.secret-config-kv-path` property supported multiple vault kv-path entries.

**Comment by vsevel** [comment]
@valones it is pretty easy (and backward compatible) if we just make it a comma separated list of paths. 
it is a bit more involved if there could be collisions on some names (for instance 2 paths with the same key `password`), which would require to be able to specify a prefix (eg mount all properties at vault path `secret/myconfig` as `myconfig.XXX` properties).
@sberyozkin what do you think?
@gsmet you can assign it to me if you want

**Comment by sberyozkin** [comment]
@vsevel we'll probably need to update [Vault KV interface](https://github.com/quarkusio/quarkus/blob/master/extensions/vault/runtime/src/main/java/io/quarkus/vault/VaultKVSecretEngine.java) with a new method accepting a set of paths too.
@vsevel, perhaps we should block such cases for now at least if the collisions occur ?

**Comment by vsevel** [comment]
see PR https://github.com/quarkusio/quarkus/pull/6174
