### ISSUE TITLE
[oidc] Add Ability to Skip TLS Verify

### ISSUE THREAD

**Issue by valones** [quarkusio/quarkus#5640]
For development purposes it would be interesting to be able to skip the tls verification of the oidc auth server.

**Comment by sberyozkin** [comment]
@valones are you working with `quarkus-oidc` only or with `quarkus-keycloak-authorization` ?

**Comment by valones** [comment]
quarkus-oidc only, following the https://quarkus.io/guides/security-openid-connect-web-authentication guide. But I used a keycloak server running on openshift

**Comment by sberyozkin** [comment]
@valones In this case it is controlled at the Vertx Oauth2 level. @cescoffier Hi Clement, do you if it is possible to configure Vertx somehow to skp the TLS verification ?

**Comment by cescoffier** [comment]
That's a question for @pmlopes.

**Comment by pmlopes** [comment]
Vertx oauth2 option class extends the netclient options so it can be disabled there:

```java
setTrustAll(true)
```

Please check the API, I'm typing out of my head...

**Comment by pedroigor** [comment]
Isn't this just a matter of pointing to a server that also exposes HTTP ? I mean, if you control the server you are free to lax security a bit in the development environment.

In general, I would say that this is more a use-case specific requirement in regards to how they deal security in their different environments. Some may also find necessary to enforce TLS to have development in sync with production (where you may also have features that need to be developed that relies on TLS).

**Comment by sberyozkin** [comment]
Looks like all is resolved here, so closing this issue now

**Comment by gsmet** [comment]
I think it would be nice to expose an option for that. @fhmwong any chance you could have a look?

**Comment by fmhwong** [comment]
sure
