### ISSUE TITLE
Bean discovery via configuration

### ISSUE THREAD

**Issue by gitBroker** [quarkusio/quarkus#5649]
I miss the cdi configuration of alternatives e.g. via beans.xml. I want to configure the use of beans without the need of recompiling my app, or did I miss something? Is there any other option than beans.xml?

**Comment by ia3andy** [comment]
I don't really understand your question, could you give more details and some example maybe?

**Comment by gitBroker** [comment]
@ia3andy Sorry ... Thanks for inspiring me to think  again ... The feature request can be closed or better deleted. Sorry for wasting your time!)

(I was searching for dynamic cdi injection at runtime. E.g. I have an interface with 2 implementations.  In another class I @Inject the interface. Now the cdi container has to know which concrete implementation should be injected. I guess the right was to to this are producer methods in combination with microprofile configuration ...)

**Comment by gitBroker** [comment]
I close ....

**Comment by ia3andy** [comment]
I am glad you found a solution to your problem! Have fun with Quarkus :-)
