### ISSUE TITLE
ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory when using jaxb for native image with jaxb classes in external jar

### ISSUE THREAD

**Issue by chriskn** [quarkusio/quarkus#5651]
Hi, the bug #5558 was fixed with the CR2 version but the same problem still occurs when I  copy the jaxb generated classes in an external jar. I updated my showcase at https://github.com/chriskn/data.provider.static/tree/external_jaxb_jar and created this branch.

See #5558 for more details. 
@gsmet I mention you because you fixed  #5558 .
Thanks in advance.

**Comment by gsmet** [comment]
You have to get your external jar properly indexed or the JAXB annotations won't be found.

See https://stackoverflow.com/a/55513723 .

**Comment by chriskn** [comment]
Does this count only for native images? Because fot the jvm image it works without indexing.

**Comment by gsmet** [comment]
Well, most of the JAXB processor work is there to tune native image building.

If we think that JAXB is useless (and this is the case if we don't find any root JAXB annotations), then we don't configure things for the native image (in particular, we don't include some classes necessary for JAXB to work to reduce the size of the native image).
