### ISSUE TITLE
Support service-account OIDC/OAuth2 applications

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#5657]
**Description**
Some Quarkus endpoints may act as `service-account` OIDC/OAuth2 applications where they need to acquire a token before accessing some other downstream endpoints.

**Implementation ideas**
Proposal is to have it supported at 2 levels:
1. Enhance the OIDC adapter itself with a new application type `service-account` - the users will have `JsonWebToken` or `AccessTokenCredential` injected, the same way they have it with the `service` application type. 
2. Introduce an injectable `OidcClient` which the users can use to get the access token

The former is better IMHO as that way we can cache the access tokens may be and auto refresh them and it just fits better into out strategy of making the OIDC experience easy for the users

CC @stianst @pedroigor @sebastienblanc @kenfinnigan

**Comment by sberyozkin** [comment]
Andrej Petras shared [this code](https://quarkusio.zulipchat.com/user_uploads/11321/tfxXcjFkRS5PSPz1d3pZ2pq_/OpenIDConnectInterceptor.java) they are using at the moment.

**Comment by kenfinnigan** [comment]
Could you add the code directly, the link requires logging in to Zulip which is a bit annoying

**Comment by andrejpetras** [comment]
Example implementation:
[OpenIDConnectInterceptor.zip](https://github.com/quarkusio/quarkus/files/3875303/OpenIDConnectInterceptor.zip)

**Comment by sberyozkin** [comment]
Vertx OAuth2 example:
```
OAuth2ClientOptions credentials = new OAuth2ClientOptions()
  .setClientID("<client-id>")
  .setClientSecret("<client-secret>")
  .setSite("https://api.oauth.com");


// Initialize the OAuth2 Library
OAuth2Auth oauth2 = OAuth2Auth.create(vertx, OAuth2FlowType.CLIENT, credentials);

JsonObject tokenConfig = new JsonObject();

oauth2.authenticate(tokenConfig, res -> {
  if (res.failed()) {
    System.err.println("Access Token Error: " + res.cause().getMessage());
  } else {
    // Get the access token object (the authorization code is given from the previous step).
    User token = res.result();
  }
});
```
So I think we can easily enough update the adapter

**Comment by stianst** [comment]
I'm not sure option 1 is possible. Use-cases for a service account include:

* A background job that is not executing in the scope of a user request
* Invoking a service with a different token to the incoming user request

Then there is also token exchange which can be used to get a different token to the incoming token from the user request to consider.

Ideal is probably something along the lines of a OidcClient that can be injected to obtain tokens for a service account, as well as in the future support token exchange. Ideally it should be configurable through the application.properties.

One question for client authentication what is supported now? For service accounts it should really use mtls or jwt auth, and not just client secret.

**Comment by sberyozkin** [comment]
@stianst @sebastienblanc thanks, yes, injectable `OidcClient`would be a way to start, especially to address Stian's 1st case `A background job that is not executing in the scope of a user request`. 
When we have `Invoking a service with a different token to the incoming user request`, we can make option1 work if we introduce a qualifier such as `@ServiceAccount`, similarly to the way we qualify ID tokens:
```
@ServiceAccount
JsonWebToken serviceAccessToken;
```
That should work even if the current user request has its own tokens...(but that even can be reviewed later)

What I'm not sure about though where this `OidcClient` code should live. The user may be using MTLS or form-based auth (i.e, not even related to OIDC) to get to the endpoint, so technically they should not be required to include `quarkus-oidc`, so may be `quarkus-oidc-client` which would just ship the MP RestClient code and possibly a client filter and support all the authentication options you have mentioned. 

I hope we can tackle the token exchange as part of the `quarkus-oidc` `service` flow later too :-)
Thanks

**Comment by pedroigor** [comment]
I also agree that a client is the best way to go. However, it is worth mentioning that spec-wise client authentication at the token endpoint does not require a refresh token to be returned. Reason being that there is no much sense about returning RT for clients acting on their own behalf (differently when they are acting on behalf of users). So refresh tokens is not a primary requirement for dealing with service accounts.

I'm also wondering whether or not we should just rely on some existing API/Impl. Do we really want to have our own? I mean, users probably have their own preferred libraries or even in-house code that is quite trivial to implement.

**Comment by pedroigor** [comment]
> ```
> @ServiceAccount
> JsonWebToken serviceAccessToken;
> ```
> 
> That should work even if the current user request has its own tokens...(but that even can be reviewed later)

It seems like a bad SoC if you have the same application using both approaches. An application acting as a background job has different requirements in terms of functionality, deployment, and execution if compared with another one that just handles access tokens to serve protected data.

In addition to that, you could even have background applications using long-lived access tokens that were issued to users (not only when acting on their own behalf).

I think that we should gather more feedback from the community and get more use cases (and requirements) before doing anything at this regard.

**Comment by sberyozkin** [comment]
@pedroigor yes, the refresh token is not expected to be actually returned for the client cred, so we indeed should not worry about it. Not sure about your point of asking the users to do some existing libraries. I've opened this issue because the users are having to write their own code (example, see one such case attached)

>  It seems like a bad SoC if you have the same application using both approaches. An application acting as a background job has different requirements...

True, I was talking about Stian's case where it is not a real background application, `Invoking a service with a different token to the incoming user request`. This is absolutely realistic, and as I said the incoming request may've  been authenticated with anything, not even OIDC.

We don't have to solve N cases with our solution. We need to let the users easily get the tokens which are not tied to the incoming requests or for the true background applications, without suggeting them a DYI token acquisition

**Comment by pedroigor** [comment]
I see your point. I'm just concerned about trying to provide an API that may not be enough even though we provide only the basic capabilities to automatically fetch tokens (based on client authentication). My point is more "let's get more use cases and feedback on that and try to come up with something".

As I said, you may not even have to DYI but use some library (if available, today there is library for everything :)).

**Comment by sunmeplz** [comment]
Hi there!
In my case I'd like to see some @ServiceAccount("tenant") with cooperation with @RegisterRestClient
so all invocations to this client should be filled with token

**Comment by sberyozkin** [comment]
@sunmeplz Hi, what token are you referring to here, the bearer access token or the access token returned with the code grant or the service account token which Quarkus will acquire itself ?

**Comment by coding4kay** [comment]
I think the “normal” use case is following:

-       public frontend client for amazing app
-       backend client with roles with roles [READ, WRITE] for amazing app
-       search service client with roles [READ, WRITE]

Now I want to call the search service from my amazing app backend.

I can give my user the role [READ,WRITE] from my amazing app and [READ] from my search service and forward the bearer token.
In quarkus with rest client setup
org.eclipse.microprofile.rest.client.propagateHeaders=Authorization

But in this setup, it would make more sense if I can add the READ role from my search service to the service account from my amazing app backend, without forwarding the user bearer token.
Then I can also execute calls from my amazing app to my search service outside a user request.

**Comment by sunmeplz** [comment]
@sberyozkin Hi
the case like @coding4kay described.
For a example we have some king of service which have scheduler and it's calls executed out of user request scope. So we are mapping the required role to service account and getting service account bearer token during schedule execution and pass to http client.

**Comment by andrejpetras** [comment]
Hi,
I need to create MP RestClient which needs to call endpoint secured with the Keycloak OpenID. 
My application itself does not have any security and does not need any security.

Do we have simple example how to setup and configure the MP RestClient to call secured endpoint with a KC?

BR,
Andrej

**Comment by sberyozkin** [comment]
Hi All just a quick update that I did start with the oidc client branch but other issues have intervened, nonetheless, this issue is on the map

**Comment by sberyozkin** [comment]
During the first phase there will be an injectable `OidcClient` provided which will help with the access token acquisition

**Comment by sberyozkin** [comment]
This issue is on track; some more time is needed to tune a few things for the initial PR.

**Comment by sberyozkin** [comment]
Draft PR is here: #5657; few more improvements are needed before I'll open it for review but it is close enough
