### ISSUE TITLE
Indicate in the guides the extensions that are preview

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#5658]

**Comment by gwenneg** [comment]
I'll take care of it.

Should I improvise about the way it is indicated or is there already an existing generic sentence somewhere and/or a way to display the info (a warning block maybe?).

**Comment by machi1990** [comment]
Hi @gwenneg maybe we can have something similar to https://quarkus.io/guides/mongodb-panache ?

**Comment by gsmet** [comment]
I would make it a NOTE instead of warning and maybe change "is still
experimental" for "is considered `preview`" to be consistent with the
code.quarkus.io wording.

If I can have it before Sunday evening, I'll include it in 1.0.0.Final as
it seems to be important information.

Thanks!

**Comment by gwenneg** [comment]
Thanks for the link @machi1990!

@gsmet I'll submit the PR in a couple hours.
