### ISSUE TITLE
Spring Security Support

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5663]
### Description
Decide on what features from Spring security should be supported then implement the important ones for this Epic.

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
- [x] Support Spring Security's `@Secured` (#5225)
- [ ] Support Spring Security's `@PreAuthorize` (in progress by @geoand)

**Comment by geoand** [comment]
Support for Spring's `@Secured` annotation has been implemented by @aureamunoz.
I am working on `@PreAuthorize` and will be opening a PR within the week.

**Comment by paulrobinson** [comment]
@geoand can you add these items to the checklist?

**Comment by geoand** [comment]
@paulrobinson done

**Comment by paulrobinson** [comment]
@geoand is there a GitHub issue for that work? If so, can you link it?

**Comment by geoand** [comment]
@paulrobinson we have this general one: https://github.com/quarkusio/quarkus/issues/4037 Should we make specific ones for each feature?

**Comment by paulrobinson** [comment]
@geoand to me it looks like #4037 is a duplicate. Do you agree? If so, i could merge them together, keeping #4037 so as to preserve the conversation.

**Comment by geoand** [comment]
@paulrobinson yeah, that makes perfect sense to me

**Comment by paulrobinson** [comment]
OK. Merged the content from here into #4037. 

Closing this issue.

**Comment by geoand** [comment]
Thanks @paulrobinson !
