### ISSUE TITLE
writing-native-applications-tips including-resources filename in snippet wrong

### ISSUE THREAD

**Issue by alexander-dammeier** [quarkusio/quarkus#5673]
Hello,

i tried to add a reflection- and a ressources-config.json. I copied the given snippet from the tutorial to include both files via applications.properties but one filename is wrong. It should be `resources-config.json` not `resource-config.json`. There is an `s` missing.
```
quarkus.native.additional-build-args =\
    -H:ResourceConfigurationFiles=resource-config.json,\
    -H:ReflectionConfigurationFiles=reflection-config.json
```
https://quarkus.io/guides/writing-native-applications-tips#including-resources

Can you please correct it? Thank you

Edit:
There is an issue with the reflection chapter too.
`
quarkus.native.additional-build-args =-H:ResourceConfigurationFiles=reflection-config.json
`
should be:
`
quarkus.native.additional-build-args =-H:ReflectionConfigurationFiles=reflection-config.json
`

**Comment by gwenneg** [comment]
Hi @alexander-dammeier and thanks for reporting this!
