### ISSUE TITLE
@QuarkusTest and Maven with range in parent pom: Failed to create the boostrap class loader

### ISSUE THREAD

**Issue by mejlholm** [quarkusio/quarkus#5678]
**Describe the bug**
Seems like there has been a regression in the latest version of Quarkus 1.0.0.CR2, where we can't run tests using @QuarkusTest, because we have a range in our parent pom. Something like this in the main pom.xml:

```
    <parent>
        <groupId>our.company.maven</groupId>
        <artifactId>git-build-pom</artifactId>
        <version>(1.0,2.0)</version>
    </parent>
```

Makes our builds fail like this:

```
build	22-Nov-2019 09:31:17	org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [dk.sparnord.menu.MenuResourceTest]: Failed to create the boostrap class loader
build	22-Nov-2019 09:31:17	Caused by: java.lang.IllegalStateException: Failed to create the boostrap class loader
build	22-Nov-2019 09:31:17	Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the deployment classloader for dk.sparnord.services:menu-of-the-day::jar:0-SNAPSHOT
build	22-Nov-2019 09:31:17	Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to read descriptor of dk.sparnord.services:menu-of-the-day:jar:0-SNAPSHOT
build	22-Nov-2019 09:31:17	Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for dk.sparnord.services:menu-of-the-day:jar:0-SNAPSHOT
build	22-Nov-2019 09:31:17	Caused by: org.apache.maven.model.resolution.UnresolvableModelException: No versions matched the requested parent version range '(1.0,2.0)'
```

I've verified that this is an issue across multiple of our Quarkus projects. We are not using GraalVM. 

**Expected behavior**
Run test without failure

**Actual behavior**
Fails with stack trace shown above

**To Reproduce**
1. mvn verify

**Comment by aloubyansky** [comment]
I just tried it to reproduce it with `org.jboss:jboss-parent` as the parent. With range `(0,36]` and it worked.

**Comment by aloubyansky** [comment]
@mejlholm do you by chance have a simple project that can be used as a reproducer? Thanks.

**Comment by aloubyansky** [comment]
What's the latest version of Quarkus that worked for you?

**Comment by aloubyansky** [comment]
Do you have a pom that satisfy the specified version constraint in your local repo?

**Comment by mejlholm** [comment]
> @mejlholm do you by chance have a simple project that can be used as a reproducer? Thanks.

I'll try to create one. The problem only seems to occur on our build environment and not locally. There shouldn't be any noticable differences, but i'll dig on our end to find out what is triggering it. 

> What's the latest version of Quarkus that worked for you?

Has worked for a long time, from the earlies versions around 0.15.0 through to 0.28.1 and 1.0.0.CR1, but not in 1.0.0.CR2. 

> Do you have a pom that satisfy the specified version constraint in your local repo?

**Comment by aloubyansky** [comment]
Ah, an interesting detail. Is the parent pom a part of the same (multimodule) project?

**Comment by mejlholm** [comment]
So after digging around, i believe that the problem is something else. If I remove the parent pom from the project and try again it still fails, but with another error

```
build	22-Nov-2019 14:38:42	org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [dk.sparnord.menu.MenuResourceTest]: Failed to create the boostrap class loader
build	22-Nov-2019 14:38:42	Caused by: java.lang.IllegalStateException: Failed to create the boostrap class loader
build	22-Nov-2019 14:38:42	Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the deployment classloader for dk.sparnord.services:menu-of-the-day::jar:0-SNAPSHOT
build	22-Nov-2019 14:38:42	Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to read descriptor of dk.sparnord.services:menu-of-the-day:jar:0-SNAPSHOT
build	22-Nov-2019 14:38:42	Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for dk.sparnord.services:menu-of-the-day:jar:0-SNAPSHOT
build	22-Nov-2019 14:38:42	Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact io.quarkus:quarkus-bom:pom:1.0.0.CR2 from/to central (https://repo.maven.apache.org/maven2): /home/bamboo/.m2/repository/io/quarkus/quarkus-bom/1.0.0.CR2/quarkus-bom-1.0.0.CR2.pom.part.lock (No such file or directory)
build	22-Nov-2019 14:38:42	Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.quarkus:quarkus-bom:pom:1.0.0.CR2 from/to central (https://repo.maven.apache.org/maven2): /home/bamboo/.m2/repository/io/quarkus/quarkus-bom/1.0.0.CR2/quarkus-bom-1.0.0.CR2.pom.part.lock (No such file or directory)
build	22-Nov-2019 14:38:42	Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.quarkus:quarkus-bom:pom:1.0.0.CR2 from/to central (https://repo.maven.apache.org/maven2): /home/bamboo/.m2/repository/io/quarkus/quarkus-bom/1.0.0.CR2/quarkus-bom-1.0.0.CR2.pom.part.lock (No such file or directory)
build	22-Nov-2019 14:38:42	Caused by: java.io.FileNotFoundException: /home/bamboo/.m2/repository/io/quarkus/quarkus-bom/1.0.0.CR2/quarkus-bom-1.0.0.CR2.pom.part.lock (No such file or directory)
```

The thing is, for our build nodes the .m2 is located in /tmp/.m2, not in /home/bamboo/.m2. 

This lead me back to the changelist and i notice this:

https://github.com/quarkusio/quarkus/pull/5607

and true enough, we are using M2_HOME on our build agents. I tried building with MAVEN_HOME and it works. So, should we just move forward and set MAVEN_HOME or would you want to support both M2_HOME and MAVEN_HOME going forward? I guess it could break some other peoples builds as well.

**Comment by aloubyansky** [comment]
Ah, ok. Yes, that was based on https://maven.apache.org/docs/3.5.0/release-notes.html (search for M2_HOME). Since Quarkus requires 3.5.3 at a minimum I decided to simply go for MAVEN_HOME.

**Comment by mejlholm** [comment]
That sounds like a fair decision, given the direction set out by maven. 

I'll setup our build agents to use MAVEN_HOME and close the issue.
