### ISSUE TITLE
Integrate mock and testing

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#568]
From Ladislav Thon

>2.3. Mock certain ArCDI beans, most likely those that reach out to 
>external services. (I'm using the word "mock" to mean "test double" 
>and don't distinguish mocks, stubs, spies etc.) I guess this might 
>already be possible, as the test class is itself considered a bean and 
>can define producer methods? (Didn't try.)

**Comment by jordanglassman** [comment]
For posterity, the easiest way to use this paradigm alongside a mocking library is to just pass a delegate mock instance from your mock library of choice to the `@Alternative`.

Here's a jmockit example:

```    
@QuarkusTest
public class MyTest {

   @Inject
    TestContext testContext;

    @Test
    public void onInstalled(@Injectable ClientManager clientManager) throws Exception {
        testContext.setClientManagerDelegate(clientManager);

        given()
                .when()... // do some testing

        new Verifications() {{
            clientManager.createUser(withNotNull());
            times = 1;
        }};
    }......
}

@Mock
public class MockClientManager extends ClientManager {
    @Inject
    TestContext testContext;

    @Override
    public void createUser(@Nonnull final AppClientData appClientData) throws Exception {
        testContext.getClientManagerDelegate().createUser(appClientData);
    }

   ....
}
```
