### ISSUE TITLE
quarkus-maven-plugin libDir configuration entry is being ignored

### ISSUE THREAD

**Issue by Arcnor** [quarkusio/quarkus#5683]
**Describe the bug**
When configuring the `quarkus-maven-plugin` with the `libDir` setting, nothing really happens. Taking a quick look at the code, the variable is being set but nothing seems to be happening with it at all.

**Comment by gsmet** [comment]
It was removed.

**Comment by Arcnor** [comment]
As you can imagine, I was using this functionality, so can you tell me what's the alternative to what the `libDir` configuration parameter was doing?

**Comment by gsmet** [comment]
Hmmm, but it wasn't wired at all? How did you make use of it?

And what were you trying to accomplish?

**Comment by Arcnor** [comment]
This was working on a previous version. But I just checked the linked issue and it looks like the `lib` directory will go wherever the final build directory is, which I guess it's wherever the `finalName` config setting points to?

That will work for my usecase.

**Comment by Arcnor** [comment]
Unfortunately it doesn't seem to work as I expected, `finalName` will move the generated `jar` to wherever I point, but the `lib` directory stays at `target`.

Is there anything I can do to move the `lib` directory to the right place, besides doing it myself with maven trickery?

**Comment by gsmet** [comment]
IMHO, it makes sense to have the `lib` directory together with the `-runner.jar`. @Arcnor when you define a `finalName`, the `-runner.jar` is generated in the appropriate directory?

**Comment by Arcnor** [comment]
Yes, the `-runner` is in the `finalName` directory, but `lib` doesn't move with it.

**Comment by gsmet** [comment]
@jaikiran could you see if it's easily doable and if it makes sense?

What is a bit annoying is that our generated Dockerfiles won't be accurate for this kind of setup.

But I'm more and more thinking that we should generate them dynamically during the build.

**Comment by jaikiran** [comment]
I'll take a more detailed look.

**Comment by diogocarleto** [comment]
@Arcnor you can use some like that as a workaround:

> <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>copy-resources</id>
            <phase>verify</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/appengine-staging/lib</outputDirectory>
              <resources>
                <resource>
                  <directory>${project.build.directory}/lib</directory>
                  <filtering>true</filtering>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

Best.

**Comment by rsvoboda** [comment]
@gsmet @jaikiran any plans around this issue ?
