### ISSUE TITLE
Clean NettyProcessor when `netty.version` is 4.1.43.Final or greater

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#5686]
The following code was introduced in the quarkus-netty extension in #5500 as a workaround for a GraalVM 19.3.0 compatibility [issue](https://github.com/netty/netty/pull/9631):

```
class NettyProcessor {
    // Other methods...

    // TODO: Remove this when netty.version is 4.1.43.Final or greater.
    @BuildStep
    public List<UnsafeAccessedFieldBuildItem> unsafeAccessedFields() {
        return Arrays.asList(
                new UnsafeAccessedFieldBuildItem("sun.nio.ch.SelectorImpl", "selectedKeys"),
                new UnsafeAccessedFieldBuildItem("sun.nio.ch.SelectorImpl", "publicSelectedKeys"));
    }
}
```

This code should be removed as soon as the Netty dependencies are updated to 4.1.43.Final or greater.

**Comment by mejlholm** [comment]
Looks like there is a 4.1.45 version of netty now - and 4.1.42 has reported vulnerabilities:

https://snyk.io/vuln/SNYK-JAVA-IONETTY-543490
https://snyk.io/vuln/SNYK-JAVA-IONETTY-543669

Is there anything holding bumping the netty version back?

**Comment by gwenneg** [comment]
Netty should be upgraded to `4.1.44.Final` on the Quarkus `master` branch before the end of the day: https://github.com/quarkusio/quarkus/pull/6956#issuecomment-581427352
