### ISSUE TITLE
document how to use 999-SNAPSHOT of quarkus with a universe-platform based project

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5687]
see https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/create.20cmd.20issue.20with.20new.20extension/near/181634045

**Comment by geoand** [comment]
cc @aureamunoz

**Comment by gsmet** [comment]
@aureamunoz so should I close this one? I see the PR has been merged.

**Comment by aureamunoz** [comment]
Yes! @gsmet, you can close it. I has been already merged. 
Thank you!!

**Comment by gsmet** [comment]
Thanks for the feedback.
