### ISSUE TITLE
HttpServletResponse.setCharacterEncoding does not wok in Quarkus/undertow

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#5693]
Quarkus: 1.0.0.CR2. 

I tried to handle exceptions by writing content into response manually.  [The original post is on stackoverflow](https://stackoverflow.com/questions/58966932/httpservletresponse-set-charset-does-not-wok-in-quarkus-undertow).

Source codes: [PostExceptionHandler#handleException2](https://github.com/hantsy/quarkus-sandbox/blob/master/spring-post-service/src/main/java/com/example/PostExceptionHandler.java#L42)

```java
@ExceptionHandler(Exception2.class)
public void handleException2(Exception2 e, HttpServletResponse response) throws IOException {
	PrintWriter out = response.getWriter();
	response.setContentType("application/json");
	response.setCharacterEncoding("UTF-8");
	response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
	out.write("{\"message\":\"" + e.getMessage() + "\"}");
	out.flush();
}

```
When I ran the application, and access url to test this exception. 

```java
@GetMapping("e2")
public ResponseEntity exception2(){
    throw new Exception2("error 2");
}
```

When the exception is caught, it always set charset as **ISO-8859-1**.

```bash
curl -v http://localhost:8080/e2
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /e2 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Type: application/json; charset=ISO-8859-1
< Transfer-Encoding: chunked
<
{"message":"Exception 2:error 2"}*
```

I am not sure this is an issue of Undertow or Quarkus. 

The complete codes is [here](https://github.com/hantsy/quarkus-sandbox/blob/master/spring-post-service/).

**Comment by geoand** [comment]
I should not that this doesn't have to do with the Spring code, the same result can be seen if one uses the following JAX-RS Resource:

```
@Path("/other")
public class OtherResource {

	private static final String message = "λαθος";

	@GET
	public void respond(@Context HttpServletResponse response) throws IOException {
		PrintWriter out = response.getWriter();
		response.setCharacterEncoding("UTF-8");
		response.setContentType("application/json");
		response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
		out.write("{\"message\":\"" + message + "\"}");
		out.flush();
	}
}
```

**Comment by jaikiran** [comment]
Hello @geoand, the Servlet spec dictates that once the `HttpServletResponse#getWriter()` is called, any calls to `HttpServletResponse#setCharacterEncoding()` will have no effect on the response's character encoding. 

In this above example, if you switch the calls to `getWriter` and `setCharacterEncoding`, I think you should start seeing the use of `UTF-8` as the response's encoding.

There are other ways to set this up too (for example at the servlet context level itself so that it's applicable to all responses). But at least in this example, I think switching the order of those calls should get it to use `UTF-8`.

**Comment by geoand** [comment]
@jaikiran Excellent, thank you very much once again for this great piece of information!

I indeed verified it and it works. So I will go ahead and close this issue.

**Comment by hantsy** [comment]
@jaikiran  Thanks for your explanation. Just verified. it and got it work.
