### ISSUE TITLE
TikaProcessorTest should use Quarkus test framework

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#5700]
**Describe the bug**
In order to get #5387 to pass, I had to add code to `TikaProcessorTest` to handle setup and tear down of the configuration.  But it would probably be better to let the Quarkus test framework code do that instead.

**Comment by gsmet** [comment]
@machi1990 could you have a look at that one once David's PR is in?

**Comment by machi1990** [comment]
@gsmet @dmlloyd sure.
