### ISSUE TITLE
Health support for 50% of the relevant extensions

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5701]
We have some extensions that did the integration, we need to get to a 50% coverage.

- Health: there is already three PRs covering extension health check, so soon Kafka, Neo4j, Mongo, Kafka-stream and Artemis will all have an health check.
- Metrics: there is one PR for the infrastructure plus some metrics for Agroal.

Hey @loicmathieu can you point to the relevant PRs from here?

**Comment by loicmathieu** [comment]
Here are the corresponding PRs, almost all are waiting feedback :)

**Health** 

- Kafka, Neo4j, Mongo: #5222 
- KafkaStream: #5125
- Artemis: #5052

**Metrics**

- Extension metrics infrastructure + Agroal metrics: #5272

**Comment by jmartisk** [comment]
I'm planning to do Vert.x metrics after the basic infrastructure is merged, then possibly Reactive Messaging (where it will need to be implemented in SmallRye first) or whatever else. If there are any "preferred" extensions that should have higher priority, please speak up

**Comment by loicmathieu** [comment]
@jmartisk 

For metrics, what I would love the have is:
- metrics for the external components: database (agroal, mongdb, ...), rest client, output messages (kafka, AMQP, ...)
- metrics for the calls of the application: jax-rs calls, input messages, ...

By this I can understand who my application are calls and respond to these calls, and how the external systems I'm connected with responds.

In my current applications, I add `@Timed` and `@Counted` on all my rest endpoint operations. I was thinking creating an interceptor for this.
Again, I think this should be disabled by default as it's a user choice of what he want to measure ...

**Comment by jmartisk** [comment]
@loicmathieu I changed my mind and now agree that metrics from extensions should be disabled by default, I updated https://github.com/quarkusio/quarkus/pull/5272 with it
Btw if you are missing metrics generated for JAX-RS endpoints, there is ongoing effort in MP Metrics to standardize this (https://github.com/eclipse/microprofile-metrics/issues/293) so in this case we might want to wait how this goes before implementing it ourselves.

**Comment by paulrobinson** [comment]
@emmanuelbernard are we ready to assign a person to this Epic?

**Comment by paulrobinson** [comment]
@emmanuelbernard also, is it 50% or 80% coverage that we seek? There seems to be an inconsistency between the title and the first sentence of the description.

**Comment by emmanuelbernard** [comment]
Jan has been leading the charge and Loic has been involved too

**Comment by paulrobinson** [comment]
I've assigned to @jmartisk based on the definition of Epic lead/assignee here: https://github.com/quarkusio/quarkus/wiki/High-Level-Planning-Process#ive-been-assigned-an-epic-what-do-i-need-to-do.

Any linked sub-issues would be assigned to whoever is responsible for that part of the work. It sounds like that is where @loicmathieu would become assignee.

**Comment by jmartisk** [comment]
I would suggest splitting this into two, one for Metrics and one for Health, as they are quite separate, and create new descriptions based on the recommended template. I also assume that I will be the main assignee for Metrics and Loïc for Health. Does that sound good? If so, I will create a new epic for Metrics, I'd like to have the permission to keep the description up to date without having to bother Emmanuel all the time with it, I currently can't do that.

**Comment by jmartisk** [comment]
I filed https://github.com/quarkusio/quarkus/issues/6196 as a tracker for metrics work and will keep the description up to date

**Comment by paulrobinson** [comment]
Thanks @jmartisk. I've updated the names of the issues to reflect the breaking up and to keep them consistent.

**Comment by jmartisk** [comment]
Health seems to be done for these extensions:
- Agroal
- Kafka Streams
- Kafka Client
- Artemis Core
- MongoDB Client
- Neo4j

The title says '50 % of the relevant extensions', not sure which exactly could be considered relevant, but I'd say we've probably accomplished that number. How about we close this epic as done, and open new issues once we decide to do this for another extension? There hasn't been much activity here lately anyway.
I'm planning to do the same for the Metrics epic once I finish just a few more extensions.
