### ISSUE TITLE
Guide to help people convert Spring knowledge into Quarkus one

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5712]
You do feature X n Spring,a nd you do it with Y in Quarkus and it's equaly awesome if not better ;) Something like that.
It's really a whitepaper kind of things for users to realize how similar the models are and that converting knowledge is doable.

**Comment by geoand** [comment]
Cool!

cc @jclingan

**Comment by geoand** [comment]
cc @cmoulliard

**Comment by cmoulliard** [comment]
We have discussed with @geoand  today what we should do around to convert or migrate a Spring(Boot) application to Quarkus.

As developing a migration tool will take time, will be difficult to maintain (excepted if it becomes part of a tool such as Windup), then we need a Guide explaining :

- How to develop a Spring application on Quarkus
- What is the migration path to follow to Spring Boot to Quarkus
- What are the Spring Modules proposed and their Quiarkus equivalent
- What are the supported Spring annotations, what they do, ...
- Table documenting the spring versions supported/Quarkus release
...

**Comment by emmanuelbernard** [comment]
We can do all that but the feedback we got from people exploring Quarkus was specifically to show the equivalent tech in the Quarkus ecosystem.
For example, to do metrics or health you do it this way in Spring and that way in Quarkus.
Some are fine to move as long as they are shown a path.

It's sort of a whitepaper to show the similarity and coverage we have technology wise.

Let's open a separate issue for a "Writing a Spring app on Quarkus guide".

**Comment by geoand** [comment]
I like the whitepaper style idea and I think it ties in nicely with what @jclingan already has

**Comment by geoand** [comment]
@jclingan have you thought how this guide should look?

**Comment by murphye** [comment]
Please see my email I sent on the internal dev mailing list "Spring Boot to Quarkus Guide: Need a Sidekick to Complete". 

I am already working on something like this based on the old version of Petclinic. As stated in the email, I could use some help, even though I have most of the hard work completed (app about 80% converted). Converting an older MVC with Thymeleaf application is much harder than a newer Spring REST app. Also there are a lot of ancillary things like Cache, JaCoCo, solid unit testing, etc.

**Comment by sirAlexander** [comment]
We use Spring webflux  and are interested in quarkus but 'mutiny' still looks and feels very alien to me. How about an example around migrating from webflux to quarkus including native builds.

**Comment by geoand** [comment]
Sounds look a good idea! 

cc @cescoffier @jclingan

**Comment by cescoffier** [comment]
WebFlux comes with a router model that is close to _reactive routes_. Unfortunately, the Mutiny integration in this area is a bit behind.

**Comment by cescoffier** [comment]
@geoand we should revisit this with RESTEasy Reactive. Also, we may want to improve the router model.

**Comment by geoand** [comment]
Good idea

**Comment by geoand** [comment]
I am going to close this as @edeandrea's resource (which is coming soon) covers all topics a Spring developer would want to know to Quarkus

**Comment by edeandrea** [comment]
It should be out mid-end of August. I'll post a link back here once it's out.
