### ISSUE TITLE
Proposal: vertx.http.security FORM auth: Make redirect to fixed landing page after login optional

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#5728]
I am beginning to learn [Vue.js](https://vuejs.org/) web app programming with [AXIOS](https://vuejs.org/v2/cookbook/using-axios-to-consume-apis.html) library to talk to my backend.

I want to programmatically do a form auth POST request (j_security_check, ``` `j_username=`+user+`&j_password=`+password``` etc.) from my web app running in user's browser to my Quarkus backend, receive a ```quarkus-credential``` cookie and go on with calling REST endpoints with that cookie.

it works fine, but since there is no page to go back to - because I directly call ```/j_security_check``` to do the login, Quarkus redirects me to ```quarkus.http.auth.form.landing-page``` just after login.  

It creates a problem to me: If the Quarkus was the actual server serving the Vue web app, the redirect after successful login would be merely superfluous, but when I run Vue app in live dev mode via [Express / Node](https://expressjs.com/) e.g. on http://localhost:8080 and Quarkus backend also in live :dev mode e.g. on http://localhost:8098, the forced redirect to e.g. http://localhost:8098 or http://localhost:8098/whateverlanding manifests as a routing error I would have to somehow workaround in Axios. Note that cors is setup for me just fine in the Express dev mode.

Being able to edit both the frontend Vue web app code and the backend Quarkus code live without any interruptions is so powerful experience I definitely don't want to give it up.

### Code
e.g. backed-api.js:
```js
import axios from 'axios'
const AXIOS = axios.create({
    baseURL: `/`,
});
export default {
    getSecured(user, password) {
        console.log("Entering get secured...");
        return AXIOS.post(`/api/j_security_check`, `j_username=`+user+`&j_password=`+password,
            withCredentials: true,
            redirect: "manual",   // does not help in browser...
            maxRedirects: 0
       });
    }
}
```

vue.config.js:

```js
module.exports = {
  devServer: {
    proxy: {
      '^/api': {
        target: 'http://localhost:8098',
        ws: true,
        changeOrigin: true
      }
    }
  },
  outputDir: 'target/dist',
  assetsDir: 'static'
};
```
### Browser debug console on login
What is happening by default with  ```quarkus.http.auth.form.landing-page=/```:
![bad](https://user-images.githubusercontent.com/691097/69494645-6dfb9200-0ebe-11ea-9618-8a7ee8167480.png)
 
# Proposal
I propose to introduce an opt-out from that redirect:

```
/**
 * Option to disable redirect to landingPage if there is no saved 
 * page to redirect back to. Form Auth POST is followed
 * by redirect to landingPage by default.
 */
@ConfigItem(defaultValue = "true")
public boolean redirectAfterLogin;
``` 
### Browser debug console on login
What is happening with the new ```quarkus.http.auth.form.redirect-after-login=false```:
![good](https://user-images.githubusercontent.com/691097/69494668-cd59a200-0ebe-11ea-8bb3-0ca61b77afdb.png)

# WDYT?

Is the redirect to  ```quarkus.http.auth.form.landing-page``` if there was no page to go back to necessary? Is there any security or spec concern bout it? Would it be O.K. to allow for an opt-out option such as ```quarkus.http.auth.form.redirect-after-login=false``` or something like if ```quarkus.http.auth.form.landing-page=``` (empty) then effectively do  ```quarkus.http.auth.form.redirect-after-login=false```  ?

**Comment by sberyozkin** [comment]
CC @stuartwdouglas

**Comment by Karm** [comment]
Merged. Closing.
