### ISSUE TITLE
How to set correctly ssl certificate oauth2

### ISSUE THREAD

**Issue by majonga88** [quarkusio/quarkus#5731]
Hi folks,

I'm trying to use oauth2 following this guide : https://quarkus.io/guides/security-oauth2 and also https://quarkus.io/guides/native-and-ssl

In application.properties, i use for the `quarkus.oauth2.introspection-url` an **https** adress ([auth0](https://auth0.com/)).

When i execute these commands separatly : 

```
./mvnw compile quarkus:dev
./mvnw clean install -Pnative 
```

I getting this error : 
> Caused by: java.lang.IllegalArgumentException: Parameter 'sslContext' may not be null

The complete stacktrace : [error-log.txt](https://github.com/quarkusio/quarkus/files/3884061/error-log.txt)

I use graalVM, the `GRAALVM_HOME` is set and the certificate of auth0 is added to the truststore of graalVM, follwing these commands :

```
echo | openssl s_client -servername NAME -connect HOST:PORT |\
  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > certificate.crt

/home/xerxes/graalvm-ce-19.2.1/bin/keytool -import -alias auth0 -storepass 'changeit' -keystore /home/xerxes/graalvm-ce-19.2.1/jre/lib/security/cacerts -file certificate.crt
```
I check with this command `keytool -list -v -keystore /home/xerxes/graalvm-ce-19.2.1/jre/lib/security/cacerts`, i have my certificate in there.

Could you explain me what i missed in my steps ?

I saw this option `quarkus.oauth2.ca-cert-file` but i don't know very well how to use it.

Thank you so much guys for your help !

**Comment by gsmet** [comment]
@loicmathieu @sberyozkin could you answer?

**Comment by loicmathieu** [comment]
The configuration property `quarkus.oauth2.ca-cert-file` cannot be used inside a native build at the moment. There is some limitation on native for SSL/TLS.

Regaring your error, it appears that you set it, that's why the build crash.

You must follow the native guide to integrate your certificate inside your SSL truststore and be sure to remove the `quarkus.oauth2.ca-cert-file` config property.

**Comment by majonga88** [comment]
> You must follow the native guide to integrate your certificate inside your SSL truststore and be sure to remove the quarkus.oauth2.ca-cert-file config property.

@loicmathieu Thank you to reply to me, i do these actions before i build the native image, i remove quarkus.oauth2.ca-cert-file on my application.properties and i add the truststore on my graalVM following these commands : 

```
echo | openssl s_client -servername NAME -connect HOST:PORT |\
  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > certificate.crt

/home/xerxes/graalvm-ce-19.2.1/bin/keytool -import -alias auth0 -storepass 'changeit' -keystore /home/xerxes/graalvm-ce-19.2.1/jre/lib/security/cacerts -file certificate.crt
```

**Comment by loicmathieu** [comment]
I think there is a bug, in case you build to native and use an HTTPS endpoint, the `OAuth2IntrospectValidator` that we use under the hood expect to have an sslContext but we didn't provides one in case there is no ca-cert-file.

I re-qualify the issue as bug and will work on it.

**Comment by majonga88** [comment]
Ok thanks a lot @loicmathieu
