### ISSUE TITLE
doc that overrides are only available when you have set the property in application.properties

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5735]
**Describe the bug**
https://quarkus.io/guides/config does not seem to mention that to do overrides via e.g. QUARKUS_HTTP_PORT you *must* have put it in `application.properties`

we should make sure that is highlighted/documented.

**Comment by machi1990** [comment]
I think with this PR https://github.com/quarkusio/quarkus/pull/5387 in (milestoned 1.1.0), it should be possible to override runtime properties even if they are not set in `application.properties`. 
/cc @dmlloyd

**Comment by maxandersen** [comment]
yes, but until that is mainstream it would be worth at least noting on the config guide.

**Comment by dmlloyd** [comment]
The notes in the guide would become mainstream at the same time that the code change does, wouldn't they?

**Comment by maxandersen** [comment]
are you saying we can't release updates to the guide before 1.1 is out ?

**Comment by dmlloyd** [comment]
I don't know, I'm asking!

**Comment by geoand** [comment]
This seems very far out of date, so I am going to close it
