### ISSUE TITLE
resteasy-jsonb and artemis-jms don't work together

### ISSUE THREAD

**Issue by sthiessen23** [quarkusio/quarkus#5739]
**Describe the bug**
When using the dependencies for resteasy-jsonb and artemis-jms together,  jsonb does not work anymore.

An error is thrown:
ERROR: HTTP Request to /legumes failed, error id: 5f10e2db-31d3-4c64-9caf-6d079d1b0c22-1
org.jboss.resteasy.spi.UnhandledException: javax.ws.rs.ProcessingException: RESTEASY008205: JSON Binding serialization error java.lang.NoSuchMethodError: 'javax.json.stream.JsonGenerator javax.json.stream.JsonGenerator.writeKey(java.lang.String)'
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:587)
...
**To Reproduce**

1. Add the artemis-jms dependency to the rest-json-quickstart 
2. Tests no longer work because of a json error

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Microsoft Windows [Version 10.0.18362.449]
 - Output of `java -version`: openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Corretto-11.0.3.7.1 (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.3.7.1 (build 11.0.3+7-LTS, mixed mode)

 - Quarkus version or git rev: 1.0.0.CR2

**Comment by gsmet** [comment]
@middagj  any chance you could have a look at that one?

**Comment by middagj** [comment]
Sure, no problem. This sounds like the issue I also encounter in commit cd312d32 which is part of #5052. Artemis uses a different JSON-P library which sometimes gets loaded before the one of Quarkus.

**Comment by middagj** [comment]
When using latest master with #5052 merged in it, and of course added the mandatory `quarkus.artemis.url` property, the tests work again.

**Comment by gsmet** [comment]
Cool, thanks for checking!
