### ISSUE TITLE
Panache: provide "final" for public entity properties

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#5754]
**Description**
With Panache, we can omit getters/setters for our entities. According to quarkus docs, encapsulation is done by generating appropriate getters/setters and overwriting all field accesses located outside of the class to property access. Inside the class, field access is still used. 

**Normally, Hibernate does not allow final field properties.** Maybe Panache can rewrite those "final" fields to normal private fields with only a getter (and omitting the generating of setter). With this, Panache can imitate finalized entity properties.

```
@Entity
public class Person extends PanacheEntity {

    // Hibernate does not allow final fields.
    // Maybe Panache can remove the final-keyword 
    // and generate only a getter on compile time.
    public final String name;
    public final LocalDate birth;
}
```

**Implementation ideas**
If panache detects `final`-keywords on entity properties, it can remove the `final`-keyword and generates only a getter on compile time and omitting the setter. Does this makes sense?

**Comment by emmanuelbernard** [comment]
I'm unclear what would be reason for some to write his entity as final if it knows it will be written by Hibernate down the line? I'm not saying it's good/bad, but I'm not sure of the train of thoughts

**Comment by nimo23** [comment]
I was thinking about having an entity with finalized properties through all layers and not only on ORM-level (which could be achieved by `org.hibernate.annotations.Immutable` or `read-only` entityManager). 

For example:

// the properties of a user entity cannot be changed after it was created
```
@Entity
@Builder
@Getter
class User {
    private final name;
   // other finalized props ...
}
```

Such _finalized entities_ can be similar to a Java Records (JEP 359) and the ORM (or Panache) can make some improvements of such _finalized entites_. For example, the improvements described in https://github.com/quarkusio/quarkus/issues/6095 with read-only-entities and entities without side effects..

But I think I will close this issue..actually, I am also unsure about the usefulness..
