### ISSUE TITLE
can not run example 

### ISSUE THREAD

**Issue by cnmade** [quarkusio/quarkus#5760]
command 
```
.\mvnw compile quarkus:dev
```

error log
```
错误: 找不到或无法加载主类 io.quarkus.dev.DevModeMain
原因: java.lang.ClassNotFoundException: io.quarkus.dev.DevModeMain
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.438 s
[INFO] Finished at: 2019-11-26T09:33:42+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by jaikiran** [comment]
Is this using Java 13 (and Windows)? If yes, then there's a known issue with that combination https://github.com/quarkusio/quarkus/issues/5359. You can use Java 8 (or even Java 11 I guess) for now, till we come up with a fix for that on Java 13 (there are some ongoing discussions about it).

**Comment by geoand** [comment]
Which example are we talking about?

**Comment by geoand** [comment]
This is very old now and since we don't have enough information, I'll close it
