### ISSUE TITLE
REST invocation with AdmissionReview fabric8 object via jackson fails in native image

### ISSUE THREAD

**Issue by simongun** [quarkusio/quarkus#5764]
**Describe the bug**
The attached web service using a fabric8 model object, and jackson for marshalling, works fine when invoked through a (provided) test case when running in the normal openJDK 1.8.
If compiled into a native image, no error is logged when invoked, but the code (including its own logging statements) are not executed.
Also, if we replace quarkus-resteasy-jackson with the quarkus-resteasy-jsonb, an invocation is attempted, but it (understandably) fails due to marshalling issues; but it is interesting to mention because it shows that the code invocation basically would work, and it actually does, if we avoid unmarshalling the payload and expect a (json) string.

[admissionreviewjackson.zip](https://github.com/quarkusio/quarkus/files/3891657/admissionreviewjackson.zip)

**Expected behavior**
The provided code should work both in openJDK and graalVM as native image.

**Actual behavior**
See above, it fails to be invoked in a native Image.

**To Reproduce**
1. maven package the attached code. This will execute a test case demonstrating the successful invocation
2. build a native image and point the restassured test towards it --> no invocation will be logged.

**Configuration**
```properties
# Add your application.properties here, if applicable.
See attachment.

**Environment (please complete the following information):**
 - Output of `java -version`: build 1.8.0_131-b11
 - GraalVM version (if different from Java): 19.2.1
 - Quarkus version or git rev: 1.0.0.FINAL

**Comment by jasmdk** [comment]
I have a similar issue when accepting AdmissionReview in Rest operation.
It seems like it interprets the some of the properties to be of a wrong type 
With quarkus-resteasy-jackson:
```
com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing property &#x27;options&#x27; (expected type:
[simple type, class io.fabric8.kubernetes.api.model.HasMetadata]; actual type:
`io.fabric8.kubernetes.api.model.CreateOptions`), problem: argument type mismatch
at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 62, column: 9] (through reference chain:
io.fabric8.kubernetes.api.model.admission.AdmissionReview[&quot;request&quot;]-&gt;io.fabric8.kubernetes.api.model.admission.AdmissionRequest[&quot;options&quot;])
```
With quarkus-resteasy-jsonb:
```
javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException:
Unable to deserialize property &#x27;request&#x27; because of: Unable to deserialize property &#x27;object&#x27; because
of: Cannot infer a type for unmarshalling into: io.fabric8.kubernetes.api.model.HasMetadata
```

**Comment by geoand** [comment]
Is this still an issue with the latest Quarkus versions?
