### ISSUE TITLE
Spring's @RequestMapping params and headers attributes are not supported.

### ISSUE THREAD

**Issue by d-yosh** [quarkusio/quarkus#5766]
**Describe the bug**

Spring's `@RequestMapping` params and headers attributes are not supported.
The same applies to the following annotations.
```
@GetMapping
@PostMapping
@PutMapping
@DeleteMapping
@PatchMapping
```

For Example:

```java
@RestController
public class GreetingController {
    @GetMapping(value = "/greeting", params = "foo")
    public String foo() {
        return "foo";
    }

    @GetMapping(value = "/greeting", params = "bar")
    public String bar() {
        return "bar";
    }
}
```

**Expected behavior**
In Spring,
`/greeting?foo` -> returns "foo"
`/greeting?bar` -> returns "bar"

**Actual behavior**
In Quarkus,
`/greeting?foo` -> returns "bar"
`/greeting?bar` -> returns "bar"

**To Reproduce**
1.  Create Quarkus Project with Quarkus Extension for Spring Web API
2.  Create the controller class in the above example
3.  Start Application

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18363.476]
 - Output of `java -version`:  "1.8.0_202"
 - Quarkus version or git rev: 1.0.0.Final

**Additional context**
I think this feature is probably not possible with JAX-RS.
If so, how about writing in the following document that params and headers are not supported?
https://quarkus.io/guides/spring-web#annotations

**Comment by geoand** [comment]
Is this still the case when using the latest version of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback
