### ISSUE TITLE
Change "quarkus.hibernate-orm.datasource.default-schema" to runtime ConfigProperty

### ISSUE THREAD

**Issue by danilomagalhaes** [quarkusio/quarkus#5769]
**Describe the bug**
I'm using quarkus-hibernate-orm with oracle ojdbc. In general when using Oracle, when the schema is omitted the default schema is the username of the DataSource. Using quarkus I'm obligated to specify the "quarkus.hibernate-orm.datasource.default-schema" property becouse quarkus-hibernate don't use the username as default schema. However if I use AgroalDatasource directly the username is used as schema. Specify the schema isn't the main problema, but the fact that I CAN'T override this property using environment variable becouse the config is ConfigPhase.BUILD_TIME.

**Expected behavior**
Change the schema using environment variable.

**Actual behavior**
I currently need to specify the default schema property, but I can't override it at runtime, which eventually requires creating a Docker image by environment.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
> Linux danilo-pc 5.3.11-200.fc30.x86_64 #1 SMP Tue Nov 12 19:25:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
> java version "1.8.0_202"
> Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
> Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.0.0.Final

**Additional context**
(Add any other context about the problem here.)

**Comment by machi1990** [comment]
Related to #2933 
/cc @gsmet @Sanne

**Comment by gsmet** [comment]
Yes, I'm closing this one as a duplicate.

We really need to work on this sooner rather than later. I will talk with Sanne.

**Comment by gsmet** [comment]
Thanks for reaching out, it helps us setting our priorities straight!
