### ISSUE TITLE
undertow-handlers.conf not working anymore

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#5775]
**Describe the bug**
I used to have it add a no-index for code quarkus staging:
`not equals(%{i,Host}, "code.quarkus.io") -> header(header=X-Robots-Tag,value=noindex)`

As you can see the header is not here anymore: https://stage.code.quarkus.io

It was working for sure (but I don't know when it stopped working)..

I've made a test with a basic Quarkus project and just a request dumper in the conf:

META-INF/undertow-handlers.conf
```
dump-request
```

I doesn't work either!

**Expected behavior**
It should run specified instructions

**Actual behavior**
It doesn't do anything at all

**Environment (please complete the following information):**

 - Quarkus version or git rev: 1.0.0.Final(Add any other context about the problem here.)

**Comment by gsmet** [comment]
Do you use `quarkus-undertow`?

**Comment by ia3andy** [comment]
It's broken since `0.24.0`, `0.23.0` was working..

**Comment by ia3andy** [comment]
@gsmet I don't, could you be more precise=n

**Comment by ia3andy** [comment]
Ok adding the dependency fixed the problem. It was not required to add it in previous version..

**Comment by ia3andy** [comment]
@gsmet thanks ;-)

**Comment by gsmet** [comment]
RESTEasy was coming with Undertow before. It’s now using Vert.x by default. 

The best course of action in the long term is to rewrite that to use a Vert.x handler.
