### ISSUE TITLE
Support Kotlin DSL Gradle projects when adding/listing/removing extensions 

### ISSUE THREAD

**Issue by pschyma** [quarkusio/quarkus#5776]
**Describe the bug**
The `addExtension` gradle task does not honor kotlin DSL build files and creates instead empty groovy DSL build configuration files: `build.gradle` and `settings.gradle`.

**Expected behavior**
Adding an extension should create a new entry in the dependencies block of the existing `build.gradle.kts` file.

**Actual behavior**
Nothing is added to `build.gradle.kts`, but instead `build.gradle` and `settings.gradle` files are created.

**To Reproduce**
1. Create a new gradle kotlin DSL project
2. Add quarkus plugin
3. Execute `./gradlew addExtension --extensions="agroal"

```
**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux voyager 5.4.0-arch1-1 #1 SMP PREEMPT Mon, 25 Nov 2019 22:31:57 +0000 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 25.232-b07-jvmci-19.3-b05, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.0.0.Final

**Comment by geoand** [comment]
Currently we don't handle `build.gradle.kts` at all. It would be a nice addition.

**Comment by KaenDagger** [comment]
I would like to take this issue :)

**Comment by belu** [comment]
@kaenlupus Any progress on this?

**Comment by kaenlupus** [comment]
Unfortunately, no. We have to deal with other Kotlin stuff and support. Kotlin is still in  experimental phase. Trying to improve the support
