### ISSUE TITLE
quarkusDev task fails with "Unable to find quarkus-gradle-plugin dependency"

### ISSUE THREAD

**Issue by acoburn** [quarkusio/quarkus#5781]
**Describe the bug**

When using gradle with quarkus 1.0.0.Final, the `quarkusDev` task fails with this error:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':trellis-quarkus:quarkusDev'.
...
Caused by: org.gradle.api.GradleException: Failed to run
        at io.quarkus.gradle.tasks.QuarkusDev.startDev(QuarkusDev.java:374)
...
Caused by: java.lang.IllegalStateException: Unable to find quarkus-gradle-plugin dependency
        at io.quarkus.gradle.tasks.QuarkusDev.lambda$addGradlePluginDeps$2(QuarkusDev.java:403)
        at io.quarkus.gradle.tasks.QuarkusDev.addGradlePluginDeps(QuarkusDev.java:403)
        at io.quarkus.gradle.tasks.QuarkusDev.startDev(QuarkusDev.java:256)
```

This task worked fine with quarkus 0.28.1 and earlier. (All other tasks seem to work fine)

**To Reproduce**
1. In a gradle project, add this to a build.gradle script:

```
plugins {
    id 'io.quarkus' version '1.0.0.Final'
}

apply plugin: 'io.quarkus'
```

2. Run `./gradlew quarkusDev`

**Environment (please complete the following information):**

 - Output of `java -version`: java version "11.0.4" 2019-07-16 LTS
 - Quarkus version or git rev: 1.0.0.Final

**Additional context**
I am able to work around this issue by adding the following to the build script, though it seems like a bit of a hack:

```
quarkusDev {
    doFirst {
        project.buildscript.repositories.gradlePluginPortal()
        project.buildscript.dependencies.add('classpath', "io.quarkus:quarkus-gradle-plugin:$quarkusVersion")
    }
}
```

**Comment by mklueh** [comment]
I´m facing the same issue with my multi module project when applying the plugin in the modules build.gradle (not in the root build.gradle)

`apply plugin: 'io.quarkus' `

**Using the "plugins" closure however within the build.gradle of my modules with version 1.1.0-Final is working**

```
plugins {
   id 'io.quarkus'
}
```

**Comment by acoburn** [comment]
Using this formulation:
```
plugins {
    id 'io.quarkus'
}
```
works with version 1.2.0.

**Comment by ssindelar** [comment]
I have the same issue but can't get it to work.

I tried different combinations of plugins/apply plugin und placement (root/modules/both) and always get the same error.

**Comment by gsmet** [comment]
@ssindelar please open another issue with a reproducer.

Thanks!

**Comment by dante-ricalde** [comment]
solved adding this buildscript in child build.gradle with version 1.3.2.Final

buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.quarkus:io.quarkus.gradle.plugin:$quarkusPluginVersion"
    }
}

**Comment by Legionarks** [comment]
> solved adding this buildscript in child build.gradle with version 1.3.2.Final
> 
> buildscript {
> repositories {
> gradlePluginPortal()
> }
> dependencies {
> classpath "io.quarkus:io.quarkus.gradle.plugin:$quarkusPluginVersion"
> }
> }

it worked for me. I'm also trying to build a multi-module project and finally I could find a solution
