### ISSUE TITLE
quarkus starters: archetype for eclipse 

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#5784]
**Description**
There are no official simple quarkus starter in Eclipse. 
![quarkus-archetype](https://user-images.githubusercontent.com/3045549/69675930-0735ce80-10a0-11ea-8480-fa59fdad1c55.png)
 Maven archetype:

**Implementation ideas**
Maybe archetypes can be added to a catalog (Maven Central or RedHat).

**Comment by gsmet** [comment]
Thanks for starting this conversation.

We don't have archetypes for simple projects: the projects are created using a Maven command from our Quarkus Maven plugin.

You can either:
- use https://code.quarkus.io/ to generate your project and then import it in Eclipse
- use the Maven command line and import it to Eclipse
- Eclipse tooling for Quarkus is coming based on the work done for VSCode: https://quarkus.io/blog/vscode-quarkus-1.2.0/

We won't add archetypes so closing this one.
