### ISSUE TITLE
NullPointerException if `quarkus.http.ssl.cipher-suites` is missing

### ISSUE THREAD

**Issue by wicksim** [quarkusio/quarkus#5790]
**Describe the bug**
When providing a SSL-keystore, I'm getting a `NullPointerException`:

> 
> 09:35:12,805 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.RuntimeException: java.lang.NullPointerException
> 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServerAfterFailedStart(VertxHttpRecorder.java:132)
> 	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup.handleFailedInitialStart(VertxHotReplacementSetup.java:30)
> 	at io.quarkus.dev.RuntimeUpdatesProcessor.startupFailed(RuntimeUpdatesProcessor.java:449)
> 	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:191)
> 	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
> 	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
> Caused by: java.lang.NullPointerException
> 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.createSslOptions(VertxHttpRecorder.java:343)
> 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:220)
> 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServerAfterFailedStart(VertxHttpRecorder.java:124)
> 	... 5 more

Quarkus is trying to read cipher-suites, but the config seems to be null. Documentation (https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.ssl.cipher-suites) is confusing, because description says "If none is given, a reasonable default is selected", but in default value there is a "required"-flag.

**Expected behavior**
I don't have to provide cipher-suites manually, quarkus should choose for me. Or at least there should be an easy-to-read exception.

**Actual behavior**
I need to provide a suitable cipher-suite.

**To Reproduce**
1. Use quickstart-example
2. Add keystore-configuration
3. Start in Dev-mode

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.ssl.certificate.key-store-file=keystore.jks
quarkus.http.ssl.certificate.key-store-password=password
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17763.805]
 - Output of `java -version`: ```java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.0.0.Final

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
Thanks for reporting this. I think the issue is already fixed in master.

In 1.0, we have:
https://github.com/quarkusio/quarkus/blob/1.0/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L343

In master, we have:
https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L359

So it should be safe.

**Comment by wicksim** [comment]
Thanks for your fast reply. I'll close this issue.
