### ISSUE TITLE
NPE is thrown with a Spring Web Controller contains a @PostConstruct annotation

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#5791]

**Comment by geoand** [comment]
This RESTEasy [PR](https://github.com/resteasy/Resteasy/pull/2233) should fix the problem.

**Comment by rsvoboda** [comment]
PR is in https://github.com/resteasy/Resteasy/commits/4.4.2.Final
Master now uses 4.4.2.Final

Can be this issue closed ?

**Comment by geoand** [comment]
Has been fixed in RESTEasy
