### ISSUE TITLE
Alpine Linux based GraalVM Docker image

### ISSUE THREAD

**Issue by fatih-erdem** [quarkusio/quarkus#5798]
Hey, I want to use GraalVM but not the native image, just normal JIT mode. 

I was searching for a Docker image for GraalVM and I saw the official one. https://hub.docker.com/r/oracle/graalvm-ce/tags

The problem is Docker image's size is about 450 MB. But for OpenJDK, I could find a Docker image based on Alpine Linux and size is around 50 MB.

Is there any plan to create the GraalVM Docker image based on Alpine Linux instead of Oracle Linux?

**Comment by yuhaibohotmail** [comment]
Please refer to this：
[](https://itaffinity.wordpress.com/2019/05/16/graal-native-images-quarkus-micronaut-helidon/)

**Comment by fatih-erdem** [comment]
@yuhaibohotmail Unfortunately, I could only see native image related Docker images in the link. I was looking for `alpine-jre` but for GraalVM.

**Comment by fatih-erdem** [comment]
And I think I should have created this issue in the GraalVM issue tracker, not the Quarkus. I am closing. the issue. Sorry for inconvenience.
