### ISSUE TITLE
@PostConstruct and Kotlin init not working in @ApplicationScoped Bean

### ISSUE THREAD

**Issue by qiuzhanghua** [quarkusio/quarkus#5799]
**Describe the bug**
(Describe the problem clearly and concisely.)
I create a gradle project with vert.x, vert.x web and kotlin, and define a bean of 
@ApplicationScoped named Server. [https://github.com/qiuzhanghua/code-with-quarkus](https://github.com/qiuzhanghua/code-with-quarkus)

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Server.kt should work as a TCP Server

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
Server.kt not initialized?

**To Reproduce**
1.  gradle quarkusDev
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 Darwin q.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009173705.graal.jdk8u-src-tar-gz-b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
1.0.0.Final

**Additional context**
(Add any other context about the problem here.)

**Comment by qiuzhanghua** [comment]
Perhaps my question is:

How do I force an application-scoped bean to instantiate at application startup?

and even I try to add @Startup, it does not work.

**Comment by qiuzhanghua** [comment]
and I try 
https://stackoverflow.com/questions/3600534/how-do-i-force-an-application-scoped-bean-to-instantiate-at-application-startup
It does not work.

**Comment by gsmet** [comment]
@mkouba @manovotn  could you please have a look? It looks more like a CDI usage question than a real Kotlin-related issue.

**Comment by qiuzhanghua** [comment]
I also think it is a CDI usage question. 
please see:
https://github.com/qiuzhanghua/code-with-quarkus/blob/master/src/main/kotlin/com/example/MyApplicationLifecycle.kt

I try to use another method, but I don't know how to do.

**Comment by mkouba** [comment]
Hi @qiuzhanghua, in quarkus your app should observe a `StartupEvent` as described in the guide: https://quarkus.io/guides/lifecycle. The difference from `@Initialized(ApplicationScoped.class)` is also described there: https://quarkus.io/guides/lifecycle#what-is-the-difference-from-initializedapplicationscoped-class-and-destroyedapplicationscoped-class.

Anything `javax.ejb` would not work.

**Comment by qiuzhanghua** [comment]
But how can I use StartupEvent to get All Singlton/ApplicationScope beans such as Vertx, and force it initialized? could you have a sample? Thanks!

**Comment by mkouba** [comment]
There is no easy way to initialize all singleton/`@ApplicationScoped` beans and in fact, you should not do this because the bean may not be designed in this way. However, you can easily initialize a specific bean like this:

```java
void onStart(@Observes StartupEvent ev, MySingleton singleton, MyAppScopedBean bean) {               
   // For singleton injection is enough
   // For @ApplicationScoped beans a client proxy is injected and so we need to invoke some method to force bean instantiation
   bean.toString();  
}
```

**Comment by manovotn** [comment]
> But how can I use StartupEvent to get All Singlton/ApplicationScope beans such as Vertx, and force it initialized? could you have a sample? Thanks!

By design, bean initialization is lazy. In order to enforce creation, you would need to invoke any method defined on the bean (and not just the proxy). That means any bussiness logic or `toString()` like Martin says because those are always delegated to contextual instance (that's defined by CDI spec).
Otherwise, if you do have control over those beans, you can also add a noop observer for the aforementioned `StartupEvent` to every single bean - that will trigger bean creation before delivering the event.

**Comment by qiuzhanghua** [comment]
It works now. Thanks @manovotn. Please see https://github.com/qiuzhanghua/code-with-quarkus/blob/master/src/main/kotlin/com/example/Server.kt and https://github.com/qiuzhanghua/code-with-quarkus/blob/master/src/main/kotlin/com/example/MyApplicationLifecycle.kt .

But I don't know why kotlin init run two times.

**Comment by qiuzhanghua** [comment]
And when I build as native, kotlin init run **one** time.

Thanks anyway! @manovotn

**Comment by manovotn** [comment]
> But I don't know why kotlin init run two times.

What do you mean by that? Does the observer get notified twice?

**Comment by mkouba** [comment]
> But I don't know why kotlin init run two times.

If I understand it correctly the kotlin init is called after the constructor. And because `Server` is `@ApplicationScoped` the constructor is invoked twice - once for client proxy and once for bean instance. This is expected behavior.

> And when I build as native, kotlin init run one time.

That's weird though.

**Comment by manovotn** [comment]
Ah you meant Kotlin init block (had to Google that since I don't use Kotlin usually).
It's really weird that it gets invoked differently in dev mode and in native though...

**Comment by qiuzhanghua** [comment]
Yes , that's weird.
I recheck it on another computer,  "in static init" appears twice if I use *-runner.jar, "in static init" appears only once if I run native code.

Thanks anyway! @manovotn @mkouba
