### ISSUE TITLE
Hashicorp Consul integration

### ISSUE THREAD

**Issue by cadu-goncalves** [quarkusio/quarkus#5802]
**Hashicorp Consul integration**
Nice to have integration with [Consul](https://www.consul.io)

**Comment by cadu-goncalves** [comment]
In a recent research I realized that **Quarkus** already provides **Consul** integration, throught **Apache Camel**.

Specifically for Service Registry **Camel** provides the component [Service Registry](https://camel.apache.org/manual/latest/service-registry.html) and also a direct [Consul Component](https://camel.apache.org/components/latest/consul-component.html) for other integrations (KV store, etc)

I don't know how much "sugar" could be built around it, but it seems that this request does not apply, since the integration is already there. 

Amazing framework!

**Comment by Imaclean74** [comment]
Thanks @cadu-goncalves . Some examples would be useful.  I'm just taking a look at the Camel integration now - but it's not immediately obvious how to use it. I already have service registration working - using the vertx-consul client directly from AppLifecycleBean.onStart() https://vertx.io/docs/vertx-consul-client/java/.  Which is fine - but it would be nice to have a more integrated declarative approach.

The micronaut integration, by contrast, allows you to enable registration via a config setting and then use the below annotation syntax to discover service instances :

```
@Client(id = "bookinventory") 
interface BookInventoryClient extends BookInventoryOperations {
```
https://guides.micronaut.io/micronaut-microservices-services-discover-consul/guide/index.html

**Comment by gastaldi** [comment]
@cescoffier I may be missing something, but isn't that already accomplished by Stork?

**Comment by cescoffier** [comment]
@gastaldi Stork uses the "service" part of Consul.  We also have consul-config which resolve the Quarkus (runtime_ config from Consul. However, we do not have a managed "low-level all-purpose" consul client. 

We have a client (the Vert.x Mutiny one), which is used by Stork and the config source. But it's not managed. It would be a nice quarkiverse extension.

**Comment by pjgg** [comment]
Related to: https://quarkiverse.github.io/quarkiverse-docs/quarkus-config-extensions/dev/consul.html

**Comment by geoand** [comment]
Closing as we have a [Quarkiverse](https://docs.quarkiverse.io/quarkus-config-extensions/dev/consul.html) extension for this.

**Comment by cescoffier** [comment]
And we have Stork integration too.
