### ISSUE TITLE
Instructions to test gradle plugin

### ISSUE THREAD

**Issue by tobad357** [quarkusio/quarkus#5804]
**Describe the bug**
There are no instructions on how to do local development of the gradle plugin
This would be to help with #5101 

**Expected behavior**
Add a README in the devtools/gradle directory that explains how to run a local copy of the plugin

**Actual behavior**
No instructions are available

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
I would like to work on defining output annotations for the gradle plugin
This would make the plugins compatible with gradle cache

**Comment by gsmet** [comment]
@gastaldi would you be able to add some documentation about it? I suppose you already have done that?

**Comment by gastaldi** [comment]
I'm working on a refactor of the Gradle plugin to match Gradle standards: https://github.com/quarkusio/quarkus/pull/5761

I'll add this README to my TODO list

**Comment by tobad357** [comment]
@gastaldi when you are doing the refactor are you looking at adding [Gradle Up To Date](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks) checks?

**Comment by gastaldi** [comment]
@tobad357 I always thought that the plugin already did that, need the check that. Have you already identified any changes that might help?

**Comment by tobad357** [comment]
@gastaldi For me quarkusbuild I get this running with --info
```
> Task :png-integ:quarkusBuild
Caching disabled for task ':png-integ:quarkusBuild' because:
  Caching has not been enabled for the task
Task ':png-integ:quarkusBuild' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
```

```
> Task :png-integ:quarkusTestConfig
Caching disabled for task ':png-integ:quarkusTestConfig' because:
  Caching has not been enabled for the task
Task ':png-integ:quarkusTestConfig' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
```

And looking at the code no Outputs are registered
