### ISSUE TITLE
[devtools] Add Gradle Kotlin DSL as another build tool option when generating a new Quarkus projects

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#5807]
Add Gradle Kotlin DSL as another build tool option, or add a **using Kotlin DSL** checkbox when Gradle is selected.

**Comment by ia3andy** [comment]
@maxandersen I think this should wait for the refactor https://github.com/quarkusio/quarkus/issues/8178 (and maybe done just after it?)

**Comment by rajatpundir** [comment]
+1

**Comment by ia3andy** [comment]
@maxandersen Would it be activated when you select Kotlin and Gradle together? Maybe you could want it without Kotlin in the code? Or would it be a plain "Gradle Kotlin" Built Tool?

The problem with the latest would be to have 2 Gradle vs 1 Maven options no?

**Comment by rajatpundir** [comment]
> @maxandersen Would it be activated when you select Kotlin and Gradle together? Maybe you could want it without Kotlin in the code? Or would it be a plain "Gradle Kotlin" Built Tool?
> 
> The problem with the latest would be to have 2 Gradle vs 1 Maven options no?

I think kotlin DSL is more elegant with a Gradle Kotlin project. That's also what Spring initializr generates by default for a gradle kotlin project, and would be good to have similar behaviour for generating new quarkus projects.

**Comment by emmanuelbernard** [comment]
Let's close this one as it's a duplicate of  #5776

**Comment by ia3andy** [comment]
@emmanuelbernard I am re-opening this one, there is a clear distinction between handling existing projects that use Gradle with Kotlin DSL (https://github.com/quarkusio/quarkus/issues/5776#event-3497676659) and generating new Quarkus project using Gradle with Kotlin DSL as a buildtool option (this one).

**Comment by ia3andy** [comment]
This option will be easy to implement when https://github.com/quarkusio/quarkus/pull/1037 gets merged

**Comment by ia3andy** [comment]
We would just need create a new Gradle buildtool Codestart strongly inspired by the Gradle one: https://github.com/ia3andy/quarkus/tree/codestarts-v0/devtools/platform-descriptor-json/src/main/resources/codestarts/base/buildtool/gradle

**Comment by Legion2** [comment]
@ia3andy #10372 was merged, what is the status of this issue?

**Comment by ia3andy** [comment]
Thanks @Legion2, yeah it's done
