### ISSUE TITLE
ComputingCache is not serializable

### ISSUE THREAD

**Issue by blxbrgld** [quarkusio/quarkus#5810]
Hello, 

we've implemented a custom **Undertow** session manager to distibute sessions but it is failing since the **HttpSessionContext listener** tries to set **ComputingCache** as an attribute but the latter is not serializable. The exception message is the following:

`Failed to set session attribute with name io.quarkus.undertow.runtime.HttpSessionContext.contextualInstances.: java.io.NotSerializableException: io.quarkus.arc.impl.ComputingCache`

Thank you.

**Comment by youngplugins** [comment]
I second this one. Can it be taken care of? Seems no problem making ComputingCache serializable.

**Comment by stuartwdouglas** [comment]
This is not intended to be serializable, marking it serialazable would likely only lead to other more subtle problems.  If you really want to use the HTTP Session I would suggest just ignoring keys that start with 'io.quarkus'.

**Comment by atzoum** [comment]
how can we ignore such keys using with undertow's session manager?

**Comment by stuartwdouglas** [comment]
The issue is about implementing a custom session manager. You just ignore
the keys in your custom code.

Stuart
