### ISSUE TITLE
Extra modules do not run on mvn package

### ISSUE THREAD

**Issue by alfredopalhares** [quarkusio/quarkus#5814]
**Describe the bug**
The project does not start properly when using `mvn clean package` the finished jar file does not execute the modules.
When using `mvn compile quarkus:dev` the projects starts as it supposed to do.

**Expected behavior**
The project should be containerized, and be able to run in standalone java jar file.

**Actual behavior**
The project launches it it does not run code, when reaching the web interface I get a "Resouce not Found" error.

**To Reproduce**
1. Take the example Dockerfile. 

```Dockerfile
FROM java-project-builder:1.5.1-OpenJDK_11 as builder

RUN mkdir -p /opt/maven/project-root
COPY . /opt/maven/project-root/
WORKDIR /opt/maven/project-root

RUN find . -type f -exec dos2unix -q {} \; \
    && mvn -q clean package

WORKDIR /opt/maven/project-root/java/quarkus/

FROM java-project-builder:1.5.1-OpenJDK_11 as runner

COPY --from=builder /opt/maven/project-root/java/quarkus/target/lib/ /opt/maven/deployments/lib/
COPY --from=builder /opt/maven/project-root/java/quarkus/target/*-runner.jar /opt/maven/deployments/app.jar

WORKDIR /opt/maven/deployments
CMD ["java", "-jar", "app.jar"]

```
2. The project has the following modules in the main `pom.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>microprofile-jee</artifactId>
        <groupId>com.myorg</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>microprofile-jee-java</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>model</module>
        <module>data</module>
        <module>business</module>
        <module>client-api</module>
        <module>quarkus</module>
        <module>webservices</module>
    </modules>

```
3. 

**Configuration**
```properties
# Logging
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}]] (%t) %s%e%n
quarkus.log.console.level=DEBUG
quarkus.log.console.color=true

# Database
quarkus.datasource.url = jdbc:postgresql://localhost:5432/user
quarkus.datasource.driver = org.postgresql.Driver
quarkus.datasource.username =
quarkus.datasource.password =
quarkus.datasource.min-size=3
quarkus.datasource.max-size=13

# Flyway minimal config properties
quarkus.flyway.migrate-at-start=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: OpenJDK 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode, sharing)
 - Output of `java -version`: 11.0.5
 - Quarkus version or git rev: 1.0.0.Final
- Apache Maven: 3.5.4

**Additional context**
I been using [sysdig](https://sysdig.com/) to reverse engineeer the `nvm compile quarkus:dev` and it all comes to this:
```
/usr/bin/java -classpath /usr/share/maven/boot/plexus-classworlds-2.5.2.jar -Dclassworlds.conf=/usr/share/maven/bin/m2.conf \
-Dmaven.home=/usr/share/maven -Dlibrary.jansi.path=/usr/share/maven/lib/jansi-native \
-Dmaven.multiModuleProjectDirectory=/opt/maven/project-root/java/quarkus org.codehaus.plexus.classworlds.launcher.Launcher quarkus:dev
```
This command works, it downloads all the dependencies and launches the project correctly, but its does not serve to package the application on docker, it would download resouces during runtime, which is not a good pratice at all. 

Any sugestions would be welcome.

**Comment by gsmet** [comment]
Does it work if you try to execute the produced jar directly i.e. outside of Docker?

**Comment by alfredopalhares** [comment]
Hello @gsmet 
> Does it work if you try to execute the produced jar directly i.e. outside of Docker?
No, the result is exactly the same :(

**Comment by alfredopalhares** [comment]
Hello,  here is a fully reproducible [project](https://github.com/lssoares/single-maven-quarkus), test with:
```
git clone https://github.com/lssoares/single-maven-quarkus 
cd single-maven-quarkus
docker build -f docker/Dockerfile -t simple-maven-quarkus:latest .
docker run -t -p 8080:8080 simple-maven-quarkus:latest
```

The docker starts and run, but if you try these 3 endpoins:
- http://localhost:8080
- http://localhost:8080/example/hello
- http://localhost:8080/swagger-ui

Only **the first** will work, if you stop docker, and then run ``mvn quarkus:dev`` the project will start and all the endpoints will work.

Any help appreciated.

**Comment by martinscmb** [comment]
Hi @alfredopalhares,

In your sequence of steps you need to add the command _mvn clean package_ before docker build:

So, now you have:
`
git clone https://github.com/lssoares/single-maven-quarkus 
cd single-maven-quarkus
mvn clean package
docker build -f docker/Dockerfile -t simple-maven-quarkus:latest .
docker run -t -p 8080:8080 simple-maven-quarkus:latest
`

Conclusions:
- With first and second endpoints everything works.

- For the third endpoint is needed to add on application properties file the following setting:
`
quarkus.swagger-ui.always-include=true
`
[See reason here...](https://github.com/quarkusio/quarkus/issues/6157)

**HOWEVER...**
When I tried with a multi-module project like this: https://github.com/martinscmb/multi-maven-quarkus all you describe happens.

When using _mvn quarkus:dev_ the projects start as it supposed to do and all endpoints work well.

To reproduce the problem:
`
git clone https://github.com/martinscmb/multi-maven-quarkus 
cd multi-maven-quarkus
mvn clean package
docker build -f docker/Dockerfile -t multi-maven-quarkus:latest .
docker run -t -p 8080:8080 multi-maven-quarkus:latest
`

The docker starts and runs, but if you try these 3 endpoints you get a web page result with **"Resource not found".**

http://localhost:8080
http://localhost:8080/examples
http://localhost:8080/swagger-ui

any help?

**Comment by radcortez** [comment]
Because you are running a multi module maven build, you need to use `mvn install` so Maven can add the project dependencies from `repository`, `service`,  `resource`, etc. to `quarkus-root`.

Since you are using `package` only, jars for each module are only going to be placed in the own module target folder. When you run `java -jar *runner`, it doesn't call the Maven reactor, so it seems fine, but then you get the erros.

For instance, if you try to call `quarkus:dev`, then you get something like:

```
[ERROR] Failed to execute goal on project quarkus-root: Could not resolve dependencies for project org.acme:quarkus-root:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.acme:repository:jar:1.0.0-SNAPSHOT, org.acme:service:jar:1.0.0-SNAPSHOT, org.acme:resource:jar:1.0.0-SNAPSHOT: Could not find artifact org.acme:repository:jar:1.0.0-SNAPSHOT -> [Help 1]
```

Because Maven is not able to pull the dependencies from your local repo, since they were not installed.

**Comment by martinscmb** [comment]
Thank you to @radcortez .

To solve the problem, the module's dependencies in _quarkus-root_ should be with **compile** scope for generating all target files correctly.

The issue can be closed.

**Comment by radcortez** [comment]
Thanks!

**Comment by n0mer** [comment]
@martinscmb do you, by any chance, know how to fix that for Gradle?

`implementation 'io.quarkus:quarkus-smallrye-openapi'` - should i substitute `implementation`with some other qualifier?

**Comment by martinscmb** [comment]
@n0mer sorry, can't help...
