### ISSUE TITLE
Take controller method into account for setting content-type in @RestControllerAdvice

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#5816]
Currently the generated `javax.ws.rs.ext.ExceptionMapper` set `application/json` as the content type of the response when the handler method of the `@RestControllerAdvice` returns an object.

This is fine for most cases, but there can be a case where the controller method needs to return say XML (which is specified in the `@RequestMapping`) then the generated `ExceptionMapper` should not force JSON.

The proper way to handle this is to include 

`@Context ResourceInfo resourceInfo` 

in generated the `ExceptionMapper` and use that to if there are any annotations on the original controller method (that threw the exception) that set the content type. 

This is a follow up from [this](https://github.com/quarkusio/quarkus/pull/5803#discussion_r351340721) discussion

**Comment by geoand** [comment]
@gytis mentioned he wants to take this one

**Comment by gytis** [comment]
While this approach makes sense, it will not align with a standard Spring Web behaviour. I've been experimenting with exception handler and found that custom content type will be returned only if a client has  added `Accept` header. Otherwise, even if a controller method has different content type, object returned by an error handler will be mapped to JSON. Here's an example that I have tried:

Controller method
```java
@GetMapping(path = "xml", produces = APPLICATION_XML_VALUE)
public Error xmlError() {
    throw new RuntimeException("xml");
}
```

Exception handler in a controller advice class
```java
@ExceptionHandler(RuntimeException.class)
public Error runtimeExceptionHandler(Throwable t) {
  return new Error(t.getMessage()); // Error is a simple POJO with a 'message' field and a getter
}
```

Test cases
```java
@Test // Passes
public void shouldGetXmlError() {
  given().accept(XML)
    .when().get("/xml")
    .then()
    .statusCode(200)
    .contentType(XML)
    .body(is("<Error><message>xml</message></Error>"));
}

@Test // Passes
public void shouldOnlyAllowAskingForXmlError() {
  given().accept(JSON)
    .when().get("/xml")
    .then()
    .statusCode(406);
}

@Test // Fails
public void shouldGetXmlErrorWithoutAsking() {
  when().get("/xml")
    .then()
    .statusCode(200)
    .contentType(XML) // Response content type is JSON
    .body(is("<Error><message>xml</message></Error>"));
}
```

**Comment by gytis** [comment]
Even though it might not be correct to look into a controller for a content type, we should definitely look into request headers before defaulting to `application/json`.

**Comment by geoand** [comment]
@gytis thanks for the detailed analysis!

I agree with your suggestions
