### ISSUE TITLE
with quarkus.http.root-path set to abc the swagger-ui is not available

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#5818]
**Describe the bug**

with quarkus.http.root-path set to abc the swagger-ui is not available

**Expected behavior**
showing the sawgger-ui by http://localhost:8080/abc/swagger-ui 

**Actual behavior**
failing with JavaScript asset not loaded exception in the browser.

**To Reproduce**
1. in application.propertes - set quarkus.http.root-path to abc
2. go by http://localhost:8080/abc/swagger-ui  in the browser
3. see the exception in the browser console

**Comment by jaikiran** [comment]
Hello @Sergey80, does http://localhost:8080/swagger-ui still work though?

**Comment by stuartwdouglas** [comment]
Does it make any difference if you set the path to "/abc/" ? I am guessing there is a missing / somewhere in our integration code.

**Comment by Sergey80** [comment]
If quarkus.http.root-path is not set then by https://localhost:8080/swagger-ui works otherwise doesn't.
As soon as tgat path has set, things start breaks. This bug, and there are others related to it. Reported before.

**Comment by jaikiran** [comment]
Which version of Quarkus is this? I haven't been able to reproduce this in a quick test against upstream master.

**Comment by gsmet** [comment]
I know we fixed some issues in this area recently.

**Comment by Sergey80** [comment]
1.0.0.CR1. i see there a new version. let me try.

**Comment by Sergey80** [comment]
same with <quarkus.version>1.0.0.Final</quarkus.version>

**Comment by jaikiran** [comment]
Hello @Sergey80, I just tested with `1.0.0.Final` and it indeed seems to be working oddly there. 

I won't be able to look more into it now, but instead of http://localhost:8080/abc/swagger-ui  can you try http://localhost:8080/abc/swagger-ui/ (notice the / at the end of the URL)? That worked for me on 1.0.0.Final.

**Comment by Sergey80** [comment]
http://localhost:8080/swagger-ui - 404

**Comment by Sergey80** [comment]
yes http://localhost:8080/abc/swagger-ui/ with that extra / works for me. thanks.

**Comment by gsmet** [comment]
I think it would probably be better to fix it as I remember we support that for some other feature. So if we can make it work, let's make it work.

**Comment by Sergey80** [comment]
at least this https://github.com/quarkusio/quarkus/issues/5494 should be fixed.
