### ISSUE TITLE
RuntimeClassLoader.findApplicationResource() does not handle the path name correctly 

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#5821]
This method is used in `getResource()` and `getResourceAsStream()` but it does not convert the path name in any way and so if you use the `/` separator in the path (as defined in those methods) it fails on windows machines because it simply walks the app directories and resolves the name against them (but system-dependent separator is used).

**Comment by mkouba** [comment]
@stuartwdouglas am I right?

**Comment by stuartwdouglas** [comment]
yes, but all this is going away soon, so I don't know if it is worth spending time on it at this stage.

**Comment by mkouba** [comment]
We can keep this issue open and verify/close it once the new CL model is in place...

**Comment by mkouba** [comment]
Hm, on the other hand, it blocks my PR: https://github.com/quarkusio/quarkus/pull/5793. So if there is a quick fix I'd vote to fix it now.

**Comment by jaikiran** [comment]
@mkouba I created https://github.com/quarkusio/quarkus/pull/5835. Would you be able to cherry-pick that one into your Qute extension PR and see if it helps?

**Comment by mkouba** [comment]
@jaikiran Of course! Let's see how it goes and if the CI is green we can close https://github.com/quarkusio/quarkus/pull/5835 and merge it as part of the https://github.com/quarkusio/quarkus/pull/5793. Thanks!

**Comment by jaikiran** [comment]
This got fixed as part of the recently merged https://github.com/quarkusio/quarkus/pull/5793. Closing.
