### ISSUE TITLE
Property handle pagination in Spring Data JPA custom queries

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#5823]
Currently pagination does not work for Spring Data JPA methods that use a custom `@Query`.
Basically an incorrect count query is generated.
The count query should be generated using the `countQuery` method of the `@Query` annotation.
This will most likely require a small change in `PanacheQueryImpl` to accept the count query (or create a subclass in the spring-data-jpa module to that will override the `count` method).

Also if no `countQuery` is specified, then the count query should probably be derived from the name of the method, as is specified in the Javadoc of `@Query`.

**Comment by geoand** [comment]
@aureamunoz mentioned that she wants to take this issue

**Comment by geoand** [comment]
@aureamunoz will you have time to get this one in for 1.1 (which is in a few days)? If not, please let me know so I can take it since it would be nice to have a fix for it.

Thanks

**Comment by uaihebert** [comment]
hello, here there is the project that reproduces this issue: 
https://github.com/uaihebert/quarkus-small-issues

If you search for ISSUE-3 in the code you will be able to find the query that is failing

**Comment by geoand** [comment]
Thanks for the link @uaihebert !

**Comment by geoand** [comment]
@aureamunoz sorry, I took this one since it's something we should really have for `1.1.0` and was unlikely to have any more time this week to help out.

@uaihebert with #6068 you should be able to get around your issue. However you will either have to explicitly add a `countQuery` to `@Query`, or make the method name something that would result in select statement that would return the proper number of elements.

**Comment by uaihebert** [comment]
@geoand thank you very much!

**Comment by geoand** [comment]
@uaihebert you are welcome!
