### ISSUE TITLE
Use of quarkus-agroal with GCP CloudSql

### ISSUE THREAD

**Issue by jtama-op** [quarkusio/quarkus#5824]
**Description**
As of now using quarkus-agroal to connect with GCP is possible but nor documented or trivial.

**Implementation ideas**
First option is to add com.google.cloud.sql:postgres-socket-factory or com.google.cloud.sql:mysql-socket-factory to the application dependencies and configuring datasource as follow : 
```properties
jdbc:postgresql:///<DB_NAME>?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=<CLOUD_SQL_INSTANCE>
```

Second option would be to add a dedicated options such as use-cloud-sql and cloud-sql-instance to  delegate the url forging to the `io.quarkus.agroal.runtime.AbstractDataSourceProducer` class. 
I don't know if we could arrange some kind of optional maven dependency to the google socket factory jar, to prevent loading unneeded jar.

I tried using both options. You can check the code for agroal extension here (https://github.com/jtama-op/quarkus/commit/eb27113c050b2c98a0ef046a84d366484adf6e21) (though it won't package due to `Dependency convergence error for com.google.http-client:google-http-client-jackson2:1.30.1`)

Anyway documenting this would be great as quarkus is great tool for deploying apps on Cloud and GCP beeing one of the top 3 provider.

**Comment by gsmet** [comment]
@jtama-op would you be up for it?

It would be nice to have a guide similar to https://quarkus.io/guides/deploying-to-azure-cloud with all the possible GCP-related issues.

The sources are there: https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc .

It doesn't need to be a big one, we can start to collect the solutions for the issues you solved.

**Comment by jtama-op** [comment]
Ok. Should I create a dedicated branch With documentation only ? Or do I add it to my master where there is also my code to modify the extension?

**Comment by gsmet** [comment]
Maybe create a PR with all you have and we can discuss from there what is better?

**Comment by jtama-op** [comment]
Please check https://github.com/quarkusio/quarkus/pull/5901 as a base for discussion
