### ISSUE TITLE
Support Bean Discovery Exclusion

### ISSUE THREAD

**Issue by norrman** [quarkusio/quarkus#5825]
When porting existing CDI applications to Quarkus, it would be good to have an exclusion mechanism that can prevent problematic Beans to be discovered. The exclusion mechanism could be the same as the one defined in the CDI 2.0 spec (chapter 12.4.2), or of similar functionality.

**Comment by geoand** [comment]
cc @mkouba @manovotn

**Comment by manovotn** [comment]
Looks like this issue got somewhat lost and forgotten, sorry for that.

I am not sure exclusion makes much sense here; it is mainly for when all classes are processed by default (`all` discovery mode). Quarkus deliberately supports only `annotated` discovery mode - only beans with [bean defining annotations (BDA)](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#bean_defining_annotations) get picked up. When porting existing app, you should be able to control discovery process simply by not using BDA for classes that should not be picked up.

**Comment by mkouba** [comment]
I think that this is already implemented via `quarkus.arc.exclude-types`: https://quarkus.io/guides/cdi-reference#how-to-exclude-types-and-dependencies-from-discovery
