### ISSUE TITLE
Support GraalVM 19.3 (no JDK 11)

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5837]

**Comment by machi1990** [comment]
Hi @emmanuelbernard, @gwenneg has been working on this issue https://github.com/quarkusio/quarkus/issues/4218 and he has an ongoing work on this PR https://github.com/quarkusio/quarkus/pull/5358 to support JDK8.

**Comment by gwenneg** [comment]
Thanks @machi1990!

Here's the current state of the GraalVM 19.3 support with JDK 8: I'm currently trying to work around a GraalVM bug (https://github.com/oracle/graal/issues/1883) that was reported and fixed this week. The fix will be part of GraalVM 19.3.1 which will be released in January. My idea is to include the fix into GraalVM 19.3.0 by substituting the faulty GraalVM code itself. If it works, Quarkus will use GraalVM 19.3.0 and if it doesn't, we may have to wait for the 19.3.1 release. The workaround didn't work on the Quarkus CI so far but I'm actively working on it.

**Comment by emmanuelbernard** [comment]
So let me close this one and reference #4218 in the Roadmap project.
Sorry about the duplication
