### ISSUE TITLE
Cannot deserialize LocalDate in @QueryParam due to missing ParamConverterProvider

### ISSUE THREAD

**Issue by cg-d** [quarkusio/quarkus#5860]
**Describe the bug**
I'm using Jackson (via quarkus-resteasy-jackson) as `ObjectMapper` with the `KotlinModule` and the `JavaTimeModule` registered using an `ObjectMapperCustomizer`. When I have an endpoint with a `@QueryParam` of type `LocalDate` quarkus does not start.

**Expected behavior**
I expect resteasy to use the provided `ObjectMapper` to deserialize a String formated "YYYY-MM-DD" into an instance of `LocalDate`.

**Actual behavior**
Omitting the name and method signature for brevity I get

```
RESTEASY003875: Unable to find a constructor that takes a String param or a valueOf() or fromString() method for javax.ws.rs.QueryParam("adate") for basetype: java.time.LocalDate
```

**To Reproduce**
1. Use 
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
```
2. Register a resource like
```kotlin
@GET
@Path("path")
fun broken( @QueryParam("adate") aDate: LocalDate) {}
```
3. Run a `@QuarkusTest` to try a start up the application.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux ninja-cgd 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.5-ea" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1, mixed mode, sharing)
 - GraalVM version (if different from Java): 
not used
 - Quarkus version or git rev: 
0.25.0
**Additional context**

The problem is fixed by adding

```kotlin
@Provider
class LocalDateConverter : ParamConverterProvider {

    override fun <T: Any?> getConverter(rawType: Class<T>?, genericType: Type?, annotations: Array<out Annotation>?): ParamConverter<T>? {
        return if (rawType == LocalDate::class.java) {
            object: ParamConverter<T> {
                val mapper = ObjectMapper().also { JacksonObjectMapperCustomizer().customize(it) }
                override fun toString(value: T?): String {
                    return mapper.writeValueAsString(value)
                }
                override fun fromString(value: String?): T {
                    return mapper.readValue(value, LocalDate::class.java) as T
                }
            }
        } else null
    }
}
```

to the project. I was expecting that this kind of Provider would be added out of the box when using Jackson's `JavaTimeModule`.

**Comment by geoand** [comment]
Thanks for the issue!

This is actually very interesting! We can and should register the module with Jackson when it's present on the user's classpath.

@gsmet @loicmathieu do you agree?

**Comment by geoand** [comment]
@cg-d Actually when thinking about this a little more, I don't think it makes sense to use Jackson to convert a value from a non -json string.
Did this actually work for you? I mean was the object mapper actually able to convert  something like `2019-01-01` into a `LocalDate`?

**Comment by loicmathieu** [comment]
We already register the jsr310 module so it should works.
Can you try with the latest version? 
Also we didn't activate the auto registration so to register an extra module you should provides an ObjectMapper customizer

**Comment by geoand** [comment]
It can't work the way it is because we don't provide a JAX-RS param converter hence my comment above

**Comment by cg-d** [comment]
@geoand "2019-01-01" is a perfectly valid JSON string. Using the JSR310 module Jackson can transform those just fine. Please take a look at the code I provided. Most JEE frameworks (e.g. Spring) will use Jackson in exactly this way.

 @loicmathieu Sorry for not providing the implementation of our `ObjectMapperCustomizer`. I thought explicitly writing that we do register the `KotlinModule` and the `JavaTimeModule` (from the jsr310 dependency) would suffice.

@geoand One way to provide the necessary `ParamConverter` along with the module might be to add a wrapper around `com.fasterxml.jackson.datatype:jackson-datatype-jsr310`similar to `io.quarkus:quarkus-resteasy-jackson`. This package could then provide a converter for the datatypes managed by the module (see https://github.com/FasterXML/jackson-modules-java8/tree/master/datetime).

It is totally possible that there already is some dependency around that will do this. If so I did not find it, though. :-)

**Comment by geoand** [comment]
> @geoand "2019-01-01" is a perfectly valid JSON string. Using the JSR310 module Jackson can transform those just fine. Please take a look at the code I provided. Most JEE frameworks (e.g. Spring) will use Jackson in exactly this way.
> 

I did try your code and it unfortunately did not work which is why I asked. Basically `objectMapper.readValue` was throwing an error.
I'll try it again, but are you sure the code you added above is correct?


> @loicmathieu Sorry for not providing the implementation of our `ObjectMapperCustomizer`. I thought explicitly writing that we do register the `KotlinModule` and the `JavaTimeModule` (from the jsr310 dependency) would suffice.
> 
> @geoand One way to provide the necessary `ParamConverter` along with the module might be to add a wrapper around `com.fasterxml.jackson.datatype:jackson-datatype-jsr310`similar to `io.quarkus:quarkus-resteasy-jackson`. This package could then provide a converter for the datatypes managed by the module (see https://github.com/FasterXML/jackson-modules-java8/tree/master/datetime).
> 
> It is totally possible that there already is some dependency around that will do this. If so I did not find it, though. :-)

This is the easy part :). As soon as I can actually get Jackson to deserialize `"2019-01-01"` to a LocalDate object, the rest is pretty much a done deal :)

**Comment by loicmathieu** [comment]
@cg-d if I recall correctly, Jackson by default serialize dates as 'timestamp' so as a long.
If you want to serialize them as STring you need to disable `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS` that's why I asked for your  `ObjectMapperCustomizer`.

@geoand did you try with disabling `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS` this should allow Jackson so serialize/deserialze LocalDate as String (I use this in the MongoDB with Panache integration test). This is the difference between Jackson and JSONB: Jackson serialize dates as timestamp by default and JSONB as String.

**Comment by geoand** [comment]
> @geoand did you try with disabling `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS` this should allow Jackson so serialize/deserialze LocalDate as String (I use this in the MongoDB with Panache integration test). This is the difference between Jackson and JSONB: Jackson serialize dates as timestamp by default and JSONB as String.

I didn't no. I'll check it out, thanks.
But ideally I need a way of convering a simple string into a LocalDate with Jackson without having to set any options for Jackson.

**Comment by cg-d** [comment]
@loicmathieu Ah, got it. We do set that feature of course :smile_cat: 
```kotlin
@Singleton
class JacksonObjectMapperCustomizer : ObjectMapperCustomizer {

    override fun customize(mapper: ObjectMapper) {
        mapper.enable(SerializationFeature.INDENT_OUTPUT);
        mapper.enable(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT);
        mapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);

        // register kotlin module for data classes
        mapper.registerModule(KotlinModule())
        mapper.registerModule(JavaTimeModule())
    }
}
```

**Comment by loicmathieu** [comment]
@cg-d this is strange because adding the `JavaTimeModule` and disabling `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS` allow to serialize/deserialize dates with the pattern YYYY-MM-DD into a LocalDate in Java.

Maybe this is a Jackson Kotlin issue? We have a test inside Quarkus that does this: https://github.com/quarkusio/quarkus/blob/master/integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/BookResourceTest.java#L97

**Comment by geoand** [comment]
When using I do `objectMapper.readValue(value, LocalDate.class)`: with  `2019-01-01` being the value

```
Unexpected character ('-' (code 45)): Expected space separating root-level values
```

**Comment by geoand** [comment]
So basically if we know how to get passed the issue I pasted above, all the rest has been taken care of

**Comment by cg-d** [comment]
@geoand The `"` is part of the JSON. `2019-01-01` is invalid; it has to be `"2019-01-01"`. See https://www.json.org/json-en.html

**Comment by geoand** [comment]
Interesting, so that means that you expect users to input `"2019-01-01"` as query param?

**Comment by cg-d** [comment]
Otherwise it would not be JSON. ¯\_(ツ)_/¯ 

And of course this is done by the Web App and not manually. The following code works fine after registering the `ParamConverter`:

```kotlin
val now = LocalDate.now()
val fromToday = NearbuyRestAssured.given().`when`()
                    .queryParam("after", now).get("offers")
                    .then().extract().jsonPath().getList(".", OfferView::class.java)
```

`NearbuyRestAssured` is just a helper class derived from `RestAssured` which provides the necessary security credentials for calling the API.

**Comment by geoand** [comment]
I have a different idea, we can just use `objectMapper.convertValue` :wink: . 
I tried it and it see to work fine, WDYT?

**Comment by cg-d** [comment]
That is no very clean. `readValue` is the intended method to parse JSON while `convertValue` actually expects an `Object`. I'd prefer using the first function but since I'm not a quarkus maintainer it's basically up to you.

**Comment by geoand** [comment]
Well TBH it doesn't make sense to me to have to expect the query string to contain quotes. Sure the converter could add them, but that doesn't feel natural.

You mentioned that Spring does this as well, do you mind point me to this feature in Spring that utilizes Jackson? I wasn't aware of it.

**Comment by cg-d** [comment]
Spring Boot will pull the `ObjectMapper` from the class path and call `findAndRegisterModules()` on it. I would need to dig a bit... Did not actively use Spring Boot much this year since I'm occupied with a quarkus based project :grin:

**Comment by cg-d** [comment]
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-json

**Comment by geoand** [comment]
Hahaha :)

Yes I know that Spring Boot auto-configures the `ObjectMapper` but I wasn't aware that it uses it for `LocalDate` parameters

**Comment by cg-d** [comment]
If you have Jackson and the module in the dependencies it will (a) register Jackson as handler for all conversion and (b) auto-register the modules. After this you can use any Java8 data types (including `ZonedDateTime` and `LocalDate`) both in `RestTemplate` as well as any `@Controller` functions.

**Comment by geoand** [comment]
OK, I'll start a demo project to see how this works but I am surprised that it depends on Jackson for such conversion

**Comment by geoand** [comment]
I did some digging in Spring Boot and as I suspected Jackson is not used to convert `LocalDate`. Instead the `Jsr310DateTimeFormatAnnotationFormatterFactory` creates a proper `TemporalAccessorParser` which does the conversion from String to `LocalDate`.

**Comment by geoand** [comment]
@asoldano does RESTEasy provide any OOTB handling of `LocalDate` and `LocalDateTime` as resource method parameters?

**Comment by asoldano** [comment]
@geoand sorry for the late answer; no, RESTEasy does not have OOTB param converter for these types afair.

**Comment by geoand** [comment]
Thanks @asoldano!

I guess the it might be interesting to add them at some point 😉

**Comment by rainmanhhh** [comment]
I defined a Provider but quarkus do not use it, why?
```
@Provider
class JdkDateTimeProvider : ParamConverterProvider
```

**Comment by belu** [comment]
@geoand
Same issue here with Quarkus 1.12 + Kotlin + Jackson. I use LocalDate as a @PathParam and expect it in ISO-8601 format.
It would be nice if this works out-of-the-box.

As a workaround I added a `ParamConverter<LocalDate>`. A project showing this + the workaround is available here:
https://github.com/belu/microquark

Fixing this issue goes into the same direction as the other improvement you and @gsmet did recently:
https://github.com/quarkusio/quarkus/pull/15139

**Comment by geoand** [comment]
@belu would you like to contribute that type to Quarkus?

**Comment by belu** [comment]
@geoand Yes, can do that with your help & guidance.

**Comment by belu** [comment]
@geoand 
Is it correct that just the `ParamConverter` for `LocalDate` has to be added to the runtime module, but not the `ParamConverterProvider` for `LocalDate`? Is this handled automagically by the `ResourceParamConverterProvider`?

The new method in the `ResteasyReactiveScanningProcessor` has to be annotated with `@BuildStep`, correct?

With "generate" you mean it returns a new `ParamConverterBuildItem`? There is also the pattern where you call `paramConverterBuildItemBuildProducer.produce()`.

Currently I get an exception when I use the updated extension in a test-project:
```
[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.NoSuchMethodError: 'boolean org.jboss.resteasy.reactive.common.processor.scanning.ApplicationScanningResult.keepClass(java.lang.String)'
        at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:383)
```

Any idea how to solve that?

**Comment by geoand** [comment]
> @geoand
> Is it correct that just the `ParamConverter` for `LocalDate` has to be added to the runtime module, but not the `ParamConverterProvider` for `LocalDate`? Is this handled automagically by the `ResourceParamConverterProvider`?
> 

Yeah, the way I propose Quarkus will be able to register it properly.

> The new method in the `ResteasyReactiveScanningProcessor` has to be annotated with `@BuildStep`, correct?
> 

Correct.

> With "generate" you mean it returns a new `ParamConverterBuildItem`? There is also the pattern where you call `paramConverterBuildItemBuildProducer.produce()`.
> 

Yes, either returning the build item or calling produce on the producer is the same thing.

> Currently I get an exception when I use the updated extension in a test-project:
> 
> ```
> [error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.NoSuchMethodError: 'boolean org.jboss.resteasy.reactive.common.processor.scanning.ApplicationScanningResult.keepClass(java.lang.String)'
>         at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:383)
> ```
> 
> Any idea how to solve that?

You are likely not using the correct versions. See https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#usage

**Comment by belu** [comment]
@geoand 
Thanks for the hint about the incorrect versions. That fixed the issue mentioned above.

Now I am running into a `ClassCastException`:
```
Caused by: java.lang.ClassCastException: class io.quarkus.resteasy.reactive.server.runtime.converter.LocalDateParamConverter cannot be cast to class javax.ws.rs.ext.ParamConverterProvider (io.quarkus.resteasy.reactive.server.runtime.converter.LocalDateParamConverter and javax.ws.rs.ext.ParamConverterProvider are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6ed256b2)
        at org.jboss.resteasy.reactive.server.core.parameters.converters.RuntimeResolvedConverter.init(RuntimeResolvedConverter.java:29)
```

Quarkus tries to cast the `LocalDateParamConverter` to a `ParamConverterProvider`. As you suggested before, I do not include my own `LocalDateParamConverterProvider`. Any idea what could be the problem?

**Comment by belu** [comment]
@geoand 
Something confuses me: in the method `ResteasyReactiveScanningProcessor.scanForParamConverters()`.

What you actually produce are `ParamConverterProviders`, and not `ParamConverters` (as you are looping over a collection `paramConverterProviders`).

So, why do you put a `ParamConverterProvider` into a `ParamConverterBuildItem`? Shouldn't that be added to a `ParamConverterProvidersBuildItem`?

Thanks for clarification!

**Comment by geoand** [comment]
It seems I misread the intent of the (badly named) `ParamConverterBuildItem`.
You indeed need to pass a `ParamConverterProvider` there

**Comment by belu** [comment]
@geoand 
Thanks! My local test-app works now.

Next step: testing. Can you recommend any QuarkusTest as a reference?

**Comment by geoand** [comment]
@belu I propose you open a draft PR. It makes it a lot easier to review

**Comment by belu** [comment]
@geoand Done. https://github.com/quarkusio/quarkus/pull/15451

**Comment by geoand** [comment]
Thanks. I'll take a look tomorrow or Friday
