### ISSUE TITLE
additional system properties are not passed as arguments to native execution during maven verify

### ISSUE THREAD

**Issue by Kin-Z** [quarkusio/quarkus#5869]
**Describe the bug**
Additional system properties, which are configured inside the `<systemProperties>` attribute in the maven-failsafe-plugin part, are not passed as arguments to native execution during maven verify.
For example:

`...
<configuration>
  <systemProperties>
    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
    <quarkus.http.test-port>8444</quarkus.http.test-port>
    <test.url>https://localhost:8444</test.url>
    <java.library.path>native-libs</java.library.path>
  </systemProperties>
</configuration>
`...

The values for `<quarkus.http.test-port>` and `<test.url>` are applied correctly but the value for `<java.library.path>` is not appended to the execute command (see behaviour below).

**Expected behavior**
The output in the log states:
`Executing [/home/daniel/IdeaProjects/lmt2-server/target/lmt2-server-1.0-SNAPSHOT-runner, -Dquarkus.http.port=8444, -Dtest.url=http://localhost:8444, -Dquarkus.log.file.path=target/quarkus.log, -Djava.library.path=native-libs]`

**Actual behavior**
The output in the log states:
`Executing [/home/daniel/IdeaProjects/lmt2-server/target/lmt2-server-1.0-SNAPSHOT-runner, -Dquarkus.http.port=8444, -Dtest.url=http://localhost:8444, -Dquarkus.log.file.path=target/quarkus.log]`

**To Reproduce**
1. Add some system property to the configuration of the maven-failsafe-plugin
2. Execute mvn verify -Pnative

**Environment (please complete the following information):**
 - Linux xxxxxxxxxxxx 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
Quarkus Version 1.0

**Comment by guilhem88** [comment]
If you copied the failsafe plugin configuration from the docs, system properties are not set properly.

If you configure it like this, it works:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>${surefire-plugin.version}</version>
    <configuration>
        <systemPropertyVariables>
            <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
        </systemPropertyVariables>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by Kin-Z** [comment]
it works for the property `<native.image.path>` both ways, but none of the above mentioned ways work for the property `java.library.path`.

**Comment by galderz** [comment]
I've just encountered this issue in master. Started a [Zulip discussion](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Multiple.20native.20test.20executions.20with.20different.20sys.20props) to see how to do this.

**Comment by galderz** [comment]
Moreover, as indicated in that zulip chat, `QuarkusTestResourceLifecycleManager` might just be enough for this since it enables to tailor the sys properties passed into the integration test. However, it doesn't seem to take into account that each the lifecycle is only associated with 1 of 2 tests and it seems to run with same sys properties for all tests.

**Comment by rkraneis** [comment]
Bitten by the same problem, trying to pass `-Dquarkus.lambda.handler=...` into native tests. We switched to using `environtmentVariables` instead. The documentation really needs to be updated ...

**Comment by JohT** [comment]
I had the same issue in a different manner. I tried to use `<argLine>` inside the failsafe configuration for standard integration tests (not native) and it was ignored. 

My goal was to attach native image agent to integration tests to get automated insights about reflection usage. 
I've found the following **workaround** using `<quarkus.test.arg-line>` instead of `<argLine>`:

```xml
<plugin>
	<artifactId>maven-failsafe-plugin</artifactId>
	<version>${failsafe-plugin.version}</version>
	<executions>
		<execution>
			<goals>
				<goal>integration-test</goal>
				<goal>verify</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<systemPropertyVariables>
			<buildDirectory>${project.build.directory}</buildDirectory>
			<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
 			<maven.home>${maven.home}</maven.home>
 			<!--  GraalVM java command arguments for the native-image-agent to write a trace file-->
 			<quarkus.test.arg-line>-agentlib:native-image-agent=trace-output=${project.build.directory}/native-image-agent-trace.json</quarkus.test.arg-line>
		</systemPropertyVariables>
	</configuration>
</plugin>
```

**Comment by geoand** [comment]
Closing as there is nothing Quarkus can do - it's all about configuring Maven Failsafe
