### ISSUE TITLE
remap "private" members to "package-private" under the hood

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#5875]
**Describe the bug**
I start the quarkus-app and following message is shown:

```
[INFO] [io.quarkus.arc.processor.BeanProcessor] 
Found unrecommended usage of private members (use package-private instead) 
in application beans:
	- @Inject field my.UserRepo#em,
	- @Inject field my.UserRepo#store,
	- @Inject field my.TaskRepo#em
	- and 19 more - please enable debug logging to see the full list
```

**Expected behavior**
quarkus should remap such `private`-members to `package-private`-members by itself (on compile) under the hood instead of forcing the user to change its code.  I guess, such `package-private`-members are only needed for _native_ compilation.

**Actual behavior**
users must change its code to be eligable for quarkus.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.0 FINAL

**Comment by geoand** [comment]
I don't think we want to do this because this could end up transforming a ton of application classes.

Furthermore, a user can get around this using constructor injection
