### ISSUE TITLE
JAX-RS requestContext in filter is not found

### ISSUE THREAD

**Issue by FreifeldRoyi** [quarkusio/quarkus#5889]
When upgrading from 0.22.0 to 1.0.1 `@QuarkusTest` of a JAX-RS resource fails. A filter, assumed to inject data to the `requestContext` runs and passes the `request.setProperty(propName,propValue)` part but when the flow reaches the JAX-RS resource and fetching the property it is not found.
I checked it also with a live service and not tests and it also fails

I see that there is a compatibility issue with `HttpServletRequest` but I'm not sure it has anything to do with setting a request property

**Comment by FreifeldRoyi** [comment]
Changing everything to RestEasy HttpRequest solved the problem, even though I'm not sure what was the problem in the first place

**Comment by geoand** [comment]
You can find more details about this in the release announcement of Quarkus 0.23 : https://quarkus.io/blog/quarkus-0-23-1-released/#new-http-layer

**Comment by FreifeldRoyi** [comment]
Won't it break compatibility to MP or JAX-RS?
