### ISSUE TITLE
The infamous DEV mode

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#589]
We're still missing a `Mode` enum that has three values: `PROD`, `DEV` and `TEST`.

That mode should be obtainable (injectable) by extensions as well as user code. It can be set by configuration files. It should default to `DEV`, or possibly `TEST` when run from Shamrock test runners.

Certain behaviour defaults change depending on that mode:

- Default landing page in `DEV` lists dev info, such as what you can do, and the list of registered URLs, possibly more deployment info. In prod it would probably be a 404.
- Default exception page in `DEV` mode shows stack trace and perhaps even code snippets. In `PROD` it should just inform the user it had an error and give (and log) that error ID (generated unique ID that users can then pass on to support, who can grep for it in the logs which have the stack trace).

So far I've only used `TEST` mode to load test data fixtures specific to tests, to avoid botching my `DEV` DB, but perhaps there are other use-cases for it.

**Comment by stuartwdouglas** [comment]
@FroMage I think this is complete?

**Comment by FroMage** [comment]
`LaunchMode` is all we need, but how do we access it from non-extensions? Like in a REST endpoint? Do we have a static method to get it? Can I inject it? Is it documented?

**Comment by cescoffier** [comment]
Is it complete now?

**Comment by FroMage** [comment]
Well, my questions remain unanswered. AFAICT the "writing an extension guide" only mentions it by accident at https://quarkus.io/guides/extension-authors-guide#conditional-step-inclusion and doesn't explain it. At a minimum we need to document it.
