### ISSUE TITLE
Allow alternative IDs for PanacheEntity POJOs

### ISSUE THREAD

**Issue by InfoSec812** [quarkusio/quarkus#5891]
Currently, PanacheEntity will automatically have a `Long` ID field added automatically, but sequential IDs are considered a bad practice in security circles because of the predictability. It would be useful if there were a way to have PanacheEntity to use alternate methods of generating the unique ID (e.g. UUIDs). 

References:
https://www.clever-cloud.com/blog/engineering/2015/05/20/why-auto-increment-is-a-terrible-idea/
https://phil.tech/http/2015/09/03/auto-incrementing-to-destruction/
https://medium.com/@hakibenita/bullet-proofing-django-models-c080739be4e#.xy7x1u2qj

The gist is that if you use a sequential ID for your data, you can expose much more data than you intend, make it easier for malicious parties to attack your application, and you can potentially violate regulatory requirements around privacy.

**Comment by machi1990** [comment]
@InfoSec812 instead of extending `PanacheEntity` you can alternatively extend from [PanacheEntityBase](https://github.com/quarkusio/quarkus/blob/92669f2aef11b860da23bcff50f75dd1b2c2776a/extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/PanacheEntityBase.java) and define aa custom  ID strategy.

**Comment by loicmathieu** [comment]
The Quarkus documentation about custom ID with Panache is here: https://quarkus.io/guides/hibernate-orm-panache#custom-ids

@InfoSec812 is it what you'r looking about? Can we close the issue ?

**Comment by InfoSec812** [comment]
Dang! And I tried so hard to make sure that I looked to see if there was already an option and I didn't find it. Yes, extending `PanacheEntityBase` appears to be a good solution for me. Cheers!
