### ISSUE TITLE
AWS Lambda Http Response is always base64 encoded.

### ISSUE THREAD

**Issue by Ravisankar-Challa** [quarkusio/quarkus#5897]
I have reported this *(https://github.com/quarkusio/quarkus/issues/5196) here but no one has looked in to this that is why I am reporting this as a bug.
This is a hello world example of aws lamnda http published through Amazon Api gateway. Response is base64 encoded.
https://k071rltja8.execute-api.ap-south-1.amazonaws.com/test/api/hello

Sample project is here https://github.com/Ravisankar-Challa/quarkus-lambda-http

**Comment by jkwasniak** [comment]
I have the same problem.

**Comment by maxandersen** [comment]
is this not a true duplicate of #5196 ?

**Comment by evanchooly** [comment]
It is.

**Comment by StefAtMentech** [comment]
I had this issue also, I fixed it by adding the following to SAM.yaml:
```yml
Globals:
  Api:
    BinaryMediaTypes:
      - "*/*"
```
