### ISSUE TITLE
Improve Hibernate Validator localization support with RESTEasy

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#5908]
We have a very low level of integration between RESTEasy and HV on the localization side.

HV supports localization, RESTEasy has support for dealing with the `Accept-Language` header (not sure how much support there is, we'll need to figure that out).

But... they are not coupled at all. Meaning you will always have the messages in the default locale.

The idea would be to take this into account in the `JaxrsEndPointValidationInterceptor` and build a specific `Validator` there, passing it a specific `MessageInterpolator` which would have the locale determined from:
- some config: for now, let's create a `HibernateValidatorBuildTimeConfig` with a `locales` property. We might generalize that but that will be good enough. This set of locales will need to be passed to the ValidatorFactory here: https://github.com/quarkusio/quarkus/blob/master/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorRecorder.java#L43 . Right now, we only pass the default one so if you try to use another locale, you will get an error as reported here https://github.com/quarkusio/quarkus/issues/5882.
- the headers of the request. I think we can get them from `ResteasyContext`. If you call `ResteasyContext.getContextDataMap()`, there should be some headers there, we need to check they are properly populated for the given method that is currently called. Playing with the `integration-tests/hibernate-validator/` should help.
The `MessageInterpolator` would be a simple wrapper around the existing `MessageInterpolator` and would just resolve the locale then pass it to the existing interpolator.

We usually have a way to define a MessageInterpolator specific to a given context via:
```
validatorFactory.usingContext()
    .messageInterpolator(specificMessageInterpolator)
    .getValidator();
```
The issue is that... I was a bit too conservative in HV and made it forbidden in `PredefinedScopeValidatorContextImpl`. I think we could allow it and it was just me being too conservative but we will need to check if it works correctly (that means that you will need to get HV master, adjust it and recompile).

I don't know if there is a proper `Accept-Language` resolution algorithm in RESTEasy, easily accessible for us. It would really nice better if we didn't have to implement our one. @asoldano any pointers?

I think this should be done in several small steps:
- support several locales in HV via configuration
- see if we can safely override the MessageInterpolator in the PredefinedScopeVF. Let's not prepare the PR for HV right away, we can do that at the end.
- see if we can resolve the locale from the RESTEasy headers and use that locale for HV.

In the end, we might make a RESTEasy-aware message interpolator the default one if we can get to a working solution. If we do that, all the HV calls would be localized by default if they are done in the context of a RESTEasy call. But that's really something for the end.

**Comment by gsmet** [comment]
@irenakezic this is the issue I was talking about on Zulip.

Feel free to ping me anytime if you have questions.

**Comment by sean-scott-lr** [comment]
@gsmet I like where you are headed with this....

One thing to add to this excellent description.  It would be nice to be able Add the "accept languages" to a context in some neutral way.  

For example... I would like to read a header similar to "accept-languages" in a GRPC interceptor and poke the values into a context so that when the validation exception is thrown ( and handled in a GRPC interceptor ) it is also already formatted in the correct locale.

**Comment by irenakezic** [comment]
Ok, thanks for such a great description. I will take a look and get back to you.

**Comment by irenakezic** [comment]
@gsmet As agreed I pushed partial implementation for the fix to my branch (https://github.com/irenakezic/quarkus/tree/issue5908). Please take a look.

**Comment by gsmet** [comment]
@irenakezic nice work. I will have a look at the HV side this week.

Could you share the commit you made to HV to allow message interpolator override? I will include it in my upcoming PR.

Thanks!

**Comment by gsmet** [comment]
@irenakezic I pushed some more stuff here: https://github.com/hibernate/hibernate-validator/pull/1063 .

The important change can be summarized by this test: https://github.com/hibernate/hibernate-validator/pull/1063/commits/1f9dc3ca980e5d10215745e8daed359efd2fb309#diff-5dd9191fc8d91809e7493c7e1d014301R30 . The idea would be to set up a custom `LocaleResolver` in Quarkus if RESTEasy is in the classpath.

I think the best way to do that would be:
- take into account a potential `LocaleResolver` bean in https://github.com/quarkusio/quarkus/blob/master/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorRecorder.java#L103 (exact same logic as for `GetterPropertySelectionStrategy`)
- implement a custom `LocaleResolver` which extracts the ``LanguageRange``s from the headers and resolve the locale. The provided context should give you all the information you need. Obviously, it also has to have a shortcut if we are not in a RESTEasy context as this could happen. Make it a `@Singleton` bean and mark it with `@DefaultBean` so that it can be overridden by the user
- add the custom `LocaleResolver` here as an `AdditionalBeanBuildItem`: https://github.com/quarkusio/quarkus/blob/master/extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java#L103

I think with this new setup:
- you could get rid of the custom message interpolator: everything will be handled by the `LocaleResolver` inside Hibernate Validator
- it should work for annotations on RESTEasy methods but it should also work if you manually validate a bean inside a RESTEasy method: we need a test for that!

**Comment by irenakezic** [comment]
@gsmet could you please check my last commit? Thanks!

**Comment by gsmet** [comment]
Sure, I'll have a look later today!

**Comment by irenakezic** [comment]
@gsmet I made changes aligned with your comments

**Comment by gsmet** [comment]
@irenakezic I added a few additional comments.

Otherwise, I think we are nearly there (except for the thing I need to fix regarding the `ParameterMessageInterpolator`).

**Comment by gsmet** [comment]
@irenakezic Apart from my comments on the commit, it would be nice to introduce a `defaultLocale` config property and push it to the ValidatorFactory configuration together with the initialized locales. I also added that to my HV PR. Having a test covering it would be nice (the test could be added in the deployment module).

Once you have addressed my last comments, could you squash all your commits, rebase and create a draft PR?

If won't pass CI until I release the next HV but it will allow us to collaborate. I want to move the locale config stuff to something more global.

**Comment by irenakezic** [comment]
@gsmet I created a pull request. Could you please review it?
Note that I still need to update the quarkus-bom/pom.xml once HV release is ready.
