### ISSUE TITLE
Database connections are leaked in AWS Lambda

### ISSUE THREAD

**Issue by otcyury** [quarkusio/quarkus#5921]
**Describe the bug**
While testing JPA with Lambda I've encountered situation when Lambda runs JPA query, which connects to database, but doesn't close connection.

**Expected behavior**
If running in Lambda it's reasonable (if possible) to close connection on lambda exit. If there is some way to use connection pool, it would be ideal.

**Actual behavior**
If I keep using Lambda, it looks like, it's reusing the same connection (same IP / connection), however, if Lambda gets "cold" AWS spawns a new one on different IP address and it get a new connection. As a result, I am observing growing number of connections on database, which will eventually lead to an issue.

**To Reproduce**
1. Created AWS Lambda using Maven Archetype
2. Added Entity and CrudRepository classes
3. Created class with injected repository object and `@Transactional` method
4. Used repository object to access database

**Environment (please complete the following information):**
 - Output of `java -version`: 1.8
 - Quarkus version or git rev: 1.0.1

**Comment by stuartwdouglas** [comment]
Are you sure the process is being terminated, and it is not just a case of multiple lambda instances running at once?

Also is this in JVM or native mode?

**Comment by stuartwdouglas** [comment]
I think the linked PR should fix this.

**Comment by otcyury** [comment]
I am invoking Lambda from command line, so yes, only one instance is running at a time. This is native mode.

Thank you for looking into this. What release will this be available in?

**Comment by stuartwdouglas** [comment]
If this is native mode then that commit is not the answer, it only applies to JVM mode. Can you get the logs from the instances that are not closing their DB connections? Does it appear that they are doing a clean shutdown?

**Comment by stuartwdouglas** [comment]
Re-opening, as I am not sure if that PR is sufficient

**Comment by otcyury** [comment]
As far as logs go, there are nothing abnormal and they only contain output from lambda code.

I know lambda finishes completely because I get its result returned with data from handler's return object. Below are two classes that show pretty much everything lambda is doing.

```
package hist.server;

import javax.inject.Inject;
import javax.inject.Named;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

@Named("test")
public class TestLambda implements RequestHandler<InputObject, OutputObject> {

    @Inject
    ProcessingService service;

    @Override
    public OutputObject handleRequest(InputObject input, Context context) {
        return service.proces(input).setRequestId(context.getAwsRequestId());
    }
}

package hist.server;

import hist.server.domain.BlueskyCompliance;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.transaction.Transactional;
import java.util.Optional;

@ApplicationScoped
public class ProcessingService {
    @Inject
    BlueskyComplianceRepository repo;

    @Transactional
    public OutputObject proces(InputObject input) {
        System.out.println("In process");
        Optional<BlueskyCompliance> bs = repo.findById(1);

        String result = input.getGreeting() + " " + (bs.isPresent() ? bs.get().getState() : "No BS");
        OutputObject out = new OutputObject();
        out.setResult(result);
        return out;
    }
}
```

**Comment by otcyury** [comment]
Conceptually, decorator that facilitates database connectivity concerns needs to take care of closing connection, even if handler code exited abnormally.

**Comment by otcyury** [comment]
Below is lambda's output from CloudWatch.

```
2019-12-04 15:44:40,828 INFO  [io.quarkus] (main) quotes 1.0-SNAPSHOT (running on Quarkus 1.0.0.Final) started in 0.215s. 
2019-12-04 15:44:40,832 INFO  [io.quarkus] (main) Profile prod activated. 
2019-12-04 15:44:40,832 INFO  [io.quarkus] (main) Installed features: [agroal, amazon-lambda, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, narayana-jta, spring-data-jpa, spring-di]
START RequestId: 671bca06-7919-4a30-96f0-af15e6ec9b77 Version: $LATEST
In process
2019-12-04 15:44:40,870 INFO  [io.agr.pool] (Lambda Thread) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
END RequestId: 671bca06-7919-4a30-96f0-af15e6ec9b77
REPORT RequestId: 671bca06-7919-4a30-96f0-af15e6ec9b77	Duration: 495.41 ms	Billed Duration: 800 ms	Memory Size: 128 MB	Max Memory Used: 78 MB	Init Duration: 299.75 ms
```

**Comment by stuartwdouglas** [comment]
Instances can serve multiple requests (i.e. lambda will keep the same process running for a while in case new requests come in). If the instance was being killed even if we did not shut down the DB connection the operating system would terminate it for us.

Maybe we need to avoid connection pooling with lambdas and connect on demand instead.

**Comment by otcyury** [comment]
I am not exactly clear on comment "...if we did not shut down the DB connection the operating system would terminate it for us", but from my observation, once lambda makes a new connection I see them in pgAdmin (PostgreSQL admin tool) for hours. I haven't checked if and when they actually go away, but if the rate of creation outpaces the rate of destruction there is a chance DB will run out of connections.

Regarding connection pool, I had a question as well. It's not clear to me how it's working in context of lambda. For example, based on below properties in lambda deployment I expect to see 5 connections initially, however checking DB I see only 1. Is my interpretation worng regarding `min-size` property?

quarkus.datasource.min-size = 5
quarkus.datasource.max-size = 10

BTW, I tested these properties with stand - alone server and I also saw only 1 DB connection.

**Comment by stuartwdouglas** [comment]
It means that if there are more than 5 some of the idle ones will be closed after idle-removal-timeout. If you want it to create 5 connections immediately you need to set initial-size.

**Comment by stuartwdouglas** [comment]
I think you will find that lambda is keeping the processes alive, which is why they still have an open connection. If lambda killed the process then the operating system would clean up any resources it had open including open sockets, so the connection would be closed. Can you try setting the min size to 0 and setting a short idle-removal-timeout and see what happens?

**Comment by otcyury** [comment]
Yes, thanks. I found documentation for initial-size property. That's why I removed my question.

**Comment by otcyury** [comment]
Looking at documentation for idle-removal-interval, its default value is 5 minutes. I just checked pgAdmin and lambda connection established at 2:52 PM is still there.

I will try setting min size to 0 and idle-removal-interval to 1M and see what happens.

**Comment by stuartwdouglas** [comment]
idle-removal will only remove connections if there are more than min-size, so unless you set min-size to 0 it will always leave connections open.

**Comment by otcyury** [comment]
Unfortunately, quarkus.datasource.min-size = 0 and quarkus.datasource.idle-removal-interval = 1M didn't help - new connection did not go away after 1 minute and is still there 10 minutes later.

**Comment by otcyury** [comment]
FYI, connection established at 2:52 PM disappeared, but I saw it at least 10 minutes ago. May be it happened at 4:52 MP.

**Comment by otcyury** [comment]
Hi, I was wondering when this will be fixed and how.

I think the best way to handle connections in lambda is to have a single connection and close it after lambda exits because AWS will keep creating new instances if the same lambda is called concurrently or when it gets "cold". Under these conditions, it's almost pointless to keep connection pool and can put extra stress on DB connections since the same lambda instance is not around for long enough to benefit connection pool.

I would like to know the timing of the solution because I want our company to invest in the conversion of our code-base from Spring into Quarkus and we are also looking to port code to AWS Lambdas.

Thank

**Comment by gsmet** [comment]
@otcyury apparently, it got fixed and the fix will be released in next week's release.

**Comment by gsmet** [comment]
@otcyury apparently, it got fixed and the fix will be released in next week's release.
