### ISSUE TITLE
OIDC integration-tests/oidc-code-flow is unstable

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#5926]
**Description**
It has failed recently with a `Too much redirect ...` error but it appears to be failing randomly. 
It is really an html unit level issue. 

**Implementation ideas**
Perhaps a newer version can be used or some alternative html-friendly test framework can be plugged in

CC Pedro @pedroigor

**Comment by stuartwdouglas** [comment]
Do you have an example of such a failure?

**Comment by pedroigor** [comment]
@sberyozkin I think we can try to solve that by using some approaches we do here at Keycloak project. But I would like to know the line shown in logs when the failure happens. Do you have it ?

**Comment by sberyozkin** [comment]
@stuartwdouglas, @pedroigor Sorry, it would keep failing with a "Too much redirect on someurl" where `someurl` would be a URL prepared by Keycloak after the authentication has been done and the (test) user is redirected back. I'll check if the builds still have it

**Comment by sberyozkin** [comment]
@stuartwdouglas @pedroigor I'm not sure I can find it, I'll close it and reopen if it fails again

**Comment by gsmet** [comment]
FWIW, I just saw a similar failure in a PR so I think it's a real issue. Unfortunately, I was in a hurry and rerun the failed check.

**Comment by stuartwdouglas** [comment]
So a quick google reveals that the most common cause of these issues is the cache. I think will open a PR that disables the cache for the HTML tests, and we can see if this fixes it.

**Comment by stuartwdouglas** [comment]
I take it this failed again? Is there a link to the failure?

**Comment by pedroigor** [comment]
@stuartwdouglas If you don't mind I can take this one.

**Comment by stuartwdouglas** [comment]
fine by me :-)
