### ISSUE TITLE
Env variable QUARKUS_LOG_CONSOLE_* do not override at runtime

### ISSUE THREAD

**Issue by lkrzyzanek** [quarkusio/quarkus#5936]
**Describe the bug**
quarkus console log should be configurable at runtime by env variables but seems to not working.

**Expected behavior**
`export QUARKUS_LOG_CONSOLE_ENABLE=false ; java -jar target/app-runner.jar`
should not log anything to console but it does.

However when trying 
`java -Dquarkus.log.console.enable=false -jar target/rhaccount-eloqua-bridge-runner.jar` it doesn't log as expected

**Actual behavior**
`export QUARKUS_LOG_CONSOLE_ENABLE=false ; java -jar target/app-runner.jar` logs everything. 

**To Reproduce**
1. mvn package
2. `export QUARKUS_LOG_CONSOLE_ENABLE=false ; java -jar target/app-runner.jar`
3. check console log

**Configuration**
```properties
quarkus.package.uber-jar=true

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: openjdk version "11.0.4" 2019-07-16
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  Quarkus 1.0.1.Final

**Comment by dmlloyd** [comment]
Hi Libor, I believe this is a duplicate of #3516 which is fixed in 1.1.0.

**Comment by lkrzyzanek** [comment]
ok. will test once 1.1.0 is out. Thanks.

**Comment by lkrzyzanek** [comment]
I confirm that this issue is fixed. Thank you!
