### ISSUE TITLE
Log a big warning if an application bean observes @Initialized(ApplicationScoped.class)

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#5946]
There is a big difference in behavior when working with native images. More details are explained in the guide: https://quarkus.io/guides/lifecycle#what-is-the-difference-from-initializedapplicationscoped-class-and-destroyedapplicationscoped-class.

**Comment by mkouba** [comment]
@manovotn would you care to take this issue?

**Comment by r-uu** [comment]
Even in trivial cases server startup fails after if this warning was logged. Logging hints at problems with injection (of EntityManager in my case). It would be nice if there would be an additional hint in this direction when injection has problems.

**Comment by manovotn** [comment]
Hello @r-uu, 
this issue (and the warning in it) is linked to usage of observer method for scope initialization which is often used as means to trigger "eager init" in CDI. And the warning is there purely because of varying behaviour between JVM and native modes, otherwise the observer works as expected. That sounds different from injection problem warning that you are mentioning - could you be more specific, please? What logging and errors are you seeing?

**Comment by r-uu** [comment]
I'll try to reproduce and let you know. Might take some time. It's a spare time activity ...

**Comment by r-uu** [comment]
I put together a minimal maven project that shows the discussed behaviour. What is the preferred way to exchange that so that you can play around with it?

**Comment by manovotn** [comment]
@r-uu you should be able to just link/attach it to this issue and we can go from there.

**Comment by r-uu** [comment]
ok, i hope the attachment is fine and usable. it's a minimal project as i said, it's not doing anything meaningful. i configured a mysql db in application properties. if you get this project started it should show problems with injection of entitymanager. if you remove the observer method in ObserverTest everything seems to be alright. btw, if there is no entity the server also does not start. the log messages do not really point to missing entities.

please let me know if you need further infos.

cheers!

[ruu.io-quarkus-observer.zip](https://github.com/quarkusio/quarkus/files/4684387/ruu.io-quarkus-observer.zip)
