### ISSUE TITLE
Pull up adduser in Dockerfile.jvm

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#5950]
The generated Dockerfile.jvm runs `RUN adduser...` very late in the game, in particular after adding the JARs of the application. This prevents this layer from being cached if the application or its dependencies change and the image is rebuilt.

Happy to file a PR for re-ordering it, but I need to know where the template is located.

**Comment by gsmet** [comment]
I think the template is there: https://github.com/quarkusio/quarkus/tree/master/devtools/platform-descriptor-json/src/main/resources/templates

**Comment by geoand** [comment]
> I think the template is there: https://github.com/quarkusio/quarkus/tree/master/devtools/platform-descriptor-json/src/main/resources/templates

Yup, that is the correct directory

**Comment by gunnarmorling** [comment]
Ok, thanks. I'll file a PR shortly.

>

**Comment by gunnarmorling** [comment]
PR is at https://github.com/quarkusio/quarkus/pull/6002
