### ISSUE TITLE
Support for Liquibase

### ISSUE THREAD

**Issue by tqvarnst** [quarkusio/quarkus#5957]
**Describe the extension**
An extension to be able to use Liquibase database migration (https://www.liquibase.org/) as part of a Quarkus project. 

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
```properties
# Add your application.properties here, if applicable.

```

**Additional context**
(Add any other context about the proposal here.)

**Comment by gsmet** [comment]
We already have Flyway. What would this one bring to the plate?

**Comment by andrejpetras** [comment]
Hi,

we have lot of JEE applications using the liquibase tool to manage the database changes. We would like to move to the quarkus and also minimize the migration effort and keep the liquibase tool.

I managed to build the liquibase in the native image (it is crazy project) with a postgresql driver. https://github.com/1000kit/liquibase
I believe it should be possible to write the liquibase quarkus extension.

We are happy to contribute to this extension.

**Comment by maxandersen** [comment]
@gsmet Liquibase has an abstraction layer so you can express migrations at a higher level which then gets converted into specific dialect so nicer to use if targeting multiple databases (like h2 for dev and postgresql for prod). Flyway is more "tuneable" but less generic so I say its worth getting both supported.

@andrejpetras contribution will be welcome! lets see what we can make happen!

**Comment by maxandersen** [comment]
btw. looks like https://www.baeldung.com/quarkus-extension-java have a good start - i haven't tested if it works :)

**Comment by andrejpetras** [comment]
I am back on the quarkus track ;) If nobody picked up this issue then please assign it to me, I will prepare the PR for it

**Comment by maxandersen** [comment]
@andrejpetras there you go - looking forward to it :)

**Comment by liebig** [comment]
Any news here? A Liquibase support would be great.

**Comment by andrejpetras** [comment]
@liebig PR for liquibase extension https://github.com/quarkusio/quarkus/pull/6334

**Comment by liebig** [comment]
Oh great, thanks for the information and the implementation.

**Comment by maxandersen** [comment]
this was merged a while back. closing.
