### ISSUE TITLE
Support for Liquibase database migrations

### ISSUE THREAD

**Issue by tqvarnst** [quarkusio/quarkus#5958]
### Description
I have a customer request for adding support for Liquibase database migration. 

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
- [ ]  Create an extension - https://github.com/quarkusio/quarkus/issues/5957
- [ ]  Write an guide

**Comment by paulrobinson** [comment]
@emmanuelbernard Can you schedule this one, and if soon find an assignee?

**Comment by arvidvillen** [comment]
I just happened to see this issue and I think it could be closed as there already exist an extension and a guide.

**Comment by gsmet** [comment]
Ah yes, thanks!
