### ISSUE TITLE
KubernetesMockServerTestResource overrides Fabric8 Kubernetes

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#5966]
**Describe the bug**
KubernetesMockServerTestResource overrides Fabric8 Kubernetes instead of the Quarkus kubernetes-client properties which make that the URL of mocked Kubernetes API server is not overriden correctly and the real kubernetes cluster is used during the test execution. 

**Expected behavior**
Use the mocked server URL

**Actual behavior**
Uses the real one cluster.

**Additional context**
PR coming.

**Comment by geoand** [comment]
Is this still an issue? I am pretty sure it's not
