### ISSUE TITLE
ArcProcessor - ApplicationClassPredicate only considers the root application archive

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#5992]
This could cause problems in the dev mode for multi-module Maven projects.

**Comment by manovotn** [comment]
Can you elaborate on what problems do you mean?

**Comment by mkouba** [comment]
Ok, I will try to ;-). So when generating beans, proxies and other internal constructs we use this predicate to test the original bean class because we have to load these classes with the same ClassLoader as the original bean class (for example to access package-private members). In the dev mode a separate CL is used for app classes so that we can drop the CL when a class is modified. In a multi-module Maven project, all modules are considered app archives so that if you modify a class in module **A** but run the app in module **B**, the change of the class results in app rebuild and you can see the changes immediately.

**Comment by mkouba** [comment]
Hm, I was probably wrong - I fixed this 7 months ago ;-). See https://github.com/quarkusio/quarkus/blob/master/core/devmode/src/main/java/io/quarkus/dev/DevModeMain.java#L157-L170.
