### ISSUE TITLE
OIDC Claim Annotation based authorization

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#5996]
**Description**
JWT token contains a lot of claims which can be used to support a generic claim based authorization beyond what can be offered by mapping the role claims to `@RolesAllowed`.

**Implementation ideas**

We can start with introducing the annotations such as `@AuthenticationMethod`/etc mapping to the well-known OIDC claims, for example, given `"amr": ["iris"]` ([RFC8176](https://tools.ietf.org/html/rfc8176), `iris scan biometrics`), one can enforce that only the users which have authenticated using the `iris` mechanism can invoke the methods on a given JAX-RS class:

```
@Path("/supersecure")
@AuthenticationMethod("iris")
public class SuperSecuredResource {
...
}
```

and similarly for other well-known claims

**Comment by sberyozkin** [comment]
I've dropped a requirement for smallrye-jwt but may be it should be included as well, since it also works with JWT. The only issue is that with smallrye-jwt we don't know for example, if a claim like `amr` was set by a self-issuing client or not.

**Comment by pedroigor** [comment]
@sberyozkin What about providing a `HttpSecurityPolicy` for path-based protection ?

I'm also wondering if we could use `HttpSecurityPolicy` to enforce access based on annotations ...

**Comment by sberyozkin** [comment]
Hi @pedroigor sure, I guess we can use one of the existing security mechanisms to enforce such annotations, this issue is mainly about introducing some cool factor into the OIDC protected applications :-), instead of for example of the users getting an `amr` claim manually from `JsonwebToken` and parsing it, etc.
What do you mean about a path based protection ? It is also possible, no ?

**Comment by pedroigor** [comment]
Sorry, I mean through the properties file ...

**Comment by sberyozkin** [comment]
That is fine; that could be another issue I guess (One caveat is that with the properties files the runtime init is not possible but we can discuss that separately for sure) thanks

**Comment by sberyozkin** [comment]
Will reopen later on
