### ISSUE TITLE
RESTEASY002020: Unhandled asynchronous exception with quarkus 1.0 Final and RestEeasy JAX-RS Resource

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#6006]
**Describe the bug**

https://stackoverflow.com/questions/59229567/resteasy002020-unhandled-asynchronous-exception-with-quarkus-1-0-final-and-rest

**Expected behavior**
No exception,

**Actual behavior**
RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.NullPointerException

**To Reproduce**
1. use similar to this code (that prove that nothing fails for hello-world-main-app), but with Rest Easy Resources it fails:

`package rxjava2.samples;

import io.reactivex.Flowable;
import io.reactivex.Single;
import io.reactivex.schedulers.Schedulers;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.ExecutionException;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class Sample1 {

    static final List<Integer> threadIds = Collections.synchronizedList(new ArrayList<Integer>());

    public static void main(String[] args) throws ExecutionException, InterruptedException {

        final long startTime = System.currentTimeMillis();

        System.out.println("Main thread: " + Thread.currentThread().getName());

        final int amountOfRequests = 1000;

        final Single<String>  single = singleIsHere(amountOfRequests);

        final CompletionStage futureHasCome = futureIsHere(single);

        String result = (String) futureHasCome.toCompletableFuture().get();

        System.out.println("Result:" + result);

        final long endTime = System.currentTimeMillis();

        System.out.println( "Execution time: " + (endTime - startTime) / 1000 + "sec.");

        System.out.println("The amount of thread is " + Collections.max(threadIds) + " which were involved to handle the " + amountOfRequests + " amount of requests");

    }

    // In case if you need to convert it to CompletionStage. Say Rest Easy JAX-RS Resource uses the CompletionStage as return types
    public static CompletionStage<String> futureIsHere(Single<String> single) {

        final CompletableFuture<String> future = new CompletableFuture<>();
        single
                //.subscribeOn(Schedulers.io())
                .subscribe(future::complete);

        return future;

    }

    // Represent some Service call that uses RX Java 2
    public static Single<String> singleIsHere(int amountOfRequests) {

        final List<Integer> requestList = IntStream.rangeClosed(0, amountOfRequests).boxed().collect(Collectors.toList());

        final Flowable<String> relatedMaps = Flowable.range(0, requestList.size())
                .concatMapEager(index ->
                                fetchByHttp(requestList.get(index))
                                        .subscribeOn(Schedulers.io())
                                        .toFlowable(),
                        /* max parallel executions: */ requestList.size(),
                        /* items expected per source: */ 1
                );

        return relatedMaps.lastElement().toSingle();
    }

    public static Single<String> fetchByHttp(final int request)  {

        return Single.fromCallable( () -> {

                System.out.println("Fetch by Http Thread name: " + Thread.currentThread().getName()); // RxCachedThreadScheduler-N

                final Integer id = Integer.parseInt(Thread.currentThread().getName().split("-")[1]);

                 threadIds.add(id);

                try {
                    Thread.sleep(1000); // say it take 1 second to do the HTTP call
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                return request + "";
        });//.subscribeOn(Schedulers.newThread());

    }

}
`

2. with this resource
  @Timeout(20000)
    @GET
    @Path("/data")
    @Produces(MediaType.APPLICATION_JSON)
    public CompletionStage<Data> getData(){

        final Single<Data> dataSingle = service.getData();

        final CompletableFuture<Data> dataFuture = new CompletableFuture<>();
        dataSingle
                //.subscribeOn(Schedulers.io())
                .subscribe(dataFuture::complete);

        return dataFuture;
    }
it will fail. Sometimes. Every 5th time for me.

More details:
 https://stackoverflow.com/questions/59229567/resteasy002020-unhandled-asynchronous-exception-with-quarkus-1-0-final-and-rest

--

P.S.

This seems about it. 
https://github.com/quarkusio/quarkus/issues/3578
And it is seems fixed. But still, it does not work for me in quarkus 1.0 Final. As I described.

**Comment by Sergey80** [comment]
https://stackoverflow.com/questions/59257978/quarkus-resteasy-ws-rs-resource-completionstage-exception-handling - if I don't use CompletionStage then seems it is stable. But I have to block thread on the Resource.

**Comment by FroMage** [comment]
Hi, Could you try with Quarkus `1.3.0.Final` please?

**Comment by Kondamon** [comment]
I have compiled the mailer example from [here](https://quarkus.io/guides/mailer) as native image running in docker:

```
@GET
@Path("/async")
public CompletionStage<Response> sendASimpleEmailAsync() {
    return reactiveMailer.send(
            Mail.withText("to@acme.org", "A reactive email from quarkus", "This is my body"))
            .subscribeAsCompletionStage()
            .thenApply(x -> Response.accepted().build());
}
```
I receive the same error with quarkus 1.5.1

```
RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

**Comment by geoand** [comment]
Closing as we got no feedback
