### ISSUE TITLE
Add version check of graalvm / javavm's into build tasks

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#6008]
**Description**
With all the funky version combinations we are ending up with using bleeding edge graalvm it would be useful if we would at least print a warning if users are using a graalvm / javavm's version combinatons that is not the recommended one.

**Implementation ideas**
like current master should warn if you use graalvm < 19.3; and jdk target > 8.

**Comment by geoand** [comment]
It does [fail](https://github.com/geoand/quarkus/blob/8a1c12d268ac2b03f9eb7f86f436800beac09944/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L316) if the GraalVM version is not the anticipared one and I recall seeing the error recently.
What scenario did you encounter were the failure wasn't being displayed?

For jdk target > 8 indeed I don't think there is a message but some random failure

**Comment by gsmet** [comment]
For the record, it didn't fail if you were using a plain JDK to build and GraalVM only to build the native image.

I fixed that a few days ago in master: https://github.com/quarkusio/quarkus/pull/5972 .

**Comment by maxandersen** [comment]
ah - so its fixed in master already ? then closing this down :)
