### ISSUE TITLE
Cannot access to swagger-ui page when native image is running

### ISSUE THREAD

**Issue by majonga88** [quarkusio/quarkus#6010]
Hi folks,

Following this guide : https://quarkus.io/guides/openapi-swaggerui
And this project : https://github.com/quarkusio/quarkus-quickstarts/tree/master/openapi-swaggerui-quickstart

I check the swagger-ui path after execute : `mvn quarkus:dev`, i have the swagger page, on this path `http://0.0.0.0:8080/swagger-ui`

But when i ran the native image with these following commands :

`mvn package -Pnative -Dquarkus.native.container-build=true`
`docker build -f src/main/docker/Dockerfile.native -t thefactory/fruit-api .`
`docker run -i --rm -p 8080:8080 thefactory/fruit-api`

I have this error when i tried to access to the swagger page, `/swagger-ui` :
> RESTEASY003210: Could not find resource for full path: http://0.0.0.0:8080/swagger-ui

I think it's append when i build the docker image, he don't copy the swagger ressources.

Could you please help me ?

Big thanks for your help

**Comment by gsmet** [comment]
Did you add:
```
quarkus.swagger-ui.always-include=true
```
to your `application.properties`?

**Comment by majonga88** [comment]
Yes it works, apologize i miss read the paragraph for production environment, could you please change the label bug to question ?

Thank you again.
