### ISSUE TITLE
Example for websocket client

### ISSUE THREAD

**Issue by see-quick** [quarkusio/quarkus#6014]
**Description**
Before i start i also looked at https://quarkus.io/guides/websockets, but this not help my use case. 

As an user,  i want to web socket secure client, because i need to download dozens of data. The example should just show how easy can be wss client written in Quarkus. Moreover, it would be great if that client download data from some wss (stream) and do some agregation of that data.

**Implementation ideas**
- Using @ApplicationScoped & @ClientEndpoint, @OnOpen annotations etc.  
- I was able to create solution with help of `com.neovisionaries.ws.client.WebSocket` but better approach would be for `javax.websocket`.

**Comment by gbdevw** [comment]
Here is a running example of a Quarkus based application which uses the websocket API from Coinbase Pro with the Undertow websocket extension and JSR annotations :

https://github.com/gbdevw/cb-etl/tree/master/src/main/java/tech/gbdevw/colibri/coinbaseetl/coinbase/websocket
