### ISSUE TITLE
tweak special classes with @ApplicationScoped or @Singleton by default

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#6028]
**Description**
There are classes in quarkus which are `@ApplicationScoped` by default, for example, classes annotated with `@Path`. 

Classes annotated with `@javax.persistence.Converter` could also be `@ApplicationScoped` by default. So user does not need to annotate such classes explicitly with `@ApplicationScoped`. Maybe some other types of annotated classes can also be `@ApplicationScoped` by default in quarkus.

**Implementation ideas**
Look for annotated classes which can be annotated with `@ApplicationScoped` by default.

**Comment by geoand** [comment]
Closing as not planned
