### ISSUE TITLE
Quarkus CLI basics

### ISSUE THREAD

**Issue by stalep** [quarkusio/quarkus#6033]
Update the current CLI code so it works similar to Maven/Gradle.
The work is happening here: https://github.com/stalep/quarkus/tree/aesh_updates
Commands implemented:

- list-extensions
- add-extension
- create-project
- compile-project
- dev-mode

The user can choose to start an interactive CLI or call the commands one by one as needed.

**Comment by anhldbk** [comment]
@maxandersen Any recommendation for the suitable implementation? May I write a Golang CLI program to invoke such commands?

**Comment by maxandersen** [comment]
Quarkus command mode should suffice should it not ?

**Comment by anhldbk** [comment]
@maxandersen Please explain.

In the related [issue](https://github.com/quarkusio/quarkus/issues/6026), we have 2 following requirements:

```
enable sdk install quarkus (osx/linux)
enable brew install quarkus (osx)
```

How does the command mode fulfill such requirement?

**Comment by maxandersen** [comment]
Quarkus can compile to a native executable.

**Comment by maxandersen** [comment]
ad even if it was just a jar that can be installed using brew and sdkman too.

**Comment by gastaldi** [comment]
I have started something in: https://github.com/gastaldi/quarkus-cli

**Comment by maxandersen** [comment]
> I have started something in: https://github.com/gastaldi/quarkus-cli

there already are a cli in /devtools/aesh and update coming here https://github.com/quarkusio/quarkus/pull/9783 we do want to get that updated/aligned but lets not create it externally as the cli would heavily depend on the code in the core devtools repo anyway.

**Comment by maxandersen** [comment]
closing as cli been updated and moved forward since.
