### ISSUE TITLE
keycloak-authorization - ProtectedResource - if-check in bodyClaim 

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6037]
https://github.com/quarkusio/quarkus/blob/master/integration-tests/keycloak-authorization/src/main/java/io/quarkus/it/keycloak/ProtectedResource.java#L62

current `if (body == null && !body.containsKey("from-body")) {` is weird

shouldn't it be
 * `if (body != null && !body.containsKey("from-body")) {` 
or 
 * `if (body == null || !body.containsKey("from-body")) { `
?

**Comment by gsmet** [comment]
@sberyozkin can you make sure this gets fixed soon? I think we will want a fix in 1.1.0.
