### ISSUE TITLE
@Fallback failing to add non-public methods during DCE  

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#6075]
**Describe the bug**
following https://quarkus.io/quarkus-workshops/super-heros/#_adding_fallbacks works in vm mode, but you eventually bump into that when using native that it will fail with an error like: 

```
javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Fallback method fallbackRandomHero with same parameters as findRandomHero not found
[2] Fallback method fallbackRandomVillain with same parameters as findRandomVillain not found
**Expected behavior**
(Describe the expected behavior clearly and concisely.)
```

by adding `public` to the method declarations it works in both vm and native mode.

**Comment by Lukkie** [comment]
I also had to register the methods for reflection. Seems like something that should be done automatically.

**Comment by geoand** [comment]
Is this still an issue?

cc @Ladicek

**Comment by Ladicek** [comment]
This was actually fixed (without knowing that this issue exists) in #17328, see https://github.com/quarkusio/quarkus/pull/17328/files#diff-f369a51a14f22acf3d2188a35fbe3961013168f437e1e96d7e915cab2e24e7cf
