### ISSUE TITLE
Panache: provide entityManager instance/proxy

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#6080]
**Description**
Please provide a thread-safe `entityManager`(-proxy) from within a `PanacheEntity`. For example by `PanacheEntity.entityManager`:

```
@Entity
public Person extends PanacheEntity implements Serializable {

   public static final checkPerson(Person p) {

       // get thread-safe entityManager from PanacheEntity
       var em = PanacheEntity.entityManager;

       // use em for direct entityManager operations:
       var containsEntity = em.contains(p);
       var session = em.unwrap(Session.class);

       // illustrates different entityManager operations:
       em.flush();
       em.clear();
       em.getEntityManagerFactory().getCache().evictAll();
       ..
    }

}
```

Actually I need to have a `PanacheRepository` if I want to access an `entityManager`-instance:

```
@ApplicationScoped
public class PersonRepository implements PanacheRepository<Person> {

    @Inject EntityManager em;
}
```

**Comment by emmanuelbernard** [comment]
One question @nimo23 , why a "thread-safe" entity manager? EntityManager by their nature are not thread safe, nor are entities. I wonder what you have in mind.

**Comment by nimo23** [comment]
> EntityManager by their nature are not thread safe

@emmanuelbernard yes, I know. The entityManager must not be accessed concurrently. By default, when using CDI injected entityManager, the container provides a new entityManager for each calling thread - in a different thread (for any scope) you will have a different EntityManager delegate by default.

I don't know how or if ARC injects an entityManager in such a way as https://developer.jboss.org/message/990458#990458 (the CDI way). Normally, injecting an entityManager within `@Singletons` or `@ApplicationScoped` should be safe. 

I ment "thread-safe" in the sense of providing a new EntityManager delegate for each calling thread.

**Comment by emmanuelbernard** [comment]
yes we do have transaction scoped entity managers

**Comment by nimo23** [comment]
Ok thanks, so I will close this because of https://github.com/quarkusio/quarkus/issues/7233
