### ISSUE TITLE
logging: Provide a /loggers endpoint for configuring the services log levels at runtime

### ISSUE THREAD

**Issue by damianoneill** [quarkusio/quarkus#6083]
**Description**
Provide a loggers endpoint that gives access to the service's loggers and the configuration of their levels.

**Implementation ideas**
The solution should consider providing the logger(s) through GET requests to the endpoint for the collection of loggers or appending to the GET endpoint a logger name to filter a specific logger.

The solution should consider setting the log level through a POST against the endpoint with a logger name with a specific level.

**Comment by gastaldi** [comment]
Closing this ticket on behalf of https://github.com/quarkusio/quarkus/issues/9482, which has more comments. Thank you ;)
