### ISSUE TITLE
build native via docker could have more informative error messages

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#6084]
**Describe the bug**
Someone did the superhero workshop and kicked of native builds on windows via docker (`./mvnw package -Pnative -Dquarkus.native.container-build=true
`) for all 4-5 services exhausting his docker allocated resources.

For the user the experience was three very slow builds (10-20 minutes) and a fourth that errored with something the lines: "Docker build exited with exit code 137".

would be good if we recognized the exit code and was a bit more informative, somtehing like:

"Docker build exited with exit code 137. This indicates the build hit a memory or cpu resource limit. Ensure your docker environment have enough memory or cpu available"

That would have helped user to realize what he was actually doing by running these parallel builds.

**Comment by gsmet** [comment]
We had two users asking the exact same thing yesterday and today. 

I’m wondering if it’s something we should get fixed in GraalVM instead?

**Comment by maxandersen** [comment]
Its not really graalvm failing - it’s the container running out of memory causing docker containers/process to fail. 

Of course graalvm could probably add better out of memory handling but since we are the one starting docker and receiving the 137 error code; we are in the position to give a better/more informative error message.

**Comment by gsmet** [comment]
On Wed, Dec 11, 2019 at 12:58 PM Max Rydahl Andersen <
notifications@github.com> wrote:

> Its not really graalvm failing - it’s the container running out of memory
> causing docker containers/process to fail.
>
No, it's GraalVM failing. You have the exact same exit code with plain old
GraalVM.

I had it a couple of times on my laptop and I don't do container builds.

-- 
Guillaume

**Comment by emmanuelbernard** [comment]
yes so we could wrap the error in our maven plugin but fixing upstream in graalVM would be nicer.

**Comment by geoand** [comment]
This keeps on coming up on chat. I propose that we implement a special handling for this one case now since it's the most common one and would go a long way to make users feel more in control

**Comment by geoand** [comment]
I did a quick dirty check with: https://github.com/quarkusio/quarkus/pull/7645

I believe it's way better than nothing having anything at this point since I have lost count of how many times we have answered this question in chat
