### ISSUE TITLE
Support `application/jwk-set+json` content type when processing responses from JWKS Endpoint

### ISSUE THREAD

**Issue by pedroigor** [quarkusio/quarkus#6087]
**Describe the bug**
`quarkus-oidc` not considering the `application/jwk-set+json` content type when processing responses from the JWKS endpoint.

**Expected behavior**
Accordingly with the [specs](https://tools.ietf.org/html/rfc7517) the `application/jwk-set+json` can be used to indicate that the content is a JWKS.

**Actual behavior**
Cannot handle content type: application/jwk-set+json; charset=UTF-8

**To Reproduce**
1. Install `quarkus-oidc` extension
2. Point to a OP that uses the `application/jwk-set+json` content type in responses from JWKS Endpoint

**Configuration**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 - v1.0.1.Final

**Additional context**
The issue was found when integrating with Identity Server 4.

**Comment by pedroigor** [comment]
@sberyozkin @pmlopes Vert.x OAuth seems to be considering only `application/json` when processing JWKS responses. Does make sense to also include `application/jwk-set+json` in the list of valid content types ?

**Comment by sberyozkin** [comment]
@pedroigor it is a standard JWK set type, so yes :-). Let me open a Vertx issue

**Comment by pedroigor** [comment]
@sberyozkin btw, shall we start documenting the OPs we can integrate with ? As well as have a "interoperability" label to differentiate such issues ?

**Comment by sberyozkin** [comment]
@pedroigor Good idea, right now such issues are indirectly described as such in #5874. I can add  `oidc-interoperability` label. I'd like to retain though the option of clicking on `component:oidc` and seeing all the OIDC issues, so please add both labels for the interop issues

**Comment by sberyozkin** [comment]
Paulo fixed it in Vertx OAuth2
