### ISSUE TITLE
quarkus:remote-dev doesn't update pom dependencies

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#6100]
**Describe the bug**
When running `:remote-dev`, additions to the pom.xml dependencies have no effect on the remotely running Quarkus.

**Expected behavior**
Dependencies in the remote dev mode are updated and potentially loaded from Maven Central (similar to local process).

**Actual behavior**
The remote dev mode doesn't seem to be notified about the change; the
locally running `:remote-dev` doesn't log the change either:
```
...
Scan complete changed srcs [] changes resources {}
```

**To Reproduce**
1. Setup `quarkus:dev` on a remote machine / container and `quarkus:remote-dev` on localhost correctly.
2. Assert that Java resource changes are updated on the remote machine
3. Add a pom.xml dependency, e.g. `quarkus-smallrye-health`
4. Nothing happens

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux archlinux 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux`
 - Output of `java -version`: `openjdk version "13.0.1" 2019-10-15 \n OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9) \n Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 13 Linux amd64-64-Bit Compressed References 20191021_96 (JIT enabled, AOT enabled)`
 - Quarkus version or git rev: `1.0.1.Final`

**Comment by stuartwdouglas** [comment]
I will try and get this into 1.2, as well as a CRC/hash based sync on connect to make sure everything is up to date.

**Comment by maxandersen** [comment]
related to #5917
