### ISSUE TITLE
[Tooling] Maven add-extension should add the extension before the "test" dependencies

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#6108]
**Describe the bug**
I like clean pom.xml, when using Quarkus Maven plugin "add-extension", if there are grouped "test" dependencies at the end, the extension should be added before it.

**Expected behavior**
Keep the pom.xml clean

**Actual behavior**
The extension is added at the end

**Comment by gastaldi** [comment]
Same for Gradle

**Comment by ia3andy** [comment]
Bonus point if all Quarkus extensions try also to be grouped together..

**Comment by ia3andy** [comment]
@mgorniew after you current PR, maybe you would like that one? it should be fairly easy now?

**Comment by mgorniew** [comment]
@ia3andy Sure, I can look into it.
