### ISSUE TITLE
Support Hibernate Envers configuration properties

### ISSUE THREAD

**Issue by vc-void** [quarkusio/quarkus#6112]
**Description**
Currently Envers supports several configuration properties, e.g. `org.hibernate.envers.default_schema`. To me it makes sense to add support for some or all of these properties on the application.properties file.

**Comment by knutwannheden** [comment]
Another one would be `org.hibernate.envers.revision_listener`.

**Comment by Sanne** [comment]
This should follow up onto #3894

**Comment by bbcjunior** [comment]
@Sanne Is there a way of changing the name of the TableSuffix and the name of the REV and REVTYPE columns of the Hibernate Envers auditing tables in Quarkus without using the persistence.xml properties? I couldn´t find those properties for the Envers extension in the application.properties.
That would be org.hibernate.envers.auditTableSuffix, org.hibernate.envers.revisionFieldName and org.hibernate.envers.revisionTypeFieldName respectively.

**Comment by moisaluc** [comment]
Hi, are these guys already supported?

- org.hibernate.envers.audit_strategy

- org.hibernate.envers.do_not_audit_optimistic_locking_field

And if not, would it be possible for them to be added?
We are migrating from an EJB application and would like to drop the existing persistence.xml file and go full application.properties in configuring it.

**Comment by Sanne** [comment]
hi @moisaluc - no these aren't supported yet; please open a new issue to track the request: it should be really straight forward.

You could also try to contribute the patch yourself; have a look at the previous patch for an example:
 - https://github.com/quarkusio/quarkus/pull/21289/files
