### ISSUE TITLE
quarkus-maven-plugin default version mismatch with quarkus

### ISSUE THREAD

**Issue by sreev** [quarkusio/quarkus#6122]
**Describe the bug**
run this command to create a sample quarkus project.
`$ mvn io.quarkus:quarkus-maven-plugin:create -DprojectGroupId=com.company -DprojectArtifactId=sample-kogito -Dextensions="kogito"
`

**Expected behavior**
create project successfully.

**Actual behavior**
Fails with this error because quarkus-maven-plugin default version mismatch with quarkus.

`[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.1.0.CR1:create (default-cli) on project standalone-pom: Execution default-cli of goal io.quarkus:quarkus-maven-plugin:1.1.0.CR1:create failed: Failed to load templates/README.maven.ftl: Failed to locate templates/README.maven.ftl in /Users/svaddi/.m2/repository/io/quarkus/quarkus-platform-descriptor-json/1.0.1.Final/quarkus-platform-descriptor-json-1.0.1.Final.jar -> [Help 1]
`
**To Reproduce**
run the above command.

**Configuration**
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin MacBook-Pro 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64

 - Output of `java -version`:
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

 - Quarkus version or git rev:
1.0.1.Final

**Additional context**
n/a

**Comment by sreev** [comment]
hack/fix: match the plugin version and run, again.

`
$ mvn io.quarkus:quarkus-maven-plugin:1.0.1.Final:create -DprojectGroupId=com.company -DprojectArtifactId=sample-kogito -Dextensions="kogito"
`

**Comment by geoand** [comment]
I wasn't able to reproduce this actually...

Just doing `mvn io.quarkus:quarkus-maven-plugin:create -DprojectGroupId=com.company -DprojectArtifactId=sample-kogito -Dextensions="kogito" ` worked just fine for me.

**Comment by gastaldi** [comment]
Because Maven resolves to the latest available version and the `quarkus-platform` 1.1.0.CR1 artifact doesn't exist yet, you need to add ` -DplatformArtifactId=quarkus-bom` to the command.

**Comment by gsmet** [comment]
I think the issue is that you need to use the version in the `create-project` command as we have documented it in all our guides:

> mvn io.quarkus:quarkus-maven-plugin:1.0.1.Final:create -DprojectGroupId=com.company -DprojectArtifactId=sample-kogito -Dextensions="kogito"

This should work and use the latest Final.

**Comment by famod** [comment]
> You need to add ` -DplatformArtifactId=quarkus-bom` to the command if you want to use the latest and greatest version for now

That works (1.1.0.Final). Might be worth to mention this property on the [getting-started page](https://quarkus.io/guides/getting-started)?

**Comment by geoand** [comment]
I think we have updated the Maven tooling guide to include this information

**Comment by sreev** [comment]
`$ mvn archetype:generate`, doesn't show this plugin.
Refer to:
https://maven.apache.org/archetype/maven-archetype-plugin/usage.html

https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

**Comment by geoand** [comment]
I am pretty sure that this has since been fixed, so I'll close the issue.
If this is not the case, feel free to comment and/or reopen
