### ISSUE TITLE
Readable pom.xml format on quarkus:create or :add-extension

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#6137]
**Description**
The pom.xml format doesn't provide a nice overview with all the Quarkus extensions and plugin definitions, when running `:create`, or worse, after running `:add-extension`, which messes up the previously formatted pom.xml.

It would help the readability, especially with the larger number of dependencies, if the pom.xml includes blank lines after some blocks.

**Format ideas**

```xml
<dependencyManagement>
    ...
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    ...
</dependencies>

<build>
    <finalName>quarkus-playground</finalName>
    ...
</build>

<properties>
    <quarkus.version>1.0.1.Final</quarkus.version>
    <maven.compiler.source>13</maven.compiler.source>
    <maven.compiler.target>13</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>
```

**Comment by geoand** [comment]
Does this Quarkus CLI deal with this nowadays?

**Comment by gsmet** [comment]
No. Unfortunately, the file is written by something which writes the entire file with a less than ideal formatting.

For adding extensions, we should probably use an approach similar to what OpenRewrite does and be careful respecting the formatting (and especially, we shouldn't remove the comments that were in the POM...).

I'll have a look at ways to improve the situation a bit.

**Comment by gsmet** [comment]
I will close this one as I centralized all the problems here: https://github.com/quarkusio/quarkus/issues/39088
