### ISSUE TITLE
FaultToleranceDefinitionException in binary mode

### ISSUE THREAD

**Issue by jefrajames** [quarkusio/quarkus#6142]
**Describe the bug**
A FaultToleranceDefinitionException is generated at startup when defining a Fallback method on a CDI bean (ApplicationScoped):
`
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:201)
	at io.quarkus.runtime.Application.start(Application.java:94)
	at io.quarkus.runtime.Application.run(Application.java:218)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: javax.enterprise.inject.spi.DeploymentException: org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceDefinitionException: Fallback method hello with same parameters as bonjour not found
`
 It looks like the fallback method is not found. The same code works well in JVM mode.

A [demo project](https://github.com/jefrajames/quarkus-microprofile-fault-tolerance-quick-start) derived from the FaultTolerance QuickStart is available on my GitHub.

**Expected behavior**
Fallback method should be called every other time.

**Actual behavior**
FaultToleranceDefinitionException at application startup.

**To Reproduce**

1. Start from the Fault Tolerance quick start
2. Add a GreetingService CDI bean with a method defining a fallback
3. Call GreetingService from CoffeeResource.

Everything detailed and reproducibale with my [demo project](https://github.com/jefrajames/quarkus-microprofile-fault-tolerance-quick-start).

**Configuration**
# Add your application.properties here, if applicable.
empty

**Screenshots**
None.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: MacOS 10.13.6
 - Output of `java -version`: openjdk version "11.0.5" 2019-10-15
 - GraalVM version (if different from Java): 19.2.1
 - Quarkus version or git rev: 1.0.1.Final

**Additional context**
Nothing special.

**Comment by jefrajames** [comment]
I've done some investigations. It works by adding @RegisterForReflection on the GreetingService CDI bean that has the @Fallback annotation. I leave the issue open since I think it deserves to be mentioned in the documentation : If you make use of @Fallback on a CDI bean with a local method, don't forget the @RegisterForReflection on that same class to enable reflection!

**Comment by geoand** [comment]
@Ladicek can this now be closed?

**Comment by Ladicek** [comment]
I have never seen this issue, but we do register all fallback methods for reflection (see https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java#L116-L152), so indeed this can be closed.
