### ISSUE TITLE
Wrap UriBuilder class

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#6146]
**Description**

Actually when you create a new entity and you are using REST, you want to use the `Response.created` which required an `URI` because it is a good practice to add the `Location` header.

The problem is that to make it work you need to do something like:

```
return Response
                .created(
                     UriBuilder.fromResource(DeveloperResource.class)
                        .path(Long.toString(developer.getId())).build())
                        .entity(developer).build();
```
Notice the amount of chain calls + calls to `build` methods I need to call and also since I am using Panache and the id is a Long I need to convert that long to string

**Implementation ideas**

Why not provide some kind of wrapper around `UriBuilder` so I can do something like:

`Response.created(QuarkusUriBuilder.uri(DeveloperResource.class, dev.getId())``

Or even better make that the entity is responsible to do it (`Response.created(developer.getUri(DeveloperResource.class)`

**Comment by sberyozkin** [comment]
@lordofthejars it may be simpler to get the baseUriBuilder from UriInfo context, can you please check if it works for you ?

**Comment by lordofthejars** [comment]
isn't the same? At the end it is a UriBuilder and I will need to still do the Long.toString, isn't it?

**Comment by sberyozkin** [comment]
At least it would avoid referring to `DevelopeResource.class` which is indeed not looking good. it s unfortunate though there are no `path` setters accepting the numbers, so yes `Long.toString(developer.getId()` would remain

**Comment by geoand** [comment]
[Renarde](https://github.com/quarkiverse/quarkus-renarde) already has something like this
