### ISSUE TITLE
Creation of custom MP Context Propagation objects fails

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#6148]
**Describe the bug**
When defining a producer for an own `ManagedExecutor`, or `ThreadContext`, the creation fails with a deployment exception:

The following describes the error for `ManagedExecutor`, the same is true for other MicroProfile Context Propagation types.

```
[1] Ambiguous dependencies for type org.eclipse.microprofile.context.ManagedExecutor and qualifiers [@Default]
	- java member: com.sebastian_daschner.coffee.mp_cp.BulkheadExampleResource#readExecutor
	- declared on CLASS bean [types=[com.sebastian_daschner.coffee.mp_cp.BulkheadExampleResource], qualifiers=[@Default, @Any], target=com.sebastian_daschner.coffee.mp_cp.BulkheadExampleResource]
	- available beans:
		- PRODUCER METHOD bean [types=[java.util.concurrent.Executor, org.eclipse.microprofile.context.ManagedExecutor, java.util.concurrent.ExecutorService, java.lang.Object], qualifiers=[@Default, @Any], target=org.eclipse.microprofile.context.ManagedExecutor managedExecutor(), declaringBean=com.sebastian_daschner.coffee.mp_cp.ManagedExecutorProducer]
		- PRODUCER METHOD bean [types=[org.eclipse.microprofile.context.ManagedExecutor], qualifiers=[@Default, @Any], target=org.eclipse.microprofile.context.ManagedExecutor getAllManagedExecutor(), declaringBean=io.quarkus.smallrye.context.runtime.SmallRyeContextPropagationProvider]
```

The SmallRye implementation seems to define their own, which then collides.

**Expected behavior**
I expect the following examples to work, as described in the spec:

**To Reproduce**

```java
public class ManagedExecutorProducer {

    @Produces
    ManagedExecutor managedExecutor() {
        System.out.println("creating managed executor");

        return ManagedExecutor.builder()
                .propagated(ThreadContext.CDI, ThreadContext.APPLICATION)
                .maxAsync(4)
                .maxQueued(4)
                .build();
    }

    public void disposeManagedExecutor(@Disposes ManagedExecutor managedExecutor) {
        System.out.println("disposing managed executor");
        managedExecutor.shutdownNow();
    }
}
```

Also see [here](https://github.com/sdaschner/quarkus-playground/tree/mp-cp/src/main/java/com/sebastian_daschner/coffee/mp_cp)

Also see my [blog post](https://blog.sebastian-daschner.com/entries/context-asynchronous-execution-bulkheads-microprofile)

Tested with Quarkus version `1.0.1.Final`

**Suggestion**

To resolve it, maybe it helps to annotate `SmallRyeContextPropagationProvider#getAllManagedExecutor` (and others) with `@DefaultBean`?

**Comment by geoand** [comment]
cc @manovotn  @FroMage

**Comment by FroMage** [comment]
We could do that indeed, but be careful that your executor will not use the Quarkus worker pool and will not propagate jax-rs, transactions, servlet so it will only work in very narrow use-cases. We really advise against doing something like this.

**Comment by sdaschner** [comment]
Hi @FroMage 

I've been using this example to create multiple bulkheads (i.e. seperate thread pools), thus not using the Quarkus worker pool is desired (right?).

> will not propagate jax-rs, transactions, servlet

I'm not sure whether I fully understand that. For this bulkhead example, I would not like to propagate an existing transaction (in my case I start the execution right at the JAX-RS resource anyway). But I'd expect that the specified `propagated` scopes or anything provided by a `ThreadContext` propagates as expected, or am I missing something?

**Comment by FroMage** [comment]
Well it depends what you will need to do in your propagated code. If you're not using anything related to JAX-RS contexts or transactions or servlets, it could work fine. But that's always more risky than propagating every context.

**Comment by sdaschner** [comment]
Right. The user can still start independent transactions, as long as they don't reuse things that aren't propagated, but that's in general the issue with this spec :)

**Comment by FroMage** [comment]
That's why it's safer to propagate everything.

**Comment by manovotn** [comment]
I think back when we integrated MP CP, the notion of `@DefaultBean` wasn't there yet. It certainly sounds logical to do that.

The other approach/option would be to support what SR impl has but Quarkus doesn't yet (we didn't have the CDI build extension capabilities back there) - in SR you can define your executor just by specifying the injection point with a config annotation and the given executor (or thread context) is created for you. The upside is that being responsible for creation, we could make use of the Quarkus thread pool below, while giving user the power to propagate contexts they want.
[This test](https://github.com/smallrye/smallrye-context-propagation/blob/master/tests/src/test/java/io/smallrye/context/test/cdi/providedBeans/BeanWithInjectionPoints.java#L29-L61) shows how it works.

**Comment by sdaschner** [comment]
@manovotn Does SmallRye on it's own supports this feature of MP CP, to define custom `ThreadContext` and `ManagedExecutor`? Correct me if I'm wrong, but the current behavior looks like a bug to me.

**Comment by manovotn** [comment]
@sdaschner  MP CP spec allow you to define producers for custom ME and TC. It however doesn't provide any ME/TC by default. The config option I described above is also purely SmallRye thing, not in the spec.

So basically, current behavior of having a default one is undefined by specification and we have it in place to allow users to grab an executor that uses our predefined thread pools that we manage.
It should be override-able, in fact it is even now, but you would need to write `AnnotationsTransformer` for that and veto those beans ;-)

**Comment by sdaschner** [comment]
> So basically, current behavior of having a default one is undefined by specification and we have it in place to allow users to grab an executor that uses our predefined thread pools that we manage.
It should be override-able, in fact it is even now, but you would need to write AnnotationsTransformer for that and veto those beans ;-)

Got it, thanks. Is there anything I can help with?

**Comment by manovotn** [comment]
I will send a PR to make the provided beans default and provide a test for that.
If you want to test your CDI build extension prowess, you could try and port that config behavior, but I don't mean to force you into that as it might be trickier. Either way, I'll create a tracking issue for that and link it here.

**Comment by manovotn** [comment]
PR solving this up available here - https://github.com/quarkusio/quarkus/pull/6154
Follow up issue for porting SR CP capabilities is here - https://github.com/quarkusio/quarkus/issues/6156

**Comment by sdaschner** [comment]
Wow, that's fast, thanks already!

I'd be happy to learn more about CDI build extensions, never touched them so far (only default, standard CDI stuff), but I'd need some pointers how to get started...

**Comment by manovotn** [comment]
Most is documented here - https://quarkus.io/guides/cdi-reference#build-time-extension-points
You'd need to first take a look at what the original CDI extension does (what extension lifecycle methods are used) and then try to map that to the build time extensions we have. They certainly aren't 1:1 but we should have a replacement for the functionality provided by each.

An examples of many build time extensions can be found within various Quarkus extensions, you could `grep` those to see some usage.
