### ISSUE TITLE
artemis-jms breaks resteasy-jsonb

### ISSUE THREAD

**Issue by bender316** [quarkusio/quarkus#6153]
**Describe the bug**
After adding artemis-jms extension to a project which already uses resteasy-jsonb extension calls to JAX-RS endpoints fail with the following exception:
`Caused by: java.lang.AbstractMethodError: Receiver class org.apache.johnzon.core.JsonGeneratorImpl does not define or inherit an implementation of the resolved method 'abstract javax.json.stream.JsonGenerator writeKey(java.lang.String)' of interface javax.json.stream.JsonGenerator`

**To Reproduce**
1. add artemis-jms extension to a project which uses resteasy-jsonb
2. make a call to an JAX-RS endpoint

**Environment (please complete the following information):**
 - Quarkus version: 1.0.1

**Additional context**
The problem occurs since artemis dependencies bring the johnzon lib which then in turn is used as the default JSONP provider. And the referenced johnzon version is not compatible with JSONP 1.1.
Getting rid of the problem is either to exclude johnzon from dependency resolution or to create a file under "META-INF/services/javax.json.spi.JsonProvider" which then points back to org.glassfish.json.JsonProviderImpl

**Comment by gsmet** [comment]
This one is already fixed in current master and will be included in the upcoming 1.1.0.Final.

See https://github.com/quarkusio/quarkus/pull/5052/commits .

Thanks for raising the issue though!
