### ISSUE TITLE
Handle escaping in Qute

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#6155]
Right now, Qute doesn't handle escaping at all and doesn't provide any facility for escaping. This is an issue as that means that users will easily have XSS issues.

My inclination would be to enable escaping by default.

The escaping should be different for each content-type.

We need to check how we will properly handle tag content escaping and attribute escaping in HTML. We need to be sure our escaping works for both and a value escaped in an attribute still has the same value as previously when submitted through a form (think of `input value=""`: if we inject a value here, we want the submitted value to be exactly the same as the injected one).

**Comment by mkouba** [comment]
> and doesn't provide any facility for escaping

In fact, we have SPI for this: `io.quarkus.qute.ResultMapper` but no default implementation ATM ;-).

**Comment by FroMage** [comment]
- We want escaping by default but it has to be content-type specific. 
  - For HTML `'"<>&` could be enough
- We need a `RawString` type which is not escaped
  - This allows us to add `RawString markdown(String text)` extension methods which return HTML
  - And `RawString raw(String text)` to be able to disable escaping in templates using `foo.stringAttribute.raw`

**Comment by mkouba** [comment]
What's `RawString markdown(String text)` useful for?

**Comment by FroMage** [comment]
To render a markdown string to html (or txt based on expected content-type). We should have an asciidoc one too, of course :)

**Comment by mkouba** [comment]
I see. That an interesting one but I think I'll create another issue.

**Comment by FroMage** [comment]
Yeah, I was just showing use-cases.
