### ISSUE TITLE
Should log if it's building on GraalVM JDK8 vs JDK11

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#6162]
**Description**
currently during the build I'm getting

`Running Quarkus native-image plugin on GraalVM Version 19.3.0 CE`

It should clearly state also the JDK version.

**Comment by gsmet** [comment]
Right now, it's displaying what `native-image` says. They don't distinguish things between Java 8 or 11.

**Comment by jaikiran** [comment]
This support was requested by someone else from the Graal image itself here https://github.com/oracle/graal/issues/1911

**Comment by jaikiran** [comment]
I've opened https://github.com/oracle/graal/pull/2148 with a change to support this.

**Comment by Sanne** [comment]
thanks @jaikiran !

**Comment by jaikiran** [comment]
With Graal 20.1.0 now being integrated into Quarkus, the log message will now cleraly show the Java version being used.
An example from one of the recent CI runs against Quarkus master:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.1.0 (Java Version 11.0.7)
```
 Closing this enhancement request.

**Comment by Sanne** [comment]
Awesome, thanks again!
