### ISSUE TITLE
documentation: compare Qute vs already existing templating engines

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#6163]
**Description**
Please clarify in the **official documentation** why implementing a new templating language in quarkus instead of **re-using or adapting** already existing templating engines in quarkus? 

For example, why not using _Jakarte Expression Language_, _JSF_ based on Jakarte EL or _vertx templating engine_ with different languages (which also supports server side rendering). What are the differences, benefits when using Qute? I think, the big benefit is that it can also be used in native mode and in any kind of file (html, txt, java, properties, yaml, etc.). However, I am not sure if Qute is more secure than jsf (cdi-scoping, escaping, csrf, etc.) or does provide composition-tags (include, etc). 

Please provide comparison between qute and others (jsf, vertx-templating,..).

**Comment by gsmet** [comment]
Qute has been designed to allow moving as much work as possible as build time.

The existing template engines are not designed for that.

Qute documentation is coming soon.
