### ISSUE TITLE
Qute parser - show the template path and line number in error messages

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#6164]
We do show this info when validating template expressions.

**Comment by angelozerr** [comment]
To support Qute validation inside an editor (with syntax error) like https://github.com/redhat-developer/vscode-quarkus/issues/178 it's very important to have detailed information about the error:

 * the character, line where there are error or the offset
 * the full file name where there is an error

For instance:

`Hello {name !`

should report an error in line=0, character=11, or offset =11.

Ideally, the error should be an error range to highlight the {name interpolation:

 * start line=0, start character = 6, end line = 0, end character = 11

Error reporting is an hard thing to manage but please consider it if you want to have an advanced editor which highlights syntax error. 

If this Qute parser could be more tolerant we could report several errors.
