### ISSUE TITLE
Fails to run? Quarkus with GraalVM Community Edition based on OpenJDK 11.0.5

### ISSUE THREAD

**Issue by PhilAndrew** [quarkusio/quarkus#6175]
GraalVM Community Edition based on OpenJDK 11.0.5

On Ubuntu, I downloaded and installed GraalVM
"graalvm-ce-java11-linux-amd64-19.3.0.tar.gz"

Then I tried https://quarkus.io/guides/getting-started with this GraalVM as the java and javac

When I run it, it fails and I have a guess that its due to a Java reflection problem. Is this the expected outcome?

```
philip@philip-All-Series:~/home/projects/cef-demos/build/src/getting-started$ mvn quarkus:dev
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.acme:getting-started >----------------------
[INFO] Building getting-started 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.0.1.Final:dev (default-cli) @ getting-started ---
OpenJDK 64-Bit GraalVM CE 19.3.0 warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
Listening for transport dt_socket at address: 5005
21:39:00,070 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.IllegalAccessError: class io.quarkus.deployment.steps.NativeImageAutoFeatureStep (in unnamed module @0x6221a451) cannot access class org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport (in module org.graalvm.sdk) because module org.graalvm.sdk does not export org.graalvm.nativeimage.impl to unnamed module @0x6221a451
	at io.quarkus.deployment.steps.NativeImageAutoFeatureStep.<clinit>(NativeImageAutoFeatureStep.java:49)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:31)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:248)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:144)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:88)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:111)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)

21:39:00,088 INFO  [io.qua.dev.DevModeMain] Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
```

**Comment by gsmet** [comment]
We don't support Java 11 with GraalVM for now. We are actively working on it but it's not an easy one.

Furthermore, we don't support GraalVM 19.3 yet.

**Comment by PhilAndrew** [comment]
Hi, ok so I did a little more investigation I found this works https://www.baeldung.com/quarkus-io with GraalVM, so following that tutorials instructions it works. What is the difference here? I guess its the version of Quarkus which was 0.13.1 and maybe it was working then with GraalVM.

Going back to your support statement, ok thanks to let me know, I understand not supported means it may or may not work and you people are trying to get it to work and get it back to supported.

**Comment by gsmet** [comment]
No, in this case, it means it won't work :).

If you want to use native images, you have to build with Java 8 and use GraalVM 19.2.1. Any other combination won't work.

If you only want to build a jar, you can use JDK 8 or JDK 11+.

GraalVM 19.3.0 has some serious issues and we can't support it for now.

**Comment by PhilAndrew** [comment]
Just to clear up a small misunderstanding, I didn't want to do native build, I wanted to just run it with GraalVM through the command line using `mvn quarkus:dev`

Maybe later I would want to do native build, but I wanted to be able to use GraalVM to run, that was my goal.
