### ISSUE TITLE
Remove the GraalVM workarounds that are no longer required with 19.3.1

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#6179]
As suggested by @jaikiran [here](https://github.com/quarkusio/quarkus/pull/6169#issuecomment-565719445), we introduced several workarounds for GraalVM issues into the Quarkus code lately. Most of them were introduced to fix GraalVM `19.3.0` issues but we also did that for previous GraalVM versions. Once GraalVM `19.3.1` is there, we should remove from the Quarkus code all of these workarounds that are no longer required because they were fixed in GraalVM itself.

Let's start a list of the workarounds that should be removed:
- ~https://github.com/quarkusio/quarkus/pull/6090~ Removed in #6364
- ~https://github.com/quarkusio/quarkus/pull/6169~ Removed in #6364
- ~[io.quarkus.runtime.graal.FieldReplacement](https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/graal/FieldReplacement.java)~ Removed in #6792
- ~[io.quarkus.vertx.core.runtime.graal.Target_sun_nio_ch_DatagramChannelImpl](https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/graal/JdkSubstitutions.java#L80)~ Removed in #6449 
- https://github.com/quarkusio/quarkus/commit/43e36e5daa104b97c319f945d55da307b6779800
- ~https://github.com/quarkusio/quarkus/commit/0f2d90f9b3c384d92945cf7797022b4e070584e9~ Removed in #6364
- ~https://github.com/quarkusio/quarkus/pull/5358/commits/85d8746449961b1e025768a12000cf217d19414a~ Tests done with GraalVM 19.3.1 showed that this commit shouldn't be removed

**Comment by gsmet** [comment]
@gwenneg what's the status of this one?

**Comment by gwenneg** [comment]
I didn't try to remove https://github.com/quarkusio/quarkus/commit/43e36e5daa104b97c319f945d55da307b6779800 so far and I'm not sure https://github.com/quarkusio/quarkus/commit/85d8746449961b1e025768a12000cf217d19414a actually needs to be removed. I'll take a look at it tonight.
