### ISSUE TITLE
New "Launching JVM" log line appearing in quarkus:dev

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#6183]
Just launched a project with `quarkus:dev` and got that one:
```
[INFO] Launching JVM with command line: /data/opt/jdk1.8.0_221/jre/bin/java -XX:TieredStopAtLevel=1 -Xverify:none -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /tmp/jpa-example/target/jpa-example-dev.jar
```

I don't think it's something we want at the info level.

@gastaldi is this the one you tweaked the other day? Do you know when it was introduced and why?

**Comment by gsmet** [comment]
OK, so it was the one you tweaked and it was originally changed here: https://github.com/quarkusio/quarkus/pull/5366 .

@jaikiran @stuartwdouglas I can't say I agree with this. We tried hard to not be verbose and this definitely seem too verbose and technical to me.

**Comment by gastaldi** [comment]
I made the Gradle version display the same output as in Maven. The PR you linked changed to INFO but I must say I am not a big fan of it. 

IMHO it should be a debug statement using the plugin 's logger

**Comment by gsmet** [comment]
Yeah, I agree. If some of the info is useful, we need to present it another way. In the meantime, I would prefer it to go back to debug.

@gastaldi would you be up for preparing a patch?

**Comment by gastaldi** [comment]
Sure, assign this issue to me and I'll submit a PR soon

**Comment by jaikiran** [comment]
> @jaikiran @stuartwdouglas I can't say I agree with this. We tried hard to not be verbose and this definitely seem too verbose and technical to me.

Hello @gsmet, it's fine with me if we want to go back to using `DEBUG` here.
