### ISSUE TITLE
Snapshots are not published anymore to OSS

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#6184]
The last snapshots published are from December 6th AFAICS:
https://oss.sonatype.org/content/repositories/snapshots/io/quarkus/quarkus-core/999-SNAPSHOT/

What's responsible for pushing these?

/cc @cescoffier @stuartwdouglas

**Comment by stuartwdouglas** [comment]
I did not even know we were doing this, is this part of your quickstarts setup @cescoffier ?

**Comment by cescoffier** [comment]
We have a nightly build doing this, but the build fail at the moment.
https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=13637:

```
[ERROR] [ERROR] Could not find the selected project in the reactor: :quarkus-gradle-plugin @ 
```

It seems the Quarkus build structure changed and these changes were not reflected.

**Comment by maxandersen** [comment]
seems this is a problem again thus reusing it as it was never closed.

This should be trivial to move to github actions - any objections on doing that ? lets make it happen :)

**Comment by geoand** [comment]
I am going to close this as we have a dedicated GH Action that runs nightly. See https://github.com/quarkusio/quarkus/actions/workflows/deploy-snapshots.yml for more details

**Comment by maxandersen** [comment]
cool, but how come https://oss.sonatype.org/content/repositories/snapshots/io/quarkus/quarkus-core/999-SNAPSHOT/ last update then is in April 21 ?

**Comment by geoand** [comment]
See https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkus/quarkus-core/999-SNAPSHOT/ (not the use of `s01`)

**Comment by maxandersen** [comment]
ah gotcha - background info at https://central.sonatype.org/publish/publish-guide/, change in '21
