### ISSUE TITLE
Kubernetes Guide says "kubernetes.yaml" instead of "kubernetes.yml"

### ISSUE THREAD

**Issue by burrsutter** [quarkusio/quarkus#6187]
**Describe the bug**
https://quarkus.io/guides/kubernetes refers to the generated file name of "kubernetes.yaml".  

**Expected behavior**
The actual file name is "kubernetes.yml"

**Actual behavior**
https://screencast.com/t/c598ryD7bQgq

**Comment by geoand** [comment]
Thanks for reporting @burrsutter!  A PR with a fix has been opened.
