### ISSUE TITLE
Make a mcve repo to give simple steps to create a reproducer

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#6189]
**Description**
it could help to create a mvcve repo (minimal complete verifiable example) with instructions on how to create a reproducer more easily - something like https://github.com/jOOQ/jOOQ-mcve

https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/mixed.20json.20processors.20expected.20to.20not.20work.20.3F/near/183529107

**Implementation ideas**
- make a basic repo with readme and scripts needed to run our tooling to get to a reproducer
- have two branches, one for gradle and one for maven pre-seeded.

**Comment by gsmet** [comment]
If you want to do it, please do. But we didn't have any issue with people creating reproducer, novices included (once they know what a reproducer is).

As you can create a project in one command (and that's what people used to create their application), it helps.

Be aware that this will need to be updated for each release.

I think a text explaining what a reproducer is (we had several people asking for what it was) and pointers to how to create sample applications would be more useful.

My 2 cents.

**Comment by maxandersen** [comment]
> I think a text explaining what a reproducer is (we had several people asking for what it was) and pointers to how to create sample applications would be more useful.

that is basically what this would be - just that its forkable :) 

I don't think you need to update it at every release unless we radically changes the structure of a default project.

**Comment by aguibert** [comment]
FYI I already have some repos for this exact purpose, feel free to re-use:
https://github.com/aguibert/basic-quarkus-mvn
https://github.com/aguibert/basic-quarkus

I kept separate repos for Gradle vs. Maven so that I can leave them imported in my IDE. If we switch branches and change to maven <--> gradle then we'd have to delete and re-import the project in our IDE

**Comment by maxandersen** [comment]
old and outdated - people submit reproducers just fine without it :)
