### ISSUE TITLE
Unit test order fails integration test based on QuarkusTest

### ISSUE THREAD

**Issue by vietk** [quarkusio/quarkus#6190]
**Describe the bug**

I have a JAX-RS resource without a default constructor, I use this constructor to ease my mockup in a mockito unit test.
I have also a @QuarkusTest that does an integration test with Kafka, Quarkus generates the default constructor based on the content of this [PR](https://github.com/quarkusio/quarkus/pull/1875).

Both test are run with surefire plugin (mvn clean test) : 
If the mockito based unit test is run **before** the @QuarkusTest, the @QuarkusTest fails with

`Caused by: java.lang.RuntimeException: RESTEASY003190: Could not find constructor for class: org.acme.quarkus.sample.PriceResource`

**Expected behavior**
Both unit test should be run with no errors whatever the order of the tests

**Actual behavior**
The QuarkusTest fails

**To Reproduce**

I have a reproducer with the quarkus quickstarts on my [fork](https://github.com/vietk/quarkus-quickstarts/tree/bug/unit-test-fails-quarkus-test) inside the [kafka-quickstart](https://github.com/vietk/quarkus-quickstarts/tree/bug/unit-test-fails-quarkus-test/kafka-quickstart) sample.
Surefire plugin is configured to run the test alphabetically to reproduce the failure as described.

1. cd kafka-quickstart 
2. mvn clean test

**Environment (please complete the following information):**
 - java 11
 - quarkus 1.0.1.Final

Regards
Kevin

**Comment by FroMage** [comment]
Can you retry on the current master? We've had a lot of classloader changes merged in recently which fixed a lot of issues.

**Comment by stuartwdouglas** [comment]
It sounds like this should have been fixed by the ClassLoader changes in 1.3.
