### ISSUE TITLE
SpringJPA: Support spring.jpa.show-sql

### ISSUE THREAD

**Issue by aureamunoz** [quarkusio/quarkus#6192]
**Description**
From a Hackaton with Quarkus suggestions and feedbacks: 
User tried to set spring.jpa.show-sql was surprised it didn’t work.

**Implementation ideas**
My idea is create a `@ConfigRoot` and `@ConfigGroup` classes to load this property and map it to the current [`quarkus.hibernate-orm.log.sql`](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.log.sql). Anyway the new spring property would be named `quarkus.spring.jpa.show-sql`, we cannot escape to have `quarkus ` in the name. WDYT @geoand ?

**Comment by geoand** [comment]
TBH I don't have a proper solution in my head, so I would suggest you go ahead and experiment and see what actually works best.

**Comment by gsmet** [comment]
I think this asks a broader question: should we support the whole Spring configuration? Because once we have added one, it's weird to not support the others.

I must admit that I'm not sold to it.

**Comment by geoand** [comment]
I am also against adding support because it then open doors other types of Java config for Spring. Would however explore if we can detect some specific configuration options that the user might have added and perhaps propose the proper Quarkus alternatives?

**Comment by gsmet** [comment]
> Would however explore if we can detect some specific configuration options that the user might have added and perhaps propose the proper Quarkus alternatives?

That would be handy and probably relatively easy to implement.

**Comment by Sanne** [comment]
I see #6291 was merged; should we close this one?

**Comment by geoand** [comment]
Definitely, thanks for catching it @Sanne
