### ISSUE TITLE
Reactive messaging display false "warning" logs

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#6197]
**Describe the bug**
When using reactive messaging with Kafka, it shows some "warning" logs about wrong config properties when it should not.
```
2019-11-20 17:45:38,978 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (main) The configuration 'channel-name' was supplied but isn't a known config.
2019-11-20 17:45:38,986 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (main) The configuration 'connector' was supplied but isn't a known config.
2019-11-20 17:45:38,986 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (main) The configuration 'topic' was supplied but isn't a known config.
```

**Comment by anamarija** [comment]
Hi,

If nobody is working on this I can fix it.

**Comment by ia3andy** [comment]
I guess you can.. just confirm with @cescoffier

**Comment by gsmet** [comment]
IIRC, the issue is that all the config is blindly passed to Kafka, even the one specific to Reactive Messaging.

Wait for @cescoffier to weigh in but I'm pretty sure it's something that needs fixing in the Reactive Messaging implementation.

**Comment by gsmet** [comment]
BTW, this is the original message which contains important information: https://groups.google.com/d/msg/quarkus-dev/sJ9RcAJSmPE/bAyJxd-vBQAJ .

**Comment by anamarija** [comment]
Yes it is surely a fix in the smallrye messaging module.

**Comment by ia3andy** [comment]
I'll create an issue there and reference this one.

**Comment by cescoffier** [comment]
The upstream issue has been fixed, so this issue will be fixed when we update.

**Comment by cescoffier** [comment]
Closing as we integrated a version of reactive messaging containing the fix.
