### ISSUE TITLE
QUARKUS - BUILDING A NATIVE EXECUTABLE Couchbase error

### ISSUE THREAD

**Issue by previousdeveloper** [quarkusio/quarkus#6199]
**Describe the bug**
Couchbase client not connect to bucket when build with a native executable 

Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of com.couchbase.client.deps.com.lmax.disruptor.RingBufferFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to sun.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.

**Comment by geoand** [comment]
I am going to close this as there is no Couchbase extension in the Quarkus codebase
