### ISSUE TITLE
Swagger UI doesn't provide correct example

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#6202]
**Describe the bug**

When you implement a POST operation that contains a field of type LocalDate or LocalTime and you open with Swagger UI the example shows the field like:

```
"depart": {
      "airport": "BCN",
      "date": "2019-12-16",
      "terminal": "T1",
      "time": {
        "hour": "00",
        "minute": "00",
        "nano": 0,
        "second": "00"
      }
    },
```

**Expected behavior**

It should be:

```
"depart": {
      "airport": "BCN",
      "date": "2019-12-16",
      "terminal": "T1",
      "time":  "23:07:41.807"
    },
```
As this is defined in the spec (https://www.javaindeed.com/getting-started-with-json-b/) for an example.

**Actual behavior**

It is treat as a POJO.

**Additional context**

Probably you can end up customizing by using annotations but I think it should be provided correctly by default.

**Comment by gsmet** [comment]
@lordofthejars can you check if it's an issue with SmallRye OpenAPI or a Swagger UI one?

/cc @EricWittmann

**Comment by AlexanderHofmeister** [comment]
@lordofthejars FYI https://github.com/smallrye/smallrye-open-api/issues/221#event-2822411719

**Comment by phillip-kruger** [comment]
I thinks this is fixed. Can you confirm @lordofthejars ?

**Comment by phillip-kruger** [comment]
No response. Closing. @lordofthejars please reopen if this is still an issue.
