### ISSUE TITLE
/health/ready does not work in 1.1.0CR1 since the quarkus-agroal has conflicts with quarkus-reactive-pg-client

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#6203]
**Describe the bug**
http://localhost:8080/my-service/health/ready
used too work with checking the database:

With this dep,
```
<!--    <dependency>-->
<!--      <groupId>io.quarkus</groupId>-->
<!--      <artifactId>quarkus-agroal</artifactId>-->
<!--    </dependency>-->
```

but now it should be commented out,
 because it fails if, say this dependency is ON

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-reactive-pg-client</artifactId>
    </dependency>
```

If both of those deps are on it would complain about dupicated 

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

related: https://github.com/quarkusio/quarkus/issues/6170

**Comment by geoand** [comment]
Being discussed [here](https://groups.google.com/d/msg/quarkus-dev/3r0lquVsUsc/DVxX7SvQAQAJ)

**Comment by stuartwdouglas** [comment]
@gsmet I think this is fixed now?

**Comment by gsmet** [comment]
Yes, closing.
