### ISSUE TITLE
Quarkus spring data jpa does not support interface/class mapping for custom JPQL @Query in CrudRepository

### ISSUE THREAD

**Issue by kenmarito** [quarkusio/quarkus#6205]
JPQL Query does not return list of mapped interface objects as in standard Spring data but returns only list of object arrays.

**Comment by geoand** [comment]
@kenmarito Thanks for reporting.

Can you please give an example?

**Comment by kenmarito** [comment]
```java
@org.springframework.stereotype.Repository
public interface SdmFwbMappingRepo extends Repository<SdmFwbMapping, Long> {

  @Query(value =
      "SELECT DISTINCT F.atlasFwbTower As tower, R.rollupLevel1Nm AS rollupLevel1 " +
          "FROM SdmFwbMapping F " +
          "LEFT JOIN SdmRollupDim R " +
          "ON F.fwbTagUid = R.fwbTagUid")
  List<FwbToCostMapping> findAllFwbToCostMapping();

  interface FwbToCostMapping {
    String getTower();
    String getRollupLevel1();
  }
}
```
This simple method findAllFwbToCostMapping() during runtime returns List<Object[]> so after accesing arbitrary element in list, we get ClassCastException.

**Comment by geoand** [comment]
Gotcha, thanks!

**Comment by geoand** [comment]
@ebullient would you be interested in this one?

**Comment by ebullient** [comment]
Once I'm done stuffing myself with holiday cookies, yes.

**Comment by geoand** [comment]
Excellent on all accounts 👌

**Comment by ebullient** [comment]
Working on this, just so ppl know. I'm going slowly (distracted).. but there is progress

**Comment by geoand** [comment]
Cool, thanks for the update
