### ISSUE TITLE
To spy on restClient in integration test

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#6208]
**Description**

I see that there is some limitation when it comes to mocking/spying in Quarkus.

To do something similar to this with Quarkus way? 

Ultimately: To spy on restClient and see how many times it was invoked.

   ```
 @QuarkusTest
    public class MyResourceTest {

      @Inject
      @RestClient
      MyRestClient restClient;

      @Ineject
      SomeServiceThatCallRestClient someService;

      @Test
      public void test() {
         restClientSpy = spy(restClient);

         someService.doSomething();     // it would call the restClient    

         assertThat(clientSpy.times(), is(equalTo(1)));

      }
```

**Implementation ideas**
maybe some feedback, or register and listen for the events if we o not want to go with proxies.

**Comment by kenfinnigan** [comment]
Could you use WireMock as the endpoint of the REST Client so you can then capture how many times it was executed?

**Comment by Chexpir** [comment]
Using wiremock is a workaround we are applying, but it would be useful to just spy on the rest client...it does not allow it fecause it´s "final". Is it a must it´s final? Is there another reason why it does not allow it to do it?

**Comment by geoand** [comment]
This has already been implemented inthe form of `@InjectMock` and `@InjectSpy`. See https://quarkus.io/guides/getting-started-testing#further-simplification-with-injectmock and https://quarkus.io/guides/getting-started-testing#using-injectmock-with-restclient for more information
