### ISSUE TITLE
don't generate libs/*.jar if quarkus.package.uber-jar=true

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#6211]
**Describe the bug**

Tested with Gradle `./gradlew clean quarkusBuild`

We probably should not
generate `/applicationName/build/libs/applicationName.jar `if` quarkus.package.uber-jar=true`

with quarkus.package.uber-jar=true - it would create /applicationName/build/applicationName-runner.jar

There is no use of` /applicationName/build/libs/applicationName.jar, `since there is no /applicationName/build/lib has generated anyways, so not way to run this jar.

**Expected behavior**
No` /applicationName/build/libs/applicationName.jar`  generated if `quarkus.package.uber-jar=true`

**Actual behavior**
The` /applicationName/build/libs/applicationName.jar ` is generated if `quarkus.package.uber-jar=true`

**Steps to reproduce:**
1. `quarkus.package.uber-jar=true` in `application.properties`
2. `./gradlew clean quarkusBuild`

Based on https://stackoverflow.com/questions/59362663/quarkus-quarkusbuild-uber-jar-to-specific-location question.

**Comment by Sergey80** [comment]
https://stackoverflow.com/questions/59379343/quarkus-uploadarchives-with-maven-plugin-re-build-my-libs-uber-jar-to-small-one

**Comment by Sergey80** [comment]
./gradlew clean quarkusBuild quarkusUberToLibs

seems as **quarkusBuild** still doing something when the quarkusUberToLibs is about to run, and it end-up picking up a small / not uber jar. I can see it from the print(404 kb instead of 42 Mb)

```
task quarkusUberToLibs() {

    print ("\nquarkusUberToLibs task")

    print "\n Copying from : ${buildDir} with *-runner.jar to ${buildDir}/libs/ replacing -runner to ''"

    String resultingJarName

    copy {
        from "${buildDir}"
        include "*-runner.jar"
        into "${buildDir}/libs/"
        rename { String fileName ->
            print ("\ngot fileName: " + fileName)
            resultingJarName = fileName.replace("-runner", "")//.replace("-SNAPSHOT", "")
        }
    }

    final String sizeInMegabytes = new File("${buildDir}/libs/" + resultingJarName).length() / 1024 / 1024
    print "\nresulting jar:" + resultingJarName + " with file length: " + sizeInMegabytes + " Mb."
}
```

**Comment by geoand** [comment]
This is not now the case with `quarkus.package.type=uber-jar`
