### ISSUE TITLE
Overriding application.properties via file in build/config folder doesn't work with Gradle

### ISSUE THREAD

**Issue by paschi** [quarkusio/quarkus#6227]
**Describe the bug**
According to the [documentation](https://quarkus.io/guides/config#overriding-properties-at-runtime) it should be possible to override the default _application.properties_ file by placing a file with the same name in the _build/config_ folder (when using Gradle). This doesn't work currently.

**Expected behavior**
It should be possible to override the properties by using the mentioned approach.

**Actual behavior**
The override approach currently works only when using Maven, but not when using Gradle.

**To Reproduce**
1. Use the [code generator](https://code.quarkus.io/) to generate the default project. The build tool needs to be set to Gradle, everything else can be left unchanged.
2. Extract the package and add the following to _src/main/resources_:
`quarkus.http.port = 41234`
3. Run the project with `./gradlew quarkusDev`. Note the correct port in the console log:
`Listening on: http://0.0.0.0:41234`
4. Create the file _build/config/application.properties_ and set a custom port:
`quarkus.http.port = 44444`
5. After restarting via `./gradlew quarkusDev` the new port is not used:
`Listening on: http://0.0.0.0:41234`

**Environment:**
 - Operating system: Windows 10 Enterprise 64 bit
 - Java version: AdoptOpenJDK version "1.8.0_202"
 - Quarkus version: 1.0.1.Final

**Comment by geoand** [comment]
Thanks for reporting!

Have you tried this with `1.1.0.CR1`?

**Comment by paschi** [comment]
> Thanks for reporting!
> 
> Have you tried this with `1.1.0.CR1`?

I just tried with `1.1.0.Final` and it's not working there either.

**Comment by geoand** [comment]
OK, let me take a quick look

**Comment by geoand** [comment]
Basically the `config/application.properties` override is really meant for the dev-mode to be honest.
That doesn't mean it won't work - it will, you just need to figure out the proper place to put it. 
For Gradle and dev-mode that place is `build/classes/java/main`.
For Maven and dev-mode that would be simply `target`.

So I am going to close this as it works as expected. Would you perhaps like to propose a Pull Request updating the documentation adding the proper file system locations to use for this feature in dev-mode and both the build tools?

**Comment by paschi** [comment]
When using the path `build/classes/java/main` it works. Thanks for the help!

I created a pull request (#6235) for the documentation issue.

**Comment by techorix** [comment]
I currently have the same Problem with Quarkus 3.2.5 and Gradle 8.1.1. Guess this problem reappeared now. Is this cloned somewhere?
