### ISSUE TITLE
Enable CDI beans based on profiles

### ISSUE THREAD

**Issue by jonathanvila** [quarkusio/quarkus#6238]
**Description**
Based on a profile especified (env var) an Annotated bean will be added to the context or filtered out.

**Comment by geoand** [comment]
cc @mkouba

**Comment by geoand** [comment]
So the idea is to conditionally create a bean based on whether or not a profile is active, correct?

Of course this can't work with profiles defined at runtime, but seems very useful for build time profiles

**Comment by jonathanvila** [comment]
Exactly that is the idea.
Basically we can activate few beans on "test" profile, others on "prod" profile..... specially databases related beans, file persistance beans.....

**Comment by mkouba** [comment]
> Of course this can't work with profiles defined at runtime, but seems very useful for build time profiles

Hm, that's something I'm concerned about. The first question will be "I do set my profile to `staging` when running my app and the beans are still there, why?".

**Comment by geoand** [comment]
Yes... 

Just an idea: Perhaps we could expand the concept of profile to encompass the build-time vs run-time difference? Or would that make things more confusing... I don't know :)

**Comment by jonathanvila** [comment]
I'm not sure to understand.

In runtime setting the -Dquarkus.profile=whatever has absolutely no effect
as it only works in the maven command.....so, my idea is when we build the
app we specify the profile used (-Dquarkus.profile ) but obviously this
wont have any effect on the result.
This is taking into account we can not do anything on runtime.

**Comment by geoand** [comment]
The issue is that `-Dquarkus.profile=whatever` does have an effect on user supplied properties (properties in `application.properties` prefixed with `%whatever` like `%whatever.greeting.message`) will be active.

So if we introduce the profiles support for beans users will get the false sense that if they use `-Dquarkus.profile=whatever` then beans for the `whatever` profile will be activated. So we would need to find a good user experience that would allow the functionality you propose but that wouldn't confuse users.

**Comment by jonathanvila** [comment]
Ohhh I see.

So passing the quarkus profile on Runtime makes the app to take the values
for those profile properties.

So then que quarkus profile is a Runtime feature not a build feature?

**Comment by geoand** [comment]
Exactly. So if we are to make something like this available for CDI beans, we need to be very careful how to make a good user experience

**Comment by mkouba** [comment]
> So then que quarkus profile is a Runtime feature not a build feature?

IIUIC it's both - the build-time and the runtime feature.

**Comment by geoand** [comment]
> > So then que quarkus profile is a Runtime feature not a build feature?
> 
> IIUIC it's both - the build-time and the runtime feature.

My interpretation is that run-time implies build-time as well :)

**Comment by jonathanvila** [comment]
which is the impact in build time of the quarkus.profile ?

**Comment by geoand** [comment]
Besides affecting the configuration stuff, it also set implicitly when running tests and the dev mode

**Comment by stuartwdouglas** [comment]
I don't think that the build time only aspect of this is an issue, as we already have the concept of build time only config.

**Comment by geoand** [comment]
I also like this idea a lot, but I my concern is summed up very well by [this](https://github.com/quarkusio/quarkus/issues/6238#issuecomment-566943990) comment from @mkouba

**Comment by stuartwdouglas** [comment]
It is now possible to enable CdI beans via config, and https://github.com/quarkusio/quarkus/pull/9933 allows them to be enabled per test easily.

**Comment by mkouba** [comment]
For the record - there's also `@IfBuildProfile` and `@UnlessBuildProfile`: https://quarkus.io/guides/cdi-reference#enabling-beans-for-quarkus-build-profile
