### ISSUE TITLE
Add support for the Elytron FileSystemSecurityRealm

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#624]
In chatting with Darran, the most functional local/file based security realm store in Elytron is the org.wildfly.security.auth.realm.FileSystemSecurityRealm, so that is something the security extension needs to support and probably should be the "default".

**Comment by gastaldi** [comment]
How does this realm compare to the existing `elytron-security-properties-file` extension?

**Comment by dmlloyd** [comment]
It is more flexible, supporting a variety of credential types and authentication methods with (iirc) one user per file.

**Comment by gastaldi** [comment]
Interesting, I'd like to give it a try if @starksm64 doesn't mind :)

**Comment by gastaldi** [comment]
Just started it: https://github.com/gastaldi/quarkus/pull/new/security-filesystem

Working on tests now

**Comment by starksm64** [comment]
Have at it George.

**Comment by emmanuelbernard** [comment]
@gastaldi is it fixed and orphan or still pending work? No rush, just doing some cleaning

**Comment by gastaldi** [comment]
@emmanuelbernard It's still pending work. PR is in #6496

**Comment by stuartwdouglas** [comment]
I am going to close this, OIDC is our preferred solution, and we already have a filesystem based provider for testing, so I don't think we want to support this.
