### ISSUE TITLE
Apply (path) params to request body before validation happens

### ISSUE THREAD

**Issue by ahofmeister** [quarkusio/quarkus#6253]
**Description**

The idea is to apply path params to the request body schema (an enity) for every request. 
Right now, the code below would throw an exception if `id` is annotated with `@NotNull`. 

```
public class Test {
    public String id;
    public String name;
}
```
```
@Path("test")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class TestResource {
    @Path("{id}")
    @POST
    public Test test(@Valid Test test){
        return test;
    }
}
```

With the new feature, it should/would be possible to annotate `id` with `@NotNull` and throw an exception if it is not valid.

Here is a reproducer to clarify the use case: https://github.com/ahofmeister/reproducer-path-param
Just start the app and execute the tests. You will notice a 400. 

CC: @geoand

**Comment by geoand** [comment]
Hi @AlexanderHofmeister 

I am sure we had a similar request but I can't seem to find it anywhere. @gsmet do you remember perhaps?

**Comment by AlexanderHofmeister** [comment]
@geoand This request comes from my SO question right here: https://stackoverflow.com/questions/59322407/how-to-put-a-path-param-to-the-request-body-before-validation-happens?noredirect=1#comment104908601_59322407

**Comment by geoand** [comment]
Thanks @AlexanderHofmeister 

I do think however that we've had a similar report that last few days, I'm still looking :laughing:

**Comment by geoand** [comment]
FWIW, I think this would be a useful feature

**Comment by gastaldi** [comment]
Isn't that the same as adding `@PathParam` to `Test.id` and `@BeanParam` to the test() method?

**Comment by AlexanderHofmeister** [comment]
@gastaldi Almost, but if you mark both properties (`id` and `name` in this case). It does not work properly: It throws always a Constraint Violation Exception for the missing `name`. 

I tried it with all param annotations (`@HeaderParam`, `@FormParam` and `PathParam`). 
I am sending the properties in the JSON body to the Server.

**Comment by ahofmeister** [comment]
Just checking: Are there any plans to implement this feature request?

**Comment by gsmet** [comment]
I had a quick look and I fail to understand what you want to do.

Could you enhance the description with a full example of what you want to do in the code and how it should behave? That might help me grasp what you want.

**Comment by ahofmeister** [comment]
@gsmet @geoand Okay. I will add a full example providing in a repository. :) Thanks for checking.

**Comment by ahofmeister** [comment]
I managed to build a reproducer and will also attach it to the description: https://github.com/ahofmeister/reproducer-path-param

**Comment by geoand** [comment]
Thanks for the reproducer.

To be honest, this sounds like a very niche feature to me.

**Comment by gsmet** [comment]
OK, apparently, nobody really has the cycles to work on this so I will close it.

If someone interested in contributing this to Quarkus arrives here, please ping us loudly and we will reopen.

Thanks for taking the time to suggest this improvement.
