### ISSUE TITLE
Improve efficiency of CI pipeline resources by partial rebuild

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#6260]
**Description**

Currently PR builds run all of our integration tests for every PR, which takes several hours and will probably take longer as time goes on and more tests are added. We could improve CI pipeline build time and resource usage by computing which integration tests are impacted by the files being changed in the PR, and only run the impacted integration tests.

Offer partial build run based on what has changed in a PR, vs the full build run we have today.

See discussion there https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/FTLRYTfmELw/wXxWS2mhAgAJ

**Comment by aguibert** [comment]
@emmanuelbernard I don't have authority to edit the description or assign the issue to myself, but can you please assign this one to me and also update the description to be the following?

----

Title: Improve efficiency of CI pipeline resources by only running impacted tests

Description: Currently PR builds run all of our integration tests for every PR, which takes several hours and will probably take longer as time goes on and more tests are added. We could improve CI pipeline build time and resource usage by computing which integration tests are impacted by the files being changed in the PR, and only run the impacted integration tests.

**Comment by emmanuelbernard** [comment]
@aguibert done

**Comment by emmanuelbernard** [comment]
Is it something we will work more on in the next 3-6 months?

**Comment by aguibert** [comment]
Yes, I'm planning to have this done within that timeframe.

However, it depends on Quarkus being a monorepo. If that plan changes please let me know because the strategy I'm using would not work.

**Comment by emmanuelbernard** [comment]
Likely what's inside the repo today will remain (except a few moves as necessary) but newer extensions will not be in the monorepo. That's a likely future anyways.

**Comment by emmanuelbernard** [comment]
hello @aguibert , with the other stuff you have on the fire, when do you think you want and can make this to land ? end of june, end of july, end of... I'm trying to map the task to a Quarkus release on the roadmap with option to move things out / adjust.

**Comment by aguibert** [comment]
hi @emmanuelbernard, sorry, I should have posted an update here sooner. Yes, this is on the back burner since I'm focusing on hibernate reactive and DB2 reactive lately.

For now I'd guess this would be around end of july, if at all.

**Comment by maxandersen** [comment]
related: https://github.com/quarkusio/quarkus/issues/7717
