### ISSUE TITLE
Maven Multi Module Project Official instructions

### ISSUE THREAD

**Issue by lssoares** [quarkusio/quarkus#6266]
Is multi module maven a possibility for a quarkus project, and if it is, do you plan to release official instructions and best practices on how to do it?

There's a lot of information on how to start a maven project, and lots of information around from several developers, but they all seem to focus on single maven module development.

My first impressions is that we're focusing on attending very small projects, where the mess of not being modularised is not quite an issue. Microservices! That's alright! But nevertheless I would like to protect the project from some spaghetti code, without solely relying on code reviews. 

Anyway, I'm intrigued wether or not, there will be some instructions for maven multi module projects, as it's not straightforward to accomplish that...

What I have found so far:

1. It's seems to be required the existence of one module dedicated for the quarkus-maven-plugin. This module might not have source code, but must have all the maven dependencies (external or internal). Thanks to [https://github.com/rebase-it/rebot/tree/master/rebot-telegram](https://github.com/rebase-it/rebot/tree/master/rebot-telegram)

1. There's no advantage on separating interfaces from implementations on different modules. Augmentation during compilation will fail to inject the interface, if the injector module does not have the implementation as a dependency.

1. Separating modules, but keeping interfaces within implementations, will let the project compile and execute, but you can't keep @Quarkustests isolated on each module. This will require that parent dependencies are maintained on the child (at least with test scope). For instance, a test located on module B, and module B depends on module A that handles database, will fail if every dependency of module A is not available on module B... 

Bottomline, what have worked for me (until the next issue), is to have one module dedicated for quarkus-maven-plugin, and @quarkustests are all located on this same module. All the dependencies on other modules are kept with the provided scope.

Project is available on [https://github.com/lssoares/multi-maven-quarkus](https://github.com/lssoares/multi-maven-quarkus)

**Comment by geoand** [comment]
The documentation does mention this, see https://quarkus.io/guides/maven-tooling#multi-module-maven

**Comment by beatngu13** [comment]
>The documentation does mention this, see https://quarkus.io/guides/maven-tooling#multi-module-maven

@geoand the documentation really doesn't cover this. The only thing explained is how "to enable CDI bean discovery for a module in a multi-module project".

One might close this issue as a duplicate of #2003, which is open since 2019 and a corresponding PR trying to add a quickstart example is left untouched. This is rather frustrating, both for users and contributors… 😕
