### ISSUE TITLE
Any reference to an Entity extending PanacheEntity in any test causes the exception "IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?"

### ISSUE THREAD

**Issue by DiegoNovati** [quarkusio/quarkus#6268]
**Describe the bug**
If in any test you import any Entity class, all the tests will fail.

**Expected behavior**
The tests should succeed

**Actual behavior**
The tests fail with the exception "IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?"

**To Reproduce**

1. Clone the project 
https://github.com/DiegoNovati/quarkus_bug.git
2. Execute the command 
mvn package quarkus:dev
3. All the test fails
4. Delete the test file "BlackListTest" and everything will work correctly

**Comment by zeljkot** [comment]
This happens to me, too, but with regular entities from another project. It works correctly in dev mode.

**Comment by irenakezic** [comment]
I tried reproducing the error with the code provided. The error is gone if you annotate BlackListTest class with the @QuarkusTest annotation.

**Comment by DiegoNovati** [comment]
Thank you irenakezic, with your help I was able to move on.
