### ISSUE TITLE
Provide deleteById() for MongoDB and Hibernate with Panache

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#6270]
**Description**
Currently, to delete an entity in both MongoDb and Hibernate by Panache we can only do it from an entity instance.

So in traditional REST API, when we implement a DELETE: /entity/id we usually load the entity from the database then delete it. Alternatively we can use Entity.delete("id", id) but in this case we must check the resulting number of deleted results to check that the entity has been deleted (and generates a 404 if not).

Providing a `Entity.deleteById(id)` method will make it easy to delete from an ID.
It should throw an exception if no delete happens.

**Comment by FroMage** [comment]
+1, but I wonder why we didn't add it from the start. Perhaps @gsmet remembers our initial discussions?

I think in many use-cases we will need to load the entity anyway to check for permissions to delete it. But some systems don't apply permissions on an entity basis, so these would benefit from this.
