### ISSUE TITLE
HotReload (extensions\vertx-http\deployment) tests fails on Windows with Java 11

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6280]
HotReload (extensions\vertx-http\deployment) tests fails on **Windows with Java 11** (Java version: 11.0.5, vendor: Oracle Corporation)

`Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/C:/Users/Rostislav/.m2/repository/org/apache/maven/surefire/surefire-booter/2.22.1/surefire-booter-2.22.1.jar`

```
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   HotReloadWithFilterTest.testFilterChange:34 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR] Errors:
[ERROR]   HotReloadWithFilterTest.testAddFilter » Runtime java.lang.RuntimeException: ja...
[ERROR]   HotReloadWithRouteTest.testAddBean » Runtime java.lang.RuntimeException: java....
[ERROR]   HotReloadWithRouteTest.testRouteChange » Runtime java.lang.RuntimeException: j...
[INFO]
[ERROR] Tests run: 41, Failures: 1, Errors: 3, Skipped: 0
```

Here is [test-log.txt](https://github.com/quarkusio/quarkus/files/3987194/test-log.txt) from `mvn clean verify -fae -pl extensions\vertx-http\deployment\` command execution.

```
$ mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: c:\Users\Rostislav\Downloads\apache-maven-3.5.3\bin\..
Java version: 11.0.5, vendor: Oracle Corporation
Java home: c:\Program Files\Java\jdk-11.0.5
Default locale: cs_CZ, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

@stuartwdouglas / @gsmet  fyi

**Comment by rsvoboda** [comment]
This wasn't seen on CI because Windows runs are using Java 8.
https://github.com/quarkusio/quarkus/blob/master/ci-templates/stages.yml#L103

**Comment by rsvoboda** [comment]
As extensions\vertx-http\deployment module failed there were several modules skipped in the maven execution
  => 
there can be more Windows with Java 11 fails

**Comment by rsvoboda** [comment]
@Karm fyi, I think you saw the same problem

**Comment by gsmet** [comment]
@rsvoboda this is with current master? /cc @jaikiran

**Comment by jaikiran** [comment]
@gsmet, @rsvoboda, I think I see what might be wrong (mostly appears to be our test framework issue). I'll see what needs to be done and update with more details.

**Comment by Karm** [comment]
@rsvoboda  @gsmet   Yes.  Master. Fails only on Windows:

(any GitHub account is O.K.; it's just to keep bots away)

https://ci.modcluster.io/view/Quarkus/job/karm-quarkus/30/

```
java.lang.RuntimeException: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/C:/Windows/system32/config/systemprofile/.m2/repository/org/apache/maven/surefire/surefire-booter/2.22.1/surefire-booter-2.22.1.jar
```

**Comment by rsvoboda** [comment]
yup, master from yesterday ~10pm Brno time

**Comment by Karm** [comment]
ClassLoaderCompiler:

```
        //this is pretty yuck, but under JDK11 the URLClassLoader trick does not work
        Enumeration<URL> manifests = classLoader.getResources("META-INF/MANIFEST.MF");
        while (manifests.hasMoreElements()) {
            URL url = manifests.nextElement();
            if (url.getProtocol().equals("jar")) {
                String path = url.getPath();
                if (path.startsWith("file:")) {
                    path = path.substring(5, path.lastIndexOf('!'));
                    urls.add(new File(URLDecoder.decode(path, StandardCharsets.UTF_8.name())).toURI().toURL());
                }
            }
        }
```

IMHO....

**Comment by jaikiran** [comment]
Hello @Karm, the root cause is actually known to us https://bugs.openjdk.java.net/browse/JDK-8232170. We have workarounds in place to get us past that. Our `QuarkusDevTest` needs an update to use such a workaround. I'm in the process of changing and testing this to see if it works. I'll update this issue shortly.

**Comment by jaikiran** [comment]
Hello @rsvoboda, @Karm, I've opened https://github.com/quarkusio/quarkus/pull/6290 with the proposed fix. My tests against Windows OS with Java 11 have passed with this change. Please give that PR a try and see how it goes in your setups.

**Comment by rsvoboda** [comment]
@jaikiran HotReload tests work for me now, thanks.

**Comment by Karm** [comment]
@jaikiran 

All good now https://ci.modcluster.io/view/Quarkus/job/karm-quarkus/32/

**Comment by jaikiran** [comment]
Thank you both @rsvoboda and @Karm for verifying
