### ISSUE TITLE
Keycloak/oidc integration tests are executed only in native mode, not with JDK 11/12

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6287]
Keycloak/oidc integration tests are executed only in native mode - https://github.com/quarkusio/quarkus/blob/master/ci-templates/native-build-steps.yaml

One can say that native mode execution also covers JVM mode execution, but that's true only for JDK 8 aspect.

There are no runs with JDK 11/12 for Keycloak/oidc.

**Comment by sberyozkin** [comment]
@rsvoboda Hi, I guess that also applies to a number of other tests (vault, and all other running in that native tests group) which depend on the pre-installed image ? CC @cescoffier @gsmet

**Comment by rsvoboda** [comment]
git grep for `test-keycloak` gives
 - integration-tests/keycloak-authorization
 - integration-tests/oidc-code-flow
 - integration-tests/oidc

**Comment by sberyozkin** [comment]
@rsvoboda all of those and likely others, https://github.com/quarkusio/quarkus/blob/master/ci-templates/native-build-steps.yaml. For example, from what I can see, the vault test depends on the test-containers postgress and possibly more.
From what I understand it is a CI resource issue. I agree it would be a good idea to test them all and `quarkus-oidc` in particular with as many JDKs as possible

**Comment by gsmet** [comment]
Well, it looks it's not tested at all in JVM mode. JDK 8 is also concerned as all the JVM tests are consistent.

**Comment by rsvoboda** [comment]
@gsmet you are right, only subset of tests runs in native mode, so my workaround story for JDK 8 is poor.

@sberyozkin I know it's CI capacity issue, this extension is quite important and we should give it some space on Quarkus CI. 

I also added similar CI issues for MariaDB and MSSQL as they should be getting more attention.
https://github.com/quarkusio/quarkus/issues/created_by/rsvoboda
