### ISSUE TITLE
Some errors in kubernetes.adoc ?

### ISSUE THREAD

**Issue by angelozerr** [quarkusio/quarkus#6303]
I create this issue since I'm developping a kubernetes support for vscode-quarkus and after reading the documentation coming from https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/kubernetes.adoc I wonder if there are some errors or not:

 * `kubernetes.docker-file` : is this property is working? I ask you that because with our JDT LS extension which generates thoses kubernetes properties (which introspect io.dekorate.kubernetes.config.KubernetesConfig) this property doesn't exists (KubernetesConfig or class extension doesn't provide the dockerFile field). This dockerFile field exists in the io.dekorate.docker.config.DockerBuildConfig, so i sit an error? If no, could you give me fore information how kubernetes.docker-file is managed (with which config class?). Thanks!

 * `Table 5. Probe`: the Property column is empty and the Type column is filled with property name. There is the same problem with Docker https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/kubernetes.adoc#docker
 * https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/kubernetes.adoc#docker I don't understand the information about this array? Perhaps it's for docker properties like `docker.docker-file`

**Comment by gsmet** [comment]
@iocanel Could you have a look at that one?

**Comment by iocanel** [comment]
@gsmet sure. Is there any way I could have permission to assign issues to me?

**Comment by gsmet** [comment]
I assigned it to you. Will add you the permission soon.

**Comment by iocanel** [comment]
Thanks

**Comment by iocanel** [comment]
I think that this can be closed now.
