### ISSUE TITLE
Usage of Kotlin default parameters instead of optionals

### ISSUE THREAD

**Issue by J00LZZ** [quarkusio/quarkus#6304]
**Description**
Kotlin can use default parameters for methods and class constructors, and quarkus does not seem to support this. It'd be a nice feature to have for the developers using Kotlin instead of Java since it basically replaces Java's `Optional<T>` class. This could then be used in for instance query parameters. 

**Implementation ideas**
Allowing defaults instead of Optionals. Instead of using `optional: Optional<String>` as the parameter type and `optional.orElse("default")` in the method, you could use `optional: String = "default"` and just `optional` in the method.

**Comment by KaenDagger** [comment]
I would like to work upon this issue

**Comment by KaenDagger** [comment]
@J00LZZ  could you please further elaborate the issue ?

**Comment by geoand** [comment]
@J00LZZ which parts of Quarkus do you have in mind for this feature?

**Comment by J00LZZ** [comment]
After doing some research of my own I found out that it might be pretty hard to handle in a generic way. The `callBy` method in `KFunction<T>` can be passed a map of `KParameters` mapped to `Any` (or `Object` in Java) to call the function, any parameters that do not have a value in the map but do have a default value will be set using the default value. 

Using this feature it should be possible to use Kotlin's default parameters. The biggest issue that I can find is type conversion, so from `String` to `Int` depending on the parameter type.

**Comment by geoand** [comment]
I'm going to close this as it is unclear what is required.

Feel free to reopen with more information if desired.
