### ISSUE TITLE
A generated Kotlin project with Gradle doesn't build 

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#6311]
**Describe the bug**
When generating a project like so:

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create     -DprojectGroupId=org.acme     -DprojectArtifactId=gradle-kotlin-test     -DclassName="org.acme.GreetingResource"     -Dpath="/greeting"     -Dextensions="kotlin" -DplatformArtifactId=quarkus-bom -DbuildTool=gradle
```

and then trying to build it like so:

```
gradle build -x test
```

I get:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/gandrian/Desktop/gradle-kotlin-test/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating root project 'gradle-kotlin-test'.
> Could not find method setOutputDirectory() for arguments [/home/gandrian/Desktop/gradle-kotlin-test/build/classes/kotlin/main] on object of type io.quarkus.gradle.QuarkusPluginExtension.

```

**Environment (please complete the following information):**
 - Quarkus version or git rev: latest `master`

**Comment by geoand** [comment]
cc @gastaldi

**Comment by gastaldi** [comment]
Hm, weird, I don't think that part have changed. Not sure how it used to work in https://github.com/quarkusio/quarkus/commit/242d2f7cb55462d402c5c99fc3aca5283dc42dd3

**Comment by geoand** [comment]
I've lost track of the changes so I don't know either :P

**Comment by gastaldi** [comment]
Actually I take that back, it changed a bit since https://github.com/quarkusio/quarkus/blob/0.28.1/devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPluginExtension.java. 

Let me provide a PR

**Comment by geoand** [comment]
Cool, thanks!

**Comment by gastaldi** [comment]
PR created in https://github.com/quarkusio/quarkus/pull/6312

**Comment by geoand** [comment]
Excellent, thanks for taking care of it so quickly!

**Comment by JBertaux** [comment]
How can we build until the release 1.2.0 will be published ? 😊

**Comment by gastaldi** [comment]
Downgrade to 1.0.0.Final until the next release comes up.

>

**Comment by gsmet** [comment]
FWIW I’m thinking about releasing a 1.1.1 at the beginning of next year.

**Comment by JBertaux** [comment]
When I downgrade to `1.0.0.Final` I have the same issue as this one #5781.
```
Caused by: java.lang.IllegalStateException: Unable to find quarkus-gradle-plugin dependency
        at io.quarkus.gradle.tasks.QuarkusDev.lambda$addGradlePluginDeps$2(QuarkusDev.java:403)
        at io.quarkus.gradle.tasks.QuarkusDev.addGradlePluginDeps(QuarkusDev.java:403)
        at io.quarkus.gradle.tasks.QuarkusDev.startDev(QuarkusDev.java:256)
        ... 95 more

```

**Comment by gastaldi** [comment]
That's because the Gradle config changed. Check the Migration guide for
more details

Em Seg, 30 de dez de 2019 03:20, JBertaux <notifications@github.com>
escreveu:

**Comment by gastaldi** [comment]
Migration guide link: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.1#gradle-plugin
