### ISSUE TITLE
UriInfo  is not available in reactive Resteay API

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#6319]
I tried to use `UriInfo` to build the uri  for new resource after the resource is created.

The source code is [here](https://github.com/hantsy/quarkus-sandbox/blob/master/cs-post-service/src/main/java/com/example/PostResource.java).

The `UriInfo` is not available as a generic Resteay resource class.

```java
//    @Context
//    UriInfo uriInfo;

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    public CompletionStage<Response> savePost(@Valid Post post/*, @Context UriInfo uriInfo*/) {
        return this.posts.save(post).thenApply(id -> created(URI.create("/posts/"+ id.toString())).build());
    }
```

**Comment by geoand** [comment]
Closing this as we have plenty of tests that use test this scenario
