### ISSUE TITLE
Replace project creation "templates" with Qute templates

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#6322]
**Description**
Currently we use a bunch of "templates" when projects are created with the maven tooling. These are severely limited and lead to a lot of code duplication among them (because we have 3 different programming languages supported, 2 build tools and different code "templates" for Spring code). 
We should replace them with Qute templates to make them more manageable.

**Comment by maxandersen** [comment]
This is related To and kinda duplicatIon of #6025 - we can update to templates before that but just be aware a) it will (most likely) break tools maven create plugin when combining "old" platform with new core b) it probably will have to change once extensions can hook into this.

**Comment by geoand** [comment]
Thanks for the heads up @maxandersen !

**Comment by maxandersen** [comment]
btw. one thing I just noticed is that qute isn't by default great for java code generation as it interprets any content inside a java statement {}'s as an expression :)

**Comment by geoand** [comment]
I'll close this in favor of #6025

**Comment by maxandersen** [comment]
I did back in december call it a duplicate of #6025 but with all the breakage we've seen in scaffolding just because we still only use string templates I'm going to reopen this one as its on its own should be feasible to do and help us alot on avoiding breakages.

**Comment by geoand** [comment]
This has already been done
