### ISSUE TITLE
Move MicroProfile Config for messaging under Quarkus namespace

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#6345]
## Description

I understand Quarkus uses SmallRye Reactive Messaging to leverage on its functionality/behavior, but I think it would be great if the configuration setting(s) for anything-quarkus lives under that namespace, even though it's using some other library to accomplish certain task(s), hence this configuration format: `mp.messaging.[outgoing|incoming].[channel-name].[attribute]=[value]` would "play" nicer under `quarkus.messaging.[outgoing|incoming].[channel-name].[attribute]=[value]`.

**Comment by kenfinnigan** [comment]
One problem with that is it makes the application non-portable, in that you no longer can use it with any MP Reactive Messaging implementation. Maybe that's not an issue.

Can you elaborate on the benefits of "play nicer"? Are you wanting all MicroProfile configuration to be settable as `quarkus.*`?

At present they're nicely separated to know which properties are Quarkus specific and which are MicroProfile related.

**Comment by x80486** [comment]
I think that separation only brings confusion, unless you know the framework/library that's using them: the keys outside the `quarkus` namespace.

For instance, Hibernate, Flyway, the (abstracted) logging library, and so on, they all live under that namespace, so I was suggesting to make the rest to play like that...but again, if it makes it so-complicated, discard it. I don't really know the side-effects this can cause, and in any case it's "cosmetics" only.

**Comment by cescoffier** [comment]
I don't see how it can be fixed as the configuration (and the `mp.messaging` prefix) comes from the specification. It's not something we control in Quarkus.
