### ISSUE TITLE
Add support for Hibernate ORM naming strategy

### ISSUE THREAD

**Issue by davide-malagoli** [quarkusio/quarkus#6346]
**Description**
Using Java naming convention, all the Entity names and all the attributes of an entity must be written in camelCase.
But, in some cases, on the database side it would be more convenient to use "all lower case" or "snake case" names, expecially when you are using an already existent database. #5935 

[Database, Table and Column Naming Conventions?](https://stackoverflow.com/questions/7662/database-table-and-column-naming-conventions)

[How I Write SQL, Part 1: Naming Conventions](https://launchbylunch.com/posts/2014/Feb/16/sql-naming-conventions/)

Now, to support this naming conventions, the only two option are the following:

1) breaking the Java entity/field naming convention
2) annotate all entities and attributes using the `@Entity` and `@Column` annotation

Using 2 is time expensive, prone to error, and sometimes breaks (partially) the readability of the entity.

Panache uses Hibernate 5, which provides two different naming strategies for use with Hibernate entities: an Implicit Naming Strategy (from DB to attribute) and a Physical Naming Strategy (from attribute to DB).

[This tutorial](https://www.baeldung.com/hibernate-naming-strategy) shows an example of implementation.

It requires just a line of configuration in the `application.properties`

`hibernate.physical_naming_strategy=<naming strategy class>`

**Implementation ideas**
Allowing the use of custom class could bring many problems, to keep thing simple and save time maybe it would be enough to support just the 3 most common naming strategy:

- camelCase (already supported)
- all lowercase
- snake_case

**Comment by gsmet** [comment]
I changed the title as it's not specific to Panache.

**Comment by gastaldi** [comment]
I could have a stab at it if @Sanne agrees on having a predefined list of supported naming strategies

**Comment by Sanne** [comment]
+1 to allow configuring a naming strategy, but in my experience people will need far more flexibility than having 3 basic choices.

**Comment by marceloverdijk** [comment]
As asked on the discussion forum, I would really like to see this in `1.2`. Will remove a lot of boilerplate from my entities.

**Comment by marceloverdijk** [comment]
Nice. 

Maybe this can be even improved by just defining a `@ApplicationScoped`? `PhysicalNamingStrategy` bean. In that case Quakrus could set it automatically and the user does not have to set the property explicitly. Of course if the user sets the property explicitly that one should be used always.

**Comment by gastaldi** [comment]
I think the problem with that is that it's all fun and games until 2 or
more PhysicalNamingStrategy beans exist in the app :)

Em Qua, 8 de jan de 2020 18:07, Marcel Overdijk <notifications@github.com>
escreveu:

**Comment by nimo23** [comment]
Can someone provide an example with if I want to use the org.hibernate.cfg.ImprovedNamingStrategy (which is the strategy which makes all properties and table names in `snake_case` format) ?

Should I only use this in `application.properties` to enable it?:

`hibernate.physical_naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy`

**Comment by gastaldi** [comment]
Yes, AFAIK that's what you need to do to use it

>

**Comment by zeljkot** [comment]
Just to clarify: This feature only allows defining a naming strategy, it does not provide naming strategies. `org.hibernate.cfg.ImprovedNamingStrategy` cannot be used as it does not implement `PhysicalNamingStrategy`; AFAIK snake strategy is not included with Hibernate. 

The current implementation does not cover the whole issue as originally defined. "snake-case" causes java.lang.ClassNotFoundException

**Comment by gastaldi** [comment]
@zeljkot yes, you're right

**Comment by nimo23** [comment]
@gastaldi Maybe one could add a new PR with default `SnakeCaseNamingStrategy` which can be used within quarkus. 

**I think only two cases are mostly used:** camelCase and snake_case. 

As camelCase is the default in jpa, it makes sense to provide the snake_case implementation by quarkus:


```
import java.util.Locale;

import org.hibernate.boot.model.naming.Identifier;
import org.hibernate.boot.model.naming.PhysicalNamingStrategy;
import org.hibernate.engine.jdbc.env.spi.JdbcEnvironment;

public final class SnakeCaseNamingStrategy implements PhysicalNamingStrategy {

	@Override
	public Identifier toPhysicalCatalogName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		return name;
	}

	@Override
	public Identifier toPhysicalSchemaName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		return name;
	}

	@Override
	public Identifier toPhysicalTableName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		if (name == null) return null;
		var tableName = name.getText();
		if (!tableName.endsWith("s")) {
			tableName = tableName.concat("s");
		}
		return Identifier.toIdentifier(tableName, name.isQuoted());
	}

	@Override
	public Identifier toPhysicalSequenceName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		return toSnakeCase(name);
	}

	@Override
	public Identifier toPhysicalColumnName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		return toSnakeCase(name);
	}

	private static Identifier toSnakeCase(Identifier name) {
		if (name == null) return null;
		String snakeCase = toSnakeCase(name.getText());
		return Identifier.toIdentifier(snakeCase, name.isQuoted());
	}


	private static String toSnakeCase(String text) {
		var buf = new StringBuilder(text);
		for (int i = 1; i < buf.length() - 1; i++) {
			if (Character.isLowerCase(buf.charAt(i - 1)) && Character.isUpperCase(buf.charAt(i))
					&& Character.isLowerCase(buf.charAt(i + 1))) {
				buf.insert(i++, '_');
			}
		}
		return buf.toString().toLowerCase(Locale.ROOT);
	}
}

```

**Comment by nimo23** [comment]
Maybe the implementation of snake_case can be provided by quarkus:

```
public final class SnakeCaseNamingStrategy implements PhysicalNamingStrategy {

	@Override
	public Identifier toPhysicalCatalogName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		return name;
	}

	@Override
	public Identifier toPhysicalSchemaName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		return name;
	}

	@Override
	public Identifier toPhysicalTableName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		if (name == null) return null;
		var tableName = name.getText();
		if (!tableName.endsWith("s")) {
			tableName = tableName.concat("s");
		}
		return Identifier.toIdentifier(tableName, name.isQuoted());
	}

	@Override
	public Identifier toPhysicalSequenceName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		return toSnakeCase(name);
	}

	@Override
	public Identifier toPhysicalColumnName(Identifier name, JdbcEnvironment jdbcEnvironment) {
		return toSnakeCase(name);
	}

	private static Identifier toSnakeCase(Identifier name) {
		if (name == null) return null;
		String snakeCase = toSnakeCase(name.getText());
		return Identifier.toIdentifier(snakeCase, name.isQuoted());
	}


	private static String toSnakeCase(String text) {
		var buf = new StringBuilder(text);
		for (int i = 1; i < buf.length() - 1; i++) {
			if (Character.isLowerCase(buf.charAt(i - 1)) && Character.isUpperCase(buf.charAt(i))
					&& Character.isLowerCase(buf.charAt(i + 1))) {
				buf.insert(i++, '_');
			}
		}
		return buf.toString().toLowerCase(Locale.ROOT);
	}
}
```

**Comment by gastaldi** [comment]
Looks like you're interested in providing a PR? ;)

**Comment by Sanne** [comment]
I'm not convinced there would be much value in having such a thing within the Quarkus repository?
Mind you, the point of this extension is to _boot_ Hibernate ORM - every further aspect belongs either in the Hibernate ORM repository or as a an extension to it.

In my personal experience, naming strategies are highly opinionated: people always want to customize _some_ detail.

That said, if you really believe that there's lots of people who'd be happy enough to just have a default snake_case and camelCase - maybe they belong in ORM so that there's more people benefitting from them?

**Comment by nimo23** [comment]
@Sanne I also think that it is better to place such implementation within Hibernate ORM by default and not in quarkus. To provide this in Hibernate ORM makes sense, because mostly only snake_case or camelCase are used.

**Comment by joaomarcosribeiroc** [comment]
It didn't work using hibernate.physical_naming_strategy=<naming strategy class>. It should be used quarkus.hibernate-orm.physical-naming-strategy=<naming strategy class> instead. According to https://github.com/quarkusio/quarkus/pull/6451/files#diff-535c697010dc8616f3b55956441f96e485455d1eb8dadd9e936df6b2b366df25R7
