### ISSUE TITLE
Different Hibernate Naming Strategy

### ISSUE THREAD

**Issue by marko-lazic** [quarkusio/quarkus#6352]
We should be able to define our own naming strategies like in following article: https://www.devglan.com/hibernate/hibernate-naming-strategy

**Configuration suggestion**
```properties
quarkus.hibernate.physical_naming_strategy=com.devglan.config.CustomPhysicalNamingStrategy

```

**Comment by machi1990** [comment]
Hi @marko-lazic thanks for reporting this. 

This seems like a duplicate of https://github.com/quarkusio/quarkus/issues/6346. Can you +1 on the issue to tract attention? thanks.  

I am closing this in favour of it.
