### ISSUE TITLE
Posgtress driver fail to connect - 

### ISSUE THREAD

**Issue by gintsgints** [quarkusio/quarkus#6353]
**Describe the bug**
Quarkus project fail to connect to postgress database.

**Expected behavior**
Project starts successfully with PostgreSQL driver.

**Actual behavior**
```
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
```

**To Reproduce**
1. In project - https://github.com/gintsgints/quarkus-ws, start postgress in docker:
```docker-compose up -d db```
2. start project issuing - ```mvnw clean compile quarkus:dev -Dquarkus.profile=dev```
3. Project fail to start with message:
```
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
```

**Configuration**
```properties
# configure your datasource
quarkus.datasource.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres_234
# hibernate configuration
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.database.charset=UTF-8
%dev.quarkus.hibernate-orm.log.sql=true
%test.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.sql-load-script=import.sql
%test.quarkus.hibernate-orm.sql-load-script=no-file
%prod.quarkus.hibernate-orm.sql-load-script=no-file

# Flyway minimal config properties
%dev.quarkus.flyway.migrate-at-start=false
# For now we depend on quarkus hibernete generation
# https://github.com/quarkusio/quarkus/issues/4232
%test.quarkus.flyway.migrate-at-start=false
%prod.quarkus.flyway.migrate-at-start=true
# Flyway optional config properties
quarkus.flyway.baseline-on-migrate=true

# Enable swagger-ui for production
quarkus.swagger-ui.always-include=true

quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret

# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17763.914]
 - Output of `java -version`:  JAVA_HOME=C:\Program Files\Java\jdk1.8.0_221
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.1.0 Final

**Comment by gsmet** [comment]
You need to properly configure your PostgreSQL server to support password authentication (see the `pg_hba.conf` file).

Also, it's not recommended to use the `postgres` superuser account for a web application, you should create a specific user.

**Comment by gintsgints** [comment]
- I can connect to same server with GUI client without problems.
- I know I have to setup own user for production. But for development, imho there should be no problem to use root.

**Comment by gsmet** [comment]
Your client might use a different way to connect to postgres (typically local instead of using a host).

You need to configure your PostgreSQL server to allow TCP connection on localhost (IPv4 and v6) for the user postgres with a password.

Basically, once `psql -h localhost -U postgres -W` works, you will be able to connect with Quarkus.

**Comment by gintsgints** [comment]
:( I can successefully connect with that command. But still quarkus can't.

**Comment by gsmet** [comment]
That is indeed strange. But our unit tests are exercising that so I don't see how it could be Quarkus failing.

Do you see something in the PostgreSQL server logs? Usually, it explains what is going wrong.

**Comment by gintsgints** [comment]
I see no logs on docker. Probably need to investigate more for logs.

But I agree, this is not quarkus who is guilty one. Because I found other framework failing with Postgres driver too. Thanks.

**Comment by rom1dep** [comment]
> Basically, once psql -h localhost -U postgres -W works, you will be able to connect with Quarkus.

not sure about that, my understanding is that this would stress the "local" authent-type, while quarkus would rather rely on "host" authent-type (under IPv4/IPv6 in the demo config)

**Comment by tleach-sgi** [comment]
I have this problem in dev mode when the datasource password is supplied by a custom ConfigSource.  My workaround is setting the env var QUARKUS_DATASOURCE_PASSWORD
