### ISSUE TITLE
quarkus bypasses maven Nexus when running 'mvn test'

### ISSUE THREAD

**Issue by zapho** [quarkusio/quarkus#6363]
**Describe the bug**
Same as https://github.com/quarkusio/quarkus/issues/2470
Case reproducer here https://github.com/zapho/issue-quarkus-bypass-nexus

**Expected behavior**
mvn test should run normally

**Actual behavior**
mvn test fails because of maven dependency resolution issue

**To Reproduce**
See https://github.com/zapho/issue-quarkus-bypass-nexus

**Configuration**
See https://github.com/zapho/issue-quarkus-bypass-nexus

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: CYGWIN_NT-10.0-WOW MORLN256 2.6.1(0.305/5/3) 2016-12-16 11:50 i686 Cygwin
 - Output of `java -version`:                                                                                                                     java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.0.1-Final

**Additional context**
See https://github.com/zapho/issue-quarkus-bypass-nexus

**Comment by gsmet** [comment]
@aloubyansky is it something you already fixed or is it a new one?

**Comment by aloubyansky** [comment]
@zapho thanks for the report and the reproducer. Sorry, it didn't receive the attention sooner. I believe this is fixed now. #2470 that you referenced has been resolved as well.
In addition, we are now generating surefire plugin config with <maven.home>${maven.home}</maven.home> property that helps pick up the current settings.
