### ISSUE TITLE
Document Qute template expression language

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#6367]
I couldn't find any reference documentation for Qute template expressions, only some examples in [its guide](https://quarkus.io/guides/qute). There should be a reference for supported expression constructs and syntax.

**Comment by gsmet** [comment]
Have you seen the more complete reference guide? https://quarkus.io/guides/qute-reference

**Comment by gunnarmorling** [comment]
Ah, no, I haven't. Thanks, that's largely what I was looking for. Would
just be good to add a link from https://quarkus.io/guides/qute to the
reference for easier navigation, otherwise this issue can be closed.

>

**Comment by machi1990** [comment]
> Have you seen the more complete reference guide? https://quarkus.io/guides/qute-reference

Aaah did not know we had this. Thanks @gsmet 

> Ah, no, I haven't. Thanks, that's largely what I was looking for. Would just be good to add a link from https://quarkus.io/guides/qute to the reference for easier navigation, otherwise this issue can be closed.
> […](#)

Let me propose a PR.
