### ISSUE TITLE
integration-tests/jpa-mysql test fails against docker instance

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6372]
integration-tests/jpa-mysql test fails against docker instance - `mvn clean install -Dtest-mysql -Ddocker -pl integration-tests/jpa-mysql`

From the stacktrace the most important message seems `Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.`

Tests are passing when running against already running database - `mvn clean install -Dtest-mysql -pl integration-tests/jpa-mysql`

Seems that `-Ddocker` way doesn't wait long enough or there is problem with exposed ports.
Running on macOS 10.15.2, OpenJDK 64-Bit GraalVM CE 19.3.0.

**Comment by geoand** [comment]
Let me check and see
