### ISSUE TITLE
Maven create-extension does not create associated integration test stubs

### ISSUE THREAD

**Issue by sfcoy** [quarkusio/quarkus#6377]
**Describe the bug**
[Quarkus - Writing Extensions §2.2.1. Create new extension modules using Maven](https://quarkus.io/guides/writing-extensions#create-new-extension-modules-using-maven) describes the steps required to generate the modules and source code stubs to build a Quarkus Extension.

It states that it "Creates four new Maven modules".

However, it only creates the first three modules listed and fails to create the `quarkus-my-ext-integration-test` module.

**Expected behavior**
Integration test stubs should be created in the `integration-tests/my-ext/deployment` directory.

**Actual behavior**
The integration test directory tree and stubs are not created.

**To Reproduce**
1. Follow the directions described at [Quarkus - Writing Extensions §2.2.1. Create new extension modules using Maven](https://quarkus.io/guides/writing-extensions#create-new-extension-modules-using-maven) 

**Configuration**
```properties
# Add your application.properties here, if applicable.
n/a
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
    Darwin steves-corei9.resolvesw.home 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
    openjdk version "1.8.0_232"
    OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
    OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

 - GraalVM version (if different from Java): 
    n/a
 - Quarkus version or git rev: 
    master branch commit 7c017871d037009cae438ed7c537202e3ca2711c

**Additional context**
On first inspection of the source it seems that the `itestParentPath` parameter is not defaulting 
to anything.

So I tried defining it on the command line by adding `-Dquarkus.itestParentPath=../integration-tests/`.

This resulted in a file system error:

        java.io.IOException: Is a directory

Line [531](https://github.com/quarkusio/quarkus/blob/c64b514641caab5efcc7dd0f5708190cf4e44800/devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java#L531) of io.quarkus.maven.CreateExtensionMojo shows clearly that the code is trying to open the `itestParentPath` as a text file (it's expecting a path to a pom.xml) when it is in fact a directory.

I changed lines 530-531 to:

    final Path itestParentPomPath = basedir.resolve(itestParentPath).resolve("pom.xml").toAbsolutePath();
    try (Reader r = Files.newBufferedReader(itestParentPomPath, charset)) {

and successfully created test stubs in `integration-tests/my-ext`.
This still does not match the documentation but it corresponds with the other tests to be found in the `integration-tests` directory.

**Comment by holly-cummins** [comment]
I think this can be closed, just because so much time has passed it got fixed along the way. I confirm that if I run the `create-extension` mojo, following the instructions on https://quarkus.io/guides/building-my-first-extension#maven-setup, I do get an `integration-tests` project. Do you agree, @sfcoy?

(On the other hand, I've raised https://quarkus.io/guides/building-my-first-extension#maven-setup for a different issue with the `create-extension` mojo we're seeing now.)
