### ISSUE TITLE
Access pre-compiled reflection information at run-time

### ISSUE THREAD

**Issue by Mason-Harding** [quarkusio/quarkus#6382]
**Description**
It would be great to have a way to access reflection information that has been pre-compiled into a class, at runtime.  Writing my own extension seems like a fairly daunting task.  If I could just add an annotation to a class, then Quarkus would compile that reflection information and provide a way to access it at runtime, it would make using it in my own code very simple.  This is the idea behind Micronaut Bean Introspection.  Thank you!

My primary need for this is to speed up initial boot time, as I am running my apps in a sever-less infrastructure (AWS Lambda).

**Comment by geoand** [comment]
Extensions are the way we propose so we won't be introducing something like this.

However, if you are have trouble writing an extension, feel free to reach out.
