### ISSUE TITLE
Qute with JS and Css Failed on build

### ISSUE THREAD

**Issue by Tayeh** [quarkusio/quarkus#6389]
**Describe the bug**
the Qute parser not sure how to deal with the JS and CSS on the template 

**Expected behavior**
https://pastebin.com/B807iJxH

**To Reproduce**
1. I'm trying to use qute with a html templete  
2.  the quarkus faild on bulid and get the error on the link above
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.
# Datasource
quarkus.datasource.url=jdbc:mariadb://localhost:3306/test
quarkus.datasource.driver=org.mariadb.jdbc.Driver
quarkus.datasource.username=root
quarkus.datasource.password=root

# JWT
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=Tayeh-Orange
quarkus.smallrye-jwt.auth-mechanism=MP-JWT
quarkus.smallrye-jwt.enabled=true
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/9280478/71716148-69f75400-2e1c-11ea-9a84-aff159e65eab.png)

![image](https://user-images.githubusercontent.com/9280478/71716160-767bac80-2e1c-11ea-84fb-93742d8acf19.png)

![image](https://user-images.githubusercontent.com/9280478/71716168-80051480-2e1c-11ea-995f-50888c5d399a.png)

**Comment by Tayeh** [comment]
hi @gsmet 
I'm trying to move all of my assets to "\src\main\resources\META-INF\resources\assets"
and keep the HTML pages that serve with qute on the qute location "\src\main\resources\templates"

and it's work correctly 
because all of the assets resources serve from "\src\main\resources\META-INF\resources\assets"
and my pages serve using qute from "\src\main\resources\templates"

**Comment by gsmet** [comment]
Ah yes, I missed that you were having the JS files in the templates.

@mkouba does Qute parse all the files in `templates` even if they are not used as templates and are not in the extension list managed by Qute?

**Comment by mkouba** [comment]
> I'm trying to move all of my assets to "\src\main\resources\META-INF\resources\assets"

That's the correct approach - `src\main\resources\templates` is not accessible via web server. In other words, even if we skipped the parsing of the files it would not work. 

> does Qute parse all the files in templates even if they are not used as templates and are not in the extension list managed by Qute?

Yes, currently it does.
