### ISSUE TITLE
Infinispan Embedded: config file not included in native image

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#6392]
This one was reported by a user so we apparently have people using this extension.

Currently the configuration file is configured at runtime (see https://github.com/quarkusio/quarkus/blob/master/extensions/infinispan-embedded/runtime/src/main/java/io/quarkus/infinispan/embedded/runtime/InfinispanEmbeddedRuntimeConfig.java#L19) and not included in the native image which makes the native image fail.

If we keep it configurable at runtime, there's no way to include it automatically in the native image so we need to choose one evil.

/cc @wburns @Sanne

**Comment by Sanne** [comment]
I believe the configuration aspect is very much work in progress: we shouldn't parse the whole thing at runtime of course :)

But I'll leave it to @wburns to decide if we should implement a stop-gap solution by including the resource, or if he'd rather directly go for the better long term solution.

thanks @gsmet.

**Comment by wburns** [comment]
Sorry, I didn't respond earlier.

The goal originally was to have this be a runtime config option for now. An example is we will want to generate a native image that runs the Infinispan server allowing a user to provide an arbitrary Infinispan config file without rebuilding.

Maybe we will need to deviate from this for the embedded extension though.

**Comment by wburns** [comment]
@jmartisk Can you describe what you are trying to do with the Infinispan embedded extension here? That way we can discuss it regarding runtime or build time config.

**Comment by gsmet** [comment]
@wburns how do you expect it to work if the configuration file is not included in the native image?

Because that's the issue we have here. You can override it but as the file is not there in the native image, it doesn't work.

**Comment by wburns** [comment]
The file would be on disk. But the more I think about it I am thinking this functionality should probably be moved up higher to our server extension (that doesn't live in Quarkus).

I personally am open to however people may use the embedded extension at this point. It is really barebones and ready to be molded as we need. I just don't know if we should ignore the xml and only go the programmatic configuration way or not.

**Comment by gsmet** [comment]
Yeah, so the problem is that we have users expecting to be able to use files in the classpath. We had one user complaining about it.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
