### ISSUE TITLE
Mime mappings in web.xml are ignored by undertow extension

### ISSUE THREAD

**Issue by mk2301** [quarkusio/quarkus#6399]
I need to serve my wasm file with 'Content-Type' header `application/wasm` instead of `application/octet-stream`. I explicitly use the quarkus-undertow extension.

I tried to add a web.xml under src/main/resources/META-INF with a mime mapping for wasm files like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         id="WebApp_ID" version="3.1">

    <mime-mapping>
        <extension>wasm</extension>
        <mime-type>application/wasm</mime-type>
    </mime-mapping>
</web-app>
```
The web.xml mime mapping seems to be ignored by the undertow extension.

**Expected behavior**
The Content-Type header for wasm files should be `application/wasm`.

**Actual behavior**
The Content-Type header for wasm files is still the original `application/octet-stream`.

**To Reproduce**
1. Add the quarkus-undertow extension
2. Add the web.xml from above under `src/main/resources/META-INF`
3. Add an empty file 'test.wasm' to `src/main/resources/META-INF/resources`
4. HTTP GET request to url `<quarkus-root>/test.wasm`
--> Content-Type header of response should be `application/wasm` like defined in the web.xml instead of `application/octet-stream`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Linux 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```
 - GraalVM version (if different from Java): CE 19.2.1
 - Quarkus version or git rev: 1.1.0.Final

**Additional context**
My original SO post: https://stackoverflow.com/q/59520915/3952202

**Comment by gsmet** [comment]
I pushed a fix here: https://github.com/quarkusio/quarkus/pull/6407 .

I'll try to get it in the upcoming 1.1.1.Final.
