### ISSUE TITLE
Has anyone managed to use KafkaContainer with Quarkus? 

### ISSUE THREAD

**Issue by FreifeldRoyi** [quarkusio/quarkus#6404]
I feel there's a chicken and egg problem regarding port mapping. Ports are mapped in `application.properties` but testcontainers map random ports and forces me to statically init everything.

I'd be happy for some working examples
Thanks!

**Comment by rquinio** [comment]
Faced same issue with a `@QuarkusTest` when using an embedded kafka broker that uses a random port.
A workaround was to get the random port and set the System property `kafka.bootstrap.servers` in static init, as it's taken into account by smallrye-reactive-messaging.

**Comment by FreifeldRoyi** [comment]
I did something similar, but then I had to manually start kafka

```
@Testcontainers
@QuarkusTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class McTestFaceIT {

    @Container
    private static final KafkaContainer KAFKA = new KafkaContainer();

    static {
        KAFKA.start();
        System.setProperty("kafka.bootstrap.servers", KAFKA.getBootstrapServers());
    }
...
```

**Comment by cescoffier** [comment]
@FreifeldRoyi Look at https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-quickstart/src/test/java/org/acme/quarkus/sample/PriceResourceTest.java or https://github.com/quarkusio/quarkus-workshops/blob/master/quarkus-workshop-super-heroes/super-heroes/rest-fight/src/test/java/io/quarkus/workshop/superheroes/fight/FightResourceTest.java
