### ISSUE TITLE
shamrock:dev does not work for WebSocket requests

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#641]
When you replace e.g. the `>>` in line 41 of the `@javax.websocket.server.ServerEndpoint` annotated `ChatSocket` [protean-quickstarts/using-websockets example](https://github.com/jbossas/protean-quickstarts/blob/master/using-websockets/src/main/java/org/acme/websocket/ChatSocket.java) by `>>>>>>>>>>>>>>>` then you would expect it to "hot code replace" and to see that change "live" when running with `mvn compile shamrock:dev`, but this does not currently work. 

In the basic getting-started which uses `javax.ws.rs.Path` it does however work as expected, of course; it's really cool BTW how it detects changes not only to e.g. the `GreetingResource` but also the `GreetingService` which the `GreetingResource` depends on!

From what little I understand of how it's implemented, the reloading isn't based on watching for class files changes on the file system but it somewhere somehow hooks into requests and see if any class used by that request changed? Perhaps that could be extended to also be aware of websocket requests....

If you want to leave some pointers here about where in the code this magic happens, then perhaps others could contribute a fix for this? (Not sure I'll get time for it myself in the very near future.)

@edewit FYI

**Comment by gsmet** [comment]
@stuartwdouglas do we want to fix that or should I close it?

**Comment by stuartwdouglas** [comment]
Let's just close it for now, there are no current plans to implement this.
