### ISSUE TITLE
Dev mode not working anymore when META-INF/resources is generated

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#6417]
**Describe the bug**
Dev mode is not working correctly when using `./mvnw compile quarkus:dev` on a project where the `target/classes/META-INF/resources` is generated.

![image](https://user-images.githubusercontent.com/2223984/71820356-26585080-308f-11ea-8914-4e579a9053f4.png)

**Expected behavior**
Should work without any error

**Actual behavior**
It works once every few page refresh

**To Reproduce**

Simulate a Maven step that generate the `target/classes/META-INF/resources`

1. Create a project with Quarkus 1.1.0.Final
2. save the `src/main/resources/META-INF/resources/index.html` somewhere
3. run `rm -rf src/main/resources/META-INF/resources` 
4. run `./mvnw compile quarkus:dev`
5. stop it
6. copy the index.html to `target/classes/META-INF/resources`
7. run `./mvnw compile quarkus:dev`
8. open in browser and refresh multiple times

**Environment (please complete the following information):**
 - Output of `java -version`: reproduced on java 1.8 and java 1.11
 - Quarkus version or git rev: 1.1.0.Final

**Additional context**
This bug was originally met on Code Quarkus using frontend maven plugin to generate the files:
https://github.com/eirslett/frontend-maven-plugin

**Comment by maxandersen** [comment]
@ia3andy if you do your workaround on precreating the dir I assume the content is lost anyways, right ? 
it’s a bit surprising devmode wants to nuke the whole META-INF/resources folder...that seems wrong.

**Comment by ia3andy** [comment]
@maxandersen I have two workaround:
- create an empty `src/main/resources/META-INF/resources` directory
or
- copy the files directly to `src/main/resources/META-INF/resources` (instead of target) and use `.gitignore` to keep them out of sync

**Comment by maxandersen** [comment]
@ia3andy yes, I get that - but i'm asking that that when you don't do that workaround the content is lost, right ? you have to manually run your other task to regenerate the content, correct ? 

Then i'm just curious how if at all this ever worked before ? as i assume in the past this folder would be recreated too...

**Comment by ia3andy** [comment]
> yes, I get that - but i'm asking that that when you don't do that workaround the content is lost, right ? you have to manually run your other task to regenerate the content, correct ?

@maxandersen no the content was kept in previous versions without any problem.

@geoand any idea of who we could assign to that one so it doesn't get lost?

**Comment by geoand** [comment]
Perhaps @machi1990 would like to take a look at it?
I can as well, but it won't be a for few days because of travel obligations

**Comment by jaikiran** [comment]
Hello @ia3andy,
> copy the index.html to target/classes/META-INF/resources

As far as I know copying anything to `target` was never supported (at least not intentionally). Quarkus only watches certain well known source locations (which isn't the `target` dir) for hot deployment. @stuartwdouglas or @machi1990 might be able to confirm this.

**Comment by ia3andy** [comment]
Hello @jaikiran,

While I get that it wasn't officially supported, I think we should provide a way to achieve such a scenario properly. People wanting to use the frontend plugin to serve their webapp with Quarkus is pretty common IMHO:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/WCjhkyY5lk0/_JPE5VdHCAAJ

cc @stuartwdouglas @machi1990

**Comment by maxandersen** [comment]
I'm just puzzled what changed since I can't grok how devmode could work before without what it does now ;)

to @ia3andy's comment then I agree we should support the usecase of serving frontend but my question is this - why can't that content be put in `src/resources`  (and then git ignored if needed) - would that work for you ? 

only usecase that might be tricky is if there are some transformations needed but lets look at solving that once we got the exact usecase down.

**Comment by stuartwdouglas** [comment]
So the actual error here is simple enough to fix, the deleteIfExists can be changed to some kind of deleteRecursive call. This is a real bug, as it will show up in other use cases if the user deletes a directory that was being watched.

Another problem is https://github.com/quarkusio/quarkus/commit/d81e508b6fb543724bd526c01304c28ebedc3d8f which now causes an app reload if a web resource is modified, just to update the not found error page. 

This is not great, as there is really no reason to restart when modifying static resources, so I am going to look at implementing a fix.
