### ISSUE TITLE
Upgrade MongoDB dependencies to 3.12.0

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#6418]
**Description**

It'd be useful if the Quarkus MongoDB dependencies could be bumped to the latest version(s) - currently 3.12.0, as it'd help the Camel Mongo extension to remain compatible.

**Comment by gastaldi** [comment]
For the record, there is a PR that changes the drivers used by MongoDB: https://github.com/quarkusio/quarkus/pull/6375

**Comment by gastaldi** [comment]
And there is a PR that fixes this issue: https://github.com/quarkusio/quarkus/pull/6347

**Comment by gastaldi** [comment]
Assigning to @loicmathieu as he already started working on it

**Comment by loicmathieu** [comment]
@jamesnetherton Apache Camel Mongo still use the uberjar `mongodb-java-driver` that includes the legacy API. Quarkus will now use the new drivers (mongodb-driver-synch and mongodb-driver-reactivestreams) so there can be some issues after  #6375 and if Camel Mongo relies of some legacy stuff they need to migrate or to include the legacy driver (mongodb-driver-legacy).

**Comment by jamesnetherton** [comment]
@loicmathieu thanks for the heads up. I need to verify, but I think using `mongodb-driver-legacy` will work ok in the short term. Ideally we'd migrate the Camel component to use newer driver dependency. I'll create an issue over on the Camel side to investigate.
