### ISSUE TITLE
Add ability to disable swagger ui

### ISSUE THREAD

**Issue by mattyb678** [quarkusio/quarkus#6425]
**Description**
It would be nice to be able to disable the swagger ui, even in dev/test mode. My company has a custom swagger-ui that we want to continue using. 

**Implementation ideas**
I'm new to quarkus, but it seems that adding a `disable` boolean to `SwaggerUiConfig` and then checking that boolean in the `BuildStep`s would suffice.

**Comment by gsmet** [comment]
Looks like you're ready to prepare your first PR :).

**Comment by gastaldi** [comment]
I'd recommend it to be named `enable` as how other extensions also do it: https://github.com/quarkusio/quarkus/blob/e07575d916f7b2229264070f99327fca8685059f/extensions/logging-json/runtime/src/main/java/io/quarkus/logging/json/runtime/JsonConfig.java#L20
