### ISSUE TITLE
url-pattern not configured properly in Vertx

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#6426]
Quarkus is not handling some contents of a web.xml file properly.
Specifically the url-pattern on a servlet-mapping does not appear
to get set properly in Vertx.

    <servlet>
        <servlet-name>javax.ws.rs.core.Application</servlet-name>
    </servlet>
    <servlet-mapping>
        <servlet-name>javax.ws.rs.core.Application</servlet-name>
        <url-pattern>/myresources/*</url-pattern>
    </servlet-mapping>

The request uri passed to resteasy from Vertx is "/myresources/hello"
but is should be "/hello".

This testcase demonstrates the issue
https://github.com/rsearls/quarkus-NoApplicationSubclassTest

--
In order to run the test you need to install this archive in your local repo

mvn install:install-file \
   -Dfile=___FIX_THIS___/lib/utils-arquillian-utils-4.5.0-SNAPSHOT.jar \
   -DgroupId=org.jboss.resteasy \
   -DartifactId=utils-arquillian-utils \
   -Dversion=4.5.0-SNAPSHOT \
   -Dpackaging=jar 

---
Set a breakpoint at following to see the issue
  RootClassNode line 67   ;; here you will see the resource path "/hello" is
                          ;; being registered

  SynchronousDispatcher line 323  ;; here you will see request is of type
                          ;; VertexHttpRequest.  In this obj the value of
                          ;; uri.path is "/myresources/hello" but it should be
                          ;; "/hello"

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 

**Additional context**
(Add any other context about the problem here.)

**Comment by stuartwdouglas** [comment]
This is actually a weird part of the JAX-RS spec that lets you map RESTeasy as an implicit Servlet. 

We should probably support it but there are already a few other ways to set this such as quarkus.resteasy.path and using the ApplicationPath annotation, so it is not a high priority.

**Comment by rsearls** [comment]
OK.  I've been asked to get all of resteasy's integration tests running with quarkus.  Do you want me to continue to filing like issues I encounter with web.xml elements or skip it for now?

**Comment by stuartwdouglas** [comment]
I have submitted a fix
