### ISSUE TITLE
web.xml's filter-class not configured properly in Vertx

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#6433]
Quarkus is not handling some contents of a web.xml file properly.
A filter-class defined in a web.xml is never called by Vertx,
nor is an error message or warning about lack of support of this 
element provided.

    <filter>
        <filter-name>Resteasy</filter-name>
        <filter-class>
            org.jboss.resteasy.plugins.server.servlet.FilterDispatcher
        </filter-class>
        <init-param>
            <param-name>javax.ws.rs.Application</param-name>
            <param-value>org.jboss.resteasy.utils.TestApplication</param-value>
        </init-param>
    </filter>

This testcase demonstrates the issue
https://github.com/rsearls/quarkus-ApplicationFilterTest

---
Set a breakpoint at following to see the issue
  FilterDispatcher line 35  ;; here you will see the class is never called.

**Comment by gsmet** [comment]
You will need the `quarkus-undertow` extension if you want the `web.xml` to be taken into account.
