### ISSUE TITLE
The quarkus-maven-plugin 1.1.1.Final is missing

### ISSUE THREAD

**Issue by Teg79** [quarkusio/quarkus#6441]
**Describe the bug**
Building a fresh project results in an error

**Expected behavior**
Compile working

**Actual behavior**
Maven error:
`The POM for io.quarkus:quarkus-maven-plugin:jar:1.1.1.Final is missing`

**To Reproduce**
1. Create a new project from START CODING
2. Run `./mvnw compile`

**Environment (please complete the following information):**

 - Output of `uname -a` or `ver`: `Darwin PC153-2 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
```
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.5.10.1 (build 11.0.5+10-LTS, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.1.1.Final

**Additional context**
If I use the quarkus maven plugin 1.1.0.Final it works

**Comment by gsmet** [comment]
Your mirror might be lagging a bit. It’s on Central: https://search.maven.org/artifact/io.quarkus/quarkus-maven-plugin/1.1.1.Final/maven-plugin

**Comment by dwamara** [comment]
Had exactly the same problem a couple of minutes ago. I had to restart the command that I use
> mvn clean package quarks:dev

to get it working

**Comment by Teg79** [comment]
Resolved, repo2.maven.org received the artifact hours ago but the repo1 only now, our proxy is on repo1, sorry
