### ISSUE TITLE
quarkus-arquillian / REST proxy builder / IllegalArgumentException

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#6450]
Quarkus 1.0.1.Final is using quarkus-arquillian 1.0.1.Final via quarkus-universe-bom.
A resteasy test run using  quarkus and arquillian is executing only the @Before
method.  The @After method nor the 2 @Test methods are executed.  The @Before
method causes an interface proxy class to be created and then called. Object
creation and call succeeds with out error however the quarkus-arquillian code
thinks there is an java.lang.IllegalArgumentException on the interface class.
Internally(arquillan)  flags the exception but does not print it to the terminal.  This
exception appears to cause @After and @Test methods to be skipped.

Test case the demonstrates the issue.
  https://github.com/rsearls/quarkus-ProviderInjectionTest.git

Set breakpoints at 
QuarkusJunitCallbacks line 27

ProviderInjectionTest line 47
                      line 53
                      line 62
                      line 73

**Comment by gsmet** [comment]
@mkouba could you have a look? IIRC, it's you who pushed the Arquillian connector?

**Comment by mkouba** [comment]
I can take a look but note that quarkus Arquillian adapter is not meant to be used for anything other than MicroProfile TCK.

**Comment by mkouba** [comment]
@rsearls is your reproducer using the resteasy master?

**Comment by rsearls** [comment]
Yes.   But you do need to install in your local repo the provided archive.

**Comment by mkouba** [comment]
@rsearls Is it still a problem with the latest version of quarkus? (1.6.0 to this date)

**Comment by mkouba** [comment]
Hm, what I observe with your reproducer (after I add the `org.jboss.arquillian.junit:arquillian-junit-container` dependency to fix a compilation problem) is that `@Before setup()` and `@After after()` are called too many times (both are invoked 4x instead of 2x, ie. for each test method).

**Comment by rsearls** [comment]
outdated
