### ISSUE TITLE
How to configure claim to use for name in UserPrincipal with OIDC adapter

### ISSUE THREAD

**Issue by vicentini** [quarkusio/quarkus#6454]
Following the [OIDC guide](https://quarkus.io/guides/security-openid-connect), we've been able to secure our web applications, but are struggling with the token content.

Is it possible to use another claim as name in UserPrincipal than preferred_username?
We've been using thorntail with the Keycloak Java Adapter where it's possible to configure _principal-attribute_ as documented [here](https://www.keycloak.org/docs/latest/securing_apps/#_java_adapter_config).

Migrating to quarkus now, we've been unable to find such an option.
Did we miss something or is this a planned feature?

**Comment by sberyozkin** [comment]
@vicentini No, unfortunately it is not possible yet. Let me update the labels.

**Comment by sberyozkin** [comment]
@vicentini FYI, [this PR](https://github.com/quarkusio/quarkus/pull/6586) introduces `quarkus.oidc.token.principal-name` property
