### ISSUE TITLE
Provide option on the @ConfigProperties annotation to control the kebab-case naming of properties

### ISSUE THREAD

**Issue by marceloverdijk** [quarkusio/quarkus#6457]
As discusses https://groups.google.com/forum/#!topic/quarkus-dev/NgbXygc1rps

Looking at https://quarkus.io/guides/all-config all config properties seem to use a kebab-case naming strategy.

When creating a custom config properties class (or interface in this case) like:

```
@ConfigProperties(prefix = "graphql")
public interface GraphQLConfiguration {

    String getSchemaLocation();

    String getSchemaFileExtension();

    Integer getMaxQueryComplexity();

    Integer getMaxQueryDepth();

    Boolean getTracing();
}
```

I would expect that these would also follow the kebab-case, but this isn't the case :-)

It is expecting the Java bean convention name, which is not consistent with out-of-the-box Quarkus configuration properties.

It can be workaround adding a `@ConfigProperty(name = "schema-location", defaultValue = "/graphqls")` annotation explicitly; but this will lead to a lot of boilerplate.

The idea mentioned on the forum is to provide an option on the `@ConfigProperties` annotation to control the kebab-case naming.

**Comment by geoand** [comment]
I only had a little battery left on my laptop but I was able to complete the actual fix for this. Sadly I don't have enough juice to clean it up and write docs, that will have to wait until tomorrow :)
