### ISSUE TITLE
RestAssuredURLManager - make it possible to set useSecureConnection through a config property

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#6459]
It is possible to use `QuarkusUnitTest.withSecuredConnection()` to use the secure protocol for `RestAssured.baseURI`. It should be possible to change this behavior for `@QuarkusTest` as well.

I propose to read the `quarkus.secure-connection` config property in `RestAssuredURLManager.setURL()` and if not set use the `RestAssuredURLManager.useSecureConnection` value.

**Comment by geoand** [comment]
@mkouba isn't this a duplicate of https://github.com/quarkusio/quarkus/issues/5877? Mind adding your comment there and closing this one?

**Comment by mkouba** [comment]
@geoand ah sorry, of course it is. I'll close this one.

**Comment by geoand** [comment]
Thanks @mkouba!
