### ISSUE TITLE
JWT cookies bug

### ISSUE THREAD

**Issue by Tayeh** [quarkusio/quarkus#6460]
**Describe the bug**
using mp-jwt with cookies 
all request get 401 Unauthorized  and also the request with @PermitAll annotation

**Expected behavior**
the page with @PermitAll Expected to work without token 

**Actual behavior**
the page with @PermitAll required token to work

**Configuration**
```properties
# JWT
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=Tayeh-Orange
smallrye.jwt.token.header=Cookie
smallrye.jwt.token.cookie=Authorization
quarkus.smallrye-jwt.enabled=true

```

**Screenshots**
![image](https://user-images.githubusercontent.com/9280478/71978127-491b6e00-3223-11ea-8918-b56c19ba19d5.png)
![image](https://user-images.githubusercontent.com/9280478/71978167-59cbe400-3223-11ea-9269-8ba1302a5fbc.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux tayeh 5.4.7-200.fc31.x86_64 #1 SMP Tue Dec 31 22:25:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "1.8.0_232"
 - GraalVM version (if different from Java): not installed
 - Quarkus version or git rev: try with 1.1.0.final and 1.1.1.final same problem

**Comment by sberyozkin** [comment]
@Tayeh As discussed at Zulip, this is no longer a bug, thanks
