### ISSUE TITLE
JWT - Token is invalid when claim "exp" is not present

### ISSUE THREAD

**Issue by seseso** [quarkusio/quarkus#6462]
**Describe the bug**
Token is invalid: JWT (....) rejected due to invalid claims or other invalid content. Additional details: [[2] No Expiration Time (exp) claim present.]

**Expected behavior**
The RFC states that there are no required claims, only Optional ones so I think it shouldn't fail (https://tools.ietf.org/html/rfc7519#section-4.1)

**Actual behavior**
Token is invalid: JWT (....) rejected due to invalid claims or other invalid content. Additional details: [[2] No Expiration Time (exp) claim present.]

**To Reproduce**
1. Create a token without the claim "exp" and send it to a rest endpoint where quarkus.smallrye-jwt.enabled is enabled and configured

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10 PRO
 - Output of `java -version`: openjdk version "1.8.0_212"
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 1.0.1.Final

**Comment by sberyozkin** [comment]
@seseso it is the same as supporting the unverified tokens really, even though the spec texts make it optional, the token with the unlimited lifetime can be used by anyone.
I don't know. In the case of supporting the unverified tokens we have them actually validated somewhere at the barrier, so the users do not want them verified. 
What is your use case ?

**Comment by seseso** [comment]
I wanted to use a token as a service to service authentication mechanism,
more or less like an API key but, for that to work, the token shouldn't
expire.  For now, I  define the expiration date as the long max value as
its required but, since the spec doesn't require any field, I was curious
about the implementation.

**Comment by sberyozkin** [comment]
@seseso but [MP JWT requires it](https://download.eclipse.org/microprofile/microprofile-jwt-auth-1.1.1/microprofile-jwt-auth-spec.html#_minimum_mp_jwt_required_claims).
I think I'll close this issue as I'm not sure we  can let the tokens without the `exp` claims without introducing the risk for the users to make a mistake.
Hope you are OK with it, since you have a reasonable workaround for your use case
Thanks

**Comment by sberyozkin** [comment]
Note we are actually going to introduce a `ttl` property to let the users to block the tokens with too long `exp` values, but the good news it would be not set by default :-)
