### ISSUE TITLE
@Transactional annotation doesn't work in JUnit tests

### ISSUE THREAD

**Issue by sudhirtumati** [quarkusio/quarkus#6463]
**Describe the bug**
Database changes made during JUnit tests are not rolled back even when test class and/or method is marked @Transactional

**Expected behavior**
Database changes must be rolled back when test method is annotated with `@Transactional `

**Actual behavior**
Database changes are not rolled back causing other tests to fail

**To Reproduce**
1. Clone this [sample](https://github.com/sudhirtumati/quarkus-sample.git) repo
2. Run `mvn clean test` from command line

**Configuration**
```properties
# datasource configuration
quarkus.datasource.url=jdbc:h2:~/test
quarkus.datasource.driver=org.h2.Driver

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create

```

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Linux SUDHIR-TP 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment 18.9 (build 11.0.5+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.5+10, mixed mode)
```
 - Quarkus version or git rev: `1.1.0.Final`

**Additional context**
(Add any other context about the problem here.)

**Comment by stuartwdouglas** [comment]
This is not how @Transactional works, it just starts a regular transaction that would be committed as normal. In addition this transaction is not propagated over JAX-RS calls, so even if it did roll back on the client side the server side transaction would commit as normal.

This would need a new annotation (we have talked about @TestTransaction in the past), and would require some work to automatically propagate the transaction over HTTP.

**Comment by sudhirtumati** [comment]
With Spring (and of course SpringBoot), `@Transactional` works this way. Just annotating the test class with this annotation makes all tests run in separate transactions and all changes are rolled back after test is complete. I find this behavior very convenient.

PS: I am sure this is the behavior with `MockMvc`. I can try and see if it is the same case with `RestAssured`

**Comment by kostacasa** [comment]
@sudhirtumati is right. Anyone coming from Spring Boot world would expect a "transactional test" to perform all persistence operations within a test-owned transaction that is rolled back at the end of that test. 

The documentation mentions the concept of transactional tests both in the transaction guide and testing guide, but doesn't fully explain what they do which is undoubtedly making people jump to the wrong conclusion.

**Comment by geoand** [comment]
> With Spring (and of course SpringBoot), `@Transactional` works this way. Just annotating the test class with this annotation makes all tests run in separate transactions and all changes are rolled back after test is complete. I find this behavior very convenient.
> 
> PS: I am sure this is the behavior with `MockMvc`. I can try and see if it is the same case with `RestAssured`

This only works in Spring when you are running tests against the in-memory spring context - it does **not** work for RestAssured style tests
