### ISSUE TITLE
JVM arguments should be an array instead (under Gradle's QuarkusDev task)

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#6464]
## Description

Currently, `jvmArgs` is just a `String` member; I think it's more appropriate to "convert it" into an array/list of `String`s.

```groovy
tasks.withType(QuarkusDev) {
  final def walletHome = System.getenv("WALLET_HOME")

  // Sausage-like String; way better as "tokens"
  jvmArgs = "-Djavax.net.ssl.keyStore=/path/to/keystores/keystore.jks -Djavax.net.ssl.keyStorePassword=store -Djavax.net.ssl.trustStore=/path/to/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword=trusted -Djdk.tls.allowUnsafeServerCertChange=true -Djdk.tls.client.protocols=TLSv1.2 -Doracle.net.tns_admin=${walletHome} -Doracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=${walletHome})))"
}
```

**Comment by gastaldi** [comment]
Good idea, want to provide a PR?

**Comment by x80486** [comment]
Do you have any pointers for backwards-compatibility? Overloading `setJvmArgs` is easy, but if someone is just using `jvmArgs` and the type is changed it's going to break the build script.

**Comment by gastaldi** [comment]
Maybe deprecate jvmArgs and create jvmArgsList?

Em Qua, 8 de jan de 2020 17:19, x80486 <notifications@github.com> escreveu:

**Comment by x80486** [comment]
OK, I'm going to go that route 🤣
