### ISSUE TITLE
Display proper error message when setting invalid configuration at runtime

### ISSUE THREAD

**Issue by zakhdar** [quarkusio/quarkus#6466]
I want to start a project deployed on kubernets (not compiled in native) 
i get this message 
`Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:307)
	at io.quarkus.runtime.Application.start(Application.java:87)
	at io.quarkus.runtime.Application.run(Application.java:210)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors has prevented the application from starting
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:28134)
	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Config.zig:1864)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:133)
	... 3 more`

is it possible to have a better error description ?

**Comment by geoand** [comment]
Hi,

Would it be possible to have a minimum reproducer project for this? I am very very interested in seeing it because so far I have been unable to reproduce the problem.

cc @gsmet

**Comment by zakhdar** [comment]
@geoand  i find the problem ,  in my project  i have a pipeline in gitlab that build and deploy the project on kubernetes . 

I had a problem in one of my gitlab scripts which defined the quarkus profile to be used in function of the branch,

on my script  if have a line like 
`sed -i 's/_BUILD_/'"$QUARKUS_PROFILE"'/g' src/main/docker/Dockerfile-java.multistage ;`

and my Dockerfile-java line are : 
`RUN mvn   -f /usr/src/app/pom.xml  clean package -Dquarkus.profile=_BUILD_ -Dmaven.test.skip=true`

but the var $QUARKUS_PROFILE  was not definied.  so i get this error, you can reproduce  step by using -D.quarkus.profil=  without variable.

it still means that if we use the -Dquarkus.profile property without defining a value it is taken into account

**Comment by geoand** [comment]
@zakhdar Thanks very much for the analysis!

I was able to reproduce this using `-D.quarkus.profile=`. We'll need to fix the error message for this

**Comment by geoand** [comment]
@dmlloyd it seems that `ConfigDiagnostic#missingValue` is logging the fact that `quarkus.profile` is missing (because the value is set to empty), but that error is never actually logged in the console.

Any idea what's going on? Is there something I need to do with the `DelayedHandler` perhaps?

**Comment by dmlloyd** [comment]
At one point we had a thing which would ensure that the logging got flushed even if configuration failed, before the application exited.  But at the very least, the caused-by of the exception should have been something like "Failed to read configuration".

One thing we talked about briefly today was maybe we should be adding suppressed exceptions for each individual validation error.  However that could result in a very large exception trace when there are multiple validation problems (unless we deliberately cut out the stack traces of the individual failures, which is an option).  Another option would be to compile the complete list of validation issues into the exception message.  But you'd still have to read the full caused-by to find it in any case.

**Comment by geoand** [comment]
Thanks for the input @dmlloyd. 

I'll look into it soon since we really should have better error messages for 1.2
