### ISSUE TITLE
Extend transaction boundary for `@Suspended` JAX-RS methods.

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#6471]
In JAX-RS we can make async requests by returning an async type, or with a `@Suspend` parameter. We already support extending the transaction boundary in the narayana transaction interceptor for async return types but we also need to do the same for `@Suspend` methods.

We can do that by adding an SPI that lets us know if an intercepted method is async or not.

**Comment by FroMage** [comment]
Actually it's not as simple as asking the SPI extension if we should extend the transaction boundary. Because we do that extension by wrapping the returned CompletionStage with an extra "andThen" action that will handle the commit/rollback.

And in the case of @Suspended methods there's no return type and the way to get notification about the request end is by hooking into the async response as a AsyncCompletionHandler (if I remember the name correctly), which is also jax-rs specific. So the SPI should do two things:

- answer if the method is async
- return a CompletionStage we can hook on if that is the case. This way we have the same transaction-boundary-extending code path for both cases. This resteasy SPI impl would create a CompletableFuture instance that gets completed by the relevant AsyncCompletionHandler it registers.

**Comment by stuartwdouglas** [comment]
Do we still care about this?

**Comment by geoand** [comment]
I think we can close this as we have better solutions for this
