### ISSUE TITLE
"Quarkus augmentation completed in" message includes native-image build time

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#6476]
**Describe the bug**
Just noticed that now the log message of "Quarkus augmentation completed in [time]" is including all the time it takes to build a native-image:

    Quarkus augmentation completed in 211620ms

This doesn't look too good.

**To Reproduce**
1. Build any native-image 
2. Read the logs

**Comment by stuartwdouglas** [comment]
Not much we can do about this other than suppress the message. It is possible that we might want to do further augmentation steps after the native image build (e.g. building and deploying docker images), so this is not restricted to native image.

**Comment by stuartwdouglas** [comment]
I am going to close this. The user already knows that the native image takes a while, so IMHO it is obvious that this time is being included.
