### ISSUE TITLE
Converter for extension config in deployment module fails in tests

### ISSUE THREAD

**Issue by manovotn** [quarkusio/quarkus#6479]
**Describe the bug**
Assuming a custom extension with a configuration that uses custom converter, then placing this converter in a deployment module results in failures within `@QuarkusTest` (while working in dev mode). The config is `ConfigPhase.BUILD_TIME` so it shouldn't be needed in runtime at all.
However, some digging shows that the generated class `io.quarkus.runtime.generated.Config` contains this config too while it (IMO) shouldn't.

**Expected behavior**
The test should pass as the converter is only used in build time.

**Actual behavior**
`@QuarkusTest` fails with:
```
[ERROR] testHelloEndpoint  Time elapsed: 0.007 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.MyResourceTest]: org/acme/myext/deployment/config/DisablementConverter
Caused by: java.lang.NoClassDefFoundError: org/acme/myext/deployment/config/DisablementConverter
Caused by: java.lang.ClassNotFoundException: org.acme.myext.deployment.config.DisablementConverter
```

**To Reproduce**
1. [Clone this reproducer (mind the branch)](https://github.com/manovotn/devconf2020-myext/tree/converterInDeploymentModuleReproducer)
2. `mvn clean install` in the `extension` directory
3. `mvn clean install` in the `example` directory and you should see the test failure

**Comment by rsvoboda** [comment]
@manovotn did you apply any workaround or you just avoided this for DevConf 2020 workshop ?

**Comment by manovotn** [comment]
@rsvoboda we avoided this

**Comment by radcortez** [comment]
I've tried the reproducer with an updated Quarkus version and it works fine. I guess this was a CL issue that was fixed in the meanwhile.
