### ISSUE TITLE
Double GraalVM compatibility effort

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#6483]
The idea is to try to support both GraalVM 19.2.1 and GraalVM 19.3.0.2 (we will upgrade to 19.3.1).

- [ ] Create an internal CI job with GraalVM branch https://github.com/oracle/graal/tree/release/graal-vm/19.3 in JDK 11 mode to test Quarkus master (@geoand) -> create proper issues as @gwenneg doesn't have access to it
- [ ] Fix the `LocalizationFeature` incompatibility (@gwenneg)
- [ ] Go back to 19.2.1 as the default image (@gwenneg)
- [ ] Figure out the JNI situation: forced to enabled for 19.3.1 only (@gwenneg)
- [ ] See if current master works with 19.2.1 or if we need to condition some added substitutions (@gwenneg)
- [ ] Which `graal-sdk` version should we use? Does both 19.2.1 and 19.3.0 work with the same version?
- [ ] Adjust documentation and website

**Comment by geoand** [comment]
Now that 19.3.1 is released, we should just rely on it for CI I think and not on the `19.3` branch

**Comment by gwenneg** [comment]
I can take care of this update as part of the double compatibility final PR which will be submitted tonight.

Unless there's a last minute issue, Quarkus `1.2` will use the GraalVM SDK from `19.2.1` and support native image generation from both GraalVM `19.2.1` and `19.3.1`.

**Comment by gwenneg** [comment]
I forgot we need @cescoffier for the Docker image generation :)

@cescoffier could you please create `ubi-quarkus-native-image:19.3.1-java8` and `ubi-quarkus-native-image:19.3.1-java11`?

**Comment by cescoffier** [comment]
@gwenneg  push to quay in progress.
See https://github.com/quarkusio/quarkus-images/commit/e391ec4a39b92854419a4e14e2f7ea3ba510738a/checks?check_suite_id=401920973

**Comment by geoand** [comment]
Things are looking good I think, thanks a lot folks

**Comment by geoand** [comment]
The latest PR is https://github.com/quarkusio/quarkus/pull/6574, correct?

**Comment by gwenneg** [comment]
@cescoffier Thanks for the push!

@geoand Yes, #6574 is the only PR that is meant to be merged. All other PRs were opened for testing purpose only and most of them have already been closed.
