### ISSUE TITLE
Should Flyway run again with hot reload (a.k.a. ./gradlew quarkusDev)

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#6486]
I think this question doesn't fit on StackOverflow, because I don't know if that is the intended behavior of the framework (or not), but in my opinion it shouldn't.

Let's say I have a project; I'm using JPA and Flyway. I also stated `clean-at-start` for Flyway. I'm not expecting this to be triggered on a hot-reload, but only on the first application start, because what I have in mind with hot-reloading classes is that: try to reload the classes that changed and continue with the updates. I may have the wrong idea though, but that's how it feels with other frameworks I've used in the past.

Now, you can argue that it's a quick restart 😉 and all the settings apply to it...hence my question: is that the intended behavior with Quarkus?

**Comment by gastaldi** [comment]
I'll jump in the conversation and say yes. IMHO during hot reload the Quarkus app should behave like it was stopped and started again, therefore if your configuration states that it should `clean-at-start` that's exactly what is doing :)

**Comment by gastaldi** [comment]
Closing. Please start a discussion in the [Mailing list](https://groups.google.com/forum/#!forum/quarkus-dev) if you need more information :wink:
