### ISSUE TITLE
Provide an extension for MyBatis

### ISSUE THREAD

**Issue by kevingty** [quarkusio/quarkus#6490]
Hi, 
Considering using JPA would cost a lot of efforts on migration from original Spring/MyBatis projects to Quarkus. I'm trying with [MyBatis-CDI](http://mybatis.org/cdi/injection.html) for rebuilding the project within Quarkus.  But I got these Build failure Errors:

>  ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems:
[1] Unsatisfied dependency for type org.unisce.mapper.CourseMapper and qualifiers [@Default]
        - java member: org.unisce.service.impl.CourseServiceImpl#courseMapper
        - declared on CLASS bean [types=[org.unisce.service.CourseService, java.lang.Object, org.unisce.service.CurdService<org.unisce.model.Course>, org.unisce.service.impl.CourseServiceImpl], qualifiers=[@Default, @Any], target=org.unisce.service.impl.CourseServiceImpl]
[2] Unsatisfied dependency for type org.apache.ibatis.session.SqlSession and qualifiers [@Default]
        - java member: org.unisce.service.impl.CourseServiceImpl#sqlSession
        - declared on CLASS bean [types=[org.unisce.service.CourseService, java.lang.Object, org.unisce.service.CurdService<org.unisce.model.Course>, org.unisce.service.impl.CourseServiceImpl], qualifiers=[@Default, @Any], target=org.unisce.service.impl.CourseServiceImpl]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:858)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:220)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:251)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
        Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.unisce.mapper.CourseMapper and qualifiers [@Default]

I refer to code [examples ](https://github.com/mnesarco/mybatis-cdi-samples) .

My  SqlSessionFactory Producers:
----------------------------------------------------------------

@ApplicationScoped
public class MyBatisProducers {

    @ApplicationScoped
    @Named("course1")
    @Produces
    @SessionFactoryProvider
    public SqlSessionFactory produceFactory() throws IOException {
        String resource = "mybatis-config.xml";
        Reader reader = Resources.getResourceAsReader(resource);
        SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(reader);
        reader.close();

        return sqlSessionFactory;
    }
}
----------------------------------------------------------------

My Resource/Controller  Class:
----------------------------------------------------------------

`
@Singleton
@Path("/course")
public class CourseController {

	@Inject
	CourseService courseService;

	@GET
	@Path(value = "/list")
	public HttpResult findAll() {
		return HttpResult.ok(courseService.findAll());
	}
}
`
----------------------------------------------------------------

My Service Interface Class:
----------------------------------------------------------------

`
public interface CourseService  extends CurdService<Course> {
        List<Course> findAll();
}
`

----------------------------------------------------------------

My ServiceImpl Class :
----------------------------------------------------------------
`	
@Singleton
public class CourseServiceImpl implements CourseService {

	@Inject
	CourseMapper courseMapper;

	@Inject
	SqlSession sqlSession;

        @Override
	public List<Course> findAll() {

		List<Course> test2 = sqlSession.getMapper(CourseMapper.class).findAll();
		return test2;
	}
}`
----------------------------------------------------------------

I dont know whether it's caused by my misusing CDI annotation or  any MyBatis-CDI Quarkus problems.  Any professionals could help? Thanks a lot.

**Comment by gsmet** [comment]
@kevingty it would help if you could put together a small Maven reproducer.

**Comment by kevingty** [comment]
Hi @gsmet , I use gradle to build the project and upload the code to [my repository](https://github.com/kevingty/reproduce-mybatis-cdi-quarkus). Hope you could check it out. Thank you.

**Comment by kevingty** [comment]
@gsmet Hi, I find out that Quarkus ArC differs a lot from Weld implementation,  which is used within MyBatis-CDI. So it seems i got to write some glue code or customize an extension. Hope there would be a extension of MyBatis soon, since MyBatis as persistance layer with better SQL optimization is kind of mainstream in East Asia for dealing with high performance requirements.

**Comment by gsmet** [comment]
@kevingty maybe you could give it a try?

**Comment by gsmet** [comment]
@kevingty btw, I think you would be able to use MyBatis by handling things with a CDI bean yourself.

**Comment by zhfeng** [comment]
@kevingty @gsmet I just raise the PR https://github.com/quarkusio/quarkus/pull/10671 to add the mybatis extension. Can you take a review please ?

**Comment by hantsy** [comment]
@zhfeng If possible, move this extension to your own repo as a community support extension. I do not think there are lots of developers outside of China who use MyBatis in daily work. Personally, I have not used Batis for the past 10 years, never used MyBatis.

**Comment by gastaldi** [comment]
Repository created in the quarkiverse org, as per https://github.com/quarkusio/quarkus/pull/10671#issuecomment-706231300.

Closing
