### ISSUE TITLE
Introduce an exit request API with wait-for-exit method

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#6498]
**Description**
Introduce an exit request API with wait-for-exit method.  Methods should be defined as follows:

- A method to request that the application exit with a given exit code (non blocking) (e.g. `requestExit(int)`; code must be between 0 and 255 (inclusive))
- A method to request that the application exit with no code (0 is implied) (non blocking) (e.g. `requestExit()`)
- A method to wait for an exit request; this method returns the requested exit code (blocking) (e.g. `awaitExit()`)

**Comment by gastaldi** [comment]
Dumb question, but after the application exits, what is a valid use case for `awaitExit()`?

**Comment by dmlloyd** [comment]
The `awaitExit` method would be used to wait for someone to call `requestExit`.  Once exit is requested, `awaitExit` returns the requested exit code.

**Comment by ToWipf** [comment]
My way to stop the application:
```java
private boolean bShutdown = false;

@Override
public int run(String... args) throws Exception {
	LOGGER.info("start");
	while (true) {
		Thread.sleep(1000);
		if (bShutdown) {
			LOGGER.info("stop");
			return 0;
		}
	}
}

**Comment by stuartwdouglas** [comment]
This is present in Quarkus.waitForExit and Quarkus.asyncExit
