### ISSUE TITLE
Introduce ability to recognize and execute user main method(s)

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#6499]
**Description**
Introduce ability to recognize and execute user main method(s).

**Requirements**
- Introduce a means to identify a method as a main method (e.g. an annotation)
- Allow build-time configuration to specify which main method (if any) should be used for the build (can `@Named` be used for this?)
- The main method should be allowed to optionally accept a `String[]` or `List<String>` which contains the command arguments (minus the arguments processed by #6497)
- The main method should be allowed to optionally return an `int` which contains the desired exit code
- If the application shutdown fails with an exception, there should be a means to override the exit code.
- A mechanism may be defined to allow users to customize the mapping of exception to exit code; if implemented, the mechanism should accept the exception and the originally requested exit code, and return the new exit code.  If the mapping fails with an exception, an exit code of 1 should be used.
- `System.exit()` should be called with the final exit code once all shutdown work is complete (at the end of the _launcher main_ method).
- If no main method is defined, then the `waitForExit` method defined in #6498 should be used, with the code returned from that method being used as the requested exit code

**Exit codes reference**

Code | Description
---- | -----------
0 | Normal exit (no error, clean shutdown)
1 | Exit due to uncaught exception
2 | Exit due to configuration or usage error
10 | (reserved due to its usage with JBoss)

**Comment by maxandersen** [comment]
Reading the proposed items I'm struggling to figure out if I'll be able to as follows:

```
class Main {
public static void main(String... args) {
    QuarkusApplication.start(Main::handler); 
} 

int handler() {
}
}
```

here I'm just using a method reference, but could also be a class.

Main point is that I'll have a plain static main that can be booted by Quarkus.

Or is the expectation all is always handled by Quarkus ?

**Comment by dmlloyd** [comment]
That seems doable to me.  We just have to be sure that the Quarkus build process has a way to know which entry point main to use during build.

**Comment by maxandersen** [comment]
Yes, I assume we'll have a way to do both - the explicit main() method is mainly just for easy launching from IDE or command line jar runs.

**Comment by dodalovic** [comment]
@maxandersen Just curious how far we are from this wonderful feature? 
Cheers

**Comment by maxandersen** [comment]
@dodalovic sorry - didn't see your ping here before now - see #7681  for current progress

**Comment by maxandersen** [comment]
@stuartwdouglas  how much of this is fullfilled by #7681 ?

**Comment by stuartwdouglas** [comment]
Most of it, except for exception mapping for exit codes, which is going to be a follow up. Also failure due to config issue does not have it's own exit code, however that can be done as part of the exception mapping work.
