### ISSUE TITLE
allow encryption of application config file

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#6510]
**Description**
Actually, `application.properties` (`application.yaml`) is stored in plain text. However, it can have sensible information which should not be not stored in plain text **while running**. There are also use cases when the contents of the application config file should not be allowed to change by the user while running. Would be nice to have **automatic encryption of `application.properties` (`application.yaml`) while compiling** by a new property either in `pom.xml` or if possible in the `application.properties `(`application.yaml`) directly. 

**Implementation ideas**
Provide a new  ("build-time-only-")-property `quarkus.config.encryption=true` which when provided as a quarkus property in `pom.xml `(or in the config files directly) encryptes the `application.properties` (`application.yaml`) when compiling the project. Maybe the _Elytron filesystem security realm_ can be uses in this case.

**Comment by geoand** [comment]
We have better ways of providing sensitive information (like `Vault`), so I'll close this
