### ISSUE TITLE
allow rename of application config file

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#6512]
**Description**
Allow the renaming of `application.properties` (`application.yaml`) while compiling the project by a new property in `pom.xml `(or if possible in the config file directly). For example, `quarkus.config.file="app.lic"`.

**Implementation ideas**
Provide a new ("build-time-only-")-property in `pom.xml` (or if possible in the config files directly) `quarkus.config.file="string-value"` to allow the renaming of the config file.

**Comment by gsmet** [comment]
We don't want that. We want the Quarkus experience to be as streamlined as possible.
