### ISSUE TITLE
Provide Hibernate OGM

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#6514]
**Describe the extension**
With https://hibernate.org/ogm/, we can connect different NoSql stores (e.g., Cassandra, CouchDB, Apache Ignite, Infinispan, MongoDB, etc.). Would be nice to add  Hibernate OGM as extension. Its OGM-entities could also be simplified with PanacheEntity for OGM. 

However, I dont know if it would be better to provide extensions for the NoSql-Database directly instead of using Hibernate OGM. For example, better provide `quarkus-ignite` or `quarkus-cassandra` instead of `quarkus-hibernate-ogm`? Or provide both?

**Comment by Sanne** [comment]
Hibernate OGM uses the various NoSQL client drivers; to make a new OGM extension we should first have an extension for each NoSQL to be supported.

So in terms of milestones, it would indeed make sense to first provide extensions allowing "raw" direct use of each NoSQL, then think of an OGM extension as a second step.

**Comment by gsmet** [comment]
I don't think we should include Hibernate OGM in Quarkus so I'm closing this one.

**Comment by nimo23** [comment]
>I don't think we should include Hibernate OGM

@gsmet more information about the reason for closing would be good so others can understand the decision. Does this mean that you think there is no need for no-sql-storages in quarkus?

**Comment by nimo23** [comment]
I also find that >it would indeed make sense to provide extensions allowing "raw" direct use of each NoSQL storages. I think Hibernate OGM is not needed if raw direct access to the no-sql-storages can be provided by quarkus.

If am going to open an issue for an extension of `quarkus-ignite` (with Apache Ignite), do you think you close this issue?

**Comment by gsmet** [comment]
No, just that Hibernate OGM is not the right solution for that.

We can have drivers for the various NoSQL databases if there is enough interest in them and people wanting to contribute.

And by interest, I mean people really wanting to use it.
