### ISSUE TITLE
Tool to generate Rest Client code

### ISSUE THREAD

**Issue by viniciusfcf** [quarkusio/quarkus#6540]
**Description**
OpenAPI and Rest Client are microprofile specs and does not exist a tool to generate a Rest Client code based on an OpenAPI generated yaml/json.

**Implementation ideas**

1. VSCode Quarkus extension upgrade to generate Rest Client based on an OpenAPI generated yaml /json file
2. Maven target to generate Rest Client based on an OpenAPI generated yaml/json
3. "Generate Rest Client" button on swagger-ui page.

**Comment by rquinio** [comment]
Maybe we would need a new "language" in swagger-codegen for mp-rest-client, similar to existing languages for JAX-RS client proxies (https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/JavaJaxRS ) ?
I think the main difference with existing JAX-RS language used via CXF/RESTEasy client would be to generate also the asynchronous return types CompletionStage<T> that come with microprofile -rest-client.
