### ISSUE TITLE
Hibernate ORM Implicit Naming Strategy Config

### ISSUE THREAD

**Issue by dima-fedotovs** [quarkusio/quarkus#6546]
Initial discussion - https://groups.google.com/forum/#!topic/quarkus-dev/F2Xu_1dKick

> I'm trying to apply a custom implicit naming strategy using hibernate.implicit_naming_strategy configuration option. 
> 
> There is no possibility to put it to application.property file yet. So I have to put it to persistence.xml. But in my case some of the hibernate options must be in application.properties as I want them to be configured via the environment variables, for example, quarkus.datasource.url.
> 
> It isn't possible to use application.properties and persistence.xml together at the same time to configure hibernate.
> 
> After some experiments, I've found that I can use hibernate.properties instead of persistence.xml to configure naming strategy. 
> 
> Running app in dev mode works as expected. I see in the log:
> 
> 020-01-14 10:39:18,119 INFO [org.hib.cfg.Environment] (build-34) HHH000205: Loaded properties from resource hibernate.properties: {hibernate.bytecode.use_reflection_optimizer=false, hibernate.implicit_naming_strategy=org.example.CustomNamingStrategy}
> 
> and further logs shows that the naming strategy is applied and everything works fine.
> 
> But after deploying to Kubernetes in prod mode it works differently. There is the same log message that configuration is read, but custom naming strategy isn't applied.
> 
> As well test-mode works same as prod - naming strategy isn't applied.

We need to support implicit naming strategy in application.properties

**Comment by gsmet** [comment]
We had a lot of reservations about implementing the customization of the implicit strategy.

So here is a question for you: why do you need that? What's your use case exactly?

**Comment by dima-fedotovs** [comment]
We have pretty strict naming conventions that are different for naming entities/properties and tables/columns. For example, all our entities are named in singular, camel case, and suffixed with "Entity" (UserEntity, UserAddressEntity), but table corresponding to the entity must be named in the plural, snake_case and without any suffixes (users, user_addresses).
Similarly, columns should be camel_cased as well.
Writing such ImplicitNameStrategy isn't tricky, as rules are defined clearly, but makes the code cleaner - it isn't requiring to add Table and Column annotation everywhere in entities

**Comment by gastaldi** [comment]
PR created in https://github.com/quarkusio/quarkus/pull/6547. I'll let @gsmet decide whether that PR should be integrated or not :smiley: 

@dima-fedotovs can you give that PR a try and see if that works for you?

**Comment by Sanne** [comment]
Ok, I think we should allow this.

Wondering though: should we explore ways to automatically discover a custom naming strategy rather than expose a configuration property?

**Comment by gastaldi** [comment]
Perhaps in a separate issue. Specifying the class name works for the
presented use cases.

Em Qua, 15 de jan de 2020 13:23, Sanne Grinovero <notifications@github.com>
escreveu:

**Comment by Sanne** [comment]
> Perhaps in a separate issue. Specifying the class name works for the
presented use cases.

I would prefer to not expose an additional configuration property: if we can keep such things simpler, we should explore that first.

**Comment by gastaldi** [comment]
I'm not sure how would that work TBH, I'm open for suggestions

**Comment by Sanne** [comment]
I'm thinking we could have an annotation to allow Quarkus to find extensions to frameworks; I've not thought much about it though, we should probably send a proposal to the mailing list - but I'm in meetings this weeks and struggling to find proper think time :)

We could have either a `@HibernateExtension` (name unimportant but I hope it gives the idea) which people could slap on implementations of `NamingStrategy` or any other Hibernate extension point - 

 - or perhaps a more generic pattern like `@FrameworkExtension` could work to express the same intent for all frameworks we support ? This one would be a bit more complicated to pull out, but could provide a more consistent way of extending all our stuff.

@gastaldi would you like to explore this and perhaps propose on the mailing list?  I don't want to push this on you, I guess if you're busy it can wait.

**Comment by dima-fedotovs** [comment]
I'm not sure how annotation can help. It isn't possible to define multiple Implicit Naming Strategies in Hibernate. So it will be required to introduce a mechanism/rules on how to select a single one if there are more than one class annotated.

**Comment by gsmet** [comment]
Yeah, frankly, we already merged the physical naming strategy as a
configuration knob, I would rather be consistent.

**Comment by dima-fedotovs** [comment]
BTW I've tested the PR. It works perfectly for me. Thanks! I really hope it will be a part of the next release

**Comment by Sanne** [comment]
Ok let's not block this one: makes sense to have the feature, I can think about my alternative extensions mechanism another time.

**Comment by gastaldi** [comment]
Cool, can someone approve https://github.com/quarkusio/quarkus/pull/6547? :smiley:
