### ISSUE TITLE
Running mvn package -DskipTests=true doesn't produce the runner jar

### ISSUE THREAD

**Issue by evanchooly** [quarkusio/quarkus#6554]
**Describe the bug**
Skipping the tests sidesteps the entire execution of the BuildMojo

**Expected behavior**
I should be able to skip running the tests and still package up the runner jar.

**Actual behavior**
The standard jar is built but not the runner.

**To Reproduce**
1. mvn clean package -DskipTests=true
2. ls target/

**Comment by gsmet** [comment]
@evanchooly it's specific to something or it's for all the Quarkus applications?

**Comment by evanchooly** [comment]
I get it trying to build an integration-test, e.g.  It seems the `skip` parameter on `BuildMojo` is picking up on that property somehow and getting set incorrectly

**Comment by evanchooly** [comment]
doh.  just [found it](https://github.com/quarkusio/quarkus/blob/master/integration-tests/pom.xml#L20).  This should be removed maybe?  Not entirely useful but I can work around it.

**Comment by evanchooly** [comment]
that did it.  i can explicitly set that property when I need it.  (mostly) false alarm.
