### ISSUE TITLE
Document OIDC Multi-Tenancy feature

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#6571]
**Description**
The new OIDC multi-tenancy mechanism has been implemented by Pedro and now needs to be documented

@pedroigor Hey Pedro, you may already have some docs in progress, please do a follow PR, thanks

**Comment by pedroigor** [comment]
@sberyozkin I have the documentation done but here it is.

The quickstart used in the guide is using Google and Keycloak to authenticate depending on the tenant. It would be really nice if we could show multi-tenancy using a different OP but at the same time that would not work when testing the application.

Do you think it is acceptable to not have tests running for this quickstart?

Other than that, I'm ready to push the docs.

**Comment by sberyozkin** [comment]
Hi @pedroigor Great, thanks. I suppose we should probably keep it to Keycloak as it also promotes the idea of having the OIDC managing the further delegation if needed, something yourself and Stian recommended. May be also have the docs having a small section on how to connect to Google...If you agree with keeping it around Keycloak only then having a test would be good
thanks

**Comment by gsmet** [comment]
Do we have a PR for that one?

**Comment by pedroigor** [comment]
@gsmet Almost there. Most of the work is done. We have been discussing some changes to multi-tenancy that were important to understand what we should put in docs/quickstarts.

Based on the latest @sberyozkin, I'm not going to promote Google integration (sadly) but a single Keycloak instance serving multiple tenants/realms.

It should be ready tomorrow.

**Comment by DorianMaliszewski** [comment]
I did a little Medium post on it :sweat_smile: So you can go check it, and If you want I can do an other for the Quarkus Guides to help you !
https://medium.com/@maliszewskid3/implement-multi-tenancy-oidc-and-hibernate-on-quarkus-4f2e0214ed2d

**Comment by pedroigor** [comment]
@DorianMaliszewski Awesome! Thanks for sharing.

Just sent PRs for both docs and quickstart:

* https://github.com/quarkusio/quarkus/pull/7260
* https://github.com/quarkusio/quarkus-quickstarts/pull/464

Please, let me know what you think. Feel free to suggest any improvement.

Your doc is more complete for sure, as it also disclaims how to set-up multi-tenancy to Hibernate. Another difference is that you are showing a `service` application while I'm using a `web-app`. If you want to contribute another one or improve the docs herein proposed with specific instructions for `service` type applications, let me know. Although they are pretty much the same thing in terms of config ...

**Comment by DorianMaliszewski** [comment]
@pedroigor Yes your doc is like mine, I think it enough for everyone will want to implement multi tenant on Quarkus.
Great job 💪🏻
