### ISSUE TITLE
GELF extension guide missing in "open guide" menu option

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#6577]
**Describe the bug**
When clicking the extension menu (verticle "...")for gelf, selecting the "Open Guide" option links to a [non-existing guide](https://quarkus.io/guides/central-logging).

**Expected behavior**
Should link to this url: https://quarkus.io/guides/centralized-log-management

**Actual behavior**
Links to wrong URL

**Comment by ia3andy** [comment]
It seems the link is wrong in the extension metadata:
https://github.com/quarkusio/quarkus/blob/master/extensions/logging-gelf/runtime/src/main/resources/META-INF/quarkus-extension.yaml
