### ISSUE TITLE
Kafka codec are not registered for reflection

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#6587]
The extension should look at the class index and for each serializer and deserializer, register the class for reflection.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/blob/aa601cde8e243cd48f6a10a565c93d45ddb3ff5a/extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java#L76

That is what this code is doing. Is it not working?

**Comment by cescoffier** [comment]
I was also surprised but yes, if the application provides the codecs I had to register them myself like in https://github.com/cescoffier/quarkus-coffeeshop-demo/blob/master/barista-kafka/src/main/java/me/escoffier/quarkus/coffeeshop/codecs/OrderDeserializer.java#L7.

**Comment by stuartwdouglas** [comment]
JsonbDeserializer is not in the index, so Jandex cannot reason about it. We need to explicitly check for subclasses of JsonbDeserializer in the processor.

**Comment by cescoffier** [comment]
It was also the case when we extended Serializer/Deserializer directly.

**Comment by stuartwdouglas** [comment]
It is using getAllKnownSubclasses rather than getAllKnownImplementors

**Comment by cescoffier** [comment]
We should add a test for this and check the various cases. I can do that Today.

**Comment by stuartwdouglas** [comment]
I think this is the fix https://github.com/quarkusio/quarkus/commit/ef43cdfffaebfeb81d88216e1f4a1410e4449213
