### ISSUE TITLE
OpenID Connect code flow problem with Microsoft Active Directory Federation Services (ADFS)

### ISSUE THREAD

**Issue by ulmtal** [quarkusio/quarkus#6603]
Using Microsoft Active Directory Federation Services (ADFS)  with OpenID Connect fails with error:

MSIS9631: Received invalid OAuth request. Multiple client authentication methods were attempted.

Is it possible to add useBasicAuthorizationHeader to quarkus OpenID Connect Extension Parameter,
io.quarkus.oidc.runtime.OidcConfig -> https://vertx.io/docs/apidocs/io/vertx/ext/auth/oauth2/OAuth2ClientOptions.html to configure not using the useBasicAuthorizationHeader in the authorisation code -> Token POST request?

Or is there another way to disable useBasicAuthorizationHeader?

**Comment by sberyozkin** [comment]
@ulmtal it will be fixed with the upgrade to Vert.x 3.8.5 (#6526), scheduled for the Quarkus 1.3.0 release, thanks
