### ISSUE TITLE
Configurable name for the attribute groups in the DefaultRoleDecoder.

### ISSUE THREAD

**Issue by andrejpetras** [quarkusio/quarkus#6607]
**Description**
Make the name of the attribute groups configurable in the DefaultRoleDecoder

**Implementation ideas**
- Create a configuration parameter for the attribute groups
- Update the guides

Source code:
https://github.com/quarkusio/quarkus/blob/master/extensions/elytron-security/runtime/src/main/java/io/quarkus/elytron/security/runtime/DefaultRoleDecoder.java

**Comment by mesejo** [comment]
Hi, I could take this. What  should be  the name of the configuration property? Is "quarkus.security.default-role-decoder-name"  acceptable?

**Comment by kunal-kushwaha** [comment]
@mesejo : Hi, are you still working on this issue?

**Comment by mesejo** [comment]
@kunal-kushwaha Hi, no I'm not actively working in this issue

**Comment by andrejpetras** [comment]
@adrianfiedler will start work on it.

**Comment by andrejpetras** [comment]
@gastaldi could we assign this issue to @adrianfiedler?

**Comment by gastaldi** [comment]
@andrejpetras hm, I think he needs to belong to a certain team, which unfortunately I don't have access to do that :(

@gsmet might help here I think

**Comment by adrianfiedler** [comment]
Can this issue please be assigned to me? I already prepared a pull request here:
https://github.com/quarkusio/quarkus/pull/8307

**Comment by gastaldi** [comment]
Ah now it works :) Not sure what changed

**Comment by adrianfiedler** [comment]
@gastaldi I guess this can be closed now, as the PR was already merged: https://github.com/quarkusio/quarkus/pull/8307
