### ISSUE TITLE
OIDC test checking the custom principal name is unstable

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#6608]

**Comment by sberyozkin** [comment]
Martin @mkouba has helped to identify a possible issue with [SecurityidentityAssociation](https://github.com/quarkusio/quarkus/blob/master/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityIdentityAssociation.java).

The way it shows itself, as exposed by the [disabled test](https://github.com/quarkusio/quarkus/pull/6610), is that `SecurityIdentity` created by [OidcIdentityProvider.authenticate](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java#L74) which contains a principal is missed when [OidcJsonWebTokenProducer](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcJsonWebTokenProducer.java) uses an injected `Securityidentity` to figure out which principal to return, and in the case of the failing test it looks like it picks up [this SecurityIdentity](https://github.com/quarkusio/quarkus/blob/master/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityIdentityAssociation.java#L46) and therefore a principal with a custom principal claim is missed

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi Stuart, what do you think, is `@Observes` needed ? Can we use ThreadLocal ?
CC @gsmet @geoand

**Comment by stuartwdouglas** [comment]
Is there an example of a failure somewhere? If the wrong bean was being provided by SecurityidentityAssociation then other tests would fail as well.

**Comment by sberyozkin** [comment]
Hi Stuart, @stuartwdouglas, the example is [here](https://github.com/quarkusio/quarkus/pull/6610).

**Comment by sberyozkin** [comment]
@stuartwdouglas I think [this test](https://github.com/quarkusio/quarkus/pull/6610) is failing (in CI only, not in the local build) because
[this code branch is executing](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcJsonWebTokenProducer.java#L61) while instead [this branch](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcJsonWebTokenProducer.java#L57) is always expected to run, which means to me that [this producer code](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcJsonWebTokenProducer.java#L38) is run before [this code is run](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java#L74).
What do you think ?

**Comment by sberyozkin** [comment]
Actually I know what it is

**Comment by mkouba** [comment]
@sberyozkin so the producer method declared on [OidcJsonWebTokenProducer](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcJsonWebTokenProducer.java#L37) should take precedence because it's declared on an enabled alternative bean (see https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#unsatisfied_and_ambig_dependencies for more information). Otherwise the build would fail with `AmbiguousResolutionException`. 

How and where do we set the `Principal` of the injected `SecurityIdentity`?

**Comment by sberyozkin** [comment]
Hi @mkouba, thanks, the principal [is set here](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java#L74).
But what happens is that by the time either of those producer methods is called, [this code](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java#L74) has not run yet (and it only is exposed in CI :-))

**Comment by sberyozkin** [comment]
@stuartwdouglas I wonder if a non-blocking CompletableFuture `authenticate` call might cause it, it is hard to come up with any other explanation as to why I can't reproduce it locally (Georgios tried it to) but it fails in the CI

**Comment by sberyozkin** [comment]
Hi Stuart, @stuartwdouglas, by the way, the reason the existing tests are not failing is that  [this code branch](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcJsonWebTokenProducer.java#L61) is parsing the same token which `OidcIdentityProvider` has already parsed. [This check](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcJsonWebTokenProducer.java#L57) I added earlier avoids it but due to the race condition suggested earlier it is now always effective, as such we have a token parsed 3 times :-) (at the Vertx level, and twice in our oidc extension).

**Comment by stuartwdouglas** [comment]
Do we have an example of what the exception actually looks like when this fails?

**Comment by stuartwdouglas** [comment]
I think I have a fix for this in the linked PR, lets see what CI says.

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi, the test I disabled would fail in CI, the test expects that `principal.getName` returning a custom principal name equal to the `email` claim but because `OidcIdentityProvider`'s customization of the `Principal` was missed in CI, the test assertion would fail, the Principal has no `principalClaim` available and the default `getName` method would be called.
Thanks for the fix, and I'll definitely keep an eye on this thread safety initialization issue going forward :-)
