### ISSUE TITLE
Refactor DynamoDB Extensions to Support Generic AWS SDK

### ISSUE THREAD

**Issue by sherl0cks** [quarkusio/quarkus#6616]
**Describe the extension**
There is a lot of config on the httpclients in https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-dynamodb/runtime/src/main/java/io/quarkus/dynamodb/runtime/DynamodbClientProducer.java that is useful beyond just dynamodb services. Quarkus in AWS Lambda is a pretty killer combo. Reducing friction here would be a big win.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Comment by machi1990** [comment]
Hi @sherl0cks there is a PR https://github.com/quarkusio/quarkus/pull/4968 to add broader support for Amazon Services by @marcinczeczko. Is that what you are looking for? 
 
/cc @gsmet

**Comment by sherl0cks** [comment]
@machi1990 wow, that's a biggie. Yea its the same idea. We can close this issue and I will watch that one.
