### ISSUE TITLE
Document how to use escaped {} in Qute

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#6621]
It would be helpful to document how users can print plain `{`s and `}`s without having them recognized as expressions.

Escaping them as XML Entities (`&#123;` and `&#125;`) works, but it took me a bit to figure that out, so other users might struggle with that as well. Or is there another, easier way?

And: is there a way to escape `{}` in plain text templates?

**Comment by maxandersen** [comment]
I bumped into this trying to use qute for .json and .java template  ...for now it seem to work as the { and } aren't on the same line so the problem might not be that big..but yeah, good to document how to work around it.

**Comment by mkouba** [comment]
So currently a valid expression must start with `{` followed by a non-whitespace char that is not `{`, and the closing `}` is ignored if not inside an expression. Ie. `{  foo}`, `{{foo}}`, `foo}` are all ignored. The plan is to only support identifiers that have characters `[A-Z]`,`[a-z]`, `[0-9]` and underscore. And we should probably also support a way (independent of file format) to escape the delimiters, e.g. `\{`.

**Comment by sdaschner** [comment]
@mkouba That is also good to know and would be super-helpful to have in the documentation.

A big +1, on the escape with `\{`, that was actually my first attempt to solve it, but doesn't work yet.

**Comment by dmlloyd** [comment]
Another use case for escaping `{` and `}` is CSS/JS.  Although templating JS might be a questionable activity. :-)

**Comment by mkouba** [comment]
Yes, especially the minified chunks of CSS/JS.
