### ISSUE TITLE
java -server or java -client

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#6626]
**Description**
I dont know if quarkus runs in **java client** or **java server** mode. Maybe it can be adjusted with a new property in `application.properties`, e.g. `quarkus.system.run`:

```
// use the java -server to enable the Java HotSpot Server VM (should be the default) 
quarkus.system.run.mode="server"
```

```
// use the java -client
quarkus.system.run.mode="client"
```

**Comment by stuartwdouglas** [comment]
This is a property of the JVM itself, it can't be changed from application.properties. If you are running a production application you control the command like that is used to launch the app, so you can select which one you want. For dev mode you can control it with "-Djvm.args=-client"
