### ISSUE TITLE
HTTP-206 when a resource is bigger than 1MB

### ISSUE THREAD

**Issue by sciack** [quarkusio/quarkus#6631]
**Describe the bug**
If a resource in META-INF/resources is bigger than 1MB the content will be partially transferred when the app is running in native mode

**Expected behavior**
The resource will be fully transferred

**Actual behavior**
Two different behavior happen:
1. Quarkus answer with 206 and a partial file is transferred
1. The browser hang waiting for the resource

**To Reproduce**
1. download this test project https://bitbucket.org/msciachero/quarkus-resource-bug-prj.git
2. mvn package -Pnative
3. `target/quarkus-resource-bug-prj-1.0.0-SNAPSHOT-runner`
4. open http://localhost:8080

**Configuration**

```properties
# Add your application.properties here, if applicable.
<empty>
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1496853/72702499-dfd61c00-3b8d-11ea-859d-40041eb7c53d.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Mirkos-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009173705.graal.jdk8u-src-tar-gz-b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
 - GraalVM version (if different from Java): 19.2.1 CE
 - Quarkus version or git rev: 1.1.1.final

**Additional context**
(Add any other context about the problem here.)

**Comment by sciack** [comment]
Just as addition, this project works perfectly fine on Linux:
Linux mirko-Inspiron-13-5378 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Could be something related to gcc on Mac?

**Comment by jaikiran** [comment]
It could be related to the browser. Is it sending "range" requests? Which browser vendor and version are you using? Can you get a screenshot of the browser's webconsole to show us what requests are made (along with the request and response headers)?

**Comment by sciack** [comment]
Hi, I tried with Firefox and Chrome on MacOs (same laptop I run the executable), right now I don't have my work laptop with me, will try it tomorrow.

**Comment by sciack** [comment]
Attached screenshot from Firefox (with Version) and Chrome (version 79)
<img width="1920" alt="Screenshot 2020-01-24 at 10 09 15" src="https://user-images.githubusercontent.com/1496853/73039648-d43a6c00-3e91-11ea-9ac5-5be1113940e3.png">
<img width="1918" alt="Screenshot 2020-01-24 at 10 10 06" src="https://user-images.githubusercontent.com/1496853/73039651-d6042f80-3e91-11ea-88ec-1b4f698aac86.png">

**Comment by stuartwdouglas** [comment]
I don't see this, can you test with 1.3.0.Final?

**Comment by geoand** [comment]
Is this still an issue?

**Comment by sciack** [comment]
Sorry I was pulled in different things for  a lot and I missed the notification, will try and give you a feedback.
