### ISSUE TITLE
Failure parsing MediaType

### ISSUE THREAD

**Issue by lucapompei** [quarkusio/quarkus#6645]
I encountered the following error after receiving a large number of requests (>= 5000) to handle:

"org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: RESTEASY003340: Failure parsing MediaType string: application\json"

The bug can be reproduced by stressing the application via ApacheBenchmark.

**Comment by sberyozkin** [comment]
@lucapompei it should be `application/json` or is it just a typo in the description ?

**Comment by geoand** [comment]
cc @johnaohara

**Comment by lucapompei** [comment]
As result it should be `application/json`.

I used the `@Produces(MediaType.APPLICATION_JSON)` and `@Consumes(MediaType.APPLICATION_JSON)` class annotations, then "`@POST`" and `@Path(value = EndpointConstants.PRINT)` method annotations.

**Comment by gastaldi** [comment]
Can you paste the full stacktrace? Also, are you sure that `application\json` is not sent in the request?

**Comment by johnaohara** [comment]
@lucapompei Do you have something that reproduces this issue that we can run? Is "large number of requests (>=5000)" the total number of requests that the application starts to fail at, or is it when you start to drive load over 5000 req/sec? Do you see the same error if you use a cl tool like wrk2 or seige to drive load?

**Comment by gsmet** [comment]
@lucapompei so did you find the issue?
