### ISSUE TITLE
Document/Fix QuarkusUnitTest's public method requirement

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#6652]
Junit 5 doesn't require public test methods as in previous versions and some tools (e.g. IntelliJ) default them to being package private.

`QuarkusUnitTest` uses proxying to manage its test instance and the proxy requires public methods; without them the test methods are called on the proxy itself and not on the target. Noting this in the documentation would save some people quite a bit of hand wringing about why everything in the test appears `null`.

Alternatively, this restriction could be relaxed to match JUnit 5 (if that's possible).

**Comment by geoand** [comment]
Thanks for reporting @kdubb. 

I'm curious, why do you want to use `QuarkusUnitTest`? Is there something in the documentation that lead you to want to use it?

**Comment by kdubb** [comment]
I'm building extensions for `Mybatis` and `Hazelcast`. I was wracking my brain trying to figure out my testing failures until I noticed the proxying in the extension.

**Comment by geoand** [comment]
Thanks! I was just wanted to make sure you were indeed planning on creating an extension.

**Comment by pivovarit** [comment]
> I'm building extensions for `Mybatis` and `Hazelcast`. I was wracking my brain trying to figure out my testing failures until I noticed the proxying in the extension.

It's not really related to the issue, but we developed the Hazelcast extension already([code](https://github.com/pivovarit/quarkus-hazelcast-client-extension)). We're doing the last round of polishing now and the PR is about to go out in a few days

**Comment by kdubb** [comment]
@pivovarit Awesome!! I've been concentrating on Mybatis so this is really great news.  Thanks!

**Comment by stuartwdouglas** [comment]
This will be fixed by the class loader changes. JUnit 5.6 does not require a proxy any more, as it lets you directly intercept the test invocation.

**Comment by stuartwdouglas** [comment]
This should be fixed now.
