### ISSUE TITLE
quarkus-maven-plugin:999-SNAPSHOT:create generated project is not using quarkus 999-SNAPSHOT 

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6653]
`quarkus-maven-plugin:999-SNAPSHOT:create` generated project is not using quarkus 999-SNAPSHOT 

It's using 1.1.1.Final atm (latest released released Quarkus version?).
https://github.com/quarkusio/quarkus-platform/blob/master/pom.xml#L49

I think we should be able to "force" version 999-SNAPSHOT for Quarkus core extensions.

I use `quarkus-maven-plugin:999-SNAPSHOT:create` generated projects to quickly check if things are fixed in master, but with https://github.com/quarkusio/quarkus ++ https://github.com/quarkusio/quarkus-platform this gets complicated.

**Comment by gastaldi** [comment]
You need to also specify `-DplatformArtifactId=quarkus-bom` otherwise it will use the `quarkus-universe-bom` which is built separately

**Comment by rsvoboda** [comment]
Thanks, I found it also in https://quarkus.io/guides/maven-tooling
