### ISSUE TITLE
Support for empty Sort object

### ISSUE THREAD

**Issue by josejulio** [quarkusio/quarkus#6664]
**Description**

Support an empty Sort object to denote "no-sorting needed".

Currently it uses `null`, but I use the Sort object to validate the sorting passed is valid (i.e. that the app allows to sort by that column). 
I can of course validate if the sort is null before trying, but would be more conveniente to just pass an "empty sort".

I tried using Sort.by() to create an empty Sort, but this line https://github.com/quarkusio/quarkus/blob/master/extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/runtime/JpaOperations.java#L209 produces an incomplete "  SORT BY " that crashes the query (`unexpected token: null`)

**Implementation ideas**

I think that the only needed thing to do is validate [here](https://github.com/quarkusio/quarkus/blob/master/extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/runtime/JpaOperations.java#L209) that sort.getColumns().size() > 0 and should be fine as far I have seen.
If this is possible, i could send the PR.

**Comment by FroMage** [comment]
It's not clear to me that `Sort.by()` has any obvious semantics. It doesn't really confer "no sort" to me. WDYT @emmanuelbernard ?

**Comment by josejulio** [comment]
Perhaps then, there could be a `Sort.empty()` method, and `Sort.by()` could thrown and exception when no columns are provided. 
As today, `Sort.by()` does not fail when no columns are provided and if you try  to use it, the error given is not really obvious unless you print the HSQL (or PanacheSQL?).

**Comment by FroMage** [comment]
Oh, OK, I see. So yeah, we could make `Sort.by()` throw, but I'm not sure why you want `Sort.empty()` when you can pass `null` instead?

**Comment by josejulio** [comment]
> Oh, OK, I see. So yeah, we could make `Sort.by()` throw, but I'm not sure why you want `Sort.empty()` when you can pass `null` instead?

Thanks. is more than a nitpick i think, and will explain below my use case.

At the begining of my request, i run a process to extract some query params to build the Pager, as of now I have to use `null` if no param is specified.
But at a later point I filter the invalid columns and directly try to iterate the columns, and have to validate if is `null`.

The idea was that it could be easier to just go over the columns (with an empty Sort), but either way i'm fine i guess. 
Feel free to close it if you see no point in that.

**Comment by FroMage** [comment]
I think initially I thought that I saw no point in being picky about users writing `Sort.by()` and just go along with it, but forgot to support that later on when we generate the SQL. So I'm torn between being picky in `Sort.by()` or relaxed about it and allow it properly even though it doesn't scream "no sort" to me.

I guess even though there's not much use to supporting `Sort.by()` it doesn't hurt to not throw and consider it equivalent to `null` and validate it as you initially said by guarding against an empty array/list of columns. If you can make a PR I'll merge it.

Ultimately I think it's better to be forgiving than too strict, so you were right from the start.

**Comment by josejulio** [comment]
> If you can make a PR I'll merge it.

I'll do, thanks!

**Comment by emmanuelbernard** [comment]
Hey @josejulio 
Can you give a concrete example of code using the Sort.by the way you intend it. From what I glimse, you have unknown input and you want to treat no sort / no paging etc as seamlessly as possible in your code. And it seems handling `null` was breaking the flow. I'd love to see the code with the new approach to figure out how you write this "generic" query engine.

**Comment by josejulio** [comment]
Hello, yes, 

Here is how i'm currently using a method to extract the sort [1] out of the query params (along pagination) and a builder to create a Pager [2]. This `Pager` initialize the `Sort` with no arguments to simplify 
```java
if(this.sort == null) {
  this.sort = Sort.by(column, order);
} else {
  this.sort.and(column, order);
}
```
to
``` this.sort.ad(column, order);```

When building the `Pager` (see [2]) I just check if the sort has 0 elements and swap it for `null`

At a later point, I want to verify that every requested column (for the sort) is valid (in my model) [3], so I the sort is not `null` I iterate over all the columns and check.

Allowing empty `Sort` would remove some null checks on this "generic pagination".

[1] https://github.com/RedHatInsights/custom-policies-ui-backend/blob/master/src/main/java/com/redhat/cloud/custompolicies/app/rest/utils/PagingUtils.java#L72-L96
[2] https://github.com/RedHatInsights/custom-policies-ui-backend/blob/master/src/main/java/com/redhat/cloud/custompolicies/app/model/pager/Pager.java#L74-L80
[3] https://github.com/RedHatInsights/custom-policies-ui-backend/blob/master/src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java#L84-L88

**Comment by emmanuelbernard** [comment]
Thanks, that's indeed what I had conceptually in mind.
`Sort.empty()` as the default where you can then apply `sort.and` on it does the job.
