### ISSUE TITLE
KubernetesProcessor - BuildInfo - possible switch of constructor attributes

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6679]
Hi @iocanel / @geoand, I'm looking at https://github.com/quarkusio/quarkus/blob/master/extensions/kubernetes/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesProcessor.java#L236 and I think attributes on line 239 and 240 should be switched. 

```
                project.getBuildInfo().getOutputFile(),
                project.getBuildInfo().getClassOutputDir());
```

BuildInfo constructor has this signature: `public BuildInfo(String name, String version, String packaging, String buildTool, Path outputFile, Path classOutputDir, Path resourceDir) {`

When looking into BuildInfo sources I'm even more confused by code like this:
```
public void setResourceOutputDir(Path classOutputDir) {
    this.classOutputDir = classOutputDir;
  }
```

It's probably working atm because `classOutputDir`  and `resourceDir` are basically the same for maven.
https://github.com/dekorateio/dekorate/blob/master/core/src/main/java/io/dekorate/project/BuildInfo.java#L54-L55

**Comment by iocanel** [comment]
BuildInfo has two constructors. One that allows specifying different values for `classOutputDir` and `resourceDir` and one which assumes that both are the same. Currently, we use the later in quarkus.

So, yes your assumption that it works only when the two are equal is correct. We should change that.

**Comment by gsmet** [comment]
@iocanel do you still have this one on your radar? Maybe you should affect it to you?

**Comment by iocanel** [comment]
@gsmet: Thanks for the reminder. I had completely forgotten about it.
