### ISSUE TITLE
-H:+AddAllCharsets passed to native-image even though no extension requested it

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#6683]
-H:+AddAllCharsets passed to native-image even though neither any extension nor user config requests it.

Thanks @lburgazzoli for spotting the symptoms. 

Steps to reproduce: run any itest where `-H:+AddAllCharsets` is not expected in the native mode. quarkus-integration-test-jackson is a good example.

Expected: Either `AddAllCharsets` does not occur at all or `-H:-AddAllCharsets` occurs in the output.

Actual: `-H:+AddAllCharsets` occurs in the output

## Explanation

The implementation of `DeprecatedBuildItemProcessor.enableAllCharsets(List<NativeEnableAllCharsetsBuildItem>)` is broken:

```
    @BuildStep
    NativeImageEnableAllCharsetsBuildItem enableAllCharsets(List<NativeEnableAllCharsetsBuildItem> oldProps) {
        return new NativeImageEnableAllCharsetsBuildItem();
    }
```

It returns a NativeImageEnableAllCharsetsBuildItem regardless if there are any oldProps.

A PR follows

**Comment by ppalaga** [comment]
BTW with the fix, the size of the native image goes down from 34552872 to 28339240 bytes which is ~5.9MB

**Comment by sberyozkin** [comment]
FYI, this is optional in the Tika extension too
