### ISSUE TITLE
Quarkus additional build args cannot handle comma separated list

### ISSUE THREAD

**Issue by christianThor** [quarkusio/quarkus#6710]
**Describe the bug**
I get a malformed command when running the quarkus plugin with the following entry in `application.properties`:

`quarkus.native.additional-build-args=--initialize-at-run-time=javax.ws.rs.Path,javax.ws.rs.GET`

**Expected behavior**
The command should execute successfully. 

GraalVM supports comma separated list for the `--initialize-at-runtime` argument:

```--initialize-at-run-time=<comma separated list of class/package names> initializes classes and implicitly all of their superclasses at run time and not during image building``` 

https://www.graalvm.org/docs/reference-manual/native-image/

**Actual behavior**

The malformed command:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.2.1 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /Users/christian.thorenfeld/.sdkman/candidates/java/19.2.1-grl/jre/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --initialize-at-run-time=javax.ws.rs.Path javax.ws.rs.GET --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar rest-json-quickstart-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace rest-json-quickstart-1.0-SNAPSHOT-runner
Error: Unknown argument: rest-json-quickstart-1.0-SNAPSHOT-runner
```

**To Reproduce**

Bug demo here: https://github.com/christianThor/quarkus-bug-demo

1. run `./mvnw package -Pnative`

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.native.additional-build-args=--initialize-at-run-time=javax.ws.rs.Path,javax.ws.rs.GET
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Darwin admins-MacBook-Pro-15.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009173705.graal.jdk8u-src-tar-gz-b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
```
 - GraalVM version (if different from Java):
 - Quarkus version or git rev: 1.1.1.Final

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Thanks for reporting.

This isn't a but actually since `,` is used to denote that values are members of a collection of configuration values, in your case where the `,` needs to be passed down to GraalVM, you need to escape it like so:

```
quarkus.native.additional-build-args=--initialize-at-run-time=javax.ws.rs.Path\\,javax.ws.rs.GET
```

**Comment by gsmet** [comment]
We need a double antislash, not a single one? Should we document this in the writing native applications guide?

**Comment by geoand** [comment]
Yeah, we need to the double one (I tried it and then double checked :)).

Documenting this a good idea. I'll open a PR

**Comment by gsmet** [comment]
@dmlloyd just to check that it's normal we need double antislashes to escape commas? It seems a bit weird.

**Comment by geoand** [comment]
Here is the PR documenting this: https://github.com/quarkusio/quarkus/pull/6715

**Comment by dmlloyd** [comment]
You need the `\,` sequence because the value is a `List`.  Because the value is in a properties file which also uses `\`, you need to escape the original `\` with a second one.  On the command line it should be `-Dquarkus.native.additional-build-args=--initialize-at-run-time=javax.ws.rs.Path\,javax.ws.rs.GET` unless you're in a shell which interprets `\`, in which case you'd have to double it up again.

**Comment by christianThor** [comment]
glad this wasn't a bug! thanks for the help!
