### ISSUE TITLE
Multiple mongo connection(diferent server) with with panache mongo extenstion

### ISSUE THREAD

**Issue by himansh-23** [quarkusio/quarkus#6713]
**Please use StackOverflow for questions.**

This helps the community to be able to find answers to their similar issues more easily.

[Click this link to ask on StackOverflow with the "quarkus" tag](https://stackoverflow.com/questions/ask?tags=quarkus).

**Comment by geoand** [comment]
This will happen at some point. We first need #4529 then some changes in Mongo Panache
