### ISSUE TITLE
Tests fail with constructor injection

### ISSUE THREAD

**Issue by TheVidAllMayThe** [quarkusio/quarkus#6722]
When injecting individual fields with the @Inject annotation the tests run fine, but when using constructor injection the tests fail with:

```
io.biapower.OverrideServiceTest > testFindAll() FAILED
    org.junit.jupiter.api.extension.TestInstantiationException
        Caused by: java.lang.ExceptionInInitializerError
            Caused by: java.lang.RuntimeException
                Caused by: java.lang.RuntimeException
                    Caused by: java.lang.NoSuchMethodError
```

In order to reproduce this error I created a sample project with only a MongoPanacheEntity Pojo, a Repository and a Service. The Repository is injected in the service. The test class only has one test that uses the service to call a listAll() function on the Repository. 

application.propertires
```properties
quarkus.mongodb.database=test
```
 - GraalVM version: 19.2.1
 - Quarkus version: 1.1.1.Final 

The sample code to reproduce is here:
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/4097832/code-with-quarkus.zip)

At first I thought this was a kotlin related issue, since I first came across it in a kotlin project, but this sample project is in Java and reproduces the same problem.

I ran `./gradlew clean test`

**Comment by rsvoboda** [comment]
Something for you @mkouba ?

**Comment by mkouba** [comment]
@TheVidAllMayThe I'm sorry but I don't see a constructor injection in your sample? For me the `gradlew clean test` fails with `com.mongodb.MongoTimeoutException at SamplePojoTest.java:16`.

**Comment by TheVidAllMayThe** [comment]
I did a field injection on SamplePojoRepository in SamplePojoService.java, but if it's changed to a constructor injection it fails. Its failing because a mongo instance should be running in localhost:27017, but I will add a mongo testcontainer so you don't have to run it localy

**Comment by TheVidAllMayThe** [comment]
A mongo container should start now when you run  `./gradlew test`, so you won't get the mongo timeout. I've switched to constructor injection in SamplePojoService.java and the test fails with the exception I mentioned originally

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/4103600/code-with-quarkus.zip)

**Comment by mkouba** [comment]
Hm, so a no-args constructor should be generated for an application scoped bean class that does not extend any other class, see https://quarkus.io/guides/cdi-reference#simplified-constructor-injection for more information. Obviously it does not work  in Gradle, but it seems to work in Maven. Unfortunately, I'm no gradle expert. @gastaldi do you have an idea what's going on? 

A workaround (that is actually a requirement in "regular" CDI environments) is to add a no-args constructor manually.

**Comment by TheVidAllMayThe** [comment]
@mkouba Thank you, I can confirm that the workaround works! It also works with kotlin

**Comment by andreas-eberle** [comment]
I also experience this and it is quite a pain. Is there some way I could help debugging this issue?

**Comment by andreas-eberle** [comment]
Is there any way to help debugging on this? It is a real pain not to be able to use constructor injection normally.

**Comment by stuartwdouglas** [comment]
I just ran the reproducer with a recent version and it seems to work now (it still failed because I did not have mongo running, but the initial problem seems to be fixed).
