### ISSUE TITLE
I can not update to 1.2.0.CR1 in a maven project

### ISSUE THREAD

**Issue by svilenvul** [quarkusio/quarkus#6724]
**Describe the bug**

I am trying to update a project from 1.1.1.Final to 1.2.0.CR1

**Expected behavior**
Dependencies are found in Maven central.

**Actual behavior**
https://mvnrepository.com/artifact/io.quarkus/quarkus-universe-bom is not available with version 1.2.0.CR1.

**Comment by gsmet** [comment]
This is expected. We only publish the quarkus-bom for Candidate Releases, not the quarkus-universe-bom.

See the announcement here for all the details: https://groups.google.com/forum/#!topic/quarkus-dev/2jFpwMt4QaI .

**Comment by svilenvul** [comment]
@gsmet, thank you!
