### ISSUE TITLE
Improve reporting in case JSON cannot be handled due to missing JSONB

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#6738]
I have a JAX-RS method like this:

```
@POST
@Consumes(MediaType.APPLICATION_JSON)
public Response newMeasurement(Measurement measurement) {
    return Response.ok().build();
}
```

`Measurement` should be unmarshalled from the incoming JSON payload. I had forgotten to add the `quarkus-resteasy-jsonb` dependency, though.

This resulted in the following, IMO rather confusing response:

```
HTTP/1.1 415 Unsupported Media Type
Content-Length: 0
```

I'd expect a more meaningful error, perhaps even exception and HTTP status 500 stating, that the request cannot be handled due to lacking unmarshalling capabilities.

**Comment by geoand** [comment]
cc @asoldano

**Comment by asoldano** [comment]
The response is perfectly fine from a pure RESTEasy PoV. Perhaps Quarkus can try being smart here and note the user is willing to use json but none of the component meant to be used for that are in place.

**Comment by fmhwong** [comment]
@gunnarmorling I tested this with the latest Quarkus with rest-json-quickstart.  If I commented out `quarkus-resteasy-jsonb`, I will got this warning during startup.

```
2020-02-03 14:09:15,737 WARN  [io.qua.res.com.dep.ResteasyCommonProcessor] (build-20) Quarkus detected the need of REST JSON support but you have not provided the necessary JSON extension for this. You can visit https://quarkus.io/guides/rest-json for more information on how to set one.
```

**Comment by gsmet** [comment]
@fmhwong thanks for checking. I think a warning is enough.

Can you add the handling of `SSE_ELEMENT_TYPE`? Once done, I think we can close this one.
