### ISSUE TITLE
Tika extension doesn't like the new class loading

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#6746]
@machi1990 stumbled upon an issue while working on improving a test: `java.lang.ClassCastException: io.quarkus.tika.runtime.TikaParserParameter cannot be cast to io.quarkus.tika.runtime.TikaParserParameter`.

The gist of it is that there is a class loader issue in `TikaProcessor`.

I think the issue is that ``TikaParserParameter``s are created during the deployment and pushed to `TikaParsersConfigBuildItem`.

```java
        Map<String, List<TikaParserParameter>> parsersConfig = getSupportedParserConfig(config.tikaConfigPath, config.parsers,
                config.parserOptions, config.parser);
        recorder.initTikaParser(beanContainer.getValue(), config, parsersConfig);
        return new TikaParsersConfigBuildItem(parsersConfig);
```

The config should be passed to the recorder and the TikaParserParameters created there, not at build time.

This should be integrated in the other BuildStep and use the config too:
```java
    @BuildStep
    public void registerTikaProviders(BuildProducer<ServiceProviderBuildItem> serviceProvider,
            TikaParsersConfigBuildItem parserConfigItem) throws Exception {
        serviceProvider.produce(
                new ServiceProviderBuildItem(Parser.class.getName(),
                        new ArrayList<>(parserConfigItem.getConfiguration().keySet())));
        serviceProvider.produce(
                new ServiceProviderBuildItem(Detector.class.getName(), getProviderNames(Detector.class.getName())));
        serviceProvider.produce(
                new ServiceProviderBuildItem(EncodingDetector.class.getName(),
                        getProviderNames(EncodingDetector.class.getName())));
    }
```
so that we can get rid of this `BuildItem`.

**Comment by sberyozkin** [comment]
Hi @gsmet @machi1990 thanks a mill for identifying the problem, will look at the PR and learn :-)
