### ISSUE TITLE
OIDC confidential clients can not authenticate with form params with Vertx 3.8.5

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#6747]
**Describe the bug**
A quarkus user works with the OIDC server which only accepts the form based authentication info during the token acquisition request. 

**Expected behavior**
Setting `Oauth2ClientOptions.useBasicAuthorizationHeader` to `false` should result in the client id and secret posted as the form parameters,

**Actual behavior**
`Oauth2ClientOptions.isUseBasicAuthorizationHeader` is ignored starting from Vertx `3.8.5`

**Additional context**

https://github.com/vert-x3/vertx-auth/issues/357

**Comment by sberyozkin** [comment]
Note I don't really know if it is a regression for Quarkus or not. Before Vertx 3.8.5, the client authentication details were duplicated with `BasicAuth` and form params. It worked for all but some stricter OIDC servers (Microsoft ADFS, Okta) but I don't know if others for which it worked were depending on the basic auth or form params.

**Comment by cescoffier** [comment]
@pmlopes @vietj any idea?

**Comment by pmlopes** [comment]
The "old" behavior was a bug. The RFC states that servers should either accept the header or the form params. While the header is a required for all implementations, form is optional. The code was fixed to deprecate the flag and rely on the header when needed (client id + client secret) is provided.

This way we are spec compliant and work with the strict idp's such as "okta" and "adfs", yet the other providers still work as before.

**Comment by pmlopes** [comment]
some extra info, the flag is now deprecated and ignored because the correct behavior is down extracted from the config. Meaning, if client id + client secret are provided then the header is used, otherwise the form version is used. So the flag is useless.

**Comment by sberyozkin** [comment]
@pmlopes Hi Paulo, thanks for the feedback, 
But the confidential client should retain the option to authenticate using the form params. 
True, we are tallkng here about the OIDC server implementations which are not meeting the spec requirement to support the basic auth format, but nonetheless, such servers can not be contacted now as per [this user thread](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/OpenId.20Question) (I can imagine there are might be a few in-house built or otherwise legacy or incomplete servers that can only accept the form params).

**Comment by emmanuelBayle** [comment]
Hi @pmlopes, @sberyozkin, I'm the user with this special case for the authentication.
After check, it's now possible on our side to support the Basic Auth for obtain the token, so it's no more a problem on my side.
@sberyozkin, as explain in zulip, I must pass an extra parameter during the code call (acr_value=XXXXXX), so if it's possible to support this like in Vertx (setExtraParameters(JsonObject)) it should be perfect.
Anyway, thank you for your vairious feedback on my problem! :)

**Comment by sberyozkin** [comment]
@emmanuelBayle thanks, good news. FYI, #6924 adds the extra parameters (I have to test that though :-) ). 
@pmlopes Hi Paulo, so it is a low priority issue then :-). I agree the basic authorization property is a bit misleading as it does not make sense for a public client. Perhaps it would make sense to add a  property letting select the confidential client auth type...
thanks

**Comment by sberyozkin** [comment]
I'm going to look at the workaround in Quarkus itself
