### ISSUE TITLE
Resteasy standalone directory redirect missing

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#6760]
**Describe the bug**
I do not get redirected from "localhost:8080/sub" to "localhost:8080/sub/" when I use resteasy standalone.
The sub folder is a static directory inside my "META-INF/resources/" directory.

**Expected behavior**
When I used quarkus-undertow, I did get redirected automaticly to "sub/". This allowed my css to get applied.

**Actual behavior**
With resteasy standalone, I do not get redirected anymore to "sub/". My css does not get applied.

**To Reproduce**
Download the reproducer project: 
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/4107627/code-with-quarkus.zip)

1. Start the reproducer project in dev mode
2. Go to "http://localhost:8080/sub". The text is in black font.
3. Now, add undertow to the pom
4. Go to "http://localhost:8080/sub". The text is now in the intended red font. You got redirected to "sub/"

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
MSYS_NT-10.0 SOMEHOST 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys
 - Output of `java -version`: 
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
 - Quarkus version or git rev: 
1.2.0.FINAL

**Additional context**
See reproducer project in the reproduction steps.

**Comment by Postremus** [comment]
This is somewhat related to https://github.com/quarkusio/quarkus/issues/3091.
In that bug, we also did not detect sub folders correctly.

https://github.com/quarkusio/quarkus/blob/6df5c5a0b4cb204f2669258581000c5d6b9dcb18/extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyStandaloneBuildStep.java#L127-L129

In this, and other similar lines, we check if an file  is the default welcome page (index.html), and then add the files directory.
But we do not respect if the welcome page is in a sub directory.
In that case, the value of the "file" string would be sub/index.html.

This seems kinda wrong. With undertow, I do get redirected to sub/, and therefore to the index.html.
@gsmet Was this an intended behaviour, that only the welcome page on top level is used?

**Comment by Postremus** [comment]
Closing this. Is fixed already in 1.10.3.Final, presumably by the linked vertx issue,

**Comment by gsmet** [comment]
@Postremus thanks for the follow-up!
