### ISSUE TITLE
QuarkusFaultToleranceOperationProvider should cache the FaultToleranceOperation

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#6761]
**Description**
`QuarkusFaultToleranceOperationProvider` re-creates a new `FaultToleranceOperation` object for each request. 

CPU profiling shows that creating such object can uses a significant amount of CPU, see here for details: https://groups.google.com/d/msg/quarkus-dev/2jFpwMt4QaI/edUfNagDCgAJ

Smallrye-fault-tolerance provides a CDI extension that caches the `FaultToleranceOperation` but Quarkus didn't use it (CDI portable extensions are not supported in Quarkus ) so we need to create something dedicated to Quarkus.

**Implementation ideas**
Fault tolerance extension can be found here: https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/DefaultFaultToleranceOperationProvider.java#L43-L56

A prototype implementation that needs to be reworked can be found here:  https://github.com/quarkusio/quarkus/compare/master...loicmathieu:fix/ft-perf-issue

**Comment by loicmathieu** [comment]
@Ladicek just see that inside `io.quarkus.smallrye.faulttolerance.runtime.SmallryeFaultToleranceRecorder` we build a `FaultToleranceOperation` for each possible bean methods (sound not very performant) and validate it if it is legitimate : https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/SmallryeFaultToleranceRecorder.java#L33

Maybe we can hook into this process and store this newly created `FaultToleranceOperation` inside a cache from the recorder. This should be easy to do.

We can always fallback to re-create it at runtime (with a WARN message) if needed.

WDYT ?

**Comment by Ladicek** [comment]
@loicmathieu I don't really understand, but what you say sounds legitimate :-) CC @michalszynkiewicz @mkouba

**Comment by mkouba** [comment]
1. Yes, I think that we should make `QuarkusFaultToleranceOperationProvider` a `@Singleton` and place the cache there and fill the cache from `io.quarkus.smallrye.faulttolerance.runtime.SmallryeFaultToleranceRecorder.validate()`.
2. However, this wouldn't help in case of Rest Client interfaces - those are not beans. And so we would have to modify `SmallRyeFaultToleranceProcessor.validateFaultToleranceAnnotations()` to also include methods from Rest Client interfaces.

**Comment by michalszynkiewicz** [comment]
Please remember to change method names from `validate` to sth else in such case :)

**Comment by michalszynkiewicz** [comment]
otherwise it sounds good to me

**Comment by loicmathieu** [comment]
@mkouba I have a working prototype, still needs to check for the restclient operations, I can still create them lazily (like in my first implementation) and add them to the cache later.

I just discover that `validate` load all classes and methods via reflection to check the presence of the annotation. 
Inside the main integration test it tooks 300ms! I work on a prototype to use Jandex at build time for doing this. Early test shows that I can save up to 290ms of startup time (the validate took 7ms instead of 300ms when restricting the number of classes to anaylize during validate thanks to Jandex). And Jandex analyse interfaces so it should covers the RestClient usage !

I'll send a PR today or Monday, stay tune :)

**Comment by mkouba** [comment]
I don't think you can move the validation to the build phase because there is a comment that MP Config must be used to read some properties at runtime: https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java#L188

> Inside the main integration test it tooks 300ms!

That's because we validate all beans. It should be possible to filter the beans here: https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java#L193 and only validate those for which `BeanInfo.hasAroundInvokeInterceptors()==true` and `io.quarkus.arc.processor.BeanInfo.getTarget()` class or any subclass has a method annotated with a FT annotation (such as `@CircuitBreaker`).

**Comment by loicmathieu** [comment]
> I don't think you can move the validation to the build phase because there is a comment that MP Config must be used to read some properties at runtime:

It's still at runtime, I didn't move the validation phase I only limit it to the needed classes instead of scanning all bean classes.

> only validate those for which BeanInfo.hasAroundInvokeInterceptors()==true and io.quarkus.arc.processor.BeanInfo.getTarget() class or any subclass has a method annotated with a FT annotation (such as @CircuitBreaker).

I limit the classes to scan to those who are annotated at class or method level with one of the FT annotations, but I didn''t add a check to `BeanInfo.hasAroundInvokeInterceptors()==true`. Is it realy needeed ? What's it purpose ?

**Comment by loicmathieu** [comment]
@mkouba it should be easier to comment on the draft PR to see what I propose :)

**Comment by mkouba** [comment]
So in theory a FT annotation could be declared on a class that is not a bean but (1) a false positive shouldn't be a problem, (2) your approach should handle the rest client interfaces as well. I'll add some comment to your PR. It looks good BTW ;-)
