### ISSUE TITLE
Hibernate-orm depends on caffeine but hibernate-orm-deployment does not depend on caffeine-deployment

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#6767]
Hibernate-orm depends on caffeine but hibernate-orm-deployment does not depend on caffeine-deployment

**Comment by gsmet** [comment]
@michalszynkiewicz do you plan to fix it or should I?

**Comment by michalszynkiewicz** [comment]
I'll fix it, asked first on zulip if that's a real issue ;) I'll have a PR in a few minutes

**Comment by gsmet** [comment]
Cool, thanks!

**Comment by Sanne** [comment]
Is it a problem? We infer the deployment artifacts from the runtime artifacts

**Comment by michalszynkiewicz** [comment]
It is for the things I do now ;) 
I can work around it, but I have been told it's a good practice to reflect the runtime dependencies in deployment dependencies. That's why I created this PR

**Comment by Sanne** [comment]
Ok sure I don't disagree on fixing it. I was just curious to know if it was "showing" as an error
