### ISSUE TITLE
OpenApi doesn't load request/response schema on endpoints when producing/consuming objects from external library

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#6780]
**Describe the bug**
OpenApi doesn't load request/response schema on endpoints when producing/consuming objects from external library. In the generated yml, simply ignores that there is a body accepted/ returned.

Note that I am using Gradle to setup my build.

```
@Path("/user/registration")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class UserRegistration {

    @POST
    public UserRegistrationResponse registerUser(UserRegistrationRequest request) {
        return new UserRegistrationResponse(request.getUsername(), request.getEmail(), "new id");
    }
}
```

In this example of my code, the schemas of both `UserRegistrationRequest` and `UserregistrationResponse` were ignored when placed in an external library (actually a sister sub project in Gradle). When I moved these objects into the server project, the issue was resolved and the schemas show up in swagger as expected.

Proper (expected?) schema excerpt when pojos are in the same project:

```
  /user/registration:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegistrationResponse'
components:
  schemas:
    UserRegistrationRequest:
      type: object
      properties:
        email:
          type: string
        plainPassword:
          type: string
        username:
          type: string
    UserRegistrationResponse:
      type: object
      properties:
        email:
          type: string
        id:
          type: string
        username:
          type: string

```

Schema when placed in external project/ library:

```
  /user/registration:
    post:
      requestBody: {}
      responses:
        "200":
          description: OK
```

It should be noted that when using the external pojos, I can't return a straight pojo, it must be wrapped in a `Response` for the server to start.

Using `1.2.0.Final`, with the `quarkus-resteasy-jackson` plugin.

**Comment by gsmet** [comment]
There's a good chance you need them to be indexed by Jandex.

See https://stackoverflow.com/a/55513723/5043585 .

**Comment by GregJohnStewart** [comment]
Happen to know how to accomplish the indexing with Gradle? I have researched this issue fairly heavily in the past but haven't been able to find a solution.

**Comment by stuartwdouglas** [comment]
If you include a META-INF/beans.xml file it should be automatically indexed.

**Comment by GregJohnStewart** [comment]
I believe this issue has been resolved. Thanks for all the hard work!
