### ISSUE TITLE
quarkus orchestration

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#6796]
**Describe the extension**
Something like a "quarkus-orchestration-extension" (maybe with the help of jgroups) could make a bi-directional communication through TCP (with AMQP) or HTTP (with JAX-RS) in combination with MP Fault Tolerance/Health to provide high availability/failover: if one quarkus node fails, another quarkus node can be used as a replacement. It would also allow the controlling of different quarkus nodes through one interface.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Comment by gastaldi** [comment]
Isn't that already what Kubernetes offers? Why reinvent the wheel?

**Comment by nimo23** [comment]
>Why reinvent the wheel?

Yes, I think we can close this issue if kubernetes provides this out of box.

**Comment by gastaldi** [comment]
Thanks @nimo23. Closing this as I believe it's a much better solution :wink:
