### ISSUE TITLE
KUBERNETES_GROUP=wonka mvn package not taking effect if kubernetes.group set in application.properties

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#6799]
while testing #5496  I noticed that `KUBERNETES_GROUP=wonka mvn package` doesn't win over `kubernetes.group=mything` in `application.properties`.

it should according to https://quarkus.io/guides/config#overriding-properties-at-runtime

**Comment by iocanel** [comment]
Just verified that myself. I will have a closer look.

**Comment by iocanel** [comment]
@maxandersen: I can no longer reproduce it on master. Can you please verify?

**Comment by iocanel** [comment]
Also, added an integration test for that. The test overrides the value found in application.properties via system.properties (due to maven invoker plugin limitations). And it seems to work fine.

**Comment by iocanel** [comment]
@maxandersen: I think that we can close this now. Any objections?

**Comment by geoand** [comment]
I assume we can close this?

**Comment by geoand** [comment]
This has since been fixed, so I am closing
