### ISSUE TITLE
Jberet is missing in Quarkus bootstrap list

### ISSUE THREAD

**Issue by Rahamathulla** [quarkusio/quarkus#6804]
**Description**
Jberet is missing in Quarkus bootstrap list. are they plans to add it here? is there any alternative given ?

**Comment by jmartisk** [comment]
There is a feature request for it here: https://github.com/quarkusio/quarkus/issues/1505
I'm kinda working on it in my free time, haven't had too much progress yet though.

**Comment by gastaldi** [comment]
Duplicate of #1505, please vote it in there if you're interested in it. Thanks!
