### ISSUE TITLE
Support ignoring an existing persistence.xml file

### ISSUE THREAD

**Issue by tisoft** [quarkusio/quarkus#6805]
**Description**
It should be possible to skip an existing persistence.xml file, that is contained in a JAR file dependency.

My use case for this is, that I need to import a legacy jar, that unfortunately contains a persistence.xml with unsupported entries. Fortunately I only need the classes from this jar, not the persistence configuration, so ignoring it would help me.

**Implementation ideas**
I see the following possibilities for this:
* add an option to ignore all persistence.xml files, not in the currently build jar.
* add an option to ignore all persistence.xml files contained in specific jars
* add an option to ignore specific persistence units by name
  * The persistence XML files would need to be parsed, and if the unit name matches would be ignored

**Comment by mkueng1** [comment]
Perhaps it helps when it comes to priorization: it's not "just" a legacy topic - I have to use a library with JPA based logic which is also used in an EE application.
