### ISSUE TITLE
Validate compatibility of quarkus.platform.version and quarkus-plugin.version properties

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#6809]
**Description**
It's not uncommon for users who update projects to only update one of the 2 properties. It would be nice to fail the build / dev-run if there is a mismatch (probably of minor versions).

See for example: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkus.201.2E1.2E1.20and.20startup.20time/near/186691685

or https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/native.20image.3A.20Class.20initialization.20of.20ApplicationImpl.20failed

**Comment by geoand** [comment]
cc @maxandersen @aloubyansky

**Comment by maxandersen** [comment]
We can add a warn but it’s a sign of a bigger issue if we need to do it.

we seem to break the expected backwards compatibility of the scaffolding logic that is in the core. You should be perfectly fine using an older or even newer plugin with a platform.

But we now know that is just not happening and its not surprising to me and why I think we either need to remove the tooling/scaffolding from the core completely or find a way to fail our builds so its very clear when we break what should be compatible.

should we add a project to core that has a fixed quarkus core version and then run these commands that can fail ?

Another problem is that it seems some of these users are seeing issues because of native image plugin changes - would it make sense we move those back into core as those are definitely way more tied to specific versions of graal ?

**Comment by geoand** [comment]
> 
> we seem to break the expected backwards compatibility of the scaffolding logic that is in the core. You should be perfectly fine using an older or even newer plugin with a platform.

I don't think that is the case. Have we ever said that you can use `1.2.0.Final` of the platform with `1.1.0.Final` of the plugin? 
Of course it should perfectly OK to use `1.1.0.Final` of the platform with `1.1.1.Final` of the plugin but I don't think we've ever stated the backward compatibility at this level is needed for minor versions.
@gsmet am I wrong?

**Comment by geoand** [comment]
> 
> Another problem is that it seems some of these users are seeing issues because of native image plugin changes - would it make sense we move those back into core as those are definitely way more tied to specific versions of graal ?

I haven't myself seen any issues specific with the native image functionality. Basically the native image goal is pretty much deprecated and hasn't been included in the projects the tooling generates for a while

**Comment by maxandersen** [comment]
> I don't think that is the case. Have we ever said that you can use `1.2.0.Final` of the platform with `1.1.0.Final` of the plugin?

that was the goal and part of the reason why we extracted the tooling so there would be a consistent API and platform, tools and core wasn't tied together at the hip.

**Comment by maxandersen** [comment]
> I haven't myself seen any issues specific with the native image functionality. Basically the native image goal is pretty much deprecated and hasn't been included in the projects the tooling generates for a while

What is https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/native.20image.3A.20Class.20initialization.20of.20ApplicationImpl.20failed about if not about native image generation failing due to differences between 1.1 and 1.2 ?

**Comment by geoand** [comment]
> 
> What is https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/native.20image.3A.20Class.20initialization.20of.20ApplicationImpl.20failed about if not about native image generation failing due to differences between 1.1 and 1.2 ?

The problem isn't limited to native-image, meaning that a problem shows up in JVM mode as well when using the mixed versions

**Comment by geoand** [comment]
> > I don't think that is the case. Have we ever said that you can use `1.2.0.Final` of the platform with `1.1.0.Final` of the plugin?
> 
> that was the goal and part of the reason why we extracted the tooling so there would be a consistent API and platform, tools and core wasn't tied together at the hip.

You would know a lot than me of course. So I'll leave it up to you to decide what's best :)
The issue is howeve that today we can't mix the versions - and people seem to be making the mistake of only upgrading one of the versions fairly often

**Comment by maxandersen** [comment]
> The issue is howeve that today we can't mix the versions - and people seem to be making the mistake of only upgrading one of the versions fairly often

yeah ;/ if only the bom could be applied to plugins....then we could default to keep them aligned ;/

**Comment by geoand** [comment]
> > The issue is howeve that today we can't mix the versions - and people seem to be making the mistake of only upgrading one of the versions fairly often
> 
> yeah ;/ if only the bom could be applied to plugins....then we could default to keep them aligned ;/

That's not the first time I've heard that :)

**Comment by geoand** [comment]
Closing this as it's now out of date with the release of `2.1`
