### ISSUE TITLE
OIDC and smallrye-jwt are unable to get groups from custom claims like "https://example.com/roles"

### ISSUE THREAD

**Issue by jean-merelis** [quarkusio/quarkus#6842]
**Describe the bug**
Auth0 only allows adding custom claims to accessToken with a namespaced format, such as "https://example.com/roles": ["user", "admin"]
As documented at  https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims#custom-claims 

Quarkus-oidc and smallrye-token fail to get the value of this custom claim.
As workaround I added these roles in the scope attribute.

**Expected behavior**
OIDC and smallrye-jwt are able to obtain groups from custom claim  such as "https://example.com/roles"

**Actual behavior**
OIDC and smallrye-jwt are unable to obtain the claims value and output the following log:
```
2020-01-28 21:01:59,623 WARN  [io.sma.jwt.aut.pri.DefaultJWTTokenParser] (vert.x-eventloop-thread-3) No claim exists at the path https://example.com/roles at segment https:
2020-01-28 21:01:59,623 WARN  [io.sma.jwt.aut.pri.DefaultJWTTokenParser] (vert.x-eventloop-thread-3) Claim value at the path https://example.com/roles is neither an array of strings nor string
```

**Configuration**
```properties
smallrye.jwt.path.groups=https://example.com/roles

```
**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux jom-mnt19 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`:  openjdk version "1.8.0_232" - OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.1.1

**Comment by sberyozkin** [comment]
@jean-merelis thanks, a `smallrye-jwt` [issue](https://github.com/smallrye/smallrye-jwt/issues/164) already exists so the fix will be in the next `smallrye-jwt` release, and I'll get the `quarkus-oidc` updated too
