### ISSUE TITLE
No instances of sun.security.provider.NativePRNG are allowed in the image heap

### ISSUE THREAD

**Issue by fcracker79** [quarkusio/quarkus#6847]
**Describe the bug**
I am implementing a Quarkus Native AWS Lambda.
I need to import an HTTP client in the project (I tried OKHTTP and Apache HTTP Client with the same outcome).
When compiling, I receive the error: `No instances of sun.security.provider.NativePRNG are allowed in the image heap`.
The same problem does not occur if I remove the dependency and usage of the HTTP client.
I tried using the option `--initialize-at-run-time`, as suggested in the online documentation, with the following classes:

1. io.mirko.alexa.home.raspberry.impl.DynamoDBDeviceRepository_ClientProxy
2. io.mirko.alexa.home.raspberry.impl.DynamoDBDeviceRepository
3. org.apache.http.impl.client
4. java.security.SecureRandom
5. org.apache.http.impl.client.InternalHttpClient
6. sun.security.provider.NativePRNG

No success though.

**Expected behavior**
I would expect a successful compilation.

**Actual behavior**
The compilation fails with the following:

```
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Detailed message:
Trace:  object java.security.SecureRandom
    object sun.security.ssl.SSLContextImpl$TLSContext
    object sun.security.ssl.SSLSocketFactoryImpl
    object org.apache.http.conn.ssl.SSLConnectionSocketFactory
    object java.util.concurrent.ConcurrentHashMap$Node
    object java.util.concurrent.ConcurrentHashMap$Node[]
    object java.util.concurrent.ConcurrentHashMap
    object org.apache.http.config.Registry
    object org.apache.http.impl.conn.DefaultHttpClientConnectionOperator
    object org.apache.http.impl.conn.PoolingHttpClientConnectionManager
    object org.apache.http.impl.client.HttpClientBuilder$2
    object java.lang.Object[]
    object java.util.ArrayList
    object org.apache.http.impl.client.InternalHttpClient
    method io.mirko.alexa.home.raspberry.impl.DynamoDBDeviceRepository.getAWSId(String)
```

**To Reproduce**
1. Create an AWS Lambda Quarkus project using Maven archetype
2. Include `org.apache.httpcomponents.httpclient.4.5.10` in your dependencies
3. Use the above library in your project
4. Run `mvn clean install -Pnative -Dnative-image.docker-build=true -Dquarkus.native.enable-jni=true`

**Environment (please complete the following information):**
Linux mypc-ThinkPad-T410 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)

Quarkus 1.1.0.Final

**Comment by gsmet** [comment]
Why don't you use our REST client extension? See https://quarkus.io/guides/rest-client .

Because if you don't you will need to do the work we already did there and add the necessary GraalVM tweaks to get the Apache HTTP client working in native mode.

**Comment by fcracker79** [comment]
Thanks for the answer, 

yes I am proceeding with that direction, as I am in control of my codebase.

In case of libraries that rely on Apache HTTP Client, though (e.g. an OAuth2 library), it would be impossible do use the REST client extension.
Since that may be a common case, I supposed there was something I could do to make it work.

Could you please provide some reference on what I should do in case I am forced to make Apache HTTP Client work ?

Thanks again.

**Comment by Sanne** [comment]
Hi @fcracker79 ; sounds like essentially you'd want to contribute an extension for the Apache HTTP Client.

The error "no instances of X are allowed in the image heap" means that there's literally an instance of type X in the heap during the native-image compilation process.  Usually the "detail message" following it should give you a good hint of which references are holding it, but when it's not clear still you coud take an heap dump, and follow the references to find it. The compilation process happens in a normal JVM, so any JVM debugging tool is available.

You'll need to figure out why this instance was created, and what could be done to prevent it. Typically this could have happened via some other static initializer, or some explicit code which is being run; for example, do your really intend to execute `DynamoDBDeviceRepository.getAWSId(String)` during the compilation phase? It looks suspicious.

**Comment by fcracker79** [comment]
@Sanne thanks for the tips. I am quite a newbie with Quarkus and GraalVM, but I will try on that.

Since my issue is solved, I close the issue.

Thanks all for the support.

**Comment by sirAlexanderT** [comment]
@fcracker79 out of interest, how did you solve your issue?

**Comment by fcracker79** [comment]
@sirAlexanderT I have used the Quarkus client. 
Recently I have had to implement a Graphql client and using that Quarkus REST client was not that comfortable. Here it is how I have implemented the Graphql client 
https://github.com/fcracker79/alexa-home-skill/blob/master/skill/src/main/java/io/mirko/impl/repository/GraphqlClient.java
