### ISSUE TITLE
Data caching - use the FQCN of the bean class as the default cache name

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#6848]
I know there was a long discussion about this topic in https://github.com/quarkusio/quarkus/issues/3306. However, I believe that the current API is not very user-friendly. In my opinion, it makes sense to use the FQCN of the bean class as the default cache name for all annotations.

1. It probably makes a lot of sense to use one cache per component by default. In our case, we're annotating business methods of a CDI bean and so it's natural to expect that all those methods share the same cache. 
2. Developers don't like writing (ie. are lazy and that's fine) and this could lead to mistakes caused by short non-unique names like `@CacheResult(cacheName = "cache")`.

**Comment by gwenneg** [comment]
If we agree on doing this, I already have the code ready on a branch since it was part of the original version of the extension during the development phase.

**Comment by mkouba** [comment]
@emmanuelbernard @Sanne @galderz and your opinion gentlemen?

**Comment by Sanne** [comment]
@mkouba no please don't do this yet, we discussed this extensively during the design. Please check the previous discussions?

We intentionally would prefer to have some "bake time" while requiring the cache name: the strategy to choose a name correctly is controversial, and it's much easier to evolve the API by making a requirement attribute no longer required, than changing the defaults.

**Comment by mkouba** [comment]
I did check the previous discussions and I did not find a reasonable argument not to do this (of course  from my POV).

> We intentionally would prefer to have some "bake time" while requiring the cache name...

I understand this point. What I don't understand is why to close this issue now? It's still IMHO a valid feature request.

**Comment by Sanne** [comment]
> What I don't understand is why to close this issue now? It's still IMHO a valid feature request.

The reason is I see often PR's being merged too quickly so I prefer issues to be closed when there's no consensus yet.

Primarily there is no consensus on the FQCN being the right name. We need to discuss that first; if you want to re-purpose this issue feel free to change its title and reopen; IMO a new "clean" issue would be better.

**Comment by Sanne** [comment]
> ... so I prefer issues to be closed when there's no consensus yet.

To be more precise, in this specific case there was explicit consensus about not doing this yet, so it shouldn't be done.

**Comment by emmanuelbernard** [comment]
So far I am of the opinion that an explicit name simplifies a lot the user
experience vs being surprised by arbitrary default. It also makes the
choice explicit to the user so the decision to share or not is obvious.

To me default is not a feature we should have. Unless to many people
complain with arguments.

**Comment by mkouba** [comment]
> So far I am of the opinion that an explicit name simplifies a lot the user
experience...

@emmanuelbernard I personally like the "resonable defaults" approach and I'm quite sure we use it all over the quarkus codebase. In this particular case, those annotations are used to apply caching to the business methods of a CDI bean and hence my argument with "single cache per component by default".

> The reason is I see often PR's being merged too quickly...

@Sanne Well, this is not a PR and I didn't find a tracking issue for this topic. And the comments history in #3306 is soooo long and hard to get oriented.

> Primarily there is no consensus on the FQCN being the right name.

Fair enough.

**Comment by Sanne** [comment]
@mkouba we all like to default to "reasonable defaults" but there's an exception which is when an unexpected default might result in wrong data being returned "sneakily"

The problem in this case is that there might be a different expectation in how an explicit eviction request actually affects the right caches, nukes the right data. Failing to do so will lead into dangerous data inconsistencies.

The severity of this is compounded by the fact that we can't catch such errors: we can't "fail fast" on mistake, nor even log a warning - therefore making it an explicit choice is actually making such logic very clear, and it's a small price to pay in exchange for a more trustable framework.

It's also interesting to see that Spring Cache and JCache have taken different approaches on the definition of what should be the right default; that also compounded the issue by "training" the user's minds into different expectations than whatever our opinion could be of what is the right choice here.

**Comment by Sanne** [comment]
One more concern is that I suspect it's very unlikely for people to notice inconsistencies in caching eviction strategies during testing; such a mistake is likely only noticed at scale in a production environment or a reproduction of production load - even then, it's going to be hard to figure out the root cause.

If we stick to our plan I'm confident that while people might be wondering why the annoyance of the required parameter, but they'll never know how much pain they've avoided :)

Open to future improvemetns though. One idea could be that if we eventually introduce the Spring Cache API and/or the JCache API, each of those will have to conform to their respective defaults.

**Comment by mkouba** [comment]
I'm not an expert in this area so although I disagree I respect the consensus ;-).

> It's also interesting to see that Spring Cache and JCache...

That's a good point.
