### ISSUE TITLE
JAX-RS Resource with Kafka Topic injection - Message body writer not found

### ISSUE THREAD

**Issue by serranisimo** [quarkusio/quarkus#6849]
I built an applictaion based on the tutorial https://quarkus.io/guides/kafka. The problem takes place with the json binding. The application functions correctly when the type being returned by the resource is `Publisher<String>` or `Publisher<double>.` In case of a POJO, e.g. `Publisher<Fruit>,` the error occurs: "Failed to write event org.jboss.resteasy.plugins.providers.sse.OutboundSseEventImpl@51eb8c1b: javax.ws.rs.ServerErrorException: RESTEASY004082: No suitable message body writer for class : org.acme.quarkus.sample.fruit.Fruit" :

@Path("/fruits")
public class FruitPriceResource {

    Logger LOG = LoggerFactory.getLogger(FruitPriceResource.class);

    @Inject
    @Channel("fruit-out")
    Publisher<Fruit> fruits;

    @GET
    @Path("/stream")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @SseElementType(MediaType.APPLICATION_JSON)
    public Publisher<Fruit> stream() {
        return fruits;
    }
} 

The application is in this repository. Here you can find the working example with a Publisher as well as the one with the Fruit object (the one not working).
Repository: https://github.com/serranisimo/kafka-json

**Comment by geoand** [comment]
I am pretty sure that when you using SSE you have to return `Publisher<String>`. Am I right @FroMage ?

**Comment by serranisimo** [comment]
You might be right, but I just copied that from the tutorial so I assumed that should be possible. 
See: https://quarkus.io/guides/kafka#sending-json-server-sent-events-sse

**Comment by FroMage** [comment]
No, it should work, and I know exactly what this bug is caused by: we scan `@Produces` to register only the body writers that are used, and we don't scan `@SseElementType` while we should.

I get adding this (unused endpoint) will make your app work:

```java
@GET
@Path("/unused")
@Produces(MediaType.APPLICATION_JSON)
public Fruit unused() {
    return null;
}
```

It will also probably work if you add `@Produces(MediaType.APPLICATION_JSON)` to your endpoint class, because in both cases it will trigger registration of the json body writer.

We should totally fix this in the resteasy extension.

**Comment by serranisimo** [comment]
thank you very much for the quick response. I have been going crazy over this the last few days. I will try the fix out later.

ps.: I see I made a mistake in the description of my bug. I meant that it works with Publisher<double> and Publisher<String> but not with Publisher<fruit> . sorry for the confusion

**Comment by gsmet** [comment]
@ia3andy this would be a good starting point for you. The hard part will be to get a proper test case, then you need to tune the provider resolution.

**Comment by gsmet** [comment]
@FroMage 

> we scan @Produces to register only the body writers that are used, and we don't scan @SseElementType while we should

That's not true. It might be flawed but we have something for it: https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L334 .

We need to understand why it's not working properly in this case.

**Comment by FroMage** [comment]
Huh, then I'm wrong, but it's less obvious what the problem could be.

**Comment by serranisimo** [comment]
@FroMage , I tried both workarounds but unfortunately  the error persists

**Comment by FroMage** [comment]
OK, in that case I was all wrong. Next possible culprit is a loss of RESTEasy context. Can you try with a fixed stream of `Fruit` instead of making them come via the channel?

**Comment by serranisimo** [comment]
Do you mean something like this?
`@Path("/fruits")
public class FruitPriceResource {

    Logger LOG = LoggerFactory.getLogger(FruitPriceResource.class);

    @GET
    @Path("/stream")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @SseElementType(MediaType.APPLICATION_JSON)
    public Publisher<Fruit> stream() {
        ArrayList<Fruit> list = new ArrayList<Fruit>();
        IntStream.range(0, 100).forEach(
                nbr -> list.add(new Fruit("Fruit".concat(String.valueOf(nbr)), nbr))
        );
        return ReactiveStreams.fromIterable(list).buildRs();
    }
}`

Still not working

**Comment by FroMage** [comment]
Yes. Damnit, it's also not a loss of context then. I'm out of idea then.

**Comment by gsmet** [comment]
I asked @ia3andy to try to debug that one.

**Comment by gsmet** [comment]
I wonder if it's more a RESTEasy issue than a Quarkus one tbh. First thing might be to see if it can be reproduced with plain RESTEasy outside of Quarkus.

**Comment by serranisimo** [comment]
I found the problem
I added the dependency :
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jsonb</artifactId>
        </dependency>

And now it works.

I realized this by creating another project following this tutorial.

**Comment by serranisimo** [comment]
I found the problem:

I added the following dependency and it worked:
`
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jsonb</artifactId>
        </dependency>`

I realized this by starting a new project following this other tutorial: https://quarkus.io/guides/rest-json

**Comment by serranisimo** [comment]
The tutorial on quarkus and kafka uses this dependency: 
`

<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jsonb</artifactId>
</dependency>

`

**Comment by FroMage** [comment]
Hah, we never even thought of returning a plain `Fruit` object to test this. We need to fix the guide. 

Thanks for figuring it out!

**Comment by geoand** [comment]
@serranisimo thanks for checking!

Would you like to propose a doc fix since you were the one that did all the work figuring it out?

**Comment by serranisimo** [comment]
@geoand no problem, I will do it.  I am glad to help out. Thank you guys for reacting so quickly!

**Comment by geoand** [comment]
Excellent, thanks!

**Comment by gsmet** [comment]
OK so I'm still mentally sane, it was indeed implemented already :).
