### ISSUE TITLE
OIDC relative redirect-path property should not be tied in to the current relative request path 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#6853]
**Description**
`redirect-path` works only if it is confirmed to be part of the request URI, example, given `https://host:8080/admin/1` and a redirect path `/admin`, the code flow `redirect_uri` parameter will become `https://host:8080/admin`. It does not work if it is set to some sibling path like `callback` in which case `redirect_uri` should become `https://host:8080/callback`.

**Comment by stefanorg** [comment]
:+1:

**Comment by stefanorg** [comment]
i would like to point out that the documentation say that:
```
Relative path for calculating a "redirect_uri" parameter. It set it will be appended to the request URI’s host and port, otherwise the complete request URI will be used. It has to start from the forward slash, for example: "/service"
```
see: https://quarkus.io/guides/security-openid-connect-web-authentication#quarkus-oidc_quarkus.oidc.authentication.redirect-path

**Comment by sberyozkin** [comment]
@stefanorg
I'd like to clarify something about this property and also ask a question. So, this property has been introduced to support an OIDC admin configuring the clients with a `redirect_uri` property, for example, the actual Quarkus request may be `https://localhost:8080/a/b/c` but the `redirect_uri` parameter will always have to be `https://localhost:8080/` which can be achieved by setting this property to `/`. Next when the OIDC server redirects the user back to `https://localhost:8080/`, the Quarkus server will restore the original request URI which was `https://localhost:8080/a/b/c`.
It appears that in your case you don't need this restoration of the original request path, for example, if the users tried to get to https://localhost:8080/a/b/c, then, you'd still prefer the user landed at https://localhost:8080/callback after the authentication, is it correct ?

**Comment by stefanorg** [comment]
Hi thank you for your respone.

I'm implementing the Authorization Code Flow, i need to specify the `redirect_uri` with a value different from "/", i need to set a specific value like "/callback" or "/auth/login" or whatever.

I'm using as oauth/oidc server "ory/hydra" https://www.ory.sh/docs/hydra/

Hope this respond to your question.

**Comment by sberyozkin** [comment]
Hi @stefanorg , thanks, it does not have to be `/`, it can be `/a', for example, given `https://localhost:8080/a/b/c` request URI, the redirect URI could become `https://localhost:8080/a` and then when the user is returned to `https://localhost:8080/a` the original `https://localhost:8080/a/b/c` will be restored, but in your case, as far as I understand, you don't want the original request URI be restored. It really depends on the application requirements.

**Comment by sberyozkin** [comment]
@stefanorg FYI, #6924 introduces a new property `restore-path-after-redirect` (set to `true` by default because this is how it now works already on the master), alongside few other fixes. So you'd just set that property to `false`, thanks

**Comment by stefanorg** [comment]
I think that there is somenthing in the flow i don't understand.

Let's say my web app context root is: `my-app` reachable `http://localhost:8080/my-app/`.
I want all my app to be secured, so i put in configuration this:

```
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
```

I've registered my oidc client in my auth provider like this:

```
|    CLIENT ID     | NAME | RESPONSE TYPES |     SCOPE      |             REDIRECT URIS             |           GRANT TYPES            | TOKEN ENDPOINT AUTH METHOD |
|------------------|------|----------------|----------------|---------------------------------------|----------------------------------|----------------------------|
| auth-code-client |      | code,id_token  | openid offline | http://localhost:8080/my-app/callback | authorization_code,refresh_token | client_secret_basic        |
```

So i'm telling my auth provider, after successfull authentication, redirect the user in my redirect_uri (give me the code to proceed with the auth code flow)...

So from a client perspective:
1. The user land to my-app (http://localhost8080/my-app/) 
2. because the app is entirely secured (except for the `/my-app/callback` path), the oidc flow start, crafting an authorization code request to my auth provider, with the redirect uri set to `http://localhost:8080/my-app/callback` that is "permitted" so the auth code flow can procede.

With this configuration:

```
quarkus.http.root-path=/my-app

# Configuration file
quarkus.oidc.application-type=web-app
quarkus.oidc.auth-server-url=http://localhost:4444
quarkus.oidc.introspection-path=http://localhost:4445/oauth2/introspection
quarkus.oidc.client-id=auth-code-client
quarkus.oidc.credentials.secret=secret
quarkus.oidc.authentication.scopes=openid,offline
quarkus.oidc.token.issuer=http://localhost:4444
quarkus.oidc.authentication.redirect-path=/my-app/callback

quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.http.auth.permission.permit1.paths=/my-app/callback
quarkus.http.auth.permission.permit1.policy=permit
```

When i land to `http://localhost:8080/my-app/`, this is the redirect where i'm redirected to:

```
http://127.0.0.1:4444/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fmy-app%2F&state=114257e2-3585-4c75-a988-82643d726a87&scope=openid+openid+offline&response_type=code&client_id=auth-code-client
```

The `redirect_uri` is not what i wanted to be `http://localhost:8080/my-app/callback` but `http://localhost:8080/my-app/`, and clearly the auth provider give me the error:

```
 The "redirect_uri" parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.
```

I've created a github repository with the code to reproduce this flow: https://github.com/stefanorg/quarkus-ory-hydra-oidc-test

**Comment by sberyozkin** [comment]
@stefanorg thanks, it all makes sense, and this is exactly what is going to be fixed, PR is still pending, as I needed to improve the tests. I'll ping you once it is merged, or if you can find some time, please test against the PR branch....
thanks
