### ISSUE TITLE
[Testing] Testing for Quarkus-allopen kotlin compiler plugin

### ISSUE THREAD

**Issue by KaenDagger** [quarkusio/quarkus#6855]
- Locally install the compiler-plugin into local maven repository from here https://github.com/KaenDagger/quarkus-allopen

### Testing for Maven
- go to `integration-tests/kotlin/src/test/resources/projects/classic-kotlin/pom.xml`
- Inside `kotlin-maven-plugin` block change kotlin-allopen to quarkus-allopen like this
  From 
  ```
               <configuration>
                    <compilerPlugins>
                        <plugin>all-open</plugin>
                    </compilerPlugins>
                    <pluginOptions>
                        <!-- Each annotation is placed on its own line -->
                        <option>all-open:annotation=javax.enterprise.context.ApplicationScoped</option>
                        <option>all-open:annotation=javax.ws.rs.Path</option>
                    </pluginOptions>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
  ``` 
  To 
  ```
      <dependencies>
          <dependency>
            <groupId>io.quarkus.allopen</groupId>
            <artifactId>quarkus-maven-allopen</artifactId>
            <version>1.0</version>
          </dependency>
        </dependencies>
        <configuration>
          <javaParameters>true</javaParameters>
          <compilerPlugins>
            <plugin>quarkus-allopen</plugin>
          </compilerPlugins>
        </configuration>
  ```
- For custom annotaions. add your annotaions like this , in `configuration` block & under `compilerPlugins` block
  ```
     <pluginOptions>
             <!-- Each annotation is placed on its own line -->
             <option>quarkus-allopen:annotation=javax.enterprise.context.ApplicationScoped</option>
             <option>quarkus-allopen:annotation=javax.ws.rs.Path</option>
      </pluginOptions>
  ```
- Run the KotlinDevModeIT and other KotlinITs
- Check the results

### Testing for Gradle
- Create a quarkus project with kotlin & gradle build tools
- Create the files which are in Integretion-tests/Kotlin resources https://github.com/quarkusio/quarkus/tree/master/integration-tests/kotlin/src/test/resources/projects/classic-kotlin/src/main/kotlin/org/acme
- In `settings.gradle` add quarkus.allopen plugin like this and add `mavenLocal()` to repositories , so that plugin can be resolved
  ```
      repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
       }
       plugins {
        id 'io.quarkus' version "${quarkusPluginVersion}"
        id 'quarkus.allopen' version "1.0"
      }
  ```
- In `build.gradle` apply quarkus.allopen like this  & add `mavenLocal()` to repositories
  ```
     plugins {
       id 'org.jetbrains.kotlin.jvm' version "1.3.41"
       id 'io.quarkus'
       id 'quarkus.allopen'
     }

    repositories {
      mavenLocal()
      mavenCentral()
    }
  ```

- For custom annotations, you can add you annotations like this 
  ```
       quarkusAllOpen{
          annotations = ["javax.ws.rs.Path"]
       }
  ```

- run `./gradlew quarkusDev` task and see the application works 

Demo project for gradle is available here https://github.com/KaenDagger/allopen-kotlin-gradle-demo

#### Maven
- In Maven, **Hot Reloading is working** and passing the **KotlinDevModeIT** 
- Please make the following change `pluginId = "io.quarkus.allopen.quarkus-allopen"` here [KotlinCompilationProvider](https://github.com/quarkusio/quarkus/blob/befe68f11828ca29901b562f1bad9de9a9a88a84/extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinCompilationProvider.java#L57). Since now , we would be using quarkus plugin, pluginId must also be of quarkus
- Please pull the latest commit of master branch

#### Gradle 
- Hot Reloading is **not** working :(

**Comment by KaenDagger** [comment]
cc @geoand

**Comment by geoand** [comment]
Thanks @KaenDagger.

@ia3andy, @gastaldi would you like to take a look at what @KaenDagger has done?

I'll probably take a look as well the following days

**Comment by gastaldi** [comment]
The gradle plugin is missing the `io`. It should read `id 'io.quarkus.allopen'`

**Comment by KaenDagger** [comment]
We could change the name later. Its not necessary for working

**Comment by geoand** [comment]
Probably not needed for testing, but I think @gastaldi means that it will be needed when we release it to the gradle portal

**Comment by KaenDagger** [comment]
Sure, I would take care of it.

**Comment by KaenDagger** [comment]
update @geoand @gastaldi  @ia3andy

**Comment by geoand** [comment]
@KaenDagger Hot reload in Gradle doesn't work with current Quarkus either. Some work needs to be done to pass the Gradle configuration to DevContext.

**Comment by KaenDagger** [comment]
So plugin is quite good to be tested for maven and integrate into quarkus ?

**Comment by geoand** [comment]
Well we haven't tested it yet , hopefully myself @gastaldi and @ia3andy can do that soon.

But we'll also need to figure out the Gradle situation as well in order to provide at least a mostly working solution.

**Comment by geoand** [comment]
@KaenDagger I did the following:

* Checked out the latest master for your https://github.com/KaenDagger/quarkus-allopen
* Built it using `./gradlew publishToMavenLocal`
* Made the following change to in Quarkus to `src/test/resources/projects/classic-kotlin/pom.xml`

```
diff --git a/integration-tests/kotlin/src/test/resources/projects/classic-kotlin/pom.xml b/integration-tests/kotlin/src/test/resources/projects/classic-kotlin/pom.xml
index 48c5019e5..e7bb9f668 100644
--- a/integration-tests/kotlin/src/test/resources/projects/classic-kotlin/pom.xml
+++ b/integration-tests/kotlin/src/test/resources/projects/classic-kotlin/pom.xml
@@ -94,19 +94,14 @@
                 </executions>
                 <configuration>
                     <compilerPlugins>
-                        <plugin>all-open</plugin>
+                        <plugin>quarkus-allopen</plugin>
                     </compilerPlugins>
-                    <pluginOptions>
-                        <!-- Each annotation is placed on its own line -->
-                        <option>all-open:annotation=javax.enterprise.context.ApplicationScoped</option>
-                        <option>all-open:annotation=javax.ws.rs.Path</option>
-                    </pluginOptions>
                 </configuration>
                 <dependencies>
                     <dependency>
-                        <groupId>org.jetbrains.kotlin</groupId>
-                        <artifactId>kotlin-maven-allopen</artifactId>
-                        <version>${kotlin.version}</version>
+                        <groupId>io.quarkus.allopen</groupId>
+                        <artifactId>quarkus-maven-allopen</artifactId>
+                        <version>1.0</version>
                     </dependency>
                 </dependencies>
             </plugin>
```
*Launched the tests in the `integration-tests/kotlin`.

But unfortunately things are failing:

```
Caused by: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.spi.DefinitionException: Normal scoped bean must not be final: CLASS bean [types=[org.acme.GreetingService, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.GreetingService]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:879)

```

**Comment by KaenDagger** [comment]
For maven you have to package and install maven artifact. Checkout the maven part of ReadMe.md

**Comment by KaenDagger** [comment]
Just install and package `allopen-maven` module of Quarkus-allopen

**Comment by geoand** [comment]
OK, I thought the top level goal would work for both.

The integration test does seem to work now, nice

**Comment by KaenDagger** [comment]
@geoand  should we close this one? Now that if we are moving with Transformation

**Comment by geoand** [comment]
Sure yeah
