### ISSUE TITLE
Quarkus is not following MP Health spec to disable vendor procedures

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6860]
http://download.eclipse.org/microprofile/microprofile-health-2.1/microprofile-health-spec.html#_disabling_default_vendor_procedures states

> An implementation is allowed to supply a reasonable default (out-of-the-box) procedures as defined in the Health Check Procedures section. To disable all default vendor procedures users can specify a MicroProfile Config configuration property `mp.health.disable-default-procedures` to `true`. This allows the application to process and display only the user-defined health check procedures.

When using Quarkus specific `quarkus.health.extensions.enabled=false` (specified in application.properties) I'm able to suppress vendor specific checks.
```json
curl http://0.0.0.0:8080/health/ 2>/dev/null | jq .
{
  "status": "UP",
  "checks": []
}
```

When using MP Health specific `mp.health.disable-default-procedures=true` (specified in application.properties) I see "Database connections health check". 

```json
curl http://0.0.0.0:8080/health/ 2>/dev/null | jq .
{
  "status": "UP",
  "checks": [
    {
      "name": "Database connections health check",
      "status": "UP"
    }
  ]
}
```
"Database connections health check" shouldn't be visible.

I used Quarkus mvn plugin generated app and added following deps to have https://quarkus.io/guides/datasource#datasource-health-check
```xml
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-smallrye-health</artifactId>
      </dependency>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-agroal</artifactId>
      </dependency>
```

Running against Quarkus master d0029637f

**Comment by jmartisk** [comment]
As the newly appointed Health liaison, I will have a look into that tomorrow, unless someone else really wants to do it :)

**Comment by gsmet** [comment]
What I'm a bit worried about is how we will make all those mp.* config working with our configuration framework (typically the build time/runtime separation for instance).

We have that in a lot of extensions (Reactive Messaging, I'm looking at you) and it's not very pretty.

I'm not sure how we can properly deal with that.

**Comment by xstefank** [comment]
We haven't run into this problem before so sorry that we didn't implement itit. But can we, for instance, introduce additional annotation in SmallRye that would mark vendor-provided health checks? This would help also with SmallRye inclusion in other runtimes.

**Comment by jmartisk** [comment]
I'm afraid that if we want to (and we do) keep the unified configuration strategy (everything is in the `quarkus.` namespace), we can't ever avoid sorts of clashes with properties that are accepted by the libraries that we depend on.
In my understanding, the meaning of `mp.health.disable-default-procedures` is basically the same as the meaning of `quarkus.health.extensions.enabled`, except that the value should be inverted.

Wild idea: Potentially we could enhance our configuration framework with some sort of mapping - aliases - "if this library-specific property is specified, apply its value to this Quarkus config property (after applying some optional transformation)" and (maybe) apply to it the same rules that apply to the Quarkus property (for example, make it available at build time only). That could avoid having to check multiple properties in the extension code. But maybe it would be confusing to users, I don't know.

**Comment by dmlloyd** [comment]
I've suggested config aliases before but it was not well-received.  Perhaps though we could allow aliases only if they are defined outside of the `quarkus.` namespace, for use cases like this?

**Comment by kenfinnigan** [comment]
I think that's a good idea

**Comment by jmartisk** [comment]
+1, I guess it would make sense to use that for mapping between Quarkus properties and outside world properties. One unfortunate thing here is that at least in this case, we need to negate the boolean value, so we might need to incorporate some value transformation mechanism, which if we over-design, will get confusing.

**Comment by jmartisk** [comment]
I'll send a PR for this that resolves it without aliases. In the future, we might potentially replace that with the alias mechanism.
