### ISSUE TITLE
ArC - introduce an annotation to mimic @Observes StartupEvent

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#6864]
Sometimes it's useful to initialize a bean at startup but perfom all the logic in the constructor and/or in a `@PostConstruct` callback.

The annotation could be named `@Startup` because it would be aligned with `StartupEvent` and also implies that the bean is initialized when the application starts. Another possibilities include `@Eager`, `@EagerInit` or `@Start`.

**Comment by mkouba** [comment]
@stuartwdouglas @gsmet @geoand @emmanuelbernard @gastaldi and others... ideas, comments?

**Comment by geoand** [comment]
I personally like `@Eager` better since I think it better conveys the intent, however given the fact that we already have `StartupEvent`, I think `@Startup` makes the most sense

**Comment by gastaldi** [comment]
`@Startup` sounds like a rip-off from the EJB spec so it may be easier to grasp the idea and as @geoand pointed out: considering that `StartupEvent` exists, that makes more sense.

+1 to `@Startup`

**Comment by manovotn** [comment]
I am leaning towards `@Eager` since most people are familiar with the concept of eager/lazy init or they even have personal experience with Weld/ArC being lazy. `@Startup` would be my second choice, but depending on impl, I think people don't even need to know it leverages `StartupEvent` (which is Quarkus-specific).

@mkouba what implementation do you have in mind? Auto-generated observer for `StartupEvent`?

**Comment by mkouba** [comment]
The problem with `@Eager` is that it may misunderstood with respect to lazy initialization of normal scoped beans (for which client proxies are injected) which a completely different concept.

> what implementation do you have in mind?

I haven't thought about this yet.

**Comment by nimo23** [comment]
@mkouba there is already an issue for that 

https://github.com/quarkusio/quarkus/issues/5955

and I think also that the name `@Startup` is the right choice..`@Eager `is misleading.

**Comment by geoand** [comment]
@nimo23 indeed! I am the one that opened that issue and I didn't even remember it existed :)

@mkouba should we close this one and perhaps copy the comments over to that one?

**Comment by mkouba** [comment]
Hehe, I also participated in that discussion ;-).

Yes, I think that we should close this one but I don't think it's necessary to copy the comments.

One more important point - we should also make it possible to specify the priority value for the startup annotation. Observers ordering might be sometimes useful.

IMPL. NOTE: I'm currently working on a PR to support synthetic observers added via `BeanRegistrar`. Once this is merged the impl should be fairly easy:
1. Find all class beans annotated with this annotation
2. Create a synthetic observer for `StartupEvent` and inside the notify method:
  A. For normal scoped beans obtain the bean instance from the context
  B. For dependent beans (rare use case) create the bean instance and destroy it immediately.
