### ISSUE TITLE
native image using Spring web is not detecting any Spring rest and beans

### ISSUE THREAD

**Issue by AnakinPt** [quarkusio/quarkus#6868]
**Describe the bug**
A small application using Spring-web and Spring-di is not working when I build a Docker Native image. The same application runs when I use the dev mode or build a JVM image

**Expected behavior**
The application should detect the Spring Beans and Rest points~

**Actual behavior**
No Spring bean and rest point is being detected in the native image

**Configuration**
Image to build the application:
```
FROM quay.io/quarkus/ubi-quarkus-native-s2i:19.3.1-java8 AS build
COPY ["settings.gradle","gradle.properties","build.gradle","src","/usr/src/app/"]
USER root
RUN chown -R quarkus /usr/src/app
USER quarkus
WORKDIR /usr/src/app
RUN gradle buildNative

FROM hectormolinero/curl:v17-amd64 AS curl

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=build /usr/src/app/build/*-runner /work/application
COPY --from=curl /curl /curl
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 CMD ["/curl", "-f", "http://localhost:8080/health"]
```
Image to build the jvm version:
```
FROM fabric8/java-alpine-openjdk8-jre:1.6.5
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV AB_ENABLED=jmx_exporter

RUN adduser -G root --no-create-home --disabled-password 1001 \
  && chown -R 1001 /deployments \
  && chmod -R "g+rwX" /deployments \
  && chown -R 1001:root /deployments

COPY build/lib/* /deployments/lib/
COPY build/*-runner.jar /deployments/app.jar
EXPOSE 8080

# run with user 1001
USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]

```
Configuration class:
```
@Configuration
@Slf4j
public class RedisConfiguration {
    @Value("${REDIS_NODE_URIS}")
    String uris;

    @Bean
    public RedisClient redisClient(){
        log.info("Connect to redis using: "+uris);
        return RedisClient.create(uris);
    }

    @Bean
    public List<RedisURI> getUris(){
        return Arrays.asList(uris.split(",")).stream().map(RedisURI::create)
                .collect(Collectors.collectingAndThen(Collectors.toList(), Collections::unmodifiableList));
    }

    @Bean
    public StatefulRedisConnection<String, String> redisConnection(){
        log.info("Creating a new Redis connection");
        return redisClient().connect();
    }
}

```
Controller:
```
@RestController
@RequestMapping("/hello")
public class Hello {

  @Autowired HelloService helloService;

  @GetMapping
  public String hello() {
      return helloService.hello();
  }
}

```

build.gradle
```
plugins {
    id 'java'
    id 'io.quarkus'
    id "io.freefair.lombok" version "4.1.6"
    id 'com.palantir.docker' version "0.24.0"
    id "com.palantir.docker-compose" version "0.24.0"
    id "com.palantir.docker-run" version "0.24.0"
}

repositories {
     mavenLocal()
     mavenCentral()
}

dependencies {
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-netty'
    implementation 'io.quarkus:quarkus-smallrye-metrics'
    implementation 'io.quarkus:quarkus-spring-data-jpa'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-spring-web'
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.lettuce:lettuce-core:5.2.1.RELEASE'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'org.mockito:mockito-junit-jupiter:2.23.0'
    testImplementation 'org.springframework:spring-test:5.2.3.RELEASE'
    testImplementation "org.testcontainers:junit-jupiter:1.12.3"
}

group 'com.xpto'
version '1.0-SNAPSHOT'

compileJava {
    options.compilerArgs << '-parameters'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dockerCompose {
    dockerComposeFile 'src/main/docker/driving-assist/docker-compose.yml'
}

docker {
    name "${project.name}"
    tag 'distroless-latest', "distroless-${project.version}"
}

dockerRun {
    name 'hello-service'
    image "${project.name}"
    ports '8100:8080'
    daemonize true
    env 'REDIS_NODE_URIS': 'redis://172.17.0.2:6379/1'
}

task copyGradleConfigurationToDocker(type: Copy) {
    from "build.gradle", "settings.gradle", "gradle.properties"
    into "build/docker"
}
task copySourceToDockerBuild(type: Copy) {
    from "src"
    into "build/docker/src"
}
copyGradleConfigurationToDocker.mustRunAfter dockerClean
copySourceToDockerBuild.dependsOn copyGradleConfigurationToDocker
dockerPrepare.dependsOn copySourceToDockerBuild

```

**Environment (please complete the following information):**
```
quarkusPluginVersion=1.2.0.Final
quarkusPlatformArtifactId=quarkus-universe-bom
quarkusPlatformVersion=1.2.0.Final
quarkusPlatformGroupId=io.quarkus
```

**Comment by michalszynkiewicz** [comment]
related stackoverflow question: https://stackoverflow.com/questions/59971552/using-spring-di-with-quarkus-the-native-image-doesnt-expose-the-spring-rest-po

**Comment by geoand** [comment]
@AnakinPt can you please attach a reproducer project or upload the code to github so we can check?

I would really like this on order to not make any mistakes during copy paste from the issue details.

**Comment by geoand** [comment]
Also, can you try using the docker image that is described [here](https://quarkus.io/guides/building-native-image#creating-a-container-with-a-multi-stage-docker-build) please?

**Comment by AnakinPt** [comment]
@geoand that's the image I'm using. The only difference, my image has the curl to run the healthcheck.

**Comment by geoand** [comment]
Okay, then please make available a reproducer and I will start debugging immediately

**Comment by AnakinPt** [comment]
I created this repo https://github.com/AnakinPt/quarkus-spring

When I try to access to http://localhost:8120/hello?name=foo it answers with a 404 and an html page with h1 "Resource not found"

**Comment by geoand** [comment]
Thanks, I will have a look soon

**Comment by geoand** [comment]
@AnakinPt I wasn't able to build the native image using `./gradlew buildNative`.

FWIW, the Redis stuff you are using almost certainly does not work in native mode.

To conclude there is a lot of stuff going on in your application (additional build args for graalVM,  Redis, Lombok) to be able to easily figure out what is going on. I suggest that you try and minimize the application and see if you can reproduce the problem (which I may add I have never seen)

**Comment by AnakinPt** [comment]
It's not the Redis. I think it's something related with the spring.
I created a new project, just with the basics and I have the same problem.
The same repo I created yesterday is the most basic thing available. Can you see it again, please?

**Comment by geoand** [comment]
Of course, I'll have a look

**Comment by geoand** [comment]
I just tried your repo doing the following:

* `/gradlew buildNative`
* `./build/hello-quarkus-1.0-SNAPSHOT-runner`
* `curl http://localhost:8080/greeting` -> `hello`

which indicates that it's working. Am I missing something?

**Comment by AnakinPt** [comment]
I use the docker image to build the native runner because I can't build it in the windows. Can it be the problem?

**Comment by geoand** [comment]
I am assuming that your Dockerfile isn't correct in some way. So I am going to close this issue.

**Comment by AnakinPt** [comment]
I tried to add elements one by one and seems to be a problem with lettuce to connect to Redis. Thanks for the help.

**Comment by geoand** [comment]
You are welcome!

There is work in progress for a redis extension so hopefully you'll be able to use that soon in native mode as well
