### ISSUE TITLE
NullPointerException in UnmarshalRSSProcess

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#6869]
More failures with quarkus master with graal master:

```
[INFO] --------------< io.quarkus:quarkus-integration-test-main >--------------
[INFO] Building Quarkus - Integration Tests - Main 999-SNAPSHOT       [379/446]
[INFO] --------------------------------[ jar ]---------------------------------
...
java.lang.NullPointerException
	at io.quarkus.it.jaxb.mapper.process.UnmarshalRSSProcess.getQuarkusNews(UnmarshalRSSProcess.java:65)
	at io.quarkus.it.jaxb.mapper.process.UnmarshalRSSProcess.retrieveLastNews(UnmarshalRSSProcess.java:49)
	at io.quarkus.it.jaxb.mapper.process.UnmarshalRSSProcess_ClientProxy.retrieveLastNews(UnmarshalRSSProcess_ClientProxy.zig:177)
	at io.quarkus.it.jaxb.rest.NewsResource.getNews(NewsResource.java:28)
```

Full stacktrace [here](https://gist.github.com/galderz/41bc45404bce7cf58ca9193d768c7ef3)

**Comment by gsmet** [comment]
@galderz it could be related to package info too. I know I had to fix a few things in Quarkus to get package info properly included in the native image and JAXB properly working.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by galderz** [comment]
@gsmet Ok. I did test this with the patched graal version that I had created to fix the other issue. So it could be caused by that fix too. I'll check again next few days.

> Is this still an issue?

@geoand What do you mean exactly? As I said on the start, this was happening with quarkus and graal master, and more specifically I was using the patched graal with the fix linked from #6685 (PR not yet integrated, style issues...)

**Comment by geoand** [comment]
Okay understood, thanks

**Comment by galderz** [comment]
This appears to be fixed in most recent graal master. Could be due to Esteban's fix which was included instead of ours. Closing this for now.
