### ISSUE TITLE
quarkus-gradle-plugin 1.2 not published to mvnrepository 

### ISSUE THREAD

**Issue by Imaclean74** [quarkusio/quarkus#6875]
**Describe the bug**
As per the subject. the latest 1.2 release is referenced here : https://plugins.gradle.org/plugin/io.quarkus but is not published to mvnrepository although the rest of the 1.2 series packages seem to be. ie : https://mvnrepository.com/artifact/io.quarkus/quarkus-gradle-plugin has 1.01 as the latest release but quarkus-core.deployment has 1.2.0.FINAL https://mvnrepository.com/artifact/io.quarkus/quarkus-core-deployment. Our organization has an internal artifact repro that pulls from mvnrepository - so currently we're not able to pull the newer 1.2 build.

**Expected behavior**
lastest plugin build also published.

**Actual behavior**
It's not :)

**To Reproduce**
NA.

**Configuration**
NA

**Comment by gsmet** [comment]
It's normal. It is pushed to the Gradle plugin portal now: https://plugins.gradle.org/plugin/io.quarkus .

See the 1.1 release notes to see how to use the plugin now: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.1#gradle-plugin .

**Comment by Imaclean74** [comment]
well - my point is some of us - aren't able to access the gradle portal from behind a corporate firewall. Whereas mvrepository is mirrored into our internal repository.  Thanks for the link - but I'm familiar with how to use the plugin. In our case the repositories config looks like :

```
repositories {
         maven {
            url uri('http://area.{company.repo.url}/area/repo/public')
        }
    }
```
which is the only source we're able to use 

is it possible to *also* publish the newer plugin version to mvnrepository ? It's likely we're not the only organization with a similar setup.

thanks,
Ian

**Comment by ewsni** [comment]
not sure the jar is available.

https://plugins.gradle.org/m2/io/quarkus/io.quarkus.gradle.plugin/1.2.1.Final/ contains pom but no jar

include plugin 12.0 or 1.2.1 is not working
