### ISSUE TITLE
Quarkus Infinispan Client Extension in a profile is not visible in Quarkus Unit Tests

### ISSUE THREAD

**Issue by MarianMacik** [quarkusio/quarkus#6885]
@gastaldi I am writing as we agreed.

**Describe the bug**
When I want to inject some CDI beans from Infinispan Client Extension, i.e. RemoteCacheManager and run unit tests with these components, I am getting:

```
Caused by: javax.enterprise.inject.spi.DeploymentException: 
Found 2 deployment problems: 
[1] Unsatisfied dependency for type org.infinispan.client.hotrod.RemoteCacheManager and qualifiers [@Default]
        - java member: org.acme.quickstart.GreetingResource#cacheManager
        - declared on CLASS bean [types=[org.acme.quickstart.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.quickstart.GreetingResource]
[2] Unsatisfied dependency for type org.infinispan.client.hotrod.RemoteCacheManager and qualifiers [@Default]
        - java member: org.acme.quickstart.GreetingResourceTest#cacheManager
        - declared on CLASS bean [types=[org.acme.quickstart.GreetingResourceTest, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.quickstart.GreetingResourceTest]
```
However, when I put the extension among the default dependencies of the project, tests will run OK. This happens when I'm injecting a bean both to the tests and my beans. The Infinispan beans are not there.
When I skip tests and just run the application, it works without any issues. You can call the REST resource which correctly calls a method on the Infinispan RemoteCacheManager CDI bean.

You can also inspect dependency trees which are identical. It seems that Quarkus JUnit Extension doesn't take into account dependencies from Maven profiles.

See the reproducer [1] for more details.

**Expected behavior**
It doesn't matter if an extension is in the profile or in the default dependencies section.

**Actual behavior**
CDI beans are discovered in unit tests when the extension is in the default dependencies section, but are not when it is added via a Maven profile.

**To Reproduce**
Can be found in the reproducer [1].

**Configuration**
See reproducer [1].

**Screenshots**
None.

**Additional context**
Reproducer available at:
[1] https://github.com/MarianMacik/quarkus-infinispan-reproducer

**Comment by MarianMacik** [comment]
Any updates guys?

**Comment by MarianMacik** [comment]
@gastaldi WIth version 1.3.0.Final this doesn't happen anymore. Did you fix it?

**Comment by gastaldi** [comment]
I don't remember TBH, maybe @aloubyansky did it. Closing this is Out of date then. Thank you!

**Comment by MarianMacik** [comment]
Thanks!
