### ISSUE TITLE
quarkus-cache extension not working due to missing libraries

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#6900]
**Describe the bug**
I was trying to use the new quarkus-cache extension in the 1.2.0.Final version but it does not seem to be possible as the necessary libraries are not found

**Expected behavior**
No compilation error and @CacheResult annotation is found

**Actual behavior**
The class with a method annotated with @CacheResult could not be compiled and the annotation is not found.
I checked the libraries loaded in IntelliJ and the closer I can get related to the quarkus-cache extension is **io.quarkus:quarkus-caffeine:1.2.0.Final**

<img width="401" alt="Screenshot 2020-01-30 22 06 27" src="https://user-images.githubusercontent.com/7215870/73490427-cf534c00-43ac-11ea-8166-14add8767768.png">

**To Reproduce**
1. Create a simple project and add quarkus-cache as specified in the documentation via Maven
2. Create a class and annotate a method with @CacheResult
3. run mvn compile
4. Actual compilation result is
`ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project inzo24-is24-expose: Compilation failure
[ERROR] /Volumes/Work/projets/inzo24/inzo24-is24-expose/src/main/java/com/dwitech/eap/inzo24/is24/exposes/control/IS24ExposeCaller.java:[35,6] cannot find symbol
[ERROR]   symbol:   class CacheResult
[ERROR]   location: class com.dwitech.eap.inzo24.is24.exposes.control.IS24ExposeCaller
`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin DWI-MBP15-1 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
 - Quarkus version or git rev: 1.2.0.Final

**Comment by gsmet** [comment]
@gwenneg can you have a look?

**Comment by dwamara** [comment]
I cleaned my local maven repository and recompiled the project. The file _quarkus-cache--1.2.0.Final.jar_ has been downloaded from the internet and is now present in my local repository but still does not appear in IntelliJ. I don't think it's an IntelliJ problem but I can't pinpoint what could be the reason.

<img width="849" alt="Screenshot 2020-01-30 22 32 44" src="https://user-images.githubusercontent.com/7215870/73492250-9ae18f00-43b0-11ea-9210-87106ddbfd8c.png">

**Comment by gwenneg** [comment]
Thanks for reporting this issue @dwamara, I'll investigate it right away.

**Comment by gwenneg** [comment]
I don't see any issue locally so far, still investigating...

Would it be possible for you to provide us with a reproducer that fails to build?

**Comment by dwamara** [comment]
It seems to have been solved, just made an update of IntelliJ, strange but I'll close the issue and let you go back to your daily business.

**Comment by gwenneg** [comment]
Since IntelliJ didn't seem to find `quarkus-cache-1.2.0.Final.jar` at first, maybe there was a problem with the `@CacheResult` import in your Java class. I checked everything from the JAR uploaded on Maven Central to the project generation and found no problem so I think your project should be fine now.

Thanks for testing this new extension!

**Comment by dwamara** [comment]
Just a quick question: does the cache get persisted or is it gone if I restart quarkus?

**Comment by gwenneg** [comment]
`quarkus-cache` stores the cached data into an in-memory Caffeine cache, so the cache will be empty if you restart your server.
