### ISSUE TITLE
JAXB Extension Project Issue

### ISSUE THREAD

**Issue by jjdestef3** [quarkusio/quarkus#6902]
Hi,

Not sure if this is an issue or done by intent. The JAXB extension deployment project has a ReflectiveClassBuildItem, com.sun.xml.internal.stream.XMLInputFactoryImpl (line 178 of JaxbProcessor.java) but not for com.sun.xml.internal.stream.XMLOutputFactoryImpl. On a project I've been working on the absence of this class in the native build caused an exception. When I created an extension to support the project and added the class in the deployment processor all worked well.  

As I mentioned above, I don't know if excluding the class was intentional based on the JAXB extension use case.

Thanks

**Comment by geoand** [comment]
@jjdestef3 Thanks for reporting!

Would you be willing to submit a Pull Request that includes the fix and a test case that showcases that the fix is needed?

Thanks
