### ISSUE TITLE
@DisabledOnNativeImage vs @DisableForNative annotations

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6904]
Having `@DisabledOnNativeImage` and `@DisableForNative` annotations to disabling tests for native mode is a bit confusing.

https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5/src/main/java/io/quarkus/test/junit/DisabledOnNativeImage.java is the end-user facing annotation.

https://github.com/quarkusio/quarkus/blob/master/integration-tests/maven/src/test/java/io/quarkus/maven/it/DisableForNative.java was introduced in https://github.com/quarkusio/quarkus/commit/03b7ae4f8b90d732d8d35879d266a4081d9a91f3. 
Benefit of DisableForNative annotation is `@DisabledIfSystemProperty(named = "quarkus.test.native", matches = "true")`

Can be `@DisabledOnNativeImage` and `@DisableForNative` merged together?

CC @geoand @gsmet

**Comment by geoand** [comment]
Well they can't really be merged, but as @gsmet pointed out when I added the annotation, we can drop the annotation altogether and just configure the failsafe and surefire plugins of the `maven` integration-test module to include / exclude only what is necessary

**Comment by geoand** [comment]
This can be closed as `@DisabledOnNativeImage` no longer exists
