### ISSUE TITLE
Vault tests have `@DisabledOnOs(OS.WINDOWS)` without any link to the issue

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6905]
Vault tests have `@DisabledOnOs(OS.WINDOWS)` without any link to the issue

```
integration-tests/vault-agroal/src/test/java/io/quarkus/vault/AgroalVaultITCase.java:@DisabledOnOs(OS.WINDOWS)
integration-tests/vault-agroal/src/test/java/io/quarkus/vault/AgroalVaultKv2ITCase.java:@DisabledOnOs(OS.WINDOWS)
integration-tests/vault-app/src/test/java/io/quarkus/it/vault/VaultInGraalITCase.java:@DisabledOnOs(OS.WINDOWS)
integration-tests/vault-app/src/test/java/io/quarkus/it/vault/VaultTest.java:@DisabledOnOs(OS.WINDOWS)
integration-tests/vault/src/test/java/io/quarkus/vault/VaultAppRoleITCase.java:@DisabledOnOs(OS.WINDOWS)
integration-tests/vault/src/test/java/io/quarkus/vault/VaultITCase.java:@DisabledOnOs(OS.WINDOWS)
integration-tests/vault/src/test/java/io/quarkus/vault/VaultMultiPathConfigITCase.java:@DisabledOnOs(OS.WINDOWS)
```

It's hard to figure out why this annotation was added. When tests are disabled, a link to the issues (or at least comment) should be added.

@vsevel, please add link to the issue for Windows disabled tests.

CC @gsmet

**Comment by vsevel** [comment]
hello @rsvoboda here is the short answer: https://github.com/quarkusio/quarkus/issues/3796

**Comment by rsvoboda** [comment]
> do you want me to add this link in each test?

+1

I can prepare PR not to bother you too much. Just say ...

**Comment by vsevel** [comment]
@rsvoboda no problem I will do it if this is common practice
