### ISSUE TITLE
jacksonDeserilazationIgnoresPersitantAttribute is disabled on native, no link to an issue

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6906]
PanacheFunctionalityTest.jacksonDeserilazationIgnoresPersitantAttribute is disabled on native
There is no link to an issue

https://github.com/quarkusio/quarkus/blob/master/integration-tests/hibernate-orm-panache/src/test/java/io/quarkus/it/panache/PanacheFunctionalityTest.java#L83

@the-bug, can you add link to the issue ? Or at least describe the problem on native image ...

**Comment by gsmet** [comment]
And maybe we should fix the typos in the method name too :).

**Comment by the-bug** [comment]
Hello,
@rsvoboda @gsmet thank you for the review!

There exists no issue for this test. There is just an PR: https://github.com/quarkusio/quarkus/pull/5421. There is the bug described.

I have created an PR that fixes the typo and extends the comment belonging to the test to answers @rsvoboda question.

**Comment by the-bug** [comment]
PR was merged.
@rsvoboda Can we close this issue?

**Comment by machi1990** [comment]
Thanks for the heads up @the-bug 

Fixed by #6942. 
Closing!
