### ISSUE TITLE
AddGradleExtensionsTest.addExtensionTwiceInTwoBatches disabled, but no issue linked

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6910]
AddGradleExtensionsTest.addExtensionTwiceInTwoBatches disabled, but no issue linked
https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/common/src/test/java/io/quarkus/cli/commands/AddGradleExtensionsTest.java#L17

@ia3andy is there an issue to implement/fix this scenario ?

This issue needs to be mentioned as value of `@Disabled` annotation for better auditing

**Comment by stuartwdouglas** [comment]
No longer an issue.
