### ISSUE TITLE
WebsocketTestCase.testSendMessageOnOpen is disabled but no followup issue is linked

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#6911]
WebsocketTestCase.testSendMessageOnOpen is disabled but no followup issue is linked

https://github.com/quarkusio/quarkus/blob/master/integration-tests/main/src/test/java/io/quarkus/it/main/WebsocketTestCase.java#L108 says:
test disabled as the message handler may be registered after the messages being sent

@cescoffier
is this something that will not change ? => test is not relevant
something to be fixed ? => issue should be created and mentioned in WebsocketTestCase.testSendMessageOnOpen

**Comment by stuartwdouglas** [comment]
This has been fixed.
