### ISSUE TITLE
Add hot reload tests for Reactive SQL Clients

### ISSUE THREAD

**Issue by tsegismont** [quarkusio/quarkus#6917]
Nothing fancy, but make sure the databases can be queried again when after code changes

**Comment by tsegismont** [comment]
@cescoffier I can't change labels, obviously this is not a bug report :wink: : 

For implementation, I wonder where I could put such a test. Is it fine in the integration test module?

**Comment by machi1990** [comment]
> @cescoffier I can't change labels, obviously this is not a bug report 😉

It is more of a housekeeping issue. I am changing the label to it. @tsegismont WDYT?

**Comment by tsegismont** [comment]
@machi1990 Fine with me
