### ISSUE TITLE
Could not resolve dependencies for project

### ISSUE THREAD

**Issue by stefvanderwel** [quarkusio/quarkus#6919]
**Describe the bug**
When having a multi-module project, Quarkus can't seem to package if a submodule has a dependency to another submodule.

**Expected behavior**
The project should be able to compile

**Actual behavior**
It fails with this error:
```stacktrace
[ERROR] Failed to execute goal on project application-1: Could not resolve dependencies for project eu.mentechinnovation.stefvdwel:application-1:jar:1.0-SNAPSHOT: Could not find artifact eu.mentechinnovation.stefvdwel:dependency-2:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :application-1
```

**To Reproduce**
The project can be found [here](https://gitlab.com/stefvdwel/quarkus-dependency-test2).
1. `./mvnw clean`
2. `./mvnw -pl dependency-2 clean install`
3. `./mvnw install -N`
4. `./mvnw install -DskipTests`
The full output can be found [here](https://gitlab.com/stefvdwel/quarkus-dependency-test2/-/jobs/422090109).

**Configuration**
See [project](https://gitlab.com/stefvdwel/quarkus-dependency-test2)

**Environment (please complete the following information):**
Docker image of adoptopenjdk/openjdk11:alpine

**Comment by aloubyansky** [comment]
Here is your fix
```
diff --git a/application-1/pom.xml b/application-1/pom.xml
index 7b1cacf..3963078 100644
--- a/application-1/pom.xml
+++ b/application-1/pom.xml
@@ -59,7 +59,7 @@
         </dependency>
 
         <dependency>
-            <groupId>eu.mentechinnovation.stefvdwel</groupId>
+            <groupId>org.acme</groupId>
             <artifactId>dependency-2</artifactId>
             <version>1.0-SNAPSHOT</version>
         </dependency>
```
