### ISSUE TITLE
properties.config file is not properly read after setting environment variables

### ISSUE THREAD

**Issue by TheVidAllMayThe** [quarkusio/quarkus#6921]
When I launch a quarkus application while setting an environment variable `QUARKUS_HTTP_PORT=8080 ./gradlew quarkusDev` everything works fine. But if I take out the environment variable I get the following error:

`Configuration key "quarkus.http.port" is required, but its value is empty/missing: Property quarkus.http.port not found`

quarkus.http.port is present in the application.properties file.

I've tried to reset the terminal, ensured that there's no environment variable set, but I only manage to run the program again without specifying the environment variable after rebooting the machine.

I've noticed this issue in multiple variables and both in ubuntu 18.04LTS and mac os Catalina.

I haven't tested with maven yet.

**Comment by dmlloyd** [comment]
The correct "spelling" of the environment variable should be `QUARKUS_HTTP_PORT` (with underscores `_` rather than periods `.`).  Could you try that out and see if it helps?

**Comment by TheVidAllMayThe** [comment]
> The correct "spelling" of the environment variable should be `QUARKUS_HTTP_PORT` (with underscores `_` rather than periods `.`). Could you try that out and see if it helps?

Sorry, my mistake. I been doing it as you said. I've corrected it above!

**Comment by dmlloyd** [comment]
OK.  And I assume you're using `application.properties` not `application.config`?

**Comment by TheVidAllMayThe** [comment]
Once again correct! Thank you for pointing it out!

**Comment by TheVidAllMayThe** [comment]
I can confirm that this issue does not happen with maven. It would be really nice to solve it for gradle since it is very annoying

**Comment by stuartwdouglas** [comment]
This is a gradle bug, you can fix it by stopping the daemon (gradle --stop). I am not sure exactly how this works, I guess gradle must be spawning the process with the env var as the empty string if the original daemon was started when it was actually set.

**Comment by AdlerFleurant** [comment]
I just tested this bug and it seems that it has been resolved.

My environment:

- Gradle 7.5.1
- MacOS Monterey
- JDK 17
- Quarkus 2.12.0

We can safely close this issue.
