### ISSUE TITLE
OpenApi NPE using default method with generic types

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#6933]
**Describe the bug**
OpenApi is unable to undertand the type of generic method in interfaces and throw NPE.

**Expected behavior**
The generic interface is parsed and docs generated

**Actual behavior**
```
Caused by: java.lang.NullPointerException
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.createResponseFromJaxRsMethod(OpenApiAnnotationScanner.java:934)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsMethod(OpenApiAnnotationScanner.java:688)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.lambda$processJaxRsResourceClass$0(OpenApiAnnotationScanner.java:422)

```

**To Reproduce**
1. mvnw quarkus:dev
2. or
3. mvnw install

**Environment (please complete the following information):**
 - Darwin WMICTLM1P.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
 - openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009173705.graal.jdk8u-src-tar-gz-b07)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 25.232-b07-jvmci-19.3-b05, mixed mode)
 - <quarkus.platform.version>1.2.0.Final</quarkus.platform.version>

**Additional context**
As a workaround you can rename the generic method, comment @Override and call the renamed method in super interface.

**Comment by masini** [comment]
[quarkus-120-issues.zip](https://github.com/quarkusio/quarkus/files/4142457/quarkus-120-issues.zip)

Reproducer project

**Comment by EricWittmann** [comment]
@gsmet This reproducer builds OK when I use the `master` **smallrye-open-api** library.  I suggest we wait for the next release (should be happening soon) and re-test this reproducer.

**Comment by EricWittmann** [comment]
For the record, this is the openapi that is generated when I use sr-oai `master` to do the build:

```json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Generated API",
    "version" : "1.0"
  },
  "paths" : {
    "/hello" : {
      "get" : {
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      },
      "post" : {
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/MyStupidEntity"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/MyStupidEntity"
                }
              }
            }
          }
        }
      }
    },
    "/hello/other" : {
      "get" : {
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "text/html" : {
                "schema" : {
                  "$ref" : "#/components/schemas/StreamingOutput"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "StreamingOutput" : {
        "type" : "object"
      },
      "MyStupidEntity" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "format" : "int64",
            "type" : "integer"
          },
          "value" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

**Comment by gsmet** [comment]
It should be fixed in Alpha2 that will be released in a couple of hours.

Please retest once released and report back, thanks!
