### ISSUE TITLE
Jandex WARNING using standard JAX-RS classes

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#6934]
**Describe the bug**
This is not a real bug but an annoying WARNING if you use classes like javax.ws.rs.core.StreamingOutput:

```
    @GET
    @Path("other")
    @Produces(MediaType.TEXT_HTML)
    public StreamingOutput renderGWTHostingPage() {

        return output -> output.write("hello".getBytes(Charset.defaultCharset()));
    }

``` 

**Expected behavior**
No WARNING

**Actual behavior**
This is printed on the console at startup:
```
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- javax.ws.rs.core.StreamingOutput
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.

```

**To Reproduce**
1. mvnw compile quarkus:dev

**Environment (please complete the following information):**
 - Darwin WMICTLM1P.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
 - openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009173705.graal.jdk8u-src-tar-gz-b07)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 25.232-b07-jvmci-19.3-b05, mixed mode)
 - <quarkus.platform.version>1.2.0.Final</quarkus.platform.version>
[quarkus-120-issues.zip](https://github.com/quarkusio/quarkus/files/4142463/quarkus-120-issues.zip)

**Additional context**
Please use the reproducer project.

**Comment by nimo23** [comment]
Related to https://github.com/quarkusio/quarkus/issues/5871

**Comment by masini** [comment]
I'm not sure it's related because that extension is jandexed and only a single class is reported (StreamingOutput) not all the included classes.

**Comment by gsmet** [comment]
It's just that it needed to be added to the ignore list as it has its own provider handling it.

I did it there: https://github.com/quarkusio/quarkus/pull/7001 .

**Comment by nimo23** [comment]
@gsmet Does this mean that one must put all those classes mentioned in https://github.com/quarkusio/quarkus/issues/5871 into ignore list?

For example:

```
DotName.createSimple("com.github.benmanes.caffeine.cache.Cache"),
DotName.createSimple("javax.crypto.Cipher"),
DotName.createSimple("javax.enterprise.event.Event"),
```

**Comment by gsmet** [comment]
@nimo23 no. For your other use case, there's probably something that should not be serialized and then drags everything with it.

Either it's an error in your code or it's Quarkus not excluding things properly.
