### ISSUE TITLE
Stop dealing with the SunEC library during the native image generation

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#6939]
GraalVM `19.3.0` removed the need to ship the SunEC library with the native image:

> GraalVM 19.3 switched to using the JDK native code instead of manual substitutions. For GraalVM Native Image this switch to Java Native Interface (JNI) platform enabled the possibility to provide support for JDK 11 and extended support for Windows OS. It has no impact on startup time or memory footprint, and eliminates the need for shipping JDK libraries such as libsunec.so along with native images that use Java crypto services. GraalVM now ships with statically linkable version of the JDK libraries.
Note that the sunec native library of SunEC provider gets statically linked into an image if required (see #951). Thus native images do not depend on the sunec shared library anymore at runtime. However, if SunEC provider gets statically linked into an image on Linux and macOS the image will depend on libstdc++.

We currently support GraalVM `19.3.1` but we're still dealing with this lib in `NativeImageConfigBuildStep` because of some old code that should be removed.

I'll submit a PR.

**Comment by valones** [comment]
Update Dockerfile.native sample too:

```
FROM quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 as nativebuilder

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=nativebuilder $JAVA_HOME/lib/security/cacerts /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djavax.net.ssl.trustStore=/work/cacerts"]
```
