### ISSUE TITLE
MultipartConfig annotation is ignored at HttpServlet by quarkus-undertow

### ISSUE THREAD

**Issue by mailq** [quarkusio/quarkus#6944]
**Describe the bug**
Adding @MultipartConfig to a HttpServlet gets ignored by quarkus. While POSTing a file to the Servlet an IllegalStateException "UT010057: multipart config was not present on Servlet" is thrown.

**Expected behavior**
Quarkus or undertow should respect the MultipartConfig annotation and act accordingly.

**Actual behavior**
Despite adding the requested annotation, it is ignored. And then quarkus complains about missing annotation.

**To Reproduce**
1. Use extracted attached minimal project
2. run "gradlew quarkusDev" inside the project folder
3. create a file "somefile.txt" with random content
4. execute "curl -F'file=@somefile.txt' http://localhost:8080/ul"

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 5.3.0-29-generic x86_64 GNU/Linux
 - Output of `java -version`: OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)
 - GraalVM version (if different from Java): not installed
 - Quarkus version or git rev: 1.2.0-Final

**Additional context**
When attaching a debugger while starting quarkus on UndertowDeploymentRecorder at method registerServlet() one can see that the attribute multipartConfig of ServletInfo is null.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/4144190/code-with-quarkus.zip)

**Comment by gsmet** [comment]
@ia3andy maybe you could have a look at that one?
