### ISSUE TITLE
A dependency with a jandex index is not more accounted as ApplicationArchive

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#6951]
**Describe the bug**

While testing against the latest quarkus bits for camel-quarkus, I've noticed that the a test named `core-main` started failed because some resources scanned at runtime are not more found, in this case it is about some files located on the classpath under `META-INF/services/org/apache/camel` even if the dependency that brings them has a proper jandex index.

This happens because for some reason the dependency is not more accounted as an `ApplicationArchive` so as workaround I've tried to force quarkus to index such dependency with:

```
quarkus.index-dependency.main-ext.group-id = org.apache.camel.quarkus
quarkus.index-dependency.main-ext.artifact-id = camel-quarkus-integration-test-support-core-main-ext
```

**Expected behavior**

**Actual behavior**

There are actually 2 isssues:
1. if the dependency is not forced to be indexed, then the resources are not found even if the jandex index is present
2. if the dependency is forcedly indexed, then build fails with:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project camel-quarkus-integration-test-core-main: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Could not resolve artifact org.apache.camel.quarkus:camel-quarkus-integration-test-support-core-main-ext:null. Please make sure it is present and contains a META-INF/MANIFEST.MF file. Note that artifacts that are part of the same project may not always be resolvable, in this case you should generate a META-INF/jandex.idx file instead using the Jandex Maven plugin.
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.getIndexDependencyPaths(ApplicationArchiveBuildStep.java:148)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.scanForOtherIndexes(ApplicationArchiveBuildStep.java:110)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.build(ApplicationArchiveBuildStep.java:97)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: Could not resolve artifact org.apache.camel.quarkus:camel-quarkus-integration-test-support-core-main-ext:null. Please make sure it is present and contains a META-INF/MANIFEST.MF file. Note that artifacts that are part of the same project may not always be resolvable, in this case you should generate a META-INF/jandex.idx file instead using the Jandex Maven plugin.
[ERROR] 	at io.quarkus.deployment.index.ClassPathArtifactResolver.getArtifact(ClassPathArtifactResolver.java:68)
[ERROR] 	at io.quarkus.deployment.index.ArtifactIndex.getPath(ArtifactIndex.java:14)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.getIndexDependencyPaths(ApplicationArchiveBuildStep.java:136)
[ERROR] 	... 14 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :camel-quarkus-integration-test-core-main
``` 

**To Reproduce**

clone `https://github.com/lburgazzoli/apache-camel-quarkus/tree/quarkus-master-pr-6951`, then:
* compile the project with `clean install -DskipTests=true` to trigger the exception
+ remove the indexing instruction from `integration-tests/core-main/src/main/resources/application.properties` and run tests on `core-main` to trigger the failure because of the resources are not found

**Additional context**

Please note that the resources under `META-INF/services/org/apache/camel` are provided by a support [extension](https://github.com/lburgazzoli/apache-camel-quarkus/tree/quarkus-master-pr/integration-tests/support/core-main).

**Comment by gsmet** [comment]
If you're talking about resources and not annotation/class scanning, then it's more related to the class loader infrastructure than to Jandex.

**Comment by lburgazzoli** [comment]
Yeah, it is not a jandex issue per se but maybe a conseguence of the classloader changes that does not add extensions as ApplicationArchives even if they have a proper jandex index file

**Comment by stuartwdouglas** [comment]
index-dependency does not work because the jar is in the project itself, so we can't interpolate it's name from the location in the maven repo. This is not really something we want to support anyway, as if it is part of the same project then you can just add an index (well you are supposed to be able to...).

**Comment by lburgazzoli** [comment]
So I found the reason and it is related how application archive are now constructed so if the archive is part of the project, then the paths the archive points to are project path, instead of pointing to a jar.

This should not cause issue usually but we have some bits in camel-quarkus that reason in term of paths and of course resources from jars have different paths than those from the filesystem.

I now have a fix in camel-quarkus.
