### ISSUE TITLE
Qute iterating by number

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#6963]
**Description**

Iterate by a number instead of by a list of elements.

**Implementation ideas**

```
{#repeat var.total}
   ...
{/repeat}
```

I think we could do things more complex like in FreeMarker but at least having this structure would help a lot in some cases.

**Comment by gastaldi** [comment]
Maybe the `for` statement could be smart enough to detect if the variable is a Number and iterate through that instead:
Eg.

Having total = 3: 

```java
    {#for i in total} 
      {i}
    {/for}
```

Would output
```
  0
  1
  2 
```
