### ISSUE TITLE
Reproducible builds: order native image BuildItems where necessary

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#6966]
The order of BuildItems consumed by NativeImageAutoFeatureStep (and possibly other steps) impacts the order of instructions output to the runner jar. To make the build binary reproducible, we need to make the ordering of the BuildItems consumed by NativeImageAutoFeatureStep deterministic. This can be done by making those BuildItems implement Comparable. 

Note that there are other build items causing similar problems. I'll create separate issues for those, to keep the size of the PRs manageable.

**Comment by dmlloyd** [comment]
Note that this only affects the reproducibility of the class files.  If two program instructions are truly order-independent, they can be reordered by the JIT, or reordered by the optimizing GraalVM compiler, at run time.

**Comment by ppalaga** [comment]
> Note that this only affects the reproducibility of the class files.

Yes, I only care for what we output to the runner.jar at build time.

**Comment by ppalaga** [comment]
This is not necessary with the last iteration of https://github.com/quarkusio/quarkus/pull/6972
