### ISSUE TITLE
NullPointerException with mixed media types

### ISSUE THREAD

**Issue by azzazzel** [quarkusio/quarkus#6974]
When there are different `@Produces`/`@Consumes` media types a `NullPointerException` is returned inside the body of a `400 Bad Request` response. No error/stacktrace in the log.

**Steps to reproduce the behavior:**
1. Use the code from rest-json-quickstart (https://github.com/quarkusio/quarkus-quickstarts/tree/master/rest-json-quickstart) 
2. Add `quarkus-resteasy-jaxb` dependency to the pom
3. Change `FruitResource` to
```java
@Consumes(MediaType.APPLICATION_XML)
@Produces(MediaType.APPLICATION_JSON)
```
4. Add `@XmlRootElement` to `Fruit` 
3. Change `FruitResourceTest.testAdd()` test to send proper XML:
```java
given()
   .body("<fruit><name>Pear</name><description>Winter fruit<description></fruit>")
   .header("Content-Type", MediaType.APPLICATION_XML)
```

**Expected result**: test passes

**Actual result**: test fails with `Expected status code <200> but was <400>`

The actual response is:
```
HTTP/1.1 400 Bad Request
Content-Length: 30
Content-Type: text/html;charset=UTF-8

<html>
  <body>java.lang.NullPointerException</body>
</html>
```

Quarkus version: 1.2.0.Final

**Comment by gsmet** [comment]
I'm unsure this could work if you don't have `quarkus-resteasy-jaxb`. But still this is weird.

**Comment by gsmet** [comment]
@ia3andy I think we need to understand where this NPE is coming from. Even if the configuration is invalid, we shouldn't throw a NPE, especially with nothing being logged.

**Comment by azzazzel** [comment]
1) I do have `quarkus-resteasy-jaxb` (see 2 in the original post)

2) My debugging research points me down to `AbstractJAXBProvider`. [This](https://github.com/resteasy/Resteasy/blob/master/providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/AbstractJAXBProvider.java#L76) returns `null`.

**Comment by ia3andy** [comment]
@gsmet sure I'll look into it tomorrow ;-)

**Comment by gsmet** [comment]
@ia3andy my guess would be that we probably need to also consider `@Consumes` for `ContextResolvers` here: https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L270 .

**Comment by gsmet** [comment]
@azzazzel @ia3andy worked on a fix that will be included in our next release.

In the meantime, there is an easy workaround: just create a dummy endpoint with `@Produces(MediaType.APPLICATION_XML)`. It will trigger the JAXB context resolver registration.

Thanks for reporting this will all the details!

**Comment by azzazzel** [comment]
Thank you @gsmet
