### ISSUE TITLE
Gradle's QuarkusPluginFunctionalTest shouldn't use @TempDir

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#6988]
When using `@TempDir` in a Junit test, the temporary directory is removed at the end of the execution.

So, right now, if you have a test failing in `QuarkusPluginFunctionalTest`, you don't know what's going wrong.

We should probably create a temporary directory in the `target` dir, that is not removed at the end of execution.

**Comment by gsmet** [comment]
@gastaldi could you check? I had a failure when releasing this morning and had to apply:
```diff
+++ b/devtools/gradle/src/functionalTest/java/io/quarkus/gradle/QuarkusPluginFunctionalTest.java
@@ -9,6 +9,7 @@ import java.util.Arrays;
 import java.util.HashMap;
 import java.util.List;
 import java.util.Map;
+import java.nio.file.Files;
 
 import org.gradle.testkit.runner.BuildResult;
 import org.gradle.testkit.runner.GradleRunner;
@@ -29,8 +30,8 @@ public class QuarkusPluginFunctionalTest {
     private File projectRoot;
 
     @BeforeEach
-    void setUp(@TempDir File projectRoot) {
-        this.projectRoot = projectRoot;
+    void setUp(@TempDir File projectRoot) throws IOException {
+        this.projectRoot = Files.createTempDirectory("gradle-test-").toFile();
     }
 
     @Test
@@ -89,4 +90,4 @@ public class QuarkusPluginFunctionalTest {
                         .withFailMessage("Project was not created")
                         .isTrue();
     }
-}
\ No newline at end of file
+}
```
to get some useful info.

**Comment by gastaldi** [comment]
I'll investigate. Two things I know in advance:

1) The `@TempDir` should refer to a new directory and contain only the generated project sources

2) Gradle test failures logs are uploaded to scans.gradle.com and are kept there for a few days AFAIR - you should see a link in the build.

**Comment by gsmet** [comment]
> The @TempDir should refer to a new directory and contain only the generated project sources

Yes but it's removed even in the case of failures. From the JUnit doc, it seems to be the expected behavior. (but I might have missed something)

> Gradle test failures logs are uploaded to scans.gradle.com and are kept there for a few days AFAIR - you should see a link in the build.

Yeah, well, they asked for an email. I stopped there. I don't want to give an email to see my own test failures.

**Comment by gastaldi** [comment]
@TempDir cleanup can be avoided when https://github.com/junit-team/junit5/issues/2159 is implemented.

**Comment by gastaldi** [comment]
Doesn't seem to be an issue now. Closing
