### ISSUE TITLE
Pac4j extension for quarkus

### ISSUE THREAD

**Issue by ewsni** [quarkusio/quarkus#6995]
I use the library pac4j in my apps to secure endpoints.
Is it possible to obtain an extension for pac4j ? 
Otherwise could somebody give me an alternative to secure endpoints and manage SSO authentication already fonctionnal with quarkus ? 
I'm not interrested by full apps like keyclock.

**Comment by nimo23** [comment]
You could use JWT https://quarkus.io/guides/security-jwt.

**Comment by sberyozkin** [comment]
Or Quarkus OIDC: https://quarkus.io/guides/security-openid-connect
and if the opaque tokens, oauth2: https://quarkus.io/guides/security-oauth2

@ewsni I don't think we will go ahead with some alternative in this space. Let me close this issue soon, thanks
