### ISSUE TITLE
Update security and jwt extension to use elytron-web 2.0

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#701]
The current security and jwt extensions rely on integrating Elytron via the wildfly-elytron-embedded and use of the undertow IdentityManager interface. Discussions with Darran and David concluded that we should move forward with a proper integration based on a new 2.0 branch of the elytron-web project. This does a proper job of modularizing the Elytron codebase and integrates with undertow in a better manner.

TBD if this is should be the basis for the first public release.

**Comment by gsmet** [comment]
I think this is out of date with all the security work being done since then.
