### ISSUE TITLE
Optimize the use of TenantConfigResolver by making OidcTenantConfig a good map key

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#7013]
**Description**
Right now using `TenantConfigProvider` (which can create `OidcTenantConfig` on the fly) involves reconnecting to the OIDC server on every request (note a combination of `TenantResolver` + having a tenant specific config in `application.properties` is very effective).

**Implementation ideas**
Implement `OidcTenantConfig` `equals` and `hashCode` and use it as a map key in the concurrent map to retrieve the already calculated `OAuth2Auth` objects. It will also make it possible to avoid blocking for `TenantConfigProvider` for all but the very 1st request

CC @pedroigor

**Comment by pedroigor** [comment]
@sberyozkin I'm not sure if we reconnect to the OIDC server on each request. We cache the config right after creation.

This https://github.com/quarkusio/quarkus/pull/6970, also does not block for every request, but only when a tenant config does not exist.

Is that right ?

**Comment by sberyozkin** [comment]
Hi @pedroigor Sorry, I did not realize that even if `OidcTenantConfig` is returned from `TenantConfigResolver` then it is cached. Hmm...
 
The reason behind my assumption was that only it returns `OidcTenantConfig`, so where is a `tenantId`... I've just looked more carefully and see in this case it is `clientId` which is used as a `tenantId` in this case but it is not a muti-tenancy which is offered by `TenantResolver`+ `application.properties` :-). During the initial review I thought it was a sanity check for every `OidcTenantConfig` and missed it. 

What `TenantResolver` + `application.properties` offers is for the users to provide the sets of the OIDC configurations keyed by some tenant identifier which is supposed to match something in the incoming request. OIDC configurations may have the same `clientId`, it does not matter really.

`TenantConfigResolver` can't do it. One way to describe a problem is that since we cache `OidcTenantConfig` returned from `TenantConfigResolver` by `clientId` then it does not really matter what is in the `RoutingContext`. Or we can say, well, let then `TenantConfigResolver` keep its own map where there a unique tenant id obtained from `RoutingContext` which is used as a key to store `OidcTenantConfig` but then `DefaultTenantConfigResolver`, since it uses a `clientId` as a `tenantId` key for `OidcTenantConfig` returned from `TenantConfigResolver`, it will have `OidcTenantConfig` meant for different tenants overriding each other.

So whichever way one looks at it it is a bit of a problem :-)

I'm quite convinced now we have to fix this issue :-)

**Comment by sberyozkin** [comment]
Perhaps another alternative would be change `TenantConfigResolver` to accept `RoutingContext` and `Function` which would provide `OAuth2Auth` for `TenantConfigResolver` to return `TenantConfigContext` which would also have a `tenantId` property so that we can key it in `DefaultTenantConfigResolver`. But I'm not really sure...It seems we'd expose the users to too many internal/runtime details this way...

**Comment by pedroigor** [comment]
The reason for using a client id, at least initially, is that it can be chosen when creating a client or, in case the client is created through RFC-7591 (Dynamic Client Registration), the client id is issued by the AS. In fact, even some well-known providers issue the client, even though creating through their administration UIs.

**Comment by sberyozkin** [comment]
@pedroigor thanks,  this is good in itself for sure, but the the `clientId` is not unique across the multi-tenancy configuration space. I'm not sure this is what the tenant config resolvers should do, there will be `quarkus-oidc-client` in time to support these kind of things...

**Comment by pedroigor** [comment]
Yes, it is not. If you find that this model is limiting people, I'm OK to review and provide the necessary means to explicitly define the tenant id when resolving configs.

**Comment by sberyozkin** [comment]
Hi Pedro since we agree it is not unique, we don't need to wait for people starting reporting the problems because they will as soon as more than one tenancy configuration will have the same clientId. 
As I said, the only difference between `TenantResolver` and `TenantConfigResolver` is `static` vs `dynamic`, they should be consistent otherwise in the way the multi-tenancy is supported. 
Making sure `OidcTenantConfig` is unique is all what is needed.
I can take care of it

**Comment by sberyozkin** [comment]
@pedroigor hey, and it will be an internal fix really, we will be able to expand `TenantConfigResolver` if needed further but I just can't see how at the moment giving the dynamic nature of it, recall, during the initial PR I was trying to convince for it to extend `TenantResolver` so that it can return a `tenantId` while also returning a Map of tenantIds to OidcTenantConfig, but then I thought, if we'd go that way then it would be just a  duplication of `TenantResolver` + `application.properties` :-) and abandoned that idea.
So if we have `TenantResolver` only we have a `tenantId` as a key, if it is `TenantConfigResolver` then we don't because it is dynamic so it is an open ended producer of `OidcTenantConfig` and as such for it we would just have `OidcTenantConfig` as a key. Going forward we can do something smarter if needed :-)

**Comment by sberyozkin** [comment]
@pedroigor Hi, I've been thinking more about how to address this issue, and would like to revisit the idea of `TenantConfigResolver` being linked directly or indirectly with `TenantResolver` as opposed to going into this `equals`/`hashCode` process. 
Here are 3 options I can think of:
1. Indirect linking. If `TenantResolver` returns `tenantId` and no configuration with this `tenantId` is available in `application.properties` then, instead of immediately returning a default configuration, check if `TenantConfigResolver` is available and if yes and it returns `OidcTenantConfig` then use that `tenantId` as a key. This supports the case a bean implementing both `TenantResolver` and `TenantConfigResolver`.
2. `TenantConfigResolver` extends `TenantResolver`. We use the injected `TenantResolver` to get `tenantId`, and then repeat the process above if `TenantResolver` is an instance of `TenantConfigResolver`. 
3. `TenantConfigResolver` stays independent of `TenantResolver` and has its own `getTenantId(RoutingContext)` method and we document that this method will be invoked first and must return non-null for the `resolve(RoutingContext)` be invoked.

What do you think ? We are still in `1.3.0.Alpha1` so have time to do it now and avoid having `TenantResolver` and `TenantConfigResolver` having different keys

I'd go for 2 probably

CC @stuartwdouglas

**Comment by pedroigor** [comment]
@sberyozkin What if we just:

* Change `TenantConfigResolver` to return a `Map<String, TenantConfig>` or a specific type that wraps both the id and config

* Have a `tenantId` property in config. In fact, for the latter, maybe the best would be to provide a more user-friendly API for configuring a tenant. I think we discussed this already ...

**Comment by sberyozkin** [comment]
@pedroigor 

> Change TenantConfigResolver to return a Map<String, TenantConfig>

But where then the dynamism will be ? It will be the same as `TenantResolver` with the only difference is that `TenantResolver` looks up for `OidcTenantConfig` in application.properties while TenantConfigResolver - would create is itself somehow.

> Have a tenantId property in config

Not sure about it - this is a dynamic property.

**Comment by sberyozkin** [comment]
`TenantConfigResolver` has the right dynamism but we just need to make sure that the tenant id it uses to create `OidcTenantConfig` is visible to `DefaultTenantConfigResolver`. Any practical implementation would need to check `RoutingContext` to get some id. If it proves tricky then at least no collision will happen (hashCode, equals). IMHO something out of those 3 options should do if the dynamism is going to remain.

**Comment by sberyozkin** [comment]
Hi Pedro @pedroigor, so I've had a long (enough :-)) period of thinking about `TenantConfigResolver` and I'm coming to the conclusion we have a case of the over-engineering here which is only me to blame for :-), as I kept asking you during the multi-tenancy PR review, `Pedro, please add something more dynamic` :-). I.e, I propose to drop `TenantConfigResolver` for the moment and revisit the idea of the open-ended tenancy support when the users will actually ask for it.
`TenantResolver` + `application.properties` combination offers a great multi-tenancy support, the connections are created at the initialization time, and in reality, should cover the majority if not all the multi-tenancy cases. The requests are never blocking.

`TenantConfigResolver` requires a blocking and expensive OIDC connection initialization call at runtime per every new tenant id. This is also inconsistent with the general `quarkus-oidc` expectation that the application does not start if no OIDC server is available. Right now, as discussed above, `DefaultTenantConfigResolver` may lose the tenant specific `OidcTenantConfig` returned from `TenantConfigResolver` as it uses `clientId` as the key hence the search for some API compromise. Minor issue, a `runtime` package `OidcTenantConfig` is making its way into a public API with it as well.

I feel we'd be better off without it right now and it is the right time to make this move as we haven't documented it yet. Instead, when there will be a real demand for it, we can do good productive discussion and come with something which works well.

@pedroigor What do you think ? If you agree I'll just drop it with my PR I'm working upon right now, with an extra plus your doc PR will be slimmer too :-)

Np if you now prefer to keep it. Let me know what you think please

**Comment by sberyozkin** [comment]
Or we just do what have discussed earlier and is something you've touched upon here:
```
interface TenantConfigResolver extends TenantResolver {
    Map<String, OidcTenantConfig> getTenantConfigurations()(
}
```
and we say, to avoid any ambiguities, you either use `TenantResolver` + `applicationProperties` combination or `TenantConfigResolver` but not both. The reason you may want to use `TenantConfigResolver` is when putting the OIDC config in the `application.properties` is not working for you.

But even here a dev mode capability of modifying the tenant configurations in the `application.properties` will not be available and again, lets wait may be for the users to say that `application.properties` is not enough...

**Comment by pedroigor** [comment]
@sberyozkin Now that we have it I think we should keep it :) As it stands today, I think the functionality is quite functional and also useful.

I don't see a reason for having `TenantConfigResolver` extending `TenantResolver`. Note that when resolving a tenant config, the implementation can even have its own cache of tenant configurations.

The tenant id issue should be quite easy to solve by just adding a runtime config property that allows users to set it when creating the tenant config. But I also think that for now, we should just continue with the client id and wait for feedback (for tenants within a same domain, it should not be a problem). 

The implementation is safe enough to:

* Avoid calling the config resolver multiple times within a same request, but during creation
* Allow users to have a default (application.properties) tenant while supporting other tenants at runtime
* Cache of tenant configs so that we are able to resolve the proper tenant right away

The only thing I'm not happy about is exposing the extension's config types to the app. But that is something we can improve anytime.

**Comment by sberyozkin** [comment]
Hey @pedroigor That is fine, lets keep it :), But IMHO we should fix the `clientId` issue then, I'm just not happy with it, let me reiterate why:
- It is simply not consistent for `DefaultTenantConfigResolver` to have the statically resolved `OidcTenantConfig` be keyed in its map cache using a proper tenant id, while dynamically created `OidcTenantConfig` are saved in the same map using `clientId`
- It should just work, i.e. IMHO we should not assume what `TenantConfigResolver` will do, if they it will want the multiple tenants with the same clientId or not, we don;t know and don't need to, but `DefaultTenantConfigResolver` can not afford overwriting `TenantConfigContext` :-)

So lets go back to the drawing board please. How do we fix it. Why are not keen on the idea of `TenantConfigResolver` extending `TenantId` ? We need to know a tenantId of the `OidcTenantConfig`, it must be obtained from `RoutingContext`. I actually don;t understand what you mean about having a configuration `tenantId` property.

**Comment by pedroigor** [comment]
What I mean is this:

```
public OidcTenantConfig resolve(RoutingContext context) {
    OidcTenantConfig config = new OidcTenantConfig();

    config.setTenantId("my-unique-tenant-id");
    config.setAuthServerUrl(getIssuerUrl() + "/realms/quarkus-d");
    // more ...
}
```
Now we use the `tenantId` as a key instead of client id.

That is why I don't think we need `TenantConfigResolver` extending the other.

**Comment by sberyozkin** [comment]
@pedroigor This looks promising, I'm feeling better already :-).
