### ISSUE TITLE
ReflectiveClassBuildItem(..., Class<?>... className) should be classProxy friendly

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#7034]
This code doesn't actually open the class "foo.Bar" up for reflection in the native image:
```
Class<?> c = recorderContext.classProxy("foo.Bar");
...
reflectiveClass.produce(new ReflectiveClassBuildItem(true, false, false, c);
```

A) Proposal A
The problem is that this method in ReflectiveClassBuildItem doesn't deal with class proxies:
```
    public ReflectiveClassBuildItem(boolean constructors, boolean methods, boolean fields, Class<?>... className) {...}
```
B) Proposal B
The alternative problem is that classProxy.getName() doesn't return the original class'sname.

**Comment by gsmet** [comment]
I'm not really sure that's something we want to fix. It is really something that shouldn't be done.

You should use the recorder proxy only to push classes to the recorder.

**Comment by geoand** [comment]
Can you explain your use case? I am pretty sure there is some better way to achieve your end result
