### ISSUE TITLE
"method is not visible from class loader" for created proxy classes.

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#7043]
Resteasy has a lot of test classes that creates a proxy class from an interface
definition.  The quarkus environment reports, "method is not visible from class loader".
and the test fails.

[ERROR] test on test(org.jboss.resteasy.test.core.basic.PartialAnnotationResourceTest)(org.jboss.resteasy.test.core.basic.PartialAnnotationResourceTest)  Time elapsed: 0.019 s  <<< FAILURE!
java.lang.IllegalArgumentException: org.jboss.resteasy.test.core.basic.resource.PartialAnnotationResource referenced from a method is not visible from class loader
	at org.jboss.resteasy.test.core.basic.PartialAnnotationResourceTest.test(PartialAnnotationResourceTest.java:61)

**Expected behavior**
The classLoader should be able to resolve this.

**To Reproduce**
  This project is provided to show the issue.  https://github.com/rsearls/quarkus-proxy-classes.git 
  Follow the directions in the README file.

**Environment (please complete the following information):**
    jdk 11.0.2
    mvn 3.6.0
    quarkus 1.2.0.Final

Project contains stackTrace of error.

**Comment by geoand** [comment]
I don't think it will make a difference, but can you please try against Quarkus 1.3.0.Final?

**Comment by rsearls** [comment]
I don't have access to 1.3.0.Final.
I have https://github.com/quarkusio/quarkus.git
but this does not appear to be the right one for building 1.3.0.Final.

**Comment by geoand** [comment]
Sorry, my bad. I meant 1.3.0.Alpha1

**Comment by rsearls** [comment]
Yes 1.3.0.Alpha1 resolves this issue

**Comment by geoand** [comment]
Excellent, an easy win the. 🤘
