### ISSUE TITLE
Test application.properties are ignored in 1.3.0.Alpha1

### ISSUE THREAD

**Issue by pschyma** [quarkusio/quarkus#7065]
**Describe the bug**
Only main `application.properties` are applied in unit tests.

**Expected behavior**
Test `application.properties` are applied.

**Actual behavior**
Only main `application.properties` are applied in unit tests.

**To Reproduce**
1. Create a simple Quarkus project
2. Override some configuration, e.g. `quarkus.http.root-path`
3. Test for test configuration

**Configuration**
main:
```properties
quarkus.http.root-path=/api
```
test:
```
quarkus.http.root-path=/test-api
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux voyager 5.5.2-arch2-2 #1 SMP PREEMPT Wed, 05 Feb 2020 22:01:13 +0000 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.0.Alpha1

**Additional context**
This works as expected in 1.2.0.Final.

Another observation: `@QuarkusTestResource` starts a H2 database for tests, but Hibernate tries to connect to Postgres from main configuration.

**Comment by radcortez** [comment]
I've just experienced the same when I've updated one of my apps to 1.3.0.Alpha1.

The issue here is that there are multiple `application.properties` in the classpath. The one in `main` and the one in `test`. Only one gets loaded, and it will be the first one found by the classloader.

Before 1.3.0.Alpha1, the test classpath url was found first, so `application.properties` from `test` was loaded first. In 1.3.0.Alpha1, the `main` classpath is first, so it uses the main `application.properties` file.

**Comment by radcortez** [comment]
Not sure if this was the intended behaviour from the start. Thinking about this, one annoying thing, is that `application.properties` test was used and the one in main was ignored. 

I'm wondering if it will be more interesting to actually read from both, and have `application.properties` from `test` to have a higher priority and just override configs from `main`.

**Comment by radcortez** [comment]
Alternative, we can always rely on profiles and have everything in one file.

**Comment by gsmet** [comment]
It's probably already solved in master: https://github.com/quarkusio/quarkus/pull/7052 .

**Comment by radcortez** [comment]
Cool. Thanks. I'll give it a try.

**Comment by radcortez** [comment]
@pschyma I can confirm that current master fixes this issue. I've just tried it and works as before.
