### ISSUE TITLE
ArC - introduce a new build item that represents a scope of a custom context registered by an extension

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#7076]
Some extension register an annotation transformer that adds a scope annotation to a class that is annotated with no scope annotation but meets some specific requirements, e.g. a class with a `@Scheduled` business methods is `@Singleton` by default: https://github.com/quarkusio/quarkus/blob/master/extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java#L106

However, when an annotation transformer is registered the final set of contexts is not known. An extension that registers a `ContextRegistrar` should also produce a build item that holds a name of the scope that will be used by the custom context, so that annotation transformers would be able to skip classes annotated with custom scope annotations.

The name could be `CustomScopeBuildItem`.

**Comment by manovotn** [comment]
Thanks for creating the issue, I'll take it :-)

**Comment by mkouba** [comment]
Actually, we could just enhance the existing `ContextRegistrarBuildItem` -> add the scope name...

**Comment by manovotn** [comment]
@mkouba Haha, I was literally just now looking at the code and thinking the same, only to come here and see your comment :D
