### ISSUE TITLE
Java 11 native builds are about 20% slower than Java8

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#7080]
**Describe the bug**
Java 11 native image builds process more classes, methods, and fields than Java 8 native builds.  The corresponding added heap and GC load is likely the cause of a ~20% slowdown for native image builds of small-sized projects (like quickstarts).

This is the downstream issue for oracle/graal#2129.  See that issue for the nitty gritty details.

We should look into what we can do to trim classes that we do not need from the build, like Truffle for example.  @jaikiran has done a really great analysis on the upstream issue.

**Comment by geoand** [comment]
I think this can be closes now, right?

**Comment by gsmet** [comment]
Yeah, reading the upstream issue, I think we can close this.
