### ISSUE TITLE
quarkus-arquillian having issue process app using CompletionStage

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#7087]
Deploying the app results is the following error message and none of
the test methods being called. I have traced the error into io.quarkus.arc.processor.BeanArchives
but have been unsuccessful determining root cause.

    [INFO] Running org.jboss.resteasy.test.asynch.AsyncInjectionTest
    18:07:48,889 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
    18:07:49,150 WARN  [io.qua.arc.pro.BeanArchives] Failed to index boolean: Stream closed
    18:07:49,153 WARN  [io.qua.arc.pro.BeanArchives] Failed to index char: Stream closed
    18:07:49,154 WARN  [io.qua.arc.pro.BeanArchives] Failed to index byte: Stream closed
    18:07:49,155 WARN  [io.qua.arc.pro.BeanArchives] Failed to index short: Stream closed
    18:07:49,157 WARN  [io.qua.arc.pro.BeanArchives] Failed to index int: Stream closed
    18:07:49,158 WARN  [io.qua.arc.pro.BeanArchives] Failed to index long: Stream closed
    18:07:49,159 WARN  [io.qua.arc.pro.BeanArchives] Failed to index float: Stream closed
    18:07:49,160 WARN  [io.qua.arc.pro.BeanArchives] Failed to index double: Stream closed
    [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.106 s - in org.jboss.resteasy.test.asynch.AsyncInjectionTest

Execution env.
    jdk 11.0.2
    mvn 3.6.0
    quarkus 1.2.0.Final

  This project is provided to demonstrate the issue
https://github.com/rsearls/quarkus-BeanArchives-index.git

  Follow the directions in the README file.

**Comment by gwenneg** [comment]
Hi @rsearls and thanks for reporting this.

You need to fix `-Dfile=FIX_THIS/lib/utils-arquillian-utils-4.5.0-SNAPSHOT.jar` (from your repository README.md) before we can use your reproducer, right?

**Comment by rsearls** [comment]
No.  If you install utils-arquillian-utils as directed there is no issue.  This archive only contains a utility used by the test to generate the test's url. 
Once you install this archive compile the project,
  mvn clean test -DskipTests=true
Then run the test.
mvn test
You will see the issue.

**Comment by gwenneg** [comment]
I'm sorry but I don't see the `utils-arquillian-utils.jar` file anywhere. Am i missing something?

**Comment by rsearls** [comment]
Try fetching the project again.   It appears lib dir was ignored by .gitignore.
when I added stuff.
I've fixed this.  You should have access to the dir and archive now.

**Comment by gwenneg** [comment]
Thanks for fixing the file issue!

I tested the project locally and confirmed both the warn messages and the fact that none of the test methods are called. I'm pretty sure there's no link between these two facts.

Actually, the warn messages in `BeanArchives` happen because we didn't expect in `ResteasyServerCommonProcessor.registerContextProxyDefinitions(...)` that primitive types would be annotated with `javax.ws.rs.core.Context`. This method produces build items that are only used for the native image generation, that's why I think both issues are unrelated. We can improve things a bit there by ignoring primitive types and therefore suppress the warn messages.

@rsearls: Does it really make sense to annotate primitives with `@Context` btw?

I'm wondering if we shouldn't put a warn message in `ResteasyServerCommonProcessor` which would explicitely state that `@Context` should not be used on primitives.

I'll try to understand tomorrow why the test methods are not called.

**Comment by rsearls** [comment]
> @rsearls: Does it really make sense to annotate primitives with @Context btw?

This is what resteasy supports currently.  It is my understanding you guys want quarkus to also support current usages.

**Comment by gwenneg** [comment]
Ok, I just wanted to make sure since I'm not a RestEasy expert :)

**Comment by gwenneg** [comment]
I guess you found in #7124 the reason why the test methods weren't called here.

Here's what I see with a breakpoint at `ObserverImpl:89`:
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type org.jboss.resteasy.test.asynch.resource.AsyncInjectionContext and qualifiers [@Default]
	- java member: org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource#<init>()
	- declared on CLASS bean [types=[org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource]
[2] Unsatisfied dependency for type java.util.concurrent.CompletionStage<org.jboss.resteasy.test.asynch.resource.AsyncInjectionContext> and qualifiers [@Default]
	- java member: org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource#<init>()
	- declared on CLASS bean [types=[org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:889)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:232)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:130)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:290)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.jboss.resteasy.test.asynch.resource.AsyncInjectionContext and qualifiers [@Default]
	- java member: org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource#<init>()
	- declared on CLASS bean [types=[org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:420)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:224)
		... 14 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.util.concurrent.CompletionStage<org.jboss.resteasy.test.asynch.resource.AsyncInjectionContext> and qualifiers [@Default]
	- java member: org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource#<init>()
	- declared on CLASS bean [types=[org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.jboss.resteasy.test.asynch.resource.AsyncInjectionResource]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:420)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:224)
		... 14 more

```

**Comment by rsearls** [comment]
outdated
