### ISSUE TITLE
amqp-host is not working in reactive messaging

### ISSUE THREAD

**Issue by hguerrero** [quarkusio/quarkus#7088]
**Describe the bug**
(Describe the problem clearly and concisely.)
Documentation states that the property `amqp-host` should be use however the one available is actually `amqp-server` as initially described in #3806
**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Documentation and property should be the same either `-host` or `-server
**Actual behavior**
(Describe the actual behavior clearly and concisely.)
Only `amqp-server` works

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 

**Additional context**
(Add any other context about the problem here.)

**Comment by cescoffier** [comment]
Documentation updated (https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/amqp/amqp.html#amqp-inbound)
