### ISSUE TITLE
Deprecate QuarkusNative

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#7104]
As discussed in #7051 and in [Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/configure.20builderImage.20via.20gradle/near/187596485), the `QuarkusNative` task from our Gradle plugin should be deprecated and kept around for backwards compatibility just like `NativeImageMojo` from the Maven plugin.

The `gradle-tooling` guide will have to be updated, but there's also some work to do in the Gradle plugin since the `QuarkusTestNative` task currently depends on the soon-to-be deprecated `QuarkusNative` task.

**Comment by gwenneg** [comment]
I haven't started anything related to this issue and I'm too busy on other subjects to take care of it for now, so I'm removing my assignment. Feel free to deprecate `QuarkusNative` if you want!

**Comment by glefloch** [comment]
@gwenneg, I would like to work on this.

**Comment by gwenneg** [comment]
Thanks @glefloch, this issue is now yours :)

**Comment by glefloch** [comment]
Thanks @gwenneg. In order to make sure I understand the problem and provide a correct fix, can we agree that it consists of:

- marking `QuarkusNative` task `@Deprecated`
- updating documentation to replace `buildNative` references by `quarkusBuild -P quarkus.package.type=native` 
- updating `testNative` task such that it doesn't depend on `buildNative` task

Am I missing something?

**Comment by gwenneg** [comment]
If I remember correctly, the documentation part will be a bit more complex than a simple replacement. You're right about everything else :)

**Comment by gsmet** [comment]
@gastaldi this looks like it would need a note here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.4 .

Could you take care of it? Thanks!

**Comment by gastaldi** [comment]
@gsmet there you go: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.4#task-buildnative-is-now-deprecated

**Comment by andreas-eberle** [comment]
What was the reasoning behind the deprecation of the buildNative task? If I have a gradle project with many microservices, I was able to use the buildNative task to configure common properties for all of them in the parent gradle file (e.g. which graalvm version to use). Now I'll have to it for every module/every microservice. Or am I missing something?

**Comment by dzwicker** [comment]
Can you please provide the reason for removing this task? Set a property at build time is some kind freaky and relay old school. We can also provide a build.properties file. A dedicated Task for such an important distinction is a better way I believe.

**Comment by glefloch** [comment]
We've updated the `quarkusBuild` task to add a `nativeArgs` property, such as: https://quarkus.io/guides/gradle-tooling#building-a-native-executable.

**Comment by grueneerle** [comment]
Right, an overrides (resolutions) entry can fix a possible version conflict, security issue, etc. temporarily. In our (@marvinjaworski) case switching `pdfjs-dist` to `4.2.67` would remove the npm audit problem, but react-pdf seems to have an incomatibility:
![image](https://github.com/quarkusio/quarkus/assets/19550091/b27c67ec-f443-427d-b78d-8d0970db213b)
We are using `react-pdf` version `8.0.2`
