### ISSUE TITLE
Panache support for Projections

### ISSUE THREAD

**Issue by bobbyphilip** [quarkusio/quarkus#7121]
**Description**
I am not really sure if my terminology is right, so I will describe the feature.
Assume I am building an API to return fruits

```
public class Fruit {

    public String name;
    public String description;
    public String colour;
    public String season;   
}   
```
I can use `@JsonbTransient`, to mark fields I dont need to be returned in the API.
However there are cases where I want to return different fields depending on the API called.
For example when I list all the fruits, I need the name and colour. And later on when I want to see more details about a fruit, I want to get all the available fields

Can Panache support this kind of API level determination of the Object to be returned

**Comment by loicmathieu** [comment]
@bobbyphilip projection is available for MongoDB with Panache, see https://quarkus.io/guides/mongodb-panache#query-projection but not yet for Hibernate with Panache.

There is an open issue for adding projection to Hibernate with Panache, #6261 if it's what you are looking for please close your issue and add comment (or at least vote for it) on #6261.
