### ISSUE TITLE
Classloader issue with CompletableFuture

### ISSUE THREAD

**Issue by aaronanderson** [quarkusio/quarkus#7123]
**Describe the bug**
This issue affects 1.3.0.Alpha1 and is probably related to the recent classloader changes.

I am using the Jakarta EE SAAJ implementation in my application which relies on the Java Service Provider Interface mechanism to instantiate the service's implementation. This works fine when invoked from the a JAX-RS method but it throws provider not found exception when run inside a ComputableFuture lambda.

The same code and test case works fine with Quarkus 1.2.0.Final

My [reproducer is located here](https://github.com/aaronanderson/quarkus-future-issue)

**Expected behavior**
The classpath should be the same inside or outside of a ComputableFuture

**Actual behavior**
Quarkus 1.3.0.Alpha1 throws this error from the reproducer:

```
Caused by: javax.xml.soap.SOAPException: Unable to create SOAP connection factory: Provider com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnectionFactory not found
	at javax.xml.soap.SOAPConnectionFactory.newInstance(SOAPConnectionFactory.java:58)
	at org.acme.quickstart.TestRS.lambda$test$0(TestRS.java:32)
	... 7 more


```

**To Reproduce**
Build this [reproducer](https://github.com/aaronanderson/quarkus-future-issue)

**Environment (please complete the following information):**
 - Quarkus 1.3.0.Alpha1
- OpenJDK 13.02

**Additional context**
(Add any other context about the problem here.)

**Comment by stuartwdouglas** [comment]
I am not sure what we can really do here. The CompletableFuture *async methods that do not take an executor are really problematic, as they run in a common pool and there is no obvious way to control the TCCL. 

I will have a look and see if there are some hacks I can do here.

**Comment by aaronanderson** [comment]
Makes sense. 

I dug around and discovered the quarkus-smallrye-context-propagation extension. I then updated reproducer and added the extension to the pom.xml, added an `@Inject 
 ManagedExecutor exec;` to the jax-rs resource, and then referenced the executor i.e.  CompletableFuture.runAsync(() -> {... }, exec);` After applying these changes the reproducer ran fine with 1.3.0.Alpha1.

I suppose if someone was using a third party library that used the default JVM fork join threadpool they would be out of luck but I am fine with the workaround mentioned above. However I would prefer not to include the context propagation extension since I don't need that feature and just need the job executor classloader set properly. 

Is there way to directly inject the core executor service via CDI as part of the Quarkus core server?

**Comment by stuartwdouglas** [comment]
We do have an internal executor, but it is not actually injectable yet. If you create your own executor managed by CDI this will also work, as the executor will pick up the TCCL of the current deployment.

**Comment by aaronanderson** [comment]
Perhaps a SystemPropertyBuildItem could set the java.util.concurrent.ForkJoinPool.common.threadFactory system property at startup to a ForkJoinPool.ForkJoinWorkerThreadFactory implementation that leverages the new classloading framework?

**Comment by aaronanderson** [comment]
I played around a bit with the reproducer and when I added this class:

```
package org.acme.quickstart;

import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.ForkJoinWorkerThread;
import java.util.concurrent.ForkJoinPool.ForkJoinWorkerThreadFactory;

public final class QuarkusForkJoinWorkerThreadFactory implements ForkJoinWorkerThreadFactory {

	public final ForkJoinWorkerThread newThread(ForkJoinPool pool) {
		return new QuarkusForkJoinWorkerThread(pool);
	}

	public class QuarkusForkJoinWorkerThread extends ForkJoinWorkerThread {

		QuarkusForkJoinWorkerThread(ForkJoinPool pool) {
			super(pool);			
			//JDK-8172726 issue fixed first access CL reference but it is desired behavior for Quarkus
			super.setContextClassLoader(Thread.currentThread().getContextClassLoader());
		}

	}
}
```

and built the project with this command: 
`mvn clean install -Djava.util.concurrent.ForkJoinPool.common.threadFactory=org.acme.quickstart.QuarkusForkJoinWorkerThreadFactory`

The test passed. 

This issue may have a larger impact on my application than I first realized since I do not have many ComputableFuture usages in my codebase but I do have numerous stream().parallel() invocations.

**Comment by aaronanderson** [comment]
I wrote a simple Quarkus extension that uses a deployment SystemPropertyBuildItem as mentioned above and this worked fine when running the application using the standalone -runner.jar file but it did not work in Quarkus dev mode. It seems Quarkus dev mode uses a stream().parallel() early in the startup before the application processed initializing the default factory before the system property is initialized. Probably Quarkus needs to be updated with a delegating ForkJoinWorkerThreadFactory implementation at the very beginning of startup.

Since this is a critical path issue for me I came up with the below temporary workaround that works in JDK 13. This probably will not be supported forever though based on this JDK bug report: https://bugs.openjdk.java.net/browse/JDK-8217225



```
import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.ForkJoinPool.ForkJoinWorkerThreadFactory;
import java.util.concurrent.ForkJoinWorkerThread;

public final class QuarkusForkJoinWorkerThreadFactory implements ForkJoinWorkerThreadFactory {

	public final ForkJoinWorkerThread newThread(ForkJoinPool pool) {
		return new QuarkusForkJoinWorkerThread(pool);
	}

	public class QuarkusForkJoinWorkerThread extends ForkJoinWorkerThread {

		QuarkusForkJoinWorkerThread(ForkJoinPool pool) {
			super(pool);
			//JDK-8172726 issue fixed first access CL reference but it is desired behavior for Quarkus
			super.setContextClassLoader(Thread.currentThread().getContextClassLoader());
		}

	}

	public static void setup() {
		try {
			Field common = ForkJoinPool.class.getDeclaredField("common");
			common.setAccessible(true);
			var lookup = MethodHandles.privateLookupIn(Field.class, MethodHandles.lookup());
			VarHandle MODIFIERS = lookup.findVarHandle(Field.class, "modifiers", int.class);
			int mods = common.getModifiers();
			MODIFIERS.set(common, mods & ~Modifier.FINAL);

			ForkJoinPool commonForkJoinPool = (ForkJoinPool) common.get(null);
			commonForkJoinPool.shutdownNow();
			common.set(null, new ForkJoinPool(Runtime.getRuntime().availableProcessors(), new QuarkusForkJoinWorkerThreadFactory(), null, false));
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	
}
```

**Comment by stuartwdouglas** [comment]
I think using -Djava.util.concurrent.ForkJoinPool.common.parallelism=0 will work for dev/test mode, as a new thread will be created each time. Production mode has a flat class loader so this will not affect production apps.

**Comment by stuartwdouglas** [comment]
This should be resolved now, I figured out a hack to set the TCCL of the fork join pool

**Comment by aaronanderson** [comment]
Today I discovered my workaround no longer works with Quarkus 1.3 and JDK 16. After removing it dev mode worked fine but my production app encountered classpath issues as before. 

Fortunately I came across issue #9397 which had an easy solution for creating a custom ForkJoinPool that references the Quarkus classpath. After that I passed the custom pool to all of my CompletableFuture.runAsync() calls since ForkJoinPool implements the Executor interface. I also was able to wrap all of my top level parallelStreams with forkJoinPool.submit(() -> someCollection.parallelStream()...).join(). All of the recursive parallelStreams seemed to pick up the custom pool and I didn't encounter any further classpath issues.

I am excited that this issue has been resolved without any further JDK internal workarounds.

**Comment by Ladicek** [comment]
Thanks for mentioning #9397 here -- I didn't know about this issue. The [hack](https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/runner/bootstrap/ForkJoinClassLoading.java) in Quarkus that sets TCCL of all threads in the common FJ pool is really brittle, because per the FJ pool [javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ForkJoinPool.html), threads in a FJ pool can be disposed and recreated. The TCCL of the newly created threads will, once again, be the system classloader.

I also didn't know about `java.util.concurrent.ForkJoinPool.common.threadFactory` -- that sounds like a much more reliable solution. I'm sure @stuartwdouglas had a reason why not to use it (maybe because that class is looked up from the system CL?), but it's super easy to accidentally use the common FJ pool (e.g. when using parallel streams), and that leads to non-deterministic failures. In my opinion, it would be much better to not have the hack at all, so that issues manifest early and deterministically, but that would be too much of a breaking change I guess.
