### ISSUE TITLE
Create a Quarkus registry

### ISSUE THREAD

**Issue by cealsair** [quarkusio/quarkus#7127]
### Description
Create a Quarkus registry to host third-party Quarkus extensions and third-party layered projects/products. This would be accompanied by documented processes on how to certify your extension and/or project/product with Quarkus. A first phase could be a process for self-certification. A future phase could consist of a more formal process.

### Analysis
What's in it for Quarkus?
This will encourage, foster and promote the adoption of Quarkus in the market

What's in it for a certified extension and/or a third-party layered project/product?
For an extension or layered project/product author, they get to list their extension in the official Quarkus registry, where developers come to discover information/documentation about existing extensions.

In addition, the registry can list information related to the level of certification for an extension (JVM mode, native mode, for example) and layered project/product ("powered by Quarkus" JVM mode, "powered by Quarkus" native mode, for example).

The technical analysis is TBD at this point. An idea would be to host a website with an Github project backend, where the registry information would be stored. The website can display information in the registry as well as describe the processes that an author needs to follow to add their extensions or layered projects/products to the registry. More brainstorming is needed here.

### Tasks
Here is a list of some potential high-level tasks:
1. Create GitHub project for Quarkus registry
2. Define a process for authors to follow to certify their extensions and layered projects/products
3. Create Test Certification Kit for extensions and layered project/products. As a first phase, these could be used by an author to self-certify. At a future phase, this process could be made more formal. These tests would be run against an extension to make sure it passes the desired level. Similarly, these tests would be run against a layered project/product to make sure it can be listed in the registry as "powered by Quarkus" with its respective level of certification.
4. Define a process for registry administrators to process submitted extensions and layered projects/products to merge them into the official Quarkus registry.
5. Maintain website and GitHub project

**Comment by maxandersen** [comment]
there is now a registry and we have ecosystem ci for verifications +quarkiverse hub for easy publishing.
