### ISSUE TITLE
Kotlin quarkusDev with gradle: javax.enterprise.inject.spi.DefinitionException: Normal scoped bean must not be final

### ISSUE THREAD

**Issue by zulq** [quarkusio/quarkus#7133]
Anytime I changed a bean I get this error. I have to restart to get the changes reflected. This is making developing with kotlin very slow as it requires full restart instead of hot reload.
Quarkus version: `1.2.0.Final`
Build Tool: `Gradle` generated from `code.quarkus.io`

**Comment by geoand** [comment]
Hello,

Which version of Quarkus are you using? Better yet, what does your `pom.xml` look like?

**Comment by zulq** [comment]
@geoand, see updates.

**Comment by geoand** [comment]
OK thanks.

We are working on this for Gradle, it's a known issue that it doesn't work currently

**Comment by zulq** [comment]
Considering this and other issues, do you advice switching to `maven` for now.

**Comment by geoand** [comment]
Maven support in Quarkus is more mature at the moment, but improvements to Gradle support are definitely coming

**Comment by zulq** [comment]
Seems this is more of a kotlin issue than gradle, similar to the following:
https://github.com/quarkusio/quarkus/issues/4414

**Comment by geoand** [comment]
It's a combination most likely

**Comment by zulq** [comment]
Not sure if this helps, but am suspecting the re-compile in dev mode is ignoring the `all-open` plugin. Is there anyway to configure that and check?

**Comment by geoand** [comment]
Yes, that is exactly what is going on. For Gradle there is no cde that glues things together (as opposed to Maven). That should change soon

**Comment by zulq** [comment]
Is there any ETA for this to be fixed? Really wanted to proceed with Kotlin but looks like the Java path is way smoother.

**Comment by geoand** [comment]
This has been fixed in `master` and will be part of the `1.4.0.Final` release (unless we also decide to backport the support).
