### ISSUE TITLE
Quarkus and Kafka

### ISSUE THREAD

**Issue by vankofalcon** [quarkusio/quarkus#7137]
Hi all, 
Is there a way to use Quarkus and the original Apache Kafka Clients artifact?
https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients
Is that going to work in native mode as well?

**Comment by cescoffier** [comment]
You need to use the quarkus-kafka-client artifact and then yes, it would work.
https://mvnrepository.com/artifact/io.quarkus/quarkus-kafka-client
