### ISSUE TITLE
Enhance JsonDeserialize reflective class registration

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#7139]
**Description**
The Jackson extension JacksonProcessor [iterates](https://github.com/quarkusio/quarkus/blob/master/extensions/jackson/deployment/src/main/java/io/quarkus/jackson/deployment/JacksonProcessor.java#L94-L116) over anything that is annotated with `JsonDeserialize`. It only creates `ReflectiveClassBuildItem` for the "using" annotation value, if the annotation target kind is a method or field.

It'd be good if it also considered classes. I was working on an extension to integrate the Camel Olingo component into the Camel Quarkus project, and found that Apache Olingo has classes like:

```java
@JsonDeserialize(using = ClientCsdlAction.ActionDeserializer.class)
class ClientCsdlAction extends CsdlAction implements Serializable {
...
} 
```

`ClientCsdlAction.ActionDeserializer` is never registered for reflection by the Jackson extension so I had to add some custom logic register such classes for reflection in my own extension.

**Comment by geoand** [comment]
Hi,

I would really like to see a reproducer for this. 
Once we have that and we can verify that registering for reflection fixes the problem, it will be trivial to add the support you requested.

**Comment by jamesnetherton** [comment]
To reproduce...

1. Clone my [fork](https://github.com/jamesnetherton/camel-quarkus) of camel-quarkus and switch to the `jackson-reproducer` branch.
2. Build the project: `mvn clean install -DskipTests`.
3. Run the Olingo4 extension native image build and observe the error. `mvn clean install -Dnative -pl :camel-quarkus-integration-test-olingo4`.
4. Uncomment the code in method `registerForReflection` within [Olingo4Producer](https://github.com/jamesnetherton/camel-quarkus/blob/jackson-reproducer/extensions/olingo4/deployment/src/main/java/org/apache/camel/quarkus/component/olingo4/deployment/Olingo4Processor.java#L52-L64). Rebuild the Olingo4 extension and then rerun `camel-quarkus-integration-test-olingo4` to see tests pass.

**Comment by geoand** [comment]
OK, thanks

**Comment by geoand** [comment]
#7157 should take care of the issue
