### ISSUE TITLE
Qute Template Extension with multiple parameters: Resulting in endless wait without error

### ISSUE THREAD

**Issue by mithandir** [quarkusio/quarkus#7144]
**Describe the bug**
I'm trying to create a Qute template extension with multiple parameters as described here: https://quarkus.io/guides/qute-reference#method-parameters

When using a method with a single parameter all is working well, when I add a second parameter in the template extension method, it results in an endless loop in the browser.

I tried setting the default logger to DEBUG, but nothing gets logged (see log under "actual behavior"). I also tried to set a breakpoint in the method that gets called, but the error seems to be happening before the breakpoint is reached.

**Expected behavior**
The template extension method is called, the result computed and displayed in my HTML template.

**Actual behavior**
Website loads endlesly in browser. Logfile shows this:

```
2020-02-11 17:00:18,069 INFO  [io.quarkus] (main) Quarkus 1.2.0.Final started in 2.818s. Listening on: http://0.0.0.0:8080
2020-02-11 17:00:18,070 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-02-11 17:00:18,070 INFO  [io.quarkus] (main) Installed features: [cdi, qute, resteasy, resteasy-jackson, resteasy-qute, spring-di, spring-web]
2020-02-11 17:00:30,242 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-1) -Dio.netty.recycler.maxCapacityPerThread: {}
2020-02-11 17:00:30,243 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-1) -Dio.netty.recycler.maxSharedCapacityFactor: {}
2020-02-11 17:00:30,243 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-1) -Dio.netty.recycler.linkCapacity: {}
2020-02-11 17:00:30,243 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-1) -Dio.netty.recycler.ratio: {}
2020-02-11 17:00:30,334 DEBUG [io.net.han.cod.com.ZlibCodecFactory] (vert.x-eventloop-thread-1) -Dio.netty.noJdkZlibDecoder: {}
2020-02-11 17:00:30,334 DEBUG [io.net.han.cod.com.ZlibCodecFactory] (vert.x-eventloop-thread-1) -Dio.netty.noJdkZlibEncoder: {}
2020-02-11 17:00:30,459 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002315: PathInfo: /
2020-02-11 17:00:31,172 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed
2020-02-11 17:00:31,175 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed.qute.html
2020-02-11 17:00:31,176 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed.qute.txt

<HERE WE HAVE AN ENDLESS WAIT, THEN IT SEEMS TO RESTART THE TASK?>

> Task :quarkusDev

<THEN RELOADING WEBSITE IN BROWSER>

2020-02-11 17:04:48,855 DEBUG [io.qua.resteasy] (vert.x-eventloop-thread-10) IO Exception : io.vertx.core.VertxException: Connection was closed

2020-02-11 17:04:48,892 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002315: PathInfo: /
2020-02-11 17:04:49,219 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed
2020-02-11 17:04:49,222 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed.qute.html
2020-02-11 17:04:49,224 DEBUG [io.qua.qut.run.EngineProducer] (executor-thread-1) Locate template for templates/feed.qute.txt

<AND ENDLESS WAIT AGAIN>
```

**Not working code example**

```
    // My @RestController method, where "downloadFolder" would be a simple String, and "feed" would be a @Component with several methods
    @GetMapping(value = "/", produces = MediaType.TEXT_HTML)
    public TemplateInstance showFeed() {
        return feed.data("feed", feedReader.readFeed())
                .data("downloadFolder", downloadFolder);
    }
```

```
@TemplateExtension
public class DownloadExistsUtil {
    public static boolean isAlreadyDownloaded(FeedItem feedItem, String downloadUrl, String downloadFolder) {
        return false;
    }
}
```

```
<table class="datagrid">
    {#for item in feed}
    <tr>
        <td>
            {#for url in item.urls}
                {#if item.isAlreadyDownloaded(url,downloadFolder) == false}
                    <p>
                        Bla
                    </p>
                {#else}
                    <p>
                        Blub
                    </p>
                {/if}
            {/for}
        </td>
    </tr>
    {/for}
</table>
```

**Working example with just 1 parameter**

```
    // No change from "not working example"
    // My @RestController method, where "downloadFolder" would be a simple String, and "feed" would be a @Component with several methods
    @GetMapping(value = "/", produces = MediaType.TEXT_HTML)
    public TemplateInstance showFeed() {
        return feed.data("feed", feedReader.readFeed())
                .data("downloadFolder", downloadFolder);
    }
```

```
@TemplateExtension
public class DownloadExistsUtil {
    public static boolean isAlreadyDownloaded(FeedItem feedItem, String downloadUrl) {
        return false;
    }
}
```

```
<table class="datagrid">
    {#for item in feed}
    <tr>
        <td>
            {#for url in item.urls}
                {#if item.isAlreadyDownloaded(url) == false}
                    <p>
                        Bla
                    </p>
                {#else}
                    <p>
                        Blub
                    </p>
                {/if}
            {/for}
        </td>
    </tr>
    {/for}
</table>
```

**Configuration**
- Nothing

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Microsoft Windows [Version 10.0.18363.592]
 - Output of `java -version`:

```
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```

 - GraalVM version (if different from Java): same as java
 - Quarkus version or git rev: 1.2.0.Final

**Comment by jaikiran** [comment]
Hello @mithandir, when that hang happens, can you get us around 2-3 thread dumps (using `jstack` against the quarkus process) with an interval of around 2 seconds between them?

**Comment by mithandir** [comment]
Sure, here are 4 dumps:

[1-before.log](https://github.com/quarkusio/quarkus/files/4192944/1-before.log)
[2-start.log](https://github.com/quarkusio/quarkus/files/4192945/2-start.log)
[3-start-plus2sec.log](https://github.com/quarkusio/quarkus/files/4192946/3-start-plus2sec.log)
[4-additional2sec.log](https://github.com/quarkusio/quarkus/files/4192947/4-additional2sec.log)

**Comment by mkouba** [comment]
@mithandir Could you pls try your app with 1.3.0.Alpha2? I know that we fixed few issues related to template extensions recently...

**Comment by gsmet** [comment]
I just released the staging repository of Alpha2 so it's not yet on Central. It should be there in ~1 hour.

**Comment by mithandir** [comment]
I will have a look later on.

**Comment by mkouba** [comment]
@mithandir Did you get a chance to test it?

**Comment by mithandir** [comment]
Yesterday Alpha2 wasn't available on maven central. Will be home in about an hour, then I can start checking the issue on Alpha2.

**Comment by mithandir** [comment]
I could test it now. Unfortunately, it isn't fixed in Alpha2.

**Comment by mkouba** [comment]
Do you get the same error? We do have a test for a template extension method that accepts multiple parameters: https://github.com/quarkusio/quarkus/blob/master/extensions/qute/deployment/src/test/java/io/quarkus/qute/deployment/TemplateExtensionMethodsTest.java#L95.

**Comment by gsmet** [comment]
@mithandir I think the easiest way to get this fixed would be for you to provide a small Maven project reproducing the issue. Thanks!

**Comment by mithandir** [comment]
Ok, no problem. Will create a small version of it tomorrow.

**Comment by mithandir** [comment]
Here you go: https://github.com/mithandir/quarkus-quote-template-bug

- Start it
- Call http://localhost:8080/working to get a version with 1 parameter that works
- Call http://localhost:8080/error to get a version with 2 parameter that doesn't work

**Comment by mkouba** [comment]
@mithandir Thanks a lot! I'll take a look later today.

**Comment by mkouba** [comment]
So there are actually two problems. 

(1) We have a bug in the "parent context resolution". Basically, when evaluating an expression a parent context should be used if we fail to resolve an expression in the [current context](https://quarkus.io/guides/qute-reference#current_context_object). Currently, we stop the resolution on the first level (in your case there is a nested loop -> 2 levels).

(2) The generated value resolver does not handle `ClassCastException` correctly.

I'm going to send a PR shortly. A workaround exists: use the `data` namespace, ie. `item.isAlreadyDownloaded(url,data:downloadFolder)`.

I've also noticed that you're using lombok in your app that does not seem to play well with quarkus development mode. TBH I'm not sure what's the current "support status" of lombok in quarkus. But I would expect troubles.

**Comment by hhhhthegamehhhh** [comment]
Is there any examples of how to use multi level (nested) loops? In the similar example given above, when I access the list inside list ( {#for url in item.urls} ), it throws, Loop section error in template - resolved to [io.quarkus.qute.Results$Result] which is not iterable. I am sure the object is the type of java.util.List but somehow it doesnt understand this.

One important note, this only happens in native build, If I do regular mvn clean quarkus:dev, it works fine but the same code, same template doesn't work when its built natively. Any suggestion?

**Comment by mkouba** [comment]
> Is there any examples of how to use multi level (nested) loops? In the similar example given above, when I access the list inside list ( {#for url in item.urls} ), it throws, Loop section error in template - resolved to [io.quarkus.qute.Results$Result] which is not iterable. I am sure the object is the type of java.util.List but somehow it doesnt understand this.
> 

Hm, what does your template look like? Nested loops should work just fine. It's possible that your app relies on the `ReflectionValueResolver` fallback which does not work in native unless the target class is registered for reflection, e.g. via `@io.quarkus.runtime.annotations.RegisterForReflection`.

A minimal reproducer would be really helpful.

**Comment by hhhhthegamehhhh** [comment]
Thank you very much for the response. Let me check the ReflectionValueResolver, that might be it, if it still doesn't work, I will provide sample project to reproduce the issue.
