### ISSUE TITLE
Classes with @ConstructorProperties for Reflection

### ISSUE THREAD

**Issue by JohT** [quarkusio/quarkus#7152]
**Description**
Classes with constructors annotated with `@java.beans.ConstructorProperties` should be registered for reflection without further configuration. 

Part of its JavaDoc:
> An annotation on a constructor that shows how the parameters of that constructor correspond to the constructed object's getter methods. [[1]](https://docs.oracle.com/javase/7/docs/api/java/beans/ConstructorProperties.html)

This annotation makes it possible to write immutable value objects that can be serialized with JSON-B [[2]](https://github.com/eclipse-ee4j/jsonb-api/issues/115#issue-398276491) and Jackson without any configuration and only depending on Java SE. This is helpful e.g. for api modules that shouldn't depend on any frameworks, but should be easy to integrate.

Since `@ConstructorProperties` is intended to be used with reflection, it makes IMO sense to register those classes. As a result, they could be used directly with `javax.ws.rs.core.Response`, `javax.json.bind.Jsonb`, `javax.ws.rs.sse.SseEventSink`,... without the need for `@RegisterForReflection` (quarkus-specific).

**Implementation ideas**
I'll provide a pull request as a proposal and for further discussion.

[[1] https://docs.oracle.com/javase/7/docs/api/java/beans/ConstructorProperties.html](https://docs.oracle.com/javase/7/docs/api/java/beans/ConstructorProperties.html)
[[2] https://github.com/eclipse-ee4j/jsonb-api/issues/115#issue-398276491](https://github.com/eclipse-ee4j/jsonb-api/issues/115#issue-398276491)

**Comment by stuartwdouglas** [comment]
Looks like this was merged
