### ISSUE TITLE
Vault add writeSecret in VaultKVSecretEngine

### ISSUE THREAD

**Issue by dcdh** [quarkusio/quarkus#7155]
**Description**
Currently `VaultKVSecretEngine` allow only to read a secret present in Vault.

An application may need to write secret.

**Implementation ideas**

In the interface `VaultKVSecretEngine` define a method to `writeSecret` like this one:

```java
writeSecret(String path, Map<String, String> secret);
```

In `VaultKvManager` the implementation could be:

```java
    @Override
    public void writeSecret(String path, Map<String, String> secret) {

        String clientToken = vaultAuthManager.getClientToken();
        String mount = serverConfig.kvSecretEngineMountPath;

        if (serverConfig.kvSecretEngineVersion == 1) {
            vaultClient.writeSecretV1(clientToken, mount, path, secret);
        } else {
            vaultClient.writeSecretV2(clientToken, mount, path, secret);
        }
    }
```

In the interface `VaultClient` we could add theses two methods to handle writing secret depending on secret version:

```java
void writeSecretV1(String token,
                              String secretEnginePath,
                              String path,
                              Map<String, String> secret);

void writeSecretV2(String token,
                              String secretEnginePath,
                              String path,
                              Map<String, String> secret);
```

In `OkHttpVaultClient` the implementation could be:

```java
@Override
public void writeSecretV1(String token,
                              String secretEnginePath,
                              String path,
                              Map<String, String> secret) {
        Request request = builder(secretEnginePath + "/" + path, token).post(requestBody(secret)).build();
        try (Response response = client.newCall(request).execute()) {
            if (response.code() != 204) {
                throwVaultException(response);
            }
        }
}

@Override
public void writeSecretV2(String token,
                              String secretEnginePath,
                              String path,
                              Map<String, String> secret) {
        Request request = builder(secretEnginePath + "/data/" + path, token).post(requestBody(secret)).build();
        try (Response response = client.newCall(request).execute()) {
            if (response.code() != 204) {
                throwVaultException(response);
            }
        }
}
```
**Remark**: We cannot use `exec` method as the response from Vault is an empty 204 and so the response cannot be deserialized using jackson to an Object.

**Comment by sberyozkin** [comment]
@dcdh Hi, is that something that may be required for the Vault administrative purposes ? So far Vault API has been built with the assumption that the secrets, etc that the application may need are added to Vault out of band, by the Vault administrator, as opposed to a service code servicing some client request.
Can you please explain the use case ?

Thanks

**Comment by dcdh** [comment]
@sberyozkin thanks for your reply. I was not aware about Vault assumption into Quarkus.

In my case it is not for an administrative purpose. Following GDPR I have to find a way to be compliant with it regarding personal data in my applications.
I am doing event sourcing (store each change on an aggregate as a domain event) and one of the golden rules is immutability. The store must not change or be altered in time. 

GDPR imply anonymization when the client leave the application. To avoid altering the event store I have defines theses steps for events lifecycle:
1. Each time a new client aggregate is created a new secret is associated to him;
1. For each event stored, personal data properties are encrypted using his secret in json event;
1. When the client aggregate is rebuilt from events the client secret is used to decrypt the encrypted properties and apply them into the aggregate;
1. When the client leave the application, only his secret is deleted. Like this, I do not alter the event store and encrypted data will remain and stay undecryptable.

So the secret must be defined dynamically depending on the client aggregate creation. I cannot create a pool of secrets as I do not know how many client I may have.

In this [sample](https://github.com/dcdh/event-data-spreader) the secret is stored in database and next it is spread into Kafka using Debezium to be consumed by other applications. I would like to use Vault to store dynamic secrets in a safer way.

**Comment by dcdh** [comment]
This [commit](https://github.com/dcdh/event-data-spreader/commit/488200a7b701fe0552286a45d5f00fa10d4f626d) is a dirty workaround.

**Comment by sberyozkin** [comment]
@dcdh Thanks. IMHO it makes sense to add this option. Vincent @vsevel is a lead of the Vault extension, but I'm not sure how available he is right now. Can you please consider creating a patch (label `area/vault`) based on your prototype above and CC to @vsevel and myself ?
Thanks

**Comment by vsevel** [comment]
hello. I think the need is legitimate. the "Implementation ideas" is looks correct.
I should be able to do it before the end of the month.
