### ISSUE TITLE
Techempower Benchmarks

### ISSUE THREAD

**Issue by matjazmav** [quarkusio/quarkus#7175]
Can you provide and reference the Techempower Benchmark so we can compare actual performance?

Is this the "official" [solution](https://www.techempower.com/benchmarks/#section=test&runid=48e28547-3d66-42e2-9a61-11b312e6e173&hw=ph&test=fortune&l=xan3hb-1r) (search for "quarkus")?

**Comment by geoand** [comment]
cc @johnaohara

**Comment by johnaohara** [comment]
@matjazmav We are preparing a PR for the Techempower benchmark. The value shown on that result page is derived from a contribution from the community that is based on a very old version, using inefficient, non-idomatic quarkus syntax.

**Comment by AceHack** [comment]
Where can we see a real techempower benchmark?

**Comment by yuhaibohotmail** [comment]
@AceHack https://tfb-status.techempower.com/

**Comment by frederikb** [comment]
Hi @johnaohara, am I correct in presuming that this PR remains in progress?

Are you going to add both GraalVM and JVM variants?

The [current implementation](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/quarkus/pom.xml) in their repo seems to be based on version 1.1.1 and [the results](https://www.techempower.com/benchmarks/#section=test&runid=600c3cb5-8e8c-4434-be90-9b2fcd6d4b06&hw=ph&test=fortune) are a bit disheartening. Do you expect to close the gap to Micronaut and some of the other "microservice/lightweight" Java stacks in the future? 

There are a lot of non-performance related reasons which make Quarkus an attractive option for client work which requires a JEE/Microprofile stack but having more "supersonic" speed would definitive help sell it.

I'm excited to see what else you have planned. Thanks!

**Comment by johnaohara** [comment]
Hi @frederikb . Yes, this PR is still in progress, work on it has stalled recently. Atm, we are planning a JVM variant.

The current implementation contains some "interesting" design choices which really do not reflect the runtime performance of Quarkus.

The reactive benchmark implementation will be built on top of vert-x web, so I am expecting throughput to be just slightly less than the vertx-web results

**Comment by johnaohara** [comment]
A PR has been opened for Quarkus on techempower: https://github.com/TechEmpower/FrameworkBenchmarks/pull/5728

**Comment by AceHack** [comment]
Can't wait to see these numbers.

**Comment by johnaohara** [comment]
The first techempower run that includes an idiomatic implementation has completed.

https://www.techempower.com/benchmarks/#section=test&runid=c5c1d265-ed92-4e9d-956d-6b8265839bc1&hw=ph&test=composite&l=zijbpb-f&a=2
