### ISSUE TITLE
Quarkus JWT Kotlin sample

### ISSUE THREAD

**Issue by zulq** [quarkusio/quarkus#7179]
Sorry if this the wrong place to create this. However I have created a `Kotlin` app with `JWT` authentication [Quarkus JWT kotlin sample](https://github.com/zulq/quarkus-jwt) .Some of the features are: 

1. Registering users with hashed password using `spring-security-crypto`.
2. Authenticate with username and password to get `JWT` token.
3. User Roles from DB as part of `JWT`.
4. Key generator

Would like you to add this to the guides under `JWT Security`. Also I think it will be useful in this google group discussion: [JHipster and Quarkus](https://groups.google.com/forum/#!topic/quarkus-dev/Dl1Awlevo8U)

**Comment by sberyozkin** [comment]
Hi @zulq, thanks,  it looks interesting.
FYI, [over here](https://github.com/zulq/quarkus-jwt/blob/master/src/main/kotlin/org/acme/config/TokenHelper.kt#L25), you can use java.util.Map to avoid dealing with Jose4J directly (few claims like `jit`, `iat`, `exp` will be added by default too), and you can use a no-arg `sign()` and drop all the code which loads the key since you have a property pointing to it.

It can make it to `quarkus-quickstarts`for a start, Guillaume, @gsmet, are you OK with it ?

**Comment by zulq** [comment]
@sberyozkin, thanks for the feedback, changes implemented as recommended.

**Comment by sberyozkin** [comment]
Hi @zulq Thanks. I think it is definitely a quarkus-quickstart issue. I'm not sure another doc is required but having one more JWT example would be useful, can you please close this issue, open a new Quickstart one with a PR and CC to @gsmet, myself ? And @geoand and @gastaldi who are Kotlin gurus :-)

**Comment by gastaldi** [comment]
I'm not really a Kotlin guru (in fact I don't use Kotlin at all :) ), but I'm happy to help when possible ;)

**Comment by geoand** [comment]
I'm not an expert, but I could try and take a look in a few days

**Comment by sberyozkin** [comment]
@gastaldi @geoand thanks, @zulq has already implemented the project, so just an extra PR check when it is open will be of help, cheers

**Comment by zulq** [comment]
@sberyozkin, closing as requested. Please bear with me sometime to create a PR or should it suffice only to create an issue on the quick-starts with a link to the project? More of a TFS guy lol.

**Comment by zulq** [comment]
@sberyozkin, getting permission error:
`15:32	Can't Create Pull Request
			Push failed:
			remote: Permission to quarkusio/quarkus-quickstarts.git denied to zulq.
			unable to access 'https://github.com/quarkusio/quarkus-quickstarts.git/': The requested URL returned error: 403`

**Comment by gastaldi** [comment]
@zulq you need to push to your fork and then create a PR

**Comment by gastaldi** [comment]
If you're using `hub` from https://hub.github.com, do: 

- `hub fork`
- `git push zulq your-branch`

**Comment by zulq** [comment]
Getting `push to origin/development was rejected`. On Windows using intellij. Do I need to `Force Push`?

**Comment by geoand** [comment]
> Getting `push to origin/development was rejected`. On Windows using intellij. Do I need to `Force Push`?

You need to your fork, not Quarkus. What does 

```
git remote -v
```

look like?

**Comment by zulq** [comment]
Here: `origin  https://github.com/zulq/quarkus-quickstarts.git (fetch)
origin  https://github.com/zulq/quarkus-quickstarts.git (push)`

**Comment by geoand** [comment]
That looks good, so you should be able to push to it. Depending on what the state of your branches are, you indeed might need to force push

**Comment by zulq** [comment]
Push successful and created a PR as well.
