### ISSUE TITLE
Observing the RxJava Vert.x `Router` does not work

### ISSUE THREAD

**Issue by Rupert-RR** [quarkusio/quarkus#7183]
**Describe the bug**

When adding a method to be called when the router is ready, in an `ApplicationScoped` class, the method is never called if we use the RxJava version of the router but is called appropriately if not. This is perhaps related to [this issue](https://github.com/quarkusio/quarkus/issues/1589).

**Expected behaviour**

The method annotated with `@Observes` should be called when the router is ready, whether it uses the standard `Router` class or the RxJava class.

**Actual behaviour**

The method is called only when it has the standard `Router` class as a parameter.

**To Reproduce**

- make a simple Hello World application, using the generator, including Vert.x, Vert.x Web, and Kotlin;
- remove the generated resource class ;
- add the class below:

```kotlin
package org.acme.myapp

import io.quarkus.runtime.ShutdownEvent
import io.quarkus.runtime.StartupEvent
import io.vertx.reactivex.ext.web.Router
import io.vertx.reactivex.ext.web.RoutingContext
import javax.enterprise.context.ApplicationScoped
import javax.enterprise.event.Observes

@ApplicationScoped
class ApplicationLifeCycleHandler() {
	fun onStart(
		@Observes event: StartupEvent
	) {
		println("Application started")
	}

	fun onNonRxRouter(
		@Observes router: io.vertx.ext.web.Router
	) {
		println("Router ready")

		router.get("/hello")
			.handler({ context: io.vertx.ext.web.RoutingContext ->
				context.response().end("Hi there!")
			})
	}

	fun onRouter(
		@Observes router: Router
	) {
		println("Rx Router ready")
		router.get("/hello")
			.handler({ context: RoutingContext ->
				context.response().end("Hi there Rx!")
			})
	}

	fun onStop(
		@Observes event: ShutdownEvent
	) {
		println("Application finished")
	}
}
```

- build and run;
- "_Router ready_" will be logged but not the Rx message.

**Environment:**

Output of uname -a or ver: `Darwin Devops.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`
Output of java -version: `openjdk64-11.0.5`
Quarkus version or git rev: `1.2.0.Final`

**Comment by cescoffier** [comment]
I don't believe we expose the RX Router. Any specific feature you would like to use from this API?

**Comment by Rupert-RR** [comment]
I was following the [Reactive Routes guide](https://quarkus.io/guides/reactive-routes) and wish to [register my routes directly on the Vert.x router](https://quarkus.io/guides/reactive-routes#using-the-vert-x-web-router), but using RxJava syntax rather than `AsyncResult`.
Is there any reason not to expose the Rx router?

As another point (which may merit a separate issue), I notice that using Vert.x classes to perform custom OIDC flows results in a crash at the Quarkus HTTP security layer because it tries to cast the generated `User` object to a `QuarkusHttpUser` which obviously fails because it is not a class used by Vert.x. Is this an inevitable problem of bypassing Quarkus' own security layer?

**Comment by cescoffier** [comment]
@Rupert-RR The Router RX API does not differ much from the _bare_ API. If you look at https://vertx.io/docs/apidocs/io/vertx/reactivex/ext/web/Router.html you will see that it does not add RX type. Do I miss something?

About the second issue, please open a separate issue. The maintainer of the extension will likely chime in.

**Comment by Rupert-RR** [comment]
@cescoffier yes, it looks like you are right. Sorry — I was expecting more Rx methods to handle the asynchronous parts of it but it looks like that is not available. Thanks for looking.
