### ISSUE TITLE
PanacheRepository injected methods cannot be made transactional

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#7188]
**Describe the bug**
If a class implementing the PanacheRepository is marked as `@Transactional`, methods injected by Quarkus are not transactional.

**Expected behavior**
All public methods should be transactional. When calling e.g. persist, a transaction should be created and operation should succeed.

**Actual behavior**
App throws `javax.persistence.TransactionRequiredException: Transaction is not active, consider adding @Transactional to your method to automatically activate one.`

**To Reproduce**
1. Create a class implementing PanacheRepository and mark it as `@Transactional`
2. Create test class, with non-transactional test method and injected repository
3. Call `persist` from a non-transactional method.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10
 - Output of `java -version`: 1.8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.0.Alpha1

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
Yeah, I think it's probably the same issue of the methods being injected too late and not being taken into account by the interception layer.

/cc @mkouba

**Comment by agoncal** [comment]
Any update on this one ? I'm using 1.3.1.Final and I have the same issue (impossible to persist an entity with the repository because of transaction not being activated)

**Comment by mkouba** [comment]
@gsmet  Yes, as described [here](https://github.com/quarkusio/quarkus/issues/7102#issuecomment-586945242) the repository class is transformed and the methods are generated and so the CDI container does not see the methods at all.

**Comment by agoncal** [comment]
(cc @FroMage that's the issue I was mentioning during the podcast)

**Comment by FroMage** [comment]
@mkouba so, why do we run ArC before the Panache enhancers? How does ArC load the bytecode to see which methods need interceptors? ClassLoader, Jandex, or using an ASM transformer?

**Comment by mkouba** [comment]
> so, why do we run ArC before the Panache enhancers?

@FroMage I have no idea when Panache enhancers are executed. By "run" you mean the analysis of the bean classes?

> How does ArC load the bytecode to see which methods need interceptors?

We only consider methods from the Jandex.

**Comment by FroMage** [comment]
> We only consider methods from the Jandex.

OK, so even if we ran ArC after we're done transforming, it would not see the new methods unless we reindexed them.

Is that the best thing to do, do you think @stuartwdouglas ?

**Comment by stuartwdouglas** [comment]
Isn't the underlying issue here just that ArC is not intercepting default methods? https://github.com/quarkusio/quarkus/pull/9472

**Comment by mkouba** [comment]
@stuartwdouglas Nope, it's not about the default methods but about "synthetic" methods added during transformation...

**Comment by FroMage** [comment]
OK, that's a very good point, because in this case all methods are defined on the superinterface. We're not introducing _new_ methods, we're just overriding them.

But perhaps what @mkouba is saying is that even if the class itself is marked as `@Transactional` it does not apply to interface methods it inherits IFF the user hasn't overriden them? The fact that we override them later via a transformer makes it too late for ArC to consider them overridden.

**Comment by mkouba** [comment]
> We're not introducing new methods, we're just overriding them.

Aha, that's a completely different situation then. I'm sorry for confusion. In that case, Stuart's PR should work fine.

**Comment by FroMage** [comment]
OK great. Note that I've filed https://github.com/quarkusio/quarkus/issues/9487 for interception of static methods.
