### ISSUE TITLE
Native JAX-RS Lambda example fails:  invalid response

### ISSUE THREAD

**Issue by TheGeekPharaoh** [quarkusio/quarkus#7191]
**Describe the bug**
Running the Resteasy AWS Lambda sample code ([found here](https://quarkus.io/guides/amazon-lambda-http)) works locally in JVM mode but fails when using native mode.

**Expected behavior**
A call (via browser, curl, etc.) should return the same results running locally using SAM, whether in JVM or native mode.

**Actual behavior**
The code is compiled using Maven:

`mvn clean install -Dnative
`
And then I attempt to run it using SAM:

`sam local start-api --template sam.native.yaml
`
The service starts as expected:

```
Mounting MylambdaNativeFunction at http://127.0.0.1:3000/{proxy+} [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2020-02-13 11:31:56  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
```

Calling the URL (http://localhost:3000/hello), however, results in the following error message:

```
Invoking not.used.in.provided.runtimei (provided)
Decompressing /Users/me/eclipse-workspace/mylambda/target/function.zip

Fetching lambci/lambda:provided Docker container image......
Mounting /private/var/folders/ld/s2cy7kwn60vctgzjv872rfx0dq49lr/T/tmpz4zqpfue as /var/task:ro,delegated inside runtime container
START RequestId: 46e08628-6cd6-1c8f-d7f8-4ee64af3e31a Version: $LATEST
END RequestId: 46e08628-6cd6-1c8f-d7f8-4ee64af3e31a
REPORT RequestId: 46e08628-6cd6-1c8f-d7f8-4ee64af3e31a	Init Duration: 32.51 ms	Duration: 0.90 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 7 MB	
Invalid API Gateway Response Keys: {'errorType', 'errorMessage'} in {'errorType': 'exitError', 'errorMessage': 'RequestId: 46e08628-6cd6-1c8f-d7f8-4ee64af3e31a Error: fork/exec /var/task/bootstrap: exec format error'}
Function returned an invalid response (must include one of: body, headers, multiValueHeaders or statusCode in the response object). Response received: {"errorType":"exitError","errorMessage":"RequestId: 46e08628-6cd6-1c8f-d7f8-4ee64af3e31a Error: fork/exec /var/task/bootstrap: exec format error"}
2020-02-13 11:32:26 127.0.0.1 - - [13/Feb/2020 11:32:26] "GET /hello HTTP/1.1" 502 -


```

**To Reproduce**
Follow the steps found here [https://quarkus.io/guides/amazon-lambda-http](https://quarkus.io/guides/amazon-lambda-http) for running locally using SAM in native mode.

**Environment (please complete the following information):**
Darwin A81621 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

graalvm-ce-19.2.1

Quarkus 1.2.0.Final

**Comment by patriot1burke** [comment]
Weird, I was getting the 502 response error as you did at first, then it just went away.  It works for me now and I can't reproduce the 502

**Comment by TheGeekPharaoh** [comment]
I just re-ran the entire process from the guide page.  I was worried I'd inadvertently changed something that was causing this.  Nope.  Still fails with the same error using the sample code.

**Comment by patriot1burke** [comment]
I don't know if the difference is that I'm running on Fedora.

**Comment by TheGeekPharaoh** [comment]
I finally had a chance to work through this again and it appears it's not a bug, per se, but rather a deficiency in the documentation.  The docs expect that you are running this example on Linux.  In my case, however, I was running on macOS.  By following the guide for [building a native](https://quarkus.io/guides/building-native-image) image -- specifically the instructions for a container-based build -- and then combining with the instructions for [running the service using SAM](https://quarkus.io/guides/amazon-lambda-http) I was able to get it running.  The key was that my native binary needed to be built for Linux, not macOS.  Once that was taken care of everything worked as expected.

A note should be added to the [Amazon Lambda HTTP](https://quarkus.io/guides/amazon-lambda-http) documentation reflecting this caveat.

**Comment by patriot1burke** [comment]
@TheGeekPharaoh Documentation already states this:

If you are building on a non-linux system, you will need to also pass in a property instructing quarkus to use a docker build as Amazon Lambda requires linux binaries. You can do this by passing this property to your maven build: -Dnative-image.docker-build=true. This requires you to have docker installed locally, however.
