### ISSUE TITLE
QuarkusTestExtension doesn't work with @ExtendWith or @RegisterExtension

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#7199]
**Describe the bug**
Using the getting-started quickstart, the test is generated as follows with the `@QuarkusTest` annotation.

```java
@QuarkusTest
public class GreetingResourceTest {
    @Test
    public void testHelloEndpoint() {
        given()
          .when().get("/hello")
          .then()
             .statusCode(200)
             .body(is("hello"));
    }
}
```

Junit offers two more ways to integrate an extension: `@ExtendWith` and `@RegisterExtension` . Both ways allows to order extensions between them so it's usefull when using multiple extensions.

Using any of these two annotations leads to the following error:
```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.quickstart.GreetingResourceTest]: Bean is null
Caused by: java.lang.NullPointerException: Bean is null
```

**Expected behavior**
We can use any of the existing way to integrate an extension with QuarkusTestExtension.

**Actual behavior**
Using any of this two extension declaration forms didn't works

```java
public class GreetingResourceTest {
  @ExtendWith(QuarkusTestExtension.class)
  public class GreetingResourceTest {
      @Test
      public void testHelloEndpoint() {
          given()
            .when().get("/hello")
            .then()
               .statusCode(200)
               .body(is("hello"));
    }
}
```

Or

```java
public class GreetingResourceTest {
    @RegisterExtension
    static QuarkusTestExtension quarkusTestExtension = new QuarkusTestExtension();

    @Test
    public void testHelloEndpoint() {
        given()
          .when().get("/hello")
          .then()
             .statusCode(200)
             .body(is("hello"));
    }
}
```

Leads to 
```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.quickstart.GreetingResourceTest]: Bean is null
Caused by: java.lang.NullPointerException: Bean is null
```

**To Reproduce**
1. Follow the getting sarted guide
2. Change the `GreetingResourceTest` to one of the two forms described here
3. `mvn clean test`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.5" 2019-10-15
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.2.0.Final or current master

**Comment by stuartwdouglas** [comment]
This is because it uses the QuarkusTest annotation to turn test classes into beans.

**Comment by loicmathieu** [comment]
Ok but Canada we fix it or at least provides a workaround? 
Using those annotations is the only way to ordering test extensions. So it is very important in order Quarkus to play well inside the Junit 5 ecosystem

**Comment by stuartwdouglas** [comment]
We can fix, we would need to use Jandex index that we already have for
QuarkusTestResource to look for @RegisterExtension and @ExtendWith, and use
that to explicitly figure out which test classes are beans. You should be
able to work around this for now by putting a CDI scope on the test class.

**Comment by loicmathieu** [comment]
@stuartwdouglas thanks, the workaround works! I annotated my class with `@Singleton` and it works.

Regarding a fix, I don't understand why you need Jandex, you can retrieve easily the test class inside an extension (via `extensionContext.getRequiredTestClass();`) and register it in CDI ...

**Comment by stuartwdouglas** [comment]
QuarkusTest only starts Quarkus once for all tests, so we need to know all the test classes at the start.

**Comment by geoand** [comment]
@loicmathieu Since Quarkus test classes are also beans, we need a way of knowing which test classes are indeed Quarkus tests.
You can follow the code starting from here: https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L498

It should be pretty easy to provide a fix.

**Comment by Xanas80** [comment]
Is there a solution in sight? Otherwise we cannot update to 1.3.1.Final

**Comment by gsmet** [comment]
@Xanas80 if the workaround of adding a CDI scope doesn't work for you, could you provide a reproducer?

@loicmathieu do you plan to work on that one?

**Comment by loicmathieu** [comment]
@gsmet I have no plan to work on this one in a near future. I have other things to finish on my Quarkus todo list ;)

If nobody have time to work on it soon, I can have a look in a few weeks but I don't now anything about Quarkus junit extension so it will take me some times ...

**Comment by Xanas80** [comment]
How to use?
@QuarkusTest
@ExtendWith(MyExtension.class)
or
@ExtendWith(QuarkusTestExtension.class)
@ExtendWith(MyExtension.class)

Nevertheless the beforeEach callback from MyExtension is performed before the quarkus injection.
Tested with 1.3.2.Final

**Comment by geoand** [comment]
Best ask a question on the Quarkus Zulip with more details in order to have a better chance of getting a meaningful answer

**Comment by Xanas80** [comment]
> Best ask a question on the Quarkus Zulip with more details in order to have a better chance of getting a meaningful answer

After some Zulip discussions, i know the Problem.

For the correct execution order, i have to use it like this:
`@ExtendWith({QuarkusTestExtension.class, MyExtension.class})`

But that issn't the real problem, it is

```
public void beforeEach(ExtensionContext context) throws Exception {
        // context.getTestInstance() != actualTestInstance from QuarkusTestExtension
```

so I am not able to resolve the injected EntityManager

**Comment by will421** [comment]
If someone else see this thread wanting to create an extension :
The test instance in ExtensionContext is still not the running instance from QuarkusTestExtension.
I managed to do what I needed by using QuarkusTestBeforeEachCallback (https://quarkus.io/guides/getting-started-testing#enrichment-via-quarkustestcallback)
