### ISSUE TITLE
java.lang.NullPointerException: null at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.getEntityManager(JpaOperations.java:75)

### ISSUE THREAD

**Issue by srivatsav** [quarkusio/quarkus#7212]
**Describe the bug**
Using hibernate ORM with Panache gives Null Pointer Exception whenever trying to  communicate with DB.

**Actual behavior**
 Throws null pointer Exception - 

java.lang.NullPointerException: null
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.getEntityManager(JpaOperations.java:75) ~[quarkus-hibernate-orm-panache-1.2.0.Final.jar:1.2.0.Final]
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.persist(JpaOperations.java:46) ~[quarkus-hibernate-orm-panache-1.2.0.Final.jar:1.2.0.Final]
	at io.quarkus.hibernate.orm.panache.PanacheEntityBase.persist(PanacheEntityBase.java:719) ~[quarkus-hibernate-orm-panache-1.2.0.Final.jar:1.2.0.Final]

**To Reproduce**
1. Run the local postgresql instance on local with port 5432 - check for public schema
2. Run the attached zipped file (demo.tar.gz) as spring boot application.
3. localhost:8080/demo/getDemo - Hit this endpoint from local

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.url=jdbc:postgresql://localhost:5432/public
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
![Screenshot from 2020-02-15 19-18-04](https://user-images.githubusercontent.com/4679983/74589107-657fa700-5028-11ea-8867-969b70cac513.png)

[demo.tar.gz](https://github.com/quarkusio/quarkus/files/4208538/demo.tar.gz)

**Environment (please complete the following information):**

 - Output of `uname -a` or `ver`: Linux PPH-LAP-00458 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 
          17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
     openjdk version "11.0.6" 2020-01-14
     OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
     OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, 
     sharing)

 - Quarkus version or git rev: 1.2.0.Final

**Additional context**
(Add any other context about the problem here.)

**Comment by loicmathieu** [comment]
@srivatsav 

> Run the attached zipped file (demo.tar.gz) as spring boot application.

How do your run your application? I notice that you have an Application class with `@SpringBootApplication` I'm not sure it is supported in Quarkus, maybe @geoand can give us some light on this.

**Comment by geoand** [comment]
@srivatsav It seems like you are mixing a Spring Boot and a Quarkus application. That is never going to work.

Please take a look at: https://quarkus.io/guides/spring-data-jpa
