### ISSUE TITLE
Dbref for mongodb

### ISSUE THREAD

**Issue by DicksengA** [quarkusio/quarkus#7213]
Any idea how i can use DBref for mongodb in quarkus. Have trying to migrate our enterprise app from spring but havent been able to find an example on how to achieve this using panache

**Comment by loicmathieu** [comment]
Did you try to use a `com.mongodb.DBRef` field inside your entity ? 

For querying, you can use a native MongoDB query so everything that is possible with raw mongodb-client is possible with MongoDB with Panache.

Please give feedback on what you tested and what works.

**Comment by DicksengA** [comment]
Hmmm was hoping for an alternative to @DBref in spring
