### ISSUE TITLE
Start many kafka consumers listening on a topic

### ISSUE THREAD

**Issue by overthetop** [quarkusio/quarkus#7215]
When I use the reactive messaging in Quarkus and annotate a method with @Incoming("orders") I get only 1 kafka consumer for that channel. Is there a way to specify a concurency number of listeners for this channel? For example I need 20 kafka consumers listening on the topic. How can I do that?

**Comment by cescoffier** [comment]
This is tracked by https://github.com/smallrye/smallrye-reactive-messaging/issues/329.

**Comment by overthetop** [comment]
Thank you @cescoffier. As a workaround until the issue is resolved I guess I have to use the vert.x kafka driver directly?

**Comment by cescoffier** [comment]
That has been fixed a long time ago.
