### ISSUE TITLE
Quarkus gradle build fails with flatDir

### ISSUE THREAD

**Issue by tk303** [quarkusio/quarkus#7217]
**Describe the bug**
I'm using gradle to build quarkus project.
I've got jar dependencies that are in my projects 'lib' folder that I need to include as dependencies.
When trying to build the project it fails

**Expected behavior**
It should build and start

**Actual behavior**
Build fails without any clear reason.

**To Reproduce**
1.  Create a sample quarkus project with gradle as a build tool
2.  Create a lib folder in your project, add some jar
(I have downloaded the appache commons lang3)

3.  Add a flat dir repository to your build.gradle file, like:
flatDir {
        name = 'Local lib'
        dir file('lib')
    }
4.  Add a dependency in your project like:
implementation ':commons-lang3-3.9'

**Note**
I ran the quarkusBuild target with **--stacktrace** and it gives this error:

`Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at io.quarkus.gradle.AppModelGradleResolver.toAppDependency(AppModelGradleResolver.java:194)
	at io.quarkus.gradle.AppModelGradleResolver.resolveModel(AppModelGradleResolver.java:134)`

So I think it must be an issue with the quarkus gradle plugin.

**Comment by gsmet** [comment]
/cc @quarkusio/devtools @quarkusio/bootstrap 
(not sure what is the issue so pinging both)

**Comment by gastaldi** [comment]
I'll have a look. But you shouldn't need to download JARs explicitly.

eg. Your implementation should read: 

`implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.9'`

**Comment by tk303** [comment]
> I'll have a look. But you shouldn't need to download JARs explicitly.
> 

Yes, this was a simple example, my use case is that I've got some jars that are not available on public Maven as they're specific to another internal project.

I appreciate your very prompt respond.
Hope it gets solved.
Thanks

**Comment by gastaldi** [comment]
Gotcha. Can you give it a try with the https://github.com/quarkusio/quarkus/pull/7225 PR and confirm that resolves your problem?
