### ISSUE TITLE
Add access to the entityManager from a JPA PanacheEntity / Repository

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#7233]
In a `PanacheEntity` entity or in `PanacheRepository`, I should be able to access the entitymanager (available via `JpaOperations.getEntityManager()` internally).

probably

```
public EntityManager entityManager() {
    return JpaOperations.getEntityManager();
}
```

**Comment by nimo23** [comment]
Related to https://github.com/quarkusio/quarkus/issues/6080.

**Comment by loicmathieu** [comment]
For the record, the entityManager should be accessible from the base classes: `PanacheEntityBase` and `PanacheRepositoryBase`.
