### ISSUE TITLE
"java.net.BindException: Address already in use" when test uses multiple arquillian's @Deployment annotation

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#7235]
I get the follow exception when a test uses multiple arquillian's @Deployment annotation.

    java.util.concurrent.ExecutionException:
    java.net.BindException: Address already in use

Execution env.
    jdk 11.0.2
    mvn 3.6.0
    quarkus 999-SNAPSHOT
    

This project demonstrates the issue
  https://github.com/rsearls/quarkus-BindException.git

Test org/jboss/resteasy/test/xxe/ExternalParameterEntityTest is enabled to run.
The pom file has tagged all such failing tests with comment 
"java.net.BindException: Address already in use".

**Comment by geoand** [comment]
Is this still an issue?

**Comment by rsearls** [comment]
No

**Comment by geoand** [comment]
Thanks
