### ISSUE TITLE
Swagger-UI/Openapi-Link provides faulty schema-components for List/Set

### ISSUE THREAD

**Issue by ehora** [quarkusio/quarkus#7238]
I'm evaluating Quarkus as backend, accessed by an angular frontend. I wanted to use the openapi data provided by Quarkus via http://localhost:8080/openapi, and generate via openapi-generator tools an typescript-angular client stub.

I used as first step the Quarkus Openapi Guide: https://quarkus.io/guides/openapi-swaggerui But after running the unmodified example and retrieve the Openapi YAML-Data via the http://localhost:8080/openapi I noticed that the generated data is wrong and the openapi generator is not able to generate a client because of a stackoverflow error.

Problem: a self-reference in the Openapi-data for the SetFruit-Definition (last line):

```
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths:
  /fruits:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetFruit'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fruit'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetFruit'
    delete:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fruit'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetFruit'
components:
  schemas:
    Fruit:
      type: object
      properties:
        description:
          type: string
        name:
          type: string
    SetFruit:
      $ref: '#/components/schemas/SetFruit'
```

**Expected behavior**
Generation result should be:
```
   SetFruit:
     type: array
     items:
       $ref: '#/components/schemas/Fruit'
```
**Actual behavior**
```
    SetFruit:
      $ref: '#/components/schemas/SetFruit'`
```

**To Reproduce**
1. Run Openapi-example from Quarkus Openapi Guide: https://quarkus.io/guides/openapi-swaggerui 
2. call http://localhost:8080/openapi

**Comment by geoand** [comment]
cc @phillip-kruger @kenfinnigan

**Comment by gsmet** [comment]
Hum. That looks like a regression if even the app from the guide is concerned.

/cc @EricWittmann

**Comment by ehora** [comment]
Created Issue at smallrye, as @EricWittmann  mentioned: https://github.com/smallrye/smallrye-open-api/issues/260

**Comment by MikeEdgar** [comment]
Looking at this issue in smallrye. Note that a temporary work-around is to add `java.util` to the property named `mp.openapi.scan.exclude.packages`.
