### ISSUE TITLE
Improve Quarkus Keycloak Documentation

### ISSUE THREAD

**Issue by stefnotch** [quarkusio/quarkus#7240]
**Description**
Currently the very well written [Quarkus Keycloak documentation](https://quarkus.io/guides/security-keycloak-authorization#starting-and-configuring-the-keycloak-server) simply states the following regarding the Keycloak configuration. 
> Import the [realm configuration file](https://github.com/quarkusio/quarkus-quickstarts/blob/master/security-keycloak-authorization-quickstart/config/quarkus-realm.json) to create a new realm. For more details, see the Keycloak documentation about how to [create a new realm](https://www.keycloak.org/docs/latest/server_admin/index.html#_create-realm).

This is amazing for quickly getting started, because it just works. However, as soon as you want to protect an additional route, you either have to dig through the massive Keycloak documentation or find another Quarkus tutorial such as [this one](https://quarkus.io/guides/security-openid-connect) or [that one](https://quarkus.io/guides/security#authorization-of-web-endpoints-using-configuration). Sadly, those tutorials aren't mentioned nor linked in the Quarkus Keycloak documentation. 

**Implementation ideas**
It'd be great to explain one way to protect additional routes and then link to one of those tutorials for more.

**Comment by gsmet** [comment]
@stefnotch would you be interested in providing a PR?

**Comment by stefnotch** [comment]
Of course, I'd love to give back to this amazing project!
