### ISSUE TITLE
Quartz extension - make it possible to access the underlying Quartz scheduler instance

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#7246]
We should probably just add a producer for `org.quartz.Scheduler` and make it injectable.

**Comment by gleb-kosteiko** [comment]
That would be useful and nice!

**Comment by gsmet** [comment]
@machi1990 would you be interested in doing it?

**Comment by mkouba** [comment]
@gsmet I'm on it. I'll ask @machi1990 for review ;-).

**Comment by machi1990** [comment]
> @gsmet I'm on it. I'll ask @machi1990 for review ;-).

Great thanks @mkouba.
