### ISSUE TITLE
XSS vulnerability in NotFoundExceptionMapper

### ISSUE THREAD

**Issue by blxbrgld** [quarkusio/quarkus#7248]
**Description**
The no resource endpoint HTML page which is rendered on 404 errors introduces XSS vulnerability. Given as an example a GET endpoint which accepts a paging parameter in the form "start,offset" (i.e. 0,10). A request like: 

`/users?paging=0%2c-1sp137%3Cscript%3Ealert(1)%3C%2fscript%3Emzx4u`

would lead to the following exception, and the 404 page in turn would execute the script (alert in our case).

`RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.QueryParam("paging") value is '0,-1sp137<script>alert(1)</script>mzx4u'`

**Implementation ideas**
Enable the 404 HTML page only in DEV mode.

**Comment by geoand** [comment]
Isn't `NotFoundExceptionMapper` only enabled in dev-mode anyway?

**Comment by gsmet** [comment]
@gastaldi would you have the cycles to check out this one?

Make sure this thing is only available in dev mode. And also, we should probably deal with escaping better than we currently do.

If you don't have the time, please say so. Thanks!

**Comment by gastaldi** [comment]
Sure, I can have a look

**Comment by gastaldi** [comment]
The NotFoundExceptionMapper is only enabled in dev-mode indeed. The 404 page that this issue refers to is the one handled by Resteasy containing the error.

**Comment by gastaldi** [comment]
Remark: I am not even sure why a 404 is returned. It would be better to return `400` (Bad Request) instead

**Comment by gastaldi** [comment]
Using `@Encoded` together with the `@QueryParam` annotation solves the problem.

**Comment by gsmet** [comment]
@gastaldi can we have a clear status on that one? I understand the culprit is not Quarkus but RESTEasy? If so, we need to involve @asoldano .

**Comment by gastaldi** [comment]
@gsmet yes, AFAIR RESTEasy handles the exception and returns that unencoded error message.

IMHO RESTEasy's error messages containing input values should always be encoded, no matter if `@Encoded` is specified or not. 

I'll create a ticket in RESTEasy to track that.

Cc @asoldano

**Comment by gsmet** [comment]
OK, thanks.

**Comment by gastaldi** [comment]
Ticket created in https://issues.redhat.com/browse/RESTEASY-2519
