### ISSUE TITLE
Remote Debug in a Docker Container

### ISSUE THREAD

**Issue by lbernardomaia** [quarkusio/quarkus#7256]
Hi,

As I mentioned in the mail group, I've updated the Quarkus version to the latest available and also updated the Java version to 11.  

A problem I'm facing is that I used to debug my app that runs in a docker container remotely and everything worked fine before bumped to Java 11. The issue is that the Quarkus classes that add the JDWP arguments to debug are always adding address=5005 instead of address=*:5000, for Java 11.

My suggestion to fix that would be to verify the Maven and Gradle compiler properties to know which Java version is in use, to add the appropriate arguments. 

Thanks

**Comment by jaikiran** [comment]
Hello @lbernardomaia, I can't seem to find the thread in the Quarkus dev mailing list. Is this issue about (remote) debugging the native image build when built within container?

**Comment by lbernardomaia** [comment]
Hi @jaikiran ,

I was not using the native image, perhaps the problem will happen with that as well. I just changed the maven devtools module to what I suggested and works. 

I can also change the Gradle and Native Image to have the change and send a PR later.

**Comment by sdaschner** [comment]
Should be fixed in #7890, also see #7889. Close?
