### ISSUE TITLE
RootDefinition should also trim RuntimeConfig and RuntimeConfiguration suffixes

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#7257]
If a config root has a `RuntimeConfig` suffix (not `RunTimeConfig`) only the `Config` part of the suffix is removed and so the property must include the `-runtime` part, ie. for `io.quarkus.quartz.runtime.QuartzRuntimeConfig#threadCount` the `quarkus.quartz-runtime.thread-count` property must be used.

This works as designed and documented, but:
(1) The generated configuration references in docs does not reflect this behavior - see for example https://quarkus.io/guides/quartz#quartz-configuration-reference
(2) In most cases the usage of `RuntimeConfig` is very likely NOT intentional but a typo

Proposed solution:
1. Fix the `RootDefinition`, ie. trim the `RuntimeConfig` and `RuntimeConfiguration` suffixes
2. Fix docs generator
3. Update the docs
4. Intruct the clients of the affected configurations to switch to the new values

**Comment by mkouba** [comment]
It seems that the only runtime config (ie. class with `RuntimeConfig`) that does not override the name and will be affected by the change is the `QuartzRuntimeConfig`.

**Comment by geoand** [comment]
I think if `quartz` is the only one affected, we can probably break it without too many people being affected.

**Comment by gsmet** [comment]
Yes, break it before 1.3.0.CR1 and add a `breaking-change` label, I'll write the migration guide.

**Comment by mkouba** [comment]
The docs generator makes use of `toLowerCase()` and thus matches the `RuntimeConfig`:
https://github.com/quarkusio/quarkus/blob/master/core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/DocGeneratorUtil.java#L470

However, this will not be an issue anymore once we fix the `RootDefinition` problem. And so there is no need to fix the generator.
