### ISSUE TITLE
Support sql-load-script with different schema compared to the entity

### ISSUE THREAD

**Issue by SchulteMarkus** [quarkusio/quarkus#7259]
This feature request is related to [Hibernate ORM in development mode](https://quarkus.io/guides/hibernate-orm#hibernate-orm-in-development-mode).

> The first choice is to use quarkus.hibernate-orm.database.generation=drop-and-create in conjunction with import.sql.
> That way for every change to your app and in particular to your entities, the database schema will be properly recreated and your data fixture (stored in import.sql)

In my use-case, my database entity is not representing a complete row of a table, but only a subset. Imaging my entity to be a "slice" as described on http://www.adam-bien.com/roller/abien/entry/creating_dtos_without_mapping_with

    @Entity
    @Table(name = "ping")
    public class PingSlice {
      public long timestamp;
      public String flightName;
    }

Imagine, the ping-table would have more columns, such as "id", ... 
Now, from my existing ping-table, I am creating a dump, which I want to use for development. The dump will contain data for the three columns "timestamp", "flightName" and "id". I will use my dump as "import.sql" as described for the configuration _quarkus.hibernate-orm.sql-load-script_.

When I run Quarkus in development mode, because of database.generation=drop-and-create a new "ping"-table will be created when staring Quarkus, containing two columns "timestamp" and "flightName". Afterwards, the import.sql is being proceeded. Which will fail with a SQL error similar to
    
    ERROR 1136 (21S01): Column count doesn't match value count at row 1

, because the INSERT statements from import.sql are including three columns "timestamp", "flightName" and "id".

**Feature request**
Please support a _quarkus.hibernate-orm.sql-load-script_ where the defined SQL contains more columns compared to the local representing entity.

**Comment by josephearl** [comment]
The issue here is your schema only has 2 columns because you are generating from your Java model.

It sounds like you want to generate your schema using something like Flyway so that it matches your real tables which have more columns than your Java models.

**Comment by SchulteMarkus** [comment]
Dude, donno, reported two years ago :-D
