### ISSUE TITLE
qute: modulo operation in iterations

### ISSUE THREAD

**Issue by fiorenzino** [quarkusio/quarkus#7283]
**Description**
`
{#for printable in printables}
<div>{printable.name}</div>   
{#if count % 5 == 0 }
           <div class="clearfix"></div>
   {/if}
{/for}
`

**Comment by gastaldi** [comment]
A workaround is to create a `@TemplateExtension` like: 

```java
public class ModuleExtension {

    @TemplateExtension
    public static Integer mod(Integer left, Integer module) {
        return left % module;
    }
}
```

And use it in the template:  

```
{#if a.mod(5) == 1}
OKAY
{/if}
```

**Comment by gastaldi** [comment]
@fiorenzino I made the `mod` function above a built-in function in Qute in https://github.com/quarkusio/quarkus/pull/7288. Please give it a try and let me know how that goes for you

**Comment by mkouba** [comment]
Also note that within a loop you should be able to use `{#if even}` and `{#if odd}`...
