### ISSUE TITLE
OIDC needs to support the opaque access tokens

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#7286]
**Description**
Some OIDC providers may return an opaque access token (alongside a JWT IdToken) as part of the authorization code flow (such as Google for example as reported by a user - likely because a mobile scope was requested). 
This is not a major problem for the OIDC `web-app` applications as `IdToken` is used by default as `Principal`, but if this access token is propagated to the downstream Quarkus nodes configured as OIDC `service` applications then they will not be able to get anything out of this opaque token.

The workaround is to use `quarkus-elytron-oauth2` for these downstream nodes but a mix in of `quarkus-oidc` and `quarkus-elytron-oauth2` in the overall architecture is not ideal. And it won't help if we start letting the users choose which token, `id` or `access` one, is used as a `Principal` for the `web-app` applications.

**Implementation ideas**
Introduce a property to let the runtime know the access tokens will be opaque. Next, in `OidcIdentityProvider`, work with the Vertx token introspection handler in order to 1) populate `Principal` and 2) synthesize a JWT token from the introspection response

**Comment by sberyozkin** [comment]
Vertx OAuth2 is already having some support around it which is great

**Comment by sberyozkin** [comment]
I'll open a new issue to do with the introspection endpoint response caching once this issue is resolved.
CC @stianst

**Comment by stianst** [comment]
Simple approach is obviously to use token introspection endpoint for every request, but a cache to prevent subsequent requests with same token to flood the IdP would be a nice addition.

**Comment by stianst** [comment]
I wonder if we can auto-detect token format? A token is typically a JWS, JWE or just a reference. Should be possible to auto-detect this.

**Comment by stianst** [comment]
Then again that may impact performance, and not sure if there would be a mix of tokens, or if one always expects a single token type

**Comment by sberyozkin** [comment]
@stianst Yeah, I'd say we can have just a property mandating that the opaque tokens are accepted per a specific tenant, it is still managed at the Vetx level, but in Quarkus we can tweak the producer code if needed. As you say, a mix of token formats may not be really there :-) so based on that property we can easily enforce that no JWS formats tokens are accepted if only opaque ones are expected, as Vertx does not support JWE yet. But we can definitely be more flexible going forward if there will be the requirements to support more than one format.
In `smallrye-jwt` we can accept both `RS256` and `ES256` signed tokens but not both at the same time and a property requiring a specific algorithm is set at the startup...
Thanks

**Comment by pedroigor** [comment]
@sberyozkin Isn't Vert.x going to fallback to introspection/opaque tokens if the bearer token sent in the request can not be parsed or validated based on the local JWKS ?

**Comment by sberyozkin** [comment]
@pedroigor Yeah, I was looking at the code the other day and it did look that it will do it as I happily noted [above](https://github.com/quarkusio/quarkus/issues/7286#issuecomment-598717216) :-), it may well already work, but at the quarkus level it may make sense to give users an option to qualify the format. I'm also not sure if Vertx will create JWT out of the introspection response. I'll need to do a test I guess.
Thanks
