### ISSUE TITLE
Quarkus is not handling annontation @JsonSubTypes properly

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#7292]
For @JsonSubTypes I have an app that defines the annotation as

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
    @JsonSubTypes({
          @JsonSubTypes.Type(value = ProxyWithGenericReturnTypeJacksonType1.class, name = "type1"),
          @JsonSubTypes.Type(value = ProxyWithGenericReturnTypeJacksonType2.class, name = "type2")})

In the endpoint the values are set
    ProxyWithGenericReturnTypeJacksonType1 first = new ProxyWithGenericReturnTypeJacksonType1();
    first.setId(1);
    first.setName("MyName");

The return value should be
    {"type":"type1","id":1,"name":"MyName"}
but is 
    {"id":1,"name":"MyName"}

Execution env.
    jdk 11.0.2
    mvn 3.6.0
    quarkus 999-SNAPSHOT

The following project demonstrates the issue
  https://github.com/rsearls/quarkus-JsonSubTypes-annotation.git

Follow the directions in the README file to setup and run the test

**Comment by loicmathieu** [comment]
You need to use `quarkus-resteasy-jackson`.

I notice also that you include in your dependencies a lot of libraries that Quarkus define in it's own dependencies, you should try to avoid that as much as possible and use Quarkus extensions whenever it's possible. This allows a better support of the librairies inside Quarkus.

**Comment by nimo23** [comment]
It is the same as https://github.com/quarkusio/quarkus/issues/7293

**Comment by rsearls** [comment]
I added quarkus-resteasy-jackson to the provided sample project and got the same error.

**Comment by rsearls** [comment]
> I notice also that you include in your dependencies a lot of libraries that Quarkus define in it's own dependencies, you should try to avoid that as much as possible and use Quarkus extensions whenever it's possible.

I am using io.quarkus:quarkus-bom.  All the needed resteasy archives listed in the BOM are referenced in the POM.  Needed archives not listed in the BOM are referenced with the appropriate version stmt in the POM

**Comment by loicmathieu** [comment]
@rsearls a Quarkus extension is more than just adding the corresponding dependencies, it does some stuff during the build of your application (this is the augmentation phase of a Quarkus application), that's why if you want to use resteasy and jackson you need to use the `quarkus-resteasy-jackson` extension in order to make everything work properly.

**Comment by gsmet** [comment]
@loicmathieu frankly, I'm not sure this is an issue with the dependencies.

I don't see any reference to `JsonSubTypes` in our code and we should probably register them for reflection.

**Comment by rsearls** [comment]
My guess is this as a CDI issue.  Quarkus is using a different CDI provider than wildfly.

**Comment by gsmet** [comment]
@rsearls I see you reported this with a JDK version. You have the failure in JVM mode, not native?

**Comment by machi1990** [comment]
Hi @rsearls I am not seeing an error in my personal sample project with the `resteasy-jackson` extension. 

I also have tried to follow the instruction provided in the README of your producer project and I stumbled upon the following error: 
```
Could not resolve dependencies for project org.jboss.resteasy:quarkus-JsonSubTypes-annotation:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.jboss.resteasy:resteasy-cache-core:jar:4.5.0-SNAPSHOT, org.jboss.resteasy:resteasy-stats:jar:4.5.0-SNAPSHOT, org.jboss.resteasy:resteasy-wadl:jar:4.5.0-SNAPSHOT: Could not find artifact org.jboss.resteasy:resteasy-cache-core:jar:4.5.0-SNAPSHOT
```

**Comment by loicmathieu** [comment]
@gsmet `JsonSubTypes` works without issue in JVM mode, I used them in one of my application. As the description of the issue and the example repository shows, the issue occurs on standard test so no native mode.

Didn't tested native mode, it may need to register the types for reflection, but the issue will be an error not a field not present I think. 

@rsearls when using `@JsonSubTypes` I configure the `@JsonTypeInfo` with `visible=true`. I didn't remember why but maybe you can test that.

**Comment by rsearls** [comment]
> Could not resolve dependencies for project org.jboss.resteasy:quarkus-JsonSubTypes-annotation:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.jboss.resteasy:resteasy-cache-core:jar:4.5.0-SNAPSHOT, org.jboss.resteasy:resteasy-stats:jar:4.5.0-SNAPSHOT, org.jboss.resteasy:resteasy-wadl:jar:4.5.0-SNAPSHOT: Could not find artifact org.jboss.resteasy:resteasy-cache-core:jar:4.5.0-SNAPSHOT

Sorry version 4.5.0-SNAPSHOT is the master branch.  Please change that to
version 4.4.2.Final in the pom.xml at line 29 property <resteasy-version>

**Comment by rsearls** [comment]
Instead of above please just update the project.  I've made the needed adjustments in the pom file you

**Comment by rsearls** [comment]
I added visible=true to @JsonTypeInfo in ProxyWithGenericReturnTypeJacksonAbstractParent but the test failed the same way for me

**Comment by geoand** [comment]
Is this still a problem in the latest Quarkus versions?

**Comment by rsearls** [comment]
Yes it still fails.  I have updated the test case to quarkus version 1.9.0.Final

**Comment by geoand** [comment]
Thanks for checking

**Comment by cjbooms** [comment]
If anyone is blocked by this issue, I have being forced to use the following workaround.
In define an additional untyped class as follows:
```
@RegisterForReflection
data class UntypedObj(
  @param:JsonProperty("type")
  @get:JsonProperty("type")
  @get:NotNull
  val type: String
) {
  val properties: MutableMap<String, Any> = mutableMapOf()
  @JsonAnySetter
  fun set(name: String, value: Any) {
    properties[name] = value
  }
}
```
Then inside my controller method I use Jackson's convert function and a bit of ugliness to convert it to the correct polymorphic type:
```
    fun processRequest(untypedObj: UntypedObj) {
        val correctType: TypedObj = when (untypedObj.type) {
            "type_one" -> objectMapper.convertValue<TypeOne>(untyped.properties.plus("type" to untypedObj.type))
            "type_two" -> objectMapper.convertValue<TypeTwo>(untyped.properties.plus("type" to untypedObj.type))
            else -> objectMapper.convertValue<TypeThree>(untyped.properties.plus("type" to untypedObj.type))
        }
``` 
Not pretty but it has unblocked me and temporarily saved me from reverting to JVM
For some reason the issue does not occur when using Jackson directly

**Comment by rsearls** [comment]
outdated
