### ISSUE TITLE
Override property values in application.properties during Unit Tests

### ISSUE THREAD

**Issue by DicksengA** [quarkusio/quarkus#7301]
Is that a way to change a property value for unit tests?
Example quarkus.mongodb.database, wanna change it in QuarkusTest but leave the original value unchanged.

**Comment by loicmathieu** [comment]
QuarkusTest uses the test profile, so you can override the property inside your application.properties like that:

```
%test.quarkus.mongodb.database=test
```

**Comment by geoand** [comment]
Closing since the answer by @loicmathieu is spot on

**Comment by DicksengA** [comment]
Thanks it works :)

**Comment by zenonwch** [comment]
Sorry for the question for the closed issue.
But what if I want to set different values for the different test classes?

**Comment by geoand** [comment]
Then you have to wait for Quarkus 1.6 which introduces the notion of [QuarkusTestProfile](https://github.com/quarkusio/quarkus/blob/2f7b40c343c81c61212c3497b6594f3b68d29feb/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestProfile.java)
