### ISSUE TITLE
Use official GraalVM images when building native images with Docker?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#732]
In NativeImagePhase.java, we have:
```
//TODO: use an 'official' image
            Collections.addAll(nativeImage, "docker", "run", "-v", outputDir.toAbsolutePath() + ":/project:z", "--rm", "swd847/centos-graal-native-image");
```

Apparently, Oracle released official GraalVM images here:
https://github.com/oracle/docker-images/tree/master/GraalVM/CE/1.0.0-rc11

There is one catch: it's using Oracle Linux :).

**Comment by evanchooly** [comment]
We now use `quay.io/quarkus/centos-quarkus-native-image:graalvm-1.0.0-rc14`

**Comment by cescoffier** [comment]
Yes, we control what's inside, and typically we have a version providing Maven and a few other tools (required for KNative)
