### ISSUE TITLE
Build error when using quarkus-tika and quarkus-narayana-jta extensions, provider com.ctc.wstx.stax.WstxInputFactory not found 

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7359]
Build error, provider `com.ctc.wstx.stax.WstxInputFactory` not found when using quarkus-tika and quarkus-narayana-jta extensions.

```
rm -rf fooBar
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=io.quarkus.qe \
    -DprojectArtifactId=fooBar \
    -DprojectVersion=1.0.0-SNAPSHOT \
    -DplatformArtifactId=quarkus-bom \
    -DclassName="io.quarkus.qe.MyResource" \
    -Dextensions="quarkus-tika,quarkus-narayana-jta"
mvn -f fooBar/pom.xml clean verify
```
```
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor#build threw an exception: javax.xml.stream.FactoryConfigurationError: Provider com.ctc.wstx.stax.WstxInputFactory not found
	at javax.xml.stream.XMLInputFactory.newInstance(Unknown Source)
	at com.arjuna.common.util.propertyservice.PropertiesFactoryStax.loadFromXML(PropertiesFactoryStax.java:46)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.loadFromFile(AbstractPropertiesFactory.java:149)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getPropertiesFromFile(AbstractPropertiesFactory.java:102)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.initDefaultProperties(AbstractPropertiesFactory.java:195)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getDefaultProperties(AbstractPropertiesFactory.java:62)
	at com.arjuna.common.util.propertyservice.PropertiesFactory.getDefaultProperties(PropertiesFactory.java:48)
	at io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor.build(NarayanaJtaProcessor.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Workaround is to add `com.fasterxml.woodstox:woodstox-core` to the deps of the app.

**Comment by sberyozkin** [comment]
Hi @rsvoboda How have you found this combination :-) ? I'm assuming it is not an urgent issue, I'd like to allocate some time to take care of a few of the Tika issues soon

**Comment by rsvoboda** [comment]
I found it using https://github.com/quarkus-qe/beefy-scenarios/tree/master/002-quarkus-all-extensions. Together with issues in other extensions

Tika extension isn't super critical so this issue is not "fix it now" ;)

**Comment by zemiak** [comment]
Hello,

I hit this today with 1.3.0. I have TIKA for parsing media files and Hibenate/Panache/JTA for storing meta data. Tests fail with:

`[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.105 s <<< FAILURE! - in com.zemiak.movies.language.LanguageServiceIntegrationTest
[ERROR] allLanguagesCountGreaterThanZero  Time elapsed: 0.009 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor#build threw an exception: javax.xml.stream.FactoryConfigurationError: Provider com.ctc.wstx.stax.WstxInputFactory not found
`

You can hit it running "mvn test" on https://github.com/zemiak/movies

**Comment by sberyozkin** [comment]
@zemiak I'll try to address it for 1.4.0.

**Comment by tgippi** [comment]
We've got the same issue when we use `1.3.0.Final` and `pact-jvm` in our tests.

Seems that those two dependencies will cause the issue:
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-narayana-jta</artifactId>
    <version>1.3.0.Final</version>
</dependency>
<dependency>
    <groupId>xml-apis</groupId>
    <artifactId>xml-apis</artifactId>
    <version>1.4.01</version>
</dependency>
```
The `xml-apis:xml-apis` dependency will come with xerces for example which is a dependency of quarkus-tika and pact-jvm.

**Comment by sberyozkin** [comment]
@tgippi Thanks for this information.
Right I see its XMLInputFactory having
```
private static final String DEFAULT_FACTORY = "com.ctc.wstx.stax.WstxInputFactory";
```
I think we can most likely exclude this API from `quarkus-tika`

**Comment by sberyozkin** [comment]
Hmm... Excluding from `quarkus-tika` causes
```
java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
```
I wonder if we should update `quarkus-narayana-jta` to set `javax.xml.stream.XMLInputFactory` to whatever the default provider in Java is set to right now so that it is `protected` from the external dependencies like `xml-apis` setting a non default provider ? 

@gsmet Hi Guillaume, what do you think ?

**Comment by gdutra-cwb** [comment]
I'm having the same problem. Still not found it a way fix it. @rsvoboda can you suggest something ?

**Comment by suchwerk** [comment]
I am facing the same problem.
`2020-10-13 08:56:05,657 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor#build threw an exception: javax.xml.stream.FactoryConfigurationError: Provider com.ctc.wstx.stax.WstxInputFactory not found
        at javax.xml.stream.XMLInputFactory.newInstance(Unknown Source)
        at com.arjuna.common.util.propertyservice.PropertiesFactoryStax.loadFromXML(PropertiesFactoryStax.java:46)
        at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.loadFromFile(AbstractPropertiesFactory.java:149)`

**Comment by rsvoboda** [comment]
@suchwerk what version of Quarkus are you using? Workaround is to add com.fasterxml.woodstox:woodstox-core to the deps of the app.

@sberyozkin, will you have chance to look into into soon-ish, or do you have any pointers for possible fix?

**Comment by suchwerk** [comment]
@rsvoboda Version is 1.8.3

**Comment by sberyozkin** [comment]
@rsvoboda When I was looking at it last time, here is the proposal I did, https://github.com/quarkusio/quarkus/issues/7359#issuecomment-610058345, but it was likely not sound enough, so may be `xml-apis:xml-apis` dependency can be emulated in some other way... I'm sorry, 2 Tika issues have been fixed very recently, so I'm slowly but surely :-) trying to pick the issues, I''ve committed to fixing #6549 next, so this issue will be next after #6549, unless it will have been fixed earlier :-)
@suchwerk, please try to experiment with excluding `xml-apis:xml-apis`/etc

**Comment by sberyozkin** [comment]
@aloubyansky has helped to confirm this issue has been resolved in the current snapshot

**Comment by sberyozkin** [comment]
Sorry, I have a test on my branch
