### ISSUE TITLE
"Socket closed by remote peer" when using http headers

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#7366]
**Describe the bug**
When trying to pass a particular value in a http header, an error is returned back "Socket closed by remote peer"

**Expected behavior**
The header is correctly processed

**Actual behavior**
When an http header is passed in the request, an error is returned mentioning that the socket has been closed by the remote peer.
Deactivating (or not passing) the http header causes the service to respond correctly

**To Reproduce**
1. Create a simple endpoint class
`import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.HttpHeaders;

@Path("/endpoint")
public class Endpoint  {
	@Context private HttpHeaders httpHeaders;

	@GET
	public String showHeaderValue() {
		return "Value of the header with key X_CORRELATION_ID : " + httpHeaders.getHeaderString("X_CORRELATION_ID");
	}
}`
2. Launch the application "mvn compile quarkus:dev" 
3. Send a simple request (here the service is running on port 21101)
`curl "http://localhost:21101/endpoint" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -H 'X_CORRELATION_ID: 76960a8e-f9b7-47b3-bc57-752df99d8141' \
     -d $'{}'
`
The error received is shown in the screenshot.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin DWI-MBP15-1 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
 - Quarkus version or git rev: 1.2.1.Final
<img width="865" alt="Screenshot 2020-02-23 19 00 06" src="https://user-images.githubusercontent.com/7215870/75117221-d69a0c80-566f-11ea-8f0e-3a86e8d7c91d.png">

**Comment by Karm** [comment]
Hello, @dwamara, I did try with your setup and I cannot reproduce it:

Your curl verbatim but for the url:

```
$ curl -X GET "http://localhost:8080/data/headers" -H 'Content-Type: application/json; charset=utf-8' -H 'X_CORRELATION_ID: 76960a8e-f9b7-47b3-bc57-752df99d8141' -d $'{}' -i
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Content-Length: 84

Value of the header with key X_CORRELATION_ID : 76960a8e-f9b7-47b3-bc57-752df99d8141
```

While in dev mode, are you sure you haven't hit the moment when it was reloading? It is fast, but it is not instantaneous...

**Comment by Karm** [comment]
@dwamara If you could share a small app or logs, it might help :)

**Comment by dwamara** [comment]
I've just made a reproducer (at least I just reproduced it again now with it): https://github.com/dwamara/quarkus_bug_7366

**Comment by Karm** [comment]
@dwamara I tried some 200K requests issued by 5 clients on a single node; both JVM mode and :dev mode and it all went well. Could you also reproduce it with curl too or just with a browser?

**Comment by dwamara** [comment]
It just worked with curl but only when I replaced the single quotes with double quotes. Strange that you got it working with single quotes.
Maybe the client that I am using (https://paw.cloud/) as problem with sending header values because I just used Postman and it worked without any problem.

**Comment by dwamara** [comment]
I will just close the but as it does not seem related to quarkus. Thanks again and sorry for the time wasted on your part on this
