### ISSUE TITLE
quarkus-rest-client causes RESTEASY003145

### ISSUE THREAD

**Issue by iming0319** [quarkusio/quarkus#7370]
**Describe the bug**
(Describe the problem clearly and concisely.)
I am using implementation "com.github.docker-java:docker-java:3.1.5"
If I add implementation 'io.quarkus:quarkus-rest-client' in my build.gradle "dependencies" section.
I'll always get a javax.ws.rs.ProcessingException after each call-back which executed by docker client.
The message of the exception is "javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type application/json and type class java.io.InputStream".

If I don't add this  implementation 'io.quarkus:quarkus-rest-client' in my build.gradle "dependencies" section.
The implementation "com.github.docker-java:docker-java:3.1.5" works fine.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
call-back wroks and docker client executes a call-back without any exception.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
call-back works but got the error during callback: javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type application/json and type class java.io.InputStream

**To Reproduce**
1. 
Generate an application from https://code.quarkus.io/, choose Gradle as the build tool.
2. 
Extract the zip file, add implementation 'com.github.docker-java:docker-java:3.1.5' in my build.gradle "dependencies" section. 
Write a simple call-back and make sure it works fine.
3. 
Now add implementation 'io.quarkus:quarkus-rest-client' in my build.gradle "dependencies" section. 
Execute gradlew clean quarkusBuild, and Execute a new gradlew quarkusDev. 
Trigger the same call-back again, now you can see the exception in your console.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.port=3747
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
# uname -a
Linux ha-master-01 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
# java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
 - GraalVM version (if different from Java): 
19.3.1
 - Quarkus version or git rev: 
1.2.1.Final

**Additional context**
(Add any other context about the problem here.)
# build.gradle
plugins {
    id 'java'
    id 'io.quarkus'
}

repositories {
     mavenLocal()
     mavenCentral()
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-resteasy-jackson'
    implementation 'io.quarkus:quarkus-rest-client'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    
    implementation 'com.github.docker-java:docker-java:3.1.5'
    implementation 'org.eclipse.jgit:org.eclipse.jgit:v5.6.1.202002131546-r'
    implementation 'commons-io:commons-io:2.6'
    
}

group 'org.acme'
version '1.0.0-SNAPSHOT'

compileJava {
    options.compilerArgs << '-parameters'
    options.encoding = 'UTF-8'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

#ExampleResource.java with a simple call back
package com.chttl.yorozuya.lab;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.jboss.logging.Logger;

import com.github.dockerjava.api.DockerClient;
import com.github.dockerjava.api.model.PullResponseItem;
import com.github.dockerjava.core.DefaultDockerClientConfig;
import com.github.dockerjava.core.DockerClientBuilder;
import com.github.dockerjava.core.DockerClientConfig;
import com.github.dockerjava.core.command.PullImageResultCallback;

@Path("/hello")
public class ExampleResource {
    private static final Logger LOGGER = Logger.getLogger("ExampleResource");
    
    private String myDockerHost = DOCKER_SERVER_TCP;
    private String myHarborUserName = foo;
    private String myHarborPassword = foo;
    private String myEmail = foo;
    private String registryUrl = HARBOR_HTTP_URI;
    private String testImage = IMAGE;
    private String testTag = TAG;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        try {
            this.testpullFromHarborRegistry();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            LOGGER.error(e.toString());
        }
        return "hello";
    }
    
    //work
    private void testpullFromHarborRegistry() throws InterruptedException {
        DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
                .withDockerHost(this.myDockerHost)
                .withDockerTlsVerify("0")
                .withDockerCertPath(".")
                .withRegistryUsername(this.myHarborUserName)
                .withRegistryPassword(this.myHarborPassword)
                .withRegistryEmail(this.myEmail)
                .withRegistryUrl(this.registryUrl)
                .build();
        DockerClient dockerClient = DockerClientBuilder.getInstance(config).build();
        LOGGER.info("pulling");
        dockerClient.pullImageCmd(this.testImage)
          .withTag(this.testTag).exec(new PullImageResultCallback(){
              @Override
              public void onNext(PullResponseItem item) {                  
                  super.onNext(item);
              }
          }).awaitCompletion();
        LOGGER.info("pull done");
    }
}

**Comment by geoand** [comment]
This would be fixed by using `io.quarkus:quarkus-rest-client-jackson` or `io.quarkus:quarkus-rest-client-jsonb`
