### ISSUE TITLE
Duplicated flags between container creation and Kubernetes extension

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#7372]
I was reading the documentation of container creation extension (https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/container-image.adoc) and kubernetes extension (https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/kubernetes.adoc) 

Then I have seen that there are some properties that are duplicated, for example, the one for the group.

In container ext. `quarkus.container-image.group` in Kubernetes extension `kubernetes.group` so if I want to create a  container image and generate/deploy kubernetes resources, I need to set both properties twice. Is there any reason for that? I think that `quarkus.container-image.group` could be used in both cases.

**Comment by geoand** [comment]
cc @iocanel

**Comment by geoand** [comment]
Are you sure you need to set both? 

IIRC, only setting `quarkus.container-image.group` will get you what you want.

The reason we have this field is that the container-image extension(s) can be used without the Kubernetes extension if all you want to do is create a container image

**Comment by lordofthejars** [comment]
Maybe you don't need both but still, both are there so the user might be confused. So I think that all these flags should be named in the same way.

**Comment by geoand** [comment]
Well, that's tricky because like I said that are more than one scenarios that we need to cover. I think if we just emphasise on using `quarkus.container-image.group` and mention that the `kubernetes.group` (now the proper use is `quarkus.kubernetes.group`) is just as an override if the users don't want to use the same value as the container image, we should be fine

**Comment by lordofthejars** [comment]
Then I agree :)

BTW docs are not updated with the new prefix :) https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/kubernetes.adoc just in case you didn't notice it hehehe

**Comment by geoand** [comment]
Thanks for checking! We definitely plan to go over the docs multiple times between now and Final and make sure everything is in place.
One reason we haven't done so yet is that @iocanel is on a roll with multiple PRs fixing various things :)

**Comment by geoand** [comment]
I'll close this as the values in the KubernetesConfig default to the container-image ones
