### ISSUE TITLE
Two flags for the same purpose in container image extension

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#7373]
I have noticed that there are two flags/properties which contain some overlapping:

`quarkus.container-image.build` which is used to set if the container should be built or not.

`quarkus.container-image.execution` which used to set if we want to build or build+ push. So an overlapping of functionality or am I missing something?

cc/ @iocanel

**Comment by geoand** [comment]
We indeed noticed this overlap and `quarkus.container-image.execution` has since been removed

**Comment by lordofthejars** [comment]
Ok so how you set if you want to build or you want to build and push? Are docs updated? I am checking the master branch.

**Comment by geoand** [comment]
I just opened a PR to update the docs of the container-image: https://github.com/quarkusio/quarkus/pull/7375

**Comment by lordofthejars** [comment]
Great thanks.

**Comment by geoand** [comment]
Thanks for reporting!
