### ISSUE TITLE
Upgrade awssdk from 2.10.3 to >= 2.10.24

### ISSUE THREAD

**Issue by eiden** [quarkusio/quarkus#7387]
I'm trying to integrate my quarkus application with [aws appconfig](https://docs.aws.amazon.com/systems-manager/latest/userguide/appconfig.html). 

Since appconfig is a fairly new aws service, version `2.10.3` of the awssdk does not have support for appconfig. It was [added to the awssdk](https://github.com/aws/aws-sdk-java-v2/commit/cf3ea7d0161e5221cfe4979ce878308e0c7da433#diff-76e56151d5d431d0903dd021fc705052) in version `2.10.24`.

It would be great if you could bump the version of the [`awssdk` dependency](https://github.com/quarkusio/quarkus/blob/master/bom/runtime/pom.xml#L142) to >= `2.10.24`.

**Comment by machi1990** [comment]
@eiden I have opened #7402.
