### ISSUE TITLE
Duplicate key value

### ISSUE THREAD

**Issue by jefrog1844** [quarkusio/quarkus#7401]
When using import.sql to pre-load the database, subsequent inserts to a previously populated table experience a duplicate key error.  Table was pre-populated with entires with id ranging from 1-14

**Expected behavior**
1. Hibernate/Panache would use the next available primary key as 15 instead of defaulting to 1 and incrementing by 1

**Actual behavior**
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "block_pkey"
  Detail: Key (id)=(15) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:85)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)

**To Reproduce**
1. specify an import.sql script to preload a table with id of 1,2,3,4,...14
2. use PanacheEntity to persist a new entity
3. Hibernate error as shown above
4. Once NextValue is 15, persist() is successful.

**Configuration**
```properties
quarkus.http.port=9080
quarkus.http.root-path=/podfx/resources

quarkus.datasource.url = jdbc:postgresql://localhost:5432/podfx
quarkus.datasource.driver = org.postgresql.Driver
quarkus.datasource.username =  podfx
quarkus.datasource.password = 

quarkus.datasource.max-size=8
quarkus.datasource.min-size=2

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=https://com.jdr.podfx
com.podfx.jwt.audience=podfx-users
com.podfx.jwt.jti=a-123
com.podfx.jwt.claims.groups=create,read,update,delete


quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS, HEAD

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: CYGWIN_NT-6.1 EMAA2AU00698KL 3.0.7(0.338/5/3) 2019-04-30 18:08 x86_64 Cygwin
 - Output of `java -version`: java version 1.8.0_201
 - GraalVM version (if different from Java): not installed
 - Quarkus version or git rev: 1.2.0.Final

**Additional context**
(Add any other context about the problem here.)

**Comment by jefrog1844** [comment]
Just found this related article stating that imports do not increment the hibernate_sequence.

https://stackoverflow.com/questions/37511719/hibernate-duplicate-key-value-violates-unique-constraint

Is this the expected behavior to make sure the sequence is correctly set?

**Comment by jefrog1844** [comment]
I will reset the sequences in the load script or assign uuid in code as I do not believe this is a quarkus issue.

**Comment by thejibz** [comment]
You can use **nextval('hibernate_sequence')** in your import.sql as in:

`INSERT INTO ticket(id, name,seat) VALUES (nextval('hibernate_sequence'), 'Phantom of the Opera','11A')`

It will increment the DB sequence when inserting rows.

Source: http://www.mastertheboss.com/soa-cloud/quarkus/managing-data-persistence-with-quarkus/
