### ISSUE TITLE
CDI beans with array type result in warning.

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#7403]
Adding a producer like:

    @Produces
    String[] produce() {
        return new String[0];
    }

results in:

2020-02-25 16:47:35,774 WARN  [io.qua.arc.pro.BeanArchives] (build-14) Failed to index [Ljava.lang.String;: Stream closed
2020-02-25 16:47:35,774 INFO  [io.qua.arc.pro.IndexClassLookupUtils] (build-14) Class for name: [Ljava.lang.String; was not found in Jandex index. Please ensure the class is part of the index.

**Comment by mkouba** [comment]
Is the declaring bean somewhat special? I've tried to add this reproducer to the [config quickstart](https://github.com/quarkusio/quarkus-quickstarts/blob/master/config-quickstart/src/main/java/org/acme/config/GreetingResource.java) and I can't see the warning. I've also tried to add an interceptor binding with no success.

**Comment by stuartwdouglas** [comment]
Actually I first saw this with a bean added by an extension, and just realised I probably still had that code locally when I tried to test.

**Comment by mkouba** [comment]
Eh?

**Comment by stuartwdouglas** [comment]
I was thinking this may have been caused by my local changes, but it is an issue, to reproduce you also need:

    @Inject
    String[] args;

**Comment by mkouba** [comment]
I see. In this case, it's about injection point validation...
