### ISSUE TITLE
Asynchronous container filters

### ISSUE THREAD

**Issue by Meemaw** [quarkusio/quarkus#7405]
**Describe the bug**
I was trying to implement asynchronous container filters. Following the guide from [here](https://developer.jboss.org/en/resteasy/blog/2018/06/18/new-asynchronous-container-filters?_sscc=t&fbclid=IwAR2OJgpzADZ6r_YIDNaxAK-Lw4jK6O9rS7B06eYq2F4AvrOheKZqs6Tjj68) I was able to suspend the request, but it failed when trying to resume it with `org.jboss.resteasy.spi.ApplicationException: javax.enterprise.context.ContextNotActiveException suspendable context jboss`

**Expected behavior**
One should be able to use asynchronous container filters and suspend/resume rqeuest.

**Actual behavior**
Request throws on resume().

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin MacBook-Pro-7.local 18.7.0 Darwin Kernel Version 18.7.0
 - Output of `java -version`: openjdk version "13" 2019-09-17
 - Quarkus version or git rev: 1.2.1 Final

**Comment by stuartwdouglas** [comment]
@FroMage does MP context propagation support this properly with RESTEasy now?

**Comment by FroMage** [comment]
I don't think so, so. I believe ATM only the RESTEasy context is propagated but we should fix this.

**Comment by Meemaw** [comment]
Any update on this cc @stuartwdouglas @FroMage ?

**Comment by FroMage** [comment]
No, sorry, no update ATM.

**Comment by geoand** [comment]
I'm going to go ahead and close this as we have a much better solution in RESTEasy Reactive, see https://quarkus.io/guides/resteasy-reactive#request-or-response-filters
