### ISSUE TITLE
Camel Kafka Producer gets Stuck with RESTEasy Endpoint

### ISSUE THREAD

**Issue by bframke** [quarkusio/quarkus#7409]
We are currently trying to setup a Camel Kafka Producer to put Messages into a Kafka via a ProducerTemplate. When we try to send some Events over the RESTEasy Endpoint it gets stuck after a short while. Like sending 100 Messages and only 53 Reach the Kafka and then the Application no longer responses.

When we do not use a RESTEasy Endpoint it works like a charm and we can send 1000 Messages in a few milliseconds without the Application getting stucked.

I had first opened an issue on Camel-Quarkus side, but now it is clear that the Problem comes from RESTEasy. 
[Camel-Quarkus 743](https://github.com/apache/camel-quarkus/issues/743)

**Test-CURL**
`for i in {1..100}; do echo "$i"; curl -v -d '{"Event": "Event $i" }' -H "content-type: application/json" http://localhost:8081/topic/curltopic3/event; done`

**RESTEasy Endpoint**
```
    @Inject
    CamelMain _camelMain;
    private CamelContext _currentContext;

    @Inject
    ProducerTemplate _producerTemplate; 

    @POST
    @Path("topic/{topicId}/event")
    @Consumes(MediaType.APPLICATION_JSON)
    public Response sendEventToTopic(String body,
                         @PathParam("topicId") String topic,
                         @Context HttpHeaders httpHeaders) throws Exception {
        Map<String, Object> headers = new HashMap<>();
        Map<String, Object> innerHeaders = new HashMap<>();

        filterKafkaHeaders(httpHeaders, innerHeaders);
        createStandardHeadersIfNeeded(innerHeaders);

        headers.put(KafkaConstants.PARTITION_KEY, "0");
        headers.put(KafkaConstants.KEY, "1");
        headers.put(KafkaConstants.OVERRIDE_TOPIC, topic);

        _logger.info("keaders for kafka: {}", headers);
        _logger.info("headers for payload: {}", innerHeaders);
        _logger.info("payload: {}", body);

        MessageEnvelope message = new MessageEnvelope(innerHeaders, body);

        if(_currentContext == null) {
            _currentContext = _camelMain.getCamelContext();
        }

        if(_currentContext.getRoute(topic) == null) {
            RoutesBuilder builder = new RouteBuilder() {
                @Override
                public void configure() {
                    from("direct:" + topic).
                            id(topic).
                            log("${body}").
                            to("kafka:"+topic+"?brokers="+_brokerList);
                }
            };

            _currentContext.addRoutes(builder);
            Thread.sleep(200);
        } else {
            _logger.info("Reusing Route for Topic: {}", topic);
        }

        _producerTemplate.start();
        _producerTemplate.sendBodyAndHeaders("direct:" + topic, message, headers);
        _producerTemplate.stop();

        return Response.ok(Response.Status.OK.toString()).build();
    } 
```

**Comment by geoand** [comment]
cc @cescoffier

**Comment by bframke** [comment]
Well it looks like logging is the problem here. After doing the rebuild to route only with processor we checked with Visual-VM and saw that one Thread just gets stuck on writing out to log.

We tried the Camel Logging Component and SLF4J-Logger and both got the Thread stuck at some point. Without logging it works fine.

**Comment by geoand** [comment]
Closing as it does not look like it's a Quarkus issue as per the comment above
