### ISSUE TITLE
@PermitAll allows unauthenticated users with JWT enabled

### ISSUE THREAD

**Issue by garrettahines1** [quarkusio/quarkus#7428]
**Describe the bug**
I have the quarkus smallrye JWT enabled. On my REST endpoints, I have the `@PermitAll` annotation. If I send a rest call with Authorization type as Bearer and an invalid JWT, it correctly verifys the JWT and doesn't allow me in. If I send in a request with no authorization type then it lets me hit the end point successfully.

**Expected behavior**
I would think if it verifies the JWT if one is present, it shouldn't allow me to hit the endpoint if none is present.

**Actual behavior**
Successfully hits the endpoint with no JWT in request.

**To Reproduce**
1. Enable quarkues smallrye jwt
2. Hit rest endpoint with no authorization

**Configuration**
```properties
quarkus.smallrye-jwt.auth-mechanism=MP-JWT
quarkus.smallrye-jwt.enabled=true
```

**Environment (please complete the following information):**
 - Output of `java -version`: 11.0.2
 - Quarkus version or git rev: 1.0.1.Final

**Additional context**
This could be intended behavior by the `@PermitAll` annotation but doesn't seem like it should be. Let me know if it is.

**Comment by sberyozkin** [comment]
@garrettahines1 `quarkus.smallrye-jwt.enabled=true` does not mean that a token must be available, it is set to `true` by default and can be set to `false` to disable the whole module functionality.
If you need to ensure that only the requests with the vaild tokens can go through (and restrict as needed using the roles) then adding `@Authenticated` annotation should do. Can you try it please ?

**Comment by sberyozkin** [comment]
@garrettahines1 You may need to update to the latest tag to verify it works

**Comment by garrettahines1** [comment]
ok, good to know, feel free to close issue.

**Comment by sberyozkin** [comment]
Hi @garrettahines1 Thanks, please create a new one if adding the `Authenticated` annotation won't help :-), cheers
