### ISSUE TITLE
OIDC extension fails with Mac OS but works in Linux

### ISSUE THREAD

**Issue by moksamedia** [quarkusio/quarkus#7446]
Using Quarkus and the OIDC extension, it works fine in Linux (on multiple systems) with various Java versions. However, on OSX with Java 8 and Java 11, we get too many redirects. Exact same code and OIDC provider.

Using Quarkus 1.3.0.Alpha2 (also tested with Alpha1)

Any ideas?

**Comment by sberyozkin** [comment]
Hi @moksamedia A fix has just got in today to the master preventing the redirect loops, we've been seeing them with HtmlUnit in CI builds sometimes. The primary cause for such redirects is a missing state cookie by the time the user has been redirected back to Quarkus. It might well be an OSX browser cookie manager's policies which are affecting it. 
Please verify with the latest master code or wait till 1.3.0 RC1 is out which is due soon. if the underlying issue persists then you'd get 401 with some relevant debug level log information.
Let us know how it goes please

**Comment by moksamedia** [comment]
@sberyozkin I should have mentioned that this is on 1.3.0.Alpha2

**Comment by sberyozkin** [comment]
@moksamedia FYI `quarkus.oidc.authentication.cookie-path` has also been introduced, the state cookie may not be available if the user is redirected back to the path which has a root different to the original one, for example, the flow started when the user tried to access `/a/b` but is returned to `/c/d/` after the authentication, so setting this property to `/` in this case would help...

**Comment by moksamedia** [comment]
We're using the root directory.

```
quarkus.oidc.auth-server-url=https://dev-123456.okta.com/oauth2/default
quarkus.oidc.client-id={redacted}
quarkus.oidc.credentials.secret={redacted}
quarkus.oidc.authentication.scopes=openid,profile
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.redirect-path=/
```

**Comment by sberyozkin** [comment]
OK, that looks fine. Yes, have a look please at the debug log when 401 occurs in OCX. It does not mean the OCX policy is buggy, might be just stricter. Or it treats max-age wrongly, etc. If needed we can support for more cookie properties like domain, etc

**Comment by sberyozkin** [comment]
@moksamedia Can you please test 1.3.0.CR1 ? By the way, with your configuration, `quarkus-oidc` will try to restore the original request URI which involves another redirect under the hood (adding `restore-path-after-redirect=false` will always return the user to the `redirect-path` itself). So having a `cookie-path` set to `/` may make sense in this case.

**Comment by moksamedia** [comment]
@sberyozkin I tried it this weekend with my older mac running High Sierra 10.13 and Java 11 and 1.3.0.A1 and 1.3.0.CR1 both worked. I'll ask my coworker with his more recent mac to try CR1.

**Comment by sberyozkin** [comment]
@moksamedia Thanks, please retry with `1.3.0.Final` and then we can close this issue

**Comment by mraible** [comment]
@sberyozkin I've been working with @moksamedia on this problem. I tried with 1.3.0.Final and IT WORKS!! Happy Friday! 😃🎉

**Comment by sberyozkin** [comment]
@mraible @moksamedia Happy to hear it, thanks
