### ISSUE TITLE
OIDC Connection-Delay config parameter doesn't work

### ISSUE THREAD

**Issue by JohnHorman** [quarkusio/quarkus#7447]
**Describe the bug**
If the quarkus.oidc.connection-delay configuration parameter startup fails right away if the OIDC server is not (yet) available instead of retrying for the configured delay period.

**Expected behavior**
If the OIDC identity provider (IDP) is not available, I expect that the quarkus OIDC setup to retry the connect every 2 seconds until the configured delay has expired.  If the IDP is available then quarkus server should start immediately.

**Actual behavior**
Message is logged "Failed to start quarkus" with a stack trace with a root "caused by" java.net.ConnectException: Connection refused: no further information

**To Reproduce**
1. Ensure IDP server is not running
2. Start Quarkus app: I used Eclipse Maven launch:  clean install quarkus:dev 

**Configuration**
```properties
quarkus.http.port=8080


quarkus.arc.remove-unused-beans=framework


# DEBUG console logging
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] %s%e%n
quarkus.log.console.level=TRACE
quarkus.log.console.color=false

# TRACE file logging
quarkus.log.file.enable=true
quarkus.log.file.path=/tmp/quarkus.log
quarkus.log.file.level=TRACE
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}]] (%t) %s%e%n

quarkus.log.level=INFO

# OpenID Connect properties -- depends on io.quarkus:quarkus-oidc 
quarkus.oidc.enabled=true
quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=http://localhost:9090/auth/realms/Quarkus
quarkus.oidc.client-id=quarkus
quarkus.oidc.credentials.secret=592a1849-3bc1-4cdb-92aa-4556f99a3a5a

quarkus.oidc.connection-delay=PT30S

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18362.657]
 - Output of `java -version`: 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
 - GraalVM version (if different from Java): (not run under GraalVM)
 - Quarkus version or git rev: 
		<quarkus.version>1.2.1.Final</quarkus.version>

**Additional context**
Dependency at issue is io.quarkus:quarkus-oidc
OIDC IDP server was keycloak.  

When debugging I observed (what I assume to be) the problem in `OidcRecorder.java` in the section of code between lines 91 and 119 (as of the most recent commit) which is a `for` loop.  In particular the catch clause is incorrect (i believe).  It tries to catch an `OIDCException`, however what is actually being thrown is a `java.util.concurrent.CompletionException`, which wraps the OIDCException.  This exception is thrown from the `cf.join()` at line 105.

Here is the code I am referring to starting at line 91 of `OidcRecorder.java`:

        for (long i = 0; i < connectionRetryCount; i++) {
            try {
                CompletableFuture<OAuth2Auth> cf = new CompletableFuture<>();
                KeycloakAuth.discover(vertx, options, new Handler<AsyncResult<OAuth2Auth>>() {
                    @Override
                    public void handle(AsyncResult<OAuth2Auth> event) {
                        if (event.failed()) {
                            cf.completeExceptionally(toOidcException(event.cause()));
                        } else {
                            cf.complete(event.result());
                        }
                    }
                });

                auth = cf.join();
                break;
            } catch (OIDCException ex) {
                if (i + 1 < connectionRetryCount) {
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException iex) {
                        // continue connecting
                    }

                } else {
                    throw ex;
                }
            }
        }

**Comment by sberyozkin** [comment]
@JohnHorman Thanks, I nearly sure I was sitting with the clock measuring it when adding this code :-) but obviously I've missed it :-). I've copied the code from the existing Vertx recorder to address this problem, see #7448, thanks

**Comment by JohnHorman** [comment]
@sberyozkin No worries.  Thanks for picking this up this quickly! 👍
