### ISSUE TITLE
An annotated TemplateExtension class, if renamed, is not deleted from target/wiring-devmode folder

### ISSUE THREAD

**Issue by nicmarti** [quarkusio/quarkus#7464]
**Describe the bug**
This is related to Qute template Engine. If you annotate a class in package `org.foo` with @TemplateExtension then launch Quarkus, then move this class to another package, say `org.foo2`, Quarkus won't clean-up the generated .class file in the target/wiring-devmode subfolder

**Expected behavior**
It should clean-up  the generated class file.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
The XXX_ValueResolver class file is not deleted

**To Reproduce**
1. Create a template with Qute
2. Create a org.foo.Price simple class 
3. Annotate this class with @TemplateExtension
4. Launch Quarkus in dev mode, check that Quarkus generates the file target/wiring-devmode/org/foo/Price_ValueResolver.class
5. Rename or move the org.foo.Price 
6. Reload Quarkus
7. Observe that the new Price file is correctly generated (that is expected)
8. ... however the old  target/wiring-devmode/org/foo/Price_ValueResolver.class is not deleted

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin Fountainhead2.localdomain 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
       
 - Output of `java -version`: 
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit GraalVM CE 19.3.1 (build 25.242-b06-jvmci-19.3-b07, mixed mode)

 - GraalVM version (if different from Java): 

 - Quarkus version or git rev: 
1.2.0Final

**Additional context**

As a workaround you can of course use "mvn clean quarkus:dev".

**Comment by mkouba** [comment]
@nicmarti could you pls verify it's still a problem with v1.3.1 or master?

**Comment by nicmarti** [comment]
Sure, will do a test :)

**Comment by nicmarti** [comment]
@mkouba you can mark this issue has resolved. I tested with 1.3.1.Final and I cannot reprodue the issue.

The generated file in target/wiring-devmode folder does not exist anymore.

**Comment by mkouba** [comment]
Great! Thanks for confirmation.
