### ISSUE TITLE
Quarkus is not handling annontation @Interceptors properly when 1 or more classes are declared in it.

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#7465]
There is a common thread between this issue and 
  - https://github.com/quarkusio/quarkus/issues/7292 Quarkus is not handling 
        annontation @JsonSubTypes properly
  - https://github.com/quarkusio/quarkus/issues/7293 Quarkus is not handling 
        annontation @JsonView properly

All three of these are annotations which allow 1 or more classes to be declared
within them.  The declared classes are not handled properly.

In standard resteasy testing which uses wildfly, application of the classes 
specified in annotations @JsonSubTypes and @JsonView are handled by 
org.eclipse.yasson.  My guess is @Interceptors are similarly handled.
Quarkas is not handling this.

Project https://github.com/rsearls/quarkus-Interceptors-annotation.git
demonstrates the issue.

Follow the directions in the proejcts README file for setup and run instructions

Execution env.
    jdk 11.0.2
    mvn 3.6.0
    quarkus 999-SNAPSHOT

This test has many supporting classes.  The classes of interest are
  InterceptorTest
  InterceptorBookReader
  InterceptorOne
  InterceptorTwo
  InterceptorResource
  InterceptorVisitList    ;; maintains a static array which is referenced in this test

Set breakpoints in 
  InterceptorVisitList line 9
  InterceptorTest line 104, 111, 119
  InterceptorResource 89, 148

run test

InterceptorTest line 104
  classes with @Interceptor annotation and no class declared in it are
  registered with InterceptorVisitList

InterceptorTest line  111  same as above

InterceptorTest line  119   InterceptorResource endpoint test() (line 88) is
executed.  The count of expectedList entries is wrong because classes
InterceptorOne and  InterceptorTwo have not been add to the list as expected.

**Comment by geoand** [comment]
cc @mkouba @manovotn

**Comment by manovotn** [comment]
@geoand we do not support `@Interceptors` annotation. The only supported way of interceptor declaration is via `@Interceptor` along with `@InterceptorBinding`

This is mentioned in the CDI reference guide - https://quarkus.io/guides/cdi-reference#limitations

**Comment by mkouba** [comment]
Yes, the EJB-style of association via `@javax.interceptor.Interceptors` is not supported at all.

**Comment by geoand** [comment]
Understood, thanks.

So let's close this
