### ISSUE TITLE
Conflicts when multiple container-image modules are present

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#7484]
If we have more than one container-image modules present, for example `container-image-s2i and `container-image-jib` the following error occurs:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project kubernetes-quickstart: 
Failed to build quarkus application: io.quarkus.builder.ChainBuildException: 
Multiple producers of item class io.quarkus.container.spi.ContainerImageResultBuildItem 
(io.quarkus.container.image.s2i.deployment.S2iProcessor#s2iBuildFromJar):
This is the location of the conflicting producer 
(io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar) -> [Help 1]
```

It would be nice if we could provide a better message.
Also it would be nice if we could enable, disable or explicitly select one of the two using configuration.

**Comment by geoand** [comment]
For now I think we just need to be explicit in the docs

**Comment by geoand** [comment]
We could also make `ContainerImageResultBuildItem` a `MultiBuildItem` and handle things ourselves. How does that sound?
