### ISSUE TITLE
Support non s2i Openshift deployments

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#7486]
At the moment the generated manifests for Openshift are generated with `s2i` in mind.
We need to make sure that even if we perform a `docker` /  `jib` build and push things still going to work as expected.

**Comment by cricket007** [comment]
Link https://github.com/GoogleContainerTools/jib/issues/1555

**Comment by geoand** [comment]
This is related to #10055

**Comment by geoand** [comment]
This has long been implemented, so I'm closing it
