### ISSUE TITLE
Cannot disable Keycloak policy enforcement for root path

### ISSUE THREAD

**Issue by maehld** [quarkusio/quarkus#7491]
**Describe the bug**
I want to implement a Quarkus application that hosts its SPA at / and its API at /api. I also want to use Keycloak for controlling API access. When I create an application.properties file like this, it ignores the root path configuration. It is working perfectly for the specific paths. Removing the * does not help. It seems as if specifing a root path is not working.

quarkus.keycloak.policy-enforcer.enable=true

quarkus.keycloak.policy-enforcer.paths.1.name=Root
quarkus.keycloak.policy-enforcer.paths.1.path=/*
quarkus.keycloak.policy-enforcer.paths.1.enforcement-mode=DISABLED

quarkus.keycloak.policy-enforcer.paths.2.name=API
quarkus.keycloak.policy-enforcer.paths.2.path=/api/*
quarkus.keycloak.policy-enforcer.paths.2.enforcement-mode=ENFORCING

quarkus.keycloak.policy-enforcer.paths.3.name=Public
quarkus.keycloak.policy-enforcer.paths.3.path=/hello
quarkus.keycloak.policy-enforcer.paths.3.enforcement-mode=DISABLED

**Expected behavior**
Everything that is not at /api should be accessable anonymously.

**Actual behavior**
/hello is, but / is not.

**To Reproduce**
1. Following the keycloak-integration example at quarkus.io 
2. Use the application.properties from above
3. Try to access / without a valid Bearer-Token
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10 
 - Output of `java -version`: OpenJDK 11
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.2.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by sberyozkin** [comment]
@pedroigor Hi Pedro, do we need a path selection algorithm/property here when multiple paths are overlapping ?

**Comment by pedroigor** [comment]
The policy enforcer has its own path matcher algorithm. I might be an issue there, I'll check it out.

**Comment by pedroigor** [comment]
Created https://issues.redhat.com/browse/KEYCLOAK-13175. We could fix in Quarkus, but better is just return the path configuration defined in the application configuration.

The problem here is that the policy enforcer is trying to fetch the resource/path from Keycloak even though the path is already defined in the application configuration. When doing that, the enforcer mode is list is set to `ENFORCING`.

**Comment by pedroigor** [comment]
@maehld Could you please try removing the `URI` from the `Root` resource (in Keycloak)? That should make the policy enforcer to not resolve the root resource from Keycloak based on the path and use the configuration you defined in your configuration.

**Comment by pedroigor** [comment]
@sberyozkin I've sent https://github.com/quarkusio/quarkus/pull/7534. This one tries includes a test for this scenario as well as a minor change to the configuration (making a property optional).

One we have KEYCLOAK-13175 merged, we can update tests accordingly.

Right now, tests are checking if the workaround I proposed in my last comment works (removing the URI from the resource).

**Comment by maehld** [comment]
@pedroigor Maybe I'm not getting Keycloak just yet. I had no Root Resource in Keycloak. But even creating one and not setting an URI did not help. I can post you the Keycloak config tomorrow if you would like to take a look at it.
