### ISSUE TITLE
dekorate will not generate kubernetes/knative resource without quarkus-resteasy dependency

### ISSUE THREAD

**Issue by Frintrop** [quarkusio/quarkus#7496]
if  you inlude 

```
<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-kubernetes</artifactId>
		</dependency>
```
without 
```
<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy</artifactId>
		</dependency>
```

dekorate will not be registered and no kubernetes/knative resources will be generated.

**Comment by geoand** [comment]
Quarkus only generates Kubernetes resources for http based services. If you don't include `quarkus-resteasy` but include `quarkus-vertx.web` it will still generate them.

This is by design. When the ability to run simple command line applications lands in Quarkus, we should revisit this

**Comment by geoand** [comment]
cc @iocanel
