### ISSUE TITLE
Best Practice for writing reactive rest endpoint

### ISSUE THREAD

**Issue by BigFatDog** [quarkusio/quarkus#7500]
I'm writing a reactive rest endpoint that gets data from `mongodb`. 

I have read related tutorial and sample code from `Quarkus`. I'm still confused and want to know if my understandings are correct:

The code below is slightly modified from `quarkus quickstart`:

```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("{name}")
    public CompletionStage<Fruit> greeting(@PathParam String name) {
        // When complete, return the content to the client
        CompletableFuture<String> future = new CompletableFuture<>();


        // find fruit from mongodb
        final Fruit fruit = xxxService.getFruit(name);

        future.complete(fruit);

        return future;
    }
```
1. Both `@Path` and `@Route` work for reactive rest endpoint, the difference is `@Route` implicitly indicates the implementation is non-blocking. 

```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Route("{name}")
    public void greeting(@RouteExchange ex) {
    	final String name = ex.getParam("name");
        // When complete, return the content to the client
        CompletableFuture<String> future = new CompletableFuture<>();


        // find fruit from mongodb
        final Fruit fruit = fruitService.getFruit(name);

        future.complete(fruit);
		ex.ok(future);
    }
```
Should I still use `CompletableFuture` in combination with `ex.ok`?

2. The `fruitService` accesses to `mongodb`. Since my rest controller is already in reactive mode, both regular `MongoClient` and `ReactiveMonogoClient` should work. My rest endpoint is eventually reactive. If this is true, then I can directly use `quarkus-mongodb-panache` even it doesn't provide a reactive mongodb client. but my rest endpoint is still reactive.

Thank you.

**Comment by loicmathieu** [comment]
In the upcomming 1.3 release, a reactive MongoDB with Panache will be integrated, it will be a lot easier to develop application accessing MongoDB with it.

With the current version, you should use the `ReactiveMongoClient` to be fully reactive.

For the question `@Route` versus `@Path`, as I understand it `@Path` is for REST service via Resteasy and `@Route` is for reactive route via Vert.X so it depends what you wan to do. Maybe @cescoffier can give a better explaination for this ...

**Comment by BigFatDog** [comment]
Thank you, `Reactive Mongo Panache` is what I'm looking for. For now I think the best strategy for me is to use `Mongo Panache` directly, because migrating from `Mongo Panache` to `Reactive Mongo Panache` should be easier than from `Reactive Mongo Client`.

I understand your explanation on `@Route` and `@Path`.  My confusion is: when I use `CompletableFuture` to accomplish reactive rest endpoint, according to Quarkus doc, using either of the two won't change the reactive nature of my rest endpoint. I want to know if there's any difference other than coding style and learn the best practice.

I do have one more question and I hope it is OK for me to post here:
`@Route`'s coding style and the philosophy of *multiple* event loop thread look quite similar to `expressjs`.  Does it mean the endpoints of `expressjs` are already reactive by nature?

I find out resources regards with the topic of building reactive endpoint with `expressjs` (e.g. [marblejs](https://github.com/marblejs/marble) ) are quite *limited*, therefore I guess part of `Quarkus`'s reactive approach has been already addressed by `expressjs` in nodejs services.  I'm not sure if I'm on the right track.

**Comment by loicmathieu** [comment]
Well, if you plan to go to Reactive MongoDB with Panache, 1.3.0.CR1 will be released in a few days so you will be able to refactor you code with it.

Regarding your questions around expressjs, I was not aware this is multiple event loops (I would expect a single one as with nodejs), anyway, Quarkus event loop is based on Vert.X so if you want to understand it more you should have a look at the Vert.X documentation.

In the next release (1.3) their will be more documentation around reactive applications due to an upcomming change of implementation, I think it will be interesting to read the new documentation :)

If the explaination are OK for you, and the solution of waiting for 1.3 for Reactive MongoDB with Panache is OK can you close the issue ?

**Comment by BigFatDog** [comment]
Thank you.  `expressjs` is single thread event loop. I should have mentioned clearly.

Your answer is good enough to me. Thank you again for your reply. 
I'd close this issue immediately since question has been answered.
