### ISSUE TITLE
ArC - register client proxies and subclasses for reflection if needed

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#7507]
Currently, client proxies and subclasses are not registered for reflection. However, sometimes it could be useful to be able to pass a client proxy/subclass of a bean into a third-party library that makes use of reflection at runtime, e.g. to serialize a bean instance to XML/JSON/etc.

The simplest possible implementation would be to register the generated classes if the bean class declares `@RegisterForReflection` ...

**Comment by mkouba** [comment]
FYI @manovotn

**Comment by mkouba** [comment]
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Native.20reflection

**Comment by manovotn** [comment]
> The simplest possible implementation would be to register the generated classes if the bean class declares @RegisterForReflection ...

That's good starting point, but it's not 100% (not that I would know how to make it always work apart from always having reflection access which defeats the purpose).

Also, this is fine for proxies, how about interceptor subclasses? For something like intercepted dependent bean, we will need to register the subclass as well. However, a subclass consumed only by proxied beans wouldn't need it, right?

**Comment by mkouba** [comment]
> That's good starting point, but it's not 100%...

Sure it's not. It's the "simplest" solution...

> However, a subclass consumed only by proxied beans wouldn't need it, right?

An intercepted dependent bean does not have a client proxy. That's why we need to register the generated subclass as well. Also a user can obtain a subclass instance directly from the context (or via `ClientProxy#arc_contextualInstance()`).

**Comment by manovotn** [comment]
> An intercepted dependent bean does not have a client proxy.

Yeah, that's what I said. My point was, if we were able to say that some subclass is only used for normal-scoped (e.g. proxied) beans, you needn't register that for reflection. But I am probably overthinking it.

**Comment by mkouba** [comment]
>  you needn't register that for reflection

You need to, because a user can "unwrap" the proxy.

**Comment by manovotn** [comment]
> user can "unwrap" the proxy

Well, there is a always a way to shoot yourself in the foot :-D

**Comment by dufoli** [comment]
My initial through was if interface used for proxy is registered for reflection all implementation must be registered too. Just my 2 cents

**Comment by dufoli** [comment]
@mkouba  what is remaining here ? an attribute for proxy like 
```
@RegisterForProxy(interface1.Class,interface2.class)
public class MyInvocationHandler implements InvocationHandler
    Object invoke(Object proxy,
            Method method,
            Object[] args)
              throws Throwable {
    }
}
```
 is not

**Comment by manovotn** [comment]
@dufoli To make what Martin suggested work, we'd need to browse discovered beans and inspect their annotations via `AnnotationStore`. If any of the classes in bean hierarchy has the `@RegisterForReflection` annotation, we keep track of it.
Later on, when generating proxies, we can register the proxy class for reflection as well. I am not sure if slapping an annotation on generated class does it or if we need to also do this via processor, but it should be doable.

**Comment by mkouba** [comment]
>  I am not sure if slapping an annotation on generated class does it or if we need to also do this via processor, but it should be doable.

I think that we'll have to produce a `ReflectiveClassBuildItem` for each relevant class.

**Comment by vsevel** [comment]
hello, do you think this point may progress, as this seems to be a prerequisite for a clean solution for https://github.com/quarkiverse/quarkus-cxf/issues/346?

**Comment by mkouba** [comment]
> hello, do you think this point may progress, as this seems to be a prerequisite for a clean solution for [quarkiverse/quarkus-cxf#346](https://github.com/quarkiverse/quarkus-cxf/issues/346)?

Do you need the proxies or intercepted subclasses to be registered? I think that we should probably register all subclasses by default because a subclass is the "contextual instance" (the instance stored in the context) if interceptors are used.

**Comment by vsevel** [comment]
hello @mkouba. only proxies subclasses it seems. do you confirm @shumonsharif?
/cc @odellamaggiore

**Comment by shumonsharif** [comment]
Hi @mkouba @vsevel I'm not familiar enough with the internals of the security annotations, eg. `@RolesAllowed`.  Is there some way to easily confirm whether the subclasses are proxies or intercepted; the issue only happens with security annotations?  Either way, seems like all subclasses would need to be registered?

**Comment by mkouba** [comment]
Just to make it clear - ArC can generate two kinds of classes for a bean:
- client proxy; implements `io.quarkus.arc.ClientProxy`
  - basically an object that delegates all method invocations to a target bean instance
  - every normal scoped bean has a client proxy
  - client proxies are injected as dependencies
- intercepted subclass; implements `io.quarkus.arc.Subclass`
  -  extends the bean class and is _stored in the context_ for any bean that has interceptors associated
  - if a bean is also normal scoped the client proxy delegates calls to a subclass instance

> Either way, seems like all subclasses would need to be registered?

It depends on you use case. However, since the subclass instance is the "bean instance" (the object that sits in the context) it's probably the bare minimum. For client proxies you can always obtain the underlying instance via `io.quarkus.arc.ClientProxy.arc_contextualInstance()`.

@manovotn @Ladicek WDYM?

**Comment by manovotn** [comment]
From this discussion and the linked issue it seems to me that the only thing we need to register for reflection are intercepted subclasses. Or am I missing something?

**Comment by Ladicek** [comment]
I'm probably just being stupid here, but I can always get hold both of the client proxy and the bean instance (which may be the subclass if the bean is intercepted or decorated). Right? So if we want to enable calling the bean's methods reflectively, both the client proxy and the subclass should be registered for reflection (if they exist).

**Comment by mkouba** [comment]
> I'm probably just being stupid here, but I can always get hold both of the client proxy and the bean instance (which may be the subclass if the bean is intercepted or decorated). Right? So if we want to enable calling the bean's methods reflectively, both the client proxy and the subclass should be registered for reflection (if they exist).

The thing is that you can easily obtain the original bean instance (be it a subclass or not) from a client proxy.

**Comment by Ladicek** [comment]
Sure I can, but why should I? The entire point of the client proxy is that I can just call its methods and everything works.

**Comment by mkouba** [comment]
> Sure I can, but why should I? The entire point of the client proxy is that I can just call its methods and everything works.

My point is that registering subclasses is the bare minimum (like I mentioned above) because there's no workaround for them. For client proxies you can apply a workaround e.g. in a json serializer lib. And to be clear - I'm talking about the bare minimum because we're talking about global registration of all subclasses/client proxies and I think that we should keep the number of registered classes minimal (or give up on quarkus goals ;-).

**Comment by Ladicek** [comment]
Oh if you're talking about registering it _globally_, for all existing beans, then that's a different question. In the first comment in this issue, you suggest that we'd only register the generated classes for reflection if the bean class is itself annotated `@RegisterForReflection`. Which makes sense, if you ask me.

**Comment by mkouba** [comment]
> Oh if you're talking about registering it _globally_, for all existing beans, then that's a different question. In the first comment in this issue, you suggest that we'd only register the generated classes for reflection if the bean class is itself annotated `@RegisterForReflection`. Which makes sense, if you ask me.

Yup, I've changed my mind in https://github.com/quarkusio/quarkus/issues/7507#issuecomment-1026591737 ;-). Anyway, scanning `@RegisterForReflection` might make sense but what about complex hierarchies? Are we going to only scan the _bean class_?

**Comment by Ladicek** [comment]
I'm pretty sure registering all subclasses of all beans for reflection, unconditionally, is going to blow up the size of the native image. Needlessly, I'd say, because for how many of those beans will reflection access actually ever happen?

When it comes to class hierarchies, IDK, I'd probably follow what we do elsewhere for `@RegisterForReflection`?

**Comment by Ladicek** [comment]
Additionally, we could/should probably expose a build item for extensions to express an interest in reflective access to specific beans?

**Comment by mkouba** [comment]
> Additionally, we could/should probably expose a build item for extensions to express an interest in reflective access to specific beans?

They should IMO just use `ReflectiveHierarchyBuildItem` and friends...

**Comment by mkouba** [comment]
> Good point. That should cover the subclass automatically, and so is probably what the CXF extension should use anyway?

+1 if they know which classes should be accessed via reflection ;-).

**Comment by shumonsharif** [comment]
Does `ReflectiveHierarchyBuildItem` discover classes both 'up' and 'down' the hierarchy?  I'm certainly happy to try it, but looking at the docs, it appears it only goes up the hierarchy - ie. superclasses are registered, but not necessarily subclasses?

**Comment by mkouba** [comment]
>  the only thing we are aware of in the CXF extension is Foo.

Well, if you're aware of `Foo` then you can find all subclasses in the index via `IndexView.getKnownDirectSubclasses()` and `IndexView.getAllKnownSubclasses()`...

**Comment by Ladicek** [comment]
If `ReflectiveHierarchyBuildItem` only traverses up, I guess I'm back to the suggestion that we should have a dedicated build item to express interest in reflective access to a given bean class. (Which would result in registering the bean class, the subclass, and the client proxy, in my opinion.) That seems best to me, because it's a lot more declarative.

**Comment by shumonsharif** [comment]
> Well, if you're aware of `Foo` then you can find all subclasses in the index via `IndexView.getKnownDirectSubclasses()` and `IndexView.getAllKnownSubclasses()`...

Yes, agreed.  That's one way to address the issue, as is the workaround we already currently have in place.  

However, I also agree with @Ladicek's comment about having a more declarative and cleaner way of doing this.  Given the CXF extension doesn't generate the subclasses, my thought was that the onus for registering those for reflective access should really fall on the subclass creator - just seems cleaner that way.

**Comment by mkouba** [comment]
> Yes, agreed. That's one way to address the issue, as is the workaround we already currently have in place.

In fact, this workaround should not work for subclasses and proxies because these classes are generated and not part of the index :-(. Anyway, I think we should add a new build item - `ReflectiveBeanClassBuildItem` and ArC will automatically register a possible generated proxy and subclass for reflection. Furthermore, a new `ReflectiveBeanClassBuildItem` will be automatically produced for a bean class annotated with `@RegisterForReflection`. 

I'm not so sure about CDI producers though. Extensions would have to produce a `ReflectiveBeanClassBuildItem` with the return type/field type of a producer to make it work. Is that acceptable? Alternatively, we could make the `ReflectiveBeanBuildItem` accept the `BeanInfo` instead and let the ArC extension decide. But this is not so flexible.

**Comment by Ladicek** [comment]
I think `ReflectiveBeanClassBuildItem` makes sense. Since this is used by Quarkus extensions, the bean in question will likely always be a class-based bean, so I wouldn't care that much about producers :-)

**Comment by manovotn** [comment]
`ReflectiveBeanClassBuildItem` sounds good. I agree with Ladislav that I wouldn't care about producers much at this point.

**Comment by shumonsharif** [comment]
@mkouba Just tested your PR with the CXF extension, works perfectly.  Thanks for the quick turnaround on this.  

I had actually experimented a little with `IndexView.getKnownDirectSubclasses()` and `IndexView.getAllKnownSubclasses()` when I had initially looked into the issue, but didn't quite understand what was going on, so assumed that I was doing something wrong.  Thanks again, look forward to this getting released.

**Comment by vsevel** [comment]
great reactivity. thanks @mkouba
