### ISSUE TITLE
.env file copy to target in dev mode

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#7519]
**Description**

When you are at dev mode and you have a file at the root of the project a `.env` file, the file is not loaded as the root directory at runtime is at `target/`.

A possible workaround is to use:

```
<build>
<resources>  
   <resource>
       <directory>${project.basedir}</directory><!-- from -->
       <targetPath>${project.build.directory}</targetPath><!-- to -->
       <includes><!-- what -->
          <include>**/.env</include>
       </includes>
    </resource> 
</resources>
</build>
```

But we could integrate this on dev mode so if there is a `.env` the file then we copy directly to `target` (I don't know if this is possible).

I know that the purpose of a `.env` is to reside outside of the project (JAR/native package) but I am thinking in the next use case:

I am demoing in front of a big audience, I have my `.env` file with my credentials to publish a docker image to quai. Then I can just say look I copy this file into root project as it has my credentials and of course, you cannot see them, and then I run mvn .... and the image is published.

I could copy directly to `target/` directory it is true, but if I do a clean then I will miss everything.

So it will be great at the plugin level to do this copy instead of having to configure `pom.xml` with the `resources` and explain to the audience why I am doing this.

**Comment by geoand** [comment]
Question: Why not have the `.env` file in `src/main/resources`? Then it would be picked up automatically, no?

**Comment by lordofthejars** [comment]
I think these files are not copied in target dir but inside an special dir
which is added to classpath.

**Comment by geoand** [comment]
Anything in `src/main/resources` should automatically be added to `target` without the user having to do anything.

So `mvn compile quarkus:dev` would automatically update the `target` directory with the latest "source" version of `src/main/resources/.env`

**Comment by lordofthejars** [comment]
No, it seems  it is not in this way, I have tried now, I copied `.env` to `src/main/resources` and the file is placed at `target/classes` so it can be picked up as classpath resource.

**Comment by geoand** [comment]
So all good?

**Comment by lordofthejars** [comment]
Nope. The `.env` should be at `target/` because of the `.env` file is loaded by using `Paths.get(System.getProperty("user.dir", "."), ".env")`

**Comment by geoand** [comment]
Oh yes, sorry, I see what you are saying

**Comment by lordofthejars** [comment]
Humm it is really strange, I am not sure if there is a bug or not. Look I share with you the project in case you see something different:

https://github.com/lordofthejars/quarkusenv

I have debugged and in the `ConfigUtils DotEnvConfig` thing I see the value correctly inserted in the map, but when the app is started I see:

```
javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: greeting.message
	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:37)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties24.deploy_0(ConfigBuildStep$validateConfigProperties24.zig:120)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties24.deploy(ConfigBuildStep$validateConfigProperties24.zig:36)
```

So it seems that the value does not end up injected correctly.

**Comment by geoand** [comment]
The config issue should be solved by #7530

**Comment by geoand** [comment]
@dmlloyd @sherl0cks since you were the ones that had the initial conversation around .dotenv, what do you think about this one?
I personally think it makes sense

**Comment by dmlloyd** [comment]
Since we're looking in `user.dir` for `.env`, I think it makes sense to make an extra effort to copy it for dev mode operation.

**Comment by sherl0cks** [comment]
@dmlloyd @geoand I'm not a dev mode user since I'm deploying to aws lambda, so keep that in mind.

That said, if the idea here is to copy the .env over to target so that dev mode works as expect, and that this is transparent to the user, this is inline with the original objective of feature, which was to support a language neutral convention.

**Comment by Legion2** [comment]
Im now getting `2020-03-30 23:00:11,392 WARN  [io.qua.dev.DevModeMain] (main) Unable to copy .env file`, I'm on Windows 10 and enabled the Windows Developer Mode, to be able to create symlinks without admin permissions. Nevertheless the environment variables from `.env` are not available in quarkus. I'm using version `1.3.1.Final`.

**Comment by geoand** [comment]
@Legion2 can you please open an issue where you give more information about the problem you are facing?

**Comment by Legion2** [comment]
@geoand I created #8297. This can be reproduced with the `config-quickstart` example.

**Comment by iriikoad** [comment]
I don't know if I'm out of subject, but I have a workaround as in my config, there is relative directories.

So I have to do this to set the user.dir:

`mvn compile quarkus:dev -Duser.dir=%cd%`
