### ISSUE TITLE
JsonNode missing in Index

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#7528]
**Describe the bug**
I get a log output about missing `com.fasterxml.jackson.databind.JsonNode` in the jandex index.
That class comes from jackson.

**Expected behavior**
No warn log output about missing classes in the index.

**Actual behavior**
I get the following output:
```
03.03.2020 09:02:22 WARN  [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - com.fasterxml.jackson.databind.JsonNode
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
```

**To Reproduce**
Have JsonNode as part of a request body.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
MSYS_NT-10.0 SOMEHOST 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys
 - Output of `java -version`: 
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
 - Quarkus version or git rev: 
1.3.0.Alpha2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: C:\eclipse\tools\apache-maven-3.5.3\bin\..
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_181\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by nimo23** [comment]
Relates to https://github.com/quarkusio/quarkus/issues/5871. That's the jandex problem:)

**Comment by gsmet** [comment]
@nimo23 please stop linking to your issue everywhere. I'll answer in your issue.

@Postremus yeah, looks like we need to ignore it. I'll add it together with another one.

**Comment by nimo23** [comment]
@gsmet ok, I only wanted to tell that this issue seems to be a duplicate because it has the same log message.

**Comment by nimo23** [comment]
I think in general, before creating always a new issue it is best to search for similar one.

**Comment by nimo23** [comment]
>yeah, looks like we need to ignore it. 

@gsmet is there a chance that the user can add a jandex-ignore manually? For example, within "application.properties", for example:

`jandex.ignore = "com.fasterxml.jackson.databind.JsonNode"`

There is a chance that some issue will come in future again..if user can add an jandex-ignore-list, would be fine.

**Comment by gsmet** [comment]
Addressed here: https://github.com/quarkusio/quarkus/pull/7537
