### ISSUE TITLE
Microprofile rest client - Can't inject config/beans to providers also in 1.2.1.Final

### ISSUE THREAD

**Issue by sassko** [quarkusio/quarkus#7531]
**Describe the bug**
As already described in #5752, it is not possible to inject CDI beans into any kind of providers that are registered by @RegisterProvider or @RegisterClientHeaders. The upgrade of quarkus to 1.2.1.Final and resteasy 4.4.2 seems not to solve this issue.

**To Reproduce**
1. Clone project from marcinczeczko from [here](https://github.com/marcinczeczko/quarkus-rest-providers-reproducer)
2. Upgrade Quarkus versions in pom.xml to 1.2.1.Final (Plugin + universe-bom)
3. Start project and do GET request to echo resource
4. Output on console is null for every injection

**Comment by gsmet** [comment]
@mkouba any chance you could have a look to that one?

**Comment by mkouba** [comment]
So it seems that only the RESTEasy part was fixed within #5752. We also need to register the classes used in `@RegisterProvider` as beans.
