### ISSUE TITLE
Introduce NativeConfig.includeAllTimeZones

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#7532]
Could we please introduce a config switch for passing `-H:+IncludeAllTimeZones` to the native-image?

The feature would allow users to enable all time zones in the native mode via `application.propreties`:

```
quarkus-core_quarkus.native.include-all-time-zones = true
```

This could work in the very same way as `quarkus-core_quarkus.native.add-all-charsets` https://quarkus.io/guides/all-config#quarkus-core_quarkus.native.add-all-charsets

I can prepare a PR if there is an interest.

**Comment by ppalaga** [comment]
The fix turns out to be very simple. I have sent a PR.

**Comment by gsmet** [comment]
@ppalaga btw, you know that you can trigger this on a per-extension basis if your extension requires it? We have a build item for it. (just checking)

**Comment by ppalaga** [comment]
@gsmet yes, thanks for the hint, I know that option. We have adopted the policy in Camel Quarkus that our extensions will not do that by themselves unless there is a 100% certainty that those additional resources are needed. In cases where we know that an extension may need non-default charsets or non-default time zones, we just document it and let the user enable it when needed.
