### ISSUE TITLE
Invalid Http Method: Patch

### ISSUE THREAD

**Issue by valadan** [quarkusio/quarkus#7545]
This bug report/feature request is directly related to this issue:

https://github.com/eclipse/microprofile-rest-client/issues/154

Since the Quarkus RestClient feature uses Eclipse Microprofile, we are unable to create Patch requests using a Quarkus Rest Client.

What are the suggested workarounds for this issue?

**Comment by stuartwdouglas** [comment]
Is this actually an issue in Quarkus? The bug that you linked to is a problem with a particular (non Quarkus) implementation, not with the specification itself.

**Comment by sberyozkin** [comment]
RestEasy uses Apache HttpClient so it should work ?
