### ISSUE TITLE
QUARKUS_PROFLE=test not applied when testing native image

### ISSUE THREAD

**Issue by SchulteMarkus** [quarkusio/quarkus#7551]
**Affected components**
Quarkus supports testing of a [produced native image](https://quarkus.io/guides/building-native-image#testing-the-native-executable).

    ./mvnw verify -Pnative
    ...

Further more, when Quarkus is running tests, the QUARKUS_PROFILE=test is being applied, as described on https://quarkus.io/guides/config#configuration-profiles.

**Expected behavior**
When running the native image tests,  QUARKUS_PROFILE=test is being applied.

**Actual behavior**
QUARKUS_PROFILE=test is not applied when running native image tests.

**To Reproduce**
This bug can be reproduced using https://github.com/quarkusio/quarkus-quickstarts/tree/master/config-quickstart with a changed application.properties. For time of writing, config-quickstart is on Git commit id 1fcd29b58ba3a80bf25ce3f5dab8d02ad0a56226 / Quarkus 1.2.1.

1. Prefix the values in https://github.com/quarkusio/quarkus-quickstarts/blob/master/config-quickstart/src/main/resources/application.properties by "%test", so the file will be:

```bash
$ cat src/main/resources/application.properties
# Your configuration properties
%test.greeting.message = hello
%test.greeting.name = quarkus
```

2. Run the native image tests:

```bash
# The Maven *test* phase will pass, the *verify* phase not.
$ ./mvnw verify -Pnative -Dnative-image.docker-build=true
...
[INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ config-quickstart ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.config.NativeGreetingResourceIT
Executing [quarkus-quickstarts/config-quickstart/target/config-quickstart-1.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2020-03-04 09:00:27,593 ERROR [io.qua.application] (main) Failed to start application: javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: greeting.message
        at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:37)
        at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties47.deploy_0(ConfigBuildStep$validateConfigProperties47.zig:101)
        at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties47.deploy(ConfigBuildStep$validateConfigProperties47.zig:120)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:132)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runtime.Application.run(Application.java:210)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
[INFO] --- maven-failsafe-plugin:2.22.1:verify (default) @ config-quickstart ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Workaround**
Set QUARKUS_PROFILE=test  when building

```bash
$ QUARKUS_PROFILE=test ./mvnw verify -Pnative -Dnative-image.docker-build=true
...
[INFO] --- maven-failsafe-plugin:2.22.1:verify (default) @ config-quickstart ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Configuration**
As described in section "To Reproduce".

**Environment**
java -version: openjdk version "11.0.6" 2020-01-14
Quarkus: v1.2.1
Build-tool: Maven

**Comment by geoand** [comment]
Hi,

As mentioned [here](https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/building-native-image.adoc#testing-the-native-executable), if you want to set the profile for testing the native image, you need to set the `quarkus.test.native-image-profile` property (to `test` in your case)

**Comment by SchulteMarkus** [comment]
Thanks for explanation.
At least I am surprised by this behavior.

**Comment by geoand** [comment]
I can understand that. However one thing that everyone needs to bear in mind is that testing the native image is more of a blackbox testing type thing. So it's meant to test the final application that is meant to be run in production

**Comment by SchulteMarkus** [comment]
I see, this is the right way thinking of the purpose of the Maven verify phase.
In my opinion, the examples for the \@io.quarkus.test.junit.NativeImageTest should not extend the "normal" application tests, as for example in https://github.com/quarkusio/quarkus-quickstarts/blob/master/getting-started/src/test/java/org/acme/quickstart/NativeGreetingResourceIT.java as (in this case) GreetingResourceTest and NativeGreetingResourceIT have different behavior.

**Comment by geoand** [comment]
That I agree with as well :) 

cc @gsmet

**Comment by SchulteMarkus** [comment]
:-)

**Comment by SchulteMarkus** [comment]
Related #4371
