### ISSUE TITLE
Bind Container Image extension to Maven deploy phase

### ISSUE THREAD

**Issue by haraldatbmw** [quarkusio/quarkus#7554]
**Description**
The current **container image** extension (e.g. docker build, docker push) is currently executed at Mavens package phase. I think maven deploy phase would be the better choice. 

In my last Quarkus test-project I introduced integration-tests based on docker-compose  (https://github.com/rmh78/quarkus-verify) and bound them to the Maven integration-test phase which is after packaging. So if i want to use the new container image build and deployments feature this has to be after my integration tests.

Important Maven phases of the default-lifecycle:
- compile
- test
- package
- pre-integration-test
- integration-test
- post-integration-test
- verify
- install
- deploy

**Additional notes**
Both maven default plugins for install and deploy can be skipped using a property.

maven.install.skip=true
https://github.com/apache/maven-install-plugin/blob/master/src/main/java/org/apache/maven/plugins/install/InstallMojo.java

maven.deploy.skip=true
https://github.com/apache/maven-deploy-plugin/blob/master/src/main/java/org/apache/maven/plugins/deploy/DeployMojo.java

``mvn deploy -Dmaven.install.skip=true -Dmaven.deploy.skip=true``

```bash
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ simple ---
[INFO] Skipping artifact installation
[INFO]
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ simple ---
[INFO] Skipping artifact deployment
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.143 s
[INFO] Finished at: 2020-03-02T11:24:09+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by geoand** [comment]
cc @maxandersen

**Comment by gsmet** [comment]
I agree `package` is too early for that. Now I'm not sure about `install` or `deploy`.

**Comment by geoand** [comment]
Sure, but we can't do much for `1.3` since the whole feature was built on Quarkus' ability to do everything during the normal build.
We would need to rethink this and possible expand the scope to include other types of deployments as well (lambda has been suggested as well)

**Comment by geoand** [comment]
I am going to close this as `won't do`. 

Our prefered solution for this case is to use the [Quarkus CLI](https://quarkus.io/blog/quarkus-cli/) which can do a container image build without these lifecycle issue
