### ISSUE TITLE
JDK language specific tests

### ISSUE THREAD

**Issue by hartimcwildfly** [quarkusio/quarkus#7564]
When checking out the current master branch and do a build,
some tests fail because the expected error message is in english but my system is not in english so the actual error message does not match.

Example:
`[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.375 s <<< FAILURE! - in io.quarkus.reactive.pg.client.ReactivePgReloadTest
[ERROR] testHotReplacement  Time elapsed: 5.365 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: (a string starting with "Connection refused" and a string ending with ":2345")
  Actual: Verbindungsaufbau abgelehnt: localhost/127.0.0.1:2345
`

Running maven with -Duser.language=en -Duser.country=US did not solve the problem.

**Comment by geoand** [comment]
Hi, it would be great to have a list of such tests that fail for you

**Comment by hartimcwildfly** [comment]
io.quarkus.reactive.pg.client.ReactivePgReloadTest.testHotReplacement()
io.quarkus.reactive.pg.client.LegacyReactivePgReloadTest.testHotReplacement()

**Comment by geoand** [comment]
Would you also like to provide a Pull Request that updates the tests accordingly?

**Comment by hartimcwildfly** [comment]
I found a solution for UNIX systems: set the ENV_VAR:  LC_ALL=en_US.UTF-8
The question is how do we integrate it into the maven project.

**Comment by geoand** [comment]
You can set env vars during command execution (simply by prepending the command with the something like NAME=VALUE mvn clean install)

**Comment by hartimcwildfly** [comment]
Yup. But it would be cool to integrate into maven pom.
