### ISSUE TITLE
AMQP and random message buffering

### ISSUE THREAD

**Issue by nderwin** [quarkusio/quarkus#7580]
**Describe the bug**
After a random number of messages, the io.vertx.amqp.impl.AmqpReceiverImpl class gets into a paused state, and all further messages are buffered.

**Expected behavior**
Messages are processed without having to be buffered, or provide a means to start sending the messages again without having to restart the Quarkus process.

**Actual behavior**
After a large-ish number of messages are put into the queue (>=100), buffering of messages kicks in and no messages are delivered until the Quarkus process is restarted.

**To Reproduce**
1. Use the docker-compose.yml file in the attached reproducer to start a Docker container running ActiveMQ (`docker-compose up activemq`)
2. Start the reproducer (`./mvnw quarkus:dev`)
3. Send 200 persistent messages to the `input` queue, with a payload of 
```
{ "type": "Car", "action": "UPDATE", "object": { "id": 42, "color": "red", "tickets": 0 } }
```
4. Note that only some of the messages are processed, the remaining messages show in the queue, and no new messages are processed by the reproducer.

**Configuration**
```properties
# Add your application.properties here, if applicable.
Included in the reproducer.
```

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux squiggy 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.119.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.119.04, mixed mode, sharing)
```
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.2.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T15:00:29-04:00)
Maven home: /home/nde/.m2/wrapper/dists/apache-maven-3.6.1-bin/38pn40mp89t5c94bjdbeod370m/apache-maven-3.6.1
Java version: 11.0.5, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-38-generic", arch: "amd64", family: "unix"
```
[reproducer.zip](https://github.com/quarkusio/quarkus/files/4289371/reproducer.zip)

**Additional context**
(Add any other context about the problem here.)

**Comment by cescoffier** [comment]
How are you sending the messages?

I have tried with:
```
@Inject @Channel("output") Emitter<String> emitter;

    @GET
    public Response send() throws InterruptedException {
        String p = "{ \"type\": \"Car\", \"action\": \"UPDATE\", \"object\": { \"id\": 42, \"color\": \"red\", \"tickets\": 0 } }";
        for (int i = 0; i < 300; i ++) {
            System.out.println("sending " + i);
            emitter.send(p);
            Thread.sleep(100);
        }
        return Response.ok().build();
    }
```

and it worked.

**Comment by nderwin** [comment]
I've been sending them directly to the queue with the ActiveMQ web console, pasting in the JSON text into the message body.

In standard use, there will be a separate application connecting to the ActiveMQ instance through JMS posting a JSON payload text message to a specially named virtual topic that fans out to specially named queues, but it should still act the same whether it's programmatically sent, or manually through the web console.

Also, try removing the `Thread.sleep(100);` line - there can be bursts of hundreds of messages placed into the queue at a time, and that's basically where it's falling down.

**Comment by nderwin** [comment]
Removing the thread sleep caused an exception because the stream was closed...  hrm.  Also, if you reduce the sleep time from 100 to 10, then you get all 300 messages delivered, but over 200 of them not processed.

**Comment by nderwin** [comment]
@cescoffier ping?  Any ideas on this one?

**Comment by nderwin** [comment]
After doing some more investigating, it appears that using an async RestClient call when processing the message is somehow interfering with future message delivery.  When I change it to use synchronous calls, and manually return either a `CompletableFuture.completedStage(Response)` or a `CompletableFuture.failedStage(Throwable)`, then all messages are delivered and processed as expected.

How could using `CompletionStage` for the MP RestClient return values interfere with `AmqpReceiverImpl` delivering messages to an `@Incoming` annotated method?

**Comment by nderwin** [comment]
A further observation - when putting the synchronous Rest Client calls under a load of 1000 messages in my production code, it still causes an interruption in delivery (and potential warnings about blocking the Vert.x eventloop thread).

**Comment by christofluethi** [comment]
any updates on this one? we seem to face the same issue with quarkus 1.4.2 and smallrye-reactive-messaging-amqp

we process "in" messages (amqp queue) and sending them to the "out" amqp queue. after some messages the processing stops and only continues by restarting quarkus.

`
@Blocking
@Incoming("in")
@Outgoing("out")
@Acknowledgment(Acknowledgment.Strategy.MANUAL)
public Message<String> process(Message<String> message) {
	String out = handleMessage(message.getPayload());
	return Message.of(out, message::ack);
}
`

**Comment by cescoffier** [comment]
First the timer issue is a back pressure issue. The AMQP client does no write fast enough and the queue is full.

About the restarting issue, be sure you don’t have a failure in the process.

BTW both issues are covered in the next reactive messaging version (credit based write and Nack/ fault tolerance support)
