### ISSUE TITLE
@ConfigProperty not resolved in native mode

### ISSUE THREAD

**Issue by blxbrgld** [quarkusio/quarkus#7607]
Hello, 

a property injected via `org.eclipse.microprofile.config.inject.ConfigProperty` in a filter like the one of the following example is not resolving when the application is running in native mode. Things are working normally if the value is introduced via `org.eclipse.microprofile.config.ConfigProvider.getConfig()` or injected using a Quarkus configuration object annotated with `io.quarkus.arc.config.ConfigProperties`. 

Quarkus version used: **1.2.1.Final**.

```
@Provider
@ApplicationScoped
public class AuthorizationFilter implements ContainerRequestFilter {

    @ConfigProperty(name = "client.key", defaultValue = "undefined")
    String clientKey;

    @Override
    public void filter(ContainerRequestContext context) {
        // clientKey is "undefined" here...
    }
}
```

Thank you.

**Comment by geoand** [comment]
Hi,

Would you be able to provide a simple reproducer for us?

Thanks

**Comment by mkouba** [comment]
AFAIK the JAX-RS providers are instantiated during the [STATIC_INIT](https://quarkus.io/guides/writing-extensions#bootstrap-three-phases) bootstrap phase, i.e. when a native image is built. This means that a config property passed as a system property or an ENV variable may not be reflected.

You can workaround this known issue by accessing the property lazily:
```java
@ConfigProperty(name = "client.key", defaultValue = "undefined")
Provider<String> clientKey;

public void filter(ContainerRequestContext context) {
   // Obtain the value - clientKey.get()
}
```
`Provider<String>` could be also replaced with `Instance<String>`.

**Comment by geoand** [comment]
@mkouba Thanks! I believe we should have a good warning message about this use case. Would you like to add it or should I?

**Comment by mkouba** [comment]
> I believe we should have a good warning message about this use case.

Sounds good. Note that it could be applied to other components as well. Basically any CDI bean that is known to be instantiated during STATIC_INIT.

> Would you like to add it or should I?

Go ahead! ;-)

**Comment by geoand** [comment]
> > I believe we should have a good warning message about this use case.
> 
> Sounds good. Note that it could be applied to other components as well. Basically any CDI bean that is known to be instantiated during STATIC_INIT.
> 

Indeed, but at the moment I don't have anything else in mind, so I'll start with this :)

> > Would you like to add it or should I?
> 
> Go ahead! ;-)

+1

**Comment by HerrDerb** [comment]
Did this notification somehow drop out? I was chasing this for the last 2 hours as I could not see any notification about directly injecting a `@ConfigProperty` into a `Provider` 🙂
running `quarkusIntTest -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true`
