### ISSUE TITLE
Kafka bootstrap property documented incorrectly

### ISSUE THREAD

**Issue by aguibert** [quarkusio/quarkus#7609]
**Describe the bug**
According to the config doc page, we the primary property for configuring Quarkus with Kafka is [`quarkus.kafka.bootstrap-servers`](https://quarkus.io/guides/all-config#quarkus-kafka-client_quarkus.kafka.bootstrap-servers). However, when I set this property it is ignored and the default value (`localhost:9092`) is still used by the Kafka Client in Quarkus.

**Expected behavior**
Configuring the kafka bootstrap servers should have an effect.

**Actual behavior**
Configured property `quarkus.kafka.bootstrap-servers` is ignored.

**To Reproduce**
1. Start with the kafka-quickstart project in the quarkus-quickstarts git repo
2. Try to configure `quarkus.kafka.bootstrap-servers` to point to kafka at a non-default location

**Configuration**
```properties
# Configured by me
quarkus.kafka.bootstrap-servers=localhost:34123

# More properties that are unchanged from the quickstart
....
```

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  MacOS
 - Output of `java -version`:  Java 8
 - GraalVM version (if different from Java): not relevant
 - Quarkus version or git rev: 1.2.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  mvnw from quickstart

**Additional context**
Using the property `kafka.bootstrap.servers` instead seems to work, so we just need a doc update.

**Comment by cescoffier** [comment]
@aguibert asked me to assign him to the issue.

**Comment by gsmet** [comment]
It's already fixed in master AFAIK.

I reverted the commit introducing this config property that was only used for Health.

See https://github.com/quarkusio/quarkus/pull/7032 .

**Comment by aguibert** [comment]
thanks for pointing that out @gsmet, I had just done a local build of the doc and saw the property was gone. I see the guide explicitly refers to the old prop so I'll go ahead and remove it from there too.

**Comment by aguibert** [comment]
never mind -- guide has been updated too. Will go ahead and close out this issue as a duplicate of #7032

**Comment by krisraich** [comment]
i encountered the same problem.
please update the documentation: https://quarkus.io/guides/kafka#kafka-health-check
it should be "kafka.bootstrap.servers"

**Comment by gsmet** [comment]
@krisraich the documentation is already updated in master. It will be fixed when we release the next version.

**Comment by gsmet** [comment]
So we removed the mention of the other property because it's not there anymore. But you're right, we don't discuss at all what you need to configure to connect to a Kafka server.

Could you open an issue?

**Comment by antoniomacri** [comment]
Done. #9063
