### ISSUE TITLE
MacOS native terminal - banner looks odd - terminal width 80

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7633]
Quarkus banner looks odd on MacOS native terminal. It's due to the default terminal width 80.
banner looks ok when the terminal width is increased.

Maybe the banner should count with default of 80 characters.

![Screenshot 2020-03-06 at 10 23 02](https://user-images.githubusercontent.com/925259/76070414-c7cb2800-5f94-11ea-9913-98e70c7ccbf3.png)
![Screenshot 2020-03-06 at 10 28 37](https://user-images.githubusercontent.com/925259/76070718-488a2400-5f95-11ea-9143-73f000e614d9.png)

**Comment by cescoffier** [comment]
On mine, it's just not readable.

![image](https://user-images.githubusercontent.com/402301/76076083-7031ba00-5f9e-11ea-80f6-b97739136930.png)

**Comment by rsvoboda** [comment]
@cescoffier I see the same as you when using iTerm2 ++ native image

But when using dev mode the banner looks ok :/
@maxandersen fyi

![Screenshot 2020-03-06 at 13 23 37](https://user-images.githubusercontent.com/925259/76083361-b8a4a400-5fad-11ea-9519-3893826e422c.png)

**Comment by gsmet** [comment]
@maxandersen FYI I consider this a blocker for 1.3.0.Final.

**Comment by maxandersen** [comment]
which part - the 80 character width ? or that character handling in native image is basically random until we apply https://github.com/quarkusio/quarkus/pull/7610 ? 

@cescoffier can you try using the fix in #7610 to see if it fixes your situation ?

**Comment by emmanuelbernard** [comment]
@maxandersen it's the 80 char width. 82 is fine. 81 and below is not.
So we could remove one column left and one column right of the Quarkus term.

But 80 is fairly arbitrary to be honest. A nice option would be for the text to not overflow. I don't know how one can do that though. CC @dmlloyd

**Comment by emmanuelbernard** [comment]
A generic solution at the terminal level is https://apple.stackexchange.com/a/210666/20624

`tput rmam` to remove wrapping of all lines. 
`tput smam` to set it back.

Apparently Lanterna has code to use this ansi logic https://stackoverflow.com/a/53267802/200911

**Comment by dmlloyd** [comment]
> @maxandersen it's the 80 char width. 82 is fine. 81 and below is not.
> So we could remove one column left and one column right of the Quarkus term.
> 
> But 80 is fairly arbitrary to be honest. A nice option would be for the text to not overflow. I don't know how one can do that though. CC @dmlloyd

[Here is a list](http://www.cse.psu.edu/~kxc104/class/cmpen472/11f/hw/hw7/vt100ansi.htm) of ANSI codes. `<ESC>[7l` will disable line wrapping, and `<ESC>[7h` will enable it.

**Comment by maxandersen** [comment]
@emmanuelbernard @cescoffier screenshot shows weird ascii characters - not just caused by 80 chars afaics.

current banner is  now max 80 char.

**Comment by emmanuelbernard** [comment]
```
                return "\u001b[7l" + bannerTitle + "\u001b[7h" + tagline;
```
in https://github.com/quarkusio/quarkus/blob/b20a74764d99ac383d006c6b5675ae3f28fcedde/core/deployment/src/main/java/io/quarkus/deployment/steps/BannerProcessor.java#L71

did not do it @dmlloyd 

I'm on iterm2 on macOS under Tmux. Maybe that's not ANSI compliant.

**Comment by maxandersen** [comment]
```
                return "\u001b[?7l" + bannerTitle + tagline + "\u001b[?7h";
```

gives you this if run widht small width and then resize it...

![2020-03-09_16-26-32](https://user-images.githubusercontent.com/54129/76229648-d464b000-6222-11ea-9a08-64f8a7a1690f.png)

**Comment by emmanuelbernard** [comment]
ah so it works here too. Yes that's what I expected. I don't know how to make it retrace upon size change.

**Comment by maxandersen** [comment]
you can't - its a terminal not a fluent graphical UI :)

**Comment by emmanuelbernard** [comment]
You can. After all vim, tmux etc all are capable of doing that. But likely
not worth doing it.

**Comment by maxandersen** [comment]
vim/tmux can do that because the characters are still there to reflow/retrace :)

By enabling that line wrapping is turned off then to not trigger line wrapping the text gets simply truncated.
