### ISSUE TITLE
the `container-image-s2i` extension runs `oc version` without reason

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7637]
**Describe the bug**

I added the `container-image-s2i` extension so that I can customize the base S2I image in generated OpenShift resources. (When the extension is not present, the base S2I image is always `fabric8/s2i-java`, even though I added the `quarkus.s2i.base-jvm-image` config property. I personally consider the `fabric8/s2i-java` image long deprecated and dangerous to use, as it clearly hasn't been kept up to date.)

That works fine, if the `oc` binary is present. (If the `oc` binary is not present, I still get all the resources, but again, I always get `fabric8/s2i-java`, even though I added the `quarkus.s2i.base-jvm-image` config property.)

However, there's a noticeable delay as it's running `oc version` to determine OpenShift version. This is because `oc version` by default talks to the OpenShift API server, which takes time.

(The process of determining server version is actually tailored to `oc` from OpenShift 3.x. The `oc` binary from OpenShift 4.x no longer prints a line starting with `kubernetes`. Also the server version is not even used!)

**Expected behavior**
I don't know why I even need the `container-image-s2i` extension to get S2I configuration applied, because the old deprecated `s2i.builder-image` config property works without the extension!

But even if I add the `container-image-s2i` extension, I expect the S2I configuration to be applied when I don't have the `oc` binary present, and I certainly don't expect the build to talk to OpenShift if I don't ask it to. (If I ask to push the container image to the OpenShift registry, or start a build in OpenShift, then sure. But not for creating the YAML files locally!)

**Actual behavior**
The build process talks to OpenShift server needlessly.

**To Reproduce**
1. Add the `container-image-s2i` extension.
2. Run `mvn clean package`.
3. If `oc` is present: observe noticeable delay. If `oc` is not present: observe that S2I configuration is not taken into account.

**Configuration**
```properties
quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.expose=true
quarkus.s2i.base-jvm-image=registry.access.redhat.com/openjdk/openjdk-11-rhel7
```

**Comment by Ladicek** [comment]
Suggestion: why doesn't `S2iBuild.getAsBoolean` simply `return true`, just like `JibBuild`?

CC @iocanel @geoand

**Comment by geoand** [comment]
I'll leave this to @iocanel  since I haven't played with s2i at all

**Comment by Ladicek** [comment]
@iocanel Any chance you could look at this and at least share some thoughts? It's not _that_ big of a deal, but it's annoying :-)

**Comment by iocanel** [comment]
It's not without a reason, we are checking if it's possible to actually
talk to API master.

We should definitely remove the dependency to OC. But doesn't it make sense
to check if we can connect to the server?

If there is no value in that, I'll remove it.

**Comment by Ladicek** [comment]
But you don't need to talk to the API server just for generating the YAML files, no? You don't check that with `container-image-docker` nor `container-image-jib`, so why with `container-image-s2i`?

My understanding is that `container-image-s2i` just makes the YAML files conform to what OpenShift expects when running an S2I binary build, but if you don't add any of the options (push/deploy), it doesn't talk to the API server at all. No?

**Comment by geoand** [comment]
I agree with @Ladicek, I don't think it makes a lot of sense for the s2i module itself to be making this check.

**Comment by glefloch** [comment]
Can I submit a pull-request for this issue ?

**Comment by geoand** [comment]
If @iocanel agrees, then I don't see why not :)

**Comment by iocanel** [comment]
@glefloch: Sure!
