### ISSUE TITLE
SSL: netty ssl substitutions fail with Graal RC12

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#764]
This is due to the `ConscryptAlpnSslEngine` class which depends on the optional conscrypt lib, and graal got better at finding optional libs. I can remove that option and force the JDK engine, but then users lose that choice of using that optional lib.

Is there any option to keep on allowing that optional lib to exist with graal, @Sanne @dmlloyd @stuartwdouglas ?

**Comment by cescoffier** [comment]
This is actually causing #4248
