### ISSUE TITLE
Wrong logging format when using -javaagent or -agentpath

### ISSUE THREAD

**Issue by crissi98** [quarkusio/quarkus#7640]
**Describe the bug**
When a Java-Agent is attached to quarkus running in jvm-Mode, the Log-Format specified by default from quarkus or the one specified in the application.properties is not used to format Log-Messages anymore. This only happens, when the Java-Agent is producing Log-Messages as well.

**Expected behavior**
Logs should look like this:
```console
2020-03-06 12:33:28,145 INFO  [io.quarkus] (main) agent-test 1.0-SNAPSHOT (running on Quarkus 1.2.1.Final) started in 0.913s. Listening on: http://0.0.0.0:8080
```

**Actual behavior**
Logs do look like this:
```console
Mõr 06, 2020 12:34:40 PM io.quarkus.runtime.Timing printStartupTime
INFO: agent-test 1.0-SNAPSHOT (running on Quarkus 1.2.1.Final) started in 0.854s. Listening on: http://0.0.0.0:8080
```

**To Reproduce**
1. I used the quarkus-create command to create a default project called "agent-test" with the following "HelloResource":
```java
package de.example;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@Path("/hello")
public class HelloResource {

    private static final Logger LOG = LoggerFactory.getLogger(HelloResource.class);

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response hello() {
        LOG.info("Entered hello");
        Response response = Response.ok("hello").build();
        LOG.info("Hello responeded with {}", response.getStatus());
        return response;
    }
}
```
You can also find the project here:
[agent-test.zip](https://github.com/quarkusio/quarkus/files/4298148/agent-test.zip)

2. I created a simple Java-Agent which is only producing a LOG-Message to avoid any issues with other thrid party agents. It has only one class called "SimpleAgent":
```java
package de.example;

import java.lang.instrument.Instrumentation;
import java.util.logging.Logger;

public class SimpleAgent {

    public static void premain(String agentArgs, Instrumentation inst) {
        Logger LOG = Logger.getLogger(SimpleAgent.class.getName());
        LOG.info("This message was created by SimpleAgent");
        System.out.println("-------------------------------------------------------------");
    }

}
``` 
and the MANIFEST.MF file:
```
Manifest-Version: 1.0
Premain-Class: de.example.SimpleAgent
```
You can also find the code for the agent here:
[SimpleJavaAgent.zip](https://github.com/quarkusio/quarkus/files/4298182/SimpleJavaAgent.zip)

3. I created a jar-artifact called "SimpleAgent.jar" for the described agent.

4. I built the quarkus-runner.jar using
```
mvn clean package
```
and started it using
```
java -javaagent:path/to/agent/SimpleAgent.jar -jar path/to/quarkus/agent-test-1.0-SNAPSHOT-runner.jar
```

**Configuration**
I used the default quarkus configuration, so there are no properties specified in application.properties

**Environment:**
 - java`: java version 1.8.0_201. also tested using OpenJDK 11.0.3
 - GraalVM version (if different from Java): not used
 - Quarkus version or git rev: 1.2.1.Final, also tested using 1.0.0.Final and 1.1.0.Final
 - Build tool:  Apache Maven 3.6.0
Different environments (java-version, quarkus-version and operating systems) did not change the described behavior.

**Comment by gsmet** [comment]
/cc @dmlloyd 

Not sure we can do anything about it though.

**Comment by dmlloyd** [comment]
Once we make the move to Java 11, we might be able to solve this kind of problem.

**Comment by stuartwdouglas** [comment]
If you start it with -Djava.util.logging.manager=org.jboss.logmanager.LogManager then I think it should work.

**Comment by crissi98** [comment]
@stuartwdouglas It does work. Thank you!

**Comment by stuartwdouglas** [comment]
@dmlloyd what changed in JDK11 that would make this easier? Looking at the LogManager init code it appears to be the same.

**Comment by dmlloyd** [comment]
A few things become possible, for example we can implement a system logger which installs our logmanager, or we can perhaps install a system class loader which encapsulates bootstrap completely (this is unreliable on 8) - maybe we could even have a Quarkus agent that does bootstrap configuration.
