### ISSUE TITLE
the `container-image-s2i` extension logs a warning when I change the base S2I image

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7641]
**Describe the bug**
I added the `container-image-s2i` extension so that I can customize the base S2I image in generated OpenShift resources. But when I do so (after overcoming all the obstacles described in #7637), I get a warning:

```
[WARNING] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Replacing s2i-java builder image with openjdk-11-rhel7
```

That is uncalled for. The config property is there for a reason. I don't think even an INFO level would be appropriate -- I don't need a message that a config property is applied.

**Expected behavior**
No message.

**Actual behavior**
Warning (as if I did something wrong!).

**To Reproduce**
1. Add the `container-image-s2i` extension.
2. Run `mvn clean package`.
3. Observe the warning.

**Configuration**
```properties
quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.expose=true
quarkus.s2i.base-jvm-image=registry.access.redhat.com/openjdk/openjdk-11-rhel7
```

**Comment by Ladicek** [comment]
CC @iocanel -- would you be fine with just removing the log message? I can submit a PR if you agree.

**Comment by geoand** [comment]
I agree with @Ladicek

**Comment by Ladicek** [comment]
Submitted https://github.com/quarkusio/quarkus/pull/7644.
