### ISSUE TITLE
quarkus.{kubernetes,openshift}.expose=true doesn't work

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7650]
**Describe the bug**

I tried to migrate from the legacy `kubernetes.expose=true` / `openshift.expose=true` properties to the new `quarkus.kubernetes.expose=true` / `quarkus.openshift.expose=true` properties, but no `Ingress` / `Route` is being generated.

Also the `KubernetesConfig` / `OpenshiftConfig` classes don't have an `expose` field, so this looks like an important omission.

**Expected behavior**
Able to generate `Ingress` / `Route` by setting `quarkus.{kubernetes,openshift}.expose=true`, instead of the legacy `{kubernetes,openshift}.expose=true`.

**Actual behavior**
Setting `quarkus.{kubernetes,openshift}.expose=true` doesn't result in generated `Ingress` / `Route`.

**To Reproduce**
1. Add the `quarkus-kubernetes` extension.
2. Run `mvn clean package`.
3. See `target/kubernetes/*.yml`.

**Configuration**
```properties
quarkus.kubernetes.deployment-target=kubernetes,openshift
quarkus.kubernetes.expose=true
quarkus.openshift.expose=true
```

**Comment by Ladicek** [comment]
CC @iocanel @geoand

**Comment by geoand** [comment]
I'll check it out, thanks for reporting

**Comment by Ladicek** [comment]
I looked at how easy/hard this would be to fix, and found `AddIngressDecorator` / `AddRouteDecorator` in Dekorate. However, their constructors accept weird objects that I don't know how to obtain. Also these 2 classes seem to be quite different in how they handle labels, which is strange.

**Comment by geoand** [comment]
@iocanel do you have any better solution in mind other than adding some hard-coded support in `KubernetesConfigUtil`?
