### ISSUE TITLE
Move from Javax to Jakarta

### ISSUE THREAD

**Issue by SR-Lut3t1um** [quarkusio/quarkus#7651]
When using quarkus currently javax is used when writing apllications on top of quarkus. This feels outdated and is a  unnesesary breaking change coming in the future. I think the switch should be made as soon as possible, to prevent breaking changes in the future.

**Comment by gsmet** [comment]
What are you talking about exactly? Because we are using the Jakarta artifacts.

As far as the `javax.*` -> `jakarta.*` package change, it's still ongoing and is still not in a final state.

**Comment by SR-Lut3t1um** [comment]
I'm talking about the package change. Where is the progressdocumented? Is there any issue to get more information about this topic?

**Comment by gsmet** [comment]
Well you can follow the discussion on the Jakarta side.

But right now, there are still a lot to do. Once every reference implementation has a stable release, we will be able to switch. But we will need to think about how we want to make the switch as it will be brutal.

In any case, I'm closing this issue for now as it's really not something we can do for the time being and we have that under radar (especially considering we maintain some of the specs and reference implementations).
