### ISSUE TITLE
Flyway multiple datasource migration does not work on native

### ISSUE THREAD

**Issue by yanxuehe** [quarkusio/quarkus#7685]
The below is the application.properties

it works on jdk 8.
not on graalvm 19.3.1
the error is 
```
org.flywaydb.core.api.flywayexception: found more than one migration with version 1.0.0
```

if i change the sql files with different versions.
then all the sql files will be executed for all the data sources

```
quarkus.datasource.db1.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.db1.url=jdbc:mysql://mysql:3306/db1
quarkus.datasource.db1.username=user
quarkus.datasource.db1.password=p@ssw0rd
quarkus.datasource.db1.min-size=1
quarkus.datasource.db1.max-size=10

quarkus.datasource.db2.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.db2.url=jdbc:mysql://mysql:3306/db2
quarkus.datasource.db2.username=user
quarkus.datasource.db2.password=p@ssw0rd
quarkus.datasource.db2.min-size=1
quarkus.datasource.db2.max-size=10


quarkus.flyway.migrate-at-start=false

quarkus.flyway.db1.schemas=MyTracker_PATIENTS
quarkus.flyway.db1.locations=db/db1
quarkus.flyway.db1.migrate-at-start=true

quarkus.flyway.db2.schemas=db2
quarkus.flyway.db2.locations=db/db2
quarkus.flyway.db2.migrate-at-start=true
```

**Comment by gsmet** [comment]
Could you provide a small reproducer? Thanks!

**Comment by yanxuehe** [comment]
> Could you provide a small reproducer? Thanks!
plz refer this, thanks!
https://github.com/quarkus-reproducers/flyway-issue-7685

**Comment by gsmet** [comment]
@machi1990 do you think you could have a look at that one?

**Comment by machi1990** [comment]
> @machi1990 do you think you could have a look at that one?

@gsmet I am just seeing the ping now. I'll have a look over the coming days.

**Comment by machi1990** [comment]
> > @machi1990 do you think you could have a look at that one?
> 
> @gsmet I am just seeing the ping now. I'll have a look over the coming days.

@gsmet I had a couple of hours with which I have opened #8065. 

The PR once merged should fix the issue @yanxuehe
