### ISSUE TITLE
Jakarta Bean Validators not working in native mode for CloudEvents api

### ISSUE THREAD

**Issue by restalion** [quarkusio/quarkus#7686]
Hi All,
I'm working in a quarkus project using [sdk-java api](https://github.com/cloudevents/sdk-java/blob/master/api/pom.xml) to create and receive events into a kubernetes cluster. If we execute the project using the JVM it is working fine, but when I launch it as a native image I see the error below:

`javax.validation.NoProviderFoundException: Unable to create a Configuration, because no Jakarta Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.`

The problem seems to be in the validations included in cloudevents/sdk-java pom.xml:

```
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>${hibernate-validator.version}</version>
        </dependency>
```

**Expected behavior**
Validations should work fine in JVM and Native.

**Actual behavior**
When executing in native mode we see an exception:
`javax.validation.NoProviderFoundException: Unable to create a Configuration, because no Jakarta Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.`

**To Reproduce**
1. Clone the repo at https://github.com/restalion/quarkus-cloudevent-sample
1. Go to cloned folder and run project in dev mode `./mvnw quarkus:dev`
1. Send a POST to `localhost:8080/event-sample` with header `Content-Type:application/json` and body `{"code":1,"value":"This is a test"}`
1. You should see a trace with the creation of the cloud event and all the headers related:
![image](https://user-images.githubusercontent.com/8156021/76196826-3d303600-61eb-11ea-87d5-970b266e414f.png)
1. Now we will try to do the same but using the native image, so, compile the project in native: `./mvnw package -Pnative`
1.  Run the native image: `target/quarkus-cloudevent-sample-1.0-SNAPSHOT-runner`
1. Send a POST to `localhost:8080/event-sample` with header `Content-Type:application/json` and body `{"code":1,"value":"This is a test"}`
1. Now you will see an error as response:
`javax.validation.NoProviderFoundException: Unable to create a Configuration, because no Jakarta Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.`
And, in logs, you can check that the cloud event was not created properly:
![image](https://user-images.githubusercontent.com/8156021/76197890-48846100-61ed-11ea-8c46-f10c01be5810.png)

**Configuration**
All the configuration is available in github project

**Screenshots**
Screenshots previously shared.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 

`Darwin MacBook-Pro-de-Julio.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

 - Output of `java -version`: 
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit GraalVM CE 19.3.1 (build 25.242-b06-jvmci-19.3-b07, mixed mode)
```
 - GraalVM version (if different from Java): 
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit GraalVM CE 19.3.1 (build 25.242-b06-jvmci-19.3-b07, mixed mode)
```
 - Quarkus version or git rev: 
```
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.2.1.Final</quarkus.platform.version>
```
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Maven home: /.m2/wrapper/dists/apache-maven-3.6.2-bin/795eh28tki48bv3l67maojf0ra/apache-maven-3.6.2
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.1/Contents/Home/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
```
**Additional context**
No additional context needed.

**Comment by gsmet** [comment]
CloudEvent is not able to build the `ValidatorFactory` as it requires a specific bootstrap for native images.

Quarkus initializes a `ValidatorFactory` itself and you should use it everywhere.

What you can do is to inject the `Validator` via CDI where you initialize the CloudEvent and use this method https://github.com/cloudevents/sdk-java/blob/master/api/src/main/java/io/cloudevents/v03/CloudEventBuilder.java#L253 to inject it into the builder.

This method has been specifically added for Quarkus.

**Comment by restalion** [comment]
Thanks a lot Guillaume! It's working fine now. The code is updated in github but I add here the changes  for future references:

I have injected the Validator in EventService class:
`    @Inject
    Validator validator;`

And add a `withValidator(validator)` to the CloudEvent builder:

```
        CloudEventImpl<SampleEvent> ce =
            CloudEventBuilder.<SampleEvent>builder()
                .withType(type)
                .withId(id)
                .withTime(ZonedDateTime.now())
                .withDatacontenttype(ContentType.APPLICATION_JSON.toString())
                .withData(payload)
                .withExtension(tracing)
                .withSubject("Sample update")
                .withSource(URI.create("/sample-source"))
                .withValidator(validator)
                .build();
```
