### ISSUE TITLE
cannot call rest api in JUnit5 @BeforeAll method

### ISSUE THREAD

**Issue by alexander-dammeier** [quarkusio/quarkus#7690]
**Describe the bug**
I want to create test data for my tests. For this reason i tried to call my rest api with RestAssured in a beforeAll method in JUnit5.
My goal is to stop using SQL files with test data because it is a mess to edit it and to create new datasets with correct references. Therefore i created a little rest client with rest assured that creates randomized data over the rest api.

**Expected behavior**
This call
```
    @BeforeAll
    public static void beforeAll(){
        given()
            .when().get("/hello")
            .then()
            .statusCode(200)
            .body(is("hello"));
    }
```
 should succeed. Quarkus should be up and running when the beforeAll method is invoked.

**Actual behavior**
I got an exception:
```
java.net.ConnectException: Connection refused: connect

	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
	...
```
If i use beforeEach everything works but its a lot of overhead to always recreate the complete test data for each test. 

**To Reproduce**
Take my reproducer:
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/4306237/code-with-quarkus.zip)
Have a look at the test class.

**Environment (please complete the following information):**
 - Output of `java -version`: 
```
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```
 - Quarkus version or git rev: 1.2.1.final 
 - IDE: IntelliJ idea

**Comment by alexander-dammeier** [comment]
I tried to reproduce it with 1.3.0.CR1 but i cannot load it from [maven central](https://mvnrepository.com/artifact/io.quarkus/quarkus-universe-bom). It is not there :/
How can i use 1.3.0.CR1? Do i need another repo?

**Comment by nimo23** [comment]
>Do i need another repo?

yes, see https://github.com/quarkusio/quarkus/issues/6171

Use the `quarkus-bom` instead of the `quarkus-universe-bom` for candidate releases:

mvn io.quarkus:quarkus-maven-plugin:1.3.0.CR1:create -DplatformVersion=1.3.0.CR1 -DplatformArtifactId=quarkus-bom

**Comment by alexander-dammeier** [comment]
> Use the `quarkus-bom` instead of the `quarkus-universe-bom` for candidate releases:

Thank you very much! Now my team and i will develop and test with your candidate releases :)
But as expected with 1.3.0.CR1 there is the same problem again.

**Comment by geoand** [comment]
Just curious: Why do you believe that `@BeforeAll` should be called after the Quarkus application has started? Have you seen something in the documentation mentioning that?

**Comment by geoand** [comment]
Actually, the problem is the following:

Your `beforeAll` method **does** get executed after Quarkus has started, however `RestAssured` has not been configured at that point to use the test port (`8081`) and default to `8080`. 
This is done by design, we don't want the Quarkus extension to mess with rest assured globally, but only on a test is executed.

There is an easy workaround however which you can use:

```
    @BeforeAll
    public static void beforeAll(){
        given().port(ConfigProvider.getConfig().getValue("quarkus.http.test-port", Integer.class))
                .when().get("/hello")
                .then()
                .statusCode(200)
                .body(is("hello"));
    }
```
