### ISSUE TITLE
QuarkusTest failed with error 'Connection timed out' since Quarkus version 1.1.0 on Windows OS

### ISSUE THREAD

**Issue by Raphael889** [quarkusio/quarkus#7699]
**Describe the bug**
Annotated tests with QuarkusTest no longer pass after version 1.0.1.Final of Quarkus.
* All tests pass with Quarkus version 1.0.1 on Windows (same code).
* All tests pass in Gitalb-ci job (Linux image) with all Quarkus version.

**Expected behavior**
All tests pass without error 'Connection timed out' in all Quarkus version on Windows OS.

**Actual behavior**
All tests annotated with @QuarkusTest failed with since Quarkus version 1.1.0.Final.
Error trace:
`
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 32.599 s <<< FAILURE! - in org.acme.ExampleResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 22.575 s  <<< ERROR!
java.net.ConnectException: Connection timed out: connect
        at org.acme.ExampleResourceTest.testHelloEndpoint(ExampleResourceTest.java:15)
`

**To Reproduce**
1. Go to 'https://code.quarkus.io/' page
2. Click on "Generate your application" and download the archive
3. Extract zip on Windows OS
4. Execute the following maven command: 'mvnw test'

**Configuration**
Default properties file generate in 'https://code.quarkus.io/' page.

**Screenshots**
NA

**Environment (please complete the following information):**
 - Windows 7+ 
 - Java version:
`$ java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)`
 - Quarkus version since 1.0.1.Final 
 - Build tool: 
`$ mvnw --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\nmdm7478\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 1.8.0_231, vendor: Oracle Corporation, runtime: C:\Java\oracle\jdk1.8.0_231\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"`

**Additional context**

**Comment by geoand** [comment]
@rsvoboda have you experienced this?

**Comment by rsvoboda** [comment]
I can't replicate the issue.

```
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to c:\Users\Rostislav\Downloads\code-with-quarkus\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ code-with-quarkus ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.ExampleResourceTest
2020-03-09 20:29:41,680 INFO  [io.quarkus] (main) Quarkus 1.2.1.Final started in 1.210s. Listening on: http://0.0.0.0:8081
2020-03-09 20:29:41,683 INFO  [io.quarkus] (main) Profile test activated.
2020-03-09 20:29:41,684 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.555 s - in org.acme.ExampleResourceTest
2020-03-09 20:29:43,094 INFO  [io.quarkus] (main) Quarkus stopped in 0.088s
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.224 s
[INFO] Finished at: 2020-03-09T20:29:43+01:00
[INFO] ------------------------------------------------------------------------
```

```
c:\Users\Rostislav\Downloads\code-with-quarkus>mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: c:\Users\Rostislav\Downloads\apache-maven-3.6.3\bin\..
Java version: 11.0.6, vendor: Oracle Corporation, runtime: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0
Default locale: cs_CZ, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by Itoriem** [comment]
For me:
`
λ mvnw test
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\Applications\workspace\code-with-quarkus\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Applications\workspace\code-with-quarkus\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\Applications\workspace\code-with-quarkus\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ code-with-quarkus ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.ExampleResourceTest
2020-03-10 08:23:08,526 WARN  [io.qua.net.run.NettyRecorder] (Thread-41) Localhost lookup took more than one second, you need to add a /etc/hosts entry to improve Quarkus startup time. See https://thoeni.io/post/macos-sierra-java/ for details.
2020-03-10 08:23:08,609 INFO  [io.quarkus] (main) Quarkus 1.2.1.Final started in 2.113s. Listening on: http://0.0.0.0:8081
2020-03-10 08:23:08,612 INFO  [io.quarkus] (main) Profile test activated.
2020-03-10 08:23:08,613 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 33.609 s <<< FAILURE! - in org.acme.ExampleResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 23.49 s  <<< ERROR!
java.net.ConnectException: Connection timed out: connect
        at org.acme.ExampleResourceTest.testHelloEndpoint(ExampleResourceTest.java:15)

2020-03-10 08:23:32,230 INFO  [io.quarkus] (main) Quarkus stopped in 0.084s
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ExampleResourceTest.testHelloEndpoint:15 » Connect Connection timed out: conne...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  45.912 s
[INFO] Finished at: 2020-03-10T08:23:32+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project code-with-quarkus: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Applications\workspace\code-with-quarkus\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

I've got this warning message that you don't have :
`2020-03-10 08:23:08,526 WARN  [io.qua.net.run.NettyRecorder] (Thread-41) Localhost lookup took more than one second, you need to add a /etc/hosts entry to improve Quarkus startup time. See https://thoeni.io/post/macos-sierra-java/ for details.`
Why is it showing on my system?

**Comment by rsvoboda** [comment]
You might be running into the similar as mentioned in https://github.com/quarkusio/quarkus/issues/3663#issuecomment-525295498 issue

Can you take a look at your hosts file? Expected location is `C:\Windows\System32\Drivers\etc\hosts` Check if you have there entry for `127.0.0.1   localhost` and `::1         localhost`

**Comment by Itoriem** [comment]
The warning is still there, but it's not very important, I guess.
I tried on my personal Windows computer and I don't have the `Connection timed out` error with the tests.

**Comment by sorin-costea** [comment]
Maybe the whole Windows is having problems? My maven tests work, but running the Lambda code.quarkus.io generated application with:
`sam local start-api --template sam.jvm.yaml`
Gives the following output - most of the time being spent in decompressing, also a bit mounting:
`Invoking io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest (java8)`
`Decompressing C:\Users\scostea\git\listlik-quarkus-lambda\target\listlik-0.0.2-SNAPSHOT-runner.jar                                                              
Fetching lambci/lambda:java8 Docker container image......`
`Mounting C:\Users\scostea\AppData\Local\Temp\tmpotk_8fgc as /var/task:ro,delegated inside runtime container`
`START RequestId: 340b0df5-1071-1732-a9ac-13753c9a16e8 Version: $LATEST`
`Function 'ListlikFunction' timed out after 15 seconds`
`<class 'samcli.local.apigw.local_apigw_service.LambdaResponseParseException'>`
`2020-04-24 19:35:27 127.0.0.1 - - [24/Apr/2020 19:35:27] "GET /hello HTTP/1.1" 502 -`

**Comment by tivrfoa** [comment]
I was having this problem on Windows.
Then I found a solution here:
https://stackoverflow.com/a/60313194

I just added `%test.quarkus.http.host=localhost` to application.properties and it worked.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by Raphael889** [comment]
Not for me, I don't work with Windows anymore. :)

**Comment by Raphael889** [comment]
Not for me, I don't work with Windows anymore. :)

**Comment by geoand** [comment]
🙏
