### ISSUE TITLE
ClassLoader and augmentation issues

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#770]
For example, Hibernate and Panache enhance entity `Foo`, and Panache then generates a `Foo$generated` class, which uses reflection on `Foo` to get some info that's hard to get using jandex. It doesn't care if it sees a non-enhanced version of the class, using its class' class loader. But if it uses theTCCL (`RuntimeClassLoader`) that will trigger a load of the entity class before the `transformers` have been set and all hell breaks loose later on with really weird failures.

And if I don't use the TCCL `shamrock:dev` does not work, for some _other_ reason.

We're going ot have to clarify what reflection is allowed during bytecode generation (Hibernate uses it, ASM uses it), and how to avoid these issues of difference between `shamrock:dev` and the normal runner.

**Comment by rsvoboda** [comment]
@FroMage is this fixed by the big CL change commit ?

**Comment by FroMage** [comment]
Yeah, at the very least it clarified how things work.
