### ISSUE TITLE
Minor mistake in azure-mvn-settings.xml

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#7700]
**Description**
Looks like we made a mistake in https://github.com/quarkusio/quarkus/commit/3c1c59d875aef0609bf002d34bb439e45fb0e13d , which I've only hit today as I was using the settings file to setup a clean machine.

AFAIK the intention of that patch was to replace the `public-jboss` group with a reference to the repository - so to avoid the "grouping" feature of Nexus which is not very fast.
But what we really did is rather than expose the JBoss repository is to expose its own mirror of Maven Central .. which is pointless as we already have a mirror for central, but is also incorrect as we can't find the dependencies which are exclusively found on the JBoss Nexus.

**Implementation ideas**
Replace the URLs with `https://repository.jboss.org/nexus/content/repositories/public-jboss/` instead;

See for example the content of, and compare:
 - https://repository.jboss.org/nexus/content/repositories/central/org/apache/maven/plugins/maven-compiler-plugin/
 - https://repository.jboss.org/nexus/content/repositories/public-jboss/org/apache/maven/plugins/maven-compiler-plugin/

**Comment by gastaldi** [comment]
Doesn't seem to be an issue with CI. Closing for now
