### ISSUE TITLE
What is the recommended way handling TypeScript

### ISSUE THREAD

**Issue by SR-Lut3t1um** [quarkusio/quarkus#7702]
As quarkus also serves normal web files, it's handy to develop Typescripts using the quarkus dev command. However having a diffrend config for TypeScript aswell as Quarkus is quiete inconvienient. IMO it would be nice to be able to handle configs in one place.

**Comment by geoand** [comment]
@ia3andy are you using typescript for `code.quarkus.io`?

**Comment by ia3andy** [comment]
@geoand I am using typescript as part of a react application.

@SR-Lut3t1um what do you mean by "it's handy to develop Typescripts using the quarkus dev command" do we support that?

**Comment by n1hility** [comment]
@ia3andy we support live updating of static resources, so from that perspective it would work. I'm not sure what a shared config would look like @SR-Lut3t1um did you want to propose a conceptual idea?

**Comment by ia3andy** [comment]
The way I use it, Typescript needs to be transpiled to be served in a browser.. so the `quarkus:dev` command is not enough for my use case at least. When developing I use a Makefile command which start both the quarkus and the web dev servers:
https://github.com/quarkusio/code.quarkus.io/blob/master/Makefile#L7

**Comment by SR-Lut3t1um** [comment]
Ah I see, Intellij handles that for me, but wouldn't it make sense if the buildscript would also transpile TypeScript eg. is there any way to silmply add these steps to the quakusDev and Build target.

**Comment by nimo23** [comment]
There is a general discussion in https://github.com/quarkusio/quarkus/issues/588.

**Comment by maxandersen** [comment]
See https://quarkus.io/blog/quarkus-and-web-ui-development-mode/ a bit old blog but I believe  i should still hold up.
