### ISSUE TITLE
Smallrye-open-api needs update

### ISSUE THREAD

**Issue by OlofSandell** [quarkusio/quarkus#7703]
**Describe the bug**
I'm porting a project to Quarkus from Wildfly. 
I didn't build. I identified the problem to be somewhere in io.smallrye.smallrye-open-api.
Updated from 1.1.20 to latest 1.2.1. Now everything works as expected.
Using quarkus 1.2.1.Final
I haven't got time to make an more in depth analyze than that. Sorry.

**Expected behavior**
Expect the project to build

**Actual behavior**
Get NPE OpenApiAnnotationScanner.java:934

**Comment by gsmet** [comment]
Master is using 1.2.1: https://github.com/quarkusio/quarkus/blob/master/bom/runtime/pom.xml#L38 .

It's the version that we will use in the soon to be released 1.3.0.
