### ISSUE TITLE
Support repeatable qualifier annotations

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#7732]
https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#repeating_qualifiers

**Comment by manovotn** [comment]
I'll take a look at this.

**Comment by manovotn** [comment]
So, querying Jandex for annotations on a given class returns the "container" class in case of repeating qualifier. E.g. using the example from linked CDI spec bit, we'd get `@Locations` to consider as an annotation on a bean.

So we need to add some form of verification that an annotation is a "container" for repeatable ones and then extract those actual qualifiers from it.

Looking at arc code, we register qualifiers while we create `BeanInfo`, so we need to do the above for bean classes and also bean producers (method/field).
Not so sure about synthetic beans now, haven't looked there yet.

**Comment by mkouba** [comment]
> So, querying Jandex for annotations on a given class returns the "container" class in case of repeating qualifier.

Yep. We will need to find the qualifiers first and afterwards find the containers.

> Looking at arc code, we register qualifiers while we create BeanInfo...

We do try to find all qualifiers when the bean deployment is created. And then when a bean is created the `io.quarkus.arc.processor.BeanDeployment.getQualifier(DotName)` method is used to identify a qualifier. For repeatable qualifiers we'll have to "extract" the real annotations, i.e. `annotation.value().asNestedArray()`.

**Comment by manovotn** [comment]
> Yep. We will need to find the qualifiers first and afterwards find the containers.

We just need to be able to say that the retrieved annotation is a meta annotation for repeateable one. Then it would work.

> annotation.value().asNestedArray()

Yeah, that's what I tried first. However, that's not quite the thing you want. Given any annotations that has an array value, you can do `annotation.value().kind().equals(AnnotationValue.Kind.ARRAY)` and this is true for `String[]` as well as an actual repeating qualifier that would have something like `Location[]`. If you then try to do `asNestedArray()` - that's gonna blow up with the former, but works with the latter :-/

**Comment by mkouba** [comment]
I think that we should use `org.jboss.jandex.AnnotationValue.componentKind()` to detect the component type of a container annotation.
