### ISSUE TITLE
quarkus-container-image-s2i bypasses the S2I `run` script, resulting in environmental differences

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7766]
**Describe the bug**

I use `quarkus-openshift` (that is, `quarkus-kubernetes` + `quarkus-container-image-s2i`) to generate OpenShift resources and customize the base S2I image. I'm specifically using the Red Hat OpenJDK 11 image based on RHEL 7. The `quarkus-container-image-s2i` extension defines exactly what command should the container run (full `java -jar ... -cp ...`), which bypasses the standard S2I `run` script. This, in turn, results in environmental differences, compared to the usual Red Hat OpenJDK S2I experience.

I specifically noticed a different "current working directory", but JVM arguments are also different, and possibly other things. A lot of work went into the Red Hat OpenJDK S2I images to pass the right JVM arguments that adapt the JVM to the container environment. Not sure how much that is still relevant with OpenJDK 11, but the S2I image still does it, so persumably it is still relevant.

On the other hand, the Red Hat OpenJDK S2I image adds the Jolokia agent, which does an "illegal reflective access operation", and perhaps isn't all that useful.

Finally, I'm well aware of the conflicting requirements: be able to use arbitrary S2I images that perhaps are not aware of the Fabric8 Java S2I / Red Hat OpenJDK S2I image conventions, while being able to leverage all the work that went into the Fabric8 Java S2I / Red Hat OpenJDK S2I images. I believe there must be a solution that satisfies both user groups, even if it would be a configuration switch.

**Expected behavior**
Leverage the JVM tuning the `run` script provides.

**Actual behavior**
Have to tune JVM myself.

**To Reproduce**
1. Add the `quarkus-openshift` extension.
2. Run `mvn clean package -DskipTests`.
3. Look at `target/kubernetes/*.yml`.

**Configuration**
```properties
quarkus.openshift.expose=true
quarkus.s2i.base-jvm-image=registry.access.redhat.com/openjdk/openjdk-11-rhel7
```

**Comment by Ladicek** [comment]
CC @iocanel @geoand

**Comment by Ladicek** [comment]
Perhaps also CC @maxandersen :-)

**Comment by geoand** [comment]
Thanks for the excellent analysis @Ladicek! 

Sounds tricky...

**Comment by Ladicek** [comment]
Looking at https://github.com/quarkusio/quarkus-images/blob/master/modules/quarkus-native-binary-s2i-scripts/s2i/run, it seems our S2I image for native binaries also does some tuning, and we probably don't want to lose that behavior.

**Comment by iocanel** [comment]
@Ladicek: Thanks!

I think that for at least `Fabric8` and `OpenJDK` s2i images we should leverage all the JVM tuning the image provides.

For those two images,  we will have to use the provided environment variables.
For all other images, we will build the cmd and args as we do right now and allow the user to specify additional jvm arguments, if desired.

@maxandersen: Do you feel that this is something we have to have in 1.3?

**Comment by Ladicek** [comment]
This was fixed by #7749.

**Comment by Ladicek** [comment]
I thought I'd close this, because it's fixed. but I figured someone should probably add some labels etc. Hence the reopen.

**Comment by Ladicek** [comment]
It seems all the necessary labels etc. were added on the PR, so I'm closing this, as it indeed is fixed.
