### ISSUE TITLE
Are Azure bits still relevant?

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7767]
As Quarkus moved to GH actions, are Azure bits still relevant?

 - https://github.com/quarkusio/quarkus/tree/master/ci-templates
 - https://github.com/quarkusio/quarkus/blob/master/azure-mvn-settings.xml
 - https://github.com/quarkusio/quarkus/blob/master/azure-pipelines.yml

**Comment by geoand** [comment]
I am pretty sure they aren't relevant anymore. @gsmet even disabled running on Azure recently, so I think we can remove the files (other than `azure-mvn-settings.xml` which is used in gh-actions as well)?

**Comment by gastaldi** [comment]
PR created: https://github.com/quarkusio/quarkus/pull/7790
