### ISSUE TITLE
 Is it possible to start system programmatically from a Java main method?

### ISSUE THREAD

**Issue by wmacibnc** [quarkusio/quarkus#7769]
Hi, is it possible to start system programmatically from a Java main method? Similar to Kumuluz.

```
public static void main(String args[]) {

        ServerConnectorConfig.Builder httpBuilder = new ServerConnectorConfig.Builder();
        httpBuilder.port(8080);

        ServerConnectorConfig.Builder httpsBuilder = new ServerConnectorConfig.Builder();
        httpsBuilder.port(8443);
        httpsBuilder.keystorePath("");
        httpsBuilder.keystorePassword("");

        ServerConfig.Builder serverBuilder = new ServerConfig.Builder();
        serverBuilder.http(httpBuilder);
        serverBuilder.https(httpsBuilder);

        DataSourceConfig.Builder dsBuilder = new DataSourceConfig.Builder();
        dsBuilder.jndiName("jdbc/H2DS");
        dsBuilder.connectionUrl("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        dsBuilder.username("sa");
        dsBuilder.password("sa");

        EeConfig.Builder eeConfigBuilder = new EeConfig.Builder();
        eeConfigBuilder.server(serverBuilder);
        eeConfigBuilder.datasource(dsBuilder);

        new EeApplication(eeConfigBuilder.build());
 }
```

Thanks!

**Comment by gastaldi** [comment]
There is a work going on in https://github.com/quarkusio/quarkus/pull/7681 to allow starting Quarkus from a main method, but I don't think it will go into this level of detail

**Comment by maxandersen** [comment]
changed the title to reflect the question - java main method is in #7681 but as @gastaldi comments I don't think this level of fluent api is even feasible/wanted as it seem impossible to then do the build time optimizations quarkus does.

I'll let @dmlloyd and/or @stuartwdouglas comment here.

**Comment by dmlloyd** [comment]
It might be theoretically possible to support some kind of fluent programmatic configuration that runs during static init for example.  We'd probably need to clarify the use case(s) though.

**Comment by nimo23** [comment]
Thats the declarative vs imperative style as little discussed in https://github.com/quarkusio/quarkus/issues/5602#issuecomment-583684750.

**Comment by wmacibnc** [comment]
> changed the title to reflect the question - java main method is in #7681 but as @gastaldi comments I don't think this level of fluent api is even feasible/wanted as it seem impossible to then do the build time optimizations quarkus does.
> 
> I'll let @dmlloyd and/or @stuartwdouglas comment here.

Sorry, But my question is:

Is it possible to start system programmatically from a Java main method?
Not configuration, but start begin to Main Class.  Why? I Have legacy application and need to translate to cloud. But my legacy application initial with Main Class, after then, I want to start Quarkus. Thank You!

**Comment by gastaldi** [comment]
Yes, but only when Quarkus 1.4.0.Final is released (see https://github.com/quarkusio/quarkus/pull/7681#issuecomment-605485380) for an example

**Comment by gastaldi** [comment]
Closing as question is answered

**Comment by wmacibnc** [comment]
Thanks!

**Comment by wmacibnc** [comment]
@gastaldi but not available in https://mvnrepository.com/artifact/io.quarkus/quarkus-universe-bom.

**Comment by gastaldi** [comment]
1.4.0.Final was not released yet. Hopefully end of the april

**Comment by wmacibnc** [comment]
Thanks!

**Comment by wmacibnc** [comment]
@gastaldi 
I need to congratulate you on your beautiful work.
Today I finished the implementation with Quarkus and the `@QuarkusMain` solution was excellent. Thank you very much for your attention and help.

**Comment by gastaldi** [comment]
@wmacibnc thank you very much! 
Hope you enjoy Quarkus as much as we do :wink:
