### ISSUE TITLE
Vert.x EventLoop Thread used on JAX-RS methods with Undertow

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#7778]
**Describe the bug**
The second HTTP request to an JAX-RS endpoint after doing a live reload results in the vert.x eventloop thread pool being used for all subsequent requests on the JAX-RS endpoint.

**Expected behavior**
The worker thread pool should always be used

**Actual behavior**
The thread pool changes to the eventloop pool after a live reload

**To Reproduce**
git clone https://github.com/bcluap/quarkus.git
cd quarkus/getting-started/
mvn quarkus:dev

Then:
curl http://localhost:8080/test  --> uses executor

Then:
Make a change to the Test.java file and save it

Then:
curl http://localhost:8080/test  --> uses executor
curl http://localhost:8080/test  --> uses eventloop

**Configuration**
```properties
Empty application.properties

I can only reproduce this when the undertow servlet extension is in the project
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26746221/76432495-bd0cfa80-63bb-11ea-9a68-dbfb37b87e0e.png)

**Environment (please complete the following information):**
 java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)
paul@PCBLaptop:/Source/quarkus/getting-started$ uname -a
Linux PCBLaptop 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
Cannot reproduce without undertow

**Comment by gsmet** [comment]
@bcluap a bit unrelated but there's a message `bootstrap classpath not set in conjunction with...`. What's that? It doesn't look like expected either or is it?

**Comment by bcluap** [comment]
Thats just an issue in the POM. Fixed that but same bug still presents itself

**Comment by FroMage** [comment]
Yeah, I can reproduce. It alternates between worker and io thread, when I keep hitting the service.

**Comment by FroMage** [comment]
This doesn't happen when not using undertow.
