### ISSUE TITLE
Generated datasource configuration: incorrect order of properties

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#7781]
When generating the datasource configuration, there is an issue with the additional datasources (the ones defined with a name): the build time properties are not first but last.

See `datasource.html#quarkus-agroal_quarkus.datasource.named-data-sources`.

And the following captures:
![capture1](https://user-images.githubusercontent.com/1279749/76440717-90a6ad80-63be-11ea-8344-2c2510d17f6a.png)

[...]

![capture2](https://user-images.githubusercontent.com/1279749/76440719-91d7da80-63be-11ea-9ad4-808db6ffca49.png)

I checked the annotations and they look consistent but we are doing a weird thing to have a `jdbc` prefix.

@machi1990 could you have a look?

**Comment by machi1990** [comment]
@gsmet I'll have a look a bit later.
