### ISSUE TITLE
Calling long-running JPA operation from non-reactive REST service causes exception

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#7782]
**Describe the bug**
When processing of the REST call takes a long time, it will end with either 

```
java.lang.IllegalStateException: You have attempted to perform a blocking operation on an IO thread.
```

or

```
ARJUNA016029: SynchronizationImple.afterCompletion - failed for io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager$1@5e290947 with exception: java.util.ConcurrentModificationException
```

**Expected behavior**
Non-reactive API should not complain about blocking operation and just execute it.

**Actual behavior**
Call throws an exception.

**To Reproduce**
1. Create REST service and repository
2. Make operation long (for example, do a long-running query repeating a couple of hundred times)
3. Call the REST service

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.19041.113]
 - Output of `java -version`: Java 8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.0.CR1 or later
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
Logs are attached
[quarkus-first.txt](https://github.com/quarkusio/quarkus/files/4319472/quarkus-first.txt)
[quarkus-second.txt](https://github.com/quarkusio/quarkus/files/4319473/quarkus-second.txt)

**Comment by gsmet** [comment]
@zeljkot could you prepare a quick reproducer for that one?

**Comment by gsmet** [comment]
It looks like there are 2 different issues and I'm pretty sure it's going to be a bit hard to reproduce.

Thanks!

**Comment by zeljkot** [comment]
I managed to reproduce first error, here is the reproducer. Note that it might be necessary to adjust the loop in the ClassicEntityRepositoryRest class.

[blocking-operation.zip](https://github.com/quarkusio/quarkus/files/4320434/blocking-operation.zip)

**Comment by stuartwdouglas** [comment]
This is because the vert.x hot deployment handler can resume on a different IO thread. Undertow only checks that the current thread is not the connections IO thread, so it does not realise it needs to dispatch to a blocking executor.

This could also happen with OIDC I think.

**Comment by stuartwdouglas** [comment]
Fix is in the linked PR

**Comment by stuartwdouglas** [comment]
I don't think there is much we can do about the transaction timeout exception. When you get a transaction being timed out from another thread it is hard to handle it well.

@Sanne is there a recommended way to deal with TX timeout with the EM?

**Comment by Sanne** [comment]
> @Sanne is there a recommended way to deal with TX timeout with the EM?

Not really; AFAIK this is a problem on WildFly as well, since a long time. I remember making a relatively simple proposal on the Narayana forums about how to fix it but they didn't like it.  I'm a bit overwhelmed at the moment but would love to revive that conversation - maybe with you as we seem more open to make changes?

**Comment by stuartwdouglas** [comment]
You could maybe add some code to our EM wrapper to handle it, detect if a thread is invoking an operation on timeout and then interrupt the thread, and have the main application thread actually do the close.
