### ISSUE TITLE
ContainerResourceLifecycleManager.inject(Object testInstance): Which class loader could we expect the object to come from ?

### ISSUE THREAD

**Issue by aldettinger** [quarkusio/quarkus#7784]
Hi there, I was no able to find info about that. We've got a ContainerResourceLifecycleManager like below:

> @Override
> public void inject(Object testInstance) {
>   if (testInstance instanceof CamelKafkaTest) {...}

When running in jvm mode instanceof is false as class loaders are distinct, while in native mode instanceof returns true as class loader is the same.

Is it intented ? a bug ? could we rely on this behaviour not to change ?

**Comment by machi1990** [comment]
cc @stuartwdouglas

**Comment by geoand** [comment]
The issue is that for JVM mode, the `testInstance` is the test instance that Quarkus creates - not the one that JUnit creates.
So essentially in order to support injection of beans into tests (of course only in JVM mode), Quarkus makes the test class a bean and all tests are run on a that bean instance. When the `ContainerResourceLifecycleManager` run, it gets an instance of the test that is not created by the same ClassLoader as the one that created `ContainerResourceLifecycleManager` itself.

There is a way to work around this JVM mode limitation and as I have demonstrated here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20test.201.2E3.2E0.2ECR2.20abstract.20test.20class.20static.20block/near/190281239 and which I'll copy here for ease of use:

```
public class DockerTestResource implements QuarkusTestResourceLifecycleManager {


    @Override
    public Map<String, String> start() {
        System.out.println("############### Resource started! ###################");
        return Collections.emptyMap();
    }

    @Override
    public void stop() {

    }

    @Override
    public void inject(Object testInstance) {
        Class<?> c = testInstance.getClass();
        while (c != Object.class) {
            for (Field f : c.getDeclaredFields()) {
                Annotation ano = null;
                for (Annotation annotation : f.getAnnotations()) {
                    if (DockerService.class.getName().equals(annotation.annotationType().getName()) && f.getType().getName().equals(DockerComposeService.class.getName())) {
                        ano = annotation;
                    }
                }
                if (ano != null) {
                    f.setAccessible(true);
                    try {
                        Class<?> dockerServiceClassFromTCCL = Class.forName(DockerService.class.getName(), false, Thread.currentThread()
                                .getContextClassLoader());
                        Method valueMethod = dockerServiceClassFromTCCL.getMethod("value");
                        String value = (String) valueMethod.invoke(ano, (Object[])null);

                        Class<?> dockerComposeServiceClassFromTCCL = Class.forName(DockerComposeService.class.getName(), true, Thread.currentThread()
                                .getContextClassLoader());
                        Constructor<?> dockerComposeServiceCtor = dockerComposeServiceClassFromTCCL.getConstructor(String.class);
                        f.set(testInstance, dockerComposeServiceCtor.newInstance(value));
                        return;
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                }
            }
            c = c.getSuperclass();
        }
    }
}
```

Note that this works in both JVM mode and native mode

**Comment by stuartwdouglas** [comment]
We have the following requirements:

- Tests must be in an isolated ClassLoader, so they can see bytecode transformation (and for a few other reasons)
- ContainerResourceLifecycleManager must run before Quarkus has started, and hence before the ClassLoader has been setup.

Thinking about it maybe I can do augmentation, setup the runtime CL, then run ContainerResourceLifecycleManager in the runtime CL, then start Quarkus.

**Comment by stuartwdouglas** [comment]
Hmm, that won't help with QuarkusUnitTest unless we also shut down the test resources after each test.

**Comment by geoand** [comment]
Should we close this issue for the time being?

**Comment by aldettinger** [comment]
Many thanks for explanations, I'm ok to close this question as the behavior is now documented here.
