### ISSUE TITLE
Introduce a "unit test" extension

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#780]
We need to introduce a fake extension for unit/regression testing the extension mechanism.

- [x] Introduce the basic extension
- [ ] Exercise all the different config phases
- [x] Exercise as many config types as possible including lists, maps, & primitives
- [x] Use bytecode recording in both stages
- [ ] Be compiled & tested with Javac and then again with ECJ
- [x] Be tested with native-image
- [ ] Include resources in native-image
- [x] Create CDI beans and interact with BeanContainer
- [x] Use substrate substitutions

(add more requirements here)

**Comment by stuartwdouglas** [comment]
Is this still relevant?

**Comment by dmlloyd** [comment]
This is done.
