### ISSUE TITLE
all-config guide - property value is fixed or configurable in runtime ?

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7812]
https://quarkus.io/guides/all-config has icon at the beginning of the row, I think it should be improved.

 - I miss clear explanation of the impact from the end user perspective
   - if a property is build-time only that it can't be overridden - e.g. via `java -Dquarkus.... -jar foo.jar`
 - I would prefer boolean-type column in the table instead of the icon or the icon should be moved at the end
   - icon at the beginning is easy to overlook

I was wondering why `java -Dquarkus.health.extensions.enabled=false -jar my.jar` is exposing built in health check and the reason is because that property is `BUILD_AND_RUN_TIME_FIXED`

The discussion started on zulip, you can read it for more context if needed - https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/mp.2Ehealth.2Edisable-default-procedures/near/190373978

**Comment by gsmet** [comment]
It has been changed for the next version.

**Comment by geoand** [comment]
> It has been changed for the next version.

Should this be closed then?

**Comment by rsvoboda** [comment]
https://quarkus.io/guides/all-config guide is updated, now we have lock icon
