### ISSUE TITLE
logging-sentry: Read additional properties from io-sentry default locations

### ISSUE THREAD

**Issue by MarcBoissonneault** [quarkusio/quarkus#7821]
**Description**
We'd like to be able to load [all the supported properties mentioned on sentry doc](https://docs.sentry.io/clients/java/config/) with the extension

**Implementation ideas**
In the Configuration of the `Lookup` uses the `Lookup. getDefaultWithAdditionalProviders(...)`.

So [in `SentryHandlerValueFactory`](https://github.com/quarkusio/quarkus/blob/master/extensions/logging-sentry/runtime/src/main/java/io/quarkus/logging/sentry/SentryHandlerValueFactory.java#L22-L23) instead of creating the Lookup this way:
```java
        final SentryConfigProvider provider = new SentryConfigProvider(config);
        final Lookup lookup = new Lookup(provider, provider);
```

Add the `SentryConfigProvider` as a High priority provider. 

Something like (DISCLAIMER: NOT TESTED):
```java
        final SentryConfigProvider provider = new SentryConfigProvider(config);
        final Lookup lookup = Lookup. getDefaultWithAdditionalProviders(List.of(provider)List.empty());
```

**Comment by ia3andy** [comment]
@MarcBoissonneault we decided to add them when someone would ask :-)

The code is already ready to introduce new properties: 
https://github.com/quarkusio/quarkus/blob/master/extensions/logging-sentry/runtime/src/main/java/io/quarkus/logging/sentry/SentryConfigProvider.java#L28

I know this looks like the easy way to allow direct access, but to integrate it properly the Quarkus way, we should map each properties to become a Sentry Logging Quarkus config property:
https://github.com/quarkusio/quarkus/blob/master/extensions/logging-sentry/runtime/src/main/java/io/quarkus/logging/sentry/SentryConfig.java

Would you provide a PR? Maybe already for the properties you are using?

**Comment by MarcBoissonneault** [comment]
Can we close this issue (at least the fields that I was expecting, has been added as part of #7833).
