### ISSUE TITLE
Custom MediaType MessageBodyWriter not triggerd when using RestAssured

### ISSUE THREAD

**Issue by cpoels** [quarkusio/quarkus#7827]
**Describe the bug**
I am currently implementing a MessageBodyWriter for my custom media type. It is basically used as an extension to JSON, so my used media type is f.e. "application/json+link".
The complete project is a Maven multi-module setup where one of the modules contains the MessageBodyWriter and the other one is the Quarkus service for testing. **So Quarkus service has a compile dependency on the body writer module**.

Definition message body writer:
```
@Provider
@Produces("application/json+link")
public class CustomBodyWriter implements MessageBodyWriter<Object>
```
The implementation is delegating to default JSON body writer and adds some headers.

Sample REST resource:
```
@Path("/")
public class SomeResource
{
    @GET
    @Produces("application/json+link")
    public List<String> get()
    {
        return List.of();
    }
}
```
I think the setup is clear. Because I don't want to share my actual project I am going to setup a minimal project reproducing my problem on Github.
Now my actual problem. I do have the following test using RestAssured:
```
@QuarkusTest
public class SomeTest
{
    @Test
    public void testSomeMore()
    {
        final var headers = RestAssured.given().when()
            .accept("application/json+link")
            .get("/")
            .headers();

        // test not completed here, but also no necessary
    }
}
```
The expected header is not present when using RestAssured in the test. But the headers are present when running Quarkus in dev mode and I am calling the REST resource with Postman.
Setting a breakpoint in the MessageBodyWriter will not be triggered when debugging the test.

Maybe I am missing or misundertsood something but I could not find anything for now. Any help or hints are highly appreciated. If anything is unclear (except of the missing test project) please let me know.

**Expected behavior**
Custom MessageBodyWriter should be executed.

**Actual behavior**
Custom MessageBodyWriter is not executed.

**Environment (please complete the following information):**
Quarkus 1.2.0.Final
Java:
```
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)
```
Maven:
```
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: D:\tools\apache-maven-3.6.2\bin\..
Java version: 11.0.6, vendor: Azul Systems, Inc., runtime: D:\java\jdk11.37.17
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Additional context**
Maven multi-module projects are running Jigsaw. MessageBodyWriter is not exported.

**Comment by cpoels** [comment]
Please forget everything I explained here. I just recognized that I made a dumb mistake.

I was calling a non-existing URI because I forgot to add the value of "quarkus.resteasy.path" to the request. I was not checking the response code and of course when recieving 404 I do not have my headers.

I just figuered it out setting up the sample project for this issue. Sorry for that!

**Comment by gsmet** [comment]
No worries, thanks for the follow-up!
