### ISSUE TITLE
Document how placeholders in application.properties work

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#7848]
**Description**
It will be good if one could use placeholders in the application.properties file in order to not repeat the same value every time and being able to change many values all at once.

I have for a particular application I am implementing the following in my application.properties file

> c2b.register.url.validation=http://localhost:21301/fedahub-gw/register/validation
c2b.register.url.confirmation=http://localhost:21301/fedahub-gw/register/confirmation
b2c.url.queue.timeout=http://localhost:21301/fedahub-gw/b2c/queuetimeout
b2c.url.result=http://localhost:21301/fedahub-gw/b2c/result
b2b.url.queue.timeout=http://localhost:21301/fedahub-gw/b2b/queuetimeout
b2b.url.result=http://localhost:21301/fedahub-gw/b2b/result
stk.url.callback=http://localhost:21301/fedahub-gw/stk/callback
balance.url.queue.timeout=http://localhost:21301/fedahub-gw/accountbalance/queuetimeout
balance.url.result=http://localhost:21301/fedahub-gw/accountbalance/result
status.url.queue.timeout=http://localhost:21301/fedahub-gw/transactionstatus/queuetimeout
status.url.result=http://localhost:21301/fedahub-gw/transactionstatus/result
reversal.url.queue.timeout=http://localhost:21301/fedahub-gw/reversal/queuetimeout
reversal.url.result=http://localhost:21301/fedahub-gw/reversal/result

If I have to change the value I will have to copy-paste the new value of the host 13 times.

**Implementation ideas**
It would be good if one could have something like

> host.gateway=http://localhost:21301/fedahub-gw

and even

> %dev.host.gateway=http://localhost:21301/fedahub-gw
> host.gateway=http://192.168.3.2:21301/fedahub-gw

> c2b.register.url.validation=%host.gateway%/register/validation
c2b.register.url.confirmation=%host.gateway%/register/confirmation
b2c.url.queue.timeout=%host.gateway%/b2c/queuetimeout
b2c.url.result=%host.gateway%/b2c/result
b2b.url.queue.timeout=%host.gateway%/b2b/queuetimeout
b2b.url.result=%host.gateway%/b2b/result
stk.url.callback=%host.gateway%/stk/callback
balance.url.queue.timeout=%host.gateway%/accountbalance/queuetimeout
balance.url.result=%host.gateway%/accountbalance/result
status.url.queue.timeout=%host.gateway%/transactionstatus/queuetimeout
status.url.result=%host.gateway%/transactionstatus/result
reversal.url.queue.timeout=%host.gateway%/reversal/queuetimeout
reversal.url.result=%host.gateway%/reversal/result

It would not only make things simpler but it would also limit typos. It could be ${host.gateway} if necessary, I really don't mind the format of the placeholder :-)

**Comment by gastaldi** [comment]
You can use `${host.gateway}` if the environment is set outside the application.properties (as an ENV variable or inside the `.env` file) if I am not mistaken. @dmlloyd can confirm

**Comment by dmlloyd** [comment]
You can even set it inside of `application.properties` if you want:

```properties
host.gateway=http://localhost:21301/fedahub-gw
%dev.host.gateway=http://192.168.3.2:21301/fedahub-gw

c2b.register.url.validation=${host.gateway}/register/validation
c2b.register.url.confirmation=${host.gateway}/register/confirmation
b2c.url.queue.timeout=${host.gateway}/b2c/queuetimeout
b2c.url.result=${host.gateway}/b2c/result
b2b.url.queue.timeout=${host.gateway}/b2b/queuetimeout
b2b.url.result=${host.gateway}/b2b/result
stk.url.callback=${host.gateway}/stk/callback
balance.url.queue.timeout=${host.gateway}/accountbalance/queuetimeout
balance.url.result=${host.gateway}/accountbalance/result
status.url.queue.timeout=${host.gateway}/transactionstatus/queuetimeout
status.url.result=${host.gateway}/transactionstatus/result
reversal.url.queue.timeout=${host.gateway}/reversal/queuetimeout
reversal.url.result=${host.gateway}/reversal/result
```

You can also change the `host.gateway` property on the commandline (via `-Dhost.gateway=xxx`) or env var (`HOST_GATEWAY=xxx ...`).

**Comment by geoand** [comment]
@dwamara have you tried using the placeholders without success?

**Comment by dwamara** [comment]
@geoand it did worked :) it's something that I was looking for for ages but never got myself to ask the question as it was sometimes only 3 or 4 properties.
It's something that should definitely be put in the documentation. 
How do I see the process of updating the documentation? I will gladly do it.

**Comment by geoand** [comment]
@dwamara Thanks for volunteering to update the docs.

I would think the best place to put this information is somewhere here: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/config.adoc

Just open a pull request updating that piece of documentation and someone will promptly review it

**Comment by gastaldi** [comment]
@dwamara I updated the issue title to reflect this task
