### ISSUE TITLE
@ConfigItem Optional<Map<String,String>> does not work

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#7856]
Declaring a config as: 

    /**
     * Sets the placeholders to replace in SQL migration scripts.
     */
    @ConfigItem
    public Optional<Map<String, String>> placeholders = Optional.empty();

Always returns an `Optional.empty()` when having the following in the `application.properties`: 

```
quarkus.flyway.placeholders.foo=bar
```

**Comment by sberyozkin** [comment]
I wonder if it is similar to what is not working in OIDC at the moment, where I'd like to have an optional ConfigGroup:
```
@ConfigGroup
class SomeGroup {}

Optional<SomeGroup> someGroup;
```
(sorry I'll open another issue if it is not related)

**Comment by gastaldi** [comment]
It may be related. If only I knew where the config is converted/parsed :)

**Comment by dmlloyd** [comment]
It's probably a different issue @sberyozkin, but even if I'm wrong, it won't hurt to have two open issues for the problem (especially since they're two different symptoms).
