### ISSUE TITLE
AssertionError in OwnerResourceTest 

### ISSUE THREAD

**Issue by skabashnyuk** [quarkusio/quarkus#7869]
**Describe the bug**
I've got AssertionError in the generated sample.

**Expected behavior**
OwnerResourceTest test passed without error

**Actual behavior**
```
java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "\"lastName\":\"Test\""
  Actual: [{"id":1,"firstName":"110 W. Liberty St.","lastName":"Madison","address":"Test","city":"Test","telephone":"6085551023"}]
```

**To Reproduce**
1.  Generate sample  https://code.quarkus.io/ with flyway, hibernate, postgresql
2.  Start postgresql
3.  Run test with ```-Dquarkus.profile=test```

**Configuration**
```properties
# docker run -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres:alpine
quarkus.datasource.url=jdbc:postgresql://localhost/postgres
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

%prod.quarkus.hibernate-orm.sql-load-script = db/prod-data.sql
%test.quarkus.hibernate-orm.sql-load-script = db/test-data.sql
%test.quarkus.hibernate-orm.database.generation = drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script = db/dev-data.sql
%dev.quarkus.hibernate-orm.database.generation = drop-and-create

quarkus.flyway.migrate-at-start=true
```

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Darwin MacBook-Pro 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64` 
 - Output of `java -version`:  `openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)`
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  `1.2.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
`
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /Users/skabashn/.m2/wrapper/dists/apache-maven-3.6.1-bin/38pn40mp89t5c94bjdbeod370m/apache-maven-3.6.1
Java version: 1.8.0_242, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
Default locale: uk_UA, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
`

**Additional context**
I assume the reason is that **test-data.sql** instead of 
```sql
INSERT INTO owners VALUES (1, 'Test', 'Test', '110 W. Liberty St.', 'Madison', '6085551023');
```
should be something like this
```sql
INSERT INTO owners (id, first_name, last_name, address, city, telephone)
       VALUES (1, 'Test', 'Test', '110 W. Liberty St.', 'Madison', '6085551023');
```

**Comment by skabashnyuk** [comment]
I can propose a pr. But I can't find OwnerResourceTest sources.

**Comment by gastaldi** [comment]
@skabashnyuk that file doesn't seem to exist in the core and the steps to reproduce don't create it either. 

Are you sure the problem is not in the migration SQL files as you pointed out?

**Comment by skabashnyuk** [comment]
@gastaldi you right. A sample comes https://github.com/kolorobot/quarkus-petclinic-api. Sorry.
