### ISSUE TITLE
Unable to use @ParameterizedTest with test annotated by @QuarkusTest

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#7877]
I was building camel-quarkus with the latest Quarkus SNAPSHOT and noticed a change in behaviour. Tests annotated with `@QuarkusTest` that use `@ParameterizedTest` have started to fail with:

```
org.junit.jupiter.api.extension.ParameterResolutionException: Discovered multiple competing ParameterResolvers for parameter [java.lang.String arg0] in method [public void org.apache.camel.quarkus.component.dataformats.json.JsonComponentsTest.testUnmarshal(java.lang.String)]: io.quarkus.test.junit.QuarkusTestExtension@36e9794c, org.junit.jupiter.params.ParameterizedTestParameterResolver@78a0d664
```

Here's an example failing test:

https://github.com/apache/camel-quarkus/blob/master/integration-tests/dataformats-json/src/test/java/org/apache/camel/quarkus/component/dataformats/json/JsonComponentsTest.java

**Comment by geoand** [comment]
I'll take a look

**Comment by geoand** [comment]
I can confirm that it works with `1.3.0.Final` and not with the latest `master`. I'll have a deeper look later on today.

**Comment by geoand** [comment]
@jamesnetherton #7881 should fix the issue
