### ISSUE TITLE
QuarkusTestResourceLifecycleManager  / injecting - getAnnotation stopped working in 1.3.0

### ISSUE THREAD

**Issue by lkrzyzanek** [quarkusio/quarkus#7880]
**Describe the bug**
I'm upgrading form 1.2.0.Final to 1.3.0.Final and my Tests stopped working when  implementing  `inject` method from `QuarkusTestResourceLifecycleManager`

I'm injecting AMQ client session in very similar way like in  https://github.com/quarkusio/quarkus/blob/master/test-framework/kubernetes-client/src/main/java/io/quarkus/test/kubernetes/client/KubernetesMockServerTestResource.java 

My implementation
```
    @Override
    public void inject(Object testInstance) {
        log.info("Inject client session to test");

        Class<?> c = testInstance.getClass();
        while (c != Object.class) {
            for (Field f : c.getDeclaredFields()) {
                if (f.getAnnotation(JMSClientSession.class) != null) {
                    if (!javax.jms.Session.class.isAssignableFrom(f.getType())) {
                        throw new RuntimeException("@JMSClientSession can only be used on fields of type javax.jms.Session");
                    }

                    f.setAccessible(true);
                    try {
                        f.set(testInstance, session);
                        return;
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                }
            }
            c = c.getSuperclass();
        }
    }
```

**Expected behavior**
Client session is injected

**Actual behavior**
f.getAnnotation(JMSClientSession.class) returns always null.
Then My Test case fails on NPE because field session is null

**To Reproduce**
1. Try to run Test that would inject  into field something in similar way like in  https://github.com/quarkusio/quarkus/blob/master/test-framework/kubernetes-client/src/main/java/io/quarkus/test/kubernetes/client/KubernetesMockServerTestResource.java and in test use the injected value.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 11.0.4, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
This is the same issue as: https://github.com/quarkusio/quarkus/issues/7784

**Comment by lkrzyzanek** [comment]
I tried check on  String representation of the annotation classes 
like `DockerService.class.getName().equals(annotation.annotationType().getName()) ` but then I cannot set the instance created within `start()`.
Looks like start + inject + stop becomes basically not useable.

**Comment by geoand** [comment]
@lkrzyzanek can you show what your code looks like? Even better if you could point to a reproducer

**Comment by geoand** [comment]
@stuartwdouglas Given that the problem described here and in #7784 is only a `QuarkusTest` problem, I think we should implement [this](https://github.com/quarkusio/quarkus/issues/7784#issuecomment-597938994) comment you made.

Wouldn't we basically just make the change in `QuarkusTestExtension` to first run augmentation, launch the `TestResourceManager` using the runtime CL and leave all other tests as they are? Am I missing something?

**Comment by stuartwdouglas** [comment]
yea, I think this is the best approach. QuarkusUnitTest is mostly for internal stuff, if it becomes a problem we can look at it later.

**Comment by stuartwdouglas** [comment]
Any chance you could test out https://github.com/quarkusio/quarkus/pull/7897, I am pretty sure it will resolve the issue.

**Comment by lkrzyzanek** [comment]
Yep #7897 fixes this issue. Thank you guys!
