### ISSUE TITLE
Remote debug into dev mode doesn't work on JDK 9+

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#7889]
**Describe the bug**
If I run `quarkus:dev` remotely (i.e. in a Docker container), I can't remote debug if I'm using JDK 9 or newer (the remote connection string has been changed and requires adapting).

Trying to debug remotely (with IDE / jdb through `localhost:5005`) fails for me with:

```
Error running Debugger: Unable to open debugger port (localhost:5005): 
java.io.IOException "handshake failed - connection prematurally closed"
```

Also see [this StackOverflow answer](https://stackoverflow.com/a/60090750).

**Environment (please complete the following information):**
 - Output of `java -version`: `openjdk version "13.0.1" 2019-10-15 \n OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)`
 - Quarkus version or git rev: `1.3.0.Final`

**Additional context**
The cause of this issue is in [DevMojo.java](https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L497) in the debug connection; instead of `transport=dt_socket,address=5005,server=y,suspend=n`, with JDK 9+ you'd need `transport=dt_socket,address=*:5005,server=y,suspend=n` for the same result (allowing connections from every host, not just localhost).

**Comment by sdaschner** [comment]
The proposed PR should work for both pre and post JDK 9 (quickly tested with 8 and 13) and has the same effect like before (connections from every host is allowed).

**Comment by geoand** [comment]
Thanks for reporting!

I am pretty sure we had a similar report a while back but I can't seem to find it now

**Comment by jaikiran** [comment]
Hello @geoand,

>I am pretty sure we had a similar report a while back but I can't seem to find it now

That was in the context of docker build process debugging and it's here https://github.com/quarkusio/quarkus/issues/7256

**Comment by geoand** [comment]
Thanks @jaikiran for pointing that out!
