### ISSUE TITLE
Interceptor resolution with multiple bindings is not done accordingly to the specification

### ISSUE THREAD

**Issue by manovotn** [quarkusio/quarkus#7931]
Given an interceptor with two bindings and a bean with only one of them, ArC currently triggers the interceptor for methods on that bean. This is not what the specification expects, it should only trigger if bean has both bindings.

**Comment by loicmathieu** [comment]
@manovotn are you sure because the following reference documentation on Weld say it's correct: https://docs.jboss.org/weld/reference/1.0.0/en-US/html/interceptors.html#d0e3567

It clearly say that if an interceptor has multiple annotation bindings using any of the annotation will triggers it.

**Comment by manovotn** [comment]
@loicmathieu yes I am sure.

That doc is pretty old (Weld 1) BTW, Weld 3 has the docs here - https://docs.jboss.org/weld/reference/latest/en-US/html_single/#_multiple_interceptor_binding_annotations
However, most of this is written in interceptor spec doc, which seems to be [broken now](https://github.com/eclipse-ee4j/interceptor-api/issues/65). CDI only adds few bits on top of it.

And looking at that doc, note that the resulting method always has *both* annotations. In interceptor spec, you combine annotations from class-level with those on method-level for resulting set of bindings. Therefore, with 2 bindings you have 4 combination of declaring them - either both bindings on class/method level or one binding on class, the other on method.

**Comment by loicmathieu** [comment]
Oh my bad !

I read too quickly the documentation and as I saw something different I read it ... the way I see it :)
