### ISSUE TITLE
Running quarkus:dev in Eclipse fails after update to quarkus-1.3.0-final

### ISSUE THREAD

**Issue by heike2718** [quarkusio/quarkus#7932]
**Describe the bug**
After updating from quarkus-1.2.0-Final to quarkus-1.3.0-Final it is not possible to run a quarkus project inside eclipse with m2e.

**Expected behavior**
Running quarkus project in eclipse with maven run configuration "clean quarkus:dev" succeeds

**Actual behavior**
I have commited a reproducer with detailed description to github: [heike2718/quarkus-eclipse-reproducer](https://github.com/heike2718/quarkus-eclipse-reproducer)

**To Reproduce**
see the linked reproducer

**Configuration**
see the linked reproducer

**Environment (please complete the following information):**
 - Output of `java -version`: Java version: 11.0.2, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-11.0.2
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.0-Final
 - Build tool maven version 3.6.3

**Comment by geoand** [comment]
I'm not an Eclipse user myself so I can't really test this in Eclipse. 
FWIW, I does work from the command line.

Perhaps an Eclipse user can have a look? @mkouba or @gsmet maybe?

**Comment by mkouba** [comment]
@heike2718 I've just tested your reproducer with Eclipse Version: 2019-12 (4.14.0), Build id: 20191212-1212, m2e 1.15.0.20200310-1832 and it runs fine. The only thing I've noticed is that you're running the goals `clean quarkus:dev` but it should be [`compile quarkus:dev`](https://quarkus.io/guides/maven-tooling#development-mode).

**Comment by gsmet** [comment]
You shouldn't need `compile` with the latest versions. It's done automatically.

**Comment by mkouba** [comment]
> You shouldn't need compile with the latest versions. It's done automatically.

In that case, we should probably update the docs.

Anyway, if this is not the problem then I've run out of ideas...

**Comment by heike2718** [comment]
@mkouba 

Thanks a lot for your reply.

Now I tried the following:

I updated eclipse to 2020-03 (eclipse-jee Version: 2020-03 M3 (4.15.0M3)
Build id: 20200227-1435) which has installed m2e version 1.15.0.20200226-2003.

I removed my local maven repository.

I switched to quarkus-1.2.0-Final and ran quarkus:dev from inside eclipse which works fine.

I switched to quarkus-1.3.0-Final whitch crashes (I did not change any maven settings in comparison with the 1.2.0 trial)

When I run it from command line with the same maven-settings it does not crash.

So now I do not have any clue.

I attached maven debug output to heike2718/quarkus-eclipse-reproducer. I also attached my maveb settings.xml to that project which except of the local-repo only uses defaults.

Perhaps somebody could have a look at these maven logs?

**Comment by heike2718** [comment]
@aloubyansky 

When I debugged the maven run in eclipse I noticed changes in the BootstrapAppModelResolver. Perhaps there went something wrong when fixing [Issue 7459](https://github.com/quarkusio/quarkus/pull/7459) or [Issue 7697](https://github.com/quarkusio/quarkus/pull/7697)

since the DefaultArtifactResolver does find all dependencies in local repo but when bootsraping tries to load it from remote repository. Could you please have a look at [my reproducers stack traces](https://github.com/heike2718/quarkus-eclipse-reproducer)

**Comment by aloubyansky** [comment]
> You shouldn't need `compile` with the latest versions. It's done automatically.

Not for multimodule projects, which is not the case here, but just in case.

@heike2718 I will have a look once I'm done with what I'm looking into at the moment.

**Comment by heike2718** [comment]
still open with Quarkus 1.3.2-Final.

**Comment by aloubyansky** [comment]
@heike2718 I just checked out your reproducer and followed the instructions. It worked for me.

```
INFO] Scanning for projects...
[INFO] 
[INFO] -------------< de.egladil.web:quarkus-eclipse-reproducer >--------------
[INFO] Building quarkus-eclipse-reproducer 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ quarkus-eclipse-reproducer ---
[INFO] Deleting /home/aloubyansky/playground/quarkus-eclipse-reproducer/quarkus-hello/target
[INFO] 
[INFO] --- quarkus-maven-plugin:1.3.0.Final:dev (default-cli) @ quarkus-eclipse-reproducer ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/aloubyansky/playground/quarkus-eclipse-reproducer/quarkus-hello/target/classes
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-04-20 12:09:17,067 INFO  [io.quarkus] (main) quarkus-eclipse-reproducer 1.0.0-SNAPSHOT (powered by Quarkus 1.3.0.Final) started in 1.038s. Listening on: http://0.0.0.0:8080
2020-04-20 12:09:17,069 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-04-20 12:09:17,069 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```
Eclipse
Version: 2020-03 (4.15.0)
Build id: 20200313-1211

Maven/M2E
3.6.3/1.15.0.20200310-1832

**Comment by aloubyansky** [comment]
I see the settings.xml in your repo. Do you expect your first module to be installed in the local repo specified in it? Following your instructions, I see 
```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ own-artifact ---
[INFO] Installing /home/aloubyansky/playground/quarkus-eclipse-reproducer/own-artifact/target/own-artifact-1.0.0.jar to /home/aloubyansky/.m2/repository/de/egladil/web/own-artifact/1.0.0/own-artifact-1.0.0.jar
[INFO] Installing /home/aloubyansky/playground/quarkus-eclipse-reproducer/own-artifact/pom.xml to /home/aloubyansky/.m2/repository/de/egladil/web/own-artifact/1.0.0/own-artifact-1.0.0.pom
```
I did not touch your settings.xml

**Comment by aloubyansky** [comment]
How/where do you specify your Maven settings?

**Comment by heike2718** [comment]
Thanks a lot for taking your time to have a look at it.

I just gave it another try and restored the default maven settings (back to ~/.m2). This way I cannot reproduce the error any more.

But when I change the eclipse default maven settings like this: in "preferences -> maven - User settings", for both "Global Settings"  and "User Settings" I selected the settings.xml from the reproducer project, I can reproduce the error but only with Quarkus 1.3.x and not Quarkus 1.2.x

This is very strange. So I think, that there could to be a bug (?) in m2e or I did miss something concerning overriding the default m2e-settings.

Perhaps you are curious, then try overriding the eclipse default maven-settings in order to see the funny stacktrace.

I am going to close this issue since everything works fine when I use the default m2e-settings.

Regards Heike.

**Comment by aloubyansky** [comment]
Ok, I see. Eclipse settings aren't visible to Quarkus bootstrap. I'll see whether there is something we could do about it. Thanks.

**Comment by aloubyansky** [comment]
Unfortunately, I don't see any hook for us to pick up the eclipse's run config. What you could do is to add "-s path_to_your_settings.xml" to the arguments.

**Comment by heike2718** [comment]
OK, thanks. Nice hint with the -s option. 

At my work it is not possible to use the m2e defaults because user home is linked to a network drive with limited storage capacity and we are not allowed to use it for local maven storage. 

So the -s option is a good workaround.

**Comment by famod** [comment]
@heike2718 You could still use that network home to put your `settings.xml` there and add `localRepository` with a path that points to a local folder on your hard drive.

That being said, I ususually don't put anything in my user home `settings.xml` apart from the `server` entries.
Everything else goes in the `<maven-home>/conf/settings.xml`, including `localRepository`.
I have multiple Maven installations and multiple local repos (diskspace is cheap), one Maven and local repo "per git clone" (and also one IDE-setup per git clone).
This way I have everything separated.

**Comment by heike2718** [comment]
@famod 

Thanks, good point. That's esier than using the -f option :)
