### ISSUE TITLE
quarkus.platform.version is not reflected in version printed by .jar application

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7954]
`quarkus.platform.version` is not reflected in version printed by .jar application

`quarkus.platform.version` is reflected in test execution where `Quarkus 1.3.0.Final started in 1.253s. Listening on: http://0.0.0.0:8081` is printed,.
.jar application says `rest-json-quickstart 1.0-SNAPSHOT (powered by Quarkus 999-SNAPSHOT) started in 0.792s.` eventhough target/lib doesn't contain any SNAPSHOT jars.

Current situation:
 - Quarkus version reported during the test execution is derived from Quarkus bits/platform version.
 - Quarkus version reported during the start of .jar app is derived from quarkus-maven-plugin version.

Expectation:
 - reported Quarkus version is unified, to me it should be based on Quarkus (core) bits version.

This has implications on product side if BOM and plugin version differ.
@michalszynkiewicz fyi

Using `rest-json-quickstart` and running `mvn clean package -Dquarkus.platform.version=1.3.0.Final && java -jar target/rest-json-quickstart-1.0-SNAPSHOT-runner.jar`

```
mvn clean package -Dquarkus.platform.version=1.3.0.Final && java -jar target/rest-json-quickstart-1.0-SNAPSHOT-runner.jar

...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.rest.json.LegumeResourceTest
2020-03-19 08:43:44,417 INFO  [io.quarkus] (main) Quarkus 1.3.0.Final started in 1.253s. Listening on: http://0.0.0.0:8081
2020-03-19 08:43:44,419 INFO  [io.quarkus] (main) Profile test activated.
2020-03-19 08:43:44,419 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jsonb]
2020-03-19 08:43:45,367 INFO  [org.acm.res.jso.LoggingFilter] (executor-thread-1) Request GET /legumes from IP 127.0.0.1:59663
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.078 s - in org.acme.rest.json.LegumeResourceTest
[INFO] Running org.acme.rest.json.FruitResourceTest
2020-03-19 08:43:45,827 INFO  [org.acm.res.jso.LoggingFilter] (executor-thread-1) Request POST /fruits from IP 127.0.0.1:59664
2020-03-19 08:43:45,887 INFO  [org.acm.res.jso.LoggingFilter] (executor-thread-1) Request DELETE /fruits from IP 127.0.0.1:59665
2020-03-19 08:43:45,934 INFO  [org.acm.res.jso.LoggingFilter] (executor-thread-1) Request GET /fruits from IP 127.0.0.1:59666
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.161 s - in org.acme.rest.json.FruitResourceTest
2020-03-19 08:43:45,991 INFO  [io.quarkus] (main) Quarkus stopped in 0.025s
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ rest-json-quickstart ---
[INFO] Building jar: /Users/rsvoboda/git/quarkus-quickstarts/rest-json-quickstart/target/rest-json-quickstart-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ rest-json-quickstart ---
[INFO] [org.jboss.threads] JBoss Threads version 3.0.1.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /Users/rsvoboda/git/quarkus-quickstarts/rest-json-quickstart/target/rest-json-quickstart-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 925ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.856 s
[INFO] Finished at: 2020-03-19T08:43:48+01:00
[INFO] ------------------------------------------------------------------------
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-03-19 08:43:49,201 INFO  [io.quarkus] (main) rest-json-quickstart 1.0-SNAPSHOT (powered by Quarkus 999-SNAPSHOT) started in 0.792s. Listening on: http://0.0.0.0:8080
2020-03-19 08:43:49,226 INFO  [io.quarkus] (main) Profile prod activated.
2020-03-19 08:43:49,227 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jsonb]
^C2020-03-19 08:50:42,947 INFO  [io.quarkus] (main) rest-json-quickstart stopped in 0.033s
```

**Comment by rsvoboda** [comment]
Dev mode says `powered by Quarkus 1.3.0.Final` 
`mvn -Dquarkus.platform.version=1.3.0.Final quarkus:dev`

**Comment by maxandersen** [comment]
The version here is the quarkus core version.

Platform could be a tons of other things and not necessarily even used/available thus I would say it's correct as is ?

**Comment by rsvoboda** [comment]
Atm Quarkus version reported by .jar is derived from quarkus plugin version.

It shouldn't be the plugin version but quarkus-core version.

I used `rest-json-quickstart` https://github.com/quarkusio/quarkus-quickstarts/blob/development/rest-json-quickstart/pom.xml#L11 with just quarkus-bom, not platform.
quarkus-bom version == quarkus-core version to me.

the version is specified by `quarkus.platform.version=1.3.0.Final` property which probably brings the confusion about platform vs. core.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by rsvoboda** [comment]
Closing, this is no longer relevant.

Checked with `mvn clean package -Dquarkus.platform.version=3.14.1 && java -jar target/quarkus-app/quarkus-run.jar` command in `quarkus-quickstarts/rest-json-quickstart`
