### ISSUE TITLE
NPE in QuarkusTestExtension when test method argument is null

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7958]
**Describe the bug**
If I have a `@QuarkusTest` and some of the test method is passed `null` as an argument, `QuarkusTestExtension` throws a NPE. Getting `null` as an argument can happen for various reasons, for example when I use parameterized tests and want to use `null` as one of the parameters.

**Expected behavior**
`null` is a valid argument that test methods can receive

**Actual behavior**
NPE

**To Reproduce**
1. Create a `@QuarkusTest`.
2. Add a `@ParameterizedTest` with `@NullSource`.
3. Observe NPE.

**Comment by Ladicek** [comment]
This is easy to fix, I'll submit a PR.

**Comment by geoand** [comment]
Thanks @Ladicek!
