### ISSUE TITLE
test Fault Tolerance + Context Propagation integration

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7962]
**Description**
Verify that MP Context Propagation works with MP Fault Tolerance `@Asynchronous` methods. I'm thinking testing just CDI contexts for now. E.g. add a `@RequestScoped` bean with some field that is initialized during request processing, but before the `@Async` method is invoked. The `@Async` method would then access the same bean and make the field value part of the result.

**Comment by michalszynkiewicz** [comment]
@Ladicek isn't it somewhat done by the test you added for opentracing propagation?

**Comment by Ladicek** [comment]
Kinda sorta, yes. I'd like to have a test that doesn't involve OpenTracing, too.

**Comment by geoand** [comment]
@rsvoboda I assume this has been done, can you confirm?

**Comment by Ladicek** [comment]
This is done, yes: https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-fault-tolerance/deployment/src/test/java/io/quarkus/smallrye/faulttolerance/test/asynchronous/context/propagation/FaultToleranceContextPropagationTest.java
