### ISSUE TITLE
test Fault Tolerance in dev mode

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7963]
**Description**
I'm thinking changing some parameters on some fault tolerance annotations and verifying that those changes are propagated?

**Comment by geoand** [comment]
I assume this has been done, right? If so, let's close the issue please.

**Comment by Ladicek** [comment]
I filed this when I was doing QE work (reviewing test coverage), and didn't address it myself.

**Comment by geoand** [comment]
@rsvoboda I assume this has been done, can you confirm?

**Comment by Ladicek** [comment]
Submitted #39030 for this.
