### ISSUE TITLE
Smallrye messaging does not allow multiple tests

### ISSUE THREAD

**Issue by burmanm** [quarkusio/quarkus#7974]
**Describe the bug**
Trying to setup an environment, where one test wants to test the main process (and see the last component of the test to send a message to Kafka/queue) and then also adding another test that tests the actual last component.

But it seems I can't have a TestSubscriber in two different test classes targeting the same channel. How do I test both processes in the same module? .dispose() does not help here. Using .dispose() for TestSubscriber causes the test to end with:

```
java.lang.IllegalStateException: The subscription to data has been cancelled
	at com.redhat.test.MyIntegrationTest.testSecond(MyIntegrationTest.java:24)
```

And leaving without .dispose() prevents the test from running also:

```
Caused by: java.lang.Exception: Emitter already created
	at com.redhat.test.MyIntegrationTest.testSecond(MyIntegrationTest.java:23
```

**Expected behavior**
Both tests should work.

**Actual behavior**
Impossible to run two separate tests that have dependent Quarkus managed objects.

**To Reproduce**
1. I created a simple reproducer here: https://gitlab.com/burmanm/emitterbug
2. 
3.

**Comment by geoand** [comment]
cc @cescoffier

**Comment by marc-christian-schulze** [comment]
I'm facing the same issue (with Quarkus 1.3.1.Final) when using multiple test methods inside the same test class:
```
@QuarkusTest
public class ExampleResourceTest {

    @Inject
    @Channel("my-channel")
    public Publisher<Integer> publisher;

    @Inject
    public ExampleResource resource;

    @Test
    public void testSenseOfLife() {
        TestSubscriber<Integer> subscriber = new TestSubscriber<>();
        publisher.subscribe(subscriber);
        resource.emitSenseOfLife();
        subscriber.assertValue(42);
    }

    @Test
    public void testLuckyNumber() {
        TestSubscriber<Integer> subscriber = new TestSubscriber<>();
        publisher.subscribe(subscriber);
        resource.emitLuckyNumber();
        subscriber.assertValue(13);
    }
}
```

Reproducer available here:
https://github.com/marc-christian-schulze/quarkus-reproducer-7974

**Comment by marc-christian-schulze** [comment]
After digging a bit deeper it seems that the actual problem is that we expect an Emitter to work like a Publisher but unfortunately it neither does implement the [Publisher](https://www.reactive-streams.org/reactive-streams-1.0.0-javadoc/org/reactivestreams/Publisher.html) interface, nor does it support multiple subscribers. However, looking into how the conversion is done we end up at the point inside of Mutiny where the emitter is wrapped into a Publisher using `io.smallrye.mutiny.operators.multi.builders.EmitterBasedMulti` but although it implements the interface through its base class - I suspect it does not conform to the specification. Let me create a reproducer for them and once confirmed I'm opening a bug report for smallrye to get it solved there.

**Comment by marc-christian-schulze** [comment]
So, I've reproduced the issue:

```
package io.smallrye.reactive.messaging.extension;

import io.reactivex.subscribers.TestSubscriber;
import org.eclipse.microprofile.reactive.messaging.Message;
import org.junit.jupiter.api.Test;
import org.reactivestreams.Publisher;

public class TestCase {

    /**
     * According to the specification of @{@link Publisher}:
     *
     *    "A Publisher can serve multiple Subscribers subscribed subscribe(Subscriber) dynamically at various points in time."
     *
     * Which is not true for the publisher created and returned by @{@link EmitterImpl::getPublisher}
     */
    @Test
    public void showcase() {
        EmitterImpl<String> emitter = new EmitterImpl<>("my-channel", "BUFFER", 128, 128);
        Publisher<Message<? extends String>> publisher = emitter.getPublisher();

        TestSubscriber<Message<? extends String>> sub1 = new TestSubscriber<>();
        publisher.subscribe(sub1);

        TestSubscriber<Message<? extends String>> sub2 = new TestSubscriber<>();
        publisher.subscribe(sub2);

        sub1.assertNoErrors();
        sub2.assertNoErrors(); // <-- will fail
    }
}
```
I'll raise a bug at smallrye.

**Comment by cescoffier** [comment]
Got a fix in SmallRye Reactive Messaging.

**Comment by cescoffier** [comment]
The issue in SmallRye Reactive Messaging has been fixed, however, this issue won't be fixed until:

1. SmallRye Reactive Messaging get released
2. We update the version in Quarkus

**Comment by cescoffier** [comment]
This has been fixed (with the update to SmallRye Reactive Messaging 2.0.2)
