### ISSUE TITLE
test OpenTracing in dev mode

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7980]
**Description**
I'm thinking adding/removing the `@Traced` annotation (or a bean with that annotation), plus perhaps adding/removing a JAX-RS endpoint (because those are traced automatically).

**Comment by Ladicek** [comment]
I filed this when I was doing QE work (reviewing test coverage), and didn't address it myself.

**Comment by geoand** [comment]
@rsvoboda I assume this has been done, can you confirm?

**Comment by geoand** [comment]
In any case, OpenTracing has been replaced by OpenTelemetry, so let's close this

**Comment by rsvoboda** [comment]
I will put it on our todo to check if the described scenario is covered for OTel.

**Comment by geoand** [comment]
🙏🏼
