### ISSUE TITLE
Make io.quarkus.security.common available as standalone

### ISSUE THREAD

**Issue by zulq** [quarkusio/quarkus#7988]
Would like to use the `io.quarkus.security.common.BcryptUtil` for password hashing with `JWT` instead of `security-jpa`. Currently ussing `spring-security-crypto`.

**Comment by dmlloyd** [comment]
You could use the underlying library, `org.wildfly.security:wildfly-elytron-credential`.  If you look at the source of `BcryptUtil`, the usage should be fairly obvious.

**Comment by zulq** [comment]
@dmlloyd added the package but can't locate `BcryptUtil`.

**Comment by dmlloyd** [comment]
It's not a package, it's an artifact, and `BcryptUtil` isn't in there.  As I said, if you look at the source of `BcryptUtil` you can see the underlying API that it is using.

**Comment by zulq** [comment]
@dmlloyd, ref link please.

**Comment by sberyozkin** [comment]
@zulq what JWA algorithm do you use with JWT ?

**Comment by zulq** [comment]
using the in-built quarkus `JWT` generator. See sample here: [Quarkus JWT](https://github.com/zulq/quarkus-jwt)

**Comment by zulq** [comment]
Figured out this is found in `quarkus-elytron-security-common`.
