### ISSUE TITLE
@Authenticated works, but @RolesAllowed("*") doesn't

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7994]
**Describe the bug**
I'm used to writing `@RolesAllowed("*")` when I want to let all authenticated users have access. (That is, all authenticated users are authorized to that particular method/class.)

The documentation (https://quarkus.io/guides/security#standard-security-annotations) specifically says:

> Quarkus also provides the `io.quarkus.security.Authenticated` annotation that will permit any authenticated user to access the resource (equivalent to `@RolesAllowed("*")`).

I interpret that as: `@Authenticated` is a quality of life improvement, but I can use both `@Authenticated` and `@RolesAllowed("*")` and they have the same meaning.

The javadoc of `@Authenticated` says:

> This is equivalent to the Jakarta EE8 {@code RolesAllowed("**")} construct.

OK, that's says `"**"` instead of `"*"`, but I'd interpret that as, again, I can use both interchangeably.

However, neither `@RolesAllowed("*")` nor `@RolesAllowed("**")` actually work. That is, authenticated users are _not_ authorized. The only way that actually works is `@Authenticated`.

**Expected behavior**
`@RolesAllowed("*")` works.

**Actual behavior**
`@RolesAllowed("*")` doesn't work, I have to use `@Authenticated`.

**To Reproduce**
1. Add a JAX-RS resource, such as:
```java
@Path("/everyone")
@RolesAllowed("*")
public class EveryoneResource {
    @GET
    public String get(@Context SecurityContext security) {
        return "Hello, " + security.getUserPrincipal().getName();
    }
}
```
2. Set up HTTP auth (see below for config file).
3. Perform an authenticated request against `/everyone` and observe authorization failure.

**Configuration**
```properties
quarkus.http.auth.basic=true

quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.albert=E!nst3iN
quarkus.security.users.embedded.roles.albert=admin
```

**Additional context**
Per the EJB spec (chapter 12.2.5.2 in EJB 3.2 Core spec), `**` means all roles.

Per the Servlet spec (chapter 13.3 in Servlet 4.0 spec), `**` means all roles and `*` should not be used (`HttpServletRequest.isUserInRole("*")` must always return `false`).

The JAX-RS specification doesn't seem to define this, but the `QuarkusResteasySecurityContext.isUserInRole` method already checks for `**` and returns `true` for all authenticated users.

On the other hand, SmallRye JWT uses `*` to mean "all roles" when processing `@RolesAllowed`.

Quarkus documentation is ambiguous in this regard, as explained above.

I personally would prefer if we could just use `*`, but it seems we really should use `**` (and fix the documentation and SmallRye JWT).

**Comment by Ladicek** [comment]
Fix would be easy (and I can submit a PR), but we need to agree what to do.

Ideas? CC @sberyozkin @michalszynkiewicz @stuartwdouglas

**Comment by stuartwdouglas** [comment]
I think we should use ** as per the spec and fix the docs.

**Comment by sberyozkin** [comment]
@Ladicek Hi Ladislav, if `smallrye-jwt` already supports `*` then we should likely keep it for now but also enhance it to support `**` but indeed document across all the extensions that `**` is the way to go (as Stuart also suggested)

**Comment by Ladicek** [comment]
Thanks @stuartwdouglas @sberyozkin, I'll submit a PR with fixes and tests.

I'll verify if the SmallRye JWT bits are used (as it currently seems to me that security in Quarkus is a blend of SmallRye JWT, parts of Elytron and some Quarkus-specific stuff, some of which is in-project and some in an extra `quarkus-security` project, which doesn't help with understanding :-) ) and if so, submit a PR to SmallRye JWT as well.

**Comment by Ladicek** [comment]
Submitted #8082.
