### ISSUE TITLE
s2i binary build - tar filename too long

### ISSUE THREAD

**Issue by eformat** [quarkusio/quarkus#8003]
**Describe the bug**
s2i build using latest 1.3.0.FINAL

mvn clean package -Dquarkus.container-image.build=true

[ERROR] Caused by: java.lang.RuntimeException: file name 'lib/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-api-1.0.jar' is too long ( > 100 bytes)

**Expected behavior**
Long File Names handled by dekorate & tar

**Actual behavior**
Get runtime exception

**To Reproduce**

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-container-image-s2i</artifactId>
        </dependency>

mvn clean package -Dquarkus.container-image.build=true

**Configuration**
```
# configure the MongoDB client for a single node cluster on localhost
quarkus.mongodb.connection-string = mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@${MONGODB_SERVICE_HOST}:${MONGODB_SERVICE_PORT}/${DATABASE_NAME}
#quarkus.mongodb.connection-string = mongodb://localhost:27017
# mandatory if you don't specify the name of the database using @MongoEntity
quarkus.mongodb.database = cats
quarkus.http.cors=true
quarkus.swagger-ui.always-include=true
# openshift/kubernetes buildand deployment configuration using dekorate
quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.name=cats
quarkus.kubernetes.part-of=cats
quarkus.kubernetes.name=cats
quarkus.kubernetes.version=1.0-rc.1
quarkus.openshift.labels.app=cats
quarkus.openshift.version=latest
quarkus.openshift.image-pull-policy=Always
quarkus.kubernetes.replicas=1
quarkus.kubernetes.readiness-probe.initial-delay=0s
quarkus.kubernetes.readiness-probe.period=10s


quarkus.s2i.base-jvm-image=quay.io/quarkus/ubi-quarkus-native-s2i:20.0.0
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux virt 5.5.8-200.fc31.x86_64 #1 SMP Thu Mar 5 21:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.o.FINAL
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven-3.6.3
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc31.x86_64/jre
Default locale: en_NZ, platform encoding: UTF-8
OS name: "linux", version: "5.5.8-200.fc31.x86_64", arch: "amd64", family: "unix"

**Additional context**

Stacktrace

1. 

[INFO] Initializing dekorate session.
[INFO] Default s2i build generator....
[INFO] Registering s2i handler!
[INFO] Registering s2i handler!
[INFO] Generating manifests.
[INFO] Processing kubernetes configuration.
[INFO] Processing openshift configuration.
[INFO] Processing s2i configuration.
[INFO] Closing dekorate session.
[INFO] [io.quarkus.container.image.s2i.deployment.S2iProcessor] Performing s2i binary build with jar on server: https://api.hivec.sandbox526.opentlc.com:6443/ in namespace:cats2.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.194 s
[INFO] Finished at: 2020-03-20T07:56:13+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.3.0.Final:build (default) on project pet-battle-api: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.s2i.deployment.S2iProcessor#s2iBuildFromJar threw an exception: java.lang.RuntimeException: Error creating the s2i binary build archive.
[ERROR] 	at io.quarkus.container.image.s2i.deployment.S2iProcessor.createContainerImage(S2iProcessor.java:246)
[ERROR] 	at io.quarkus.container.image.s2i.deployment.S2iProcessor.s2iBuildFromJar(S2iProcessor.java:192)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:938)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:273)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: file name 'lib/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-api-1.0.jar' is too long ( > 100 bytes)
[ERROR] 	at io.dekorate.deps.commons.compress.archivers.tar.TarArchiveOutputStream.handleLongName(TarArchiveOutputStream.java:683)
[ERROR] 	at io.dekorate.deps.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:358)
[ERROR] 	at io.dekorate.utils.Packaging.putTarEntry(Packaging.java:125)
[ERROR] 	at io.dekorate.utils.Packaging$2.visitFile(Packaging.java:109)
[ERROR] 	at io.dekorate.utils.Packaging$2.visitFile(Packaging.java:92)
[ERROR] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
[ERROR] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
[ERROR] 	at io.dekorate.utils.Packaging.packageFile(Packaging.java:92)
[ERROR] 	at io.quarkus.container.image.s2i.deployment.S2iProcessor.createContainerImage(S2iProcessor.java:241)
[ERROR] 	... 13 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by geoand** [comment]
Hi,

This has been fixed by: https://github.com/quarkusio/quarkus/pull/7944 and will be part of `1.3.1.Final`
