### ISSUE TITLE
Tone down the need for hotrod-client.properties to use the Infinispan Client

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#802]
This is mostly to focus on the docs, so to express a single and simple way to configure the Hot Rod client: by using the standard Protean configuration entries.

To get to that point, it's possible we need to first improve / revisit which things need to be exposed via this file.

If we really still mention a `hotrod-client.properties`, that should be limited to a final note meant for specific advanced uses. The expectation is that the most common use cases won't need this file.

Possibly needs to re-iterate on the Infinispan Quickstart a couple of times to nail this?

**Comment by gsmet** [comment]
The PR got merged so let's close it.
