### ISSUE TITLE
Testcontainers - FixedHostPortGenericContainer throws NullPointer on method getContainerIpAddress()

### ISSUE THREAD

**Issue by BaptisteCyrill** [quarkusio/quarkus#8030]
**Describe the bug**
If I start a FixedHostPortGenericContainer during my test phase, a NullPointer is thrown on method getContainerIpAddress(). This only happens with Quarkus version 1.3.0.Final. On version 1.2.1.Final everything is fine.

**Expected behavior**
IP address will be returned.

**Actual behavior**
A NullPointerException is thrown.

**To Reproduce**
1. Download example project in `https://bitbucket.org/aki_joeris/myservice`
2. Open the project in your ide
3. Run test `de.taf.autolane.MyResourceTest` - it will fail
4. Change property `quarkus-universe-bom.version` in `pom.xml` to version `1.2.1.Final`
5. Run test `de.taf.autolane.MyResourceTest` again - it will be ok

**Configuration**
- see test project `application.properties`

**Screenshots**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux jojo-020 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
 - Quarkus version or git rev: 1.3.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): maven

**Additional context**
Test project in `https://bitbucket.org/aki_joeris/myservice`

**Comment by geoand** [comment]
Hi,

Thank you for reporting.
This issue has already been fixed in `master` by #7880 and the fix will be part of `1.3.1.Final`.
