### ISSUE TITLE
Resources clashing in multi-module Gradle project with more than one library module with ZipException: duplicate entry

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#8032]
Using **1.3.0** it seems that quarkusBuild is not handeling resources of multiple library modules correctly when they have the same name. 

For example, all my modules are having an **application.properties** file which clashes and more importantly, the required **META-INF/beans.xml** to make dependency injection working with library modules clashes, making the use of multiple library modules unusable

> java.util.zip.ZipException: duplicate entry: META-INF/beans.xml
>   	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.filterZipFile(JarResultBuildStep.java:596)
>   	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.copyLibraryJars(JarResultBuildStep.java:472)
>   	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.doThinJarGeneration(JarResultBuildStep.java:437)
>   	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:326)
>   	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:152)
>   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   	at java.lang.reflect.Method.invoke(Method.java:498)
>   	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:938)
>   	at io.quarkus.builder.BuildContext.run(BuildContext.java:273)
>   	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
>   	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
>   	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
>   	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
>   	at java.lang.Thread.run(Thread.java:748)
>   	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
>   Caused by: java.util.zip.ZipException: duplicate entry: META-INF/beans.xml
>   	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
>   	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.filterZipFile(JarResultBuildStep.java:584)
>   	... 16 more

Problem could be related to https://github.com/quarkusio/quarkus/pull/7441

**Comment by gsmet** [comment]
@mklueh could you prepare a quick reproducer?

**Comment by mklueh** [comment]
@gsmet I´ll try to create one and update the issue with the url

**Comment by mklueh** [comment]
This was a false alarm. I could not reproduce it in the reproducer project, so I did a **gradle clean** on my original project which has solved the issue

**Comment by gsmet** [comment]
Thanks for the follow-up!

**Comment by mageddo** [comment]
I'm with this exactly issue, [here a demo][1] to reproduce the issue 

```bash
./gradlew clean build
```
Try run it 2 or 3 times if it works at the first execution, the command bellow works great though

```bash
./gradlew clean quarkusDev
```

[1]: https://github.com/mageddo/java-examples/tree/quarkus-issue-8032/quarkus/quarkus-gradle-reactjs-example

**Comment by aloubyansky** [comment]
@mageddo `clean build` is constantly failing for me
````
> Task :application:test

StockPriceServiceTest > mustGetErrorOnInsertAndRollbackJustTheSecondWhenUsingNestedPropagation() PASSED

StockPriceServiceTest > mustGetErrorOnInsertAndRollbackAllRecords() FAILED
    org.opentest4j.AssertionFailedError at StockPriceServiceTest.java:65

StockResourceTest > mustGetStocks() FAILED
    org.jdbi.v3.core.statement.UnableToExecuteStatementException at StockResourceTest.java:26
        Caused by: org.postgresql.util.PSQLException at StockResourceTest.java:26

StockPriceMDBTest > mustConsumeAndSave() PASSED

4 tests completed, 2 failed
````
````
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "stock_pkey"
  Detail: Key (idt_stock)=(PAGS) already exists.
````
`clean quarkusBuild` seems to always work.
