### ISSUE TITLE
Expose metrics on a separate port

### ISSUE THREAD

**Issue by Meemaw** [quarkusio/quarkus#8049]
**Description**
It is a common pattern to expose metrics on a separate port (that is not exposed via Ingress) than the application server itself. Exposing `/metrics` to the "world" is not exactly acceptable for a production server.

Related https://github.com/coreos/prometheus-operator/issues/800

**Comment by Meemaw** [comment]
Ah, this looks like a duplicate of https://github.com/quarkusio/quarkus/issues/7893

**Comment by jmartisk** [comment]
Yes, let's close this and discuss in the original issue. Thanks!
