### ISSUE TITLE
Infinispan Client should auto-enable needs it has on encryption

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#805]
The Infinispan Client guide today suggests that in certain configurations, such as using encryption via the Hot Rod client, some extra flags shall be enabled on the native-image tasks (see the docs for details).

People shouldn't be bothered with this, let's automate it!

**Comment by karesti** [comment]
I totally agree on this, how can we make this automate?

**Comment by wburns** [comment]
This is always enabled now without user interaction. https://github.com/quarkusio/quarkus/blob/master/extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java#L89
