### ISSUE TITLE
Zipkin integration

### ISSUE THREAD

**Issue by agentS** [quarkusio/quarkus#8053]
Hi,

I hope that my issue is in the right place. A friend of mine and I are developing a mini project for one of our university's classes and we want to demonstrate distributed tracing across various services. Since [IBM's OpenLiberty](https://openliberty.io) which the other service is based upon has excellent support for [Zipkin](https://zipkin.io/), we want to use Zipkin instead of Jaeger for tracing; both servers implement the OpenTracing standard.

However, I failed how to figure out a way to make my Quarkus-based application send its traces to Zipkin. I tried setting the configuration parameter `quarkus.jaeger.endpoint` to various values (including `http://127.0.0.1:9411/api/v2/spans`, and `http://127.0.0.1:9411/zipkin/api/v2/spans`), but none of them worked.

Therefore, I would be most grateful if somebody could provide me a description on how to set the Microprofile OpenTracing client to the Zipkin collector. Thank you so much!

If this question is in the wrong place, I'll post it on StackOverflow, but this has become such a hostile place.

**Comment by sberyozkin** [comment]
@agentS It may be better to open a `smallrye-open-api` issue, perhaps there is already a way there to plugin alternative tracing providers

**Comment by agentS** [comment]
Thanks, I'll check their repository.

**Comment by pavolloffay** [comment]
@sberyozkin it is  `SmalRye-OpenTracing` and not `SmallRye-OpenAPI`.

SmallRye-OpenTracing is vendor-neutral. It can work with any tracer. Quarkus choose to use Jaeger. What happens in Quarkus is when `quarkus-smallrye-opentracing` is on classpath it automatically chooses to use Jaeger as preferred tracer.

@agentS what tracing backend are you using? Jaeger can natively collect data in Zipkin format. If your clients are instrumented with Zipkin just point them to the Jaeger server and enable Zipkin endpoint in Jaeger. Then configure Quarkus to use `b3` propagation. This ensures that spans started in Zipkin instrumented service can be continued in Jaeger instrumented service.

https://www.jaegertracing.io/docs/1.17/getting-started/#migrating-from-zipkin
https://quarkus.io/guides/opentracing#quarkus-jaeger_quarkus.jaeger.propagation

**Comment by Ladicek** [comment]
I have _briefly_ looked into using Zipkin with SmallRye OpenTracing a while ago (cca a year back, perhaps more). If I remember correctly, SmallRye OpenTracing requires the tracer to provide a `TracerResolver` (see https://github.com/opentracing-contrib/java-tracerresolver), which isn't available for Zipkin (at least I didn't fine one in Brave). Considering how small the `TracerResolver` implementation is for Jaeger (see https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-tracerresolver), it should be relatively simple to implement rudimentary one for Zipkin yourself. I wanted to try this myself, but never found the time, and it has never been a priority.

**Comment by agentS** [comment]
Thanks for the help, @Ladicek and @pavolloffay!

@pavolloffay We have not set on a specific Tracing backend yet, we just tried out Zipkin, because the [OpenLiberty guide](https://openliberty.io/guides/microprofile-opentracing.html) suggested it.

I'm going to try switching to Jaeger for OpenTracing and use its Zipkin compatibility mode, then.

@Ladicek Thanks for the pointers. Maybe I'll have time to implement a Zipkin tracer resolver in the course of this project, but its not our top priority. I was just curious how to do this using Quarkus.

**Comment by pavolloffay** [comment]
> @Ladicek Thanks for the pointers. Maybe I'll have time to implement a Zipkin tracer resolver in the course of this project, but its not our top priority. I was just curious how to do this using Quarkus.

It is not something that is officially supported. Feel free to comment back with findings or open a PR that would enable you to do it. We can at least support it with a minimal hacking around.

**Comment by lenalebt** [comment]
Hey, did you solve this? I do have a case where I'd like to report traces back to a zipkin backend (or rather: zipkin-gcp, which integrates zipkin with the gcloud tracing backend). It already is forwarding zipkin headers, but it is trying to report to the zipkin server in the jaeger format. I'm already deep in debugging for how to work around this, but maybe you already have a solution?
