### ISSUE TITLE
Constructor of bean with @Startup annotation is called twice

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#8062]
Constructor of bean with @Startup annotation is called twice, @mkouba fyi

Tried with https://quarkus.io/guides/getting-started#bootstrapping-the-project ++ FooBean

```java
package org.acme.getting.started;

import javax.enterprise.context.ApplicationScoped;
import io.quarkus.runtime.Startup;

@ApplicationScoped
@Startup
public class FooBean {
    FooBean() {
        System.out.println("Init ..");
    }
}
```

```
Init ..
Init ..
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-03-22 10:13:40,042 INFO  [io.quarkus] (main) getting-started 1.0-SNAPSHOT (powered by Quarkus 1.3.0.Final) started in 0.686s. Listening on: http://0.0.0.0:8080
2020-03-22 10:13:40,072 INFO  [io.quarkus] (main) Profile prod activated.
2020-03-22 10:13:40,072 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```

**Comment by mkouba** [comment]
This works as designed (and required by the spec). For a normal scoped bean a client proxy is used instead of the contextual instance for injection, observers notification, etc. So the no-args constructor is first called when instantiating the proxy (which is a subclass of `FooBean`) and then for the contextual instance. It's a good practice to use a `@PostConstruct` callback to initialize the bean. Also if your bean declares a bean constructor with parameters (injection points) you would not observe this behavior either (client proxy is always instantiated via the noa-args constructor). Another solution is to switch to `@Singleton` or `@Dependent` for which a client proxy is not created at all.

**Comment by mkouba** [comment]
In fact, I was wrong! Client proxies should not be used for observers. I'll fix it next week.

**Comment by mkouba** [comment]
I've sent a [PR](https://github.com/quarkusio/quarkus/pull/8087) that partially fixes you problem. However, note that the no-args constructor will be called once a client proxy is needed, i.e. when the bean is injected somewhere. This is a well-known limitation of CDI.

**Comment by sfeuerhahn** [comment]
The issue does not seem to be fixed in version 1.9.2 of Quarkus. The no args constructor is called twice when using @Startup even though the bean is not inject anywhere.

**Comment by mkouba** [comment]
> The issue does not seem to be fixed in version 1.9.2 of Quarkus. 

So first of all it not an issue but a well known limitation as described above. Even if we don't create a client proxy for an observer it will be created once the bean is actually used (upon the first method invocation).

> The no args constructor is called twice when using the Startup annotation even though the bean is not inject anywhere.

A contextual instance is also created if you obtain a bean via `CDI.current()` and programmatic lookup. Could it be the case?

**Comment by sfeuerhahn** [comment]
> A contextual instance is also created if you obtain a bean via CDI.current() and programmatic lookup. Could it be the case?

I don't think so. When I only add: `void startup(@Observes StartupEvent event) {} ` to the application scoped class, then the constructor is only called once. When I add `@Startup`instead, then the constructor is called twice.

**Comment by mkouba** [comment]
> When I add @Startup instead, then the constructor is called twice.

I see. You're actually right, for `@Startup` we obtain the bean instance via `Arc.container().instance(bean)`, so the client proxy is involved. We could modify the code to access the contextual instance directly. However, it's not a big win (for the reasons mentioned above).

**Comment by sfeuerhahn** [comment]
>  However, it's not a big win (for the reasons mentioned above).

I agree. I cannot judge if it is worth the effort.
