### ISSUE TITLE
keycloak.policy-enforcer doesn't take effect when setting root context path in a certain pattern

### ISSUE THREAD

**Issue by BigFatDog** [quarkusio/quarkus#8064]
**Describe the bug**
I turn on keycloak security authorization for my api and turn it off for *public* apis including:
- metrics
- openapi
- health
I can access public apis as expected, however, when I set my `quarkus.http.root-path` to `/api/workbench`, I always get `401 unauthorized error` when accessing public apis

Please note: from my observations this bug **only** apply to root context path `/api/workbench`.
It works with other paths such as:
- /api
- /api/work
- /api/workwork2

I tested both in my application and in [quarkus quickstart](https://github.com/quarkusio/quarkus-quickstarts)

**Expected behavior**
I should access to public API

**To Reproduce**
1.  clone from [security-keycloak-authorization-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/security-keycloak-authorization-quickstart)
2. remove public api java code: `PublicResource.java` 
3. add dependencies:
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-opentracing</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-metrics</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
```

**Configuration**
```properties
# OIDC Configuration
quarkus.oidc.auth-server-url=some-url
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret
quarkus.http.cors=true

# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true

quarkus.keycloak.policy-enforcer.paths.1.path=/api/workbench/public/*
quarkus.keycloak.policy-enforcer.paths.1.enforcement-mode=DISABLED

quarkus.http.root-path=/api/workbench
quarkus.smallrye-openapi.path=/public/openapi
quarkus.swagger-ui.path=/public/swagger-ui
quarkus.smallrye-health.root-path=/public/health
```

**Environment:**
 - quarkus version:
Quarkus 1.3.0.final
 - Output of `java -version`: 
`openjdk version "13" 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)`

**Comment by sberyozkin** [comment]
Hi @BigFatDog 
Should the policy path exclude the root context path, and instead have
```
quarkus.keycloak.policy-enforcer.paths.1.path=/public/*
```
CC @pedroigor

**Comment by BigFatDog** [comment]
@sberyozkin  I tried but this approach doesn't work neither in my application nor in [security-keycloak-authorization-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/security-keycloak-authorization-quickstart).

when set:
`quarkus.http.root-path=/api/work`

this works:
`
quarkus.keycloak.policy-enforcer.paths.1.path=/api/work/public/*
`
This one gets `401 unauthorized error`:
`
quarkus.keycloak.policy-enforcer.paths.1.path=/public/*
`

**Comment by sberyozkin** [comment]
@BigFatDog thanks, what is `/api/work`, do you have `quarkus.http.root-path=/api/work` ?

**Comment by BigFatDog** [comment]
@sberyozkin Yes, as stated in my previous reply:

> when set:
quarkus.http.root-path=/api/work

**Comment by sberyozkin** [comment]
@BigFatDog Oh sorry, missed it.

So, if you have
```
quarkus.http.root-path=/api/workbench
quarkus.keycloak.policy-enforcer.paths.1.path=/api/workbench/public/*
```
then it does not work but if you have

```
quarkus.http.root-path=/api/work
quarkus.keycloak.policy-enforcer.paths.1.path=/api/work/public/*
```
 
then it does work ?

**Comment by BigFatDog** [comment]
@sberyozkin That's all fine.

Yes, exactly the case: it doesn't work **only** when `/api/workbench` is used.

**Comment by sberyozkin** [comment]
@BigFatDog I wonder, if this issue a duplicate of #6807 ?
CC @pedroigor

**Comment by BigFatDog** [comment]
Hi @sberyozkin I've just checked [#6807](https://github.com/quarkusio/quarkus/issues/6807#issuecomment-599400163).
I don't think it is a duplicate for now but I'm not totally sure.  Let me have a closer look later.

**Comment by pedroigor** [comment]
Not sure if related. 

It is a weird issue though, considering it works when using paths other than `/api/workbench`. I'll give this one a try.

@BigFatDog Thanks.

**Comment by BigFatDog** [comment]
After double check I still tend to think this issue is not a duplicate.

Thank you guys a lot for your time on this. @sberyozkin  @pedroigor

**Comment by sberyozkin** [comment]
@BigFatDog thanks.
@pedroigor I wonder if `workbench` is a reserved path segment in keycloak...

**Comment by BigFatDog** [comment]
@sberyozkin @pedroigor ,
My latest observation is:  this issues happens when setting the `quarkus.http.root-path`,  it is not related to a specific path pattern.

In fact /api/work` didn't work. I got it wrong because I configured `/api/workbench` in `keycloak` but not for`/api/work`. After I add `/api/work/*` to the `keycloak` resource, both of the two path patterns share the same behavior.

Is  this still considered a bug of `quarkus`? I'll explore if there's anything that I can do on the `keycloak` side.

**Comment by sberyozkin** [comment]
@BigFatDog Np, can you please post the updated configuration ?

**Comment by pedroigor** [comment]
@BigFatDog That explains. It is not an issue. The policy enforcer takes the resources managed in Keycloak to map them to your application paths so that access can be enforced accordingly.

**Comment by sberyozkin** [comment]
@pedroigor Hi Pedro, so Keycloak policies have to be updated to `/api/work/something` ?
It seems too tied to the individual deployment so would not scale across multiple one with the different contexts.
Having only `/something` set in KC seems better, can `quarkus-keycloak-authorization` check `quarkus.http.root-path` and deduct it from the request path. Or as suggested earlier, check if Quarkus specific authorization policy already says something about a given path ? So that we can have `quarkus-keycloak-authorization` synced better witth Quarkus :-) ?

**Comment by BigFatDog** [comment]
Hi @sberyozkin, @pedroigor
I believe this is a duplicate of #8207 
My latest configuration is:
1. in `application.properties`, I separate `public endpoints`(swagger, health) from `rest endpoints` via avoiding using `root context path`:
```
quarkus.oidc.auth-server-url=***
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=***
quarkus.http.cors=true

# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true

quarkus.keycloak.policy-enforcer.paths.1.path=/public/*
quarkus.keycloak.policy-enforcer.paths.1.enforcement-mode=DISABLED


quarkus.smallrye-openapi.path=/public/workbench/openapi
quarkus.swagger-ui.path=/public/workbench/swagger-ui
quarkus.smallrye-health.root-path=/public/workbench/health
quarkus.swagger-ui.always-include=true
```
2. in rest endpoints:
```
@Path("/api/workbench/projects")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Tag(name="project", description="CRUD operations on projects.")
public class ProjectApi {
```
3. in keycloak, only `/api/workbench/*` is configured
4. Still gets `401 error` with public endpoints, saying `not resource defined` from keycloak.

A desired behavior is `quarkus-keycloak-authorization` stops communicating with `keycloak` for these `public endpoints`.

Do I need to close this issue and mark it as a duplicate of #8207 ?

**Comment by sberyozkin** [comment]
@BigFatDog Did you mean #6807 ? If you agree it is a duplicate then please close this one

**Comment by sberyozkin** [comment]
@BigFatDog Hmm, probably not a duplicate of #6807, lets keep it open for a while so that we discuss it with Pedro a bit more

**Comment by pedroigor** [comment]
@BigFatDog Could you try setting `quarkus.keycloak.policy-enforcer.lazy-load-paths=true`. See https://quarkus.io/guides/security-keycloak-authorization#mapping-protected-resources.

It should make the policy enforcer to not load resources during startup and avoid going to the server to get a reference to the public path.

**Comment by pedroigor** [comment]
@BigFatDog Sorry for the delay. You should not get "resource not defined" and you should be able to access the paths you marked as DISABLED.

Can you check the latest release?

**Comment by pedroigor** [comment]
It seems related to this one https://github.com/quarkusio/quarkus/issues/8204. There I was also able to disable paths and access them. But there is a catch in regards to dev mode.

**Comment by sberyozkin** [comment]
Hi @BigFatDog @pedroigor let me close this issue as a duplicate of #9565
