### ISSUE TITLE
JWT RBAC not working in 1.3.0 FINAL

### ISSUE THREAD

**Issue by bbixler** [quarkusio/quarkus#8074]
**Describe the bug**
Following the JWT guide, [JWT RBAC Guide](https://quarkus.io/guides/security-jwt), JWT authentication no longer works in 1.3.0 FINAL

**Expected behavior**
Per the guide, authentication should be possible as follows using a generated JWT

$ curl -H "Authorization: Bearer eyJraWQ..." http://127.0.0.1:8080/secured/roles-allowed; echo
hello + jdoe@quarkus.io, isSecure: false, authScheme: MP-JWT, hasJWT: true

**Actual behavior**
Authentication is failing.

curl -v -H "Authenticate: Bearer eyJraWQiOiIvcHJpdmF0ZUtleS5wZW0iLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vdXNpbmctand0LXJiYWMiLCJqdGkiOiJhLTEyMyIsInN1YiI6Impkb2UtdXNpbmctand0LXJiYWMiLCJ1cG4iOiJqZG9lQHF1YXJrdXMuaW8iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqZG9lIiwiYXVkIjoidXNpbmctand0LXJiYWMiLCJiaXJ0aGRhdGUiOiIyMDAxLTA3LTEzIiwicm9sZU1hcHBpbmdzIjp7Imdyb3VwMSI6Ikdyb3VwMU1hcHBlZFJvbGUiLCJncm91cDIiOiJHcm91cDJNYXBwZWRSb2xlIn0sImdyb3VwcyI6WyJFY2hvZXIiLCJUZXN0ZXIiLCJTdWJzY3JpYmVyIiwiZ3JvdXAyIl0sImlhdCI6MTU4NDkzMTk2MCwiYXV0aF90aW1lIjoxNTg0OTMxOTYwLCJleHAiOjE1ODQ5MzIyNjB9.h3nbjQXcjiZ1AV-oWWTQtUV7K6bHm1PAVEZlXaGtgKSKTBD06d0LZ7hEpnXaCQ6IkmP848XcuRZnz7pJxQ2sg3lsrWXxHG4QtZIFwaPfBdS7aA2slCcvKUtBdjJQqmUTUoGKq4WERgXVqYW6q7QA9wmn4x10kn2VKdNGMQQkrDmBOrm4qhj_dJOngM2mc3-_2XNuXA1amTmgAtH-yVNsbXBBVBor9MTIi-u3IoCRX_6lfJ7Z-S24od31Ps7HBoC9GZyGOZq5UhnuCaqqe-KBCRRJcwZZa7odPgL37GGyJLfHMEIXQ6aXE0fqKjJaNV5bit5bkt4D62dYhxd-VsBxCA" http://127.0.0.1:8080/secured/roles-allowed\;
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /secured/roles-allowed; HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Authenticate: Bearer eyJraWQiOiIvcHJpdmF0ZUtleS5wZW0iLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vdXNpbmctand0LXJiYWMiLCJqdGkiOiJhLTEyMyIsInN1YiI6Impkb2UtdXNpbmctand0LXJiYWMiLCJ1cG4iOiJqZG9lQHF1YXJrdXMuaW8iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqZG9lIiwiYXVkIjoidXNpbmctand0LXJiYWMiLCJiaXJ0aGRhdGUiOiIyMDAxLTA3LTEzIiwicm9sZU1hcHBpbmdzIjp7Imdyb3VwMSI6Ikdyb3VwMU1hcHBlZFJvbGUiLCJncm91cDIiOiJHcm91cDJNYXBwZWRSb2xlIn0sImdyb3VwcyI6WyJFY2hvZXIiLCJUZXN0ZXIiLCJTdWJzY3JpYmVyIiwiZ3JvdXAyIl0sImlhdCI6MTU4NDkzMTk2MCwiYXV0aF90aW1lIjoxNTg0OTMxOTYwLCJleHAiOjE1ODQ5MzIyNjB9.h3nbjQXcjiZ1AV-oWWTQtUV7K6bHm1PAVEZlXaGtgKSKTBD06d0LZ7hEpnXaCQ6IkmP848XcuRZnz7pJxQ2sg3lsrWXxHG4QtZIFwaPfBdS7aA2slCcvKUtBdjJQqmUTUoGKq4WERgXVqYW6q7QA9wmn4x10kn2VKdNGMQQkrDmBOrm4qhj_dJOngM2mc3-_2XNuXA1amTmgAtH-yVNsbXBBVBor9MTIi-u3IoCRX_6lfJ7Z-S24od31Ps7HBoC9GZyGOZq5UhnuCaqqe-KBCRRJcwZZa7odPgL37GGyJLfHMEIXQ6aXE0fqKjJaNV5bit5bkt4D62dYhxd-VsBxCA
>
< HTTP/1.1 401 Unauthorized
< www-authenticate: Bearer {token}
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0

**To Reproduce**
1. Follow the guide exactly - https://quarkus.io/guides/security-jwt
2. Run the security-jwt-quickstart from the Quarkus quickstarts
3. Generate a JWT - mvn exec:java -Dexec.mainClass=org.acme.security.jwt.GenerateToken -Dexec.classpathScope=test
4. Test it - $ curl -H "Authorization: Bearer eyJraWQ..." http://127.0.0.1:8080/secured/roles-allowed; echo

**Configuration**
Using the same from the guide...

mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem 
mp.jwt.verify.issuer=https://quarkus.io/using-jwt-rbac (also tried http://127.0.0.1:8080 and http://localhost:8080)
quarkus.smallrye-jwt.enabled=true 

**Environment (please complete the following information):**
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)
Mac OS Catalina

Thank you.

**Comment by sberyozkin** [comment]
@bbixler the quickstart tests pass, but I'll have a look

**Comment by bbixler** [comment]
Apologies, but after further troubleshooting, I've determined that this issue was on my side with my code.

@sberyozkin - Your point about the tests running made me realize the issue had to be on my end.

Thanks for your patience.
