### ISSUE TITLE
Security - RolesAllowed returns 403 with invalid content

### ISSUE THREAD

**Issue by seseso** [quarkusio/quarkus#8107]
On a resource, I have a @RolesAllowed annotation with @Produces(MediaType.APPLICATION_JSON), but, when Forbidden, the returned response by quarkus security is a 403 (correct), header Content-Type: application/json  but with a body text "Forbidden", wich is an invalid JSON.

**Expected behavior**
Not sure. Empty body or a valid JSON.

**To Reproduce**
1. Create a resource method with @RolesAllowed and @Produces
2. Invoke the method with a disallowed role
3. See the body response and header Content-Type mismatch

**Comment by sberyozkin** [comment]
Hi @seseso thanks, I think this is a duplicate of #5998, I will close this issue as a duplicate, please watch #5998

**Comment by seseso** [comment]
My bad, didn't found the opened issue.

Thanks!
