### ISSUE TITLE
quarkus.container-image.group could be blank

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#8117]
it's not mandatory to have a group for docker image in the repository for private docker repository.

so we have

quarkus.container-image.registry=docker.example.com:5000
quarkus.container-image.group=
quarkus.container-image.tag=latest

**Comment by geoand** [comment]
We can certainly do this, but I would like the opinion of @iocanel and @Ladicek before I make any change.

**Comment by geoand** [comment]
If we don't allow it be black, we should throw a proper exception.

**Comment by Ladicek** [comment]
Isn't our configuration a bit too rigid here? The entire idea that a container image name always looks like `<registry>/<group>/<name>:<tag>` is flawed IMHO. For example, the GitLab registry [supports](https://docs.gitlab.com/ee/user/packages/container_registry/#build-and-push-images-from-your-local-machine) "up to three levels of image repository names":

- registry.example.com/group/project:some-tag
- registry.example.com/group/project/image:latest
- registry.example.com/group/project/my/image:rc1

How would our configuration look like for each of them? I think I've seen code that splits around `/` -- would that code work for the 2nd and 3rd case?

**Comment by geoand** [comment]
> Isn't our configuration a bit too rigid here? 

That's what I am asking essentially :)

But the examples you show are in the opposite direction of what @survivant asks.
For cases 2) and 3), we indeed don't generate that. But on the other hand, should we be able to generate that? And if so, what would a simple and consistent configuration strategy look like that would allows to be that flexible?

**Comment by Ladicek** [comment]
Yea, I'm just showing that there are many possibilities. What we're doing now is probably a good default, but the configuration structure doesn't allow the required flexibility.

What we can configure now is `registry`, `group`, `name` and `tag`, which is put together as `registry/group/name:tag`. IMHO, it should be possible to configure the entire string. But I don't see a way how to make that possible without making the set of config options confusing as hell :-)

**Comment by geoand** [comment]
Yes exactly... it is always a delicate balance :)

**Comment by geoand** [comment]
@Ladicek WDYT about making group optional? Have you seen that anywhere?

**Comment by Ladicek** [comment]
I have not, but apparently it is valid, see e.g. https://docs.docker.com/registry/deploying/#copy-an-image-from-docker-hub-to-your-registry. Making the group optional makes sense to me.

**Comment by geoand** [comment]
Thanks for the info!

I'll take it up then (hopefully in time for `1.3.1.Final`)
