### ISSUE TITLE
Reverse-router

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#814]
Very often it's important to generate URIs for pieces of the REST service we implement:

- for [`Link` headers](https://www.w3.org/wiki/LinkHeader)
- for [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) inside resources
- to generate templates (email, html)
- for redirects

JAX-RS has support for reverse-routing, but it just sucks:

```java
    @GET
    @Path("router")
    public String testRouter(@Context UriInfo uriInfo) {
        
        URI uri1 = uriInfo.getBaseUriBuilder().path(TestEndpoint.class).path(TestEndpoint.class, "testRouter").build();
        Assertions.assertEquals("http://localhost:8080/test/router", uri1.toString());
…
```

It sucks for many reasons:

- Java does not have method literals (it has class literals), so we're down to using strings for method names
- The API requires you to call `.path` first with the class, then a second time with the same class and the method name, but _only_ if the method is annotated with `@Path` (not mandatory). If you mess it up you either have an exception or a missing path part
- Not type-safe in terms of the URI parameters that the path requires

I have a reverse-router implementation that solves the first two issues (can't do anything about the third):

```java
    @GET
    @Path("router")
    public String testRouter() {
        
        Assertions.assertEquals("http://localhost:8080/test/router", Router.getURI(TestEndpoint::testRouter).toString());
        Assertions.assertEquals("http://localhost:8080/test/router-test/stef", Router.getURI(TestEndpoint::testMethod1, "stef").toString());
        Assertions.assertTrue(Router.getURI(TestEndpoint::testMethod2, 2, new byte[] {20}).toString()
                .startsWith("http://localhost:8080/test/router-test/2-"));
…
```

This relies on two tricks:

- On the JVM, lambda method references such as Class::method can be roughed up into spilling the name of the method they point to.
- On SVM, _naturally_ this does not work… BUT I have a `ClassVisitor` that knows how to substitute calls to `Router.getURI(Class::method)` into `_Router.getURI(Class.class, "method", new Class<?>[0])` (last one being for the parameter types required to disambiguate overloaded methods).

So… it works on SVM too.

It's not pretty in terms of implementation, though it's not less efficient than the manual alternative, and it's much nicer.

I would propose this to RESTEasy, except it's a bit small, and it would not work on SVM for us, so we would still need special support for the transformation I do.

Initially I pictured Panache to be more than just the JPA layer we're working on for #646, with all the bells and whistles that a dev would want that belonged into more than a single extension, so it was incubated there, but I'm not sure if that's what we will end up with. If we do want that, I'm not sure where it should end up.

But the more pressing questions is: _do_ we want that?

@emmanuelbernard @asoldano others?

**Comment by sberyozkin** [comment]
Hi Stephane,

`URI uri1 = uriInfo.getBaseUriBuilder().path(TestEndpoint.class).path(TestEndpoint.class, "testRouter").build();`

can be done as

`URI uri1 = uriInfo.RequestUriBuilder().build();` ?

**Comment by FroMage** [comment]
Well that's a special case where you make a URI to the current endpoint, and you don't need to change its parameters. But that never happens.

**Comment by sberyozkin** [comment]
It is not a special case, I'd've added more paths to the request URI if example a new resource is created, `/resources` -> `/resources/a`, etc.
So you'd like to replace something in say `https://localhost:8080/webapp/router/a`, for example, have `https://localhost:8080/webapp/router/b` instead ?
One way to do it if you know which segment(s) will be replaced, is to do 
```
URI uri = uriInfo.getBaseUriBuilder().path("{path1}/{path2}").build("testRouter", "b");
``` 
This should produce what is needed.  I agree that the JAX-RS way of using the classes, methods is not good. But I guess I'm missing something in the proposal as well.

**Comment by FroMage** [comment]
Well this proposal does away with using paths or classes or methods, and just uses method references: `Router.getURI(Controller::method, "params")` this way you don't have to know what paths the method is using, it will just work. That's much more ergonomic.

**Comment by geoand** [comment]
I wonder if we could also use this to make testing endpoints easier

**Comment by FroMage** [comment]
Now that @Ladicek is merging wildfly/jandex#84 we could resurrect this :)

**Comment by geoand** [comment]
@FroMage you did this for Renarde, right? If so, I think we can close this.

**Comment by FroMage** [comment]
Yeah, I guess we can say that if anybody wants this, they have to use Renarde. We can always revisit if micro-services users also want a reverse-router.
