### ISSUE TITLE
API for application data caching

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#8140]
Offer a programmatic API for application data cache offering features above and beyond the annotation based ones.
Follow up of https://github.com/quarkusio/quarkus/issues/3306

CC @karesti and @gwenneg

**Comment by nimo23** [comment]
One question: 
Will quarkus use an already established **caching provider** (e.g. Infinispan) for its API? I think quarkus could indeed use, for example "Infinispan-embeeded" and provide its caching services (e.g. annotations and beyond) around this core.

**Comment by emmanuelbernard** [comment]
Right now we only plan to sue the existing cache implementation which uses caffeine.

If we go and support alternative providers like Infinispan or Hazelcast, we need to be very careful as these involve remote calls and the API must not assume locality cc @Sanne

**Comment by nimo23** [comment]
In my opinion, _Quarkus Caching Layer_ should only use one cache provider internally. There is no need to support different caching providers (the same as there is no need to support different jpa providers). Quarkus should stick with only one good caching provider and build on that. I think caching providers like infinispan would be better suited for the _Quarkus Caching Layer_ than to only use caffeine because I would like to see the following features for _Quarkus Caching Layer_:

- off-heap-cache
- hot and cold cache
- caching data should not be limited to RAM but to storage (for inspiration see https://github.com/OpenHFT/Chronicle-Map or https://github.com/jankotek/mapdb)
- annotations for domain layer to enable and control the caching

**Comment by nimo23** [comment]
>as these involve remote calls and the API must not assume locality

Using caching providers in _embeeded mode_ (e.g. infinispan-embeeded) can be run locally (and does not involve remove calls).

**Comment by Sanne** [comment]
Sure: Infinispan is built on Caffeine providing such additional capabilities. We'll likely base such capabilities on the Infinispan code base, either directly or reimplementing bits and pieces with the help of the Infinispan team as best suited.

**Comment by emmanuelbernard** [comment]
> > as these involve remote calls and the API must not assume locality
> 
> Using caching providers in _embeeded mode_ (e.g. infinispan-embeeded) can be run locally (and does not involve remote calls).

I know but there is likely little value in swapping implementation in that case compared to the extra complexity of explaining how to configure stuff depending on the provider (more complex doc for example)

**Comment by seseso** [comment]
One thing I miss is an enabled flag on prpperties to enable or disable the extension. I have quite a long list of classes methods annotated and would like to easily enable/disable the extension, for instance, to compare performance. Unless I missed something in the docs, today this is not possible and would require the removal of all annotations from my code.

**Comment by gwenneg** [comment]
You are absolutely right @seseso, there is currently no way to disable the cache extension using a property, but I could easily take care of that missing flag. It looks like a build time property (meaning the flag could not be changed at runtime) would be enough, what do you think about that?

**Comment by seseso** [comment]
It would solve my use case for sure. And it would bring it closer to other
extensions that provide a similar flag!

**Comment by gwenneg** [comment]
I created #11139 to address your request @seseso.

**Comment by agentgonzo** [comment]
Should this be closed as done? https://quarkus.io/guides/cache

**Comment by mkouba** [comment]
> Should this be closed as done?

@agentgonzo I don't think so, this issue is about adding a "programmatic API", i.e. to be able to inject  a `Cache` object representation and obtain a cached value for a given key.

**Comment by gwenneg** [comment]
@mkouba is right, this is still an ongoing subject.

**Comment by vteferrer** [comment]
In my opinion, a programmatic way to access and operate the Cache is mandatory. The current operation is a good starting point but as a project grows, quickly emerge many situations where the minimalistic current API is not enough. I look forward to your next steps in this direction with great interest!

**Comment by gwenneg** [comment]
Thank you for your interest @vteferrer! There is actually an open PR (see #8631) with a proposal of programmatic caching API. It is purposely restricted to data access methods for now but there will certainly be more features in the future (like stats for example). Feel free to comment it if you have any idea or suggestion!

**Comment by vteferrer** [comment]
I´ve reviewed the open PR and I only miss a method to retrieve the keys associated with a Cache. This would be useful to  to know what content has a Cache and find a particular item

**Comment by gwenneg** [comment]
Thanks for reviewing the PR @vteferrer! I pushed https://github.com/quarkusio/quarkus/pull/8631/commits/bdb47f4f90e9016b27552f8126d7d34fb6017e38 to expose the cache keys in `CaffeineCache` (it might be part of the `Cache` API in the future).

**Comment by vteferrer** [comment]
The idea behind this change would be this, wouldn´t it?

```
    @Inject 
    @CacheName("my-cache")
    Cache cache;

    ...

    CaffeineCache caffeineCache = cache.asSpecializedCache(CaffeineCache.class);
    Set<Object> cachedKeys = caffeineCache.keySet();
    ...
```

I think it´s great!

Thanks!

**Comment by gwenneg** [comment]
Yes, that's exactly the idea.

**Comment by giulianoAX** [comment]
any workaround available at the moment to retrieve the Caffeine cache stats, while we wait for the PR #8631 to be merged?
