### ISSUE TITLE
Config sources are loaded and invoked multiple times

### ISSUE THREAD

**Issue by giova333** [quarkusio/quarkus#8145]
**Describe the bug**
We are trying to implement custom `org.eclipse.microprofile.config.spi.ConfigSource` implementation for AWS Systems Manager Parameter Store(SSM)

Everything works well, but we noticed that configSources are created and invoked 3 times and 3 

calls are performed to SSM accordingly(first time during the maven build phase).

We use serverless architecture in AWS with native images and as you can

imagine, multiple calls to the external system are not the desired behavior for us because they affect startup time. 

**Expected behavior**
Config sources should be loaded only once

**Actual behavior**
Config sources are loaded multiple times(in our case 3 times)

**Comment by stuartwdouglas** [comment]
So it is expected that this will happen twice, once when you build the application to get the build time config, and a second time when you actually start the app to get the runtime config.

3 times sounds like a problem though.

**Comment by giova333** [comment]
@stuartwdouglas Is it possible to distinguish the current state(deployment or runtime)?
With development profile, I see that different classloaders are used but of course we cannot rely on that.

**Comment by giova333** [comment]
I solved the problem using `Class.forName("io.quarkus.deployment.steps.RuntimeConfigSetup");`
That helped me not to load the config at the deployment phase.
But for some reason at runtime phase, `ConfigSource` are instantiated twice, that is strange and to me looks like a bug. I solved that by using inner singleton which was initialized only during the class loading, no matter how much time constructor was invoked.
```
public class AwsSSmConfigSource extends AbstractConfigSource {


    public AwsSSmConfigSource() {
        super(AwsSSmConfigSource.class.getSimpleName(), 200);
    }

    @Override
    public Map<String, String> getProperties() {
        return AwsSsmConfigHolder.getProperties();
    }

    @Override
    public String getValue(String propertyName) {
        return AwsSsmConfigHolder.getProperties().get(propertyName);
    }

    private static class AwsSsmConfigHolder {

        private static final String RUNTIME_CLASS = "io.quarkus.deployment.steps.RuntimeConfigSetup";

        private static final String REGION = "eu-west-1";

        private static final AwsSsmConfigHolder INSTANCE = new AwsSsmConfigHolder();

        private final Map<String, String> ssmProperties;

        private AwsSsmConfigHolder() {
            if (isRuntimePhase()) {
                this.ssmProperties = fetchSsmProperties();
            } else {
                this.ssmProperties = Collections.emptyMap();
            }
        }

        public static Map<String, String> getProperties() {
            return INSTANCE.ssmProperties;
        }

        private Map<String, String> fetchSsmProperties() {
            Optional<String[]> parameterNames = findParameterNames();

            if (!parameterNames.isPresent()) {
                return Collections.emptyMap();
            }

            AWSSimpleSystemsManagement client = AWSSimpleSystemsManagementClientBuilder
                .standard()
                .withCredentials(new EnvironmentVariableCredentialsProvider())
                .withRegion(REGION)
                .build();

            GetParametersRequest request = new GetParametersRequest()
                .withNames(parameterNames.get())
                .withWithDecryption(true);

            return client.getParameters(request)
                .getParameters()
                .stream()
                .collect(Collectors.toMap(Parameter::getName, Parameter::getValue));
        }

        private Optional<String[]> findParameterNames() {
            Map<String, String> envVariables = System.getenv();
            String ssmParameterNames = envVariables.get("SSM_PARAMETER_NAMES");
            return StringUtils.isNullOrEmpty(ssmParameterNames)
                ? Optional.empty()
                : Optional.of(ssmParameterNames.split(","));
        }

        private boolean isRuntimePhase() {
            try {
                Class.forName(RUNTIME_CLASS);
                return true;
            } catch (ClassNotFoundException e) {
                return false;
            }
        }

    }
}
```

**Comment by stuartwdouglas** [comment]
This is because there is a different config object created at static init (which corresponds to native image build time) and at the start of the actual runtime code.

@dmlloyd should the static init config be loading custom config sources? I would have thought it would just have the build time values?

**Comment by dmlloyd** [comment]
> @dmlloyd should the static init config be loading custom config sources? I would have thought it would just have the build time values?

We do provide the build time values at this stage, but there is probably no reason why other values can't be available too.  That said, we probably should not autodetect sources at static init time since it seems to result in unexpected behavior.  If it's desired to provide additional sources for this stage, it probably should be done via build item explicitly.

**Comment by squakez** [comment]
We've hit the same [issue](https://github.com/apache/camel-k-runtime/issues/625) and I've applied the workaround described by @giova333 to fix it. However it seems to be confirmed the behavior of double calls during runtime. I've created a simple [reproducer](https://github.com/squakez/test-quarkus-config-source) that I hope can help you spotting the problem.

Executing that you will see the following traces:
```
2021-02-11 10:12:19,355 INFO  [tes.ApplicationConfigSourceProvider] (main) Getting config sources for class loader QuarkusClassLoader:Deployment Class Loader
2021-02-11 10:12:19,355 INFO  [tes.ApplicationConfigSourceProvider] (main) Deploy phase
2021-02-11 10:12:19,919 INFO  [tes.ApplicationConfigSourceProvider] (Quarkus Main Thread) Getting config sources for class loader QuarkusClassLoader:Quarkus Runtime ClassLoader
2021-02-11 10:12:19,919 INFO  [tes.ApplicationConfigSourceProvider] (Quarkus Main Thread) Runtime phase
2021-02-11 10:12:19,919 INFO  [tes.ApplicationConfigSourceProvider] (Quarkus Main Thread) Fetching application and user properties
2021-02-11 10:12:20,020 INFO  [tes.ApplicationConfigSourceProvider] (Quarkus Main Thread) Getting config sources for class loader QuarkusClassLoader:Quarkus Runtime ClassLoader
2021-02-11 10:12:20,172 INFO  [io.quarkus] (Quarkus Main Thread) quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.11.2.Final) started in 0.933s. Listening on: http://localhost:8080
```
Notice that the `Getting config sources` is executed twice by runtime classloader, though the effects are minimized by the presence of the `Singleton`. I can tell that the same behavior happens in native execution:
```
[INFO] Getting config sources for class loader QuarkusClassLoader:Deployment Class Loader
[INFO] Deploy phase
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/squake/workspace/hello.
...
[quarkus-1.0.0-SNAPSHOT-runner:21689]        setup:   2,060.09 ms,  0.94 GB
10:13:16,471 INFO  [tes.ApplicationConfigSourceProvider] Getting config sources for class loader com.oracle.svm.hosted.NativeImageClassLoader@3c756e4d
10:13:16,495 INFO  [tes.ApplicationConfigSourceProvider] Runtime phase
10:13:16,495 INFO  [tes.ApplicationConfigSourceProvider] Fetching application and user properties
10:13:26,034 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
[quarkus-1.0.0-SNAPSHOT-runner:21689]     (clinit):     715.30 ms,  2.71 GB
...

$ ./target/quarkus-1.0.0-SNAPSHOT-runner 
2021-02-11 10:14:31,349 INFO  [tes.ApplicationConfigSourceProvider] (main) Getting config sources for class loader jdk.internal.loader.ClassLoaders$AppClassLoader@17c3020
2021-02-11 10:14:31,361 INFO  [io.quarkus] (main) quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 1.11.2.Final) started in 0.013s. Listening on: http://0.0.0.0:8080
```
It seems that in this case the call is done both during the native image build phase and later at runtime, though also here the effects are minimized by the singleton.

@stuartwdouglas, @dmlloyd what do you think?

**Comment by gsmet** [comment]
@radcortez any chance you could have a look at this one? It's a problem for the Camel team.

It might warrant a discussion and in this case, let's organize one.

Thanks!

/cc @lburgazzoli

**Comment by radcortez** [comment]
Sure, I'll have a look.

**Comment by radcortez** [comment]
I had a quick look and I first tried to just remove the discovered sources from static init, which solves the duplication issue. This does create an additional one, where some libraries (RESTEasy) which use the Config to configure itself, is also part of static init, meaning that it will miss its configuration and not work properly. There might be other libraries in this situation.

The only good solution right now, it's to probably add a specific build item that can contribute sources to static init and drop the auto discovered. This would allow us to fine tune sources at this stage, but we would need to be careful to make sure that all discovered required sources are manually registered.

**Comment by argenstijn** [comment]
A question. So when i use rest easy as lib my configsource is loaded twice? 

I use quarkus 2.6.1 and i see the configsource is loaded twice while (not using @StaticInitSafe). I am using rest-easy-reactice.
Is this expected?

**Comment by argenstijn** [comment]
@radcortez @gsmet  See my quesiton above

**Comment by radcortez** [comment]
Yes, that is expected. A `ConfigSource` annotated with `@StaticInit` is initialized 3 times:

- At Build Time
- At Static Init
- At Runtime

When the `ConfigSource` is not annotated, then it is only initialized 2 times:

- At Build Time
- At Runtime

**Comment by argenstijn** [comment]
How can i only make sure it;s run at Runtime for a native image?

**Comment by argenstijn** [comment]
_When the ConfigSource is not annotated, then it is only initialized 2 times:

    At Build Time
    At Runtime_

Also when you just run a Test Using @QuarkusTest?

**Comment by radcortez** [comment]
> How can i only make sure it;s run at Runtime for a native image?

Are you seeing a source initializing multiple times in native image? It should only happen once (if they are not annotated with `@StaticInitSafe`. Some selected Quarkus sources are supposed to be used that way. The reason for this, is that some components require configuration during static init, but some sources may not be suitable for static init (imagine a source that uses the rest client to provide configuration values).

> Also when you just run a Test Using @QuarkusTest?

When running in a test, you always have the build part, so at least you get 2 inits (or 3 with the `@StaticInitSafe`).

**Comment by argenstijn** [comment]
_Are you seeing a source initializing multiple times in native image? It should only happen once (if they are not annotated with @StaticInitSafe. Some selected Quarkus sources are supposed to be used that way. The reason for this, is that some components require configuration during static init, but some sources may not be suitable for static init (imagine a source that uses the rest client to provide configuration values)._

Not tried yet due another problem i have. But only see it being called during the build as expected. 
.......
[aabserviceauthproxy-1.0.0-b8242844-runner:214]        (cap):     822.38 ms,  0.94 GB
_**[aabserviceauthproxy-1.0.0-b8242844-runner:214]        setup:   3,887.54 ms,  0.94 GB
12:23:53,396 WARN  [com.nn.aav.ins.aab.pro.bus.SecretConfigSource] AwsSsmConfigSource not retrieving any secrets because ENV system 'config_aws_paramstore_name' was not set**_
12:23:58,235 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
[aabserviceauthproxy-1.0.0-b8242844-runner:214]     (clinit):   1,117.22 ms,  5.66 GB
......

But i understand now how it works. Thanks for the explanation. Really appreciate it :)

**Comment by radcortez** [comment]
Great. Let me know if you need any additional clarification.
