### ISSUE TITLE
Unable to get DB Connection in @QuarkusTest + Jupiter Extension

### ISSUE THREAD

**Issue by tgippi** [quarkusio/quarkus#8148]
**Describe the bug**
Since `1.3.0.Final` calling `DriverManager.getConnection` in a test from a Jupiter Extension in combination with `@QuarkusTest` will throw an exception.
It seems that the Driver has been loaded by another `ClassLoader`.

When I downgrade quarkus to `1.2.1.Final` it works like expected.

The Jupiter Extension initializes the database by using Liquibase. The test should verify that the liquibase scripts are working.

**Expected behavior**
Calling `DriverManager.getConnection` in a test from a Jupiter Extension in combination with `@QuarkusTest` should return the connection object.

**Actual behavior**
Calling `DriverManager.getConnection` in a test from a Jupiter Extension in combination with `@QuarkusTest` throws an exception `SQL No suitable driver found for jdbc:h2:mem:test;DB_CLOSE_DELAY=-1...`.

**To Reproduce**
1. Clone the repository `git clone git@github.com:tgippi/quarkus-liquibase-issue.git`
2. Run the tests `mvn clean test`
3. See the exception
4. Downgrade to `1.2.1.Final`
5. Rerun the tests `mvn clean test`
6. See that it works

**Configuration**
```properties
quarkus.datasource.url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
quarkus.datasource.driver = org.h2.Driver
```

**Environment (please complete the following information):**
 - Output of `uname -a`: `Linux localhost.localdomain 5.5.5-200.fc31.x86_64 #1 SMP Wed Feb 19 23:28:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode, sharing)
```
 - Quarkus version `1.3.0.Final`
 - Build tool `mvn --version`: 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-11.0.6.10-0.fc31.x86_64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.5.5-200.fc31.x86_64", arch: "amd64", family: "unix"
```

**Additional context**
It looks like a class loading issue. The `java.sql.DriverManager` contains the driver `org.h2.Driver` but the following code in the `isDriverAllowed()` method returns false

`result = aClass == driver.getClass();`

While debugging I saw that `aClass.getClassLoader()` returns `ClassLoader$AppClassLoader`  
And `driver.getClass().getClassLoader()` returns `QuarkusClassLoader`

**Comment by geoand** [comment]
@tgippi Thanks for reporting.

Unfortunately your code won't without a small modification in the latest version of Quarkus (due to the ClassLoader changes that were made, and the fact that `DriverManager` doesn't have seem to have an option to accept a ClassLoader as input).

However you can still get your code to work with a minor modification, like so:

```
    private Connection getDatabaseConnection() throws Exception {
        String connectionString = Optional.ofNullable(url)
                .orElseGet(() -> {
                    try {
                        Properties prop = new Properties();
                        prop.load(this.getClass().getClassLoader().getResourceAsStream("application.properties"));
                        return prop.getProperty("quarkus.datasource.url");
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                });

       // we need to load the driver from the TCCL 
        Class<?> h2DriverClass = Class.forName("org.h2.Driver", true, Thread.currentThread().getContextClassLoader());
        return ((Driver) h2DriverClass.newInstance()).connect(connectionString, new Properties());
    }
```

Another option would be would probably be more robust is to use a `QuarkusTestResourceLifecycleManager`.

I am going to close as a result of my above explanation. If you feel that it should be re-opened, feel free to do so with your thoughts on the matter.
