### ISSUE TITLE
Add extension for hazelcast

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#8160]
Need share session use cluster manager like hazelcast etc when use websocket.

**Comment by nimo23** [comment]
Already there: https://github.com/quarkusio/quarkus/pull/6758

**Comment by geoand** [comment]
See https://github.com/quarkusio/quarkus/pull/6758

**Comment by emmanuelbernard** [comment]
Yes let's consider it a dupe of #6758 for now.
