### ISSUE TITLE
Implement the flow of GitHub Action jobs reporting Quarkus Platform readiness

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#8163]
**Context**

In this issue, we assume that some extensions of the platform live in the Quarkus monorepo and some live outside the Quarkus monorepo.

Making sure the platform works for every change to Quarkus core implementation, is naturally done in the CI job for the Quarkus Monorepo. But we need more for extensions living outside. 

**Proposition**

Here is a proposed model built on two flow of tests
1. Quarkus platform is build daily (or every push to Quarkus core?) on
    - the known fixed versions of the extensions (except the monorepo ones)
    - on a SNAPSHOT of Quarkus monorepo
2. Each external Quarkus extension has 
    a. a GitHub action job that runs the extension tests on the specific version of Quarkus the extension has been built on for every push to the extension master
        - this one does not improve the discovery of the platform stability  but is just recommended template of job for all extensions and help build 2.b.
    b. a GitHub action job that takes Quarkus monorepo SNAPSHOT and build the master version of the extension against it
        - value?
    c. a GitHub action job that takes Quarkus monorepo SNAPSHOT and build the stable tagged version of the extension against it
        - this one is technically a duplicate of 1. but
            - it runs on the extension's own GitHub action pool
            - it allows to detect a failure and report to the extension writer even if the quarkus platform job stops at the first failing extension
            - it might run more comprehensive tests than the smoke tests the Quarkus Platform runs for each extension

Upon failure, email or open an issue to the Quarkus issue tracker or/and the extension issue tracker.

With these flows, we allow within 24 hours to:
- know if Quarkus Core is breaking an existing published extension of the platform and are notified
- know if an extension master is not going to work on Quarkus master within 24 hours

This essentially limits the risk of adding external extensions to a 24 hour window. This does not address the need to control the source that Guillaume mentioned.
But the trust would likely be built differently. new external extensions in the platform would start as preview / experimental or graduating. After a few releases where things are fine and owners are reactive, we can graduate them and treated like the monorepo ones.

Questions:
- replace SNAPSHOT with DAILY build passing the tests?

**Excluded work (for now)**

Also test Quickstart on the latest platform

**Comment by emmanuelbernard** [comment]
@maxandersen @aloubyansky @gsmet I've written down the short feedback loop proposal between an external extension in the platform and the Quarkus monorepo. We can discuss from this.

**Comment by emmanuelbernard** [comment]
@maxandersen @geoand should we consider this one done?

**Comment by geoand** [comment]
@emmanuelbernard I think we should. This is pretty much what the ecosystem CI is and it's already proven useful by reporting stuff that we removed in Quarkus and broke external extensions (see https://github.com/quarkusio/quarkus/pull/9231 for example).
