### ISSUE TITLE
Kafka Client does not support SASL with JASS

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#8168]
**Describe the bug**

Kafka SASL is not supported in native mode.

Even with the added set of classes, it fails with:

```
Caused by: javax.security.sasl.SaslException: Cannot get userid/password [Caused by javax.security.auth.callback.UnsupportedCallbackException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user.]
 at com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:157)
        at com.sun.security.sasl.ClientFactoryImpl.createSaslClient(ClientFactoryImpl.java:94)
        at javax.security.sasl.Sasl.createSaslClient(Sasl.java:433)
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslClient$0(SaslClientAuthenticator.java:183)
        at java.security.AccessController.doPrivileged(AccessController.java:144)
        at javax.security.auth.Subject.doAs(Subject.java:423)
```

**Current Status**

I have added the following code to `io.quarkus.kafka.client.deployment.KafkaProcessor`.

```
reflectiveClass.produce(new ReflectiveClassBuildItem(true, false, SaslClientCallbackHandler.class.getName()));
        reflectiveClass.produce(new ReflectiveClassBuildItem(true, false, DefaultLogin.class.getName()));
        reflectiveClass
                .produce(new ReflectiveClassBuildItem(true, false,
                        AbstractLogin.DefaultLoginCallbackHandler.class.getName()));
        reflectiveClass.produce(new ReflectiveClassBuildItem(true, false, PlainLoginModule.class.getName()));
```

**Comment by gsmet** [comment]
@cescoffier You said you created a GraalVM issue, could you link it here?

**Comment by cescoffier** [comment]
@gsmet I didn't create the issue yet. I was about to pinpoint the issue to... JAAS!

```
props.put("sasl.jaas.config",
                   "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"foo\" password=\"bar\";");
```

SASL without JAAS works (writing the tests right now).

**Comment by cescoffier** [comment]
@dmlloyd By any chance do you have any idea about the usage of JASS in native mode?

**Comment by dmlloyd** [comment]
I think this is the first usage I've seen of JAAS in native mode.  In general, I'd avoid it (because it is a poor framework)!  But nothing special should be necessary, just the usual registering of things.

**Comment by tfve** [comment]
So, has anyone found a workaround yet?
@dmlloyd what do you mean with "just the usual registering of things"?

**Comment by dmlloyd** [comment]
With native images, anything that is expected to be accessible to reflection needs to be registered as such.

**Comment by cescoffier** [comment]
No workaround yet, I will go back to it shortly.

**Comment by schulzp** [comment]
@cescoffier, we ran into the same problem and work around it with a custom [`SaslClientCallbackHandler`](https://gist.github.com/schulzp/479ab2c85d9ca30bf8d5f505bd493097) which considers the native case where `AccessController.getContext() == null`

**Comment by cescoffier** [comment]
Amazing @schulzp ! We should definitely provide this class and document it.

**Comment by schulzp** [comment]
@cescoffier are you on it or shall I create a pull request?

**Comment by cescoffier** [comment]
@schulzp If you can open one, it would be great! 

Basically, you need:

* to provide the class in the kafka/runtime module
* document the usage in the documentation module
* in the KafkaProcessor register this class for reflection

**Comment by schulzp** [comment]
@cescoffier, sure, will do that.

How can I run my application (which already uses native JAAS/SASL) against a locally build of `quarkus:999-SNAPSHOT`? If I just run `clean install` and add it as a dependency I and up with the following maven build error: `Non-resolvable import POM: Failure to find io.quarkus:quarkus-universe-bom:pom:999-SNAPSHOT`. How does that `quarkus-universe-bom` come into existence?

**Comment by cescoffier** [comment]
Exactly, replace the universe bom with the quarkus bom

**Comment by tfve** [comment]
I added the @schulzp 's SaslClientCallbackHandler class to my project, registered it for reflection and set the "*.sasl.client.callback.handler.class" property. Now I'm getting this error:
```
org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.DefaultLogin
```

**Comment by cescoffier** [comment]
@tfve See the first post on this issue, it gives you the necessary changes.

**Comment by schulzp** [comment]
Thanks, @cescoffier. In which extension should the `NativeSaslClientCallbackHandler` reside? `kafka-client`? If so, should it set the `sasl.client.callback.handler.class` property by default (how?) or just document, that in case of native builds this has to be set, either for consumer/producer in case of `quarkus-smallrye-reactive-messaging` or in general for `quarkus-kafka-streams`.

**Comment by tfve** [comment]
> @tfve See the first post on this issue, it gives you the necessary changes.

Thanks, it worked!
Are those changes to KafkaProcessor going to be merged into master?

**Comment by gsmet** [comment]
@schulzp I'm totally not aware of what you're doing but couldn't we replace the default handler code via a GraalVM substitution automatically?

I don't know if it's just a small code update or something fundamentally different.

**Comment by gsmet** [comment]
That would be nicer as you wouldn't need any configuration at all.

**Comment by schulzp** [comment]
@gsmet, sure, I can do that (already suspected that this was the preferred way to go). Currently I'm extending the default `SaslClientCallbackHandler`, so if I replace that class, I would have to copy the original code (that is still used while running on a JVM) into my replacement class.

**Comment by cescoffier** [comment]
So, I was thinking about the substitution. I would do it in a second step once we have this in. We need to see where we need to `replace` and how much collateral damage need to be adjusted. (let's avoid the "Dexter" mode for once ;-) )

**Comment by gsmet** [comment]
@schulzp you can substitute only specific methods via GraalVM substitutions so you don't have to copy the whole class.

@cescoffier not sure I understand what you're saying. But I agree we need to make it work before thinking about changing it to substitutions. But I would like to have the final solution substitution-based if possible.

**Comment by cescoffier** [comment]
I agree the goal is a substitution. My concerns are that substitutions are not easy to be "right" and create a dependency on upstream code that may change over time. Unfortunately, I'm not sure we can come up with a good test for it. So, we need to make to implement a substitution very carefully. 
This is why I would like to see this in first, and then, let's work on a substitution.

**Comment by schulzp** [comment]
@gsmet got it to work with GraalVM substitution. I'm not sure if my way of implementing the runtime configuration meets your standards. This was the only way to get a dynamic set of properties in there. Maybe this approach would work for/could be reused in #4961?
