### ISSUE TITLE
Switch to Java 11

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#818]
This is the blanket issue to cover switching to Java 11.  Here's the check list:

- [ ] Introduce an artifact which contains the contents of the `com.oracle.svm.driver` package from the SubstrateVM build (the default coordinates are `com.oracle.substratevm:svm-driver`; use `mx maven-install` to install it locally after checking out & building with the `vm-1.0.0-rc11` tag under Java 11)
- [ ] Make the native image generator depend on this artifact
- [ ] Change `org.jboss.shamrock.creator.phase.nativeimage.NativeImagePhase` to use `com.oracle.svm.driver.NativeImage` from the driver artifact directly for normal builds, and via container execution of `java` (11) for container builds
- [ ] Delete checks for `GRAALVM_HOME`
- [ ] Update POMs to require Java 11 (use `<release>11</release>` in the compiler plugin, not `-source`/`-target`)
- [ ] Full integration test run on Linux & Windows

Note that some of these steps will have to change if the class loading changes come in first.

**Comment by bobmcwhirter** [comment]
https://github.com/oracle/graal/issues/1392

**Comment by gsmet** [comment]
@dmlloyd should I close this one? Looks like the effort is now made in separate issues specific to GraalVM?

**Comment by dmlloyd** [comment]
Yep this is out of date.

**Comment by dmlloyd** [comment]
Please see #5691 for the up-to-date migration steps.
