### ISSUE TITLE
Define our Kotlin roadmap for the next 3 and 6 months delivery

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#8194]
While working on the roadmap ideas, I realize that Kotlin is a big blind spot of mine. Let's define what we want achieved for the next 3 to 6 months. Assigning @evanchooly to lead this.

https://github.com/orgs/quarkusio/projects/5

**Comment by akoufa** [comment]
Hello to all and thank you for the great work on Quarkus. Do you have any news regarding the focus of the Quarkus team on improving the experience for Quarkus Kotlin projects? Will this be in the roadmap for the next month?
