### ISSUE TITLE
Using the REST Client with Multipart not working in all cases

### ISSUE THREAD

**Issue by ranko6** [quarkusio/quarkus#8223]
**Describe the bug**
(Describe the problem clearly and concisely.)
Proxying multipart call using `@RestClient` is not working with only GET resource, you have to have at least one POST.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Expected behavior is successful multipart call toward another service even when there is only GET resource.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
Results is:
RESTEASY003215: could not find writer for content-type multipart/form-data type: org.acme.rest.client.multipart.MultipartBody

**To Reproduce**
1.  Follow this guide till end: https://quarkus.io/guides/rest-client-multipart
2. At this point everything should work so run test to confirm everything is working as intended.
3. Replace only `@POST` with `@GET` at
Class: `MultipartClientResource `
Method: `public String sendFile() throws Exception`

So, from:
```
@POST
@Path("/multipart")
@Produces(MediaType.TEXT_PLAIN)
public String sendFile() throws Exception {
    MultipartBody body = new MultipartBody();
    body.fileName = "greeting.txt";
    body.file = new ByteArrayInputStream("HELLO WORLD".getBytes(StandardCharsets.UTF_8));
    return service.sendMultipartData(body);
}
```
to:
```
@GET
@Path("/multipart")
@Produces(MediaType.TEXT_PLAIN)
public String sendFile() throws Exception {
    MultipartBody body = new MultipartBody();
    body.fileName = "greeting.txt";
    body.file = new ByteArrayInputStream("HELLO WORLD".getBytes(StandardCharsets.UTF_8));
    return service.sendMultipartData(body);
}
```

Now if you run it, it should fail with:

> RESTEASY003215: could not find writer for content-type multipart/form-data type: org.acme.rest.client.multipart.MultipartBody

To make it work, leave sendFile as GET and add another simple POST method in same class. Such as:
```
@POST
@Path("/temp")
@Produces(MediaType.TEXT_PLAIN)
public String simplePost() throws Exception {
    return "something";
}
```
Now it should work with GET.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18363.720]
 - Output of `java -version`: openjdk version "1.8.0_202"
 - Quarkus version or git rev: 1.3.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by gsmet** [comment]
I explained it to @irenakezic on Zulip.

The thing is that it never works. The `@POST` is missing a `@Consumes` annotation so all the providers are registered. That's why it works.

The `@GET` doesn't need a `@Consumes` so it doesn't trigger the registration of all the providers.

I gave @irenakezic some guidance on how to debug this.

**Comment by irenakezic** [comment]
Debugging the issue I came to the conclusion that reader providers are registered correctly for all @Consumes annotations. However, when invoking the Rest client service from MultipartClientResource class in the example the writer provider is needed as well.
A solution might be to search for the @RestClient annotation when registering providers. In case @RestClient annotation is found register writer providers (in addition to reader) for all @Consumes annotations in the client service.
@gsmet what do you think?
