### ISSUE TITLE
OracleXADataSource SQLException: Invalid Oracle URL: OracleDataSource.makeURL

### ISSUE THREAD

**Issue by sekaijin** [quarkusio/quarkus#8249]
**Describe the bug**
when using OracleXADataSource an invalid URL exception is `throws`

**Expected behavior**
Add oracle XADatasource and run JPA operations

**Actual behavior**
Add OracleXADataSource 
build => 
`SQLException: L'URL Oracle indiquée n'est pas valide: OracleDataSource.makeURL`

**To Reproduce**
1. add oracle jdbc on your project
2. define quarkus datasource using OracleXADataSource
3. build

**Configuration**
```properties
quarkus:
      datasource:
            driver:  oracle.jdbc.xa.client.OracleXADataSource
            url: 'jdbc:oracle:thin:@myhost:284/ASID'
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Windows10
 - Output of `java -version`:  java8
 - GraalVM version (if different from Java):  none
 - Quarkus version or git rev: 1.3.0-FINAL
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn 3.6.4

**Additional context**
I debugged step by step. the url is not transmitted to the xa driver only the login and password are.

In the driver's setUrl method is never called.
the problem comme with OracleXADataSource
this class has a setter for the url named setURL but quarkus use setUrl

**Solution**
1 add new OracleXADataSource class extends oracle.jdbc.xa.client.OracleXADataSource
```java
package maia;

import java.sql.SQLException;

public class OracleXADataSource extends oracle.jdbc.xa.client.OracleXADataSource
{
   private static final long serialVersionUID = -7361423077146488092L;

   public OracleXADataSource() throws SQLException{
      super();
   }

   public synchronized void setUrl(String url) {
      setURL(url);
   }
}
```
2 use new driver class
```properties
quarkus:
      datasource:
            driver:  maia.OracleXADataSource
            url: 'jdbc:oracle:thin:@myhost:284/ASID'
```

**Comment by gastaldi** [comment]
This is no longer reproducible in 3.13, closing as outdated. Please reopen with a reproducer project if that still happens
