### ISSUE TITLE
ClassCastException in @ParameterizedTest: Base Class from Different Class Loader

### ISSUE THREAD

**Issue by schulzp** [quarkusio/quarkus#8251]
**Describe the bug**
Running a `@QuarkusTest` fails with a `java.lang.ClassCastException`, see [MWE](https://github.com/schulzp/quarkus-classcast-mwe).

**Expected behavior**
The tests passes.

**Actual behavior**
When using `@ParameterizedTest` with `@MethodSource`, see [MWE](https://github.com/schulzp/quarkus-classcast-mwe), the test fails with the following exception:
`java.lang.ClassCastException: class org.hamcrest.core.Is cannot be cast to class org.hamcrest.Matcher (org.hamcrest.core.Is is in unnamed module of loader 'app'; org.hamcrest.Matcher is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @7188af83)`

However, if the test parameters are [mapped manually](https://github.com/schulzp/quarkus-classcast-mwe/blob/master/src/test/java/com/example/ExampleResourceTest.java#L28) (using a regular `@Test`) it passes.

**To Reproduce**
1. Check out the [MWE](https://github.com/schulzp/quarkus-classcast-mwe)
2. run `./mvnw verify`

**Configuration**
```properties
# no properties are set explicitly
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
   ```
   Darwin Kernel Version 19.3.0; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
   ```
 - Output of `java -version`: `11.0.1, vendor: Oracle Corporation`
 - Quarkus version or git rev: `1.3.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
   ```
   Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
   Java version: 11.0.1, vendor: Oracle Corporation, runtime: [...]
   Default locale: de_DE, platform encoding: UTF-8
   OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
   ```
**Additional context**
The behavior occurred when I upgraded quarkus from 1.2.1.Final to 1.3.0.Final/1.3.1.Final.

**Comment by geoand** [comment]
The issue should be fixed by #8252
