### ISSUE TITLE
Quarkus Kubernetes - Host is ignored

### ISSUE THREAD

**Issue by UnvirtualHH** [quarkusio/quarkus#8257]
**Describe the bug**
When using the Kubernetes Extension and adding exposed=true and host=service.bla.com
the host entry is not added to the generated ingress part. Host is always ""

**To Reproduce**
1.  Create a small application
2. add Kubernetes extension
3. Add config properties and build by execute package
4. Check the configs

**Configuration**
```properties
 quarkus:
    kubernetes:
      group: bla
      replicas: 2
      imagePullPolicy: Always
      host: service.bla.com
      expose: true

``` 

**Environment (please complete the following information):**
 - Output of `java -version`: 11
 - Quarkus version or git rev: 1.3.1.Finial
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  maven

**Comment by geoand** [comment]
Thanks for reporting,

I'll take a look
