### ISSUE TITLE
Quarkus OIDC web-app cleanup state & code

### ISSUE THREAD

**Issue by lodrantl** [quarkusio/quarkus#8259]
When using OIDC extension in web-app mode the authorization code flow looks like this:

1. user accesses http://localhost:8080/locked
2. get redirected to http://keycloak/auth.....?redirect_url=http://localhost:8080/locked
3. logs in and gets redirected back to http://localhost:8080/locked?state=.....&code=......

Now the OIDC extension has the authorization code and is able to request the token. The problem is however that the URL remains polluted with the Keycloak/OIDC provider code and state parameters. Native Keycloak adapter for Wildfly solves this problem by adding another 302 redirect at the end of step 3 so a step 4 could be:

4. gets redirected back to http://localhost:8080/locked.

It would be nice if Quarkus OIDC extension supported something like this too.

**Comment by sberyozkin** [comment]
One extra redirect is already done when the original request_uri overlaps with the `request_uri`. So with this feature we can have one more extra redirect in that case. So if we do it it would likely need to be optional.
