### ISSUE TITLE
Quarkus 1.3.x: AMQP Emitter<JsonObject> does not set content-type

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#8274]
**Describe the bug**
When using an `Emitter<JsonObject>` of the `quarkus-smallrye-reactive-messaging-amqp` extension, Quarkus 1.2.1.Final added the Content-Type: application/json to the properties of the message. This is also documented under https://smallrye.io/smallrye-reactive-messaging/#_forwarding_messages_to_amqp: `(Vert.x) JSON Array or JSON Object (send as binary with content type set to application/json)`

In Quarkus 1.3.x, the content type property is not set in the message. 

**Expected behavior**
Content type should be set. 

**Actual behavior**
Content type is missing.

**To Reproduce**
1. Download [reproducer-smallrye-amqp-emitter-not-working.zip](https://github.com/quarkusio/quarkus/files/4403371/reproducer-smallrye-amqp-emitter-not-working.zip) and unzip it.
2. In the unzipped directory run `docker-compose up -d` to start an activemq broker. 
3. Run `./mvnw quarkusDev` to start the container
4. Open http://localhost:8080/hello in a browser

**Comment by andreas-eberle** [comment]
@cescoffier: Is there an option to set the application/json header or might this be a bug in smallrye-reactive-messaging?

**Comment by cescoffier** [comment]
That will be fixed in Quarkus 1.4 :-)

**Comment by cescoffier** [comment]
For now, you can send an AMQP MEssage or a Message with OutgoingAmqpMetadata setting the content-type explicitly.

**Comment by andreas-eberle** [comment]
Thanks! Is it in the CR1 already? Or not yet?

**Comment by cescoffier** [comment]
Not yet.

**Comment by andreas-eberle** [comment]
@cescoffier: It seems this didn't make it into 1.4.1.Final, am I right? I still see the same problem.

**Comment by cescoffier** [comment]
I need to check, but I don't believe this was backported.

**Comment by gsmet** [comment]
@cescoffier what's the PR?

**Comment by cescoffier** [comment]
it's more when the reactive messaging 2.0 was integrated.

**Comment by gsmet** [comment]
Yeah, this wasn't included in 1.4.

**Comment by gsmet** [comment]
Hmmm, let me correct that. It was included. So there's something else going on.

**Comment by cescoffier** [comment]
Yes... most probably be a bug.

**Comment by cescoffier** [comment]
(Assigned to myself so I won't forget to look)

**Comment by cescoffier** [comment]
Damned! Found the issue... Fixing it. Unfortunately, it's upstream.

**Comment by cescoffier** [comment]
https://github.com/smallrye/smallrye-reactive-messaging/pull/527 fixes it.

**Comment by andreas-eberle** [comment]
Will this make it into 1.4.2.Final?

**Comment by gsmet** [comment]
@andreas-eberle can you confirm it fixes your problem?

**Comment by andreas-eberle** [comment]
Is it in the quarkus repo already? Or do you have to manually update it before I build quarkus?

**Comment by gsmet** [comment]
You would need to build SmallRye Reactive Messaging, update the Quarkus bom and then build Quarkus.

**Comment by gsmet** [comment]
I'm reopening this one until we have upgraded Reactive Messaging so that we don't forget about it.

**Comment by cescoffier** [comment]
SmallRye Reactive Messaging 2.0.2 has been integrated.

**Comment by andreas-eberle** [comment]
I just built the current master and it seems to work. Thx @cescoffier for the fix. Is there an approximate date for Quarkus 1.4.2 already?

**Comment by cescoffier** [comment]
Tomorrow if I recall correctly.
