### ISSUE TITLE
Cannot use base image from private registry with container-jib extension

### ISSUE THREAD

**Issue by pyranja** [quarkusio/quarkus#8282]
**Describe the bug**

Building an image of a quarkus application with the container-jib extension fails, if the base image is hosted in a private registry.

**Expected behavior**

The jib build discovers docker credentials from well known locations or uses provided `quarkus.container-image.username` and `quarkus.container-image.password` to authenticate when pulling the base image from a private registry.

**Actual behavior**

The build fails with a `FORBIDDEN` error when pulling the base image.

**To Reproduce**
1. Create a quarkus project with container-jib extension
2. Set `quarkus.jib.base-jvm-image` to use an image from a private registry
3. Run the build

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.3.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**

I think the JibProcessor is only adding credentials (retriever) for pushing an image. The jib maven plugin has config options to separately configure credentials for pulling too (auth.from.*).
If replicating all config options of jib is not feasible, at least adding the well-known retrievers could be a compromise.

**Comment by geoand** [comment]
Thanks for reporting!

#8288 should fix the problem
