### ISSUE TITLE
Enrich Kubernetes SPI with build items other extensions might need.

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#8295]
**Description**

Often we have other extension need to contribute to the strucutre of the generated kubernetes manifests. Some examples:

- smallrye-health contriubtes Probe configuration
- vertx contributes port configuration
- container-image-xxx contribute image configuration
- kubernetes-client contributes service account & role binding configuration

As discussed in the mailiing list we should expand the converage, to at least:

- [ ] Environment variables
- [ ] Labels
- [ ] Annotations

**Comment by iocanel** [comment]
@lordofthejars @geoand @maxandersen

**Comment by geoand** [comment]
:+1:

**Comment by lordofthejars** [comment]
ConfigMaps
Secrets

**Comment by lordofthejars** [comment]
Great!!! Thanks.
