### ISSUE TITLE
Should be able to run Integration tests without native mode

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#8298]
[INFO] Running org.acme.NativeExampleResourceIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.088 s <<< FAILURE! - in org.acme.NativeExampleResourceIT
[ERROR] org.acme.NativeExampleResourceIT  Time elapsed: 0.088 s  <<< ERROR!
org.junit.platform.commons.JUnitException: Quarkus native image start failed, original cause: java.lang.RuntimeException: Unable to automatically find native image, please set the native.image.path to the native executable you wish to test
Caused by: java.lang.RuntimeException: Unable to automatically find native image, please set the native.image.path to the native executable you wish to test

mars 30, 2020 1:16:01 P.M. io.quarkus.runtime.Timing printStopTime
INFO: Quarkus stopped in 0.042s
[INFO]

I'll have integration tests in my project.  What is the best pratice for Quarkus for running IT without native mode.  Yes, I'll try to go native later, but for now.. I'll run them without native mode.

I added this section in my pom.xml

```
<profile>
  <id>integration-test</id>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <includes>
                <include>**/*IT.java</include>
              </includes>
              <excludes>
                <exclude>**/*Native*IT.java</exclude>
              </excludes>

            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</profile>
```

it works like that, but I wanted to know if there was something in QuarkusTest framework to exclude the native tests when not in "native mode".  I know, I have some wierd usecases something :)

but if I do that, I'll pick up the tests with @NativeImageTest   and they will failed like the error given before.

what are your thoughs about that ?

I actually think this is a very good feature request. I personally find the idea that integration tests are reserved for testing native binaries very bad. There are other use cases for integration tests, e.g. running tests against the application deployed in Kubernetes/OpenShift. This would let that problem go away. Mind filing an issue on GitHub? :-)

LT

**Comment by bvarner** [comment]
according to https://quarkus.io/guides/getting-started-testing#native-executable-testing, the native image test annotation is deprecated.

I've been using @QuarkusIntegrationTest, and I'm able to run with `-Pnative` and without, by adding a failsafe execution to my normal build plugins listing.

**Comment by survivant** [comment]
Oh!  that's a old issue that I filled.  It was a issue in 2020.  Let's close this issue.
