### ISSUE TITLE
Unrecognized configuration key "quarkus.http.insecure-requests" was provided; it will be ignored

### ISSUE THREAD

**Issue by rahulwagh** [quarkusio/quarkus#8309]
**Describe the bug**
I was trying to implement a rest endpoint and it worked properly. After that, I was trying to disable the insecure-requests by defining the following property in application.properties

`quarkus.http.insecure-requests=disabled`
`quarkus.http.ssl.certificate.key-store-file=/keystore/keystore.jks`
`quarkus.http.ssl.certificate.key-store-password=mypassword`

But what happened is now I can access the rest endpoint using both **http** as well as **https**

Here is the log trace, which i noticed in while starting the application 

`2020-03-31 15:26:56,628 INFO  [io.quarkus] (main) Quarkus 1.2.1.Final started in 2.735s. Listening on: http://0.0.0.0:8080 and https://0.0.0.0:8443`

**Complete log trace -** 

`Listening for transport dt_socket at address: 5005`
`2020-03-31 15:26:55,328 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.http.insecure-requests" was provided; it will be ignored`
`2020-03-31 15:26:56,628 INFO  [io.quarkus] (main) Quarkus 1.2.1.Final started in 2.735s. Listening on: http://0.0.0.0:8080 and https://0.0.0.0:8443`
`2020-03-31 15:26:56,628 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.`
`2020-03-31 15:26:56,628 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]`
`> Task :quarkusDev`

PS - I have generated the self-signed certificate using - 

`keytool -genkey -keyalg RSA -alias quarkusdemo -keystore keystore.jks -storepass mypassword -validity 365 -keysize 2048`

**Expected behavior**
I was expecting the application should only be accessible via "https e.g. -https://0.0.0.0:8443" since i have disabled the insecure-requests

**Actual behavior**
I can access secured as well as unsecured rest enpoint 

**To Reproduce**
1. Here is my git-repo - https://github.com/rahulwagh/Quarkus.git

**Comment by geoand** [comment]
The `quarkus.http.insecure-requests` option was added in Quarkus `1.3.0.Final` while you are using `1.2.1.Final`.
