### ISSUE TITLE
Property quarkus.banner.path not found

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#8326]
**Describe the bug**

Reading the [Quarkus Configuration](https://quarkus.io/guides/all-config#quarkus-core_quarkus-core) documentation, there is the `quarkus.banner.path` with the following description:

```
The path of the banner (path relative to root of classpath) which could be provided by user | string | default_banner.txt
```

So when I get the configuration property `quarkus.banner.path` I expect the value `default_banner.txt` but I get a `NoSuchElementException: Property quarkus.banner.path not found`

**Expected behavior**

Reading the description of the `quarkus.banner.path`, I expect the property to have the default value `default_banner.txt`. So if I don't explicitelly set it, I expect to have the default value

**Actual behavior**

```
NoSuchElementException: Property quarkus.banner.path not found
```

**To Reproduce**
1. Go to https://code.quarkus.io/
2. Add the code below
3. Execute the endpoint, it crashes with the exception

```
@GET
@Produces(MediaType.TEXT_PLAIN)
public String hello() {
    Config config = ConfigProvider.getConfig();
    return "hello " + config.getValue("quarkus.banner.path", String.class);
}
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin MacBook-Pro-de-Antonio.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3

**Comment by geoand** [comment]
[BannerConfig](https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/banner/BannerConfig.java#L7) is a build-time only property (due to the default of `@ConfigRoot`), meaning that it isn't visible at all at runtime.

See [this](https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/annotations/ConfigPhase.java) for more details on the available config phases.

**Comment by agoncal** [comment]
Thanks.

Why not adding an extra column in the config documentation (https://quarkus.io/guides/all-config#quarkus-core_quarkus-core) adding the config phase ? That would be a precious information.

**Comment by geoand** [comment]
https://quarkus.io/guides/all-config#quarkus-core_quarkus.banner.path has an icon with a tooltip saying that it's fixed at build time.
But I have to admit that isn't the first time I have heard of someone not noticing it :).

@gsmet @maxandersen ^

**Comment by agoncal** [comment]
Oh, the little lock ?! Ok, makes sense. Well, I should have paid more attention to the icon then. Sorry.

Thanks for your help

**Comment by geoand** [comment]
You are welcome :)

**Comment by maxandersen** [comment]
@agoncal so you think the lock is enough ? before we had both a lock (build time) and a gear (runtime) but I suggested we just showed lock so we only put a visual icon for things that has "limitations"....but sounds like you still missed it ;)

**Comment by agoncal** [comment]
@maxandersen well, if I am the only who missed the lock, never mind. But if I'm not the only one, maybe the UI coud be improved. For me, an extra column with this information would have been better (but it's personal taste)
