### ISSUE TITLE
Add extension metadata to all the extensions

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#833]
Following the integration of https://github.com/jbossas/protean-shamrock/pull/663/files#diff-2cfc93ecb828363d0be95549c3abbbfeR31 , we need to add the appropriate metadata to all the existing extensions.

See our `extensions.json` for some label ideas.

**Comment by maxandersen** [comment]
Since GA is now getting closer we should do this.

- add the labels, cateogories, etc. to the `quarkus-extension.properties` 
- extension.json should then be generated from this file.
