### ISSUE TITLE
quarkus:dev don't close DB connections

### ISSUE THREAD

**Issue by sekaijin** [quarkusio/quarkus#8335]
**Describe the bug**
Wthen you run `mvn quarkus:dev`
hit CTRL+C to stop. on windows 10 the process are killed. And the db connections never closes.

**Expected behavior**
clean server shutdown

**Actual behavior**
process killed

**To Reproduce**
1. create project with datasource and select data
2. run mvn quarkus:dev
3. hit Ctrl+C

**Configuration**
```properties
   quarkus:
      datasource:
            driver: oracle.jdbc.driver.OracleDriver
            url: 'jdbc:oracle:thin:@myhost.fr:25284/ASID'
```

**Screenshots**
```
SID|SERIAL#|STATUS  |PROGRAM         |TERMINAL|MACHINE   |MODULE          |
---|-------|--------|----------------|--------|----------|----------------|
149|    376|INACTIVE|JDBC Thin Client|unknown |SAP5223897|JDBC Thin Client|
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10
 - Output of `java -version`:  Java8
 - GraalVM version (if different from Java): none
 - Quarkus version or git rev: 1.3.1-Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3

thank

**Comment by gsmet** [comment]
This is weird. The datasources are supposed to be closed. Do you have a remaining Java process maintaining the connection?

**Comment by sekaijin** [comment]
Nothin else
```java
@ApplicationScoped
public class AlertBean {

   @Inject
   AlertTypeService alertTypeService;

   private int index = 0;

   private int i = 0;

   private Set<AlerteTypeDTO> data;

   @Transactional
   @Scheduled(every = "{alert.schedule}")
   synchronized void schedule() {
      System.err.println("Alert running " + index++);
      this.data = alertTypeService.findAll();
   }

   synchronized public Set<AlerteTypeDTO> getData(){
      System.err.println("SSE => " + this.i++);
      return data;
   }
   
   private static final Logger LOGGER = LoggerFactory.getLogger("ListenerBean");

   void onStart(@Observes StartupEvent ev) {               
       LOGGER.info("The application is starting...");
   }

   void onStop(@Observes ShutdownEvent ev) {               
       LOGGER.info("The application is stopping..."); // <= never call on Ctrl+C when running mvn quakus:dev
   }
   
}
```
And AlertType Entity

**Comment by gsmet** [comment]
@stuartwdouglas looks like this is an unexpected behavior?

**Comment by stuartwdouglas** [comment]
I wonder if this is windows specific, although I don't really see how there could still be a connection after the process has been killed.

I testing this out locally on my mac and onStop is called as normal.

**Comment by sekaijin** [comment]
Yes I only saw the problem on windows.

closing the connection frees the client's resources (java)
but also on the server side.

when the processe is killed without closing the connection, on the client side the memory is emptied so there is no problem.
But the server side resources are still there.
The server maintains information about the client its connection, current transactions etc.
these resources therefore remain until a more or less long timeout.

If we are not careful we end up with the maximum connection reached on the server side when there are no more clients.

This is particularly true with Oracle.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
