### ISSUE TITLE
Unable to listen startup event and to schedule when insecure-requests is disabled (SSL/TLS)

### ISSUE THREAD

**Issue by ddewalle** [quarkusio/quarkus#8336]
**Describe the bug**
When using SSL/TLS with property quarkus.http.insecure-requests = disabled :

- onStart(@Observes StartupEvent evt) is not called
- Method annotated with @Scheduled are not invoked

**To Reproduce**
1. Create a project
```
mvn io.quarkus:quarkus-maven-plugin:1.3.1.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=foo-server -DclassName="org.acme.FooResource" -Dpath="/foo" -Dextensions="scheduler"
```
2. In src/main/java/org/acme add FooService.java
```java
package org.acme;

import io.quarkus.runtime.ShutdownEvent;
import io.quarkus.runtime.StartupEvent;
import io.quarkus.scheduler.Scheduled;
import org.jboss.logging.Logger;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;

@ApplicationScoped
public class FooService {

    private static final Logger LOGGER = Logger.getLogger("FooService");

    public void onStart(@Observes StartupEvent evt) {
        LOGGER.info("The application is starting...");
    }

    public void onStop(@Observes ShutdownEvent evt) {
        LOGGER.info("The application is stopping...");
    }

    @Scheduled(every = "10s")
    public void scheduledTask() {
        LOGGER.info("scheduledTask called");
    }

}
```
3. In src/main/resources , Create a foo.jks file with self-signed certificate
```
keytool -genkey -keyalg RSA -alias selfsigned -keystore foo.jks -storepass fooPass -validity 365 -keysize 2048
```
4. In src/main/resources/application.properties
```properties
quarkus.http.insecure-requests = disabled
quarkus.http.ssl.certificate.key-store-file = foo.jks
quarkus.http.ssl.certificate.key-store-file-type = JKS
quarkus.http.ssl.certificate.key-store-password = fooPass
```

**It is working if (but http stays active)**
In src/main/resources/application.properties
```properties
#quarkus.http.insecure-requests = disabled
quarkus.http.ssl.certificate.key-store-file = foo.jks
quarkus.http.ssl.certificate.key-store-file-type = JKS
quarkus.http.ssl.certificate.key-store-password = fooPass
```

**Environment**
 - Java versions: 11 & 14
 - Quarkus versions: 1.3.0.Final & 1.3.1.Final

**Comment by gsmet** [comment]
This looks very odd to say the least.

@mkouba could you have a look?

**Comment by mkouba** [comment]
I've tried the reproducer locally and it seems that the HTTP server is stuck if `quarkus.http.insecure-requests=disabled` is used. We'll need to investigate this further.

**Comment by mkouba** [comment]
@gsmet So it seems that `quarkus.http.insecure-requests=disabled` actually never worked. I've sent a PR with a minimal fix. @ddewalle it would be great if you could test the PR.

**Comment by ddewalle** [comment]
> @gsmet So it seems that `quarkus.http.insecure-requests=disabled` actually never worked. I've sent a PR with a minimal fix. @ddewalle it would be great if you could test the PR.

I tested the PR, merging the modifications of VertxHttpRecorder.java in top of extensions/vertx-http/runtime with latest Quarkus 1.3.1.Final tag.
I only rebuilt quarkus-vertx-http-1.3.1.Final.jar locally and executed the bug reproducer (with Java 11) -> the bug seems to be fixed and the Quatkus Ascii logo is back too ;-)

I also tested the fix on a real project with multi quarkus servers communicating with each others (non-native mode) with Quarkus 1.3.1.Final and Java 14 and the bug seems to be fixed too.
Well done :-)

**Comment by mkouba** [comment]
@ddewalle Thanks for confirming!
