### ISSUE TITLE
Injection on @QuarkusTest too late for @ExtendWith

### ISSUE THREAD

**Issue by Xanas80** [quarkusio/quarkus#8344]
**Describe the bug**
Since version 1.3.0.Final for example injected UserTransaction on @QuarkusTest ist too late if we use @ExtendWith. All @Inject fields on the test class are null on BeforeEachCallback.

**Expected behavior**
We expect the fields to be injected before BeforeEachCallback, as they were until Quarkus version 1.2.1.Final.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
1. Create a @QuarkusTest and an @ExtendWith BeforeEachCallback and @Inject an UserTransaction
2. In BeforeEachCallback  get class instance context.getTestInstance()
  - get UserTransaction
3. UserTransaction ist null

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: Java version: 11.0.3
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.0.Final, 1.3.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Java version: 11.0.3, vendor: Amazon.com Inc., runtime: C:\Program Files\Amazon Corretto\jdk11.0.3_7
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
@loicmathieu IIRC you had some experience with `@ExtendWith`. Does this ring a bell?

**Comment by loicmathieu** [comment]
If it works before 1.3 it should be something related to the new classloader implementation, maybe @stuartwdouglas have an idea.

And also, `@ExtendWith` didn't play well with Quarkus, see #7199 so @Xanas80 can you provides more details onto how to reproduce this issue? 

@Xanas80 if you use `@ExtendWith` to load a custom JUnit extension, you need to use it also for the Quarkus JUnit extension via `@ExtendWith(QuarkusTestExtension.class)` or you will have no way to force the Quarkus extension to execute before your extension. Mixing `@ExtendWith` and `@QuarkusTest` is not a correct way to integrate multiple JUnit extensions. And as I said, there is issue with using `@ExtendWith(QuarkusTestExtension.class)` ...

**Comment by Xanas80** [comment]
@loicmathieu Yes, this is simple the execution order. 

I tried the workaround with the CDI Scope, but that did not work either. as seen at #7199 
@Singleton
@ExtendWith(QuarkusTestExtension.class)
@ExtendWith(MyExtension.class)

**Comment by loicmathieu** [comment]
So can we close this issue ?
You can comment or subscribe on #7199 if needed as it's the same issue

**Comment by Xanas80** [comment]
yes
