### ISSUE TITLE
Move OidcTenantConfig out of the runtime package

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#8347]
**Description**
Right now `OidcTenantConfig` is in the runtime package: `io.quarkus.oidc.runtime` but since it is now visible to `io.quarkus.oidc.TenantConfigResolver` it could be a bit better to move `OidcTenantConfig` out of `runtime` as it is really part of the API now, and we'll offer a builder support around it too.

**Implementation ideas**
Move `OidcTenantConfig` to `io.quarkus.oidc`

The only concern is that I know at least a single user who was looking at it. It is still the relatively early days though for the multi-tenancy and `TenantConfigResolver` in particular, so I reckon we should do it for `1.4.0` before it will become used a lot

**Comment by sberyozkin** [comment]
@pedroigor @stuartwdouglas - if you have concerns about it please let me know.

**Comment by gsmet** [comment]
Hum. I have some serious concerns about making some config class part of the API.

I'm not sure how the user is supposed to implement this?

**Comment by sberyozkin** [comment]
@gsmet Hi, it is not an interface, yes. it is what the custom implementations of this [interface](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/TenantConfigResolver.java) have to provide and as such it feels it belongs in [this package](https://github.com/quarkusio/quarkus/tree/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc) where not all the classes are the interfaces.
So my `API` I meant the classes outside of the `runtime` package.

**Comment by sberyozkin** [comment]
It probably does not matter much, but I recall I was thinking about the other day so decided to open an issue

**Comment by sberyozkin** [comment]
@gsmet, FYI, @pedroigor has also suggested a builder support around this class but for now we just keep adding setters/getters to make it easy for the users to init it

**Comment by sberyozkin** [comment]
Hi @pedroigor @stuartwdouglas Do you have any preferences ? I can do a quick PR if you are fine with it, before 1.4.0.Final is out

**Comment by stuartwdouglas** [comment]
We probably should do this, even though it feels a bit wrong to have config as part of the API in this caae it makes sense, as otherwise we would just have to copy the config class and then copy between them, which is not a route we want to go down.

It should definitely go in before 1.4 if we are going to do this though.

**Comment by sberyozkin** [comment]
@stuartwdouglas Sure, yeah. Pedro had an idea of doing a builder too, so we can make more than a config :-). It can be also very dynamic with `TenantConfigResolver`
