### ISSUE TITLE
Kogito Bug when using Declared Types

### ISSUE THREAD

**Issue by carlosthe19916** [quarkusio/quarkus#8358]
I've been trying to use Kogito and Quarkus but I ended up not being able to use all the features that Drools gives. I'm not sure where to raise this bug so I'll start reporting it here:

If I declare a type inside a `.drl` file the I have an exception: `/classes/META-INF/native-image/org/acme/kogito/reflect-config/json.java (11:1) : class, interface, or enum expected`.

To reproduce the error you only need to add a declared type inside a `.drl` file like this example: https://github.com/carlosthe19916/quarkus-quickstarts/blob/patch-1/kogito-quickstart/src/main/resources/org/acme/kogito/person-rules.drl#L6

Is this a problem that can be solved by adding some configuration or is it a bug?

**Comment by carlosthe19916** [comment]
@gsmet @mariofusco This question has been answered in https://github.com/kiegroup/kogito-examples/issues/145. Sorry for having duplicated the issues.

**Comment by geoand** [comment]
So should this be closed if it's being tracked in kogito?

**Comment by mariofusco** [comment]
@geoand yes you can close this, thank you.

**Comment by geoand** [comment]
Thanks @mariofusco
