### ISSUE TITLE
no license information in quarkus security pom

### ISSUE THREAD

**Issue by alexander-dammeier** [quarkusio/quarkus#8364]
Hello,

i built our quarkus application with our internal Ci/CD system and it gave me an alert that the artefact `io.quarkus.security:quarkus-security` has no license information. We are using Quarkus 1.3.1 but i wonder that the version of the artefact is 1.0.1.final.
`mvn dependency:tree` says:
```
[INFO] +- io.quarkus:quarkus-resteasy:jar:1.3.1.Final:compile
[INFO] |  +- io.quarkus:quarkus-vertx-http:jar:1.3.1.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:1.3.1.Final:compile
[INFO] |  |  +- io.quarkus.security:quarkus-security:jar:1.0.1.Final:compile
```

Can you please add license information to your pom.xml for this artefact?

**Comment by sberyozkin** [comment]
CC @stuartwdouglas

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus-security/pull/7 .

**Comment by gsmet** [comment]
Reopening this one as we need a release of Quarkus security.
