### ISSUE TITLE
Should be ManagedExecutor in the Reactive Messaging Doc

### ISSUE THREAD

**Issue by murphye** [quarkusio/quarkus#8371]
There is an error on the doc here:
https://quarkus.io/guides/reactive-messaging#implementing-fire-and-forget-interactions

Not correct:
`@Inject Executor executor;`

Correct:
`@Inject ManagedExecutor executor;`

**Comment by murphye** [comment]
Opening issue for website.

**Comment by gsmet** [comment]
Reopening as the doc are maintained here.

@cescoffier @FroMage could you check and fix if needed?

**Comment by FroMage** [comment]
Mmm, I wonder if it's required. `ManagedExecutor` is an `Executor`, so it would work unless there are other `Executor` beans, and I'm not sure there are in Quarkus. I'd have to actually try this code out to know.

**Comment by FroMage** [comment]
@cescoffier I assume you did try that example code?

**Comment by gsmet** [comment]
Well, if it doesn't hurt, I would be in favor of using `ManagedExecutor`.

Having some other `Executor` bean could be quite frequent.

**Comment by loicmathieu** [comment]
If it's still needed, I can take care of this one.

**Comment by cescoffier** [comment]
I just opened a PR.
