### ISSUE TITLE
(Outdated) Wiremock should not be defined in BOM?

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#8378]
**Describe the bug**
A fellow developer has just introduced Wiremock in our current project and I was surprised that he did not have to define a version for it. I then discovered that suddenly Junit4 popped up on the test classpath (Eclipse asked me to choose between two `@Test` annotations).
This is when I stumbled upon https://github.com/tomakehurst/wiremock/issues/684#issuecomment-600127042:

> the JUnit 4 dependency is already optional

which is not (yet) true for 2.24.1 that is defined in the Quarkus BOM. The dependency was removed in 2.25.0, latest version is 2.26.3.

To make a long story short: Why does the "user-facing" BOM bring in Wiremock anyway?

**Expected behavior**
_No_ Wiremock in the Quarkus BOM _at all_ or at least a recent version that does not pull in Junit4.

**Actual behavior**
Outdated Wiremock with JUnit4 dependency is present in BOM.

**To Reproduce**
1. Just look at the BOM 😉 and the Dependencies: https://mvnrepository.com/artifact/com.github.tomakehurst/wiremock-jre8/2.24.1

**Configuration**
n/a

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.3.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Additional context**
Wiremock was introduced here, but just in a test of an extension: https://github.com/quarkusio/quarkus/commit/b958ca1022b64c2698701706312230df7749a779

**Comment by geoand** [comment]
Yeah, I think it should be removed.

**Comment by famod** [comment]
@geoand 

The follwing two tests use WireMock:
- `quarkus\extensions\spring-cloud-config-client\runtime\src\test\java\io\quarkus\spring\cloud\config\client\runtime\SpringCloudConfigClientGatewayTest.java`
- `quarkus\integration-tests\elytron-security-oauth2\src\test\java\io\quarkus\it\elytron\oauth2\ElytronOauth2ExtensionResourceTestCase.java`

So the fix would be to move the WireMock dependency to `spring-cloud-config-client\runtime` and `integration-tests\elytron-security-oauth2` individually?

**Comment by geoand** [comment]
Yeah, I don't see why not
