### ISSUE TITLE
Hyperlink Rest Resources on 404 page

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#8392]
**Description**
When an application attempts to access an invalid REST endpoint, Quarkus will provide a 404 page with a list of valid endpoints. There are some additional developer joy opportunities here:

1. Make non-parameterized resource access a hyperlink to application endpoint on 404 pages. Seems like low-hanging fruit with a nice upside.
2. Optional: Make resource parameters editable in 404 page. This is a nice-to-have feature and is not intended to be feature rich and replace swagger UI. Alternatively, if swagger extension is loaded, provide hyperlink to swagger endpoint.
<img width="688" alt="Browser_Preview__404_-_Resource_Not_Found__—_mp-spring" src="https://user-images.githubusercontent.com/73075/78461489-34157600-767e-11ea-8e14-cf3fd9942da8.png">

**Comment by geoand** [comment]
@ia3andy would you like to take a stab at this one?

**Comment by ia3andy** [comment]
I need to get to it, it's still in my TODO list, let me know it that becomes urgent..

**Comment by jclingan** [comment]
Not urgent. A  nice-to-have developer joy feature.

**Comment by ia3andy** [comment]
I removed myself as assigned, it's still in my TODO, but if someone want to take it I would be happy :)

**Comment by geoand** [comment]
@phillip-kruger I wonder if we were planning on tackling this as well

**Comment by phillip-kruger** [comment]
This gets a bit into what the swagger UI is for... But making the GET without parameters a link should be easy enough

**Comment by geoand** [comment]
Maybe we can link to the Swagger UI it it exists?

**Comment by phillip-kruger** [comment]
Yea, if swagger UI is included, the link to it should be in the list of links, with all the other /q links

**Comment by geoand** [comment]
👍🏼 

Maybe it can be highlighted somehow so it doesn't get lost in the list of all the other links?

**Comment by phillip-kruger** [comment]
I actually did make the GET a link, but then I revert it to not make my PR too big. I also had some new styling that looks more like the welcome screen, but I also reverted that, that needs a discussion first :)

**Comment by geoand** [comment]
Sounds good
