### ISSUE TITLE
quarkus-container-image-jib: add support for labels

### ISSUE THREAD

**Issue by fredmtyro** [quarkusio/quarkus#8406]
**Description**
Support adding labels to the image produced by quarks-container-image-jib.

**Implementation ideas**
The feature seems to already exist in jib itself (see [jib docs](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage))

**Comment by geoand** [comment]
Good idea. I'll get it done for `1.4`.
