### ISSUE TITLE
Quarkus OIDC with cookie-path does not remove cookie

### ISSUE THREAD

**Issue by lodrantl** [quarkusio/quarkus#8417]
**Describe the bug**
When using Quarkus OIDC with type web-app and a cookie-path set, the whole authentication process only works the first time. When the tokens expire, a new challenge is sent out but the old session cookie is never removed. The call to remove cookie at https://github.com/quarkusio/quarkus/blob/7e969004866b195a4ee20b5e16ff005b9e3c4d84/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L283

will not work because the initial cookie was set with a cookiepath, which means it can only be expired using the same cookiepath. 

**Expected behavior**
1. user logs in
2. tokens expire
3. new challenge is sent, old session cookie is removed, redirect to OIDC provider
4. redirect back to app, new session cookie is created

**Actual behavior**
1. user logs in
2. tokens expire
3. new challenge is sent, old session cookie is not removed, redirect to OIDC provider
4. redirect back to app, new challenge is sent, old session cookie is not removed, redirect to OIDC provider
5. infinite loop

**Configuration**
```properties
quarkus.oidc.authentication.cookie-path=/api
quarkus.oidc.application-type=web-app
```
**Environment (please complete the following information):**
 - Quarkus version or git rev: 91248634585a3b75ccfc8addf49902bd04b973cd

**Comment by sberyozkin** [comment]
@lodrantl Thanks for spotting it, please check #8424

**Comment by lodrantl** [comment]
Looks good to me if that is how vertx does it. Although it seems pretty redundant to send the token value back in the expired cookie. When debugging the network requests it is not immediately obvious that the cookie is meant to be removed.

**Comment by sberyozkin** [comment]
yes I have seen that an empty value/etc is set, but if the browsers work as expected then it is not too bad
