### ISSUE TITLE
Update Netty library to `4.1.46.Final` or higher to improve GraalVM support

### ISSUE THREAD

**Issue by provcristianmaluenda** [quarkusio/quarkus#8427]
**Description**
Netty has an issue with GraalVM. 
The explanation from micronaut [ticket](https://github.com/micronaut-projects/micronaut-core/issues/2335#issuecomment-570151944) (Sorry, I know is the competition):
>io.netty.util.concurrent.ScheduledFutureTask contains a memoized static value from System.nanoTime() that all task timers are normalized to (see ScheduledFutureTask.java#L28).

>Because Netty is defaulting to initialize-at-build-time, this value is computed when the native image is created, but System.nanoTime() can return an arbitrary value not one that is consistent across environments. If the value memoized in native-image is higher than the one returned by System.nanoTime() at runtime then the computed deltas go negative and get clamped to 0 causing the immediate timeout.

>On a local environment the values are consistent, which explains why local testing works fine, whereas the opposite is true for Lambda where the runtime is fresh on every function update, so Lambda would be more susceptible to the problem even though there doesn't appear to be anything Lambda specific to it.

[Netty ticker 9928](netty/netty/issues/9928)

**Implementation ideas**
Update the Netty dependency to `4.1.46.Final` or higher.

**Comment by gsmet** [comment]
We shouldn't be affected by this issue: we initialize it at runtime exactly for that reason.

**Comment by provcristianmaluenda** [comment]
Thanks!
