### ISSUE TITLE
Improved production mode ClassLoader

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#8439]
We should use a faster ClassLoader for production mode, and pre-index the lib directory so lookups are O(1) instead of O(n) on the number of classes.

**Comment by geoand** [comment]
Is the idea to generate some kind of tree like index of packages to jars, inside a generated classloader?

**Comment by nimo23** [comment]
>pre-index the lib directory 

So the lib-directoy will be pre-indexed on compile. Then I am wondering wheter it can 
also benefit from creating (or bypassing the need) for a (detailed) jandex index in quarkus? It sounds like the jandex and this classpath index can be substituted or if not then at least benefit from each other..
