### ISSUE TITLE
A multi-stage Docker build, error COPY --from=build /usr/src/app/target/*-runner /work/application 

### ISSUE THREAD

**Issue by ieozt38** [quarkusio/quarkus#8450]
**Describe the bug**
When I try to make a multi-stage Docker build, on stage 2 i get an exception:

DockerFile.multistage
COPY --from=build /usr/src/app/target/*-runner /work/application
-> COPY failed: no source files were specified

**Expected behavior**
build succeeded
**Actual behavior**
COPY failed: no source files were specified

**To Reproduce**
1. build docker

**Configuration**
```properties
## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/centos-quarkus-maven:19.2.1 AS build
WORKDIR /usr/src/app
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
USER root
RUN chown -R quarkus /usr/src/app
USER quarkus


COPY settings.xml /home/quarkus/.m2
COPY settings-security.xml /home/quarkus/.m2

RUN mvn -f /usr/src/app/pom.xml -Pnative clean package

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=build /usr/src/app/target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]

```

**Comment by geoand** [comment]
I am assuming you tried to follow: https://quarkus.io/guides/building-native-image#creating-a-container-with-a-multi-stage-docker-build

If so, have you followed this:

```
Before launching our Docker build, we need to update the default .dockerignore file as it filters everything except the target directory and as we plan to build inside a container we need to be able to copy the src directory. So edit your .dockerignore and remove or comment its content.
```

?

**Comment by ieozt38** [comment]
> I am assuming you tried to follow: https://quarkus.io/guides/building-native-image#creating-a-container-with-a-multi-stage-docker-build
> 
> If so, have you followed this:
> 
> ```
> Before launching our Docker build, we need to update the default .dockerignore file as it filters everything except the target directory and as we plan to build inside a container we need to be able to copy the src directory. So edit your .dockerignore and remove or comment its content.
> ```
> 
> ?

Yes i did

**Comment by geoand** [comment]
I tried the process and it works. 

Can you perhaps upload a reproducer which demonstrates the failure?

**Comment by ieozt38** [comment]
Sure 

> I tried the process and it works.
> 
> Can you perhaps upload a reproducer which demonstrates the failure?

Sure: https://gyazo.com/c410aac0e9c45d9ca37e406bbb4c884c
I Use Java11, Windows10, Docker Desktop installation. 
Quarkus 1.3.0 final

**Comment by geoand** [comment]
Thanks.

I am not on Windows so I can't really test that setup. Hopefully someone else will be able to.

**Comment by ieozt38** [comment]
> Thanks.
> 
> I am not on Windows so I can't really test that setup. Hopefully someone else will be able to.

It happens also on Mac

**Comment by geoand** [comment]
I'm not on Mac either :P

**Comment by ieozt38** [comment]
haha okay thanks btw :)

**Comment by flyingkaktus** [comment]
same problem here on linux with quarkus native docker build with default .native, *-runner exisit, but it throws this error as above
