### ISSUE TITLE
@QuarkusTest classloader problems when executing XPathFactory.newInstance()

### ISSUE THREAD

**Issue by diogocarleto** [quarkusio/quarkus#8451]
Hi guys, I've faced an issue when parsing a .xlsx file in my JUnit tests.

The problem is that an internal lib tries to call the following code:

`XPathFactory.newInstance()`

Suppose we have the followings scenarios:

<pre>
@org.junit.Test
    public void testXpathFactory() {
        XPathFactory xPathFactory = XPathFactory.newInstance();
        assertNotNull(xPathFactory);
    }
</pre>

<pre>
@Test //@org.junit.jupiter.api.Test
    public void testXpathFactory() {
        XPathFactory xPathFactory = XPathFactory.newInstance();
        assertNotNull(xPathFactory);
    }
</pre>

The first one executes ok, the last one throws the error:

`java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: No XPathFctory implementation found for the object model: http://java.sun.com/jaxp/xpath/dom
`

Both scenarios are in a class annotated with the `@QuarkusTest`

Any ideas on how I can solve this?

Best.

**Comment by geoand** [comment]
I wasn't able to reproduce this in a simple test.

Perhaps you could provide a small reproducer?

**Comment by diogocarleto** [comment]
Hi @geoand, I've started a new project and wasn't able to reproduce also. I'm adding my libs one by one to check which one brings this problem. 

I'll let you know when done.

Thanks.

**Comment by diogocarleto** [comment]
@geoand the problem happens when I add this dependency:

<dependency>
      <groupId>com.monitorjbl</groupId>
      <artifactId>xlsx-streamer</artifactId>
      <version>2.1.0</version>
    </dependency>

I'm checking here why.

**Comment by diogocarleto** [comment]
@geoand you can close this one. I've found the problem.

```
<dependency>
      <groupId>com.monitorjbl</groupId>
      <artifactId>xlsx-streamer</artifactId>
      <version>2.1.0</version>
      <exclusions>
        <exclusion>
          <groupId>com.rackspace.apache</groupId>
          <artifactId>xerces2-xsd11</artifactId>
        </exclusion>
        <exclusion>
          <groupId>xml-apis</groupId>
          <artifactId>xml-apis</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

Thank you so much.

**Comment by geoand** [comment]
Great! Thanks for looking into it

**Comment by diogocarleto** [comment]
@geoand I think I said you to close so earlier :)

```
See what I'm getting now after this exclusion when trying to parse my .xlsx file, 
java.lang.LinkageError: loader constraint violation: when resolving field "NODESET" of type javax.xml.namespace.QName, the class loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @34d11c92 (instance of io.quarkus.bootstrap.classloading.QuarkusClassLoader, child of 'bootstrap') of the current class, com.monitorjbl.xlsx.XmlUtils, and the class loader 'bootstrap' for the field's defining type, javax.xml.xpath.XPathConstants, have different Class objects for type javax.xml.namespace.QName

```

**Comment by geoand** [comment]
Reopening then 😎

**Comment by jzampieron** [comment]
There are also similar problems with `XPathFactory.newDefaultInstance()` in certain build/run scenarios. 

We get no-such-method errors in certain builds (e.g. w/ Xerces present) for the above method.

When packaging the apps to a fast-jar it appears as if the Quarkus Classloader will not always load from the "default" JRE library set.

This is pretty clearly a bug in either the Quarkus build tooling and/or the Quarkus Classloader.

Libraries available in the system JRE should, by definition, never throw a ClassNotFound or NoSuchMethod error... if they do, that ClassLoader is either "special" and shouldn't happen without explicit request and/or broken.

Now interactions and behavior in native builds probably need very explicit definition in these cases.

**Comment by dmlloyd** [comment]
There is a chance that this is related to #40601. Linking it to double-check later.

**Comment by jzampieron** [comment]
We are in the process of upgrading from 3.2 LTS to 3.8 LTS and then 3.12/3.13 LTS (whatever is the next LTS). 

Will update if we see the issue in a newer version.

**Comment by geoand** [comment]
Thanks!
