### ISSUE TITLE
OIDC parameters required in application.properties even when using custom TenantConfigResolver

### ISSUE THREAD

**Issue by TheGeekPharaoh** [quarkusio/quarkus#8460]
**Describe the bug**
Error message displayed saying 

> auth-server-url and client-id must be configured when the quarkus-oidc extension is enabled

 even when using a custom `TenantConfigResolver`

**Expected behavior**
The custom `TenantConfigResolver` should be the source for OIDC configuration rather than `application.properties`.  I should be able to skip all `quarkus.oidc.*` parameters in `application.properties` and get those values from my `TenantConfigResolver` instead.

**Actual behavior**
The `TenantConfigResolver` works as expected but *something* must be configured for `auth-server-url` and `client-id` or the application will fail to start

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin A81621 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64
 - Output of `java -version`:  openjdk version "13.0.1" 2019-10-15
- Quarkus version 1.3.1

**Comment by sberyozkin** [comment]
@TheGeekPharaoh I'm not sure it is a bug - `TenantConfigResolver` is expected to return `OidcTenantConfig` with its own `auth-server-url` and `client-id`. Does your implementation set those properties ?
If you don't need to configure a default tenant (the usual application.properties) then you can add `quarkus.oidc.tenant-enabled = false`

**Comment by sberyozkin** [comment]
@TheGeekPharaoh FYI, the reason the default tenant is not disabled by default when `TenantConfigResolver` is available is because `quarkus-oidc` needs to fallback to it if `TenantConfigResolver` chooses to return `null` `OidcTenantConfig` for a current request.

**Comment by TheGeekPharaoh** [comment]
Thanks for the explanation.  Looks like it’s not a big, then.  I’ll close the issue.  
    On Wednesday, April 8, 2020, 07:51:37 AM EDT, sberyozkin <notifications@github.com> wrote:  
 
 


@TheGeekPharaoh FYI, the reason the default tenant is not disabled by default when TenantConfigResolver is available is because quarkus-oidc needs to fallback to it if TenantConfigResolver chooses to return null OidcTenantConfig for a current request.
