### ISSUE TITLE
OpenTracing Version Upgrade from 0.31.0 -> 0.33.0

### ISSUE THREAD

**Issue by DeepakkumarArumugam** [quarkusio/quarkus#8461]
Team,
Please update opentracing version to 0.33.0. opentracing-util:0.33.0 exposed new methods to atomically update Global Tracer.
Thanks.

**Comment by geoand** [comment]
cc @pavolloffay

**Comment by pavolloffay** [comment]
This has to wait until MicroProfile-OpenTracing 2.0 is out in the MP summer release.

**Comment by rquinio** [comment]
It depends on smallrye https://github.com/smallrye/smallrye-opentracing/issues/85

**Comment by pavolloffay** [comment]
The MP 2.0-RC2 has been released and SmallRye-OpenTracing has been updated. Does Quarkus use MicroProfile RC releases? If so then we can update otherwise we will have to wait for https://github.com/eclipse/microprofile/issues/169

**Comment by geoand** [comment]
@kenfinnigan ^

**Comment by kenfinnigan** [comment]
We don't use RC releases, we need Finals just because of the fast release schedule

**Comment by dufoli** [comment]
here we have a patch on qxf extension for switch to 0.33
https://github.com/quarkiverse/quarkus-cxf/pull/164
I think that best is that quarkus is updated instead of cxf extension.

**Comment by ntrp** [comment]
I guess we are still far away from getting opentracing 0.33 in quarkus?

**Comment by kenfinnigan** [comment]
This is present in `main` and will be released as part of the 2.x stream
