### ISSUE TITLE
documentation for Keycloak authorization is insufficient

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#8469]
**Describe the bug**
I've spent some time investigating usage of the `quarkus-keycloak-authorization` extension in the OpenShift context and found a few insufficiencies in the documentation. Specifically:

- [ ] 1. In OpenShift, the `/health` endpoint (and possibly also `/metrics`) must always be accessible. However, if I use `quarkus-keycloak-authorization`, it takes over the entire URL space, OpenShift can't reach the health endpoint and the application is never ready. (Yes, I always include health checks. If I omitted them, this wouldn't be a problem, but that's always a bad idea.) This behavior is probably correct from Keycloak perspective, but it took me a long time to figure out how to make my application work.

    I first tried to configure the Keycloak realm to let anyone and everyone access `/health/*`. But I wasn't able to figure out the correct Keycloak configuration. I'm certainly no Keycloak expert, for sure. Then, I spent some time in the debugger and in the end, I have found some undocumented configuration options that let me disable authz for the `/health` endpoint:

    ```properties
    quarkus.keycloak.policy-enforcer.enable=true
    quarkus.keycloak.policy-enforcer.paths.health.path=/health/*
    quarkus.keycloak.policy-enforcer.paths.health.enforcement-mode=DISABLED
    ```

    There should be a reference for all these additional options (unless they are not documented because the config shape is experimental and will change in the future, in which case I'd suggest something needs to be stabilized at least for the health check usecase). I'd also say there should be an example -- ideally with this exact usecase.

- [ ] 2. The documentation also says (https://quarkus.io/guides/security-keycloak-authorization#mapping-protected-resources) that `quarkus.keycloak.policy-enforcer.lazy-load-paths` defaults to `false`, which wrong. It clearly defaults to `true`: https://github.com/quarkusio/quarkus/blob/73fc9276ae/extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java#L67-L68 That documentation section should be rewritten.

- [x] 3. In OpenShift, it is rather easy for a small clock skew to happen between the Keycloak server and the Quarkus application. In my case, I've seen Keycloak being cca 10 seconds _ahead_ of the Quarkus app. In such case, I had weird 403 errors, because the token _wasn't yet valid_. It is possible to setup some leeway using `quarkus.oidc.token.expiration-grace`, but the documentation isn't really clear in this regard. It sounds like it only affects token expiration check, but it also affects token issue time check. This should be at least clearly mentioned in https://quarkus.io/guides/security-openid-connect#quarkus-oidc_quarkus.oidc.token.expiration-grace, but if the property had a more accurate name, that would be better.

**Comment by Ladicek** [comment]
CC @sberyozkin @pedroigor

**Comment by sberyozkin** [comment]
Hi @Ladicek Thanks for the above, re 3., I did see `leeway` was being used in `Vertx` but since at a time I was dealing with the user request to do with the the expiration grace I called it as such :-).
I think to address `3` properly we'd also need to introduce `not-before` check which is also done by Vertx during the token verification

**Comment by Ladicek** [comment]
I'm also thinking if perhaps the default leeway should be > 0, WDYT? I'm no security expert, but clock skew of about 10 seconds is not unheard of, I'd say.

**Comment by pedroigor** [comment]
@Ladicek Regarding documentation, you are right. However, the reason why we don't have more references in `quarkus-keycloak-authorization` extension is that I did not want to replicate what we have in the Keycloak Authorization Services [documentation](https://www.keycloak.org/docs/latest/authorization_services/index.html#_enforcer_filter).

The extension is basically exposing the Keycloak Policy Enforcer to Quarkus application. All configuration you can do there you can have in Quarkus. Yeah, we are talking about properties vs json, so for certain configuration options (like the path config) is not so obvious how to map them to Quarkus.

That said, I'm not sure about replicating all the config there into Quarkus docs. But maybe we can describe better some very common usages and use cases like this one for disabling policy enforcement for a specific path?

Regarding the clock skew, we have that for SAML but not for OIDC. Not sure why, we should probably include that.

**Comment by Ladicek** [comment]
@pedroigor I'd say "is not so obvious" is an understatement. One, I had no clue this mirrors some Keycloak configuration that I could look at. Two, I had to step through the `quarkus-keycloak-authorization` extension code _in a debugger (!)_ to find these configuration options and how to use them.

Given that Quarkus has (wants to have) a monopoly on configuration, the properties must be documented. The autogenerated documentation should cost you nothing. Adding an example or two would be good for sure.

**Comment by pedroigor** [comment]
@Ladicek You are right. We can definitely include the config options as we have for other extensions.

I'm going to update docs to make more clear the extension is related to Keycloak Policy Enforcer as well as add the config options.

**Comment by Ladicek** [comment]
Thank you!

**Comment by pedroigor** [comment]
Humm.. Let me fix those ..

**Comment by pedroigor** [comment]
@Ladicek Could you check https://github.com/quarkusio/quarkus/pull/9972? Anything else?

**Comment by Ladicek** [comment]
Thanks @pedroigor, no, that should be all :-)
