### ISSUE TITLE
`QuarkusMock` makes it hard to access mock objects

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#8472]
The docs tell me to do mocking this way:

```java
    @Inject
    MockableBean1 mockableBean1;

    @Inject
    MockableBean2 mockableBean2;

    @BeforeAll
    public static void setup() {
        MockableBean1 mock = Mockito.mock(MockableBean1.class);
        Mockito.when(mock.greet("Stuart")).thenReturn("A mock for Stuart");
        QuarkusMock.installMockForType(mock, MockableBean1.class);  <1>
    }

    @Test
    public void testBeforeAll() {
        Assertions.assertEquals("A mock for Stuart", mockableBean1.greet("Stuart"));
        Assertions.assertEquals("Hello Stuart", mockableBean2.greet("Stuart"));
    }
```

But then in `testBeforeAll()` I can't easily call `verify` methods such as: 

```java
Mockito.verify(mockOfMockableBean1).greet("Stuart");
Mockito.verifyNoMoreInteractions(mockOfMockableBean1);
```

Either I need to hang on to the mock instances from the `setup` to the tests, or I need to be able to access the mock instances from the mocked beans. In `panache-mock` I've added helpers that you can call instead of calling them on `Mockito`. So we could do:

```java
    @Inject
    MockableBean1 mockableBean1;

    @Inject
    MockableBean2 mockableBean2;

    @BeforeAll
    public static void setup() {
        MockableBean1 mock = Mockito.mock(MockableBean1.class);
        Mockito.when(mock.greet("Stuart")).thenReturn("A mock for Stuart");
        QuarkusMock.installMockForType(mock, MockableBean1.class);  <1>
    }

    @Test
    public void testBeforeAll() {
        Assertions.assertEquals("A mock for Stuart", mockableBean1.greet("Stuart"));
        Assertions.assertEquals("Hello Stuart", mockableBean2.greet("Stuart"));
        // Call QuarkusMock instead of Mockito
        QuarkusMock.verify(mockOfMockableBean1).greet("Stuart");
        QuarkusMock.verifyNoMoreInteractions(mockOfMockableBean1);
```

And `QuarkusMock.verify*` can implement it by adding a `MockableProxy.quarkus$$getMock()` method to unwrap the mock object from the proxy.

It's a pity there's no `MockWrapper` interface in Mockito which we could implement to get this automatically working. We could make a PR there.

WDYT @stuartwdouglas ?

**Comment by stuartwdouglas** [comment]
Does @InjectMock solve all these problems? Maybe we should just update all the docs to use it if so?

**Comment by geoand** [comment]
`@InjectMock` does indeed solve the problem that @FroMage is referring to.

**Comment by geoand** [comment]
Let's close this as `@InjectMock` is the proposed solution
