### ISSUE TITLE
Trailing slash required with Undertow + custom root path

### ISSUE THREAD

**Issue by dteleguin** [quarkusio/quarkus#8475]
**Describe the bug**
When using `quarkus-undertow` in combination with custom root path, a trailing slash has to be appended to the app path. This is not required when using vert.x. Additionally, Java™ Servlet Specification assumes that the slash shouldn't be required:

> A `ServletContext` is rooted at a known path within a Web server. For example, a
servlet context could be located at `http://www.mycorp.com/catalog`. All requests
that begin with the `/catalog` request path, known as the *context path*, are routed to
the Web application associated with the `ServletContext`.

**Expected behavior**
GET http://localhost:8080/foo => 200 OK (Welcome page or root resource)
GET http://localhost:8080/foo/ => 200 OK (ditto)

**Actual behavior**
GET http://localhost:8080/foo => 404 Not Found + "Resource not found" page
GET http://localhost:8080/foo/ => 200 OK

**Configuration**
```properties
quarkus.servlet.context-path = /foo
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.3.1.Final

**Comment by sberyozkin** [comment]
Hi Stuart @stuartwdouglas is it somewhere in Quarkus or in Undertow itself where it is handled ?
