### ISSUE TITLE
Instance of class Instant creation error - Serialization

### ISSUE THREAD

**Issue by EfraimLA** [quarkusio/quarkus#8485]
**Describe the bug**
I've an Panache Entity and i'm trying to test a REST Endpoint which produces and consumes only `application/json` but cannot serialize and deserialize my entity object to persist it

**Expected behavior**
POST an entity as JSON and get entity saved

**Actual behavior**
When i send my entity got a status code 400 cause when i'm trying to serialize/deserialize i got this:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
Cannot construct instance of `java.time.Instant` (no Creators, like default construct, exist): no String-argument constructor/factory method to deserialize from String value ('2020-04-08T23:16:11.633278Z')
```

**To Reproduce**
1. Initialize docker containers extension
2. Create Entity Object and put some attributes/properties
3. POST entity as JSON and get saved

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10 Pro v,1909 (OS Build 18363.752)
 - Output of `java -version`: OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
 - GraalVM version (if different from Java): 20.0.0
 - Quarkus version or git rev: 1.3.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by loicmathieu** [comment]
Can you give us the list of extensions you are using ?
Is the issue on jvm mode or when running a native executable ?

**Comment by stuartwdouglas** [comment]
This definitely works, I just tested it and support was added in https://github.com/quarkusio/quarkus/commit/732217639e9f8926373ded2667bcbe774f490b59
