### ISSUE TITLE
Changes to superclass are not transacted

### ISSUE THREAD

**Issue by vc-void** [quarkusio/quarkus#8504]
**Describe the bug**
Class A has protected field X. Class B extends A. If during a method annotated with @Transactional an instance of class B edits field X directly, changes to field X wont be transacted.

**Expected behavior**
Changes to field X should be transacted

**Actual behavior**
Changes to field X aren't reflected in the DB

**To Reproduce**
The test project below is using quarkus 1.3.2.Final and hibernate ORM. It has two endpoints, one for creating "TestEntity"s (Class B), and another to edit.
[https://bitbucket.org/victorhbdc/quarkussuperclasstx/src/master/](https://bitbucket.org/victorhbdc/quarkussuperclasstx/src/master/)

**Comment by stuartwdouglas** [comment]
@Sanne is this supposed to work? My gut feeling is that this is not considered supported, but I don't know enough about hibernate to say for sure.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
