### ISSUE TITLE
Improve OOTB experience with extensions for newly generated projects

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#8506]
### Description
Improve OOTB experience with extensions for newly generated projects.

There are several extension which are requiring configuration eagerly and this breaks "1) generate the bootstrap app 2) run dev mode 3) enjoy" flow / developer joy.

### Analysis
Identified extensions needing initial configuration: 
```
# no longer needed, quarkus-smallrye-jwt works out of the box
# mp.jwt.verify.publickey=asd
# mp.jwt.verify.publickey.location=/foo/bar

# Flyway minimal config properties
quarkus.flyway.migrate-at-start=false

# Flyway needs to configure a datasource
quarkus.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=sarah
quarkus.datasource.password=connor

quarkus.kafka-streams.application-id=foo-id
quarkus.kafka-streams.topics=kafka-topic

quarkus.artemis.url=foo
quarkus.qpid-jms.url=bar

quarkus.oauth2.client-id=client_id
quarkus.oauth2.client-secret=secret
quarkus.oauth2.introspection-url=http://oauth-server/introspect

quarkus.oidc.auth-server-url=https://localhost:8180/auth/realms/quarkus
quarkus.oidc.client-id=quarkus-app

quarkus.oidc-client.auth-server-url=http://localhost:6661/auth/realms/quarkus
quarkus.oidc-client.client-id=666
quarkus.oidc-client.token-path=token
quarkus.oidc-client.discovery-enabled=false
```
Note: this list was composed some time ago (~ 2020-03-10), anyway, a good starting point.

### Tasks
`__TODO__`
- [ ] _Checklist of sub tasks goes here, represented as links to GitHub issues_

**Comment by sberyozkin** [comment]
Re OIDC, it has a `tenant-enable` property set to true by default. IMHO it would not be ideal to start without the OIDC server being around in a non-dev mode so I'm not sure how to deal with it such that it is possible to add the connection properties in the dev mode but not in the dev mode. CC @stuartwdouglas

**Comment by rsvoboda** [comment]
@maxandersen / @paulrobinson please create tasks / checklist of needed actions

I didn't want to interfere in that section with your common workflow.

Should things like https://github.com/quarkusio/quarkus/issues/8534 be part of this epic too?

**Comment by maxandersen** [comment]
@rsvoboda yeah #8534 is relevant too!

**Comment by sberyozkin** [comment]
quarkus-smallrye-jwt will not need an initial configuration in Quarkus 1.5.0

**Comment by rsvoboda** [comment]
Adding `quarkus.qpid-jms.url` to the set of required properties

**Comment by rsvoboda** [comment]
Adding `quarkus.oidc-client` related properties

**Comment by sberyozkin** [comment]
@rsvoboda #16060 will fix it for `quarkus-oidc`

**Comment by rsvoboda** [comment]
`quarkus-qpid-jms` has better initial experience now, no extra config needed for generated project

**Comment by geoand** [comment]
Is there anything more to be done around this?

**Comment by rsvoboda** [comment]
I think the key parts were done, let's close it. We can file another issue if we notice another bulk.
