### ISSUE TITLE
container-image-docker erroneously logs "Pushed container image..."

### ISSUE THREAD

**Issue by arvidvillen** [quarkusio/quarkus#8507]
**Describe the bug**
When building docker images, the docker extension erroneously logs `Pushed container image...`
```
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor]  ---> Running in 99a4706fa61a
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] Removing intermediate container 99a4706fa61a
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor]  ---> e08fb3484fad
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] Successfully built e08fb3484fad
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] Successfully tagged example.com:5000/example/example:dev
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] Pushed container image example.com:5000/example/example:dev (e08fb3484fad)

[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 2680ms
```

**Expected behavior**
Do not log that the image is pushed if it was not.

**Actual behavior**
Always logs `Pushed container image ...` even if the image not pushed.

**To Reproduce**
1. ./mvnw quarkus:add-extension -Dextensions="container-image-docker"
2. ./mvnw clean package -Dquarkus.container-image.build=true
3. look at the log file

**implementation ides**
I think the problem is that `DockerProcessor.createContainerImage` prints the message even if `pushRequested ` and `containerImageConfig.push` is false.

The message could possibly be changed from `Pushed container image...` to `Built container image...`?

**Comment by geoand** [comment]
Thanks for spotting this!

#8517 should take care of it.
