### ISSUE TITLE
Importing libs with Provider

### ISSUE THREAD

**Issue by FreifeldRoyi** [quarkusio/quarkus#8509]
Hey,  
I created a multi-module project with common classes being used in different Quarkus modules in my project.  
For example the common module, contains `ExceptionMapper`s that are used throughout my code, with `@Provider` annotation.  
I couldn't get the mappers to run. Do I need to do something special in order to make it work ?

Thank you

**Comment by asodja** [comment]
You probably want to index them. Check this:
https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index.

I think you want something similar as it was asked here:
https://stackoverflow.com/a/55513723 -> Check Indexing other dependencies part.

**Comment by FreifeldRoyi** [comment]
Works thnx!
