### ISSUE TITLE
RequestScoped context is not propagated using rest-client and mutiny

### ISSUE THREAD

**Issue by AmsterdamFilho** [quarkusio/quarkus#8538]
**Describe the bug**
When using Mutiny, rest-client and context propagation, the request context is not propagated.

**Expected behavior**
The context is propagated.

**Actual behavior**
The following exception is thrown: 
ERROR [org.jbo.res.res.i18n] (pool-4-thread-2) RESTEASY002020: Unhandled asynchronous exception, sending back 500: javax.ws.rs.ProcessingException: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped

**To Reproduce**
A project to reproduce it is available [here](https://github.com/AmsterdamFilho/async-rest-client). It is based on the rest-client quick start guide. A ContainerRequestFilter was added to capture the authorisation header of every request and save it to a RequestScoped bean. Then, a ClientRequestFilter was added to insert this authorisation to the header of the external request using the RequestScoped bean. When executing the synchronous endpoint, it works just fine. But when using async call with mutiny, the exception is thrown.

1. Execute the project in using ./mvnw quarkus:dev;
2. Execute curl -w '\n' -X GET localhost:8080/country/name/greece --header "Authorization: 12345"
3. Verify a correct response is returned;
4. curl -w '\n' -X GET localhost:8080/country/name-uni/greece --header "Authorization: 12345"
5. Verify an exception is thrown.

**Environment:**
 - Output of `java -version`: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
 - Quarkus version: 1.3.2.Final

**Comment by cescoffier** [comment]
It's a Context Propagation issue. Both the method returning a `CompletionStage` and a `Uni` fails.

CC @FroMage

**Comment by cescoffier** [comment]
To clarify a bit, the Uni returned from the Rest Client does not get access to the request scope. I don't know where this Uni is created. @FroMage any idea? Is this in the extension or in RestEasy?

**Comment by FroMage** [comment]
So this is very different to #9141 because anything async will trip the client filter. So it doesn't matter if the endpoint's returned value is a `CompletionStage` or a `Uni` because we're not even there when the async http client barfs:

```
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:692)
	at org.jboss.resteasy.microprofile.client.impl.MpClientInvocation.filterRequest(MpClientInvocation.java:45)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:485)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.lambda$executorSubmit$11(ClientInvocation.java:765)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.jboss.resteasy.microprofile.client.async.AsyncInvocationInterceptorHandler$Decorator.lambda$decorate$0(AsyncInvocationInterceptorHandler.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
	at org.quarkus.test.app.AuthorizationHolder_ClientProxy.arc$delegate(AuthorizationHolder_ClientProxy.zig:202)
	at org.quarkus.test.app.AuthorizationHolder_ClientProxy.getAuthorization(AuthorizationHolder_ClientProxy.zig:68)
	at org.quarkus.test.app.GlobalClientRequestFilter.filter(GlobalClientRequestFilter.java:18)
	at org.quarkus.test.app.GlobalClientRequestFilter_ClientProxy.filter(GlobalClientRequestFilter_ClientProxy.zig:95)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:679)
	... 8 more
```

What this means is that the async http client runs on an executor and invokes the client request filters on it, but since this is on a new thread, the contexts are gone, and MP-CP never had a chance to act.

**Comment by FroMage** [comment]
That could also happen for async server filters, TBH. Except in this case the async is being sorta-hidden by the usage of the client.

**Comment by FroMage** [comment]
So, presumably I could call `RestClientBuilder.executorService` with the MP-CP `ManagedExecutor` and get context propagation, except I'm really not sure where I can get my hand on a `RestClientBuilder` when the client is autogenerated.

**Comment by AmsterdamFilho** [comment]
I am currently migrating some Thorntail micro services that communicate synchronously to Quarkus. Since they need to pass the token around, this is a blocker. Is there a workaround?

**Comment by FroMage** [comment]
Add this bean to you application:

```java
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;

import org.eclipse.microprofile.context.ManagedExecutor;
import org.eclipse.microprofile.rest.client.RestClientBuilder;
import org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver;

import io.quarkus.restclient.runtime.BuilderResolver;
import io.quarkus.runtime.Startup;
import io.quarkus.runtime.StartupEvent;

@ApplicationScoped
@Startup
public class Init {
    
    void onStartup(@Observes StartupEvent evt, ManagedExecutor executor) {
        RestClientBuilderResolver.setInstance(new BuilderResolver() {
            @Override
            public RestClientBuilder newBuilder() {
                RestClientBuilder ret = super.newBuilder();
                ret.executorService(executor);
                return ret;
            }
        });
    }

}

```

**Comment by FroMage** [comment]
If we fix this, we need to be careful that the client filters are not executed with the RESTEasy context from the server, but the client one, unlike the transaction/cdi contexts which should be propagated.

**Comment by FroMage** [comment]
PR https://github.com/quarkusio/quarkus/pull/9303 should fix this.

**Comment by AmsterdamFilho** [comment]
I tested the workaround. It works.
