### ISSUE TITLE
YAML Configuration ignores entries that use `.` instead of line breaks

### ISSUE THREAD

**Issue by oscarfh** [quarkusio/quarkus#8553]
**Describe the bug**
The configuration yaml extension does not parse configurations correctly when they are in the format
```
my.configuration: value
```

***Details***
I generated my application using https://code.quarkus.io/ and I selected the configuration yaml extension.
I renamed `application.properties` to `application.yaml` and added the entry (my config file has only this)
```
quarkus.log.level: DEBUG
```
This entry is ignored and my logs do not show up
I reorganize the configuration file to look like this
```
quarkus:
  log:
    level: DEBUG
```
It works.

**Expected behavior**
Both ways should be accepted, since both are valid YAML entries.

**Actual behavior**
the one-line variant is ignored

**To Reproduce**
1.  Download the application with the yaml configuration extension
2.  Add a logger with DEBUG level to your code
3.  Add the "multi line" variant in the configuration, it will work
4. Change it to be a one-liner, it will be ignored.

**Comment by dmlloyd** [comment]
While "quarkus.log.level: DEBUG" is a valid YAML entry, it is not equivalent to 
```yaml
quarkus:
  log:
    level: DEBUG
```
at a YAML level.  The mapping of YAML to configuration equates one YAML key to one MP Config key segment.

So this is really a feature request to interpret single YAML keys with embedded dots in the same way as YAML nested maps, which is not part of the YAML specification.  But doing so would prevent things like category names from working in YAML, which *do* need to be single YAML keys, and therefore I'm inclined to say that this is working as intended and is thus not a bug.

**Comment by oscarfh** [comment]
Ok, thanks for the reply. It makes sense.
I thought that category names would be expressed between quotes
as in:
```
quarkus.log.category."org.hibernate".level=DEBUG
```
from https://quarkus.io/guides/logging

I was in the process of trying to clone the project and prepare a PR, but if it is working as expected, I will leave it as it is.

thanks a lot

**Comment by cylab** [comment]
Actually it works like the OP expected in Spring, so this might be a confusing aspect for people migrating to Quarkus (like me)
