### ISSUE TITLE
quarkus-quartz using JobStoreTX and not JobStoreCMT

### ISSUE THREAD

**Issue by apat59** [quarkusio/quarkus#8555]
Hi,
as per [discussion](https://groups.google.com/forum/#!msg/quarkus-dev/5E86jXmzzmY/ri0NbOO-CQAJ)

Stuart Douglas thinks this may be a bug.
Env: quarkus 1.3.2.Final + maven + Postgres

is it expected quakus uses JobStoreTX and not JobStoreCMT with clustered
Quartz and db store type?

We're implementing an application mixing Panache and Quartz, we should
have to handle a global transaction to persist both PanacheEntities and a
related quartz Job.

We can workaround but we'd like to know if we could set
org.quartz.jobStore.class in some way.
Pseudo code is

```
    @Transactional
    void doStuff() {
            ...
            anEntity.persist();
            try {
                //create job and trigger ...
                quartz.scheduleJob(job, trigger);
            } catch (SchedulerException e) {
                LOGGER.error("unable to set jobs" + e);
            }
        }
    }
```

```
15:12:39 ERROR [co.re.ce.co.ap.jo.JobBuilderBean]
(QuarkusQuartzScheduler_Worker-2)  -> unable to set
jobsorg.quartz.JobPersistenceException: Couldn't commit jdbc connection.
Attempting to commit while taking part in a transaction [See nested
exception: java.sql.SQLException: Attempting to commit while taking part in
a transaction]
org.quartz.JobPersistenceException: Couldn't commit jdbc connection.
Attempting to commit while taking part in a transaction [See nested
exception: java.sql.SQLException: Attempting to commit while taking part in
a transaction]

```

**Comment by mkouba** [comment]
CC @machi1990

**Comment by machi1990** [comment]
I missed the discussion sorry @apat59 and thanks for reporting, but I second what @stuartwdouglas said and we should make this configurable.   I'll prepare a PR on this later on.
