### ISSUE TITLE
QuarkusTest start multiple services

### ISSUE THREAD

**Issue by Meemaw** [quarkusio/quarkus#8585]
**Description**
As part of the integration tests, I would like to start multiple (dependant) services for my tests as part of multi module project. Is this feasible to be in Quarkus?

**Comment by stuartwdouglas** [comment]
You can use @QuarkusTestResource, which is what we use internally. It's not really documented but it will work.

**Comment by Meemaw** [comment]
Can you point me to some examples? I'm sure there are other people that are interested in this so documenting it would also be great.

**Comment by famod** [comment]
See this discussion for an example: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/QuarkusTest.20.2B.20WireMock.20.2B.20dynamic.20port

**Comment by geoand** [comment]
Closing as `@QuarkusTestResource` is now documented in https://quarkus.io/guides/getting-started-testing#testing_different_profiles
