### ISSUE TITLE
Max frame length of 65536 has been exceeded

### ISSUE THREAD

**Issue by incube8r** [quarkusio/quarkus#8612]
**Description the bug**

In my code I added this to check for the real max frame size set:

```
@ConfigProperty(name = "quarkus.websocket.max-frame-size"")
Integer maxFrameSize;
```

Then simply log it:

```
@OnMessage
public void onMessage(ByteBuffer message, @PathParam("username") String username) {
 System.out.println("Max frame size: " + maxFrameSize);
 broadcast(message, username);
}
```

Here's the output:

```
Max frame size: 1048576
2020-04-16 15:29:23,901 WARN  [io.net.cha.DefaultChannelPipeline] (vert.x-eventloop-thread-1) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did no
t handle the exception.: io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
```

It seems like even the parameter is set the actual handler is still using the default one `65536`

**Expected behavior**

The max frame size should have been used as the configuration and clients should be able to transact to the server.

---

Tested with https://github.com/quarkusio/quarkus-quickstarts/tree/master/websockets-quickstart
Using `ByteBuffer` as payload and not String

**Comment by stuartwdouglas** [comment]
This is a build time config property, did you set the property at build time?

**Comment by stuartwdouglas** [comment]
Looks like there is an issue here: https://github.com/quarkusio/quarkus-http/pull/22

**Comment by incube8r** [comment]
@stuartwdouglas what would be the work-around for the meantime?

**Comment by provcristianmaluenda** [comment]
I am facing the same issue. Any work-around?

**Comment by gsmet** [comment]
The workaround would be to force the versions of the quarkus-http artifacts to 3.0.6.Final in your projects.

But 1.4 is coming with the fix really soon as we target Thursday for it.
