### ISSUE TITLE
Ability to use InjectMock on MicroProfile RestClient

### ISSUE THREAD

**Issue by eye0fra** [quarkusio/quarkus#8622]
**Describe the bug**

I would like to leverage the new `InjectMock` annotation to mock request/response to external service using the Microprofile Rest Client. The MP registers the implementation of the rest-client at runtime.

1. Injection

```java
 @InjectMock
 @RestClient
 GreetingService greetingService;
```

2. when

```java 
Mockito.when(greetingService.hello()).thenReturn("hello from server");
```

**Expected behavior**
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.client.mtls.GreetingResourceTest
2020-04-16 14:55:45,219 INFO  [io.quarkus] (main) Quarkus 1.4.0.CR1 started in 1.187s. Listening on: http://0.0.0.0:8081
2020-04-16 14:55:45,220 INFO  [io.quarkus] (main) Profile test activated. 
2020-04-16 14:55:45,221 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client, resteasy, resteasy-jsonb]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.432 s - in org.acme.client.mtls.GreetingResourceTest
2020-04-16 14:55:46,258 INFO  [io.quarkus] (main) Quarkus stopped in 0.027s
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```
**Actual behavior**
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.client.mtls.GreetingResourceTest
2020-04-16 14:47:34,265 INFO  [io.quarkus] (main) Quarkus 1.4.0.CR1 started in 1.200s. Listening on: http://0.0.0.0:8081
2020-04-16 14:47:34,266 INFO  [io.quarkus] (main) Profile test activated. 
2020-04-16 14:47:34,267 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client, resteasy, resteasy-jsonb]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.123 s <<< FAILURE! - in org.acme.client.mtls.GreetingResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.006 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.mockito.exceptions.base.MockitoException: 

Cannot mock/spy class com.sun.proxy.$Proxy52
Mockito cannot mock/spy because :
 - final class

2020-04-16 14:47:34,997 INFO  [io.quarkus] (main) Quarkus stopped in 0.028s
```

**To Reproduce**
1.  Find here a sample code: https://github.com/openlab-red/quarkus-client-mtls
2. Launch `mvn clean test`

**Configuration**
```properties
# N/A for the Test Case
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin MacBook-Pro 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`
 - Output of `java -version`: `openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)`
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  1.4.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  `OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/mmascia/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /Users/mmascia/.sdkman/candidates/java/20.0.0.r11-grl
Default locale: en_CH, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"`

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Actually, this will work if you add `@ApplicationScoped` to the `GreetingService` interface.

**Comment by geoand** [comment]
So maybe all we need to do is add an section to the documentation to mention if that if you want to be able to mock the RestClient, you need to make it `@ApplicationScoped`.

Would you like to contribute that fix @eye0fra ?

**Comment by eye0fra** [comment]
It does!

I tried before, but it was missing the @RestClient on the @InjectMock.

So the GreetingService will be like:

```
@Path("/")
@ApplicationScoped
@RegisterRestClient
public interface GreetingService {
```

Sure I can send a pull request on the documentation.

**Comment by geoand** [comment]
Excellent!

**Comment by UrosOdateam** [comment]
I get the same bug if I add `configKey` to @RegisterRestClient annotation like:

```
@Path("/")
@ApplicationScoped
@RegisterRestClient(configKey = "my-configkey-rest")
public interface GreetingService {
```
Without this configKey the thing works.

**Comment by geoand** [comment]
@UrosOdateam can you open a new issue with all the relevant information?

**Comment by ambition-consulting** [comment]
I don't see how this solution works for programatically built RestClients

**Comment by RaulGF92** [comment]
For clarify more the solution for a config-key RestClient in application-properties you should put that:

```
service/mp-rest/scope=javax.inject.Singleton
%test.service/mp-rest/scope=
```

**Comment by dufoli** [comment]
@geoand @gastaldi @famod we have exactly the same issue on cxf side 
quarkiverse/quarkus-cxf#248

Can you help us on it ? Because cxf generate the webservice class (SEI) so we can not add ApplicationScopped annotation to class.
IS there any transformation build item to do this kind of stuff. (modified generated class build item) ?
I notify maintainer of resteasy if you have idea about how to fix this bug for cxf, it can be helpfull.
@michalszynkiewicz  @gsmet @ronsigal @patriot1burke

**Comment by geoand** [comment]
I don't understand completely, but what scope is the `CXFClient`?

**Comment by dufoli** [comment]
CXFClient is an annotation to define soap client injection.
You can found example here :  https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/client.html
it is like a RESTClient.

**Comment by geoand** [comment]
And what kind of bean is created?

**Comment by dufoli** [comment]
the processor
https://github.com/quarkiverse/quarkus-cxf/blob/master/deployment/src/main/java/io/quarkiverse/cxf/deployment/QuarkusCxfProcessor.java
generate

client producer:
```
 // For a given SEI we create a dedicated client producer class, i.e.
        //
        // >> @ApplicationScoped
        // >> [public] {SEI}CxfClientProducer implements CxfClientProducer {
        // >>   @Inject
        // >>   @Named(value="{SEI}")
        // >>   public CXFClientInfo info;
        // >>
        // >>   @Produces
        // >>   @CXFClient
        // >>   {SEI} createService(InjectionPoint ip) {
        // >>     return ({SEI}) super().loadCxfClient(ip, this.info);
        // >>   }
        // >>
        // >>   @Produces
        // >>   @CXFClient
        // >>   CXFClientInfo createInfo(InjectionPoint ip) {
        // >>     return ({SEI}) super().loadCxfClientInfo(ip, this.info);
        // >>   }
        // >> }
```
and webservice class which are generated from wsdl by CXF:
example:

https://github.com/quarkiverse/quarkus-cxf/blob/master/integration-tests/src/main/java/io/quarkiverse/it/cxf/GreetingWebServiceImpl.java

https://github.com/quarkiverse/quarkus-cxf/blob/master/integration-tests/src/main/java/io/quarkiverse/it/cxf/GreetingWebService.java

**Comment by geoand** [comment]
So what scope are the produuced service and info? Dependant? If so, that doesn't work with mocking
