### ISSUE TITLE
Add quarkus:remove-extension

### ISSUE THREAD

**Issue by dhinojosa** [quarkusio/quarkus#8626]
**Description**
Every pencil needs an eraser.  If there is a `quarkus:add-extension` there must be `quarkus:remove-extension`. Example use case. Someone uses 'logging-json' and they don't like the verbosity, they can go back easy the way they came in.

**Implementation ideas**
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/remove-extension.3F

**Comment by aelfric** [comment]
Copying my comment from the chat.  It would be nice if a remove-extension goal could warn you if the extension is  being used in the project.
