### ISSUE TITLE
Set multiple tags to image

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#8643]
**Description**
image-container accepts version as the only image tag. Typically images have multiple tags, like version and "latest", or, as PostgreSQL, version tags with different precision used in combination with semantic versioning (e.g. "latest", "12", "12.5" and "12.5.4"). We also use multiple tags per image for our internal process.

**Implementation ideas**
An image should by default have "latest" and quarkus.application.version (which is by default version from the pom.xml). Users can specify "tags" property to enumerate tags. In that case, "latest" and ${quarkus.application.version} must be explicitly written.

**Comment by glefloch** [comment]
I'm interesting into working on this!
