### ISSUE TITLE
Elytron LDAP native test failure

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#8651]
Got this testing latest Graal/Quarkus with OpenJDK 11 (https://github.com/openjdk/jdk11u-dev/commit/f3b9513155b5e36cfc0e74048eca23b38485e0b1):

```
2020-04-17 15:21:30,378 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /api/requiresStandardRole failed, error id: 
4af2a4af-1daf-448c-8336-69ab4abec3c2-1: 
com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: 
Target_java_lang_ClassLoader.createOrGetClassLoaderValueMap()
```

Longer output [here](https://gist.github.com/galderz/54118a03f60e8c2422dcc994469bfb15).

Not 100% sure, but might be related to using OpenJDK instead of labs JDK, since @zakkak's latest failures with Labs JDK and Graal/Quarkus masters (see [here](https://github.com/zakkak/graal/actions/runs/79288545)) do not show a failure.

**Comment by zakkak** [comment]
Note that in my runs I am using the LabsJDK only for building GraalVM. For running the *native* quarkus tests I use the latest release of JDK 11 from adoptOpenJDK as the `JAVA_HOME` and the GraalVM build as the `GRAALVM_HOME`.

**Comment by galderz** [comment]
>  For running the native quarkus tests I use the latest release of JDK 11 from adoptOpenJDK as the JAVA_HOME and the GraalVM build as the GRAALVM_HOME.

Having AdoptOpenJDK 11 as JAVA_HOME does not much (if any) difference when it comes to native image building. In fact, I'd say that based on my personal experience, it complicates/obfuscates set ups. E.g. what JDK is used for what and what happens when the JAVA_HOME and GRAALVM_HOME differ?

So, what I tend to do is build graal and use the output of that as JAVA_HOME. That way you have a single thing JDK tree to worry about: the one that goes into the graal build and the one that comes out as a result (which is the one that went it + extras).

**Comment by galderz** [comment]
Indeed the origin of this issue is the underlying JDK. Latest jdk11u-dev contains fix for [JDK-8223260](https://bugs.openjdk.java.net/browse/JDK-8223260) which adds caching of `InitialContextFactory` instances, which can result of ClassLoaders being created on the fly. Graal code forbids that.

A workaround to avoid that path is to use a custom `InitialContextFactoryBuilder`. I've tried this and it worked. I'll send a PR in a few minutes.

Also, since @jerboaa reviewed the JDK fix, maybe he has ideas on how to improve the code at the JDK level and avoid/improve the experience.

**Comment by galderz** [comment]
Sent [draft PR](https://github.com/quarkusio/quarkus/pull/8696)

**Comment by galderz** [comment]
Note that Labs JDK source does not contain this fix yet, hence why the issue won't appear with latest GraalVM releases.

**Comment by jerboaa** [comment]
@galderz I don't think there is anything we can do at the JDK level for this.

**Comment by jerboaa** [comment]
@galderz note that the code path yielding up to `createOrGetClassLoaderValueMap()` comes from new code introduced via JDK-8223260 as you say. Namely:

```
var key = FACTORIES_CACHE.sub(className);
[...]
factory = key.computeIfAbsent(loader, (ld, ky) -> getFactory(ky.key()));
```

So I'd think a proper fix would be to adjust subtrate vm upstream to account for this new code path. They'll end up running into this as well one way or another at some point too. I'd think the cache needs to get replaced with a substrate vm version of it.

**Comment by galderz** [comment]
Thanks for the input @jerboaa, I'll report it on svm right away.

**Comment by galderz** [comment]
Opened https://github.com/oracle/graal/issues/2367

**Comment by galderz** [comment]
Issue fixed in GraalVM, so no need for a PR and we can close this issue now.
