### ISSUE TITLE
Start the application myself for @NativeImageTest 

### ISSUE THREAD

**Issue by andrejpetras** [quarkusio/quarkus#8654]
**Description**
I want to start the application myself for the integration tests. For example using the TestContainers framework.

**Implementation ideas**
Our delivery is Linux base docker image + native image. On the Windows (also on Linux) it is "hard" to test the native image.
I want to use the TestContainers for the integration test and for this I would like to have custom NativeImageLauncher.

We can use `ServiceLoader` and have a custom implementation of the `NativeImageLauncher`.
https://github.com/quarkusio/quarkus/blob/49964c7cf1850096fe90eaaa7a1cb7f0c119de44/test-framework/junit5/src/main/java/io/quarkus/test/junit/NativeTestExtension.java#L57

**Comment by geoand** [comment]
The use case you mention where you want to start the built container should be covered by https://github.com/quarkusio/quarkus/pull/15227
