### ISSUE TITLE
Use of validation groups 

### ISSUE THREAD

**Issue by fabiomrch** [quarkusio/quarkus#8668]
It seems not possible to apply javax.validation annotation @ConvertGroup to REST service parameters when REST resource class implements an API Interface.

My REST resource class:
```
@RequestScoped
public class RestR implements IRestR {
    @Override
    @Path("path")
    @POST
    @GZIP
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public ResponseDTO postApi(
            @Valid @ConvertGroup(to = CreateCheck.class) @NotNull(groups = CreateCheck.class) InputDTO dto) {
            return null;
    }
}
```

It implements the following interface:
```
public interface IRestR {
    @Path("path")
    @POST
    @GZIP
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public ResponseDTO postApi(
            @Valid @ConvertGroup(to = CreateCheck.class) @NotNull(groups = CreateCheck.class) InputDTO dto
    );
}
```

The application cannot start since it generates this exception: `javax.validation.ConstraintDeclarationException: HV000124: Found multiple group conversions for source group javax.validation.groups.Default: com.myapp.api.dto.validation.groups.CreateCheck.`

Ommitting @ConvertGroup in API interface method would cause  `javax.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not redefine the parameter constraint configuration, but method RestR#postApi(InputDTO) redefines the configuration of IRestR#postApi(InputDTO).`

Is there a way to exclude some annotations from being detected by redefinition check?

An alternative implementation of bean validation would require AspectJ that it is not supported by Quarkus.

**Comment by gsmet** [comment]
Yeah, unfortunately the rules for validation in hierarchy are quite strict.

You can disable the checks in Hibernate Validator but we haven't exposed the configuration to do it.

Maybe we should.

**Comment by gsmet** [comment]
@fabiomrch could you try this PR: https://github.com/quarkusio/quarkus/pull/8698 ?

Get the PR, build it with:
```
mvn clean install -DskipTests -DskipITs
```
Then upgrade your project to use `999-SNAPSHOT`, be careful you need to use the `quarkus-bom` not the universe one and also update the Quarkus Maven plugin accordingly.

Once done, try to add: `quarkus.hibernate-validator.method-validation.allow-overriding-parameter-constraints` to your `application.properties`.

If you can confirm it works, I'll push that in 1.4.

Thanks!

**Comment by fabiomrch** [comment]
Thanks @gsmet !

Unfortunately this error occurs when I try to build my project:
```
Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project myapp: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]     [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: io.quarkus.deployment.configuration.ConfigurationError: Hibernate extension cannot guess the dialect as no database kind is specified by 'quarkus.datasource.db-kind'
[ERROR]     at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.guessDialect(HibernateOrmProcessor.java:857)
[ERROR]     at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcessor.java:677)
[ERROR]     at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.build(HibernateOrmProcessor.java:237)
[ERROR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]     at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]     at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:931)
[ERROR]     at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]     at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
[ERROR]     at java.lang.Thread.run(Thread.java:748)
[ERROR]     at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

application.properties file includes the following lines:
```
quarkus.datasource.db-kind = postgresql
quarkus.hibernate-validator.method-validation.allow-overriding-parameter-constraints=true
```

**Comment by gsmet** [comment]
Could you prepare a small reproducer in the form of a Maven project so that I can have a look?

It looks odd.

**Comment by fabiomrch** [comment]
I have some problems while building my project with 'mvn clean install' that I'm trying to solve. I have just run it using 'mvn compile quarkus:dev' and everything works fine! Your fix actually disables checks in Hibernate Validator!
