### ISSUE TITLE
Firebase SDK Extension

### ISSUE THREAD

**Issue by ridvan70** [quarkusio/quarkus#8671]
**Description**
Firebase Admin SDK is a widely used artifact in google cloud.

**Implementation ideas**

```
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.12.2</version>
        </dependency>
```

**Comment by add-harris** [comment]
Is there any update on this pls?

**Comment by samekim** [comment]
+1

**Comment by loicmathieu** [comment]
This has been provided inside the Google Cloud Services extension pack in https://github.com/quarkiverse/quarkus-google-cloud-services/pull/336
