### ISSUE TITLE
1.4RC1 quarkus.smallrye-jwt @Authenticated not working 

### ISSUE THREAD

**Issue by seseso** [quarkusio/quarkus#8673]
When quarkus.smallrye-jwt is enabled and configured and a resource is marked with @Authenticated annotation, two things happen differently:
- If no token is passed, my ContainerRequestFilter is executed as if the request is "Authenticated" wich is not true. This was not happening in 1.3 FINAL.
- If an invalid token is passed to the resource, my ContainerRequestFilter is not invoked, which is the expected behavior.

**Expected behavior**
When no token is sent, a 401 code should be returned for @authenticated reources, before invoking any ContainerRequestFilter 

**Actual behavior**
The ContainerRequestFilter is invoked if no token is sent along a request to an @Authenticated resource

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.4.0.CR1

**Additional context**
I don't have a reproducer right now available but please let me know if it's necessary. My application just have ContainerRequestFilter with some resources, all of which should be accessed by authenticated users.

**Comment by sberyozkin** [comment]
@seseso is you filter pre- or post- match ?

**Comment by seseso** [comment]
It have both, but I only use (for now,) the pre-:

@Provider
public class SecurityContextFilter implements ContainerRequestFilter,
ContainerResponseFilter {

    @Override
    public void filter(ContainerRequestContext crc) throws IOException {
        // My code
    }

    @Override
    public void filter(ContainerRequestContext crc,
ContainerResponseContext crc1) throws IOException {
        // empty for now
    }
}


Sérgio Sousa

**Comment by sberyozkin** [comment]
@seseso I'm not sure right now what might have changed, but we are trying to get the Quarkus security closer to JAx-RS chains, and the pre-matching chain is not tied to any JAX-RS resource (class or method). So if the pre-matching filter is invoked when even no token is available, I'd not consider it a bug.

If you a post-matching filter invoked with `Authenticated` on the class resource, then it would closer to a bug, though even in this case `Authenticated` is not saying that the filters can't be invoked at all.

What happens if you use a post-matching filter ?

CC @stuartwdouglas

**Comment by seseso** [comment]
The problem is that I need to "enrich" user data on each request so a
post-matching filter won't solve my problem. This behavior does not
happened in 1.3.2.Final nor previous releases since I'm developing this app
for quite some time.
I would expect that a previous security filter from quarkus would return a
401 before it reaches my filter, since I've the security enabled.
Otherwise, it wouldn't make much sense to have a security extension but
still implement basic security logic on my filter.

Sérgio Sousa

**Comment by stuartwdouglas** [comment]
So a pre match filter can change the target of the request, which means at this point we have no way of knowing if a request is authenticated or not (as the endpoint has not been matched yet).

If you want to apply a blanked @Authenticated approach you are probably better off using some config in application.properties https://quarkus.io/guides/security#authorization-of-web-endpoints-using-configuration

**Comment by seseso** [comment]
I get it now. What got me confused was the fact that an invalid token didn't reach my filter, so, I assume that there is a security filter that validate the token, if exists, otherwise, send the request downstream in the filter queue.

I'll close this.

Thanks guys!
