### ISSUE TITLE
Parametrize native build on docker

### ISSUE THREAD

**Issue by leandrodelsole** [quarkusio/quarkus#8674]
**Describe the bug**
Running 
`mvn package -Dnative -Dnative-image.docker-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 -Dnative-image.xmx=7g` 
fails to include configuration files as this in `pom.xml`
`<additionalBuildArg>-H:ConfigurationFileDirectories=${project.basedir}/native/config</additionalBuildArg>`

The same also happens using: 
`<additionalBuildArg>-H:ResourceConfigurationFiles=${project.basedir}/src/main/resources/native/resource-config.json</additionalBuildArg>`

If I build the native image without using `docker-build` option, it works as expected.

It is clear to me that happens because docker can't access this directory structure, as the `docker run` has only this volume:
`docker run -v /home/leandrodelsole/gitbzion/fiscal/target/fiscal-0.0.1-SNAPSHOT-native-image-source-jar:/project:z ...`

**Workaround**
Or the way I could get this to work currently.

Placing the files in `<project>/src/main/resources/` and configuring `pom.xml` args as:
```
<additionalBuildArg>-H:ResourceConfigurationFiles=resource-config.json</additionalBuildArg>
<additionalBuildArg>-H:ReflectionConfigurationFiles=reflect-config.json</additionalBuildArg>
```

However, it is not desirable. I don't want these file to be packaged within my jar. Further, I find it is better organized if configuration files are in specific folder.

**Expected behavior**
`-H:ConfigurationFileDirectories` specified dir is reachable to docker when using `-Dnative-image.docker-build=true` option.
`-H:ResourceConfigurationFiles` could reference files outside the `src/main/resources` root. Even subdirectories doesn't work.
Both `-Dnative-image.docker-build` true and false work with same `pom.xml` configuration.

**Actual behavior**
Native image build happens, but when `-Dnative-image.docker-build=true` configurations such as resources / reflections are not applied if they are not in `src/main/resources` root and referenced through `-H:ResourceConfigurationFiles`

**To Reproduce**
1. Create a minimal project that depends on reflection.
2. Place reflect-config.json on a path different from `src/main/resources`, e.g. `${project.basedir}/native/config`
3. Configure reflect-config.json on `pom.xml`, e.g. `H:ResourceConfigurationFiles=${project.basedir}/native/config/reflect-config.json`
4. Run `mvn clean package -Dnative -Dnative-image.docker-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 -Dnative-image.xmx=7g`

**Configuration**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux ubunputtu 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`:
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

 - GraalVM version (if different from Java): 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)

 - Quarkus version or git rev: 
1.3.2.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Implementation ideas**
Some options:
1. Change maven cycle in a way that allow us to copy our resources to the final directory. E.g. in `prepare-package` phase, I would copy my files to `fiscal-0.0.1-SNAPSHOT-native-image-source-jar`. Extend this to Gradle if not achiavable yet.
2. Less flexible but seamless: parse all arguments, understand directory structure and reproduce it in the volume directory, in this example: /home/leandrodelsole/gitbzion/fiscal/target/fiscal-0.0.1-SNAPSHOT-native-image-source-jar.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
