### ISSUE TITLE
Some tracing integration tests that run against an actual Jaeger instance

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#8680]
Probably we would use `testcontainers`. For inspiration see https://medium.com/jaegertracing/generating-jaeger-grpc-services-and-using-jaeger-in-junit-with-testcontainers-ac08a6e4e1c

**Comment by geoand** [comment]
Just in case it's not well, known, here is an example of what we usually do to integrate testcontainers with Quarkus: https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-quickstart/src/test/java/org/acme/kafka/KafkaResource.java

**Comment by lburgazzoli** [comment]
We use testcontainers extensively in camel, an example: https://github.com/apache/camel-quarkus/blob/master/integration-tests/mongodb/src/test/java/org/apache/camel/quarkus/component/mongodb/it/MongoDbTestResource.java

**Comment by geoand** [comment]
I am pretty sure this has long been resolved, so I will go ahead and close it.
