### ISSUE TITLE
Warning with infinispan embedded config doc missing

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#8697]
I just had the following warning when building master:
```
[INFO] asciidoctor: INFO: infinispan-embedded.adoc: line 82: optional include dropped because include file not found: /data/home/gsmet/git/quarkus/target/asciidoc/generated/config/quarkus-infinispan-embedded.adoc
```
We have `InfinispanEmbeddedRuntimeConfig` though so I'm not sure what's going on.

@machi1990 could you have a look?

**Comment by machi1990** [comment]
It is related to https://github.com/quarkusio/quarkus/pull/8641 and more specifically - https://github.com/quarkusio/quarkus/pull/8684. 

Here is an important info that we missed when review the first PR, the doc generator checked if a config root is used in any build step before generating corresponding global config doc file.

**Comment by gsmet** [comment]
Ah ah, we probably need to remove that check :).

But the issue is that we have a bunch of config stuff that is only there to avoid having warnings when using `quarkus.` properties.

**Comment by gsmet** [comment]
Or maybe we can also check if it's injected somewhere?

**Comment by machi1990** [comment]
I am looking at removing that check. Well, I am building now, it should probably work.

**Comment by machi1990** [comment]
> Or maybe we can also check if it's injected somewhere?

This is my option B. But I am afraid it could complicate the processor code, so for now I am looking at removing the check.

**Comment by gsmet** [comment]
Yeah, I'm a bit worried about this fake config we created. I'll see what you have in your PR :).

**Comment by geoand** [comment]
So do you want me to do anything?

**Comment by gsmet** [comment]
Nope, just wanted you to be aware of that one.

**Comment by machi1990** [comment]
> Yeah, I'm a bit worried about this fake config we created. I'll see what you have in your PR :).

Oh yes, most of these are in the `core` module, the only affected file will be `quarkus-core.adoc` which is not included anywhere. 

The are already included in the all configuration docs which is not a shock to me.

**Comment by machi1990** [comment]
By the way, if these fake configs become a problem in the long run maybe we could introduce a `@SkipConfigDocGeneration` annotation for them.
