### ISSUE TITLE
Forwarding to JAX-RS from ServletFilter returns 404

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#8709]
**Describe the bug**
When a servlet filter tries to forward a request to a valid JAX-RS (Resteasy) endpoint, undertow cannot locate the endpoint and returns a 404 not found

**Expected behavior**
Undertow should be able to forward the request successfully as JAX-RS should just be another endpoint on the same server and accessible with a forward.

**Actual behavior**
404 not found is returned

**To Reproduce**
git clone https://github.com/bcluap/quarkus-forward.git; cd quarkus-forward; mvn clean install

**Configuration**
```
Empty properties file
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26746221/79786638-1155b380-8346-11ea-842c-9a38cf16dec7.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux PCBLaptop 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.6" 2020-01-14
 - GraalVM version (if different from Java): NA
 - Quarkus version or git rev: 1.4.0.CR1 and 999-SNAPSHOT both fail

**Additional context**
Same code works on TomEE
Checked all the way back to 1.0.0.Final and it also fails the test

**Comment by gastaldi** [comment]
@stuartwdouglas any clue?

**Comment by bcluap** [comment]
Thanks guys. Confirmed working with latest source. Brilliant - this would have been a real blocker for us on an app we migrating to Quarkus.

**Comment by gsmet** [comment]
Thanks for the confirmation. I backported it to the 1.4 branch so it will be part of 1.4.0.Final.
