### ISSUE TITLE
Make enabling OpenTracing for JDBC a property

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#8710]
Right now, you have to define a specific driver and a specific JDBC URL whereas we could make it a simple property and keep everything as is.

Also, we should probably register the driver for reflection even if disabled, as long as it is in the classpath.

It would be nice if this flag could be enabled/disabled at runtime.

See `io.opentracing.contrib.jdbc.TracingDriver` for more info.

**Comment by Ladicek** [comment]
I think I even looked into the `TracingDriver` code and it doesn't support MSSQL, which is unfortunate. (I'm not sure why they need to parse the JDBC URL, but there's probably a reason :-) )

**Comment by adrianfiedler** [comment]
Hi @gsmet,
what exactly would be the idea here? I guess there is a need for a new runtime config `quarkus.smallrye-opentracing.enabled` boolean (default true). And this should then set implicitly `quarkus.datasource.jdbc.driver=io.opentracing.contrib.jdbc.TracingDriver` and `quarkus.datasource.jdbc.url=jdbc:tracing:<rest>`? Not sure where this replacement should happen. Also not sure what happens if you disable it at runtime, because the jdbc driver is set at build time.

**Comment by nunomarks** [comment]
Hello @gsmet,
Is this still needed ? I would like to take this up as a first contribution to Quarkus repository.

**Comment by gsmet** [comment]
Sorry I totally missed the comments here :/.

My idea was to somehow keep the driver and then have something like:
```
quarkus.datasource.jdbc.tracing=true (default value would be false, this would be a build time property)
quarkus.datasource.jdbc.tracing.enabled=true/false that could be a runtime property and that would enable the tracing effectively, default value would be false if tracing=false and true if tracing=true
```

When `quarkus.datasource.jdbc.tracing` is true, we would register the tracing driver for reflection together with the underlying JDBC driver.

If `quarkus.datasource.jdbc.tracing.enabled` is true, we would use the tracing driver in `DataSources` at runtime.

My guess is that could work but only if we can find a reliable way to make a standard JDBC URL a tracing one. I'm unsure how additional parameters are handled typically.

**Comment by tmihalac** [comment]
I would like to start working on the issue, can you please point me in the right direction.

**Comment by gsmet** [comment]
@tmihalac so the first step would be to add the config items:
- here for the build time config: `DataSourceJdbcBuildTimeConfig`
- here for the runtime one: `DataSourceJdbcRuntimeConfig`
(see above comment for the items)

Then the key is to use these properties:
- in `DataSources` to initialize the datasource with the proper tracing driver and the tracing URL (what I'm not exactly sure is if it will be easy/doable to take the JDBC URL and transform it to a tracing URL)
- in the `AgroalProcessor`, you will need to register the tracing driver for reflection in addition to the resolved driver class if the build time config is enabled:
```
            reflectiveClass
                    .produce(new ReflectiveClassBuildItem(true, false,
                            aggregatedDataSourceBuildTimeConfig.getResolvedDriverClass()));
```

Also, you probably need to throw an error in the `AgroalProcessor` if build time property is true and you don't have the tracing driver around.
You can use this method for that: https://github.com/quarkusio/quarkus/blob/main/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java#L56 (but I need to fix the Javadoc as it's incorrect, will do so right away).

**Comment by tmihalac** [comment]
default value would be false if tracing=false and true if tracing=true
Where do I write the code to enforce this ?

**Comment by tmihalac** [comment]
> 

There is an option to use the tracing driver in interceptor mode : https://github.com/opentracing-contrib/java-jdbc#interceptor
Maybe it is better to use in this mode and then we dont need to replace the url.

**Comment by tmihalac** [comment]
> @tmihalac so the first step would be to add the config items:
> 
> * here for the build time config: `DataSourceJdbcBuildTimeConfig`
> * here for the runtime one: `DataSourceJdbcRuntimeConfig`
>   (see above comment for the items)
> 
> Then the key is to use these properties:
> 
> * in `DataSources` to initialize the datasource with the proper tracing driver and the tracing URL (what I'm not exactly sure is if it will be easy/doable to take the JDBC URL and transform it to a tracing URL)
> * in the `AgroalProcessor`, you will need to register the tracing driver for reflection in addition to the resolved driver class if the build time config is enabled:
> 
> ```
>             reflectiveClass
>                     .produce(new ReflectiveClassBuildItem(true, false,
>                             aggregatedDataSourceBuildTimeConfig.getResolvedDriverClass()));
> ```
> 
> Also, you probably need to throw an error in the `AgroalProcessor` if build time property is true and you don't have the tracing driver around. You can use this method for that: https://github.com/quarkusio/quarkus/blob/main/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java#L56 (but I need to fix the Javadoc as it's incorrect, will do so right away).

There is an option to use the tracing driver in interceptor mode : https://github.com/opentracing-contrib/java-jdbc#interceptor
Maybe it is better to use in this mode and then we dont need to replace the url.

**Comment by gsmet** [comment]
Yeah I'm not entirely sure how this would work with Quarkus as IIRC we are doing things with the `DriverManager` too. Also there is this warning `Please note driver like Oracle JDBC may fail since it's destroyed forever after deregistration`.

It might be worth testing if it works or not, though as that would solve one of our problems.

**Comment by tmihalac** [comment]
@gsmet 

quarkus.datasource.jdbc.tracing.enabled=true/false (default value would be false if tracing=false and true if tracing=true)
Where do I write the code to enforce this ?

**Comment by gsmet** [comment]
hey @tmihalac ,

I'm not sure I understand your question. If you use the JDBC URL mode, you shouldn't have to do anything?

At least, that's what our documentation is saying: https://quarkus.io/guides/opentracing#jdbc .

Let me know if something is unclear. I will be around for the coming weeks.

**Comment by tmihalac** [comment]
> hey @tmihalac ,
> 
> I'm not sure I understand your question. If you use the JDBC URL mode, you shouldn't have to do anything?
> 
> At least, that's what our documentation is saying: https://quarkus.io/guides/opentracing#jdbc .
> 
> Let me know if something is unclear. I will be around for the coming weeks.

@gsmet On the open tracing github https://github.com/opentracing-contrib/java-jdbc the instruction for JDBC URL mode, say 
 the last step to do is as following:

```Instantiate tracer and register it with GlobalTracer.

// Instantiate tracer
Tracer tracer = ...

// Register tracer with GlobalTracer
GlobalTracer.register(tracer);```

I was asking about the tracer instantiation phase.

**Comment by gsmet** [comment]
This is all done automatically here when using the Jaeger extension: https://github.com/quarkusio/quarkus/blob/main/extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/JaegerDeploymentRecorder.java#L46-L66 .

**Comment by tmihalac** [comment]
> This is all done automatically here when using the Jaeger extension: https://github.com/quarkusio/quarkus/blob/main/extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/JaegerDeploymentRecorder.java#L46-L66 .

So there is no need to do this code block ?

```
Instantiate tracer and register it with GlobalTracer.

// Instantiate tracer
Tracer tracer = ...

// Register tracer with GlobalTracer
GlobalTracer.register(tracer);
```

In addition while running tests using DB containers the tracing driver didn't work with Oracle DB, I found this [issue 18509](https://github.com/quarkusio/quarkus/issues/18509), tried to updated opentracing-jdbc from 0.2.4 to 0.2.15 but then I encounter this issue [issue 18033](https://github.com/quarkusio/quarkus/issues/18033) 
Any ideas ?

**Comment by tmihalac** [comment]
I want to open a pull request but the gradle tests are failing, I don't know what is wrong with them: https://github.com/tmihalac/quarkus/runs/6881642640?check_suite_focus=true

**Comment by michalvavrik** [comment]
Closing as @tmihalac PR is merged - https://github.com/quarkusio/quarkus/pull/26144.
