### ISSUE TITLE
Unable to set custom app.openshift.io/runtime label when deploying with OpenShift extension

### ISSUE THREAD

**Issue by jamesfalkner** [quarkusio/quarkus#8730]
**Describe the bug**
When using the OpenShift extension, if I provide a label for the runtime icon, it gets overwritten with `quarkus`.

**Expected behavior**
The label I set with `-Dquarkus.openshift.labels.app.openshift.io/runtime=java` should be set on the resulting `DeploymentConfig`

**Actual behavior**
The label is set to `app.openshift.io/runtime=quarkus`

**To Reproduce**
1. Add `openshift` extension
2. Deploy to OpenShift with `mvn clean package [...] -Dquarkus.openshift.labels.app.openshift.io/runtime=java`
3. See resulting label is set to `quarkus` instead of `java`

**Comment by geoand** [comment]
Does the same occur if you use:

```
quarkus.openshift.labels."app.openshift.io/runtime"=java
```

?

**Comment by jamesfalkner** [comment]
Nope, didn't work. I suspect the problem is with the dots, because:

`-Dquarkus.openshift.labels.foo.bar=java` does not work (no label at all is set)
`-Dquarkus.openshift.labels."foo.bar"=java` does not work (no label at all is set)
`-Dquarkus.openshift.labels.foo=java` works as expected

**Comment by geoand** [comment]
OK, I'll check it out tomorrow and let you know

**Comment by geoand** [comment]
@jamesfalkner if you add `quarkus.openshift.labels."foo.bar"=java` to `application.properties` it works as is.

If however you are passing a system property (which appears to be the case), you need to escape the the quote (this is shell thing, not anything to do with Quarkus). In that case doing `-Dquarkus.openshift.labels.\"foo.bar\"=java` works.

I'll go ahead and close this issue. If you try and it doesn't work, feel free to reopen.
