### ISSUE TITLE
Support @RequestScoped beans in command line mode

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#8758]
**Description**
Having 
```java
@RequestScoped
public class MyJPAService {
}
```

And the main class for a command line application: 

```java
@QuarkusMain
public class MainApplication implements QuarkusApplication {
    @Inject
    MyJPAService service;

    public static void main(String[] args) {
        Quarkus.run(MainApplication.class, args);
    }
    @Override
    public int run(String... args) throws Exception {
        System.out.println("Instance:  " + service);
        return 0;
    }
}
```

When I run `mvn quarkus:dev`, I get the following exception: 

```
2020-04-22 13:29:50,255 ERROR [io.qua.run.Application] (Quarkus Main Thread) Error running Quarkus application: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped

```

A workaround is to call `Arc.container().requestContext().activate();` in the `MainApplication#run` method (and deactivate when it's done). 

**Implementation ideas**
Change the core implementation that calls my Main method to initialize the Arc container if a `@RequestScoped` class is used.

**Comment by maxandersen** [comment]
yeah would be great to be able to put *Scopes on the main class to simplify writing of the class.

**Comment by Ladicek** [comment]
CC @mkouba @manovotn

**Comment by manovotn** [comment]
Well, req. context (de)activation is bound to HTTP request. You can activate it manually either the way you noted, or you can use `@ActivateRequestContext` method annotation (interceptor in fact) that will activate the scope for the given method and shut it down afterwards.

If you activate request context for the whole main method, it means it will be active from app start to its shutdown. That kind of defeats the purpose of the scope, you might as well use `@ApplicationScoped` at that point. Unless I am missing something? :)

**Comment by mkouba** [comment]
> If you activate request context for the whole main method, it means it will be active from app start to its shutdown. That kind of defeats the purpose of the scope...

I believe that the intention is to support `@RequestScoped` beans during "quarkus command execution". And the request context is not necessarlly bound to an HTTP request. There are few exceptions in the spec and we have few more in Quarkus. In this case, the command execution is a "request".

Yes, `@ActivateRequestContext` should work.

**Comment by manovotn** [comment]
Yea, I am aware of the exceptions.

> the intention is to support @RequestScoped beans during "quarkus command execution". 

Ok, that makes some sense :)
So I guess we could use annotations transformer and just slam `@ActivateRequestContext` on those `run` methods?

**Comment by mkouba** [comment]
Sounds too complicated ;-). I'd rather just activate the context.

**Comment by maxandersen** [comment]
@mkouba you mean users should be required to put `Arc.container().requestContext().activate();` in every cli or that you think the context should just always be activated ? 

btw. if alternative contexts makes sense i'm fine requiring users to put an annotation to be specific - but it would be nice if in the run method there would be something available by default as the whole purpose of the run is to do something useful ;)

**Comment by maxandersen** [comment]
hmm - just tried just adding `@ActivateRequestContext` and it seem to just work.

```
  @ActivateRequestContext
  public int run(String... args) throws Exception {   
```

I think I'm actually fine with that if there is a downside on having it activated always ? cc @stuartwdouglas

**Comment by maxandersen** [comment]
did a PR to docs at #8809 to highlight the need.

**Comment by mkouba** [comment]
> @mkouba you mean users should be required to put Arc.container().requestContext().activate(); in every cli or that you think the context should just always be activated ?

Nope. We should either activate it automatically or encourage users to use `  @ActivateRequestContext`.

**Comment by stuartwdouglas** [comment]
Maybe just document `@ActivateRequestContext`. The down side to automatically activating it is that users can't control it manually if they actually want a more limited scope.

**Comment by mkouba** [comment]
Yes, that's what we agreed on as the automatic activation turns `@RequestScoped` beans into `@ApplicationScoped` beans and that's probably not always desirable.

**Comment by maxandersen** [comment]
yeah, we agreed request mode should be explicitly requested as other @injects just work and you do want to be able to have multiple request scopes available to you.

thus closing this one as wont-fix and documenting at https://github.com/quarkusio/quarkus/pull/8809
