### ISSUE TITLE
Improve error reporting of configuration

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#876]
Two cases that might need some love:
- when creating a ConfigRoot with a name containing a dot, we don't have any error saying it is not valid but the config root can't be found: "Unknown root key: ". Either we should support that or throw a proper error (I would like for it to be supported but I can live without it).
- AFAICS, nested ConfigGroup classes need to be static. Otherwise, you end up with a rather cryptic error from the compiler:
```
Fatal error compiling: java.lang.UnsupportedOperationException: Instantiating a Nested type XXXConfig of Reference of type XXXParentConfig as a class
```
Throwing a proper error from the annotation processor would probably be nicer.

**Comment by radcortez** [comment]
I believe with the move to @ConfigMapping this is no longer relevant.
