### ISSUE TITLE
Empty configuration values are passed to the converter

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#877]
From a discussion with David today.

When you have something like:
```
MyEnum configProperty;
```
with `MyEnum` having a `of(String)` method to have an implicit converter, the empty value (empty string) is passed to the converter to determine the default.

David thinks the value should be null and the empty string should not be passed to the converter.

Note that it works OK when the configProperty is of type `Optional<MyEnum>`.

**Comment by dmlloyd** [comment]
This was previously fixed and should no longer be a problem.
