### ISSUE TITLE
Reactive PG client native test NPE with latest masters and jdk11u-dev

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#8776]
Environment: 
Master branches for Quarkus and SVM, jdk11u-dev based JDK (not labs JDK)

Error building native for `reactive-pg-client` test:
```
Caused by: java.lang.NullPointerException
        at java.base/java.lang.ClassValue$ClassValueMap.loadFromCache(ClassValue.java:535)
        at java.base/java.lang.ClassValue$ClassValueMap.probeHomeLocation(ClassValue.java:541)
        at java.base/java.lang.ClassValue.get(ClassValue.java:101)
```

[Longer output](https://gist.github.com/galderz/4426cc2285588286710331b4ddeca1ee)

**Comment by galderz** [comment]
Note: I used a rebased branch of #8651 here, in case that fix is indirectly causing this... I'll dig into this today

**Comment by cescoffier** [comment]
@galderz Anything that needs to be fixed in the extension?

**Comment by galderz** [comment]
@cescoffier I've not been able to reproduce it again in the different envs I have (with the same code), so it might be a race condition of some sort. I don't think this is anything Quarkus related at this stage, so I'll probably close this issue later today and open one in oracle/graal.

**Comment by galderz** [comment]
Closing this since it's a JDK issue. Follow https://github.com/graalvm/mandrel/issues/22 for further progress.

**Comment by Karm** [comment]
> Closing this since it's a JDK issue. Follow [graalvm/mandrel#22](https://github.com/graalvm/mandrel/issues/22) for further progress.

@galderz So...is this Quarkus one closed then? Could you close it then?
