### ISSUE TITLE
Eclipse Debug looses Quarkus connection

### ISSUE THREAD

**Issue by semisft** [quarkusio/quarkus#8793]
**Description**
Eclipse debugging attached to quarkus:dev session is lost after a few restarts of quarkus.

**Implementation ideas**
Quarkus may obtain the Eclipse debug endpoint and keep between restarts.

**Comment by jaikiran** [comment]
Which operating system is this on? We had a recent issue that was reported where during restarts, Quarkus would skip staring in "debug" mode in some cases https://github.com/quarkusio/quarkus/issues/8927. That has been fixed in the upstream master branch of Quarkus.

**Comment by semisft** [comment]
Windows platform, and it seems to be fixed. Thanks.
