### ISSUE TITLE
Kubernetes: remove useless and potentially confusing dekorate output

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#8798]
**Description**
When using the Kubernetes extension, one will see the following (or similar output) during build:
```
[INFO] Initializing dekorate session.
[INFO] Default s2i build generator....
[INFO] Registering s2i handler!
[INFO] Registering s2i handler!
[INFO] Generating manifests.
[INFO] Processing kubernetes configuration.
[INFO] Processing openshift configuration.
[INFO] Processing s2i configuration.
[INFO] Closing dekorate session.
```
This not only doesn't provide any useful information but is potentially confusing, in particular when neither openshift nor s2i extensions are enabled.

**Comment by gsmet** [comment]
I agree this should be debug.

@geoand WDYT?

**Comment by geoand** [comment]
Yeah, these outputs make no sense most of the time and should be debug logging

**Comment by geoand** [comment]
@metacosm do you plan on working on this?

It looks like it might need some changed in dekorate as well, since these messages come from an internal dekorate implementation (which I assume was done to get past problems with logging and annotation processors).

**Comment by metacosm** [comment]
Planning on working on #8792 first, though I might work on this at the same time.

**Comment by geoand** [comment]
Cool

**Comment by geoand** [comment]
I'll do this one real quick then :)

**Comment by geoand** [comment]
This also requires: https://github.com/dekorateio/dekorate/pull/488

I should have fixed that in the first place... Oh well

**Comment by gsmet** [comment]
I removed the backport tag and marked it for 1.5.0 so that we don't forget about it.

**Comment by geoand** [comment]
Good idea. This needs a new dekorate release to be properly fixed
