### ISSUE TITLE
Windows synchronizes files to Linux incorrectly in Remote Development Mode

### ISSUE THREAD

**Issue by yuhaibohotmail** [quarkusio/quarkus#8803]
**Describe the bug**
Windows synchronizes files to Linux incorrectly in Remote Development Mode.
Remote host will create the file  with window directory name :
org\acme\MessageResource.java
![1587687073(1)](https://user-images.githubusercontent.com/48646226/80161533-375bac00-8603-11ea-808d-89b176ee960f.png)

**To Reproduce**
1. On Linux remote host run:
mvn compile quarkus:dev -Dquarkus.live-reload.password=123
2. On Windows local  agent  run: 
mvn quarkus:remote-dev  -Dquarkus.live-reload.password=123  -Dquarkus.live-reload.url=http://192.168.177.128:8080
3. Change the source code on local host

**Comment by jaikiran** [comment]
I don't have a Windows OS to test it out, but I've issued a PR which I think should fix this issue https://github.com/quarkusio/quarkus/pull/8862.

Would it be possible for you to try that change?
