### ISSUE TITLE
Quarkus websockets should be reactive

### ISSUE THREAD

**Issue by flatlanderer** [quarkusio/quarkus#8805]
The Quarkus websockets implementation is not reactive/async compared to Spring WebFlux/Websockets

Here's a detailed description:
https://stackoverflow.com/questions/61384810/quarkus-websockets-does-not-seem-to-be-async-or-just-slow

Reference:
https://quarkus.io/guides/websockets

**Comment by questionaut** [comment]
Here's a test application to showcase the issue:
https://github.com/questionaut/quarkus-websockets-streamer

**Comment by oleksiylukin** [comment]
Quarkus websocket requires Udertow dependency as mandatory but with reactive approach we can use websocket implemented on top of pure Netty. This is more preferable then old-fashioned Websocket API.
Besides it, it could be good idea to explicitly expose Netty API to implement other communications protocols with  Quarkus

**Comment by stuartwdouglas** [comment]
Quarkus websockets are now based on top of pure Netty.
