### ISSUE TITLE
.env file at project root replaced with symbolic link pointing back to the same location

### ISSUE THREAD

**Issue by Nillkki** [quarkusio/quarkus#8812]
**Describe the bug**
When running Quarkus with `mvn quarkus:dev`, `.env` file at project root gets replace with symbolic link pointing to that same location. The behaviour seems to be related to having `workingDir`set in pom.xml.

**Expected behavior**
While running Quarkus in dev mode `.env` should be read from project root.

**Actual behavior**
`.env` file at project root gets replaced with symbolic link pointing to the same location. 

**To Reproduce**
1. Clone example from: https://github.com/Nillkki/quarkus-example
2. Observer that you have `.env` file at the root
3. Run `mvnw quarkus:dev`
4. Observer how `.env` file is replaced with symbolic link pointing to it

**Configuration**
```properties
# Add your application.properties here, if applicable.
com.example.message=${MESSAGE}
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
> Darwin Jenss-MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.6" 2020-01-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
 - GraalVM version (if different from Java): 
> openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
 - Quarkus version or git rev: 1.3.2-Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

> Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
> Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec

- Java version:
> 11.0.6, vendor: AdoptOpenJDK, runtime: >/Library/Java/JavaVirtualMachines/adoptopenjdk-> 11.jdk/Contents/Home
> Default locale: en_GB, platform encoding: UTF-8
> OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

**Additional context**
I am using Quarkus with the Camel extension and for the use case setting `workingDir` seem to be a requirement.

**Comment by geoand** [comment]
Thanks for reporting and figuring out that it's `workingDir` that causes the issue.
