### ISSUE TITLE
Could not mock CDI bean created via @Produces method

### ISSUE THREAD

**Issue by miron4dev** [quarkusio/quarkus#8814]
**Describe the bug**
When I create a bean via `@Produces` method I expect to mock it and inject into `@QuarkusTest`, but I get 

```java
java.lang.RuntimeException: software.amazon.awssdk.services.s3.DefaultS3Client@670a4738 is not a normal scoped CDI bean, make sure the bean is a normal scope like @ApplicationScoped or @RequestScoped
```

**Expected behavior**
A bean should be mocked and injected successfully.

**Actual behavior**
See the stack trace above.

**To Reproduce**
1. Create a config class with a `@Produces` method, e.g. 
```kotlin
@Produces
    fun amazonS3(): S3Client {
        return S3Client.builder()
                .region(Region.of(awsRegion))
                .httpClient(UrlConnectionHttpClient.builder().build())
                .build()
    }
```
2. Inject the mocked client into `@QuarkusTest`

```kotlin
    @InjectMock
    lateinit var s3Client: S3Client
```
3. Execute the test and see the stacktrace above.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin localhost 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
 - Output of `java -version`: java version "1.8.0_231"
 - Quarkus version or git rev: 1.4.0.Final
 - Build tool: Apache Maven 3.6.2

**Additional context**
The issue happens inside `MockSupport#installMock`. It tries to lookup `instance.getClass().getDeclaredMethod("quarkus$$setMock", Object.class)`, but fails because the method doesn't exist.

**Comment by geoand** [comment]
I don't think this is a bug, but has to do with the scope of the produced CDI bean (as mentioned in the error message).

Can you try doing the following please:

```
    @Produces
    @ApplicationScoped
    fun amazonS3(): S3Client {
        return S3Client.builder()
                .region(Region.of(awsRegion))
                .httpClient(UrlConnectionHttpClient.builder().build())
                .build()
    }
```

**Comment by miron4dev** [comment]
@geoand you're right. As I didn't define any scope, I produced a default `@Dependent` bean. 
I added `@ApplicationScoped` for the `@Produces` method and now it works as expected. 
The issue can be closed. Thank you @geoand

**Comment by geoand** [comment]
You are welcome!
