### ISSUE TITLE
Uppercase quarkus.container-image.group causes docker error

### ISSUE THREAD

**Issue by haraldatbmw** [quarkusio/quarkus#8819]
**Describe the bug**
Quarkus extension **quarkus-container-image-docker** fails with uppercase repository name.

```
[INFO] --- quarkus-maven-plugin:1.3.2.Final:build (default) @ simple ---
[INFO] [io.quarkus.container.image.docker.deployment.DockerBuild] Docker daemon found! Version:'19.03.8'
[INFO] [org.jboss.threads] JBoss Threads version 3.0.1.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: C:\git\Back2Code.CampusStudents\__temp\simple\target\simple-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] Building docker image for jar.
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] invalid argument "ABC/simple:1.0.0-SNAPSHOT" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] See 'docker build --help'.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Expected behavior**
Docker image gets built.

**Actual behavior**
Docker error because of uppercase repository name.
Without setting the container-image.group my windows username is used instead,
which is uppercase too and causes the same error.

**To Reproduce**
1. Use quarkus-container-image-docker extension
2. In ``application.properties`` set ``quarkus.container-image.group=ABC``
3. Call maven package: ``mvn clean package -Dquarkus.container-image.build=true``

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Microsoft Windows [Version 10.0.17134.1425]
```
 - Output of `java -version`: 
```
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\devtools\apache-maven-3.6.3\bin\..
Java version: 11.0.6, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-11
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by geoand** [comment]
I'll check it out

**Comment by geoand** [comment]
This isn't actually a bug, using uppercase values seems not be allowed by Jib either: https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/api/ImageReference.java#L64

**Comment by haraldatbmw** [comment]
Without setting the container-image.group my windows username is used instead per default,
which is uppercase too and causes the same error.

So shouldn't be an automatic toLowercase inside the code?

**Comment by gsmet** [comment]
Yeah, if it takes the username by default, we certainly need to lowercase it if uppercase is not allowed.

**Comment by geoand** [comment]
OK yeah, I see your point

**Comment by geoand** [comment]
#8823 should take care of it
