### ISSUE TITLE
RESTEasy: generic type argument class not registered in native image

### ISSUE THREAD

**Issue by PieterjanDeconinck** [quarkusio/quarkus#8849]
**Describe the bug**
When using RESTEasy, generic type argument classes are not registered automatically for native image compilation.

Example - class MyData does not get registered:

> Class:
> ```
> public class ExtendedClass extends BaseClass<MyData> { ... }
> ```
> Resource:
> ```
> @GET
> @Produces(MediaType.APPLICATION_JSON)
> public ExtendedClass getMethod() { ... }
> ```

**Expected behavior**
Generic type argument classes get registered in native image automatically.
Use case is for example a Pagination DTO with a generic type argument, meaning that all the classes that are using it have to be registered explicitly.
User experience will be better if this does not have to be done manually.

**Actual behavior**
Generic type argument classes are not registered automatically and cause an exception at runtime:

`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.test.generics.MyData and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.test.generics.ExtendedClass["data"])`

(example - issue occurs for both Jackson and JSON-B)

Current solutions to register the class:
* `@RegisterForReflection` annotation (not possible when class is in an external dependency)
* adding the class to a `reflection-config.properties` file (works, but less user friendly IMHO)

**To Reproduce**
Reproducer can be found on GitHub:
https://github.com/PieterjanDeconinck/quarkus-generics-reflection-reproducer

**Environment**
 - Quarkus 1.3.2.Final (same on master branch before 1.4.x release)
 - JDK 11

**Additional notes**
* Class should be resolvable (unlike #5420)
* Only used classes should be added for reflection, in order not to defeat the purpose of the optimization
* Original question: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Generic.20type.20argument.20class.20not.20registered.20in.20native.20image

**Comment by geoand** [comment]
Is this still an issue?

**Comment by PieterjanDeconinck** [comment]
Hi, @geoand.
I just updated the reproducer to use the latest available versions, ran the tests and the issue still remains.

Versions:
- Quarkus: 1.12.0.Final
- Docker image: quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11
- GraalVM in this Docker: GraalVM Version 21.0.0 (Java Version 11.0.10+8-jvmci-21.0-b06)

For your information, we are currently registering these kind of classes in the reflection config file, so it's certainly not a blocker issue.

**Comment by geoand** [comment]
#15367 should take care of it.

Thanks for updating the reproducer

**Comment by geoand** [comment]
Also just as an FYI, you don't need to use reflection config files in Quarkus, you can just use `@RegisterForReflection`
