### ISSUE TITLE
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

### ISSUE THREAD

**Issue by questionaut** [quarkusio/quarkus#8859]
When JS client tried to connect to Quarkus websocket handler it throws :

`Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
`

Here's a demo showcasing the bug:
https://github.com/questionaut/quarkus-jsclient-websocket-connect-bug

**Comment by gsmet** [comment]
@stuartwdouglas does it ring a bell?

**Comment by stuartwdouglas** [comment]
Why do you think this will work? You are sending 'null' as a protocol and have not configured the server to understand this 'null' protocol.
