### ISSUE TITLE
Typo in Quarkus 1.4 migration guide

### ISSUE THREAD

**Issue by bobbyphilip** [quarkusio/quarkus#8869]
**In the section Hibernate Search + Elasticsearch (Preview)**
The newly renamed parameter should be quarkus.hibernate-search.elasticsearch.index-defaults.schema-management.required-status and not quarkus.hibernate-search.elasticsearch.index_defaults.schema_management.required_status .
(Underscore replaced by hyphens)
The other parameters which have also been renamed might have to be changed as well

**Comment by gsmet** [comment]
Thanks! It's fixed!
