### ISSUE TITLE
Performance regression of security handling code

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#8879]
**Describe the bug**
On current master, the security handling have a performance regression compare to what I measure last week after the fix to DefaultRoleDecoder.

It appears that security now uses context-propagation, and the cost of context propagation is huge.
Based on the profiles I have, the cost to perform authentication double with context-propagation.

I attached both cpu and allocation profiles, if you zoom into the `QuarkusIdentityProviderManagerImpl.run` method you can see that it allocate at least 50 ` ActiveContextState` objects ... maybe the regression comes from this.

[20200427-master-profiles.zip](https://github.com/quarkusio/quarkus/files/4540110/20200427-master-profiles.zip)

**Comment by loicmathieu** [comment]
I debug this a little more.
In my application, I'm using embedded authentication in dev mode and OAuth2 in production (I assume a lot of people should do the same).
So I have multiple security providers.
And OAuth2 is using an augmentor.

With all this, I discover that Unis are created at each level of the authentication:

- Inside the `HttpSecurityRecorder`
- Inside the `QuarkusIdentityProviderManagerImpl` for each provider and for each augmentor
- Inside the identity provider, in my case the `ElytronPasswordIdentityProvider` 

If we think of what can really block in all these layers, it's the identity provider (can call an external service or access a database).
So I wonder if we can remove some async code (so some Uni) from the other layer.

 @stuartwdouglas WDYT ?

**Comment by stuartwdouglas** [comment]
At the moment anything can block, but you need the flexibility of the async API's to enable full async support. The big problem here is that these are supposed to be cheap to create, but including context propagation changes this.

**Comment by loicmathieu** [comment]
@stuartwdouglas when digging an allocation profile, I saw that a lot of allocations are done loading the transaction manager inside context propagation, I can count multiple hundreds on them.
And it's not allocation free.
Maybe we can do something for this ?
See the attached part of the profile.
![context-propagation-tm](https://user-images.githubusercontent.com/1819009/80795024-aacd6280-8b9b-11ea-83bb-e1379f6ec8da.png)

**Comment by stuartwdouglas** [comment]
We can definitely optimise that.

Stuart

**Comment by gsmet** [comment]
@stuartwdouglas I think this has been fixed?

**Comment by stuartwdouglas** [comment]
Yea, I think it can be closed, there have been a lot of improvements here.
