### ISSUE TITLE
quarkus-smallrye-jwt fails to load RSA key factory in Native mode with Java8 u252 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#8881]
**Describe the bug**
The following smallrye-jwt quickstart [failure](https://github.com/quarkusio/quarkus/issues/6588#issuecomment-619906774) is caused by:
```
The key content is not a valid encoded PEM key: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
	at java.security.KeyFactory.<init>(KeyFactory.java:138)
	at java.security.KeyFactory.getInstance(KeyFactory.java:172)
	at io.smallrye.jwt.KeyUtils.decodePublicKey(KeyUtils.java:211)
```

See also https://github.com/mandrel/graal/issues/12

**Comment by sberyozkin** [comment]
smallrye-jwt quickstart native build will have to be re-enabled once this issue is fixed

**Comment by galderz** [comment]
I don't expect this to be fixed, since the issue goes away using newer GraalVM 19.3.2, where the compiler has been updated to the latest one that might be used to compile the java classes. I'd suggest closing this.
