### ISSUE TITLE
@QuarkusTest @InjectMock @RestClient with @Scheduled looks broken

### ISSUE THREAD

**Issue by apat59** [quarkusio/quarkus#8887]
**Describe the bug**
attached is the simplified testcase.
Basic idea, we have a @Scheduled job which uses a @RestClient.

For tests, we want to mock the RestClient @TestClient.
The really first job execution is not mocked.
It seems mocking happens too late, within ms late, next job executions are fine.

    @InjectMock
    @RestClient
    SomeRestClient mockedClient;

    @Inject
    DummyScheduler scheduler;

    @Inject
    DummyBean bean;

    @Test
    public void mockedViaScheduler () throws InterruptedException {
        Mockito.when(mockedClient.getName()).thenReturn("I'm mock");
        // this will let the job executes many times
        Thread.sleep(6000);
        Set<String> names = scheduler.getNames();
        LOGGER.debug(names.size());
        for (String name : names)
            LOGGER.debug(name);
        // we only want "I'm mock" value, but we'll get 'OK' at the first job execution.
        Assertions.assertEquals(1, names.size());
    }

see attached project
[schedulermockfail.zip](https://github.com/quarkusio/quarkus/files/4541385/schedulermockfail.zip)

Some words about the test, I expect only one same value returned by the RestClient SomeRestClient.getName.
It is mocked to "I'm mock". Instead I'm getting "I'm mock" + "OK" which is returned by
org.acme.SomeRestClient/mp-rest/url=https://requestinspector.com/inspect/01e60qvymh7jj2wdb0nkp6whyy

**Expected behavior**
I expect the @Scheduled to always use the mocked @RestClient 

**Actual behavior**
The really 1st job trigerred uses the actual bean, not the mock.

**To Reproduce**
See attached project

**Configuration**
```properties
# Add your application.properties here, if applicable.
# /The @RestClient uses a  dummy fake endpoint which always returns 200 OK.
org.acme.SomeRestClient/mp-rest/url=https://requestinspector.com/inspect/01e60qvymh7jj2wdb0nkp6whyy
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: fedora 29
 - Output of `java -version`: 11
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.5, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-11.0.5.10-0.fc29.x86_64
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "5.3.11-100.fc29.x86_64", arch: "amd64", family: "unix"

**Comment by apat59** [comment]
Stuart Douglas answered and this is the expected behaviour.
https://groups.google.com/forum/#!msg/quarkus-dev/ZjDgCRMFP9Y/wh7gDJ9oAwAJ

Sorry for false entry

**Comment by geoand** [comment]
As explained by @stuartwdouglas on the mailing list, this happens because the mock comes into play only for the duration of the test, so if the scheduler runs outside of the test run, you don't get a mock, but the regular bean

**Comment by stuartwdouglas** [comment]
Maybe we need some kind of scheduler test framework, so they can be enabled/disabled on a per test basis.

**Comment by geoand** [comment]
I could see that being useful
