### ISSUE TITLE
Defining the http root path broken starting with Quarkus version 1.4.0.Final

### ISSUE THREAD

**Issue by heike2718** [quarkusio/quarkus#8888]
**Describe the bug**
With Quarkus <= 1.3.2.Final it was possible to define the http root in two ways:

- define quarkus.http.root-path in application.properties
- add a subclass of javax.ws.rs.core.Application and annotating it with javax.ws.rs.ApplicationPath

Using either of these posibilities the application fails to startup with 1.4.1.Final or later. See [reproducer](https://github.com/heike2718/quarkus-eclipse-reproducer)

**Expected behavior**
It should be possible to define a custom http-root

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
described in [reproducer](https://github.com/heike2718/quarkus-eclipse-reproducer)

**Environment (please complete the following information):**
 - Output of `java -version`: 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

 - Quarkus version or git rev: 
1.4.0.Final or 1.4.1.Final
 - Build tool mvn

**Comment by gsmet** [comment]
@heike2718 you need to upgrade the platform to 1.4.1.Final too:
https://github.com/heike2718/quarkus-eclipse-reproducer/blob/master/quarkus-hello/pom.xml#L20

**Comment by heike2718** [comment]
@gsmet 

Thanks and sorry for wasting your time.

**Comment by gsmet** [comment]
No worries! Thanks for the feedback!
