### ISSUE TITLE
[CI] - Hazelcast Client extension + Quarkus Snapshots

### ISSUE THREAD

**Issue by pivovarit** [quarkusio/quarkus#8893]
This issue will be open and closed dependent on the state of http://github.com/hazelcast/quarkus-hazelcast-client building against Quarkus master snapshot.

If you have interest in being notified of this subscribe to the issue.

**Comment by pivovarit** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/hazelcast/quarkus-hazelcast-client/actions/runs/102154404

**Comment by geoand** [comment]
Looks like a change we made, broke the extension. https://github.com/quarkusio/quarkus/pull/9231 should fix it
