### ISSUE TITLE
Allow to Veto/Ignore dependent Jars in regards to Arc/CDI

### ISSUE THREAD

**Issue by 38leinaD** [quarkusio/quarkus#8905]
**Description**
My Auarkus application depends on an external JAR-file (from the customer) that contains some POJOs i need to reference in my application. The JAR-file also contains CDI beans and a beans.xml. I do not use the CDI beans in my application but because Arc resolves the DI during build-time, I get errors about "Unsatisfied dependency" from Arc during the build. This is because the CDI beans in the external Jar themself inject other classes that are not on the classpath and thus cannot be resolved.
I think it would be useful to have a way of depending on JAR-files that have a beans.xml but tell Quarkus/Arc to ignore/veto them.

**Implementation Idea**
In case quarkus has something like this, it would be good to write the dependencies (groupid:artifactid) in some meta-file that is read during the build by the Arc BuildItems and ignores the listed jars.
(if this is reasonably simple and someone could point me in the right direction where/how this is possible, I could give it a shot myself)

**Comment by geoand** [comment]
We now have `quarkus.class-loading.removed-artifacts` which can be configured in an application in order to exclude entire dependencies from taking effect.
