### ISSUE TITLE
Scheduler - add config property to disable the scheduler completely

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#8913]
This could be useful for running tests.

**Comment by geoand** [comment]
:+1

**Comment by geoand** [comment]
@mkouba perhaps a good first issue?

**Comment by adrianfiedler** [comment]
Hi @geoand. I would like to take a look on this. 
Should this config be fixed at build time? Or should it be overridable at runtime? For me it's not clear if the config should just intercept invocations, or really prevent them from being created.

**Comment by geoand** [comment]
I haven't look at the implementation much, but ideally it should remove as much trace of scheduler as possible.

As for build-time vs runtime, ideally it would be runtime, but if that's not easy to do, I think we could live with build time.

**Comment by mkouba** [comment]
So first of all I think that it should a _runtime_ config property. Speaking of the functionality we have two options: (1) boolean flag to indicate wheter the scheduler should be started or not, (2) property to delay the start of the scheduler with no delay by default (this would be more flexible but probably not very intuitive).

Therefore, I'd go with a _simple boolean runtime config property_. @geoand WDYT?

IMPL. NOTES:

- we need to modify both the `io.quarkus.scheduler.runtime.SimpleScheduler` and the `io.quarkus.quartz.runtime.QuartzScheduler`
- `io.quarkus.scheduler.runtime.SchedulerConfig` is BUILD_AND_RUN_TIME_FIXED; we'll need a different config class for RUN_TIME phase (you can inject the config bean in the scheduler beans)

**Comment by geoand** [comment]
> Therefore, I'd go with a _simple boolean runtime config property_. @geoand WDYT?
 
 +1

**Comment by machi1990** [comment]
> IMPL. NOTES:
> 
> * we need to modify both the `io.quarkus.scheduler.runtime.SimpleScheduler` and the `io.quarkus.quartz.runtime.QuartzScheduler`

Should the QuartzScheduler be created at least? Since it is a bean and can actually be injected?

**Comment by mkouba** [comment]
@machi1990 The `QuartzScheduler` bean itself will exist. However, an injection point for `org.quartz.Scheduler` will be `null`.

**Comment by machi1990** [comment]
Gotcha, just wanted to be sure if we want it to be `null`.

**Comment by mkouba** [comment]
@machi1990 So we should probably throw an ISE instead.

@aalmiray ^ another impl note ;-).

**Comment by adrianfiedler** [comment]
> So first of all I think that it should a _runtime_ config property. Speaking of the functionality we have two options: (1) boolean flag to indicate wheter the scheduler should be started or not, (2) property to delay the start of the scheduler with no delay by default (this would be more flexible but probably not very intuitive).
> 
> Therefore, I'd go with a _simple boolean runtime config property_. @geoand WDYT?
> 
> IMPL. NOTES:
> 
> * we need to modify both the `io.quarkus.scheduler.runtime.SimpleScheduler` and the `io.quarkus.quartz.runtime.QuartzScheduler`
> * `io.quarkus.scheduler.runtime.SchedulerConfig` is BUILD_AND_RUN_TIME_FIXED; we'll need a different config class for RUN_TIME phase (you can inject the config bean in the scheduler beans)

@mkouba I added a new RuntimeConfiguration for phase RUN_TIME and tried to inject it directly into SimpleScheduler as you said. But somehow I only get Unsatisfied dependency errors. I see the builtime config is passing its values trough SchedulerContext. Should I do the same?

**Comment by mkouba** [comment]
> But somehow I only get Unsatisfied dependency errors.

@adrianfiedler this should work and it's a preferred solution. I'll add some comments to your PR.

**Comment by mkouba** [comment]
@adrianfiedler it would be great if you could share the version with config root injection so that we could investigate the unsatisfied dependency errors.
