### ISSUE TITLE
Injection of JWT available in OIDC implementation

### ISSUE THREAD

**Issue by paulkmoore** [quarkusio/quarkus#8915]
**Description**
When using the OIDC for Services for the first time, I was unaware that the JsonWebToken could be injected and used (per the JWT for RBAC documentation). 

**Implementation ideas**
I suggest that a section is added to the documentation at `quarkus/docs/src/main/asciidoc/security-openid-connect.adoc` to include clarification that `@Inject JsonWebToken jwt;` can be relied upon to provide access to the JWT properties.

This was discussed here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Keycloak.20integration

I'm happy to draft something if useful

**Comment by sberyozkin** [comment]
@paulkmoore I agree, I thought there was an updated example there, along the lines of the `web-app` application quickstart, https://github.com/quarkusio/quarkus-quickstarts/blob/master/security-openid-connect-web-authentication-quickstart/src/main/java/org/acme/security/openid/connect/web/authentication/TokenResource.java.

But for simple cases dealing with `SecurityIdentity` is enough.

Can you please add a subsection, perhaps named as "Accessing JWT claims", under https://quarkus.io/guides/security-openid-connect#writing-the-application ? This section can start with "If you need to access JWT token claims then you can do this or that...", please have a look at this [test resource](https://github.com/quarkusio/quarkus-quickstarts/blob/master/security-openid-connect-web-authentication-quickstart/src/main/java/org/acme/security/openid/connect/web/authentication/TokenResource.java). This is used for the `web-app`, but the following would work for `service`: 

```
@Inject
JsonWebToken accessToken;

@Inject
AccessTokenCredential accessTokenCredential;
```

`AccessTokenCredential` will only hold a raw token, see this [check](https://github.com/quarkusio/quarkus/blob/master/integration-tests/oidc-code-flow/src/main/java/io/quarkus/it/keycloak/ProtectedResource.java#L90) - if all what is needed to propagate the raw token then `AccessTokenCredential` is enough.

We don't need to rewrite the quickstart, as some users may not even need it. But indeed providing some extra information would be useful.

Thanks

**Comment by sberyozkin** [comment]
Hi @paulkmoore I'll a similar section to the OIDC `web-app` page. Perhaps for simplicity, lets cover only `JsonWebToken`

**Comment by sberyozkin** [comment]
@paulkmoore That is fine, I believe it is sufficient, I've personally have not seen other contexts used. (These are the 2 contexts which MP JWT 1.2 will formally support so should be enough)

**Comment by sberyozkin** [comment]
@paulkmoore FYI, here is what I've added to the `web-app` page, #8955 (see the section about the claims). I don't we have mentioned the contexts before, so lets start it with your PR :-). Please add a small code fragment as is done in #8955 (show the injected jwt token and have some method returning the value of some claim).

Thanks
