### ISSUE TITLE
JsonbSerializer doesn't work with extended generic class

### ISSUE THREAD

**Issue by benneq** [quarkusio/quarkus#8918]
**Describe the bug**
When extending a class that implements `JsonbSerializer` I get a `java.lang.ClassCastException`:
```
class org.acme.Container cannot be cast to class org.acme.Foo
```
But when also adding `implements JsonbSerializer` it works as expected. (Example Code below)

**Expected behavior**
Should work without having to add an additional `implements JsonbSerializer`, because the super class already has it.

**Actual behavior**
I get a `java.lang.ClassCastException`. It looks like it's trying to serialize an entirely different class with this serializer.

**To Reproduce**
```java
public class Container {
  public Foo foo;
}

public class Foo {
  public String value;
  public String getValue() { return value; }
}

public abstract class AbstractSerializer<T extends Foo> implements JsonbSerializer<T> {
  public void serialize(T obj, JsonGenerator generator, SerializationContext ctx) {
    generator.write(Base64.getEncoder().encodeToString(obj.getValue().getBytes()));
  }
}

// throws ClassCastException:
public class FooSerializer extends AbstractSerializer<Foo> { }

// works fine:
// public class FooSerializer extends AbstractSerializer<Foo> implements JsonbSerializer<Foo> { }

@Singleton
public class FooJsonbConfigCustomizer implements JsonbConfigCustomizer {
  public void customize(JsonbConfig config) {
    config.withSerializers(new FooSerializer());
  }
}

@Path("")
public class MyResource {
  @GET @Produces(MediaType.APPLICATION_JSON)
  public Container test() {
    Container c = new Container();
    c.foo = new Foo();
    c.foo.value = "test";
    return c;
  }
}
```

**NOTE:** The error does **not** occur when returning `Foo` from `test()`. It only happens when it's nested.

**Configuration**
```properties
# empty
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: macOS Catalina 10.15.4, Darwin Kernel Version 19.4.0
 - Output of `java -version`: 11.0.7
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.4.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Comment by geoand** [comment]
@aguibert want to take a look at this?

**Comment by aguibert** [comment]
@geoand yep I can look into this one, go ahead and assign to me

**Comment by geoand** [comment]
Done

**Comment by geoand** [comment]
Closing as this is (was?) a Yasson issue
