### ISSUE TITLE
Banner with default_banner.txt not working

### ISSUE THREAD

**Issue by fjsventura** [quarkusio/quarkus#8919]
**Describe the bug**
With a file named default_banner.txt in the classpath, if I run in dev mode the banner is overrided as expected but if I run with java -jar it is not.

**Expected behavior**
The custom banner should appear both in dev mode and java -jar.

**Actual behavior**
Running the jar only shows the default banner, unless I set the property quarkus.banner.path to another name.

**To Reproduce**
1. Add a custom banner to the classpath named default_banner.txt 
2. Build the project
3. Run the project as a java application

**Configuration**
```properties
Not applicable to reproduce the behaviour

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux {user} 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu219.10)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu219.10, mixed mode, sharing)
 - GraalVM version (if different from Java): NA
 - Quarkus version or git rev: 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven-3.6.3
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-46-generic", arch: "amd64", family: "unix"

**Additional context**
The problem above only appeared after updating from 1.3.1.Final to 1.4.1.Final

**Comment by geoand** [comment]
@aloubyansky if you haven't started working on this, I can look into it

**Comment by aloubyansky** [comment]
Sure, I'll working on later tonight.

**Comment by aloubyansky** [comment]
I just wanted to collect regressions to make sure I don't miss any of those.

**Comment by aloubyansky** [comment]
It could be the order of the jars on the CP

**Comment by aloubyansky** [comment]
Although, there is a prioritizing logic, affair.

**Comment by geoand** [comment]
Okay, I'll check it out later on.

**Comment by geoand** [comment]
This does seem to have broken because of the ordering of the CP, but frankly the implementation should be made better to not depend on it - or at least not depend on the order of the quarkus jar that contains the default banner. I'm guilty of making that the case.

I'll update the implementation to be more robust and provide a PR.

**Comment by aloubyansky** [comment]
Excellent. Thanks!

**Comment by geoand** [comment]
#8926 should take care of it
