### ISSUE TITLE
JsonbSerializer order priority when using inheritance / polymorphism

### ISSUE THREAD

**Issue by benneq** [quarkusio/quarkus#8925]
**Describe the bug**
When adding multiple JsonbSerializers of the same class hierarchy, the executed serializer is chosen randomly (can change with each application restart).

**Expected behavior**
Have a JsonbSerializer hierarchy which prioritizes the most precise matching class. So if we have a `FooSerializer` for `Foo` and a `BarSerializer` for `Bar extends Foo`, then serializing `Bar` should always prefer `BarSerializer`, because it's the most exact match in the class hierarchy.

**Actual behavior**
It's totally random.

**To Reproduce**
```java
public class Foo { }

public class Bar extends Foo { }

public class FooSerializer implements JsonbSerializer<Foo> {
  public void serialize(Foo obj, JsonGenerator generator, SerializationContext ctx) {
    System.out.println("FOO SERIALIZER");
    generator.write("foo");
  }
}

public class BarSerializer implements JsonbSerializer<Bar> {
  public void serialize(Bar obj, JsonGenerator generator, SerializationContext ctx) {
    System.out.println("BAR SERIALIZER");
    generator.write("bar");
  }
}

class MyJsonbConfigCustomizer implements JsonbConfigCustomizer {
  public void customize(JsonbConfig config) {
    config.withSerializers(new FooSerializer(), new BarSerializer());
  }
}

@Path("/test")
public class TestResource {
  @GET
  public Bar test() { ... }
}
```

**Configuration**
```properties
# empty
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: macOS Catalina 10.15.4, Darwin Kernel Version 19.4.0
 - Output of `java -version`: 11.0.7
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.4.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Additional context**
I'm not sure if this really belongs to Quarkus, or it's better suited for RestEasy or Yasson Bug Tracker. Already created this issue at EclipseEE JsonB BugTracker: https://github.com/eclipse-ee4j/jsonb-api/issues/234

**Comment by gsmet** [comment]
@aguibert how are the priorities supposed to be managed?

**Comment by aguibert** [comment]
The spec doesn't say anything about a priority, but it should certainly be deterministic regardless of priorities. I agree with @benneq that the most specific serializer makes sense. 

@gsmet go ahead and assign to me and I can investigate further

**Comment by aguibert** [comment]
Fix has been delivered in Yasson here: https://github.com/eclipse-ee4j/yasson/pull/409
It will be available in the next release

**Comment by geoand** [comment]
The release that includes the fix has since been included in Quarkus
