### ISSUE TITLE
Access to public field returns null for Hibernate entity lazy-loaded from polymorphic toOne association

### ISSUE THREAD

**Issue by jrongs** [quarkusio/quarkus#8932]
**Describe the bug**
Since release 1.3.2.Final, I noticed hibernate lazy load is no long working properly in my project.  here is the hierarchy of the entities:

```
@MappedSuperclass
public abstract class EntityBase extends PanacheEntityBase {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;
}

@Entity
public class EntityA extends EntityBase  {
   @Column(nullable = false)
    public String name;
}

@Entity
**@Inheritance(strategy = InheritanceType.JOINED)**
public class EntityB extends EntityBase  {
	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	public EntityA a;
}

@Entity
public class EntityC  extends EntityBase  {
	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	public EntityB b;
        @Column(nullable = false)
        public String uuid;
}

and I'm getting NPE when accessing the entities this way:

EntityC  c= EntityC .find("uuid=?1", id).firstResult();

if (c.b.a.name.equals("") { ... 
}
```

c.b.a is null, because c.b is a hibernate proxy and it is not getting lazy loaded.   everything worked fine before 1.3.2.Final.

**Expected behavior**
Hibernate lazy load works for all entities.

**Actual behavior**
Hibernate lazy load not working for entities annotated with Inheritance

**To Reproduce**
see description above. 

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.url = jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
quarkus.datasource.driver = com.mysql.cj.jdbc.Driver
quarkus.datasource.username = usr
quarkus.datasource.password = pwd

quarkus.hibernate-orm.database.generation = none
quarkus.hibernate-orm.log.sql = true
quarkus.hibernate-orm.dialect = org.hibernate.dialect.MySQLDialect
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux orchid 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`:   java 11.0.1 2018-10-16 LTS
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.3.2.Final and 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by jrongs** [comment]
looks like lazy load is not getting triggered when the entity is annotated with:
`@Inheritance(strategy = InheritanceType.JOINED)`

**Comment by gsmet** [comment]
@jrongs could you prepare a simple Maven project reproducing the issue?

/cc @Sanne @dreab8

**Comment by jrongs** [comment]
@gsmet   thanks for the quick reply.  I have attached a simple maven project to demonstrate the issue.  

download, extract, and run the project: 
./mvnw quarkus:dev

then run the curl:   
curl -v -w "\n" localhost:8080/hello

you'll get the following message:
name: null

in the quarkus console, you'll notice that lazy load never triggered on the "Content" entity:

```
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/4552811/code-with-quarkus.zip)

Hibernate: 
    select
        folder0_.id as id1_1_0_,
        folder0_.content_id as content_2_1_0_ 
    from
        folder folder0_ 
    where
        folder0_.id=?

```
working as expected if I remove the following line from the "Content" entity:

`@Inheritance(strategy = InheritanceType.JOINED)` 

curl command returns:
name: it is working!

and we get the following the console out:

```
Hibernate: 
    select
        folder0_.id as id1_1_0_,
        folder0_.content_id as content_2_1_0_ 
    from
        folder folder0_ 
    where
        folder0_.id=?
Hibernate: 
    select
        content0_.id as id1_0_0_,
        content0_.name as name2_0_0_ 
    from
        content content0_ 
    where
        content0_.id=?

```

please let me know if you need more details to troubleshoot.  Thanks!

**Comment by darmanovic** [comment]
I've similar problem.
```java
@Entity
public class Nalog extends PanacheEntityBase {
      @Id
      public Long id;
...
      @ManyToOne(fetch = FetchType.LAZY)
      public Zaposleni zaposleni;
...
```

```java
@Entity
public class Zaposleni extends PanacheEntityBase {
	@Id
	public Long id;
...
        @OneToMany(fetch = FetchType.LAZY, mappedBy = "zaposleni")
	public List<Nalog> nalog;

	@ManyToOne(fetch = FetchType.LAZY)
	public Pozicija pozicija;
...
```

```java
@Entity
public class Pozicija extends PanacheEntityBase {
...
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pozicija")
	public List<Zaposleni> zaposleni;
...
```

Hibernate SQL log:
```log
Hibernate: 
    select
        distinct nalog0_.id as id1_2_0_,
        zaposleni1_.id as id1_8_1_,
        nalog0_.aktivno as aktivno2_2_0_,
        nalog0_.broj as broj3_2_0_,
...
        zaposleni1_.createdAt as createda2_8_1_,
....
    from
        Nalog nalog0_ 
    left outer join
        Zaposleni zaposleni1_ 
            on nalog0_.zaposleni_id=zaposleni1_.id 
    where
        nalog0_.aktivno=true 
        and nalog0_.obrisano=false limit ?
Hibernate: 
    select
        pozicija0_.id as id1_4_0_,
        pozicija0_.createdAt as createda2_4_0_,
        pozicija0_.naziv as naziv3_4_0_,
        pozicija0_.obrisano as obrisano4_4_0_ 
    from
        Pozicija pozicija0_ 
    where
        pozicija0_.id=?

```

Query
```
find("SELECT DISTINCT n FROM Nalog n LEFT JOIN FETCH n.zaposleni WHERE n.aktivno IS TRUE AND n.obrisano IS FALSE").range(od, do)
				.list()
```

**Comment by jrongs** [comment]
still experiencing the same issue in release 1.10.5.Final.  we did find a workaround by manually define the getters and setters on entities in the inheritance hierarchy:

 @MappedSuperclass
public abstract class EntityBase extends PanacheEntityBase {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;
    
    **public Long getId() {
        return id;
    }**
}

@Entity
** @Inheritance(strategy = InheritanceType.JOINED)**
public class File extends EntityBase  {
       @Column(nullable = false)
	public String name;
	
	**public String getName() {
	    return name;
	}
	public void setName(String name) {
	    this.name = name;
	}**
}

@Entity
public class Image extends File {
    @Column(nullable = false)
    public int size;
    
    **public int getSize() {
        return size;
    }
    public void setSize(int size) {
        this.size = size;
    }**
}

@Entity
public class Folder extends BaseEntity {
    @ManyToOne(fetch=FetchType.Lazy)
    public File file;
}

with those getters/settings, everything works as expected:

Folder f = Folder.findById(1L);
System.out.println(f.file.name); //we get null without the getter (File.getName()).  

Hope this helps.

**Comment by HonoluluHenk** [comment]
Maybe related to this Hibernate-Bug?
https://hibernate.atlassian.net/browse/HHH-14549
In case this is the cause: just bump hibernate to 5.4.31

**Comment by dan-dr** [comment]
Encountered this on `1.13.7 Final`. same with @jrongs , i can circumvent it with getters, but really don't want to... any other solution?

**Comment by yrodiere** [comment]
The problem appears to be in Hibernate ORM itself. I created https://hibernate.atlassian.net/browse/HHH-15090 and will handle this upstream.
