### ISSUE TITLE
IntelliJ hangs when debugging quarkus quickstart project

### ISSUE THREAD

**Issue by martinformanko** [quarkusio/quarkus#8940]
**Describe the bug**
When I create debug running configuration for maven goal `quarkus:dev` in IntelliJ for the project microprofile-metrics-quickstart and run it, it hangs when trying to close it. Breakpoints seem to be also ignored. I am not sure if this is really quarkus related, I just wanted to ask, if anybody can reproduce. It may be, this started to occur after IntelliJ update to 2020.1

```
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< org.acme:microprofile-metrics-quickstart >--------------
[INFO] Building microprofile-metrics-quickstart 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.4.1.Final:dev (default-cli) @ microprofile-metrics-quickstart ---
[INFO] Nothing to compile - all classes are up to date
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-04-29 08:43:33,685 INFO  [io.quarkus] (Quarkus Main Thread) microprofile-metrics-quickstart 1.0-SNAPSHOT (powered by Quarkus 1.4.1.Final) started in 1.391s. Listening on: http://0.0.0.0:8080
2020-04-29 08:43:33,694 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-04-29 08:43:33,694 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, smallrye-metrics]
```

**Expected behavior**
The debugger is attached and debug session quits when I click Stop. 

**Actual behavior**
The Java process does not quit after stopping, it needs to be killed with task manager.

**To Reproduce**
1. Download IntelliJ 2020.1 Ultimate
2. Checkout quickstarts project
3. Create debug running configuration on maven goal `quarkus:dev`
4. Start the app and stop it

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18363.778]
 - Output of `java -version`: OpenJDK 64-Bit GraalVM CE 19.3.0 (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.2

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Hi,

What you are trying to do won't actually work becase `mvn quarkus:dev` launches another different java process for the application (and this is the process you want to connect a debugger to - this is a similar situation to what happens when the Maven surefire plugin is executed).
So you don't want to debug Maven, but instead the java process that the Quarkus Maven plugin launches.
To do that you need to run `mvn quarkus:dev -Dsuspend` and then connect use create a `Remote` configuration in `IntelliJ` which you launch (debug).

**Comment by eriknyk** [comment]
@martinformanko  this plugin is very helpful https://plugins.jetbrains.com/plugin/14242-quarkus-integration
