### ISSUE TITLE
support/warn if KUBECONFIG has multiple paths

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#8946]
**Describe the bug**
when having KUBECONFIG like:

```
echo $KUBECONFIG
/Users/max/.kube/config:/Users/max/.kube/kubeconfig:/Users/max/Downloads/openshift-install-mac-4.2.2/myinstall/auth/kubeconfig
```

kubernetes client related operations fails siliently and you get "Unknown host kubernetes.default.svc: nodename nor servname provided, or not known"

**Expected behavior**
read the working KUBECONFIG or at least warn.

**Actual behavior**

**Comment by geoand** [comment]
@iocanel are there any utilities in the Kubernetes Client that deal with this or should we just roll something up in Quarkus?

**Comment by iocanel** [comment]
No, this is a limitation of the client and needs to be fixed there I am afraid.

**Comment by geoand** [comment]
Are you going to take care of it, or should we engadge the DevTools folks?

**Comment by iocanel** [comment]
Let's ask Rohan or Marc if the can take care of it.

**Comment by geoand** [comment]
@rohanKanojia can you take a look please?

**Comment by rohanKanojia** [comment]
We will take care of it. Thanks for letting us know

**Comment by geoand** [comment]
Great, thanks

**Comment by manusa** [comment]
What would the preferred behavior be?

As of now I see a couple of corner cases to "read the working KUBECONFIG":
- More than one configuration works
- None works

Maybe pick the first one and show a WARNING like "Detected several configurations in KUBECONFIG environment, using ${firstConfiguration}"

**Comment by geoand** [comment]
> Maybe pick the first one and show a WARNING like "Detected several configurations in KUBECONFIG environment variable, using ${firstConfiguration}"

I think that is a reasonable way to move forward. Also perhaps a message on how users can get rid of the multiple configurations would be nice.

**Comment by manusa** [comment]
We just released https://github.com/fabric8io/kubernetes-client/releases/tag/v4.10.0

[Warning](https://github.com/fabric8io/kubernetes-client/blob/509a2e857353c1586373b09d90ab2c167febbd64/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L476) should be visible in this new version.

**Comment by geoand** [comment]
Excellent!

**Comment by geoand** [comment]
Closing as the client already addressed this issue
