### ISSUE TITLE
S2i build and self signed certificates

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#8947]
**Describe the bug**

Performing an s2i build using `mvn clean install -Dquarkus.container-image.build=true` can result is certificate related exceptions, when the server has a self signed certificate.

**Expected behavior**
Build to be triggered or display a warning on how to trust the certificates.

**Actual behavior**

```
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

*Note* We have something similar in the deploy process: https://github.com/quarkusio/quarkus/blob/55cae6828e6b2d41399786654ee026aa42e0910b/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesDeploy.java#L44

We should also apply this idea for s2i builds too.

**Comment by geoand** [comment]
@iocanel the exceptions should have been handled: https://github.com/quarkusio/quarkus/blob/f3f85159afe3cffccb8637f6591a791cc945644c/extensions/kubernetes-client/deployment-internal/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientErrorHanlder.java

So obviously there is some kind of issue there :)

**Comment by geoand** [comment]
Is this still an issue @iocanel ?

**Comment by geoand** [comment]
Let's close for now. We can reopen if it still is an issue
