### ISSUE TITLE
Error: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by smoell** [quarkusio/quarkus#8952]
**Describe the bug**
My Lambda based [example](https://github.com/aws-samples/aws-quarkus-demo/tree/master/lambda) works fine using Quarkus 1.2.1, but after switching to 1.4.1, I receive the error the trustAnchors parameter must be non-empty

**Expected behavior**
Working example without the trustAnchors parameter must be non-empty error

**Actual behavior**

START RequestId: 40cd7978-18ce-41d9-8ef3-07c778d7f562 Version: $LATEST
--
  | __  ____  __  _____   ___  __ ____  ______
  | --/ __ \/ / / / _ \| / _ \/ //_/ / / / __/
  | -/ /_/ / /_/ / __ \|/ , _/ ,< / /_/ /\ \
  | --\___\_\____/_/ \|_/_/\|_/_/\|_\|\____/___/
  | 2020-04-29 12:43:16,445 INFO  [io.quarkus] (main) LambdaQuarkus 1.0-SNAPSHOT (powered by Quarkus 1.4.1.Final) started in 0.178s.
  | 2020-04-29 12:43:16,452 INFO  [io.quarkus] (main) Profile prod activated.
  | 2020-04-29 12:43:16,452 INFO  [io.quarkus] (main) Installed features: [amazon-lambda, cdi, dynamodb]
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) javax.net.ssl.trustStore: /cacerts
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.specification.version: 11
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) org.graalvm.nativeimage.kind: executable
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) vertx.cacheDirBase: /tmp/vertx
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) sun.jnu.encoding: ANSI_X3.4-1968
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.class.path:
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.net.preferIPv4Stack: true
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) user.name: sbx_user1051
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) path.separator: :
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.vm.vendor: Oracle Corporation
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) os.version: 4.14.165-102.205.amzn2.x86_64
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.endorsed.dirs:
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) file.encoding: UTF-8
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.vendor.url: https://www.graalvm.org/
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.vm.name: Substrate VM
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.vm.specification.version: 11
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) os.name: Linux
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) javax.net.ssl.trustAnchors: /libsunec.so
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) jdk.lang.Process.launchMechanism: FORK
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.io.tmpdir: /tmp
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.version: 11.0.6
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) user.dir: /var/task
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) user.home: /home/sbx_user1051
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) os.arch: amd64
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.specification.vendor: Oracle Corporation
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.vm.specification.name: Java Virtual Machine Specification
  | 2020-04-29 12:43:16,459 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) org.graalvm.nativeimage.imagecode: runtime
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) io.netty.allocator.maxOrder: 1
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) file.separator: /
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) line.separator:
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.util.logging.manager: org.jboss.logmanager.LogManager
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.library.path:
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.vendor: Oracle Corporation
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.vm.specification.vendor: Oracle Corporation
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.specification.name: Java Platform API Specification
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.vm.version: GraalVM 19.3.1 CE
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.ext.dirs:
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) java.class.version: 55.0
  | 2020-04-29 12:43:16,460 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) [{resource: /users,path: /users,httpMethod: POST,headers: {Accept=*/*, CloudFront-Forwarded-Proto=https, CloudFront-Is-Desktop-Viewer=true, CloudFront-Is-Mobile-Viewer=false, CloudFront-Is-SmartTV-Viewer=false, CloudFront-Is-Tablet-Viewer=false, CloudFront-Viewer-Country=US, content-type=application/json, Host=0t3q470mzk.execute-api.eu-west-1.amazonaws.com, User-Agent=curl/7.61.1, Via=2.0 32c5b7040885724e78019cc31f0ef3e9.cloudfront.net (CloudFront), X-Amz-Cf-Id=rF5W-gqZAfF3d8GmUBhR7Q97GgHk71xBLNVBTDtv_O_O-BwZB5-yyg==, X-Amzn-Trace-Id=Root=1-5ea97663-dfa302c08973f3ba33c303c0, X-Forwarded-For=18.234.206.69, 70.132.60.69, X-Forwarded-Port=443, X-Forwarded-Proto=https},multiValueHeaders: {Accept=[*/*], CloudFront-Forwarded-Proto=[https], CloudFront-Is-Desktop-Viewer=[true], CloudFront-Is-Mobile-Viewer=[false], CloudFront-Is-SmartTV-Viewer=[false], CloudFront-Is-Tablet-Viewer=[false], CloudFront-Viewer-Country=[US], content-type=[application/json], Host=[0t3q470mzk.execute-api.eu-west-1.amazonaws.com], User-Agent=[curl/7.61.1], Via=[2.0 32c5b7040885724e78019cc31f0ef3e9.cloudfront.net (CloudFront)], X-Amz-Cf-Id=[rF5W-gqZAfF3d8GmUBhR7Q97GgHk71xBLNVBTDtv_O_O-BwZB5-yyg==], X-Amzn-Trace-Id=[Root=1-5ea97663-dfa302c08973f3ba33c303c0], X-Forwarded-For=[18.234.206.69, 70.132.60.69], X-Forwarded-Port=[443], X-Forwarded-Proto=[https]},requestContext: {accountId: 116657585477,resourceId: cpv6th,stage: prod,requestId: 9427efc8-0ee2-471e-88eb-f17ca9753689,identity: {sourceIp: 18.234.206.69,userAgent: curl/7.61.1,},resourcePath: /users,httpMethod: POST,apiId: 0t3q470mzk,path: /prod/users,},body: {"userName":"hmueller", "firstName":"Hans", "lastName":"Mueller", "age":"35"},isBase64Encoded: false}] Processed data
  | 2020-04-29 12:43:16,468 INFO  [com.ama.exa.ProcessingLambda] (Lambda Thread) POST: UserPojo{userId=c41c2921-b68d-4bc0-b319-b975823befce, userName='hmueller', firstName='Hans', lastName='Mueller', age=35}
  | 2020-04-29 12:43:19,331 ERROR [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread) Failed to run lambda: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  | at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.handleThrownException(RetryableStage.java:137)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:95)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:63)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:43)
  | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
  | at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:81)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:61)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:43)
  | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
  | at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:198)
  | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:122)
  | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:148)
  | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:102)
  | at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
  | at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
  | at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.putItem(DefaultDynamoDbClient.java:2451)
  | at io.quarkus.dynamodb.runtime.DynamodbClientProducer_ProducerMethod_client_15a968126f29bfeefe628e806398394e57fc3411_ClientProxy.putItem(DynamodbClientProducer_ProducerMethod_client_15a968126f29bfeefe628e806398394e57fc3411_ClientProxy.zig:1061)
  | at com.amazon.example.service.UserService.add(UserService.java:39)
  | at com.amazon.example.service.UserService_ClientProxy.add(UserService_ClientProxy.zig:369)
  | at com.amazon.example.ProcessingLambda.handleRequest(ProcessingLambda.java:114)
  | at com.amazon.example.ProcessingLambda.handleRequest(ProcessingLambda.java:36)
  | at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:148)
  | at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:66)
  | at java.lang.Thread.run(Thread.java:834)
  | at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
  | at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
  | Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  | at sun.security.ssl.Alert.createSSLException(Alert.java:133)
  | at sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
  | at sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
  | at sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
  | at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1313)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408)
  | at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
  | at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
  | at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
  | at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:205)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:66)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:51)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:35)
  | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:74)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:43)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:114)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:87)
  | ... 29 more
  | Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  | at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
  | at sun.security.validator.Validator.getInstance(Validator.java:181)
  | at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)
  | at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
  | at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:189)
  | at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
  | at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625)
  | at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460)
  | at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
  | at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
  | at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
  | at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
  | at sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
  | at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
  | at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
  | at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
  | ... 46 more
  | Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  | at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
  | at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
  | at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
  | at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86)
  | ... 62 more
  | END RequestId: 40cd7978-18ce-41d9-8ef3-07c778d7f562
  | REPORT RequestId: 40cd7978-18ce-41d9-8ef3-07c778d7f562	Duration: 2892.19 ms	Billed Duration: 3200 ms	Memory Size: 256 MB	Max Memory Used: 90 MB	Init Duration: 300.45 ms

**To Reproduce**
1. Clone repo
2. Change Quarkus version in pom.xml to 1.4.1
3. Deploy as described in README-file
4. Trigger Lambda function with an empty event

**Configuration**
```properties
# Add your application.properties here, if applicable.

quarkus.lambda.handler=processing
quarkus.ssl.native = true

**Comment by gsmet** [comment]
@oztimpower would you have some time to look at this one this week? We plan to release 1.4.2 early next week.

**Comment by oztimpower** [comment]
Yep, I have a few queued up to look at. I’ll prioritise this one tomorrow.

**Comment by oztimpower** [comment]
@gsmet To update you, I have been working with @smoell via internal AWS channels. I've spent a few hours going through the example.

The main difference between Quarkus v.1.2.1 and 1.4.1 for the sample project is the different GraalVM, from 19.2.1 to 19.3.1, and as you know 19.3 has SSL related improvement. I'm working with @smoell to get the project more in line with the Quarkus documentation, since I have specifically added this issue into the Quarkus AWS Lambda guide (SSL issues with AWS SDK v2). The project needs some modification as it is assuming a Linux implementation, and needs to adapt to the changes that @patriot1burke introduced to customise the function.zip (which were really cool enhancements).

i.e. this is not an issuer per-se that should detract from 1.4.2 release. It can be resolved by following the Quarkus AWS Lambda docs. I'm almost finished validating that, and will submit PR to @smoell once done.  

Also I would not here that the sample code is using AWS Lambda with API Gateway, thus the Quarkus module being used perhaps should be Quarkus Amazon Lambda HTTP instead (for simpler code).  Though it's worth getting this one working too.

**Comment by smoell** [comment]
A quick update: I should have spent more time reading the updated documentation :) Thank you @oztimpower , that was really helpful!
