### ISSUE TITLE
Error with Google Firestore client after upgrading to 1.4.1

### ISSUE THREAD

**Issue by luis-martinez-herrera** [quarkusio/quarkus#8962]
**Describe the bug**
After upgrading to version 1.4.1, the Firestore client throws an error.

**Expected behavior**
The Firestore client should work as in version 1.3.2.

**Actual behavior**
Calling the Firestore API throws an error and cancels the request.

**Additional context**
This error occurs at runtime, when executing the query in Firestore.
Version 1.3.2 does not display warning messages.
JDK 11 is used in both cases.
The error occurs in Dev and Production mode.

The following messages are displayed in the log.

![Screenshot_1](https://user-images.githubusercontent.com/5863787/80620805-154f9880-8a0c-11ea-8998-b697ed05f360.png)
![Screenshot_2](https://user-images.githubusercontent.com/5863787/80620813-17195c00-8a0c-11ea-81a6-49b06e8247c6.png)

**Comment by gsmet** [comment]
I would bet on a version mismatch between the protobuf version we impose in your pom and the version your component uses.

**Comment by geoand** [comment]
Yeah this almost certainly isn't a bug in Quarkus, not least because we don't do anything with `Firestore`

**Comment by luis-martinez-herrera** [comment]
> I would bet on a version mismatch between the protobuf version we impose in our BOM and the version your component uses.

@gsmet I think you're right, they use an old version in the build.

> com.google.protobuf:protobuf-java:jar:3.6.1:compile
