### ISSUE TITLE
Quarkus AWS attempts resolve dependencies on abstract class

### ISSUE THREAD

**Issue by bsamartins** [quarkusio/quarkus#8964]
**Describe the bug**
Quarkus attempts to resolve dependencies on an abstract RequestHandler.

**Expected behavior**
I would expect that dependency resolution would only apply to concrete classes.

**Actual behavior**
Quarkus attempts to resolve dependencies on abstract even if there's no implementation for it.
```
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.bsamartins.quarkus.ReactiveFunction<I, O> and qualifiers [@Default]

	- java member: io.bsamartins.quarkus.AbstractReactiveRequestHandler#<init>()
	- declared on CLASS bean [types=[java.lang.Object, io.bsamartins.quarkus.AbstractReactiveRequestHandler<I, O>, com.amazonaws.services.lambda.runtime.RequestHandler<I, O>], qualifiers=[@Default, @Any], target=io.bsamartins.quarkus.AbstractReactiveRequestHandler]
```

**To Reproduce**
Sample code
```
public interface ReactiveFunction<I, O> extends Function<I, Maybe<O>> {}
```
```
public abstract class AbstractReactiveRequestHandler<I, O> implements RequestHandler<I, O> {

    final private ReactiveFunction<I, O> function;

    public AbstractReactiveRequestHandler(ReactiveFunction<I, O> function) {
        this.function = function;
    }

    @Override
    public O handleRequest(I input, Context context) {
        return function.apply(input).blockingGet();
    }
}
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.4.1.Final

**Comment by oztimpower** [comment]
Do you have a concrete implementation of this abstract class? 
"Quarkus attempts to resolve dependencies on abstract even if there's no implementation for it"

Goes without saying it won't work? :)

There is a way to pick this up as part of the build where is scans the classes looking for an implementation of RequestHandler<I, O>, it could also check that the implementing class is not abstract. The result would be that you would get a build time error (I think) that no handler implementation was found.

**Comment by oztimpower** [comment]
PR #9023 submitted to address this, appreciate if you could test it.

**Comment by bsamartins** [comment]
Thanks, it's skipping the abstract class now.

**Comment by satroro** [comment]
Hello everyone, I am new to quarkus and have the similar usecase above where I have abstract class implementing multiple interfaces and I have a concrete class extends abstract class. But mvn build is throwing unsatisfieddependency error. Is this fix applied to only certain artifcats? or please help me how can we resolve dependency injection issue for concrete class extending abstract class.
