### ISSUE TITLE
have a global default flag for trusting certificates 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#8975]
**Description**
Today we (so far) have the following properties to indicate if a certain extension should trust-all extension. 

```
quarkus.oidc.tls.verification
quarkus.vault.tls.skip-verify
quarkus.kubernetes-client.trust-certs
quarkus.mailer.trust-all
quarkus.vertx.eventbus.trust-all
```

That feels maddening :) 

Suggestion is two-fold:

1) have one global property that all of these uses as default.
2) deprecate the above names and use the basename, i.e. "trust-all"  so when searching you can find all the places you can tweak if you want to.

**Comment by sberyozkin** [comment]
`trust-all` sounds good. Though it is only a leaf property, I suppose we should encourage OIDC users to do `quarkus.oidc.tls.trust-all` as `trust-all` only makes sense in scope of TLS and there will be more TLS specific properties. Proposal is to have `tls.trust-all` for all the extensions.

**Comment by glefloch** [comment]
@maxandersen, I would be interested to work on this. Regarding the name of the key, would `quarkus.tls.trust-all` be ok ?

**Comment by maxandersen** [comment]
I think so - but i think we'll finally know better when we got a PR to look and touch it ;) the good thing is that once we get this cleaned up adjusting the final names should be fairly easy i hope!

and thanks @glefloch for taking this one up and sorry for delay in response!
