### ISSUE TITLE
ClassCastException when using pact-jvm Jupiter extension and @QuarkusTest

### ISSUE THREAD

**Issue by tgippi** [quarkusio/quarkus#8978]
**Describe the bug**
We're using [Pact-JVM](https://github.com/DiUS/pact-jvm) to specify and test consumer driven contracts.
We implement those tests by running Junit Jupiter tests with a combination of `@QuarkusTest` and Pact-JVM Jupiter extensions.

Unfortunately since Quarkus `1.3.0.Final` those tests will fail because of `ClassCastException`. 
After a short research I've seen that those exceptions will be thrown, because the test encounters multiple ClassLoaders.
It seems that the different stages of the Pact Jupiter extension lifecycle are running with a different ClassLoader than the tests itself. So there is an incompatibility between the shared objects (parameters given from the extension into the `@Test` method).

When we use Quarkus `1.2.1.Final` everything works fine.
The issue still appears when we use Quarkus `1.4.1.Final`.

**Expected behavior**
When using Pact-JVM Jupiter Extension and `QuarkusTest` there should be no ClassCastException.

**Actual behavior**
When using Pact-JVM Jupiter Extension and `QuarkusTest` there will a ClassCastException be thrown.

**To Reproduce**

Clone this repo
`$ git clone git@github.com:tgippi/quarkus-pact-issue.git`

Run the tests either with `1.3.2.Final` or with `1.4.1.Final`:
`$ mvn -P1.3 clean test`
or
`$ mvn -P1.4 clean test`

See that there will a ClassCastException be thrown.

**Configuration**
No explicit configuration.

**Screenshots**
Shouldn't help explaining the problem.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux localhost.localdomain 5.5.5-200.fc31.x86_64 #1 SMP Wed Feb 19 23:28:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode, sharing)
```
 - GraalVM version (if different from Java):  No GraalVM
 - Quarkus version or git rev: Every version since `1.3.0.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-11.0.6.10-0.fc31.x86_64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.5.5-200.fc31.x86_64", arch: "amd64", family: "unix"
```

**Comment by geoand** [comment]
Seems like another manifestation of #8251
