### ISSUE TITLE
quarkus-core - Log in the INFO log (powered by Quarkus) if running in JVM or Native mode

### ISSUE THREAD

**Issue by davsclaus** [quarkusio/quarkus#8980]
**Description**
(Describe the feature here.)

When you startup Quarkus it logs when its started and its time it took to startup. This log message is the same whether its JVM vs native mode. It would be good if we could log which mode it runs as, or at least for native log this. 

**Implementation ideas**
(If you have any implementation ideas, they can go here, however please note that all design change proposals should be posted to [the Quarkus developer mailing list](mailto:quarkus-dev@googlegroups.com) (or [the corresponding Google Group](https://groups.google.com/group/quarkus-dev); see [the decisions process document](https://github.com/quarkusio/quarkus/blob/master/DECISIONS.adoc) for more information).

**Comment by jaikiran** [comment]
I've opened https://github.com/quarkusio/quarkus/pull/9249 with the proposed change.
