### ISSUE TITLE
vertx-http deployment tests failing on my macOS

### ISSUE THREAD

**Issue by marcinczeczko** [quarkusio/quarkus#8982]
**Describe the bug**
Any unit test using `@TestHTTPResource` annotation that provides an url to be called by Restassured fails with connection timeout.
I investigated the issue for a while and here's what I found:
- With the mentioned annotation HTTP client of rest assured is doing calls agains https://0.0.0.0:8444 or http://0.0.0.0:8081  (depending on test) as it's shown when enabled DEBUG log
```
2020-04-30 10:53:37,130 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 1.265s. Listening on: http://0.0.0.0:8081 and https://0.0.0.0:8444
2020-04-30 10:53:37,133 INFO  [io.quarkus] (main) Profile test activated.
2020-04-30 10:53:37,133 INFO  [io.quarkus] (main) Installed features: [cdi, security]
2020-04-30 10:53:38,482 DEBUG [org.apa.htt.imp.con.BasicClientConnectionManager] (main) Get connection for route {s}->https://0.0.0.0:8444
2020-04-30 10:53:38,493 DEBUG [org.apa.htt.imp.con.DefaultClientConnectionOperator] (main) Connecting to 0.0.0.0:8444
```
- If i change the test by providing the url string as `http://localhost:8081` or `https://localhost:8444` everything works fine
- When test is running, I can do the calls using `0.0.0.0` either via browser or `cURL` without any hassle
- Open question: should the annotation use `localhost` instead of `0.0.0.0` ?

**Expected behavior**
Tests passed

**Actual behavior**
All tests using `@TestHTTPResource` annotation fails with connection timeout error
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 79.362 s <<< FAILURE! - in io.quarkus.vertx.http.ssl.SslServerWithP12Test
[ERROR] testSslServerWithPkcs12  Time elapsed: 77.25 s  <<< ERROR!
java.net.ConnectException: Operation timed out (Connection timed out)
```

**To Reproduce**
As  for now, I can reproduce it only on my macOs when running `mvn clean tests` on `vertx-http` extension

**Configuration**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin PL-MAC-MARCINCZ 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: tried with `Oracle 1.8.0.192, openJdk 11.0.2 & openJdk 13.0.2`
 - GraalVM version (if different from Java): `19.3.1`
 - Quarkus version or git rev: `master`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `3.6.3`

**Additional context**
- I spoke to @cescoffier and it works fine of his macOS
- The unit test I started looking first: https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/ssl/SslServerWithP12Test.java

**Comment by jaikiran** [comment]
Taking a quick look at the code, it looks like this value is inferred from the `quarkus.http.host`. If that's not set, it defaults to `localhost`. Within your setup, is `quarkus.http.host` being configured to some value (perhaps `0.0.0.0`)?

**Comment by marcinczeczko** [comment]
Actually it is `quarkus.http.host = null`

**Comment by marcinczeczko** [comment]
I debugged the code and found out that `0.0.0.0` is because of that config default: https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpConfiguration.java#L38

**Comment by stuartwdouglas** [comment]
Is this still an issue?

**Comment by cescoffier** [comment]
For some reason, on the machine, the tests fail because it can't bind to the 0.0.0.0 interface. Not sure we can do anything, I would say it's an infrastructure issue. 

I don't have this issue (also using a Mac).

**Comment by stuartwdouglas** [comment]
Are you sure it was a bind issue and not an issue with attempting to connect to 0.0.0.0 ? I think this was actually a problem at one point, that was fixed.

**Comment by cescoffier** [comment]
Possibly. It only happened to the TLS tests, which was a bit odd.

**Comment by marcinczeczko** [comment]
I finally solved my issue. Sharing my findings.
Assuming my mac hostname is `MY-MAC`, the `/etc/hosts` must have following entry
```
127.0.0.1   localhost MY-MAC
```
For some reason I had that caused the issue.
```
127.0.0.1   localhost MY-MAC.local
```
