### ISSUE TITLE
Support mocking of @Singleton beans

### ISSUE THREAD

**Issue by miron4dev** [quarkusio/quarkus#8983]
**Description**
As a developer, I want to mock `@Singleton` beans. 
Sometimes, it's not possible to annotate a bean by `@ApplicationScoped`, e.g. in the case described here https://github.com/quarkusio/quarkus/issues/8960

**Comment by zenonwch** [comment]
And for @InjectSpy as well.
Pls.

**Comment by fabasoad** [comment]
I just faced this problem. I have added `vertx` extension to use `EventBus` class. And it is defined as `@Singleton`:
https://github.com/quarkusio/quarkus/blob/main/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java#L34
So I can't mock it in my test class. Are there any workarounds on how can I mock `@Singleton` annotated class' instances?

**Comment by geoand** [comment]
You can use `@InjectMock(convertScopes=true)` if absolutely necessary

**Comment by takesson** [comment]
Does convertScopes work for Named beans?

I am getting exactly the same error regardless of convertScopes setting:
```
Invalid use of io.quarkus.test.junit.mockito.InjectMock - the injected bean does not declare a CDI normal scope but: javax.inject.Singleton. Offending field is solrClient of ...
```

Quarkus 2.4.1.
```
	@InjectMock(convertScopes=true)
	@Named("repositem")
	SolrClient solrClient;
```

**Comment by geoand** [comment]
Can you please open a new issue? Attaching an example application that fails like you mention would be very helpful

**Comment by takesson** [comment]
I now understand the issue better. 
 - I have confirmed that convertScopes works fine in combination with Named.
 - The issue I saw was the final method that forced the use of Singleton in the first place. We have Named beans that extend a class with a final method and tons of other methods (out of our control).

In that situation, the error message is identical regardless of convertScopes setting so it wasn't obvious if convertScopes was in effect. I now understand its limitations better.

**Comment by gian1200** [comment]
For anyone working with Quarkus 3 reaching this point:

`io.quarkus.test.junit.mockito.InjectMock` was replaced with `io.quarkus.test.InjectMock`. `convertScopes` doesn't exist in the new class. To get the same behavior, you should implement it this way:

```java
@InjectMock
@MockitoConfig(convertScopes = true) 
EventBus eventBus; // or your favorite singleton
```
