### ISSUE TITLE
Slow Dev Mode Startup

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#9001]
**Description**
I am currently trying to migrate a rather large wildfly 10 application to quarkus.
* The app consist of  more than 50 jpa entities.
* About 400 ApplicationScoped beans.
* It is a multi-module project. About 87 modules of my 150 modules are used inside the application.
* Overall, I have about 2200 java files in my project. Some of them are automaticly generated using jpamodelgen, or mapstruct.

So far, I have only encountered one big Problem, which I can't solve on my own.

On my linux vm, I have the following startup times.
* Starting quarkus in dev mode takes about 57 seconds.
* Starting quarkus as uber jar takes about 10 seconds, which is as expected.

On my local windows laptop, these numbers are increased by about 2 times (130 seconds for dev mode to start). Keep this in mind please will investigating this issue.

I attached some flamegraphs with event=cpu, event=alloc, and some with event=wall, respectivly. I used the linux vm for obtaining all the numbers and flamegraphs here.
Done with following settings:
-agentpath:/root/mnp/src/async-profiler-1.7/build/libasyncProfiler.so=start,event=alloc,file=/root/mnp/profile-alloc.svg,interval=1000000,width=600,framebuf=2000000,simple

You can find them here: https://github.com/Postremus/9001-flamegraphs
* For Quarkus 1.3.2.Final
* For Quarkus 1.4.1.Final
* For #8995
** Dev mode takes  28 seconds to launch on java 8.
** Dev mode takes  16 seconds to launch on java 11. 
* For master (87522320380e9f201a2f4c027f3e50bc1ffd6f06)
** Dev mode takes 90 seconds to launch on java 8.
* For Quarkus 1.5.0.CR1
** Dev mode takes 28 to 33 seconds to launch on java 8.

java version and maven:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /root/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 1.8.0_252, vendor: Azul Systems, Inc., runtime: /root/mnp/java/zulu8.46.0.19-ca-jdk8.0.252-linux_x64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.12.14-lp150.12.67-default", arch: "amd64", family: "unix"

Operation system:
Linux version 4.12.14-lp150.12.67-default (geeko@buildhost) (gcc version 7.4.1 20190424 [gcc-7-branch revision 270538] (SUSE Linux) ) #1 SMP Tue Jul 9 08:18:26 UTC 2019 (b610084)

Can you please investigate / give aid what needs to be done?

**Comment by Postremus** [comment]
Relates to this discussion in the mailing-list: https://groups.google.com/forum/#!topic/quarkus-dev/Lz7SvD0ANrQ

Relates to this zulip chat: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Slow.20Dev.20Mode.20startup

**Comment by johnaohara** [comment]
@Postremus the start times you quoted
```
For #8995
** Dev mode takes 28 seconds to launch on java 8.
** Dev mode takes 16 seconds to launch on java 11.
```
Were these measure on your linux VM, or on your windows laptop?

**Comment by Postremus** [comment]
On my linux vm wiht 4 cores, 32GB of memory. I updated the description to reflec this.
I guess we should first worry about getting dev mode launching fast on the linux vm, since I can get flamegraphs easily there.

**Comment by Postremus** [comment]
I am closing this issue. WIth the latest improvements in 1.6.0.Final, the project now start in around 13 seconds in devmode - good enough for now. :)

**Comment by omprakashyadav** [comment]
Hello Everyone,

I am using `Quarkus 2.7.4.Final` and as the project has grown from few classes to 100 classes, we are experiencing slowness in the server startup time in dev mode.

Our server startup now takes more than a 55 seconds on `Java 17.0.5`
I profiled the application and found that `getAllKnownImplementors` is taking more than 28seconds.
`org.jboss.jandex.CompositeIndex.getAllKnownImplementors ()	28,676 ms (80.3%)	28,676 ms (80.3%)`

Is there a way to improve the startup time?
My machine is M1 Max with 32GB RAM. I even tried other machines and seeing the similar slowness.
Please help!

![SCR-20221226-bl2](https://user-images.githubusercontent.com/64246390/209567179-b340a02d-3523-44f4-8dd8-6166996232fb.png)

**Comment by gsmet** [comment]
@omprakashyadav please open a different issue. My guess is that somehow you're adding a reflective hierarchy for `Object` that would load all classes.

This behavior is definitely not expected so there's something fishy.

**Comment by omprakashyadav** [comment]
Hmmm.. 

Thanks @gsmet,
I can file a new ticket, but I am not sure if it is something just related to our environment and setup.
Do you have any idea what is going on here?
