### ISSUE TITLE
Automatic Kafka Topic Subscription

### ISSUE THREAD

**Issue by tobiasstadler** [quarkusio/quarkus#9004]
In Kafka Streams it is possible to subscribe to popics matching a pattern (see `org.apache.kafka.streams.StreamsBuilder#stream(java.util.regex.Pattern)`). It would be nice if the subscription could be automatically updated by Quarkus when topics matching the given pattern are created/deleted in Kafka (similar to what is possible in Kafka Connect).

**Comment by rquinio** [comment]
Isn't this something handled internally by Kafka Streams ?

**Comment by tobiasstadler** [comment]
Ys seems to work.
