### ISSUE TITLE
Add support for multiple SMTP servers to quarkus-mailer

### ISSUE THREAD

**Issue by Nunalves** [quarkusio/quarkus#9064]
**Description**
When using the `quarkus-mailer` extension it is only possible to setup a single SMTP server configuration. In a SaaS context clients usually want to use their own STMP server.

**Implementation ideas**
I think the approach could be the same as with datasources. Where you can have multiple datasources configured and then specify a qualifier when injecting it (https://quarkus.io/guides/datasource#multiple-datasources).

**Comment by gsmet** [comment]
@Nunalves let us a few days to revisit the multiple datasource code as we might be able to simplify it with the new Quarkus developments. If it's the case, it will be a good source of inspiration if you want to contribute the multiple SMTP support.

Provided @cescoffier is OK this is a good feature request.

/cc @geoand

**Comment by cescoffier** [comment]
I never thought we would need multiple SMTP :-)

**Comment by geoand** [comment]
After going through the motions of refactoring the multiple datasource handling, I think that we know have a good blueprint of how to do this with little friction.

**Comment by geoand** [comment]
I'll make a first pass on the mailer extension to simplify it's CDI configuration. That should pave the way for supporting multiple SMTPs.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/9151 makes things much simpler so when it's merged then it should be a lot easier for someone to work on this issue

**Comment by danyadibence** [comment]
Hi,

are there any updates on this issue?

**Comment by csmuller** [comment]
Is there a workaround for this, besides manually instantiating a `MailClient` with my own `MailConfig`?

**Comment by gsmachado** [comment]
@gsmet are you taking this issue to solve it for the next release?

Any estimates on a SNAPSHOT ready for testing?

**Comment by gsmet** [comment]
No estimates. I will work on it when time permits and it will be ready when it's ready.

**Comment by gsmachado** [comment]
@gsmet sure, no pressure. 😄 

I thought there was a backlog or sprint planning or smth.

But all fine! Thanks for taking a look into it.

**Comment by NebulousWeb** [comment]
Our company also needs this feature, it was rather surprising to see this limitation in Quarkus where it is a non issue in other frameworks.  We have multiple SMTP servers, and depending on the mails sent out, many different from addresses. I saw a comment where the workaround is to instantiate a MailClient with another MailConfig, now trying to find an example of that workaround. Not sure if thats feasible as we have 3-4 SMTP configurations and about 20 different from addresses depending on the mail, otherwise we may need to pull in another Java SMTP library.
