### ISSUE TITLE
Arguments for QuarkusTestResource

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#9066]
**Description**
We use `@QuarkusTestResource` to start databases using Testcontainers, which works very nicely. It would be nice if the `@QuarkusTestResource` annotation allowed passing arguments to the `QuarkusTestResourceLifecycleManager`; e.g. to allow specifying the tag for the Docker container image.

**Comment by geoand** [comment]
This is an interesting idea. I assume the arguments would just be an object array that the author of the resource would have to handle, right?

**Comment by knutwannheden** [comment]
Yes, possibly the arguments would just be strings and need to be deserialized as appropriate by the `QuarkusTestResourceLifecycleManager` implementation. Usage would be something like `@QuarkusTestResource(Foo.class, args="a")` or `@QuarkusTestResource(Foo.class, args={"a","b"})`.

I suppose there could be a new corresponding (default) `QuarkusTestResourceLifecycleManager#init(String...)` method which would be called before `start()` is called. That would then also be backwards compatible. Or should the method possibly even have a first `Object testInstance` argument. That way the implementation could also check for further annotations.

**Comment by geoand** [comment]
> Yes, possibly the arguments would just be strings and need to be deserialized as appropriate by the `QuarkusTestResourceLifecycleManager` implementation. Usage would be something like `@QuarkusTestResource(Foo.class, args="a")` or `@QuarkusTestResource(Foo.class, args={"a","b"})`.
> 

Hm... I think that `Object[]` as a type for arguments would be more general, as I can definitely see this being passed in int for example.

> I suppose there could be a new corresponding (default) `QuarkusTestResourceLifecycleManager#init(String...)` method which would be called before `start()` is called. That would then also be backwards compatible. Or should the method possibly even have a first `Object testInstance` argument. That way the implementation could also check for further annotations.

Yes, we would definitely need to preserve backward compatibility so a new `default` method would be the way to go.

I like this idea, @stuartwdouglas WDYT? If you think it's worth it, I'll go ahead and get it done.

**Comment by geoand** [comment]
In any case, https://github.com/quarkusio/quarkus/pull/9082 should do the trick

**Comment by knutwannheden** [comment]
> In any case, #9082 should do the trick

Very nice! What are your thoughts on an additional `Object testInstance` parameter passed to `init()`? I don't have a usecase for this yet. I was just thinking this could be useful if the `QuarkusTestResourceLifecycleManager` instance would like to check for the presence of some other annotation on the test.

**Comment by geoand** [comment]
Unfortunately we can't do that (yet), because a `QuarkusTestResourceLifecycleManager` runs before all tests, so it's not really bound to a specific test.

Which actually makes me think that #9082 needs to be updated to reflect that as well - basically we need to ensure that we don't have conflicting args.

**Comment by famod** [comment]
The idea with the `testInstance` reminds me of a discussion we had on Zulip:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/QuarkusTest.20.2B.20WireMock.20.2B.20dynamic.20port/near/193014573

Which in turn reminds me to check that "Test improvement ideas email thread in quarkus-dev mailing list"...
