### ISSUE TITLE
Uberjar does not include add dependencies

### ISSUE THREAD

**Issue by oscarfh** [quarkusio/quarkus#9068]
**Describe the bug**
[This](https://github.com/oscarfh/code-with-quarkus) is a project created from code.quarkus.io and configured to generate a uber jar and to use `com.google.common.base.Strings` class.
It will work if ran from maven (`./mvn quarkus:dev`), but not from the uber jar (`java -jar ...`) due to a missing dependency (the above mentioned class)

**Expected behavior**
Both should run.

**Actual behavior**
Only the maven version runs, because the development version seems to get this class from the dependency `quarkus-ide-launcher-1.4.1.Final.jar`. 
It can be even worse, is case the version executed in dev is different than the one executed on the environment.

**To Reproduce**
1. Checkout the project
2. Run with maven -> calling `http://localhost:8080/hello` works
3. Generate the uber jar (or use the one I added to the projecT)
4. See that you cannot call

**Comment by geoand** [comment]
I don't think this is a bug TBH. You haven't added Guava to your `pom.xml`, so it most certainly does not end up in the built jar.

**Comment by oscarfh** [comment]
@geoand I agree, but then it should fail in the dev mode, right?

**Comment by geoand** [comment]
Right, ideally it should. Problem is that devmode has some dependencies of it's own that are being picked up in this case.

cc @stuartwdouglas @aloubyansky

**Comment by oscarfh** [comment]
@geoand Sorry for hijacking the thread (I will delete this message soon).
Here is the link of the thread I created about hardcoded path in tests (we talked about it in stackoverflow): https://github.com/quarkusio/quarkus/issues/8950#issuecomment-623728781
If you could provide some guidance I would love to contribute, but I am missing some context to be able to do it meaningfully. It would be nice if you could take a look

**Comment by geoand** [comment]
@oscarfh Thank you for volunteeting. The best person to help you out and / or coordinate efforts is @aloubyansky who has steadily been improving our Gradle support with difficult to make fixes.

**Comment by aloubyansky** [comment]
Ideally, it should simply fail to build. And even compile. The IDE should be highlighting this as a missing dependency. I think we should review our IDE launcher implementation to avoid this kind of issues. It enables not only guava but all sorts of other dependencies during development that won't be there at runtime.

**Comment by stuartwdouglas** [comment]
The only real option here would be to shade all the IDE launcher dependencies, although we will need to be careful about which ones to shade.

**Comment by geoand** [comment]
+1 for shading to avoid such issues
