### ISSUE TITLE
Proposal to implement a RabbitMQ extension via MicroProfile Reactive Messaging

### ISSUE THREAD

**Issue by fabiojapa** [quarkusio/quarkus#9076]
Offer a RabitMQ integration. Please Thumbs up if interested. And consider volunteering for a contribution if really interested :D
---
[was]
Are you working on a extension to connect to rabbitMQ?

**Comment by emmanuelbernard** [comment]
I converted the issue to an extension proposal. At the moment the people working in the messaging area have their plate full. But they can definitely guide someone to provide a contribution.

**Comment by cescoffier** [comment]
There is a suitable underlying client here: http://smallrye.io/smallrye-reactive-utils/apidocs/io/vertx/mutiny/rabbitmq/RabbitMQClient.html

**Comment by cassunde** [comment]
Hi @fabiojapa you started the implementation?

**Comment by fabiojapa** [comment]
Hi @cassunde I didn't.

**Comment by cassunde** [comment]
Hi @cescoffier, is there a documentation or specification to follow? what is the best way to start this implementation?

**Comment by cescoffier** [comment]
@cassunde have a look to the exiting connector like this one https://github.com/smallrye/smallrye-reactive-messaging/tree/master/smallrye-reactive-messaging-kafka.

A connector is a bean implementing 2 interfaces (for inbound and outbound). On the reception side you need to produce a stream (it’s easy with the client mentioned above). To send, we may need to investigate if rabbit has a flow control mechanism.

**Comment by gastaldi** [comment]
@bpasson will contribute to a Quarkiverse extension in https://github.com/quarkiverse/quarkus-rabbitmq-client. Closing this now
