### ISSUE TITLE
Bump Keycloak to 9.0.3

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#9083]
requires backport to 1.3

**Comment by sberyozkin** [comment]
We have this PR, https://github.com/quarkusio/quarkus/pull/8987 which updates to KC 10.
The relevant changes are listed at
https://github.com/quarkusio/quarkus/pull/8965

Is 9.0.3 important for the 1.3 backport ?

**Comment by michalszynkiewicz** [comment]
yes

**Comment by michalszynkiewicz** [comment]
We may switch to 9.0.3 in the 1.3 branch directly in this case, WDYT @gsmet ?

**Comment by sberyozkin** [comment]
Whatever is simpler, I can rebase my PR later if needed.

**Comment by gsmet** [comment]
Yes we can update directly in 1.4 and 1.3. I don't think we will make another 1.4 but it doesn't cost us much to push it to 1.4 too.

**Comment by michalszynkiewicz** [comment]
@harshmadhani would you like to take this one?

**Comment by harshmadhani** [comment]
Yes @michalszynkiewicz I will take this up

**Comment by michalszynkiewicz** [comment]
@sberyozkin is there anything more than the tests in the Quarkus repo that is worth checking after the version bump?

**Comment by sberyozkin** [comment]
HI @michalszynkiewicz @harshmadhani 

`securiry-openid-connect-*` quickstarts at https://github.com/quarkusio/quarkus-quickstarts.
2 of them have tests but this one, https://github.com/quarkusio/quarkus-quickstarts/tree/master/security-openid-connect-quickstart requires a manual check starting from:
https://quarkus.io/guides/security-openid-connect#starting-and-configuring-the-keycloak-server

**Comment by harshmadhani** [comment]
@sberyozkin Sure I will check the tutorial and test it as mentioned in the guide

**Comment by harshmadhani** [comment]
PR #9156 is raised for resolution of the issue
