### ISSUE TITLE
Dev-Mode: Remove "[WARNING] The project's sources directory does not exist"

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#9093]
**Description**
In the process of migrating my current project from 1.3.1 to 1.4.2, I happily removed  a `Dummy.java` from the main module after having seen this comment: https://github.com/quarkusio/quarkus/pull/8712#issuecomment-616989898

This now yields a warning:
```
[WARNING] The project's sources directory does not exist C:\Develop\SomeProject\server\src\main\java
```

I suggest to remove this warning, especially for multi-module projects.

cc @harthorst

**Comment by famod** [comment]
@aloubyansky & @geoand WDYT?

**Comment by geoand** [comment]
I don't have an educated opinion on this unfortunately

**Comment by aloubyansky** [comment]
@famod i'd say that's not a big deal. However, could you just give an simple example of a project? That does look a bit unusual.

**Comment by famod** [comment]
@aloubyansky 
Something like this:
```
root
   ├─ shared
   │      ├─ event
   │      ├─ soap
   │      ├─ rest
   │      └─ ...
   ├─ billing
   │      ├─ api
   │      ├─ core
   │      └─ ...
   ├─ user
   │      ├─ api
   │      ├─ core
   │      └─ ...
   ├─ ...
   └─ server
```
In `server` (could also be `dist`or whatever), everything comes together as an Quakus app.
The actual business concerns are implemented in separate modules (e.g. `billing`) which can use stuff from `shared`.
In this setup, `server` does not necessarily have to contain any java sources.

**Comment by aloubyansky** [comment]
Ok, sure. Where is `application.properties` in your case, btw?

**Comment by famod** [comment]
We have have a modular YAML approach:
- commons for all in `shared-config` (`application-shared.yaml`)
- specific module specific config is located in the respective business module (e.g. `application.config` in `user-core`)
- `application.yaml` in `server` contains settings that are common to all but that are not relevant to dev-mode in the business modules (e.g. always include swagger-ui)
- we merge the files accordingly with a maven plugin

**Comment by aloubyansky** [comment]
And the resulting config is stored in the server module?
The reason I'm asking is that, resources should be considered as sources in our case. If the module contains no sources and no resources that'd be an edge case.

**Comment by famod** [comment]
> And the resulting config is stored in the server module?

Correct. It is generated/merged to `target/classes`.

> The reason I'm asking is that, resources should be considered as sources in our case. If the module contains no sources and no resources that'd be an edge case.

Right now it is complaining only about `src/main/java`, not `src/main/resources`.
But I could even imagine valid cases where you don't even have `src/main/resources`.

**Comment by aloubyansky** [comment]
Would you like to submit a PR?

**Comment by famod** [comment]
> Would you like to submit a PR?

Yeah, I can do that. So I'll simply remove it, right? The alternative to that would be _trying_ to detect whether we have a multi-module project. But that is not so easy.

**Comment by aloubyansky** [comment]
It's probably not that difficult, actually. You can get the Model and check whether it includes modules. And probably `project.getParentFile()` to check whether the parent project is a part of the workspace. Haven't actually verified it though.

**Comment by famod** [comment]
> You can get the Model and check whether it includes modules.

That won't work if using `mvn -f server` or `cd server && mvn ...`.

> And probably `project.getParentFile()` to check whether the parent project is a part of the workspace.

I have also thought about that but this might just be some common parent, not really a project-specific one.
On the other hand I don't think that anyone would use such a structure:
```
general-parent
   ├─ project1
   │     ├─ p1-module
   │     └─ p1-server
   ├─ project2
   │     ├─ p2-module
   │     └─ p2-server
  └─ ...
```
So, yeah - this might work (especially since it's just about a warning).

**Comment by aloubyansky** [comment]
Alright, looking forward to your PR.
