### ISSUE TITLE
Dev-Mode: Remove check for build goal (or provide opt-out)

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#9094]
**Description**
In my current multi-module project we have one main `server` module where everything comes together and where the `quarkus:build` is configured.

To be able to just start only a part of the application, we introduced a Maven profile that allows to start Dev-Mode in certain other modules which do not (and must not) have `quarkus:build` configured.

Due to a check in https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L259 we have to "fake" the build goal:
```xml
        <profile>
            <id>qdev</id>
            <build>
                <defaultGoal>quarkus:dev</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>io.quarkus</groupId>
                        <artifactId>quarkus-maven-plugin</artifactId>
                        <executions>
                            <!-- presence of build-goal is enforced by dev-goal, but is not required to actually run (sic!) -->
                            <execution>
                                <id>default</id>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
```

It would be nice to get rid of this fake build goal workaround.

**Implementation ideas**
In case you want to prevent Quarkus-newbies from making mistakes, there could be a mojo parameter for opting out of the check that the experienced users could use.

cc @harthorst

**Comment by famod** [comment]
@aloubyansky & @geoand WDYT?

**Comment by geoand** [comment]
An opt-out flag sounds reasonable to me.
