### ISSUE TITLE
fix guide -> Deploying the application as Java application in OpenShift with jdk11

### ISSUE THREAD

**Issue by fiorenzino** [quarkusio/quarkus#9100]
**Describe the bug**
Today quarkus support  JDK 8 or 11+ - but In the guide "deploying s2i for openshift"
https://quarkus.io/guides/deploying-to-openshift-s2i
 when you speak about "Deploying the application as Java application in OpenShift" you don't give info about jdk11.

for jdk18:
# To build the image on OpenShift
oc new-app registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift~https://github.com/quarkusio/quarkus-quickstarts.git --context-dir=getting-started --name=quarkus-quickstart

for jdk11:
oc new-app registry.access.redhat.com/openjdk/openjdk-11-rhel7~https://github.com/quarkusio/quarkus-quickstarts.git --context-dir=getting-started --name=quarkus-quickstart

**Comment by geoand** [comment]
Thanks for reporting this,

Would you like to submit a PR updating the guide?

**Comment by gsmet** [comment]
We should just document 11 now. Also should we use UBI instead?

/cc @cescoffier

**Comment by geoand** [comment]
This was fixed with 2cfb6bd43117aa119ebf8538e4e104b3f6760a8e
