### ISSUE TITLE
Test BOM

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#9103]
Followup https://github.com/quarkusio/quarkus/pull/9073 and https://github.com/quarkusio/quarkus/pull/9078

After jna and testcontainers were removed from the Runtime BOM, we (Camel Quarkus) have to manage the jna version (otherwise conflicting between testcontainers and mongodb) ourselves. This is because we cannot inherit from Quarkus build parent.

We'd prefer that Quarkus manages its test deps in a new dedicated Test BOM, that we could import. We could thus avoid maintaining versions Quarkus team has to keep consistent anyway. Quarkus could import that BOM in its build parent too.

WDYT?

**Comment by ppalaga** [comment]
I have proposed a minimal version of the Test BOM https://github.com/quarkusio/quarkus/pull/9104

**Comment by galderz** [comment]
Indeed I've just came across this trying to run camel-quarkus native tests (see [here](https://gist.github.com/galderz/32d961402486f8a415f746a6a63e92bc)).

**Comment by galderz** [comment]
@ppalaga I'll try your branch later on

**Comment by geoand** [comment]
cc @gsmet @aloubyansky

**Comment by aloubyansky** [comment]
I think it makes sense. We should probably make its purpose clear in its comments (and docs) to avoid misuse. Which, as I understand, facilitate testing config of external extensions. And in case of high demand we could move certain things from it to the runtime BOM eventually.

**Comment by ppalaga** [comment]
> We should probably make its purpose clear in its comments

I have added a description https://github.com/quarkusio/quarkus/pull/9104/files#diff-28c5659b9e1dced68146f7cfe2fbb1bfR16
