### ISSUE TITLE
Security: Support password algorithms besides MD5 in elytron-security-properties-file extension

### ISSUE THREAD

**Issue by tdussmann** [quarkusio/quarkus#9122]
**Description**
When using quarkus for our services we'd like to utilize the existing extensions as much as possible, instead of reinventing the wheel. For adding a straight-forward basic authentication to a service that does not use jdbc at all we looked into [_elytron-security-properties-file_](https://quarkus.io/guides/security-properties). 
However at the moment this extension does only support passwords either stored as plaintext or hashed as HEX( MD5( username ":" realm ":" password ) ). For us however, the use of MD5 is not allowed anymore according to internal security guidelines. Given the easily achievable hash rates for MD5 at the current time I think the risk of brute forcing a hash like this is indeed rather high. 

Since the extension acts as a wrapper around _Wildfly Elytron_, which supports [other, more secure digest algorithms](https://docs.wildfly.org/17/WildFly_Elytron_Security.html#Passwords) it should be possible to extend the configuration from plaintext true/false to a larger set of algorithms that can be passed through to Elytron. 

**Implementation ideas**
Replace the hard-coded MD5 digest algorithm in elytron-security-properties-file extension with a configurable value. 
https://github.com/quarkusio/quarkus/blob/6fedd3061fbfaf424dce86d9ed0d2a7c6dea0126/extensions/elytron-security-properties-file/runtime/src/main/java/io/quarkus/elytron/security/runtime/ElytronPropertiesFileRecorder.java#L144-L146

Then, when [configuring](https://quarkus.io/guides/security-properties#quarkus-elytron-security_quarkus.security.users.embedded.plain-text) the elytron-security-properties-file extension instead of specifying the boolean property `quarkus.security.users.embedded.plain-text` , we could pass in a choice of (a subset of) Elytron's supported digests that gets passed to its `PasswordFactory` when the realm is loaded from the properties file.

**Comment by lower-case** [comment]
Hi @sberyozkin , I'd like to work on this enhancement. I'm new to Quarkus. Please review my Draft PR and provide your suggestions. 
Thanks in Advance!!
