### ISSUE TITLE
quarkus-smallrye-jwt JWT generation code fails to load the token resource in the dev mode 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#9135]
**Describe the bug**
@radcortez has reported an issue that the token resources are not loaded in the dev mode. An issue around loading the keys [was also reported in Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Smallrye.20KeyUtils) if KeyUtis are used directly

**Comment by radcortez** [comment]
Thanks @sberyozkin.

Btw, the code that loads the keys for validation seems to work fine. The issue is with the following API:

```java
Jwt.claims(resource)

// calls JwtSigningUtils.java:279
InputStream contentIS = JwtSigningUtils.class.getResourceAsStream(jsonResName);
```

In dev mode you get a NPE. Works fine in standard VM mode (haven't tried it in native yet).

**Comment by sonu3706** [comment]
Verified in native as well it throws NPE.

**Comment by sberyozkin** [comment]
Will be fixed with the next smallrye-jwt release

**Comment by sonu3706** [comment]
Thanks @sberyozkin
