### ISSUE TITLE
Support for Custom Named Injections

### ISSUE THREAD

**Issue by cpmoore** [quarkusio/quarkus#9136]
Currently quarkus supports named datasources.  This allows for multiple properties to be configured per each injected instance. 
From the documentation:
```
@Inject
@DataSource("inventory")
AgroalDataSource inventoryDataSource;
```

I would like to see similar support added for custom classes
```
@Inject
@Prefix("hello")
Greeting hello

@Inject
@Prefix("goodbye")
Greeting goodbye
```

Then in application.properties
```
greeting.hello.message=hello there General Kenobi
greeting.goodbye.message=these are not the droids you're looking for
```

I'm aware that there is already support for `ConfigProperties(prefix="whatever")` however there doesn't seem to be a way to set the prefix dynamically.

**Comment by mkouba** [comment]
I'm not sure I fully understand. So this should only work for config properties?

cc @geoand you might be interested in this one.

**Comment by geoand** [comment]
Right, this is indeed very interesting.

So basically you want `ConfigProperties` but with the prefix set at the call-site, right?

**Comment by cpmoore** [comment]
@geoand 

Bingo! In my opinion it would allow for easier reuse of custom libraries. Glad you figured out what I meant, I’m not always great at fully explaining my ideas. lol

**Comment by geoand** [comment]
Thanks for confirming! 

It's an interesting addition, I'll look into it.
