### ISSUE TITLE
Warn when using old image in Docker files

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#9149]
**Description**
In a project that started around quarkus 0.x we have old base images (`fabric8/java-alpine-openjdk8-jre` for the JVM version). We bump quarkus version from time to time but the base images get forgotten - it would be nice if `quarkus:dev` or similar often run feature would warn about using image that's not tested with recent quarkus.

**Implementation ideas**
Also the quarkus app itself could check the base image version and complain if it is started in such. Not sure if the info would be somehow accessible from within the container (without using custom base images).

**Comment by geoand** [comment]
Closing this as `fabric8/java-alpine-openjdk8-jre` is way out of date as this point, but we can certainly look into doing something similar in the future
