### ISSUE TITLE
create a camel group 

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#9150]
GitHub IDs:

- davsclaus
- lburgazzoli
- ppalaga
- jamesnetherton

**Comment by maxandersen** [comment]
github group @quarkusio/camel created - 3 pending invites that needs confirming before they will get notiifed.

if you want zulip i'll need their zulip names too..

**Comment by lburgazzoli** [comment]
can you also add gnodet ?

**Comment by maxandersen** [comment]
all done.
