### ISSUE TITLE
Command mode doesn't exit after unchecked exception

### ISSUE THREAD

**Issue by targeter21** [quarkusio/quarkus#9163]
**Describe the bug**
Command mode projects will not exit if an unchecked exception occurs (might not only be that, but that's how I reproduced it.). It will show the stacktrace then sit doing nothing.

**Expected behavior**
I would expect the application to exit after the stacktrace and any following code has executed.

**Actual behavior**
It shows the stacktrace but does nothing afterwards.

**To Reproduce**
1. Create an empty quarkus command mode project with the following code:
JavaMain:
```
@QuarkusMain
public class JavaMain
{
  public static void main(String... args) {
    Quarkus.run(Testing.class, args);
  }
}
```
Testing.java:
```
public class Testing implements QuarkusApplication
{
  @Override
  public int run(final String... args) {
    boolean willFail = args[0].equals("foo");

    return 0;
  }
}
```
2. Run either in Intellij or command line. Behavior was observed to be the same in Intellij and dockerized native image.

**Configuration**
No additional configuration is needed.

**Screenshots**
<img width="1571" alt="Screen Shot 2020-05-07 at 11 17 48 AM" src="https://user-images.githubusercontent.com/6563769/81319157-e1502500-9054-11ea-894b-c6c61b7f2150.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
**Darwin MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64**
 - Output of `java -version`: 
**openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)**
 - GraalVM version (if different from Java): 
**Used the default Quarkus native build plugins**
 - Quarkus version or git rev: 
**1.4.1.Final**
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
**Tested with mvnw and mvn, both 3.6.3**

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
I can reproducer this
