### ISSUE TITLE
Certificate validation error while connecting to DocumentDB (via native) on aws

### ISSUE THREAD

**Issue by amenic-hub** [quarkusio/quarkus#9165]
**Describe the bug**
Hi everyone, I'm experiencing a problem while connecting to AWS DocumentDB using tls-encrypted connection.
Actually it happens only when building the executable in native mode, since by building as standard java application there's no issue.
Let's start by saying that I built the trustore following this guide:
[DocumentDB and TLS](https://docs.aws.amazon.com/documentdb/latest/developerguide/connect_programmatically.html)
Then I'm copying the trustore in the /work/ directory where the native executable stands, I run the executable passing "-Djavax.net.ssl.trustStore=/work/trustore" system property but I get the exception pasted below.

In order to create the native executable, enabled to leverage on SSL, I followed this guide:
[native and ssl](https://quarkus.io/guides/native-and-ssl)

**I'd like to highlight that if I use the same trustore, in the same way but with the standard java artifact (by omitting -Pnative -Dquarkus.native.container-build=true ) the application works like a charm.**

**Expected behavior**
The application to properly connect to DocumentDB (MongoDB compatible), validating the certificate and performing the handshake successfully

**Actual behavior**
Actually I get this exception:
`com.mongodb.MongoSocketWriteException: Exception sending message
        at com.mongodb.internal.connection.InternalStreamConnection.translateWriteException(InternalStreamConnection.java:550)
        at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:432)
        at com.mongodb.internal.connection.InternalStreamConnection.sendCommandMessage(InternalStreamConnection.java:272)
        at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:256)
        at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:83)
        at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:33)
        at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:103)
        at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:60)
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:641)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:716)
        at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:969)
        at com.mongodb.internal.connection.SocketStream.write(SocketStream.java:99)
        at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:429)
        ... 11 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
        at sun.security.validator.Validator.validate(Validator.java:264)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625)
        ... 25 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
        ... 31 more`

**Configuration**
```properties
  application.yaml: |-
    quarkus:
      log:
        level: INFO

      mongodb:
        connection-string: mongodb://<MY_HOSTNAME>:27017/?ssl=true&sslVerifyCertificate=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=true
        tls: true
        tls-insecure: false
        credentials:
          username: <MY_USERNAME>
          password: <MY_PASSWORD>
          auth-source: <MY_AUTH_SOURCE>

```

**Environment (please complete the following information):**
 - GraalVM version: I built the native executable using quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 
 - Quarkus version: 1.4.2.Final
 - DocumentDB engine: docdb 3.6.0

**Context:**
I have my application deployed onto Kubernetes (EKS), connecting to MongoDB.
The image is built using following Dockerfile:
```
FROM registry.access.redhat.com/ubi8/ubi-minimal

WORKDIR /work/

COPY target/*-runner /work/application
COPY rds-truststore.jks /work/trustore

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djavax.net.ssl.trustStore=/work/trustore", "-Djavax.net.ssl.trustStorePassword=<MY_PASSWORD>"]
```

This is the command I use in order to create the executable:
`./mvnw clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.ssl.native=true`
The last parameter should be redundant as I am using the quarkus-provided dependency 
```
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-client</artifactId>
   </dependency>
```

If it can be of any help, by running together the image produced and a local mongodb (by using a docker-compose file) with no tls encryption, it works... so the issue is strictly related to the TLS handshaking phase.

**Comment by oztimpower** [comment]
Hi @amenic-hub this is the cacerts and libsunec.so issue. It's covered in the AWS Lambda Quarkus Extension docs.

May I ask what Quarkus extensions you are using, i.e. are you making these calls from AWS Lambda?

**Comment by amenic-hub** [comment]
Hi @oztimpower and many thanks for your reply.

Actually I revised my dockerfile so that I can include the `libsunec.so` but I get the same exception.

As far as I can understand, in order to connect to Amazon DocumentDB I'm requested to use AWS-provided certificate authority that is not shipped in the default java/graalvm cacert, so I'm still using my custom trustore.
If you want to give it a try, I can move all certificates in my trustore into the default cacert... even though I don't think that's the issue.

Here is my new multistage Dockerfile
```
FROM quay.io/quarkus/ubi-quarkus-native-image:20.0.0-java11 as nativebuilder
RUN mkdir -p /tmp/ssl \
  && cp /opt/graalvm/lib/libsunec.so /tmp/ssl/
  
  
FROM registry.access.redhat.com/ubi8/ubi-minimal

WORKDIR /work/

COPY --from=nativebuilder /tmp/ssl/ /work/ssl
COPY target/*-runner /work/application
COPY rds-truststore.jks /work/trustore

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djava.library.path=/work/ssl", "-Djavax.net.ssl.trustStore=/work/trustore", "-Djavax.net.ssl.trustStorePassword=<MY_PASSWORD>"]
```

**Comment by oztimpower** [comment]
Thanks yeah I would be keen to give it try. I do a lot of work work EKS. More DynamoDB than DocumentDB, but it is an interesting challenge.

**Comment by amenic-hub** [comment]
Well, I did... but unfortunately I keep getting the exception.

This is the full content of my cacerts file:
```
Trust store content is:
 Certificate actalisauthenticationrootca [jdk] expires in 'Sun Sep 22 13:22:02 CEST 2030'
 Certificate addtrustclass1ca [jdk] expires in 'Sat May 30 12:38:31 CEST 2020'
 Certificate addtrustexternalca [jdk] expires in 'Sat May 30 12:48:38 CEST 2020'
 Certificate addtrustqualifiedca [jdk] expires in 'Sat May 30 12:44:50 CEST 2020'
 Certificate affirmtrustcommercialca [jdk] expires in 'Tue Dec 31 15:06:06 CET 2030'
 Certificate affirmtrustnetworkingca [jdk] expires in 'Tue Dec 31 15:08:24 CET 2030'
 Certificate affirmtrustpremiumca [jdk] expires in 'Mon Dec 31 15:10:36 CET 2040'
 Certificate affirmtrustpremiumeccca [jdk] expires in 'Mon Dec 31 15:20:24 CET 2040'
 Certificate amazon rds af-south-1 ca expires in 'Mon Oct 28 19:06:53 CET 2024'
 Certificate amazon rds af-south-1 root ca expires in 'Sat Oct 26 20:05:58 CEST 2024'
 Certificate amazon rds ap-east-1 ca expires in 'Wed Jun 01 14:00:00 CEST 2022'
 Certificate amazon rds ap-east-1 root ca expires in 'Fri Feb 16 03:46:11 CET 2024'
 Certificate amazon rds ap-northeast-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds ap-northeast-2 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds ap-northeast-3 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds ap-south-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds ap-southeast-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds ap-southeast-2 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds beta root 2019 ca expires in 'Mon Aug 19 19:38:26 CEST 2024'
 Certificate amazon rds beta us-east-1 2019 ca expires in 'Mon Aug 19 19:38:26 CEST 2024'
 Certificate amazon rds ca-central-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds eu-central-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds eu-north-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds eu-south-1 ca expires in 'Wed Oct 30 21:21:30 CET 2024'
 Certificate amazon rds eu-south-1 root ca expires in 'Mon Oct 28 21:20:36 CET 2024'
 Certificate amazon rds eu-west-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds eu-west-2 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds eu-west-3 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds me-south-1 ca expires in 'Sun Jun 01 14:00:00 CEST 2025'
 Certificate amazon rds me-south-1 root ca expires in 'Wed May 08 23:48:27 CEST 2024'
 Certificate amazon rds preview root 2019 ca expires in 'Thu Aug 22 00:29:49 CEST 2024'
 Certificate amazon rds preview us-east-2 2019 ca expires in 'Thu Aug 22 00:29:49 CEST 2024'
 Certificate amazon rds root 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds sa-east-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds us-east-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds us-east-2 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds us-west-1 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazon rds us-west-2 2019 ca expires in 'Thu Aug 22 19:08:50 CEST 2024'
 Certificate amazonrootca1 [jdk] expires in 'Sun Jan 17 01:00:00 CET 2038'
 Certificate amazonrootca2 [jdk] expires in 'Sat May 26 02:00:00 CEST 2040'
 Certificate amazonrootca3 [jdk] expires in 'Sat May 26 02:00:00 CEST 2040'
 Certificate amazonrootca4 [jdk] expires in 'Sat May 26 02:00:00 CEST 2040'
 Certificate baltimorecybertrustca [jdk] expires in 'Tue May 13 01:59:00 CEST 2025'
 Certificate buypassclass2ca [jdk] expires in 'Fri Oct 26 10:38:03 CEST 2040'
 Certificate buypassclass3ca [jdk] expires in 'Fri Oct 26 10:28:58 CEST 2040'
 Certificate camerfirmachambersca [jdk] expires in 'Sat Jul 31 14:29:50 CEST 2038'
 Certificate camerfirmachamberscommerceca [jdk] expires in 'Wed Sep 30 18:13:44 CEST 2037'
 Certificate camerfirmachambersignca [jdk] expires in 'Sat Jul 31 14:31:40 CEST 2038'
 Certificate certumca [jdk] expires in 'Fri Jun 11 12:46:39 CEST 2027'
 Certificate certumtrustednetworkca [jdk] expires in 'Mon Dec 31 13:07:37 CET 2029'
 Certificate chunghwaepkirootca [jdk] expires in 'Wed Dec 20 03:31:27 CET 2034'
 Certificate comodoaaaca [jdk] expires in 'Mon Jan 01 00:59:59 CET 2029'
 Certificate comodoeccca [jdk] expires in 'Tue Jan 19 00:59:59 CET 2038'
 Certificate comodorsaca [jdk] expires in 'Tue Jan 19 00:59:59 CET 2038'
 Certificate digicertassuredidg2 [jdk] expires in 'Fri Jan 15 13:00:00 CET 2038'
 Certificate digicertassuredidg3 [jdk] expires in 'Fri Jan 15 13:00:00 CET 2038'
 Certificate digicertassuredidrootca [jdk] expires in 'Mon Nov 10 01:00:00 CET 2031'
 Certificate digicertglobalrootca [jdk] expires in 'Mon Nov 10 01:00:00 CET 2031'
 Certificate digicertglobalrootg2 [jdk] expires in 'Fri Jan 15 13:00:00 CET 2038'
 Certificate digicertglobalrootg3 [jdk] expires in 'Fri Jan 15 13:00:00 CET 2038'
 Certificate digicerthighassuranceevrootca [jdk] expires in 'Mon Nov 10 01:00:00 CET 2031'
 Certificate digicerttrustedrootg4 [jdk] expires in 'Fri Jan 15 13:00:00 CET 2038'
 Certificate dtrustclass3ca2 [jdk] expires in 'Mon Nov 05 09:35:58 CET 2029'
 Certificate dtrustclass3ca2ev [jdk] expires in 'Mon Nov 05 09:50:46 CET 2029'
 Certificate entrust2048ca [jdk] expires in 'Tue Jul 24 16:15:12 CEST 2029'
 Certificate entrustevca [jdk] expires in 'Fri Nov 27 21:53:42 CET 2026'
 Certificate entrustrootcaec1 [jdk] expires in 'Fri Dec 18 16:55:36 CET 2037'
 Certificate entrustrootcag2 [jdk] expires in 'Sat Dec 07 18:55:54 CET 2030'
 Certificate geotrustglobalca [jdk] expires in 'Sat May 21 06:00:00 CEST 2022'
 Certificate geotrustprimaryca [jdk] expires in 'Thu Jul 17 01:59:59 CEST 2036'
 Certificate geotrustprimarycag2 [jdk] expires in 'Tue Jan 19 00:59:59 CET 2038'
 Certificate geotrustprimarycag3 [jdk] expires in 'Wed Dec 02 00:59:59 CET 2037'
 Certificate geotrustuniversalca [jdk] expires in 'Sun Mar 04 06:00:00 CET 2029'
 Certificate globalsignca [jdk] expires in 'Fri Jan 28 13:00:00 CET 2028'
 Certificate globalsigneccrootcar4 [jdk] expires in 'Tue Jan 19 04:14:07 CET 2038'
 Certificate globalsigneccrootcar5 [jdk] expires in 'Tue Jan 19 04:14:07 CET 2038'
 Certificate globalsignr2ca [jdk] expires in 'Wed Dec 15 09:00:00 CET 2021'
 Certificate globalsignr3ca [jdk] expires in 'Sun Mar 18 11:00:00 CET 2029'
 Certificate globalsignrootcar6 [jdk] expires in 'Sun Dec 10 01:00:00 CET 2034'
 Certificate godaddyclass2ca [jdk] expires in 'Thu Jun 29 19:06:20 CEST 2034'
 Certificate godaddyrootg2ca [jdk] expires in 'Fri Jan 01 00:59:59 CET 2038'
 Certificate identrustcommercial [jdk] expires in 'Mon Jan 16 19:12:23 CET 2034'
 Certificate identrustdstx3 [jdk] expires in 'Thu Sep 30 16:01:15 CEST 2021'
 Certificate identrustpublicca [jdk] expires in 'Mon Jan 16 18:53:32 CET 2034'
 Certificate keynectisrootca [jdk] expires in 'Tue May 26 02:00:00 CEST 2020'
 Certificate letsencryptisrgx1 [jdk] expires in 'Mon Jun 04 13:04:38 CEST 2035'
 Certificate luxtrustglobalroot2ca [jdk] expires in 'Mon Mar 05 14:21:57 CET 2035'
 Certificate luxtrustglobalrootca [jdk] expires in 'Wed Mar 17 10:51:37 CET 2021'
 Certificate quovadisrootca [jdk] expires in 'Wed Mar 17 19:33:33 CET 2021'
 Certificate quovadisrootca1g3 [jdk] expires in 'Sun Jan 12 18:27:44 CET 2042'
 Certificate quovadisrootca2 [jdk] expires in 'Mon Nov 24 19:23:33 CET 2031'
 Certificate quovadisrootca2g3 [jdk] expires in 'Sun Jan 12 19:59:32 CET 2042'
 Certificate quovadisrootca3 [jdk] expires in 'Mon Nov 24 20:06:44 CET 2031'
 Certificate quovadisrootca3g3 [jdk] expires in 'Sun Jan 12 21:26:32 CET 2042'
 Certificate secomscrootca1 [jdk] expires in 'Sat Sep 30 06:20:49 CEST 2023'
 Certificate secomscrootca2 [jdk] expires in 'Tue May 29 07:00:39 CEST 2029'
 Certificate securetrustca [jdk] expires in 'Mon Dec 31 20:40:55 CET 2029'
 Certificate soneraclass2ca [jdk] expires in 'Tue Apr 06 09:29:40 CEST 2021'
 Certificate starfieldclass2ca [jdk] expires in 'Thu Jun 29 19:39:16 CEST 2034'
 Certificate starfieldrootg2ca [jdk] expires in 'Fri Jan 01 00:59:59 CET 2038'
 Certificate starfieldservicesrootg2ca [jdk] expires in 'Fri Jan 01 00:59:59 CET 2038'
 Certificate swisssigngoldg2ca [jdk] expires in 'Sat Oct 25 10:30:35 CEST 2036'
 Certificate swisssignplatinumg2ca [jdk] expires in 'Sat Oct 25 10:36:00 CEST 2036'
 Certificate swisssignsilverg2ca [jdk] expires in 'Sat Oct 25 10:32:46 CEST 2036'
 Certificate teliasonerarootcav1 [jdk] expires in 'Mon Oct 18 14:00:50 CEST 2032'
 Certificate thawtepremiumserverca [jdk] expires in 'Sat Jan 02 00:59:59 CET 2021'
 Certificate thawteprimaryrootca [jdk] expires in 'Thu Jul 17 01:59:59 CEST 2036'
 Certificate thawteprimaryrootcag2 [jdk] expires in 'Tue Jan 19 00:59:59 CET 2038'
 Certificate thawteprimaryrootcag3 [jdk] expires in 'Wed Dec 02 00:59:59 CET 2037'
 Certificate ttelesecglobalrootclass2ca [jdk] expires in 'Sun Oct 02 01:59:59 CEST 2033'
 Certificate ttelesecglobalrootclass3ca [jdk] expires in 'Sun Oct 02 01:59:59 CEST 2033'
 Certificate usertrusteccca [jdk] expires in 'Tue Jan 19 00:59:59 CET 2038'
 Certificate usertrustrsaca [jdk] expires in 'Tue Jan 19 00:59:59 CET 2038'
 Certificate utnuserfirstobjectca [jdk] expires in 'Tue Jul 09 20:40:36 CEST 2019'
 Certificate verisignclass2g2ca [jdk] expires in 'Wed Aug 02 01:59:59 CEST 2028'
 Certificate verisignclass3ca [jdk] expires in 'Thu Aug 03 01:59:59 CEST 2028'
 Certificate verisignclass3g2ca [jdk] expires in 'Wed Aug 02 01:59:59 CEST 2028'
 Certificate verisignclass3g3ca [jdk] expires in 'Thu Jul 17 01:59:59 CEST 2036'
 Certificate verisignclass3g4ca [jdk] expires in 'Tue Jan 19 00:59:59 CET 2038'
 Certificate verisignclass3g5ca [jdk] expires in 'Thu Jul 17 01:59:59 CEST 2036'
 Certificate verisigntsaca [jdk] expires in 'Sat Jan 02 00:59:59 CET 2021'
 Certificate verisignuniversalrootca [jdk] expires in 'Wed Dec 02 00:59:59 CET 2037'
 Certificate xrampglobalca [jdk] expires in 'Mon Jan 01 06:37:19 CET 2035'
```

As you can see is made up of default CAs, plus the ones imported with the aws-provided script.

This is my updated dockerfile
```
FROM quay.io/quarkus/ubi-quarkus-native-image:20.0.0-java11 as nativebuilder

RUN mkdir -p /tmp/ssl && cp /opt/graalvm/lib/libsunec.so /tmp/ssl/
  
  
FROM registry.access.redhat.com/ubi8/ubi-minimal

WORKDIR /work/

COPY --from=nativebuilder /tmp/ssl/ /work/ssl
COPY target/*-runner /work/application
COPY src/main/docker/cacerts /work/cacerts

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

ENTRYPOINT [ "./application", \
              "-Dquarkus.http.host=0.0.0.0", \
              "-Djava.library.path=/work/ssl", \
              "-Djavax.net.ssl.trustStore=/work/cacerts", \
              "-Djavax.net.ssl.trustStorePassword=changeit", \
              "-Djavax.net.ssl.trustAnchors=/work/cacerts" \
]
```

Is the mongo client looking at system properties when built in native mode? It seems like properties are ignored.

**Comment by oztimpower** [comment]
Hi @amenic-hub, any chance you have a trimmed down version of the application for me test? Finally have some time to look at it.

**Comment by marcinczeczko** [comment]
Wondering if quarkus mongodb client could use truststore related options: https://docs.mongodb.com/manual/reference/connection-string/#urioption.tlsCertificateKeyFile that allows to provide TLS certificate keys/password, root CA etc. ?

**Comment by loicmathieu** [comment]
@marcinczeczko this is not related to this issue, better ask this on StackOverflow or Zulip.
Anyway, you can use any options available inside the connection-string of MongoDB via the connection-string property. But we awas that if you package your application as a native image only certificate inside your JVM cacert file will be used.

**Comment by marcinczeczko** [comment]
@loicmathieu sorry, looks like I skipped some part of the issue desc. 
Anyway, I believe this issue might be connected with the way how graalvm treats root certs, as far as I remember it simply get them into the image at build time, so sys props at runtime simply does not have effect. 

@amenic-hub 
You can try building your app by providing those sys props when building native image, e.g. via 'quarkus.native.additional-build-args' on application.properties or in maven - see here for more options https://quarkus.io/guides/writing-native-applications-tips

**Comment by oztimpower** [comment]
@marcinczeczko That actually worked - adding to the additional native build args :)

First - I added the Amazon RDS certificates to the GraalVM cacerts, and used that in the app.

To build, Maven needed the location of the `cacerts`, and the `application.properties` also added the path `cacerts`.

Maven command:

`./mvnw -Djavax.net.ssl.trustStore=path-to-cacerts -Djavax.net.ssl.trustStorePassword=changeit package -Pnative` 

Application.properties:

`quarkus.native.additional-build-args= -Djavax.net.ssl.trustStore=path-to-cacerts, -Djavax.net.ssl.trustStorePassword=changeit`

`./target/myproject-runner` worked fine.

@amenic-hub I'll try this using your multi-stage docker build, and see I can bundle to EKS-Fargate

**Comment by oztimpower** [comment]
Confirmed working on local Docker, and also on `EKS` and `EKS-Fargate` (VPC Peering to DocDB). Used the Quarkus generated K8s extension.

Crude `Dockerfile` as below. The `cacerts` needed an explicit full path (I used `/tmp/cacerts` for the build and `application.properties` additional build args). Relative paths didn't work. 

Had to modify `.dockerignore` also to use a path to copy the `cacerts`, I used the `src/main/resources/cacerts` folder, and then softlinked to `/tmp/cacerts` to make it all work.

application.properties

```
quarkus.native.additional-build-args= -Djavax.net.ssl.trustStore=/tmp/cacerts, -Djavax.net.ssl.trustStorePassword=changeit
```

Dockerfile.native

```
FROM ubuntu:18.04

WORKDIR /work/
COPY --chown=1001:root target/classes/cacerts /tmp/cacerts

COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

Maven

```
./mvnw -Djavax.net.ssl.trustStore=/tmp/cacerts -Djavax.net.ssl.trustStorePassword=changeit clean package -Pnative
```
.dockerignore

```
*
!target/*-runner
!target/*-runner.jar
!target/lib/*
!target/classes/cacerts
```

**Comment by oztimpower** [comment]
@amenic-hub Can we close this now that I have demonstrated it's possible to generate a native-binary?

**Comment by amenic-hub** [comment]
Hi @oztimpower, I'm really sorry for my absence, but I was quite packed these weeks. I read your comments and I am going to integrate your suggestions in my code in the next week.

Anyway, as you've been able to mimic my environment with positive outcomes, we can close the issue now. Then I'll do it my business to update you/reopen in case of useful insights or unexpected behaviours.

Many thanks for your support!!
