### ISSUE TITLE
Quarkus Reactive Route misreads part of request URL as path variable

### ISSUE THREAD

**Issue by KienDangTran** [quarkusio/quarkus#9200]
**Describe the bug**
I have 2 routes like this: 
```java
@Route(path = "/accounts/:id", methods = HttpMethod.GET)
void getAccount(RoutingContext ctx) {
  ...
}

@Route(path = "/accounts/me", methods = HttpMethod.GET)
void getCurrentUserAccount(RoutingContext ctx) {
  ...
}
```
but quarkus reactive route always read `me` as `id` param and throw error.

**Comment by cescoffier** [comment]
Conflict resolution documented in https://github.com/quarkusio/quarkus/pull/9203.

**Comment by cescoffier** [comment]
You need to add the `order` attribute to evaluate the routes in the right order:

```
    public static class MyRoutes {

        @Route(path = "/conflict/:id", methods = HttpMethod.GET, order = 2)
        void getAccount(RoutingContext ctx) {
            ctx.response().end(ctx.pathParam("id"));
        }

        @Route(path = "/conflict/me", methods = HttpMethod.GET, order = 1)
        void getCurrentUserAccount(RoutingContext ctx) {
            ctx.response().end("/me called");
        }

    }
```

**Comment by spligo** [comment]
I have a similar problem but with quarkus-resteasy: 
`@Get
@Path("/accounts/{id}")
@Produces(MediaType.APPLICATION_JSON)
public Response getAccount(@PathParam("id") String id) {
  ...
}

@Get
@Path("/accounts/me")
@Produces(MediaType.APPLICATION_JSON)
public Response getCurrentUserAccount() {
  ...
}`

Is there a similar solution for this?

`https://stackoverflow.com/questions/66651426/is-there-a-way-to-order-path-in-quarkus`
