### ISSUE TITLE
Cannot execute more than 16384 requests without slow down in responses

### ISSUE THREAD

**Issue by dawiki** [quarkusio/quarkus#9202]
**Describe the bug**
When executing a lot of http requests, the application slows down (stops?!) responding after about 16384 requests sent. It is not always exactly that number but reasonably close

**Expected behavior**
Application is responding to http requests as quickly as possible considering system load and computation requirements

**Actual behavior**
The sample app ("GET /hello" -> hello response) stops responding after about 16384 requests

**To Reproduce**
1. download unchanged code.quarkus.io sample app
2. package `./mvnw package`
3. run `java -jar target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar`
4. execute apache bench load test `ab -c 10 -n 20000 http://localhost:8080/hello` -> does not finish. Stops at about 16384

**Apache Benchmark output**
```
 dawiki@daWikiMac  ~  ab -c 10 -n 20000  http://localhost:8080/hello
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 16338 requests completed
 ✘ dawiki@daWikiMac  ~  ab -c 10 -n 20000  http://localhost:8080/hello
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 16384 requests completed
 ✘ dawiki@daWikiMac  ~  ab -c 10 -n 20000  http://localhost:8080/hello
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 16394 requests completed
 ✘ dawiki@daWikiMac  ~ 
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin daWikiMac.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

 - Output of `java -version`: 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Maven home: /Users/dawiki/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Users/dawiki/.sdkman/candidates/java/11.0.2-open
Default locale: en_AT, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
cc @johnaohara

**Comment by johnaohara** [comment]
I can not recreate this on Linux using ab `Version 2.3 <$Revision: 1843412 $>`, it runs to completion for me.  Is there anyone with a mac that can recreate?  

@dawiki  what happens if you use a different load generation tool?
e.g 

1) download https://github.com/Hyperfoil/Hyperfoil/releases/download/release-0.8/hyperfoil-0.8.zip
2) unzip hyperfoil-0.8.zip
3) ./hyperfoil-0.8/bin/wrk.sh -c 10 -d 10s http://localhost:8080/hello

I just ran against the sample app and saw
`273669 requests in 10.0s,  33.41MB read`

**Comment by dawiki** [comment]
hmmm .. looks like it is related to apache bench

```
Running for 10s test @ http://localhost:8080/hello
2 threads and 10 connections

benchmark finished
                  Avg     Stdev       Max
Latency:    191,52 μs  90,82 μs   3,83 ms
451887 requests in 9.999s,  55,16MB read
Requests/sec: 45193,22
Transfer/sec:   5,52MB
```

**Comment by dawiki** [comment]
@johnaohara if it is ok for you I will close this ticket

**Comment by johnaohara** [comment]
@dawiki thank you for confirming, yes you can close this issue
