### ISSUE TITLE
MQTT client disconnects when receiving longer messages

### ISSUE THREAD

**Issue by jnsfrg** [quarkusio/quarkus#9204]
**Describe the bug**
In our application we are using the smallrye-mqtt extension to integrate our service into our existing landscape. When we try to receive MQTT messages containing more than ~9000 characters, the message is not passed to the @Incoming function nor is there any error message. After the sending the longer message the client disconnect from the MQTT Broker and doesn't receive any further Messages. 

We are also able to reproduce this using the MQTT Quickstart project https://github.com/quarkusio/quarkus-quickstarts/tree/master/mqtt-quickstart and tweaking it to just log the incoming string instead of forwarding the prices.

**Expected behavior**
The message is received and the client stays connected to the broker.

**Actual behavior**
No message is logged and the client silently disconnects from the broker. 

**To Reproduce**
1. Tweak the mqtt-quickstart to just log prices as String
2. Send a mqtt message to "prices" with a payload of 10.000 characters
3. check the broker for connected clients.

**Configuration**
```properties
# Configure the MQTT source (we read from it)
mp.messaging.incoming.prices.type=smallrye-mqtt
mp.messaging.incoming.prices.topic=prices
mp.messaging.incoming.prices.host=localhost
mp.messaging.incoming.prices.port=1883
mp.messaging.incoming.prices.auto-generated-client-id=true
```

**Environment (please complete the following information):**
- Output of `java -version`: 
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```
 - Broker: hivemq 4.2.3
 - Quarkus version or git rev: 1.4.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
incoming Method:
```
    @Incoming("prices")
    public void process(byte[] priceRaw) {
        System.out.println("Receiving price: " + new String(priceRaw));
    }
```

**Comment by geoand** [comment]
cc @cescoffier @michalszynkiewicz

**Comment by cescoffier** [comment]
Which broker are you using?

**Comment by jnsfrg** [comment]
> Which broker are you using?

I am using a HiveMQ Broker v4.2.3 via the official docker image hivemq/hivemq4:4.2.3

**Comment by cescoffier** [comment]
Thanks! I will try to reproduce it and come back to you.

**Comment by gautric** [comment]
hi @cescoffier 

we can reproduce it with mosquitto too.

I just send this command (`mvnw` file is over 10k)

> mosquitto_pub -i CLI -t prices -f mvnw

```
mosquitto_1  | 1589202256: New connection from 172.18.0.1 on port 1883.
mosquitto_1  | 1589202256: New client connected from 172.18.0.1 as CLI (p2, c1, k60).
mosquitto_1  | 1589202256: Client CLI disconnected.
mosquitto_1  | 1589202256: Socket error on client cee05f71-0688-4ff9-899f-7d359b35eeb0, disconnecting.
```

**Comment by gautric** [comment]
hi all,

I think the max size (including header) is 8092 bytes.

I had noticed this information about this topic here.

https://github.com/vert-x3/vertx-mqtt/issues/10
https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/mqtt/mqtt.html#mqtt-installation
https://github.com/netty/netty/issues/9983

https://github.com/netty/netty/blob/4.1/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java#L42

**Comment by cescoffier** [comment]
Issue fixed upstream: https://github.com/smallrye/smallrye-reactive-messaging/pull/541.

**Comment by cescoffier** [comment]
To be fixed, it requires:

* a release of SmallRye Reactive Messaging
* Update the version in Quarkus

It should be done before 1.5.
