### ISSUE TITLE
Generated kubernetes for Ingress does not work in GKE

### ISSUE THREAD

**Issue by lfcortes12** [quarkusio/quarkus#9257]
Deploying to GKE with Ingress does not work properly due to GKE is not able to identify the backend services. The issue is fixed changing the script in this way:

Generated structure:

apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  labels:
    app.kubernetes.io/name: "servicename"
    app.kubernetes.io/version: "v3"
  name: "servicename"
spec:
  rules:
  - host: ""
    http:
      paths:
      - backend:
          serviceName: "servicename"
          servicePort: 8080
        path: "/"

It was fixed changing the paths like this:

apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  labels:
    app.kubernetes.io/name: "servicename"
    app.kubernetes.io/version: "v3"
  name: "servicename"
spec:
  rules:
  - host: ""
    http:
      paths:
      **- path: "/*"**
        backend:
          serviceName: "developer"
          servicePort: 8080 

Then, GKE was able to deploy the ingress correctly.

**Comment by geoand** [comment]
@iocanel I wonder if we can provide more options for customizing the Ingress

**Comment by geoand** [comment]
ping @iocanel :)

**Comment by geoand** [comment]
@iocanel does dekorate have a way to set the Ingress path?

**Comment by iocanel** [comment]
It should be trivial to do so. In dekorate land we do that automatically for spring boot apps.

**Comment by geoand** [comment]
Trivial as in "there is a property", or as in "write a decorator"?

**Comment by geoand** [comment]
Is this still an issue? I vaguely remember a related fix...

**Comment by iocanel** [comment]
I think this is still an issue

**Comment by geoand** [comment]
@lfcortes12 is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
