### ISSUE TITLE
Migrate to Vert.x 4

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9262]
- [ ] review security code
- [ ] perf review
- [x] Netty integration review
- [x] update Quarkus usage of vert.x to new v4 API
- [ ] documentation
- [x] context propagation
- [x] mutiny API
- [x] Microprofile 4 integration
- [x] SmallRye Reactive Messaging update (in progress)
- [x] Quarkus HTTP update (in progress)
- [ ] Hibernate Reactive update (in progress)
- [x] RESTEasy Reactive update

**Comment by davsclaus** [comment]
Apache Camel via camel-quarkus would also need to upgrade and support vertx 4 in some of our components/extensions.

**Comment by ppalaga** [comment]
Yeah, a branch where we could follow the progress would be nice

**Comment by cescoffier** [comment]
The code generator is almost ready. 
I will be able to create a branch soon, as we started having the first upstream components "VertexyFourized".

**Comment by pokusak** [comment]
Hi, 
any update on this?
Thanks.

**Comment by cjioh** [comment]
Hi
Any ETA for this?

**Comment by cescoffier** [comment]
Oh! Missing this issue. Yes, Quarkus 2.x uses vertx 4.
