### ISSUE TITLE
Exception java.util.ServiceConfigurationError thrown

### ISSUE THREAD

**Issue by gnodet** [quarkusio/quarkus#9273]
**Describe the bug**
In certain cases, tests throw an exception before being executed
```
java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
```

**Expected behavior**
The test can be run.

**Actual behavior**
An exception is thrown during the test initialization.

**To Reproduce**
Test available with PR #9274

**Environment (please complete the following information):**
 - Quarkus version or git rev: `1.4.2.Final`

**Comment by gnodet** [comment]
This looks similar to https://github.com/quarkusio/quarkus/issues/8210 but requires a different fix.

**Comment by gnodet** [comment]
The problem is that `io.smallrye.config.SmallRyeConfigFactory` is loaded by both the application classloader and the quarkus classloader without the quarkus classloader delegating to its parent (the application classloader).

It suppose it could be fixed by specifying a flag for the jar, but imho, it should work out of the box.

The original issue comes from `camel-quarkus`, where flags defined in the extension's runtime jar  are also used to enable/disable some integration tests.

**Comment by fstarred** [comment]
I had the same issue on a quarkus main application that involved some tasks using parallel().stream().
If I remove the parallel() operation, it works
