### ISSUE TITLE
Provide single MP Config value for getting effective HTTP port

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#9287]
I have noticed that the configuration value `quarkus.http.port` is injected as `8080` during a test run, but the webserver actually starts up on `8081`. This is preventing me from properly creating urls to test against.

Log output:
```
# port in URL gotten from quarkus.http.port
2020-05-13 22:47:41,345 INFO  [Test worker] (com.gjs.taskTimekeeper.webServer.server.LifecycleBean.onStart(LifecycleBean.java:74)                                         ) - Base URL: http://localhost:8080

# log output from quarkus
2020-05-13 22:47:41,512 INFO  [Test worker] (io.quarkus.runtime.Timing.printStartupTime(Timing.java:85)                                                                   ) - Quarkus 1.4.2.Final started in 6.747s. Listening on: http://0.0.0.0:8081
```

I would say that `quarkus.http.port` should be accurate to the actual port being listened on.

**Comment by geoand** [comment]
`quarkus.http.test-port` is the property that gives the port that tests run on.

Furthermore, in tests you can use the `test.url` MicroProfile Config value to get the URL of the running application.

Does that solve your issue, or are you looking for something more elaborate?

**Comment by GregJohnStewart** [comment]
Interesting. Good to know, just that I was expecting to have `quarkus.http.port` being the source of truth on what port the server was running on, test/dev/prod.

I see why it is this way, but I would argue it makes sense to keep things consistent. I have some instances where I am creating urls to pass back to the user, using `quarkus.http.port` for the port in the url. This makes it slightly harder to test, as I will potentially have to replace the port if I wanted to use the url as-is (if it was a link to a webpage, for example, just plugging it into selenium would not work).

I can see some ways around it, so not a real issue I guess.

Perhaps have a new config value like `quarkus.http.running-port` would allow for the centrallized port for whatever profile is currently running?

**Comment by geoand** [comment]
The problem I see with that is that there isn't a way to make `quarkus.http.running-port` read-only. 
I am sure that if we do add it, someone will expect to be able to set the port just by changing it

**Comment by GregJohnStewart** [comment]
I agree, but maybe that could be desirable? Like if one wanted to force the port value in any profile.

At any rate, ideally if the documentation mentions the relationship I think it would largely be fine.

Part of me thinks that this is a thing that one can easily overthink as well.

**Comment by geoand** [comment]
Would you like to add some documentation mentioning it?

**Comment by famod** [comment]
The test-port property documented here: https://quarkus.io/guides/getting-started-testing#controlling-the-test-port

But I guess this is not sufficient?

**Comment by GregJohnStewart** [comment]
I suppose it does, but it's really hard to know sometimes what configuration is available and how it relates to others. Of course that page does explain that particular config entry well, but I was looking for something else. Though it could just be a not knowing where to look/ lack of google fu on my end.

**Comment by sleberrigaud** [comment]
I'm facing a similar situation where I'd like to know the actual port being used by Quarkus, _before_ any request is made (so for example on `StartupEvent`). This becomes even more important when in tests (or prod) the configured port is `0` for randomization.

I couldn't find a way to access that port number at runtime. I've noticed that it's being set on `io.vertx.core.http.HttpServerOptions` but AFAICT this is not injectable, nor might it be desriable to make it injectable.

**Comment by gsmet** [comment]
Dunno how we can solve this but this looks like a very reasonable request.

/cc @stuartwdouglas

**Comment by geoand** [comment]
We can certainly make a read-only version of `HttpServerOptions` a bean that users can inject. WDYT?

**Comment by GregJohnStewart** [comment]
I mean I like the idea, just something that gives us access to current running port (wasn't sure if the question was directed at me, @geoand )

**Comment by geoand** [comment]
It wasn't directed to anyone specifically.

A CDI bean like the one I mentioned above shouldn't be hard to create and should solve the problem

**Comment by ppalaga** [comment]
This would indeed be handy in an integration test app which needs to know on which port is it running. The main problem is that the MP config property to check is different when running in JVM and native mode. For JVM it is `quarkus.http.test-port` and for native it is `quarkus.http.port`. To figure out the effective port one has to select one e.g. based on `"executable".equals(System.getProperty("org.graalvm.nativeimage.kind"))`:

```
    @ConfigProperty(name = "quarkus.http.test-port")
    int httpTestPort;
    @ConfigProperty(name = "quarkus.http.port")
    int httpPort;

    private String getEffectivePort() {
        final boolean isNativeMode = "executable".equals(System.getProperty("org.graalvm.nativeimage.kind"));
        return isNativeMode ? httpPort : httpTestPort;
    }
```

Another option is to pass the port form `RestAssured.port` to the app via `@QueryParam` or similar.

**Comment by yblazart** [comment]
Hello, I wanted to open a new issue but I saw this one.
In my case this is annoying. Because it's true that when quarkus.http.test-port is set to 0, the choosed port is not fallbacked to quarkus.http.port var.

In my code, I use quarkus.http.port in some services, and it give me 8080. Even  @RestClient do not work in this case.
It's usefull to use that in case of // maven builds.

For me, first we should only use %test.quarkus.http.port and if it's set to 0, it's choosed by quarkus and then it naturally fallback to quarkus.http.port.

Just my 2 cent.

**Comment by feitian124** [comment]
any progress or any guide? same issue here, need the the actual http port to do "consul http health check", but do not know how to find the running http port.

**Comment by feitian124** [comment]
@stuartwdouglas 
is it possible to get the running port? thanks

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/blob/d3325b53252fa33e8ca7c1103a95fc9149d37f62/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L928

This is set as a system property, so should be be able to read it from the property, either directly or using MP Config.

**Comment by ppalaga** [comment]
> https://github.com/quarkusio/quarkus/blob/d3325b53252fa33e8ca7c1103a95fc9149d37f62/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L928
> 
> This is set as a system property, so should be be able to read it from the property, either directly or using MP Config.

Is it possible to get the `launchMode` from application code?

I think the most of the folks here are asking for a simple direct way to obtain the effective port from an application code (and perhaps also from a test). A single property (new or exiting one) that works over all modes would be nice. Or a read-only injectable `HttpServerOptions` mentioned by @geoand. Or we should stop relying on `quarkus.http.test-port` and instead recommend using `%test.quarkus.http.port` so that `quarkus.http.port` always bears the effective value as suggested by @yblazart. All of the listed options would work for me.

**Comment by sleberrigaud** [comment]
@stuartwdouglas just adding my input here. From my point of view, I'm trying to run the application on a random port, using `http.port=0` and let quarkus decide which port at runtime. But I still need to know the actual port that was selected. So accessing the system property is not enough in that case.
