### ISSUE TITLE
No form based authentication with security-jpa

### ISSUE THREAD

**Issue by quachc** [quarkusio/quarkus#9292]
**Describe the bug**
I'm trying to implement form based login with my own user database using the `security-jpa` provider.

**Expected behavior**
I expect to be able to use `/j_security_check` to `POST` my credentials and obtain a "session" cookie so I can access secured resources.

**Actual behavior**
Every call to `j_security_check` returns `404 Not Found` and every call to a secured resources returns `403 Forbidden`.

**To Reproduce**
1. create an application as described by https://quarkus.io/guides/security-jpa
2. Enable form based authentication as described by https://quarkus.io/guides/security (see 'Configuration')

**Configuration**
```properties
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.redirect-after-login=false
```

**Environment (please complete the following information):**
 - Linux intrepid 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
 - Quarkus 1.4.2.Final
 - Gradle 6.4

**Additional context**
I attached a debugger and found that `io.quarkus.vertx.http.runtime.security.HttpAuthenticator#attemptAuthentication` could only use the `io.quarkus.vertx.http.runtime.security.HttpAuthenticator.NoAuthenticationMechanism` (which probably explains the 403 responses).
So I started digging around and found an empty if statement in `io.quarkus.vertx.http.deployment.HttpSecurityProcessor` on line 111.
Browsing the history I found that before 1.3.0.Final the line was:

```java
if (buildTimeConfig.auth.form.enabled) {
  beanProducer.produce(AdditionalBeanBuildItem.unremovableOf(FormAuthenticationMechanism.class));
}
```
I'm not able to find why this line was removed (I really dislike Github's history view) but I guess it could be the source of this issue.
Which suggests it's not really related to the `security-jpa` extension but form based authentication is broken in general.

**Comment by quachc** [comment]
Being kinda stuck with `security-jpa` I decided to check out `elytron-security-jdbc`.
I'm able to get form based login to work (`/j_security_check` is available), so my assumption that form based authentication is broken in general seems to be wrong.
Sadly, I ran into another issue: https://github.com/quarkusio/quarkus/issues/9296

**Comment by stuartwdouglas** [comment]
This will be fixed in 1.5

**Comment by geoand** [comment]
@stuartwdouglas should we close this as fixed https://github.com/quarkusio/quarkus/pull/8734?

**Comment by stuartwdouglas** [comment]
Yes. There is still a lot of work I want to do in this area to improve it,  but this issue is fixed.

**Comment by geoand** [comment]
Cool
