### ISSUE TITLE
Registry for extensions and platforms

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#9294]
**Description**
Part of #5962 

Provide notion of a registry that contain list of extensions, extension-releases  and platforms + additional metadata to use when quarkus tools need to query and operate on possible list of extensions.

**Comment by gastaldi** [comment]
Here is what I have prototyped so far: https://github.com/gastaldi/quarkus-extension-catalog

My idea is to have a GitHub Action that will generate a JSON file containing all the data resolved from the Maven repositories in the catalog when a GitHub Release is triggered. Thoughts?

**Comment by gastaldi** [comment]
Here are the model classes to transform the intermediary model in the extension catalog repository into the models understood by our plugins: https://github.com/gastaldi/quarkus-extension-catalog-service

**Comment by gastaldi** [comment]
Created https://github.com/quarkusio/quarkus-extension-catalog which produces a Docker image containing an HTTP Server producing the result JSON (https://quay.io/repository/quarkus/registry-app)
