### ISSUE TITLE
Default quarkus.http.access-log.pattern "common" duplicate query_string

### ISSUE THREAD

**Issue by joan-miralles** [quarkusio/quarkus#9295]
With default access-log configuration, the query string is duplicated in access-log.

**To Reproduce**
1. GET /myapp?someparam=1
2. In access-log appears: GET /myapp?someparam=value?someparam=value

**Comment by jaikiran** [comment]
I've raised https://github.com/quarkusio/quarkus/pull/9435 with a potential fix.
