### ISSUE TITLE
elytron-security-jdbc does not use attribute-mappings

### ISSUE THREAD

**Issue by quachc** [quarkusio/quarkus#9296]
**Describe the bug**
Role is not mapped from database to the Elytron realm

**Expected behavior**
Role should be mapped from the database to the security principal

**Actual behavior**
The configuration in `security-jdbc-quickstart` does not extract the `role` column from the database.
When debugging `io.quarkus.elytron.security.jdbc.PrincipalQueryConfig#attributeMappings` never gets populated.

**To Reproduce**
1. Download https://github.com/quarkusio/quarkus-quickstarts/tree/master/security-jdbc-quickstart
2. Follow the instructions to start the database and application
3. `curl -i -X GET -u user:user http://localhost:8080/api/users/me`

**Configuration**
Same as [here](https://github.com/quarkusio/quarkus-quickstarts/blob/master/security-jdbc-quickstart/src/main/resources/application.properties)

**Environment (please complete the following information):**
 - Linux intrepid 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
 - Quarkus 1.4.2.Final
 - Gradle 6.4

**Comment by stuartwdouglas** [comment]
This works in tests, but not in dev mode.
