### ISSUE TITLE
Make sure GraalVM 20.1 works for Quarkus

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9297]
We want support for Quarkus application build on GraalVM 20.1 native image

- [x] Core support for GraalVM 20.1 https://github.com/quarkusio/quarkus/pull/9486
- [x] Run extensions test with GraalVM 20.1
- [ ] Offer quarkus property to enable debug symblos (`quarkus.native.debug-symbols` ?)
- [ ] Add CI job to test `-H:+RemoveSaturatedTypeFlows` and `-H:+PrintAnalysisStatistics` as noted here oracle/graal#2384
- [ ] consider `--install-exit-handlers`

**Comment by jaikiran** [comment]
While doing this, perhaps we might want to have a CI job which enables (by default) `-H:+RemoveSaturatedTypeFlows` and `-H:+PrintAnalysisStatistics` as noted here https://github.com/oracle/graal/issues/2384. The graal team on their slack channel had requested projects to enable this setting and try out building native image and report any issues. This setting apparently is to help better native image build times.

**Comment by heubeck** [comment]
Hey guys, thank you for your dedication to this awesome project Quarkus.

Will you set the new native-image flag `--install-exit-handlers` by default?
Right now the signal handler has to be disabled when running Quarkus native built applications on Knative-serving.

Thank you and best regards

**Comment by emmanuelbernard** [comment]
@dmlloyd what would be the impact of `--install-exit-handler` by default?

**Comment by maxandersen** [comment]
> Hey guys, thank you for your dedication to this awesome project Quarkus.
> 
> 
> 
> Will you set the new native-image flag `--install-exit-handlers` by default?
> 
> Right now the signal handler has to be disabled when running Quarkus native built applications on Knative-serving.

Why is that actually ?

**Comment by dmlloyd** [comment]
> @dmlloyd what would be the impact of `--install-exit-handler` by default?

I'm not 100% sure, but if I had to guess, I'd say it wouldn't make a difference: our exit handler wouldn't be installed for those signals, but presumably theirs does the same thing as ours (exit the process with signal number + 128) so I think it'd likely be fine.  It should be fairly easy to test though.

**Comment by heubeck** [comment]
My assumption was that the `--install-exit-handler` flag would address/solve these issues:
https://github.com/quarkusio/quarkus/issues/4262
https://github.com/quarkusio/quarkus/issues/7589
But this was just a gut feeling.

**Comment by gsmet** [comment]
The heavy lifting of this one has been done.

If we need to expose more things, I think we probably need more focus issues opened by @dmlloyd or @galderz to tell us what we should to?

**Comment by dmlloyd** [comment]
AFAIK the exit handler thing won't fix the AWS issue.  The problem lies in a shared handler stub which uses forbidden APIs.
