### ISSUE TITLE
Unable to create instance of JwtClaimsBuilder

### ISSUE THREAD

**Issue by sonu3706** [quarkusio/quarkus#9298]
@bobmcwhirter @adietish @gunnarmorling @Sanne @stalep 

Issue while creating JWT token with quarkus-smallrye-jwt dependency
While creating token 

`  JwtClaimsBuilder claims = Jwt.claims(jsonResName);` throws NPE.
Initially thought file is not loading may be the path of the file is wrong, but when I 
tried to read the content of the file with below code, I am getting the content. So it means file path is correct.
`InputStream inputStream = JwtUtil.class.getResourceAsStream("/privateKey.pem")` 

Below is my piece of code to create token.

```

public static String generateTokenString(PrivateKey privateKey, String kid,
                                             String jsonResName, Map<String, Long> timeClaims) throws Exception {
        JwtClaimsBuilder claims = Jwt.claims(jsonResName);
        long currentTimeInSecs = currentTimeInSecs();
        long exp = timeClaims != null && timeClaims.containsKey(Claims.exp.name())
                ? timeClaims.get(Claims.exp.name()) : currentTimeInSecs + 300;

        claims.issuedAt(currentTimeInSecs);
        claims.claim(Claims.auth_time.name(), currentTimeInSecs);
        claims.expiresAt(exp);

        return claims.jws().signatureKeyId(kid).sign(privateKey);
    }

```

**Comment by sberyozkin** [comment]
@sonu3706 I've answered the question at https://stackoverflow.com/questions/61713369/unable-to-create-instance-of-jwtclaimsbuilder-in-quarkus-application. File system based resources will work in smallrye-jwt-2.1.2 release and Quarkus 1.5.0.

**Comment by sonu3706** [comment]
@sberyozkin  Thanks for the comment

**Comment by EfraimLA** [comment]
> @sonu3706 I've answered the question at https://stackoverflow.com/questions/61713369/unable-to-create-instance-of-jwtclaimsbuilder-in-quarkus-application. File system based resources will work in smallrye-jwt-2.1.2 release and Quarkus 1.5.0.

I just update to 1.5.0.Final and still cannot use file system resources, i get NPE in native mode
