### ISSUE TITLE
MQTT Messages are send to the wrong callbacks using a single client-id

### ISSUE THREAD

**Issue by jnsfrg** [quarkusio/quarkus#9302]
**Describe the bug**
When I subscribe to multiple topics using the same client-id, incoming messages are not passed to the correct subscribed method of the incoming channel. 

**Expected behavior**
Incoming Messages are passed to the subscribed methods and the connector should use the same connection when they use the same host and client-id.

**Actual behavior**
Connectors using the same client-id do not reuse connections therefore subscriptions are not acknowledged and the client does not get the right callback. 

**To Reproduce**
I uploaded a Reproducer here https://github.com/jnsfrg/quarkus_mqtt_sample
1. set 2 retained messages for "prices" and "products" in the Broker
2. start the application 
3. the log looks like:
Receiving price: 34
Receiving price: banana

where banana should be listed as a product.

**Configuration**
```properties
mp.messaging.incoming.prices.type=smallrye-mqtt
mp.messaging.incoming.prices.topic=prices
mp.messaging.incoming.prices.host=localhost
mp.messaging.incoming.prices.port=1883
mp.messaging.incoming.prices.qos=1
mp.messaging.incoming.prices.client-id=quick_start_test_id

mp.messaging.incoming.products.type=smallrye-mqtt
mp.messaging.incoming.products.topic=products
mp.messaging.incoming.products.host=localhost
mp.messaging.incoming.products.port=1883
mp.messaging.incoming.products.qos=1
mp.messaging.incoming.products.client-id=quick_start_test_id

```

**Environment (please complete the following information):**
- Output of `java -version`: 
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```
 - Broker: hivemq 4.2.3
 - Quarkus version or git rev: 1.4.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
See https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/smallrye-reactive-messaging-mqtt

**Comment by cescoffier** [comment]
Fixed by https://github.com/smallrye/smallrye-reactive-messaging/pull/545.

Once the linked PR is merged, it would require a release of Smallrye reactive messaging and the integration of this release in Quarkus.
