### ISSUE TITLE
1.4 migration guide does not mention changed JDBC configuration

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#9307]
Changes in datasource guide not mentioned in migration guide (".jdbc.", db-kind ):

https://github.com/quarkusio/quarkus/commit/e8b530d87521798daaa99afa2e7077b676fffa44

**Comment by geoand** [comment]
Actually this was a 1.3 change IIRC

**Comment by zeljkot** [comment]
It could be, but it is not documented in any of the migration guides.

**Comment by geoand** [comment]
cc @gsmet

**Comment by geoand** [comment]
Closing as out of date
