### ISSUE TITLE
Documentation On Building Quarkus Core

### ISSUE THREAD

**Issue by amihaiemil** [quarkusio/quarkus#9308]
The [Contributing.MD](https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#building-master) has clear instructions on how to build the master branch.

However, this build takes a lot of time (10min+). From my understanding, this is because also a lot of Quarkus Extensions are being built.

It would be nice to have some documentation on how to build just the core part of Quarkus, for instance.

The first build of a project is usually longer because Maven downloads all the dependencies. But even the second build, with the cached dependencies, takes about 7 minutes.

**Comment by famod** [comment]
FWIW, I can bring it down to ~5 mins by adding `-T4` on a pretty dated i7-6700k.

**Comment by geoand** [comment]
I'll add a couple workflow tips I use all the time

**Comment by geoand** [comment]
#9308 should take care of this

**Comment by amihaiemil** [comment]
@geoand Nice, thank you!
