### ISSUE TITLE
Quarkus/Undertow does not parse request parameters correctly from multipart post

### ISSUE THREAD

**Issue by tandraschko** [quarkusio/quarkus#9309]
**Describe the bug**
We tried to setup a PrimeFaces FileUpload with the new MyFaces Quarkus Extension but the post is not correctly considered as postback in JSF as the underlying HttpServletRequest doesnt have any post params.
I tested it and it works fine on jetty.

**Expected behavior**
HttpSevletRequest also parses post params from the multipart request

**Actual behavior**
empty request params

**To Reproduce**
1. Build MyFaces (git clone https://github.com/apache/myfaces/  and  mvn clean install -DskipTests)
2. Run the Showcase (https://github.com/apache/myfaces/tree/master/extensions/quarkus/showcase): mvn compile quarkus:dev -Ddebug
3. Open localhost:8080/file.xhtml
4. Select a file in the second / simple exmaple and use the styled or not styled button to submit it
5. if you check the post in the browser tools, it's a multipart and correclty contains the javax.faces.ViewState param
6. Now debug HtmlResponseStateManager#isPostback and you will see that the underlying HttpServletRequest doesnt have ANY request params

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by mgorniew** [comment]
Servlets registered `ServletBuildItem` will not respect `@MultipartConfig`. Because of that `FacesServlet` will not parse form data. I'm working on PR which will fix that.

**Comment by tandraschko** [comment]
cool! can we merge it into the next release?

**Comment by tandraschko** [comment]
@stuartwdouglas thanks, the MyFaces JSF extensions works fine now.
I have another bug which appears when using the JSF extension. Could anyone of you guys have a look plz? https://github.com/quarkusio/quarkus/issues/9702
I would like to release a bugfree version soon.
