### ISSUE TITLE
No WebSocket @ServerEndpoint @OnClose event when Web Browser closes

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#9319]
**Describe the bug**

WebSocket `@ServerEndpoint` `@OnClose` does not get called when the user closes their Web Browser.  See https://groups.google.com/forum/#!topic/quarkus-dev/nhW19mwWDAg for more details.

**Expected behavior**
`@OnClose` should get called so that we can clean up any resources.

**Actual behavior**
`@OnClose` does not get called, **although Session::isOpen returns false.**

**To Reproduce**
Add logging to the websockets-quickstart `ChatSocket` `@OnOpen` and `@OnClose` methods.
Start server.
Start browser an do some chatting.
Close browser.
Observe that `@OnOpen` is logged but `@OnClose` is not.

**Environment (please complete the following information):**

Quarkus 1.4.2

**Comment by stuartwdouglas** [comment]
I think this should be fixed by https://github.com/quarkusio/quarkus-http/pull/32

**Comment by jimbogithub** [comment]
Thanks.  Is https://github.com/quarkusio/quarkus/issues/9318 another easy fix for you?
