### ISSUE TITLE
Add support for compressor

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#9324]

**Comment by michalszynkiewicz** [comment]
Looks like vertx-grpc will support compression from 4.0.0: https://github.com/vert-x3/vertx-grpc/issues/63 , can we wait for it?

**Comment by cescoffier** [comment]
The integration of Vert.x 4.x is planned for the end of the year (guestimate). So, I believe it can wait. I don't believe it's a frequently used feature.

**Comment by michalszynkiewicz** [comment]
For non-mutiny usage, the following works:
```
((ServerCallStreamObserver<?>) responseObserver).setCompression("gzip");
```

Mutiny services don't get responseObserver as parameter, it should be doable to add this with an interceptor
