### ISSUE TITLE
add @InjectSpy feature

### ISSUE THREAD

**Issue by dcdh** [quarkusio/quarkus#9377]
**Description**
Since Quarkus 1.4 we can inject mocked beans by using the `@InjectMock` annotation.

In some condition it is very hard to use mock and spy can be enough when we only want to ensure that methods have been called.

For example I use an interceptor and I just want to ensure that the @AroundInvode has been called.

```java
@Interceptor
@CommandExecutorBinding
public class CommandExecutorInterceptor {

    final CommandExecutor commandExecutor;

    public CommandExecutorInterceptor(final CommandExecutor commandExecutor) {
        this.commandExecutor = Objects.requireNonNull(commandExecutor);
    }

    @AroundInvoke
    private Object execute(final InvocationContext context)  throws Throwable {
        return this.commandExecutor.execute(() -> context.proceed());
    }

}
```
In this case I just want to know that the method `execute` has been called to ensure that my interceptor is working and so my intercepted class is well bounded. Using a mock and so mocking the callable is very hard.

So having the possibility to inject a spy of CommandExecutor just for ensuring that its method execute has been called would be a great help.

I made this workaround by producing a spy alternative of my bean.

```java
@ApplicationScoped
public class TestBeansProducers {

    private final CommandExecutor commandExecutor;

    private TestBeansProducers() {
        commandExecutor = spy(new CommandExecutor());
    }

    @Produces
    @AlternativePriority(1)
    public CommandExecutor commandExecutor() {
        return commandExecutor;
    }

}
```

**Implementation ideas**

**Comment by geoand** [comment]
Seems reasonable to me

**Comment by glefloch** [comment]
I would be interested into working on this!

**Comment by geoand** [comment]
@glefloch too late unfortunately :)

It has been fixed in https://github.com/quarkusio/quarkus/pull/9388

**Comment by glefloch** [comment]
@geoand  I will look for another one then :)
