### ISSUE TITLE
Support JSON logging for file

### ISSUE THREAD

**Issue by fatih-erdem** [quarkusio/quarkus#9386]
**Describe the bug**
Quarkus supports JSON logging for the console. But when it writes to the file, it writes with a normal structure. We need to write JSON to the file as well as the console.

**Actual behavior**
By default when JSON logging for the console is enabled, it writes JSON format in the console.  But when it writes to the file, it writes with a normal structure.

There is a property called `quarkus.log.console.json` but there is no `quarkus.log.file.json` property.

**To Reproduce**
1. Add `quarkus-logging-json` dependency to the pom.xml. This enables the json logging to the console.
2. Add `quarkus.log.file.path=/tmp/example.log` property to the application.properties file.
3. Start the app.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin Fatihs-MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

 - Output of `java -version`:  
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: Quarkus 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /Users/fatih/.sdkman/candidates/java/20.0.0.r11-grl
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

**Additional context**
(Add any other context about the problem here.)

**Comment by aoudiamoncef** [comment]
Hi @dmlloyd, 
I looked at the console JSON formatter integration && i'm interested to add extend it with your help.

**Comment by dmlloyd** [comment]
My availability is fairly limited, but if you have questions, I'd recommend asking them on [the Quarkus developer Zulip chat](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev).

**Comment by matfa42** [comment]
+1

**Comment by deep21786** [comment]
Hi team @dmlloyd, @matfa42  
Greetings:)
I am also looking for similar solution. Any update on this?

**Comment by synox** [comment]
is this a good first issue? Is there guidance how this should be implemented?

**Comment by dmlloyd** [comment]
I think it could be a good first issue; I don't think it should be too complicated since file handling is essentially similar to console handling. It should be just a question of replicating the relevant config and config processing elements.

**Comment by dev-di** [comment]
I am also hoping this feature could be implemented

**Comment by martinffx** [comment]
Yeah, this is proving to be huge pain point for me. All our logging is done as JSON to file picked up by filebeat on the Node and shipped to ELK.

I've tried various workarounds but I can't quite get JSON logs in a file.

https://github.com/quarkiverse/quarkus-logging-logback/issues/58

**Comment by mihaipoenaru** [comment]
I also need this. I'm trying workarounds but nothing really does what I need it to.

**Comment by lost4git** [comment]
Is there any progress on this issue, or has it been abandoned?

**Comment by dmlloyd** [comment]
I don't think anyone has taken it up yet.

**Comment by mihaipoenaru** [comment]
One workaround, I think, is to redirect the standard output (that is printed in json) to a file, however you lose log rotation with this. But we do really need someone to look at this. It sounds like a trivial issue to solve, if you know where to look.

**Comment by mihaipoenaru** [comment]
@gsmet I've already forked the project, I'll probably have it done by the end of the day, hopefully. But if you want to do it, that's fine as well.

**Comment by gsmet** [comment]
@mihaipoenaru sorry, it wasn't clear you wanted to work on this :). Anyway, I think I'm done. Now I need to have a look at testing it :).

**Comment by wiradikusuma** [comment]
While we're on this topic, slightly OOT, is there a way to customize (adding and removing) the JSON fields? Currently I use Vector (https://vector.dev/) to do that, but if it can be done "from the source" I don't need to transform it before sending it to Grafana.

**Comment by mihaipoenaru** [comment]
@gsmet 

No, sorry, I deleted my reply as soon as I posted it. I was watching multiple issues and I thought this was a different thing. Please, you take care of it, I have no idea how 😆

**Comment by gsmet** [comment]
@wiradikusuma for more advanced use cases, you have https://github.com/quarkiverse/quarkus-logging-json/ which allows customization (and you can contribute there if you want more).

As soon as the file handling is in core, I suspect @SlyngDK will use it in the Quarkiverse extension too.

**Comment by gsmet** [comment]
PR is here: https://github.com/quarkusio/quarkus/pull/25505 .

**Comment by synox** [comment]
Did this feature already make it into a release?

**Comment by gsmet** [comment]
No, it’s 2.10 material. It will be released by end of June. That being said, you can test the snapshots and report back. That would be helpful.

**Comment by synox** [comment]
FYI, 2.10 is released, so this should be ready for test.

**Comment by dfa1** [comment]
> @wiradikusuma for more advanced use cases, you have https://github.com/quarkiverse/quarkus-logging-json/ which allows customization (and you can contribute there if you want more).
> 
> As soon as the file handling is in core, I suspect @SlyngDK will use it in the Quarkiverse extension too.
@gsmet is quarkus-logging-json still actively maintained? I found this same issue and looks like nothing is moving there since a long time...

**Comment by gsmet** [comment]
@dfa1 I don't know. This is a community effort so I'm not sure if @SlyngDK has the time, I'll reach out to him. In any case, if you want the file logging to be implemented, maybe you can create a PR? I'll make sure it gets merged as it's related to the work I did in the core.

We are happy to welcome multiple maintainers in Quarkiverse extensions, as long as the original maintainer is OK with it.

**Comment by lisle777** [comment]
Hi all.

I wondered if this has made it into a release?

Thanks in advance.

**Comment by gsmet** [comment]
@lisle777 see the milestone of the issue. It has been merged for 2.10.
