### ISSUE TITLE
Import grpc-bom in quarkus-bom instead of managing individual grpc artifacts

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#9403]
**Description**
Since the GRPC extension was moved to Quarkus source tree, we (Camel Quarkus) have hard time to align dependencies coming from Quarkus with the one coming from Camel. This is because Quarkus runtime BOM manages just `grpc-api` and `grpc-stub`. We'd actually need much more, nearly all listed in https://repo1.maven.org/maven2/io/grpc/grpc-bom/1.29.0/grpc-bom-1.29.0.pom

So is there a reason not to import the whole grpc-bom in quarkus-bom?

**Comment by geoand** [comment]
cc @cescoffier

**Comment by gsmet** [comment]
I created a PR after discussing with @cescoffier .
