### ISSUE TITLE
AvroRuntimeException thrown while serializing an Apache Avro schema from buildtime to runtime

### ISSUE THREAD

**Issue by aldettinger** [quarkusio/quarkus#9446]
**Describe the bug**
An exception is thrown when Quarkus attempt to serialize an org.apache.avro.Schema instance while I would expect the instance to be serialized correctly.

**To Reproduce**
1. In a processor, create a build step parsing an avro schema
2. Schema avroSchema = new Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Value\",\"namespace\":\"org.apache.camel.quarkus.component.avro.it\",\"fields\":[{\"name\":\"value\",\"type\":\"string\"}]}")
3. Pass the schema as argument to a recorder
4. The processor fails at build time with a stack trace including "AvroRuntimeException"

**Additional information**
It looks that BytecodeRecorderImpl invoke the always throwing method [Schema.getTypes()](https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/Schema.java?L371#L366)

**Workaround**
One could implement a substitution to serialize/deserialize such classes.

**Comment by geoand** [comment]
Thanks for reporting,

What is the easiest way to reproduce this?

**Comment by aldettinger** [comment]
@geoand:
git clone git@github.com:aldettinger/quarkus-9446-reproducer.git
mvn clean install

Hope reproducer express could keep you satisfied :)

**Comment by geoand** [comment]
Thanks a lot @aldettinger!

**Comment by geoand** [comment]
I looked at this and there isn't much Quarkus can do here. 
Bytecode recording doesn't work with any type under the sun and in this case it doesn't work because the `getTypes` method of `Schema` throws an exception (and Quarkus has no way to know how to skip this method).

So as I am sure you have already done, you'll have to pass the String from the processor to the recorder.

**Comment by aldettinger** [comment]
@geoand thanks for taking a look. Indeed I could have passed the schema string to the recorder. For the sake of sharing tips to deal with those kind of issues, I was even able to workaround using an [object substitution](https://quarkus.io/guides/writing-extensions#object-substitution). That way, schema parsing occur at build time.

**Comment by geoand** [comment]
Yeah, I understand. Unfortunately you hit a corner case :)
