### ISSUE TITLE
Kafka and AMQP connector concurrency

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9447]
Quarkus 1.6
Requires SmallRye Reactive Messaging  2.1.0

**Comment by kenfinnigan** [comment]
Relevant SmallRye Reactive Messaging issues:

- https://github.com/smallrye/smallrye-reactive-messaging/issues/424
- https://github.com/smallrye/smallrye-reactive-messaging/issues/290
- https://github.com/smallrye/smallrye-reactive-messaging/issues/329

**Comment by cescoffier** [comment]
Upstream issues have been fixed.
