### ISSUE TITLE
AsyncAPI support in Reactive Messaging

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9448]
Quarkus 1.8

Mostly about generating the descriptor at build time and extend it at runtime (with broker location)

Also see https://github.com/smallrye/smallrye-parent/issues/106

**Comment by geoand** [comment]
Is this still something that we plan on doing @cescoffier ? @kenfinnigan ?

**Comment by kenfinnigan** [comment]
It is, but I think the priority has slipped. Might be worth re-evaluating when Clement returns

**Comment by cescoffier** [comment]
Still something I want. We never had the time to look into that seriously.

**Comment by cescoffier** [comment]
This issue was opened 5 years ago, and, unfortunately, we never found the time to implement it. We also never had a huge demand for it.

As I don’t see when this will be implemented, let’s close that issue and see if we get new requests.
