### ISSUE TITLE
Messaging - Tracing support

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9449]
Quarkus 1.x, with x > 7

**Comment by cescoffier** [comment]
Tracked upstream by https://github.com/orgs/quarkusio/projects/6#card-38980522 and https://github.com/smallrye/smallrye-reactive-messaging/issues/562

**Comment by kenfinnigan** [comment]
Just an FYI, to have this make a 1.7 release I don't think it will have an aligned OpenTelemetry extension for Quarkus as well, it might require adding OT dependencies directly by user "to work".

Will have to see

**Comment by n1hility** [comment]
@cescoffier This is looking like a 1.9 item now? wdyt?

**Comment by cescoffier** [comment]
In 1.9, we will only support Kafka. (CC @kenfinnigan). 
Other connectors will come next.

**Comment by kenfinnigan** [comment]
Right, do we need an OpenTelemetry extension for Quarkus for 1.9 as well, or are we ok with users needing to add OpenTelemetry into their application for "day one"?

**Comment by n1hility** [comment]
@kenfinnigan @cescoffier it feels like its unlikely to make it in 1.9 so perhaps it could come in as quarkiverse if it beats 1.10.

**Comment by kenfinnigan** [comment]
There won't be an extension for 1.9, but I don't think it can be in quarkiverse as it would be a replacement for opentracing extension long term.
