### ISSUE TITLE
QuarkusTestResourceLifecycleManagers override each others' props

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#9453]
**Describe the bug**
If I have many implementations of QuarkusTestResourceLifecycleManager, they are all run before all tests, and as a consequence they override each others' properties.

Is this the intended behaviour?

**Expected behavior**
The QTRLM implementation annotated in each QuarkusTest should be run to set up the QuarkusTest itself.

**Actual behavior**
All the QTRLM implementations are run before all QuarkusTests.

**To Reproduce**
```
public class TestResourceA implements QuarkusTestResourceLifecycleManager {
    @Override
    public Map<String, String> start() {
        return Collections.singletonMap("my.prop", "A");  // Setting A
    }

    @Override
    public void stop() {}
}
```
```
public class TestResourceB implements QuarkusTestResourceLifecycleManager {
    @Override
    public Map<String, String> start() {
        return Collections.singletonMap("my.prop", "B");  // Setting B
    }

    @Override
    public void stop() {}
}
```
```
@QuarkusTest
@QuarkusTestResource(TestResourceA.class)
public class TestA {
    @Inject
    @ConfigProperty(name = "my.prop")
    String prop;

    @Test
    public void test() {
        assertThat(prop).isEqualTo("A");  // Expecting A
    }
}
```
```
@QuarkusTest
@QuarkusTestResource(TestResourceB.class)
public class TestB {
    @Inject
    @ConfigProperty(name = "my.prop")
    String prop;

    @Test
    public void test() {
        assertThat(prop).isEqualTo("B");  // Expecting B
    }
}
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.4.2.Final

**Comment by geoand** [comment]
Yes, **all** `QuarkusTestResourceLifecycleManager` classes on tests annotated with `@QuarkusTest` are run before any test.
So if you have multiple such classes define the same project, then the same properties will be ignored for one of them.

If you need to define priority, there is the `order` method on `QuarkusTestResourceLifecycleManager` that you can override.

Currently in Quarkus there isn't a way to change properties per test (this will likely change in the near future).

**Comment by antoniomacri** [comment]
Thanks for the clarification.

But now I don't understand the purpose of annotating with QuarkusTestResource each test: it's practically the same as putting all QTR annotations on a single QuarkusTest?

**Comment by geoand** [comment]
> Thanks for the clarification.
> 

You are welcome

> But now I don't understand the purpose of annotating with QuarkusTestResource each test: it's practically the same as putting all QTR annotations on a single QuarkusTest?

Yes, it is effectively the same thing
