### ISSUE TITLE
Bad JSON returned from the default QuarkusErrorServlet

### ISSUE THREAD

**Issue by lodrantl** [quarkusio/quarkus#9463]
**Describe the bug**
Using quarkus-undertow and quarkus-resteasy, if an exception is thrown in a JAX-RS endpoint and no ExceptionMapper catches it gets forwarded to QuarkusErrorServlet. 

In case of JSON Accept header the stack does not get properly escaped there.

For example, I've encountered a stack ending with (there's a tab before ....):
`(SynchronousDispatcher.java:488)\n	... 53 more`
which produces a JSON with a string including a tab delimiter.

Here is an example of a more thorough escaping from JSON simple.
https://github.com/fangyidong/json-simple/blob/master/src/main/java/org/json/simple/JSONValue.java#L270

**Environment:**
 - Quarkus version 1.4.2.Final

**Comment by geoand** [comment]
Thanks for reporting!

Since you seem to have found your way around the code, would you care to submit a Pull Request fixing the issue?

Thanks
