### ISSUE TITLE
Mongo - SRV support in native

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#9476]
SRV URLs do not work in native because it uses JNDI to resolve the names. 

One solution would be to replace this code using a substitution to resolve the record using a native-compatible approach.

**Comment by mutasemhidmi** [comment]
is there a timeline for this feature?

**Comment by eduardovpessoa** [comment]
I'm still getting this error: unable to support mongodb+srv:// in native =(

**Comment by elcaven** [comment]
Is there any update on this feature?

**Comment by eduardovpessoa** [comment]
> Is there any update on this feature?

I'd like to know as well... I didn't see any update about it since last year. Unfortunately, it's a major "issue" for my company not to adopt quarkus.

**Comment by cescoffier** [comment]
While we could use Vert.x do to the DNS call (instead of JNDI), the substitution to write is not trivial. However, if any of you want to contribute, I would be happy to help.

**Comment by nicolas-vivot** [comment]
+1

Will try to have a look cause i need it. And at some point, the old format is not going to be supported anymore by Mongo Atlas.

**Comment by marcogutto** [comment]
Hi @cescoffier !
Any update about this issue?
This is a problem on Quarkus adoption for us.

Thanks in avance!

**Comment by gsmet** [comment]
@marcogutto This discussion might be of interest to you: https://github.com/quarkusio/quarkus/discussions/22613 .

**Comment by loicmathieu** [comment]
Fixed by #22944
