### ISSUE TITLE
Integrate reactive routes and Mutiny

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#9477]
Better integration of reactive routes and mutiny to allow routes to return Uni/Multi.

**Comment by murphye** [comment]
I was playing with this previously. This seems to work, but I am wondering what improvements you have in mind...

```
    @Route(path = "/multi", methods = HttpMethod.GET)
    void multi(RoutingExchange ex) {
        Multi<String> source = Multi.createFrom().items("a", "b", "c");

        var response = ex.response();
        response.setChunked(true);
        source.onCompletion().invoke(response::end).subscribe().with(response::write);
    }
```

**Comment by murphye** [comment]
Another example using SSE. This will send messages to all consumers of the `/stream` endpoint from the EventBus.

```
    @Route(path = "/stream", methods = HttpMethod.GET)
    void stream(RoutingExchange ex) {
        var response = ex.response();
        response.setChunked(true);
        response.headers().add("Content-Type", "text/event-stream;charset=UTF-8");
        response.headers().add("Connection", "keep-alive");

        eventBus.<String>consumer("sample").toMulti().onItem().apply(m -> data(m.body())).subscribe()
                .with(response::write);
    }

    private String data(String data) {
        return "data: " + data + "\n\n";
    }
```

**Comment by cescoffier** [comment]
The idea is to return the `Uni` and `Multi` directly and avoid the user-managed subscription.

**Comment by murphye** [comment]
OK. Maybe the functionality could be extended a bit:

1. Automatically handle `subscibe` and `onCompletion`
1. Automatically handle the `onError` and return appropriate response (500 error?)
1. Automatically `setChunked(true)` for Multi
1. Automatically add `data: ` and `\n\n` for optional SSE
1. Automatically `headers().add` `text/event-stream` and `keep-alive` for optional SSE
1. Automatically return `body()` from `eventBus.<String>consumer("sample").toMulti()` when EventBus is used

**Comment by cescoffier** [comment]
It's exactly what I had in mind!

**Comment by cescoffier** [comment]
@mkouba and I have done a first integration - already in master.
