### ISSUE TITLE
Add Avro support to the Kafka connector

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#9478]
It should already work, but we need to add a test verifying that Avro can be used.

We should verify using the Confluent registry and the Apicurio registry (and custom serde). 

This feature deserves a specific section in the documentation.

Estimation: Quarkus 1.6

**Comment by anamarija** [comment]
Hi,

If nobody is working on this, can I take a look at this and test everything out.

**Comment by cescoffier** [comment]
Thanks @anamarija ! 

I already added a few Avro tests using the Confluent Registry to the Kafka client IT. In this issue, we need to extend these tests with the Apicurio registry (they also provide they own serde). Hopefully this one would work in native (The other Avro does not).

Finally, some tests need to be added to the IT checking the reactive-messaging Kafka connector. 

Some references:

* https://github.com/Apicurio/apicurio-registry
* https://debezium.io/documentation/reference/configuration/avro.html - explain how to use the Avro serde
* https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/kafka/kafka.html - reactive messaging Kafka connector documentation
