### ISSUE TITLE
Integrate Vertx 3.9.2

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#9480]
Including the MS SQL Driver

**Comment by sberyozkin** [comment]
Vertx Oauth2 JWK refresh fix is incomplete so it will have to be in 3.9.2 as well

**Comment by Sanne** [comment]
+ DB2 driver

@cescoffier @emmanuelbernard can we hope to see a PR soon to play with?

**Comment by Sanne** [comment]
ah, I confused this with the vertx 3.9.1 upgrade - that's what we needed.

No rush with this one - although having MS SQL support would be great too :)

**Comment by cescoffier** [comment]
Forgot to close this one.
