### ISSUE TITLE
ClassCastException for QuarkusTestResourceLifecycleManager across modules in gradle 

### ISSUE THREAD

**Issue by tobad357** [quarkusio/quarkus#9511]
**Describe the bug**
There is a class cast exception when using a test resource from another gradle module 

**Expected behavior**
We should be able to use test resources from other modules

**Actual behavior**

@aloubyansky this is based on the project inject-bean-from-test-config

Add LibraryTestResource.java in library/src/test/org.acme
```
package org.acme;

import io.quarkus.test.common.QuarkusTestResourceLifecycleManager;
import java.util.Collections;
import java.util.Map;

public class LibraryTestResource  implements QuarkusTestResourceLifecycleManager {

    @Override
    public Map<String, String> start() {
        return Collections.emptyMap();
    }

    @Override
    public void stop() {}    
}
```

In application/src/test/java/org/acme/ExampleResourceTest.java add

```
@QuarkusTestResource(LibraryTestResource.class)
```

Try to run test

```
gradle -PquarkusPluginVersion=1.5.0.CR1 -PquarkusPlatformVersion=1.5.0.CR1 test --info
```

Result

```
 Caused by:
            java.lang.ClassCastException: class org.acme.LibraryTestResource cannot be cast to class io.quarkus.test.common.QuarkusTestResourceLifecycleManager (org.acme.LibraryTestResource is in unnamed module of loader 'app'; io.quarkus.test.common.QuarkusTestResourceLifecycleManager is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @380c4de)
                at io.quarkus.test.common.TestResourceManager.getTestResources(TestResourceManager.java:130)
                at io.quarkus.test.common.TestResourceManager.<init>(TestResourceManager.java:29)
                ... 67 more
```

**Environment (please complete the following information):**
------------------------------------------------------------
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.4 (AdoptOpenJDK 11.0.4+11)
OS:           Mac OS X 10.15.4 x86_64
QuarkusVersion: 1.5.0.CR1

**Additional context**
This works in 1.2

**Comment by geoand** [comment]
@tobad357 Thanks for reporting!

Two things:

1) Have you tried with `1.4.2.Final`? If not, can you try and let us know if that version suffered the same problem
2) Do you have a small reproducer we can use?

**Comment by tobad357** [comment]
No problems

1. Can't test as including test deps from another module doesn't work in 1.4.2.Final. It was fixed for 1.5.0.CR1

2. Please see included which is an adaptation of inject-bean-from-test-config under devtools/gradle/src/funcationalTest/resources/

Build it by doing
```
gradle -PquarkusPluginVersion=1.5.0.CR1 -PquarkusPlatformVersion=1.5.0.CR1 test --info
```

[inject-bean-from-test-config.zip](https://github.com/quarkusio/quarkus/files/4661025/inject-bean-from-test-config.zip)

**Comment by geoand** [comment]
> No problems

You mean it works for 1.4.2.Final ?
> 
> 1. Can't test as including test deps from another module doesn't work in 1.4.2.Final. It was fixed for 1.5.0.CR1
> 2. Please see included which is an adaptation of inject-bean-from-test-config under devtools/gradle/src/funcationalTest/resources/
> 
> Build it by doing
> 
> ```
> gradle -PquarkusPluginVersion=1.5.0.CR1 -PquarkusPlatformVersion=1.5.0.CR1 test --info
> ```
> 
> [inject-bean-from-test-config.zip](https://github.com/quarkusio/quarkus/files/4661025/inject-bean-from-test-config.zip)

Thanks

**Comment by tobad357** [comment]
I don't know if it works as can't get that far due to issue #9232

**Comment by geoand** [comment]
I see, thanks

**Comment by aloubyansky** [comment]
I'll have next week.

**Comment by aloubyansky** [comment]
Ok, I see where the problem is.

**Comment by aloubyansky** [comment]
Thanks again for the reproducer. I've adjusted the previous PR to include it along with the fix.

**Comment by Alexander-Krause** [comment]
Hi, I have the same problem using the `com.datastax.oss.quarkus.test.CassandraTestResource` in my `integrationTest` source set for Quarkus `1.11.3.Final`:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

Caused by: java.lang.reflect.InvocationTargetException

Caused by: java.lang.ClassCastException: class com.datastax.oss.quarkus.test.CassandraTestResource 
cannot be cast to class io.quarkus.test.common.QuarkusTestResourceLifecycleManager 
(com.datastax.oss.quarkus.test.CassandraTestResource is in unnamed module of loader 'app'; 
io.quarkus.test.common.QuarkusTestResourceLifecycleManager is in unnamed module of loader 
io.quarkus.bootstrap.classloading.QuarkusClassLoader @3558c20f)
```

**Comment by aloubyansky** [comment]
@Alexander-Krause could you please create a new issue with either a reproducer or instructions to reproduce your issue? Thanks.
