### ISSUE TITLE
KafkaStreams + CLI + custom properties fail

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#9532]
**Describe the bug**

I am developing a CLI application with KafkaStreams, and I need to set the Configuration of Kafka Streams programmatically. When I do and I run the application in *native* mode I get a Serde cannot be found.

The project is in this project in `quarked` branch https://github.com/lordofthejars/kstreamscat/tree/quarked

**Expected behavior**

Works without any problem.

**Actual behavior**

```
2020-05-22 11:38:22,213 ERROR [io.qua.run.Application] (main) Error running Quarkus application: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serialization.Serdes$StringSerde for configuration default.key.serde: Class org.apache.kafka.common.serialization.Serdes$StringSerde could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:728)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:474)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:467)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
	at org.apache.kafka.streams.StreamsConfig.<init>(StreamsConfig.java:907)
	at org.apache.kafka.streams.StreamsConfig.<init>(StreamsConfig.java:902)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:566)
	at com.lordofthejars.kstreamscat.KafkaStreamsProducer.buildKafkaStreams(KafkaStreamsProducer.java:38)
	at com.lordofthejars.kstreamscat.KStreamsCatMain.run(KStreamsCatMain.java:35)
	at com.lordofthejars.kstreamscat.KStreamsCatMain_ClientProxy.run(KStreamsCatMain_ClientProxy.zig:156)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
```

**To Reproduce**

1. Clone  https://github.com/lordofthejars/kstreamscat/tree/quarked and move to `quarkued` branch
2. Compile to native
3. Run ./kstreamscat-runner --topic=songs --id=songs -b=localhost:29092 --GT
4. The exception is thrown.

**Environment (please complete the following information):**
- Quarkus 1.5.0.CR1
- Mac OS
- Java 11

Maybe @gunnarmorling might give some hints if this is the expected or not.

**Comment by rquinio** [comment]
I think you'd need to specify `kafka-streams.default.key.serde` /  `kafka-streams.default.value.serde` in application.properties, so they can be seen at build time by the quarkus-kafka-streams extension to register the Serdes for reflection ? cf #3547 

Normally it's the runtime part of the extension that creates the KafkaStreams instance, so it's not actually possible to set configuration programmatically like you're doing.

**Comment by lordofthejars** [comment]
But I need to do it programmatically as it is a CLI tool not a server tool. So I think it should be possible to be done. There is a workaround maybe?

**Comment by rquinio** [comment]
Ha ok because the value seemed hardcoded in https://github.com/lordofthejars/kstreamscat/blob/685069a2f61c28bc2780760feb377b7fbed645e5/src/main/java/com/lordofthejars/kstreamscat/KafkaStreamsProducer.java#L34 , but you'd want to be able to `./kstreamscat-runner --key-serde=com.acme.MySerde` ?

There are workarounds to manually register for reflection a third-party class: https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection but class has to be known at build time.

Btw #4961 is enabling kafka-streams.* entries in application.properties to be overridden at runtime, but I guess there'll be such a gap in native mode for any property that references a class loaded via reflection...

**Comment by lordofthejars** [comment]
> Ha ok because the value seemed hardcoded in

This is a trick I do to be able to boot up Quarkus and not complain about not set properties.

**Comment by lordofthejars** [comment]
The problem is that after Serdes I am sure it will be another one.

**Comment by rquinio** [comment]
Looking at https://docs.confluent.io/current/streams/developer-guide/config-streams.html , the config keys that reference classes are:
- default.deserialization.exception.handler (built-ins: LogAndFailExceptionHandler / LogAndContinueExceptionHandler, LogAndFailExceptionHandler) - only LogAndFailExceptionHandler is registered today.
- default.production.exception.handler  (built-in: DefaultProductionExceptionHandler) 
- default.key.serde (many built-ins)
- default.value.serde (same as previous)
- default.windowed.key.serde.inner (same as previous)
- default.windowed.value.serde.inner  (same as previous)
- default.timestamp.extractor (built-ins: FailOnInvalidTimestamp, UsePartitionTimeOnInvalidTimestamp, WallclockTimestampExtractor.) - only FailOnInvalidTimestamp is registered today.
- metric.reporters (no built-in apparently)

If these make sense to be changed at runtime via a command option, then all built-ins have to be registered for reflection (it's what quarkus-kafka extension does for Serdes: https://github.com/quarkusio/quarkus/blob/2d8867d9f1481b02a94a334da86a2068cd4733a7/extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java#L60-L82 )

Even more generic would be to search Jandex for classes implementing known interfaces (i.e. org.apache.kafka.common.serialization.Serde), to cover cases where the Serde would be in any third-party dependency of your project and not only Kafka built-ins.

**Comment by geoand** [comment]
I don't see why this is a Quarkus problem. You are programmatically configuring Kafka Streams which means Quarkus can't know which things you actually need for reflection.
So I propose you just use `@RegisterForReflection` with the classes you need.

The alternative would be for you to write your own extension that would fit your programmatic logic like a glove and then make your application use it.
So I propose we either close this issue (because this is not a Quarkus bug), or you convert it to feature request for Quarkus to somehow provide a means to support the type of programmatic configuration you are using.

**Comment by lordofthejars** [comment]
But how I can mark as register for reflection classes that I do not own?

**Comment by geoand** [comment]
The annotation will let you register any class

**Comment by lordofthejars** [comment]
But Serdes class is from Apache Kafka project.

**Comment by geoand** [comment]
It doesn't matter. You can place the annotation on any of your own classes and use the `target` (I think that's what it's called) method of the annotation

**Comment by lordofthejars** [comment]
ah ok, great

**Comment by lordofthejars** [comment]
I'll update the docs as it is not explicitly explained :)
