### ISSUE TITLE
quarkus-bom 1.3.3 declares smallrye-reactive-messaging-in-memory

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#9540]
smallrye-reactive-messaging-in-memory 1.1.0 doesn't work with Quarkus yet it is in the BOM for 1.3.3 (info from @cescoffier)

It should be dropped from quarkus-bom in the 1.3 branch.

**Comment by cescoffier** [comment]
@michalszynkiewicz I've a "bad" news for you: now it's working :-D 

Should we add it back?

**Comment by cescoffier** [comment]
@gsmet shouldn't we close this one?
