### ISSUE TITLE
Add option to configure import.sql charset

### ISSUE THREAD

**Issue by danowrw** [quarkusio/quarkus#9542]
**Description**
For now quarkus uses system default charset for import.sql. This causes errors depending on which system it is run. 

**Implementation ideas**
Please add an option to configure hibernate.hbm2ddl.charset_name from quarkus properties.

**Comment by geoand** [comment]
@danowrw you can set `hibernate.hbm2ddl.charset_name` by setting `quarkus.hibernate.datase.charset`

**Comment by xstefank** [comment]
@geoand so this can be closed I believe?

**Comment by geoand** [comment]
Yes, that is correct
