### ISSUE TITLE
(1.5.0.CR1) Qute Template not found

### ISSUE THREAD

**Issue by SR-Lut3t1um** [quarkusio/quarkus#9543]
**Describe the bug**
I get a template not found error in Quote when updating to 1.5.0.CR1

**Expected behavior**
Qute works just like it does in 1.4.2.Final

**Actual behavior**
I'm getting [this](https://gist.github.com/SR-Lut3t1um/b634649af59be67ef2d765ba4a8d6717) stacktrace

**To Reproduce**
 1. Download [this](https://gitlab.informatik.uni-bremen.de/tobias5/aut0m4t0n) repo
 2. Start the docker-compose to start a postgress database.
 3. Run quakus:dev when changing to 1.4.2.Final the templating-system will work.

**Configuration**
```properties
#Gradle properties
#Tue Feb 11 17:11:23 UTC 2020
quarkusPluginVersion=1.5.0.CR1
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=1.5.0.CR1
quarkusPlatformGroupId=io.quarkus

```

**Environment (please complete the following information):**
Java 11; 
Windows 10;
Gradle 6.4.1

**Comment by geoand** [comment]
I believe this is a known issue that @aloubyansky is working on
