### ISSUE TITLE
QuarkusTestResource initialization and stop behavior

### ISSUE THREAD

**Issue by derKrischan** [quarkusio/quarkus#9544]
**Describe the bug**
I#M not sure whether this is a bug or a discussion about the pros and cons of the current behavior...
Assume I have two tests and each one has it's own QuarkusTestResource than I would expect that only the QuarkusTestResource(implementing QuarkusTestResourceLifecycleManager) that is referenced in the tests annotation is initialized. But as far as I can see every class implementing QuarkusTestResourceLifecycleManager at classpath is started. This may be pretty resource exhausting. I wrote some tests with a serverless setup using localstack (ApiGateway, DynamoDB, Lambda, IAM, Cloudwatch Logs, S3) and I don't want it to be initialized every time I start a simple test that does not need this setup.

**Expected behavior**
Only the QuarkusTestResources that are referenced at the test via annotation are started (and stopped afterwards).

**Actual behavior**
Every QuarkusTestResourceLifecycleManager is initialized and in addition the call to 'stop()' is performed three times for every QuarkusTestResourceLifecycleManager.

**To Reproduce**
I wrote a simple reproducer/demonstrator: https://github.com/derKrischan/quarkus-reproducer-testresource-init

**Screenshots**
![image](https://user-images.githubusercontent.com/19590835/82709291-89363700-9c80-11ea-9b39-65cae1f52cc5.png)

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
 - Quarkus version 1.4.2 and 1.5.0.CR1:

**Comment by geoand** [comment]
Hi,

As hopefully is mentioned in the docs and the javadoc, this is the intended behavior.

The reason it's done this way is because is the Quarkus application starts only once (before all tests) and is not restarted per test.

This might change in the future, but for the time being this is the intended behavior.
