### ISSUE TITLE
Ability to exclude 3rd party CDI beans/factories from Quarkus Arc bean resolution

### ISSUE THREAD

**Issue by vladimirfx** [quarkusio/quarkus#9545]
**Description**
Currently using some 3rh party libraries that have CDI annotated classes can crash Quarkus Arc container. In order to use such libraries we need class/artifact exclusion mechanism for Arc scanner.

See https://stackoverflow.com/questions/61952174

**Implementation ideas**
Config properties would be enough:

    # for fine grained exclusion 
    quarkus.arc.exclude-classes=class list like in .selected-alternatives

    # for coarse grained exclusion 
    quarkus.arc.exclude-dependency."exclude-dependency".group-id
    quarkus.arc.exclude-dependency."exclude-dependency".artifact-id

Related issue - https://github.com/apache/camel-quarkus/issues/1197

**Comment by mkouba** [comment]
Sounds reasonable. 

CC @manovotn

**Comment by manovotn** [comment]
So, basically an alternative to https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#exclude_filters
Yeah, we should add that and using `application.properties` is probably the most natural way for that.

**Comment by mkouba** [comment]
Actually, it might make sense to replace `quarkus.arc.exclude-classes` with a regex-based filter so that it's possible to exclude "groups" of classes...

**Comment by vladimirfx** [comment]
> So, basically an alternative to https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#exclude_filters
> Yeah, we should add that and using `application.properties` is probably the most natural way for that.

IMO, patterns like selected-alternatives is simpler to understand and Quarkus users already familiar with it.

**Comment by mkouba** [comment]
The difference is that `quarkus.arc.selected-alternatives` is designed to be used with several classes whereas `quarkus.arc.exclude-classes` could be used to exclude all classes from a package, or even several packages accross several jars...

**Comment by vladimirfx** [comment]
From `quarkus.arc.selected-alternatives` doc:
>  a fully qualified class name, i.e. org.acme.Foo - a simple class name as defined by Class#getSimpleName(), i.e. Foo - a package name with suffix ., i.e. org.acme., matches a package - a package name with suffix ., i.e. org.acme., matches a package that starts with the value

It is clear that package match is supported. It is not flexible enough?

**Comment by mkouba** [comment]
Oh, you're right, I completely forgot I implemented it this way ;-). So we should probably match the FQCN and packages with suffix `.*` and `.**`.

BTW it seems that the descriptions of the `ArcConfig` are not rendered correctly on https://quarkus.io/guides/all-config....
