### ISSUE TITLE
ExtenstionIssue: ServletBuildItem.addInitParam cannot retrieve initparam in runtime mod

### ISSUE THREAD

**Issue by mkdirJava** [quarkusio/quarkus#9559]
**Describe the bug**
Trying to wire in configuration to extenstion run time via BuildSteps using ServletBuildItem.addInitParam
Successfully builds but calling getInitParameter returns null

**Expected behavior**
Passing configurations in BuildStep to build ServletBuildItem via .addinitParam 
should be avaliable in the servlet when calling getInitParameter

**Actual behavior**
Trying to wire in configuration to extenstion run time via BuildSteps using ServletBuildItem.addInitParam
Successfully builds but calling getInitParameter returns null

**To Reproduce**
1.  checkout :
https://github.com/mkdirJava/QuarkusBugServletBuildStep-
2.  run:
mvn test

**Comment by gastaldi** [comment]
Can you use 1.5.0.CR1? I believe that was already fixed

**Comment by geoand** [comment]
I just tested the reproducer with `1.5.0.CR` and the tests passed. Was most likely fixed by https://github.com/quarkusio/quarkus/pull/9233
