### ISSUE TITLE
Make the console logging output stream configurable.

### ISSUE THREAD

**Issue by bpasson** [quarkusio/quarkus#9569]
**Description**
For command line applications it can be useful to have console log to standard err instead of standard out because standard out can then be used to output command line results. When console logging is output on std err it makes capturing the command line output a lot easier since not logs have to be filtered out.

Even better would be an option to be able to have two console loggers, one for standard err and one for standard out which can be configured individually. This way you can output to console using a logger on both streams and not have to fall back to System.out or System.err for one or the other.

**Implementation ideas**
No idea if this is easy to do, but maybe add a second console logger for standard err which is disabled by default and configurable like the console logger is now. I'm guessing some work needs to be done to make the default logger configurable (seems to be console on standard out now). No idea yet how to resolve which logging needs to go to which appender.

**Comment by gsmet** [comment]
Sounds like a very legitimate request, thanks for opening this issue.

/cc @stuartwdouglas

**Comment by stuartwdouglas** [comment]
@dmlloyd can JBoss Logging handle this ATM?

**Comment by dmlloyd** [comment]
Yes, it should be trivial to add a property to the console handler config to specify whether the output should go to console, stdout, or stderr.

**Comment by bpasson** [comment]
If there is anything I can do to help out let me know.
