### ISSUE TITLE
Change plugin native-image.docker-build property to native-image.container-build

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#958]
Regarding $subject, Red Hat has been replacing references to "docker" with "container" where applicable, so Quarkus should do so here as well unless there is a compelling reason not to.

**Comment by gunnarmorling** [comment]
Ha, just came here to report the same issue, but it's there already :) Besides for the reason you describe, I also think it's current name is confusing because of the support for "podman" as container runtime. So the following option config would be valid but quite a bit confusing:

    -Dnative-image.docker-build=myBuilderImage -Dnative-image.container-runtime=podman

**Comment by gsmet** [comment]
It would be nice if we could do it in a backward-compatible way.

**Comment by quintesse** [comment]
Wouldn't it be enough to support both and just log a warning saying the older is deprecated and remove it at some point in the future. Also remove mention of it from any docs and only mention the new one.

**Comment by gsmet** [comment]
@quintesse yup, exactly.

**Comment by gsmet** [comment]
This has been done a loooong time ago.
