### ISSUE TITLE
Offer a quarkus:remote-dev in binary form

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9585]
Offer a quarkus:remote-dev command not requiring maven / gradle tooling and be more friendly to deployment tools.

Related to #9271

**Comment by emmanuelbernard** [comment]
Is that done in master @stuartwdouglas or is it looking good for 1.6?
I'm asking to move to 1.7 if not on the roadmap.

**Comment by stuartwdouglas** [comment]
It is done. It does need a blog post but I will do that once it is released.
