### ISSUE TITLE
Change target package format to facilitate tooling

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9587]

**Comment by emmanuelbernard** [comment]
@maxandersen @stuartwdouglas add details please

**Comment by maxandersen** [comment]
@stuartwdouglas  what PR was it you said contained this ? my searches are not finding it.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/9394

**Comment by emmanuelbernard** [comment]
So it's really the reaugment stuff, mind if I close this one?

**Comment by stuartwdouglas** [comment]
The re-augment stuff still has not been merged, but I think the basic fast-jar format is probably enough to resolve this issue.

**Comment by emmanuelbernard** [comment]
Where has fatjart it landed? 1.5 or master?

**Comment by geoand** [comment]
`1.5` contains the new `fast-jar`, but it's undocumented so far. One would need to look at the package config to see the new value

**Comment by stuartwdouglas** [comment]
Note this is just the basic fast-jar support, support for reaugmentation was only merged into master last night.
