### ISSUE TITLE
code.quarkus.io should have option for including maven repository in its resulting projects

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9588]
for code.quarkus.redhat.com there are the issue that some of the extensions are only served from maven.repository.redhat.com.  You can have similar for other platforms or company specific code.quarku instances.

proposal is that code.quarkus.io gets a flag or env setting that enables it to include a maven repository setup for its generated projects.

**Comment by emmanuelbernard** [comment]
removing from roadmap until more details are in

**Comment by maxandersen** [comment]
@ia3andy can you think of any other way to solve this than have code.quarkus have option to pass in to include a specific repository ?

**Comment by ia3andy** [comment]
@maxandersen I guess we could add an option to the CodeGenerator so specify a maven repository, and then activate it for code.quarkus.redhat.com, wdyt?

**Comment by ia3andy** [comment]
@maxandersen, @tqvarnst is asking for this, wdyt of my suggestion?

**Comment by maxandersen** [comment]
I'm all good. If you read my comment just before i suggest the exact same thing :)
