### ISSUE TITLE
Have a catalog to describe community quarkus extensions  with and without a platform

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#9592]
**Description**
Issue to capture the work @gastaldi started around extension registry.

this is about having catalog defined, created and setup to publish to a registry as basis for first exploration.

**Comment by gastaldi** [comment]
In https://github.com/quarkusio/quarkus-extension-catalog, community extensions can be published as separate JSON files under the `extensions/` directory (see https://github.com/quarkusio/quarkus-extension-catalog#extensions)
