### ISSUE TITLE
Add initial implementation of list/add/remove extension utilizing registry

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#9593]
**Description**

list/add/remove extension should get implemented using registry from #9294  

in addition list should with this be able to find extensions that are not directly part of released platform,
add/remove should be able to figure out if need to explicit add version info in case not part of include BOM.

**Comment by emmanuelbernard** [comment]
Will this one be in 1.6 int he end? Or more 1.7?

**Comment by gastaldi** [comment]
The original idea is to be in 1.6 AFAIK

**Comment by gastaldi** [comment]
Looks like the 1.6 ship has sailed. Targetting 1.7
