### ISSUE TITLE
Native build fail to run on Docker

### ISSUE THREAD

**Issue by agagliardi** [quarkusio/quarkus#9640]
**Describe the bug**
Docker run of a native build of an app created with quarkus-maven-plugin fail to start with the error message:
standard_init_linux.go:211: exec user process caused "no such file or directory"

Workaround:
ldd application
	linux-vdso.so.1 (0x00007ffe08bbc000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc72ec59000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc72ea55000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc72e83e000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc72e635000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc72e272000)
	/home/linuxbrew/.linuxbrew/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007fc72ee79000)

Adding this in the DockerFile

RUN mkdir -p /home/linuxbrew/.linuxbrew/lib  && \
         ln -s /lib64/ld-linux-x86-64.so.2 /home/linuxbrew/.linuxbrew/lib/ld.so

**Expected behavior**
[io.quarkus] (main) rest-hero 1.0-SNAPSHOT (powered by Quarkus 1.4.2.Final) started in 0.015s. Listening on: http://0.0.0.0:8080

**Actual behavior**
standard_init_linux.go:211: exec user process caused "no such file or directory"

**To Reproduce**
1.mvn io.quarkus:quarkus-maven-plugin:1.4.2.Final:create \       
     -DprojectGroupId=org.acme \
     -DprojectArtifactId=getting-started \
     -DclassName="org.acme.getting.started.GreetingResource" \
     -Dpath="/hello"
2. mvn clean package -Pnative -Dnative-image.docker-build=true -DskipTests 
3. docker build -f src/main/docker/Dockerfile.native -t quarkus/getting-started
4. docker run -i --rm -p 8080:8080 quarkus/getting-started  

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux xxx 3.10.0-1062.18.1.el7.x86_64 #1 SMP Wed Feb 12 14:08:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

 - Quarkus version or git rev: 
1.4.2

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

Apache Maven 3.6.3
Docker version 19.03.9, build 9d988398e7

**Comment by gsmet** [comment]
Which Dockerfile are you using?

/cc @cescoffier

**Comment by agagliardi** [comment]
Sorry, I've lot the notification.

Docker version 19.03.11, build 42e35e61f3

**Comment by cescoffier** [comment]
@agagliardi Which Linux distribution are you using?

**Comment by agagliardi** [comment]
@cescoffier 
RHEL 7.7
Reproduced with base image:
- registry.access.redhat.com/ubi8/ubi-minimal:8.1
- amd64/alpine:latest (needs `apk add libc6-compat`)

**Comment by cescoffier** [comment]
I don't understand why it tries to use `/home/linuxbrew/.linuxbrew/lib/ld.so`. From your instruction, the native executable is built in a container, so it should not be linked with libraries from your host. 

Can you try with:

```
mvn clean package -Pnative -Dquarkus.native.container-build=true -DskipTests
```

It seems that you got the wrong system property.

**Comment by agagliardi** [comment]
Your right. Building within the container works as expected. Should be something wrong with my environment. Thanks for your help!
