### ISSUE TITLE
Bytecode recorder can not record ResteasyDeployment properties

### ISSUE THREAD

**Issue by pedroigor** [quarkusio/quarkus#9647]
**Describe the bug**

When using a `ResteasyDeploymentCustomizerBuildItem` to customize the deployment, properties set using the build item are not recorded.

It seems the recorder can not record the properties because`ResteasyDeploymentImpl` is lacking a getter/setter.

**Expected behavior**

Resteasy extension should respect the properties set by an extension using `ResteasyDeploymentCustomizerBuildItem`.

**Actual behavior**

`ResteasyDeployment` properties are not recorded.

**To Reproduce**

```java
   @BuildStep
    void configureRestEasy(BuildProducer<ResteasyDeploymentCustomizerBuildItem> deploymentCustomizerProducer) {
        deploymentCustomizerProducer.produce(new ResteasyDeploymentCustomizerBuildItem(new Consumer<ResteasyDeployment>() {
            @Override
            public void accept(ResteasyDeployment deployment) {
                deployment.setProperty("key", "value");
            }
        }));
    }
```

**Configuration**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Quarkus 1.5.0.CR1 (and master)

**Additional context**
N/A

**Comment by geoand** [comment]
@pedroigor which properties aren't being set?

The existing codebase does use `ResteasyDeploymentCustomizerBuildItem` here: https://github.com/quarkusio/quarkus/blob/341b54ff25e24a80eb7dc3d2233622b77bbe4ef9/extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/SpringWebProcessor.java#L174 and that works just fine

**Comment by pedroigor** [comment]
@geoand I looked that code. But when setting the deployment properties (`deployment.setProperty("key", "value")`) they are not there when the `io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder#staticInit` is called. Even though the properties are there when running the build step that calls that recorder method.

**Comment by geoand** [comment]
@pedroigor https://github.com/quarkusio/quarkus/pull/9661 should fix the problem
