### ISSUE TITLE
Allow extensions to disable the banner

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#9658]
**Description**
When working on Google Cloud Function support, I find the banner not displayed correctly.
They uses there own logging system (JUL) and the banner is displayed when the Quarkus ends and not when Quarkus starts !

Moreover, logs are available on a web console where a banner don't make a lot of sense.

**Implementation ideas**
Allow extensions to publish a build item that will disable the banner.

**Comment by geoand** [comment]
You should be able to do this today:

Just create a `RunTimeConfigurationDefaultBuildItem` with `quarkus.banner.enabled` as the key and `false` as the value and it should work.

**Comment by machi1990** [comment]
> You should be able to do this today:
> 
> Just create a `RunTimeConfigurationDefaultBuildItem` with `quarkus.banner.enabled` as the key and `false` as the value and it should work.

We should probably add this in this guide https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/writing-extensions.adoc

**Comment by geoand** [comment]
I'll let @loicmathieu do that after he confirms it actually does work :)

**Comment by loicmathieu** [comment]
The following code do the trick:
```
    @BuildStep
    public RunTimeConfigurationDefaultBuildItem disableBanner(){
        // the banner is not displayed well inside the Google Cloud Function logs
        return new RunTimeConfigurationDefaultBuildItem("quarkus.banner.enabled", "false");
    }
```

Regarding the extension author guide, it misses a lot of documentation about all the various build items that we can use ...
It don't know where to put this one ... maybe inside the configuration section explaining how we can control other extension configuration ?
By the way, this is for runtime configuration, can we also control build time one ?

**Comment by geoand** [comment]
This trick will only work for runtime configuration, it's only good for setting a default (this is essentially the same as `defaultValue` of `ConfigItem` does)

**Comment by radcortez** [comment]
While nothing is stopping extensions from doing things like this now, it is unreliable. Another extension, may be enabling the banner, and we have no way of knowing which is the correct configuration or which will win.
