### ISSUE TITLE
Better document the logging levels...

### ISSUE THREAD

**Issue by sorin-costea** [quarkusio/quarkus#9667]
**Description**
I needed days only to figure out how logging in Quarkus has to be configured. Can we do something to document it better?

**Implementation ideas**
This is how I understand Q logging - after reading the logging guide, trying with a zillion combinations and pouring through SO...
```
quarkus.log.console.enable=true <--- do this or you'll never ever see anything in the console
quarkus.log.level=FINE <--- do this because NO MATTER what you put after that anything below this level will be ignored
quarkus.log.console.level=FINE  <--- do this because NO MATTER what you put after that anything below this level will be ignored in console
quarkus.log.category."io.quarkus".level=WARNING <--- now take out everything you don't need
quarkus.log.category."org.sorincos".level=FINE <--- and categories will work as well
```
I stand to be corrected but the above is the ONLY way I was able to see something in both Maven build logs and Eclipse console. 

_(Of course the logger itself and -D will bring you only so far but that's for another issue)_

**Comment by loicmathieu** [comment]
@sorin-costea I plan to work on improving the logging guide. 

`quarkus.log.console.enable` is true by default so you should be able to remove it. Can you try and give feedback ?

`quarkus.log.console.level` is by default at `ALL` so you should be able to skip this as it will by default emit all log events, the configuration property `quarkus.log.level` should be enought. Can you try and give feedback ?

You talk about logs inside Maven build and Eclipse, do you see a difference in behaviour between these two ?
