### ISSUE TITLE
GZip filter doesn't work

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#9671]
**Describe the bug**
I followed the steps in https://quarkus.io/guides/rest-json#gzip-support but the filter doesn't seem to be activated.

**Expected behavior**
Content will be compressed as GZIP 

**Actual behavior**
No GZIP compression

**To Reproduce**
1. Create any endpoint with code.quarkus.io
2. Add `quarkus.resteasy.gzip.enabled=true` to application.properties
3. Run `http localhost:8080/hello Content-Encoding:gzip Accept-Encoding:gzip`

**Configuration**
```properties
quarkus.resteasy.gzip.enabled=true
```
**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Fedora 32
 - Output of `java -version`: OpenJDK 11
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.5.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3 

**Additional context**

It looks like the `Content-Encoding` and `Accept-Encoding` headers are not propagated to the internal Vert.x Request, thus making `org.jboss.resteasy.plugins.interceptors.GZIPEncodingInterceptor` ignore the request to GZIP the output

**Comment by gastaldi** [comment]
Something tells me that the following line is wrong: 

https://github.com/resteasy/Resteasy/blob/master/resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/GZIPEncodingInterceptor.java#L78

It should be testing if `Accept-Encoding` contains `gzip` instead

**Comment by glefloch** [comment]
I would like to work on that.

**Comment by stuartwdouglas** [comment]
I think this is a RESTEasy bug rather than a Quarkus one.

**Comment by glefloch** [comment]
I haven't got much time to work on it, but while debugging on a sample project, headers where looking ok on the quarkus side.

**Comment by asoldano** [comment]
@liweinan, can you check this please?

**Comment by geoand** [comment]
We had someone else report this as well. @liweinan were you able to look into this one?

**Comment by jessequinn** [comment]
@gastaldi agreed. as the standard i believe is application/gzip and not just gzip.

**Comment by tsfullman** [comment]
I am hitting this as well or at least something similar when trying to return compressed JSON. I stepped through the GZIPEncodingInterceptor code and if you add the @GZIP annotation to the rest method it finds "gzip" under the Content-encoding, but still always returns json instead of encoded. I had to write my own interceptor to accomplish what I wanted. I only tested on quarkus 1.7.5.Final though and not the latest yet.

**Comment by dfa1** [comment]
As a temporary workaround I'm using the following code since June. 

```
/**
 * Custom gzip support, workaround for https://github.com/quarkusio/quarkus/issues/9671
 *
 * NB: must be deleted when quarkus will have proper gzip support.
 */
@Provider
public class GzipSupport implements ReaderInterceptor, WriterInterceptor {

    public static final String COMPRESS_RESPONSE = "__COMPRESS_RESPONSE__";

    @Override
    public Object aroundReadFrom(ReaderInterceptorContext context) throws IOException {
        MultivaluedMap<String, String> headers = context.getHeaders();
        String wantedEncoding = headers.getFirst(HttpHeaders.ACCEPT_ENCODING);
        if (wantedEncoding != null && wantedEncoding.contains("gzip")) {
            context.setProperty(COMPRESS_RESPONSE, true);
        }
        return context.proceed();
    }

    @Override
    public void aroundWriteTo(WriterInterceptorContext context) throws IOException {
        if (Boolean.TRUE.equals(context.getProperty(COMPRESS_RESPONSE))) {
            MultivaluedMap<String, Object> headers = context.getHeaders();
            headers.add(HttpHeaders.CONTENT_ENCODING, "gzip");
            OutputStream outputStream = context.getOutputStream();
            context.setOutputStream(new GZIPOutputStream(outputStream));
        }
        context.proceed();
    }
}
```

**Comment by pcasaes** [comment]
@jessequinn @gastaldi That line in the resteasy interceptor looks correct

```java
     Object encoding = context.getHeaders().getFirst(HttpHeaders.CONTENT_ENCODING);
```

In this case the headers being checked are response headers not request headers. When accepting gzip from a request the server should respond with the headers **Content-Encoding: gzip**

**Comment by BastianSperrhacke-Otto** [comment]
Hello everyone. First of all: +1 for this topic.
The workaround from @dfa1  does not work for me, the interceptor methods are called in a wrong Order (aroundWriteTo first), which is kind of confusing to me...

Nevertheless I rewrote a workaround which is working for me (even shorter):
``@Provider
public class GzipSupport  implements ContainerResponseFilter {

    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext)
            throws IOException {
        String encoding = requestContext.getHeaderString(HttpHeaders.ACCEPT_ENCODING);
        if(encoding != null && encoding.contains("gzip")) {
            responseContext.getHeaders().put(HttpHeaders.CONTENT_ENCODING, Arrays.asList("gzip"));
            OutputStream outputStream = responseContext.getEntityStream();
            responseContext.setEntityStream(new GZIPOutputStream(outputStream));
        }
    }
}``

**Comment by dfa1** [comment]
@BastianSperrhacke-Otto does your class support reading a gzipped request as well?

**Comment by BastianSperrhacke-Otto** [comment]
No, but my Test does:
```
    public void sendCompressedRequestAndAssert(WebTarget testTarget ) {
        Response response = testTarget
                .request()
                .accept(MediaType.APPLICATION_JSON)
                .header(HttpHeaders.ACCEPT_ENCODING, "gzip")
                .get();

        Assertions.assertEquals(Response.Status.OK.getStatusCode(), response.getStatus(), testTarget.toString());
        InputStream respBody = response.readEntity(InputStream.class);
        Assertions.assertNotNull(respBody);
        String json = null;
        try {
            json = unzipGzip(respBody);
        } catch (IOException e) {
            Assertions.fail(e);
        }
        Assertions.assertTrue(json.contains("myjsonvalue"));
        Assertions.assertEquals("gzip", response.getHeaderString("Content-Encoding"));
    }

    private String unzipGzip(InputStream messageCompressed) throws IOException {
        try(GZIPInputStream gzip = new GZIPInputStream(messageCompressed);
             InputStreamReader inputStreamReader = new InputStreamReader(gzip, StandardCharsets.UTF_8);
             BufferedReader bufferedReader = new BufferedReader(inputStreamReader);) {
            StringBuilder output = new StringBuilder();
            String line;
            while ((line = bufferedReader.readLine()) != null) {
                output.append(line);
            }
            return output.toString();
        }
    }
```

**Comment by stuartwdouglas** [comment]
I just wrote a test for this and it appears to work, the main issue is that the docs don't mention that you need a @GZIP annotation for this to take effect.

**Comment by StFS** [comment]
@stuartwdouglas good catch with the `@GZIP` annotation and the lack of documentation. However, it still seems that the `quarkus.resteasy.gzip.max-input` property is ignored. I'm only able to send 10M gzipped requests even though I configure that property to something much larger.

I ended up creating my own interceptor along with an ObservableInputStream to keep track of the amount of data read. It's written in Kotlin though but if it helps anyone I'm sharing it here:

```kotlin
package com.genuitysci.fileservice.interceptor

import io.quarkus.runtime.configuration.MemorySize
import org.eclipse.microprofile.config.ConfigProvider
import org.jboss.resteasy.resteasy_jaxrs.i18n.Messages
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.math.BigInteger
import java.util.zip.GZIPInputStream
import java.util.zip.GZIPOutputStream
import javax.ws.rs.WebApplicationException
import javax.ws.rs.core.HttpHeaders
import javax.ws.rs.core.Response
import javax.ws.rs.core.Response.Status.*
import javax.ws.rs.ext.*


/**
 * Custom gzip support, workaround for https://github.com/quarkusio/quarkus/issues/12647
 * - even though the issue was closed, it's not fixed!
 *
 * NB: should be deleted when quarkus will have proper built-in gzip support.
 */
@Provider
class GZIPInterceptor : ReaderInterceptor, WriterInterceptor {

    // The below properties are lazy-loaded in this weird way to support native image building.
    //  The native build initializes all classes and if these properties were initialized in a
    //  constructor the would be initialized at build time and not runtime.

    private var _isEnabled: Boolean? = null
    private val isEnabled: Boolean
        get() {
            if (_isEnabled == null) {
                val quarkusResteasyGzipEnabled =
                    ConfigProvider.getConfig().getOptionalValue("quarkus.resteasy.gzip.enabled", Boolean::class.java)
                val workaroundResteasyGzipEnabled = ConfigProvider.getConfig()
                    .getOptionalValue("workaround.resteasy.gzip.enabled", Boolean::class.java)

                workaroundResteasyGzipEnabled.ifPresent {
                    quarkusResteasyGzipEnabled.ifPresent {
                        if (workaroundResteasyGzipEnabled.get() && quarkusResteasyGzipEnabled.get()) {
                            throw IOException("Can't have both Quarkus and workaround gzip interceptors enabled")
                        }
                    }
                    _isEnabled = workaroundResteasyGzipEnabled.get()
                }
            }
            return _isEnabled as Boolean
        }

    private var _maxInput: MemorySize? = null
    private val maxInputBytes: Long
        get() {
            if (_maxInput == null) {
                val workaroundResteasyGzipMaxInput = ConfigProvider.getConfig()
                    .getOptionalValue("workaround.resteasy.gzip.max-input", MemorySize::class.java)
                if (workaroundResteasyGzipMaxInput.isPresent) {
                    _maxInput = workaroundResteasyGzipMaxInput.get()
                } else {
                    _maxInput = MemorySize(BigInteger.valueOf(100 * 1024 * 1024)) // Default to 100M
                }
            }
            return _maxInput!!.asLongValue()
        }


    @Throws(IOException::class)
    override fun aroundReadFrom(context: ReaderInterceptorContext): Any {
        if (!isEnabled) {
            return context.proceed()
        }

        val clientAcceptEncodingHeaders = context.headers[HttpHeaders.ACCEPT_ENCODING]
        val clientAcceptsGzip = clientAcceptEncodingHeaders?.flatMap { headerLine ->
            headerLine.split(",").map { headerItem -> headerItem.trim() }
        }?.contains("gzip") ?: false

        if (clientAcceptsGzip) {
            context.setProperty(COMPRESS_RESPONSE, true)
        }
        val requestContentEncoding = context.headers.getFirst(HttpHeaders.CONTENT_ENCODING)
        if (requestContentEncoding?.contains("gzip") == true) {
            context.inputStream = ObservableInputStream(GZIPInputStream(context.inputStream)) { bytesRead ->
                if (bytesRead > maxInputBytes) {
                    // We can only do this after we've read the content as streams usually don't support reporting size
                    val size = if (maxInputBytes > Int.MAX_VALUE) Int.MAX_VALUE else maxInputBytes.toInt()
                    throw WebApplicationException(
                        Response.status(REQUEST_ENTITY_TOO_LARGE)
                            .entity(Messages.MESSAGES.gzipExceedsMaxSize(size)).build()
                    )
                }
            }
        }
        return context.proceed()
    }

    @Throws(IOException::class)
    override fun aroundWriteTo(context: WriterInterceptorContext) {
        if (!isEnabled) {
            return context.proceed()
        }

        if (true == context.getProperty(COMPRESS_RESPONSE)) {
            val headers = context.headers
            headers.add(HttpHeaders.CONTENT_ENCODING, "gzip")
            context.outputStream = GZIPOutputStream(context.outputStream)
        }
        context.proceed()
    }

    companion object {
        const val COMPRESS_RESPONSE = "__COMPRESS_RESPONSE__"
    }
}

/**
 * An input stream that observes the amount of data streamed and reports it to a callback function.
 */
class ObservableInputStream(
    private val wrapped: InputStream,
    private val onBytesRead: (Long) -> Unit
) : InputStream() {
    private var bytesRead: Long = 0

    // Delegate all read methods of InputStream, collecting the bytes read.

    @Throws(IOException::class)
    override fun read(): Int {
        val res = wrapped.read()
        if (res > -1) {
            bytesRead++
        }
        onBytesRead(bytesRead)
        return res
    }

    @Throws(IOException::class)
    override fun read(b: ByteArray): Int {
        val res = wrapped.read(b)
        if (res > -1) {
            bytesRead += res
            onBytesRead(bytesRead)
        }
        return res
    }

    @Throws(IOException::class)
    override fun read(b: ByteArray, off: Int, len: Int): Int {
        val res = wrapped.read(b, off, len)
        if (res > -1) {
            bytesRead += res
            onBytesRead(bytesRead)
        }
        return res
    }

    @Throws(IOException::class)
    override fun readAllBytes(): ByteArray {
        val res = wrapped.readAllBytes()
        bytesRead += res.size
        onBytesRead(bytesRead)
        return res
    }

    @Throws(IOException::class)
    override fun readNBytes(len: Int): ByteArray {
        val res = wrapped.readNBytes(len)
        bytesRead += res.size
        onBytesRead(bytesRead)
        return res
    }

    @Throws(IOException::class)
    override fun readNBytes(b: ByteArray, off: Int, len: Int): Int {
        val res = wrapped.readNBytes(b, off, len)
        bytesRead += res
        onBytesRead(bytesRead)
        return res
    }

    @Throws(IOException::class)
    override fun transferTo(out: OutputStream): Long {
        val res = wrapped.transferTo(out)
        bytesRead += res
        onBytesRead(bytesRead)
        return res
    }

    // Delegate all other methods of InputStream directly

    @Throws(IOException::class)
    override fun close() {
        wrapped.close()
    }

    @Throws(IOException::class)
    override fun skip(n: Long): Long {
        return wrapped.skip(n)
    }

    @Throws(IOException::class)
    override fun available(): Int {
        return wrapped.available()
    }

    override fun mark(readlimit: Int) {
        wrapped.mark(readlimit)
    }

    @Throws(IOException::class)
    override fun reset() {
        wrapped.reset()
    }

    override fun markSupported(): Boolean {
        return wrapped.markSupported()
    }
}
```

**Comment by stuartwdouglas** [comment]
The issue is that there is a global quarkus.http.limits.max-body-size that defaults to 10mb for requests. If you are using compressed requests (which are not part of the HTTP standard) then the gzip param will take effect if it is smaller than the global limit, but compressed requests are non-standard and very rare (e.g. a browser will never send one).

**Comment by StFS** [comment]
Hmm... ok so I apologize in advance if I'm just complicating things @stuartwdouglas but I'm still not getting things to work.

So my project is a simple REST service that has a PUT method. I've annotated that function with `@GZIP` and for small payloads that seems to work fine.

```kotlin
    @PUT
    @Path("{project}/{path:.*}")
    @Produces(MediaType.APPLICATION_JSON)
    @GZIP
    fun upload(
        @PathParam project: String,
        @PathParam path: String,
        @QueryParam("uploadId") uploadId: String?,
        @QueryParam("partNumber") partNumber: Int?,
        body: InputStream
    ): FileUploadResponse {

        return try {
            if (uploadId != null && partNumber != null) {
                fileTransferService.writeFilePart(project, path, uploadId, partNumber, body)
            } else {
                fileTransferService.writeFile(project, path, body)
            }
        } catch (e: WebApplicationException) {
            throw e
        } catch (e: Exception) {
            println("Woops... something went wrong: ${e.message}")
            e.printStackTrace()
            throw WebApplicationException("Something went wrong", e, Response.Status.NOT_IMPLEMENTED)
        }
    }
```

My `application.settings` are as follows:

```
quarkus.http.limits.max-body-size=10G

quarkus.resteasy.gzip.enabled=true
quarkus.resteasy.gzip.max-input=300M
```

And here is the result of running a `curl` command that sends a small gzipped file as a payload:

```
curl -v -s -D- -X PUT 'http://localhost:8080/fts/prj/gzipped_payload.txt' -H "Content-Encoding: gzip" --data-binary "@/Users/stefan/work/gor/quarkus/file-transfer-service/data/http-content-data/temp_3M_file.gz" --compressed              ─╯
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> PUT /fts/prj/gzipped_payload.txt HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Encoding: gzip
> Content-Length: 3096
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
* Done waiting for 100-continue
* We are completely uploaded and fine
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Encoding: gzip
Content-Encoding: gzip
< Content-Length: 94
Content-Length: 94
< Content-Type: application/json
Content-Type: application/json

<
* Connection #0 to host localhost left intact
{"response":"FileUploadCompletedResponse","projectId":"prj","path":"gzipped_payload.txt"}* Closing connection 0
```

And here's the output when I run `curl` with a gzip file that is larger.. the size of the .gz file that I'm sending below is 199K which expands to 200M:

```
❯ curl -v -s -D- -X PUT 'http://localhost:8080/fts/prj/gzipped_payload.txt' -H "Content-Encoding: gzip" --data-binary "@/Users/stefan/work/gor/quarkus/file-transfer-service/data/http-content-data/temp_200M_file.gz" --compressed            ─╯
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> PUT /fts/prj/gzipped_payload.txt HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Encoding: gzip
> Content-Length: 203875
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
* Done waiting for 100-continue
* We are completely uploaded and fine
< HTTP/1.1 413 Request Entity Too Large
HTTP/1.1 413 Request Entity Too Large
< Content-Encoding: gzip
Content-Encoding: gzip
< Content-Length: 68
Content-Length: 68
< Content-Type: application/json
Content-Type: application/json

<
* Connection #0 to host localhost left intact
RESTEASY003357: GZIP input exceeds max size: 10000000* Closing connection 0
```

So in this case, both `quarkus.resteasy.gzip.max-input` and `quarkus.http.limits.max-body-size` are set to much more than 200M (which is the expanded size of the gz body) but it's still failing, citing a max size of 10_000_000 which is not something I'm setting anywhere.

So again, sorry if I'm just confusing matters, this might actually not be the correct place for this problem, I'm just so happy to get in contact with somebody who seems to be able and willing to fix it :)

**Comment by stuartwdouglas** [comment]
@patriot1burke @asoldano  I am not sure what the correct fix is here. In org.jboss.resteasy.plugins.interceptors.GZIPDecodingInterceptor#getMaxSize it attempts to read the config via 

      ResteasyConfiguration context = ResteasyContext.getContextData(ResteasyConfiguration.class);

But for standalone mode the context is always null (this works if Undertow is present).

When Resteasy standalone does bootstrap it does not call org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap#createDeployment which seems to be what sets this up for Undertow. Do we need to copy this logic into RESTEasy standalone somehow?

**Comment by patriot1burke** [comment]
Yeah, I probably missed some initialization code.  I'll assign this issue to myself.

**Comment by StFS** [comment]
Any news on solving this @patriot1burke ?

**Comment by patriot1burke** [comment]
@StFS Attached PR incoming.  This should fix a lot of config issues for Resteasy Standalone.  You'll configure via application.properties

**Comment by marcelstoer** [comment]
The latest is this

>  WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.resteasy.gzip.enabled" was provided;
>  WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.resteasy.gzip.max-input" was provided;

Is https://quarkus.io/guides/rest-json#gzip-support outdated?

**Comment by rgmz** [comment]
> Oh...no, things are just different for resteasy-reactive.

@marcelstoer: Did you by chance figure out what configuration is necessary for resteasy-reactive? 👀

**Comment by liweinan** [comment]
Sorry I missed this issue long before :D

I'll check the `resteasy-reactive` side of this issue.

**Comment by cylab** [comment]
@liweinan any findings?

**Comment by gsmet** [comment]
@geoand do we have a GZip filter in RESTEasy Reactive?

**Comment by geoand** [comment]
Not currently

**Comment by gsmet** [comment]
@geoand could you create an issue with it (you will be able to be more specific than I would)? Because I have seen quite a lot of people using the GZip filter for RESTEasy and it makes total sense if you're paying for the traffic.

**Comment by geoand** [comment]
We already have https://github.com/quarkusio/quarkus/issues/16425

**Comment by gsmet** [comment]
OK. I added it to the board here:
https://github.com/orgs/quarkusio/projects/13/views/18

Because I really think it's something we will need for 2.8.

**Comment by geoand** [comment]
That is very unlikely to happen for `2.8`. The issue is that we likely want to use Vert.x's GZIP support, but that will take some time to figure out

**Comment by liweinan** [comment]
@cylab Sorry I was busy on other tasks at hands. @gsmet @geoand Thanks for checking this!

**Comment by itzsuman** [comment]
> Hello everyone. First of all: +1 for this topic. The workaround from @dfa1 does not work for me, the interceptor methods are called in a wrong Order (aroundWriteTo first), which is kind of confusing to me...
> 
> Nevertheless I rewrote a workaround which is working for me (even shorter):
> 
> ```
> @Provider
> public class GzipSupport  implements ContainerResponseFilter {
>     @Override
>     public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext)
>             throws IOException {
>         String encoding = requestContext.getHeaderString(HttpHeaders.ACCEPT_ENCODING);
>         if(encoding != null && encoding.contains("gzip")) {
>             responseContext.getHeaders().put(HttpHeaders.CONTENT_ENCODING, Arrays.asList("gzip"));
>             OutputStream outputStream = responseContext.getEntityStream();
>             responseContext.setEntityStream(new GZIPOutputStream(outputStream));
>         }
>     }
> }
> ```

In my case response is gzip'd but getting weird characters in response like 
��`I�%&/m�{J�J��t�`$ؐ@�������iG#)�*��eVe]f@�흼��{����{����;�N'���?\fdl��J�ɞ!���?~|?"~�G�����~�߿�^�=��'.������V�by�/��f�2?/&�,[N�ٴ*�|�R��F�y�~�nW��^��ϋ����-�

@BastianSperrhacke-Otto Do I need to pass any extra header other than Accept-Encoding: gzip.

**Comment by dfa1** [comment]
@itzsuman I'm surprised that you still need the workaround. I'm running with quarkus 2.13.3 and the workaround is not needed anymore!

**Comment by itzsuman** [comment]
> @itzsuman I'm surprised that you still need the workaround. I'm running with quarkus 2.13.3 and the workaround is not needed anymore!

yes , you are right Quarkus http compression available but if I add quarkus-amazon-lambda-rest dependency then it's not working , even with resteasy-reactive-jackson dependency also http compression not working . Hence I need this workaround. 

Fyi, [https://github.com/quarkusio/quarkus/issues/34472](url)
