### ISSUE TITLE
Docker --build-arg property for extension container-image-docker

### ISSUE THREAD

**Issue by haraldatbmw** [quarkusio/quarkus#9676]
**Describe the bug**
Using the extension **container-image-docker** there is no way to pass dockers `--build-arg`.
My docker build (Dockerfile.jvm) fails because I'm behind a proxy and during build internet connectivity is needed (RUN microdnf install ...).

I need run the docker build like `docker build --build-arg http_proxy=http://localhost:3128 --build-arg https_proxy=http://localhost:3128 ...`

**Expected behavior**
The extension has a property inside application.properties to be able to configure dockers build-arg.

**Actual behavior**
No configuration option

**To Reproduce**
1. Add extension container-image-docker to pom.xml
2. Be sure to be behind a proxy
3. Let the extension do your docker build.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17134.1488]
 - Output of `java -version`: 
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.5.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by haraldatbmw** [comment]
cc @geoand

**Comment by geoand** [comment]
#9678 introduces that ability.

By just adding:

```
quarkus.docker.build-args.http_proxy=http://localhost:3128
quarkus.docker.build-args.https_proxy=http://localhost:3128
```

the docker command would now be something like:

```
docker build -f /home/gandrian/projects/redhat/quarkus-quickstarts/getting-started/src/main/docker/Dockerfile.jvm --build-arg http_proxy=http://localhost:3128 --build-arg https_proxy=http://localhost:3128 -t geoand/my-app:1.0-SNAPSHOT /home/gandrian/projects/redhat/quarkus-quickstarts/getting-started
```
