### ISSUE TITLE
Logging: support microseconds in %d log pattern

### ISSUE THREAD

**Issue by rquinio** [quarkusio/quarkus#9679]
**Description**

The current implementation is based on SimpleDateFormat and is limited to milliseconds (i.e. %d{SSSSSS} does not work and prefixes with 000).
https://github.com/jboss-logging/jboss-logmanager/blob/master/core/src/main/java/org/jboss/logmanager/formatters/Formatters.java#L443-L458

With Java 9+, OpenJDK added support for better precision than milliseconds/nano-of-second (https://bugs.openjdk.java.net/browse/JDK-8068730).

Quarkus being supersonic, its logging should support this ! :p

**Implementation ideas**

Since [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html ) was added in Java 8, maybe there's a fallback and it doesn't have to wait for Quarkus to drop Java 8 support ?

**Comment by gkfirst8** [comment]
This is also useful to match the format that AWS needs in awslogs-datetime-format. That is following Pythons logging format: https://strftime.org/ which expects 'Microseconds'.

**Comment by jamezp** [comment]
@geoand Once the log manager is updated to the 3.0.2.Final version that @dmlloyd is working on, then the `%d` pattern uses the `java.time.format.DateTimeFormatter` so the patterns supported there will work.

**Comment by geoand** [comment]
Excellent!
