### ISSUE TITLE
Allow CDI bean creation from picocli args parsing

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#9684]
**Description**
The purpose of the feature would be to wait until Picocli ends the CLI parsing to configure and create CDI Beans. 

**Implementation ideas**
I found 2 options for now:
1- Define a custom Picocli Execution Strategy just to capture the parsed CLI before the command execution. Then use CDI Events to fire an event , another method is observing this event, once catch build the bean and store it in property. Finally a getter-like is anotated `@Produces` to make this object available.

2- the Command is a callable returning the CDI  and annotated @Produces + injection point delayed. The command has to be a singleton otherwise CDI creates one instance an Picocli another one. I guess this scenario only works with Cmmands/Sub-Commands

**Comment by geoand** [comment]
Releavant chat conversation: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/picocli.20DI

**Comment by geoand** [comment]
@danielpetisme IIUC by looking at https://github.com/danielpetisme/kafkactl, 

you essentially want to use `GlobalOptions` in a CDI producer?

**Comment by danielpetisme** [comment]
Yes, I want to use parsed arguments in a CDI producer

**Comment by geoand** [comment]
From what I saw from the picocli source code, this will require deep integration with it. 

cc @mgorniew @remkop

**Comment by danielpetisme** [comment]
Indeed, I had a look to and seems tricky to insert CDI actions in between
the args parsing and the command execution.
Even if it would neat, i'm really wondering if it's a good idea...

The limit between DI and picocli are not perfectly clear for me.

**Comment by geoand** [comment]
Ideially we should make it dead simple to do this kind of thing. It sounds like something very useful and common

**Comment by danielpetisme** [comment]
Should it be specific to picocli or do you thinks could be reused by other CLI libs?

**Comment by geoand** [comment]
Here we are talking about picocli specifically.

In vanilla command mode you can use the `@CommandLineArguments` as a CDI qualifier and then do your own parsing in a CDI producer method, but that is really tedious...

**Comment by remkop** [comment]
Hi @danielpetisme  and @geoand, I took a look at the chat conversation: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/picocli.20DI 

The custom execution strategy that Daniel suggested (near the end of the chat session) makes sense to me.

**Comment by mgorniew** [comment]
@remkop @geoand I've have some code prepared which will produce events as in @danielpetisme example. I wonder if it make any sense to also produce ParseResult like this:

```java
    @Produces
    public CommandLine.ParseResult picocliParseResult(CommandLine commandLine, @CommandLineArguments String[] args) {
        return commandLine.parseArgs(args);
    }
```

**Comment by remkop** [comment]
@mgorniew You are a rock star!
