### ISSUE TITLE
Hot reload with Gradle and Kotlin doesn't recognize `src/main/java`

### ISSUE THREAD

**Issue by joshuadavis** [quarkusio/quarkus#9688]
**Describe the bug**
Hot reload with Gradle and Kotlin doesn't recognize `src/main/java` changes.

**Expected behavior**
When Java files in `src/main/java` are changed in a Kotlin project, the classes are recompiled and hot reload functions.

**Actual behavior**
When Java files in `src/main/java` are changed in a Kotlin project nothing happens.   The classes are not compiled and there is no hot reload. 

**To Reproduce**
1. Create a gradle / kotlin / jaxrs quarkus project.
2. Add a `src/main/java` and add some Java code to that directory.   Either make a JAX-RS resource in Java, or have the Kotlin JAX-RS paths call the Java code.
3. Launch the application with `./gradlew quarkusDev`
4. Change one of the Java files.
5. Hit the API.
Observe: No recompilation.   Hot reload appears 

**Environment (please complete the following information):**
 - `Darwin JODAVIS-C02ZW3CMLVDL 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6ü15/RELEASE_X86_64 x86_64`
 - openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
 - GraalVM version graalvm                  
19.3.2              GraalVM Core        
native-image             19.3.2              Native Image        github.com
 - Quarkus version 1.4.2.Final
``` 
% ./gradlew --version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.15.4 x86_64
```

**Comment by glefloch** [comment]
Hi @joshuadavis with the recent gradle plugin update we have done, this is now working. 
Could you give a try with quarkus 1.8.1.Final ?
If this is working as expected, we could close this issue.

**Comment by evanchooly** [comment]
confirmed fixed.
