### ISSUE TITLE
Please adopt aws-lambda-java-events 3.1.0

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#9690]
**Description**
Please adopt **aws-lambda-java-event-3.1.0**, aws events underwent some major refactoring and now it supports **ApplicationLoadBalancerRequestEvent**, many of us were waiting for it for a long time

Hopefully it should be a straight forward adoption
https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-events

```xml
    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-lambda-java-core</artifactId>
        <version>1.2.1</version>
    </dependency>
    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-lambda-java-events</artifactId>
        <version>3.1.0</version>
    </dependency>
```

**Comment by geoand** [comment]
cc @patriot1burke @oztimpower

**Comment by oztimpower** [comment]
Submitted PR #9692. Tested and working ok on local build, and projects.

**Comment by geoand** [comment]
Thanks @oztimpower
