### ISSUE TITLE
Panache methods are not visible to IntelliJ IDEA’s “Evaluate Expression” debugger feature

### ISSUE THREAD

**Issue by Cellane** [quarkusio/quarkus#9701]
**Describe the bug**
After creating an empty Quarkus project and adding a few Panache entities (by following the Panache tutorial), everything works as expected when created endpoints are queried from an HTTP client or web browser.

However, after attaching IntelliJ IDEA’s debugger, pausing on a breakpoint inside request handler and attempting to use the “Evaluate Expression” feature, all Panache methods fail with an exception. The exception type is `java.lang.IllegalStateException`, with a detail message of `This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?`.

I tried two ways of attaching the debugger:
1. Adding a `main` method and running the Quarkus app as a normal Java application in debug mode.
2. Executing `compile quarkus:dev` Maven goals and attaching a remote debugger.

However, both methods yielded the same results.

**Expected behavior**
It would be nice if Panache methods could be executed from debugger and output could be evaluated in an interactive way.

**Actual behavior**
Panache methods fail with the `IllegalStateException` when executed from debugger’s “Evaluate Expression” feature.

**To Reproduce**
1. Create a blank project in IntelliJ IDEA, with Panache and database-of-choice extensions enabled
2. Add a Panache entity
3. Add an endpoint querying the entity
4. Have IDEA execute the `compile quarkus:dev` Maven goals
5. Configure a remote debugger connection on port 5005
6. Set a breakpoint inside the request handler
7. Trigger the breakpoint by accessing the request handler’s URL
8. Once paused, try executing any Panache method using the “Evaluate Expression” feature

**Screenshots**
<img width="586" alt="obrazek" src="https://user-images.githubusercontent.com/171604/83367231-7f35d600-a3ee-11ea-8dc7-d4dd5310b63e.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin Fenchurch.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
```
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment GraalVM EE 20.1.0 (build 11.0.7+8-LTS-jvmci-20.1-b02)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.1.0 (build 11.0.7+8-LTS-jvmci-20.1-b02, mixed mode, sharing)
```
 - Quarkus version or git rev: `1.4.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/Milan/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.7, vendor: Oracle Corporation, runtime: /Users/Milan/.jabba/jdk/graalvmee@20.1.0/Contents/Home
Default locale: cs_JP, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

**Additional context**
The issue was originally [reported as a question on StackOverflow](https://stackoverflow.com/questions/62077142/is-there-a-way-to-get-panache-queries-working-in-debugger-using-intellij-idea-s), but reposted here as requested.

**Comment by geoand** [comment]
Can you check and see if the following ugly work-around will work?

```
Class.forName(Author.class.getName(), true, ((Author)(Thread.currentThread().getContextClassLoader()).newInstance())).listAll()
```

**Comment by Cellane** [comment]
@geoand Unfortunately, it doesn’t look like it works.

<img width="586" alt="obrazek" src="https://user-images.githubusercontent.com/171604/83379949-ae147200-a417-11ea-96c5-31859a207d6b.png">

**Comment by geoand** [comment]
There isn't much we can do here unfortunately... Mind opening an issue in the IntelliJ tracker?

**Comment by Cellane** [comment]
Sorry for the delayed answer! Issue [opened over at YouTrack](https://youtrack.jetbrains.com/issue/IDEA-242531).

**Comment by geoand** [comment]
It seems like IntelliJ for whatever reason is not using the `Fruit` class loaded from the Thread Context ClassLoader and there is nothing we can do about it in Quarkus, so I'll close this
