### ISSUE TITLE
Websocket ServerContainer not found anymore

### ISSUE THREAD

**Issue by tandraschko** [quarkusio/quarkus#9702]
**Describe the bug**
In the past MyFaces correctly lookuped the ServerContainer and websockets worked.

**Expected behavior**
ServerContainer will be found like in older versions.
MyFaces includes io.quarkus:quarkus-undertow-websockets:jar:1.5.0.Final:compile for it

**Actual behavior**
no ServerContainer  found

**To Reproduce**
1. clone https://github.com/apache/myfaces
2. mvn install -DskipTests
3. cd extensions/quarkus/showcase
4. mvn compile quarkus:dev
5. you will notice a message like: f:websocket support enabled but cannot found websocket ServerContainer instance on current context.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by tandraschko** [comment]
See: https://github.com/apache/myfaces/blob/master/impl/src/main/java/org/apache/myfaces/webapp/AbstractFacesInitializer.java#L715

**Comment by stuartwdouglas** [comment]
You need to add quarkus-undertow-websockets as a dependency.

**Comment by tandraschko** [comment]
@stuartwdouglas if you do a mvn dependency:tree on the showcase, you will seee it:

[INFO] |  +- io.quarkus:quarkus-undertow-websockets:jar:1.5.1.Final:compile

**Comment by stuartwdouglas** [comment]
This is really odd, as I see it start to work if I add the dependency directly. @aloubyansky  this may be a resolver problem, but we have not really had any other reports of anything like this.

**Comment by stuartwdouglas** [comment]
It works if you add a dependency on quarkus-undertow-websockets-deployment in your -deployment module, but that still should not be necessary.

**Comment by aloubyansky** [comment]
When adding a dependency in extension E1 on extension E2 we do require adding a dependency in E1 runtime on E2 runtime and in E1 deployment on E2 deployment. We could make it optional but then we'd have to recursively process injected deployment dependency branches checking whether the found runtime extension artifacts have already been replaced (given that the deployment is supposed to always depend on the runtime artifact). To make the implementation simpler we decided to assume that when we resolve dependencies of the deployment artifact, it's a complete deployment branch for that artifact.
Here is how dependencies of the referenced reproducer could be simplified
````
diff --git a/extensions/quarkus/deployment/pom.xml b/extensions/quarkus/deployment/pom.xml
index 75ffd40f6..315112c2b 100644
--- a/extensions/quarkus/deployment/pom.xml
+++ b/extensions/quarkus/deployment/pom.xml
@@ -36,17 +36,7 @@
     <dependencies>
         <dependency>
             <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-core-deployment</artifactId>
-            <version>${quarkus.version}</version>
-        </dependency>
-        <dependency>
-            <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-arc-deployment</artifactId>
-            <version>${quarkus.version}</version>
-        </dependency>
-        <dependency>
-            <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-undertow-deployment</artifactId>
+            <artifactId>quarkus-undertow-websockets-deployment</artifactId>
             <version>${quarkus.version}</version>
         </dependency>
         <dependency>
````
````
     <build>
diff --git a/extensions/quarkus/runtime/pom.xml b/extensions/quarkus/runtime/pom.xml
index ca0271e8b..776537323 100644
--- a/extensions/quarkus/runtime/pom.xml
+++ b/extensions/quarkus/runtime/pom.xml
@@ -54,16 +54,6 @@
             <version>9.0.30</version>
         </dependency>
 
-        <dependency>
-            <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-core</artifactId>
-            <version>${quarkus.version}</version>
-        </dependency>
-        <dependency>
-            <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-undertow</artifactId>
-            <version>${quarkus.version}</version>
-        </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-undertow-websockets</artifactId>
````
I'm closing this issue for now.

**Comment by tandraschko** [comment]
works fine, thanks!
