### ISSUE TITLE
Create an integration test with both Hibernate and MongoDB with Panache

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#9722]
**Description**
Hibernate with Panache and MongoDB with Panache are both popular extensions that share some common concepts and code.

We have separate integration test for both, but we need to be sure that when using both in the same project it works.

**Implementation ideas**
Create an ingegration test with both extension that make some basic database access (simple CRUD).
It's not needed to make it run as a native integration test as it is already covered by the separate integration tests.

**Comment by loicmathieu** [comment]
@evanchooly we don't plan any refactory for now, we _think_ including both extension will works and wants to provide an integration test for it.
If it didn't works, then we'll need to investiguate and see if we can do anything about it ...

Your work on #9211 is more important (nobody complain yet about these two extensions not working together but some complain about our Kotlin support), so if we discover that both extensions are incompatible I would be very careful if we need to make any modifications ...

**Comment by SaumyaSingh1** [comment]
@loicmathieu after contributing to doc area I want to try this issue of testing.

I am not that much into Hibernate , MongoDB, Panache and I just started learning JUNIT5 from[ here](https://youtube.com/playlist?list=PLqq-6Pq4lTTa4ad5JISViSb2FVG8Vwa4o).

Should I go ahead with this issue ?🤔

**Comment by loicmathieu** [comment]
@SaumyaSingh1 this seems to be a bit difficult if you didn't know the techs used here. If you wanted to find some issues to start with but didn't find them from the [good first issue](https://github.com/quarkusio/quarkus/labels/good%20first%20issue)label the best is to go to Zulip on the dev channe and ask for some idea.

**Comment by SaumyaSingh1** [comment]
ok

**Comment by cchacin** [comment]
@loicmathieu I'd like to help with this task

Question: where the integration tests should live in?

- An example application
- In the `panache` module
- In the `mongo` module

**Comment by cchacin** [comment]
I just noticed that there is an `integration-test` maven module, if that is the right place to do it, I'm ready to start drafting the PR for this task, can you please assign the task to me?

**Comment by loicmathieu** [comment]
@cchacin yes, it should be a new module inside our existing integration-test module, with both extension and some minimal code to check if we can use both or not.

I'll put you as assignee, thanks for working on this.

**Comment by loicmathieu** [comment]
If it didn't work, please don't try to fix any of the existing extension and just report the failure it, we will look if we want to support both extension together or not.

**Comment by cchacin** [comment]
Initial PR: https://github.com/quarkusio/quarkus/pull/16066

**Comment by loicmathieu** [comment]
Closing it as there is already a lot of different IT and we should focus on enhancing the existing and not creating new one.
