### ISSUE TITLE
Add to `quarkus:dev` the ability to run the "unit tests"

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#973]
Today we allow to hit refresh and see the result of the code.

I'd like us to also deploy tests and be able to run them by refreshing a specific web pages when run under `quarkus:dev`. `http://localhost:8080/tests/` would show the list of tests, the one failing and display to the logs / errors.

My main use cases are two fold:

* once I'm happy with my inner loop, I verify that tests pass before moving on
* I want to be able to run tests from within a container which has my app deployed.

The usage is for HotSpot `quarkus:dev`. Not for native.

**Comment by geoand** [comment]
Something similar came up on the mailing list recently:

https://groups.google.com/g/quarkus-dev/c/qB3iW0ciLqI/m/UJAB7KbRAgAJ
