### ISSUE TITLE
QuarkusTest does not work in Gradle projects when invoked from IDE

### ISSUE THREAD

**Issue by jskovjyskebankdk** [quarkusio/quarkus#9738]
**Describe the bug**
Running a @QuarkusTest annotated unit test in eclipse (Run As->Junit Test) fails for Gradle projects.

**Expected behavior**
I would expect the unit test to execute properly, the way it does for Maven projects.

**Actual behavior**
The console outputs:
````
Jun 03, 2020 8:17:23 AM io.quarkus.bootstrap.BootstrapAppModelFactory resolveAppModel
WARN: Unable to locate the maven project on the filesystem
````

**To Reproduce**
1. Create a template project with build type Gradle
2. Import into Eclipse
3. Open ExampleResourceTest and try to execute it

**Configuration**
Gradle project template as provided by the Quarkus Maven plugin.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux localhost.localdomain 5.6.15-300.fc32.x86_64 #1 SMP Fri May 29 14:23:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14
 - GraalVM version (if different from Java): na
 - Quarkus version or git rev: 1.5.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.5
 - Eclipse: 2020.03

**Comment by ozkanpakdil** [comment]
I created a gradle project and trying to run test from visual studio code and got 
`Jun 28, 2020 2:00:42 PM io.quarkus.bootstrap.BootstrapAppModelFactory resolveAppModel
WARN: Unable to locate the maven project on the filesystem`

**Comment by glefloch** [comment]
Yes we are working on the Gradle plug-in to make this working.

**Comment by aloubyansky** [comment]
Should be fixed with https://github.com/quarkusio/quarkus/pull/10459
