### ISSUE TITLE
Java 8 DateTime can NOT be unserialized in Vertx Mutiny WebClient 

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#9741]
The client sample code is [here](https://github.com/hantsy/quarkus-sample/tree/master/restclient-vertx-munity).

I have added the following dependencies.

```xml
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-vertx</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-mutiny</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-web-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
```
I used the [post-service](https://github.com/hantsy/quarkus-sample/tree/master/post-service) as api producer.

When run **post-service**(:8081/api), **restclient-vertx-munity**(:8080/posts), and background **mongodb**(via `docker-compose up postgres`) respectively.

And access `http://localhost:8081/api`, and got the following exceptions in the console of **restclient-vertx-munity**.

```bash
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.time.LocalDateTime` (no Creators, like default construct, exist): no String-argument constructor/factory method to deserialize from String value ('2020-06-03T18:04:45.125679')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.example.Post["createdAt"])
```

**Comment by hantsy** [comment]
In other client samples, I used `jsonb` to handle json, all worked. 

But the vertx extension depends on jackson extensions, I switched to `jackson` in this sample.

**Comment by hantsy** [comment]
Tried to customize ObjectMapper. 

```java
@ApplicationScoped
public class CustomObjectMapper implements ObjectMapperCustomizer {

    @Override
    public void customize(ObjectMapper objectMapper) {
        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        objectMapper.disable(SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS);
        objectMapper.disable(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS);

        JavaTimeModule module = new JavaTimeModule();
        LocalDateTimeDeserializer localDateTimeDeserializer =  new LocalDateTimeDeserializer(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        module.addDeserializer(LocalDateTime.class, localDateTimeDeserializer);
        objectMapper.registerModule(module);
    }
}
```

But not resolved my problem yet.

**Comment by gsmet** [comment]
The JSR 310 support is supposed to be automatically included in Quarkus for
a while. Definitely in 1.4.2.Final.

Is it in native or in JVM mode?

**Comment by hantsy** [comment]
@gsmet JVM mode.

**Comment by gsmet** [comment]
Not sure it's related but your post service is using jsonb. I'm not sure it
will serialize things in a way Jackson can understand it.

**Comment by hantsy** [comment]
@gsmet  By default, the producer side convert to string using the standard ISO format I think.

**Comment by hantsy** [comment]
It seems the Vertx internal `JsonCodec` does not apply my custom `ObjectMapper`.

**Comment by hantsy** [comment]
The `Json` class is from vertx which is included as dependency of the Quarskus vertx extension, so I think vertx extension could have some way to hooks ObjectMapper to it's internal `Json`.

**Comment by geoand** [comment]
> The `Json` class is from vertx which is included as dependency of the Quarskus vertx extension, so I think vertx extension could have some way to hooks ObjectMapper to it's internal `Json`.

This point has indeed come up elsewhere.

I am wondering if we should indeed be making this hard-coded assignment (which could potentially be dangerous) or if should just document it for users. @gsmet what's your take?

**Comment by hantsy** [comment]
@geoand As mentioned by Thomas https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20Vertx.20WebClient/near/204920121, I think it is possible to declare a  Quarkus specific `BodyCodec` in the vertx extension, and read our custom Jackson `ObjectMapperCustomizer` automatically.

**Comment by geoand** [comment]
Yeah, we just need to agree if we want that or not

**Comment by gsmet** [comment]
I'm not sure I see an easy way out here...

The `ObjectMapper` used by Vert.x has some specific customization. The fields in `Json` are public static so we could override them as long as we do it early enough. We could have to talk to @vietj about that though.

And then, we have two options: either entirely replace the mapper and apply the specific Vert.x extensions as customizers or do the opposite and apply the customizers on top of the Vert.x ones.

All in all, I think a discussion with @vietj is necessary.

In the meantime, I think you could just push your own mapper to `Json` in a startup event. Not pretty but that should work.

**Comment by cescoffier** [comment]
We should document that somewhere.

**Comment by cescoffier** [comment]
Actually, to work properly, we need to implement the Vert.x JsonCodec.
While possible (I just did it), I'm blocked by https://github.com/eclipse-vertx/vert.x/issues/3766.

**Comment by hantsy** [comment]
It seems Vertx 4.0 changed the related APIs.

**Comment by cescoffier** [comment]
yes, but for the time being, we need a Vert.x 3.x fix. Vert.x 4 integration is still a couple of months away.

**Comment by smil2k** [comment]
Workaround for the time being:

@Startup 
public class SetupJsonCodec {
    
    public SetupJsonCodec(Instance<ObjectMapperCustomizer> customizers) {
        for (ObjectMapperCustomizer customizer : customizers) {
            customizer.customize(DatabindCodec.mapper());
            customizer.customize(DatabindCodec.prettyMapper());
        }
    }
}

**Comment by cescoffier** [comment]
This has been fixed in _main_. @geoand we worked on that, right?

**Comment by geoand** [comment]
Yes, that's right!
