### ISSUE TITLE
CDI static initialization prevents MP-config from functioning

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#975]
CDI applications using MP-Config will fail to function after the next round of configuration changes, where the run time configuration is not available until the main method executes.  As the code stands, user applications will only be able to read values from the build configuration, not from the run time configuration.

Blocks #784; see that issue for more information.

**Comment by mkouba** [comment]
So the bean container is currently initialized during `STATIC_INIT` and it's legal and often practical to create bean instances in this phase too.

I don't think we should disallow using CDI beans during `STATIC_INIT` or move the whole container initialization to the `RUNTIME_INIT` phase. Instead, we should document that runtime config properties are not available there. I do plan to start a new doc about Quarkus extensions and CDI integration - that would be probably the best place for this kind of info.

Also once we merge https://github.com/quarkusio/quarkus/pull/1568 the validation of `@ConfigProperty` injection points will happen during `RUNTIME_INIT`.

@stuartwdouglas @gsmet @Sanne comments/ideas?

**Comment by Sanne** [comment]
sounds sensible, but I'm wondering about the usability implications.

> we should document that runtime config properties are not available there

 - Did we get to a point in which it's very clear to users which ones are runtime config properties?
 - Can we strictly validate mistakes made in this area and provide a good error message?

**Comment by gsmet** [comment]
@dmlloyd I suppose it works now, no?

**Comment by dmlloyd** [comment]
Yep I think this is solved.
