### ISSUE TITLE
The property definition in .env file is case sensitive.

### ISSUE THREAD

**Issue by jayakrishnankarolilnlsn** [quarkusio/quarkus#9760]
**Describe the bug**
The property definition in .env file is case sensitive. It should be CAPS as of `1.4.2.Final`
```
MESSAGE=hello  # -> succeeds
name=quarkus   # -> fails
```

**Expected behavior**
Developers should be able to use both lowercase and upper case letters in .env file

**Actual behavior**
lower case letter variables defined in `.env` file is not recognized in the `application.properties` resulting in startup failure
```
[io.qua.application] (Quarkus Main Thread) Failed to start application: java.util.NoSuchElementException: Property name not found
        at io.smallrye.config.SmallRyeConfig.propertyNotFound(SmallRyeConfig.java:209)
        ....
        ....
```

**To Reproduce**
```
git clone https://github.com/quarkusio/quarkus-quickstarts.git
git checkout 1.4.2.Final
cd quarkus-quickstarts/config-quickstart
```
**Configuration**
`application.properties`:
```properties
greeting.message = ${MESSAGE}
greeting.name = ${name}
```

`.env`:
```properties
MESSAGE=hello
name=quarkus
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Microsoft Windows [Version 10.0.18363.720]`
 - Output of `java -version`: `java 11.0.6 2020-01-14 LTS`
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: `1.4.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**
Issue created from a comment in #8297

**Comment by geoand** [comment]
`.env` is meant to set environment variables, so they should always be upper case.

**Comment by jayakrishnankarolilnlsn** [comment]
Thanks. Yeah, did some research. Environment variables should be in upper case by convention.

https://google.github.io/styleguide/shellguide.html#constants-and-environment-variable-names
https://stackoverflow.com/questions/673055/correct-bash-and-shell-script-variable-capitalization
