### ISSUE TITLE
FormAuthenticationMechanism is not registered

### ISSUE THREAD

**Issue by sanyarnd** [quarkusio/quarkus#9763]
**Describe the bug**
`FormAuthenticationMechanism` is not registered if project has a single
```xml
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-security</artifactId>
</dependency>
```
dependency.

**Expected behavior**
With
```properties
quarkus.http.auth.basic=false
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.redirect-after-login=false

quarkus.http.auth.form.login-page=/
quarkus.http.auth.form.error-page=/
quarkus.http.auth.form.landing-page=/
```
and custom `IdentityProvider` I'd expect that `FormAuthenticationMechanism` will be registered and available.

**Actual behavior**
There is no `FormAuthenticationMechanism` in available mechanisms. `HttpAuthenticator#attemptAuthentication` has only one mechanism: `NoAuthenticationMechanism`.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10
 - Output of `java -version`: 14.0.1
 - Quarkus version or git rev: 1.5.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Additional context**
If `quarkus.http.auth.basic` is set to `true`, `HttpAuthenticator#attemptAuthentication` contains `BasicAuthenticationMechanism`. Seems like `FormAuthenticationMechanism` bean registration is missing from somewhere.

**Comment by sberyozkin** [comment]
@sanyarnd What happens when no `custom IdentityProvider` is provided ?

**Comment by sanyarnd** [comment]
I see no changes after removing custom `IdentityProvider`. 
`HttpAuthernicator`'s `mechanisms` contains `NoAuthenticationMechanism`.
.properties:
```
quarkus.http.auth.basic=false
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.cookie-name=sessionId
quarkus.http.auth.form.redirect-after-login=false
```

Enabling basic auth holds the same result: `NoAuthenticationMechanism` (because there are no identity providers beans, I suppsose)

**Comment by geoand** [comment]
Is still an issue?

**Comment by geoand** [comment]
Closing for lack of feebackj
