### ISSUE TITLE
Add "prefix" to @ConfigRoot

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#9791]
**Description**
We are using Quarkus at a large scale to develop many microservices. In this setup we also have quite a few homegrown libraries and tools, which we now look to integrate into the Quarkus development as Quarkus extensions. For this purpose we want to use `@ConfigRoot` et al. to define the configuration properties and also generate corresponding documentation, as is being done for Quarkus itself. Since most of the extensions we are developing are not applicable outside our corporation, these won't be opensourced under the Quarkus project and so it doesn't really make any sense for the configuration properties to have the `quarkus` prefix.

I would therefor like to propose that the `@ConfigRoot` annotation type is extended with a `prefix` attribute (possibly defaulting to `"quarkus"`, so that we can specify our own prefix.

**Implementation ideas**
As described, I think a new `prefix` attribute on `@ConfigRoot` would make sense.

**Comment by dmlloyd** [comment]
Sure. It does raise a few questions about validation though: normally if we encounter an unknown property we can log it because we control the whole namespace.  So we need to define a useful set of rules for this case.

**Comment by knutwannheden** [comment]
I thought the properties get validated against the accessible `@ConfigRoot` items, in which case this should work with a custom prefix as well, no?

**Comment by dmlloyd** [comment]
No, we validate all of the `quarkus.` space.  If a property with that prefix is found that isn't mapped, we print a warning about it (this helps avoid typos).  The question is, do we expand this behavior to cover other prefixes as well (potentially triggering many warnings if the user uses the namespace for something else in addition to extension config), or do we leave those out (potentially losing out on validation)?

**Comment by knutwannheden** [comment]
I understand. Thanks for the explanation. A config property to disable the validation? 🤣

**Comment by knutwannheden** [comment]
It may also make sense to make the values represented by the constants `io.quarkus.annotation.processor.Constants#PKG_PATTERN` and `io.quarkus.annotation.processor.generate_doc.ConfigDocItemScanner#IO_QUARKUS_TEST_EXTENSION_PACKAGE` configurable in the context of `io.quarkus.annotation.processor.generate_doc` where they are used.

**Comment by knutwannheden** [comment]
I would like to start looking into this issue. Of course it would be best if it could be integrated into Quarkus, but that will require some decisions on the raised questions. Should this be discussed here in the issue comments?

Alternatively I will look into employing some kind of workaround, so that we don't need the config properties of our custom extensions to all be defined in the `quarkus` namespace.

**Comment by knutwannheden** [comment]
I believe some of the existing extensions in Quarkus would also benefit from a `namespace` for `@ConfigRoot`. One example being `smallrye-jwt` for which the config properties are documented [in the guide](https://quarkus.io/guides/security-jwt#additional-smallrye-jwt-configuration) as well as in the [SmallRye documentation](https://smallrye.io/docs/smallrye-jwt/configuration.html#_smallrye_jwt_properties).

Currently there is at least one property which is documented in SmallRye but not in the Quarkus guide: `smallrye.jwt.verify.key.location`. This could of course be because Quarkus currently uses a different version. I didn't check that.

Also note that the [all configuration options](https://quarkus.io/guides/all-config) doesn't contain the config properties for `smallrye-jwt`. That could also be problematic for users who want to use this guide quickly find out about all JWT-related config options offered by Quarkus.

**Comment by jlannoy** [comment]
I would like to see the same feature too. When writing an extension that can not be available directly from the Quarkus repository, it could be less strange imho to propose an alternative prefix in this specific case.
