### ISSUE TITLE
Add job to test `-H:+RemoveSaturatedTypeFlows` and `-H:+PrintAnalysisStatistics`

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9794]
**Description**

In GraalVM 20.1, they offer faster compilation with lower memory usage with these enabled flags.
It decreases the perf optimization but if they are witin acceptable limits, the gain might be good and we could enable.

**Comment by emmanuelbernard** [comment]
Report issues to oracle/graal#2384

**Comment by zakkak** [comment]
`-H:+RemoveSaturatedTypeFlows` is the default since 20.2
