### ISSUE TITLE
Add Gradle native TS

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#9797]
At this point our Gradle TS is missing native tests. We should add native build tests that would be enabled by `-Dnative` or `-Pnative` as the rest of the Quarkus native TS.

**Comment by aloubyansky** [comment]
I'm not sure why I can't assign this one to you @glefloch

**Comment by glefloch** [comment]
yes that's weird but I'm on it ;)

**Comment by glefloch** [comment]
Thanks @gastaldi for the assignement. 
Looking at github action, it looks like native tests are only run for module under `integration-tests`:
https://github.com/quarkusio/quarkus/blob/e99fded5c13c09526b45d6a268bb196ac7ac2b31/.github/workflows/ci-actions.yml#L549

So I was thinking of creating a `gradle` module under `integration-tests`. WDYT of moving gradle `functionalTest` their ?
Or is there an easier way to add native test into the gradle module?

**Comment by gastaldi** [comment]
> So I was thinking of creating a `gradle` module under `integration-tests`. WDYT of moving gradle `functionalTest` their ?

+1, I think that makes sense.
