### ISSUE TITLE
BeanDefiningAnnotationBuildItem - support for meta-annotations

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#980]
So that all annotations annotated with the specified meta-annotation are considered bean defining annotations. This is how CDI stereotypes work.

**Comment by stuartwdouglas** [comment]
Do we actually need this? It is very easy to do just looking at usages in the index, so IMHO this is not really worth perusing.

**Comment by mkouba** [comment]
> Do we actually need this?

Probably not. Let's reopen if needed.

**Comment by matejthetree** [comment]
this would be nice

```
  @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE)
    @ApplicationScoped
    @Startup
    public @interface MetaStartupBean {
    }
```

**Comment by mkouba** [comment]
> this would be nice
> 
> ```
>   @Retention(RetentionPolicy.RUNTIME)
>     @Target(ElementType.TYPE)
>     @ApplicationScoped
>     @Startup
>     public @interface MetaStartupBean {
>     }
> ```

You should not need this annotation at all because classes with no built-in scope annotated with `@Startup` automatically receive `@ApplicationScoped`.

**Comment by fxrobin** [comment]
@mkouba, I guess this was only an example.

In my case I would like this :

```java
@QuarkusTest
class MyTestClass {
     @InjectMock
     @MockitoConfig(convertScopes = true)
     EventBus bus;
}
```

to become

```java
@QuarkusTest
class MyTestClass {
     @EventBusMock
     EventBus bus;
}
```

`@EventBusMock` would have been defined as a stereotype of `@InjectMock` and `@MockitoConfig`
But these annotation cannot be placed on a type, so they are not candidates to become part of a composite.

Any idea?

**Comment by mkouba** [comment]
That's a completely different problem though - a bean defining annotation is used to turn a class into a bean. In your particular case, an injection point of a test class is annotated with `@EventBusMock`; `@InjectMock` is processed by `quarkus-junit5-mockito`/`quarkus-junit5-component` and `@MockitoConfig` is only processed by `quarkus-junit5-mockito`. Unfortunately, CDI/quarkus has no API to define a "stereotype"-like annotation for an injection point and `quarkus-junit5-mockito` reads the annotations directly from the test instance using the reflection API 🤷.

**Comment by fxrobin** [comment]
Ok, thanks for your answer. I thought this thread was dealing with annotation stereotypes. Sorry If I have misunderstood it.
