### ISSUE TITLE
Command mode doesn't exit after exception

### ISSUE THREAD

**Issue by targeter21** [quarkusio/quarkus#9808]
**Describe the bug**
Hi, I logged #9163 which was marked as Fixed, but it looks like in 1.5.0.Final the problem is not fixed and worse off than before.

**Expected behavior**
Command Mode should exit completely after a failure (unhandled exception) occurs. There shouldn't be a message to restart as that is not proper CLI behavior and it shouldn't sit waiting for a response.

**Actual behavior**
Command Mode still hangs and lets you press Enter or Ctrl+C to restart, which isn't right as a CLI app should fully exit in a failure scenario. Also Ctrl + C does not restart and appears to do nothing on MacOS.

**To Reproduce**

1. Create an empty quarkus command mode project with the following code:
JavaMain:
```
@QuarkusMain
public class JavaMain
{
  public static void main(String... args) {
    Quarkus.run(Testing.class, args);
  }
}
```

Testing.java:
```
public class Testing implements QuarkusApplication
{
  @Override
  public int run(final String... args) {
    boolean willFail = args[0].equals("foo");

    return 0;
  }
}
```
2. Run either in Intellij or command line. Behavior was observed to be the same in Intellij and dockerized native image.

**Configuration**
No additional configuration is needed.

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
- Output of `uname -a` or `ver`: 
**Darwin MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64**
 - Output of `java -version`: 
**openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)**
 - GraalVM version (if different from Java): 
**n/a**
 - Quarkus version or git rev: 
**1.4.1.Final**
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
**Tested with mvnw and mvn, both 3.6.3**

**Additional context**
(Add any other context about the problem here.)

**Comment by maxandersen** [comment]
Not a bug / but more an IDE bug..

To actually run your app to this:

```
$ mvn clean package
$ java -jar target app-1.0-SNAPSHOT-runner.jar
```

with your example that exits immediatly.

when you run from IDE we assume you want to be in devmode. thus it is expected to not exit here. 
you can see that it behaves same ways as when running `mvn quarkus:dev` on command line.
 
I can see though that idea does not seem to handle Ctrl+c in its virtual console though. That is a general issue with idea though and I recommend you just click the red stop button (or use cmd+F2) to work around that issue.

**Comment by targeter21** [comment]
Ahh I did not realize devmode had different behavior. Thanks for clearing that up; I verified running the jar itself demonstrates the expected behavior thanks!
