### ISSUE TITLE
Quarkus 1.5.0 Flyway not running Java Migrations

### ISSUE THREAD

**Issue by brentcrammond** [quarkusio/quarkus#9819]
**Describe the bug**
Quarkus 1.5.0 Flyway not running Java Migrations

**Expected behavior**
All migrations (sql and Java) are run.

**Actual behavior**
Only the sql migrations are running.

**To Reproduce**
1. Create MySQL8 database with schema testflyway
2. Update database config in application.properties
3. Run using maven compile quarkus:dev

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.flyway.migrate-at-start = true
quarkus.flyway.baseline-on-migrate = true

quarkus.log.console.enable = true
%dev.quarkus.log.console.enable = true
quarkus.log.console.format = %d{yyyy-MM-dd HH\:mm\:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.console.color = true
quarkus.log.console.level = DEBUG

quarkus.log.file.enable = true
quarkus.log.file.format = %d{yyyy-MM-dd HH\:mm\:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.file.path = logs/app.log
quarkus.log.file.rotation.max-file-size = 10M
quarkus.log.file.rotation.max-backup-index = 5
quarkus.log.file.rotation.rotate-on-boot = true

quarkus.datasource.db-kind = mysql
quarkus.datasource.username = root
quarkus.datasource.password = xxxxx
quarkus.datasource.jdbc.url = jdbc:mysql://127.0.0.1:3306/testflyway
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

<img width="1515" alt="Screen Shot 2020-06-05 at 10 59 45 PM" src="https://user-images.githubusercontent.com/6261538/83869186-4d22cc00-a780-11ea-9a93-53fc7567ae10.png">

<img width="1439" alt="Screen Shot 2020-06-05 at 10 59 56 PM" src="https://user-images.githubusercontent.com/6261538/83869196-514ee980-a780-11ea-9a35-d33250a66cc9.png">

<img width="403" alt="Screen Shot 2020-06-05 at 11 01 22 PM" src="https://user-images.githubusercontent.com/6261538/83869331-88bd9600-a780-11ea-94a8-ecff88621917.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Brents-MBP 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`:  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.5.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
(Add any other context about the problem here.)
- It works in Quarkus 1.4.2
- The sql and classes are in the target directory
- The example runs first two SQL migrations but not the Java one that should follow.

** Simple Test Project **
[testflyway.zip](https://github.com/quarkusio/quarkus/files/4735623/testflyway.zip)

**Comment by geoand** [comment]
What exactly are Java migrations?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/9824 fixes the issue
