### ISSUE TITLE
MP Metrics - expose more metrics in base scope

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#983]
Quarkus:
```
curl http://localhost:8080/metrics 2>/dev/null | grep -v HELP | grep -v TYPE | grep base
base:gc_ps_mark_sweep_count 2.0
base:gc_ps_scavenge_count 6.0
base:gc_ps_mark_sweep_time_seconds 0.061
base:gc_ps_scavenge_time_seconds 0.041
```

WildFly:
```
curl http://localhost:9990/metrics 2>/dev/null | grep -v HELP | grep -v TYPE | grep base
base:classloader_total_loaded_class_count 18418.0
base:cpu_system_load_average 2.97998046875
base:thread_count 127.0
base:classloader_current_loaded_class_count 18346.0
base:jvm_uptime_seconds 14.203
base:memory_committed_non_heap_bytes 1.47587072E8
base:gc_ps_mark_sweep_count 1.0
base:memory_committed_heap_bytes 2.34881024E8
base:thread_max_count 127.0
base:gc_ps_scavenge_count 25.0
base:cpu_available_processors 8.0
base:thread_daemon_count 17.0
base:classloader_total_unloaded_class_count 73.0
base:memory_used_non_heap_bytes 1.340024E8
base:memory_max_heap_bytes 4.77626368E8
base:cpu_process_cpu_load 0.0
base:memory_used_heap_bytes 1.8209984E8
base:gc_ps_mark_sweep_time_seconds 0.138
base:memory_max_non_heap_bytes 8.64026624E8
base:gc_ps_scavenge_time_seconds 0.195
```

**Comment by jmartisk** [comment]
I believe the best solution would be for Quarkus to start using a `base.properties` file just like Thorntail does - https://github.com/thorntail/thorntail/blob/2.3.0.Final/fractions/microprofile/microprofile-metrics/src/main/resources/io/smallrye/metrics/base-metrics.properties - it contains definitions of the base metrics, which will be easier to maintain than the current logic which creates the four existing metrics programmatically. SmallRye Metrics contains the logic to parse this and turn it into actual metric registrations. Can try to do that next week.

**Comment by jmartisk** [comment]
Ah, I didn't realize that it's not possible to use JMX in SubstrateVM. In that case we will have to keep the current approach - we can't use `base-metrics.properties` because it references MBeans using their ObjectNames, which we can't do. I will add the missing metrics without accessing the MBean server.
