### ISSUE TITLE
quarkus-resteasy-common depends on groupId com.sun.activation but rest-assured depends on groupId jakarta.activation

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#9834]
I am seeing this in my `mvn dependency:tree`:

```
58-[INFO] |     +- io.quarkus:quarkus-resteasy-common:jar:1.5.0.Final:compile
59-[INFO] |     |  +- ...
63:[INFO] |     |  \- com.sun.activation:jakarta.activation:jar:1.2.1:compile
```

```
181-[INFO] |  \- io.rest-assured:xml-path:jar:4.3.0:test
182-[INFO] |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:test
183:[INFO] |     |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:test
```

This leads to:

```
16:01:54 [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
16:01:54 Duplicate classes found:
16:01:54 
16:01:54   Found in:
16:01:54     jakarta.activation:jakarta.activation-api:jar:1.2.1:test
16:01:54     com.sun.activation:jakarta.activation:jar:1.2.1:compile
16:01:54   Duplicate classes:
16:01:54     javax/activation/MailcapCommandMap$1.class
16:01:54     javax/activation/CommandInfo$Beans$1.class
16:01:54     javax/activation/CommandInfo$Beans.class
16:01:54     javax/activation/MimetypesFileTypeMap$1.class
```

Suggestion on how to fix: Add enforcer rule `<banDuplicateClasses>` and see what breaks.
https://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html

Relates to https://github.com/quarkusio/quarkus/pull/9839 
Relates to https://github.com/rest-assured/rest-assured/issues/1332 (= separate issue) and  https://github.com/rest-assured/rest-assured/pull/1333

**Comment by sebthom** [comment]
Just hit this issue too, it is still present in the latest Quarkus release.

![image](https://user-images.githubusercontent.com/426959/129340010-3c1e4da3-7bbc-4f13-a863-54d1f5f80f02.png)

We have the banDuplicateClasses enforcer rule globally activated.

**Comment by gsmet** [comment]
Yeah, it's not so easy to use `banDuplicateClasses` in our case as there are a ton of issues that are not fixable by us directly. Typically like the REST Assured issue.

That being said, I'll have a look at what @sebthom is showing as I wouldn't expect it to break on our own dependencies.

**Comment by gsmet** [comment]
I pushed a PR that should this one issue: https://github.com/quarkusio/quarkus/pull/19422 .
