### ISSUE TITLE
Quarkus Config Server Client Error.

### ISSUE THREAD

**Issue by TRL-Official** [quarkusio/quarkus#9840]
**Describe the bug**
I want to customize ConfigServer and QurakusConfigServerClient.

But I get an error. Gist error log URL: https://gist.github.com/TRL-Official/f3fe2a60c1040587d0929d14f598ad45

ConfigServer returns configuration correctly.

It seems to me that during the init microservice "config-server-client(user-service)" configuration from config-server is not injected. And because of this, hibernate throws an error.

QuarkusConfigServerClient support "bootstrap.yml" or "bootstrap.properties" file?
For example.
Spring Cloud Context: https://cloud.spring.io/spring-cloud-commons/multi/multi__spring_cloud_context_application_context_services.html#_the_bootstrap_application_context

URL repo of config-server and config-server-client(user-service): https://github.com/quarkus-based-application

**Comment by geoand** [comment]
Which properties are you trying to set from the config server?

Keep in mind that you can only set runtime properties

**Comment by TRL-Official** [comment]
I'm trying to set the configuration of Datasource, Hibernate, Logging,  Health Check, SwaggerUI.

URL config that I trying set via SpringServerConfig -> [config.](https://github.com/quarkus-based-application/configs/blob/master/user-service.properties)

Settings such as Datasource, Hibernate, Logging,  Health Check, SwaggerUI must be set in "build time". This information is correct?

If this configuration should be set in "build time". How I can make this.

Or am I wrong about that?

**Comment by geoand** [comment]
Take a look at : https://quarkus.io/guides/all-config

It says for each option whether it's build time or not. Keep in mind that for each group (for example data source), there could be both build time and runtime properties.
It looks like you are attempting to set both in the config server - that certainly won't work.

So I'll close this for now, but if you see that a rutime property is not taking effect, feel free to reopen
