### ISSUE TITLE
Build multi-arch images

### ISSUE THREAD

**Issue by gmussi** [quarkusio/quarkus#9843]
**Description**
The base image used by quarkus ( ubi8/ubi-minimal ) has multi-arch support. 
Running `mvn package` should have the possibility of building multi-arch images, too.

**Implementation ideas**
As far as I know, there is no way to currently building multi-arch images with the Docker plugin.
There should be a parameter for selecting which archs you want to build against.

**Comment by geoand** [comment]
This is possible via `quarkus.docker.buildx.platform`
