### ISSUE TITLE
Quarkus 1.5 + Liquibase

### ISSUE THREAD

**Issue by jglink** [quarkusio/quarkus#9846]
With Quarkus 1.5 the Liquibase integration has an issue (Liquibase version: 3.9.0).
The combination of quarkus:dev and Liquibase changeLog.xml with an includeAll tag does not find the files under a given folder. It always says: 
  _File does not exist: D:/Projekte/myproject/target/classes/db/1.0.0/0010_init.sql_

In Quarkus 1.4.x this was working fine.

If I run Quarkus tests with the same Liquibase changeLog.xml or if I start the application via the runner JAR, the referenced Liquibase files are found.

`<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd
    http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd">
<includeAll path="db/1.0.0/" errorIfMissingOrEmpty="true"/>
</databaseChangeLog>
`

This is working in all modes: 
`
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd
    http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd">
<include file="db/1.0.0/0010_init.sql"/>
</databaseChangeLog>
`

It seems that the modification to the QuarkusClassLoader has something to do with it.

Liquibase liquibase.util.StreamUtil#singleInputStream tries to load the files referenced by the includeAll tag via _resourceAccessor.getResourcesAsStream(path)_.
This uses the QuarkusClassLoader which returns NULL in quarkus:dev mode, but the expected stream if running QuarkusTests or when application is started with the -runner JAR.

**Comment by geoand** [comment]
Hi,

Do you have a reproducer for this? I can't seem to reproduce the problem in out testsuite.

**Comment by jglink** [comment]
The problem is, that the includeAll tag is working fine during the test phase, but not if you start the application with "mvn quarkus:dev".
So, providing a test case (@QuarkusTest) is of no use.

But I can try to set-up a simple Quarkus project to demonstrate this.

**Comment by geoand** [comment]
> The problem is, that the includeAll tag is working fine during the test phase, but not if you start the application with "mvn quarkus:dev".
> So, providing a test case (@QuarkusTest) is of no use.
> 

Yeah, I get that. What I meant was that doing `quarkus:dev` on our liquibase integration test, things worked fine.

> But I can try to set-up a simple Quarkus project to demonstrate this.

:+1:

**Comment by jglink** [comment]
Can you give me a hint were you´ve executed the `quarkus:dev` command, so that I can have a look at that configuration.
Maybe I´m doing something wrong or have a different configuration.
Thanks

**Comment by geoand** [comment]
This is where I tried it: https://github.com/quarkusio/quarkus/tree/master/integration-tests/liquibase

It could very well be that the integration test isn't doing enough, in which case a reproducer for the issue would be great so we can not only fix the issue, but also improve coverage

**Comment by gsmet** [comment]
Our test uses `<include>`. Apparently, that one is working, it's `<includeAll>` not working. At least, that's what I understood.

**Comment by jglink** [comment]
Yes, exactly.
I just had a look at the sources as well and the liquibase tests are using `include`.

The `include` is working in my environment, just not the `includeAll`.

**Comment by geoand** [comment]
Very good info

**Comment by jglink** [comment]
Just created a PR to show the issue: https://github.com/quarkusio/quarkus/pull/9876

(The PR has no fix in it but just added an `includeAll` to the Liquibase config and a SQL changeset file which is referenced from the includeAll.
I also had to modify the application.properties to get it working locally.)

**Comment by geoand** [comment]
Thanks, I'm going to look at the issue now

**Comment by jglink** [comment]
@geoand Great! That was really fast.
Thank you!

**Comment by geoand** [comment]
You are welcome :)
