### ISSUE TITLE
bean validation does not work in multi module project

### ISSUE THREAD

**Issue by pcarrara** [quarkusio/quarkus#9858]
Describe the bug
When you define a multi module project, keeping a interface definition in one module and its implementation in another, bean validation doesn't work as expected. When submit a request no validation occurs. If you put both (interface an its implementation) within same module, everything works fine: validation occurs according to defined constraints.

Expected behavior
Validation should occurs based on constraint definition

Actual behavior
No validation occurs

To Reproduce

Create a new maven project

Create a module and define Interface and a request entity with a constratint:
@path("/path")
public interface Api {

@post
@produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
MyResponseEntity process(@HeaderParam("id") final String id, @Valid final Request request);
}

Constraints definition:
@builder
@DaTa
@AllArgsConstructor
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class Request implements Serializable {

private static final long serialVersionUID = 1L;

@notblank(message = "Document can't be blank")
@JsonProperty("document")
private String document;
}

Modules dependencies:

io.quarkus
quarkus-resteasy-jackson

io.quarkus
quarkus-hibernate-validator
Create a project with implementation:
@path("/path")
public class Resource implements Api {
@override
public MyResponseEntity process(@HeaderParam("id") final String id, final Request request) {
return null;
}
}
Modules dependencies:
io.quarkus quarkus-rest-client io.quarkus quarkus-config-yaml io.quarkus quarkus-hibernate-orm-panache io.quarkus quarkus-jdbc-postgresql io.quarkus quarkus-flyway
Environment (please complete the following information):

Output of java -version:
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

Quarkus version or git rev:
1.5.0.Final

Build tool (ie. output of mvnw --version or gradlew --version):
Maven home: /usr/local/apache-maven-3.6.3
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: pt_BR, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-53-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Hi,

Have you made Quarkus aware of these other modules? 
See https://stackoverflow.com/a/55513723/2504224 for a great overview of how to do it.

**Comment by pcarrara** [comment]
> Hi,
> 
> Have you made Quarkus aware of these other modules?
> See https://stackoverflow.com/a/55513723/2504224 for a great overview of how to do it.

Sorry, i didn't understand. I think the explanation about the problem it's clear about the modules. In fact, i've described the modules dependenciies and the classes within each on of them

**Comment by geoand** [comment]
In order for Quarkus to be able to read annotations from other modules, you need to make Quarkus aware of those modules like the link I pasted above explains

**Comment by pcarrara** [comment]
Hi @geoand!! I'm sorry by my missunnderstanding
I added the reference of the module where the interfaces are within the pom of the implementation module:

Module A: has interface
Module B: has implementation.

Module B also has the reference (as maven depedency) to module A. But the validation described in the interface is ignored. It only works if put both (interface and implementation) in the same module

**Comment by geoand** [comment]
Can you try adding an empty

```
src/main/resources/META-INF/beans.xml
```

file to module A?

**Comment by pcarrara** [comment]
Thanks @geoand !! It worked!!
But, just to known. This is a expected behavior?

**Comment by geoand** [comment]
It is, see https://quarkus.io/guides/maven-tooling#multi-module-maven
