### ISSUE TITLE
Apache Ignite extension 

### ISSUE THREAD

**Issue by junaid155** [quarkusio/quarkus#9867]
**Describe the extension**
Apache ignite extension to provide a way to automatically create a reusable Instance of Ignite object and way to interact with basic crud operations for any repository just like Spring data Apache ignite repository. 

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
`

quarkus.ignite.hostname:localhost:9000

**Comment by geoand** [comment]
Closing as a duplicate of #6986
