### ISSUE TITLE
Respect submodule application.properties config when packaging the application

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#9869]
**Description**

When using a shared library module between several application modules, you probably will have some library-specific properties set, like default timeouts, urls etc.

Currently you have to redefine them in the application.properties file of the application module, as the properties of the library are not carried into the application and therefore those config entries are missing.

It leads to this issue:

[**"DeploymentException: No config value of type [java.lang.String] exists for" #8999**](https://github.com/quarkusio/quarkus/issues/8999)

Redefining all library module properties in each application would create a huge mess and discrepancys over time if not handled carefully

**Implementation ideas**

I think it would be helpful to have some kind of merging, where library properties are threated as default values unless they are overwritten by a property defined in the application´s .properties file.

**Comment by rquinio** [comment]
In a shared library you need to put the config inside the jar `META-INF/microprofile-config.properties`

It's an information that seems missing in the guide https://quarkus.io/guides/config (though it's a microprofile-config standard thing and not Quarkus specific).
