### ISSUE TITLE
Enhance quarkus vault integration - allow users to specify k8s auth method mount path

### ISSUE THREAD

**Issue by precompiler** [quarkusio/quarkus#9871]
**Description**
Kubernetes auth method mount path can be customized by users, e.g. using below command
```bash
vault auth enable -path mycluster kubernetes
```
In this case if we want to do vault k8s login, we need to login against "auth/mycluster/login".

But currently, the [OkHttpVaultClient ](https://github.com/quarkusio/quarkus/blob/master/extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/client/OkHttpVaultClient.java#L93)hard coded the mount path to "auth/kubernetes/login", which won't work if users specify different mount paths.

New application configuration property should be introduced to allow users to specify customized k8s auth mount path.

**Comment by ejba** [comment]
It seems a straightforward task, I would like to contribute on this one if you don't mind.

**Comment by precompiler** [comment]
> It seems a straightforward task, I would like to contribute on this one if you don't mind.

@ejba please go ahead, thanks.

**Comment by geoand** [comment]
cc @vsevel
