### ISSUE TITLE
Missing skip- or exclusive-feature for Scheduler system

### ISSUE THREAD

**Issue by McIntozh** [quarkusio/quarkus#9883]
**Description**
I encountered the problem, that when the triggered method is currently processing and the same timer hits again, the method is also processed again.
Migrating from the EJB `@Schedule` annotation, this is a different behaviour. In EJB the method is processed exclusively, and during that, additional triggers are ignored.

I tried setting the method to synchronized but then - like I expected - the triggers are stacking up, firing again as soon as the method finishes.

Only current workaround is
```
  private boolean running = false;
  @Scheduled(cron = "* * * * * *")
  public void doSomethingThatSometimesTakesLonger() {
    if (running) {
      return;
    }
    running = true;
    try {
      ...Method code...
    } finally {
      running = false;
    }
  }
```
I would like to have the possibility to skip triggers on methods that are still being processed

**Implementation ideas**
Either:
- Add a configuration property
- Add a property to the `@Scheduler` annotation

**Comment by mkouba** [comment]
I think that we should definitely address this. Your workaround is OK except that the `running` field should be `volatile` or even an `AtomicBoolean`:

```java
private final AtomicBoolean running = new AtomicBoolean();

@Scheduled(cron = "* * * * * *")
public void doSomethingThatSometimesTakesLonger() {
    if (running.compareAndSet(false, true)) {
       try {
         ...Method code...
       } finally {
        running.set(false);
       }
    }
  }
```

**Comment by mkouba** [comment]
I've created a draft PR here: https://github.com/quarkusio/quarkus/pull/10338

**Comment by McIntozh** [comment]
I haven't had time to test this, but on first sight it looks like what I wanted :)
