### ISSUE TITLE
Add metadata to mark an extension as deprecated on code.quarkus.io

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#9885]
We'd like to deprecate camel-quarkus-hystrix extension, because the underlying Camel component got deprecated by Camel https://camel.apache.org/components/latest/eips/hystrix-eip.html Once Camel removes the component, we (Camel Quarkus) will be forced to remove it as well. The users are advised to use [MP Fault Tolerance](https://camel.apache.org/camel-quarkus/latest/extensions/microprofile-fault-tolerance.html) instead.

**Implementation ideas**

AFAIK, the `status` field currently supports `stable`, `preview` and `experimental`. I am not 100% sure `deprecated` should be added there. I'd say it is perfectly reasonable for an extension to be stable and deprecated at the same time.

Except for the logical deprecation status, it would be nice to be able to express also

* Since which version the extension is deprecated, e.g. `deprecatedSince: "Camel Quarkus 1.2.3"
* A free text field for the reason for the deprecation and/or any possible replacements

**Comment by ppalaga** [comment]
> When you mention Camel Quarkus 1.2.3, I think it means a thing for a Camel user using Quarkus underneath, I wonder what it means of a Quarkus platform user using this camel extension.

I admit the Quarkus platform version number would be more useful there (and also in general, because we do not use quarkus-extension.yaml anywhere else), but the problem is that quarkus-extension.yaml is maintained on the Camel Quarkus level where we cannot tell upfront which Platform version will the given Camel Quarkus release be part of.

**Comment by emmanuelbernard** [comment]
you sort of do know that if you want to deprecate extension Foo ad day D, then the closest release of Quarkus platform after day D will be the one. But to your point, it feels like deprecation is a platform stuff more than an extension stuff.

**Comment by ppalaga** [comment]
> you sort of do know that if you want to deprecate extension Foo ad day D, then the closest release of Quarkus platform after day D will be the one.

Not exactly. We have to release Camel Quarkus between D and Quarkus platform release. It already happened in the past, that we have not caught the train. Releasing at ASF has some procedural overhead. But it perhaps does not matter so much if we are sometimes not 100% accurate with the deprecation version estimate.

> But to your point, it feels like deprecation is a platform stuff more than an extension stuff.

Not sure I follow. Could you please explain that? We definitely need to maintain the deprecation metadata on our side too (probably as runtime POM's properties) because we want to expose them on the extension pages, like e.g. on the Hystrix extension page https://camel.apache.org/camel-quarkus/latest/extensions/hystrix.html

**Comment by ia3andy** [comment]
@ppalaga you can use both, but the second is nicer IMO.

**Comment by ppalaga** [comment]
@ia3andy we publish the deprecation status [as described above](https://github.com/apache/camel-quarkus/blob/master/extensions/hystrix/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L30-L32) but it is not shown on https://code.quarkus.io/?extension-search=hystrix Did it ever work?

**Comment by gsmet** [comment]
I see `RESTEasy Classic Mutiny` on code.quarkus.io having a `deprecated` label so I think we can close this one.
