### ISSUE TITLE
Metrics aren't registered for default methods inherited from interfaces when a class is annotated

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#9887]
... but metric interceptors ARE applied to the default method, so calling that method will result in an error

**Comment by rmanibus** [comment]
I think it's not only for default method,

I have 
```java
public interface SomeResource {
  @GET 
  @Timed 
  String method();
}

public class TheImpl implements SomeResource {
  @Override
  String method() {
  }
}
```
and it is throwing UnsupportedOperationException

**Comment by jmartisk** [comment]
@rmanibus, your scenario is different - here we're talking about the scenario where the implementation class (no method) is annotated with a metric annotation.
In your case, you have an interface method annotated, and that's not a supported scenario (for now) - there is an open discussion how to handle it at https://github.com/eclipse/microprofile-metrics/issues/451 but it's not yet clear how exactly it should work
