### ISSUE TITLE
Generate application.yaml when quarkus-config-yaml extension is enabled during generation

### ISSUE THREAD

**Issue by BiggA94** [quarkusio/quarkus#9894]
**Description**
If I generate a new Quarkus application and I am using the quarkus-config-yaml extension, a application.properties file is generated.
I would assume that users that are using the quarkus-config-yaml extension rather want to use application.yaml file.
(Could be extended if [CodeStarts](https://github.com/quarkusio/quarkus/issues/8134) are implemented)

**Implementation ideas**
Since the generated application.properties file is empty anways, it would be enough, to only change to filename on generation from application.properties to application.yaml at code generation.

**Comment by geoand** [comment]
This has already been fixed - I just tested an application generated from code.quarkus.io
