### ISSUE TITLE
Allow logging via OpenTelemetry

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#9916]
**Description**
Allow the `smallrye-opentracing` to optionally register a logging handler which would add all logging events above a given threshold level to the currently active tracing span (if any).

The user would use dedicated config properties to enable this feature (disabled by default) and configure the threshold level to use to filter the events to log via OpenTracing.

**Comment by kenfinnigan** [comment]
I don't believe we'd implement this with OpenTracing, but we could look to do it with OpenTelemetry when that's added to Quarkus

**Comment by kenfinnigan** [comment]
I changed the title to refer to OpenTelemetry, as that's the tracing approach we'd implement this idea with

**Comment by jtama** [comment]
Is it possible to help on this ? 

For reference [Log and Event Record Definition](https://github.com/quarkusio/quarkus/projects/20)

**Comment by brunobat** [comment]
@knutwannheden will close this issue because we plan to have support for OpenTelemetry Logging: https://github.com/quarkusio/quarkus/issues/30712
