### ISSUE TITLE
code.quarkus.io should search description

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#9918]
@maxandersen said on quarkus-dev ML https://groups.google.com/d/msg/quarkus-dev/uc3N_cQzG1g/C75JdHOvDwAJ

> Yes, code.quarkus uses description too

But when testing it does not seem to be the case:

1. Go to https://code.quarkus.io/
2. Search for `mqtt`

Actual: finds only `SmallRye Reactive Messaging - MQTT Connector`
Expected: should find also `Camel Paho` becuase it has MQTT in its description - check by searching for `paho` and see that `MQTT` occurs in its description.

Could we please get the expected behavior?

**Comment by ia3andy** [comment]
@ppalaga we could do that directly in the code quarkus extension processor to make that available for all extensions, would you provide a PR?

https://github.com/quarkusio/code.quarkus.io/blob/master/src/main/kotlin/io/quarkus/code/misc/QuarkusExtensionUtils.kt#L44

(If Kotlin is a problem, you could create a java class containing the code and just call it from there)..

**Comment by ppalaga** [comment]
Good idea! Let me try.
