### ISSUE TITLE
ReflectiveHierarchyStep warning for org.slf4j and javax.security.auth classes

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#9954]
ReflectiveHierarchyStep throws warning for org.slf4j and javax.security.auth classes, Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index

```
2020-06-11 16:28:37,597 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-22) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- javax.security.auth.Subject
	- javax.security.auth.login.AppConfigurationEntry
	- javax.security.auth.spi.LoginModule
	- org.slf4j.Logger
	- org.slf4j.spi.LocationAwareLogger
```

Reproducer:
```
wget -O code-with-quarkus.zip https://code.quarkus.io/api/download?s=ur3.9qf.FKK.UAO.WqB.7pM.QYr.tqK.vgg.Ll4
unzip -q code-with-quarkus.zip
mvn quarkus:dev -f code-with-quarkus/pom.xml
```

**Comment by gsmet** [comment]
This is due to: https://github.com/quarkusio/quarkus/blob/master/extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java#L148 .

Given it doesn't work as the type is not indexed, I wonder if a simple reflective class registration would be enough.

@cescoffier WDYT?

**Comment by cescoffier** [comment]
Registering the classes won't be enough, we would need to add them to the index somehow.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/10052 to fix it.

**Comment by NathanSchmid** [comment]
Is there a workaround for this in 1.5?

**Comment by gsmet** [comment]
No. 1.6.0.CR1 will contain the fix and should be released next week.
