### ISSUE TITLE
Quarkus "quarkus-smallrye-jwt" does not recognize x5t as alias to identify key-id working with JWKS

### ISSUE THREAD

**Issue by ahamed-k** [quarkusio/quarkus#9965]
Appreciate the way quarkus-smallrye-jwt works. We all know kid(in jwt token header) is used to identify the correspoding signature in JWKS to validate the token. However quarkus-smallrye-jwt does not seem to support x5t as an alias name or key-id - an alternate to kid(in header) while working with JWKS. There are identity servers like WSO2 - that supports JWKS with keys containing x5t - as alias name rather than kid. 

Expect the extension to support x5t - as alias name and alternate to kid to match the key from keys in JWKS to validate and verify the token like any other third-party libraries. Request you to provide support for the same.

As of now the current version of the extension does not support x5t - as alias name or key id in alternate to kid(as exists)

1. Provide JWKS resource URL that exposes JWKS keys/signatures with x5t to identify the headers in the public key location property - mp.jwt.verify.publickey.location - alternate to publicKey in .pem format
2. Build and run quarkus
3. Throws Invalid JWK signature.

```properties
mp.jwt.verify.publickey.location

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Java 1.8: 
 - Quarkus 1.2.1.Final and above 
 - Maven 3.6: 

**Additional context**
(Add any other context about the problem here.)

**Comment by sberyozkin** [comment]
`x5t` is a certificate thumbprint, what do you mean when you say it is an `alias` ?

**Comment by ahamed-k** [comment]
Yes. x5t is a thumbprint used as an identifier(alternate to kid) to identify the JWT token and the matching signature from JWKS. It seems Quarkus does not support x5t to be used as an identifier like other 3rd party libraries and would appreciate if you make Quarkus support x5t along with kid. Thanks.

**Comment by sberyozkin** [comment]
`x5t` is not an alternative to `kid`, it is a way to link to a certificate which can be used to verify a token.

If one has a JWK set with N+ JWKs, then, one would need to potentially iterate over each of the JWKs, check which one of them has an encoded `x5c` cert, calculate a thumbprint out of it and match with the token `x5t`. It would be expensive.

Question: do JWK keys in your JWK sets have both `x5t` and `x5c` ? Or only `x5t` ?

**Comment by sberyozkin** [comment]
I've opened https://github.com/smallrye/smallrye-jwt/issues/260.
IMHO it is not correct just to assume `x5c` is an alternative to `kid`, both properties serve different purposes, overloading `x5t` as `kid` without the use of `x5c` is unlikely to be supported. But lets start with supporting `x5c`, if a JWK key has `x5c` then it will work even without `kid` if a JWK set has a single JWK key

**Comment by ahamed-k** [comment]
Yes. JWKS has both x5c and x5t. And would appreciate if you add support for x5t. Please add this feature to support x5t too alternate to kid in case of JWKS

**Comment by sberyozkin** [comment]
@ahamed-k will be possible update the upgrade to smallrye-jwt 2.3.0
