### ISSUE TITLE
Quarkus cant be launched with Main-Class anymore

### ISSUE THREAD

**Issue by fluoxa** [quarkusio/quarkus#9974]
**Describe the bug**
I'm using IntelliJIdea and i cant directly start my Quarkus Mainclass anymore in my IDE. I dont like the maven dev-mode to much and i like to debug my application directly. This worked without problems in Quarkus 1.4.1.Final

Quarkus-Version: 1.5.1.Final
Java: jdk11.0.6_10
IntelliJ: 2020.1.2

**Expected behavior**
Application should start normally

**Actual behavior**
Application terminates with NullPointerException

Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:53)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:93)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:79)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at de.hup.one.portal.content.quarkus.container.ContentQuarkusApplication.main(ContentQuarkusApplication.java:11)
Caused by: java.lang.NullPointerException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:30)
	... 4 more

**Comment by jaikiran** [comment]
I just gave this a try locally with 11.0.1 (and Java 8) and it worked fine in both cases. Can you tell us a bit more about your IDE modules etc? What I mean is where exactly is the `de.hup.one.portal.content.quarkus.container.ContentQuarkusApplication` class located (are there multiple IDE modules)? Also can you edit your `ContentQuarkusApplication#main` to print the following:
```
System.out.println("TCCL is " + Thread.currentThread().getContextClassLoader().getName());
```
just before you call `Quarkus.run`?

**Comment by fluoxa** [comment]
Thanks for your fast reply,

It's a maven multi module project in the form of

root
-- module 1
-- module 2
-- module backend
---- module logic (Service Impls)
---- module persistence (Repos and Entities)
---- module model (DTOs and Business-Models)
---- module quarkus container (Quarkus Runnable)
------ deps: spring compatibility layers, quarkus deps and extensions, MainClass, logic, persistence 
------ and model
---- module spring boot container (Spring Boot Runnable)
-- module x

My MainClass

@QuarkusMain
public class ContentQuarkusApplication {

    public static void main(String... args) {
        System.out.println("TCCL is " + Thread.currentThread().getContextClassLoader().getName());
        Quarkus.run(QuarkusApplicationImpl.class, args);
    }

    public static class QuarkusApplicationImpl implements QuarkusApplication {

        @Override
        public int run(String... args) throws Exception {
            Quarkus.waitForExit();
            return 0;
        }
    }
}

Console-Output including your statement


Connected to the target VM, address: '127.0.0.1:58262', transport: 'socket'
TCCL is app
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:53)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:93)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:79)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at de.xxx.xxx.xxx.content.quarkus.container.ContentQuarkusApplication.main(ContentQuarkusApplication.java:12)
Caused by: java.lang.NullPointerException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:30)
	... 4 more
Disconnected from the target VM, address: '127.0.0.1:58262', transport: 'socket'

Process finished with exit code 1

Greetings and i hope this helps

**Comment by TranNgocKhoa** [comment]
Same problem here.
JDK: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)

**Comment by felixgborrego** [comment]
Same problem here too.
Also odd, 
the source code in `quarkus-ide-launcher-1.5.1.Final-sources.jar` contains  the expected `String classResource = callingClass.replace(".", "/") + ".class";` 
whereas  the decompiled version of the `.class` contains:
```
 String classResource = callingClass.replace("io.quarkus.launcher.shaded..", "io/quarkus/launcher/shaded//") + "io.quarkus.launcher.shaded..class";
```

**Comment by jaikiran** [comment]
It's looking like Maven shade plugin is causing some issue while the bytecode of these classes is being "remapped" (even though this class has been excluded from the Maven shade plugin)? I haven't yet been able to reproduce this. I'll see if I can find a way to reproduce this somehow.

**Comment by TranNgocKhoa** [comment]
> It's looking like Maven shade plugin is causing some issue while the bytecode of these classes is being "remapped" (even though this class has been excluded from the Maven shade plugin)?

It happened with Gradle too. I'm using Gradle + IntelliJ

**Comment by gsmet** [comment]
@jaikiran my understanding is that the exclusions defines the packages files that will be transformed to the new pattern, not if the file will be filtered or not. I haven't found a way to exclude files from the filtering. As soon as the file is included, it looks like it will be filtered.

In the launcher file, there are 2 issues IMHO:
- the string replacement for the resource: this is mostly due to the fact that we use an empty pattern. Dots and slashes are being replaced. We can work around it with some hacks in `QuarkusLauncher` but... I'm pretty sure it will break other things as we have a lot of `.` -> `/` replacements in the code. One option would be to use patterns for each TLDs instead it being empty. Still a hack but might work.
- even if we fix that we also have the deployment class being replaced, this is easily fixable with an exclusion.

I have no plans to work on this myself but I thought it might be worth logging my thoughts here.

/cc @aloubyansky

**Comment by gsmet** [comment]
It's not tested but I ended up with something like: https://github.com/quarkusio/quarkus/pull/10012

Note that excluding the service files looks like something we don't want to do but I might miss something.

**Comment by hosseinmp76** [comment]
same problem with eclipse and Gradle

**Comment by gsmet** [comment]
Could one of you try if https://github.com/quarkusio/quarkus/issues/9974 improves the situation or not?

Thanks!

**Comment by hosseinmp76** [comment]
> Could one of you try if #9974 improves the situation or not?
> 
> Thanks!

isn't #9974 this issue? did you mean #10067?

**Comment by TranNgocKhoa** [comment]
> > Could one of you try if #9974 improves the situation or not?
> > Thanks!
> 
> isn't #9974 this issue? did you mean #10067?

I think he means [#10012](https://github.com/quarkusio/quarkus/pull/10012)

**Comment by aloubyansky** [comment]
@gsmet did mean #10012 but #10067 is the one we are going to merge.
