### ISSUE TITLE
External library's application properties completely overridden

### ISSUE THREAD

**Issue by fabiomrch** [quarkusio/quarkus#9992]
I developed a utils library that has its own properties (rest client paths included). I placed the application.properties file in config folder in order not to come across resources override problem while building main project that imports that library.
The project that imports the utils library and injects its classes through Jandex indexing.

The expected beavior would be having separated properties files and not forcing each project that uses a common library to override the same properties.

Actually the project that imports the utils library has to override the library's application properties because I cannot find a way to maintain a reference to them (even if I place application.properties inside build tool’s output directory) and avoid errors concerning missing values for those properties.

**Comment by famod** [comment]
Possible Workaround: You could use a different name and implement a `ConfigSourceProvider` that provides that file.

**Comment by radcortez** [comment]
It is possible. Just place `application.properties` in `src/main/resources` in the lib module. Quarkus applications load all `application.properties` from dependencies available in the classpath.
