### ISSUE TITLE
datasource problem in document

### ISSUE THREAD

**Issue by hubinix** [quarkusio/quarkus#9996]
**Describe the bug**
(Describe the problem clearly and concisely.)
https://quarkus.io/guides/datasource
in this page,JDBC Configuration Reference chapter
i set quarkus.datasource.jdbc.transaction-isolation-level, but it doesn't work.
the TransactionIsolation is UNDEFINED.
I removed the ".jdbc.“ it works.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
quarkus.datasource.jdbc.transaction-isolation-level=repeatable-read,

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
quarkus.datasource.transaction-isolation-level=repeatable-read,

 
**Configuration**
```properties
# Add your application.properties here, if applicable.

```
And I think the agroalDatascource doesn't have default TransactionIsolation,
so if I don't put configuration (that is quarkus.datasource.transaction-isolation-level=repeatable-read, )  in application.properties. 
I wrote code like this

            connection = dataSource.getConnection();
           
            connection.setAutoCommit(true);
      
            connection.setTransactionIsolation(Connection.TRANSACTION_REPEATABLE_READ);

   and there is an SQLException will be thrown,when this connection.close is called.That is the resetConnection() failed.  
        try {
                    connection.close();
                } catch (SQLException e) {
                    log.error("errorOccurred: {}", e.getMessage());
                } finally {
                    connection = null;//
                }

**Comment by gsmet** [comment]
Could you paste all the datasource related properties of your `application.properties`? (just make the user and password blank)

Thanks.

**Comment by hubinix** [comment]
> Could you paste all the datasource related properties of your `application.properties`? (just make the user and password blank)
> 
> Thanks.


quarkus.datasource.url=jdbc:mysql://localhost:3306/promo
quarkus.datasource.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.username=aaaaaa
quarkus.datasource.password=12121
quarkus.datasource.min-size=3
quarkus.datasource.max-size=13
quarkus.datasource.transaction-isolation-level=repeatable-read

**Comment by gsmet** [comment]
Yeah, so your issue is that you were trying to mix old style configuration and new style configuration.

Either use what you have (which is deprecated) or use:
```
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=aaaaaa
quarkus.datasource.password=12121
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/promo
quarkus.datasource.jdbc.min-size=3
quarkus.datasource.jdbc.max-size=13
quarkus.datasource.jdbc.transaction-isolation-level=repeatable-read
```

**Comment by hubinix** [comment]
> Yeah, so your issue is that you were trying to mix old style configuration and new style configuration.
> 
> Either use what you have (which is deprecated) or use:
> 
> ```
> quarkus.datasource.db-kind=mysql
> quarkus.datasource.username=aaaaaa
> quarkus.datasource.password=12121
> quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/promo
> quarkus.datasource.jdbc.min-size=3
> quarkus.datasource.jdbc.max-size=13
> quarkus.datasource.jdbc.transaction-isolation-level=repeatable-read
> ```

Ok,I got it，thanks!

**Comment by YusufIsah** [comment]
thanks guys.
