### ISSUE TITLE
io.smallrye.jwt.build.impl.JwtProviderImpl must be registered for reflection

### ISSUE THREAD

**Issue by teoincontatto** [quarkusio/quarkus#9999]
`io.smallrye.jwt.build.impl.JwtProviderImpl` (i.e. its no-args constructor) must be registered for reflection to be usable in native images:

`Caused by: io.smallrye.jwt.build.JwtException: JwtProvider io.smallrye.jwt.build.impl.JwtProviderImpl could not be instantiated: java.lang.InstantiationException: Type `io.smallrye.jwt.build.impl.JwtProviderImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
`

As a workaround, add an entry in reflection config file.

See https://github.com/quarkusio/quarkus/issues/5341#issuecomment-575916971_

**Comment by gsmet** [comment]
@sberyozkin could you have a look at that one?

**Comment by sberyozkin** [comment]
@teoincontatto Hi, It has been fixes in `1.4.0.Final`, what version do you use ?

**Comment by gsmet** [comment]
It's 1.2.1.Final AFAICS: https://github.com/ongres/stackgres/blob/development/stackgres-k8s/src/pom.xml#L59 .

Let's close this one then.
